### ISSUE TITLE
/stock/$symbol/quote doesn't document some fields

### ISSUE THREAD

**Issue by eigood** [iexg/IEX-API#10]
* ytdChange
* latest* fields
* sector

**Comment by joshuablackburn-iex** [comment]
There are a number of updates to the API that need documentation updates, and will be updated this week.

**Comment by eigood** [comment]
For the fields listed, it's not too hard to figure out, of course.

So far, in the 30 minutes I've known about you guys, I like what I see.

**Comment by joshuablackburn-iex** [comment]
Documentation has been updated.
