### ISSUE TITLE
After market price...

### ISSUE THREAD

**Issue by Harmonium** [iexg/IEX-API#100]
I was wondering where I can find datas for aftermarket hours? I need the price for a symbol after market hours. Is it possible?

Thanks

**Comment by joshuablackburn-iex** [comment]
In the stock quote endpoint, delayedPrice and iexRealtimePrice will continue to update until 5pm EST.  Each price has an associated timestamp to indicate when it was last updated.

**Comment by Harmonium** [comment]
And what about Pre-Market?

Normally, after hours goes until 20h00.

Thanks

**Comment by Harmonium** [comment]
In Pre market and after hours, which informations will continue to update? 

delayedPrice and iexRealtimePrice?

Thanks
