### ISSUE TITLE
Dividends for symbols outside the US and how to call them?

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#1002]
Hi

What is the symbol's format to get data from outside the US? Lately you added several new stock exchanges but I couldn't find the symbol's format for those.

Also, is there a dividend history for symbols outside the US or only US symbols (not all) are supported?

Thanks

**Comment by evancarter-iex** [comment]
https://cloud.iexapis.com/stable/ref-data/exchanges has the list of exchanges/suffixes. We do not currently support dividend data from overseas exchanges.
