### ISSUE TITLE
JSON returned instead of number

### ISSUE THREAD

**Issue by SLguy** [iexg/IEX-API#1004]
When running https://cloud.iexapis.com/stable/stock/@Ticker/quote/latestPrice for tickers IMMY and SIR the data returned is in JSON format whereas expected format is number.

**Comment by McQgit** [comment]
@SLguy Those tickers don't trade anymore and are not supported by IEX.  To find the list of supported symbols, try: /stable/ref-data/symbols?token=(redacted)
[]https://iexcloud.io/docs/api/#symbols

If you just want a more graceful response to unsupported tickers, it would be helpful if you just said that.

**Comment by SLguy** [comment]
@McQgit If I realised they had ceased trading then perhaps I would have requested a more graceful response...perhaps exercising some grace yourself would be a good idea instead of being so curt to other users!

**Comment by McQgit** [comment]
@SLguy  It was hard for me to know what you did and didn't know from your brief submission.  I thought I was being helpful by both showing you how to determine supported tickers and to re-frame your trouble report in case that wasn't it.  Perhaps you could thank people, at least a little, who choose to help you than criticize their writing style.

**Comment by evancarter-iex** [comment]
@SLguy We do recommend checking the refdata since its updated daily with new information every day. Couple of older stuff stuck around from our cleanup script, ill look into why thats happening.
