### ISSUE TITLE
chartLast returns only a small number of prices

### ISSUE THREAD

**Issue by lohisoftware** [iexg/IEX-API#1006]
**Clearly describe the problem**

When I made following request on 6/2/2019, where chartLast=250, it returned only 22 prices. It seems like it returns only one calendar month worth of prices.

https://cloud.iexapis.com/v1/stock/aapl/chart?chartLast=250&filter=date,open,high,low,close,volume&token=<token>

I would expect that this API returns as many prices as I request in chartLast parameter (in this case, 250 prices).

**What time did the problem occur? (with timezone)**

6/2/2019 11AM PST

**What is the expected behavior?**

Expected behavior is that the API returns as many prices as chartLast=N parameter specifies.

**Your environment (e.g. browser, OS, API version, language):**

Browser/CURL.

**API URL (if applicable)**

https://cloud.iexapis.com/v1/stock/aapl/chart?chartLast=250&filter=date,open,high,low,close,volume&token=<token>

**What are the steps to reproduce the bug?**

Please make the request and observe the result.

**Additional context**

If I cannot rely that chartLast returns expected number of prices, I have to add more logic to my code, i.e. if I need more than "about 20" prices, then use chart/3m, else use chartLast. It makes my code more complicated and prone to bugs.

Could you please change how chartLast works. Thanks.

**Comment by lohisoftware** [comment]
Sorry, I realized that this API uses 1m as default, and chartLast refers to 1m. If I change the URL to chart/3m/chartLast=N, I get more prices.

You can close the issue. However, please update the documentation! It says that chartLast returns the latest N prices. Thanks.

**Comment by SeamusBoyle** [comment]
@lohisoftware You're missing the `range` path parameter, try this instead:

https://cloud.iexapis.com/v1/stock/aapl/chart/max?chartLast=250&filter=date,open,high,low,close,volume&token=

I just added `/max` to the path

**Comment by evancarter-iex** [comment]
@lohisoftware I updated the docs to make it more clear. Next time documentation is deployed it will go out. Thanks.
