### ISSUE TITLE
[Issue] All news urls return 403 forbidden

### ISSUE THREAD

**Issue by hengchu** [iexg/IEX-API#1008]
**Clearly describe the problem**
All news urls from the `api.iextrading.com` domain are returning 403 forbidden instead of redirecting to the news site. Example (https://api.iextrading.com/1.0/stock/aapl/article/7551742606036347)

**What time did the problem occur? (with timezone)**
From what I can tell, around 5/31 2019 New_York/USA

**What is the expected behavior?**
These urls should redirect to the original source of the news.

**Your environment (e.g. browser, OS, API version, language):**
Chrome 74.0.3729.169, OS X 10.12.6, API 1.0, HTTP JSON requests

**API URL (if applicable)**
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl&types=news

And then follow any entry's url field.

**What are the steps to reproduce the bug?**
Go to `https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl&types=news`, and copy any of the url fields into your browser and hit enter.

**Additional context**

**Comment by joshuablackburn-iex** [comment]
The IEX API has completed the 1st phase sunset.  (https://iextrading.com/developer/)
Please use IEX Cloud (https://iexcloud.io) to continue receiving data.
