### ISSUE TITLE
[Data] Please include more TSX Stocks Namly Toronto Stock Exchange Symbol BTO.TO (BTO.TSX)

### ISSUE THREAD

**Issue by KevinQJai** [iexg/IEX-API#1009]
**Clearly describe the data problem**

**Data URL (The URL you used to access the data without your token):**

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
This is available here:

https://cloud.iexapis.com/stable/stock/BTO-CT/quote

Please check out the list of exchanges: 
https://cloud.iexapis.com/beta/ref-data/exchanges

**Comment by datarix** [comment]
Are the TSX symbols only for TSX-Venture?
