### ISSUE TITLE
Dividends and Stock Price and Return Adjustments

### ISSUE THREAD

**Issue by CoderTarek** [iexg/IEX-API#101]
## Summary
For stock price history is historical stock price to adjusted to include reinvestment of dividends?
Does return data assume reinvestment of dividends?

**Comment by jcape** [comment]
@CoderTarek Stock prices are the open-market prices of the stock, so whether dividend re-investment activities affect the price of the stock or not is a function of the market itself.

**Comment by CoderTarek** [comment]
Ok, thanks.  Is there any documentation about how stock "year5ChangePercent" is calculated?  I am wondering if this is off off open/close price and other relevant details.  Based on prior response am I correct that "year5ChangePercent" does not include the value of any dividends received as part of a return calculation?
