### ISSUE TITLE
[Issue] SSE news streaming issue

### ISSUE THREAD

**Issue by hengchu** [iexg/IEX-API#1012]
**Clearly describe the problem**
I used the endpoint https://cloud-sse.iexapis.com/stable/news-stream?nosnapshot=true&last=1&symbols=... to open roughly 160 connections and listened to news updates on roughly 8000 symbols. As soon as all connections are established, the messages used count in the usage console becomes a huge negative number. I had pay-as-you-go enabled as well, and the pay-as-you-go messages count also becomes negative.

**What time did the problem occur? (with timezone)**
6/3 2019 New_York/USA
But the problem persists now.

**What is the expected behavior?**
The console should report approximately the actual number of messages used. This is pretty concerning as I can't estimate the API costs given these negative numbers.

**Your environment (e.g. browser, OS, API version, language):**
I used Python3.7 with asyncio to establish all connections in a single process.

**API URL (if applicable)**
https://cloud-sse.iexapis.com/stable/news-stream?nosnapshot=true&last=1&symbols=... 

**What are the steps to reproduce the bug?**
First fetch a list of all symbols, and then use the API URL above to listen to all of the news updates. And then watch the usage page in the iexcloud console.

**Additional context**
Here's a screen shot of my usage console.

<img width="650" alt="iexcloudusage" src="https://user-images.githubusercontent.com/1427187/58899856-eaf63d80-86cb-11e9-9ba4-19398045ae8f.png">

**Comment by hengchu** [comment]
Pinging devs. Is this issue being investigated? Thanks!

**Comment by evancarter-iex** [comment]
@hengchu we are working on this

**Comment by hengchu** [comment]
Just to catch up: I just ran the same test on sandbox servers, and they still result in large negative numbers. Let me know in case you need a small program to reproduce the issue.

**Comment by evancarter-iex** [comment]
@hengchu can you send the test case to support@iexcloud.io Ill take a look at it

**Comment by hengchu** [comment]
Sent. Thanks for following up.
