### ISSUE TITLE
Since today or yesterday, the crypto API method does not work anymore

### ISSUE THREAD

**Issue by reuniware** [iexg/IEX-API#1013]
Hi,
I've just opened an Android app that I have developed around your API and data are not updated from the following API method endpoint :

https://investors-exchange-iex-trading.p.rapidapi.com/stock/market/crypto

Also on the following URL the "crypto" method is not available anymore...

https://rapidapi.com/eec19846/api/investors-exchange-iex-trading?endpoint=apiendpoint_a6e1ce24-15fc-48d6-bc4a-78b7cd056614

The Android app on Google Play Store is at :

https://play.google.com/store/apps/details?id=com.reuniware.cryptoview

**Comment by joshuablackburn-iex** [comment]
The IEX API has completed the 1st phase sunset. (https://iextrading.com/developer/)
Please use IEX Cloud (https://iexcloud.io) to continue receiving data.

**Comment by reuniware** [comment]
So does that mean that I have to modifiy the source code of my Android app and to deploy it again on Google Play Store ?
