### ISSUE TITLE
Image not available to download from URLs returned by the logo endpoint

### ISSUE THREAD

**Issue by achenft** [iexg/IEX-API#1014]
6/4/2019  the GET /stock/{symbol}/logo endpoint returned URLs to download the logo, but no logo file was actually available at the URLs.  For example:

https://storage.googleapis.com/iex/api/logos/TMUS.png
https://storage.googleapis.com/iex/api/logos/DIS.png
https://storage.googleapis.com/iex/api/logos/BA.png

Also, can you advise on the coverage of the logo availability in terms of how many/which exchange-listed companies or how many percent of publicly trades companies are covered?

Thanks.

**Comment by kotarofujita** [comment]
There are a lot of these that use to work but no longer do.

**Comment by achenft** [comment]
Thanks.  Any idea if they plan on completing the coverage?

**Comment by evancarter-iex** [comment]
We are looking into this, but getting additional data in this realm isnt as easy as it looks unfortunately.

**Comment by evancarter-iex** [comment]
This should be fixed now.
