### ISSUE TITLE
[Issue] I got an error when calling the dividend history API

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#1016]
Hi

For one of my calls to the dividend history API, I got the following error:
Remote host terminated the handshake. The api was: https://cloud.iexapis.com/beta/stock/vea/dividends/5y?token=

It looks like a temporary thing but maybe you can check your side on what can cause this.

**Comment by Amosss** [comment]
Just got it again with NFLX

**Comment by evancarter-iex** [comment]
@Amosss This shouldnt happen that often but if it does we are usually aware and working to resolve. Closing for now.

**Comment by Amosss** [comment]
I just got several "An unknown error has occurred" errors when calling div history.
