### ISSUE TITLE
How to get realtime crypto data list with new API ?

### ISSUE THREAD

**Issue by reuniware** [iexg/IEX-API#1017]
I have developed on the old API.

I would like to port the app on the new API.

I used to call the following method for getting cryptocurrencies realtime quotes : 
https://investors-exchange-iex-trading.p.rapidapi.com/stock/market/

Now I would like to have the same results (if possible, or nearest) and the only method that I have identified on the new cloud API is this one : 
https://cloud.iexapis.com/v1/crypto/BTCUSDT/quote/?token=pk_6ed42be3b1d44cb78e5cxxxxxxxxxxxx

Is there a method to get the list of each cryptocurrency name (BTCUSDT...) ? Then, for each, I would call the method above, but I have not idenfitifed how to get the list of each cryptocurrency name (I can get the list of Stocks but not cryptocurrencies names).

Thanks !

**Comment by evancarter-iex** [comment]
@reuniware Sorry for the delay. We are updating the documentation but the symbol pairs supported currently are:
BTCUSDT
EOSUSDT
ETHUSDT
BNBUSDT
ONTUSDT
BCCUSDT
ADAUSDT
XRPUSDT
TUSDUSDT
TRXUSDT
LTCUSDT
ETCUSDT
IOTAUSDT
ICXUSDT
NEOUSDT
VENUSDT
XLMUSDT
QTUMUSDT

**Comment by reuniware** [comment]
Ok, thank you. I will review parts of my Android app to use the cloud API and the symbol pairs you listed.
