### ISSUE TITLE
[Data] Historical Prices not updated at 4AM ET

### ISSUE THREAD

**Issue by lohisoftware** [iexg/IEX-API#1019]
**Clearly describe the data problem**

Historical Prices API documentation says: "Data SchedulePrior trading day available after 4am ET Tue-Sat"

However, previous day (in this case, 6/7) price of AAPL was updated 6/8/2019 sometime between 5AM and 6AM. The price was not available at 4AM.

Could you please update the documentation about when previous day price of all stocks is available?

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/v1/stock/aapl/chart/max?chartLast=1

**What time did the problem occur (including timezone)?**

6/8/2019 4AM ET

**What is the expected behavior?**

Prior day price of all stocks is available at 4AM ET, as specified in the API documentation.

**What are the steps to reproduce**

Please call below URL at 4AM Tue-Sat

https://cloud.iexapis.com/v1/stock/aapl/chart/max?chartLast=1

**Comment by evancarter-iex** [comment]
@lohisoftware Unfortunately, we dont know exactly when it will come in, hence the "after 4am eastern". I will say that we are working hard on moving it up to around midnight, if not earlier, but not sure on the timetable on that.

**Comment by lohisoftware** [comment]
@evancarter-iex Thanks!
