### ISSUE TITLE
[Issue] chartLast=0 returns all prices

### ISSUE THREAD

**Issue by lohisoftware** [iexg/IEX-API#1020]
**Clearly describe the problem**

If chartLast parameter is 0, historical prices API returns all prices. In the case of AAPL, that is since 2003.

**What time did the problem occur? (with timezone)**

6/8/2019 12PM ET

**What is the expected behavior?**

In my opinion, it should return 0 prices (an empty array).

**API URL (if applicable)**

https://sandbox.iexapis.com/v1/stock/AAPL/chart/max?chartLast=0

**Additional context**

Why this would be nice to fix: if I had a bug in my code where I accidentally call historical prices API with /max?chartLast=0, it will consume some of the valuable monthly quota.

**Comment by evancarter-iex** [comment]
@lohisoftware Thanks. I think we fail "open" so to speak for a reason but Ill have to go back and check why that is.
