### ISSUE TITLE
[Data] '' day30changepercent '' and '' mouth1Changepercent'' incorrect 

### ISSUE THREAD

**Issue by alexeevaa7** [iexg/IEX-API#1021]
**Clearly describe the data problem**
For example:
ticker = REG
two variables: '' day30changepercent '' = - 0.00148 and '' mouth1Changepercent'' =0.033548 

My calculations with google finance:  2.26%

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/REG/stats?token=MYTOKEN

**What time did the problem occur (including timezone)?**
10/06/2019 22 00 MSK

**What is the expected behavior?**
Must return number 2.26%

**What are the steps to reproduce**
open https://cloud.iexapis.com/stable/stock/REG/stats?token=MYTOKEN

**Your environment (e.g. browser, OS, API version, language):**
google chrome

**Additional context**
How do you consider the price change% in 30 days? What is such a big difference with Google Finance?
 My calculation with google finance on this day: (current price - price 30 calendar days ago) / price 30 calendar days ago = day30changepercent (ticker is REG)

**Comment by evancarter-iex** [comment]
This is fixed.
