### ISSUE TITLE
[Data] Percent % displays 0 after midnight and before market open

### ISSUE THREAD

**Issue by SongoMen** [iexg/IEX-API#1022]
**Clearly describe the data problem**
Few days earlier i started using your api and everything was fine but today, every change percentage display's as 0

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/AAPL/quote?displayPercent=true

**What time did the problem occur (including timezone)?**
14:18 GMT +2

**What is the expected behavior?**
It should display valid percentages.

**Your environment (e.g. browser, OS, API version, language):**
Browser: Chrome, Framework: React, Language: JavaScript

**Comment by evancarter-iex** [comment]
@SongoMen Thanks, it's something we are aware of and will be cleaning up to make it display the % after midnight ET and before the market opens.
