### ISSUE TITLE
Batch request issue

### ISSUE THREAD

**Issue by ctalbott11** [iexg/IEX-API#1023]
Hi, I have been using the iexcloud api for stock requests for a personal app I made for myself. Everything has been working fine, but now the batch requests are not working.  I am parsing JSON in android,fyi.  

The URL I have been using and until recently worked is:  
https://cloud.iexapis.com/beta/stock/market/batch?types=quote&symbols=bac,c?token=pk_54c562eedb9f4a479238c4c78a72daf7

I have tried changing beta to stable and v1, and nothing works.  

Sometimes I get an error saying "types" entry is not valid, but all I have in types is "quote", 
and other times I'm getting an error saying an API key was not provided even though my API key is included.  I tried generating a new API key, and it doesn't work either.

Please help me with this issue, I don't feel like finding another api to use and implement. 

Thank you 

Colin Talbott

**Comment by schardtbc** [comment]
In the example given you would need to use & token=pk.... instead of ?token=pk...

Bruce C. Schardt

**Comment by ctalbott11** [comment]
It works, thank you for responding, I knew it was something simple

**Comment by evancarter-iex** [comment]
@ctalbott11 Make sure you rotate that public key you posted. This is a public issue tracker so anyone could use that public key.
