### ISSUE TITLE
[Request] Increase SSE endpoints symbol limit from 50 to 500

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#1024]
**Is your feature request related to a problem? Please describe.**

According to documentation, 

> SSE endpoints are limited to 50 symbols per connection. You can make multiple connections if you need to consume more than 50 symbols. 

Hence, at client side (Android app), the more symbols we need to handle, the more "SSE objects" we need to create. At certain cases which client creates a huge amount of symbols, the huge amount of "SSE objects" will cause out of memory.

**Describe the solution you'd like**
Is it possible to increase the symbol limit to 500, so that this can reduce the required "SSE objects" at client side?

**Describe alternatives you've considered**

**Additional context**

**Comment by timpaine-iex** [comment]
Closing as stale and won't fix.
