### ISSUE TITLE
Disagreement on volume between IEX cloud and google finance [Data]

### ISSUE THREAD

**Issue by cosmo86** [iexg/IEX-API#1025]
**Clearly describe the data problem**
AAPL volume data spike around 3:10 pm on June 11 2019, but this spike is not found on other platform such as Tradingview.

**Data URL (The URL you used to access the data without your token):**
url='https://cloud.iexapis.com/stable/stock/aapl/quote?token=token
**What time did the problem occur (including timezone)?**

June 11 2019 around 3:10 pm
**What is the expected behavior?**
there is a huge increase in volume, it should not do that?

**What are the steps to reproduce**
Get the AAPL volume, with 5 seconds resolution, and then plot it you will see.

**Your environment (e.g. browser, OS, API version, language):**
Browser: google chrome
OS: windows 10
API:  IEX cloud
Language: python

**Additional context**

**Comment by joshuablackburn-iex** [comment]
It would be helpful if you can paste in the volume you saw from each source.

**Comment by cosmo86** [comment]
how do you post pics on on the comment? i am new to github

**Comment by joshuablackburn-iex** [comment]
You can drag and drop them into the comment text box.
