### ISSUE TITLE
volume of stock decrease[Data]

### ISSUE THREAD

**Issue by cosmo86** [iexg/IEX-API#1027]
**Clearly describe the data problem**
the 'LatestVolume' of a stock when you call API returns the accumulative volume of that stock, therefore, this 'latestVolume ' should always increase. right? there is no such thing as negative volume in stock marker(not to confuse with negative volume index)

**Data URL (The URL you used to access the data without your token):**
url='https://cloud.iexapis.com/stable/stock/aapl/quote?token=

**What time did the problem occur (including timezone)?**
New york time June 12 2019

**What is the expected behavior?**
'Latest volume ' decrease at some time points

**What are the steps to reproduce**
Call API and plot the 'latest volume'. there are some points where the volume decrease

**Your environment (e.g. browser, OS, API version, language):**
chrome
windows 10
python

**Additional context**

**Comment by joshuablackburn-iex** [comment]
What values did you actually see?

**Comment by cosmo86** [comment]
out of 4405 data points, there are about 30(i didnt count) of them that actually decrease( the time interval is 5 seconds) ovet time.
here is the volume data
first column is the volume when t=x and the second column is when t=x+5s
3116369.0 3099786.0
4358995.0 4343065.0
5664479.0 5657828.0
7253545.0 7244754.0
10642709.0 10639911.0
11430898.0 11414871.0
12118950.0 12114329.0
12635285.0 12633832.0
13562322.0 13543083.0
14696576.0 14695140.0
14721909.0 14720447.0
15286661.0 15275054.0
15733344.0 15727515.0
16061488.0 16056813.0
16072786.0 16069117.0
16415301.0 16408421.0
16424012.0 16419890.0
16419890.0 16415301.0
16905465.0 16903478.0
17448899.0 17444077.0
17852444.0 17842025.0
18325731.0 18324379.0
18847260.0 18842695.0
20139097.0 20131023.0
20152536.0 20145566.0
21724821.0 21696464.0

**Comment by joshuablackburn-iex** [comment]
This may be due to our massively parallel data processing, where our output is an unordered stream. We do provide a timestamp on the message, but we will implement some code to minimize these types of events.
