### ISSUE TITLE
Rules engine, alpha

### ISSUE THREAD

**Issue by kalevigit** [iexg/IEX-API#1028]
In your pricing page https://iexcloud.io/pricing/ 
I can see that my plan has 2 rules.

but in the console, I get: 
Rules Engine is currently an Alpha Product only available for Scale users. Upgrade your account to unlock access to Alpha Products. Once Rules Engine advances to beta, Launch users will be given access.Upgrade now.

what does that mean?

**Comment by evancarter-iex** [comment]
This is resolved.
