### ISSUE TITLE
After hours and pre market...

### ISSUE THREAD

**Issue by Harmonium** [iexg/IEX-API#103]
I just want to be sure to get the datas I need at the right place as seen on the image I added.

For the After hours and Pre market, I need the price and change in currency and percentage in realtime and the close price, close change in percentage and currency.

Can I get all these datas?

Thanks for your help!

![after hours](https://user-images.githubusercontent.com/4366227/33132354-7e218786-cf67-11e7-8e55-803c7d99d88b.png)

**Comment by jcape** [comment]
@Harmonium We do not provide any currency data at this time, though there is an open request for it in issue #91. The rest of this request can be calculated using the data already provided during the IEX pre/post market sessions, which is 08:00 US ET to 09:30 US ET and 16:00 US ET to 17:00 US ET, respectively. This information is available on the STOCKS API, which is documented at https://iextrading.com/developer/docs/#stocks

Note: Different markets may different pre/post-market session hours (starting as early as 04:00 US ET, for example, and running as late as 20:00 US ET), but we're currently only covering IEX hours for pre-post prices.

**Comment by MasterJames** [comment]
Doesn't the Forex ultimately drive everything else? It seems it's a pretty important indicator for any automated or not system especially ANN and DNN regardless of actually trading those symbols.

A lack of this information seems pretty unfortunate for my interest level in IEX. I would like to be notified when Forex data is available [without writing a daily cron job on https://api.iextrading.com/1.0/ref-data/symbols] and then maybe it's not too late for my interest in IEX to see a return. If only I could Short my intellectual interest too.

Seriously though it would be good to get some feedback on an action plan for this or an explanation why that's not going to happen anytime soon.
