### ISSUE TITLE
[Data] Is the chart/dynamic endpoint working correctly?

### ISSUE THREAD

**Issue by bmwelu** [iexg/IEX-API#1032]
**Clearly describe the data problem**
I'm trying to use the new chart/dynamic endpoint as described in the API doc, but I continue to get 404 not found returned.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/tsla/chart/dynamic?token=XXXXXX

**What time did the problem occur (including timezone)?**
Always

**What is the expected behavior?**
Data returned

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
Postman

**Additional context**

**Comment by josephmaxim** [comment]
can confirm endpoint doesn't work

**Comment by kotarofujita** [comment]
consistent failure on sandbox as well:
https://sandbox.iexapis.com/stable/stock/AAPL/chart/dynamic?token=xxx

**Comment by evancarter-iex** [comment]
Sorry somehow this slipped through. We are looking into it.

**Comment by evancarter-iex** [comment]
This was fixed a while ago. Closing.
