### ISSUE TITLE
[Request] Name and Type for IEX Symbols

### ISSUE THREAD

**Issue by vslee** [iexg/IEX-API#1034]
The /ref-data/iex/symbols currently only provides **symbol**, **date**, and **isEnabled**. Could it also return **name** and **type**? I'd assume that IEX already has that info so you wouldn't need to pay a third party for that. Also, in V1, there was a **iexId** included in the response. Is that still a thing?

**Comment by McQgit** [comment]
@vslee Have you seen the `company` endpoint?  It only costs 1 unit and gives you what you ask for and more
[]https://iexcloud.io/docs/api/#company

Sorry, no ideas for iexId

**Comment by vslee** [comment]
Yes, thanks for pointing that out. The Company endpoint costing 1 unit per company makes it more expensive than the Symbols endpoint, which is 100 for all symbols. I just figured that since the IEX Symbols subset were ones that IEX had data on themselves, those extra fields could be included for free.

**Comment by joshuablackburn-iex** [comment]
This is already available on the normal ref data symbols endpoint.
https://iexcloud.io/docs/api/#symbols

Are you looking for something different?

**Comment by vslee** [comment]
No, the Symbols endpoint will be fine , thanks
