### ISSUE TITLE
Message used 

### ISSUE THREAD

**Issue by snoze** [iexg/IEX-API#1035]
Hi, I was testing new iex cloud and after downloading only SPY data, I have reached 500k messages.  I can't download anymore any data. Is there any problem?

![Screenshot from 2019-06-16 16-37-01](https://user-images.githubusercontent.com/51891024/59569867-51c51080-9055-11e9-9989-450b69bbaabe.png)

Anyhelp. Old API was working fine without any issue. But after using new cloud API with token all messages reached to 500K.

Thank you

**Comment by joshuablackburn-iex** [comment]
These should help:

https://intercom.help/iexcloud/articles/2851174-getting-started-with-iex-cloud
https://intercom.help/iexcloud/articles/2850919-what-is-a-message

**Comment by gnicolosi** [comment]
I have the exact same issue.  I was using the old IEX API just fine, but after updating the spreadsheets I use with students to the cloud API, on 7/1 I opened the spreadsheet for 2 minutes and 1/2 of my monthly message allotment was used.  I quickly closed the spreadsheet and emailed IEX support.  No word, but shortly after that on the same day despite having nothing open the remaining messages were mysteriously used.  What is going on?
