### ISSUE TITLE
[Data] PreviosClose data not streaming

### ISSUE THREAD

**Issue by etnatrader** [iexg/IEX-API#1036]
**Clearly describe the data problem**
Connect to https://api.iextrading.com/1.0/stock/market/previous
Forbidden
**Data URL (The URL you used to access the data without your token):**
https://api.iextrading.com/1.0/stock/market/previous

**What time did the problem occur (including timezone)?**
The problem already existed at 06/17/2019 09:00 ET

**What is the expected behavior?**
Endpoint available and providing close values
https://api.iextrading.com/1.0/stock/market/previous

**What are the steps to reproduce**
Connect to https://api.iextrading.com/1.0/stock/market/previous
Forbidden

**Your environment (e.g. browser, OS, API version, language):**
1.0

**Additional context**

**Comment by joshuablackburn-iex** [comment]
The old API has sunset all third party data according to the schedule we posted on our developer page https://iextrading.com/developer/

This data is now on [IEX Cloud](https://iexcloud.io).
