### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by scriptedlogic** [iexg/IEX-API#1037]
**Clearly describe the data problem**
I migrated from the old system over the weekend; just a few hiccups that I was able to fix quickly.

This morning, I noticed that the (new) Canadian Stocks (e.g. RY-CT) only show the 'close of last business day' values

**Data URL (The URL you used to access the data without your token):**
This ...   
https://cloud.iexapis.com/stable/stock/market/quote?token=MY_TOKEN_HERE&filter=symbol,latestPrice,change,changePercent&symbols=msft,ry-ct
... only returns data for msft

This works ...
https://cloud.iexapis.com/stable/stock/MSFT/chart/1d?token=MY_TOKEN_HERE&filter=date,minute,close,changeOverTime&changeFromClose=true&chartInterval=1
... but this returns values as of 'close of previous business day' ...
https://cloud.iexapis.com/stable/stock/RY-CT/chart/1d?token=MY_TOKEN_HERE&filter=date,minute,close,changeOverTime&changeFromClose=true&chartInterval=1

Both these return expected data (i.e. up to 'close of previous business day') ...
https://cloud.iexapis.com/stable/stock/MSFT/chart/5d?token=MY_TOKEN_HERE&filter=date,minute,close,changeOverTime&changeFromClose=true&chartInterval=1
https://cloud.iexapis.com/stable/stock/RY-CT/chart/5d?token=MY_TOKEN_HERE&filter=date,minute,close,changeOverTime&changeFromClose=true&chartInterval=1
 
**What time did the problem occur (including timezone)?**
Today after US/Canadian markets opened.

**What is the expected behavior?**
Detailed above alongside the url's.

**What are the steps to reproduce**
Just use the same url's (with proper tokens).

**Your environment (e.g. browser, OS, API version, language):**
Windows 10, Chrome

**Additional context**

**Comment by joshuablackburn-iex** [comment]
International stocks are currently end of day prices.

**Comment by dfaust** [comment]
> International stocks are currently end of day prices.

@joshuablackburn-iex are there any plans to provide more frequent updates for international stock prices?
