### ISSUE TITLE
How to call the could iex api

### ISSUE THREAD

**Issue by pmillerhk** [iexg/IEX-API#1039]
I used to use the following call to access 1 minute data intraday from IEX:

https://api.iextrading.com/1.0/stock/aapl/chart/1d?chartInterval=1

I pulled it into a pandas dataframe for manipulation

I signed up for the new cloud program at the launch level ...

What is the new syntax to make the same API call?

**Comment by joshuablackburn-iex** [comment]
https://cloud.iexapis.com/stable/stock/aapl/chart/1d?chartInterval=1&token=YOUR_TOKEN
