### ISSUE TITLE
1d chart returns date field which it should not

### ISSUE THREAD

**Issue by somnath-nirakari** [iexg/IEX-API#104]
## Summary
Chart for 1d returns date as part of response.
As per documentation, this should not be returned as part of the 1d response.
**date | string | is not available on 1d chart.**

We can always ignore that field but it will be good if the response is consistent with the documentation. 

### Date/time of issue
Nov 22 2017

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/1d

### What you expected to happen
Response should not contain date field
Ex -
{
        "minute": "14:23",
        "label": "2:23 PM",
        "high": 174.315,
        "low": 174.29,
        "average": 174.304,
        "volume": 400,
        "notional": 69721.5,
        "numberOfTrades": 6,
        "changeOverTime": 0.005056882722990132
    },

### What actually happened
Response contained date field
{
        **"date": "20171122",**
        "minute": "14:23",
        "label": "2:23 PM",
        "high": 174.315,
        "low": 174.29,
        "average": 174.304,
        "volume": 400,
        "notional": 69721.5,
        "numberOfTrades": 6,
        "changeOverTime": 0.005056882722990132
    },

**Comment by jcape** [comment]
@somnath-nirakari Thanks for reporting this, I recommend just ignoring it for now, we'll be looking to update the docs, unless there's a deeper issue, so I recommend just ignoring it.
