### ISSUE TITLE
[Issue] Inconsistent behavior with lower case query parameters

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#1041]
**Clearly describe the problem**

The following request returns OK (e.g. Stock endpoints): 

https://sandbox.iexapis.com/stable/stock/aapl/quote?token=

However on other endpoints (such as Data APIs), upper case keys work:

https://sandbox.iexapis.com/stable/time-series/REPORTED_FINANCIALS/AAPL?token=Tsk_c11564dc30a611e9958142010a80043c

But lowercase do not:

https://sandbox.iexapis.com/stable/time-series/reported-financials/AAPL?token=Tsk_c11564dc30a611e9958142010a80043c

https://sandbox.iexapis.com/stable/time-series/REPORTED_FINANCIALS/aapl?token=Tsk_c11564dc30a611e9958142010a80043c

https://sandbox.iexapis.com/stable/time-series/reported-financials/aapl?token=Tsk_c11564dc30a611e9958142010a80043c

**What time did the problem occur? (with timezone)**

6/17/19 10PM EST

**What is the expected behavior?**

Consistent behavior for lowercase values

**Additional context**

Unsure of entirety of endpoints which are experiencing this issue, will update with more if found.

**Comment by timpaine-iex** [comment]
This is the correct behavior as time series ids are case sensitive whereas api paths are not.
