### ISSUE TITLE
[Data] TSX Symbols missing P/E ratio values in the key stats endpoint

### ISSUE THREAD

**Issue by gyfis** [iexg/IEX-API#1045]
The API is returning null P/E ratio values for TSX tickers in the key stats endpoint.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/beta/stock/TD-CT/stats
https://cloud.iexapis.com/beta/stock/CAE-CT/stats
...

**Comment by timpaine-iex** [comment]
this falls under "international fundamentals" http://iexcloud.io/console/roadmap
