### ISSUE TITLE
[Request] Add list-types to docs

### ISSUE THREAD

**Issue by markwheeler** [iexg/IEX-API#1047]
**Is your feature request related to a problem? Please describe.**
I couldn't find a clear definition for valid list-types at https://iexcloud.io/docs/api/#list
There are examples there but it isn't clear if these cover all the available options?

**Describe the solution you'd like**
Would be great to have list-type clearly defined.

**Comment by timpaine-iex** [comment]
closing, added to https://iexcloud.io/docs/api/#list
