### ISSUE TITLE
[Data] MarketCap Missing from all ADRs

### ISSUE THREAD

**Issue by exiao** [iexg/IEX-API#1049]
**Clearly describe the data problem**
marketCap is returning null for the quotes endpoint and the advanced stats endpoint.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/beta/stock/market/batch?types=quote&symbols=hmc&range=2y&token=****&last=4

**What time did the problem occur (including timezone)?**
June 20, 2019 12AM PST

**What is the expected behavior?**
MarketCap returns the real value

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by exiao** [comment]
Market cap is also missing for TCEHY

**Comment by evancarter-iex** [comment]
This is fixed.

**Comment by exiao** [comment]
Thank you :)
