### ISSUE TITLE
[Data] The requested data requires a Scale account and granted permission to access.

### ISSUE THREAD

**Issue by RuiFigueiredoAlgo** [iexg/IEX-API#1050]
I'm getting this output

"The requested data requires a Scale account and granted permission to access."

when using 
"https://cloud.iexapis.com/beta/stock/" & rs!Symbol & "/chart/1d?token=" & Token

I'm using only 17% of my messages

**Comment by McQgit** [comment]
@RuiFigueiredoAlgo  What was the symbol you were trying?  You will get the error you describe if using an OTC ticker as those require Scale account and permission from OTC market.  Here are the notes from the docs change log:

"2019-04-26
    Added EOD options data
    Added 15 minute delayed OTC data (Only available to Scale users with permission from OTC Markets)"

I can retrieve EOD OTC data w/out being Scale or special permission using the Quote and similar endpoints.  But, the url you are using asks for intraday pricing.
