### ISSUE TITLE
[Data] stock/market/previous In IEX API vs CloudIEX #828

### ISSUE THREAD

**Issue by RuiFigueiredoAlgo** [iexg/IEX-API#1051]
In IEX API stock/market/previous

https://api.iextrading.com/1.0/stock/market/previous

It will bring the closing prices for the previous session from all major Stocks Exchanges Nyse, Nasdaq, etc.

    The ancient API returns around 5.800 symbols

Now in IEX Cloud

https://cloud.iexapis.com/beta/stock/market/previous?token=my_token

It brings all stocks even from OTC, pinksheets, etc.

    In these new API it returns around 48.000 symbols !!!!

Can there be a compatibility option in order to get the same base symbols as the old IEX API
stock/market/previous

Examples:
https://cloud.iexapis.com/beta/stock/market/previous_compatibility?token=my_token
or
https://cloud.iexapis.com/beta/stock/market/previous?token=my_token&version=iexapi
or
https://cloud.iexapis.com/beta/stock/market/previous_old?token=my_token

Thanks for your attention.

Kind regards.

**Comment by evancarter-iex** [comment]
This is resolved.
