### ISSUE TITLE
[Data]previousClose not correct for mutual funds

### ISSUE THREAD

**Issue by kswier** [iexg/IEX-API#1053]
I don't think IexCloud is handling the previousClose field correctly for mutual funds. It is correct for stock prices but since mutual funds only update their prices at market close this field needs to be handled differently.   

At market close, IexCloud shows the closing price for the mutual fund and the previousClose field shows the price from the previous day.  When the market opens the next day, the previousClose field gets updated to show the closing price of the previous day.  So for the day, the previousClose price and the close price for mutual funds are the same.  Since the price of mutual funds only change at the end of the day, the previous close should always reflect the day before the last closing price.  

For example, on Wednesday a mutual fund has an end of day price of $75.50.  On Thursday the end of day price is $76.00.  On Friday when the market opens, the closing price should be $76 and the previous close should be $75.50.  Currently, the previous close and closing price is $76.

I believe the old API handled this correctly.

**Comment by evancarter-iex** [comment]
This should be fixed now.

**Comment by kswier** [comment]
It has been a while since I have used mutual fund quotes but it looks like this is an issue again.  On market open, the previous close price is getting updated to the closing price of the previous day.
