### ISSUE TITLE
StockTwits coding

### ISSUE THREAD

**Issue by 4samstrades** [iexg/IEX-API#1056]
Hi,

I'm new to IEX and wanted to know how I could create the below screenshot to send me alerts instantly. If anyone knows how I would really appreciate it. I tried e-mailing support but no one responded.

Sincerely,

Sam

<img width="506" alt="Screen Shot 2019-06-20 at 3 26 52 PM" src="https://user-images.githubusercontent.com/52054012/59885363-dd99ae00-936f-11e9-953a-e6d9113466a4.png">

**Comment by dmikester1** [comment]
You want alerts via email or SMS or what?
