### ISSUE TITLE
get_historical_data costs 2510 messages each time regardless the number of days

### ISSUE THREAD

**Issue by lujiantony** [iexg/IEX-API#1057]
Hi there,

I'm recently testing the latest version 0.4.1 but found the following bug. 

I'm running on MacOS 10.14.2. Python 3. 

When ever I use the following command to get daily historical data, it will eat 2510 message counts, no matter how long the period I choose.

I have tried the following, which start and end is basically the same day but iexcloud account still burned 2510 messages. 

start = datetime.date(2019,6,21)
end = datetime.date(2019,6,21)
output = get_historical_data('AAPL',start=start,output_format='pandas')

From what I have read in the iexcloud, each day is supposed to burn 10 messages. See below. 

Adjusted + Unadjusted
10 per symbol per time interval returned (Excluding 1d)
Example: If you query for AAPL 5 day, it will return 5 days of prices for AAPL for a total of 50.

Unless I'm not understanding correctly the phrase "Excluding 1d". But from the example provided, it seems that 5 days of AAPL daily price should cost me 50 messages not 2510 messages.

Could you please help look into the API see if there anything that underlying the get_historical_data that's causing this?

My public api key is the following: pk_e81a2c5955aa4846b5f5bba0bce5d613

Thank you.
Jian

**Comment by McQgit** [comment]
@lujiantony  Your complaint looks the same as one posted against the python extension iexfinance - which you are using.  See:
[]https://github.com/addisonlynch/iexfinance/pull/153

Note that extension is not provided by IEX.  It was developed independently.

**Comment by evancarter-iex** [comment]
@lujiantony 1) This looks like an issue with the pyIEX extension 2) Please rotate that public api key, its now compromised since its been posted in a public forum.
