### ISSUE TITLE
[Data] /ref-data/symbols is missing several stocks, mainly financials

### ISSUE THREAD

**Issue by dmikester1** [iexg/IEX-API#1058]
**Clearly describe the data problem**
For some reason there seem to be several stocks missing from the call to /ref-data/symbols that are mostly from the Financials sector.  Maybe there is a good reason IEX cannot get data on these stocks, but there seem to be several big name financial institutions in this list that I think they should be able to get.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/ref-data/symbols/?token=

**What time did the problem occur (including timezone)?**
June 21, 2019 10pm CST

**What is the expected behavior?**
Get many of these common stocks returned

**What are the steps to reproduce**
Make the above API call to get "an array of symbols that IEX Cloud supports for API calls".

**Your environment (e.g. browser, OS, API version, language):**
Firefox, Windows 10, Cloud, English

**Additional context**
Some of the missing stocks are here:
![Capture2](https://user-images.githubusercontent.com/8491610/59958834-787ab100-9472-11e9-98fd-f3d856d00fdf.PNG)

**Comment by joshuablackburn-iex** [comment]
These all look to be pink sheets. 
https://iexcloud.io/docs/api/#otc-symbols

Our symbols are split up at the moment, but we do plan to consolidate everything into one call.
