### ISSUE TITLE
Excel Webservice returns #VALUE! when using "... chart/1y"

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#106]
Hi. Working in Excel and found something which may be a bug.  I'll try again when the market is open, and will update the issue if results vary.

### What you expected to happen
  Return same type of array for 1y as 1m - just with more data  

### What actually happened
  **This works fine**: =WEBSERVICE("https://api.iextrading.com/1.0/stock/aapl/chart/1m").
    Same goes for 3m and 6m.

  **This fails**:            =WEBSERVICE("https://api.iextrading.com/1.0/stock/aapl/chart/1y")
    Same goes for 1d, ytd and 2y.

  I haven't tried .../date or .../dynamic

### Other Information (sample code, links, etc.)
  Please let me know if I can help

**Comment by ModelsRUs** [comment]
I just retested this (during market hours) and got the same result. Seems like a bug...

Thank you for your attention.

**Comment by ModelsRUs** [comment]
Update: =WEBSERVICE("https://api.iextrading.com/1.0/stock/AAPL/chart/date/2017115"). It returns a null set (i.e., "[]" ). Not what I was looking for, but unlike ..../2y, ../1y, and .../ytd, it does not return #VALUE!.

**Comment by joshuablackburn-iex** [comment]
You need to add ?format=csv to your call to return a CSV.

Additionally, your latest call is for 20171105 which is a Sunday and does not have data.  If you use 20171106 instead, you'll see data.

**Comment by ModelsRUs** [comment]
Sorry Josh, but I'm not understanding.
1) I tried =WEBSERVICE("https://api.iextrading.com/1.0/stock/aapl/chart/1y&format=csv") but the call still fails. How should this be amended?
Sorry, but I know I'm doing something wrong, and searched in the documentation, but found very little about CSV - can you please explain further?

2) Why would =WEBSERVICE("https://api.iextrading.com/1.0/stock/aapl/chart/1m") be fine, but =WEBSERVICE("https://api.iextrading.com/1.0/stock/aapl/chart/1y") fail? Is there a limit based upon amount of data to be retrieved?

3) I don't know about the "latest call", but many tests I ran WERE for valid business days (including today, Nov 27th), and .../1y still fails.

Thank you

**Comment by ModelsRUs** [comment]
Sorry Josh. Re point # 3 below, I know Chart will only retrieve 
historical data. I tried the function on many valid business days, 
though, and it always fails. If you can explain how to incorporate CSV 
format, I'll try that.

Thank you.
- *Paul*
   (917) 476-4468
===================================================================

**Comment by jcape** [comment]
@ModelsRUs You need ?format=csv, not &format=csv

**Comment by ModelsRUs** [comment]
thank you. that works

- *Paul*
   (917) 476-4468
===================================================================

**Comment by ModelsRUs** [comment]
Hi all.
Thank you again for your help, as well as making the API available.
Apologies, but I'm not very familiar with the syntax, so I have 3 
follow-up questions:

1. If know 
WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart*?filter=date,open,high,low,close*/1m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") will 
extract only specific endpoints. To pull all endpoints EXCEPT one - 
e.g., "label" - is there syntax like 
WEBSERVICE(".../chart?filter=*-**label*/1m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>"), or 
WEBSERVICE(".../chart?filter*<>label*/1m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>"), or must 
I specifically include all endpoints /except /those to be omitted? I 
tried both "-label" and "<>label" so I know they don't work.

2. I'm trying to pull specific endpoints from /chart (e.g., omitting 
"label").
    >  A period of (1m) works fine: 
WEBSERVICE(".../chart?filter=date,open,high,low,close/*1*m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>"),
    >  Other periods (3m, 6m, 1y, etc) seem to only return data for 1m, 
regardless of the parameter being entered. For example: 
WEBSERVICE("...chart?filter=date,open,high,low,close/*6*m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") only 
returns data for 1m.
    >  This (without specifying specific endpoints) 
WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart/*6*m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") also 
works fine.
What am I doing wrong?

3. Querying WEBSERVICE(".../chart/1m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") returns 
data /with /a line-feed "Chr(10)" character at the end of each line. I 
can strip it out using Excel's REPLACE function, so no problem, but 
WEBSERVICE(".../chart*?filter=date,open,high,low,close*/1m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") returns 
data /without /the line-feed character. Is this a switch I can control - 
i.e., to extract without Chr(10)?

Thanks again,
- *Paul*
   (917) 476-4468
===================================================================

**Comment by ModelsRUs** [comment]
Thank you Josh. I wasn't implying that your csv format is non-compliant, 
and will review RFC 4180 for further insight. Part of my problem is lack 
of experience as a developer outside of Excel.
I'm trying to work around the "label" issue I'm having (by excluding it 
from the query). To that end, when possible, I would very much 
appreciate it if you could please respond to the first 2 questions I've 
posed below.

Regards,
- *Paul*
   (917) 476-4468

===================================================================

The label field was designed as a convenience and specifically used in 
our own apps. If you don't find the format to be useful, the "date" 
field should provide sufficient information to calculate your own date 
string.

As for the CSV, commas in values are valid. Refer to RFC 4180 
<https://tools.ietf.org/html/rfc4180#page-2> section 2, sub-section 6 
"Fields containing line breaks (CRLF), double quotes, and commas should 
be enclosed in double-quotes." Any good CSV parsing library will handle 
this for you.

===================================================================

**Comment by ModelsRUs** [comment]
Hi Josh
I realize this issue is different from my original submission. If you 
prefer, I can submit it as a separate issue.

To summarize, the Stock endpoint with parameters > 1m, when used in 
conjunction with filters, seem to only return 1 month of data.

  * WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart*?filter=date,open,high,low,close*/1m?format=csv
    <https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") is fine
  * other periods, such as "6m":
    WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart*?filter=date,open,high,low,close*/6m?format=csv
    <https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") only
    return 1 month of data

Thank you
- Paul
------------------------------------
1. If know 
WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart*?filter=date,open,high,low,close*/1m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") will 
extract only specific data. Is there a syntax to pull all endpoints 
EXCEPT one - e.g., "label" - is there syntax like 
WEBSERVICE(".../chart?filter=*-**label*/1m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>"), or 
WEBSERVICE(".../chart?filter*<>label*/1m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>"), or must 
I specifically include all endpoints /except /those to be omitted? I 
tried both "-label" and "<>label" so I know they don't work.

2. I'm trying to pull specific endpoints from /chart (e.g., omitting 
"label").
    >  A period of (1m) works fine: 
WEBSERVICE(".../chart?filter=date,open,high,low,close/*1*m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>"),
    >  Other periods (3m, 6m, 1y, etc) seem to only return data for 1m, 
regardless of the parameter being entered. For example: 
WEBSERVICE("...chart?filter=date,open,high,low,close/*6*m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") only 
returns data for 1m.
    >  This (without specifying specific endpoints) 
WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart/*6*m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv>") also 
works fine.
What am I doing wrong?

Thank you,
- *Paul*
   (917) 476-4468
===================================================================

**Comment by jcape** [comment]
@ModelsRUs I answered your question on #114.
