### ISSUE TITLE
IEX Market Data - Last, what is the format for time

### ISSUE THREAD

**Issue by adharbert** [iexg/IEX-API#1060]
I have been looking around and not sure how to find out what exactly the format for the "time" parameter on the IEX Market Data Last.  Time is a long integer, but I don't see anything regarding what format is using.

"time": 1480446206461

I didn't want to create this but I don't see any documentation on the site for this.

**Comment by joshuablackburn-iex** [comment]
https://currentmillis.com/

Epoch time in milliseconds.
