### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by emarcier** [iexg/IEX-API#1062]
We are getting `Forbidden` for our URL requests, my guess is that you would have probably closed your API v1.0 and is no longer available or I might be wrong?  Can you please comment on this issue? 

`file_get_contents(https://api.iextrading.com/1.0/stock/market/batch?symbols=DBVT&types=quote,chart&range=1m&last=10): failed to open stream: HTTP request failed! HTTP/1.1 403`

Thanks a million for your time! 
Emma

**Comment by evancarter-iex** [comment]
@emarcier Yes. We had announced the sunset of the api.iextrading.com for June of this year, a while ago. We recommend moving over to https://iexcloud.io
