### ISSUE TITLE
[Data] LLOY not found dividends

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#1063]
request: https://cloud.iexapis.com/v1/stock/LLOY-LN/dividends/5y?token=TOKEN
response: []

but: https://www.lloydsbankinggroup.com/investors/shareholder-info/dividends/

**Comment by McQgit** [comment]
@xxx44yyy  If you use the US ADR symbol LYG you will see the dividends.  I think they only do EOD prices for non-US exchange symbols as noted in their change log.  But, evan is best to address that.  I think they should doc better what they provide for the foreign exchanges - FWIW.  As an aside, you'll find the financials don't work for LLOY-LN but do for LYG

**Comment by xxx44yyy** [comment]
:facepalm:

**Comment by evancarter-iex** [comment]
@xxx44yyy @McQgit is right we only have the rights to EOD prices of non US exchange symbols. We are working on getting more data but it takes a lot of time unfortunately (lots of legal agreements etc), for the moment use the LYG symbols.

**Comment by lars670** [comment]
Evan Carter when you write non US exchange symbols, are you aware of the European MIFID2 ruleset that basically dictates that all EU exchanges must set their data free after 15 minutes, free as in free with no IP and redistribution probihitions whatsoever?
Of course the exchanges doesn´t like this new set of laws/rules

**Comment by evancarter-iex** [comment]
@lars670 Yeah, we are aware but its not that simple based on how some lawyers are reading those documents. We are working our way through it.
