### ISSUE TITLE
GROW TOPs SSE Connection limit

### ISSUE THREAD

**Issue by rmantovani** [iexg/IEX-API#1065]
**Clearly describe the problem**

I'm a Grow user and I'm selecting all the symbols and creating threads of 50 symbols each and calling the TOPS api
Docs said: "Currently SSE requests are limited to 50 symbols per connection, but you can have multiple connections."

I open the necessary number of connections and realize that there are some non-streaming connections

Is there a limit of simultaneous connection?

**What time did the problem occur? (with timezone)**
anytime

**What is the expected behavior?**
All conections streaming

**Your environment (e.g. browser, OS, API version, language):**
Linux, Ubuntu Java

**API URL (if applicable)**
https://cloud-sse.iexapis.com/stable/tops?token=TOKEN&symbols=A,AA...

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by evancarter-iex** [comment]
@rmantovani No there isnt. It should be streaming fine.
