### ISSUE TITLE
[Request] Price call with multiple symbols

### ISSUE THREAD

**Issue by dmikester1** [iexg/IEX-API#1066]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is possible or not and would like to know how to do it if so.  I am using the `price` call: https://iexcloud.io/docs/api/#price but I want to query multiple symbols at once to speed up my data fetching.  I noticed the `query parameters` option: https://iexcloud.io/docs/api/#query-parameters but it does not say which calls those can be used with.  I tried it with `price` to no avail: https://cloud.iexapis.com/stable/stock/price/?token=&symbols=A,AA,AAAU

**Describe the solution you'd like**
The fastest solution to get latest `close` prices of several stocks at once.  I trying to assign the `close` prices to all stocks in the calls for ref-data/otc/symbols and ref-data/symbols.

**Describe alternatives you've considered**
Doing it one at a time is very slow.

**Additional context**

**Comment by McQgit** [comment]
@dmikester1  Does this help?
`https://cloud.iexapis.com/stable/stock/market/batch?symbols=aapl,msft&types=quote&filter=latestPrice&token=(redacted)`

You can list multiple items in `filter` if you want other items from the quote response.

**Comment by dmikester1** [comment]
@McQgit That looks very promising, I will give it a go and let you know.  Thanks!
