### ISSUE TITLE
add IEXDotNetWrapper to list of libraries

### ISSUE THREAD

**Issue by vslee** [iexg/IEX-API#1067]
I found another C# library for IEX Cloud: https://git.zh-code.com/zhironghuang/iexdotnetwrapper

**Comment by evancarter-iex** [comment]
Thanks will be added in our next documentation update.

**Comment by vslee** [comment]
Hi @evancarter-iex, I have started working on a library for IEX Cloud at https://github.com/vslee/IEXSharp, if you could add it to the list.
