### ISSUE TITLE
Previous Day Price for multiple stocks

### ISSUE THREAD

**Issue by BrianARice** [iexg/IEX-API#1069]
The documentation says for Previous Day Price:
This returns previous day adjusted price data for one or more stocks.

How can you get it for more than one stock since the symbol is part of the url?
/stock/{symbol}/previous

/stock/fb,aapl/previous didn't work... not sure what else to do.

What is the best way to get the previous day close for, say, 20 stocks at once?

**Comment by McQgit** [comment]
@BrianARice  Perhaps something like this?
[]https://cloud.iexapis.com/v1/stock/market/batch?symbols=aapl,msft,fb&types=previous&token=TOKEN

Also see post #1066 where I give example of retrieving single value from quote endpoint for multiple symbols

**Comment by evancarter-iex** [comment]
/batch with close is a good way to get the data you need.
