### ISSUE TITLE
Inconsistent date pattern

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#107]
## Summary

Currently for different messages we have different date patterns. For some of messages pattern is yyyyMMdd and for some other it is yyyy-MM-dd. Would be more convenient to have it standardized.

### Date/time of issue

2017-11-25

### API URL

https://iextrading.com/developer/docs/#hist
https://iextrading.com/developer/docs/#financials

### What you expected to happen

I expected that 

Financials#reportDate
HIST#date

will have the same date format.

### What actually happened

Instead I get:

Financials#reportDate - yyyy-MM-dd
HIST#date - yyyyMMdd

**Comment by SeamusBoyle** [comment]
Also, `/stock/chart` responses containing daily data return dates in ISO8601 extended but those returning minute data return dates in ISO8601 basic.

**Comment by joshuablackburn-iex** [comment]
Confirmed inconsistency.  We will resolve this in our 2.0 release.
