### ISSUE TITLE
Using WEBSERVICE in Excel 2016

### ISSUE THREAD

**Issue by andrewbigler** [iexg/IEX-API#1070]
I am attempting to query some fairly basic data using the WEBSERVICE function, but it has been challenging to figure out how to retrieve anything other than the quote endpoints. I have read through the introductory material (https://iexcloud.io/docs/api/#introduction) to navigate the data but keep getting stuck. I don't have a programming background, which doesn't help, so is there a resource that has more examples or instructions specific to Excel other than the example template that only has 3 data points?  Is it easier for a beginner to use Sharp, JSONP, or another option?

For example, I tried a few different ways to get just the dividendYield key/datapoint and the Excel formula either returns the #VALUE! error or I get all of the keys for that endpoint.

**API URL (if applicable)** - https://cloud.iexapis.com/stable/stock/

**Comment by McQgit** [comment]
@andrewbigler First, have you read:
[]https://iexcloud.io/docs/api/#excel-how-to

Presumably you got at least some data item into excel from those examples.  If so, for items in the stats endpoint, you can use something like this:
[]https://cloud.iexapis.com/stable/stock/aapl/stats/dividendYield?token=TOKEN

Do you see the pattern?  
Fixed start of url: https://cloud.iexapis.com/stable/stock
Symbol: aapl
Endpoint: stats
Item: dividendYield 

Just substitute your symbol, endpoint, and item for any other (and token of course).  The endpoints can be any shown in the Excel How-to above.  The name of the item is case sensitive and is any item shown for the endpoint used.

It is challenging to learn your first api w/out a programming background.  And, IEX isn't the easiest to learn given its APIs are evolving faster than its docs (ahem).  Stick to the simplest basics like these before considering things like json, sharp, or other integration with excel.  Once you do get some skills, I think what works best is to download whole endpoints as a csv into its own worksheet and use that as source for other worksheets (with excel search, index, match, and so on).  But, that's my personal preference and not for beginners.

Lastly, when you ask for help and say "I tried a few ways" it is helpful to show what those things were.  That way those of us wishing to help don't have to guess what you did wrong.

Good luck.

**Comment by andrewbigler** [comment]
Thank you for taking the time to respond, McQgit. This is very helpful. I think part of the issue may be in how I was using CONCATENATE to create the queries.

I will report back if I have any new examples.

**Comment by andrewbigler** [comment]
@McQgit Here is an example I can't get to work using the same methodology as above (symbol/endpoint/item):

https://cloud.iexapis.com/stable/stock/aapl/advanced-stats/forwardPERatio?token=TOKEN

**Comment by McQgit** [comment]
@andrewbigler Yeah, didn't work for me either.  Evan already closed this so you'll have to submit new issue giving this specific example along with any others that failed.  You should include a few that work as comparison.  It's helpful anyway now that it is more specific problem.

For example, I found `beta`, `exDividendDate`, `companyName`, and `employees` to all work.  But, `pegRatio`, `forwardPERatio`, and a couple others did not.  Maybe coincidental, but the ones that failed were later in the sequence of items returned.

Oh, and when I say those didn't work I mean instead of getting just the single value I got the entire JSON response block for that endpoint - all 50+ items from `week52change` through `peLow`.
