### ISSUE TITLE
IEX Cloud Reports Inconsistent Closing Date for Specific Equities

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#1071]
**Clearly describe the problem**
The 'closeTime' for several equities (AINV, GDV, JQC, MCC) is consistently for the next business day when prices are pulled after 20:00 (Eastern).

**What time did the problem occur? (with timezone)**
The issue has occurred repeatedly when prices are pulled after 20:00 Eastern

**What is the expected behavior?**
The closing date should reflect the last closing price, any price after the last close should be reported under the 'extended' fields.

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Mac/Windows, IEX Cloud v1, PHP

**API URL (if applicable)**
https://cloud.iexapis.com/V1/stock/market/batch?types=quote,dividends&symbols=ainv,gdv,jqc,mcc&token=MY_TOKEN

**What are the steps to reproduce the bug?**
The API call above consistently reproduces the issue when executed after 20:00 eastern

**Additional context**

**Comment by joshuablackburn-iex** [comment]
How are you parsing the timestamp? I just pulled GDV and the date is showing as June 26th at 20:57 ET

**Comment by GraceRg** [comment]
The specific PHP instruction is listed below:
`$quote->dt_close = date('Y-m-d', $quote->dt_close/1000);`

where $quote->dt_close is assigned from 'closeTime'.
I pulled my latest info this morning at about 05:55AM Eastern, before the markets opened.

**Comment by McQgit** [comment]
@GraceRg  You are likely having an issue with timezone conversion.  I had similar issues with php when I first started with IEX.  To best diagnose, you need to show the numeric timestamp value.  Then, use one of the online translaters to see what it converts to.  IEX refers to this one in their docs: []https://currentmillis.com/

You need to take care with php's date function and your default timezone setting, if any.  It's a bit of a guess but I'm thinking you are converting an eastern timestamp to GMT and thus getting the wrong date when the timestamp is late in the day.  Can't know better until you show the actual numeric timestamp.

Here is a good stackoverflow description of php and timezone:
[]https://stackoverflow.com/questions/20288789/php-date-with-timezone/20288836

Hope this helps.
