### ISSUE TITLE
[Data] ex-date sometimes have zero

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#1073]
**Clearly describe the data problem**
ticker: DIS
ex-date: 0000-00-00
{"exDate":"0000-00-00","paymentDate":"2019-07-25","recordDate":"2019-07-08","declaredDate":"2019-06-26","amount":0.88,"flag":"No Change QoQ","currency":"USD","description":"Walt Disney Co. Declares Semi Annual Dividend of $0.88 Per Share","frequency":"Semi-Annual","symbol":"DIS"}

ticker: AGX
ex-date: 2019-07-22
data: {"exDate":"2019-07-22","paymentDate":"2019-07-31","recordDate":"2019-07-23","declaredDate":"2019-06-20","amount":0.25,"flag":"No Change QoQ","currency":"USD","description":"Argan Declares Quarterly Dividend of $0.25 Per Share","frequency":"Quarterly","symbol":"AGX"}

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/dis/dividends/next?token=MY_TOKEN

**What time did the problem occur (including timezone)?**
now

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
API version

**Additional context**

**Comment by evancarter-iex** [comment]
This has been resolved with our expanded and updated Dividend data.
