### ISSUE TITLE
[Data] Previous Day Price endpoint unstable

### ISSUE THREAD

**Issue by gromgit** [iexg/IEX-API#1075]
**Clearly describe the data problem**

I've been polling the Previous Day Price endpoint for *A* and *AAPL* every hour since 6:06am ET today (2019-06-28), and getting bizarre results:

* 6:06am: A and AAPL return `date` = 2019-06-27, but the `close`/`uClose` value for _2019-06-26_ instead (confirmed manually via MarketWatch), and OHLV etc. are all `0`
* 7:06am: _see 6:06am_
* 8:06am: AAPL reports as per _6:06am_, but A returns dataset for **2019-03-04**!
* 9:06am: _see 6:06am_
* 10:06am: A and AAPL return `date` = 2019-06-27, as well as (finally!) correct `close`/`uClose` values for that date, but all other values still `0`
* 11:06am: _see 10:06am_

I gave up trying to get correct data at this point.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=A,AAPL&types=previous

**What time did the problem occur (including timezone)?**

See above

**What is the expected behavior?**

When a different date is received in a response, **all** values should be correct for that date. Also, the sudden "time-traveling" that A underwent hints at a serious backend bug.

**What are the steps to reproduce**

`curl https://cloud.iexapis.com/stable/stock/market/batch?symbols=A,AAPL&types=previous&token=...`

**Your environment (e.g. browser, OS, API version, language):**

Ubuntu Linux 18.04.2 LTS, command-line `curl` client

**Additional context**

I've saved the server's response headers + JSON output for every hour, and can provide them via a separate channel if needed.

**Comment by evancarter-iex** [comment]
@gromgit Thanks for the detailed report. We are aware and are working with our data provider to fix the problem for the outstanding 0 values.

**Comment by gromgit** [comment]
Noted with thanks. How about the issue of A abruptly backstepping over 3 months?

**Comment by evancarter-iex** [comment]
@gromgit This should be fixed now. As per the weird issue with A, it was a one off issue that we added a check to prevent it from happening again.
