### ISSUE TITLE
[Issue] Quote endpoint returns null latestPrice for some OTC stocks

### ISSUE THREAD

**Issue by smidwap** [iexg/IEX-API#1076]
**Clearly describe the problem**
Some OTC stocks have a null `latestPrice` in the Quote endpoint.

**What time did the problem occur? (with timezone)**
11:41am EST

**What is the expected behavior?**
I'd expect `latestPrice` to return yesterday's closing price for OTC stocks. I believe the majority of OTC stocks return the expected result.

**Your environment (e.g. browser, OS, API version, language):**
IEX Cloud stable

**API URL (if applicable)**
Example: https://cloud.iexapis.com/stable/stock/BASFY/quote

**What are the steps to reproduce the bug?**
Call the API

**Additional context**
Here's the response I receive for BASFY:

```
{
  "symbol": "BASFY",
  "companyName": "BASF SE",
  "calculationPrice": "previousclose",
  "open": null,
  "openTime": null,
  "close": null,
  "closeTime": null,
  "high": null,
  "low": null,
  "latestPrice": null,
  "latestSource": "N/A",
  "latestTime": "N/A",
  "latestUpdate": null,
  "latestVolume": 0,
  "iexRealtimePrice": null,
  "iexRealtimeSize": null,
  "iexLastUpdated": null,
  "delayedPrice": null,
  "delayedPriceTime": null,
  "extendedPrice": 17.44,
  "extendedChange": null,
  "extendedChangePercent": null,
  "extendedPriceTime": 1561492651000,
  "previousClose": null,
  "change": null,
  "changePercent": null,
  "iexMarketPercent": null,
  "iexVolume": null,
  "avgTotalVolume": 292824,
  "iexBidPrice": null,
  "iexBidSize": null,
  "iexAskPrice": null,
  "iexAskSize": null,
  "marketCap": null,
  "peRatio": null,
  "week52High": 24.74,
  "week52Low": 16.3,
  "ytdChange": 0.015003
}
```

**Comment by jcpny1** [comment]
I'm having the same issue, but with NYSE.

At approx 4:15pm ET, while IBM change was -4.54, for about 20 minutes I was getting null.

**Comment by evancarter-iex** [comment]
This appears to be working.
