### ISSUE TITLE
[Issue] OTC stock has stale closing price

### ISSUE THREAD

**Issue by smidwap** [iexg/IEX-API#1077]
**Clearly describe the problem**
TCEHY (an OTC stock) returned a `latestPrice` of 44.95 timestamped June 27, 2019 via the Quote endpoint. 44.95 is TCEHY's June 26th's closing price.

**What time did the problem occur? (with timezone)**
June 28, 2019 at ~12:30pm EST

**What is the expected behavior?**
TECHY should return 44.36 as its closing price for June 27. However, I just re-called the Quote endpoint at around 12:38pm EST, and the problem appears to have been resolved.

**Your environment (e.g. browser, OS, API version, language):**
IEX Cloud stable

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/TCEHY/quote

**What are the steps to reproduce the bug?**
Call the API

**Additional context**
Here's the response I received:

```
{
  "symbol": "TCEHY",
  "companyName": "Tencent Holdings Ltd.",
  "calculationPrice": "previousclose",
  "open": null,
  "openTime": null,
  "close": null,
  "closeTime": null,
  "high": null,
  "low": null,
  "latestPrice": 44.95,
  "latestSource": "Previous close",
  "latestTime": "June 27, 2019",
  "latestUpdate": 1561608000000,
  "latestVolume": 0,
  "iexRealtimePrice": null,
  "iexRealtimeSize": null,
  "iexLastUpdated": null,
  "delayedPrice": null,
  "delayedPriceTime": null,
  "extendedPrice": 45.35,
  "extendedChange": 0.4,
  "extendedChangePercent": 0.0089,
  "extendedPriceTime": 1561665600000,
  "previousClose": 44.95,
  "change": 0,
  "changePercent": 0,
  "iexMarketPercent": null,
  "iexVolume": null,
  "avgTotalVolume": 3422476,
  "iexBidPrice": null,
  "iexBidSize": null,
  "iexAskPrice": null,
  "iexAskSize": null,
  "marketCap": null,
  "peRatio": 34.49,
  "week52High": 51.24,
  "week52Low": 31.54,
  "ytdChange": 0.137687
}
```

**Comment by evancarter-iex** [comment]
This should be resolved.

**Comment by smidwap** [comment]
Thanks for taking a look. Do you know whether a systematic issue was fixed or if the problem simply went away after a day? In other words, it would be comforting to know that this problem is less likely to occur in the future because of some fix applied.

For context, we currently source end-of-day prices from another supplier, but we're interested in switching to IEX. We haven't noticed any issues like this with our current supplier, making me hesitant to switch unless quality is on par.

**Comment by evancarter-iex** [comment]
@smidwap We worked with our data provider to fix the issue. I cant tell you that it wont happen again but this if the first time we have seen it in this particular way (after long use with them). We have written a lot of safeguards on our side and will add more in case this happens again. Hope that helps.

**Comment by smidwap** [comment]
It does! Encouraging to hear data quality is continually being improved. Thanks.
