### ISSUE TITLE
[Issue] VERY URGENT: Latest Price wrong for all stocks right now

### ISSUE THREAD

**Issue by ohlhaver** [iexg/IEX-API#1079]
The latestPrice is showing the value for the previousClose at the moment (instead of for Close as it should).

It’s using previousclose as calculationPrice. See below. Leads to the wrong price being displayed on all applications that rely on your latestPrice data, including your own website https://iextrading.com/apps/stocks/AAPL
where it is also showing the previousClose in place of the latest price!

{"symbol":"AAPL","companyName":"Apple, Inc.","calculationPrice":"previousclose","open":198.61,"openTime":1561728600872,"close":197.92,"closeTime":1561752000870,"high":199.495,"low":197.05,"latestPrice":199.74,"latestSource":"Previous close","latestTime":"June 27, 2019","latestUpdate":1561608000000,

**Comment by ohlhaver** [comment]
Can you please still address this issue? This was a serious problem. It has been fixed by now but it would be nice to see someone addressing it.

**Comment by evancarter-iex** [comment]
@ohlhaver Hi there, there was an issue with our data provider on Friday. This was probably related. It's resolved as you can see.

**Comment by ohlhaver** [comment]
Ok, thanks but is it safe then to rely on the 'latestPrice' value? (In this case we were showing to all our users the wrong price for quite a while. Our conclusion now is - as a safeguard - to check on  it to check on the 'calculationPrice' and also to require that "latestUpdate" > "closeTime" and otherwise just show the "close". I wished that safeguards like that wouldn't be necessary as they increase complexity and likelihood of other errors.)

**Comment by evancarter-iex** [comment]
@ohlhaver I cant really go into what happened with the data provider but I suspect it was a one off issue. We have a lot safeguards in place on our end. Its possible to occur again of course but we are also adding checks on our side as well.

**Comment by mikezliu** [comment]
This issue seems to be reoccurring: https://github.com/iexg/IEX-API/issues/1098
