### ISSUE TITLE
Odd SystemEvent endpoint

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#108]
## Summary

According to the description we should receive a map where the key are symbols provided in the request. Behavior should be similar to one from other endpoints like Trading Status, Security Event, OpHaltStatus, etc. Instead we get single System Event object, no matter how many symbols is provided in the request.

### Date/time of issue

2017-11-25

### API URL

https://iextrading.com/developer/docs/#system-event

### What you expected to happen

According to the description for request:

* /deep/system-event?symbols=snap

I should receive response:

```json 
{
  "SNAP": {
    "systemEvent": "S",
    "timestamp": 1494595800005
  }
}
```

### What actually happened

So for whatever request, like

* /deep/system-event?symbols=snap,aapl

I receive response that is not a map:

```json
{
  "systemEvent": "R",
  "timestamp": 1510947000001
}
```

**Comment by joshuablackburn-iex** [comment]
We will update our docs.  This endpoint is to identify the current state of our trading system, and is not related to a specific symbol.
