### ISSUE TITLE
Missing data in AMZN stock

### ISSUE THREAD

**Issue by kfilonchik** [iexg/IEX-API#1081]
**Clearly describe the problem**
There are missing prices in AMZN stock data. 

![Bildschirmfoto 2019-06-30 um 18 06 05](https://user-images.githubusercontent.com/16308333/60399234-d178d200-9b61-11e9-987b-6f8283e359d7.png)

**What time did the problem occur? (with timezone)**
I took the data between 03.06.2019 and 21.06.2018. In this period there are a lot of missing prices.

**What is the expected behavior?**
There are no some special behavior, just during the day by some timestamps there are no stock price. 

**Your environment (e.g. browser, OS, API version, language):**
The access to data was made in Chrome in Python

**API URL (if applicable)**
https://pypi.org/project/iexfinance/

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by humenick** [comment]
This means no trades crossed on IEX in that minute. Use marketOpen, marketClose... instead of open, close...

**Comment by kfilonchik** [comment]
Ok, but there are also missing prices by marketClose. I have checked the Amazon data on Alphavantage API and I got the full data. 

![Bildschirmfoto 2019-06-30 um 19 30 31 1](https://user-images.githubusercontent.com/16308333/60399973-ccba1b00-9b6d-11e9-90f4-7ce4dbba5924.png)

**Comment by humenick** [comment]
Looks like some intraday data is missing on 2019-06-03 and 2019-06-18. 

Attached minutes where numberOfTrades = 0.

<img width="478" alt="numTrades" src="https://user-images.githubusercontent.com/1775830/60400292-a755ee80-9b26-11e9-8949-d624a65e93d5.png">

**Comment by kfilonchik** [comment]
Well, I have compared the data with other resources (like Alphavantage API) and I got the full data without missed prices. It means that it is something wrong in IEX Cloud.

**Comment by joshuablackburn-iex** [comment]
Is this an ongoing issue?
