### ISSUE TITLE
[Data] Dividend history inconsistencies - the sequel

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#1084]
The previous ticket got lost in the past and no response nor fixes seem to happen. Here is a new one with an update, hopefully this one will be taken care of.

CBSH: zero in 2018 and 2016 here is the history for CBSH: https://www.gurufocus.com/stock/cbsh/dividend

XBI: The last 2 divs from 2019-03-15 and 2019-06-11 are zero.

BF-B: Returns nothing even though it has dividend history (same for other symbols with -/. in the name like jw.a/jw-a. Not sure if - should be a dot in the API

SRC: exDate | "2018-12-28" should be 0.625 and not 0.125 as it came AFTER the reverse split.

IAF: no div history at all

NVO: missing a div in 2016!

SQQQ: Lots of duplicates in general

**Comment by evancarter-iex** [comment]
@Amosss SQQQ is weird, lots of places are reporting different data, so its hard to tell whats right and not.

Ill look into the others

**Comment by McQgit** [comment]
@evancarter-iex  SQQQ's official data is at the sponsor's site:
[]https://www.proshares.com/funds/sqqq_distributions.html

I always prefer the sponsor over any 3rd party site for ETFs.  If they can't get the data right, don't buy it :)

**Comment by Amosss** [comment]
VOD div history: completely wrong, here is the list: https://www.gurufocus.com/stock/vod/dividend

**Comment by McQgit** [comment]
@Amosss  Gurufocus has reasonable approximations of VOD dividends but they are not completely accurate.  They are often off by a couple cents and also truncate the amounts paid to 3 places.  Guru also only has the US ADR amounts, not the native currency amount for ordinary shares.  IEX very helpfully provides the native currency values in upcoming-dividends endpoint.  

The precise amounts are found on the company's site or its ADR sponsor's site.  This is true of VOD and any ADR when needing US dollar amounts.

It is reasonable for individuals to rely on such 3rd party approximations.  But, a data provider like IEX should be more precise.

Company ADR info:
[]https://www.vodafone.com/content/index/investors/shareholders/adr_holders/dividends.html

Deutsche Bank is VOD's ADR sponsor:
[]https://www.adr.db.com/drwebrebrand/dr-universe/dr_details.html?identifier=10112#/divident-history-data

I didn't look at IEX's dividend history for VOD and you didn't mention what exactly is wrong.  I just want to point out that IEX should be accurate and not try to match some 3rd party approximations.

**Comment by Amosss** [comment]
@McQgit , VOD div history contains only 2 dividends out of the so many. One from 2018 and one from 2019.

**Comment by Amosss** [comment]
TERP- div from 2017 has invalid pay date (all zeros)

**Comment by Amosss** [comment]
GSK: the dividend history is of the LSE stock and not of NYSE.  I expect it to be of NYSE:
https://cloud.iexapis.com/stable/stock/gsk/dividends/5y?token=

**Comment by evancarter-iex** [comment]
@Amosss 
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
