### ISSUE TITLE
[Issue] The search endpoint crashes the browser in sandbox API requests.

### ISSUE THREAD

**Issue by aspenforest** [iexg/IEX-API#1085]
**Clearly describe the problem**
When you query https://sandbox.iexapis.com/v1/search/symbol?token=yourvalidsandboxtoken, the browser crashes harder than a flaming Hindenburg zeppelin on a sunny afternoon in 1937.

**What time did the problem occur? (with timezone)**
Continouous

**What is the expected behavior?**
Not crash the browser software.

**Your environment (e.g. browser, OS, API version, language):**
Any browser, does not matter what you use.

**API URL (if applicable)**
https://sandbox.iexapis.com/v1/search/symbol?token=yourvalidsandboxtoken

**What are the steps to reproduce the bug?**
Query the API url with valid symbol and token parameters.

**Additional context**

**Comment by evancarter-iex** [comment]
@aspenforest Is this still a problem. I redeployed the sandbox but doesnt appear to be happening for me. (Not sure if the redeploy fixed the problem or my browser is magically okay)

**Comment by aspenforest** [comment]
It works now ^_^
