### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by derekg52** [iexg/IEX-API#1086]
**Clearly describe the data problem**
The dividend rates provided by the stats endpoint switched from the current rate to a "ttm" during the switch over from API IEX to Cloud IEX.  Leads to missing dividend increases for companies and the data for ETFs is null (SCHD, PCEF for two examples)

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/schd/stats?token=ABC

**What time did the problem occur (including timezone)?**
7/2/2019 9:50:00 AM EST

**What is the expected behavior?**
At a minimum, the rate for an ETF should show, even if it's TTM.  Preferable the dividend rates should be current not TTM for all tickers.

**What are the steps to reproduce**
Use the end point to compare the dividend rate versus other websites with such information.

**Your environment (e.g. browser, OS, API version, language):**
Chrome / Windows 10 / stable and beta API / browser URL

**Additional context**

**Comment by evancarter-iex** [comment]
This is resolved.
