### ISSUE TITLE
SPDR Gold Trust (GLD) Missing Logo

### ISSUE THREAD

**Issue by Jacyle** [iexg/IEX-API#1090]
Following query returns a missing picture:

company_logo = requests.get('https://cloud.iexapis.com/v1/stock/GLD/logo?token=%s')

**Comment by Jacyle** [comment]
This appears to be true with other SPDR logo links as well.

**Comment by evancarter-iex** [comment]
Its really a company logo endpoint, so unfortunately it wont display anytime soon.
