### ISSUE TITLE
[Data] Incorrect beta values for many (all?) stocks

### ISSUE THREAD

**Issue by smidwap** [iexg/IEX-API#1091]
**Clearly describe the data problem**
Stocks are returning erroneous values for beta. For example, BA (Boeing) is returning about -0.02, which is definitely not correct. I see this happening across the board with all stocks — the values all appear to be too low.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/BA/stats/beta?filter=beta

**What time did the problem occur (including timezone)?**
Wed, July 3, 2019 at 2:00pm EDT

**What is the expected behavior?**
BA should return something above 1.

**What are the steps to reproduce**
Call the API

**Your environment (e.g. browser, OS, API version, language):**
N/A

**Additional context**
Perhaps an issue related to month-end updates? I didn't notice this problem when I was reviewing beta values last week.

**Comment by smidwap** [comment]
This appears resolved, but it would be good to know the source of the issue.

**Comment by evancarter-iex** [comment]
@smidwap Has this reoccurred. I suspect I know what the issue was, and it has been fixed going forward.

**Comment by smidwap** [comment]
Thanks for the update. I haven't seen the issue come up again.
