### ISSUE TITLE
Messages all mysteriously used

### ISSUE THREAD

**Issue by gnicolosi** [iexg/IEX-API#1092]
I teach a financial modeling class and have the students pull in IEX data with the API.  Before the summer term, I updated the spreadsheets I teach with to use the cloud API.  However, on 7/1 I opened the spreadsheet for 2 minutes and 1/2 of my monthly message allotment was used. I quickly closed the spreadsheet and emailed IEX support. No word, but shortly after that on the same day despite having nothing open the remaining messages were mysteriously used. What is going on? I have postponed the assignment slightly but I need to know if I need to find another source for the students to pull data from.

**Comment by smidwap** [comment]
Not an IEX employee, but this sounds like a tough problem to debug unless you share your spreadsheet and message use. You can log into the IEX console, click on Message Use, and scroll down to "Usage by Data Type" to see what data points were being queried.

Are you sharing your API token with your students (or anyone else)? If so, someone may be misusing your token to query the API. You can destroy your API token and create a new one here:
https://iexcloud.io/console/tokens

**Comment by gnicolosi** [comment]
Thanks.  No, I haven't shared the API token with anybody, I haven't had the chance.  It was only when I was prepping between semesters that I noticed that the old IEX links weren't working anymore so I scrambled and updated my spreadsheets before the summer term started.  When modifying the spreadsheets in June I exhausted my pulls all in one day, but I thought I did something wrong.  So I postponed my demonstration to the class until this Monday when the month reset.  But before class started when I briefly opened the first spreadsheet, I realized that 2 minutes ate up half of the pulls! So I quickly shut it down and lectured on a different topic that night.

Under Usage by Data Type, it says that on 7/1 during that brief window I used 253.450 historical_prices, 246,000 balance_sheet, 415 key_stats, and 135 stock_quotes.

Here's a link to one line from the spreadsheet (copied and pasted onto a new google sheet).  The students manage a portfolio that tracks 50 securities and can either track the portfolio's performance and various statistics using Google Sheets or Excel (both of which incorporate the IEX API).  Some of the cells are returning reference errors as they refer to cells that I've deleted for brevity, but you should get the idea in that any cell that refers to IEX cloud doesn't pull in (and they did all pull in on the day that I converted the sheet). I don't think it's an issue that I share my token here as the pulls are already depleted, but please don't copy it, nevertheless. 
[googlesheetlink]( https://docs.google.com/spreadsheets/d/1ssYeMKupRdnFnyjSNv3zXmd5JUxe1UAL8Ks4SdaLF0c/edit?usp=sharing)

Thanks!

**Comment by smidwap** [comment]
Do you pull several years worth of prices for each security?

**Comment by smidwap** [comment]
I believe it’s 1 message per stock per day for historical prices. That can quickly add up.

**Comment by gnicolosi** [comment]
For each of the current securities we grab the most recent price plus a historic price for the last week and the last few quarter ends... It looks like I'm not consistent and used iex for some historic prices and Googlefinance for others, I'll switch them all to Googlefinance!

**Comment by McQgit** [comment]
@gnicolosi  Perhaps this will shed light on your situation.  I saw this in your spreadsheet:

2 places you used /chart/1m which is roughly 400 msgs each symbol (1m = ~20days * 10weight * 2)
1 place you used /chart/3m which is roughly 600 msgs each symbol (3m = ~60days * 10weight)
So, it looks like you looked up 235 symbols worth of historical data based on your counts above

1 place you used /income for 1,000 each symbol for 235 symbols worth (although why its shown as Balance Sheet in your totals above I'm not sure)

1 place you used /quote which weighs 1 msg so 135 symbols looked up based on your numbers above

3 places you used /stats/ which is 3 msgs (3x1) so 138 symbols looked up based on 415 total above

Does this help make sense of what happened?  Could you have refreshed your spreadsheet a couple times as you were fixing the url's?  It wouldn't take very many symbols to put you over the free tier limit.

What you might not know is that each time you use the importjson2 for a url the entire contents of that request are pulled into the sheet and then a part of that is selected and put in the cell based on your importjson2 parameters (e.g., /close).  So, each reference is pulling more data than you need.

You can dramatically reduce the historical price weight cost by using the chartLast parameter as it won't return the full period of which you extract just the last anyway.  See:
[]https://iexcloud.io/docs/api/#historical-prices

There might be a more efficient way of getting the /income statement item.  Maybe somebody else can help.

**Comment by gnicolosi** [comment]
Thank you so much! There's Room to unpack here but I'm going to patiently wage through it on Friday before Mondays class. I really appreciate the time you took to help me out, thank you!

**Comment by evancarter-iex** [comment]
Im going to close this. If theres additional issues, please reopen or open a new ticket.
