### ISSUE TITLE
stats API not behaving according to docs

### ISSUE THREAD

**Issue by mmistroni** [iexg/IEX-API#1094]
**Clearly describe the problem**
stats endpoint should return a symbol as part of the json response, according to documentation
https://iexcloud.io/docs/api/#key-stats

**What is the expected behavior?**
symbol should be one of the fields returned

**Your environment (e.g. browser, OS, API version, language):**
irrelevant, i am doing  CURL call

**What are the steps to reproduce the bug?**
curl "https://cloud.iexapis.com/stable/stock/AMZN/stats?token=<apitoken>&filter=companyName,beta,symbol,day50MovingAvg,day200MovingAvg,month6ChangePercent,month3ChangePercent,month1ChangePercent"

**Additional context**
this is the result, and symbol is not there. 
{"week52change":0.140769,"week52high":2050.5,"week52low":1307,"marketcap":954631748000,"employees":647500,"day200MovingAvg":1744.88,"day50MovingAvg":1871.88,"float":412858103,"avg10Volume":2761197.4,"avg30Volume":3608890.9,"ttmEPS":24.5526,"ttmDividendRate":null,"companyName":"Amazon.com, Inc.","sharesOutstanding":492332000,"maxChangePercent":75.372357,"year5ChangePercent":5.663763,"year2ChangePercent":1.055287,"year1ChangePercent":0.140769,"ytdChangePercent":0.259803,"month6ChangePercent":0.230806,"month3ChangePercent":0.066052,"month1ChangePercent":0.121094,"day30ChangePercent":0.042652,"day5ChangePercent":0.018233,"nextDividendDate":null,"dividendYield":null,"nextEarningsDate":"2019-07-27","exDividendDate":null,"peRatio":78.97,"beta":1.8432967011342332}"

**Comment by evancarter-iex** [comment]
Documentation will be updated on the next deployment.
