### ISSUE TITLE
Historical data chartCloseOnly param returns with open 

### ISSUE THREAD

**Issue by josephmaxim** [iexg/IEX-API#1096]
**Clearly describe the data problem**
chartCloseOnly param returns with open, high, low etc.

**Data URL (The URL you used to access the data without your token):**
https://sandbox.iexapis.com/stable/stock/market/batch?symbols=AAPL&types=quote,chart&range=1mm&chartCloseOnly=true&displayPercent=true&token=XXXXXXXX

**What time did the problem occur (including timezone)?**
6:14PM EST

**What is the expected behavior?**
Only return close price on chart

**What are the steps to reproduce**
https://sandbox.iexapis.com/stable/stock/market/batch?symbols=AAPL&types=quote,chart&range=1mm&chartCloseOnly=true&displayPercent=true&token=XXXXX

**Comment by evancarter-iex** [comment]
@josephmaxim  range=1mm is defined as: "Historically adjusted market-wide data in 30 minute intervals"

If you do range=1m it will work as expected.

**Comment by josephmaxim** [comment]
What if i only want to only have the Close value by using chartCloseOnly param? i cant use it for 1mm you mean?

**Comment by evancarter-iex** [comment]
@josephmaxim 1mm is defined as 30 minute intervals, not end of day data.

**Comment by josephmaxim** [comment]
@evancarter-iex oh ok my bad. I misunderstood the use of chartCloseOnly param. I thought its for when you only want to return minimal response data like the "close" attribute.
