### ISSUE TITLE
High, Low, change, changePercent returns null or 0 on Market holidays

### ISSUE THREAD

**Issue by josephmaxim** [iexg/IEX-API#1097]
**Clearly describe the data problem**
High, Low, change, changePercent returns null or 0

**Data URL (The URL you used to access the data without your token):**
https://sandbox.iexapis.com/stable/stock/aapl/quote?token=XXXXXXXX

**What time did the problem occur (including timezone)?**
6:19PM EST

**Your environment (e.g. browser, OS, API version, language):**
Chrome, OSX, stable, English

`{
"symbol": "AAPL",
"companyName": "Apple, Inc.",
"calculationPrice": "previousclose",
"open": 212.84,
"openTime": 1596758280092,
"close": 204.57,
"closeTime": 1627167528758,
"high": null,
"low": null,
"latestPrice": 209.92,
"latestSource": "Previous close",
"latestTime": "July 3, 2019",
"latestUpdate": 1610644955339,
"latestVolume": 11673583,
"iexRealtimePrice": null,
"iexRealtimeSize": null,
"iexLastUpdated": null,
"delayedPrice": 0,
"delayedPriceTime": 1619920588423,
"extendedPrice": 213.2,
"extendedChange": -0.01,
"extendedChangePercent": -0.00005,
"extendedPriceTime": 1594510533838,
"previousClose": 207.93,
"change": 0,
"changePercent": 0,
"iexMarketPercent": null,
"iexVolume": null,
"avgTotalVolume": 26066028,
"iexBidPrice": null,
"iexBidSize": null,
"iexAskPrice": null,
"iexAskSize": null,
"marketCap": 951383431529,
"peRatio": 17.88,
"week52High": 233.74,
"week52Low": null,
"ytdChange": 0.29441
}`

**Comment by evancarter-iex** [comment]
@josephmaxim For US holidays when there's no trading we will return null For high/low/etc. Change and change% would also be 0 or null in this scenario. We will look into doing something about that.

**Comment by scottyrotten6** [comment]
yours is a little different. Mine returned a completely blank csv or [] in json. No headings no nothing. Anyway, they fixed my issue. I hope they get yours taken care of soon!

**Comment by evancarter-iex** [comment]
This should be fixed going forward.
