### ISSUE TITLE
[Issue] Quote on weekend sometimes returns wrong price (usually Fridays)

### ISSUE THREAD

**Issue by ruijiang** [iexg/IEX-API#1098]
**Clearly describe the problem**

This has happened to me many times. Basically sometimes after Friday when I request quote for a stock it returns latestPrice, close etc for one business earlier instead of Friday.

**What time did the problem occur? (with timezone)**

7/6/2019, 12:10 AM PDT.

**What is the expected behavior?**

Should return latest/close price on Friday.

**Your environment (e.g. browser, OS, API version, language):**

Chrome.

**API URL (if applicable)**

https://cloud.iexapis.com/v1/stock/roku/quote?token=XXX

**What are the steps to reproduce the bug?**

Just call this API after Friday.

**Additional context**

At this time, calling quote for ROKU returns: 

{
symbol: "ROKU",
companyName: "Roku, Inc.",
calculationPrice: "close",
open: 93.17,
openTime: 1562333400946,
close: 93.51,
closeTime: 1562356800678,
high: 98.444,
low: 92.51,
latestPrice: 93.51,
latestSource: "Close",
latestTime: "July 5, 2019",
latestUpdate: 1562356800678,
latestVolume: 12044003,
iexRealtimePrice: 98.09,
iexRealtimeSize: 18,
iexLastUpdated: 1562356797119,
delayedPrice: 98.11,
delayedPriceTime: 1562356800678,
extendedPrice: 98.27,
extendedChange: 4.76,
extendedChangePercent: 0.0509,
extendedPriceTime: 1562370012737,
previousClose: 93.05,
change: 0.46,
changePercent: 0.00494,
iexMarketPercent: 0.006252987482650079,
iexVolume: 75311,
avgTotalVolume: 10501446,
iexBidPrice: 0,
iexBidSize: 0,
iexAskPrice: 0,
iexAskSize: 0,
marketCap: 10646293133,
peRatio: -851.64,
week52High: 108.32,
week52Low: 26.3,
ytdChange: 1.880401
}

However, on 7/5/2019, Friday, ROKU's closing price is 98.11 (matches delayedPrice). Latest prce/close returned from API 93.51 is actually one business day earlier (on 7/3/2019).

This happens to many other symbols as well: Z/QCOM/AMD etc... So it's not an isolated case.

**Comment by ruijiang** [comment]
By the way, this issue is usually gone the next day. But when it happens it's very annoying.

**Comment by evancarter-iex** [comment]
This is fixed

**Comment by ruijiang** [comment]
Thanks a lot!
