### ISSUE TITLE
[Issue] API Docs: Sample JSON is not valid JSON, need explanation

### ISSUE THREAD

**Issue by onwsk8r** [iexg/IEX-API#1099]
**Clearly describe the problem**

Some of the sample JSON responses in the API documentation are not valid JSON, and there's no explanation why.

1. Are these some fake, hand-written thing?
2. Are these actual responses?
3. Something else?

**What time did the problem occur? (with timezone)**

Current as of the time of this issue (6-Jul-2019 1900Z)

**What is the expected behavior?**

1. Use actual response data, or
2. Document that your API does not return valid JSON.

**Your environment (e.g. browser, OS, API version, language):**

Indeed, some issues are language-dependent. Read on!

**What are the steps to reproduce the bug?**

```
echo '{
  "symbol": "AAPL",
  "earnings": [
    {
      "actualEPS": 2.1,
      "consensusEPS": 2.02,
      "announceTime": "AMC",
      "numberOfEstimates": 14,
      "EPSSurpriseDollar": 0.08,
      "EPSReportDate": "2017-05-02",
      "fiscalPeriod": "Q2 2017",
      "fiscalEndDate": "2017-03-31",
      "yearAgo": 1.67,
      "yearAgoChangePercent": .30,
    },
    {
      "actualEPS": 3.36,
      "consensusEPS": 3.22,
      "announceTime": "AMC",
      "numberOfEstimates": 15,
      "EPSSurpriseDollar": 0.14,
      "EPSReportDate": "2017-01-31",
      "fiscalPeriod": "Q1 2017",
      "fiscalEndDate": "2016-12-31",
      "yearAgo": 1.67,
      "yearAgoChangePercent": .30,
    },
  ]
}' | jq .
parse error: Expected another key-value pair at line 15, column 5
$ echo $?
4
$  man jq | grep -B1 "no valid result"
           Sets the exit status of jq to 0 if the last output values was neither false nor null, 1 if the last output value  was  either
           false  or  null, or 4 if no valid result was ever produced. Normally jq exits with 2 if there was any usage problem or system
```

**Additional context**

The JSON above comes from the docs for the [earnings endpoint](https://iexcloud.io/docs/api/#earnings) and contains two obvious errors. A parser that expects [McKeeman Form](https://www.crockford.com/mckeeman.html) will find either two or four more (depending on the implementation) - do you know what they are? Neither Javascript nor `jq` require McKeeman form, but I can point at five of the [most popular languages](https://insights.stackoverflow.com/survey/2019#technology) that do (and I certainly can't speak for all of them), including the one that prompted this.

But guess what?

```
$ node
> obj = {
...   "symbol": "AAPL",
...   "earnings": [
...     {
.....       "actualEPS": 2.1,
.....       "consensusEPS": 2.02,
.....       "announceTime": "AMC",
.....       "numberOfEstimates": 14,
.....       "EPSSurpriseDollar": 0.08,
.....       "EPSReportDate": "2017-05-02",
.....       "fiscalPeriod": "Q2 2017",
.....       "fiscalEndDate": "2017-03-31",
.....       "yearAgo": 1.67,
.....       "yearAgoChangePercent": .30,
.....     },
...     {
.....       "actualEPS": 3.36,
.....       "consensusEPS": 3.22,
.....       "announceTime": "AMC",
.....       "numberOfEstimates": 15,
.....       "EPSSurpriseDollar": 0.14,
.....       "EPSReportDate": "2017-01-31",
.....       "fiscalPeriod": "Q1 2017",
.....       "fiscalEndDate": "2016-12-31",
.....       "yearAgo": 1.67,
.....       "yearAgoChangePercent": .30,
.....     },
...   ]
... }
{ symbol: 'AAPL',
  earnings:
   [ { actualEPS: 2.1,
       consensusEPS: 2.02,
       announceTime: 'AMC',
       numberOfEstimates: 14,
       EPSSurpriseDollar: 0.08,
       EPSReportDate: '2017-05-02',
       fiscalPeriod: 'Q2 2017',
       fiscalEndDate: '2017-03-31',
       yearAgo: 1.67,
       yearAgoChangePercent: 0.3 },
     { actualEPS: 3.36,
       consensusEPS: 3.22,
       announceTime: 'AMC',
       numberOfEstimates: 15,
       EPSSurpriseDollar: 0.14,
       EPSReportDate: '2017-01-31',
       fiscalPeriod: 'Q1 2017',
       fiscalEndDate: '2016-12-31',
       yearAgo: 1.67,
       yearAgoChangePercent: 0.3 } ] }
> obj.earnings[0].yearAgoChangePercent
0.3
```

Node has no trouble with it. You'll notice when it prints the value of `obj`, it prints in McKeeman form - it's fixed the extra and missing `0`'s on the `yearAgoChangePercent` fields as well as the extra commas.

McKeeman says numbers match `/[1-9][0-9]*(\.[0-9]*[1-9])?/`, but some parsers use a simpler `/[0-9]+(\.[0-9]+)?/` and I find it unlikely that a computer would print a floating point number as `.30` unless you've found some trick to omit the leading zero - if so, will an increase of >=100% be represented correctly?

To be clear, none of these are guaranteed to yield the same result when parsing:

- `"yearAgoChangePercent": 0.3`
- `"yearAgoChangePercent": .3`
- `"yearAgoChangePercent": .30`
- `"yearAgoChangePercent": 0.30`
- `"yearAgoChangePercent": ".30"`

Also, how are your math skills?
```
{
  ...
  "yearAgo": 1.67,
  "yearAgoChangePercent": .30,
  "actualEPS": 3.36
}
```
The other object in the array has
```
{
  ...
  "yearAgo": 1.67,
  "yearAgoChangePercent": .30,
  "actualEPS": 2.1
}
```
Which isn't much better-
```
$  echo $((1.67 * (1 + 0.30/100)))
1.6750099999999997
$  echo $((1.67 * (1 + 30/100.0)))
2.1709999999999998
```
There's the obvious - is `yearAgoChangePercent` not actually a percent? I bet you'll be getting some angry calls if the API returns a percent (ie `30`)! But then there's the more subtle math issue in the second statement (note I'm using zsh so I can do FP math): I can't come up with a single equation that involves 1.67, 2.1, and anything close to 0.3 - the closest I could get is `2.1 / 1.67 - 1` is `0.257`. Is my math wrong? Are the numbers wrong? Is there undocumented rounding? Have I discovered a bug?

Also, what about zero/missing values? If a trading `volume` is missing, will we get `"volume": 0`? If so how can we tell if, for example, the stock was just not traded that day/minute? `"volume": -1`? As a developer, I might use an unsigned number for that value, and as a DBA, I might `CHECK` that field for a positive integer. Nothing at all? Are any values guaranteed to be there?

Supposing the docs are wrong, is the sandbox data correct? Are there accurate docs that can be used for development? A reference implementation? Do we have to burn through API calls to "see what happens"? That's a pretty expensive way to figure out what missing values look like.

Anyways, I hope this provides some direction looking forward, and some clarity around what developers require to create robust software. The TL;DR is

- Provide samples of real data. As a developer, I need the actual response from the server, and my employer is unlikely to let me test against the nonfree production API any more than is absolutely necessary. As a decision maker, I want to work with companies that understand this.
- If those samples don't demonstrate how missing data is represented, the docs must. This is essential for anything derived from historical prices: again, if company X was not traded last Tuesday, what do those values look like? What about OHLC requests for a holiday?

**Comment by evancarter-iex** [comment]
@onwsk8r Thanks for the detailed bug report.  I have updated the example to make sure it accurately reflects what is returned in sandbox/production. It will be deployed during our next docs deploy.  Sandbox is 1:1 to production minus randomized data.

**Comment by onwsk8r** [comment]
Thanks @evancarter-iex , looks like most updates are there already. Apologies on the verbosity if you are a developer- you probably already know all that stuff.
