### ISSUE TITLE
[Data] Excel Power Query 400 error

### ISSUE THREAD

**Issue by RyanAKaplan** [iexg/IEX-API#1100]
**Clearly describe the data problem**
Attempting batch request via Excel Power Query results in 400 error

**Data URL (The URL you used to access the data without your token):**

= Json.Document(Web.Contents("https://cloud.iexapis.com/stable/stock/market/batch?symbols=aapl,fb,tsla&types=quote,news,chart&range=1m&last=5?token=YOUR_TOKEN_HERE"))

**What time did the problem occur (including timezone)?**
07/07/2019 10:11AM PST

**What is the expected behavior?**
Returns multiple columns of data by date range? Not sure what the output should look like. Other simple requests such as quote / financials etc work fine. Including batch and range always seem to either 400 error or say "Access Forbidden". This one gives a 400 error.

**What are the steps to reproduce**
Power Query Editor > New Source > Blank Query > see above URL (I am replacing "YOUR_TOKEN_HERE" with my publishable token.)

**Your environment (e.g. browser, OS, API version, language):**
Excel Power Query

**Additional context**
I am pretty new to this, so apologies if this is a simple thing I'm missing.

**Comment by McQgit** [comment]
@RyanAKaplan Your question mark in front of `token=` should be an ampersand.  A single question mark delineates the url from the query parameters.  An ampersand separates multiple queries.

[]https://en.wikipedia.org/wiki/Query_string
