### ISSUE TITLE
[Data] Chart API: Open, High, Low are still 0 for many stocks (various dates)

### ISSUE THREAD

**Issue by lohisoftware** [iexg/IEX-API#1101]
**Clearly describe the data problem**

There was a data issue with chart API on 6/27 that affected most stocks, where at least Open, High and Low were 0. That bug has been closed as [fixed](https://github.com/iexg/IEX-API/issues/1078). However, the issue seems to be on-going with some stocks. As you can see below, chart API returns 0 values as recently as 7/3. The ticker ACY is just one example.

Could you please investigate with your data provider if the issue can be fixed. These stocks may have low volume, but in my opinion it is still wrong to return Open, High and Low as 0 if Close is not zero.

[
...
    {
        "date": "2019-06-24",
        "open": 0,
        "high": 0,
        "low": 0,
        "close": 7.26,
        "volume": 98
    },
...
    {
        "date": "2019-06-27",
        "open": 0,
        "high": 0,
        "low": 0,
        "close": 7.33,
        "volume": 44
    },
...
    {
        "date": "2019-07-03",
        "open": 0,
        "high": 0,
        "low": 0,
        "close": 7.3,
        "volume": 100
    }
]

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/v1/stock/acy/chart?chartLast=20&filter=date,open,high,low,close,volume&token=

**What time did the problem occur (including timezone)?**

7/7/2019 3:40pm PST 

**What is the expected behavior?**

If Close is not 0 then at least High should not be 0.

**What are the steps to reproduce**

Please use the URL above.

**Your environment (e.g. browser, OS, API version, language):**

Chrome

**Additional context**

**Comment by evancarter-iex** [comment]
@lohisoftware This is most likely due to the fact that the volume is extremely low on those dates. Most likely any trades that occurred on that date (ie 7/3 with a volume of 100) are not last sale eligible thus dont count for high/low etc.

Page 22 of this pdf goes into it (but its basically the same on NYSE and NASDAQ)
http://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NLSSpecification.pdf
