### ISSUE TITLE
1 minute chart data is not returning any data for July 5, 2019 for AMAT, ALK

### ISSUE THREAD

**Issue by scottyrotten6** [iexg/IEX-API#1102]
Clearly describe the data problem
1 minute chart data is not returning any data for July 5, 2019 for several symbols. So far ALK and AMAT don't work, I'm guessing there are more.

Data URL (The URL you used to access the data without your token):
https://cloud.iexapis.com/v1/stock/ALK/chart/date/20190705/?token=myToken&filter=minute,marketOpen,marketHigh,marketLow,marketClose,marketVolume&format=csv

What time did the problem occur (including timezone)?
7/5/2019 is not working. I tried to call the data on 7/8/2018.

What is the expected behavior?
I expect a csv file to be returned with the requested data.

What are the steps to reproduce
Just follow the URL above. It will return an empty csv file.

Your environment (e.g. browser, OS, API version, language):
google chrome, Windows, v1, english

Additional context

**Comment by josephmaxim** [comment]
https://github.com/iexg/IEX-API/issues/1097

**Comment by evancarter-iex** [comment]
@scottyrotten6 @jonathanyam-iex Can you check now?

**Comment by scottyrotten6** [comment]
All good. Thank you!

**Comment by scottyrotten6** [comment]
Bro now its doing it for ABC for 20190708. Can you please reopen and see if you can fix this? I lost a trading day yesterday because my system counts on scanning through the stocks looking for set ups. If I don’t hear back I guess I’ll open a new issue, but this is exactly the same thing.

**Comment by evancarter-iex** [comment]
@scottyrotten6 Im seeing data for abc 20190708. I just triple checked.

**Comment by scottyrotten6** [comment]
https://cloud.iexapis.com/v1/stock/ABC/chart/date/20190708/?token=myToken&filter=minute,marketOpen,marketHigh,marketLow,marketClose,marketVolume&format=csv

I just did the above link with my token and it won’t work. Can you try this exact link? I really appreciate your help btw.

**Comment by evancarter-iex** [comment]
@scottyrotten6 Can you try again? Just tried and its fine for me.

**Comment by scottyrotten6** [comment]
I emailed you earlier let you know that it was working:

Well I swear it was not working for me. I am not a newbie and am certain that it wasn’t; and I would never want to waste your time. That being said, I just tried again and it worked. My apologies and thank you again for all your help.

Thanks again!
Scott

**Comment by evancarter-iex** [comment]
@scottyrotten6 No worries. Let me know if it happens again.

**Comment by scottyrotten6** [comment]
Will do. Have a good one!

**Comment by scottyrotten6** [comment]
Hello

The same thing is happening again this morning for July 26th, 2019 (20190726). I stopped my algo after it crashed on ABC and ABT, I’m guessing there are more. Please let me know if there is anything else I need to provide.

Thanks,
Scott

From: Langford, Scott
Sent: Tuesday, July 9, 2019 8:21 AM
To: iexg/IEX-API <reply@reply.github.com>
Subject: RE: [iexg/IEX-API] 1 minute chart data is not returning any data for July 5, 2019 for AMAT, ALK (#1102)

Will do. Have a good one!

**Comment by evancarter-iex** [comment]
@scottyrotten6 I see data for ABC and ABT can you recheck?

**Comment by scottyrotten6** [comment]
All good. I was just about to email. Thank you for fixing that so fast!

Scott

**Comment by scottyrotten6** [comment]
Same thing again. I read your email from last time more closely and it implied that you never noticed an error, and that it just started working for me again. Below is the exact link I’m using, and it works every day except random days when it stops for certain stocks. I’ve tried it a dozen times this morning and it returns an empty file. Further, it works with other stocks. Short version – I’m 100% certain this isn’t an error on my end. Thanks again for all your help.


https://cloud.iexapis.com/v1/stock/ABC/chart/date/20190806/?token=sk_577cf0dc1ce3480d9ad06b8bc28a745e&filter=minute,marketOpen,marketHigh,marketLow,marketClose,marketVolume&format=csv



From: Langford, Scott
Sent: Monday, July 29, 2019 6:55 AM
To: iexg/IEX-API <reply@reply.github.com>
Subject: RE: [iexg/IEX-API] 1 minute chart data is not returning any data for July 5, 2019 for AMAT, ALK (#1102)

All good. I was just about to email. Thank you for fixing that so fast!

Scott
