### ISSUE TITLE
[Issue] stock/......./previous does not return previous session

### ISSUE THREAD

**Issue by RuiFigueiredoAlgo** [iexg/IEX-API#1103]
**Clearly describe the problem**

when using
https://cloud.iexapis.com/v1/stock/AAPL/previous?token=mytoken
does not return the previous session data

![Untitled](https://user-images.githubusercontent.com/47220667/60871708-2e901a00-a22b-11e9-8de7-62e108c4daa0.png)

**What time did the problem occur? (with timezone)**

9:20 GMT

**What is the expected behavior?**

Return previous session data

**Your environment (e.g. browser, OS, API version, language):**

Windows 7 English, firefox
**API URL (if applicable)**
https://cloud.iexapis.com/v1/stock/AAPL/previous?token=mytoken

**What are the steps to reproduce the bug?**
https://cloud.iexapis.com/v1/stock/AAPL/previous?token=mytoken

**Additional context**
Regarding this Isse ?
https://github.com/iexg/IEX-API/issues/1051
I based all my SW on the stock/market/previous

Since there was no answer instead of a one request I'm making the symbols I want to get the previous session

After 10:00 AM GMT already works as expected

**Comment by evancarter-iex** [comment]
This is fixed.
