### ISSUE TITLE
[Bug] stock/......./previous returns diferents types of data

### ISSUE THREAD

**Issue by RuiFigueiredoAlgo** [iexg/IEX-API#1104]
**Clearly describe the problem**

In most cases does not return symbol

**What time did the problem occur? (with timezone)**

10:31 GMT

**What is the expected behavior?**

To not return symbol 

**Your environment (e.g. browser, OS, API version, language):**

windows 7 english firefox

**API URL (if applicable)**

https://cloud.iexapis.com/v1/stock/APRI/previous?token=token
https://cloud.iexapis.com/v1/stock/AAPL/previous?token=token

![Untitled2](https://user-images.githubusercontent.com/47220667/60877091-09a0a480-a235-11e9-916d-b6923151ad73.png)

![Untitled3](https://user-images.githubusercontent.com/47220667/60877416-ac592300-a235-11e9-9816-a329d77ac8df.png)

**Comment by evancarter-iex** [comment]
@RuiFigueiredoAlgo Not sure I understand this bug report. In your screenshots, you can clearly see (and I confirmed) that symbol is in both return values.

**Comment by RuiFigueiredoAlgo** [comment]
Yes, but in diferent order !
I got around it, but it is not logical that in 98% of the requests "symbol" lies in the returning json at the end, and the remaining 2% of the requests is at the beginning of the json.
Would you not agree ?

**Comment by evancarter-iex** [comment]
It depends where the data is coming from internally. Either way its json object that can be parsed anyway you want.
