### ISSUE TITLE
Pre and Post 

### ISSUE THREAD

**Issue by jjreego** [iexg/IEX-API#1105]

**Comment by jjreego** [comment]
for Quotes I need real time price and volume information and for pre and post trading sessions. Some stocks now trade 24/7 on TDAmeritrade. Information delayed 15 minutes is not of any value. What is the issue here.? Why can't real time proce and volume information be provided?  I can get this information from TDAmeritrade, ETrade, Fidelity and others.

**Comment by joshuablackburn-iex** [comment]
TD, eTrade, etc pay a ton of money for real time data, and that is just to display it on a website. In order for us to distribute real time data via API, you would be required to contract directly with the exchanges and pay the same fee. The access fee alone is over $1,500 a month.
