### ISSUE TITLE
[Data] Missing intraday data for specific symbols and dates

### ISSUE THREAD

**Issue by pathvine** [iexg/IEX-API#1111]
**Clearly describe the data problem**
Some of the intraday data for some symbols are missing.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/ko/chart/date/20190628
https://cloud.iexapis.com/stable/stock/c/chart/date/20190627
https://cloud.iexapis.com/stable/stock/slv/chart/date/20190703

**What time did the problem occur (including timezone)?**
For whole trading day when those data are missing.

**What is the expected behavior?**
The API should return the market minute-by-minute OHLCV quotes for those symbols and dates. 

**What are the steps to reproduce**
By Visiting those API listed above.

**Your environment (e.g. browser, OS, API version, language):**
Any

**Additional context**

**Comment by rmantovani** [comment]
I came across the same problem on days:

https://cloud.iexapis.com/stable/stock/aapl/chart/date/20190619
https://cloud.iexapis.com/stable/stock/aapl/chart/date/20190620

**Comment by evancarter-iex** [comment]
@pathvine Your stuff should be backfilled. @rmantovani I am backfilling yours as we speak. If you see any additional ones, let me know, I'm trying to figure out why we are having a backfill issue sporadically
