### ISSUE TITLE
[Issue]SSLError

### ISSUE THREAD

**Issue by hukf** [iexg/IEX-API#1112]
**Clearly describe the problem**
received error like this HTTPSConnectionPool(host='cloud.iexapis.com', port=443): Max retries exceeded with url: /v1/ref-data/symbols?token=pk_0772b1b29f7xxxxxxxxx  (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

**What time did the problem occur? (with timezone)**
7/12/2019

**What is the expected behavior?**
SSL should pass with my secret token. (from free account)

**Your environment (e.g. browser, OS, API version, language):**
Windows 10 Python 3.6 , iexfinance library 0.4.2

**API URL (if applicable)**

**What are the steps to reproduce the bug?**
I wonder what cause the SSL verify failed.?
Thanks a million!

**Additional context**

**Comment by evancarter-iex** [comment]
@hukf Certificates are fine on our side. Does it reoccur? If so its probably something to do with your environment.

**Comment by hukf** [comment]
I just found out the problem. The SSL error is caused by VPN. The token isn't setup at the VPN server side so it caused certification errors. Once the code is running without VPN, error goes away. Unfortunately, the VPN is set by company admin, I don't know if there is a way to solve the problem behind VPN?
