### ISSUE TITLE
[Data] Financials mismatch with SEC.gov for revenues

### ISSUE THREAD

**Issue by xunamcapital** [iexg/IEX-API#1113]
**Clearly describe the data problem**

I have noticed that numbers in income statements from your "financials" API do not match Sec.gov filings.

For example for Realty Income corporation (Ticker O), total revenue for report date 03-31-2019 is:

Your API: "totalRevenue":357765000
Sec 10-Q filing: Total Revenue 354,365   thousand

As you can see the numbers are not the same by around $3 million. Other numbers such as operating revenues also do not match

Net incomes on the other hand match.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/o/financials
or
https://cloud.iexapis.com/stable/stock/o/income

**What time did the problem occur (including timezone)?**
Any time, the problem is with financials data, not live data

**What is the expected behavior?**
Financial information published on https://www.sec.gov/ 

**What are the steps to reproduce**
Compare totalRevenue number in https://cloud.iexapis.com/stable/stock/o/income call with Total revenues on sec.gov website, direct link to 10-Q report from 03-31-2019: https://www.sec.gov/Archives/edgar/data/726728/000072672819000049/o-03311910qdocument.htm

**Your environment (e.g. browser, OS, API version, language):**
tried downloading with wget in ubuntu or in chrome

**Additional context**

Was trying to ensure "financials" and "income" functions are reliable, but found this mismatch

I have checked another symbol (EPR) and it has the same exact discrepancy. 

Could you please explain where this discrepancy comes from? I have noticed the same discrepancy?

Thank you very much in advance!

**Comment by evancarter-iex** [comment]
Hi there, our primary data partner has a proprietary methodology for how it consolidates and reports the financials.

If you are looking for as reported financials from the SEC you can use https://iexcloud.io/docs/api/#financials-as-reported

**Comment by xunamcapital** [comment]
Thank you!

**Comment by baddy79** [comment]
@xunamcapital, I can not find the "totalRevenue" in the mentioned financials-as-reported API call, did you?
