### ISSUE TITLE
[Data] News SSE stream with snapshotAsOf

### ISSUE THREAD

**Issue by gcobcqwe** [iexg/IEX-API#1114]
**Clearly describe the data problem**
I used the endpoint https://cloud-sse.iexapis.com/stable/news-stream?symbols={symbols}&snapshotAsOf={latest_timeStamp_of_ticker}+1&token={token} to open connection. And then I've found part of tickers still returned older data to me.

**Data URL (The URL you used to access the data without your token):**
https://cloud-sse.iexapis.com/stable/news-stream?symbols=UDBKL,TNREF,VFWSX,UCLQF,UBMRF,TMRAY,UETTU,TVIFX,TORC,VADDX,UCON,VIGIX,TRKCY,TSFBX,TUSK,UCO,VIAB,UNPA,UPMKY,TRNO,URSSF,TRAIX,VADFX,VINIX,URGN,TSMWX,TRMIX,TOCA,TPHCX,UCSO,TSPABX,TLPC,USGBX,UGEIX,TOMI,VGMUFX,TRTN,TSSXX,VB,VAGLX,UWPSX,TMOL,TOGL,TRUHY,TMNCX,VASO,UOLGY,VGELX,UNAM,UMAM&snapshotAsOf=1563003757001&token={token}

**What time did the problem occur (including timezone)?**
2019/07/14 UTC+8
The problem persists now.

**What is the expected behavior?**
No older data response

**What are the steps to reproduce**
Use the API URL above to listen to news updates. And then wait for response.

**Your environment (e.g. browser, OS, API version, language):**
I used node v8.10.0 with request library to establish connection

**Additional context**
This is my log:
requestUrl: https://cloud-sse.iexapis.com/stable/news-stream?symbols=UDBKL,TNREF,VFWSX,UCLQF,UBMRF,TMRAY,UETTU,TVIFX,TORC,VADDX,UCON,VIGIX,TRKCY,TSFBX,TUSK,UCO,VIAB,UNPA,UPMKY,TRNO,URSSF,TRAIX,VADFX,VINIX,URGN,TSMWX,TRMIX,TOCA,TPHCX,UCSO,TSPABX,TLPC,USGBX,UGEIX,TOMI,VGMUFX,TRTN,TSSXX,VB,VAGLX,UWPSX,TMOL,TOGL,TRUHY,TMNCX,VASO,UOLGY,VGELX,UNAM,UMAM&snapshotAsOf=1563003757001&token={token}
{ symbol: 'UCO',
  datetime: 1562992817000,
  url: 'https://cloud.iexapis.com/v1/news/article/00a4fd66-4487-48ce-ad1e-3002fa087a26',
  ...
}
{ symbol: 'UCO',
  datetime: 1562992817000,
  url: 'https://cloud.iexapis.com/v1/news/article/00a4fd66-4487-48ce-ad1e-3002fa087a26',
  ...
}
{ symbol: 'UCO',
  datetime: 1562992817000,
  url: 'https://cloud.iexapis.com/v1/news/article/00a4fd66-4487-48ce-ad1e-3002fa087a26',
  ...
}
{ symbol: 'UCO',
  datetime: 1562992817000,
  url: 'https://cloud.iexapis.com/v1/news/article/00a4fd66-4487-48ce-ad1e-3002fa087a26',
  ...
}
{ symbol: 'UCO',
  datetime: 1562992817000,
  url: 'https://cloud.iexapis.com/v1/news/article/00a4fd66-4487-48ce-ad1e-3002fa087a26',
  ...
}
{ symbol: 'UCO',
  datetime: 1562992817000,
  url: 'https://cloud.iexapis.com/v1/news/article/00a4fd66-4487-48ce-ad1e-3002fa087a26',
  ...
}
{ symbol: 'UCO',
  datetime: 1562992817000,
  url: 'https://cloud.iexapis.com/v1/news/article/00a4fd66-4487-48ce-ad1e-3002fa087a26',
  ...
}

**Comment by ryandietrich-iex** [comment]
I've tried sending modified versions of the request for the last half or so.  The worst I can see is it will send back values MATCHING the snapshotAsOf time (I did not do `>=`, just `>` when I wrote the code a few months ago), but I can't get it to send older values than the one supplied.  Try making the problem smaller for a second.

Run this request:
`curl -v -s -k --header 'Accept: text/event-stream' "https://cloud-sse.iexapis.com/stable/news-stream?symbols=$SYM&token=$TOKEN&snapshotAsOf=$TS"`

Then place your request library in debug mode and see what it is sending.  I'd be curious if how the request is being made and how it may possibly differ.

To be clear, this is totally working as expected, I can't get the SSE server to send me data older than the snapshotAsOf time that I sent in.

**Comment by gcobcqwe** [comment]
@ryandietrich-iex After I tried curl -v -s --header 'Accept: text/event-stream' 'https://cloud-sse.iexapis.com/stable/news-stream?symbols=UDBKL,TNREF,VFWSX,UCLQF,UBMRF,TMRAY,UETTU,TVIFX,TORC,VADDX,UCON,VIGIX,TRKCY,TSFBX,TUSK,UCO,VIAB,UNPA,UPMKY,TRNO,URSSF,TRAIX,VADFX,VINIX,URGN,TSMWX,TRMIX,TOCA,TPHCX,UCSO,TSPABX,TLPC,USGBX,UGEIX,TOMI,VGMUFX,TRTN,TSSXX,VB,VAGLX,UWPSX,TMOL,TOGL,TRUHY,TMNCX,VASO,UOLGY,VGELX,UNAM,UMAM&token={token}&snapshotAsOf=1563378900000'

It look like some symbols(VIAB, UCO) will return older data. 

*   Trying 104.197.97.64...
* TCP_NODELAY set
* Connected to cloud-sse.iexapis.com (104.197.97.64) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.iexapis.com
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> GET /stable/news-stream?symbols=UDBKL,TNREF,VFWSX,UCLQF,UBMRF,TMRAY,UETTU,TVIFX,TORC,VADDX,UCON,VIGIX,TRKCY,TSFBX,TUSK,UCO,VIAB,UNPA,UPMKY,TRNO,URSSF,TRAIX,VADFX,VINIX,URGN,TSMWX,TRMIX,TOCA,TPHCX,UCSO,TSPABX,TLPC,USGBX,UGEIX,TOMI,VGMUFX,TRTN,TSSXX,VB,VAGLX,UWPSX,TMOL,TOGL,TRUHY,TMNCX,VASO,UOLGY,VGELX,UNAM,UMAM&token={token}&snapshotAsOf=1563378900000 HTTP/1.1
> Host: cloud-sse.iexapis.com
> User-Agent: curl/7.54.0
> Accept: text/event-stream
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 18 Jul 2019 00:45:15 GMT
< Content-Type: text/event-stream
< Connection: close
< Cache-Control: no-cache, no-transform
< Access-Control-Allow-Origin: *
< Cache-Control: no-cache
< Strict-Transport-Security: max-age=15768000
< 
data: [{"datetime":1563378900000,"headline":"CBS and Viacom could finally announce a tie-up (VIAB, CBS)","source":"Business Insider","url":"https://cloud.iexapis.com/v1/news/article/12276088-ce1e-4a62-8bb2-a9855918db8d","summary":"This is an excerpt from a story delivered exclusively to Business Insider Intelligence Digital Media Briefing subscribers. To receive the full story plus other insights each morning, click here. As we approach Q2 earnings season, CBS Corp. and Viacom have set the same reporting date — August 8 — in what apparently could double as a merger announcement, according to information obtained by CNBC. The companies have been circling a re-combination for over a year, after splitting up in 2006. The potential merger comes as the traditional media landscape consolidates for scale to better compete with the tech giants including Netflix, Apple, and Amazon that are increasingly investing in content. A quick refresher: Comcast officially acquired NBCUniversal in 2013, AT&T now owns WarnerMedia, and Disney is now integrating the majority of 21st Century Fox assets. Now that CBS CEO Les Moonves — who had previously resisted the merger — has been ousted, the merger appears more likely to proceed. The content possibilities for the combined company are vast, and that strength would allow a combined entity to better compete as cord-cutting steadily worsens and the streaming wars reach their peak.","related":"VIA,VIAB","image":"https://cloud.iexapis.com/v1/news/image/12276088-ce1e-4a62-8bb2-a9855918db8d","lang":"en","hasPaywall":false,"symbol":"VIAB"}]

data: [{"datetime":1563327934000,"headline":"Australian watchdog says Uber Eats will amend \"unfair\" contract terms","source":"Reuters","url":"https://cloud.iexapis.com/v1/news/article/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","summary":"Australia's competition watchdog said Uber Technologies Inc's food delivery service Uber Eats will amend its contract terms to accept more accountability for delivery issues, easing the burden on restaurants.","related":"UBER","image":"https://cloud.iexapis.com/v1/news/image/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","lang":"en","hasPaywall":false,"symbol":"UCO"}]

data: [{"datetime":1563327934000,"headline":"Australian watchdog says Uber Eats will amend \"unfair\" contract terms","source":"Reuters","url":"https://cloud.iexapis.com/v1/news/article/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","summary":"Australia's competition watchdog said Uber Technologies Inc's food delivery service Uber Eats will amend its contract terms to accept more accountability for delivery issues, easing the burden on restaurants.","related":"UBER","image":"https://cloud.iexapis.com/v1/news/image/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","lang":"en","hasPaywall":false,"symbol":"UCO"}]

data: [{"datetime":1563327934000,"headline":"Australian watchdog says Uber Eats will amend \"unfair\" contract terms","source":"Reuters","url":"https://cloud.iexapis.com/v1/news/article/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","summary":"Australia's competition watchdog said Uber Technologies Inc's food delivery service Uber Eats will amend its contract terms to accept more accountability for delivery issues, easing the burden on restaurants.","related":"UBER","image":"https://cloud.iexapis.com/v1/news/image/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","lang":"en","hasPaywall":false,"symbol":"UCO"}]

data: [{"datetime":1563327934000,"headline":"Australian watchdog says Uber Eats will amend \"unfair\" contract terms","source":"Reuters","url":"https://cloud.iexapis.com/v1/news/article/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","summary":"Australia's competition watchdog said Uber Technologies Inc's food delivery service Uber Eats will amend its contract terms to accept more accountability for delivery issues, easing the burden on restaurants.","related":"UBER","image":"https://cloud.iexapis.com/v1/news/image/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","lang":"en","hasPaywall":false,"symbol":"UCO"}]

data: [{"datetime":1563327934000,"headline":"Australian watchdog says Uber Eats will amend \"unfair\" contract terms","source":"Reuters","url":"https://cloud.iexapis.com/v1/news/article/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","summary":"Australia's competition watchdog said Uber Technologies Inc's food delivery service Uber Eats will amend its contract terms to accept more accountability for delivery issues, easing the burden on restaurants.","related":"UBER","image":"https://cloud.iexapis.com/v1/news/image/7dd3c672-5bb9-4d63-828d-76c1fc61d4dd","lang":"en","hasPaywall":false,"symbol":"UCO"}]

**Comment by ryandietrich-iex** [comment]
I haven't had time to look into this again, but based on what you're seeing I have a thought that I need to look into later.  The concept of "snapshotAsOf" pertains to not sending data to the client that is stored in our "snapshot cache" when a connection is made.  It has nothing to do with subsequent messages that come in after the snapshot is/isn't sent.  It is prohibitively expensive to do per-connection timestamp filtering (or based on other filters sadly) for everyone, but it may be possible to do it based on the subscription tier.  This is conjecture on my part, and would need to be approved.
