### ISSUE TITLE
Can't connect to both website and API.

### ISSUE THREAD

**Issue by mik3y64** [iexg/IEX-API#1115]
Please see the error messages below. Can't access to both https://iexcloud.io/ and API. No issues on any other websites or internet access. 

Windows' troubleshooting: "Your computer appears to be correctly configured but the device or resource (iexcloud.io) is not responding. Windows can't communicate with the device or resource (iexcloud.io). The computer or service you are trying to reach might be temporarily  unavailable"

I even tried soutions on Youtube (https://www.youtube.com/watch?v=RBwtQEWt6L0) but no help.

Please kindly advise on the issues. Thank you.

This site can’t be reached iexcloud.io took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Comment by erichodges** [comment]
This has happened to me a few times and is happening right now.

**Comment by evancarter-iex** [comment]
The site is up and running with lots of requests coming in. Unfortunately, without more information I cant be much help here.

**Comment by mik3y64** [comment]
Why did you close this issue without providing any information? What information do you need for you to diagnose the problem?

**Comment by evancarter-iex** [comment]
@mik3y64 The only thing that would be helpful would be an ip address. Are you able to access https://cloud.iexapis.com/ ?
