### ISSUE TITLE
Please differentiate between stocks and mutual funds

### ISSUE THREAD

**Issue by JPayne3** [iexg/IEX-API#1118]
I like to keep up-to-date data on about 10,000 stocks.    When I use an endpoint with /stock/market/previous   and no list of symbols, I get tons of data. THE MAJORITY OF WHICH IS MUTUAL FUNDS.  (The cost is 137K messages!)

I would like the word STOCK to mean .... stocks ...  and NOT mutual funds.

My current way of dealing with this problem is to break up my list of stocks into 100 symbol blocks and download and download next etc.

**Comment by xunamcapital** [comment]
This is what I do, I iterate through my saved symbols and manually request all of them.

It does not seem very reasonable that for /stock/market/previous IEX sends way more instruments back than they have in their /ref-data/symbols API.
