### ISSUE TITLE
Inconsistent Boolean value in response

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#112]
## Summary

Boolean value is inconsistent among response messages. For some messages boolean is sent as a text value "false" or "true" and for other messages they are sent as a number value 0 or 1.

### Date/time of issue

2017-11-24

### API URL

https://iextrading.com/developer/docs/#recent
https://iextrading.com/developer/docs/#historical-daily

### What you expected to happen

I expect to have for all message consistent boolean value. 

### What actually happened

For some of message we receive:

* "true"/"false"

for others:

* 0/1

### Other Information (sample code, links, etc.)

Historical Daily:

```json
{
    "date": "2017-05-09",
    "volume": 152907569,
    "routedVolume": 46943802,
    "marketShare": 0.02246,
    "isHalfday": 0,
    "litVolume": 35426666
}
```

Recent stats:

```json
  {
    "date": "2017-01-11",
    "volume": 128048723,
    "routedVolume": 38314207,
    "marketShare": 0.01769,
    "isHalfday": false,
    "litVolume": 30520534
  }
```

**Comment by timpaine-iex** [comment]
closing as stale
