### ISSUE TITLE
[Issue] IEX news returns invalid 404 urls pointing to IEX servers

### ISSUE THREAD

**Issue by mikezliu** [iexg/IEX-API#1120]
**Clearly describe the problem**

When streaming news, IEX is returning urls that are invalid (404). The url is cached by IEX and doesn't redirect to an external website so this is an IEX issue.

For example, this returns 404 without redirection:
https://cloud.iexapis.com/v1/news/article/c081751a-2d3d-4122-ac07-4793a72b7d1f

**What time did the problem occur? (with timezone)**

July 15 11PM EDT, ongoing

**What is the expected behavior?**

404 urls should not be returned by IEX

The url is cached by IEX servers and does not redirect to an external website, so this is an IEX issue. If the external site goes down, that's a different issue.

**Your environment (e.g. browser, OS, API version, language):**

IEX Cloud stable

**API URL (if applicable)**

https://cloud-sse.iexapis.com/stable/news-stream?symbols=UDBKL,TNREF,VFWSX,UCLQF,UBMRF,TMRAY,UETTU,TVIFX,TORC,VADDX,UCON,VIGIX,TRKCY,TSFBX,TUSK,UCO,VIAB,UNPA,UPMKY,TRNO,URSSF,TRAIX,VADFX,VINIX,URGN,TSMWX,TRMIX,TOCA,TPHCX,UCSO,TSPABX,TLPC,USGBX,UGEIX,TOMI,VGMUFX,TRTN,TSSXX,VB,VAGLX,UWPSX,TMOL,TOGL,TRUHY,TMNCX,VASO,UOLGY,VGELX,UNAM,UMAM&token={token}

**What are the steps to reproduce the bug?**

Stream the API url

**Additional context**

**Comment by joshuablackburn-iex** [comment]
We are just proxying the news article. If it is returning 404, then the source article is no longer available.

**Comment by mikezliu** [comment]
The 404 comes from IEX servers before redirect happens. If it's proxying the news article shouldn't the 404 come from the publisher website?
