### ISSUE TITLE
Receiving "Revocation information for the security certificate for this site is not available" warning 

### ISSUE THREAD

**Issue by wbhern** [iexg/IEX-API#1122]
Starting within the last week, I've begun to receive a "Revocation information for the security certificate for this site is not available" warning when launching the Excel VBA macro I built to utilize the IEX API. I've not changed anything from a code standpoint, and once the warning is received and clicked through, everything works per usual. Has any change occurred on the server side that might have caused this? I've checked the server cert and it looks OK to my very uncritical eye -- it hasn't expired, anyway -- and it's not a time sync problem on my client. Not a raging garbage fire, but a bit of a nuisance, as it takes about 30-45 seconds for the warning to pop up before I can click through to run the intended queries.

Latest instance was approximately 10 minutes ago, at 23:30 US CDT.

Expected behavior is to not be warned about a certificate issue.

I'm running a current/patched/up-to-date version of Windows 10 on a Surface Pro 6 with 8 GB RAM; the API is being accessed through a VBA macro in Excel issuing the requests.

**Comment by evancarter-iex** [comment]
Hi there,

is this still an issue?

**Comment by timpaine-iex** [comment]
closing as stale
