### ISSUE TITLE
Stock price not available to free tier

### ISSUE THREAD

**Issue by wstrege** [iexg/IEX-API#1125]
Calling https://cloud.iexapis.com/stable/stock/aapl/price?token=__MyToken__ receives a response of "The requested data is not available to free tier accounts. Please upgrade for access to this data."

The problem occurred 7/17/2019 9:54am CDT

The price of the stock is expected to be returned.

Chrome browser, windows.

Thanks for all assistance.

**Comment by evancarter-iex** [comment]
@wstrege We sent an email about this to all users several days ago. Unfortunately, this is due to a vendor policy change.

**Comment by wstrege** [comment]
Crud, thanks.

**Comment by evancarter-iex** [comment]
@wstrege Yeah we arent happy about it either

**Comment by jzstoller** [comment]
I can't find the email. Is this announcement/email posted on the website somewhere? It would be useful to know what API calls were affected. Thanks.

**Comment by kwandrews7** [comment]
@jzstoller 

I landed on this issue trying to track down a problem with null values and went and dug up the email. It's attached below if anyone else needs it.

[Gmail - Updates to IEX Cloud.pdf](https://github.com/iexg/IEX-API/files/3419237/Gmail.-.Updates.to.IEX.Cloud.pdf)

**Comment by liuyigh** [comment]
So the free plan is really limited ...
