### ISSUE TITLE
[Needs: documentation] Documentation of free tier changes in changelog or on website

### ISSUE THREAD

**Issue by jzstoller** [iexg/IEX-API#1126]
In #1125, @evancarter-iex mentioned an email had been sent out about changes to the free tier that now result in a response of "The requested data is not available to free tier accounts. Please upgrade for access to this data."

Today I noticed this with OHLC.

I didn't see anything in the [changelog](https://iexcloud.io/docs/api/#changelog) or elsewhere on IEX Cloud website.

Can these changes be added to the changelog? What API calls are affected?

Thanks

**Comment by evancarter-iex** [comment]
@jzstoller Yeah we are in the process of doing that. Thanks for the reminder. Just for your knowledge its:

"Quote”
“OHLC”
“Intraday Prices”
"Volume by Venue"
"Market Volume"

**Comment by jzstoller** [comment]
@evancarter-iex Thanks for the clarification. 

Are some or all of these limited only during trading hours? or at all times?

Thanks

**Comment by evancarter-iex** [comment]
@jzstoller Unfortunately all times, but you can use historical prices to get the open/close if you stay in free (note they come in later in the evening)

**Comment by erichodges** [comment]
I can't even test sandbox quotes? Your website seems to be down also.

**Comment by evancarter-iex** [comment]
@erichodges Sandbox /quote works fine and the website is up.

**Comment by erichodges** [comment]
If I hit "CompanyDetails" looking for the closing price and I get null, then this is an issue with the new pricing?

**Comment by evancarter-iex** [comment]
@erichodges companyDetails?

**Comment by erichodges** [comment]
I'm trying to figure out where I'm getting an error...I think it's on Quote and I'm using the sandbox...looking into it.

**Comment by erichodges** [comment]
Ok, yeah if I hit the sandbox using Quote, open, openTime, close, closeTime, high, low are all null. This breaks my app at the moment.

**Comment by evancarter-iex** [comment]
@erichodges Ill look into adding back dummy data into sandbox

**Comment by erichodges** [comment]
Ok, thank you.

**Comment by kwandrews7** [comment]
@evancarter-iex I landed here tracking down `null` on high and low on `/quote`. So these values are no longer going to be available for free? Is `week52low` and `week52high` going to eventually become null as well?

Also, in case anyone in the future lands here looking for the email in question.
[Gmail - Updates to IEX Cloud.pdf](https://github.com/iexg/IEX-API/files/3419237/Gmail.-.Updates.to.IEX.Cloud.pdf)
