### ISSUE TITLE
[Data]Got an authentication problem all of a sudden

### ISSUE THREAD

**Issue by JustinLin88** [iexg/IEX-API#1127]
**Clearly describe the data problem**
Today when I tried to download the stock data  using the API (python) , I got this auth error:
IEXAuthenticationError: The query could not be completed. There was a client-side error with your request.

**Data URL (The URL you used to access the data without your token):**
I used the python API. The line to grab the data for a stock is 
stock = Stock(symbol, token="mytoken")
But it stopped working today. The toke is the same, and no code changed.
Do I need to upgrade the tier?

**What time did the problem occur (including timezone)?**
7pm PST in the U.S

**What is the expected behavior?**
It worked yesterday, with the same token. 

**What are the steps to reproduce**
I tried to generate a new token. But the problem persisted. 

**Your environment (e.g. browser, OS, API version, language):**
Windows 

**Additional context**

**Comment by evancarter-iex** [comment]
@JustinLin88 Sounds like something is going on with the library. Which library are you using?

**Comment by JustinLin88** [comment]
> @JustinLin88 Sounds like something is going on with the library. Which library are you using?

I used the iexfinance library for python. I tried to use the get_ohlc() function to get latest stock price of a stock , and I got that auth error. Some other functions worked fine, as I tested them, and I could use get_historical_prices() function to get the latest stock prices and volume, but it costs more data quota.
Did you guys just remove the get_ohlc() and get_volume() functions ?

**Comment by JustinLin88** [comment]
Also, Is there any way I can just get the latest day's ohlc prices of a stock using the get_historical_prices() function? Looks like there is param, range, to control the time span, but when I tried to change it from range='1m' ,which is the default, to range='1d', I got the same auth error.

**Comment by evancarter-iex** [comment]
Yeah OHLC was changed due to the NASDAQ data issue.

Unfortunately, I cant comment on the get_historical_prices because that's dependent on how the library is designed, but free should still have access to that. You will have to take it up the person who wrote the library
