### ISSUE TITLE
i am suddenly getting "The requested data is not available to free tier accounts." message for OHLC. i thought this API was open to free tier

### ISSUE THREAD

**Issue by munishar** [iexg/IEX-API#1129]
**Clearly describe the data problem**

**Data URL (The URL you used to access the data without your token):**

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
@munishar Please refer to the email we sent out earlier this week regarding NASDAQ's data policy.

**Comment by munishar** [comment]
Data URL (The URL you used to access the data without your token):
https://cloud.iexapis.com/v1/stock/aapl/ohlc?token=<my token>
What time did the problem occur (including timezone)?
7/17
What is the expected behavior?
I have not seen any communication that suddenly OHLC is not available. 
What are the steps to reproduce?
use the above API call for free tier account
Your environment (e.g. browser, OS, API version, language):
chrome
Additional context

**Comment by munishar** [comment]
> @munishar Please refer to the email we sent out earlier this week regarding NASDAQ's data policy.

Thank you. I understand it now. What is the best way to pull today's OHLC data after market close?

**Comment by evancarter-iex** [comment]
@munishar /previous should give you what you need but thats updated after 11pm ET.

**Comment by munishar** [comment]
perfect. that would do for now. you guys are doing a great job. 
It would be convenient if something is available at the end of the day that is intuitive like OHLC or eodToday and conveys just today's OHLC around 9:00 PM ET.  I am very grateful to you for the prompt response and help.

**Comment by evancarter-iex** [comment]
@munishar Yeah, we hear you. We will work on getting it moved up even sooner.
