### ISSUE TITLE
Mysterious field in Dividends

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#113]
## Summary

In Dividends there are 2 mysterious fields. They are not listed in the description, but also most of the time if not all of the time they come empty:

* flag 
* indicated

### Date/time of issue

2017-11-17

### API URL

https://iextrading.com/developer/docs/#dividends

### What you expected to happen

I expected to receive only fields listed in the description. I also expected to have some values there.

### What actually happened

I received 2 additional fields not listed in the description. They are empty strings all of the time.

**Comment by michel-barakat** [comment]
+1 on this issue

I have seen some dividends showing a flag key with values such as SP, EX, FI, SU. Some of these dividend payments have an empty amount as well.

Examples:
https://api.iextrading.com/1.0/stock/RSX/dividends/1y
https://api.iextrading.com/1.0/stock/FXB/dividends/1y

What does the flag key indicate?

**Comment by bstruck** [comment]
I would also like to know what this is. 
Here's what I have so far:
I've figured out that SP = special dividend. 
EX seems to be heavy with foreign stocks/etfs and muni related stuff. I would assume this means exempt, but it also has a special div from CME listed as EX...
FI no clue what this is.
SU no clue, but the amount seems to be "" on these.
