### ISSUE TITLE
open, openTime, close, closeTime, etc. All NULL

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#1132]
**Clearly describe the problem**
For the last two days, open, openTime, close, closeTime, high, low are all null for equities and ETFs. The only current information is being returned for mutual funds, which don't report those fields regardless.

**What time did the problem occur? (with timezone)**
Latest attempt was at 08:33 Eastern, though attempts have been made at different times during the day

**What is the expected behavior?**
When query is run after trading close, fields should contain values from the last trading session

**Your environment (e.g. browser, OS, API version, language):**
Chrome, MacOS/Windows/Unix, v1, PHP

**API URL (if applicable)**
https://cloud.iexapis.com/V1/stock/market/batch?types=quote,dividends&symbols=ainv,o, aceix&token=MY_KEY

**What are the steps to reproduce the bug?**
The API has been executed both on served pages and within an API-testing environment.

[2019-07-19 Sample Dailies.txt](https://github.com/iexg/IEX-API/files/3411108/2019-07-19.Sample.Dailies.txt)

**Additional context**
Please note that the listed call only includes 3 symbols, the issue affects all 200+ symbols I currently track.

**Comment by evancarter-iex** [comment]
@GraceRg Per our email earlier in the week, due to NASDAQ's data policy, we are unable to provide high/low except to people who are paid users and have a contract with NASDAQ/UTP.  If you just need high/low at end of the day /previous updates at around 11pm every night.

**Comment by rosswinters** [comment]
OK what about quote endpoint stats for open, close, marketcap, volume. These have quite working recently too. As in: https://cloud.iexapis.com/stable/stock/dwin/quote?token=pk_3e454c7415a64ceca50772b8dde970d2

It's difficult for me to develop applications and trust your data when it keeps changing or drops out arbitrarily.
