### ISSUE TITLE
[Issue] Access changes for Start accounts 

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#1135]
**Clearly describe the problem**

Have the available endpoints for free-tier (Start) accounts changed? Per the documentation below, equities data is available for this tier:

<img width="288" alt="Screen Shot 2019-07-19 at 9 13 10 PM" src="https://user-images.githubusercontent.com/21162161/61572345-0b0a7200-aa6a-11e9-89c1-3397fa2f8b1b.png">

But the below is received:

> The requested data is not available to free tier accounts. Please upgrade for access to this data.

**What time did the problem occur? (with timezone)**

7/19/19 9:30pm EST

**What is the expected behavior?**

**Your environment (e.g. browser, OS, API version, language):**

V1 and Sandbox

**API URL (if applicable)**

**What are the steps to reproduce the bug?**

https://cloud.iexapis.com/v1/stock/AAPL/price?token=

https://cloud.iexapis.com/v1/stock/AAPL/chart/1d?token=

**Additional context**

Both calls above are fine with a **launch** account. If the endpoints have changed, documentation would be helpful (I didn't see updates to the changelog). Thank you!

**Comment by tsnethen** [comment]
I'm having the same issue. It was working on 7/16/2019, but is no longer working. I've only used 102,970 messages in July, so well below the 500k cap. 
![IEXCloud-1](https://user-images.githubusercontent.com/48545042/61655668-e1bd3200-ac73-11e9-9c90-e6fe9aafeb59.png)
![IEXCloud-2](https://user-images.githubusercontent.com/48545042/61655674-e681e600-ac73-11e9-86d3-ffcda302761d.png)

**Comment by addisonlynch** [comment]
@evancarter-iex can you review when you have a minute? This is causing breaking changes in many downstream libraries.

**Comment by evancarter-iex** [comment]
@addisonlynch We just sent a followup email with additional information.
