### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by srivastavafts** [iexg/IEX-API#1136]
**Clearly describe the data problem**
EOD Option closing prices are incorrect.  For example, symbol SPY, the option ID
SPY20191220C00300000 maturing on 20191220 has a closingPrice of 10.41
The CBOE delayed quote shows a closing price of 9.61, as does Yahoo finance at the URL
https://finance.yahoo.com/quote/SPY/options?date=1576800000
[IEXOptionChain_SPY_201912.txt](https://github.com/iexg/IEX-API/files/3413765/IEXOptionChain_SPY_201912.txt)

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/SPY/options/201912?token=

**What time did the problem occur (including timezone)?**
11:43am EST on 7/20/2019

**What is the expected behavior?**
The end of day closing price for the above option of 9.61

**What are the steps to reproduce**
Download the option chain:
https://cloud.iexapis.com/stable/stock/SPY/options/201912?token=
Compare it to the CBOE delayed quotes or the Yahoo URL above.

**Your environment (e.g. browser, OS, API version, language):**
C#, Windows 10.  Reproduced on Firefox

**Additional context**
The July 19 EOD prices did not update until sometime after 9am on July 20.

**Comment by evancarter-iex** [comment]
This has been cleaned up and shouldnt be an issue a while ago.
