### ISSUE TITLE
Missing Elements in chart response

### ISSUE THREAD

**Issue by MSeneadza** [iexg/IEX-API#114]
## Summary
First, thanks for the awesome API!

In some cases some elements (open, high and low) are missing from the prices in the stocks-chart endpoint.  Is it possible to always output those elements, even if they're empty/null

### API URL
https://api.iextrading.com/1.0/stock/zom/chart/1y

### What you expected to happen

I expected the open, high and low to be present for every day's prices.

### What actually happened

the open, high and low are missing for some days.  See 2017-01-23 and 2017-02-08

**Comment by SeamusBoyle** [comment]
For both the dates (2017-01-23 and 2017-02-08) the change value is zero, so the missing values; open maybe high and low, are all equal too close. If this is the case it should just be documented or the API could fill in the values correctly, preferably the later as all these edge cases slow down and complicate client code.

I don't like the idea of using null values for missing data when the fact that something is missing already means it is null.

**Comment by joshuablackburn-iex** [comment]
#47

**Comment by ModelsRUs** [comment]
Re missing data, I've also noticed that Chart requests using Webservice (Excel) filters, and retrieved with csv format fail to return more than 1 month of data, even when specifying other periods - e.g., 3m, 6m, 1y, 2y.
Example: WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart?filter=date,open,high,low,close/6m?format=csv") only returns 1 month of data.

**Comment by joshuablackburn-iex** [comment]
If you refer to our documentation, https://iextrading.com/developer/docs/#chart, you can see examples of how to call a 6 month chart.  The URL you are using is malformed.  The proper format for the URL is https://api.iextrading.com/1.0/stock/T/chart?filter=date,open,high,low,close/6m?format=csv

**Comment by ModelsRUs** [comment]
Thank you for the response, Josh.
Apologies for the trouble and inconvenience - I'm using formulas in my 
worksheet and must have transcribed incorrectly in my email, but the 
formula is correct, and the issue still exists. Please see attached 
workbook - the formula is in $A$1.
=WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart?filter=date,open,high,low,close/*6*m?format=csv 
<https://api.iextrading.com/1.0/stock/T/chart?filter=date,open,high,low,close/6m?format=csv>") 
only returns *1* month of data.

I've replicated the issue with time periods of 3m, 1y, and 2y.

Regards,
- *Paul*
   (917) 476-4468
===================================================================

**Comment by jcape** [comment]
@ModelsRUs The problem is the request URL is malformed, you need to have format and filter together, separated by an "&". For reference, the way a URL works is like this:

```
https://api.iextrading.com/1.0/stock/T/chart/6m?format=csv&filter=date,open,high,low,close
<protocol>://<server>/<path>?<search>
```

So in this case:

```
protocol = https
server = api.iextrading.com
path = "1.0/stock/T/chart/6m"
search = "format=csv&filter=date,open,high,low,close"
  format = csv
  filter = [ date, open, high, low, close ]
```

The URL you're giving https://api.iextrading.com/1.0/stock/T/chart?filter=date,open,high,low,close/6m?format=csv will get evaluated like this:

```
protocol = https
server = api.iextrading.com
path="1.0/stock/T/chart" (i.e. the 1m endpoint)
search = "filter=date,open,high,low,close/6m?format=csv"
  filter = [ date, open, high, low, close/6m?format=csv ]
```
