### ISSUE TITLE
[Data] Key Stats data unreliable/incorrect

### ISSUE THREAD

**Issue by ckz8780** [iexg/IEX-API#1140]
**Clearly describe the data problem**
The key stats endpoint seems to provide incorrect/unreliable data. Sometimes data is missing entirely, shows 0 when it should clearly have a value, or is very obviously incorrect (e.g. AAPL float of 6.55 million shares currently)

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/aapl/stats?token=xxx

**What time did the problem occur (including timezone)?**
07/23/2019, 10:53AM EST

**What is the expected behavior?**
Key stats data should be correct, but it is not. Recently the float was missing entirely for various symbols but currently it is there but incorrect: 

- **AAPL (shows float of 6.55M vs actual of ~4.60B shares):** 
```
{
   "week52change":0.08146800000000001,
   "week52high":233.47,
   "week52low":142,
   "marketcap":953435797600,
   "employees":132000,
   "day200MovingAvg":187.19,
   "day50MovingAvg":193.44,
   "float":6551937.92000046,
   "avg10Volume":18597329.3,
   "avg30Volume":21502068.23,
   "ttmEPS":11.99,
   "ttmDividendRate":2.92,
   "companyName":"Apple, Inc.",
   "sharesOutstanding":4601080000,
   "maxChangePercent":205.130117,
   "year5ChangePercent":1.463761,
   "year2ChangePercent":0.362525,
   "year1ChangePercent":0.081468,
   "ytdChangePercent":0.312183,
   "month6ChangePercent":0.346284,
   "month3ChangePercent":-0.001253,
   "month1ChangePercent":0.043509,
   "day30ChangePercent":0.07602,
   "day5ChangePercent":0.013301,
   "nextDividendDate":null,
   "dividendYield":0.014091303928192259,
   "nextEarningsDate":"2019-07-30",
   "exDividendDate":"2019-05-10",
   "peRatio":17.35,
   "beta":1.5205464758066647
}
```

- **MSFT (shows float of 116.99M vs actual of ~7.56B shares):** 
```
{
   "week52change":0.282115,
   "week52high":140.67,
   "week52low":93.96,
   "marketcap":1058020490000,
   "employees":null,
   "day200MovingAvg":116.15,
   "day50MovingAvg":131.82,
   "float":116999044,
   "avg10Volume":24989260.5,
   "avg30Volume":23234075.37,
   "ttmEPS":5.11,
   "ttmDividendRate":1.84,
   "companyName":"Microsoft Corp.",
   "sharesOutstanding":7662820000,
   "maxChangePercent":4.262834,
   "year5ChangePercent":2.250476,
   "year2ChangePercent":0.858863,
   "year1ChangePercent":0.282115,
   "ytdChangePercent":0.368968,
   "month6ChangePercent":0.297254,
   "month3ChangePercent":0.103555,
   "month1ChangePercent":0.004718,
   "day30ChangePercent":0.043967,
   "day5ChangePercent":0.009848,
   "nextDividendDate":"2019-08-14",
   "dividendYield":0.013291916492089864,
   "nextEarningsDate":"2019-10-24",
   "exDividendDate":"2019-08-14",
   "peRatio":27.16,
   "beta":1.4179671783781507
}
```

**What are the steps to reproduce**
Query a company on the `stats` endpoint

**Your environment (e.g. browser, OS, API version, language):**
- Chrome 75.0.3770.90 (Official Build) (64-bit)
- Ubuntu 18.04
- Kernel 4.18.0-25-generic

**Additional context**
This has been an ongoing issue on multiple endpoints but this is just the latest. As a paying customer on the IEX Grow plan it's quite annoying that the data is so unreliable. [This issue](https://github.com/iexg/IEX-API/issues/834) (#834) was closed and never truly resolved and I still have to get backup data from other sources for top gainers/losers since they will randomly disappear or be out of order, incorrect, missing, etc. Also, this same `stats` endpoint has shown incorrect EPS but was supposedly resolved in [this issue](https://github.com/iexg/IEX-API/issues/398) (#398). 

It seems to be an issue across the platform and it hurts the credibility of our sites that are using the data when we display IEX data and it says that AAPL has 655% short interest due to the float coming back from the API as 6.55 million shares :) Can we get a serious look into this and try to work on getting the data to be a bit more reliable? This platform has **so much potential** but it's not worth paying for without reliable data. 

Thank you!!

**Comment by jesseorosz** [comment]
I'm there with you. It has HUGE potential but it's just not reliable enough. I spend more time doing QA on the data than actually using it.

What vendor supplies the key stats data?

**Comment by evancarter-iex** [comment]
@ckz8780 We have been spending some time working on some of these issues. Gainers?losers still a problem? What else?

**Comment by ckz8780** [comment]
Hi @evancarter-iex 

It's tough to say what is still a problem at this point since I've resorted to using primarily my backup data provider for top gainers, top losers, and float/short interest. I've noticed that the "most active" list sometimes only displays one or two items (particularly outside normal market hours, like after hours when people might be checking to see what the most active tickers of the day were, which is a problem for obvious reasons), and I've seen the same for top gainers and losers, and most recently this issue w/ float and various key stats being missing or incorrect. If you could focus your efforts on making sure the daily lists (gainers, losers, most active, sector performance, etc) and the key stats endpoints are providing reliably correct data that would be a huge improvement. 

Thanks again and let me know if you want me to test anything out as you're making updates! 

Cheers

**Comment by evancarter-iex** [comment]
@ckz8780 Could you email at support@iexcloud.io. Id like to take this offline so we can figure out whats going on here with the most active

**Comment by evancarter-iex** [comment]
Closing this. Please reach out to support@iexcloud.io if you see additional issues.

**Comment by joshuablackburn-iex** [comment]
The data is accurate and representative of the IEX book only. If there are no bud or asks on the inside, then what you see is the next available price. Some market makers may have prices booked way outside the latest price, and if they are no other lit orders, you'll see what you described as a "crazy" price. When the price is 0, that means there are no lit orders on that side of the book.

**Comment by DataSoftSystem** [comment]
> The data is accurate and representative of the IEX book only. If there are no bud or asks on the inside, then what you see is the next available price. Some market makers may have prices booked way outside the latest price, and if they are no other lit orders, you'll see what you described as a "crazy" price. When the price is 0, that means there are no lit orders on that side of the book.

i am dev a windows application to simulate the trades using real time data. i need bids and asks for level 2 , trades data for times and sale  and price/bid/ask data for transactions.... what is the best rout in your opinion? thank you for your prompt reply
