### ISSUE TITLE
OHLC endpoint going away as of 7/31/19?

### ISSUE THREAD

**Issue by ggarrisonsr** [iexg/IEX-API#1141]
**Clearly describe the data problem**
Just received the email on provider data changes (7/23/19) - "Important update: Data for Nasdaq-listed stocks on IEX Cloud"

**Data URL (The URL you used to access the data without your token):**
GET /stock/{symbol}/ohlc

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**
It appears this email is saying that HLOC will no longer be available. Moving forward, how do we get a simple HLOCV (High, Low, Open, Close, Volume) intraday?

**Comment by lgellert** [comment]
IEX is passing the cost on to its users to access this particular type of data. This is outrageous. How did this not get caught during the beta? This is going to cause a lot of problems for anybody that integrates with IEX.  Why not add extra API call cost for these symbols instead of force individual accounts to deal with all the red tape?

Can IEX do its own calculations to provide unofficial values for the NASDQA symbols?

Excerpts from email:

```
To be clear, IEX Cloud will continue to provide non-delayed intraday data for all stocks when those quotes and trades occur on the Investors Exchange. That’s a lot of data! But you will notice that, for Nasdaq-listed stocks only, some key points, such as the official opening and closing price, as well as pre- and post-market prices (before 9:30 am ET and after 4:00 pm ET), will be missing. 
```

```
If you’d like to get authorization to receive this data through IEX Cloud or any other data vendor (Nasdaq UTP's policy applies to all redistributors of Nasdaq UTP data) you’ll need to fill out Nasdaq UTP’s forms and pay the applicable fees, which start at $250 per year (additional Nasdaq UTP fees may apply). 
```

```
Affected endpoints for Nasdaq-listed symbols ONLY 

    "Quote”: open, openTime, close, closeTime, delayedPrice, delayedPriceTime,extendedPrice, extendedPriceTime, extendedChange, extendedChangePercent, week52High, week52Low, high, low fields will be null.  
    “Quote”: latestPrice, latestUpdate, latestTime, latestSource, change, changePercent, marketCap, ytdChange will no longer incorporate Nasdaq UTP data but will continue to use Investors Exchange data.  
    “OHLC”: all fields will be null.  
    “Intraday Prices”: all fields prefixed with “market” will be null. 

```

**Comment by erichodges** [comment]
Why is the sandbox data being blocked as well?

**Comment by ggarrisonsr** [comment]
This is just getting worse and worse. I'm fine with paying. I just don't like deception. Any basic chart needs HLOC and V (olume). To get this I used the OHLC. But if time is intraday then the C(lose) value is previous day. So I am then required to make a call to the Quote API. The OHLC api costs 2 points. This is bad enough. But then I have to pay an extra point for the Quote API. If the Quote response is IEX data I should not have to pay, but often it is not, especially if the security is smaller volume. Speaking of Volume:  The Volume value requires a call to the Quote API as well. The Volume is suspect because it always seems low compared to the ThinkOrSwim volume. This is true even when the volume is not IEX volume. Regardless, I just need HLOCV for a basic chart. Shouldn't be that difficult. So by Nulling the OHLC fields how do I get a simple HLOCV throughout the day to make a simple chart, and how much is this going to cost me. 
I can appreciate IEX Trading and their origins but cloud project is becoming a nightmare for my application and time.

**Comment by erichodges** [comment]
I'm in the same boat as ggarrisonsr. I'm wondering what is the value in working with IEX for my portfolio project that will be seen by maybe 50 people.

**Comment by joshuablackburn-iex** [comment]
Our goal is to make data as accessible as possible. Our IEX data is available for free and is unlimited use. As you know, we also provide data from many other sources, and therefore do not own the rights to that data. Nasdaq policy requires this change and they are the sole owner of this data. They dictate the price and have the ability to charge anyone that does not abide by their policy. They have stated each user needs to have a **direct** contract with them. There isn't even a chance to pass through fees. This fee applies to **everyone** they feel provides a feed of their data.

I understand everyones frustration. Unfortunately, Nasdaq is the only source of this data. We continue to fight for the everyday investor.

https://uk.reuters.com/article/us-iexgroup-data/iex-slams-egregious-market-data-fees-at-other-u-s-exchanges-idUKKCN1PN2SD

**Comment by lgellert** [comment]
> Our goal is to make data as accessible as possible. 

If NASDAQ symbols trade on IEX, would it be possible to create a version of OHLC based on IEX trades? Or does that violate some licensing agreement already in place?  Seems like as developers we could obtain similar data through the chart API but it is a huge pain and adds overhead on both sides.

**Comment by ggarrisonsr** [comment]
Thanks for the response Joshua. That I think we all get what's going on.  But that article is from January 2019. The cloud service and pricing began in May? June? Why wasn't all this figured in the pricing and data feeds before release? I really don't even want an answer to that question. I just need HLOCV. Like lgellert said, how do we get this data?

**Comment by joshuablackburn-iex** [comment]
We still provide OHLCV for over 5000 stocks. Only Nasdaq listed stocks were impacted. If you'd like to continue receiving this data, Nasdaq requires you to pay them $250 per year to access it **from anywhere**.

**Comment by ggarrisonsr** [comment]
Joshua - are you saying the OHLC endpoint will not have null values as long as the security can be obtained from an alternate exchange (not nasdaq)? Even besides the IEX Trading Exchange? I ask this because the email makes it look like this endpoint is going away.

**Comment by joshuablackburn-iex** [comment]
The email states that everything applies to Nasdaq listed stocks **only** OHLC are all values that can only come from Nasdaq. Trades can occur on any exchange, so we will continue to provide non Nasdaq trades.

**Comment by ggarrisonsr** [comment]
This is a lot of "Office Speak". Talking around the issue. What you are saying is the OHLC endpoint values only come from nasdaq so this endpoint becomes useless. Given that what combination of endpoints do we need to get a High/Low/Open/(current close) and (current) Volume to make a simple bar chart? I need to know this. My application is on the web. I need to know what to do moving forward.

**Comment by joshuablackburn-iex** [comment]
You will need to follow the instructions we laid out in the email.

**Comment by ggarrisonsr** [comment]
Joshua not lying about the greedy nasdaq. Intrino data feeds notes.
Professionals are billed an additional $250 one-time fee directly by the exchange.
Startups and Enterprises with an internal-use license are billed an additional $250 per year directly by the exchange.
Startups and Enterprises with a display-use license are billed an additional $250 per month directly by the exchange.

**Comment by cgailey** [comment]
@joshuablackburn-iex does this also affect the 'previous' endpoint for NASDAQ stocks?

**Comment by evancarter-iex** [comment]
@cgailey /previous endpoint is not affected by this

**Comment by mikezliu** [comment]
What options do we have if we already paid for a whole year?  250 extra / month to nasdaq isn’t something we budgeted for.

**Comment by mikezliu** [comment]
What options do we have if we already paid for a whole year? It seems we need to pay $250+ / month to keep using what we originally paid for. Taking away features that customers already paid for does not seem like the right thing to do. If your hands are tied then customers should have an option to get a refund (and not in future credits).

**Comment by smidwap** [comment]
Obviously not great news, but the all-in cost of IEX is still a lot less than any other data provider we've come across.

**Comment by lgellert** [comment]
The book Flash Boys by Michael Lewis first introduced me to IEX and its mission. When the IEX Cloud API came out I was really excited. It is by far the only API I've ever worked with to give me a sense of joy because of the positive change it represents.  This new NASDAQ policy screws up the pricing model for IEX and I feel sorry for them.  I imagine this was stressful for the people at IEX given this was a sudden change, well after the beta ended.  I hope IEX can continue to find ways to make all data accessible.  I'd be fine with an IEX only data source for OHLC, but reading between the lines maybe that is against whatever agreement IEX has with NASDAQ?

**Comment by scottyrotten6** [comment]
Can someone post the instructions for signing the agreement that IEX emailed? I can't find them anywhere and must have deleted them thinking it wasn't important.
