### ISSUE TITLE
[Data] - Employees Null in Key_Stats

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1142]
**Clearly describe the data problem**
Employee field for MSFT is null

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/beta/stock/msft/stats?token=

**What time did the problem occur (including timezone)?**
6AM UTC

**What is the expected behavior?**
has value

**What are the steps to reproduce**
make api call

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
This is fixed.
