### ISSUE TITLE
Quote Stock Null values

### ISSUE THREAD

**Issue by wilbertvb** [iexg/IEX-API#1143]
I got following values from the API:
"open":null,"openTime":null,"close":null,"closeTime":null,"high":null
With the test URL:

https://cloud.iexapis.com/stable/stock/aapl/quote?token=<my_token>

Null values are the same for all the other companies.
Could you help why is not returning the current values?

Best regards,
Wilbert Valverde B.

**Comment by evancarter-iex** [comment]
@wilbertvb Please refer to the emails sent regarding NASDAQ data.

**Comment by wilbertvb** [comment]
Could you sent email again?
