### ISSUE TITLE
Get Data dump of stock quotes

### ISSUE THREAD

**Issue by eddadjei** [iexg/IEX-API#1144]
Is there any way to get daily or 15min delay of all stock quotes as csv without calling the api with 100 symbol

**Comment by McQgit** [comment]
When you say "daily" does that include prior close?  If so, try:
`/stock/market/previous`

Note the weight is 2 per symbol returned so be careful.

Docs here:
[]https://iexcloud.io/docs/api/#previous-day-price

**Comment by eddadjei** [comment]
am looking at something like this /ref-data/symbols. where I dont have to pass in any symbols but get an entire quote.

**Comment by McQgit** [comment]
Yeah, the thing I linked to is pretty much an entire quote for all symbols in one call - it's just for prior day close.  I guess I'm not understanding what you need exactly.

**Comment by eddadjei** [comment]
Yes it shows but I can't control the time. Basically, I want to say "Give me all quotes for the past 15min"

**Comment by McQgit** [comment]
I don't know then.  For anyone else to help though you're going to have to clarify what you mean by "quotes".  Do you really mean "trades" in last 15 minutes?  Or, do you mean give you the most recent 15 min delayed quote for everything?

You should also clarify what you mean by "all" - is that just US exchanges or all world-wide exchanges on IEX or what?

Note there has been recent discussion about change to Nasdaq listed stocks and intraday prices won't be available for those in IEX unless you have a direct contract with Nasdaq.  See, for example:
[]https://github.com/iexg/IEX-API/issues/1141

**Comment by eddadjei** [comment]
Thanks @McQgit please bare with me as I am getting used to the API. What I meant was the trading price for all stocks (All US stocks) dump as a csv

**Comment by mikezliu** [comment]
You can use firehose for getting all stocks

**Comment by eddadjei** [comment]
I got the data using the /top however, prices are off compared to what I see on google. here is an example
{
    "symbol": "AAPL",
    "bidSize": 0,
    "bidPrice": 0,
    "askSize": 0,
    "askPrice": 0,
    "volume": 312840,
    "lastSalePrice": 207.065,
    "lastSaleSize": 300,
    "lastSaleTime": "2019-07-25T19:59:55.445Z",
    "lastUpdated": "2019-07-25T20:00:00.004Z",
    "sector": "electronictechnology",
    "securityType": "cs"
}

The last sale is 207.065 while google is showing 207.02 even though the market is close. why the price difference?

**Comment by McQgit** [comment]
Because /tops shows IEX trades only

**Comment by eddadjei** [comment]
I have looked through the documentation and was wondering if I could get the same csv dump that /tops offers but include a price that also matches the one on google
