### ISSUE TITLE
[Data] MarketCap is NULL in Quote for BABA

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1145]
**Clearly describe the data problem**
marketCap is null for at least BABA in Quote

{"symbol":"BABA","companyName":"Alibaba Group Holding Ltd.","primaryExchange":"New York Stock Exchange","calculationPrice":"close","open":178,"openTime":1563975001037,"close":178.67,"closeTime":1563998434046,"high":178.96,"low":176.938,"latestPrice":178.67,"latestSource":"Close","latestTime":"July 24, 2019","latestUpdate":1563998434046,"latestVolume":14909196,"iexRealtimePrice":178.665,"iexRealtimeSize":100,"iexLastUpdated":1563998397703,"delayedPrice":178.67,"delayedPriceTime":1563998434081,"extendedPrice":178.5,"extendedChange":-0.17,"extendedChangePercent":-0.00095,"extendedPriceTime":1564046113245,"previousClose":178.09,"previousVolume":20881546,"change":0.58,"changePercent":0.00326,"volume":0,"iexMarketPercent":0.033083474118926336,"iexVolume":493248,"avgTotalVolume":18183199,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":null,"peRatio":35.7,"week52High":198.35,"week52Low":129.77,"ytdChange":0.310283,"lastTradeTime":1563998434081}

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/baba/quote?token=

**What time did the problem occur (including timezone)?**
2:30AM PST

**What is the expected behavior?**
does not return null

**What are the steps to reproduce**
run API call

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**
It's also null in KeyStats

**Comment by evancarter-iex** [comment]
This should be fixed.
