### ISSUE TITLE
[Data] OHLC data does not match the official exchange open

### ISSUE THREAD

**Issue by aftersought** [iexg/IEX-API#1147]
**Clearly describe the data problem**
Getting one month worth of historical data of OHLC prices via the https://cloud.iexapis.com/stable/stock/AMZN/chart/1m endpoint yields 1892.48 as the "open" price for AMZN on 2019-06-26. However the official opening price for AMZN on that date was 1893.73 (unlike the first trade for the date). 

**What is the expected behavior?**
The [OHLC api](https://iexcloud.io/docs/api/#ohlc) states:
> [open] refers to the official open price. Will return 0 if symbol has no volume for the day.

and your colleague confirmed elsewhere that the official open price has to be the price of the opening auction on the primary exchange (see https://github.com/iexg/IEX-API/issues/684#issuecomment-464050906):

> ... market open and close represent the official open or close reported by the listing exchange. The historical close is reported by our partner and adjusted for corporate actions. These two prices can differ based on adjustment, and more commonly, is the result of being the first crossing trade. Since multiple exchanges have open and close cross for a symbol, some vendors (like Yahoo and Google) report that first cross rather than the official open or close. Pro trading terminals will report the official listing exchange open and close, which is the only one that matters for pricing the next day.

OHLC help redirects to `chart` functionality for historical OHLC data, so we assume it offers historical OHLC prices and should conform to the same logic. This is clearly not the case for AMZN opening price on 2019-06-26.

**Comment by evancarter-iex** [comment]
@aftersought 1,892.48 is the closing price listed on several other websites.

**Comment by aftersought** [comment]
@evancarter-iex "Several other sites" do not state that their opening price is the "official open". Depending on the policy of each source, the opening price may either come as first price after 9.30am or the opening auction price from the official exchange. They are not always the same thing! However the "official open" is by definition the opening auction from the primary exchange, so you either need to change the docs or change the functionality.

You will note I quoted your colleague who correctly identifies the issue when noting that Yahoo / Google have different opening prices from "pro trading terminals" (bloomberg, for instance).

**Comment by evancarter-iex** [comment]
@aftersought Our data for Open/Close comes from the SIP, which transmits the auction data from the listing exchange.

**Comment by aftersought** [comment]
@evancarter-iex The SIP does have indeed that infomation. I have checked the SIP feed and the correct price for AMZN on 2019-06-26 is 1893.73 not 1892.48.
