### ISSUE TITLE
No one responding on support email channel to sign UTP data agreement [Data]

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#1148]
**Clearly describe the data problem**
Email sent out indicating the UTP data issue describes contacting support@ to get instructions on how to sign your UTP agreement. No one responds on that channel, and we need to ensure we have no data interruption.

What do we do please IEX? Can someone respond in a timely fashion?

**Data URL (The URL you used to access the data without your token):**
N/A

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by joshuablackburn-iex** [comment]
The instructions are in the email we sent. We can direct you to the forms, but we are not authorized to recommend how to fill out the forms.
http://www.utpplan.com/DOC/VendorAgreement.pdf

**Comment by professorDante** [comment]
That clearly is not true at all. Here is the excerpt:

If you intend to get Nasdaq UTP approval to continue receiving the data, or if you already have a Nasdaq UTP agreement and just need to add IEX Cloud as an approved channel, please email us at support@iexcloud.io. We will do everything we can to help you avoid a disruption in the data you receive through IEX Cloud and will let you know when the forms are ready for you to fill out. 

We have an existing UTP agreement,  so what do we do pease? There is no link to fill out the forms at all.

**Comment by evancarter-iex** [comment]
@professorDante Please email support@iexcloud.io and I will take care of it.

**Comment by scottyrotten6** [comment]
professor Dante - I just found out about all this and am scrambling to get it taken care of.  It sounds like you got further than me and have a UTP agreement. Could you tell me how to do that? I don't have the email they sent and I am not getting anywhere using the above link provided by joshuablackburn. Sorry to appeal to you for help but I'm really struggling with this.

**Comment by professorDante** [comment]
@evancarter-iex I've already done that! There has been no response, hence the github. 

I think we are in the process of getting IEX added to our UTP directly through them. If not, I'll try you guys again.

**Comment by professorDante** [comment]
No problem brother - you need to go to www.utpplan.com <http://www.utpplan.com/>, and you can start the process there. We already have one in place, as we draw data from another provider as well as IEX.

**Comment by scottyrotten6** [comment]
Thanks a million for responding. I actually deleted the comment on GitHub though. Moments after I posted it evancarter-iex emailed me directly with instructions. He ensured me I won’t see a data interruption and said further directions were forthcoming, so my stress level instantly went down 3 orders of magnitude. Good luck with your endeavors and I can’t thank you enough for helping me out.

Scott

**Comment by evancarter-iex** [comment]
@professorDante I went through and responded to a bunch of questions. If you still havent received a response please email us again. Thanks.

**Comment by professorDante** [comment]
@evancarter-iex Gotcha - i'll send another one through now, under our business email.

**Comment by professorDante** [comment]
@evancarter-iex just sent now, under Trade Cheetah email
