### ISSUE TITLE
Is there any rate limit on the IEX API? 

### ISSUE THREAD

**Issue by zxcvbn97** [iexg/IEX-API#115]
## Summary

I am querying stock quotes every 5 seconds, is it ok?

**Comment by joshuablackburn-iex** [comment]
Current rate limit is around 25 per second with a higher burst rate.  You should be fine.

**Comment by timkpaine** [comment]
is there bulk download? I'm setting up to pull around [10 fields for the whole 8000 ticker universe](https://github.com/timkpaine/hedgeme/blob/master/hedgeme/cache.py#L63) nightly and dumping to [quilt](https://quiltdata.com/package/timkpaine/hedgeme), wouldnt mind grabbing a tarball instead
