### ISSUE TITLE
[Data] Alibaba (BABA) has a price target that is way too high $1502 vs $176 closing price

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1150]
**Clearly describe the data problem**
BABA is reporting way too high price targets:
{"symbol":"BABA","updatedDate":"2019-07-24","priceTargetAverage":1502.07,"priceTargetHigh":1925.2,"priceTargetLow":1114.28,"numberOfAnalysts":50}

It closed at $177 so the number is way out of wack.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/baba/price-target?token=

**What time did the problem occur (including timezone)?**
8:30AM PST July 26

**What is the expected behavior?**
Returns a realistic number

**What are the steps to reproduce**
Make the API call

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by joshuablackburn-iex** [comment]
The price target for ADR looks to be reported in local currency. We will take a look at converting these to the currency of the market.

**Comment by jesseorosz** [comment]
Makes sense. Thank you for taking a look.

**Comment by jesseorosz** [comment]
Any progress yet? This has been seven months.

Is there anyway to tell what is being reported in USD and what isn't? Or what currency the Price Target is being reported as?

**Comment by timpaine-iex** [comment]
dupe https://github.com/iexg/IEX-API/issues/915
