### ISSUE TITLE
[Data]Question about dividend datapoints available from 1st Aug under START plan

### ISSUE THREAD

**Issue by mickeyjain26** [iexg/IEX-API#1151]
**Clearly describe the data problem**
Have questions about the dividend api availability from aug 1 onwards

**Data URL (The URL you used to access the data without your token):**
Will the following be available from aug 1 on START plan ?
https://cloud.iexapis.com/stable/stock/AAPL/dividends/3m?token=pk_xxxxxx

https://cloud.iexapis.com/stable/stock/AAPL/dividends/1y?token=pk_xxxx

https://cloud.iexapis.com/stable/stock/AAPL/stats/ttmDividendRate?token=pk_xxxx

**What time did the problem occur (including timezone)?**
Might occur

**What is the expected behavior?**
just need this info

**What are the steps to reproduce**
URL's provided above

**Your environment (e.g. browser, OS, API version, language):**
browser/sheets

**Additional context**
If the above URL's wont be available what function will get the last dividend ?

**Comment by evancarter-iex** [comment]
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
