### ISSUE TITLE
https://cloud.iexapis.com/v1/stock/market/batch?token=pk_mykey&symbols=ZYXI,ZYNE,ZYME,ZVO,ZUO,ZUMZ,ZTS,ZSL,ZSAN,ZS&types=chart&range=1d&chartLast=1

### ISSUE THREAD

**Issue by mwk1000** [iexg/IEX-API#1153]
This endpoint has been working for many weeks and stopped working with a 401 - Payment required. Much time was spent tuning the query message use,  Is this a bug , it is not documented as a "paid only" call ?

**Comment by evancarter-iex** [comment]
Please check your message usage
