### ISSUE TITLE
When Can I get a Refresh on my Free Key?

### ISSUE THREAD

**Issue by ggarrisonsr** [iexg/IEX-API#1154]
**Clearly describe the data problem**
Free Key is not refreshing

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/account/metadata?token=xxxxxx

**What time did the problem occur (including timezone)?**
July 17, 2019

**What is the expected behavior?**
Should have received a refresh on the key for another 500,000 tokens

**What are the steps to reproduce**
Get a free key. Use the 500,000 tokens. Wait a month to see if it refreshes.

**Your environment (e.g. browser, OS, API version, language):**
N/A

**Additional context**
Given all the changes to the data over the past month and all the testing I've had to perform. I've exceeded my tokens on my paid account along with the free key. How about giving us back some tokens!

**Comment by McQgit** [comment]
Docs say: "Billing resets on the first of every month at 00:00:00 UTC"

So, wait another day.  See:
[]https://iexcloud.io/docs/api/#usage

*I am not an IEX employee

**Comment by ggarrisonsr** [comment]
{"payAsYouGoEnabled":false,"effectiveDate":1560826285000,"subscriptionTermType":"annual","tierName":"start","messageLimit":500000,"messagesUsed":500000,"circuitBreaker":0}

The effectiveDate equates to : Mon Jun 17 2019 22:51:25. Today is July 31st.

**Comment by ggarrisonsr** [comment]
The keys are not resetting.

**Comment by joshuablackburn-iex** [comment]
Your account is billed on a pro rated basis. We even allow you to access the full message amount of each tier for the remainder of the month. Message allocation is per calendar month. You have full flexibility to use as much or as little as you want with pay as you go. We apply a volume discount once you exceed your monthly allocation.
