### ISSUE TITLE
[Issue] LatestPrice on Quote endpoint returning null

### ISSUE THREAD

**Issue by juanrodriguezcen** [iexg/IEX-API#1156]
When hitting the quote endpoint for some symbols I'm receiving null for `latestPrice`, even though `previousClose` has value. From the docs:

>Use this to get the latest price Refers to the latest relevant price of the security which is derived from multiple sources. We first look for an IEX real time price. If an IEX real time price is older than 15 minutes, 15 minute delayed market price is used. If a 15 minute delayed price is not available, we will use the current day close price. **If a current day close price is not available, we will use the last available closing price (listed below as previousClose)**

Example: https://cloud.iexapis.com/v1/stock/VHT/quote

```
{
    "symbol": "VHT",
    "companyName": "Vanguard Health Care Index Fund",
    "primaryExchange": "NYSE Arca",
    "calculationPrice": "sip",
    "open": null,
    "openTime": null,
    "close": null,
    "closeTime": null,
    "high": null,
    "low": null,
    "latestPrice": null,
    "latestSource": "15 minute delayed price",
    "latestTime": null,
    "latestUpdate": null,
    "latestVolume": null,
    "iexRealtimePrice": 0,
    "iexRealtimeSize": 0,
    "iexLastUpdated": 0,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 173.38,
    "previousVolume": null,
    "change": null,
    "changePercent": null,
    "volume": null,
    "iexMarketPercent": null,
    "iexVolume": 0,
    "avgTotalVolume": 171466,
    "iexBidPrice": 173.8,
    "iexBidSize": 100,
    "iexAskPrice": 0,
    "iexAskSize": 0,
    "marketCap": null,
    "peRatio": null,
    "week52High": 181.91,
    "week52Low": 149.54,
    "ytdChange": null,
    "lastTradeTime": 1564586524891
}
```
I'm not sure if there is a problem with the API or with the docs, but there is a miss match. 

Also, any reason why IEXCloud wouldn't have the price for VHT (it's a pretty popular ETF)?

**Comment by bartclaeys** [comment]
I've noticed the same, `latestPrice` is empty for most of the `NYSE Arca` stocks when requesting `quote` data, however `previousClose`, `iexBidPrice` and `iexAskPrice` are available.

This is the API call:
https://cloud.iexapis.com/v1/stock/market/batch?symbols=IHE&types=quote&range=5y&token=loremipsum

Here are a couple of examples:

https://iextrading.com/apps/stocks/DIV
https://iextrading.com/apps/stocks/FXC
https://iextrading.com/apps/stocks/SPHD

For the followingt there isn't even `iexBidPrice` or `iexAskPrice`:
https://iextrading.com/apps/stocks/RYH
https://iextrading.com/apps/stocks/IHE

**Comment by evancarter-iex** [comment]
This is due to the fact that these stocks/etfs etc are lightly traded on IEX.

Paid accounts have access to 15 minute delayed SIP data for non NASDAQ stocks. For NASDAQ stocks please refer to the emails sent regarding their processes/costs.

@bartclaeys These are lightly traded stocks/etfs on IEX so you may not even see bids or asks depending on whose on the book at that particular point.

**Comment by bartclaeys** [comment]
> @bartclaeys These are lightly traded stocks/etfs on IEX so you may not even see bids or asks depending on whose on the book at that particular point.

But still, why is `latestPrice` and `changePercent` not provided then?

**Comment by evancarter-iex** [comment]
@bartclaeys I am seeing latest price on DIV, FXC and SPHD. Are you on a free account?

IHE and RYH haven't been traded today.

**Comment by bartclaeys** [comment]
Yes, currently on a free account, creating an app (but limited to personal use right now).

**Comment by evancarter-iex** [comment]
@bartclaeys you should still see latestprice. It looks like theres a bug in the change/changePercent for free accounts probably due to the recent changes. We will look into it.
