### ISSUE TITLE
[Data] various stock symbol quotes return “NOT FOUND” during trading day

### ISSUE THREAD

**Issue by Webclipper36** [iexg/IEX-API#1157]
Fairly new iex cloud user. Worked fine the first couple of months, but last couple of weeks have received "NOT FOUND" message for various symbols LatestPrice quote requests each day. The NOT FOUND messages tend to reduce in number as the day goes along and are all gone by end of day or end of week. Seems to be worse in the mornings. I am wondering if I am using the correct quote request? Must be something I am missing here.

MyRequest.Open "GET", "https://cloud.iexapis.com/stable/stock/" & symbol & "/quote/latestPrice?token=<token here>

Using EXCEL VBA to make request.

**Comment by zwatgit** [comment]
Starting to see similar issue tonight,  quote and price return "Not Found" for some symbols, e.g., WDC.  Looks like this is related to the UTP data change happening tonight.  Fixing the symbol "Not Found" issue is one thing, more importantly the error message could be more meaningful. 

I like the IEXCloud product, however the data issues just happened too often. I wish IEXCloud could have a more reliable continuous delivery process.

**Comment by saunders77** [comment]
I'm experiencing the same issue

**Comment by evancarter-iex** [comment]
Will reopen if we get more information.
