### ISSUE TITLE
[Data] Unable to access market wide intraday quotes for non-Nasdaq stocks.

### ISSUE THREAD

**Issue by pathvine** [iexg/IEX-API#1159]
**Clearly describe the data problem**
I have just changed back to the "Starter" plan. Before I was able to access intraday quotes (with "Starter plan) from endpoints such as this: 
https://cloud.iexapis.com/stable/stock/spy/chart/date/20190731
https://cloud.iexapis.com/stable/stock/gld/chart/date/20190731

Now I can't access such data anymore. Instead, I got the following error message,
"The requested data is not available to free tier accounts. Please upgrade for access to this data.", which I thought would only happen on the Nasdaq stocks.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/gld/chart/date/20190731

**What time did the problem occur (including timezone)?**
Since today 8/1 12AM (NY time)

**What is the expected behavior?**
Able to retrieve market wide intraday quotes data.

**What are the steps to reproduce**
By accessing the above endpoints.

**Your environment (e.g. browser, OS, API version, language):**
Google Chrome on Mac OS X

**Additional context**

**Comment by evancarter-iex** [comment]
@pathvine Is this still an issue? I am able to access it with my test account.

**Comment by pathvine** [comment]
@evancarter-iex thanks Evan. It is fixed now and accessible. It was very odd that none of them could be accessed earlier today.

**Comment by evancarter-iex** [comment]
@pathvine Ill look into it tonight with my test account. Thanks for the update.
