### ISSUE TITLE
Webservice: Chart as CSV returns inconsistent formatted label for 1m vs other periods

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#116]
## Summary
Webservice: Chart as CSV returns inconsistent formatted label for 1m vs other periods

## Details
>   Running WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart/1m?format=csv") returns label as "MMM DD" (_without_ the quotation marks).
This is consistent with other data in the CSV import.

- Example:
date,open,high,low,close,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
2017-10-24,35.31,35.36,34.81,34.86,52235811,52235811,-0.39,-1.106,34.9448,Oct 24,0
2017-10-25,34.26,34.35,33.33,33.4854,91195287,91195287,-1.3746,-3.943,33.6384,Oct 25,-0.03943201376936319....

>   Other (e.g., 3m, 6m, 1y)
Running WEBSERVICE("https://api.iextrading.com/1.0/stock/T/chart/3m?format=csv") returns label as "MMM DD, YY" (_with_ quotation marks).
This is inconsistent with other data in the CSV import.

- Example:
date,open,high,low,close,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
2017-08-24,48.35,48.555,48.18,48.31,8898226,8898226,0.03,0.062,48.3596,"Aug 24, 17",0
2017-08-25,48.48,48.98,48.43,48.68,9846677,9846677,0.37,0.766,48.7567,"Aug 25, 17",0.00765886979921336....

I tried with multiple Symbols (e.g., AAPL, VZ, PG) and got the same result.

### Other Information (sample code, links, etc.)

Thank you.

**Comment by joshuablackburn-iex** [comment]
The label field is intended to vary based on the range selected.  This field is optional since the full date is provided as "date".  We use this field in our charts (https://iextrading.com/apps/stocks/#/AAPL).

**Comment by ModelsRUs** [comment]
Thank you Josh, although I can't imagine why this (being intended) would 
be the case. Depending upon the query as-of date, historical data could 
easily span multiple years regardless of the time period - why assume 
this is NOT the case with "1m"?

As I'm sure you know, consistency is quite important when parsing data.

Best regards,
- *Paul*
   (917) 476-4468
===================================================================

**Comment by ModelsRUs** [comment]
Sorry to be a pest, but I've worked with this some more, and it makes no sense to me that a CSV file would have a comma that doesn't signify a new field. I'm trying to parse the Webservice return. 

(date,open,high,low,close,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
2017-08-24,48.35,48.555,48.18,48.31,8898226,8898226,0.03,0.062,48.3596,"Aug 24, 17",0
2017-08-25,48.48,48.98,48.43,48.68,9846677,9846677,0.37,0.766,48.7567,"Aug 25, 17",0.00765886979921336....)

I understand it's in quotes but comma in "Aug 25, 17" is being read as a field separator! This strikes me as a bad design.

**Comment by joshuablackburn-iex** [comment]
The label field was designed as a convenience and specifically used in our own apps.  If you don't find the format to be useful, the "date" field should provide sufficient information to calculate your own date string.

As for the CSV, commas in values are valid.  Refer to [RFC 4180](https://tools.ietf.org/html/rfc4180#page-2) section 2, sub-section 6 "Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes."  Any good CSV parsing library will handle this for you.
