### ISSUE TITLE
[Data] Mutual Fund quotes coming up null

### ISSUE THREAD

**Issue by lgellert** [iexg/IEX-API#1160]
**Clearly describe the data problem**

Price quotes on mutual funds are returning Null:

`{"VTMFX":{"quote":null}}`

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/v1/stock/market/batch?symbols=VTMFX&types=quote&token=****

**What time did the problem occur (including timezone)?**

Thu Aug  1 07:48:42 UTC 2019

**What is the expected behavior?**

To get quote data.

**Additional context**

Is this because of the NASDAQ licensing issue?  Does this mean IEX Cloud will no longer provide prices for mutual funds unless we get the agreement with NASDAQ?  The emails that went out only mention NASDAQ listed stocks, not mutual funds, but if I'm not mistaken NASDAQ handles mutual fund prices.

**Comment by mikezliu** [comment]
Scale customer and seeing the same issue. Unfortunately given that IEX forms were just added to the UTP website today, there was no way to avoid data disruption.

**Comment by evancarter-iex** [comment]
@lgellert Is this still an issue, Im seeing data?

**Comment by lgellert** [comment]
@evancarter-iex Looking good!
