### ISSUE TITLE
[Issue] extendedPrices missing / timestamp wrong this morning (even on IEX website)

### ISSUE THREAD

**Issue by ohlhaver** [iexg/IEX-API#1161]
None of the stocks are currently showing post-market prices at a time after market close and before pre-market trading. Neither on the IEX website (https://iextrading.com/apps/stocks/AAPL) nor in the API response (below) where the latestUpdate and closeTime are both greater than the delayedPriceTime rightfully leading our system (as I assume most systems) to ignore the extendedPrice.

{ symbol: 'AAPL',
  companyName: 'Apple, Inc.',
  primaryExchange: 'NASDAQ',
  calculationPrice: 'close',
  open: 216.35,
  openTime: 1564579800948,
  close: 213.04,
  closeTime: 1564603200696,
  high: 221.37,
  low: 211.3,
  latestPrice: 213.04,
  latestSource: 'Close',
  latestTime: 'July 31, 2019',
  latestUpdate: 1564603200696,
  latestVolume: 69064160,
  iexRealtimePrice: 213.08,
  iexRealtimeSize: 50,
  iexLastUpdated: 1564603195310,
  delayedPrice: 213.376,
  delayedPriceTime: 1564603094660,
  extendedPrice: 216.59,
  extendedChange: 3.55,
  extendedChangePercent: 0.01666,
  extendedPriceTime: 1564579800826,
  previousClose: 208.78,
  previousVolume: 33935718,
  change: 4.26,
  changePercent: 0.0204,
  volume: 0,
  iexMarketPercent: 0.032349513843359566,
  iexVolume: 2234192,
  avgTotalVolume: 22725485,
  iexBidPrice: 0,
  iexBidSize: 0,
  iexAskPrice: 0,
  iexAskSize: 0,
  marketCap: 980214083200,
  peRatio: 18.01,
  week52High: 233.47,
  week52Low: 142,
  ytdChange: 0.369437,
  lastTradeTime: 1564603195310 }

**Comment by evancarter-iex** [comment]
This is fixed.
