### ISSUE TITLE
[Data] Open High Low Close price data all the same

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#1162]
**Clearly describe the data problem**

Around 8-8:45pm EST yesterday 7/31 many quotes using the batch endpoint where returning the same open high low and close price data. At the same time calls to the api where taking much longer than normal 10x the time. Please look into this, I will add code to check for this error and alert in the future if it happens again.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/v1/stock/market/batch?token=...types=quote&filter=open,high,low,latestUpdate,latestPrice,latestVolume&symbols=AAPL etc...

**What time did the problem occur (including timezone)?**

8:-8:45 EST 7/31

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
@StockConsultant We saw a latency spike at around 9:30 but were able to mitigate it by 9:35am or so. Are you still seeing the latency issue?

**Comment by StockConsultant** [comment]
This morning? I think we saw 3 spikes (time to get and process about 7900 stocks) then back close to the 2-2.5 sec time. The latency has been a little higher and more volatile the past few days.

![image](https://user-images.githubusercontent.com/42130156/62299690-644bab80-b443-11e9-8749-5950b9db6cf8.png)

**Comment by evancarter-iex** [comment]
@StockConsultant Ok Im keeping an eye on the latencies on my end...Definitely saw a spike at 9am and 9:30am

**Comment by StockConsultant** [comment]
yep it was at 9:30 ish we got a text alert since we monitor the latency, as for many of the quotes open high low and close being the same for the batch mode call yesterday around 8 to 8:30pm we didn't notice the data issue till this morning, by then it was too late to reproduce but will add code to monitor and alert this condition in the future.

**Comment by evancarter-iex** [comment]
@StockConsultant Ok let me know if you see anything else but needless to say I got the alerts about latency as well :)

**Comment by StockConsultant** [comment]
@evancarter-iex 

I just noticed a porblem with batch mode that probably started yesterday around 8pm EST and continues today

https://cloud.iexapis.com/v1/stock/market/batch?token=...&types=quote&filter=open,high,low,latestUpdate,latestPrice,latestVolume&symbols=AAPL,AMD

returns nulls for open high low

{"AAPL":{"quote":{"open":null,"high":null,"low":null,"latestUpdate":1564674954462,"latestPrice":217.66,"latestVolume":17100884}},"AMD":{"quote":{"open":null,"high":null,"low":null,"latestUpdate":1564674956167,"latestPrice":31.225,"latestVolume":29278729}}}

did something change? Is there some new rev I'm not using?

**Comment by evancarter-iex** [comment]
@StockConsultant Thats due to the UTP/Nasdaq issue we sent several emails about

**Comment by StockConsultant** [comment]
Yep just filled out all the forms hopefully it doesn't take long to process, I thought for the subscription we signed up for would include this delayed data as it was originally. I'm assuming once we get approval and pay it is easy for you to set it active again on your end?

**Comment by evancarter-iex** [comment]
@StockConsultant Yeah on our end its pretty instantaneous once you get approval from UTP/NASDAQ.
