### ISSUE TITLE
[Data] Batch request returning null values

### ISSUE THREAD

**Issue by romelusw** [iexg/IEX-API#1163]
**Clearly describe the data problem**
Most of the fields returned are null, making the data returned mostly useless.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/batch?symbols=LOGI&token=<TOKEN>&types=quote

**What time did the problem occur (including timezone)?**
10:15am EST

**Your environment (e.g. browser, OS, API version, language):**
Chrome 75.0.3770.142 (Official Build) (64-bit)

I have seen this occur many times for various stocks.

**Comment by evancarter-iex** [comment]
@romelusw Please refer to the emails we sent regarding NASDAQ/UTP.
