### ISSUE TITLE
[Issue] Aapl showing wrong price after close

### ISSUE THREAD

**Issue by jmoscatiello** [iexg/IEX-API#1165]
**Clearly describe the problem**
Apple closing price on July 31 should be approx 208.50

On iex the latest price after hours is 213.04

Why such a big difference?

**What time did the problem occur? (with timezone)**

After hours July 31

**Your environment (e.g. browser, OS, API version, language):**
API call for quote

**Comment by McQgit** [comment]
I think you may be having some problems with your dates or timezones.  The official close on Jul30 was 208.78 and on Jul31 was 213.04.  AAPL is listed on the Nasdaq exchange - see their official close history here:
[]https://www.nasdaq.com/aspx/historical_nocp.aspx?symbol=AAPL&selected=AAPL

**Comment by jmoscatiello** [comment]
I got my dates mixed up but it corrected itself within the last hour. It was 213 but now I recalled the API and it shows the correct 208.

**Comment by McQgit** [comment]
No worries.  I was seeing odd stuff myself and came here to see if anyone reported it.  Seems that at 5:30pm eastern IEX was showing 'previousclose' as the calculation price in the quote for Nasdaq stocks with a date stamp from Jul31 - not the most recent close Aug1.  It has now reverted to showing the latest trade on IEX which for AAPL and other actively traded stocks is close to the official close.  

So, probably a glitch in IEX related to the Nasdaq UTP change.
