### ISSUE TITLE
Sandbox only returns 1 dividend on free account

### ISSUE THREAD

**Issue by asher-scott** [iexg/IEX-API#1166]
**Clearly describe the problem**
The `/stock/{symbol}/dividends/{range}` endpoint does not appear to be respecting the range parameter.  If used with a range parameter of `5y`, the endpoint responds with a JSON array containing a single dividend object, rather than multiple dividend objects for that 5 year range.
This issue occurs no matter what range parameter is used.

**What time did the problem occur? (with timezone)**
August 1st, 2019 8:30 PM EST

**What is the expected behavior?**
The dividends endpoint respects the range parameter and returns the full dividend history according to the range specified.

**Your environment (e.g. browser, OS, API version, language):**
Firefox, Windows 10

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/stock/F/dividends/5y?token=<YOUR_TOKEN>
(This bug also occurs in the production api)

**What are the steps to reproduce the bug?**
Perform a test/regular call from the IEX Cloud console.  Change the range parameter in the URL to see that the amount of data in the response does not comply with the range specified.

**Additional context**
This bug may be related to an earlier posted issue: https://github.com/iexg/IEX-API/issues/1164

**Comment by Christian-Oette** [comment]
I can confirm this issue. It used to be a list. Checked with ticker symbols 0,KHC,AAPL and different ranges.
Please fix!

**Comment by evancarter-iex** [comment]
@asher-scott @Christian-Oette Are you using free accounts?

**Comment by Christian-Oette** [comment]
For now yes. If its only available for paid accounts it would be nice if the test server returns more then one entry. This makes the Implementation easier.

**Comment by evancarter-iex** [comment]
@Christian-Oette Yeah I'll add it to a sandbox update

**Comment by Christian-Oette** [comment]
Great. Thx.

**Comment by evancarter-iex** [comment]
@Christian-Oette 
@asher-scott 

@theofficejackpot  
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
