### ISSUE TITLE
Feature Request: only return last quarter of financials

### ISSUE THREAD

**Issue by anujgoyal** [iexg/IEX-API#117]
## Summary
Pulling 4 quarters of financials is unnecessary in many applications.  It would save bandwidth to transmit just a minimal set of quarters. For example

### Date/time of issue
Nov 27, 2017

### API URL
https://iextrading.com/developer/docs/#financials

### Other Information (sample code, links, etc.)
1 picks the latest quarter, 2 picks the last 2 quarters, etc.
/stock/aapl/financials/1
/stock/aapl/financials/2
/stock/aapl/financials/3

**Comment by evancarter-iex** [comment]
Quarterly is the default in IEXCLoud. https://iexcloud.io
