### ISSUE TITLE
Options return all available expiration dates for the symbol

### ISSUE THREAD

**Issue by Jacyle** [iexg/IEX-API#1170]
**Clearly describe the problem**
The API Documentation says the expiration date is is optional and will return all available expiration dates for a symbol. However, the API Documentation is not clear how to do that because if you don't include the expiration and optionSide, the endpoint returns available expiration dates.

Could you explain how to receive all available contract expiration dates for a symbol?

**What time did the problem occur? (with timezone)**
Eastern

**What is the expected behavior?**
endpoint returns all available expiration dates

**Your environment (e.g. browser, OS, API version, language):**
chrome,windows 7,stable,python

**API URL (if applicable)**
Returns expiration dates available:
https://cloud.iexapis.com/stable/stock/vix.cbo/options?token=%s

**Comment by McQgit** [comment]
I think what you described is the intended operation.  That is, you call it first without any expiration date to receive the list of possible dates for that symbol.  Then, call again once for each date in that list you are interested in to get the option data.

Each symbol may have a different sequence of dates and you may not be interested in all of them.  This allows you to minimize your cost.  Granted, if you just want all the options for all the dates it is more cumbersome.  That said, the way IEX does it is how I've had to do it with other vendor API.
