### ISSUE TITLE
batch stock quotes url is not returning much of the data I am requesting

### ISSUE THREAD

**Issue by BrianARice** [iexg/IEX-API#1172]
The batch stock quotes url is not returning much of the data I am requesting…

This url:
https://cloud.iexapis.com/stable/stock/market/batch?symbols=FB,AMZN&types=quote&filter=latestPrice,close,closeTime,high,low,close,closeTime,open,openTime,latestVolume&token={mypublickey}

Note: this was submitted at 10:45am CST on a Friday.

is giving me:
{
  "FB": {
    "quote": {
      "latestPrice": 190.05,
      "close": null,
      "closeTime": null,
      "high": null,
      "low": null,
      "open": null,
      "openTime": null,
      "latestVolume": 7181708
    }
  },
  "AMZN": {
    "quote": {
      "latestPrice": 1815.81,
      "close": null,
      "closeTime": null,
      "high": null,
      "low": null,
      "open": null,
      "openTime": null,
      "latestVolume": 2294745
    }
  }
}

**Comment by evancarter-iex** [comment]
Unfortunately this is due to the UTP/NASDAQ issue. Please refer to the emails we sent out.
