### ISSUE TITLE
IEXCloud SSE is not sending CORS HTTP headers

### ISSUE THREAD

**Issue by ronnyhaase** [iexg/IEX-API#1175]
**Clearly describe the problem**
Opposite to the normal HTTP endpoints, SSE does not send CORS headers and therefor makes it impossible to stream directly from browsers.

**What is the expected behavior?**
Send CORS headers as do the normal HTTP endpoints.

**Your environment (e.g. browser, OS, API version, language):**
Not browser related, but occuring in all due to security restrictions.

**API URL (if applicable)**
E.g. `/stock/{symbol}/news`, `/stock/{symbol}/price`, `/stock/{symbol}/intraday-prices`

**What are the steps to reproduce the bug?**
Try to stream directly from browser using `EventSource`

**Comment by evancarter-iex** [comment]
@ronnyhaase Is this still an issue?

**Comment by ronnyhaase** [comment]
@evancarter-iex I just tried, yes it is. Still no CORS headers.

**Comment by ronnyhaase** [comment]
Hi,

I think your docs just received an update or I was blind.

I was simply requesting the same paths as I would for normal HTTP requests (e.g. `/stock/aapl/quote`, but obviously that's not supposed to work, since the SSE path is different.

Using the correct path it works, fine. Thank you.
