### ISSUE TITLE
[Data] Multiple options with same ID

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1176]
**Clearly describe the data problem**

Some symbols and option dates return multiple options with the same option ID, one of which is inaccurate. 

**Data URL (The URL you used to access the data without your token):**

/stable/stock/CI/options/202101
/stable/stock/UTX/options/202101

**What time did the problem occur (including timezone)?**

June 30th 6:00pm ET
August 6th 2:15am ET

**What is the expected behavior?**

- The ID field should be unique. 
- Pricing data should be accurate; the bid/ask midpoint should be above the intrinsic value of the option.

**What are the steps to reproduce**

Request the above URLs and notice multiple options returned with the same ID, one of which is inaccurate:
UTX: UTX20210115P00135000
CI: CI20210115C00125000

**Comment by evancarter-iex** [comment]
@humenick I believe this is fixed now.
