### ISSUE TITLE
changePercent for NYSE is zero after 4pm[Data]

### ISSUE THREAD

**Issue by TradingLicks** [iexg/IEX-API#1177]
I’m currently subscribed to the Grow plan. In past 3 sessions I’ve been getting a zero value changePercent for New York Stock Exchange issues after 4pm EST. Is there now a new endpoint for changePercent with NYSE issues between 4 and 4:15 PM EST?

**Comment by smidwap** [comment]
I'm seeing a related issue where latest prices fall back to the previous day's closing price between about 4 and 4:30pm EST. Grow plan subscriber as well here.

**Comment by StockConsultant** [comment]
@smidwap my latest post brings this up for NYSE prices just after 4pm to about 4:30 EST for latest prices, I posted some examples

**Comment by pdxsteve** [comment]
I'm seeing this behavior for SPY. Change percent goes to 0% at 4pm EST. Then at next day open it's reading correctly again.

**Comment by pdxsteve** [comment]
This looks like related to this issue of data resetting to previous days close: https://github.com/iexg/IEX-API/issues/1180
