### ISSUE TITLE
[Issue] Open Prices missing for some symbols in OHLC API

### ISSUE THREAD

**Issue by xunamcapital** [iexg/IEX-API#1178]
**Clearly describe the problem**
There is missing data for some symbols in your OHLC API

**What time did the problem occur? (with timezone)**
Any time (trying after 9:45 due to 15 minute delayed data)

occurs every day - some symbols do not have data
**What is the expected behavior?**
Expected to return open high low data for symbols

**Your environment (e.g. browser, OS, API version, language):**
Browser

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/AAL/ohlc?token=TOKEN

**What are the steps to reproduce the bug?**
https://cloud.iexapis.com/stable/stock/AAL/ohlc?token=TOKEN

Some symbols that were not returned (out of many):
AAL
ACAD
ACER
ACGL
ACHC
ACHN
ACHV
ACIA
ACIU
ACIW
ACLS

**Additional context**

**Comment by evancarter-iex** [comment]
This is due to the NASDAQ UTP issue which is referenced in documentation and emails that were sent.
