### ISSUE TITLE
[Issue] Not reliable /search endpoint

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#1179]
**Clearly describe the problem**

Sometimes search endpoint is returning HTTP status 500 with message "An unknown error has occurred". 

**What time did the problem occur? (with timezone)**

Multiple times, but some of them:

2019.08.07 7:48PM CEST
2019.07.28 8:07PM CEST
2019.07.28 4:42AM CEST

**What is the expected behavior?**

I get results instead of 500 HTTP status

**Your environment (e.g. browser, OS, API version, language):**

Java 8-12 / Firefox / Postman

**API URL (if applicable)**

https://sandbox.iexapis.com/v1/search/apple?token=

https://iexcloud.io/docs/api/#search

**What are the steps to reproduce the bug?**

Call endpoint untill it returns 500 status

**Additional context**

**Comment by evancarter-iex** [comment]
@wenxinyang-iex We deployed a fix for this yesterday. Is this still a problem?

**Comment by WojciechZankowski** [comment]
It seems to be fixed. Thanks!
