### ISSUE TITLE
Feature Request: /stock/quote/{symbol}, not /stock/{symbol}/quote

### ISSUE THREAD

**Issue by anujgoyal** [iexg/IEX-API#118]
## Summary
Most APIs I have used place the stock symbol at the suffix of the HTTP request, not in the middle.

## Details
Here is an example (eg. https://medium.com/codingthesmartway-com-blog/create-a-rest-api-with-json-server-36da8680136d).  It's slightly unusual to have it in the middle of the request, but I understand that it might be the result of your API implementation. 
```
GET    /employees
GET    /employees/{id}
```
IMHO placing the symbol set at the suffix is cleaner.
```
GET    /stock/quote/{stock1,stock2,stock3,stock4}
GET    /stock/financials/{stock}
```

### Date/time of issue
Nov 27, 2017

### API URL
All APIs

### Other
What was the design decision that led to this choice?

**Comment by timpaine-iex** [comment]
This is deliberate, but likely to change in the future as more things move to the [time series](https://iexcloud.io/docs/api/#time-series) method of access.

E.g. for some of the newer endpoints (like [fundamentals](https://iexcloud.io/docs/api/#advanced-fundamentals))
`GET /time-series/fundamentals/{symbol}/{period}`
