### ISSUE TITLE
[Data] Missing GDX intraday data

### ISSUE THREAD

**Issue by pathvine** [iexg/IEX-API#1181]
**Clearly describe the data problem**
GDX (7/30/2019 and 8/7/2019) intraday quotes are missing.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/gdx/chart/date/20190730
https://cloud.iexapis.com/stable/stock/gdx/chart/date/20190807

**What time did the problem occur (including timezone)?**
For whole trading day when those data are missing.

**What is the expected behavior?**
The API should return the market minute-by-minute OHLCV quotes for those symbols and dates.

**What are the steps to reproduce**
By Visiting those API listed above.

**Your environment (e.g. browser, OS, API version, language):**
Any

**Additional context**

**Comment by evancarter-iex** [comment]
This should be fixed now.
