### ISSUE TITLE
[Data] Missing data for certain stocks

### ISSUE THREAD

**Issue by shawnsxyin** [iexg/IEX-API#1182]
**Clearly describe the data problem**
Blank data returned historical intraday for certain stocks on 20190807: HUM, HCI, UPS...
Response = []
However I can access for 20190806 for these stocks

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/UPS/chart/date/20190807

**What time did the problem occur (including timezone)?**
Started Aug 7, 2019 ~12:00 pm EST

**What is the expected behavior?**
List of minute data

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
Chrome, MacOS

**Additional context**

**Comment by scottyrotten6** [comment]
I noticed the same thing for ABC and ABT (and many more) for 20190806. I got an email yesterday saying they are looking into it but nothing since. Its come up before and is usually fixed right away, so I'm getting concerned now...

**Comment by evancarter-iex** [comment]
@scottyrotten6 We are working on. I took time off to reply to this github. We are trying to fix it going forward, so its just taking a bit longer.

**Comment by scottyrotten6** [comment]
Cool and thank you for taking the time to put me at ease. I know I get annoying, but it’s because I have to shut down my algos. It’s good to know your fixing it once and for all. Good luck with it - I know how crazy debugging this kind of thing can be.

Thank you,
Scott

**Comment by evancarter-iex** [comment]
@scottyrotten6 No worries. I know its aggravating on your side as well.

**Comment by shawnsxyin** [comment]
It seems like for today's data it is always there but there's list of companies that we can no longer query for once we move to tomorrow. Seems like we need to create a system to save data locally if we need to access it in the future...

**Comment by evancarter-iex** [comment]
These are backfilling as we speak. Next week we should have a longer term solution that will prevent this issue going forward.
