### ISSUE TITLE
[Data] International Symbols & How to get quote/ EOD data

### ISSUE THREAD

**Issue by thinkcodellc** [iexg/IEX-API#1183]
I am trying to use the API to get the quote for Bombay Stock Exchange.

When i look at the symbols from the reference data, as indicated below, it seems more like IDs and there is no API doc on how to get the quote using such non intuitive symbols.

{
  **"symbol": "500002-IB",**
  "exchange": "BOM",
  "name": "ABB India Limited",
  "date": "2019-08-06",
  "type": "cs",
  "iexId": "IEX_5747504E444A2D52",
  "region": "IN",
  "currency": "INR",
  "isEnabled": true
}

Is there not a ticker symbol that can be used. How does one get query by these IDs?  I am looking to query the EOD data / Quote for the international stocks by symbols like US Stocks.
 Is there an option to get the quote readily for international stocks similar to that of US stocks?

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/ref-data/exchange/BOM/symbols/?token=<TOKEN>

**What time did the problem occur (including timezone)?**
5 PM CST 8/7

**What is the expected behavior?**
Expect to see ticker symbols and updated API documentation on how to query international stocks for the most recent quote and that doesnt consume a heavy data weighting call.

**Comment by evancarter-iex** [comment]
@thinkcodellc India uses Numbers https://www.bseindia.com/corporates/List_Scrips.aspx
