### ISSUE TITLE
DELAYED_UTP Error

### ISSUE THREAD

**Issue by jimskin** [iexg/IEX-API#1184]
We are subscribed to the Launch plan and are trying to access IEX SSE steaming quotes and 'IEX only' historical data but are receiving the error below. Also, both of our API keys (live and sandbox) keys are not working. I've sent a number of emails to support@iexcloud.io but no reply which isn't good.

Request:
https://cloud-sse.iexapis.com/stable/stocksUS?symbols=MSFT&token=sk_key

Response
Access to the requested data requires the following permission(s): DELAYED_UTP

**Comment by ben-berman-iex** [comment]
Hi James, I just responded: 

As noted in the docs:

"Users who are not authorized by UTP to receive 15 minute delayed data for Nasdaq listed stocks should use stocksUSNoUTP to stream data for US based stocks. Users who are authorized to receive 15 minute delayed data for Nasdaq listed securities should use stocksUS to stream data for US based stocks."
