### ISSUE TITLE
[Issue] Getting the news for BTC returns Unknown Symbol while ETH/ LTC works

### ISSUE THREAD

**Issue by thinkcodellc** [iexg/IEX-API#1186]
**Clearly describe the data problem**
 I am using the URL as suggested in the API doc for getting the news for crypto. However when used for BTC, it returns Unknown Symbol.

But the same URL works for ETH, BCH and LTC. Does it mean it is not available / not implemented for BTC or simply not working?

**Data URL (The URL you used to access the data without your token):**
Not working
https://cloud.iexapis.com/stable/stock/BTC/news?token=(token)

Works
https://cloud.iexapis.com/stable/stock/ETH/news?token=(token)
https://cloud.iexapis.com/stable/stock/BCH/news?token=(token)
https://cloud.iexapis.com/stable/stock/LTC/news?token=(token)

**What time did the problem occur (including timezone)?**
All times

**What is the expected behavior?**
Returns the news

**What are the steps to reproduce**
Invoke using the URL

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Win 10

**Additional context**

**Comment by McQgit** [comment]
And, the related question, how would I get the news for:

ETH - Ethan Allen company and not Ethereum
LTC - LTC Properties and not Litecoin
BCH - Banco de Chile ADR and not Bitcoin Cash

All of the above are NYSE.  As @thinkcodellc notes, these three return news for the crypto symbols which are far more voluminous than the same equity symbol.

There is no equity symbol for BTC so no confusion.

Full disclosure: I personally don't need the news for the above equity symbols today.  I am more bothered by the symbol collision and the implications thereof throughout the API.

**Comment by evancarter-iex** [comment]
We currently dont support news for crypto symbols currently.
