### ISSUE TITLE
Filter parameters in chart/date and chartbyDay

### ISSUE THREAD

**Issue by manni1970** [iexg/IEX-API#1187]
**Clearly describe the data problem**

**Data URL (The URL you used to access the data without your token):**

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by manni1970** [comment]
I need the historical close date of a stock, let's say BAC, in Excel.

I tried different ways, none of them works.
When I try this:
https://sandbox.iexapis.com/stable/stock/A/chart/5d?token=xxx

I get 5 days of data (back 5 days from current date). But what if I need only 1 day (and only the close price) and from a specific date, e.g. 20190220). Is that possible at all? And is it possible in Excel as well?

Thanks for your help

**Comment by McQgit** [comment]
To get data for one date use something like this:
[]https://cloud.iexapis.com/stable/stock/aapl/chart/date/20190109?chartByDay=true&token=(token)

See the docs for related examples:
[]https://iexcloud.io/docs/api/#historical-prices

Note, the above returns OHLCV in json format - not just the close as you asked.  But, perhaps this gets you one step closer.

**Comment by manni1970** [comment]
That helped already a lot, I am still struggling with the filter option to only get the close response attribute (close price) as result. This one I tried returns the same dataset as yours, is the syntax wrong?

https://cloud.iexapis.com/stable/stock/aapl/chart/date/20190109?chartByDay=true&filter=close&token=(token)
--

**Comment by McQgit** [comment]
Yeah,`filter` didn't work for me either - good try though.  The docs say it's not supported for all endpoints so this must not be one.  There is a `format` parameter which will return csv rather than json - if that helps.  I don't use Excel much for this kind of thing anymore but when I did csv was easier to work with.

[]https://cloud.iexapis.com/stable/stock/aapl/chart/date/20190109?chartByDay=true&format=csv&token=(token)

**Comment by manni1970** [comment]
Thanks for your help again. The hint with the CSV format is valuable.
Still surprised that the filter argument doesn't work though.

**Comment by manni1970** [comment]
After a bit of research, there seems to have been a similar problem, issue #781 which was tagged solved.
The filter seems to work with for example 5d or 1m, but not without a specific date like above. Then the whole dataset is returned.

Oh mighty IEX developers, help us :-)

**Comment by manni1970** [comment]
Nobody here to comment this problem? No solution around?

**Comment by evancarter-iex** [comment]
@manni1970 I dont believe we currently support filter with chart/date. We will add it as an enhancement request
