### ISSUE TITLE
Using latest in URI instead of v1 returns 404

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1189]
Date/time of the issue

8/11 11:23 PM PDT

What you did

https://cloud.iexapis.com/latest/stock/goog/ceo-compensation?&token=

What you expected to happen

Get 200 server status code

What actually happened

Got 404 server status code

Additional relevant information

When I replace latest with v1 in URL I get 200 status code

**Comment by MorningSleeper** [comment]
Thanks for updating the documentation to reflect latest is no longer a supported version value.

**Comment by timpaine-iex** [comment]
it was not being used as clearly evidenced by nobody paying attention to this for years
