### ISSUE TITLE
Web-socket Random Price Spikes

### ISSUE THREAD

**Issue by chaseolsen** [iexg/IEX-API#119]
## Summary
I'm using socket.io to receive web-socket data to my Node server. After logging incoming quotes received from the Web-socket, the price will randomly shoot upwards 6-10$ and then return to its normal state. (This is happening to every symbol I subscribe to). Other than that, I absolutely love IEX, but hope to find a fix or solution with this issue sometime soon.

## Details
My server is currently subscribed to NVDA, on this date 11/28/2017. NVDA has yet to ever reach an askPrice of $216+, however, every time an incoming spike message is received, it always sits at $216.62 (as of today for example).

### Date/time of issue
Been acting this way since I started working with the WS since 11/8/2017

### API URL
https://ws-api.iextrading.com/1.0/tops

### Other Information (sample code, links, etc.)
Log Example:
![datalog](https://user-images.githubusercontent.com/12260976/33334671-eae9c364-d427-11e7-976f-a2941cab7ae5.PNG)

Data Going to Chart:
![dataimage](https://user-images.githubusercontent.com/12260976/33334708-08cf561e-d428-11e7-8f6e-b850cb13e0c4.PNG)

**Comment by jcape** [comment]
@chaseolsen Hi,

We looked into this issue for you. While those prices are correct, it's important to note that they represent the price sellers were willing to accept on IEX at that time. In other words, that's not the last sale price, that's just one side of the market. On the other side, for example, buyers seemed to be willing to pay between 207 and 210 for NVDA around that time.

In this particular case, there were multiple sellers at different prices (this is from the DEEP "book" websockets feed)

```
{
  "symbol": "NVDA",
  "messageType": "pricelevelsell",
  "data": [
    {"price":211.59,"size":100,"timestamp":1511910556551},
    {"price":211.61,"size":100,"timestamp":1511910551240},
    {"price":216.62,"size":100,"timestamp":1511903355166},
    {"price":221.17,"size":100,"timestamp":1511897403697},
    {"price":228.19,"size":100,"timestamp":1511897403703},
    {"price":230.28,"size":100,"timestamp":1511898300093}
  ]
}
```

What appears to have happened is that the quotes for the best price were withdrawn (or they traded), and that left the ‘more expensive’ quotes remaining, so what happened is this:

```
{
  "symbol": "NVDA",
  "messageType": "pricelevelsell",
  "data": [
//  {"price":211.59,"size":100,"timestamp":1511910556551}, <-- withdrawn
//  {"price":211.61,"size":100,"timestamp":1511910551240}, <-- withdrawn
    {"price":216.62,"size":100,"timestamp":1511903355166},
    {"price":221.17,"size":100,"timestamp":1511897403697},
    {"price":228.19,"size":100,"timestamp":1511897403703},
    {"price":230.28,"size":100,"timestamp":1511898300093}
  ]
}
```

Then after some period of time, a seller came back at a similar price. The TOPS websocket feed, however, only shows the best price. So when the seller at $211 went away, the "best" price became the $216 quote.
