### ISSUE TITLE
[Issue] companyName response attribute is blank in ceo-compensation

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1190]
**Clearly describe the problem**

companyName response attribute is blank in ceo-compensation

**What time did the problem occur? (with timezone)**

8/11 11:23 PM PDT

**What is the expected behavior?**

Should not be blank if other data is available.

**API URL (if applicable)**

https://cloud.iexapis.com/v1/stock/goog/ceo-compensation?&token=

**Additional context**

Tried with symbols GOOG, FB and IBM.

**Comment by evancarter-iex** [comment]
This is fixed.Though GOOG/GOOGL are out of alignment for some reason which I will look into when I have a chance.

**Comment by MorningSleeper** [comment]
BTW, when you wrote GOOG/GOOL were out of alignment I assume you mean the companyName response attribute is returning the security name of "Alphabet Inc. Class A" instead of just "Alphabet Inc."? If so, I wanted to let you know that the same problem exists for Facebook as it is showing "Facebook Inc. Class A" as the companyName instead of just "Facebook Inc.".
