### ISSUE TITLE
[Data] 404 server error on CEO Compensation for ADR

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1191]
**Clearly describe the data problem**

Get 404 server error for CEO compensation for an ADR on Nasdaq, symbol ZLAB. If ADRs are not supported for this end point, please advise.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/v1/stock/zlab/ceo-compensation?token=

**What time did the problem occur (including timezone)?**

8/12/19 12:03 PM PDT

**What is the expected behavior?**

Provide data or null.

**Comment by joshuablackburn-iex** [comment]
Currently supporting Russell 1000 stocks. Docs will be updated to reflect this.
