### ISSUE TITLE
[Data] Most Insider Transactions contain blank tranShares, tranPrice & tranValue

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1194]
Clearly describe the data problem

The following response attributes for the Insider Transactions endpoint are blank for 17 out of the 20 most recent results returned for symbol GOOG.

tranShares
tranPrice
tranValue

They all have dates, names and titles.

Data URL (The URL you used to access the data without your token):

https://cloud.iexapis.com/v1/stock/goog/insider-transactions?&token=

What time did the problem occur (including timezone)?

8/12/19 9:52 PM PDT

What is the expected behavior?

For each or at least most records to have at least one of the number of shares or transaction price or transaction value.

**Comment by evancarter-iex** [comment]
@MorningSleeper Hi there, Im looking into this

**Comment by evancarter-iex** [comment]
This is fixed.

**Comment by MorningSleeper** [comment]
Hi, I see all records now return something for tranShares response attribute, thank you. I see some records still returned with no transPrice, transValue or fullName. Should they or unlike tranShares are those response attributes just not available for some records?

**Comment by evancarter-iex** [comment]
@MorningSleeper it depends on whats recorded. For some transactions like "M", they are part of a (M)ultipart transaction thus its recorded as part of the original transaction. 

For transactions like "A" its a "Grant" which doesnt have a value/price until they are "sold" etc. Hope that helps.

**Comment by MorningSleeper** [comment]
Ok, that helps, thanks for the additional info.
