### ISSUE TITLE
[Data] Symbol AMPY listed twice in Symbols (OTC and NYS)

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1195]
**Clearly describe the data problem**

{
		"symbol": "AMPY",
		"exchange": "NYS",
		"name": "Amplify Energy Corp.",
		"date": "2019-08-13",
		"type": "cs",
		"iexId": "IEX_5636305A50312D52",
		"region": "US",
		"currency": "USD",
		"isEnabled": true
	},
	{
		"symbol": "AMPY",
		"exchange": "OTC",
		"name": "Amplify Energy Corp.",
		"date": "2019-08-13",
		"type": "cs",
		"iexId": "IEX_4437384C4D342D52",
		"region": "US",
		"currency": "USD",
		"isEnabled": true
	},

Data URL (The URL you used to access the data without your token):
https://cloud.iexapis.com/v1/ref-data/symbols?token=

What time did the problem occur (including timezone)?
10:41AM PST

What is the expected behavior?
Symbol is unique in symbols file

Only appears once
What are the steps to reproduce
Run API

Your environment (e.g. browser, OS, API version, language):

Additional context
This has happened with other symbols - please change the symbols call to only return the current value for each symbol. Or either add the exchange value to all calls that have symbol in them

**Comment by evancarter-iex** [comment]
This is resolved.
