### ISSUE TITLE
[Data] Dividend Yield is incorrect in KeyStats

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1196]
**Clearly describe the data problem**
Dividend Yield in Key States is using the ttmDividendRate to calculate DividendYield which is absolutely the wrong way to calculate Dividend Yield. No one uses ttmDividendRate to calculate Dividend Yield. Use the most recent dividend multiplied by 4 (or how many payments per year).

At a closing price of 200.48 for AAPL on August 12 the Dividend Yield (using the current yearly amount of $3.08 at 77 cents  ) should be 0.0153631284916201‬ --> 3.08 / 200.48

The KeyStats is calculating it as  0.014764565043894654  -->2.96 (ttm Rate) / 200.48

{
	"week52change": -0.040168999999999999,
	"week52high": 233.47,
	"week52low": 142,
	"marketcap": 906005206400,
	"employees": 132000,
	"day200MovingAvg": 185.91,
	"day50MovingAvg": 199.62,
	"float": 4512749206.860001,
	"avg10Volume": 39379043.7,
	"avg30Volume": 25484349.3,
	"ttmEPS": 11.83,
	"ttmDividendRate": 2.96,
	"companyName": "Apple, Inc.",
	"sharesOutstanding": 4519180000,
	"maxChangePercent": 205.130117,
	"year5ChangePercent": 1.463761,
	"year2ChangePercent": 0.362525,
	"year1ChangePercent": -0.040169,
	"ytdChangePercent": 0.269504,
	"month6ChangePercent": 0.178047,
	"month3ChangePercent": 0.079474,
	"month1ChangePercent": -0.02305,
	"day30ChangePercent": -0.005309,
	"day5ChangePercent": 0.017665,
	"nextDividendDate": null,
	"dividendYield": 0.014764565043894654,
	"nextEarningsDate": "2019-10-31",
	"exDividendDate": "2019-08-09",
	"peRatio": 17.7,
	"beta": 1.5060612259095585
}

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/aapl/stats?token=

**What time did the problem occur (including timezone)?**
3:30PM EST

**What is the expected behavior?**
Returns the standard calculation for Yield.

**What are the steps to reproduce**
Run API

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**
 1. Change ttmDividendRate to DividendRate (most current rate times 4 or how many payment periods per year)

2. Use that DividendRate to calculate DividendYield

3. I'd use the Dividend API however that has shown to be incomplete and often incorrect

**Comment by McQgit** [comment]
@jesseorosz  I regularly look at the ttm dividend rate.  In some cases it is the only meaningful number.  See prior topic on this issue: https://github.com/iexg/IEX-API/issues/1043#issuecomment-514590932 

That topic also shows how to derive the indicated yield from the most recent.

**Comment by jesseorosz** [comment]
@McQgit - very helpful. thank you!
