### ISSUE TITLE
[Data]Open / Close outside High / Low range

### ISSUE THREAD

**Issue by hmTodd** [iexg/IEX-API#1197]
**Clearly describe the data problem**
There are numerous instances of the Open or Closing price to be outside the High - Low range.  

Is this normal behavior that we need to manage as best we can?  From a very limited sample it appears that when the open is outside the range that the open is often, but not always, incorrect.  When the close is outside the range it appears the range is incorrect.

This may be normal, but I have not experienced it in the past with other vendors.  Just looking for feedback on an odd issue.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/batch?symbols=cnya&types=ohlc&token=pk_
Also on the 'quote' endpoint.

CNYA |  
-- | --
ohlc |  
open |  
price | 26.567
time | 1565703000000
close |  
price | 27.46
time | 1565726400000
high | 27.62
low | 27.19
volume | 45610
symbol | "CNYA"

**What time did the problem occur (including timezone)?**
For past month anyway.  Gathering prices at about 5:00pm ET.

**What is the expected behavior?**
Generally high low range includes open and closing prices.

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
@hmTodd Is this still an issue?

**Comment by hmTodd** [comment]
Yes.  At 5:00 pm ET I updated prices for 2,760 symbols and had 35 where the Close was outside the High/Low range, including the 7 symbols in the url below.  There are 540 where the Open is outside the range.  Thanks for following up.

https://cloud.iexapis.com/stable/stock/market/batch?symbols=ipay,fem,pui,ewza,vigi,vrig,bgrn&types=ohlc&token=XXX

**Comment by hmTodd** [comment]
Anything new on this?  I was doing my own follow up today and found several hundred quotes where the open was outside the high/low range.  The first example on my list was KOMP, an odd ETF but that shouldn't matter.  The OHLC endpoint looks like this:
request:  https://cloud.iexapis.com/stable/stock/komp/ohlc
return:  {"open":{"price":33.72,"time":1569591000151},"close":{"price":33.04,"time":1569614400074},"high":33.56,"low":32.972,"volume":206456,"symbol":"KOMP"}

You can see the OPEN was 33.72 but the HIGH was 33.56.   This request was well after the close and should be the "official" data from the consilidated tape if I understand correctly.  Others have the OPEN at 33.42, including StockCharts, Yahoo, and BarChart.  Google does agree with you at 33.72.  

Thanks,

**Comment by evancarter-iex** [comment]
@hmTodd I am going to reach out to our data source. it doesnt make much sense to me after some investigation. I have some guesses but really need to forward this on to them.

**Comment by evancarter-iex** [comment]
I suspect I know whats going on. Can you send an email to support@iexcloud.io so I can keep you in the loop? I'm going to close this in the meantime.
