### ISSUE TITLE
[Data] AAPL missing from dividends/next

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1198]
**Clearly describe the data problem**
Calling the API for AAPL returns empty

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/aapl/dividends/next?token=

**What time did the problem occur (including timezone)?**
11:45PM PST

**What is the expected behavior?**
Returns value

**What are the steps to reproduce**
Run API

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**
AAPL is paying on August 15 so should have value

**Comment by McQgit** [comment]
@jesseorosz  An IEX person can give definite answer but they likely use the ex-div date which has already past for that AAPL dividend.  Their `/upcoming-dividends` endpoint cuts off by ex-div date so I presume the `next` does as well.

As an aside, I think that's reasonable.  If you buy AAPL today you won't get paid that dividend.  If you owned it before Aug9, you've already earned it.  Ex-div dates are commonly used on api's oriented around trading and prices (like IEX).
