### ISSUE TITLE
[Request] For datasets with bugs do not count against monthly quota

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1199]
**Is your feature request related to a problem? Please describe.**
Yes - ongoing incomplete data for dividends

**Describe the solution you'd like**
Several data sets have had ongoing issues every since release - like dividends. It's extremely frustrating to download the entire data set, look through it for issues, find issues, report on GitHub, receive no response, and then repeat. And every time those calls counting against your monthly quota.

So for data sets with known issues, like dividend, reduce the cost to 0.

**Describe alternatives you've considered**

**Additional context**

**Comment by evancarter-iex** [comment]
Closing. Dividends have been replaced. If there is additional dataset issues please reach out to support@iexcloud.io
