### ISSUE TITLE
Request to raise maximum stocks on stocks endpoint

### ISSUE THREAD

**Issue by jrseriel** [iexg/IEX-API#12]
Would it be at all possible to raise the maximum stocks that can be gathered from 25 to say, 50 or more? 

The reason being is that only pulling 25 doesn't even fill a screen top to bottom not to mention for large portfolios making multiple calls for close to real time accuracy can be very heavy on the server end.

**Comment by yccheok** [comment]
@jrseriel 

Sorry. It might out of topic. But, may I know how do you query for 25 stocks at 1 time?

As, the API end point I know, can only support 1 stock.

https://api.iextrading.com/1.0/stock/aapl/quote

**Comment by jrseriel** [comment]
@yccheok 

One of the developers mentioned it in a previous post. For a batch call to the api for multiple quotes the endpoint would look something like...

https://api.iextrading.com/1.0/stock/market/batch?types=quote,news&symbols=aapl,nflx,fb

**Comment by yccheok** [comment]
Didn't find it in documentation.

However, I do notice this thread : https://github.com/iexg/IEX-API/issues/7

Thanks.

**Comment by yccheok** [comment]
https://iextrading.com/developer/docs/#tops would be able to return last price for all stocks. However, I guess it only return last price transacted through IEX

quote end point returns 15 min delayed (which I guess include aggregation from other stock exchanges). But, it can only return 25 per call.

**Comment by joshuablackburn-iex** [comment]
We are working on the documentation today.  It'll show how to make multiple calls, and we've increased the symbol limit from 25 to 100.

**Comment by joshuablackburn-iex** [comment]
Documentation has been updated.
