### ISSUE TITLE
Adding current day's high & low to stock/{symbol}/book endpoint

### ISSUE THREAD

**Issue by fimmugit** [iexg/IEX-API#120]
## Summary
need more fields in stock/{symbol}/book endpoint

## Details
Initially, I requested an API enhancement to include these fields:
open, high, low, prev_close, volume, last_price, last_size, last_time, asks[], bids[]
But the issue was partially solved with some missing fields： high & low.

Note that the high & low are not the high & low of a single bar (e.g. 1-min, 5-min). They are the high & low counted from the open up to the moment quotes are generated.

### Date/time of issue
Sept 19, 2017 opened
Sept 20, 2017 closed by developer

### API URL
stock/{symbol}/book endpoint

### What you expected to happen
Whenever possible:
I like to add current day's running high & low, in addition to other fields listed;
Allow multiple symbols (like 10 or 50) in one call to reduce the number of requests if not too much to ask (**something similar to /stock/market/previous**).

### What actually happened
It returns most fields I listed for a single symbol. There is no day's running high and low.
I really appreciate the hard works from the developer and wish he could do a little more to return the information I need in a single call.

**Comment by Harmonium** [comment]
I agree! I need the same informations but would like to have it in the /stock/{symbol}/quote API call.

**Comment by fimmugit** [comment]
You can do that by entering one symbol even with an API that accepts multiple symbols

**Comment by Harmonium** [comment]
I meant to have the High and low too in that call! I use that call.

FG

**Comment by fimmugit** [comment]
Would be nice to have a versatile call to accept one to many symbols

**Comment by joshuablackburn-iex** [comment]
High low was discussed in #47 and is on the way.  Multiple symbols is already available by using batch requests  https://iextrading.com/developer/docs/#batch-requests
