### ISSUE TITLE
[Issue] Historical Prices - chartCloseOnly returns unadjusted data for 1 date

### ISSUE THREAD

**Issue by rayshan** [iexg/IEX-API#1200]
**Clearly describe the problem**

Calling

https://sandbox.iexapis.com/v1/stock/AAPL/chart/date/20190220?token={{token}}&chartCloseOnly=true&chartByDay=true

Returns

```json
[
    {
        "date": "2019-02-20",
        "uClose": 174.99,
        "uOpen": 179.6,
        "uHigh": 175.8,
        "uLow": 177.07,
        "uVolume": 27387223,
        "close": 173.56,
        "open": 171.27,
        "high": 178.74,
        "low": 177.81,
        "volume": 26525681,
        "change": 1.1,
        "changePercent": 0.6544,
        "label": "Feb 20, 19",
        "changeOverTime": 0.006445
    }
]
```

**What time did the problem occur? (with timezone)**

8-14-19 midnight pacific

**What is the expected behavior?**

Per API docs: "Will return adjusted data only with keys date, close, and volume."

**Comment by Itsme23333** [comment]
If you are parsing your response as JSON instead of parsing it as text then this should not be a problem.
