### ISSUE TITLE
closeTime and openTime is null for all assets

### ISSUE THREAD

**Issue by bartclaeys** [iexg/IEX-API#1202]
`closeTime` and `openTime` is null for all assets (on free plan), not only NASDAQ assets, but also assets on New York Stock Exchange.

https://cloud.iexapis.com/stable/stock/market/batch?symbols=T,F,IBM&types=quote&range=1m&token=<YOUR TOKEN>

**Comment by evancarter-iex** [comment]
@bartclaeys Unfortunately due to UTP requirements, we are unable to distribute that information (even for non nasdaq assets) to non paying customers.

**Comment by bartclaeys** [comment]
Makes sense, would be great if that would be communicated in the API doc.

**Comment by evancarter-iex** [comment]
@bartclaeys Hmm I thought that was added but Ill check
