### ISSUE TITLE
[Request] Retrieving data on preferred shares

### ISSUE THREAD

**Issue by jason-vanderzalm** [iexg/IEX-API#1203]
I can't seem to retrieve data on preferred shares. For example making a request to:

https://cloud.iexapis.com/stable/stock/ala-CT/quote/symbols

Works fine, and returns info on Altagas common shares, on the TSX. but I can't seem to request a quote for any of Altagas' preferred shares (unless I perhaps just don't know how the symbol should be formatted). Normally the symbol used would be ala.pr.a or ala-pr-a (https://web.tmxmoney.com/quote.php?qm_symbol=ALA.PR.A), but when I try that, ie: 

https://cloud.iexapis.com/stable/stock/ala.pr.a-CT/quote/symbols

I just get "Unknown symbol". Any thoughts?

**Comment by McQgit** [comment]
See prior thread on that issue: https://github.com/iexg/IEX-API/issues/1138  

Yours adds the twist of the Toronto exchange but that may get you closer.

**Comment by evancarter-iex** [comment]
Just to close the loop on this. The symbol in this case is:

ALA-PA-CT

You can get the Canada symbols list by hitting this url:

https://cloud.iexapis.com/stable/ref-data/region/ca/symbols

**Comment by jason-vanderzalm** [comment]
I ended up using a different service to retrieve this info, since I hadn't heard anything back. But thanks for the reply.
