### ISSUE TITLE
SPLIT api does not return any data

### ISSUE THREAD

**Issue by lvca** [iexg/IEX-API#1204]
**Clearly describe the problem**
Any call to split API returns an empty array

**What time did the problem occur? (with timezone)**
12:05 Central USA

**What is the expected behavior?**
No split are returned. Tried with multiple stocks.

**Your environment (e.g. browser, OS, API version, language):**
CURL

**API URL (if applicable)**
curl "https://cloud.iexapis.com/stable/stock/JNUG/splits/2y?token=XXX"

**What are the steps to reproduce the bug?**
Type the url above with a valid token

**Additional context**

**Comment by evancarter-iex** [comment]
@ivca Per the documentation: Splits prior to last reported are only included with paid subscription plans. 

We also do not currently have splits for ETF but are working on that.
