### ISSUE TITLE
[Data] When I use /stock/v/chart/1mm some days are missing

### ISSUE THREAD

**Issue by BrianARice** [iexg/IEX-API#1207]
Right now if I call the url below... 7/25/2019 is missing any data... of course holidays would be missing... but it seems like other days are missing too.

https://cloud.iexapis.com/stable/stock/v/chart/1mm?token=

Attached are my json results from a call that was made on 8/15/2019 at 5:00pm CST.

[result.txt](https://github.com/iexg/IEX-API/files/3507408/result.txt)

**Comment by evancarter-iex** [comment]
@BrianARice Im seeing the 25th in there? Can you recheck?

**Comment by BrianARice** [comment]
It's there now... but if I see other missing dates I'll report back.
