### ISSUE TITLE
Sse - Broken TOPs message (JSON)

### ISSUE THREAD

**Issue by rmantovani** [iexg/IEX-API#1208]
**Clearly describe the problem**
We are receiving messages from SSE and JSON came broken.

**What time did the problem occur? (with timezone)**
São Paulo UTC -3 - [2019-08-16 15:07:57.932

**What is the expected behavior?**
receive the full json

**Your environment (e.g. browser, OS, API version, language):**
Linux - Java 

**API URL (if applicable)**
	
https://cloud-sse.iexapis.com/stable/tops?token=TOKEN&symbols=XLB, IVZ

**What are the steps to reproduce the bug?**

**Additional context**

**Sample** :  
[{"symbol":"XLB","sector":"miscellaneous","securityType":"et","bidPrice":56.5900,"bidSi

**Sample 2** : 

[{"symbol":"IVZ","sector":"finance","securityType":"cs","bidPrice":15.6700,"bidSize":301,"askPrice":0.0000,"askSize":0,"lastUpdated":1

**Comment by evancarter-iex** [comment]
@rmantovani Hi there, I have been working heavily with these endpoints and havent seen this issue. Is it constant?

**Comment by rmantovani** [comment]
@evancarter-iex  I noticed this bug last Wednesday, persisted on Thursday and Friday happening a few times in the afternoon.

**Comment by evancarter-iex** [comment]
@rmantovani We arent seeing any issues on our end.
