### ISSUE TITLE
[Data] Close price issue after midnight on fridays

### ISSUE THREAD

**Issue by ohlhaver** [iexg/IEX-API#1209]
**All closing prices on your website and via you API are completely off at the moment.**

For example AAPL is showing a $201.74 closing price for Friday 4PM EST 
when in reality it is $206.5 on NASDAQ.

AAPL on IEX: https://iextrading.com/apps/stocks/AAPL

AAPL on Yahoo Finance: https://finance.yahoo.com/quote/AAPL?p=AAPL&.tsrc=fin-srch

This is true also for you API and SSE output and for ALL other stocks!!!

Can this please be fixed immediately?

**Comment by ohlhaver** [comment]
The prices have been wrong for over 12 hours now.  Can someone please address this? 

Is there no one on call to fix something like this even at night or on weekends?

**Comment by ohlhaver** [comment]
UPDATE: It has been fixed now. Thanks. However, ALL stock prices (closing prices, i.e. latest regular prices) were wrong for over 12 hours. Could someone please address this? 

You are charging for this service and we - as I am sure many more of your clients - have paying users who rely on the data. I don't think it's too much to ask that things like this should not happen and if do they definitely should not remain unfixed and unaddressed for over 12 hours. 

Could you please have some monitoring/warning systems in place and someone on call to react & fix swiftly no matter what time of the night or day of the week?

Thanks!

**Comment by oxydaemon** [comment]
The data is useless if it is not accurate
