### ISSUE TITLE
1d chart returns datas that should not

### ISSUE THREAD

**Issue by Harmonium** [iexg/IEX-API#121]
## Summary

We receive informations that we should not.

## Details

We receive a lot of datas that the values are 0 or -1 and we should not. We have to filter the informations to avoid to display wrong informations.

### Date/time of issue

November 28th, 2017

### API URL

api.iextrading.com/1.0/stock/aapl/chart/1d

### What you expected to happen
    "label" : "10:30 AM",
    "low" : 173.90000000000001,   --> No 0 here
    "average" : 173.922,    --> No -1 here
    "numberOfTrades" : 5,   --> No 0 here
    "date" : "20171128",
    "volume" : 735,   --> No 0 here
    "changeOverTime" : -0.0016417156502571716,
    "high" : 173.935,   --> No 0 here
    "minute" : "10:30",
    "notional" : 127832.55.  --> No 0 here

### What actually happened
    "label" : "10:29 AM",
    "low" : 0,
    "average" : -1,
    "numberOfTrades" : 0,
    "date" : "20171128",
    "volume" : 0,
    "changeOverTime" : -1.0057402645113886,
    "high" : 0,
    "minute" : "10:29",
    "notional" : 0

**Comment by evancarter-iex** [comment]
This is fixed in iexcloud. https://iexcloud.io
