### ISSUE TITLE
Historical Treasuries Data Issue

### ISSUE THREAD

**Issue by oxydaemon** [iexg/IEX-API#1210]
According to https://portal.productboard.com/iexcloud/1-iex-cloud-roadmap/tabs/3-deployed-and-available, Treasuries Historical Data is deployed since 30th April

I can see the endpoints listed in https://iexcloud.io/docs/api/#v1 for the current daily Treasuries data, and I can successfully get data out for the current day, however I can't see any way to access the historical data.

**Comment by oxydaemon** [comment]
Hi IEX Team, can I get some comment on this issue?

**Comment by evancarter-iex** [comment]
@oxydaemon Hi there, we currently only offer current treasury data. I will fix the description in the roadmap. Thanks.
