### ISSUE TITLE
[Issue] The /stats endpoint is missing `year5ChangePercent` for certain stocks

### ISSUE THREAD

**Issue by saadq** [iexg/IEX-API#1211]
**Clearly describe the problem**
Some stocks, such as `WORK`, have no `year5ChangePercent` field when using the `/stats` API. 

**What time did the problem occur? (with timezone)**
N/A

**What is the expected behavior?**
The field should exist.

**Your environment (e.g. browser, OS, API version, language):**
N/A

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/work/stats?token=<TOKEN>

**What are the steps to reproduce the bug?**
Look at the JSON response for the above endpoint and see that the `year5ChangePercent` field is missing from the response.

**Additional context**
N/A

**Comment by joshuablackburn-iex** [comment]
WORK just went IPO. They don't have 5 years of data.
