### ISSUE TITLE
[Issue] Authentication not working according to docs for '/ref-data/isin'.

### ISSUE THREAD

**Issue by anback** [iexg/IEX-API#1212]
**Clearly describe the problem**
401 back when POSTing to '/ref-data/isin'. Token used is verified working on other requets (GET requests). 

**What time did the problem occur? (with timezone)**
07:47:00 CET

**What is the expected behavior?**
200

**Your environment (e.g. browser, OS, API version, language):**
https://cloud.iexapis.com/stable

**API URL (if applicable)**
/ref-data/isin

**What are the steps to reproduce the bug?**
Call /ref-data/isin with token in your post body.

**Additional context**
From what i can see /ref-data/isin is the only endpoint that has token in body. Perhaps this is not working according to docs. See pic. Probably there is something more to this. Do you need to sign the token perhaps ? (if you could give me a curl that works according to doc i would be super glad, however i dont think you can. There is something wrong with the docs)

![image](https://user-images.githubusercontent.com/2440382/63242010-106bff80-c256-11e9-8bdf-19bb8c2a9a80.png)

**Comment by joshuablackburn-iex** [comment]
What library are you using to do the HTTP call?

There is a GET request version of the endpoint. Just call /ref-data/isin?token=TOKEN&isin=ISIN,ISIN,ISIN

**Comment by anback** [comment]
Alright it says post in the docs. il ltry the get version asap

**Comment by anback** [comment]
@joshuablackburn-iex  akright the get version is confirmed working, you should really change your docs, the post version confused me a lot. Thx for the support! :) 

Cheers
Anders
