### ISSUE TITLE
[Issue] /crypto/{symbol}/quote changed data type (IEX Cloud)

### ISSUE THREAD

**Issue by sqaxomonophonen** [iexg/IEX-API#1213]
Around 2019-08-19 16:44 UTC you changed the data format of `/v1/crypto/{symbol}/quote`; the `latestPrice` field changed type from a JSON Number to a number-like String. Our software blew up because strings are not numbers in sane programming languages, so could you do one of the following (in order of preference):
 - make a public and stable JSON schema for endpoints, and validate responses against them?
 - never change the data types of responses? (especially `/v1/*` and `/stable/*`)
 - clearly state in the documentation that everything is loosely typed ("numbers can be strings, null, etc")?

**Comment by joshuablackburn-iex** [comment]
Understand your frustration and apologize for the issue. We added an additional exchange which apparently reports in strings. We will update our docs in the coming days.

**Comment by thinkcodellc** [comment]
Please fix the crypto issue. Now even the volume, open/close seem to be null. Thanks

**Comment by joshuablackburn-iex** [comment]
We are close to providing broad support for cryptocurrency. The current endpoint was a carry over from the old API. It is likely we will provide all prices and quantities as strings to avoid floating point issues. This will be consistent with most crypto exchanges.
