### ISSUE TITLE
The possible values and/or format for Data Timing, Schedule, Sources

### ISSUE THREAD

**Issue by wyattbiker** [iexg/IEX-API#1214]
You have a description of

>  Data Weighting,

 but no description that I could find of:

> Data Timing
> Data Schedule
> Data Source(s)

What are the possible values and formats?

Thanks!

**Comment by joshuablackburn-iex** [comment]
Can you please provide more information? Where do you see Data Timing, Data Schedule, etc? Are you looking at the docs or the result of an endpoint?

**Comment by wyattbiker** [comment]
In the docs. Here is an example for Price:

https://iexcloud.io/docs/api/#price

I see examples, but what are the values/formats (in case I need to parse them)

> Data Timing
> realtime 15min delayed End of day
> 
> Data Schedule
> 4:30am-8pm ET Mon-Fri
> 
> Data Source(s)
> Primary Partner Investors Exchange Consolidated Tape
