### ISSUE TITLE
Executing Batch Quote with Dividends and Range Only Returns Oldest Dividend in Range

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#1215]
**Clearly describe the problem**
If I request a batch quote with dividends and a range, the API only returns the oldest dividend in the range rather than all dividends in the range.

**What time did the problem occur? (with timezone)**
2019-08-21 07:32 (Eastern)

**What is the expected behavior?**
Requesting a batch quote with dividends and a range should return all dividends declared within the range rather than only the oldest dividend declared.

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Mac OS, UNIX, v1, PHP

**API URL (if applicable)**
https://cloud.iexapis.com/V1/stock/market/batch?types=quote,dividends&symbols=acc,aceix, acn, adp, aee&token=MY_TOKEN&range=2y

**What are the steps to reproduce the bug?**
Simply execute provided API call
[2019-08-21 Sample Dailies.txt](https://github.com/iexg/IEX-API/files/3525101/2019-08-21.Sample.Dailies.txt)

**Additional context**

**Comment by evancarter-iex** [comment]
@GraceRg Are you a free user?

**Comment by GraceRg** [comment]
Evan, 
Yes, I have a free account.

**Comment by evancarter-iex** [comment]
The free account only includes the latest dividend as stated in the documentation

________________________________

**Comment by GraceRg** [comment]
Evan,
If a range is included in the API call the API is not returning the latest dividend. It is returning the oldest dividend that would have appeared in the range.

**Comment by marekk657** [comment]
@GraceRg +1
It's the same issue is with /dividend endpoint also.

Examples:
https://cloud.iexapis.com/stable/stock/pfe/dividends?token=TOKEN&range=ytd
returns:
```
[
  {
    "exDate": "2019-01-31",
    "paymentDate": "2019-03-01",
    "recordDate": "2019-02-01",
    "declaredDate": "2018-12-14",
    "amount": 0.36,
    "flag": "Increase",
    "currency": "USD",
    "description": "Pfizer Hikes Quarterly Dividend 5.88%",
    "frequency": "Quarterly",
    "date": "2019-08-29"
  }
]
```

while https://cloud.iexapis.com/stable/stock/pfe/dividends?token=TOKEN&range=3m
returns:
```
[
  {
    "exDate": "2019-08-01",
    "paymentDate": "2019-09-03",
    "recordDate": "2019-08-02",
    "declaredDate": "2019-06-27",
    "amount": 0.36,
    "flag": "No Change QoQ",
    "currency": "USD",
    "description": "Pfizer Declares Quarterly Dividend of $0.36 Per Share",
    "frequency": "Quarterly",
    "date": "2019-08-29"
  }
]
```

I would expect that ytd range returns the same result as 3m, for free user.

**Comment by davidh71** [comment]
I see the same behavior on the free account.  What is the recommended way to get the last dividend?

**Comment by evancarter-iex** [comment]
This is fixed.
