### ISSUE TITLE
[Issue] Sandbox should not randomize enum strings

### ISSUE THREAD

**Issue by neomantra** [iexg/IEX-API#1216]
**Is your feature request related to a problem? Please describe.**

The Sandbox environment randomizes enum strings.  While data randomization for a sandbox makes total sense, enums should be more "smartly" randomized.

For example, `announceTime` in `/earnings` and `/estimate` is specified to only be `BTO`, `DMT`, or `AMC`.   But randomization is outputting `MAC`, `CMA`, etc.

That makes it hard to test code -- if one tries to validate the message (e.g. for proper enums), most of the responses will be rejected.   

It's annoying as a developer (wading through those errors) and we also have to hit your sandbox environment more than necessary to get a corpus of valid messages.

**Describe the solution you'd like**

Ideally, if you wanted to randomize an enum field, you would pick randomly from the possible values, not scramble the enum values themselves.  It seems like you do that with date fields -- the random date strings with valid dates.

**Describe alternatives you've considered**

So far, I just accept a bunch of validation failures in testing / development.  It's not a showstopper, just very inconvenient.

**Additional context**

Related to #868.  Otherwise, enjoying the product so far :)

**Comment by vslee** [comment]
I would also like to request the de-obfuscation of a few more enum strings:

- endpoint Dividends (Basic): `flag` ("Dividend income", "Cash", ...), `frequency` ("quarterly")

**Comment by timpaine-iex** [comment]
This will be deployed today, I will close the issue when it is available
