### ISSUE TITLE
Dividends data is missing when making a batch request call

### ISSUE THREAD

**Issue by jakdock** [iexg/IEX-API#122]
## Summary

Dividends data is missing when making a batch request call.

## Details

When making this call, the dividends data is missing in the return:
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl&types=financials,splits,dividends,earnings&range=5y
[![Screenshot from Gyazo](https://gyazo.com/cff559a09050b4a65cb6f72da8570245/raw)](https://gyazo.com/cff559a09050b4a65cb6f72da8570245)

However, when "splits" is removed, dividends data is available:
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl&types=financials,dividends,earnings&range=5y
[![Screenshot from Gyazo](https://gyazo.com/92db04aad31c76038ac4be1f79d0a3ad/raw)](https://gyazo.com/92db04aad31c76038ac4be1f79d0a3ad)

### Date/time of issue

2017-11-29 00:30 CST

**Comment by payne92** [comment]
+1  Just ran into this bug/issue myself.  

When the "splits" type is present in a batch request, the dividends list returned is empty.

**Comment by rodoabad** [comment]
Just letting the team know that this i still not fixed. Any updates @jcape? In order to get `splits` and `dividends` we have to make two calls.
