### ISSUE TITLE
Image url's for news often come back as "Not Found"

### ISSUE THREAD

**Issue by BrianARice** [iexg/IEX-API#1224]
When I get news from, for example, this url...

https://cloud-sse.iexapis.com/stable/stock/nflx/news/last?token=

Many of the image url's get a response of Not Found... for example:

https://cloud.iexapis.com/v1/news/image/6dadf226-0fc7-4c34-b07e-42230bb01ab9 (not found)
https://cloud.iexapis.com/v1/news/image/535178eb-aca9-4886-9f37-da9643c61d47 (worked)
https://cloud.iexapis.com/v1/news/image/adb7bfef-6703-4e64-b097-1c802b01d971 (not found)

Any idea what the problem is?

- Brian

--- full response below ---

[{"datetime":1566423921000,"headline":"Netflix (NFLX) Stock Sinks As Market Gains: What You Should Know","source":"Zacks Investment Research","url":"https://cloud.iexapis.com/v1/news/article/6dadf226-0fc7-4c34-b07e-42230bb01ab9","summary":"Netflix (NFLX) closed at $297.81 in the latest trading session, marking a -0.39% move from the prior day.","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/6dadf226-0fc7-4c34-b07e-42230bb01ab9","lang":"en","hasPaywall":false},{"datetime":1566249540000,"headline":"'Chinese Netflix' iQiyi passes 100 million subscribers, but stock plunges more than 10%","source":"MarketWatch","url":"https://cloud.iexapis.com/v1/news/article/535178eb-aca9-4886-9f37-da9643c61d47","summary":"iQiyi Inc. , a streaming platform in China commonly compared with Netflix Inc. in the U.S., passed the 100-million-subscriber milestone in an earnings report…","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/535178eb-aca9-4886-9f37-da9643c61d47","lang":"en","hasPaywall":false},{"datetime":1565962223000,"headline":"Why Is Netflix (NFLX) Down 9.1% Since Last Earnings Report?","source":"Zacks Investment Research","url":"https://cloud.iexapis.com/v1/news/article/3d60c7e4-42ac-4335-8ff2-0a7ba905f28a","summary":"Netflix (NFLX) reported earnings 30 days ago. What's next for the stock? We take a look at earnings estimates for some clues.","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/3d60c7e4-42ac-4335-8ff2-0a7ba905f28a","lang":"en","hasPaywall":false},{"datetime":1565621640000,"headline":"Netflix (NFLX) Inks Deal With Game of Thrones Creators","source":"Zacks Investment Research","url":"https://cloud.iexapis.com/v1/news/article/adb7bfef-6703-4e64-b097-1c802b01d971","summary":"Netflix's (NFLX) original content portfolio is set to get a boost with Game of Thrones creators Benioff and Weiss coming on board to produce films and series for the platform.","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/adb7bfef-6703-4e64-b097-1c802b01d971","lang":"en","hasPaywall":false},{"datetime":1565348280000,"headline":"Netflix snags ‘Game of Thrones’ creators away from HBO in mega-deal","source":"MarketWatch","url":"https://cloud.iexapis.com/v1/news/article/77364951-a040-4d13-995b-52b1f93a44d0","summary":"The Emmy Award-winning creators of “Game of Thrones” have landed at Netflix Inc. in a deal reportedly worth between a $200 million to $300 million to create…","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/77364951-a040-4d13-995b-52b1f93a44d0","lang":"en","hasPaywall":false},{"datetime":1565049600000,"headline":"Disney’s Firing On All Cylinders, But Is It Sustainable?","source":"Investing.com","url":"https://cloud.iexapis.com/v1/news/article/ded655e7-0578-452e-9691-43be25eef7ab","summary":"Stocks Analysis by Investing.com (Clement Thibault/Investing.com) covering: Walt Disney Company, Netflix Inc. Read Investing.com (Clement Thibault/Investing.com)'s latest article on Investing.com","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/ded655e7-0578-452e-9691-43be25eef7ab","lang":"en","hasPaywall":false},{"datetime":1565046281000,"headline":"Tech's 5 FAANG stocks just saw $150 billion of their market value vaporized, and Apple is reeling the hardest (FB, AAPL, AMZN, NFLX, GOOG)","source":"Business Insider","url":"https://cloud.iexapis.com/v1/news/article/6c0be3b3-f708-489f-a7ff-ed837b0133f7","summary":"Shares of Facebook, Apple, Amazon , Netflix and Google — known as the FAANG stocks— tumbled as China hit back at the US after the Trump Administration said it planned new tariffs. Apple took the biggest hit as its share fell 5% on worries that the new tariffs are a \"potential gut punch\" for the iPhone maker. The plunge represented $53 billion in market value. The FAANG market cap losses totaled $150 billion, the value of a company bigger than either Costco or IBM . Click here for more BI Prime stories. The giants of the US tech industry shed $150 billion in market value on Monday, as China hit back in an escalating trade war with the US. The lost market value is the equivalent of a company the size of Costco or IBM instantly evaporating into thin air, a sobering sign of how the raging trade tit-for-tat is rattling Wall Street. For tech companies, which are heavily reliant on China for components and manufacturing of their products, the trade war is especially concerning. The battle heated up after China let its currency, the yuan, weaken to below 7 to a dollar on Monday, in response to the Trump Administration's recent announcement that it will impose new tariffs on Chinese goods .","related":"NDAQ,NFLX","image":"https://cloud.iexapis.com/v1/news/image/6c0be3b3-f708-489f-a7ff-ed837b0133f7","lang":"en","hasPaywall":false,"symbol":"NDAQ"},{"datetime":1564583798000,"headline":"Facebook approaches Netflix, Disney to support TV chat device: The...","source":"Reuters","url":"https://cloud.iexapis.com/v1/news/article/a46289a9-d734-46b4-a77e-122a4ce79bb5","summary":"Facebook Inc has approached Netflix Inc, Walt Disney Co and other media companies about putting their streaming services on a new Facebook device for making video calls from televisions, The Information reported on Wednesday.","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/a46289a9-d734-46b4-a77e-122a4ce79bb5","lang":"en","hasPaywall":false},{"datetime":1564455644000,"headline":"Three ex-bankers win Netflix backing to shake up Bollywood","source":"The Economic Times India","url":"https://cloud.iexapis.com/v1/news/article/e992dd4e-0ae9-4fd8-9660-94c7811c4e32","summary":"By Saritha RaiA tiny digital studio is making a name for itself in the world’s most prolific movie industry, scoring funding from a marquee Silicon Valley investor right after nailing a deal to stream its most popular show on Netflix.Pocket Aces Pvt has raised $14.7 million from Sequoia Capital, DSP Group, 3one4 Capital and others to bankroll content aimed at pushing Indian shows beyond hackneyed Bollywood formulas -- like “saas-bahu” or mother-in-law versus daughter-in-law dramas. It’s one of a band of startups moving away from familiar staples to try and hook an exploding population of mobile viewers. Pocket Aces plans to use the funds to get into gaming content, make strategic acquisitions and boost production to 30 shows a year from the current dozen.India has become a battleground for global streaming giants from Netflix Inc. to Amazon.com Inc. and Walt Disney Co.-owned Hotstar. They’re drawn by a market that could hit 829 million smartphone users by 2022, compared with about half a billion now, according to Cisco Systems Inc. estimates, many of them first-time Internet users consuming entertainment via their mobiles.Last week, Netflix raised the stakes, announcing one of the world’s cheapest streaming subscriptions: an under-$3 monthly mobile-only plan for India.","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/e992dd4e-0ae9-4fd8-9660-94c7811c4e32","lang":"en","hasPaywall":false},{"datetime":1564435920000,"headline":"Netflix places a big bet on big-budget movies","source":"MarketWatch","url":"https://cloud.iexapis.com/v1/news/article/c78ab510-1e76-4b99-b0b4-eaf161cf13b0","summary":"Netflix Inc. is spending hundreds of millions of dollars to produce big-budget films as it tries to shore up its subscriber base and push further into…","related":"NFLX","image":"https://cloud.iexapis.com/v1/news/image/c78ab510-1e76-4b99-b0b4-eaf161cf13b0","lang":"en","hasPaywall":false}]

**Comment by timpaine-iex** [comment]
duplicate https://github.com/iexg/IEX-API/issues/879
