### ISSUE TITLE
[Data] Market Cap missing for some ETFs

### ISSUE THREAD

**Issue by dylanitorium** [iexg/IEX-API#1226]
**Clearly describe the data problem**
Market Cap value for the following symbols returns zero:

XLK, VGT, IYW, MJ, ICLN, PBW, QCLN, SHE

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/XLK/quote
https://cloud.iexapis.com/stable/stock/VGT/quote
https://cloud.iexapis.com/stable/stock/IYW/quote
https://cloud.iexapis.com/stable/stock/MJ/quote
https://cloud.iexapis.com/stable/stock/ICLN/quote
https://cloud.iexapis.com/stable/stock/PBW/quote
https://cloud.iexapis.com/stable/stock/QCLN/quote
https://cloud.iexapis.com/stable/stock/SHE/quote

**What time did the problem occur (including timezone)?**
On Going (Currrent time 9:52 am Pacific/Auckland)

**What is the expected behavior?**
A market cap value exists that is not zero

**What are the steps to reproduce**
Visit the URL

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Ubuntu, V1, JS/Ruby

**Additional context**

**Comment by dylanitorium** [comment]
I think we are after net asset value, however since ETF quotes are
available on the same end point I’d either expect a net asset value key in
the response or have the value populated in the market cap key, or
alternatively in the stats endpoint.

If they can’t provide that they can let us know and we can look at other
ways we can sort our ETFs.

As a side note, some of the ETFs I listed have market cap values available
in Google.

**Comment by evancarter-iex** [comment]
This is fixed.
