### ISSUE TITLE
IEXOnly Symbols

### ISSUE THREAD

**Issue by jimskin** [iexg/IEX-API#1227]
I have been informed by our developers that certain symbols (e.g BABA) are not available when using the 'IEXOnly=true' parameter. Is this the case?

We are using the following endpoints:

Real-time - https://cloud-sse.iexapis.com/stable/stocksUSNoUTP?symbols=aapl&token=*******&chartIEXOnly=true

Historical - https://cloud.iexapis.com/beta/stock/aapl/intraday-prices?token=********&chartIEXOnly=true

**Comment by jimskin** [comment]
Any support?

**Comment by evancarter-iex** [comment]
@jimskin I'm sorry, what exactly is the issue?

**Comment by evancarter-iex** [comment]
@jimskin https://cloud.iexapis.com/stable/stock/baba/intraday-prices?chartIEXOnly=true&token works fine here

And the real time endpoint https://cloud-sse.iexapis.com/stable/stocksUSNoUTP?symbols=aapl&token=******* doesnt support chartIEXOnly=true if you want only IEX data for streaming, use the tops streaming endpoint

**Comment by jimskin** [comment]
I'm trying to find out what symbols are available when using the IEX Only parameter. I have been told that some symbols are not available. Is that correct?

**Comment by evancarter-iex** [comment]
@jimskin All 8000+ NMS symbols are traded on IEX. So if its traded that day on IEX you will receive data back using the chartIEXOnly=true. Its possible in lightly traded symbols that you might not have trades on IEX during that time period and IEXOnly parameter wouldnt return anything.

**Comment by jimskin** [comment]
> And the real time endpoint https://cloud-sse.iexapis.com/stable/stocksUSNoUTP?symbols=aapl&token=******* doesnt support chartIEXOnly=true if you want only IEX data for streaming, use the tops streaming endpoint> 

Unfortunately, we cant use that endpoint. You can't build a real-time (current) bar on a chart by polling that API. It's not accurate. So we have to use the SSE streaming endpoint.
