### ISSUE TITLE
[Issue] Data for Forex - USDINR Incorrect

### ISSUE THREAD

**Issue by thinkcodellc** [iexg/IEX-API#1229]
**Clearly describe the problem**
Forex quote from the endpoint
https://cloud.iexapis.com/stable/fx/rate/USD/INR?token=<token> yields the same incorrect values

**What time did the problem occur? (with timezone)**
Has been occuring over a week

**What is the expected behavior?**
Right values be displayed

**Your environment (e.g. browser, OS, API version, language):**
Chrome browser on Win 10

**API URL (if applicable)**
https://cloud.iexapis.com/stable/fx/rate/USD/INR?token=<token>

**What are the steps to reproduce the bug?**
Invoke the URL

**Additional context**
The quote data is incorrect and has been stuck at the same level of 70 for days. EOD data also not matching upto what is being returned.

Its extremely disappointing to note that the quality of data for 
1. Forex is low with no useful refresh other than end of day data - which is wrong!
2. Crypto data has OHLC data missing & so is the volume missing
3. News for Crypto symbols are not available.

It does not make any sense to pay for subscription, when the key data that we are paying for is missing or incorrect!

**Comment by evancarter-iex** [comment]
@thinkcodellc We have launched updated Forex including streaming which has a lot more detailed granularity. We also launched a lot more crypto information including book and events.
