### ISSUE TITLE
When does chart data get updated?

### ISSUE THREAD

**Issue by darose** [iexg/IEX-API#123]
## Summary

I've been starting to use the IEX API data - great stuff!  Thanks so much for providing this service to the community!

I have some code that downloads a subset of the day's closing prices, using the chart API.  (E.g., https://api.iextrading.com/1.0/stock/AAPL/chart/1m)  Just wondering:  at (approximately) what time of day does the chart API get updated with the current day's closing prices?  My downloads are triggered by a timer, and I want to make sure I don't try to download the data before it's available.

**Comment by joshuablackburn-iex** [comment]
Prices should be updated by 2am EST.
