### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by t2lt** [iexg/IEX-API#1232]
**Clearly describe the problem**
I'm trying to get 15 years of OHLC with get_historical_data method of iexfinance and I get an error "ValueError: Invalid date specified. Must be within past 5 years.". 

**What time did the problem occur? (with timezone)**
N/A

**What is the expected behavior?**
I have a paid account Launch tier, so I must be able to have access to 15 years of historical data. 

**Your environment (e.g. browser, OS, API version, language):**
N/A

**API URL (if applicable)**
get_historical_data method of iexfinance

**What are the steps to reproduce the bug?**
N/A

**Additional context**
N/A

**Comment by t2lt** [comment]
Update: 
fixed by changing _URLS in iexfinance/__init__.py to https://cloud.iexapis.com/stable/"
and in iexfinance/stocks/historical.py
        if self.single_day is True:
            return "date"
        delta = datetime.datetime.now().year - self.start.year
        if 2 <= delta <= 5:
            return "5y"
        elif 1 <= delta <= 2:
            return "2y"
        elif 0 <= delta < 1:
            return "1y"
        else:
            raise ValueError(
                "Invalid date specified. Must be within past 5 years.")
to
        if self.single_day is True:
            return "date"
        delta = datetime.datetime.now().year - self.start.year
        if 5 <= delta <= 15:
            return "max"
        if 2 <= delta <= 5:
            return "5y"
        elif 1 <= delta <= 2:
            return "2y"
        elif 0 <= delta < 1:
            return "1y"
        else:
            raise ValueError(
                "Invalid date specified. Must be within past 15 years.")

**Comment by McQgit** [comment]
@t2lt Just fyi, there is also an active group for the iexfinance sdk at []https://github.com/addisonlynch/iexfinance

That's not developed by the IEX folks and sometimes has its own issues - as you've discovered.
