### ISSUE TITLE
Historical Prices changed API v1 and cloud over time [Data]

### ISSUE THREAD

**Issue by rmantovani** [iexg/IEX-API#1233]
**Clearly describe the data problem**

Chart values  from V1 Api are  differentes from cloud API .
Just volume have the same value everything else changed.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/aapl/chart/max?token=TOKEN

**What time did the problem occur (including timezone)?**
every time

**What is the expected behavior?**
price dont change over time.

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
LINUX - Java

**Additional context**

AAPL historical price called today (cloud API)
{"date":"2014-06-09","uClose":93.7,"uOpen":92.7,"uHigh":93.88,"uLow":91.75,"uVolume":75414804,"close":93.7,"open":92.7,"high":93.88,"low":91.75,"volume":75414804,"change":1.48,"changePercent":1.6001,"label":"Jun 9, 14","changeOverTime":91.64386}

AAPL historical price called last year near 2018-10-01 (V1 API)

 id_point   vl_open vl_high vl_low  vl_close vl_volume   
-------- -------- ------ ----------- ------- ------- ------- -------- ----------- 
20140609  85.9536 87.0477 85.0727 86.8808  75414804.00 

Also
Ajusted values and unajusted values are the same. (cloud API)

**Comment by joshuablackburn-iex** [comment]
Prices are currently adjusted for splits only. Given how rare splits are, values will be the same in most cases. We will release dividend and split adjusted historical prices at a later date.
