### ISSUE TITLE
[Issue] No results for list/mostactive

### ISSUE THREAD

**Issue by markwheeler** [iexg/IEX-API#1234]
Right now https://cloud.iexapis.com/stable/stock/market/list/mostactive is returning no results (I just see `[]`). This is also true for some of the other `list` queries.

Testing at 18:30, Pacific Time, Sept 2nd.
Expecting to see a list of most active companies.

Is this expected behavior? Something to do with markets being closed for Labor Day? When is mostactive guaranteed to return a list?

**Comment by evancarter-iex** [comment]
@markwheeler This was most likely due to the holiday. We will look in making sure it keeps the last trading day information on a holiday.
