### ISSUE TITLE
[Data] issueType values not documented

### ISSUE THREAD

**Issue by dylanitorium** [iexg/IEX-API#1235]
**Clearly describe the data problem**
The `/company` endpoint can return an `issueType` value that's not documented. 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/aaba/company (cef)
https://cloud.iexapis.com/stable/stock/stay/company (ut)

**What time did the problem occur (including timezone)?**
12:38pm 4th August 2019 New Zealand Standard Time

**What is the expected behavior?**
The `issueType` to be documented

**What are the steps to reproduce**
Visit the data URL with a non-sandbox token

**Your environment (e.g. browser, OS, API version, language):**
Brave Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit), Ubuntu, v1

**Additional context**
The `cef` type could possibly the same as `ce`

**Comment by evancarter-iex** [comment]
This is documented now.
