### ISSUE TITLE
[Data] Incorrect latestUpdate & closeTime data

### ISSUE THREAD

**Issue by RobCanton** [iexg/IEX-API#1237]
**Clearly describe the data problem**
Quote endpoint is returning a latestUpdate and closeTime of _1567569600000_ or 4:00 AM, September 4. Even if adjusted for EDT (12:00 AM) this does not seem to be the correct data.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/aapl/quote
_Occurred for all symbols I tried at the time: **msft**, **atvi**, **nflx**, **twtr**, **wmt**_

**Edit:** International symbols seem to be returning the exact same timestamp as well.
Tested: **000020-kp**, **ADCB-DH**, **TDE-LN**

**What time did the problem occur (including timezone)?**
11:55 AM EDT, September 4

**What is the expected behavior?**
I would expect the latestUpdate and closeTime to be 4 PM EDT

**What are the steps to reproduce**
Call quote endpoint after trading hours (or possibly only after after-market hours).

**Your environment (e.g. browser, OS, API version, language):**
Chrome

**Additional context**

**Comment by kswier** [comment]
On October 19, AAPL is returning 1571371200000 for the latestUpdate.  That translates to Thursday, October 17, 2019 11:00:00 PM CST.

**Comment by evancarter-iex** [comment]
@kswier I will have a fix for the weekend lastupdate & close time tomorrow. The international ones are a bit trickier

**Comment by evancarter-iex** [comment]
This is resolved.
