### ISSUE TITLE
[Data] 5yr Return in KeyStats is wrong

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1238]
**Clearly describe the data problem**
"year5ChangePercent": 1.463761 for AAPL when KeyStats was run on Sept 5 (closing Sept 4)

It's way too high using either close or the adjusted close.

Sept 4 2019 closing: 209.19
Sept 4 2014 closing: 98.12  (adjusted 90.03)
Sept 5 2014: closing 98.97 (adjusted 90.81)

[{
	"week52change": -0.07793,
	"week52high": 233.47,
	"week52low": 142,
	"marketcap": 945367264200,
	"employees": 132000,
	"day200MovingAvg": 185.86,
	"day50MovingAvg": 204.64,
	"float": 4512514209.5,
	"avg10Volume": 24008312.2,
	"avg30Volume": 29806753.7,
	"ttmEPS": 11.83,
	"ttmDividendRate": 2.96,
	"companyName": "Apple, Inc.",
	"sharesOutstanding": 4519180000,
	"maxChangePercent": 205.130117,
	"year5ChangePercent": 1.463761,
	"year2ChangePercent": 0.362525,
	"year1ChangePercent": -0.07793,
	"ytdChangePercent": 0.324658,
	"month6ChangePercent": 0.191762,
	"month3ChangePercent": 0.145995,
	"month1ChangePercent": 0.08198,
	"day30ChangePercent": 0.002492,
	"day5ChangePercent": 0.017808,
	"nextDividendDate": null,
	"dividendYield": 0.014149815956785697,
	"nextEarningsDate": "2019-10-31",
	"exDividendDate": "2019-08-09",
	"peRatio": 17.68,
	"beta": 1.5125314290909129
}](url)

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/aapl/stats?

**What time did the problem occur (including timezone)?**
8:10AM PST Sept 5

**What is the expected behavior?**
Returns correct number

**What are the steps to reproduce**
Run API

**Your environment (e.g. browser, OS, API version, language):**
Chrome

**Additional context**
Others report high, others report low. Some are paying dividends, others not. There's no rhyme or reason on how the number is calculated - the API docs provide no explanation. Other periods and tickers are incorrect as well.

**Comment by evancarter-iex** [comment]
@jesseorosz this should be correct now. I will update documentation to make clear about 30 days being 30 trading days etc
