### ISSUE TITLE
Using IEX 5Y Chart Data for Zipline?

### ISSUE THREAD

**Issue by freddiev4** [iexg/IEX-API#124]
Hi there! I'm currently a maintainer of [Zipline](https://github.com/quantopian/zipline) and we've been using `pandas-datareader` to pull data for `SPY` from Yahoo & Google Finance, to be used as a benchmark for people who want to write their own trading algorithms with Zipline. Because of the numerous breaks/changes in both the Yahoo & Google Finance APIs, we've been looking for alternatives. 

We came across IEX Trading sometime ago; the documentation is awesome, and considering we can get data up to 5Y for `SPY` from IEX, we figured we could use that [here](https://github.com/quantopian/zipline/pull/2031)

We also read https://iextrading.com/api-terms/:

> 1. If you sell, lease, furnish, permit or provide access to, or otherwise redistribute Investors Exchange (“IEX”) API data, which includes API data licensed from third-parties, to any other person:
a. you must provide a link to https://iextrading.com/api-exhibit-a or otherwise obtain consent from such person to the terms of use substantially in the form of the above Exhibit A;
b. you must cite IEX as the source in accordance with the instructions available on https://iextrading.com/developer;

And so I was wondering what you'd expect from us/where you'd think the best place for putting attribution is, and if it's even alright to use your data for our Zipline users.

**API URL:** https://api.iextrading.com/1.0/stock/SPY/chart/5y

**Comment by joshuablackburn-iex** [comment]
If this is a library, you can just put "Data provided by IEX" as a comment at the top of the file requesting data and/or your github docs page.  You can definitely use the API.

**Comment by timkpaine** [comment]
@joshuablackburn-iex @freddiev4 I know this is closed [but](https://github.com/timkpaine/pyEX-zipline)

**Comment by jcape** [comment]
@timkpaine Awesome, thanks for sharing 👍
