### ISSUE TITLE
[Issue] Misleading exception 

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#1241]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**

Minor thing, but seems like there is misleading exception in case that query parameters are not correct. For instance correct path for batch instance would be: 

https://cloud.iexapis.com/stable/stock/aapl/batch?types=quote,news,chart&token=YOUR_TOKEN

but if we don't put required types like that: 

https://cloud.iexapis.com/stable/stock/aapl/batch?token=YOUR_TOKEN

you will receive an exception:  "The API key provided is not valid."

I would expect something about no correct path or I even see that for batch there is some special error: "400 | Type Required | Batch request types parameter requires a valid value"

**What time did the problem occur? (with timezone)**

8th of September 2019 14:41 CEST

**What is the expected behavior?**

I would expect something about no correct path or I even see that for batch there is some special error: "400 | Type Required | Batch request types parameter requires a valid value"

**Your environment (e.g. browser, OS, API version, language):**

Irrelevant probably, but:  Windows 10 / Firefox 69 / Postman / Java

**API URL (if applicable)**

https://cloud.iexapis.com/stable/stock/aapl/batch?token=YOUR_TOKEN

**What are the steps to reproduce the bug?**

1. Open batch endpoint without types and with valid API key

**Additional context**

NaN

**Comment by isdyaufh8o7cq** [comment]
Same here with curl from linux, osx browser etc..

**Comment by timpaine-iex** [comment]
I'll fix this this week
