### ISSUE TITLE
[Issue] Inconsistent data model between Fund Ownership and Institutional Ownership

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#1242]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**

Minor thing, but:

Fund Ownership returns report_date

https://sandbox.iexapis.com/v1/stock/AAPL/fund-ownership?token=Tsk_3eedff6f5c284e1a8b9bc16c54dd1af3

    {
        "report_date": 1571704934963,
        "entityProperName": "r darVoTaeMed S unuglodata  ntInkxFctk",
        "adjHolding": 116715320,
        "adjMv": 24745845345,
        "reportedHolding": 119965324,
        "reportedMv": 25387099546
    }

Institutional Ownership returns as reportDate

https://sandbox.iexapis.com/v1/stock/AAPL/institutional-ownership?token=Tsk_3eedff6f5c284e1a8b9bc16c54dd1af3

    {
        "reportDate": 1608099826381,
        "adjHolding": 338248073,
        "reportedHolding": 342108760,
        "adjMv": 67447698468,
        "entityProperName": "Iupac,rS.g) GnidfaberVnl(u our "
    }

**What time did the problem occur? (with timezone)**

All the time

**What is the expected behavior?**

Both endpoint return the same field name, perhaps "reportDate"

**Your environment (e.g. browser, OS, API version, language):**

Windows 10 / Firefox 69 

**API URL (if applicable)**

https://sandbox.iexapis.com/v1/stock/AAPL/fund-ownership?token=Tsk_3eedff6f5c284e1a8b9bc16c54dd1af3
https://sandbox.iexapis.com/v1/stock/AAPL/institutional-ownership?token=Tsk_3eedff6f5c284e1a8b9bc16c54dd1af3

**What are the steps to reproduce the bug?**

1. Call both endpoints and compare field names

**Additional context**

NaN

**Comment by timpaine-iex** [comment]
this is a known, tracked,  and deeply annoying (to me as a person) issue that we can't fix until we release `v2-beta` to ensure backwards compat.
