### ISSUE TITLE
[Data] null returning for stock for latestPrice

### ISSUE THREAD

**Issue by dayidp** [iexg/IEX-API#1244]
Clearly describe the data problem
Some stocks are returning null for latest price
Data URL (The URL you used to access the data without your token):

https://cloud.iexapis.com/stable/stock/lake/quote?token=

What time did the problem occur (including timezone)?
11:40
Sept 9, 2019  

What is the expected behavior?
"latestPrice":10.61
 

What are the steps to reproduce
call https://cloud.iexapis.com/stable/stock/lake/quote?token=

Your environment (e.g. browser, OS, API version, language):
API

Additional context

  
I get the following response:
{"symbol":"LAKE","companyName":"Lakeland Industries, Inc.","primaryExchange":"NASDAQ","calculationPrice":"sip","open":null,"openTime":null,"close":null,"closeTime":null,"high":null,"low":null,"latestPrice":null,"latestSource":null,"latestTime":null,"latestUpdate":null,"latestVolume":null,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":10.61,"previousVolume":16622,"change":null,"changePercent":null,"volume":null,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":10640,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":null,"peRatio":null,"week52High":null,"week52Low":null,"ytdChange":null,"lastTradeTime":1567782095101,"isUSMarketOpen":true}

Several important metrics return null. The most important is latestPrice.
Cannot rely on iex cloud API.

**Comment by evancarter-iex** [comment]
@dayidp Hi there, this appears to be only affecting NASDAQ symbols that havent traded today and on our free tier. Ill have a fix shortly.

**Comment by evancarter-iex** [comment]
This is fixed now
