### ISSUE TITLE
How to get open/close price of a specific day for a stock in Google App Script? 

### ISSUE THREAD

**Issue by seanchs** [iexg/IEX-API#1245]
I registered to IEX cloud. I have been trying to get a historical open and close price of a historical day for some tickers but couldn't figure out how to use the IEX API in google app script and/or Google sheet. Have done tone of googling for a couple of days but no success. Any help would be highly appreciated! 

Thanks,

**Comment by McQgit** [comment]
It would be helpful if you could be more specific on what's causing you trouble.

For example, do you just not know what IEX API url to use?  Or, are you unsure how that works with google sheets 'importdata'?  Or, are you struggling with handling json in your google sheet?  That sort of thing.  

An example of something you've got working that's close to what you want is helpful too, if you have something.

I don't know anything about your background so not sure where to begin.  I don't want to waste either of our time rehashing things you know well.

**Comment by seanchs** [comment]
@McQgit Sorry about the confusion. I am trying to figure out what IEX API URL and syntax are to get the open and/or close price on a specific day for a stock.  

I used to have GoogleFinance to accomplish this: = GoogleFinance(ticker, "Open", Date). But some times, GoogleFinance is funky since it doesn't allow Google App Script to get the price data. 

I also used importHTML to scrape data from BigCharts: 
= index(ImportHtml(http://bigcharts.marketwatch.com/historical/default.asp?symb=TSLA&closeDate=8%2F09%2F20&x=0&y=0, "table"),4,2), "Error"))

But sometimes it gives me error. 

Thanks a lot,

**Comment by McQgit** [comment]
@seanchs Well, then you have some more reading to do :)

First, see the IEX docs section on google sheets.  Try their exact samples and get those working before trying different url lookups.  I know the link says Excel, the google sheets is just after that.
[]https://iexcloud.io/docs/api/#excel-how-to

Once mastered, check out their historical price lookup:
[]https://iexcloud.io/docs/api/#historical-prices

Note that will return json (or csv) so will require some work to unpack the response.  Search stackoverflow for that.

Lastly, see this previous github issue for someone doing the same thing as you except with Excel.  Still, there are several useful bits for your situation:
[]https://github.com/iexg/IEX-API/issues/1187

**Comment by seanchs** [comment]
@McQgit Thank you so much for the pointers. Very very helpful : ) 

Based on what I read, I use below line retrieve some data from IEX: 
URL: https://cloud.iexapis.com/stable/stock/aapl/chart/date/20190109?chartByDay=true&token=myToken 
Result (showed in Google Script):  [{date=2019-01-09, uHigh=154.53, uVolume=45099081, change=2.56, uOpen=151.29, uLow=149.63, uClose=153.31, label=Jan 9, 19, volume=45099081, high=154.53, low=149.63, changeOverTime=0.016982, changePercent=1.6982, close=153.31, open=151.29}]

However, when I tried to get the uOpen (using xpath), it's said the node doesn't exist. Could you shed some lights on the proper xpath to retrieve uOpen from the data I get? Thanks a lot
