### ISSUE TITLE
[Data] IEX Only - Historical

### ISSUE THREAD

**Issue by jimskin** [iexg/IEX-API#1246]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**

Which endpoint should we be using to retrieve IEX Only (free) historical data to build OHLC charts (different timeframes)? We are using the 'historical_prices' endpoint with the IEXOnly parameter but each time we retrieve historical data it is costing us 2,000,000+ messages per request.

**Data URL (The URL you used to access the data without your token):**

*****************************************

baseHistory = "https://cloud.iexapis.com/stable"

************************

func (p *provider) equityHistoricalDataURL(ctx context.Context, startDate time.Time, endDate time.Time, step common.TimeStep, symbol common.Symbol) ([]string, error) {
	now := time.Now()
?
	switch step {
	case common.T1min:
		{
			cutoff := now.AddDate(0, 0, -10)
			if startDate.Before(cutoff) {
				startDate = cutoff
			}
			nowD := takeDataItem(now)
			dates := getDates(startDate, endDate)
			urls := make([]string, 0)
			var url string
			todayIsTradeDay, err := p.isTodayTradeDay(ctx)
			if err != nil {
				return nil, err
			}
?
			for _, e := range dates {
				if !todayIsTradeDay || !e.equal(nowD) {
					url = fmt.Sprintf("%s/stock/%s/chart/date/%s?token=%s&chartIEXOnly=true", baseHistory, symbol.Name, e.original.Format("20060102"), p.apiKey)
				} else {
					url = fmt.Sprintf("%s/stock/%s/intraday-prices?token=%s&chartIEXOnly=true", baseHistory, symbol.Name, p.apiKey)
				}
				urls = append(urls, url)
			}
			return urls, nil
		}
	case common.T1day:
		{
?
			var interval string
			days := int(now.Sub(startDate).Hours() / 24)
			if days < 5 {
				interval = "5d"
			} else if days < 30 {
				interval = "1m"
			} else if days < 30*3 {
				interval = "3m"
			} else if days < 30*6 {
				interval = "6m"
			} else if days <= 365 {
				interval = "1y"
			} else if days <= 365*5 {
				interval = "5y"
			} else {
				interval = "max"
			}
?
			url := fmt.Sprintf("%s/stock/market/batch?symbols=%s&types=chart&range=%s&token=%s&chartIEXOnly=true", baseHistory, symbol.Name, interval, p.apiKey)
			return []string{url}, nil
?
		}
	case common.T30min:
		{
			url := fmt.Sprintf("%s/stock/market/batch?symbols=%s&types=chart&range=1mm&token=%s&chartIEXOnly=true", baseHistory, symbol.Name, p.apiKey)
			return []string{url}, nil
		}
	}
	return nil, errors.New("unsupported timestep")
}

************************************************************************************

**What time did the problem occur (including timezone)?**
n/a

**What is the expected behavior?**
n/a

**What are the steps to reproduce**
n/a

**Your environment (e.g. browser, OS, API version, language):**
n/a

**Additional context**
n/a

**Comment by evancarter-iex** [comment]
@jimskin chartIEXOnly is only for the intraday endpoint. Historical data is from our partner and will cost messages unfortunately.

**Comment by jimskin** [comment]
I've been told there is only one days worth of data available with the 'intraday_prices_iex' endpoint. Is that correct? If so, it's unuseable.

**Comment by evancarter-iex** [comment]
@jimskin We have 30 days worth of data and will be backfilling more but its a slow process.
