### ISSUE TITLE
[Issue] Full quota in Prod denies access to Test (Sandbox) APIs

### ISSUE THREAD

**Issue by amittleider** [iexg/IEX-API#1249]
**Clearly describe the problem**
I have filled my available quota and I am using the "Pay as you go" feature. I am running integration tests against IEX using the sandbox (test) endpoint. When I hit the quota limit and begin to use "Pay as you go", the sandbox APIs throw a 403 Forbidden error. 

**What is the expected behavior?**
I expect the test APIs to always work, even if my production quota is filled for this period and I am currently on Pay-as-you-go.

**API URL (if applicable)**
Balance sheet, income statement, cash flow statement, historical data (daily candles)

**What are the steps to reproduce the bug?**
Get your account into a pay-as-you-go state and then try to hit the sandbox APIs.

**Comment by evancarter-iex** [comment]
@amittleider Hmm that shouldnt be happening. Ill try and look into it on monday.

**Comment by amittleider** [comment]
Thanks @evancarter-iex , were you able to reproduce the issue?

**Comment by markcorwin-iex** [comment]
@amittleider I have not been able to recreate this issue. Can you reach out to IEX Cloud support via email (support@iexcloud.io) with this issue's contents? They might have a few questions but can best facilitate getting to the bottom of this. Thanks.

**Comment by amittleider** [comment]
Sure @markcorwin-iex , I have sent an email to the support. 

I did find something else interesting though, so I will post it here. Here's what happens when I hit the API in the browser. Note that this is the sandbox environment. 

![image](https://user-images.githubusercontent.com/1625951/65273664-f60d9600-db21-11e9-8747-a7107546f8d6.png)

**Comment by markcorwin-iex** [comment]
@amittleider Thanks for the info. This will definitely be helpful in tracking down the issue.

**Comment by markcorwin-iex** [comment]
@amittleider This issue has been fixed. You should also receive an email confirming this from the IEX Cloud support team.

**Comment by amittleider** [comment]
Thanks a lot, @markcorwin-iex  and @evancarter-iex!  I'm a big fan of the IEX mission, good luck to you guys.
