### ISSUE TITLE
inaccurate/missing data symbol  VMW

### ISSUE THREAD

**Issue by earningsquest** [iexg/IEX-API#125]
## Summary
Missing earnings data for a number of symbols. 

## Details
VMW only returns earnings data for 2016 , while company was reportin  after that, 
https://api.iextrading.com/1.0/stock/vmw/earnings
{"symbol":"VMW","earnings":[{"actualEPS":null,"consensusEPS":null,"estimatedEPS":null,"announceTime":null,"numberOfEstimates":null,"EPSSurpriseDollar":null,"EPSReportDate":null,"fiscalPeriod":null,"fiscalEndDate":null},{"actualEPS":null,"consensusEPS":null,"estimatedEPS":null,"announceTime":null,"numberOfEstimates":null,"EPSSurpriseDollar":null,"EPSReportDate":null,"fiscalPeriod":null,"fiscalEndDate":null},{"actualEPS":null,"consensusEPS":null,"estimatedEPS":null,"announceTime":null,"numberOfEstimates":null,"EPSSurpriseDollar":null,"EPSReportDate":null,"fiscalPeriod":null,"fiscalEndDate":null},{"actualEPS":1.11,"consensusEPS":1.08,"estimatedEPS":1.08,"announceTime":"AMC","numberOfEstimates":4,"EPSSurpriseDollar":0.03,"EPSReportDate":"2017-01-26","fiscalPeriod":"Q4 2016","fiscalEndDate":"2016-12-31"}]}

### API URL

https://api.iextrading.com/1.0/stock/vmw/earnings

### What you expected to happen

expect to get earnings data for past 4 earnings, instead getting null for  3 out of 4

**Comment by earningsquest** [comment]
inaccurate/missing  data for LULU , last report date 2016-12-07 for Q3 2017

https://api.iextrading.com/1.0/stock/lulu/earnings

{"symbol":"LULU","earnings":[{"actualEPS":0.47,"consensusEPS":0.43,"estimatedEPS":0.43,"announceTime":"AMC","numberOfEstimates":17,"EPSSurpriseDollar":0.04,"EPSReportDate":"2016-12-07","fiscalPeriod":"Q3 2017","fiscalEndDate":"2016-10-31"},{"actualEPS":0.38,"consensusEPS":0.38,"estimatedEPS":0.38,"announceTime":"AMC","numberOfEstimates":14,"EPSSurpriseDollar":null,"EPSReportDate":"2016-09-01","fiscalPeriod":"Q2 2017","fiscalEndDate":"2016-07-31"},{"actualEPS":0.3,"consensusEPS":0.3,"estimatedEPS":0.3,"announceTime":"BTO","numberOfEstimates":16,"EPSSurpriseDollar":null,"EPSReportDate":"2016-06-08","fiscalPeriod":"Q1 2017","fiscalEndDate":"2016-04-30"},{"actualEPS":0.85,"consensusEPS":0.8,"estimatedEPS":0.8,"announceTime":"BTO","numberOfEstimates":17,"EPSSurpriseDollar":0.05,"EPSReportDate":"2016-03-30","fiscalPeriod":"Q4 2016","fiscalEndDate":"2016-01-31"}]}

**Comment by earningsquest** [comment]
inaccurate/missing data for RH , last report date 2016-12-08 for Q3 2017
https://api.iextrading.com/1.0/stock/rh/earnings

{"symbol":"RH","earnings":[{"actualEPS":0.19,"consensusEPS":0.16,"estimatedEPS":0.16,"announceTime":"AMC","numberOfEstimates":11,"EPSSurpriseDollar":0.03,"EPSReportDate":"2016-12-08","fiscalPeriod":"Q3 2017","fiscalEndDate":"2016-10-31"},{"actualEPS":0.38,"consensusEPS":0.29,"estimatedEPS":0.29,"announceTime":"AMC","numberOfEstimates":11,"EPSSurpriseDollar":0.09,"EPSReportDate":"2016-09-08","fiscalPeriod":"Q2 2017","fiscalEndDate":"2016-07-31"},{"actualEPS":-0.05,"consensusEPS":0.05,"estimatedEPS":0.05,"announceTime":"AMC","numberOfEstimates":11,"EPSSurpriseDollar":-0.1,"EPSReportDate":"2016-06-08","fiscalPeriod":"Q1 2017","fiscalEndDate":"2016-04-30"},{"actualEPS":0.99,"consensusEPS":1.39,"estimatedEPS":1.39,"announceTime":null,"numberOfEstimates":13,"EPSSurpriseDollar":-0.4,"EPSReportDate":"2016-03-29","fiscalPeriod":"Q4 2016","fiscalEndDate":"2016-01-31"}]}

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
