### ISSUE TITLE
latestVolume returns null while iexVolume returns a number

### ISSUE THREAD

**Issue by ykoitzsch** [iexg/IEX-API#1250]
According to the API docs, "latestVolume" returns the latest total market volume of the stock across all markets. 

How is it possible that latestVolume returns null (and not a just 0 btw?) and iexVolume returns for example 100? Doesn't "total market" include the iexVolume?

This is super confusing. The Symbol in this case is "AAC".

**Comment by evancarter-iex** [comment]
@ykoitzsch If you are on a free account that data is nulled out (paid users have access to it)
