### ISSUE TITLE
[Data] Missing data for TM in Key Stats

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1251]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
MarketCap, ttmDividendRate, sharesOutstanding, DividendYield are all null

exDividendDate has a value.

```
{
	"week52change": 0.117599,
	"week52high": 137.18,
	"week52low": 111.12,
	"marketcap": null,
	"employees": 370870,
	"day200MovingAvg": 123.42,
	"day50MovingAvg": 130.02,
	"float": 1412044946.60886,
	"avg10Volume": 157023,
	"avg30Volume": 142001.77,
	"ttmEPS": 12.0035,
	"ttmDividendRate": null,
	"companyName": "Toyota Motor Corp.",
	"sharesOutstanding": null,
	"maxChangePercent": 1.69044,
	"year5ChangePercent": 0.127946,
	"year2ChangePercent": 0.116072,
	"year1ChangePercent": 0.117599,
	"ytdChangePercent": 0.175267,
	"month6ChangePercent": 0.161088,
	"month3ChangePercent": 0.098641,
	"month1ChangePercent": 0.080487,
	"day30ChangePercent": 0.059791,
	"day5ChangePercent": 0.028834,
	"nextDividendDate": null,
	"dividendYield": null,
	"nextEarningsDate": "2019-11-04",
	"exDividendDate": "2019-03-29",
	"peRatio": 11.39,
	"beta": 0.5898215452244654
}
```

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/tm/stats?

**What time did the problem occur (including timezone)?**
4AM PST Sept 15

**What is the expected behavior?**
Returns value

**What are the steps to reproduce**
Run API call

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
@jesseorosz Im looking into this.

**Comment by evancarter-iex** [comment]
This should be fixed.

**Comment by evancarter-iex** [comment]
@jesseorosz Hmm you are right let me take a look.
