### ISSUE TITLE
[Issue] Unable to change plan to Launch

### ISSUE THREAD

**Issue by jonwho** [iexg/IEX-API#1252]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**
I'm trying to pay for the yearly Launch plan. The change button to submit payment is disabled due to address not being validated.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/3283146/65176354-78eefd80-da09-11e9-938a-28215f7f9235.png">

**What time did the problem occur? (with timezone)**
11:43 PST

**What is the expected behavior?**
Recognize my existence.

**Your environment (e.g. browser, OS, API version, language):**

**API URL (if applicable)**

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by ben-berman-iex** [comment]
Please email support@iexcloud.io with the address you were using so we can help diagnose what went wrong
