### ISSUE TITLE
[Data]Dividends endpoint missing key:value for "symbol"?

### ISSUE THREAD

**Issue by WillTron** [iexg/IEX-API#1253]
**Clearly describe the data problem**
The json output for the "dividends" endpoint and the "upcoming-dividends" endpoint are identical with the exception of the last key:value pair. "upcoming-dividends" outputs the ticker symbol ..... "frequency":"Quarterly","symbol":"TGT"}]

The API call for "dividends" endpoint outputs the query date as the last key:value, but no "symbol" key:value ...... "frequency":"Quarterly","date":"2019-09-18"}]

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/tgt/dividends?token=my_token
I'm currently using the Free plan. 

**What time did the problem occur (including timezone)?**
US central, 5pm but occurs every time the API is called that outputs a non-empty array

**What is the expected behavior?**
For the "dividends" endpoint to have a key:value for the symbol. It makes it tough parsing through a batch call of several dozen tickers and trying to figure out which sub-array belongs to which ticker.

**What are the steps to reproduce**
Run an API call on any symbol for "dividends" endpoint that has an ex-div date plus or minus 30 days from current date (I'm on the Free plan)

**Your environment (e.g. browser, OS, API version, language):**
latest Chrome, Win10 Pro, stable IEX cloud, php

**Additional context**
example json output for ticker TGT using "dividends" endpoint:
[
  {
    "exDate": "2019-08-20",
    "paymentDate": "2019-09-10",
    "recordDate": "2019-08-21",
    "declaredDate": "2019-06-13",
    "amount": 0.66,
    "flag": "Increase",
    "currency": "USD",
    "description": "Target Corp. Hikes Quarterly Dividend 3.13%",
    "frequency": "Quarterly",
    "date": "2019-09-18"
  }
]

**Comment by McQgit** [comment]
@WillTron The iex guys can address your concern about the symbol in /dividends.  But, my results for batch requests do include the symbol as a wrapper for each endpoint returned.  For example:

`https://cloud.iexapis.com/v1/stock/market/batch?symbols=tgt,vz&types=dividends&token=(token)`

In the response below, notice the symbol in the outer layer for dividends.  If I was retrieving multiple endpoints, like `types=dividends,company` the symbol wraps both of them.

```
{
  "TGT": {
    "dividends": [
      {
        "exDate": "2019-08-20",
        "paymentDate": "2019-09-10",
        "recordDate": "2019-08-21",
        "declaredDate": "2019-06-13",
        "amount": 0.66,
        "flag": "Increase",
        "currency": "USD",
        "description": "Target Corp. Hikes Quarterly Dividend 3.13%",
        "frequency": "Quarterly",
        "date": "2019-09-19"
      }
    ]
  },
  "VZ": {
    "dividends": [
      {
        "exDate": "2019-10-09",
        "paymentDate": "2019-11-01",
        "recordDate": "2019-10-10",
        "declaredDate": "2019-09-05",
        "amount": 0.615,
        "flag": "Increase",
        "currency": "USD",
        "description": "Verizon Communications Hikes Quarterly Dividend 2.07%",
        "frequency": "Quarterly",
        "date": "2019-09-19"
      }
    ]
  }
}
```

**Comment by WillTron** [comment]
ahhh ... thanks McQ that makes sense. I guess i should have ran a batch request to experience what you pointed out. it's just odd that the output for "upcoming-dividends" and "dividends" endpoints don't mirror each other when you enter an API call on a single ticker, so that's what threw me off.
