### ISSUE TITLE
a soup to nuts SIMPLE Python script to show how to avoid 403 errors.

### ISSUE THREAD

**Issue by sio2bagger** [iexg/IEX-API#1254]
I'm just starting with the iex cloud in Python and am finding it VERY difficult as I keep hitting the 403 error.

  What seems to be missing is a SIMPLE example program that just shows how to use the token functionality.

  I have looked around and used what I found ( see below) BUT I keep getting 403 errors.  

```
from iex import Stock
import os
os.environ['IEX_TOKEN'] = "I put my public key here" #public

Stock("F").price()
```

============
when I run
 File "/home/xxxxxx/.local/lib/python3.6/site-packages/iex/stocks.py", line 31, in _get
    raise Exception(f"{response.status_code}: {response.content.decode('utf-8')}")
Exception: 403: Forbidden

**Comment by McQgit** [comment]
@sio2bagger  Well, I am far from a python expert.  But, are you by chance using the iexfinance python module?  If so, that's a 3rd party extension whose docs are here:

[]https://pypi.org/project/iexfinance/
or here:
[]https://github.com/addisonlynch/iexfinance

The docs in either location show what you are asking for.  If you are using some other python module, I guess that won't help.

**Comment by sio2bagger** [comment]
@McQgit you make an EXCELLENT point and I missed that completely. I REALLY should take the time to sit down and think about this before wasting everyone's time.  Sorry to have bugged you and thanks for being so understanding and helpful.  Have an excellent weekend.
