### ISSUE TITLE
[Data] No marketvolume in intraday-prices endpoint

### ISSUE THREAD

**Issue by perigee** [iexg/IEX-API#1255]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
Intraday-prices endpoint misses the

- MarketVolume data

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/amd/intraday-prices

**What time did the problem occur (including timezone)?**
now

**What is the expected behavior?**

should contain following data according to doc

        "marketOpen": 143.98,
        "marketClose": 143.775,
        "marketHigh": 143.98,
        "marketLow": 143.775,
        "marketAverage": 143.889,
        "marketVolume": 3070,
        "marketNotional": 441740.275,
        "marketNumberOfTrades": 20,
        "marketChangeOverTime": -0.004,

**What are the steps to reproduce**

Just invoke the endpoint

**Your environment (e.g. browser, OS, API version, language):**

curl under linux

**Additional context**

**Comment by evancarter-iex** [comment]
@perigee Hi there, are you on a free plan?

**Comment by perigee** [comment]
@evancarter-iex  Yes, it is free plan, if it were the issue, thx for your help. Another question if i can post here:
- How to check TSX/VSE (canadian) data ? little bit confused with endpoint

thank you in adavance.

**Comment by evancarter-iex** [comment]
@perigee The Market Volume is only available for paid customers. 

https://cloud.iexapis.com/stable/ref-data/region/ca/symbols&token= will give you the list of symbols we support
