### ISSUE TITLE
Data Limits

### ISSUE THREAD

**Issue by jimhoranjr** [iexg/IEX-API#126]
## Summary
I have a call with 40 symbols with 6 attributes per symbol. The first call of the day works fine then subsequent call return the same data string. Am I making too many requests?

### Date/time of issue
12/1/17

### API URL
strURL = "https://api.iextrading.com/1.0/stock/market/batch?symbols=" & SymbLst & _
    "&types=quote&filter=" & AttribLst
With xmlhttp
        .Open "get", strURL, False
        .send
        x = .ResponseText
    End With

### What you expected to happen
I expected current update

### What actually happened
Last update was returned

**Comment by jcape** [comment]
@jimhoranjr Could you let us know what symbol and attribute list you're using, and/or provide the actual output indicating what you expect to be different?

**Comment by joshuablackburn-iex** [comment]
This may be due to low trading activity or premarket requests.  Without further details on what attributes you're using and what time of day, we are unable to provide more information.
