### ISSUE TITLE
Symbols API endpoint does not include mutual fund symbols in response body

### ISSUE THREAD

**Issue by interzone2001** [iexg/IEX-API#1261]
Date/time of the issue:  9/30/2019 12:44PM ET
What you did:  Called the Symbols API endpoint GET /ref-data/symbols
What you expected to happen:  A full list of symbols supported by other IEX API endpoints to be returned.
What actually happened:  Only exchange traded instruments (equities/ETFs/closed end funds) are returned.

Additional relevant information:  Open ended US mutual funds are supported by other IEX API endpoints.  For example, Company and Previous Day Prices works fine for them (along with others).   

If other endpoints support mutual funds, I would argue that your symbol list endpoint should also.   It states in the documentation that "This call returns an array of symbols that IEX Cloud supports for API calls."  which is not the case as demonstrated below.

As an example, calling Company with a mutual fund symbol, ODIYX returns the following:
{"symbol":"ODIYX","companyName":"Invesco Oppenheimer Discovery Fund","exchange":"NASDAQ","industry":"Investment Trusts/Mutual Funds","website":"","description":"","CEO":"","securityName":"Invesco Oppenheimer Discovery Fund Class Y","issueType":"oef","sector":"Miscellaneous","employees":null,"tags":["Investment Trusts/Mutual Funds","Miscellaneous"],"address":null,"address2":null,"state":null,"city":null,"zip":null,"country":null,"phone":null}

Thanks!

**Comment by evancarter-iex** [comment]
@interzone2001 the ref-data endpoints need to be cleaned up and will be for v2. If you want all symbols including mutual funds you can use https://cloud.iexapis.com/stable/ref-data/region/us/symbols?token=
