### ISSUE TITLE
Start Level - Sandbox key returns HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by dp6000** [iexg/IEX-API#1262]
**Clearly describe the problem**
Using the sandbox test key results in a HTTP 403 error when requesting historical data.  If I use a standard key, I am able to download historical data.

**What time did the problem occur? (with timezone)**
Between 9 am - 10 am (PDT)

**What is the expected behavior?**
Sandbox should return randomized data for the selected range. (I have tried '1m' and '1y')

**Your environment (e.g. browser, OS, API version, language):**
Windows 10 Pro Version 1903, 
Chrome Browser version Version 77.0.3865.90 (Official Build) (64-bit)

**API URL (if applicable)**
sym = 'AAPL'
token = INSERT TEST PUBLIC KEY
df_temp = pd.read_json('https://cloud.iexapis.com/stable/stock/'+sym+'/chart/1m?token='+token+'')

**What are the steps to reproduce the bug?**
Run the above code with a valid test public key

**Additional context**

**Comment by joshuablackburn-iex** [comment]
https://iexcloud.io/docs/api/#sandbox

Please refer to our docs on sandbox. You'll need to use the appropriate sandbox url (sandbox.iexapis.com) and your test token.

**Comment by dp6000** [comment]
Thank you. That fixed the issue.
