### ISSUE TITLE
[Data] /ref-data/symbols endpoint on cloud.iexapis.com and api.iextrading.com return different numbers of common stocks

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#1263]
``https://cloud.iexapis.com/v1/ref-data/symbols?token=`` returns 4550 common stocks (type=cs)
``https://api.iextrading.com/1.0/ref-data/symbols`` returns 5460 common stocks (type=cs)

which one is correct?

Thanks!

**Comment by evancarter-iex** [comment]
Resolved via support channel.
