### ISSUE TITLE
[Issue] SSE Streaming multiple connections

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#1264]
Out of ``https://iexcloud.io/docs/api/#sse-streaming`` "Currently SSE requests are limited to 50 symbols per connection, but you can have multiple connections. Not available to Start users."

How many connections I can have? Looks like I am not allowed more than 3 connections...If i have more than 3 connection I am auto disconnected . Tested on GROW plan.

Thanks!

**Comment by evancarter-iex** [comment]
@gabrieldodan Please start to use support@iexcloud.io so we can get you a faster response.  We allow more than 3 connections on our side.
