### ISSUE TITLE
The Logo Endpoint isn't returning any logo for SPY

### ISSUE THREAD

**Issue by Jacyle** [iexg/IEX-API#1265]
**Clearly describe the problem**
The following returns no logo:

company_symbol = requests.get('https://cloud.iexapis.com/stable/stock/%s/logo?token=%s' % ('SPY',os.getenv('IEX_TOKEN'))).json()

**What time did the problem occur? (with timezone)**
Within the past week or so

**What is the expected behavior?**

**Your environment (e.g. browser, OS, API version, language):**
Browser, Windows, stable, Python

**Comment by evancarter-iex** [comment]
is this just for SPY?

**Comment by joshuablackburn-iex** [comment]
The company logo endpoint only returns logos for companies. SPY isn't a company, so we do not have a logo at this time.

**Comment by McQgit** [comment]
@evancarter-iex  @joshuablackburn-iex  The logo endpoint does return symbols for some ETFs at least - iShares EEM and Invesco PGF for example.  The logo for them is the sponsor logo.
