### ISSUE TITLE
[Data] SFB symbol returns 404 

### ISSUE THREAD

**Issue by juliuskittler** [iexg/IEX-API#1266]
**Clearly describe the data problem**

Some of the IEX tickers for which I request intra-day data (1-min resolution for a specific date), return response `404`  instead of intra-day data. This is the case even for tickers that are marked as `isEnabled` in the ticker overview (https://cloud.iexapis.com/stable/ref-data/iex/symbols?format=csv&token={}). 

Example: On Sunday (06.10.2019), I request the complete ticker overview for Friday (the request always returns the overview for the latest work week day). On the same Sunday, I request all enabled tickers according to the overview (https://cloud.iexapis.com/stable/stock/{}/chart/date/{}?format=csv&token={}&chartIEXOnly=true) for the same Friday. Then, some of the requests for tickers that were listed as `isEnabled`  return `404` error codes.

**Data URL (The URL you used to access the data without your token):**

This is the url used to get all tickers. From these, I filter to only get the tickers where `isEnabled==True`: https://cloud.iexapis.com/stable/ref-data/iex/symbols?format=csv&token={}

This is the url, I use to get the data for the resulting tickers: https://cloud.iexapis.com/stable/stock/{}/chart/date/{}?format=csv&token={}&chartIEXOnly=true

**What time did the problem occur (including timezone)?**

Sunday, 6.10.2019. It has always been occurring for certain tickers in the past.

**What is the expected behavior?**

Intra-day data like for all other tickers (for which it works well) should be returned.

**What are the steps to reproduce**

1. Check the tickers in Additional context. All of them are enabled according to https://cloud.iexapis.com/stable/ref-data/iex/symbols?format=csv&token={} as of Friday, 04.10.2019.
2. Request them with https://cloud.iexapis.com/stable/stock/{}/chart/date/{}?format=csv&token={}&chartIEXOnly=true and you will see that they return `404`.

**Your environment (e.g. browser, OS, API version, language):**

- macOS Mojave, 10.14
- various browsers (Chrome, Opera)
- API version: see api_urls above (it seems like they use the last stable version)

**Additional context**

symbol,name,date,isEnabled,type,iexId
ALL-D*,,2019-10-04,true,N/A,8185
ALL-E*,,2019-10-04,true,N/A,8323
ALL-F*,,2019-10-04,true,N/A,8857
BFS-C*,Saul Centers Inc. Depositary Shares Series C,2019-10-04,true,ps,707
CBO,,2019-10-04,true,N/A,7897
CBX,,2019-10-04,true,N/A,7898
FRC-D*,First Republic Bank San Francisco California Depositary Shares Series D,2019-10-04,true,ps,2629
GDV^#,,2019-10-04,true,N/A,16154
JMPB*,JMP Group Inc 8.00% Senior Notes due 2023,2019-10-04,true,N/A,3801
NNN-E*,National Retail Properties Depositary Shares Series E,2019-10-04,true,ps,4879
NTEST,,2019-10-04,true,N/A,11845
NTEST.A,,2019-10-04,true,N/A,11846
NTEST.B,,2019-10-04,true,N/A,11847
NTEST.C,,2019-10-04,true,N/A,11848
PSA-U*,Public Storage Depositary Shares Series U,2019-10-04,true,ps,5594
SFB,Stifel Financial Corporation 5.20% Senior Notes due 2047,2019-10-04,true,N/A,13551
UBP-G*,,2019-10-04,true,N/A,9456
ZAZZT,,2019-10-04,true,N/A,11842
ZBZX,,2019-10-04,true,N/A,7904
ZBZZT,,2019-10-04,true,N/A,11843
ZCZZT,,2019-10-04,true,N/A,11844
ZEXIT,ZEXIT Test Incorporated,2019-10-04,true,N/A,15033
ZIEXT,ZIEXT Test Incorporated,2019-10-04,true,N/A,13389
ZJZZT,,2019-10-04,true,N/A,7905
ZTEST,,2019-10-04,true,N/A,7906
ZVV,,2019-10-04,true,N/A,7907
ZVVV,,2019-10-04,true,N/A,7908
ZVZZT,NASDAQ TEST STOCK,2019-10-04,true,N/A,7909
ZWZZT,NASDAQ TEST STOCK,2019-10-04,true,N/A,7910
ZXIET,ZXIET Test Incorporated,2019-10-04,true,N/A,13391
ZXZZT,NASDAQ TEST STOCK,2019-10-04,true,N/A,7911

**Comment by evancarter-iex** [comment]
@juliuskittler A lot of these are test stocks and wont have any data.

**Comment by evancarter-iex** [comment]
@juliuskittler Im looking into the some of the others that should have data.

**Comment by juliuskittler** [comment]
@evancarter-iex, would it be possible to label test stocks as such?

**Comment by evancarter-iex** [comment]
@juliuskittler i mean most of the test ones have TEST in the name or description. But Ill look into it.

**Comment by juliuskittler** [comment]
@evancarter-iex if these are TEST tickers for you guys at IEX, then maybe it would be an option to just not return any of these tickers to the public https://cloud.iexapis.com/stable/ref-data/iex/symbols?format=csv&token={}

**Comment by evancarter-iex** [comment]
Looking into this. The following symbols all work:

curl https://cloud.iexapis.com/beta/stock/ALL-D/quote?token=
curl https://cloud.iexapis.com/beta/stock/ALL-E/quote?token=
curl https://cloud.iexapis.com/beta/stock/ALL-F/quote?token=
curl https://cloud.iexapis.com/beta/stock/BFS-C/quote?token=
curl https://cloud.iexapis.com/beta/stock/FRC-D/quote?token=
curl https://cloud.iexapis.com/beta/stock/GDV^/quote?token=
curl https://cloud.iexapis.com/beta/stock/JMPB/quote?token=
curl https://cloud.iexapis.com/beta/stock/NNN-E/quote?token=

curl https://cloud.iexapis.com/beta/stock/PSA-U/quote?token=
curl https://cloud.iexapis.com/beta/stock/SFB/quote?token=
curl https://cloud.iexapis.com/beta/stock/UBP-G/quote?token=

Looking into why SFB doesnt work.

The rest are test symbols from various exchanges. They are used for testing in various places so we need to keep them in the symbology.

**Comment by evancarter-iex** [comment]
Fixed.
