### ISSUE TITLE
Problems extracting 52week high data (but other company data works

### ISSUE THREAD

**Issue by mmbarbon** [iexg/IEX-API#1267]
Just started getting data, but ran into an issue. 

https://cloud.iexapis.com/stable/stock/GE/company?token works   but https://cloud.iexapis.com/stable/stock/GE/week52high?token does not.  I keep getting forbidden.

Note in Google docs, the  IMPORTDATA("https://cloud.iexapis.com/stable/stock/"&A12&"/company?token also works.  but =IMPORTDATA("https://cloud.iexapis.com/stable/stock/"&A12&"/week52high?token does not....

I was successful with quote/open, etc.

**Comment by McQgit** [comment]
@mmbarbon The `week52high` data item is part of the `stats` endpoint.  You need to include the endpoint name before its data item.  Example:

`https://cloud.iexapis.com/v1/stock/ge/stats/week52high?token=(redacted)`

See []https://iexcloud.io/docs/api/#key-stats

Your company example worked as that is an endpoint name.  You should have seen multiple items in json using that one.

**Comment by mmbarbon** [comment]
Perfect..  Worked.   THankyou very much for the quick response....
