### ISSUE TITLE
[Request] OHLC for international symbols

### ISSUE THREAD

**Issue by videokojot** [iexg/IEX-API#1268]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Is your feature request related to a problem? Please describe.**
Hello,
We would like to use OHLC data for the international stock symbols, but currently the API returns the only the EOD data. 

Is there plan/roadmap for those to be available?

**Describe the solution you'd like**
OHLC historical data for international markets

**Describe alternatives you've considered**
We woudl need to start using another data provider for those data.

**Additional context**

**Comment by evancarter-iex** [comment]
This is available via the /chart endpoint.
