### ISSUE TITLE
Getting CSV Data Dump for /stock/{symbol}/quote

### ISSUE THREAD

**Issue by eddadjei** [iexg/IEX-API#1269]
I am wanting to upgrade my subscription and wanted to know how I would be able to get /stock/{symbol}/quote for all securities as a csv instead of making a single API call per symbol.

I would need the actually NASDAQ feeds not only the IEX quotes

**Comment by McQgit** [comment]
@eddadjei  Here's some bits to get you started:

You can retrieve 100 quotes at a time using `batch`.  Example:
`https://cloud.iexapis.com/stable/stock/market/batch?symbols=sbux,mcd&types=quote&token=X`
See: []https://iexcloud.io/docs/api/#batch-requests

For Nasdaq, see this important notice:
[]https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud
