### ISSUE TITLE
Sandbox testing SSE

### ISSUE THREAD

**Issue by xchen10bu** [iexg/IEX-API#1270]
Hi, I'm trying to build a connection with the new iexcloud api. But when I try the GET request of : https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=spy&token=TEST_TOKEN. I could not access the end point...Is this the correct way of testing sse? Thanks!

**Comment by evancarter-iex** [comment]
@xchen10bu that looks correct, what is the response you receive?

**Comment by xchen10bu** [comment]
I received no response. Just kept waiting

**Comment by evancarter-iex** [comment]
@xchen10bu try curl --header 'Accept: text/event-stream' https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=spy&token=TESTTOKEN

**Comment by xchen10bu** [comment]
curl --header 'Accept: text/event-stream' https://sandbox-sse.iexapis.com/stable/stocksUS\?symbols\=spy\&token\=TESTTOKEN works. I need to add slashes. Thanks!
