### ISSUE TITLE
Today's `change` and `changePercent` properties missing from /chart endpoint

### ISSUE THREAD

**Issue by GoldbergGLG** [iexg/IEX-API#1272]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
Similar to:
https://github.com/iexg/IEX-API/issues/1271

We are getting zeros back for the `change` and `changePercent` properties.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/aapl/chart/1m?chartLast=5&token=TOKEN&filter=date,high,low,close,volume

**What time did the problem occur (including timezone)?**
Approximately 2PM and after, but the larger issue started earlier today (10/09/19)

**What is the expected behavior?**
We should get back the real `change` and `changePercent`

**What are the steps to reproduce**
As before Select any ticker within the `chart` (historical data) endpoint

**Your environment (e.g. browser, OS, API version, language):**
various.

**Additional context**
This almost definitely relates to the issue introduced earlier in the day:
https://github.com/iexg/IEX-API/issues/1271

**Comment by evancarter-iex** [comment]
@GoldbergGLG this should get resolved soon. We are just waiting for some long running jobs to finish.

**Comment by evancarter-iex** [comment]
This should be resolved now.
