### ISSUE TITLE
[Issue] Sandbox time series data causes unknown error

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#1273]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**

``/time-series`` works in prod but not sandbox

**What time did the problem occur? (with timezone)**

8pm EST 10/9

**What is the expected behavior?**

**Your environment (e.g. browser, OS, API version, language):**

**API URL (if applicable)**

``/time-series``

**What are the steps to reproduce the bug?**

**Additional context**

Works ok in prod:

https://cloud.iexapis.com/stable/time-series?token=
OK

https://sandbox.iexapis.com/stable/time-series?token=
An unknown error occurred

**Comment by evancarter-iex** [comment]
@addisonlynch This should be fixed now.

**Comment by addisonlynch** [comment]
@evancarter-iex thanks.
