### ISSUE TITLE
Intraday request..

### ISSUE THREAD

**Issue by lars670** [iexg/IEX-API#1275]
Have you made any changes to the intraday request?

This works:
https://cloud.iexapis.com/stable/stock/AA/intraday-prices/date/20191010?token=pk_XX
This does not work anymore:
https://cloud.iexapis.com/stable/stock/AA/intraday-prices/date/1d?token=pk_XX
And returns: "You have supplied invalid values for this request"

This is new behaviour

**Comment by evancarter-iex** [comment]
@lars670 we are looking into this currently.

**Comment by evancarter-iex** [comment]
@lars670 https://cloud.iexapis.com/stable/stock/AA/intraday-prices/1d?token=pk_XX should work. intraday-prices is really for todays data only. If you want historical intraday day, you should use the chart endpoint. Hope that helps.
