### ISSUE TITLE
[Issue] US Exchanges endpoint record missing a response atribute

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1276]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**

Endpoint /ref-data/market/us/exchanges contains a record for an exchange with response attribute name of "Off Exchange" but the longName response attribute does not appear in output. 

**What time did the problem occur? (with timezone)**

10/13/19 9:11 PM PST

**What is the expected behavior?**

longName response attribute to be defined for each record, even if blank.

**Your environment (e.g. browser, OS, API version, language):**

Browser

**API URL (if applicable)**

https://cloud.iexapis.com/v1//ref-data/market/us/exchanges?token=XXX

**What are the steps to reproduce the bug?**

Visit endpoint

**Additional context**

![image](https://user-images.githubusercontent.com/8920632/66729750-48c92d80-ee02-11e9-80dd-6ea8c4adf41f.png)

**Comment by evancarter-iex** [comment]
@MorningSleeper Thanks. This will be fixed in the next deploy.
