### ISSUE TITLE
[Issue] Question about crypto response attributes being null with some crypto symbols

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1278]
**Clearly describe the problem**

I am trying to get quote data for some of the more popular cryptos such as BTC, ETH and LTC. I tried crypto pairs that end in USD like

BTCUSD
ETHUSD
LTCUSD

but they all have null values for the following response attributes?

high
low
previousClose

According to following page they all have had volume in past 24 hours at the data source used so how come those response attributes are null?

[https://coinmarketcap.com/exchanges/gemini/](https://coinmarketcap.com/exchanges/gemini/
)

If I am using the wrong symbols, can you please recommend one for each that would contain such data? 

**API URL (if applicable)**

https://cloud.iexapis.com/v1/crypto/BTCUSD/quote?token=xxx

**Comment by timpaine-iex** [comment]
what does `previousClose` mean in the context of an exchange that is always open?

**Comment by MorningSleeper** [comment]
@timpaine-iex according to your API docs it means something ...

![image](https://user-images.githubusercontent.com/8920632/116480416-28bb5c80-a836-11eb-8e1b-82166d02366d.png)

If the endpoint is not going to support it that is fine but perhaps remove it from the documentation then?
