### ISSUE TITLE
[Issue] Crypto endpoint returns data from quote endpoint for unsupported crypto symbols

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1279]
**Clearly describe the problem**

Don't know if this is an intended "feature" but if one tries to use a symbol with the crypto endpoint that is not in the list of supported crypto symbols but is in the list of supported stock symbols, it seems to redirect to the /stock/{symbol}/quote/ endpoint and return data from it. Shouldn't it return a 404 like other endpoints that get a request for an unsupported symbol so we can return a helpful error message about the symbol not being supported for the crypto endpoint?

**API URL (if applicable)**

https://cloud.iexapis.com/v1/crypto/GOOG/quote?token=XXX

**Comment by MorningSleeper** [comment]
@timbaker-iex I take it then this is by design and we just need to do our own symbol validation?

**Comment by timpaine-iex** [comment]
don't really need to do "validation", there are endpoints for symbols vs crypto symbols

**Comment by MorningSleeper** [comment]
Very well, I just asked as some end users mistakenly enter stock symbols in a feature I have to look up price of a crypto symbol in the crypto endpoint, so it helps to validate them as a known crypto symbol before sending the request to the crypto API since it redirects to stock quote endpoint instead of returning a 404 error.

**Comment by timpaine-iex** [comment]
this is how it was implemented in [the original API](https://iextrading.com/developers/docs/#getting-started) so it remains for backwards compatibility (for now)

**Comment by MorningSleeper** [comment]
Ah ok, thanks.
