### ISSUE TITLE
Market Active, Losers, Gainers

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#128]
## Summary

Losers list have stock gainers and Gainers list have stock losers. 

## Details
Both API and Website, Losers list have stock gainers and Gainers list have stock losers.  The Gainers should be green list and Losers should be red list.

### Date/time of issue
12-1-2017

### API URL

https://api.iextrading.com/1.0/stock/market/list/gainers
https://api.iextrading.com/1.0/stock/market/list/losers

### What you expected to happen

Do losers have change in negative and Gainers have change in positive? Maybe we don't understand your criteria. How do you screen actives, losers and gainer?

### Other Information (sample code, links, etc.)

Thanks for providing this API. We will help you to improve.

**Comment by bishinew** [comment]
When market opens this morning, it seems working fine now. Thanks

**Comment by kayos592** [comment]
Is there anyway I can get the gainers list can match this?
https://finance.yahoo.com/gainers

**Comment by joshuablackburn-iex** [comment]
@kayos592 The criteria for our list may be different than what Yahoo uses, and we do not have any plans at this time to replicate their functionality.

**Comment by bishinew** [comment]
https://api.iextrading.com/1.0/stock/market/list/gainers
https://api.iextrading.com/1.0/stock/market/list/losers

The website and API are not correct in the weekends.  During the regular trading days, they seems OK. Please check.
