### ISSUE TITLE
[Issue] Crypto response attributes missing for some symbols

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1281]
**Clearly describe the problem**

I notice some supported crypto symbols, for example LTCBTC, are missing the following response attributes.

bidPrice
bidSize
askPrice
askSize

Shouldn't they appear in JSON response of all supported crypto symbols even if blank?

**API URL (if applicable)**

https://cloud.iexapis.com/v1/crypto/LTCBTC/quote?token=XXX

**Comment by evancarter-iex** [comment]
@MorningSleeper I'm seeing this data so I am closing this issue.

**Comment by MorningSleeper** [comment]
Agreed that one is now showing the response attributes but others supported symbols are still not take for example ETHUSD

![image](https://user-images.githubusercontent.com/8920632/68078144-95fb4800-fd8d-11e9-91b9-d9224c0d4495.png)

https://cloud.iexapis.com/v1/crypto/ETHUSD/quote?token=XXX
