### ISSUE TITLE
[Issue] chartLast does not work

### ISSUE THREAD

**Issue by dsrapaport** [iexg/IEX-API#1283]
**Clearly describe the problem**
chartLast does not work

**What time did the problem occur? (with timezone)**
Today at 5:30am PST

**What is the expected behavior?**
produces the last 5 data points

**Your environment (e.g. browser, OS, API version, language):**
Win 10

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/aapl/chart/3m?token=<INSERT YOUR TOKEN HERE>&chartLast=5

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by evancarter-iex** [comment]
@dsrapaport This should be resolved.

**Comment by evancarter-iex** [comment]
@dsrapaport you are correct I am in the process of fixing it

**Comment by evancarter-iex** [comment]
The fix is rolled out.
