### ISSUE TITLE
[Issue] Second issue this AM -- incorrect data

### ISSUE THREAD

**Issue by dsrapaport** [iexg/IEX-API#1284]
The query below is giving the incorrect data:

https://cloud.iexapis.com/stable/stock/aapl/chart/1m?chartLast=5&token=pk_XXXXXX&filter=date,high,low,close,volume

The high, low, close, and volume data are incorrect.  This is related to the chartLast issue I pointed out earlier this morning.  Specifically, it is giving the first 5 days data instead of the last 5 days data.

**Comment by evancarter-iex** [comment]
This should fixed now.
