### ISSUE TITLE
[Data] Excel API issue

### ISSUE THREAD

**Issue by mbaichikov** [iexg/IEX-API#1285]
I'm pretty new to this whole API thing but I have a question in regard to pulling date into excel. I'm trying to create a quick way to get fundamental data into excel. Though when I pull it, it shows the entire balance sheet not just one category 

This is my formula: =WEBSERVICE("https://cloud.iexapis.com/stable/stock/" &A4& "/balance-sheet/currentCash?token=*********")

But it comes out looking like that.

[https://ibb.co/NnYPXXv](url)

How should it be changed just to pull specific data into excel?

**Comment by timpaine-iex** [comment]
https://iexcloud.io/community/blog/an-introduction-to-fundamental-analysis-in-excel
