### ISSUE TITLE
[Data] New dividend data and key stats not matching

### ISSUE THREAD

**Issue by ngburke** [iexg/IEX-API#1289]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
I was excited to see that there was some improvement in the dividend data. For my app's purposes, what is contained in the stats endpoint is sufficient. Unfortunately, on the first ETF I checked (VOO) the data does not match. Furthermore, other ETFs such as SPYD continue to report `null` for dividend data.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/voo/dividends?token=(redacted)
https://cloud.iexapis.com/stable/stock/voo/stats?token=(redacted)

**What time did the problem occur (including timezone)?**
2:47pm UTC +7

**What is the expected behavior?**
`dividendYield` and `ttmDividendRate` should not be `null`. It would also be nice if `nextDividendDate` could be filled in.

**What are the steps to reproduce**
Compare data from the two URLs

**Your environment (e.g. browser, OS, API version, language):**
n/a

**Additional context**

**Comment by evancarter-iex** [comment]
@ngburke We are in final testing to release stats so that data is filled in.

**Comment by evancarter-iex** [comment]
@ngburke This should be resolved. Please email support@iexcloud.io if you see any additional issues
