### ISSUE TITLE
Order book exchanges

### ISSUE THREAD

**Issue by flynnben123** [iexg/IEX-API#129]
This is not so much an issue as it is a question(which I had to put here since IEX does not offer any other form of support), does the IEX api offer order book data that comes from other exchanges.  For example, is there a way to get bid, bid size, ask, and ask size information from NYSE, NASDAQ, and other exchanges through the IEX exchange or is it just bids and asks that go through the IEX exchange?  I only ask because I notice that on exchanges such as BATS they offer other exchanges information as well.

**Comment by joshuablackburn-iex** [comment]
Order book information on our API is for IEX only.  Other exchange information has associated fees and requires individual contracts with the exchange.
