### ISSUE TITLE
[Issue] Upcoming-dividends has some liquidated ETFs listed in it

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#1291]
**Clearly describe the problem**
The upcoming-dividends endpoint with new dividend provider returns a number of records for ETF dividends whose symbols are not listed in your ref-data/symbols.  Most ETF dividends are in ref-data/symbols - but not all.  There was about 20 missing as of now.

**What time did the problem occur? (with timezone)**
Fri Oct25 2019 at 8am eastern

**What is the expected behavior?**
To find /ref-data/symbols data for all tickers in /upcoming-dividends

**Your environment (e.g. browser, OS, API version, language):**
n/a

**API URL (if applicable)**
/ref-data/symbols and /upcoming-dividends

**What are the steps to reproduce the bug?**
Retrieve /upcoming-dividends to list all symbols.  Remove symbols in /ref-data/otc/symbols.  Compare remaining symbols to /ref-data/symbols.  Note there will also be many 5-letter symbols which won't be found but I didn't evaluate why (many probably in mutual fund symbol list).  So, just look at symbols with less than 5 characters for this purpose.

**Additional context**
Here are 3 upcoming-dividend records without matching /ref-data/symbols:

{"exDate":"2019-12-30","paymentDate":"2020-01-08","recordDate":"2019-12-31","declaredDate":"2019-02-12","amount":"","flag":null,"currency":"","description":"Global X JPMorgan Efficiente Index ETF","frequency":null,"symbol":"EFFE"}

{"exDate":"2019-12-20","paymentDate":"2019-12-26","recordDate":"2019-12-23","declaredDate":"2019-05-10","amount":"","flag":null,"currency":"","description":"Columbia EM Quality Dividend ETF","frequency":null,"symbol":"HILO"}

{"exDate":"2019-11-12","paymentDate":"2019-11-18","recordDate":"2019-11-13","declaredDate":"2019-01-16","amount":"","flag":null,"currency":"","description":"VanEck Vectors High Income Infrastructure MLP ETF","frequency":null,"symbol":"YMLI"}

Other symbols in upcoming-dividends not in ref-data/symbols

SCTO, INXX, SCIN, AXJV, BCNA, GDXX, GDXS, HYDD, XMX, BBRC, PRME, TYNS, DEZU, LLQD, IBMH, MLQD, DEWJ, EUXL, BKCH, XINA, WYDE

**Comment by evancarter-iex** [comment]
https://www.etfexpress.com/2019/06/17/276559/global-x-liquidate-two-etfs
https://www.etfexpress.com/2019/05/16/275761/columbia-threadneedle-liquidate-four-etfs

http://www.direxion.com/products/daily-high-yield-bear-2x-shares
https://seekingalpha.com/news/3500779-wisdomtree-close-global-ex-mexico-equity-fund

Looks like most of these have been liquidiated or going to be liquidated. Not sure if any of them are doing final dividend payouts.

**Comment by McQgit** [comment]
@evancarter-iex  Well, perhaps I misunderstand the purpose of /ref-data/symbols.   I have been using it to obtain metadata about symbols in your system.  Like the 'type' of security and its name.  That's helpful, even needed, to select the symbols I want to focus on.

But, your ref-data/symbols doesn't have info on these items.  Fair enough that /ref-data is missing it for liquidated ETFs.  But, shouldn't they then be suppressed from /upcoming-dividends?

If /ref-data/symbols describes all the symbols valid in your API, why do you pass through these symbols for /upcoming-dividends when they don't show in any other endpoint?

I'll note that there are other kinds of symbols in /upcoming-dividends that are not in /ref-data/symbols.  Some are preferred shares which can be identified using the description in /upcoming-dividends.  Others are hard to tell w/out manual lookup.  Not even all the missing ETFs have 'ETF' in their description.

**Comment by evancarter-iex** [comment]
@McQgit /ref-data/symbols are the list of currently active stocks/etfs that are traded on IEX (its a legacy based on the old api).  

https://cloud.iexapis.com/stable/ref-data/region/us/symbols is an easy way to obtain the entire universe of symbols in the US that we have data for, including mutual funds etc.

As for suppressing liquidated symbols from upcoming-dividends, I would agree but I'm still looking into if they had any outstanding/or still upcoming dividends that would pay out.

**Comment by McQgit** [comment]
@evancarter-iex Ok, I'll start using that symbol list.  But, you might want to note this in your docs.  You say above that `/ref-data/symbols` is for traded symbols.  But, the docs say `/ref-data/iex/symbols` is for traded but /ref-data/symbols is for all api symbols.  Maybe just a short note in the docs for /ref-data/symbols to start using /ref-data/region/us/symbols instead?

**Comment by evancarter-iex** [comment]
@McQgit yeah totally agree, we are working on how to refactor ref-data for v2 to make it a lot better. But its a big process. But in the meantime I'll add a note.
