### ISSUE TITLE
[Data] New dividend data source use flag 'cash' instead of indicating increase/decrease

### ISSUE THREAD

**Issue by WillTron** [iexg/IEX-API#1292]
**Clearly describe the data problem**
the recent switch to the new dividend data provider fails to generate usable content for the [flag] and [description] array elements for the /dividends/ endpoint compared to the previous div data provider. My web app uses these key:values to generate a list of tickers in a user's portfolio that have declared dividend "increases" or "decreases" including highlighting in green (div increase) or red (div decrease) the web page content that outputs a list in nicely formatted Bootstrap notification elements.

The old dividend endpoint had [flag] key values that were one of the following: 'Special', 'Interim', 'Resume', 'Increase', 'Decrease', 'Initiation', 'No Change' or 'Stock'. Instead, now it just says 'Cash' for every ticker that distributes a cash dividend. Thus, the code in my app can no longer locate tickers with declared dividend increases/decreases. In other words, this feature in my app no longer works. In addition, the [description] key in the new dividend data outputs a value of 'Ordinary Shares' instead of a more informative description as before -- which I also used heavily in my increase/decrease web app feature. My particular usage of IEX data is predominantly dividend data oriented. this recent change on your end impacts my web app in a significant way.

**Example:**
New /dividends/ endpoint output -
flag => Cash
description => Ordinary Shares

Prior endpoint output -
flag => Increase
description => JPMorgan Chase & Co. Hikes Quarterly Dividend 12.50%

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=jpm&types=dividends&token=my_token

**What time did the problem occur (including timezone)?**
after you changed your dividend data provider

**What is the expected behavior?**
for it to be as before, or at the very least, IEX should inform their paying subscribers in ADVANCE that the format of the content for endpoints is going to be changing -- these kind of changes affect users apps. I get it ... you can't please all of the people all of the time, but in this particular case IEX could have been a little more forthcoming -- especially since you have been working on this dividend data switch-over for many months.

**What are the steps to reproduce**
just do a /dividends/ api call for any ticker and compare result output with previous dividend data output

**Your environment (e.g. browser, OS, API version, language):**
latest Chrome, Win10 Pro, IEX Cloud v1, Launch Plan

**Additional context**
**New json output:**
```
{
  "JPM": {
    "dividends": [
      {
        "exDate": "2019-10-03",
        "paymentDate": "2019-10-31",
        "recordDate": "2019-10-04",
        "declaredDate": "2019-06-27",
        "amount": "0.9",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2019-10-25"
      }
    ]
  }
}
```
**Old json output:**
```
{
  "JPM": {
    "dividends": [
      {
        "exDate": "2019-10-03",
        "paymentDate": "2019-10-31",
        "recordDate": "2019-10-04",
        "declaredDate": "2019-06-27",
        "amount": 0.9,
        "flag": "Increase",
        "currency": "USD",
        "description": "JPMorgan Chase & Co. Hikes Quarterly Dividend 12.50%",
        "frequency": "Quarterly",
        "date": "2019-09-28"
      }
    ]
  }
}
```

**Comment by evancarter-iex** [comment]
hey @WillTron can you email us at support@iexcloud.io. I want to see what we can do to help you in this.
