### ISSUE TITLE
BABA shares outstanding 10.000x too low

### ISSUE THREAD

**Issue by nickkraakman** [iexg/IEX-API#1295]
Hi,

Since Friday, symbol BABA returns `sharesOutstanding` not as an integer, but as a decimal, and the value is _way_ too low.

The value returned by the IEX Cloud `stats` endpoint is `261787.0993`, or ~261K, while BABA actually has ~2.6 **Billion** shares outstanding. 

The dot in the returned value seems to be the issue, as this dot is also not present in the shares outstanding of other symbols.

**Comment by evancarter-iex** [comment]
Hi there,

I am showing 2617870993 shares outstanding. Can you confirm on your side?
