### ISSUE TITLE
[Issue] Brand new account, getting 402 Payment Required for basic API calls

### ISSUE THREAD

**Issue by emptyopen** [iexg/IEX-API#1296]
**Clearly describe the problem**
I get a 402 Payment required exactly in the same manner as other closed issues here.

**What time did the problem occur? (with timezone)**
Time of this post

**What is the expected behavior?**
200

**Your environment (e.g. browser, OS, API version, language):**
Windows 10, stable, Python

**API URL (if applicable)**
Any

**What are the steps to reproduce the bug?**
Call any basic API endpoint

**Additional context**

**Comment by evancarter-iex** [comment]
@emptyopen Is this still an issue for you? If so can you email support@iexcloud.io so we can fix it for you?

**Comment by emptyopen** [comment]
Hi this was resolved with an email! My misunderstanding of the docs.
