### ISSUE TITLE
[Issue] Earnings API is not honoring the last param

### ISSUE THREAD

**Issue by Siddeshwaraswamy** [iexg/IEX-API#1297]
**Clearly describe the problem**
When I make the call 
https://cloud.iexapis.com/beta/stock/aapl/earnings/last/4
or
https://cloud.iexapis.com/stable/stock/aapl/earnings/last/4
it returns only last quarter earnings. Ideally, it should last four-quarter earnings. 

**What time did the problem occur? (with timezone)**
7:30AM PST

**What is the expected behavior?**
It should give results depending requested "last" param.

**Your environment (e.g. browser, OS, API version, language):**
Chrome

**API URL (if applicable)**
https://cloud.iexapis.com/beta/stock/aapl/earnings/last/4
https://cloud.iexapis.com/stable/stock/aapl/earnings/last/4

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by evancarter-iex** [comment]
@Siddeshwaraswamy Are you on a free account?

**Comment by Siddeshwaraswamy** [comment]
Yes, does that make a difference?

**Comment by evancarter-iex** [comment]
@Siddeshwaraswamy Free accounts only get access to the last earnings data. See Notes in the documentation: https://iexcloud.io/docs/api/#earnings
