### ISSUE TITLE
[Issue] Forex Data New Source - takes 5 sec for each call

### ISSUE THREAD

**Issue by thinkcodellc** [iexg/IEX-API#1298]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**
The new source for Forex, supposed to be endpoint for latest data for forex on an avg takes 5 seconds for each request. Its latency makes it a costly call for the data weight of 500.

**What time did the problem occur? (with timezone)**
Verified at 7 PM CST

**What is the expected behavior?**
Low latency as other instruments like crypto or stock

**Your environment (e.g. browser, OS, API version, language):**
Chrome Browser

**API URL (if applicable)**
https://cloud.iexapis.com/stable/fx/latest?symbols=USDINR

**What are the steps to reproduce the bug?**
Invoke the URL

**Additional context**
5 sec latency is pretty large be usable

**Comment by evancarter-iex** [comment]
@thinkcodellc We are looking into this

**Comment by evancarter-iex** [comment]
@thinkcodellc This should be resolved now.

**Comment by thinkcodellc** [comment]
@evancarter-iex  Thanks for the fast resolution. Works now 430ms!

**Comment by luke-kehoe** [comment]
I've currently been experiencing this for the last week or so.
