### ISSUE TITLE
Whats the purpose of the pcap files available through /hist

### ISSUE THREAD

**Issue by MoorsTech** [iexg/IEX-API#13]
Love the API so far!

I'm wondering what the pcap files available through the /hist endpoint are supposed to be used for.
Even when I manage to parse them, I'm unable to decode the payloads and there seems to be no documentation on what I should expect to see once I do manage to decode the payload.

Cheers!

**Comment by joshuablackburn-iex** [comment]
PCAP files are packet captures of our binary data feeds.  These are feeds from the trading system, and not from the API.  Documentation for those are available at https://iextrading.com/trading/market-data/
