### ISSUE TITLE
[Data] Incorrect Dividend data

### ISSUE THREAD

**Issue by Pesiacik** [iexg/IEX-API#1300]
since approx 10/29/2019, API is returning doubled (or more?) dividend information in Google Sheets, eg:

https://cloud.iexapis.com/stable/stock/AM/stats/ttmDividendRate?token=TOKEN
or
https://cloud.iexapis.com/stable/stock/AM/stats/dividendYield?token=TOKEN

- same for other tickers, like BEP, SKT, BEP....

**Comment by ngburke** [comment]
Seeing the same thing for numerous tickers.

**Comment by evancarter-iex** [comment]
This should be resolved.

**Comment by rsksmiles** [comment]
Are we getting invoiced for the duplicates?
I appreciate that the service is low cost - thanks very much for this and your efforts to keep the costs low.
However, I have to code defensively to ensure that I am not adding duplicate dividends to my database.
Please fix this urgently
