### ISSUE TITLE
Possible Data missing from batched historical prices endpoint

### ISSUE THREAD

**Issue by fabiansteuer** [iexg/IEX-API#1301]
**Date/time of the issue**
31 October 2019, 10AM UTC

**What you did**
In Python:
```
import requests
response = requests.get('https://cloud.iexapis.com/v1/stock/market/batch/?symbols=AAPL,ADSK,ALGN,AMT,AMZN,ANET,ATVI,AX,BF.B,BKNG,BL,BRK.B,BZUN,CASY,CGNX,CHGG,CHUY,CMG,COST,CPRT,CTRP,CTSH,CVGW,DEO,DIS,DLTH,DOCU,EB,ERIC,EVH,F,FB,FDS,FDX,FIT,GNTX,GOOG,GPRO,HABT,HACK,HAIN,HAS,HD,HHC,HTHT,IDXX,IMAX,INTU,IRBT,JWN,KO,LULU,MA,MELI,MKL,MNST,MSFT,MTCH,MTN,NFLX,NKE,NLS,NOBL,NOW,PAYC,PLNT,PSTG,PYPL,ROBO,ROIC,ROKU,SAM,SBUX,SFIX,SHOP,SIVB,SMAR,SQ,SSTI,STZ,TDOC,TEAM,TIF,TRIP,TRUE,TRUP,TSLA,TTD,TTWO,TWLO,TWOU,TWTR,TXRH,UAA,ULTA,VB,VEEV,VIGI,VNQ,VOO&types=chart&range=5y&chartCloseOnly=true&token=TOKEN')
data = response.json()
```

**What you expected to happen**
Getting back 5y historical prices for all stocks in the request.

**What actually happened**
Only a single date was returned for many stocks (also ignoring the chartCloseOnly parameter). 

Example:
`data['ADSK']`

Output:
```
{'chart': [{'date': '2019-10-30',
   'uClose': 148.78,
   'uOpen': 146.24,
   'uHigh': 149.52,
   'uLow': 144.84,
   'uVolume': 1114309,
   'close': 148.78,
   'open': 146.24,
   'high': 149.52,
   'low': 144.84,
   'volume': 1114309,
   'change': 0,
   'changePercent': 0,
   'label': 'Oct 30, 19',
   'changeOverTime': 0}]}
```

All stock symbols:
```
for symbol in data:
    print(symbol, len(data[symbol]['chart']))
```

Output:
`AAPL 1258
ADSK 1
ALGN 1258
AMT 1
AMZN 1258
ANET 1258
ATVI 1258
AX 1258
BF.B 1258
BKNG 1258
BL 1
BRK.B 1258
BZUN 1120
CASY 1258
CGNX 1
CHGG 1258
CHUY 1258
CMG 1
COST 1258
CPRT 1258
CTRP 1258
CTSH 1258
CVGW 1258
DEO 1258
DIS 1258
DLTH 992
DOCU 381
EB 280
ERIC 1258
EVH 1110
F 1258
FB 1258
FDS 1258
FDX 1258
FIT 1101
GNTX 1258
GOOG 1258
GPRO 1
HABT 1244
HACK 1250
HAIN 1258
HAS 1258
HD 1
HHC 1258
HTHT 1258
IDXX 1258
IMAX 1258
INTU 1
IRBT 1258
JWN 1
KO 1258
LULU 1258
MA 1
MELI 1258
MKL 1258
MNST 1258
MSFT 1258
MTCH 993
MTN 1
NFLX 1258
NKE 1258
NLS 1
NOBL 1258
NOW 1258
PAYC 1
PLNT 1067
PSTG 1024
PYPL 1090
ROBO 1258
ROIC 1258
ROKU 526
SAM 1
SBUX 1258
SFIX 490
SHOP 1
SIVB 1
SMAR 381
SQ 1
SSTI 605
STZ 1258
TDOC 1092
TEAM 979
TIF 1258
TRIP 1258
TRUE 1258
TRUP 1
TSLA 1258
TTD 783
TTWO 1258
TWLO 845
TWOU 1258
TWTR 1
TXRH 1258
UAA 1258
ULTA 1258
VB 1258
VEEV 1258
VIGI 924
VNQ 1258
VOO 1258`

**Additional relevant information**
For the stock symbols with `len(data[symbol]['chart']) > 1` the historical prices were returned correctly.

**Comment by evancarter-iex** [comment]
@fabiansteuer Can you try again? Im returning data for all symbols now.

**Comment by fabiansteuer** [comment]
Yes, it started working properly again. Let's hope it continues to do so.
