### ISSUE TITLE
IBM dividend info

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1302]
Using endpoint /stock/IBM/advanced-stats and getting following as of time of post.

![image](https://user-images.githubusercontent.com/8920632/68067227-36eff180-fd01-11e9-88e7-99217c73db96.png)

The response attribute ttmDividendRate returns 6.38 when other sources such as the one below show it to be 6.48.
 
[https://www.dividend.com/dividend-stocks/technology/diversified-computer-systems/ibm-ibm-corp/](https://www.dividend.com/dividend-stocks/technology/diversified-computer-systems/ibm-ibm-corp/)

The response attribute dividendYield returns 0.04707444846159522 when other sources such as the example below show it to be .0485

[https://www.dividend.com/dividend-stocks/technology/diversified-computer-systems/ibm-ibm-corp/](https://www.dividend.com/dividend-stocks/technology/diversified-computer-systems/ibm-ibm-corp/)

The response attribute exDividendDate and the nextDividendDate are the same, 2019-11-07. According to the API docs the first attribute is supposed to be the ex date of the last dividend which is correct and the second the ex date of the next dividend which seems incorrect since the next ex div date, while not officially announced, is expected to be around Feb 7th 2020.

[https://www.dividendchannel.com/symbol/ibm/next-dividend-date/](https://www.dividendchannel.com/symbol/ibm/next-dividend-date/)

Appreciate if you can look into these, thanks.

**Comment by McQgit** [comment]
@MorningSleeper  I have a guess as to why the exDividendDate and nextDividendDate are the same but I'll leave it to someone at IEX to respond to you about that.

As for ttmDividendRate, it is correct as shown by IEX.  A ttm rate is the amount of dividends paid in the Trailing Twelve Months.  If you add up the last 4, you get 6.38 (1.62, 1.62, 1.57, 1.57).  The dividend.com source you referenced shows the annualized (or indicated) annual amount.  This is derived using the most recent multiplied by the number of times it's paid per year.  Different things each with their own pros and cons.

The ttm rate can be based on ExDiv dates or Pay dates.  For IBM right now it gives the same result.  But, I'll leave it to IEX to address that issue.  Or, you could search for other examples to see which one they use.  It's one of my pet peeves about dividend info is the site's don't say what methods they use often times (ttm, annualized, ...).  That's pretty much all of them :)

The dividend yield is also correct.  It is just using the ttmDividendRate and not the annualized.

While I'm here, I will hazard a guess about the exDividendDate and nextDividendDate.  I think they are the same for IBM right now as there is an actual next one so there is no need to guess.  After Nov7 I'd expect the next to be as you say, early in Feb.  But, clarity from IEX is best.

I'll add that IEX just over a week ago changed the data provider they used for dividend data.  So, take care when searching this git as their dividend api response was considerably different before that.

**Comment by MorningSleeper** [comment]
Thanks for explaining the reason the ttmDividendRate and dividendYield are different from some other sources, makes sense now.

Regarding the exDividendDate and nextDividendDate, I guess my mind can't wrap itself around the two attributes ever  having the same value if as the API docs state the first is supposed to represent the last ex div date (which i interpret as a date that has already happened) and the other the next ex div date (which I interpret as a date that has not already happened). Of course I may be misinterpreting what last and next mean in the docs so will await further clarification.

**Comment by ngburke** [comment]
I would love it if the `exDividendDate` was the next known ex date (or previous one if there is no announced next one) and the `nextDividendDate` was the next known actual payment date (or previous one if not known).
