### ISSUE TITLE
You have exceeded your allotted message quota

### ISSUE THREAD

**Issue by hilaal** [iexg/IEX-API#1303]
Hi
I am very new to this and have been testing for past two days...

Date/time of the issue: Sun, 3 Nov 2019 17:18:12 +0000

What you did: Filtering FB stock prices columns

What you expected to happen: Download the stock data

What actually happened: Unable to read URL: https://cloud.iexapis.com/stable/stock/market/batch?symbols=FB&types=chart&range=max&token=pk_eb4f53f4ee1c4894b3f487afa2b8f65f
Response Text:
b'You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access'

Additional relevant information: I am just running the sample code from - https://medium.com/@jasonbamford/machine-learning-algorithm-to-predict-stock-direction-d54b7666cc7c

Thank you very much in advance...

**Comment by McQgit** [comment]
@hilaal  I apologize if this seems too basic but have you read the intro material for IEX Cloud?

For example, to learn about the data weighting:
[]https://iexcloud.io/docs/api/#data-weighting

You can review your message use and see what exactly consumed all your alloted messages by logging in to your account.  There is a section which shows each api and the messages used.

As an example, using 'max' with 'chart' (like you did) can use about 37,500 messages each api call:
(15 years X approx 250 market days/year) = 3,750 days X 10 message weight = 37,500
This assumes you have a paid account as free accounts are limited to 5 years of data so a single /max call would only be roughly 12,500 messages.

If you used multiple symbols in your batch request, multiply above by the number of symbols. 

By the way, you should change your token now that you've shown it to the world :)
See:
[]https://iexcloud.io/docs/api/#authentication
