### ISSUE TITLE
[Data] Missing and incorrect data, especially for ADR stocks

### ISSUE THREAD

**Issue by nickkraakman** [iexg/IEX-API#1304]
**Clearly describe the data problem**
When I run calculations on all US listed `Common Stock` and `ADR` symbols available on IEX, I get some strange results, the cause of which I narrowed down to major omissions or discrepancies in the data supplied by the IEX Cloud API.

Here are some examples:

1. **UVE**: `currentCash` returns `null`, while latest quarter `Cash and Cash Equivalents` should equal ~181M according to their SEC filing
**Data URL**: https://cloud.iexapis.com/stable/stock/UVE/balance-sheet
**SEC filing**: https://www.sec.gov/cgi-bin/viewer?action=view&cik=891166&accession_number=0000891166-19-000041&xbrl_type=v#

2. **GGAL**: `netIncome` in 2018 returns `511341082.488638` (~511M), but should equal ~ -3.4B [note the _minus_] according to both Yahoo Finance and Morningstar. It seems IEX converts the ADR source currency (in this case Argentinian Pesos) to USD, but that does not explain how a loss can turn into a profit.
**Data URL**: https://cloud.iexapis.com/stable/stock/GGAL/income?period=annual
**Yahoo Finance**: https://finance.yahoo.com/quote/GGAL/financials?p=GGAL
**Morningstar**: https://financials.morningstar.com/ratios/r.html?t=0P000002J6&culture=en&platform=sal

3. **BMA**: `netIncome` 2018 returns `559508160.779431` (~559M), but should equal ~ -19M [note the _minus_] according to Morningstar
**Data URL**: https://cloud.iexapis.com/stable/stock/BMA/balance-sheet
**Morningstar**: https://financials.morningstar.com/ratios/r.html?t=0P00001XA8&culture=en&platform=sal

Seems like ADR stocks, and ADR _finance_ stocks in particular, have significant data discrepancies that are far beyond small currency conversion differences.

For now, this makes it impossible for me to trust and use any data returned for ADR stocks.

**What time did the problem occur (including timezone)?**
This is happening right now, November 3rd 2019.

**Your environment (e.g. browser, OS, API version, language):**
Chrome 78.0.3904.87 on MacOS 10.14.6.

**Comment by evancarter-iex** [comment]
Hi there,

Per our documentation, the data provider we use has limited information on financial companies:
https://iexcloud.io/docs/api/#balance-sheet  (see the note)

I would recommend using https://iexcloud.io/docs/api/#financials-as-reported to help supplement in this particular case. Hope that helps.

**Comment by nickkraakman** [comment]
Thanks for that suggestion, Evan.

The IEX documentation indeed says:

"Financial information is *limited* for some financial firms."

This explains why UVE `currentCash` returns `null`, but does _not_ explain
why a profit is returned for the other two stocks while they actually seem
to be making a loss.

That is not _limited_ information, but _incorrect_ information.

Also, it seems strange to me to suggest that your users should supplement
data returned for financial stocks, as IEX is providing the missing or
incorrect data, and so it seems IEX should be the one to resolve this
instead of delegating this responsibility to their (paying) users.

Thanks again for your speedy reply, I do appreciate it.
