### ISSUE TITLE
[Data] Institutional owners data

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1305]
Curious how come the following endpoint does not always return 10 results for some symbols as the description in API docs suggest it should when one uses a supported symbol for which there are more than 10 institutional owners? For example as you can see RKDA only returns 1 result.

https://cloud.iexapis.com/v1//stock/RKDA/institutional-ownership?token=

![image](https://user-images.githubusercontent.com/8920632/68177515-63904d00-ff3d-11e9-9dc5-f6eeded824ee.png)

The page below indicates there are 17 total.

https://www.nasdaq.com/market-activity/stocks/rkda/institutional-holdings

I don't know the method by which it is determined if an institutional holder is a buy-side or sell-side firm and thus would or would not qualify to appear in that endpoint's results so if 16 out of the 17 listed on that Nasdaq page are neither I guess that would explain it.

**Comment by McQgit** [comment]
@MorningSleeper  Hey again.  Yeah, the IEX guys are best to address this.  In the meantime, I noticed Cambridge was the only one of the 17 that had a report date of Sep 30.  All others shown on that Nasdaq page were from Jun 30.  Coincidence?

**Comment by MorningSleeper** [comment]
@McQgit good catch, apparently those that are required to file quarterly have 45 days from end of last quarter to report so will be interesting to see if the results returned changes after the 15th. Perhaps IEX limits their results to only those that have reported on the end of and hopefully after the last completed quarter. Will await word from IEX but if so that would seem to often exclude many holders from the list in the 45 days following the end of a quarter since it is apparently common for holders to take advantage of the 45 day delay.

**Comment by joshuablackburn-iex** [comment]
Is this still an issue? I'm seeing 10 results for RKDA

**Comment by MorningSleeper** [comment]
@joshuablackburn-iex It appears institutions are only included in the top 10 if their most recent quarterly filing was within the last quarter which can be problematic as detailed below.

For example when I originally reported this, of the 17 total institutional holders, 1 had a reporting date of Sept 30th (end of last quarter) and was included in endpoint's output while the rest had a reporting date of June 30th ( end of two quarters ago) and thus the 16 others were not considered for inclusion in the endpoints output resulting in the endpoint outputting 1 instead of 10 as reported.

Once the 16 others filed their most recent reports, their last filed date changed from June 30th to Sept 30th, and the endpoint returned and now returns the expected top 10.

The problem is institutions, as you may know, legally have 45 days from end of each quarter to file and thus if the endpoint only looks at those that have done so by the end of the last quarter, it will exclude those that have taken advantage of the 45 delay (which many do)  and if less than 10 have reported by end of last quarter, the endpoint will not be able to output the top 10.

Only solution I can think of is on your end for if the endpoint can't find at least 10 institutions that have reported on time at the end of last quarter, for the endpoint to query for institutions, that don't include those already found, that filed at the end of two quarters ago.
