### ISSUE TITLE
[Data] Missing data for European stocks on US markets' holidays

### ISSUE THREAD

**Issue by dugwood** [iexg/IEX-API#1306]
There's no quotes available on 2019-09-02 and 2019-07-04 for European stocks, although day is valid.

For example with Gecina (French company, quoted at Euronext Paris):
https://sandbox.iexapis.com/v1/stock/GFC-FP/chart/date/20190704?chartByDay=true&token=xxx

All other days are working, including 2019-05-01 which is a holiday in France (returns a close price, but no high/low/volume, as expected).

Tested on sandbox API from a Linux computer.

Thanks :-)

**Comment by evancarter-iex** [comment]
This is resolved.
