### ISSUE TITLE
[Data] Quote endpoint latestTime response attribute

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1307]
Regarding the quote endpoint at https://iexcloud.io/docs/api/#quote

I understand I can use response attribute lastestUpdate to get my desired output format but was curious about the response attribute latestTime. The description in API docs indicates it should return "a human readable _time_"  but, at least when latestSource is equal to Close, it returns a date in format of month, day and year, is it also supposed to include a time or does it sometime just return a date?

**Comment by evancarter-iex** [comment]
Fixed in latest documentation.
