### ISSUE TITLE
[Issue] Dividends endpoint returns wrong data

### ISSUE THREAD

**Issue by philippschladitz** [iexg/IEX-API#1308]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**
Whenever I use the dividends endpoint it is returning the wrong data which is not described in the api.

For example:
https://cloud.iexapis.com/stable/stock/sbfgp/dividends/5y

Returns:
[
    {
        "date": "2019-11-05",
        "open": 0,
        "close": 17,
        "high": 0,
        "low": 0,
        "volume": 0,
        "uOpen": 0,
        "uClose": 17,
        "uHigh": 0,
        "uLow": 0,
        "uVolume": 0,
        "change": 0,
        "changePercent": 0,
        "label": "Nov 5",
        "changeOverTime": 0
    }
]

**What time did the problem occur? (with timezone)**
The problem occured since I tried the endpoint for the first time yesterday.

**What is the expected behavior?**
It should return the attributes listed in the api, like exDate...

**Your environment (e.g. browser, OS, API version, language):**
MacOS, Postman, API Version stable

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/sbfgp/dividends/5y

**What are the steps to reproduce the bug?**
Just run the api request.

**Comment by jdrod0803** [comment]
Also having this issue. Only /next returns the correct data.

**Comment by evancarter-iex** [comment]
We are looking into it

**Comment by evancarter-iex** [comment]
Fix is rolling out.

**Comment by evancarter-iex** [comment]
Fixed
