### ISSUE TITLE
[Data] Quote endpoint Data schedule and extendedPrice description

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1310]
Regarding the quote endpoint at https://iexcloud.io/docs/api/#quote

My understanding is that pre market trading begins at 4:00 AM ET.

The API docs for the quote endpoint shows a data schedule of 4:30am-8pm ET Mon-Fri does that mean it starts updating 30 minutes after pre market trading begins with its first 15 minute delayed quote? If so, curious why not start at 4:15 when the first 15 minute delayed quote would seem to be available?

The extendedPrice response attribute description states "0500 - 0930 ET and 1600 - 2000 ET" does that mean it never contains the extended price in the first hour of pre market trading between 4-5 AM ET? If so, curious why not start at 4:15 when the first 15 minute delayed quote would seem to be available or at least 4:30 when the data schedule starts?

**Comment by evancarter-iex** [comment]
Fixed in documentation.

**Comment by MorningSleeper** [comment]
I assume the fix made to docs  will go out soon as I don't see any change right now.

**Comment by MorningSleeper** [comment]
Ok, thanks for the update, so just to clarify, since the data schedule does not start till 4:30 AM M-F, the extendedPrice will never have a price between 4:00 - 4:29 AM M-F even though the response attribute description includes reference to 4:00 AM correct?
