### ISSUE TITLE
[Data] Quote endpoint iex data

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1312]
Endpoint: https://cloud.iexapis.com/v1/stock/amd/quote?token=

I see the API docs have a note about Nasdaq listed securities stating that one will continue to get Investors Exchange data, is that data for Nasdaq listed securities limited to the response attributes in that endpoint that have a name that begins with iex or does it include any others. If others, can you please provide a list of response attributes which it does or does not include - whichever is shorter? Is it just those that do not return null or might a response attribute be null for some other reason?

**Comment by evancarter-iex** [comment]
https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud has a list of what parts of what endpoints are affected by NASDAQ/UTP requirements.
