### ISSUE TITLE
[Data] How to identify companies that are no longer trading?

### ISSUE THREAD

**Issue by jacklin10** [iexg/IEX-API#1315]
It is difficult to know when a company has stopped trading.  

For example the ticker OAK.  
I pulled quotes from IEX for this ticker until 2019-07-30.

It seems that trading has stopped on this symbol,  but I don't have a way of knowing that.

Looking at the company endpoint doesn't give any hint as to the company's trading status.
(https://cloud.iexapis.com/stable/stock/oak/company)

The iex_symbol endpoint shows isEnabled=true also suggesting trading is still active.

Is there a better way (or any way) for me to tell when a ticker has stopped actively trading?

Thanks!

**Comment by McQgit** [comment]
@jacklin10  I'll be brief in case you've already figured this out and/or IEX fixed it for you.

OAK does not appear in the /iex/symbols list any longer.  There are entries for OAK-A and OAK-B and their quote endpoints are current.  The quote endpoint for OAK is old - as you say.  I guess it's there for historical lookups.

[]https://cloud.iexapis.com/v1/ref-data/iex/symbols?token=(redacted)

**Comment by jacklin10** [comment]
Okay, yeah I'm seeing that now too.  I was thinking it would keep it in symbols but change to disabled in these cases. I guess they just remove it from the list all together?    That's fine I guess.  I'll just have to adjust for that on my end.   Thanks @McQgit!
