### ISSUE TITLE
Anyway to test endpoints in development?

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1316]
Hi, was interested in trying out the short interest endpoint at /stock/{symbol}/short-interest which I see is marked "In Dev" in API docs. Is there any version I can pass to the base URL of it or any other endpoints in development to try it? I tried latest but get 404 error.

Also can you please confirm if this short interest endpoint is still in active development as I don't see it listed in the roadmap and the link to the following document in current API docs

https://iextrading.com/docs/IEX%20Short%20Interest%20Report%20Specification.pdf

contain links to old API that no longer work, thanks.

**Comment by dugwood** [comment]
You may probably use the Cloud version: https://iexcloud.io/docs/api/

**Comment by MorningSleeper** [comment]
@dugwood I tried passing every version name to the endpoint URL and none of them worked.

**Comment by dugwood** [comment]
It's working fine for me. Once you're logged in iexcloud.io, the documentation changes to provide you with sandbox urls:
https://sandbox.iexapis.com/stable/stock/twtr/chart?token=XXX

My only issue to this day... is that adjusted and unadjusted quotes are exactly the same :-( Looking for another provider...

**Comment by MorningSleeper** [comment]
Obviously I don't want to use sandbox URLs for getting real data but even it does not work. As I mentioned I have tried all versions in the endpoint.

https://sandbox.iexapis.com/stable/stock/goog/short-interest
https://cloud.iexapis.com/stable/stock/goog/short-interest
https://cloud.iexapis.com/latest/stock/goog/short-interest
https://cloud.iexapis.com/v1/stock/goog/short-interest

If there is a URL to the short interest endpoint that worked for you, please let me know the URL.

**Comment by dugwood** [comment]
It doesn't work for me either.

**Comment by MorningSleeper** [comment]
Ok, will await word from IEX, thanks.

**Comment by MorningSleeper** [comment]
Nevermind, found the note in the roadmap on the under consideration tab so it appears it is not in development.
