### ISSUE TITLE
[Data] Quote endpoint extendedPriceTime is in future?

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1317]
https://cloud.iexapis.com/v1/stock/sq/quote?token=

![image](https://user-images.githubusercontent.com/8920632/68453711-4365c580-01ab-11ea-8606-0a7587894ef6.png)

Requested on Thursday 11/7/19 10:08 PM PT

extendedPriceTime: 1573261192076

When I convert the above epoch timestamp from milliseconds to a date/time it is

Friday, November 8, 2019 4:59:52.076 PM GMT-08:00 (PT)

Which is about 24 hours after the date I was expecting. I was expecting it to be a time near the end of after hours trading on Thursday evening around 5:00 PM PT, not Friday as Friday has not occurred yet.

I believe the response attribute's timestamp was correct during after hours trading. Don't know why it would but perhaps it is getting reset to the close of after hours trading for the following day once after hours trading has concluded? I think at end of current day it gets set to null. So to replicate, you will need to check this between the end of after hours trading and the end of the current day.

**Comment by evancarter-iex** [comment]
@MorningSleeper Has this reoccurred? I havent seen it.

**Comment by MorningSleeper** [comment]
I will check today between the end of after hours trading and the end of the current day which is the only time I have seen it.

**Comment by MorningSleeper** [comment]
Ok, I tried again on Wednesday 11/13/19 5:03 PM PT or 3 minutes after after hours session closed. As you can see from below the response attribute extendedPriceTime returns a value of 1573778226921 which is Thursday 11/14/19 4:37:06.921 PM PT so a date and time that has not occurred yet which is close to 24 hours in future.

![image](https://user-images.githubusercontent.com/8920632/68817752-928e7900-0637-11ea-95cc-a3b84b16bb17.png)

**Comment by MorningSleeper** [comment]
Gave it one more test at

Wednesday 11/13/19 8:45 PM PT

or 3 hours and 45 minutes after after hours closed but before the end of the day and the extendedPriceTime attribute now returns 1573779553219 which is

Thursday 11/14/19 4:59:13 PM PT

or almost exactly 24 hours in future from todays after hours session close.

![image](https://user-images.githubusercontent.com/8920632/68827404-b4e3bf00-0656-11ea-844f-6059efe1ae42.png)

**Comment by evancarter-iex** [comment]
This should be resolved now. Thanks
