### ISSUE TITLE
Zero OHLC Values in many symbol on Historical Prices API - ERROR

### ISSUE THREAD

**Issue by rmantovani** [iexg/IEX-API#1318]
theres many zero OHLC values in historical prices API

Example:

https://cloud.iexapis.com/stable/stock/AAMC/chart/1y?token=XXXXXX

Symbol: AAMC - Date:"2019-01-25"

{
"date":"2019-01-25",
"open":0,
"close":26.49,
"high":0,
"low":0,
"volume":10,
"uOpen":0,
"uClose":26.49,
"uHigh":0,
"uLow":0,
"uVolume":10,
"change":0,
"changePercent":0,
"label":"Jan 25, 19",
"changeOverTime":-0.410022
},

**Comment by evancarter-iex** [comment]
Hi there,
This is due to the fact that the price did not move during that day.

**Comment by vslee** [comment]
I found another datapoint, but I'm pretty confident that it did move during this day:

https://cloud.iexapis.com/stable/stock/ORCL/chart/date/20150601?chartByDay=true&token=

returns:
`[{"date":"2015-06-01","uClose":43.79,"uOpen":0,"uHigh":44.06,"uLow":43.64,"uVolume":9764305,"close":43.79,"open":0,"high":44.06,"low":43.64,"volume":9764305,"change":0.3,"changePercent":0.6898,"label":"Jun 1, 15","changeOverTime":0.006898}]`

Should I open a separate issue?
