### ISSUE TITLE
[Issue] News API doesn't return any new news since 3 days ago

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1319]
**Clearly describe the problem**
The News API returns the latest news from 8th November when there is clearly newer news available. Actually all the news end on 8th November.

**What is the expected behavior?**
Get the latest news.

**Your environment (e.g. browser, OS, API version, language):**
API

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/market/news/last/10?symbols=GOOGL&token=YOUR_TOKEN

**Comment by evancarter-iex** [comment]
This is resolved.
