### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by jonvonexp** [iexg/IEX-API#1321]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
https://cloud.iexapis.com/stable/stock/T/dividends?token=
returns []
Several other urls did the same, such as with ticker VZ, but, some of them worked...

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/T/dividends?token=
...this is the ticker for AT&T

**What time did the problem occur (including timezone)?**
9pm EST

**What is the expected behavior?**
It should return JSON

**What are the steps to reproduce**
Put https://cloud.iexapis.com/stable/stock/T/dividends?token= into the browser

**Your environment (e.g. browser, OS, API version, language):**
browser

**Additional context**
Tried in both Google sheets and directly in the browser

**Comment by evancarter-iex** [comment]
Hi there,

That is because there was no dividends in the last month. If you use https://cloud.iexapis.com/beta/stock/t/dividends/1y?token= it shows dividends.
