### ISSUE TITLE
[Data] ttmEPS returns null for SBUX

### ISSUE THREAD

**Issue by nickkraakman** [iexg/IEX-API#1323]
**Clearly describe the data problem**
When calling the stats endpoint for `SBUX`, `ttmEPS` returns `null`, but should return an actual value, as it is a regular stock.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/SBUX/stats

**What time did the problem occur (including timezone)?**
Nov 14 2019, 3PM Indochina Time

**What is the expected behavior?**
An actual value for `ttmEPS` should be returned.

**What are the steps to reproduce**
Call the stats endpoint for `SBUX` and check the `ttmEPS` value

**Comment by evancarter-iex** [comment]
This is resolved.
