### ISSUE TITLE
Getting NULL's from Quotes Endpoint

### ISSUE THREAD

**Issue by eddadjei** [iexg/IEX-API#1324]
I am getting nulls (high, low, open, openTime, close, etc) from the quotes endpoint any time **calculationPrice** is **top**

here is an example of a call at 6:44pm CST

https://cloud.iexapis.com/v1/stock/AAPL/quote?token=
```
{
"symbol": "AAPL",
"companyName": "Apple, Inc.",
"primaryExchange": "NASDAQ",
"calculationPrice": "tops",
"open": null,
"openTime": null,
"close": null,
"closeTime": null,
"high": null,
"low": null,
"latestPrice": 262.77,
"latestSource": "IEX price",
"latestTime": "3:59:51 PM",
"latestUpdate": 1573765191429,
"latestVolume": 22222410,
"iexRealtimePrice": 262.77,
"iexRealtimeSize": 100,
"iexLastUpdated": 1573765191429,
"delayedPrice": null,
"delayedPriceTime": null,
"extendedPrice": null,
"extendedChange": null,
"extendedChangePercent": null,
"extendedPriceTime": null,
"previousClose": 264.47,
"previousVolume": 25817593,
"change": -1.7,
"changePercent": -0.00643,
"volume": 22222410,
"iexMarketPercent": 0.008687221592977539,
"iexVolume": 193051,
"avgTotalVolume": 25422166,
"iexBidPrice": 0,
"iexBidSize": 0,
"iexAskPrice": 0,
"iexAskSize": 0,
"marketCap": 1167558057900,
"peRatio": 22.02,
"week52High": 264.78,
"week52Low": 142,
"ytdChange": 0.668279,
"lastTradeTime": 1573765201922,
"isUSMarketOpen": false
}
```

**Comment by McQgit** [comment]
@eddadjei If you only see nulls with Nasdaq listed stocks, you can read more about that issue here:
[]https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud

If that doesn't resolve your question, maybe someone from IEX will respond or try emailing them.

**Comment by eddadjei** [comment]
Thanks @McQgit. This only happens between 6pm and 7pm. I don’t think it’s related to the nasdaq UTP as it works post 7pm

**Comment by evancarter-iex** [comment]
@eddadjei are you receiving the open/high/low/close during the day?

**Comment by eddadjei** [comment]
Yes am getting all nasdaq values during the day. Right around 6:30pm CST to 7:15pm, everything becomes null and then it corrects it self after 7:30

**Comment by evancarter-iex** [comment]
@eddadjei Can you send an email to support@iexcloud.io, Ill need account information etc and Github is not the correct place to discuss that. Thanks!

**Comment by eddadjei** [comment]
@evancarter-iex i just send the email with my account information
