### ISSUE TITLE
Where/How do I format extra argumentsI?

### ISSUE THREAD

**Issue by Ganondorc** [iexg/IEX-API#1325]
I've been combing the docs (https://iexcloud.io/docs/api/) for the answer to my question, but I can't seem to locate the answer.

Here's the base URL for a standard quote (sandbox version):
https://sandbox.iexapis.com/stable/stock/twtr/quote?token=Tpk_c72352ab6cf9403db89a7a721b5434cc

Essentially, I'm trying to construct the URL required to add extra arguments:

    ?filter=high,low,open,close
    ?format=csv
Despite placing these arguments before or after ?token, I can't seem to get it to work. Here's what I've tried:

https://sandbox.iexapis.com/stable/stock/twtr/quote?token=Tpk_c72352ab6cf9403db89a7a721b5434cc?filter=close
https://sandbox.iexapis.com/stable/stock/twtr/quote?filter=close?token=Tpk_c72352ab6cf9403db89a7a721b5434cc
https://sandbox.iexapis.com/stable/stock/twtr/quote?token=Tpk_c72352ab6cf9403db89a7a721b5434cc?format=csv
https://sandbox.iexapis.com/stable/stock/twtr/quote?format=csv?token=Tpk_c72352ab6cf9403db89a7a721b5434cc

As you can see, if you navigate to those links, they give various API token related errors, but the same token works without the arguments.

**Comment by McQgit** [comment]
@Ganondorc  A single question mark delineates the url from the query parameters.  An ampersand separates multiple queries.  You have used a question mark for each query parameter.  This is not unique to IEX - it is standard url formatting - which is why they haven't included it in the docs (I'm guessing).

See:
[]https://en.wikipedia.org/wiki/Query_string

**Comment by joshuablackburn-iex** [comment]
We have a help article to assist with making calls to the API. I’ll make sure a link to this article is added to the docs. 

https://intercom.help/iexcloud/en/articles/2851957-how-to-make-an-api-call
