### ISSUE TITLE
[Issue] Sentiment endpoint Documentation fixes

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1326]
In API docs for sentiment endpoint at

https://iexcloud.io/docs/api/#social-sentiment130

I suspect the following URL is supposed to have aapl instead of market in it.

`https://sandbox.iexapis.com/stable/stock/market/sentiment/minute?token=`

Also there is a question mark in the example HTTP request for date

`GET /stock/{symbol}/sentiment/{type}/{?date}`

to I assume indicate it is an optional path parameter and that is how it is described in the path parameters section yet in my tests both path parameters type and date are required in order to get results.

**Comment by joshuablackburn-iex** [comment]
Resolved
