### ISSUE TITLE
[Issue] Documentation of Sentiment endpoint path parameters

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1327]
API docs for sentiment endpoint

https://iexcloud.io/docs/api/#social-sentiment

states path parameter type is optional in path parameters section yet leaving it out or even specifying the supported value of minute or daily such as any of the following

https://cloud.iexapis.com/stable/stock/goog/sentiment/minute/?token=
https://cloud.iexapis.com/stable/stock/goog/sentiment/daily/?token=
https://cloud.iexapis.com/stable/stock/goog/sentiment/?token=

all return

{}

on 11/18/2019 7:20 PM PT

It is only when one includes the optional path parameter of type, either daily or minute AND adds the optional path parameter of date does it return results such as

https://cloud.iexapis.com/stable/stock/goog/sentiment/daily/20191118?token=
https://cloud.iexapis.com/stable/stock/goog/sentiment/minute/20191118?token=

Example of daily when specifying date ...

![image](https://user-images.githubusercontent.com/8920632/69113569-3745f780-0a38-11ea-9863-f52de104c8a4.png)

Same issue was mentioned https://github.com/iexg/IEX-API/issues/680#issue-410075485 So it appears both path parameters type and date described as optional in docs are required or it is not working as described.

**Comment by joshuablackburn-iex** [comment]
Resolved
