### ISSUE TITLE
Preferred Share no covered

### ISSUE THREAD

**Issue by cgailey** [iexg/IEX-API#1328]
The preferred NYSE:TRTN-PC is not covered for quotes.

Using https://cloud.iexapis.com/v1/stock/TRTN-PC/chart/1m?token=myToken

or

https://cloud.iexapis.com/v1/stock/market/batch?symbols=TRTN-PC&types=quote&token=myToken

Thanks.

**Comment by evancarter-iex** [comment]
@cgailey

Per our ref data we have the following preferred shares stocks for TRTN.

```
TRTN-A,NYS,Triton International Ltd. 8.5% Cum Conv Red Perp Pfd Registered Shs Series A,2019-11-19,ps,IEX_475A39594D352D52,US,USD,true
TRTN-B,NYS,Triton International Ltd 8% Conv Cum Red Perp Pfd Registered Shs Series B,2019-11-19,ps,IEX_504E315656532D52,US,USD,true
TRTN-C,NYS,Triton International Ltd 7.375 % Cum Conv Red Perp Pfd Registered Shs Series C,2019-11-19,ps,IEX_4A38354D304A2D52,US,USD,true
```

Hope that helps.
