### ISSUE TITLE
[Data] Historical Data issue

### ISSUE THREAD

**Issue by dugwood** [iexg/IEX-API#1329]
I'm using `Historical Prices` to get OHLC data for past 120 days.

The documentation (https://iexcloud.io/docs/api/#historical-prices) states that data is available at `4 AM ET`. So I'm running my script 30 minutes after that.

Example URL: https://cloud.iexapis.com/stable/stock/twtr/chart/date/20191119?chartByDay=true&token=TOKEN (was not available at 10:30 am, Paris Time, which should be 4:30 am ET)

From time to time, data is empty, but requests are `200 OK`. I can understand this behaviour for stocks that don't have data (newly added stocks, no history), but for known stocks this should answer with an error.

So far I can't define if the data will be missing for ever, or is just a temporary issue. As such, to avoid requesting the same empty dates again and again, I'm storing zero values. Else I would be querying the same unavailable data every day.

Can you provide another status code for data not yet ready? Or send 404 for data that will never be available. Or should I detect this by knowing that you don't have data prior to a specific date (I can't find the information in the docs...)?

Another question: is there any option to get End of Day earlier than 4am ET? As I read the sentence again:
`Prior trading day adjusted data available after 4am ET Tue-Sat`
means that data should be available before this date, with unadjusted data (unadjusted data is already discussed in many other bug reports, as no adjustment is done except for splits).

Thanks :smiley:

**Comment by evancarter-iex** [comment]
@dugwood Hi there,

Hi there,
I show that data loading around 00:45 UTC time this morning. 

That being said, once data is loaded in, its loaded all at once so its a binary for the entire days history for all stocks. Either its there or its not, if that makes sense.

**Comment by dugwood** [comment]
Thanks @evancarter-iex so the data should have been there at 9:30 AM UTC this morning.

The thing is that some stocks have never any data. For example: PING (NYSE) which returns `"status":200,"contents":"[]"` for every date.

I should disable those for good when I get a lot of errors. But if I stop on the first one that returns `[]`, I will never download anything in the end...

So maybe I should stop if data isn't available for 10 selected stocks (say `AAPL` for instance). That could be a trigger for running the whole script. Just one to ten hits, every hour, until I get a go.

I'll try to change my script, but adding an endpoint to know if historical prices are available for the past day would be great.

I can see that this endpoint is to be changed in the future, is it available in Beta perhaps?

**Comment by evancarter-iex** [comment]
@dugwood Well PING started trading on September 19th, so anything before that wont have data but I confirmed after that date we have historical data.

And yes we are looking into adding that endpoint for historical upload last upload time.

**Comment by evancarter-iex** [comment]
Closing this as the suggestion for the endpoint with the update time has been discussed elsewhere.
