### ISSUE TITLE
End Of Day Data (Enhancement Request)

### ISSUE THREAD

**Issue by kg4iae** [iexg/IEX-API#133]
I would like end of day snapshots of all symbols on American Markets.  I use the data to do market research.  I realize you can take a list of symbols and use the quote API to get the data.

It would be nice to be able to retrieve all 5000 or so symbols at one time.  There are a few free sites that already do this, but you have to login, and download manually.  None that I have found allow you do script it.
Just a simple CSV output.  
Date, Symbol, Open, High, Low, Close, Volume
12-5-2017, AA, 10.45, 11.10, 9.97, 10.50, 453983

**Comment by joshuablackburn-iex** [comment]
Open High Low and Close are now are available from /quote.  Documentation update to follow.
