### ISSUE TITLE
[Issue] Splits (Basic) endpoint

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1330]
On grow plan, trying out splits basic endpoint at:

https://iexcloud.io/docs/api/#splits-basic

The examples below show no results for supported symbols that have had splits in the specified range path parameter of 5 years. Appreciate if someone could take a look for me, thanks.

=================

Symbol: NURO
API URL: https://cloud.iexapis.com/v1/stock/nuro/splits/5y?token=

Splits:

05/12/2017 | 1 for 8
11/19/2019 | 1 for 10

Sources:

https://www.stocksplithistory.com/?symbol=nuro
https://seekingalpha.com/symbol/NURO/splits

Result: Empty array.

=================

Symbol: SLS
API URL: https://cloud.iexapis.com/v1/stock/sls/splits/5y?token=

Splits:

01/02/2018 | 1 for 30
11/08/2019 | 1 for 50

Sources:

https://www.stocksplithistory.com/?symbol=sls
https://seekingalpha.com/symbol/SLS/splits

Result: Empty array.

=================

Symbol: CEI
API URL: https://cloud.iexapis.com/v1/stock/cei/splits/5y?token=

Splits:

03/05/2018 | 1 for 25
12/24/2018 | 1 for 25
07/08/2019 | 1 for 25
10/29/2019 | 1 for 50

Sources:

https://www.stocksplithistory.com/?symbol=cei
https://seekingalpha.com/symbol/CEI/splits

Result: Empty array.

**Comment by dwhitney** [comment]
Would love to see this fixed as well

**Comment by stammy** [comment]
+1 I can't seem to get this endpoint to return any data?

**Comment by MorningSleeper** [comment]
I emailed them 4 months ago and was told they would investigate and update me, no update yet. You may want to email them as well.

**Comment by MorningSleeper** [comment]
Seems all the examples are now returning info, thanks to whomever fixed this.

**Comment by MorningSleeper** [comment]
@evancarter-iex , just noticed, how come the declareDate response attribute is null in all of them?
