### ISSUE TITLE
[Data] Historical News Source is Always "CityFalcon"

### ISSUE THREAD

**Issue by exiao** [iexg/IEX-API#1332]
**Clearly describe the data problem**
The source for all historical news does not say the real source. It always defaults to CityFalcon, which is different than the normal news API.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/time-series/news/TSLA?limit=5&token=&on=2019-02-01

**What time did the problem occur (including timezone)?**
2019-11-24

**What is the expected behavior?**
Source will be the actual publisher of the article

**Comment by joshuablackburn-iex** [comment]
This is fixed.
