### ISSUE TITLE
IEX Cloud Excel Webservice financial endpoint import issue

### ISSUE THREAD

**Issue by mjsvends** [iexg/IEX-API#1334]
looking for help to correct this excel webservice formula to import /financials/ data.

current cell: 
=WEBSERVICE(CONCATENATE($B$4,$A6,"/financials/",D$5,"?token=",$B$1))
B4: https://cloud.iexapis.com/stable/stock/
A6: stock symbol
D5: any financial endpoint, example "totalRevenue"
B1: token

This concatenate setup is working fine for /quote/ data, just not /financials/
I've run this with out the concatenate, same issue. Cell returns #VALUE! 

Any help is appreciated

**Comment by McQgit** [comment]
@mjsvends For /financials, you have to indicate which financial period you want.  For example:

[]https://cloud.iexapis.com/v1/stock/msft/financials/1/totalRevenue?token=(redacted)

I don't know if this is intended or a bug but it works.  I guessed at the url from the sample in the Excel How To docs.  They explicitly state the period in the url for the earnings estimate example.
[]https://iexcloud.io/docs/api/#excel-how-to

**Comment by PEPPPPP** [comment]
Was this solved? Having the same issue with endpoints /financials, /balance-sheet, /cash-flow, /income and /dividends, and tried adding the period (/1) as mentioned above with no success. 

Endpoints /quote and /stats are working fine, but getting #VALUE! for all others. 

Thanks
