### ISSUE TITLE
News API don't return news for topics other than oil

### ISSUE THREAD

**Issue by timefrancesco** [iexg/IEX-API#1335]
When calling either a news or historical news with a topic and not a symbol, only the oil topic works, the others return "Unknown symbol".

API endpoint:

https://sandbox.iexapis.com/stable/stock/us-market/news?token=

or 

https://sandbox.iexapis.com/stable/stock/funding/news?token=

Tried in both sandbox mode and production mode, same results.

**Comment by McQgit** [comment]
@timefrancesco  I get the same problem as you so an IEX person will need to address that. 

I just wanted to add you can use the new /time-series endpoint for news and topics.  Example:

[https://cloud.iexapis.com/v1/time-series/news/fx?limit=2&token=X]

I have tried several topics and they all return some articles.  Alas, many don't have anything to do with the topic requested but I guess that's a different problem.  The 'fx' example above just returned an article about OPEC's latest oil forecast and another about a cannabis company winning some Canadian award.

**Comment by timefrancesco** [comment]
@McQgit Thanks, I checked that, but the weight for it is 5000 per news item, while normal news is just 1 per symbol. 
Also it doesn't work well either, it seems the news returned are a bit all over the place and depending on interval it might be empty.

Hopefully they will fix the normal news endpoint.

**Comment by jamesmogg** [comment]
This is ridiculously annoying, it still doesn't work, same error, can someone fix it please.

**Comment by Hastewave** [comment]
Hello! I've got the same problem with news response for us-market filter. Please fix this.
My request - GET 'https://cloud.iexapis.com/v1/stock/us-market/news/last/20?token=XXX"

**Comment by Hastewave** [comment]
Hello everyone! I apologize for importunity, but the functionality does not work. Should I wait for a fix or not? Thank you in advance for your response
