### ISSUE TITLE
[Data] Some fields have minor rounding issues

### ISSUE THREAD

**Issue by AndreHaueisen** [iexg/IEX-API#1336]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
Cash flow netBorrowings is sending a double instead of an integer
It looks like the value is not getting rounded: -292999999.999999
It does not happen for all symbols. In my case, it occurred for aapl.

**Data URL (The URL you used to access the data without your token):**
The problem even occurs in the example URL in the documentation.
https://sandbox.iexapis.com/stable/stock/aapl/cash-flow?token=Tsk_bf34a328d0dc4d268812ba08967ee7ac
Take a look at netBorrowings value

**What time did the problem occur (including timezone)?**
10:20 AM -3GMT

**What is the expected behavior?**
I was expecting a rounded number as all the other values: -293000000

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
Windows 10. Android Studio. Dart language

**Additional context**

**Comment by evancarter-iex** [comment]
This is resolved.
