### ISSUE TITLE
[Data] REITs are being reported as Common Stocks

### ISSUE THREAD

**Issue by AndreHaueisen** [iexg/IEX-API#1337]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
In reference data / symbols, REITs symbols have the type 'cs' instead of 're'

**Data URL (The URL you used to access the data without your token):**
https://sandbox.iexapis.com/stable/ref-data/symbols?token=Tsk_bf34a328d0dc4d268812ba08967ee7ac

**What time did the problem occur (including timezone)?**
10:50 AM -3GMT - 11 / 30 / 2019

**What is the expected behavior?**
type should yield 're' instead of 'cs' according to the documentation

**What are the steps to reproduce**
Make the get request and try to find one single REIT by its type

**Your environment (e.g. browser, OS, API version, language):**
Windows. Android Studio, Dart

**Additional context**

**Comment by rmantovani** [comment]
Hi There, 

I got same problem. I need get reit stocks. there'a no reit issue type in symbols endpoint.
Symbol: AIV.


IssueType says:	
string	refers to the common issue type of the stock. 

ad – American Depository Receipt (ADR’s) 
re – Real Estate Investment Trust (REIT’s) 
ce – Closed end fund (Stock and Bond Fund) 
si – Secondary Issue 
lp – Limited Partnerships 
cs – Common Stock 
et – Exchange Traded Fund (ETF) 
wt – Warrant 
rt – Right 
(blank) – Not Available, i.e., Note, or (non-filing) Closed Ended Funds
ut - Unit
temp - Temporary
