### ISSUE TITLE
[Issue] (403) Forbidden only from Azure Cloud

### ISSUE THREAD

**Issue by leftmostlane** [iexg/IEX-API#1338]
Need your help with a baffling error.  

Date/time of the issue: All day 11/29/2019 and 11/30/2019
What you expected to happen: Receive the usual json result
What actually happened: Received (403) forbidden error
What you did: Ran the following from Azure Web App for Linux

Works fine locally in desktop browser, works fine when run from the cloud (Azure Web App for Linux):
String url = "https://cloud.iexapis.com/stable/ref-data/symbols?token=pk_#############";
String jsonContent = new WebClient().DownloadString(url);

Works fine locally in desktop browser, fails when run from the cloud with (403) Forbidden error
String url = "https://cloud.iexapis.com/stable/stock/market/batch?symbols=SPY&types=quote&token=pk_#############";
String jsonContent = new WebClient().DownloadString(url);

It is baffling how the first URL works in the cloud and the second URL receives a 403 Forbidden error from IEX.  Yet, both URLs work in my browser.  Any help is appreciated.

**Comment by leftmostlane** [comment]
Created a new publishable key.  The new key works from local and the cloud.  Delete the previous publishable key.

**Comment by leftmostlane** [comment]
Created a new publishable key. The new key works from local and the cloud. Delete the previous publishable key.

**Comment by chriszubrod** [comment]
@leftmostlane ... Even though creating a new publishable key worked, were you able to nail down a specific answer why this was happening? 

Like you, I am trying to use an Azure Web Job to pull data, but I am now getting an error as well.

Thanks,

Chris

**Comment by leftmostlane** [comment]
> @leftmostlane ... Even though creating a new publishable key worked, were you able to nail down a specific answer why this was happening?
> 
> Like you, I am trying to use an Azure Web Job to pull data, but I am now getting an error as well.
> 
> Thanks,
> 
> Chris

Nope.
