### ISSUE TITLE
[Data] International EOD data now missing

### ISSUE THREAD

**Issue by f2calv** [iexg/IEX-API#1339]
**Clearly describe the data problem**
I synchronise international EOD data every morning, the last successful sync was on 27th Nov for EOD data from 2019-11-26.

Now any query to return EOD data *for any date in the past* returns *no price data* at all!

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/BARC-LN/chart/date/20191127?chartByDay=true&chartCloseOnly=true
https://cloud.iexapis.com/stable/stock/BARC-LN/chart/date/20191128?chartByDay=true&chartCloseOnly=true
https://cloud.iexapis.com/stable/stock/BARC-LN/chart/date/20191129?chartByDay=true&chartCloseOnly=true

**What is the expected behavior?**
API should return EOD price data.

**Comment by evancarter-iex** [comment]
Hi there,

This is resolved. Next time please email support@iexcloud.io for faster response time.
