### ISSUE TITLE
Options chain support

### ISSUE THREAD

**Issue by eric-appeagle** [iexg/IEX-API#134]
## Summary
It'd be really awesome if you could also do option expirations and pricing, I didn't see anything on the roadmap, is this something you already do or can do in the future?

**Comment by lars670** [comment]
Derivatives are not traded on IEX

**Comment by evancarter-iex** [comment]
End of day options are now available on https://iexcloud.io  https://iexcloud.io/docs/api/#options for more information

**Comment by renou** [comment]
Any plan for real-time option data?
