### ISSUE TITLE
REST API Call for Time-Series Reported Financials does not return sales revenue for some years

### ISSUE THREAD

**Issue by rrprasan** [iexg/IEX-API#1340]
The following REST API call has 
https://cloud.iexapis.com/v1/time-series/REPORTED_FINANCIALS/FOSL/10-K?from=2010-01-01&to=2019-12-31&token='<Your Token Here>'

This call returns 'SalesRevenueNet'  in the JSON array for the following years:
2010 2030690000
2011 830756000
2012 947700000
2013 100700000
2014 3509691000

But fails to return any sales data for 2015 and later years. 
For some reason, the JSON array does not have 'SalesRevenueNet' or any revenue related naming - such as 'Revenue' or 'Total Sales' - for the years 2015 and later.  This is strange. There might be an issue with the SEC filing rather than the IEX REST end point.  I am seeing that the SEC XBRL data does not contain sales revenue.  I have filed a "complaint" with the SEC.  
The SEC XBRL data has Sales Revenue by product line but does not have a total revenue XBRL tag.  

**API URL (if applicable)**
https://cloud.iexapis.com/v1/time-series/REPORTED_FINANCIALS/FOSL/10-K?from=2010-01-01&to=2019-12-31&token

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by evancarter-iex** [comment]
Hi there,

I see it in 2015,2016, 2017 but not 2018. Unfortunately, I checked the SEC data and its not there either as far as I can tell, which means its something beyond our control so I am closing this.
