### ISSUE TITLE
[Data] company information endpoint returns 158.5 employees?

### ISSUE THREAD

**Issue by f2calv** [iexg/IEX-API#1341]
**Clearly describe the data problem**
When querying the below URL for company information, the number of employees comes back as 158.5 - thus breaking parsing as I'm expecting an integer.

```json
... \"primarySicCode\":6022,\"employees\":158.5,\"tags\":[\"Finance\", ...
```

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/AUBN/company

**What time did the problem occur (including timezone)?**
First noticed on 2019-12-01.

**What is the expected behaviour?**
Maybe this property could be standardised/forced to integer at your end so us end-consumers don't have to handle this data quality issue ourselves?

**What are the steps to reproduce**
Call the above URL w/token.

**Comment by evancarter-iex** [comment]
This is resolved.
