### ISSUE TITLE
[Data] Market cap for BRBR is null

### ISSUE THREAD

**Issue by achtsisn** [iexg/IEX-API#1342]
Clearly describe the data problem
Market cap for BRBR is null. This is a recent IPO.

Data URL (The URL you used to access the data without your token):

https://cloud.iexapis.com/stable/stock/BRBR/quote?token=

What time did the problem occur (including timezone)?
12/03 6am PST

What is the expected behavior?
Market cap should be a correct number.

**Comment by evancarter-iex** [comment]
fixed.
