### ISSUE TITLE
[Request] Only fetch news starting from a certain ID

### ISSUE THREAD

**Issue by pks5** [iexg/IEX-API#1344]
**Is your feature request related to a problem? Please describe.**

I would like to fetch news for a certain symbol, and cache them in my database. If there are new news items on IEX for that symbol, i want only to fetch the new ones. Currently there is no way to fetch only the news items that have been added since my last sync.

**Describe the solution you'd like**

It would be great to add an unique ID to each news item response, and then use this ID to only fetch those news items that have been added after the item with the unique ID.

GET /stock/{symbol}/news?since=123456 
Only return news items that have been added after news item #123456

**Comment by timpaine-iex** [comment]
You can do this on a daily basis via [time series](https://iexcloud.io/docs/api/#time-series).
