### ISSUE TITLE
High and Low of stocks is null in batch requests for US stocks. [Data]

### ISSUE THREAD

**Issue by KingIsulgard** [iexg/IEX-API#1346]
When getting data via a batch request the high and low of the day are always null for US stocks.
Normally it should only be null till 9:45 AM but for some reason in batch requests this is always null.

Works fine in single quote requests though. 

Edit: open and close are null too.

**Comment by evancarter-iex** [comment]
@KingIsulgard What stocks and what type of account do you have?

**Comment by KingIsulgard** [comment]
> @KingIsulgard What stocks and what type

I have a Launch plan. And this issue is for US stocks. For example AAPL. 
The high and low do work for single quote endpoints but not batch requests so this seems like a data issue. Not a plan limitation.

**Comment by KingIsulgard** [comment]
PS : open and close are null too. Very odd.

**Comment by evancarter-iex** [comment]
@KingIsulgard What request are you making in the non batch request for something like AAPL?

**Comment by KingIsulgard** [comment]
Sorry my bad, I was comparing TWTR and AAPL,TSLA.
For some reason TWTR has open, close, high & low data but AAPL & TSLA don't.
What's the reason for this? It used to work.

**Comment by evancarter-iex** [comment]
Hi there, 

This document should explain it. https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud Hope that helps.
