### ISSUE TITLE
Have a bunch of symbols been removed this week?

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1347]
Noticed that on Dec 1 and comparing today (Dec 6) there are about 600 less symbols in the symbols file.

For example:
AABA
AAC
ACET
ACIM
ACP^
ADOM
ADYX
AED
AEH
AESEW
AETI
AFGE

Has this been cleaned up?

**Comment by SeamusBoyle** [comment]
For me, between 2019-12-04 and 2019-12-09:

- using `/ref-data/region/{region}/symbols` and `/ref-data/exchange/{exchange}/symbols` (for all regions/exchanges), I have 5719 removed symbols

- using `/ref-data/symbols`, I have 8 removed symbols

I initially assumed these were international symbols that were removed, but in fact, all of them were US region, with 4612 Nasdaq symbols removed

**Comment by evancarter-iex** [comment]
Periodically, old symbols are removed if they are no longer in use/functional etc. So most likely thats what occurred in this case.

For example AETI was delisted. 
ACIM changed to SPGM 
AABA was halted for dissolution etc.


Hope that helps.

**Comment by jesseorosz** [comment]
it does help - thanks!
