### ISSUE TITLE
Data request: Add delayedVolume and delayedChange to Quote endpoint

### ISSUE THREAD

**Issue by tcrsavage** [iexg/IEX-API#135]
First of all, thanks so much for providing an excellent free service. Efforts like this deserve more than just appreciation.

As a developer I'd like to use this API to provide an IR site quote module. In this specific use case I'm expected to use global market data as opposed to the IEX subset. 

Currently the quote endpoint appears to provide me with everything required for this aside from `delayedVolume` and `delayedChange`. The existing `Volume` and `Change` look to be calculated realtime with `latestSource` which skew results when compared to other datasources providing global data. 

I can manually calculate change for `delayedPrice` via an additional API call but can't see a way to pull out an accurate volume associated with `delayedPrice`.

**Comment by timpaine-iex** [comment]
closing as stale
