### ISSUE TITLE
[Data] Incorrect Dividend for IXUS

### ISSUE THREAD

**Issue by cgailey** [iexg/IEX-API#1355]
Dec 16 declared dividend for IXUS is incorrect.

Using endpoint: 
https://cloud.iexapis.com/v1/stock/ixus/upcoming-dividends?token=myToken

returns:  
[{"exDate":"2019-12-16","paymentDate":"2019-12-20","recordDate":"2019-12-17","declaredDate":null,"amount":"0.085383","flag":"Cash","currency":"USD","description":"BTC iShares Core MSCI Total International Stock ETF","frequency":null,"symbol":"IXUS"}]

where the amount is incorrect according to NASDAQ page:
https://www.nasdaq.com/market-activity/funds-and-etfs/ixus/dividend-history

and iShares page:
https://www.ishares.com/us/products/244048/#distributionsDialog

Thanks!
.cg.

**Comment by McQgit** [comment]
@cgailey  Adding more info to this confusing item from cgailey ... the advanced_dividends endpoint has the 0.085583 amount seen in /upcoming-dividends as a marker=Special dividend with frequency=null.  This is shown second in the json snip below.

On the same payment date it also has marker=final with frequency=semi-annual which seems like it should be the 0.977473 noted by iShares.  Alas, this dividend record has an amount=0 which is wrong.  This is the first json segment below.

Interestingly, the 'notes' field for the special dividend (below) has the 0.977473 amount - just not in any form readily usable.  I don't see any special amount on the iShares site so not sure where 0.085583 even comes from - other than it also shows in this notes field.

I'm not sure this helps the matter.  Just something else for IEX to consider when researching.

From:
[]https://cloud.iexapis.com/v1/time-series/advanced_dividends/ixus?dateField=paymentDate&on=2019-12-20&token=X

[
  {
    "symbol": "IXUS",
    "exDate": "2019-12-16",
    "recordDate": "2019-12-17",
    "paymentDate": "2019-12-20",
    "announceDate": "2018-12-26",
    "currency": "",
    "frequency": "semi-annual",
    "amount": 0,
    "description": "BTC iShares Core MSCI Total International Stock ETF",
    "flag": null,
    "securityType": "Exchange Traded Fund",
    "notes": null,
    "figi": "BBG003H6TM38",
    "lastUpdated": "2019-01-08",
    "countryCode": "US",
    "parValue": 0,
    "parValueCurrency": "USD",
    "netAmount": 0,
    "grossAmount": 0,
    "marker": "Final",
    "taxRate": 0,
    "fromFactor": 0,
    "toFactor": 0,
    "adrFee": 0,
    "coupon": 0,
    "declaredCurrencyCD": "",
    "declaredGrossAmount": 0,
    "isNetInvestmentIncome": 0,
    "isDAP": 0,
    "isApproximate": 0,
    "fxDate": null,
    "secondPaymentDate": null,
    "secondExDate": null,
    "fiscalYearEndDate": "2019-12-31",
    "periodEndDate": "2019-12-31",
    "optionalElectionDate": null,
    "toDate": null,
    "registrationDate": null,
    "installmentPayDate": null,
    "declaredDate": "2018-12-26",
    "refid": "1483177",
    "created": "2018-12-27",
    "id": "ADVANCED_DIVIDENDS",
    "source": "IEX Cloud",
    "key": "IXUS",
    "subkey": "1483177",
    "date": 1576454400000,
    "updated": 1573582375000
  },
  {
    "symbol": "IXUS",
    "exDate": "2019-12-16",
    "recordDate": "2019-12-17",
    "paymentDate": "2019-12-20",
    "announceDate": null,
    "currency": "USD",
    "frequency": null,
    "amount": 0.085383,
    "description": "BTC iShares Core MSCI Total International Stock ETF",
    "flag": "Cash",
    "securityType": "Exchange Traded Fund",
    "notes": "(As on 13/12/2019) USNASDAQA <BR>Daily List Date 12/13/2019 18:20:31<BR>Market Category G<BR>Issue Symbol IXUS<BR>Company Name iShares Core MSCI Total International Stock ETF<BR>Declaration Date  <BR>Amount 0.977473<BR>Payment Freq S<BR>X-Date 12/16/2019<BR>Record Date 12/17/2019<BR>Payment Date 12/20/2019<BR>NOTES for Each Dividend Special Per Share:  0.085383<BR>Dividend Type Id XC<BR>Stock Amount <BR>Cash Amount 0.977473<BR>QualDiv U<BR>Net Amount <BR>",
    "figi": "BBG003H6TM38",
    "lastUpdated": "2019-12-16",
    "countryCode": "US",
    "parValue": 0,
    "parValueCurrency": "USD",
    "netAmount": 0,
    "grossAmount": 0.085383,
    "marker": "Special",
    "taxRate": 0,
    "fromFactor": 0,
    "toFactor": 0,
    "adrFee": 0,
    "coupon": 0,
    "declaredCurrencyCD": "",
    "declaredGrossAmount": 0,
    "isCapitalGains": 0,
    "isNetInvestmentIncome": 0,
    "isDAP": 0,
    "isApproximate": 0,
    "fxDate": null,
    "secondPaymentDate": null,
    "secondExDate": null,
    "fiscalYearEndDate": "2019-12-31",
    "periodEndDate": null,
    "optionalElectionDate": null,
    "toDate": null,
    "registrationDate": null,
    "installmentPayDate": null,
    "declaredDate": null,
    "refid": "1750094",
    "created": "2019-12-16",
    "id": "ADVANCED_DIVIDENDS",
    "source": "IEX Cloud",
    "key": "IXUS",
    "subkey": "1750094",
    "date": 1576454400000,
    "updated": 1576491882000
  }
]

**Comment by evancarter-iex** [comment]
This is fixed.
