### ISSUE TITLE
Symbol: DOW Stock.get_income_statement(period = 'quarterly', last = 4) returns 3 quarters not 4

### ISSUE THREAD

**Issue by rrprasan** [iexg/IEX-API#1356]
This happens for DOW ticker. But for others it seems to be working. Not sure why.  
The Stock.get_income_statement(period = 'quarterly', last = 4) or Stock.get_income_statement(period = 'quarter', last = 4)  returns only 3 quarters worth of data for DOW. The API says 4 quarters worth of data is available.
May be there was a change the business entity (e.g. merger or divestiture) that's not captured by the API.  

**What is the expected behavior?**
Seems to be a problem with the data for the DOW ticker symbol

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/stock/dow/income?period=quarter&last=4&token=

**What are the steps to reproduce the bug?**
Please try the above URL with your token

**Comment by McQgit** [comment]
@rrprasan Because DOW separated from Dow-DuPont (DD) earlier this year.

[]https://www.dupont.com/news/dowdupont-completes-spin-off-of-dowinc.html

and here

[]https://investors.dow.com/en/investor-resources/stockholder-information/default.aspx
