### ISSUE TITLE
[Data] DIS dividend is missing through the dividend (basic) end point

### ISSUE THREAD

**Issue by shawnlinxl** [iexg/IEX-API#1359]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**

DIS (Disney) paid dividends in all last 5 years. However, when explicitly requesting for 5y dividends through the dividends (basic) API, only 1 year of dividends is returned.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/dis/dividends/5y?token=mytoken

**What time did the problem occur (including timezone)?**

Thu Dec 19, 2019 2:00AM (GMT -5)

**What is the expected behavior?**

To return dividends as suggested at Nasdaq's [website](https://www.nasdaq.com/market-activity/stocks/dis/dividend-history)

**What are the steps to reproduce**

Call
`https://cloud.iexapis.com/stable/stock/dis/dividends/5y?token=mytoken`
and you should see
`[{"exDate":"2019-12-13","paymentDate":"2020-01-16","recordDate":"2019-12-16","declaredDate":"2019-12-04","amount":"0.88","flag":"Cash","currency":"USD","description":"Ordinary Shares","frequency":"semi-annual","date":"2019-12-19"},{"exDate":"2019-07-05","paymentDate":"2019-07-25","recordDate":"2019-07-08","declaredDate":"2019-06-26","amount":"0.88","flag":"Cash","currency":"USD","description":"Ordinary Shares","frequency":"semi-annual","date":"2019-12-19"}]`

**Your environment (e.g. browser, OS, API version, language):**

OSX, IEX Cloud Table

**Additional context**

* Advanced dividend seems to have the same issue.
* Disney merged with 21century Fox this year. It could be that some underlying id that's not exposed to the user has been updated after the merger (e.g. ISIN/CUSIP, I've verified these two and they haven't changed) which caused dividends before the merger to become unavailable.

**Comment by shawnlinxl** [comment]
Is IEX Cloud dead? I am a grow customer, and have not received any response on Github for 26 days, and via support@iexcloud.io for 7 days now.

**Comment by xxx44yyy** [comment]
> Is IEX Cloud dead? I am a grow customer, and have not received any response on Github for 26 days, and via [support@iexcloud.io](mailto:support@iexcloud.io) for 7 days now.

Holidays...

**Comment by joshuablackburn-iex** [comment]
This is due to the merger where a completely new legal entity was formed. New ISIN, new CUSIP, new LEI, etc. We currently have data for the new entity.
