### ISSUE TITLE
actualEPS is wrong for this this stock

### ISSUE THREAD

**Issue by shonick** [iexg/IEX-API#136]
https://api.iextrading.com/1.0/stock/aiz/earnings

![capture](https://user-images.githubusercontent.com/34329317/33700336-9ed9f424-dae6-11e7-86b0-38ae3dfb2378.PNG)

comparing the actualEPS vs the EPS from the following site
http://www.nasdaq.com/symbol/aiz/revenue-eps
https://finance.google.com/finance?q=NYSE%3AAIZ&fstype=ii&ei=MscoWpCjONG_mAGbqoTADg

The actualEPS is too much a difference from those 2 sites.

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud. If you havent already you can sign up for the beta here: https://iexcloud.io
