### ISSUE TITLE
Dividend returned amount for SPYD is null

### ISSUE THREAD

**Issue by eyalgett** [iexg/IEX-API#1362]
Dividend returned amount for SPYD is null:

https://cloud.iexapis.com/stable/stock/spyd/dividends/1m

**What time did the problem occur (including timezone)?**
now (12/22/2019 16:00:00 UTC)

**Additional context**

[
    {
        "exDate": "2019-12-20",
        "paymentDate": "2019-12-26",
        "recordDate": "2019-12-23",
        "declaredDate": "2019-01-10",
        "amount": "",
        "flag": null,
        "currency": "",
        "description": "SPDR Portfolio S&P 500 High Dividend ETF",
        "frequency": null,
        "date": "2019-12-22"
    }
]

correct data should be:  0.497170
(according to https://www.ssga.com/us/en/individual/etfs/resources/documents/dividend-distributions)

**Comment by evancarter-iex** [comment]
Resolved.
