### ISSUE TITLE
[Data] Totals from minute daily data are ABSOLUTELY wrong

### ISSUE THREAD

**Issue by pps83** [iexg/IEX-API#1363]
Daily data from [nasdaq for MSFT](https://www.nasdaq.com/market-activity/stocks/msft/historical) for 20191220:

DATE           | CLOSE/LAST | VOLUME     | OPEN    | HIGH     | LOW
12/20/2019 | $157.41        |  53,474,150 | $157.35 | $158.49 | $156.29

daily data as returned by IEX api, isn't exactly the same, but very close:
{"date":"2019-12-20","open":157.35,"close":157.41,"high":158.49,"low":156.29,"volume":53599613}

However, if I use minute data https://cloud.iexapis.com/stable/stock/msft/chart/date/20191220?token=XXX

and calculate totals myself, I get absolutely bogus data:
MSFT ohlc:{157.35, 158.49, 156.29, 157.38} volume:25553634 as you can see the total volume is **more than 50% off** from real market volume. 

I also checked for SPY, and I got 52182014 volume, while correct volume is 148M, eg, it's 65% off from correct market volume.

I recall, that the market data used to be correct and was very close to what hasdaq site reports, how come it's so wrong now!?

**Comment by joshuablackburn-iex** [comment]
If you take a look at our documentation you’ll see that the key ‘volume’ represents volume traded only on the Investors Exchange. The key ‘marketVolume’ is total market.

**Comment by pps83** [comment]
There was nothing in my post that implied that I used wrong data. In fact, I even said that
> I recall, that the market data used to be correct and was very close to what hasdaq site reports
which would be impossible. If I used iex-only data, totals wouldn't be 50% off, they would be 97% off.

**Comment by pps83** [comment]
@joshuablackburn-iex try this script to verify that the market data from minutes is completely wrong now:

```
const https = require('https');
const sym = 'msft';
const token = 'sk_XXX'; // set token

function httpGet(url, func)
{
  https.get(url, (res) => {
    var data = '';
    res.on('data', (d) => { data += d; });
    res.on('end', () => { func(data); });
  }).on('error', (e) => {
    console.error(e);
  });
}

httpGet('https://cloud.iexapis.com/stable/stock/'+sym+'/chart/1m/?token=' + token, (data) => {
  var x = JSON.parse(data);
  var d = x[x.length-1];
  var date = d['date'];
  var volume = d['volume']|0;
  console.log('volume for '+sym+' on '+date+' is:', volume);
  httpGet('https://cloud.iexapis.com/stable/stock/'+sym+'/chart/date/'+date.replace(/\-/g, '')+'/?token='+token, (data) => {
    var x = JSON.parse(data);
	var marketVolume = 0;
    for (var i=0; i<x.length; ++i)
      marketVolume += x[i]['marketVolume'];
    var err = Math.round(10000 - 10000*marketVolume/volume)/100.0;
    console.log('marketVolume for '+sym+' on '+date+' from minute data is:', marketVolume, '(error:', err+'%)');
  });
});
```

This is what I get for different tickers:

> volume for spy on 2019-12-20 is: 149338215
> marketVolume for spy on 2019-12-20 from minute data is: 52182014 (error: 65.05%)
> 
> volume for aapl on 2019-12-20 is: 69032743
> marketVolume for aapl on 2019-12-20 from minute data is: 24609918 (error: 64.35%)
> 
> volume for msft on 2019-12-20 is: 53599613
> marketVolume for msft on 2019-12-20 from minute data is: 25553634 (error: 52.32%)
> 
> volume for ba on 2019-12-20 is: 9493539
> marketVolume for ba on 2019-12-20 from minute data is: 5469419 (error: 42.39%)

**Comment by joshuablackburn-iex** [comment]
The minute bar data does not include the crosses, 4am-9:30am, or 4pm-8pm. It is trading hours only. If you need the full day volume I recommend using /previous or one of the other historical price ranges.

**Comment by pps83** [comment]
Yes, it doesn't include, but I hope you aren't trying to say that pre-market and post-market has 50% of SPY volume. Those errors are way too huge to be caused by pre/post market volume.

Does `/previous` provide minute data? By the way, I always didn't get the point of providing /chat data where you cannot even draw anything for pre/post market on your charts.
