### ISSUE TITLE
[Issue] Indicators listed in API doc table without INPUTS option return NULL

### ISSUE THREAD

**Issue by hudhacks** [iexg/IEX-API#1364]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**
Technical Indicators return a NULL that do not have an entry in "INPUTS" column of table in API doc.

![image](https://user-images.githubusercontent.com/1726425/71414419-16af2580-2614-11ea-96d6-0a8e0162aaca.png)

**What time did the problem occur? (with timezone)**
6:00 AM MST

**What is the expected behavior?**
I expect a return of either a single value for avgprice and medprice, or an Indicator and chart arrays with historical data for obv, crossover, and crossany related to the range. 

**Your environment (e.g. browser, OS, API version, language):**
OS = MacOS Mojave 10.14.5
Browser = Firefox 71.0b12, Chrome 79.0.3945.88, Safari 12.1.1 
API = current
Language = EN

**API URL (if applicable)**

- https://sandbox.iexapis.com/stable/stock/khc/indicator/obv?range=5y&token=Tsk_f0fe070d38154654b46ae58ec55c15d2
- https://sandbox.iexapis.com/stable/stock/khc/indicator/avgprice?range=5y&token=Tsk_f0fe070d38154654b46ae58ec55c15d2
- https://sandbox.iexapis.com/stable/stock/khc/indicator/medprice?range=5y&token=Tsk_f0fe070d38154654b46ae58ec55c15d2
- https://sandbox.iexapis.com/stable/stock/khc/indicator/ad?range=5y&token=Tsk_f0fe070d38154654b46ae58ec55c15d2

**What are the steps to reproduce the bug?**
Enter the above URLs or replace Indicator with one that does not have item in INPUTS column

**Additional context**

**Comment by hudhacks** [comment]
Additionally, I suggest providing a simple statement (i.e. "... not activated for use ...") for the API items in doc that are underdevelopment or on roadmap. This statement is so users are aware the API call is not currently available, so they don't burn through messages and get frustrated. Just my $0.02

**Comment by serhito70** [comment]
Been trying to get just the last value of stochastic with 14,3,3 parameters, but no success. Excel 365
Anybody can help me figure how to input last and 14,3,3 parameters ?

=@WEBSERVICE(CONCATENATE(“https://cloud.iexapis.com/stable/stock/AAPL/indicator/stoch/?token=MYTOKEN

Well appreciated

**Comment by McQgit** [comment]
@serhito70  You'll have to sort out parsing json in Excel on your own.  but, I think the url you are looking for is something like this:

https://cloud.iexapis.com/stable/stock/AAPL/indicator/stoch?range=1d&input1=14&input2=3&input3=3&token=(token)

Note especially that RANGE is required.  I didnt test that the three input terms give correct result.  But, I did get a value returned.  I dont use that indicator myself - I am just familiar with their api in general.

https://iexcloud.io/docs/api/#technical-indicators

**Comment by timpaine-iex** [comment]
Apologies, I finally got around to this and will release the fix momentarily
