### ISSUE TITLE
[Issue] Chart Batch request cannot use specific Date as a range

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1366]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**
Cannot make a batch call in Chart and return data for a specific day

**What time did the problem occur? (with timezone)
Dec 25 2019 6:15AM PST

**What is the expected behavior?**
Query for specific date

**Your environment (e.g. browser, OS, API version, language):**
chrome win 10

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/market/batch?types=chart&token=pk_12345&symbols=AAPL,MSFT&chartCloseOnly=true&chartByDay=true&range=5d

**What are the steps to reproduce the bug?**

This brings back the last five days of data:
https://cloud.iexapis.com/stable/stock/market/batch?types=chart&token=pk_12345&symbols=AAPL,MSFT&chartCloseOnly=true&chartByDay=true&range=5d

I'd like to bring back a specific day:
https://cloud.iexapis.com/stable/stock/market/batch?types=chart&token=pk_12345&symbols=AAPL,MSFT&chartCloseOnly=true&chartByDay=true&range=20191223

https://cloud.iexapis.com/stable/stock/market/batch?types=chart&token=pk_12345&symbols=AAPL,MSFT&chartCloseOnly=true&chartByDay=true&range=date/20191223

None of these work.

**Additional context**
I'm sure it's possible, tried many combinations but nothing has worked. 

API docs states that range can be used, and can query by date when not using a batch call..

**Comment by jesseorosz** [comment]
Still not working.

**Comment by jesseorosz** [comment]
Closing it, Found out you can use the exactDate param

https://cloud.iexapis.com/stable/stock/market/batch?types=chart&token=pk_&symbols=AAPL,MSFT&chartCloseOnly=true&chartByDay=true&exactDate=20200305

**Comment by Justinohallo** [comment]
This really needs to be in the documentation.
