### ISSUE TITLE
ISIN mapping is not one-to-one

### ISSUE THREAD

**Issue by bockelmansebastian** [iexg/IEX-API#1368]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**
When calling the ISIN mapping API with 100 ISIN codes, I get back 258 IEX codes.
Now, clearly, it is hard to know which requested ISIn belonged to which IEX codes
I think that this is caused by symbols existing on multiple exchanges.

**What time did the problem occur? (with timezone)**
09:00:00 EET
Tuesday, 31 December 2019

**What is the expected behavior?**
1. Ideally: returning both the requested ISIN and the related IEX code, but as answered here: https://github.com/iexg/IEX-API/issues/187 it might not be possible.
Another alternative solution, would be to return the IEX codes with the index of the requested ISIN.
2. That way, the response IEX codes could be mapped back to the requested ISIN codes based on the index.
3. Yet another solution would be to have the data weight according to the number of ISINs requested, so that the API could be called separately for each ISIN. That way it would be clear that the returned IEX code(s) belonged to the single requested ISIN.

**Your environment (e.g. browser, OS, API version, language):**
python, API version v1(?)

**API URL (if applicable)**
POST /ref-data/isin  { "token" : "YOUR_TOKEN", "isin" : [ "isin", "isin", "isin" ] }

**What are the steps to reproduce the bug?**
Call the API with ISIN belonging to symbols existing on multiple exchanges.

**Additional context**

**Comment by codeofsumit** [comment]
I would like to second this.
A one-to-one mapping would be great!

**Comment by timpaine-iex** [comment]
No such one to one mapping exists.

**Comment by ConJabi** [comment]
Would be great to specify which exchange you want ISIN info from. That way you can indeed have one-to-one mapping.

**Comment by timpaine-iex** [comment]
@ConJabi this endpoint takes ISINs and returns the IEX Cloud symbol associated with it.
