### ISSUE TITLE
[Issue] CryptoBook SSE API returns nothing

### ISSUE THREAD

**Issue by amittleider** [iexg/IEX-API#1371]
**Clearly describe the problem**
The CryptoBook SSE API does not return any data.

**What time did the problem occur? (with timezone)**
10:11am Paris time, Jan 4, 2020

**What is the expected behavior?**
Expected to receive book value changes

**Your environment (e.g. browser, OS, API version, language):**
Bash

**API URL (if applicable)**
```
curl --header 'Accept: text/event-stream' 'https://cloud-sse.iexapis.com/stable/cryptoBook?symbols=btcusd&token=tok'
```

**What are the steps to reproduce the bug?**
Just put the curl command above in a bash shell, you will never see an event.

**Additional context**

**Comment by evancarter-iex** [comment]
Fixed.
