### ISSUE TITLE
use of tops endpoint

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#1375]
Hi
Sorry - I know I'm probably doing something basic wrong.

This works: https://cloud.iexapis.com/stable/tops/last?symbols=MSFT&token=MYSECRETTOKEN

This does not:  https://cloud.iexapis.com/stable/tops?symbols=MSFT&token=MYSECRETTOKEN

How do I retrieve data using the TOPS endpoint?
Thank you.

**Comment by evancarter-iex** [comment]
Hi there please check out the documentation here: https://iexcloud.io/docs/api/

**Comment by timpaine-iex** [comment]
here is the direct link https://iexcloud.io/docs/api/#tops

**Comment by timpaine-iex** [comment]
@ModelsRUs your second link is correct, but note the data schedule in the docs `9:30am-4pm ET Market hours`
