### ISSUE TITLE
Dividend Payment Date For $RA Is Incorrect

### ISSUE THREAD

**Issue by dvolatility** [iexg/IEX-API#1376]
Hi, I'm seeing that the dividend payment date for the symbol RA is showing that it's on 3/26/2020. It's a CEF that pays monthly and the payable date is 1/23/2020. Did I use the wrong key for this data point? This is what I used:

https://cloud.iexapis.com/stable/data-points/RA/LAST-DIVIDEND-PAYMENT-DATE/?token=

Thanks for your help.

**Comment by McQgit** [comment]
@dvolatility Brookfield announces three dividends at a time at the start of each quarter.  The Mar 26 payable is the 'last' dividend in the series.  See:
https://publicsecurities.brookfield.com/funds-overview/us-closed-end-funds/brookfield-real-assets-income-fund?id=192676

I don't use /data-points myself so can't help much with that.  But, there are other ways to lookup basic dividend data such as:
https://cloud.iexapis.com/v1/stock/market/batch?symbols=ra&types=dividends&range=1y&token=
or 
https://cloud.iexapis.com/v1/stock/market/batch?symbols=ra&types=dividends&range=next&token=
or
https://cloud.iexapis.com/v1/stock/market/batch?symbols=ra&types=dividends&range=next&token=(token)&format=csv

There is also the advanced dividend lookup in /time-series but note the much higher message weight for those retrievals.

**Comment by cgailey** [comment]
Any idea how to get all 3 of the announced divs?  range=next seems to only return 1 value, and 'https://cloud.iexapis.com/v1/stock/ra/upcoming-dividends?token=...' returns an empty set.

**Comment by McQgit** [comment]
@cgailey  The advanced dividend /time-series should do that.  I don't have a ready sample but there are fancy options with that.  Something I found in my samples to get you thinking (I didn't test this so ...)
https://cloud.iexapis.com/v1/time-series/advanced_dividends/RA?dateField=announceDate&on=2020-01-04&last=3&token=(token)&format=csv

**Comment by cgailey** [comment]
@McQgit Thanks for that, I'll give it a try.  I have already poked around with advanced_dividends a bit, but made a mistake with the range parameter and got all 43 past dividends for a cost of 3,000,000 messages!

**Comment by McQgit** [comment]
@cgailey Yeah, the last= is very helpful when playing around with time-series :)

**Comment by dvolatility** [comment]
Thanks for the replies. I’m trying. To figure out if there’s a way to filter the payable dates in the url. I just want the data-point to use in a Google Sheet cell.  Can we use ?filter= or ?range=... This is really annoying!

**Comment by dvolatility** [comment]
It’s happening with GGN, OXLC, OXSQ, and AAR-B as well. They all show March 2020 payment dates.

**Comment by dvolatility** [comment]
So I think I figured it out, thanks to the ImportJSON function in a script. See this comment: [https://github.com/iexg/IEX-API/issues/742#issuecomment-478089280](https://github.com/iexg/IEX-API/issues/742#issuecomment-478089280).

For RA's first dividend payment date, I used

=ImportJSON("https://cloud.iexapis.com/stable/stock/RA/dividends?range=next&format=psv&token=xxxxxxxxxx", "/paymentDate[0]", "noHeaders") 

and got the first dividend payment date of 2020-01-23 instead of the March dividend.

Does anyone know how to make it so I can change the format of the number on my Google Sheet?

**Comment by evancarter-iex** [comment]
Fixed.
