### ISSUE TITLE
[Data] quote endpoint: ytdChange value looks to be starting from 1/2 close instead of 12/31 close

### ISSUE THREAD

**Issue by KevinRPope** [iexg/IEX-API#1377]
For example, when pulling data for ECL this morning (/stock/ECL/quote), ytdChange shows -0.00633 (0.633%), while pulling CHG_PCT_YTD from Bloomberg at the same time returns -2.091%.  The Jan 2 1-day return per Bloomberg is -1.43%, which would make up that difference.

**Comment by hudhacks** [comment]
@KevinRPope - nice catch I noticed this situation too, and you are correct the start quote value for ytdChange is close of 2020-01-02 rather than 2019-12-31. As you know the API doc defines ytdChange as "_Refers to the price change percentage from **start of year** to previous close_", so it seems "start of year" is based on first close not the open. 

To resolve can always do some processing of data pulled via API, though would be nicer to have an additional key "ytdChangePreviousYear" that would make life easier :-)

**Comment by KevinRPope** [comment]
Thanks @hudhacks , but unfortunately omitting the returns for the first day of the year means that the ytdReturn field is calculating incorrectly.  If it were actually calculating from the "start of year" as you quoted from the docs, it would run from the **open** on 1/2/20, not the close on 1/2 (though in practice the calculation is normally done from the close of the prior day, in this case 12/31/19).  

As it stands, it is a bug since the values returned are demonstrably wrong based on the definition given in the docs.

**Comment by hudhacks** [comment]
@KevinRPope - I agree, the value should align with other data sources that follow accepted industry practice for YTD as you stated "... **open** on 1/2/20 ..."

**Comment by vanfad13** [comment]
I agree with you Kevin.  It should be based on 12/31 not 1/2.  On this subject, has anyone noticed that ytdChange is returning strange numbers?  For example, look at APA (Apache) -100.9% or NBL (Noble Energy) - 98.1%.
https://cloud.iexapis.com/v1/stock/market/batch?symbols=NBL,APA&types=quote&token=<yourtokenhere>
Am I missing something?

**Comment by hudhacks** [comment]
@vanfad13 - yes I've seen strange results too, which is reason I opened an [Issue] yesterday. The limited symbols I compared between IEX, MarketWatch,  and Schwab resulted in stocks matched and mutual funds not matching the ytdChange. Additionally, mutual funds ytdChange is the same value as the daily changePercent. Looks like a miss-assignment of function to the variable.

**Comment by loopasam** [comment]
important issue (in particular to gain trust from non-technical users), in my experience YTD return is computed using the close value of the last day for the year (= Dec 31), that's how Bloomberg traditionally reports it and what is generally accepted in the community.
