### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#1378]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
This works:
  https://cloud.iexapis.com/stable/stock/aapl/quote/latestPrice?token=MYTOKEN

This returns "Not found": 
  https://cloud.iexapis.com/stable/stock/aapl/quote/latestVolume?token=MYTOKEN

**Data URL (The URL you used to access the data without your token):**
See above

**What time did the problem occur (including timezone)?**
EST 12:40 PM

**What is the expected behavior?**
return volume

**What are the steps to reproduce**
see above

**Your environment (e.g. browser, OS, API version, language):**
Firefox, Windows 10, Stable, 

**Additional context**

**Comment by evancarter-iex** [comment]
Please see this: https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud
