### ISSUE TITLE
[Issue] SSE Streaming DEEP Trades Returns data for only first symbol

### ISSUE THREAD

**Issue by xanderdunn** [iexg/IEX-API#1379]
**Clearly describe the problem**
Attempting to use the SSE streaming DEEP Trades endpoint for multiple symbols returns data for only the first symbol in the list of given symbols. 

**What time did the problem occur? (with timezone)**
Ongoing

**What is the expected behavior?**
I expect the below URL to return data for all the given symbols (GOOG, SPY, TWTR, and AAPL), not just the first symbol. 

**Your environment (e.g. browser, OS, API version, language):**
Debian 9, stable API, Python 3.6

**API URL (if applicable)**
`https://cloud-sse.iexapis.com/stable/deep?token={}&symbols=goog,spy,twtr,aapl&channels=trades`

**What are the steps to reproduce the bug?**
Simply request messages from the above API URL and notice that trades only come through for GOOG but not of the other provided symbols.

**Additional context**
I am currently an IEX Cloud Launch customer.

The API docs say in one place: "Currently SSE requests are limited to 50 symbols per connection, but you can have multiple connections. Not available to Start users." This seems to indicate that the SSE endpoints should support multiple symbols. 

Specifically on the DEEP Trades endpoint the docs say "Maximum of 10 symbols". So, I would expect the above URL to work for all four symbols I provided.  I get all the data I expect for GOOG, but I never receive any trades for TWTR, SPY, or AAPL. 

My URL isn't malformed, is it?

**Comment by damienjs** [comment]
@xanderdunn did you get any resolution on this issue?

**Comment by mvandergrift** [comment]
I'm also experiencing this issue with all DEEP channels. They work fine for a single symbol, but multiple symbol queries only return the first. Requesting multiple channels (e.g. channels=trades,securityevent) works fine.

**Comment by ramicaza** [comment]
+1

**Comment by timpaine-iex** [comment]
docs updated
