### ISSUE TITLE
Chart starting time is 11AM

### ISSUE THREAD

**Issue by radikal9** [iexg/IEX-API#138]
## Summary
All the charts seem to be starting at 11 AM instead of 9.30AM. Sample chart of BAC added to this post but all the charts are doing this for me. 

## Details
<img width="678" alt="screen shot 2017-12-08 at 12 46 53 pm" src="https://user-images.githubusercontent.com/33485975/33778322-2bc3d30c-dc16-11e7-8a5b-71194751e2c1.png">

**Comment by evancarter-iex** [comment]
We are looking into this.
