### ISSUE TITLE
[Data]Symbol SPEC Not Current

### ISSUE THREAD

**Issue by kswier** [iexg/IEX-API#1380]
The price for symbol SPEC hasn't been updated since January 6th.

**Comment by McQgit** [comment]
@kswier It is now showing 0.0908 which matches what I see in Schwab as the latest price.  It is very thinly traded - going many days w/out any trades which is likely why you didn't see any updates in IEX.  In fact, I didn't see any trades between Jan 3 and Jan 8.

**Comment by kswier** [comment]
OK that makes sense.  I didn't realize it would go days without trades.
