### ISSUE TITLE
[Data] Quote Endpoint consistently failing to retrieve data

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#1381]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
>  Data not retrieved (e.g., open, hIgh, low, close, latestVolume are all NULL
> I tried this with MULTIPLE symbols. Same result

**Data URL (The URL you used to access the data without your token):**
URL: https://cloud.iexapis.com/stable/stock/T/quote?token=mytoken

**What time did the problem occur (including timezone)?**
3:23 EST

**What is the expected behavior?**
Retrieve data <> NULL

**What are the steps to reproduce**
see above. URL fails to retrieve data

**Your environment (e.g. browser, OS, API version, language):**
> Tried it directly in Firefox. Also using Webservice in Excel
> O/S = Windows 10
> API version: Tried V1, stable

**Additional context**

**Comment by evancarter-iex** [comment]
https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud
