### ISSUE TITLE
[Data]Symbol LHSIF Price Not Current

### ISSUE THREAD

**Issue by kswier** [iexg/IEX-API#1382]
As of January 9, 2020 LHSIF price has not been updated since January 7, 2020.

**Comment by McQgit** [comment]
@kswier  I'm seeing it current now - are you?  I believe there is a delay posting OTC stocks data and it should reflect Jan9 later tonite.  If you still see only Jan7, what url are you using?  

With this:
https://cloud.iexapis.com/v1/stock/market/batch?symbols=lhsif&types=quote,previous&token=X

I see this:
{
  "LHSIF": {
    "previous": {
      "date": "2020-01-08",
      "open": 0.391,
      "close": 0.4322,
      "high": 0.442,
      "low": 0.391,
      "volume": 182412,
      "uOpen": 0.391,
      "uClose": 0.4322,
      "uHigh": 0.442,
      "uLow": 0.391,
      "uVolume": 182412,
      "change": 0.0185,
      "changePercent": 4.4718,
      "changeOverTime": 0,
      "symbol": "LHSIF"
    },
    "quote": {
      "symbol": "LHSIF",
      "companyName": "Liberty Health Sciences, Inc.",
      "primaryExchange": "US OTC",
      "calculationPrice": "previousclose",
      "open": null,
      "openTime": null,
      "close": null,
      "closeTime": null,
      "high": 0.47,
      "low": 0.4236,
      "latestPrice": 0.4322,
      "latestSource": "Previous close",
      "latestTime": "January 8, 2020",
      "latestUpdate": 1578459600000,
      "latestVolume": 1775849,
      "iexRealtimePrice": null,
      "iexRealtimeSize": null,
      "iexLastUpdated": null,
      "delayedPrice": 0,
      "delayedPriceTime": 1578603593000,
      "extendedPrice": 0,
      "extendedChange": null,
      "extendedChangePercent": null,
      "extendedPriceTime": 0,
      "previousClose": 0.4322,
      "previousVolume": 182412,
      "change": 0,
      "changePercent": 0,
      "volume": 1775849,
      "iexMarketPercent": null,
      "iexVolume": null,
      "avgTotalVolume": 725138,
      "iexBidPrice": null,
      "iexBidSize": null,
      "iexAskPrice": null,
      "iexAskSize": null,
      "marketCap": 149234770,
      "peRatio": 32.99,
      "week52High": 0.9392,
      "week52Low": 0.2559,
      "ytdChange": -0.036343,
      "lastTradeTime": 1578603593000
    }
  }
}

**Comment by kswier** [comment]
Yes I am seeing it correct now.  I think the issue is it just doesn't have many trades so the price may not be updated each day if there are no trades or very few trades.

**Comment by McQgit** [comment]
@kswier That can happen but LHSIF trades more actively than that other one you saw delayed.  What I noticed is for OTC traded stocks (like LHSIF), IEX only supports end-of-day (EOD) pricing and they don't update that until very early morning eastern time (sometime between midnight and 6am).  So, depending on your timezone and when you look, it might be further behind than you expect. That is, Fri at 10pm eastern will show Thu close, for example.

I wish IEX would clearly document when everything got refreshed.
