### ISSUE TITLE
Missing chartByDay data on dates after 2020-01-20

### ISSUE THREAD

**Issue by rmantovani** [iexg/IEX-API#1387]
**Clearly describe the problem**
Missing  Char data on dates after 2020-01-20 - APPL, ORCL and many other stocks 

**What time did the problem occur? (with timezone)**
everytime

**What is the expected behavior?**
Chart return data by day

**Your environment (e.g. browser, OS, API version, language):**
Linux, Java

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/aapl/chart/date/20200120?chartByDay=true&token=XXXXXXXXXXXXXX

**What are the steps to reproduce the bug?**
Call example above

**Comment by evancarter-iex** [comment]
January 20th was a holiday in the US.  The 21st has data as expected.
