### ISSUE TITLE
Double pasted text in 'EDN' company name

### ISSUE THREAD

**Issue by mmjdotdk** [iexg/IEX-API#139]
## Summary
The company info text for https://api.iextrading.com/1.0/stock/EDN/company seems wrong.

## Details
`$ curl -s https://api.iextrading.com/1.0/stock/EDN/company | python -mjson.tool | grep companyName
    "companyName": "Empresa Distribuidora Y Comercializadora Norte S.A. (Edenor) Empresa Distribuidora Y Comercializadora Norte S.A. (Edenor) American Depositary Shares",`

### Date/time of issue

2017-12-11T17:54:00.000+01

### API URL
https://api.iextrading.com/1.0/stock/EDN/company 

### What you expected to happen
`$ curl -s https://api.iextrading.com/1.0/stock/EDN/company | python -mjson.tool | grep companyName
    "companyName": "Empresa Distribuidora Y Comercializadora Norte S.A. (Edenor) American Depositary Shares",`

### What actually happened
`$ curl -s https://api.iextrading.com/1.0/stock/EDN/company | python -mjson.tool | grep companyName
    "companyName": "Empresa Distribuidora Y Comercializadora Norte S.A. (Edenor) Empresa Distribuidora Y Comercializadora Norte S.A. (Edenor) American Depositary Shares",`

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
