### ISSUE TITLE
Inconsistent CORS headers on streaming quote data

### ISSUE THREAD

**Issue by stobor827** [iexg/IEX-API#1390]
When using the 'last' streaming api (https://ws-api.iextrading.com/1.0/last), sometimes the CORS header ‘Access-Control-Allow-Origin:*' is set, but it is missing frequently.

 Is this intended behavior?  I can workaround this for my webapp by proxying the request through a backend, but would prefer not to if this can be fixed...

**Comment by joshuablackburn-iex** [comment]
Have you tried using IEX Cloud for streaming IEX data?

**Comment by timpaine-iex** [comment]
closing as stale
