### ISSUE TITLE
[Data] Missing intraday data 2020-01-23

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1391]
**Clearly describe the data problem**
All data pulled yesterday from /intraday-prices appears to be missing 15 random minutes throughout the day. 

Today, the same data from the chart endpoint is missing 9 minutes of data.

Also today, some market data returned by the chart endpoint for 2020-01-23 is clearly inaccurate, as a minute will state both that no trades occurred and trades occurred on IEX in the same minute. 

**Data URL (The URL you used to access the data without your token):**
/stock/SPY/intraday-prices
/stock/SPY/chart/date/20200123

**What time did the problem occur (including timezone)?**
2020-01-23 16:30 ET - current

**What is the expected behavior?**
- 390 minutes of intraday data per day. 
- 0/null with last trade price if no trades occurred during a minute. 
- marketVolume should always equal or exceed IEX volume.

**What are the steps to reproduce**
Request /stock/{symbol}/chart/date/20200123 for any stock.

**Comment by noam2** [comment]
check out www.spikeet.com

**Comment by timpaine-iex** [comment]
consolidating with https://github.com/iexg/IEX-API/issues/1701
