### ISSUE TITLE
[Data] Gold price in commodities

### ISSUE THREAD

**Issue by Jokero** [iexg/IEX-API#1393]
**Clearly describe the data problem**
Currently I'm looking for a way to fetch gold price using your API. Among different commodities present in documentation there are oil, gas and other stuff prices but there is no price for gold (and other metals). 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/ref-data/symbols does not contain symbol for gold

**What is the expected behavior?**
I would expect to have gold among other commodities

**Additional context**
What is the current recommended way to fetch price for gold using your API?

**Comment by idahosummits** [comment]
Did you ever figure this out?

**Comment by Jokero** [comment]
@idahosummits they replied me in email that this request to add gold will be passed to the team

**Comment by idahosummits** [comment]
@Jokero Thanks for the quick response!

**Comment by met68** [comment]
Any update on this? A quote for all precious metals would sure be MUCH appreciated!

**Comment by timpaine-iex** [comment]
vote on roadmap, there's a process of sourcing vendors and ingesting data. 
https://iexcloud.io/console/roadmap

futures daily should be released in the next quarter or so
