### ISSUE TITLE
Matching Prices for Open/Close? 

### ISSUE THREAD

**Issue by andyschleckfan** [iexg/IEX-API#1394]
This may be a resolved issue, but I pulled SPY 3m data and TSLA 3m data, and I can't seem to match the opening prices or closing prices with other data sets. 

Call is simple for either, but here is TSLA: 
"https://sandbox.iexapis.com/stable/stock/TSLA/chart/3m?token=###"

And for today 2020-01-28:
I have Open/Close at 580.84, 579.8 from API
However, TSLA Opened/Closed at or very close to 570.17, 566.90 via two other sources 

What API should I be making/what is my error?

**Comment by joshuablackburn-iex** [comment]
Your URL shows you’re using the testing sandbox. Test data is purposefully randomized. If you need to validate data please use production API calls.
