### ISSUE TITLE
[Request] TSX Upcoming Dividends/Distributions & ETF Holdings

### ISSUE THREAD

**Issue by hatzopoulos** [iexg/IEX-API#1395]
I am curious if any of the API data plans (premium etc) provide upcoming dividend and distributions data for the Toronto Stock Exchange? 

I'm also interested in TSX ETFs holdings data, is that available yet? I saw https://github.com/iexg/IEX-API/issues/491 and just wondering when or if that will be available?

If this info was already posted somewhere can you provide any links to more info?

Thanks

p.s. thanks for all the great work.

**Comment by rickyplouis** [comment]
Any update on this issues? Was also looking at dividends for TSX and saw that many dividend producing stocks are returning null for their dividendYield

**Comment by timpaine-iex** [comment]
https://iexcloud.io/console/roadmap
