### ISSUE TITLE
[Request] Use of Standard HTTP Authentication Scheme

### ISSUE THREAD

**Issue by Spomky** [iexg/IEX-API#1396]
**Is your feature request related to a problem? Please describe.**
The API authentication uses a token that is sent in the query string (e.g. `https://sandbox.iexapis.com/stable/ref-data/exchanges?token=aabbccddeeff00112233445566778899`) or in the request body

```
POST /stable/ref-data/isin HTTP/1.1
Host: sandbox.iexapis.com

{
    "token" : "aabbccddeeff00112233445566778899",
    "isin" : [
        "isin",
        "isin",
        "isin"
    ]
}
```

This authentication mechanism is really risky as proxy may intercept and store the request and thus catch the token.
Moreover, it requires the transmission of credentials in the search items and cause integration problem. For each request, the application have to know if the token shall be set in the query string of the body.

**Describe the solution you'd like**
A better approach could be the use of the standard `Authentication` HTTP header and the `Bearer` scheme.
With this scheme, no matter if the request is a POST, GET, PUT request or other method. The credential is always available at the same place.
The quesry string and the body will always have exactly what is needed for the request. No more, no less.

```
POST /stable/ref-data/isin HTTP/1.1
Host: sandbox.iexapis.com
Authorization: Bearer aabbccddeeff00112233445566778899

{
    "isin" : [
        "isin",
        "isin",
        "isin"
    ]
}
```

**Describe alternatives you've considered**
none

**Additional context**

* https://tools.ietf.org/html/rfc6750
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
* https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml

**Comment by joshuablackburn-iex** [comment]
I agree with you that there are multiple ways to authenticate requests, and some viewed as more correct. We made the deliberate decision to start with query string authentication for ease of use. For those that require more sophisticated security, we do provided signed requests https://iexcloud.io/docs/api/#signed-requests

The optimal solution is to support both methods which gives our users more flexibility. I'm not sure if header based authentication will be available in v1 or rolled out with v2. TBD.
