### ISSUE TITLE
ENB missing upcoming-dividend value

### ISSUE THREAD

**Issue by WillTron** [iexg/IEX-API#1397]
**Clearly describe the data problem**
The "upcoming-dividends" endpoint for ticker ENB outputs an empty value for "amount". 

```
{
  "ENB": {
    "upcoming-dividends": [
      {
        "exDate": "2020-02-13",
        "paymentDate": "2020-03-01",
        "recordDate": "2020-02-14",
        "declaredDate": "2019-12-10",
        "amount": "",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "ENB"
      }
    ]
  }
}
```

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=enb&types=upcoming-dividends&token=my_token

**What time did the problem occur (including timezone)?**
today (CST) as of this post and multiple times when checked in past several weeks

**What is the expected behavior?**
"amount" key to have the dividend value posted

**What are the steps to reproduce**
run above API call

**Your environment (e.g. browser, OS, API version, language):**
latest Chrome, Win10 Pro, IEX Cloud v1, Launch Plan

**Additional context**
an additional datapoint: ENB had a similar missing div "amount" value for 4Q2019. In that case, the /dividend EP was missing the latest USD div amount value but included the CAD amount value (reference post #1320). That issue eventually self-corrected itself sometime in the 4th quarter, but who knows. So, ENB dividend output seems to be an ongoing issue in one form or another from quarter-to-quarter. It trades as an ADR so that may perhaps be a contributing factor -- or not.

**Comment by WillTron** [comment]
Two more Canadian ADRs -- Canadian Pacific Railway Limited (CP) and TransAlta Corporation (TAC) also have missing key values for dividend amounts in the upcoming-dividends EP

```
{
  "CP": {
     "upcoming-dividends": [
       {
        "exDate": "2020-03-26",
        "paymentDate": "2020-04-27",
        "recordDate": "2020-03-27",
        "declaredDate": "2020-01-28",
        "amount": "",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "CP"
      }
    ]
  }
}

{
  "TAC": {
    "upcoming-dividends": [
      {
        "exDate": "2020-02-28",
        "paymentDate": "2020-04-01",
        "recordDate": "2020-03-02",
        "declaredDate": "2020-01-16",
        "amount": "",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "TAC"
      }
    ]
  }
}
```

**Comment by McQgit** [comment]
@WillTron  In case this is helpful ... their time-series/advanced_dividends has the amount in CAD for both ENB and CP (didn't check TAC).  I didn't check if the final USD amount has been determined for the ADR - it may not be set yet.  I don't care about the final, I just approximate that using the current exchange rate.  Example:

https://cloud.iexapis.com/v1/time-series/advanced_dividends/cp?last=1&token=X

Shows (partial):

    "symbol": "CP",
    "exDate": "2020-03-26",
    "recordDate": "2020-03-27",
    "paymentDate": "2020-04-27",
    "announceDate": "2020-01-28",
    "currency": "CAD",
    "frequency": "quarterly",
    "amount": 0.83,
    "description": "Ordinary Shares",
    "flag": "Cash",
    "securityType": "Equity Shares",

**Comment by McQgit** [comment]
@WillTron  Adding to the background on this issue ...  I saw this on ENB corporate site:
"Payment of dividends will be delivered to the U.S. holders in U.S. Dollars converted at the prevailing exchange rate on the dividend record date. "

The record date has not yet arrived so only estimates of USD amounts are possible.  I don't know that this is the reason for IEX not providing an amount, just thought it might be useful.  See:
https://www.enbridge.com/Investment-Center/FAQs/Dividend-QA.aspx

Personally, I'd prefer seeing the amount in the announced currency (in this case CAD) rather than somebody elses estimate of USD amount.  But, it is common for sites to estimate USD (w/various methods).

**Comment by WillTron** [comment]
Thanks @McQgit for the advanced_dividends work-around suggestion and the corporate link. I wasn't aware that ADR currency amounts were handled this way -- but I guess it makes sense since div payout dates are often 30 to 60 days (or more) past the declared div date. I agree, I don't think this is an IEX missing data issue so much as it's a consequence of how ADR's are handled in general when it comes to compensating for currency conversion.

I'll have to play around with adding some conditional logic to my code functions to try and get the time-series EP to give me what I'm looking for. At 75K data weight per returned dividend I'll need to be careful when I do some tests -- remembering to switch over to my sandbox API key when performing those initial loops may prove to be challenging, otherwise oh-oh ....
