### ISSUE TITLE
[Data] SSE interval streaming not working?

### ISSUE THREAD

**Issue by alstephan** [iexg/IEX-API#1398]
**Clearly describe the data problem**
I'm a paying customer. Can't get interval SSE streaming to work.

I'm requesting a non-Nasdaq stock (XOM).

Doesn't work (stocksUS1Minute):
```
$ curl --header 'Accept: text/event-stream' 'https://cloud-sse.iexapis.com/stable/stocksUS1Minute?token=YOUR_TOKEN&symbols=xom'

The requested data requires permission to access.
```

Works (stocksUSNoUTP):
```
$ curl --header 'Accept: text/event-stream' 'https://cloud-sse.iexapis.com/stable/stocksUSNoUTP?token=YOUR_TOKEN&symbols=xom'
```

Is UTP needed even to get non Nasdaq stocks with interval SSE streaming? Why?

Is UTP needed to get any SSE streaming endpoint (including interval endpoints) working other than stocksUSNoUTP?

**Comment by joshuablackburn-iex** [comment]
If you don't have UTP authorization you should use the NoUTP stream.
