### ISSUE TITLE
[Data] Cash flow data sometimes missing for newly reported

### ISSUE THREAD

**Issue by CraigerBrau** [iexg/IEX-API#1399]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
When there is a new report date, I collect income statement, balance sheet, and cash flow data.  I've noticed that if the report date is especially fresh, some of the data is null.  

Case in point:
{
  "symbol": "DAL",
  "cashflow": [
    {
      "reportDate": "2019-12-31",
      "netIncome": 1099000000,
      "depreciation": null,
      "changesInReceivables": -18000000,
      "changesInInventories": null,
      "cashChange": null,
      "cashFlow": null,
      "capitalExpenditures": 3864000000,
      "investments": null,
      "investingActivityOther": null,
      "totalInvestingCashFlows": 3864000000,
      "dividendsPaid": null,
      "netBorrowings": 555000000,
      "otherFinancingCashFlows": null,
      "cashFlowFinancing": 555000000,
      "exchangeRateEffect": null
    }
  ]
}

Delta pays quarterly dividends (the last being in Nov '19), so for "dividendsPaid" to be **null** is wrong.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/dal/cash-flow/?token=[hidden]&period=quarter&last=1

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**
Report values to be accurate for the report date.  If the data is not complete, then the statements as of the report date should not be available.

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by CraigerBrau** [comment]
Since I'm not getting any response on this, I'll keep posting other instances.

https://cloud.iexapis.com/stable/stock/wfc/cash-flow/?token=[hidden]&period=quarter&last=2

{
  "symbol": "WFC",
  "cashflow": [
    {
      "reportDate": "2019-12-31",
      "netIncome": 2873000000,
      "depreciation": null,
      "changesInReceivables": null,
      "changesInInventories": null,
      "cashChange": null,
      **"cashFlow": null,**
      "capitalExpenditures": null,
      "investments": null,
      "investingActivityOther": null,
      "totalInvestingCashFlows": null,
      **"dividendsPaid": null,**
      "netBorrowings": -12401000000,
      "otherFinancingCashFlows": null,
      "cashFlowFinancing": -12401000000,
      "exchangeRateEffect": null
    },
    {
      "reportDate": "2019-09-30",
      "netIncome": 4610000000,
      "depreciation": null,
      "changesInReceivables": null,
      "changesInInventories": null,
      "cashChange": -15696000000,
      "cashFlow": -86000000,
      "capitalExpenditures": null,
      "investments": 312000000,
      "investingActivityOther": null,
      "totalInvestingCashFlows": -20367000000,
      "dividendsPaid": -2458000000,
      "netBorrowings": -3890000000,
      "otherFinancingCashFlows": -78000000,
      "cashFlowFinancing": 4757000000,
      "exchangeRateEffect": null
    }
  ]
}

**Comment by CraigerBrau** [comment]
Another...

https://cloud.iexapis.com/stable/stock/pfe/cash-flow/?token=[hidden]&period=quarter&last=2

{
  "symbol": "PFE",
  "cashflow": [
    {
      "reportDate": "2019-12-31",
      "netIncome": -336000000,
      "depreciation": null,
      "changesInReceivables": null,
      "changesInInventories": null,
      "cashChange": null,
      **"cashFlow": null,**
      "capitalExpenditures": null,
      "investments": null,
      "investingActivityOther": null,
      "totalInvestingCashFlows": null,
      **"dividendsPaid": null,**
      "netBorrowings": -9234000000,
      "otherFinancingCashFlows": null,
      "cashFlowFinancing": -9234000000,
      "exchangeRateEffect": null
    },
    {
      "reportDate": "2019-09-30",
      "netIncome": 7680000000,
      "depreciation": 1553000000,
      "changesInReceivables": 354000000,
      "changesInInventories": null,
      "cashChange": 1010000000,
      "cashFlow": 4510000000,
      "capitalExpenditures": -662000000,
      "investments": 4797000000,
      "investingActivityOther": null,
      "totalInvestingCashFlows": -6760000000,
      "dividendsPaid": -2004000000,
      "netBorrowings": 5347000000,
      "otherFinancingCashFlows": -125000000,
      "cashFlowFinancing": 3273000000,
      "exchangeRateEffect": -13000000
    }
  ]
}

**Comment by naftalyava** [comment]
I get "dividendsPaid":null for all companies I tried. [Very large dividend paying companies: INTC, CSCO, IBM and etc...]

Any news on this issue?
