### ISSUE TITLE
Support: Difference between "latestPrice" and "delayedPrice"

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#14]
First of all, thank you very much for providing free API to developer community.

I have a question regarding https://api.iextrading.com/1.0/stock/aapl/quote

I understand that, `latestPrice` is the latest price solely from IEX stock exchange only

However, for `delayedPrice`, may I know is it a 15 min delayed price solely from IEX stock exchange only, or it is an aggregated 15 min delayed value from multiple stock exchanges (IEX, Nasdaq, Dow Jone, ...) ?

Thank you

**Comment by joshuablackburn-iex** [comment]
latestPrice can be up to 3 sources depending on which is most recent.  We use the IEX real time price first.  If we don't have an IEX price in the last 15 minutes, we fall back to the market wide 15 minute delayed price.  If we don't have that, we fall back to previous close price.  All three prices are separately available in the quote data.

**Comment by joshuablackburn-iex** [comment]
Documentation has been updated.
