### ISSUE TITLE
Batch request with symbol WFC+

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#140]
## Summary

If the batch request includes WFC+, it returns WFC. 

Quote api for WFC+ works.

## Details

If the batch request includes WFC+, it returns WFC. 

Quote api for WFC+ works.

### Date/time of issue

12/11/2017

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb,WFC+,&types=quote

### What you expected to happen

WFC+ should return warrant quote instead of WFC.

### What actually happened

WFC+ was treated as WFC.

**Comment by jcape** [comment]
@bishinew The plus sign is actually a special character in a URI (it means " " [space]), so to have a literal "+" you need to use the escape version: "%2b", so the working URI would be:

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb,WFC%2b,&types=quote

Most languages have some kind of URL encoding method which will do the escapes/unescapes properly.

**Comment by bishinew** [comment]
Your suggestion works. Thanks
