### ISSUE TITLE
When are upcoming-dividends no longer upcoming-dividends?

### ISSUE THREAD

**Issue by WillTron** [iexg/IEX-API#1404]
**Clearly describe the data problem**
Occasionally on a ticker's ex-Div date the json output will include the dividend information in both the "dividends" EP and in the "upcoming-dividends" EP. This has happened in the past for several tickers -- JPM comes to mind, but today it's TJX.  How are these two EP's supposed to work with regards to one another? This isn't happening with the vast majority of tickers on the ex-Dates -- but why is it happening for some?

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=tjx&types=dividends,upcoming-dividends&token=my_token

**What time did the problem occur (including timezone)?**
today (CST) about 30 minutes prior to this post. 

**What is the expected behavior?**
It seems the dividend should either be in the "dividends" EP OR in the "upcoming-dividends" EP but not both. If today's date is the ex-Div date for a ticker, shouldn't the dividend just be in the "dividends" EP since it's no longer "upcoming"? 

**What are the steps to reproduce**
run above API call. although, the issue may resolve itself by tomorrow since tomorrow will no longer be the ex-Date for TJX.

**Your environment (e.g. browser, OS, API version, language):**
latest Chrome, Win10 Pro, IEX Cloud v1, Launch Plan

**Additional context**
```
{
  "TJX": {
    "dividends": [
      {
        "exDate": "2020-02-12",
        "paymentDate": "2020-03-05",
        "recordDate": "2020-02-13",
        "declaredDate": "2019-12-03",
        "amount": "0.23",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-02-13"
      }
    ],
    "upcoming-dividends": [
      {
        "exDate": "2020-02-12",
        "paymentDate": "2020-03-05",
        "recordDate": "2020-02-13",
        "declaredDate": "2019-12-03",
        "amount": "0.23",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "TJX"
      }
    ]
  }
}
```

**Comment by WillTron** [comment]
It's one day after TJX's ex-Date and the ticker is still double reporting its upcoming-dividend. In addition, MMM has a dividend ex-Date today and it's double reporting also.

```
{
  "MMM": {
    "dividends": [
      {
        "exDate": "2020-02-13",
        "paymentDate": "2020-03-12",
        "recordDate": "2020-02-14",
        "declaredDate": "2020-02-04",
        "amount": "1.47",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-02-14"
      }
    ],
    "upcoming-dividends": [
      {
        "exDate": "2020-02-13",
        "paymentDate": "2020-03-12",
        "recordDate": "2020-02-14",
        "declaredDate": "2020-02-04",
        "amount": "1.47",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "MMM"
      }
    ]
  }
}
```

**Comment by WillTron** [comment]
Just found another one -- SPG .... I'm sensing a trend

```
{
  "SPG": {
    "dividends": [
      {
        "exDate": "2020-02-13",
        "paymentDate": "2020-02-28",
        "recordDate": "2020-02-14",
        "declaredDate": "2020-02-04",
        "amount": "2.1",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-02-14"
      }
    ],
    "upcoming-dividends": [
      {
        "exDate": "2020-02-13",
        "paymentDate": "2020-02-28",
        "recordDate": "2020-02-14",
        "declaredDate": "2020-02-04",
        "amount": "2.1",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "SPG"
      }
    ]
  }
}
```

**Comment by McQgit** [comment]
@WillTron I agree it's wrong to have the same div show in both past /dividends and future /upcoming.  

But, the more interesting example to me is your original TJX.  It's ex-date was Feb12 and it still appears in /upcoming-dividends as of 10:33p eastern on Feb13.  Regardless of the timing of the updates to these endpoints, a Feb12 ex-date should not be /upcoming late on Feb13.

An aside ... their new time-series doesn't exhibit such problems.  Although, the message cost (75K) may not work for you.  The below url costs 150K msgs (75K x 2 divs).
https://cloud.iexapis.com/v1/time-series/advanced_dividends/mmm?last=2&token=X
Sorry if we've gone over time-series before.

**Comment by WillTron** [comment]
Yes @McQgit you pointed me to the time-series EP previously which was helpful since I wasn't aware of it's capability, but the double reporting of the upcoming-dividend shouldn't require a work-around let alone a work-around with a heavy data weight associated with it.

There is clearly something amiss with the upcoming-dividends EP data. I just randomly chose 10 tickers that have ex-Dates of today (2020-02-13) and 100% of them are all exhibiting the same double reporting of the dividend in the /dividends EP and the /upcoming-dividends EP. --> AGN, AMGN, BSET, BA, BFST, COP, DUK,  EMR, FBK, FSB

**Comment by jesseorosz** [comment]
I handle this by throwing the data in SQL then putting a UNION over the two tables.
