### ISSUE TITLE
Incorrect Market Caps for Quote Endpoint

### ISSUE THREAD

**Issue by pwenke** [iexg/IEX-API#1405]
Problem
At some point between 2/10/20 and 2/13/20, the market caps returned by the quote endpoint for many stocks (across almost all sectors) changed drastically, and I believe incorrectly.

Examples (symbol, previous market cap data, incorrect market cap data):
BRK.A
      555,566,818,400.00
471,744,515,000,000.00

BABA
  582,714,697,250.00
4,814,092,828,258.00

TLK
    27,360,979,640.00
2,751,948,436,931.00

CEO
    70,993,989,750.00
7,255,211,724,800.00

CEA
    2,544,905,048.00
128,642,927,758.00

RYAAY
  19,987,968,000.00
100,640,063,657.00

ENIA
  14,578,135,080.00
725,102,562,509.00

Data URL
https://cloud.iexapis.com/v1/stock/{symbol}/quote
https://cloud.iexapis.com/stable/stock/{symbol}/quote

Date / Time
BRK.A is still reporting a market cap of $470T as of 2/15/20 CST

Expected Behavior
As far as I know, the BRK.A market cap is still around $555B, not $470T

Steps to Reproduce
https://cloud.iexapis.com/stable/stock/BRK.A/quote

Environment
Chrome
Windows 10
Both v1 and stable API
ColdFusion

Additional Context
I'm hoping you can look at the historical market caps around 2/11-2/12 for your stocks and compare them to your current data to fix all of the problems.

Thanks,
Pat

**Comment by evancarter-iex** [comment]
This is resolved.

**Comment by pwenke** [comment]
Looks good, thanks Evan!
