### ISSUE TITLE
[Data] How can I know that a new report has been published?

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#1406]
**nextEarningsDate** shows the date the report was published. But if from the beginning of this date, I will send a request every day [https://cloud.iexapis.com/v1/stock/{stock}/income](https://cloud.iexapis.com/v1/stock/{stock}/income) and check whether new information has appeared - it will be expensive. Are there other ways?

We know when the report will be in the future. But we don't know if it's published. :(

**Comment by McQgit** [comment]
@xxx44yyy You could look at their new Rules Engine (in beta).  It sends event-driven alerts.  See:
https://intercom.help/iexcloud/en/collections/2109136-rules-engine

I didn't look to see if it handled new 10K/10Q data.  But, this is their only api that I know of that does event-driven alerts.  I usually rely on polling with the IEX APIs - as you describe.

**Comment by xxx44yyy** [comment]
@McQgit Thanks, bro! Rules doesn't know how to do this. Apparently I will send requests once a week after the nextEarningsDate date, so that it is cheaper.

**Comment by xxx44yyy** [comment]
@McQgit 

I have a plan:
1. Looking for a company's CIK, for example: https://www.sec.gov/cgi-bin/browse-edgar?CIK=**AmeriCann**&Find=Search&owner=exclude&action=getcompany&output=**atom**
2. Write CIK to the database 
3. After **nextEarningsDate** check every day https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=**0001508348**&type=10-Q&dateb=&owner=include&count=10&output=**atom**
4. If there is a fresh **FilingDate**, we send requests to IEX to get **Income** data.


The second way: the same thing, but we are waiting for the information to appear here: https://www.sec.gov/cgi-bin/browse-edgar?company=&CIK=**0001508348**&type=10-Q&owner=include&count=40&action=getcurrent


What do you think about it?

**Comment by joshuablackburn-iex** [comment]
You can also take a look at Cloud Cache. We built it to solve for this exact situation. Cloud Cache (iexcloud.io/cloud-cache) allows you to simply pass cache=true on an API call, and we will only charge the full message rate if the data changes. If the data is the same then the message rate is only 1.

**Comment by xxx44yyy** [comment]
@joshuablackburn-iex It's cool, but expensive. If I understand correctly, it is necessary to buy slots. 1 slot = 1 URL. If I want to receive Income quarterly and annual, then I need 2 URLS. Why should I pay for 98 slots (I mean, at least 100 slots for $ 50) if I only need 2?

**Comment by McQgit** [comment]
@xxx44yyy Edgar is useful.  A couple comments on your method:

1) You can use the symbol directly - no need for CIK lookup
https://www.sec.gov/cgi-bin/browse-edgar?CIK=MSFT&owner=exclude&action=getcompany

2) You have to look for both 10-Q (quarterly) and 10-K (annual)
https://www.sec.gov/cgi-bin/browse-edgar?CIK=MSFT&owner=exclude&action=getcompany&count=2&type=10-K

There may be a lag between the SEC filing and it showing up in IEX.  I don't use IEX for financials but a lag isn't unusual at other fin API so I'm just guessing IEX also may have a lag.

**Comment by xxx44yyy** [comment]
@McQgit Ok, thanks! Where do you get your financial information? Parsing data from the SEC or using a different API?

**Comment by McQgit** [comment]
@xxx44yyy I get financials from another API (a paid service).  I don't like to mention other commerical products on a vendor site (even a git).  I use Edgar to review the financials when something looks odd and I want to review in more depth (the notes, specific line items, ...).  Over the years I have used a variety of fin API.

**Comment by xxx44yyy** [comment]
@McQgit Ok, thanks

**Comment by joshuablackburn-iex** [comment]
We do offer the as reported numbers directly from the filings and we hope to expand this functionality in the near future to include providing search through the documents.

**Comment by xxx44yyy** [comment]
@joshuablackburn-iex Do you have an email subscription to changelog? I am your client, but I do not receive emails with information that I see in the documentation in the changelog section.

**Comment by xxx44yyy** [comment]
@McQgit How can I contact you?

**Comment by McQgit** [comment]
@xxx44yyy I sympathize with your plight and would help.  But, I don't wish to publish personal contact info.  And, github doesnt seem to offer inter-user convo.  If you show a way for me to contact you, I will.

**Comment by xxx44yyy** [comment]
@McQgit  my current nickname [at] gmail.com

thanks
