### ISSUE TITLE
[Data] I can't believe that MasterCard has no revenue for 5 years

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#1409]
**URL:** [https://cloud.iexapis.com/stable/stock/MA/income?&period=annual&last=5&token=TOKEN](https://cloud.iexapis.com/stable/stock/MA/income?&period=annual&last=5&token=TOKEN)

**Result:**
```json
{"symbol":"MA","income":[{"reportDate":"2019-12-31","totalRevenue":null,"costOfRevenue":null,"grossProfit":null,"researchAndDevelopment":null,"sellingGeneralAndAdmin":null,"operatingExpense":null,"operatingIncome":9703000000,"otherIncomeExpenseNet":28000000,"ebit":9703000000,"interestIncome":224000000,"pretaxIncome":9731000000,"incomeTax":1613000000,"minorityInterest":0,"netIncome":8118000000,"netIncomeBasic":8118000000},{"reportDate":"2018-12-31","totalRevenue":null,"costOfRevenue":null,"grossProfit":null,"researchAndDevelopment":null,"sellingGeneralAndAdmin":null,"operatingExpense":null,"operatingIncome":8357000000,"otherIncomeExpenseNet":-1153000000,"ebit":8357000000,"interestIncome":186000000,"pretaxIncome":7204000000,"incomeTax":1345000000,"minorityInterest":0,"netIncome":5859000000,"netIncomeBasic":5859000000},{"reportDate":"2017-12-31","totalRevenue":null,"costOfRevenue":null,"grossProfit":null,"researchAndDevelopment":null,"sellingGeneralAndAdmin":null,"operatingExpense":null,"operatingIncome":6879000000,"otherIncomeExpenseNet":-357000000,"ebit":6879000000,"interestIncome":154000000,"pretaxIncome":6522000000,"incomeTax":2607000000,"minorityInterest":0,"netIncome":3915000000,"netIncomeBasic":3915000000},{"reportDate":"2016-12-31","totalRevenue":null,"costOfRevenue":null,"grossProfit":null,"researchAndDevelopment":null,"sellingGeneralAndAdmin":null,"operatingExpense":null,"operatingIncome":5884000000,"otherIncomeExpenseNet":-238000000,"ebit":5884000000,"interestIncome":95000000,"pretaxIncome":5646000000,"incomeTax":1587000000,"minorityInterest":0,"netIncome":4059000000,"netIncomeBasic":4059000000},{"reportDate":"2015-12-31","totalRevenue":null,"costOfRevenue":null,"grossProfit":null,"researchAndDevelopment":null,"sellingGeneralAndAdmin":null,"operatingExpense":null,"operatingIncome":5006000000,"otherIncomeExpenseNet":-48000000,"ebit":5006000000,"interestIncome":61000000,"pretaxIncome":4958000000,"incomeTax":1150000000,"minorityInterest":0,"netIncome":3808000000,"netIncomeBasic":3808000000}]}
```

**Question.** What should I do? I've seen similar problems with other companies.

**Comment by xxx44yyy** [comment]
More than 500 companies with the same problem ([https://gist.github.com/xxx44yyy/fda38f05177487706e79eb94e2d7877c](https://gist.github.com/xxx44yyy/fda38f05177487706e79eb94e2d7877c)). I downloaded data on 2,000 companies, paying about $ 35. But it turned out that a quarter of them were bad.

**Comment by xxx44yyy** [comment]
You have the same problem on your site: [https://iextrading.com/apps/stocks/MA](https://iextrading.com/apps/stocks/MA)

**Comment by joshuablackburn-iex** [comment]
Our documentation does not that financial companies will have limited information due to the way their financials are reported, and how our data partner calculates their fields.

**Comment by xxx44yyy** [comment]
@joshuablackburn-iex I don't know what you mean. Do you mean something like "we have nothing to do with this, just be patient, it's not our problem, relax, don't like it-leave"? Please explain, I do not understand.

**Comment by joshuablackburn-iex** [comment]
I corrected the previous post. What I’m saying is our provider does not provide those data points, so that is why we pull the as reported numbers directly and provide them in the as reported endpoint. Until they advise otherwise, I don’t have a way around this.

**Comment by xxx44yyy** [comment]
@joshuablackburn-iex What should I do? I spent money, and a quarter of the information was useless. It's like buying a truck and then discovering that the body is made of cardboard.

**Comment by McQgit** [comment]
@xxx44yyy To add color to Joshua's comment (mind you, I am not IEX): 

It is not unusual for api providers to use templates for financial reports.  Because of this, certain line items in the reports or certain kinds of businesses (financial companies, REITs, ...) may not fit the template and that data won't appear.  That is what is happening here on IEX /income endpoint.

When Joshua refers to the 'as reported' endpoint, I believe he is referring to their:
https://iexcloud.io/docs/api/#financials-as-reported

I have not played around with that but if it is a pure pass-thru of the SEC filings (via xbrl for example), it will get quite tedious for summary assessment of these reports.  The raw data will be there - but be prepared for lots of variance between companies.

**Comment by tmd2142** [comment]
> @joshuablackburn-iex What should I do? I spent money, and a quarter of the information was useless. It's like buying a truck and then discovering that the body is made of cardboard.

What Josh was referring to is that IEXcloud use a fixed template so some fields might be null if the data from their provider is not available. If you need more data, should probably check other services where they source their own data like [Finnhub stock api ](https://finnhub.io/)or providers on [Quandl](https://www.quandl.com/). 

Example to get 30 years of income statement for MA : [https://finnhub.io/api/v1/stock/financials?symbol=MA&statement=ic&freq=annual](https://finnhub.io/api/v1/stock/financials?symbol=MA&statement=ic&freq=annual)

**Comment by joshuablackburn-iex** [comment]
I would caution the use of Finnhub as we have found they are using our data and reselling it against our terms. If you just check their docs they even leave our urls in the examples.

**Comment by joshuablackburn-iex** [comment]
Also, all providers are pulling from the same source; public company filings. In that case we source the data ourselves as well. It’s worth noting that every provider can differ in how they calculate certain fields.

**Comment by xxx44yyy** [comment]
@joshuablackburn-iex Josh, I still don't know what to do. Did I buy the data for nothing? :)

**Comment by jesseorosz** [comment]
Try Quandl for financials.

**Comment by xxx44yyy** [comment]
@jesseorosz 
It's very expensive.

**Comment by jesseorosz** [comment]
@xxx44yyy $49/month and includes institutional and insider

it's actual way cheaper and higher quality than the provider IEX is using

**Comment by xxx44yyy** [comment]
@jesseorosz This is for personal use, not for commercial use.

**Comment by xxx44yyy** [comment]
> @joshuablackburn-iex Josh, I still don't know what to do. Did I buy the data for nothing? :)

@joshuablackburn-iex Josh?

**Comment by noam2** [comment]
check out www.spikeet.com . They have financial statements as well

**Comment by evancarter-iex** [comment]
This is fixed.
