### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by ARMDAT** [iexg/IEX-API#141]
## Summary

503 Service Unavailable

## Details
Command works in Google Chrome and Microsoft Edge. However, when using Indy 10.6 protocols for Delphi XE8 I keep getting the the 'Http 1.1 503 Service Unavailable' message. I have used Indy for other https commands for years so i know it supports HTTPS. 

Your documentation say, "We provide a valid, signed certificate for our API methods. Be sure your connection library supports HTTPS." Is there a certificate I should include or check for in the Indy code?

### Date/time of issue
Dec 14, 2017 noon 

### API URL
https://api.iextrading.com/1.0/stock/A/quote?format=csv

### What you expected to happen
I was hoping to download the info in a CSV file

### What actually happened
503 Error message 

### Other Information (sample code, links, etc.)
idHTTP1.Get(https://api.iextrading.com/1.0/stock/A/quote?format=csv', AStream);  //where AStream is previously created and should contain the information. However it returns NIL

**Comment by evancarter-iex** [comment]
Please make sure your client libraries support SNI https://en.wikipedia.org/wiki/Server_Name_Indication
