### ISSUE TITLE
Pe ratio and market capitalisation missing for UK stocks

### ISSUE THREAD

**Issue by Eeedgar** [iexg/IEX-API#1410]
Hello IEX team - great tool thanks!

I'm starting to work with international data and e.g. tried today to explore the UK market.  For the UK stocks, key fundamentals are missing from the stats API call - try for example: https://cloud.iexapis.com/stable/stock/lgen-ln/stats?token=

Is this due to availability?  Or another reason?  I'd be particularly interested in the beta, PE ratio, dividend yield, market capitalisation and earnings per share.

If it helps I'm using Chrome on a Windows desktop machine.

Cheers
Ed

**Comment by tmd2142** [comment]
My understanding is that IEXcloud doesn not support fundamental data for international market yet.
![image](https://user-images.githubusercontent.com/25411382/75080475-13cc9600-54da-11ea-92c1-58295367d1fd.png)

You can check out other services like [Finnhub stock API](https://finnhub.io/docs/api) where they have global coverage for PE ratio, beta, market cap, earnings v.v.

**Comment by joshuablackburn-iex** [comment]
I would caution the use of Finnhub as they are pulling our data and reselling against our terms. This may suggest data is not being properly sourced.

**Comment by Eeedgar** [comment]
Thanks both!  I'll add my vote to the roadmap and well noted on Finnhub.

**Comment by ShillSeeker2020** [comment]
Found you shilling, again.  Is there no end to FinnHub's shilling?

tmd2142 is Tri Minh Do, one of Finnhub's founders.

More shilling on Github by two Finnhub people here:
https://github.com/piquette/finance-go/issues/14
https://www.reddit.com/r/algotrading/comments/in5u6x/beware_medium_guide_stock_market_apis_for_2020/
