### ISSUE TITLE
Chart Max only returns 5 years of Data

### ISSUE THREAD

**Issue by drewbutcher** [iexg/IEX-API#1411]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**
When I request max chart data for AAPL I only receive 5 years of data instead of 15.

**What time did the problem occur? (with timezone)**
Feb 23, 2020 EST

**What is the expected behavior?**
15 years of data returned

**Your environment (e.g. browser, OS, API version, language):**
Chrome Browser

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/stock/aapl/chart/max?token=Tsk_c979fbb830a611e9958142010a80043c

**What are the steps to reproduce the bug?**
Click the API URL

**Additional context**
Thank you for any assistance and your time.

**Comment by joshuablackburn-iex** [comment]
15 years of data is only available to paid accounts.
