### ISSUE TITLE
[Data] Many Price Targets are incorrect - no way to discern what is USD or local currency

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1412]
**Clearly describe the problem**
The Price Target end point reports Price Targets in their local currency. This would not be an issue however there is no field that states what currency the field is being reported in. If there was I could do the conversion myself.

**What time did the problem occur? (with timezone)**
24-7

**What is the expected behavior?**
Either one of the following:
1. Numbers all reported in USD
2. A field is added that states which currency is being reported

**Your environment (e.g. browser, OS, API version, language):**
Chrome, .NET

**API URL (if applicable)**
stock/{symbol}/price-target

**What are the steps to reproduce the bug?**
run API for BABA

**Additional context**
This has been an issue for at least seven months. Yet we're still being charged for the API calls which return bad data and the end point is still active. It's frustrating seeing so many new data sets being added yet the existing issues not being resolved. With financial data it's quality not quantity of data, and it would be nice to see IEX concentrate on quality.

**Comment by joshuablackburn-iex** [comment]
Resolved

**Comment by rada-it** [comment]
Excuse me for writing in this old issue.
I´m using the API and getting data from different symbols of different exchanges.

Wenn i try to get the symbols https://cloud.iexapis.com/stable/ref-data/exchange/FRA/symbols?token=xxx i get the full list of all symbols with the currency. >> Here for **AHLA-GF** the currency is **USD**
But when i request the price for the symbols (for example: **AHLA-GF** for the **Alibaba Share** in **XETRA**) i get the price in **Euro**. 
Is the price always the price of the requested Exchange Location? ( Xetra = EUR = German Exchange, NYSE = USD = US exchange)?
Found nothing in the documentation...
