### ISSUE TITLE
[Data] Chart endpoint not providing values for some stocks on date 2020-02-24

### ISSUE THREAD

**Issue by evdubs** [iexg/IEX-API#1413]
**Clearly describe the data problem**
Despite being well after 4 AM ET on Feb 25, 2020, the open, high, low, close, and volume values for the previous day are incomplete. 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/batch?symbols=A,AAMC&types=chart&range=date&exactDate=20200224&chartByDay=true

**What time did the problem occur (including timezone)?**
2020-02-25 18:00 ET

**What is the expected behavior?**
The expected behavior is that close to all symbols return OHLCV values. This usually ends up being ~25 kB of JSON returned for each call of 100 stocks. It is currently returning just ~20 kB for symbols A - ADX.

**What are the steps to reproduce**
Call the URL above and look at JSON output.

**Your environment (e.g. browser, OS, API version, language):**
Ubuntu 19.10; "stable" API version; Racket language

**Additional context**
I expect that this will eventually just work. I just want to point this out in case there is something simple that can be done to help ensure chart data availability as close to 4 AM ET as possible. I hope we can continue to rely on IEX's API as a great, high-quality service for retail investors.

**Comment by evdubs** [comment]
Update: as of 2020-02-26 05:00:00 ET, I can get values for nearly all stocks for Feb 25, but I still only get values for around 80% of stocks for Feb 24.

**Comment by evdubs** [comment]
Update: as of 2020-02-26 18:30:00 ET, Feb 24 data seems mostly complete.

**Comment by JimLynchCodes** [comment]
Can someone from iex please confirm- is it expected that OHLCV data takes a full two days to become available??

This seems kind of absurd given that the intraday data is realtime... 🤔
