### ISSUE TITLE
/ref-data/symbols endpoint only returns crypto symbols

### ISSUE THREAD

**Issue by danlinenberg** [iexg/IEX-API#1414]
This is the response from said endpoint :
`[
    {
        "symbol": "BTCUSDT",
        "name": "Bitcoin USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000000
    },
    {
        "symbol": "EOSUSDT",
        "name": "EOS USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000001
    },
    {
        "symbol": "ETHUSDT",
        "name": "Ethereum USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000002
    },
    {
        "symbol": "BNBUSDT",
        "name": "Binance Coin USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000003
    },
    {
        "symbol": "ONTUSDT",
        "name": "Ontology USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000004
    },
    {
        "symbol": "BCCUSDT",
        "name": "Bitcoin Cash USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000005
    },
    {
        "symbol": "ADAUSDT",
        "name": "Cardano USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000006
    },
    {
        "symbol": "XRPUSDT",
        "name": "Ripple USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000007
    },
    {
        "symbol": "TUSDUSDT",
        "name": "TrueUSD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000008
    },
    {
        "symbol": "TRXUSDT",
        "name": "TRON USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000009
    },
    {
        "symbol": "LTCUSDT",
        "name": "Litecoin USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000010
    },
    {
        "symbol": "ETCUSDT",
        "name": "Ethereum Classic USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000011
    },
    {
        "symbol": "IOTAUSDT",
        "name": "MIOTA USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000012
    },
    {
        "symbol": "ICXUSDT",
        "name": "ICON USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000013
    },
    {
        "symbol": "NEOUSDT",
        "name": "NEO USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000014
    },
    {
        "symbol": "VENUSDT",
        "name": "VeChain USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000015
    },
    {
        "symbol": "XLMUSDT",
        "name": "Stellar Lumens USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000016
    },
    {
        "symbol": "QTUMUSDT",
        "name": "Qtum USD",
        "date": "2020-02-28",
        "isEnabled": true,
        "type": "crypto",
        "iexId": 10000017
    }
]`

It used to gives thousands of tickers, now only 18 crypto symbols...
It started today at around 3PM GMT.

**Comment by evancarter-iex** [comment]
@danlinenberg This should be resolved now.
