### ISSUE TITLE
[Data] Documentation issue in basic dividends

### ISSUE THREAD

**Issue by AndreHaueisen** [iexg/IEX-API#1418]
**Clearly describe the data problem**

The documentation says this is the result to expect
```
 {
        "symbol": "AAPL",
        "exDate": "2017-08-10",
        "paymentDate": "2017-08-17",
        "recordDate": "2017-08-14",
        "declaredDate": "2017-08-01",
        "amount": 0.63,
        "flag": "Dividend income",
        "currency": "USD",
        "description": "Apple declares dividend of .63",
        "frequency": "quarterly"
}
```

In reality, we are getting this

```
 {
        "exDate": "2017-08-10",
        "paymentDate": "2017-08-17",
        "recordDate": "2017-08-14",
        "declaredDate": "2017-08-01",
        "amount": 0.63,
        "flag": "Dividend income",
        "currency": "USD",
        "description": "Apple declares dividend of .63",
        "frequency": "quarterly"
}
```

**Data URL (The URL you used to access the data without your token):**

This URL is given in the example.
https://sandbox.iexapis.com/stable/stock/aapl/dividends/5y

The documentation should be edited to represent the actual response

**Comment by McQgit** [comment]
@AndreHaueisen This has been reported before and has remained as you describe.  An alternative is to use a batch request which will return the symbol.  See: https://github.com/iexg/IEX-API/issues/1253#issuecomment-532951418

**Comment by AndreHaueisen** [comment]
Thanks @McQgit 
I will edit this as a documentation issue then.
