### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by jimhoranjr** [iexg/IEX-API#142]
## Summary
When I use the following call in a browser it updates with new information each time I refresh the browser
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote&filter=symbol,latestPrice,latestTime

When I use the same string in a xmlhttp get request it gives me current data the first time but subsequent calls return the exact same data 

I'm sure I'm missing something very basic. 
Thanks

### Date/time of issue

12/14/17 

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote&filter=symbol,latestPrice,latestTime

### What you expected to happen
I expected a new price and time 

### What actually happened
I got back the same price and time from my 1st request on all subsequent requests
I set x = to the responsestext  and it doesn't change

### Other Information (sample code, links, etc.)
My Code to request data 

 Sub Price_from_IEX3()
  
  'take line from browser to get 2 stocks price an time
  
    Dim xmlhttp As New MSXML2.XMLHTTP60
    
    Dim ws As Worksheet
    
    
    Set ws = Sheets("IEXWorksheet")
    
    test4URL = "https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote&filter=symbol,latestPrice,latestTime"
      
    With xmlhttp
        .Open "get", test4URL, True
        .send

        x = .ResponseText
    End With
    
    ws.Range("A1") = x
    
    ws.Select
    Range("A1").Select
    Selection.TextToColumns Destination:=Range("A5"), DataType:=xlDelimited, _
        TextQualifier:=xlDoubleQuote, ConsecutiveDelimiter:=True, Tab:=False, _
        Semicolon:=False, comma:=True, Space:=False, Other:=True, OtherChar:= _
        ":", FieldInfo:=Array(Array(1, 1), Array(2, 1), Array(3, 1), Array(4, 1), Array(5, 1), _
        Array(6, 1), Array(7, 1), Array(8, 1), Array(9, 1)), TrailingMinusNumbers:=True
        
End Sub

**Comment by joshuablackburn-iex** [comment]
Can you tell us what time you are making the request?

**Comment by joshuablackburn-iex** [comment]
Additionally, the data will not always update on each request.  It depends on when the next trade occurs before the price updates.

**Comment by jimhoranjr** [comment]
Doesn't seem to matter when. Ive tried all the the day while markets are open .  Seems symbol as I tried different active issues . GE, IBM, AAPL

**Comment by jcape** [comment]
Here's what I got running this just now:

`{"GE":{"quote":{"symbol":"GE","latestPrice":17.505,"latestTime":"3:59:54 PM"}},"IBM":{"quote":{"symbol":"IBM","latestPrice":152.53,"latestTime":"3:59:59 PM"}},"AAPL":{"quote":{"symbol":"AAPL","latestPrice":175.05,"latestTime":"3:59:59 PM"}}}`

What does your side show?

**Comment by jimhoranjr** [comment]
Sorry I was a bit slow 

{"GE":{"quote":{"symbol":"GE","latestPrice":17.5,"latestTime":"December   22, 2017"}
--
IBM":{"quote":{"symbol":"IBM","latestPrice":152.5,"latestTime":"December   22, 2017"}
AAPL":{"quote":{"symbol":"AAPL","latestPrice":175.01,"latestTime":"December   22, 2017"}}}
My problem is not getting the data on the first request . It's that I get the same data on each subsequent request . 
This will have to wait till next week as market is closed.  Have a good Holiday

**Comment by jcape** [comment]
Not to put too fine a point on it, but if you get new data on the first request your application makes after it starts, but dupe/replay data on all subsequent requests, that is almost certainly a problem with your application.

Have you tried updating `ws.Range` after you set `x` to the responsetext?

**Comment by jimhoranjr** [comment]
I thought I'd looked at that but worth another try . Let you know when we reopen

**Comment by jcape** [comment]
@jimhoranjr We're open now.

**Comment by jimhoranjr** [comment]
first run worked fine as usual will be back shortly

**Comment by jimhoranjr** [comment]
No still no update 
I had added the lines
Application.Calculation = xlCalculationAutomatic
Application.ScreenUpdating = True
Application.EnableEvents = True
to the above code after the Dim statements to make sure  things were updating 
but no luck. Any Thoughts ?
Thanks

**Comment by jimhoranjr** [comment]
So updated code using current 3 symbols looks like this

Dim xmlhttp As New MSXML2.XMLHTTP60
Dim ws As Worksheet
Dim Data() As String

Application.Calculation = xlCalculationAutomatic
Application.ScreenUpdating = True
Application.EnableEvents = True

Set ws = Sheets("IEXWorksheet")

test4URL = "https://api.iextrading.com/1.0/stock/market/batch?symbols=GE,IBM,AAPL&types=quote&filter=symbol,latestPrice,latestTime"

ws.Range("B10:B12").ClearContents

       
            With xmlhttp
                 
                .Open "GET", test4URL, False
                .send
            
                x = .ResponseText
                y = .Status
             End With
                
        Data() = Split(x, "}," & Chr(34))
        
        For i = 0 To UBound(Data)
        Sheets("IEXWorksheet").Range("A10").Offset(i, 0) = Data(i)
        Next i

**Comment by jimhoranjr** [comment]
I added code to set all variables to null and noted the get response status in A9 still not updating . 
Do you still think in is something on my side? If so I'd really appreciate any thoughts on where to start.

New code is below.
Thanks

Sub Price_from_IEX4()


Dim xmlhttp As New MSXML2.XMLHTTP60
Dim ws As Worksheet
Dim Data() As String

Application.Calculation = xlCalculationAutomatic
Application.ScreenUpdating = True
Application.EnableEvents = True

Set ws = Sheets("IEXWorksheet")

test4URL = "https://api.iextrading.com/1.0/stock/market/batch?symbols=GE,IBM,AAPL&types=quote&filter=symbol,latestPrice,latestTime"
x = ""
Erase Data()
ws.Range("A10:A12").ClearContents

       
            With xmlhttp
                 
                .Open "GET", test4URL, False
                .send
            
                x = .ResponseText
                y = .Status
             End With
                
        Data() = Split(x, "}," & Chr(34))
        
        For i = 0 To UBound(Data)
        Sheets("IEXWorksheet").Range("A10").Offset(i, 0) = Data(i)
        Next i
        
        Sheets("IEXWorksheet").Range("A9") = y
        
End Sub

**Comment by jimhoranjr** [comment]
May have just figured it out . I added 
.SetRequestHeader "If-Modified-Since", "Sat, 1 Jan 2000 00:00:00 GMT"
after .open  line
and it returned the close . I'll give it a shot in the morning and let you know. 

Knowledge from 
https://stackoverflow.com/questions/11620747/excel-vba-rest-wcf-works-on-1st-call-but-subsequent-calls-return-cached-non-cu

**Comment by jimhoranjr** [comment]
That seems to have solved the problem. I now am getting updates .  Thanks for your time and help.
