### ISSUE TITLE
[Request] Allow for minute/configurable resolution for a date range

### ISSUE THREAD

**Issue by jrnt30** [iexg/IEX-API#1420]
**Is your feature request related to a problem? Please describe.** 
We are looking to provide our applications the ability to pull chart data for a configurable set of time ranges.  

One of the features we are providing is the ability to see fairly granular data for the past week, up to *and including* today.  With the current API this seems to necessitate two distinct calls without providing the ability to customize our date range very directly.

**Describe the solution you'd like**
Ideally we would be able to use the `intraday-prices` endpoint with a more arbitrary start day so we could pull back the data for the past N days including today while preserving the `chartInterval` option.

**Describe alternatives you've considered**
Making a batch call to the `stock/:symbol/chart/5dm` endpoint and the `intraday-prices` endpoint and combining the results together.

**Additional context**

**Comment by timpaine-iex** [comment]
https://github.com/iexg/IEX-API/issues/221
