### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by arunkatti** [iexg/IEX-API#1421]
**Clearly describe the data problem**
Getting erroneous values for parameter: "beta". Using the simplified query below, I had gotten the right values yesterday, but am getting an extremely low value today.

The response seemed to provide correct value of beta yesterday (around 1.08), but the same query today is producing a really low values of 0.013 for FB stock, which is wrong)
{"FB":{"stats":{"beta":0.013202227179838644}}}

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?types=stats&last=1&filter=symbol,beta&symbols=FB,371753&&token=mytokenhere

**What time did the problem occur (including timezone)?**
4:00 PM EST on March 3, 2020

**What is the expected behavior?**
The beta value returned should be around 1.08 (instead of what is being returned today, which is 0.13).

**What are the steps to reproduce**
Run the provided URL with an appropriate token

**Your environment (e.g. browser, OS, API version, language):**
Edge or Chrome brownser on Windows 10, version 1.0 

**Additional context**

**Comment by joshuablackburn-iex** [comment]
This seemed to be temporary and related to an erroneous shares outstanding update from upstream. Closing this issue, but reopen if the issue continues.
