### ISSUE TITLE
[Data] Cant't seem to find swap rates?

### ISSUE THREAD

**Issue by gjvdkamp** [iexg/IEX-API#1422]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
I'm looking for the deposit and swap rates like in these links:
https://www.iex.nl/Koersen/Rentes/Interest_Rate_Swaps/compactlist.aspx
https://www.iex.nl/Koersen/Rentes/Euro_Deposite_Rates/compactlist.aspx

Are they on the API? 

**Data URL (The URL you used to access the data without your token):**

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by gjvdkamp** [comment]
Wait haha I found iexcloud by googling 'iex api' but I'm starting to suspect you're a different outfit form iex.nl?

**Comment by joshuablackburn-iex** [comment]
Correct. We are part of IEX Group in the U.S. which operates the US stock exchange IEX.  https://iextrading.com/about/
