### ISSUE TITLE
Sandbox call from Python

### ISSUE THREAD

**Issue by mlapenna7** [iexg/IEX-API#1423]
I like the concept of the Sandbox, especially to test out use cases.  SO I thought I would give it a try  but I have an issue right off the bat.

From python, I have a simple one stock call:

imports ...
aapl = Stock("AAPL",token='Tpk_....')
print( aapl.get_company() )

Here's the result:
...
  File "C:\Users\7mlap\AppData\Roaming\Python\Python36\site-packages\iexfinance\base.py", line 178, in _handle_error
    raise IEXQueryError("The query could not be completed. "
iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.

Other things to note:
1) I can use the sandbox successfully from the URL call (this works):
https://sandbox.iexapis.com/stable/stock/aapl/quote?token=Tpk_...
2) I can retrieve AAPL succesfully from Python when I use the PROD token (which is set in environment variable IEX_TOKEN)
3) For the sandbox python call, I even unset the environment variable IEX_TOKEN (which was set to the PROD token), thinking it might be interfering with the Sandbox call.

Can anyone suggest other things for me to check or change?

**Comment by McQgit** [comment]
@mlapenna7 A number of people struggle using that iexfinance python app.  It was not developed (and not supported by) the IEX folks.  See this prior topic for where to find help for iexfinance: https://github.com/iexg/IEX-API/issues/1257

**Comment by mlapenna7** [comment]
McQgit Thanks for your note. I'll do a little more digging and I looked at your reference link.  It is important for everyone to note that the python API was NOT provided by IEX folks.
