### ISSUE TITLE
[Request] More fundamental historical data (Balance sheet, cash flow, income statement)

### ISSUE THREAD

**Issue by amittleider** [iexg/IEX-API#1424]
**Describe the solution you'd like**
Currently we can pull 4 years of annual statements or 12 quarters of statements for fundamentals (balance sheet, cash flow, income statement). We would like to have quarterly data for at least 10 years.

**Describe alternatives you've considered**
There are a few other providers that are offering this. Their start-up fees are a bit more expensive than IEXs though.
https://finnhub.io/docs/api#financials
https://polygon.io/

**Additional context**
Overall, very happy with IEX data and support. Thanks

**Comment by simmyaziz81** [comment]
Any update on this. I would also like 10 years of fundamentals data (balance sheet, cash flow, income statement). 

Is this planned?

**Comment by VldChk** [comment]
Any follow up here?
