### ISSUE TITLE
/stock/[stock]/chart/date/[date] returns empty dataset

### ISSUE THREAD

**Issue by aupilot** [iexg/IEX-API#1427]
Hi,

Requests like the one below work well for recent data, but return empty dataset for older days. 
https://sandbox.iexapis.com/stable/stock/twtr/chart/date/20191220?token=Tsk_e5e4f26dc6c94e4f86783f410dd05953

For example, the request below (taken from your API docs) returns empty set.
https://sandbox.iexapis.com/stable/stock/twtr/chart/date/20190220?token=Tsk_e5e4f26dc6c94e4f86783f410dd05953

Same story with a real non-sandbox token. So, is there any way to get access to earlier data?
That's the reason I wanted to use IEX Cloud...

Cheers,
Kir

**Comment by joshuablackburn-iex** [comment]
We need to update our docs, but intraday minute bar data is only available back to April 2019.

**Comment by aupilot** [comment]
Is it kinda politics or technical isue?

**Comment by noam2** [comment]
check www.spikeet.com

**Comment by ol-lo** [comment]
> We need to update our docs, but intraday minute bar data is only available back to April 2019.

Is it a temporary issue or IEX does not provide such data at all?  

Thanks
