### ISSUE TITLE
[Data] API question (intraday prices)

### ISSUE THREAD

**Issue by CAPFinance** [iexg/IEX-API#1428]
Hello,  We have a question regarding your API. Specifically, the data weighting section with regard to the intraday prices. It states that API users have "1 per symbol per time interval with a max of 50 messages." What does this statement mean exactly? Are we allowed to take 50 requests per day, and does 1 request include ALL the data points listed from date going down to change over time? Or does it mean we get 50 data points in each request? For example, a data point would be "marketClose" and/or "marketHigh"

**Comment by evancarter-iex** [comment]
If you are having an issue please reach out to support@iexcloud.io for the answer on this questin.

**Comment by timpaine-iex** [comment]
@CAPFinance each object in the array costs 1 message, e.g.

<img width="455" alt="Screen Shot 2020-12-28 at 10 05 36 AM" src="https://user-images.githubusercontent.com/74613173/103223428-3bf40500-48f4-11eb-8201-7719e3b0f1c5.png">

in the above example, the inner object costs 1. If you request 90 minutes of data, you will get back up to 90 objects, but you will only pay a max of 50 messages. So its basically 1 message per object returned up to a max of 50.

So if I request some data and its like:

```
[
 {...},
 {...},
 {...},
]
```

I will pay `3` messages. If I get 

```
[
 {...},
 ...49 more
]
```

I will pay `50` messages. 


If I get 

```
[
 {...},
  ...100 more
]
```

I will still pay `50` messages
