### ISSUE TITLE
[Data] ValueError: If using all scalar values, you must pass an index

### ISSUE THREAD

**Issue by ZeliangSu** [iexg/IEX-API#1429]
**Clearly describe the data problem**

> ValueError: If using all scalar values, you must pass an index
while using

`pd.read_json('https://cloud.iexapis.com/stable/stock/aapl/stats?token={}'.format(my_token))`

**Data URL (The URL you used to access the data without your token):**
While I'm trying to get key stats from the cloud. Apparently, it might be the python's library pandas that couldn't parse your data 
https://cloud.iexapis.com/stable/stock/aapl/stats?token={}'.format(my_token)

**What time did the problem occur (including timezone)?**
When withdrawing key stats from Cloud

**What is the expected behavior?**
A dictionary or a pandas.DataFrame 
Comparing with other data that can be successfully read by pandas, the **only difference of 'key stats' is without the brackets [ ]** (when I check with the sandbox)

**e.g. with chart/1y:**

> [{"date":"2020-02-21","open":38.77,"close":39.78,"high":39.05,"low":39.31,"volume":15931989,"uOpen":39.04,"uClose":39.58,"uHigh":39.71,"uLow":39.65,"uVolume":15749364,"change":0,"changePercent":0,"label":"....,"change":2.14,"changePercent":9.7211,"label":"Mar 19","changeOverTime":-0.379304},{"date":"2020-03-20","open":25.9,"close":24.6,"high":26.6,"low":24.4,"volume":28816116,"uOpen":25.51,"uClose":25,"uHigh":26.08,"uLow":24.2,"uVolume":29610963,"change":-0.18,"changePercent":-0.777,"label":"Mar 20","changeOverTime":-0.377006}]

**whereas e.g. with stats:**

> {"week52change":0.179631,"week52high":340.1,"week52low":178.26,"marketcap":1023207528810,"employees":137597,"day200MovingAvg":258.5,"day50MovingAvg":301.9,"float":4427374189,"avg10Volume":82601370.7,"avg30Volume":58718949.34,"ttmEPS":12.8187,"ttmDividendRate":3.08,"companyName":"Apple, Inc.","sharesOutstanding":4504233078,"maxChangePercent":230.911,"year5ChangePercent":0.8513,"year2ChangePercent":0.3103,"year1ChangePercent":0.229,"ytdChangePercent":-0.2342,"month6ChangePercent":0.0553,"month3ChangePercent":-0.1883,"month1ChangePercent":-0.2971,"day30ChangePercent":-0.2885,"day5ChangePercent":-0.0546,"nextDividendDate":null,"dividendYield":0.013511316031747734,"nextEarningsDate":"2020-05-15","exDividendDate":"2020-02-13","peRatio":18.27,"beta":1.261314134799162}

**What are the steps to reproduce**
As simple as
```
import pandas as pd
pd.read_json('https://cloud.iexapis.com/stable/stock/aapl/stats?token={}'.format(my_token))
```

**Your environment (e.g. browser, OS, API version, language):**
Python 3.6
Pandas 1.0.1

**Additional context**
The full Traceback:
Traceback (most recent call last):
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-390b363c7c52>", line 1, in <module>
    pd.read_json('https://cloud.iexapis.com/stable/stock/aapl/stats?token=pk_80c82b2e43e1491ea4a29d6d5ab54dde')
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/util/_decorators.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/io/json/_json.py", line 608, in read_json
    result = json_reader.read()
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/io/json/_json.py", line 731, in read
    obj = self._get_object_parser(self.data)
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/io/json/_json.py", line 753, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/io/json/_json.py", line 857, in parse
    self._parse_no_numpy()
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/io/json/_json.py", line 1089, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
    index = extract_index(arrays)
  File "~/anaconda3/envs/iex/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 355, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")

**Comment by ZeliangSu** [comment]
Same problem is present with `quote`

**Comment by ZeliangSu** [comment]
A manuel solution can get around this:

```
import urllib.request as request
import json as js

with request.urlopen() as response:
     binary = response.read()
     data = js.loads(binary.decode('utf-8'))
```

**Comment by linehammer** [comment]
This [machine learning](http://net-informations.com/ds/iq/mliq.htm) error message says pandas DataFrame needs an index. While pandas create data frame from a dictionary, it is expecting its value to be a list or dict. If you give it a scalar , you'll also need to supply index. What this is essentially asking for is a column number for each dictionary items. You can solve this issue by using the following methods:

```
x = 100
y = 200
df = pd.DataFrame({'X': [x], 'Y': [y]}) //adding values inside squire brackets
```

Or

`df = pd.DataFrame({'X': x, 'Y': y}, index=[0]) //pass index value`
