### ISSUE TITLE
Question about mutual fund data

### ISSUE THREAD

**Issue by moonlitSpider** [iexg/IEX-API#1430]
Hello,

I am unable to find via the IEX-Cloud APIs specific mutual funds in which I am interested. These are:

- VDIGX
- VBILX
- VPMAX
- VWENX

Questions:

1. Why are these not among your mutualFundSymbols interface (in fact, there are no occurrences of "vanguard" in that data)?
2. How can I get end of day closing prices for mutual funds?

Thank you.

**Comment by McQgit** [comment]
@moonlitSpider I see VDIGX pricing and in the ref-data for mutual fund symbols.  I also see VFINX but didn't check your others.

https://cloud.iexapis.com/v1/ref-data/mutual-funds/symbols?token=(token)

Pricing:
https://cloud.iexapis.com/v1/stock/market/batch?symbols=vfinx,vdigx&types=quote&token=(token)
OR
https://cloud.iexapis.com/v1/stock/market/batch?symbols=vfinx,vdigx&types=previous&token=(token)

I don't know why you didn't see it in ref-data.  If you were using the sandbox some of the data is randomized so maybe the names don't show Vanguard?  I'm guessing.  Try testing small bits outside of the sandbox first.

**Comment by moonlitSpider** [comment]
@McQgit thank you for your most helpful answer. 

Using Postman I was able to to successfully use the URLs you provided. And this prompted me to look again at the software program I am developing where I found my error.

Thank you again for your clear and quick reply.
