### ISSUE TITLE
[Request] Get a list of symbols per index and/or exchange?

### ISSUE THREAD

**Issue by mj-fintech** [iexg/IEX-API#1432]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Is your feature request related to a problem? Please describe.**
No there is no problem. I was looking for this in the documentation but haven't found it yet. So I figured I may want to ask it here.

**Describe the solution you'd like**
I would like to call a request that would return a list of symbols in a particular index or exchange. 
for example:
In: https://cloud.iexapis.com/stable/lookup/sp500/list?token=mytoken
Out: {'A', 'AA', 'AAPL', etc.. all the symbols of the company that are listed in s&p 500 index}

In: https://cloud.iexapis.com/stable/lookup/nyse/list?token=mytoken
Out: {'A', 'AA', 'AAPL', etc.. all the symbols of the company that are listed in nyse}

**Describe alternatives you've considered**

**Additional context**
Please let me know if there is any already available solution that can achieve this at one request.

**Comment by antoinesaliba** [comment]
I'd love to see this feature added

**Comment by timpaine-iex** [comment]
exchange is supported, index constituents are being actively sourced
