### ISSUE TITLE
[Data] duplicate close prices returned from /stock/<symbol>/chart/5y

### ISSUE THREAD

**Issue by f2calv** [iexg/IEX-API#1433]
**Clearly describe the data problem**
It seems 2020-03-27 is a key date for these issues. Requesting close prices for securities returns multiple identical or non-identical price objects for the same date (2020-03-27);
- PURE-H-CV returns multiple identical objects on date 2020-03-27
![image](https://user-images.githubusercontent.com/16097639/78052546-91a87a80-737f-11ea-8a4d-777dfe0c8918.png)
- CARR# returns multiple non-identical objects on date 2020-03-27
![image](https://user-images.githubusercontent.com/16097639/78099252-9736ac80-73e1-11ea-9f1f-427052152f90.png)

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/PURE-H-CV/chart/5y?token=[token]&chartCloseOnly=true
https://cloud.iexapis.com/stable/stock/CARR%23/chart/5y?token=[token]&chartCloseOnly=true

**What is the expected behavior?**
This endpoint should only *ever* return 1 price object per date.
Note: the given symbols aren't the only ones to exhibit the problem, so any fix/check should be applied to all symbols not just the example given.
IMO there should be a unique database key on Symbol+Date.

**What are the steps to reproduce**
Hit the above URLs with a working access token.

The following symbols are affected with duplicated data - but there may be others on top;

- CARR#
- DFNS
- OTIS#
- AITXD
- AMOSF
- BRTXQ
- ERGZF
- HMFAF
- HZBBD
- HZBRD
- HZOZD
- HZRZD
- IMCUF
- INAPQ
- LFERD
- LGMFD
- MDRSF
- PFFEF
- PITAF
- PVLTF
- SFBQF
- SGSPF
- SHRMF
- SILEF
- TKAYY
- TRNF
- TSVNF
- ULURD

**Comment by evancarter-iex** [comment]
Fixed.
