### ISSUE TITLE
NEED HELP TO CLOSE THE  IEXCLOUD ACCOUNT 

### ISSUE THREAD

**Issue by Chr728** [iexg/IEX-API#1434]
Hello,I have an account with the iexcloud.io  and I want to completely close and cancel my account how can I do that ?

Christina.

**Comment by McQgit** [comment]
@Chr728 After I logon, I see a "Cancel Your Plan" button on the bottom of this page:
https://iexcloud.io/console/manage-plan

**Comment by Chr728** [comment]
I dont see any " cancel your plan " botton.
There is nothing !!!

**Comment by McQgit** [comment]
@Chr728  Then I suggest you email support.

**Comment by KAWDUP** [comment]
With a Free account you have no e-mail support.  Again, the question is - How do you cancel your free account?  There is no damn "cancel your plan" button.  What is going on here?

**Comment by Chr728** [comment]
This case was resolved by someone else!  so you can close the case !

Christina

**Comment by KAWDUP** [comment]
Resolved HOW?

**Comment by KAWDUP** [comment]
Without E-mail support - we are supposed to do what exactly?

**Comment by joshuablackburn-iex** [comment]
Just email support and let us know you want your account deleted.
