### ISSUE TITLE
[Issue] ISIN endpoint returns 400 error

### ISSUE THREAD

**Issue by Spomky** [iexg/IEX-API#1435]
**Clearly describe the problem**
I always receive error 400 Bad Request when trying to get symbols using the ISIN code.

**What time did the problem occur? (with timezone)**
With the sandbox and the same request body, I can get symbols using ISINs and the `/ref-data/isin` endpoint.
Until yesterday, it worked great also on the production endpoint.

**What is the expected behavior?**
Get the symbols using the ISIN codes

**Your environment (e.g. browser, OS, API version, language):**
GEROKU server

**API URL (if applicable)**

**What are the steps to reproduce the bug?**

Works fine
```
POST /v1/ref-data/isin HTTP/1.1
Host: sandbox.iexapis.com
Content-Type: application/json

{"token":"**SANDBOX TOKEN HERE**","isin":["US0378331005"]}
```

Does not work
```
POST /v1/ref-data/isin HTTP/1.1
Host: could.iexapis.com
Content-Type: application/json

{"token":"**PRODUCTION TOKEN HERE**","isin":["US0378331005"]}
```

**Additional context**

**Comment by timkou-iex** [comment]
Hi there,

It seems like there is currently an issue with POST functionality for this endpoint. We're working on a fix.
For now, please try using a GET request and adding the ISINs as parameters: https://cloud.iexapis.com/stable/ref-data/isin?token={token}&isin={ISIN}
 
Tim

**Comment by philippschladitz** [comment]
@timkou-iex regarding this endpoint the GET also only returns 404's for me. Also is the documentation for the isin endpoint gone?

**Comment by timpaine-iex** [comment]
this endpoint is restored
