### ISSUE TITLE
[Data] Fx rate incorrect for USD to USD

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1437]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
Calling the FX endpoint returns incorrect rate for same currency conversions.

[{"symbol":"USDUSD","rate":230.92,"timestamp":1585842245000,"isDerived":false}]

Should return a rate of 1

Also does this for other conversions: EUREUR, CADCAD

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/fx/latest?symbols=USDUSD&token=

**What time did the problem occur (including timezone)?**
April 2 2020 9:10AM PST

**What is the expected behavior?**
Returns 1 

**What are the steps to reproduce**
Run API

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Win 10, .NET

**Additional context**

**Comment by jesseorosz** [comment]
Has this been changed?

I'm seeing "An unknown error has occurred" when making this call now.

**Comment by jesseorosz** [comment]
It appears that it was changed on either April 2 or 3

**Comment by joshuablackburn-iex** [comment]
Resolved.
