### ISSUE TITLE
[Request] Hex Codes.

### ISSUE THREAD

**Issue by seanwatters** [iexg/IEX-API#1439]
**Describe the solution you'd like**

It would be really cool if at some point, a "primaryHexCode" attribute could be added to the Company Profile response. 

i.e 

```
GET /stock/APPL/company
```

Response includes:
```
{
  "symbol": "AAPL",
  "companyName": "Apple Inc.",
  ...,
  primaryHexCode: "#000000"
}
```

I don't know if this is a feature anyone besides me would use, but for a project I am working on currently, I am having to predefine all of the hex codes for each symbol on some styled graphs and it would be awesome to have it in the Company Profile response.

**Comment by timpaine-iex** [comment]
I agree this would be a super cool thing to have, but I can almost guarantee no provider has this data. Might be a good idea for a startup if you're interested in starting a financial data company.
