### ISSUE TITLE
Change and Change Percentage are missing for OTIS,RTX, CARR

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#1442]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**

Change and Change Percentage are missing for OTIS, RTX, CARR. Those three symbols are spin offs from United Technologies recently. They are listed in NYSE.
Here are the some of the lines from API

previousClose	null
previousVolume	null
change	null
changePercent	null

**What time did the problem occur? (with timezone)**

During the market trading time (EST)

**What is the expected behavior?**
API should show current price, change and change percentage. 

**Your environment (e.g. browser, OS, API version, language):**
https://cloud.iexapis.com/stable

**API URL (if applicable)**
/stock/RTX/quote/

**What are the steps to reproduce the bug?**
https://cloud.iexapis.com/stable/stock/market/batch?symbols=RTX,OTIS,CARR&types=quote&token=?

**Additional context**

**Comment by evancarter-iex** [comment]
Fixed.
