### ISSUE TITLE
Sandbox not working [Issue]

### ISSUE THREAD

**Issue by fridary** [iexg/IEX-API#1446]
I want to use iexcloud, but how can I pay money to you if I can't just test sandbox.
On my account dashboard I turned on sandbox button. When I enter this page:
https://sandbox.iexapis.com/stable/stock/IBM/financials?token=my_token&period=annual
I have error "Production tokens cannot be used in the sandbox environment. Please use https://cloud.iexapis.com"

What to do?

**Comment by McQgit** [comment]
@fridary  Have you reviewed this topic?  https://iexcloud.io/docs/api/#testing-sandbox
Especially the part of the special test tokens.

**Comment by fridary** [comment]
Thank you. This is very hard to figure out what I have to do, I think you lose clients because of this. How can I also talk with IEX manager about API, I have questions? Before paying for account.

**Comment by McQgit** [comment]
@fridary I don't work for IEX - just trying to help.  You could also contact them through their corporate site: https://iexcloud.io/

**Comment by tjGecko** [comment]
@fridary Yeah...I'm running into the same thing. Still not quite working, but here's how I'm approaching the problem:

`
from iexfinance.stocks import Stock
import pprint
# import iex.MongoWriter as mw
from iexfinance.refdata import get_symbols
import os
import pandas as pd
import json


from pymongo import MongoClient


class Writer:
    def __init__(self, config):
        self.url = f'{config["MongoWriter"]["mongo_url"]}:{config["MongoWriter"]["mongo_port"]}'
        self.client = MongoClient(self.url)
        self.db = self.client.get_database(config["MongoWriter"]["mongo_database"])
        self.collection_name = config["MongoWriter"]["mongo_collection"]      # Table name

    def write_to_table(self, rec, table):
        db_table = self.db.get_collection(table)
        result = db_table.insert_one(rec)

    def write(self, rec):
        db_table = self.db.get_collection(self.collection_name)
        result = db_table.insert_one(rec)

        # print(f'Insert: {result.inserted_id}')

    def drop_collection(self):
        db_table = self.db.get_collection(self.collection_name)
        print(f'Drop output table: {self.collection_name}')
        db_table.drop()


class StockData:
    def __init__(self, config):
        self.d = config
        self.writer = Writer(config=config)
        # self.writer = mw.Writer(config=config)

    def run(self):
        self._switch_to_sandbox()
        self._fetch_data()

    def _switch_to_sandbox(self):
        # bash> export IEX_API_VERSION="iexcloud-sandbox"
        os.environ.setdefault(key='IEX_API_VERSION', value=self.d['iex_sandbox']['IEX_API_VERSION'])

    def _fetch_data(self):
        for ticker in self.d['iex']['tickers']:
            stock = Stock(ticker, token=self.d['iex']['token'])
            bs_json = stock.get_balance_sheet(output_format=self.d['iex']['output_type'])
            pprint.pprint(bs_json)

            d = {
                'Header': self.d['Header']
            }
            d['Header']['ticker'] = ticker
            self.writer.write(d)

    def _load_symbols(self):
        abs_path = os.path.join(self.d['history']['save_dir'], 'tickers.pkl')
        df = pd.read_pickle(abs_path)

        jsdf = df.to_json(orient='records')
        data = json.loads(jsdf)

        for idx, rec in enumerate(data):
            self.writer.write_to_table(rec, table='tickers')

    def _fetch_symbols(self):
        abs_path = os.path.join(self.d['history']['save_dir'], 'tickers.pkl')
        df_tickers = get_symbols(output_format='pandas', token=self.d['iex']['token'])
        df_tickers.to_pickle(abs_path)
        print(f"Saved: {abs_path}")
        print(df_tickers)

        # self.writer.write_to_table(rec=js_tickers, table='tickers')
        # pprint.pprint(js_tickers)


if __name__ == '__main__':
    python_script = __file__

    d = {
        'Header': {
            'python_script': python_script
        },
        'iex_sandbox': {
            'info': [
                'https://addisonlynch.github.io/iexfinance/stable/sandbox.html',
                'https://iexcloud.io/console/tokens',
                'https://intercom.help/iexcloud/en/articles/2915433-testing-with-the-iex-cloud-sandbox',
                'https://intercom.help/iexcloud/en/articles/2851957-how-to-use-the-iex-cloud-api',
            ],
            'IEX_API_VERSION': 'iexcloud-sandbox',
            'IEX_API_VERSION_info': [
                'Setting this turns on the sandbox mode',
                'https://addisonlynch.github.io/iexfinance/stable/configuration.html#config-api-version',
                'bash> export IEX_API_VERSION="iexcloud-sandbox"'
            ],
            'test_key_info': 'https://iexcloud.io/console/tokens',
            'test_keys': {
                'Tsk': 'Tsk_xxxxxxxxxxxxxxxxxxxxxxxxxx',
                'Tsk_info': [
                    'Test SECURE key. Pass this to make requests',
                    'https://iexcloud.io/docs/api/#sandbox'
                ],
                'Tpk': 'Tpk_yyyyyyyyyyyyyyyyyyyyyyyyyyyy',
                'Tpk_info': 'Test PUBLIC key. Not sure why I need this'
            }

        },
        'MongoWriter': {
            'mongo_url': 'localhost',
            'mongo_port': 26017,
            'mongo_database': 'stocks',
            'mongo_collection': 'sandbox_data',
        },
        'history': {
            'save_dir': '/home/temp/stock_data'
        },
    }

    # Override to use the SANDBOX key
    d['iex'] = {
        'account_no': 'zzzzzzzzzzzzzzzzzzzzzzzzzz',
        'token': d['iex_sandbox']['test_keys']['Tsk'],
        'tickers': ['AMZN'],
        'output_type': 'json'
    }

    util = StockData(config=d)
    util.run()


`

**Comment by GerryOnGithub** [comment]
Call me strange but I actually read the instructions, and my API call to the sandbox server fails anyway. Every time I got back to the console, **Sandbox View has turned itself off**. Why?

**Comment by McQgit** [comment]
@GerryOnGithub The sandbox button in the console is just a toggle to view your sandbox tokens.  It resets to off on each login - at least it does for me.  

Once you toggle it on, click the `API Tokens` tab to see them - they should start with letter T

Once in the API Tokens tab, toggling Sandbox View on and off will alternately show your regular and sandbox tokens.

It the correct token does not resolve your problem, the exact error and sample url would be helpful.

**Comment by GerryOnGithub** [comment]
I switched to open source chrome build and the facebook error is gone, switch and api works

**Comment by timpaine-iex** [comment]
@GerryOnGithub do you mind sharing more info about your other browser so we can debug? The `fb` stuff is completely separate and a red herring (it just comes from Google Analytics), its more likely that we're using a feature in our JS code that didn't work on your browser.

**Comment by GerryOnGithub** [comment]
I tried with Firefox and Edge. Disabled installed plug-ins Privacy Badger and UBlock Origin. Disabled winhelp etc/hosts ad/malware blocker. No luck. 

Switched to unadulterated Chrome, works as expected.

**Comment by timpaine-iex** [comment]
Which FF version? I cannot repro on `87.0`

**Comment by GerryOnGithub** [comment]
I'm afk, ff updates automatically
