### ISSUE TITLE
Historical Intraday

### ISSUE THREAD

**Issue by YBZ59** [iexg/IEX-API#1447]
Hi,

Does anybody know How far back can I get INTRADAY HISTORICAL data of 1min bar ?
I mainly want to get the PREMARKET Volume for specific US equities  

Appreciate any advise.
Thanks,
YBZ59

**Comment by smileycap** [comment]
I am also interested by this very question

**Comment by evancarter-iex** [comment]
We only officially support 30 days of intraday historical.
