### ISSUE TITLE
[Issue] Chart SPY range=max returning duplicates for same day

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1448]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**

running chart API for SPY range=max returns April 3 2020 three times

if you run range=3m this does not happen

`		}, {
				"date": "2020-04-01",
				"close": 246.15,
				"volume": 189554623,
				"change": -11.6,
				"changePercent": -4.5005,
				"changeOverTime": 1.860879
			}, {
				"date": "2020-04-02",
				"close": 251.83,
				"volume": 177660430,
				"change": 5.68,
				"changePercent": 2.3075,
				"changeOverTime": 1.926894
			}, {
				"date": "2020-04-03",
				"close": 248.19,
				"volume": 135561171,
				"change": -3.64,
				"changePercent": -1.4454,
				"changeOverTime": 1.884589
			}, {
				"date": "2020-04-03",
				"close": 248.19,
				"volume": 135561171,
				"change": 0,
				"changePercent": 0,
				"changeOverTime": 1.884589
			}, {
				"date": "2020-04-03",
				"close": 248.19,
				"volume": 135561171,
				"change": 0,
				"changePercent": 0,
				"changeOverTime": 1.884589
			}, {
				"date": "2020-04-06",
				"close": 264.86,
				"volume": 188061238,
				"change": 16.67,
				"changePercent": 6.7166,
				"changeOverTime": 2.078336
			}, {`
**What time did the problem occur? (with timezone)**

april 13 2020 530AM

**What is the expected behavior?**
doesn't return duplicates

**Your environment (e.g. browser, OS, API version, language):**
chrome

**API URL (if applicable)**

bad:
https://cloud.iexapis.com/stable/stock/market/batch?types=chart&token=pk_&symbols=SPY&chartCloseOnly=true&range=max

good:
https://cloud.iexapis.com/stable/stock/market/batch?types=chart&token=pk_&symbols=SPY&chartCloseOnly=true&range=3m

**What are the steps to reproduce the bug?**
run API

**Additional context**
please implement basic data checks! a simple PK would prevent this

**Comment by evancarter-iex** [comment]
Fixed.
