### ISSUE TITLE
Getting "Forbidden" when trying to get quotes for multiple symbols

### ISSUE THREAD

**Issue by arunkatti** [iexg/IEX-API#145]
## Summary
Getting "Forbidden" response when trying to get quotes for multiple symbols

## Details
Needed to get multiple stock quotes in one call (about 25 - 30). The IEX API documentation says I can use /market and then include multiple symbols separated by commas. I tried the following, but the response I get back says "Forbidden".

[https://api.iextrading.com/1.0/stock/AMZN,FB/market]

### Date/time of issue
12/18/2017 12:53 PM Eastern

### API URL
[Link][https://api.iextrading.com/1.0/stock/AMZN,FB/market]

### What you expected to happen
Expected to see multiple quotes according to the documentation

### What actually happened
Got "Forbidden" as my response instead.

**Comment by joshuablackburn-iex** [comment]
Please refer to the batch request documentation for details on how to call multiple symbols.

https://iextrading.com/developer/docs/#batch-requests

**Comment by arunkatti** [comment]
Thanks for the response. I guess I didn't read far enough in the documentation.
