### ISSUE TITLE
Gainers and Losers not returning anything

### ISSUE THREAD

**Issue by brianarice2** [iexg/IEX-API#1452]
On April 17th, 9:00am CST...

The request for gainers and losers is not returning anything (see urls below).

Has the endpoint for these changed or been deprecated?

Thanks!

- Brian

https://cloud.iexapis.com/stable/stock/market/list/gainers?filter=symbol,companyName,changePercent&listLimit=36&token=pk_mytoken

https://cloud.iexapis.com/stable/stock/market/list/losers?filter=symbol,companyName,changePercent&listLimit=6&token=pk_mytoken

**Comment by evancarter-iex** [comment]
This should be resolved.
