### ISSUE TITLE
1 min chart data is returning null for the pricing fields of several bars

### ISSUE THREAD

**Issue by djimoh5** [iexg/IEX-API#1453]
1 min chart data is returning null for pricing fields (open, high, low, close, average) for several different bars.

Symbol: AAPL
Date: Current day, which as of this writing is 4/16/2020
https://cloud.iexapis.com/v1/stock/AAPL/chart/1d

Ex.
{"date":"2020-04-16","minute":"10:42","label":"10:42 AM","high":null,"low":null,"open":null,"close":null,"average":null,"volume":0,"notional":0,"numberOfTrades":0

{"date":"2020-04-16","minute":"10:56","label":"10:56 AM","high":null,"low":null,"open":null,"close":null,"average":null,"volume":0,"notional":0,"numberOfTrades":0}

**Comment by FutureKode** [comment]
What happened with this? Is there a fix?

**Comment by joshuablackburn-iex** [comment]
As shown in our docs, those fields are IEX only data. If IEX does not have a trade in that minute of the day then we return null. For market wide data you should use the keys prefixed with “market”.

**Comment by FutureKode** [comment]
I am not seeing the market keys, anything wrong here?

```
let response = await fetch('https://cloud.iexapis.com/stable/stock/AAPL/intraday-prices?token=pk_27b957fb25f94e12b093b4f72d2b876f&chartLast=30');
if (response.ok) {
  let json = await response.json();
console.log(json);
}
```

Also, is there anyway to get live market-data without the 15min delay?

Thanks
