### ISSUE TITLE
[Issue] Advanced Dividends endpoint returns duplicate data.

### ISSUE THREAD

**Issue by wickman** [iexg/IEX-API#1458]
**Clearly describe the problem**

I queried the advanced_dividends endpoint with symbol `ITM`, constraining to dividends with `recordDate` within 2019: `params={'from': '2019-01-01', 'to': '2019-12-31', 'dateField': 'recordDate'}`.  A number of duplicate records were returned, specifically 3 separate records with `refid` of 1717647.  I believe I was charged for this duplicate data.

**What time did the problem occur? (with timezone)**

`2020-04-21 12:30:35-07:00`

**What is the expected behavior?**

As a user I expect to receive no duplicate data.

**Your environment (e.g. browser, OS, API version, language):**

Python 3 and [requests](https://github.com/psf/requests).  API v1 stable.

**API URL (if applicable)**

https://cloud.iexapis.com/v1/time-series/advanced_dividends/ITM

**What are the steps to reproduce the bug?**

Hit https://cloud.iexapis.com/v1/time-series/advanced_dividends/ITM with the following params:
```json
{
    "from": "2019-01-01",
    "to": "2019-12-31",
    "dateField": "recordDate"
}
```

**Additional context**

Potentially related to #940 on the Basic Dividend endpoint.

**Comment by evancarter-iex** [comment]
Fixed.
