### ISSUE TITLE
How to get Open and close of market index S&P for any date?

### ISSUE THREAD

**Issue by taj3rconnect** [iexg/IEX-API#1459]
I am writing a simple code which requires to get Open and Close of index S&P on a particular date.
How can I do that?
I just created a account at IEX.

**Comment by McQgit** [comment]
I don't work for IEX but this came up before.  

See: https://github.com/iexg/IEX-API/issues/901

**Comment by AdrienPoupa** [comment]
They don't have it, use SPY instead
