### ISSUE TITLE
Composite Market Prices for DOW Jones

### ISSUE THREAD

**Issue by SanjayThumati** [iexg/IEX-API#146]
### API URL: 
https://iextrading.com/developer/

### What you expected to happen:
Looking up "DJIA" in the stock API would return the actual composite market price for DOW Jones

### What actually happened:
No values are returned for this symbol.

### Other Information (sample code, links, etc.)
I talked to James Cape from Platform Team about this issue and he recommended submitting this issue as a new feature request here. James also gave an alternate solution, so-called "index-tracking ETFs,", which do trade like stocks and may be good enough:

Nadsaq: ONEQ https://api.iextrading.com/1.0/stock/ONEQ/quote (ONEQ * 25 ~= Nasdaq Composite)
DJIA: DIA https://api.iextrading.com/1.0/stock/DIA/quote (DIA * 100 ~= DJIA)
S&P 500: SPY https://api.iextrading.com/1.0/stock/DIA/quote (SPY * 10 = S&P500)
Nasdaq 100: QQQ https://api.iextrading.com/1.0/stock/DIA/quote (QQQ * 40 = Nasdaq 100)
 

However, these calculations are not tracking 100%.

**Comment by joshuablackburn-iex** [comment]
This is unfortunately not possible at this time.  Index data is tightly controlled by a single data source, and requires a very expensive (>$10k) contract paid by each consumer.  We have not found a reasonable way to provide this data.  Further, scraping sites that do display index data is against their terms of service.
