### ISSUE TITLE
Previous Close DCUE Null  - Quote

### ISSUE THREAD

**Issue by rmantovani** [iexg/IEX-API#1460]
I found some null values in PreviousClose filed calling Quote endpoint

**What time did the problem occur? (with timezone)**
Any time

**What is the expected behavior?**
Previous value

**Your environment (e.g. browser, OS, API version, language):**
Linux, Java, cloud

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/DCUE/quote?token=XXXX

**Additional context**
{"symbol":"DCUE","companyName":"Dominion Energy, Inc.","primaryExchange":"New York Stock Exchange","calculationPrice":"sip","open":100.94,"openTime":1587562200586,"openSource":"official","close":98.22,"closeTime":1587499320704,"closeSource":"official","high":100.4,"highTime":1587571339503,"highSource":"15 minute delayed price","low":98.94,"lowTime":1587562608935,"lowSource":"15 minute delayed price","latestPrice":100.12,"latestSource":"15 minute delayed price","latestTime":"12:28:35 PM","latestUpdate":1587572915402,"latestVolume":49359,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":100.12,"delayedPriceTime":1587572915402,"oddLotDelayedPrice":100.24,"oddLotDelayedPriceTime":1587573600732,"extendedPrice":99.13,"extendedChange":-0.99,"extendedChangePercent":-0.00989,"extendedPriceTime":1587561742144,**"previousClose":null,**"previousVolume":null,"change":null,"changePercent":null,"volume":49359,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":null,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":100.35,"iexAskSize":200,"iexOpen":null,"iexOpenTime":null,"iexClose":25.125,"iexCloseTime":1587574307598,"marketCap":83900560000,"peRatio":null,"week52High":0,"week52Low":0,"ytdChange":0,"lastTradeTime":1587572915402,"isUSMarketOpen":true}

**Comment by evancarter-iex** [comment]
Fixed.
