### ISSUE TITLE
[Data] Income statement income tax field

### ISSUE THREAD

**Issue by amittleider** [iexg/IEX-API#1461]
**Clearly describe the data problem**
The reported income taxes of some companies is 0, which is not correct.

**What time did the problem occur (including timezone)?**
April 23, 2020

**What are the steps to reproduce**
Use the income statements endpoint with 12 quarterly statements for MSFT

Here is the data for that call:

```

symbol | report_date | income_tax
MSFT | 2017-03-31 | 0.0
MSFT | 2017-06-30 | 0.0
MSFT | 2017-09-30 | 0.0
MSFT | 2017-12-31 | 0.0
MSFT | 2018-03-31 | 0.0
MSFT | 2018-06-30 | 0.0
MSFT | 2018-09-30 | 0.0
MSFT | 2018-12-31 | 0.0
MSFT | 2019-03-31 | 0.0
MSFT | 2019-06-30 | 0.0
MSFT | 2019-09-30 | 0.0
MSFT | 2019-12-31 | 0.0
```

The expected results of the income tax column can be found here: https://finance.yahoo.com/quote/MSFT/financials?p=MSFT

**Comment by McQgit** [comment]
@amittleider I am not an IEX rep nor an accountant.  I am just helping you clarify what you are looking for re: taxes.  Based on your description, you may not be aware this is more complicated.  If you are, then I apologize.

The yahoo site shows the amount of "Provision for Income Taxes" from MSFT's Income Statement.  That is not the amount paid in cash as taxes for that period (it is the accounting provision).  For the amount paid you must look at the Cash Flow Statement and in some cases the notes to that.

This info is on the 10K and 10Q statements which are readily available on SEC's Edgar:
https://www.sec.gov/cgi-bin/viewer?action=view&cik=789019&accession_number=0001564590-20-002450&xbrl_type=v#

If you were using the IEX 'as reported' financials endpoint, it should reflect what you see in the 10K/10Q.  If you were using their basic financials, that's a different matter.  You didn't say in your post which it was.

I find 3rd party sites, like yahoo, simplify the actual financial statements often times to their detriment.  There is no reason IEX should follow the standard of any other 3rd party site.  Although, it should represent the actual financials.  I didn't look but perhaps IEX has the tax paid in the cash flow statement in the 'as reported' endpoint?

There are many articles on google about this.  Here is just one example:
http://accounting-financial-tax.com/2009/04/income-taxes-and-the-statement-of-cash-flows/

Hope this helps.

**Comment by amittleider** [comment]
Hi @McQgit , thanks for this helpful post. 

I definitely agree with you that IEX shouldn't follow the standards of other 3rd party sites. The Yahoo link is to specify what I expect the endpoint to return.

First, to clarify, I am not using the 'as reported' financials, I am using the `income` endpoint (https://iexcloud.io/docs/api/#income-statement).

Second, I too am not an accountant, but I believe that this field (which IEX calls `incomeTax`) is what Yahoo finance is calling `Income Tax Expense`. I suppose another name for that would be "Provision for Income Taxes". Please say so if you think I'm wrong there.

Lastly, I should comment that the cash flow statement from IEX does not include any tax-related fields, a reasonable suggestion though.

The end result of all of this is to compute the effective tax rate, which is the income tax expense divided by the pretax income. Whether I use the accounting provision or the cash value, hopefully doesn't have a significant impact, as long as the metric is computed using the same data across all companies.

**Comment by McQgit** [comment]
@amittleider Yes, your request is now clearer.  Hopefully IEX can remedy it.  You want the IEX basic Income Statement endpoint to include the "Provision for Income Taxes" from the actual 10K/10Q.

I generally avoid using Income Statement data in favor of Cash Flow analysis due to the highly variable I/S changes due to accounting rules, time shifts, and other accounting quirks.  I wish you good luck in getting the data you want.

**Comment by amittleider** [comment]
@McQgit Interesting point. Sounds like you know your way around the data pretty well.

I'd be interested to hear more about how you're using IEX data. If you want to chat about it send me a mail, my github username at gmail.

**Comment by McQgit** [comment]
@amittleider  I may do that.  Just for fun I looked at the latest 10K using the IEX time-series Income Statement.  Oddly, they don't have the "provision ..." item as seen on the 10K statement itself.  But, they did have many metrics for effective tax rates.  I assume the "provision ..." omission is due to them passing along the XBRL of the statements, but I didn't review the taxonomy (not related to income tax) of that to see if that's the case.

    "EffectiveIncomeTaxRateContinuingOperations": 0.102,
    "EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate": 0.21,
    "EffectiveIncomeTaxRateReconciliationDeductionsExcessTaxBenefitsStockBasedCompensation": 0.022,
    "EffectiveIncomeTaxRateReconciliationForeignDerivedIntangibleIncomeDeduction": 0.014,
    "EffectiveIncomeTaxRateReconciliationForeignIncomeTaxRateDifferential": -0.041,
    "EffectiveIncomeTaxRateReconciliationIntangiblePropertyTransfers": -0.059,
    "EffectiveIncomeTaxRateReconciliationInterestIncomeExpense": 0.01,
    "EffectiveIncomeTaxRateReconciliationOtherAdjustments": 0.025,
    "EffectiveIncomeTaxRateReconciliationPhoneBusinessGainsLosses": 0,
    "EffectiveIncomeTaxRateReconciliationTaxCreditsResearch": 0.011,
    "EffectiveIncomeTaxRateReconciliationTaxCutsAndJobsActPercent": 0.004,

The joy of computerized analysis :)
