### ISSUE TITLE
Need help for deep data

### ISSUE THREAD

**Issue by fimmugit** [iexg/IEX-API#1463]
I have used the old api (v1.0) in the past to get deep data for multiple symbols. I noticed the old api is still working but am not sure for how long in the future. So I intend to migrate to the new cloud. When I try the new request like this: 
https://cloud.iexapis.com/stable/deep?token=pk_40ad3e2faffe4de8ab05002e7b8c8d8e&symbols=aapl,spy

I only get deep data for the first symbol! How can I get deep data in batch like before:
https://api.iextrading.com/1.0/deep/trades?symbols=snap,aapl

**Comment by evancarter-iex** [comment]
Hi there, you posted your token so hopefully you rotated that. The documentation is here: https://iexcloud.io/docs/api/

**Comment by foltz** [comment]
I'm seeing the same issue with the symbols query-string - on the stable version.  If you specify more than one symbol (per the documentation) it only returns data for the first one you specified.

I encountered the issue with this url:
https://cloud-sse.iexapis.com/stable/deep?channels=deep&symbols=SPY,QQQ&token=XXXX

I get the same behavior when trying channels=trades and channels=book as well.
