### ISSUE TITLE
[Issue] NASDAQ quotes out of date by 1 day on /stock endpoint

### ISSUE THREAD

**Issue by saunders77** [iexg/IEX-API#1464]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**
Stock quotes from /stock/market/batch are currently showing yesterday's price for NASDAQ-exchange quotes. For example, the MSFT quote is showing 169.81, whereas today's actual last price is around 177.43.
In addition, % Change is listed as zero.

**What time did the problem occur? (with timezone)**

Around 4pm Eastern time on 4/29

**What is the expected behavior?**

Expected today's prices rather than yesterday's close.

**Your environment (e.g. browser, OS, API version, language):**

Windows, Chrome, /stable/, JavaScript. I also have users who reproduce the issue on Mac OS.

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/market/batch?symbols=GOOG,MSFT

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by saunders77** [comment]
This issue was resolved about 2 hours after I reported it here. It would be good to know whether this type of issue is likely to happen in the future though.

**Comment by evancarter-iex** [comment]
Fixed.
