### ISSUE TITLE
Get Options GREEK

### ISSUE THREAD

**Issue by taj3rconnect** [iexg/IEX-API#1465]
Is there anyway to get delayed or real time options pricing along with it GREEKS like Delta?

Something like this which I am getting from Tradier.

"symbol": "AAPL200508C00135000",
                "description": "AAPL May 8 2020 $135.00 Call",
                "exch": "Z",
                "type": "option",
                "last": 162.0,
                "change": 18.94,
                "volume": 5,
                "open": 158.05,
                "high": 162.0,
                "low": 158.05,
                "close": 162.0,
                "bid": 152.15,
                "ask": 156.6,
                "underlying": "AAPL",
                "strike": 135.0,
                "greeks": {
                    "delta": 1.0,
                    "gamma": -8.0179E-16,
                    "theta": 2.05883E-13,
                    "vega": -2.4687E-12,
                    "rho": 0.0,
                    "phi": 0.0,
                    "bid_iv": 0.0,
                    "mid_iv": 0.0,
                    "ask_iv": 0.0,
                    "smv_vol": 0.57464,
                    "updated_at": "2020-05-01 19:56:43"

**Comment by Jacyle** [comment]
This would be a great feature to add!

**Comment by timpaine-iex** [comment]
duplicate https://github.com/iexg/IEX-API/issues/906#issuecomment-511433874
