### ISSUE TITLE
[Data] advanced splits endpoint not returning data

### ISSUE THREAD

**Issue by arifb** [iexg/IEX-API#1467]
**Clearly describe the data problem**
advanced splits endpoint doesn't return any data.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/time-series/advanced_splits/AAPL

**What time did the problem occur (including timezone)?**
Tues May 5 1530PT

**What is the expected behavior?**
According to docs, that should return 12 years of historical data, and a split occured in 2014

**Comment by MorningSleeper** [comment]
Unfortunately, there is an issue with the basic splits endpoint as well, https://github.com/iexg/IEX-API/issues/1330

**Comment by arifb** [comment]
thanks @MorningSleeper, have +1'd that issue. Unfortunate as that issue is 6+ months so clearly not a priority. Have you found an alternate data source for splits?

**Comment by MorningSleeper** [comment]
Thanks, I have not looked for any alternatives. I did email them about it a little over a month ago and was told they would investigate it and keep me updated although no update as of yet. You may want to consider emailing them as well.
