### ISSUE TITLE
Why does the 1d chart not include open/close values?

### ISSUE THREAD

**Issue by tradetools** [iexg/IEX-API#147]
## Summary

This might be a silly question but, I am trying to create a hloc candle chart with no success since there are no open and close values for the 1d chart. How is it possible to create a candle chart with minute candles for the latest day?

**Comment by jcape** [comment]
@tradetools It may not be possible to do this with a single call, but you can easily call the quote endpoint in a different call to get that information.

**Comment by joshuablackburn-iex** [comment]
Additionally, the official open and close can happen at different times for different stocks.  They may not line up with the minute buckets we return for 1d chart.  We do return Open, High, Low, Close data in the open-close endpoint, and you can get all of this data in one call by using the batch endpoint.

**Comment by tradetools** [comment]
thank you for the feedback
