### ISSUE TITLE
Is Dividend (Basics) only supposed to return the historical price for one quarter?

### ISSUE THREAD

**Issue by maureenv** [iexg/IEX-API#1470]
**Clearly describe the data problem**
When making a request to the following URL: `https://cloud.iexapis.com/stable/stock/aapl/dividends/5y?token ` I was expecting to to get a response with dividends from all 4 quarters in 2015. Instead I only received dividend information for one quarter in 2015. 

This was the response: `[{"exDate":"2015-05-07","paymentDate":"2015-05-14","recordDate":"2015-05-11","declaredDate":"2015-04-27","amount":"0.520000000","flag":"Cash","currency":"USD","description":"Ordinary Shares","frequency":"quarterly","date":"2020-05-06"}]`

This gives me the dividend amount for 2015-05-07 (amount: 0.52). However, Apple had a different dividend amount in the same year, different quarter (2015-02-05 | $0.47) as discovered on another website. 

The dividend basics response is an array so I expected to receive an array of all dividends paid that year but this wasn't the case. Is this endpoint supposed to only send dividends for one quarter of the year?

Thank you!

**Data URL (The URL you used to access the data without your token):**
`https://cloud.iexapis.com/stable/stock/aapl/dividends/5y?token `

**What time did the problem occur (including timezone)?**
May 6, 2020, 10am CST

**What is the expected behavior?**
Return every quarter's dividends for a historical year.

**Comment by JamesChloroBenzene** [comment]
Use
https://cloud.iexapis.com/stable/stock/aapl/dividends?range=5y&token

**Comment by maureenv** [comment]
Hi @JamesChloroBenzene  thank you for your response! I tried the end point you gave me but I still only get one dividend quarter in the response instead of all the dividends for the last five years:

**API Endpoint without range**
Request: `https://cloud.iexapis.com/stable/stock/aapl/dividends/5y?token=`
Response: `[{"exDate":"2015-08-06","paymentDate":"2015-08-13","recordDate":"2015-08-10","declaredDate":"2015-07-21","amount":"0.520000000","flag":"Cash","currency":"USD","description":"Ordinary Shares","frequency":"quarterly","date":"2020-05-08"}]`

**API Endpoint with range**
Request: `https://cloud.iexapis.com/stable/stock/aapl/dividends?range=5y&token=`
Response: `[{"exDate":"2015-08-06","paymentDate":"2015-08-13","recordDate":"2015-08-10","declaredDate":"2015-07-21","amount":"0.520000000","flag":"Cash","currency":"USD","description":"Ordinary Shares","frequency":"quarterly","date":"2020-05-08"}]`

Please let me know if I'm missing anything or if there is something wrong with the data.

Thank you!

**Comment by McQgit** [comment]
@maureenv  Do you have a paid account?  This is in the docs for basic dividends:

"Notes
Dividends prior to last reported are only included with paid subscription plans"
https://iexcloud.io/docs/api/#dividends-basic

Based on that you should have only seen the most recent one.  But, I seem to remember this coming up before that with range and not a paid account you just get one - not necessarily the latest.  If you didn't specify the range, I think you'd get just the latest.

BTW, your original url was fine too.  It works fine for me, for all 5 years

**Comment by maureenv** [comment]
@McQgit Thank you! I saw that message about needing a paid account too so I thought if I used my sandbox test account I might be able to see all 5 years worth of test data but that didn't work either. At least now I know for paid accounts this works fine. So with a paid account it will return every paid dividend in the last 5 years?

Thank you!

**Comment by McQgit** [comment]
@maureenv  Yes, as I noted, it worked fine for me.  Specifically, for AAPL, the 2 in this year and the latest 2 in year 2015 (5 years of dividends).
