### ISSUE TITLE
Error of 'The API key provided is not valid'

### ISSUE THREAD

**Issue by rubicon-sasgeo** [iexg/IEX-API#1471]
- Date/time of the issue
~14:00 05/07/2020

- What you did
Used Postman to test production API 'https://cloud.iexapis.com/v1/stock/TSLA/chart/3d?token=pk_...'

- What you expected to happen
The API should return JSON data set.

- What actually happened
I got 'The API key provided is not valid.'

- Additional relevant information
a. The API worked properly today till about 14:00.
b. I have verified that the token is correct production token.
c. Sandbox API still works
![image](https://user-images.githubusercontent.com/55929460/81336055-3ea4a000-906e-11ea-8c16-76138a1c06c8.png)

**Comment by joshuablackburn-iex** [comment]
The error is actually wrong and misleading. The range you’re using is not supported. 3d is not a supported range. You can find our supported ranges in our docs.

**Comment by rubicon-sasgeo** [comment]
Thank you, Josh! That is exactly true.
