### ISSUE TITLE
[Request] Years of Dividend Growth

### ISSUE THREAD

**Issue by TechniumUnlimited** [iexg/IEX-API#1473]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Is your feature request related to a problem? Please describe.**
I dont want to spend 75000 requests * unknown to discover how many years of dividend growth a company has, 

**Describe the solution you'd like**
can there be a maybe 100 cost request to return an int of years of growth in dividend

**Describe alternatives you've considered**
Calling for advanced dividend data for as far back as it can go, which could end up costing the entire plans allotted request cap for a single stock

**Additional context**

**Comment by JoelCCodes** [comment]
Yes please
