### ISSUE TITLE
[Data] Ford motor company dividend should be 0

### ISSUE THREAD

**Issue by norlan-perdomo** [iexg/IEX-API#1475]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
The "F" ticker, which is the ford motor company has currently suspended dividend payments, however, the IEX API still returns as the dividend rate of 0.6.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/f/stats/ttmDividendRate

**What time did the problem occur (including timezone)?**
12:21 EST

**What is the expected behavior?**
ttmDividendRate should be 0

**What are the steps to reproduce**
Hit https://cloud.iexapis.com/stable/stock/f/stats/ttmDividendRate in your browser with a proper token, notice that the data returned is 0.6, it should be 0.

**Your environment (e.g. browser, OS, API version, language):**
Browser

**Additional context**
https://www.barrons.com/articles/ford-suspends-its-dividend-shuts-north-american-factories-51584638990

**Comment by McQgit** [comment]
@norlan-perdomo The item you are looking at is the ttm (trailing twelve month) amount.  So, 0.6 is correct.  Going forward, this will diminish if F doesn't pay new dividends and previous ones become older than the last twelve months.  

As you point out, given F's announcement the 'indicated yield' or 'forward yield' or 'annualized yield' (or similar terms) is zero.  But, that's not what this data item reflects.

I'm not from IEX, just explaining dividend terminology.  Tracking halted or suspended dividends is tricky.

**Comment by norlan-perdomo** [comment]
@McQgit thanks for pointing that out!

Closing out ticket.
