### ISSUE TITLE
API call from AWS cloud or European IP time out

### ISSUE THREAD

**Issue by rubicon-sasgeo** [iexg/IEX-API#1476]
- Date/time of the issue
~14:00 05/11/2020

- What you did
1. Call 'https://sandbox.iexapis.com/stable/stock/BKNG/chart/5d?token=Tpk_***' from AWS Lambda function (us east 1 region) failed due to timeout.
2. Call the same url from European IP and the call timed out too.

- What you expected to happen
The API should return JSON data set.

- What actually happened
I got '
**The connection has timed out
The server at sandbox.iexapis.com is taking too long to respond.**
' after ~30s.

- Additional relevant information
Postman / Node.js call from localhost (US IP) succeeded 100%

**Comment by rubicon-sasgeo** [comment]
Any suggest? I am waiting for your answer to make a decision if to upgrade membership.

**Comment by evancarter-iex** [comment]
@rubicon-sasgeo Can you email support with the ips in question so we can take a look?

**Comment by rubicon-sasgeo** [comment]
> @rubicon-sasgeo Can you email support with the ips in question so we can take a look?

Thank you for replying. I was giving up...

I don't have a static IP 
- AWS service does not have a fixed IP
- I also used TOR to get random European IPs.

You may install TOR and simple paste the 'https://sandbox.iexapis.com/stable/stock/BKNG/chart/5d?token=Tpk_***' to the address bar of TOR and observe the result. (Compare using the url in Firefox / Chrome / Edge / etc.)

![image](https://user-images.githubusercontent.com/55929460/83317386-cacf6080-a1f1-11ea-8cca-0a2bbd2174ff.png)

![image](https://user-images.githubusercontent.com/55929460/83317379-b8edbd80-a1f1-11ea-9c3a-d0a78d9b4bc6.png)

**Comment by rubicon-sasgeo** [comment]
Update - please ignore the issue with AWS. We have decided to use virtual machine to host NodeJS instead of Lambda Function (NodeJS 12.x) to bypass part of the problem. But we are still curious about the TOR / European IP issue.

**Comment by rubicon-sasgeo** [comment]
I am going to close this issue because we have decided to buy the subscription for further testing and use dedicated US server(s).
