### ISSUE TITLE
Can't Get Historical Intraday Data Back Past One Year

### ISSUE THREAD

**Issue by raeldor** [iexg/IEX-API#1478]
Using Python library I am doing...

date =datetime(2019,1,17)
get_historical_intraday('AAPL',date,output_format='pandas')

But I'm getting no data returned.

**Comment by McQgit** [comment]
@raeldor  Are you by chance using the iexfinance python module? If so, that's a 3rd party extension whose docs are here:

[]https://pypi.org/project/iexfinance/
or here:
[]https://github.com/addisonlynch/iexfinance

The docs in either location show what you are asking for. If you are using some other python module, I guess that won't help.

**Comment by raeldor** [comment]
Appreciate the reply.  Here's an example using the endpoint that returns no data...

https://cloud.iexapis.com/stable/stock/twtr/chart/date/20190220?token=xxxx

But if you change to 2020 it returns data.

**Comment by hyunraekim** [comment]
I've been experiencing the same thing. The data exists given that when a range is provided, it shows data that spans back many years, but when specifying the date past around early 2019, it will return nothing.

**Comment by joshuablackburn-iex** [comment]
As stated in our docs, we only officially support 30 days of intraday data. There is an item on our roadmap to expand availability to cover many years, but we are still sourcing the data.

**Comment by raeldor** [comment]
Appreciate the response.  30 days isn't a lot of data for machine learning.  Do you have an ETA for covering many years?  Also, do you guys also cover indexes such as VIX and CL2?
