### ISSUE TITLE
Chart Data for EOD same day is not always available.

### ISSUE THREAD

**Issue by munishar** [iexg/IEX-API#1481]
I recently subscribed to the IEX annual basic plan for my individual stock analysis needs. I want to get end of the day data (OHLCV)  on same day. Right now quote endpoint is not very friendly to offer OHLCV. in old IEX, it used to be so easy. Please help with creating a reliable endpoint for OHLCV...

**Comment by JimLynchCodes** [comment]
I too am seeing this behavior and posted about it in this issue here: https://github.com/iexg/IEX-API/issues/1662

Would appreciate if someone from iex could comment on this...

**Comment by timpaine-iex** [comment]
moving to #1662
