### ISSUE TITLE
ITW missing latest upcoming-dividend data[Data]

### ISSUE THREAD

**Issue by WillTron** [iexg/IEX-API#1482]
**Clearly describe the data problem**
ITW announced their second quarter dividend on 5-8-20. It's been more than a few business days since the official div declared date and the 2nd quarter div info is still missing from the "upcoming-dividends" EP. The dividend info is appearing on other web sites -- dividend.com and Yahoo Finance for example.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=itw&types=upcoming-dividends&token=my_token

**What time did the problem occur (including timezone)?**
today (MST) around 3 pm

**What is the expected behavior?**
The latest Declared dividend data to show up in the json output for the "upcoming-dividends" endpoint following the company declaration -- give-or-take a few business days.

[exDate] => 2020-06-29
[paymentDate] => 2020-07-15
[recordDate] => 2020-06-30
[declaredDate] => 2020-05-08
[amount] => 1.07

**What are the steps to reproduce**
run above API call.

**Your environment (e.g. browser, OS, API version, language):**
latest Chrome, Win10 Pro, IEX Cloud v1, Launch Plan

**Additional context**
```
{
  "ITW": {
    "upcoming-dividends": []
  }
}
```

**Comment by evancarter-iex** [comment]
Fixed.
