### ISSUE TITLE
Fund Ownership vs. Institutional Ownership

### ISSUE THREAD

**Issue by whitewolf92** [iexg/IEX-API#1483]
I understand from the docs that..

1) Institutional ownership is for firms considered buy-side or sell-side.

2) Fund ownership are for all other firms, such as mutual or pension funds, not classified as buy-side or sell-side.

But why is it that both endpoint data is similar for some companies. E.g. AAPL.

**Comment by whitewolf92** [comment]
Any response from IEX staff? :(

**Comment by joshuablackburn-iex** [comment]
Ownership is split by institutions or mutual funds. Some institutions have mutual funds, so you’ll see similar names.

**Comment by whitewolf92** [comment]
Ah ok. Thanks joshua
