### ISSUE TITLE
[Request] Price data from Nordic Exchanges

### ISSUE THREAD

**Issue by christiankm** [iexg/IEX-API#1484]
Hi IEX,

Thanks for a fantastic API!

For the product I'm building it is becoming really urgent to provide support and price data for the Nordic/Scandinavian Exchanges: Copenhagen, Stockholm, Oslo and Helsinki.

Without this, my product is completely redundant in that region, and cannot be launched.

I sincerely hope you can prioritize adding these exchanges soon, so we can have more international exchange data.

I would be more than happy to discuss further details if needed.

Thank you!

**Comment by lars670** [comment]
Fellow countryman :-)
I would think that NasdaqOmxNordic will not be very interested in distributing through IEX with the redistribution polices and good low prices. But cool if that came too
Just a qualified guess
/Lars

**Comment by MoeAmine** [comment]
Same request here. Oslo Børs data availability will be great.

**Comment by evancarter-iex** [comment]
These are now available.

**Comment by christiankm** [comment]
> These are now available.

That's fantastic, thank you so much! I tried the search feature and it looks like it shows up there fine. But it does not return any date for those symbols in the /quote-endpoint. I can't guarantee this is not a mistake in my code, but will look closer during the holidays.

**Comment by evancarter-iex** [comment]
@christiankm /previous /chart are available. Ill look into why /quote isnt available for them.

**Comment by christiankm** [comment]
> @christiankm /previous /chart are available. Ill look into why /quote isnt available for them.

Thank you. Any change we should reopen this issue, or create a new one? For example for Danske Bank I get a 404 response:

```
<NSHTTPURLResponse: 0x6030001e92b0> { URL: https://cloud.iexapis.com/stable/stock/DANSKE-DC/quote?displayPercent=true&token=xxxxxxxxxxxxx} { Status Code: 404, Headers {
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    "Content-Encoding" =     (
        gzip
    );
    "Content-Type" =     (
        "text/html; charset=utf-8"
    );
    Date =     (
        "Tue, 29 Dec 2020 15:35:29 GMT"
    );
    Server =     (
        nginx
    );
    "Strict-Transport-Security" =     (
        "max-age=15768000"
    );
    "access-control-allow-credentials" =     (
        true
    );
    "access-control-allow-headers" =     (
        "Origin, X-Requested-With, Content-Type, Accept, Request-Source"
    );
    "access-control-allow-methods" =     (
        "GET, OPTIONS"
    );
} }
```
