### ISSUE TITLE
[Issue] sandbox testing does not work for premium data on free accounts

### ISSUE THREAD

**Issue by vslee** [iexg/IEX-API#1486]
**Clearly describe the problem**

I am the developer of the [C# API IEXSharp](https://github.com/vslee/IEXSharp). We are now enabling support in the API for premium data. There are tests in our library to make sure we are calling the IEX APIs properly. However, I only have a free account, and the tests don't work for Premium Data. 

**What is the expected behavior?**

It would be great if sandbox testing worked for Premium Data on free plans. Sandbox testing currently works for other endpoints that require paid plans, such as SSE streaming. Since the data is obfuscated anyways, it is protected from abuse. Providing this sandbox functionality would greatly help developers of IEX libraries, especially those which are free and open source.

**Comment by vslee** [comment]
@timpaine-iex Is there a plan for this in the future? It would help out greatly for library maintainers. Obfuscated data would be enough.

**Comment by timpaine-iex** [comment]
@vslee this works fine for everything except reports

**Comment by timpaine-iex** [comment]
e.g. from `pyEX`
<img width="640" alt="Screen Shot 2021-04-29 at 4 49 06 PM" src="https://user-images.githubusercontent.com/74613173/116616555-d0a25a00-a90a-11eb-9d52-acb41d6dc127.png">

**Comment by timpaine-iex** [comment]
ah are you asking about specifically free accounts vs paid accounts? ping me and we'll get you a paid account if you don't have one
