### ISSUE TITLE
[Data] NTES Dividend Duplicates on 1y

### ISSUE THREAD

**Issue by rickyplouis** [iexg/IEX-API#1488]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
Whenever the dividend endpoint for NTES is called it gives the following duplicate datapoint. The responses are nearly identical except one of them has a frequency of null
`
{
        "exDate": "2019-12-05",
        "paymentDate": "2019-12-13",
        "recordDate": "2019-12-06",
        "declaredDate": "2019-11-20",
        "amount": "4.14",
        "flag": "Cash",
        "currency": "USD",
        "description": "ADR",
        "frequency": "quarterly",
        "date": "2020-05-25"
    },
    {
        "exDate": "2019-12-05",
        "paymentDate": "2019-12-13",
        "recordDate": "2019-12-06",
        "declaredDate": "2019-11-20",
        "amount": "3.45",
        "flag": "Cash",
        "currency": "USD",
        "description": "ADR",
        "frequency": null,
        "date": "2020-05-25"
    },
`

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/NTES/dividends/1y

**What time did the problem occur (including timezone)?**
CST

**What is the expected behavior?**
Expected one datapoint per dividend payment

**What are the steps to reproduce**
GET REQ https://cloud.iexapis.com/stable/stock/NTES/dividends/1y

**Your environment (e.g. browser, OS, API version, language):**
Stable API

**Additional context**

**Comment by McQgit** [comment]
@rickyplouis  There were two dividends issued that day - at least according to this other source:
https://seekingalpha.com/symbol/NTES/dividends/history

Note also that the amounts are different.  Often when frequency is 'null' it means it is a special dividend.  You can find other comments about that by searching this git.

It would be nicer if IEX indicated special dividends more clearly.  Alas this is not so in the basic dividends.  In the advanced_dividends you would probably see this clearer.

I did not visit the corporate site to confirm what I describe here - I am only going by what we've seen in the past in general.

**Comment by rickyplouis** [comment]
> @rickyplouis There were two dividends issued that day - at least according to this other source:
> https://seekingalpha.com/symbol/NTES/dividends/history
> 
> Note also that the amounts are different. Often when frequency is 'null' it means it is a special dividend. You can find other comments about that by searching this git.
> 
> It would be nicer if IEX indicated special dividends more clearly. Alas this is not so in the basic dividends. In the advanced_dividends you would probably see this clearer.
> 
> I did not visit the corporate site to confirm what I describe here - I am only going by what we've seen in the past in general.

Yeah, Seeking Alpha lists two different dividend payments but here on Nasdaq's site I'm seeing one payment at a higher rate than the others.

https://www.nasdaq.com/market-activity/stocks/ntes/dividend-history


12/05/2019 | Cash | $7.59 |   | 12/06/2019 | 12/13/2019
-- | -- | -- | -- | -- | --

Also I looked through the quarter financial statement and found the following

> “During our eventful third quarter, we realized value for our shareholders across our business lines. On a year- over-year basis, we achieved solid growth in net revenues of 11% and non-GAAP net income from continuing operations of 74%. In recognition of this success, our board of directors has approved a dividend of US$7.59 per ADS for the third quarter,” said Mr. William Ding, Chief Executive Officer and Director of NetEase. “Our main areas of investment are online games, online education, music and private label e-commerce. With the completion of Youdao’s IPO, we will continue to invest in knowledge tools, online courses and smart devices to empower even more efficient learning in China.


It appears this was more like a one-time dividend hike than it was a separate dividend. SeekingAlpha and both IEX are both reading it as two separate payments when it seems to be only one. I don't believe this was the intended behavior of the API.

**Comment by McQgit** [comment]
@rickyplouis When 3rd party sites vary, it's always best to go to the actual sources.  One is the corporate site.  And, in fact, I saw them describe the two dividend payments here - scroll to the 'Quarterly Dividend' section:
http://ir.netease.com/news-releases/news-release-details/netease-reports-third-quarter-2019-unaudited-financial-results

For your further education in such matters, in the case of ADRs, the US Depositary is also helpful.  They collect the dividend from the foreign company and distribute to holders of the US ADR.  In short, what they say about the US dividend is 'golden'.  NTES' depositary is BNY.  See:
https://www.adrbnymellon.com/search?q=netease

If you view the BNY details on this dividend, you will see it was two - a special and a regular (see the addendum on the bottom of this pdf page):
https://www.adrbnymellon.com/publicSiteProxyExport.jsp?resourceName=getExportDsf&statusCode=F&cactnId=170000050942&exportFormat=pdf
The amounts for each are exactly as shown by IEX.  Note that on their website dividend summary page they show these two payments combined.  It is only looking at the details you see it is two.

Just for fun, JP Morgan is a depositary for many ADRs and has helpful info even when it isn't.  You can see the two dividends more clearly than with BNY - fwiw.
https://www.adr.com/drprofile/64110W102

Hope this helps.  I'll note from years of personal experience using API's and websites that ADR dividends are fraught with oddities.  Many 3rd party sites will show them wrong, especially yields when the payments are not consistent.  It will help you to maintain a wary eye when viewing data from such sources and verify that data with manual inspection of the company site and the depositary.  Cheers

**Comment by rickyplouis** [comment]
@McQgit Thank you for the sources, you are right about it not being a duplicate, but this does not solve the issue. Based what you've stated above, the API does not distinguish between regular and special dividends at this endpoint. I'm indifferent to the way it is being handled (i.e. one payment of $7.59 or two seperate payments) but it is not explicitly stated, and it seems a bit unreasonable that someone would be able to infer this without prior knowledge. At the very least shouldn't this be documented somewhere on the official docs?

**Comment by McQgit** [comment]
@rickyplouis  I sympathize with your frustration but what IEX is doing in this case seems ideal.  The company issued two dividends (a special and a regular) and IEX show it as such.  I find knowing whether a dividend is special or not very valuable info.  IEX do distinguish between the two - the special is identified with the frequency of 'null'.  While this may not be self-evident, it is also not unusual.  Other data sources will often just say 'unknown' or such for special dividends.  Perhaps IEX could doc this better - but it has come up before in this git at least.

You may also wish to evaluate IEX time series advanced dividends.  Those endpoints have more data - at higher message cost.  

Doing computerized analysis of dividends, especially ADRs, is not trivial.  It takes some experience to appreciate all the unusual variations that exist.  I've been working at it for nearly 10 years :)  I wish you the best of luck.
