### ISSUE TITLE
Null Security Name using Search endpoint with various symbols

### ISSUE THREAD

**Issue by tyirvine** [iexg/IEX-API#1489]
I've noticed sometimes data is missing when using the Search endpoint. For instance, when searching for `'apple'` or `'ford'` the security name field is null. I've noticed this is usually updated but because of this would you recommend just not using that endpoint?

Here is the response I got back from searching for `aapl` 
```
[{"symbol":"AAPL","securityName":"","securityType":"cs","region":"US","exchange":"NAS"},{"symbol":"AAPL-MM","securityName":"Apple Inc.","securityType":"cs","region":"MX","exchange":"MEX"}]
```

As you can see, `securityName` is null

**Comment by jbsheds** [comment]
I'm seeing the same thing on almost a lot of tickers. Seems like data for the foreign exchanges is populated but not the US exchanges.

**Comment by tyirvine** [comment]
@jbsheds I emailed them last night so hopefully it gets resolved soon. I think though this is an ongoing issue

**Comment by joshuablackburn-iex** [comment]
We are looking into the issue. We do have an update to our indexing strategy going out which will hopefully resolve this.

**Comment by JoelCCodes** [comment]
@tyirvine @jbsheds 
Can confirm this issue in our instance as well. 


Do you have a timeline for when this will be resolved? @joshuablackburn-iex

**Comment by tyirvine** [comment]
@joshuablackburn-iex Awesome, if you guys are redoing the indexing is it possible to add a header in to customize how many results are returned?

Right now just a select few results (10 max) are returned as you know and it'd be nice if this could be bumped up to say 20. Perhaps I could just submit a feature request

**Comment by tyirvine** [comment]
Thank you for fixing this @joshuablackburn-iex! I'm closing this for now 🥳

``` javascript
[{"symbol":"AAPL","securityName":"Apple Inc.","securityType":"cs","region":"US","exchange":"NAS"},{"symbol":"APLE","securityName":"Apple Hospitality REIT Inc","securityType":"cs","region":"US","exchange":"NYS"},{"symbol":"APRU","securityName":"Apple Rush Company, Inc.","securityType":"cs","region":"US","exchange":"OTC"},{"symbol":"AGPL","securityName":"Apple Green Holding, Inc.","securityType":"cs","region":"US","exchange":"OTC"},{"symbol":"APPLX","securityName":"Appleseed Fund","securityType":"oef","region":"US","exchange":"NAS"},{"symbol":"APGN-LN","securityName":"Applegreen plc","securityType":"cs","region":"GB","exchange":"LON"},{"symbol":"APGN-ID","securityName":"Applegreen plc","securityType":"cs","region":"IE","exchange":"DUB"},{"symbol":"AAPL-MM","securityName":"Apple Inc.","securityType":"cs","region":"MX","exchange":"MEX"},{"symbol":"APC-GY","securityName":"Apple Inc.","securityType":"cs","region":"DE","exchange":"ETR"},{"symbol":"511339-IB","securityName":"Apple Credit Corp. Ltd.","securityType":"cs","region":"IN","exchange":"BOM"}]
```
