### ISSUE TITLE
The Upstream SSL certificate for cloud.iexapis.com may have expired

### ISSUE THREAD

**Issue by kristjanmar** [iexg/IEX-API#1493]
The SSL certificate for cloud.iexapis.com has expired, so API calls are returning an error.

See here: https://www.ssllabs.com/ssltest/analyze.html?d=cloud.iexapis.com

> **Valid until | Sat, 30 May 2020 10:48:38 UTC (expired 2 hours and 34 minutes ago) EXPIRED**

**Comment by evancarter-iex** [comment]
@kristjanmar What OS/browser are you using? We arent seeing any issues with vast majority of browsers etc

**Comment by professorDante** [comment]
Same for us:

"URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)'),)"

**Comment by evancarter-iex** [comment]
@professorDante What OS and Browser?

**Comment by professorDante** [comment]
> @professorDante What OS and Browser?
no browser - its a cron job running on a linux server.

**Comment by evancarter-iex** [comment]
@professorDante What linux version then?

**Comment by evancarter-iex** [comment]
https://support.comodoca.com/Com_KnowledgeDetailPageSectigo?Id=kA01N000000rgSZ might be the issue.

**Comment by professorDante** [comment]
> @professorDante What linux version then?

CentOS Linux 7

**Comment by evancarter-iex** [comment]
@professorDante its possible that it doesnt contain the updated trust root as per that support document.

**Comment by professorDante** [comment]
I have no idea - all we know is that everything worked up to this morning.

**Comment by McQgit** [comment]
@professorDante  Try disabling SSL certificate checking - presuming you are using curl:
https://knowledge.digicert.com/solution/SO6318.html

This will get you past the issue until you can sort out why your system is invalidating a 'down the chain' cert.  (I am not IEX)

**Comment by professorDante** [comment]
Alrighty - I'll contact the sysadmin of the box to see if they know anything.
