### ISSUE TITLE
PEP missing latest upcoming-dividend data

### ISSUE THREAD

**Issue by WillTron** [iexg/IEX-API#1494]
**Clearly describe the data problem**
PEP declared their second quarter dividend on 5-5-20. the "upcoming-dividends" EP has no entry for the upcoming dividend. the EP data has been missing for well over a week.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=pep&types=upcoming-dividends&token=my_token

**What time did the problem occur (including timezone)?**
today (MST) around 10:30 am but the data has been missing for over a week

**What is the expected behavior?**
the /upcoming-dividends EP should return the latest declared dividend. for PEP the latest declared date is 2020-05-05. the ex-Date (2020-06-04) is still in the future as of today, so the announced dividend data should appear in the /upcoming-dividends EP

**What are the steps to reproduce**
run above API call (before 2020-06-04)

**Your environment (e.g. browser, OS, API version, language):**
latest Chrome, Win10 Pro, IEX Cloud v1, PHP/Python, Launch Plan

**Additional context**
API output:
```
{
  "PEP": {
    "upcoming-dividends": []
  }
}
```

**Comment by McQgit** [comment]
Further to @WillTron , right now there are only 13 upcoming dividends using:
https://cloud.iexapis.com/v1/stock/market/upcoming-dividends?token=XX&format=csv

Earlier today, at 6am eastern, there were at least 275 upcoming dividends using this same endpoint.

I'll note that PEP was available on this endpoint earlier this month when it was announced.  But, I agree with Will that it isn't showing right now - along with hundreds of others.

**Comment by WillTron** [comment]
I agree with @McQgit regarding PEP. the upcoming div data was there earlier in the month and then the data was hit-and-miss depending on when you did the API call -- seemed random. The last two times I checked for PEP in the past week it had missing data for upcoming-dividends, so apparently the randomness is continuing for PEP and others. .... PEP is still responding with an empty data object as of 9:45am MST today.

**Comment by evancarter-iex** [comment]
Fixed.
