### ISSUE TITLE
[Issue] earnings "last" parameter has no effect

### ISSUE THREAD

**Issue by vahtos** [iexg/IEX-API#1495]
Per the documentation [(IEX Cloud Doc),](https://iexcloud.io/docs/api/#earnings) this should give the last 2 quarters of earnings for AAPL:
https://sandbox.iexapis.com/stable/stock/aapl/earnings?last=2&token=Tsk_b70a58b87bc94ace8e74fd00b27782a0

However, this returns only the last 1 earnings data:

> {"symbol":"AAPL","earnings":[{"actualEPS":2.58,"consensusEPS":2.29,"announceTime":"MAC","numberOfEstimates":33,"EPSSurpriseDollar":0.3,"EPSReportDate":"2020-04-26","fiscalPeriod":"Q1 2020","fiscalEndDate":"2020-03-22","yearAgo":2.57,"yearAgoChangePercent":0.038,"currency":"USD"}]}

**Comment by oliveirard** [comment]
I have the same problem (tried demo and my apikey). If anyone figures out how to use "last" for the earnings endpoint or if IEX Cloud fixes it, please let us know.

**Comment by oliveirard** [comment]
I understand it now. Reading the documentation, it turns out "Earnings prior to last quarter are only included with paid subscription plans"

**Comment by vahtos** [comment]
> I understand it now. Reading the documentation, it turns out "Earnings prior to last quarter are only included with paid subscription plans"

I don't think it is that simple. I am using the sandbox api, it should function the same as a paid subscription, they just randomize some data. So either way this should be returning more than just the last quarter's earnings.

**Comment by vblagoje** [comment]
Yeah, you need a paid plan. I had the same issue, subscribed, everything worked as advertised.

**Comment by vahtos** [comment]
That's fine. But then the bug is needing a paid subscription for the sandbox to function correctly.
