### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by serhito70** [iexg/IEX-API#1497]
Hi,
I am new to IEX and trying to understand how it all work. But before I dig deeper, I just want to let you know if that will be what I need at a decent cost.
All I need is to pull the 1hr stochastic for a list of stocks, but just during trading hours. 
I tried in excel for one stock but it gave me the whole historical when I just need the last value.
As a result, my number of messages was huge for just one request. 
I am using excel, so is there a way to just get the last stochastic value and therefore the amount of messages ?
If you dont mind, could you please tell me how I would request that ? I need the 14,3,3 parameter as well. I might also consider pulling the 4hr and daily stochastic as well.
"https://sandbox.iexapis.com/stable/stock/twtr/indicator/stoch?range=ytd&token=MYTOKEN

Thanks for your help.

Serge

**Comment by evancarter-iex** [comment]
If this is still a question please reach out to support@iexcloud.io for more help.
