### ISSUE TITLE
Question: Keeping database up to date with stock fundamentals

### ISSUE THREAD

**Issue by smartstoic** [iexg/IEX-API#1499]
Hello all,

I would like to keep my database up to date with stock fundamentals: BalanceSheet, Earnings, CashFlow and Income Statement. These endpoints are expensive to probe in order to check if the returned date/values are different to the latest in my database.

What is the proper flow which allows me to know that there is new data on these endpoints?

Best regards
smartstoic

**Comment by McQgit** [comment]
@smartstoic  One idea is to poll only when you expect new data.  For example, use 
` stock/{$tkr}/upcoming-earnings` endpoint (very cheap)
and start polling daily on that date until it is updated.  Then quit polling until the next earnings date.

I vaguely remember someone saying there is a way to be pushed notices but I don't remember the details of that.  Perhaps search this git or the docs.

**Comment by joshuablackburn-iex** [comment]
We have a couple methods. One solution we’ve developed is Cloud Cache. It allows you to query the API as often as you need and only pay the full message rate when data changes. 

Another method is to use our Data Points endpoint. We publish the current financials date, so you can compare with what you’ve already downloaded. 

Lastly, you can try our Rules Engine. Currently in beta, but it allows you to set up a rule and get notified when it passes. So, you could create a rule against all symbols that executes when the next financials available event triggers. We have integrations like webhooks, email, sms, google functions, slack, etc.

**Comment by smartstoic** [comment]
Thank you both for the responses.

@joshuablackburn-iex , I have a few follow up questions. It looked like the DataPoints endpoint could solve my issue but after randomly checking the following:

https://cloud.iexapis.com/stable/data-points/csco
https://cloud.iexapis.com/stable/data-points/aapl
https://cloud.iexapis.com/stable/data-points/msft

I see that the 'lastUpdated' field shows today's date for almost all keys. I doubt it that the values of all the fields changed since yesterday. Can you please elaborate?

Cloud Cache is a nice solution but super expensive for my one man show. According to your examples, you can only connect 1 stock per slot. Polling multiple stocks gets very expensive.

I also tried the graphical interface of the Rules Engine but my understanding is that you cannot create a rule for a group of stocks but only individually. I would need to play with this option a bit more. Please correct me if I am wrong. Also, I assume that the flow for this option is to eg create a rule for "Revenue" and when an alert is sent, go to the income endpoint to get the changed values. Is this correct?

**Comment by joshuablackburn-iex** [comment]
For data points, the easiest way to see what is available is to use the search in your console. Search for a symbol, then scroll down to the table. If you click the name of the data point, it will make the call and show the value. Last updated is the last time we refreshed the data, but the actual data point may be the same. 

Rules can be created for all symbols. When you’re on the first step, just click on the box and select “Any Symbol”. That execute your rule for every symbol. If you choose an integration like webhook, we will post a json object with the rule data. On the last step, you can choose additional data that was not part of your rule, and that will be sent to you as well.

**Comment by McQgit** [comment]
@smartstoic An example api for what Josh said:
https://cloud.iexapis.com/stable/data-points/MSFT/LATEST-FINANCIAL-REPORT-DATE?token=(token)

The response should be 2020-03-31 (which was a 10-Q)

The url you gave earlier was a free endpoint to list all data items.  There are also data-points for annual and quarterly dates if you want those specifics.  See the list you got back from your sample url.

**Comment by smartstoic** [comment]
Thank you both,

@McQgit this is example what I need. Thanks for helping out.
