### ISSUE TITLE
Is it possible to provide an API, which returns history of dividend payment of a stock?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#15]
Hi, I was wondering, whether is it possible for IEX to provide an API, which returns history of dividend payment of a stock?

The reason is that, we plan to provide an auto dividend feature (instead of input manually by users), for our portfolio management tool - https://play.google.com/store/apps/details?id=org.yccheok.jstock.gui&hl=en

Thank you very much!

**Comment by joshuablackburn-iex** [comment]
This feature is currently in testing.

**Comment by joshuablackburn-iex** [comment]
Dividends and Splits are available.  We will update the documentation later today.  They follow the same time range syntax as Chart.

https://api.iextrading.com/1.0/stock/aapl/dividends/2y
https://api.iextrading.com/1.0/stock/aapl/splits/5y
