### ISSUE TITLE
Question: Dividend Frequency

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#150]
## Summary
Is there a direct way to return dividend frequency? If not, can this please be put in the Enhancement queue?
I'm currently dividing {.../stats?filter=dividendRate} by {.../dividends/1Y?filter=" & amount}, but this will be incorrect for cases where the dividend has changed throughout the year.

Thank you.

**Comment by evancarter-iex** [comment]
Closing. This is fixed in IexCloud https://iexcloud.io
