### ISSUE TITLE
Interval for us no utp ssestream

### ISSUE THREAD

**Issue by argo1089** [iexg/IEX-API#1500]
Is there a way to provide intervals to the https://cloud-sse.iexapis.com/stable/stocksUSNoUTP endpoint in the same way they are provided here: https://cloud-sse.iexapis.com/stable/stocksUS5Second

**Comment by evancarter-iex** [comment]
Yes just use https://cloud-sse.iexapis.com/stable/stocksUSNoUTP1Second etc.
