### ISSUE TITLE
[Data] historical data constantly fails for some tickers and returns empty array

### ISSUE THREAD

**Issue by pps83rbx** [iexg/IEX-API#1501]
For example, this one returns empty data (eg `[]`):
https://cloud.iexapis.com/stable/stock/GOOGL/chart/date/20200528?token=xxx

While this one returns data for AAPL on the same date with no issues:
https://cloud.iexapis.com/stable/stock/AAPL/chart/date/20200528?token=xxx

There must have been some serious regression in last few weeks.

**Comment by evancarter-iex** [comment]
This is resolved.
