### ISSUE TITLE
[Issue] Search API endpoint is returning empty array

### ISSUE THREAD

**Issue by whitewolf92** [iexg/IEX-API#1503]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**
Help!!! https://sandbox.iexapis.com/stable/search/microsoft?token={########}

is not returning any search result. Both sandbox and production are returning empty array!!!!

**What time did the problem occur? (with timezone)**
5pm GMT+8

**What is the expected behavior?**
Return search result

**Your environment (e.g. browser, OS, API version, language):**
Chrom

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/search/msft

**What are the steps to reproduce the bug?**
Call search api

**Additional context**

**Comment by laimis** [comment]
I can confirm I see the same in production as well (and your API console site):

https://cloud.iexapis.com/stable/search/stitch?token=...

returns empty array.

Our users reported this yesterday and it seems like this is still happening today.

**Comment by gregorycarter** [comment]
I can also confirm I'm seeing this.  I emailed the support desk...

**Comment by christiankm** [comment]
Same problem here!

**Comment by stammy** [comment]
Same problem here, noticed it yesterday evening.

**Comment by gregorycarter** [comment]
This is now working for me again - you can check sandbox here: https://sandbox.iexapis.com/stable/search/apple?token=Tsk_cb5d5b9114d44dec920bc127b277be2d

**Comment by whitewolf92** [comment]
Yes, it fixed now. I hope it doesn't happen again :( cause this brought me quite a fair bit of disgrunted users.

**Comment by whitewolf92** [comment]
Does IEX personnel want to comment what happen on weekend? If not, i will just close the issue.
