### ISSUE TITLE
Endpoint "/chart/date/20190109" returns incorrect data when using "chartLast=true"

### ISSUE THREAD

**Issue by MattAbar** [iexg/IEX-API#1504]
**Clearly describe the problem**

The `chart` endpoint with `date` range and `chartLast=##` parameter ignores the specified date.

For example...

[https://cloud.iexapis.com/stable/stock/twtr/chart/date/20190109?token=pk_XXX&chartByDay=true&chartLast=3&chartCloseOnly=true&filter=date,close,volume](https://cloud.iexapis.com/stable/stock/twtr/chart/date/20190109?token=pk_XXX&chartByDay=true&chartLast=3&chartCloseOnly=true&filter=date,close,volume)

...ignores the specified `2019-01-07` date and incorrectly returns current-day prices:

```
[
  {
    "date": "2020-06-03",
    "close": 34.88,
    "volume": 28396335
  },
  {
    "date": "2020-06-04",
    "close": 33.72,
    "volume": 20265079
  },
  {
    "date": "2020-06-05",
    "close": 34.87,
    "volume": 23211535
  }
]
```

**What is the expected behavior?**

Should return prices as-of the specified date of `2019-01-07`.

**API URL (if applicable)**

https://cloud.iexapis.com/stable/stock/twtr/chart/date/20190109?token=pk_XXX&chartByDay=true&chartLast=3&chartCloseOnly=true&filter=date,close,volume

**Comment by nanovationlabs** [comment]
I have the same problem. I would like to retrieve daily chart data between two dates but that option is not there. So at least I though I would be able to select a date and then tell it to retrieve the last N elements and then saying chartByDay that would mean I could get last N days worth of data from date.

But the api call does not seem to work.

Let's say I want to retrieve the las 10 days of data in 1 day candle for Twitter from march 10 2020.

I would do this API Call:

https://cloud.iexapis.com/stable/stock/twtr/chart/date/20200310?chartLast=10&chartByDay=true&token={your_token}

Yet this will return the last 10 day candles from current date and not from march 10th 2020.

If I remove the chartByDay=true then the api call works fine but will return data on a minute scale meaning will return 10 candles of 1 minute each for march 10th 2020.

Either this needs fixing or some other end point so we can retrieve candle data between dates or at least say a date and then how many candles and in what interval (1 minute or 1 day) we want to get.

**Comment by evancarter-iex** [comment]
Fixed.
