### ISSUE TITLE
[Issue] Reason: header ‘user-agent’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response

### ISSUE THREAD

**Issue by awarmfastbear** [iexg/IEX-API#1505]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**

I am making an API call to the IEX Sandbox API when my Reactjs app loads in a browser. Firefox throws a CORS error from the preflight response from IEX, Chrome does not. Firefox makes the request to the IEX API using an OPTIONS request and Chrome makes a GET request.

Apparently Firefox is the one compliant according to [this](https://stackoverflow.com/a/32262532/6448312)

Full error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sandbox.iexapis.com/stable/stock/market/batch?symbol…,SBUX&types=price&token=Tpk_2f78524e534.....24b5.

(Reason: header ‘user-agent’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).
```

**What is the expected behavior?**

The API call should succeed

**Your environment (e.g. browser, OS, API version, language):**
Firefox 77
Chrome 83

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/stock/market/batch?symbols=AAPL,MSFT,NFLX,TSLA,SBUX&types=price&token=Tpk_2f78524e5345.......c327e24b5

**What are the steps to reproduce the bug?**

Visit this in Firefox: [http://mofi.nonset.com/investments](http://mofi.nonset.com/investments)

Then look in your browser dev tools console in Firefox and you'll see the CORS issue. Clicking the button on the page 'List Stocks' will generate new options requests with the CORS error.

If you visit the link in Chrome you should see white boxes showing stock symbols and their prices which resolved from the API call to IEX.

**Additional context**

I've Googled all over, made changes to my Nginx config which is hosting the site but I can't figure out if this is something on my side or an issue with CORS on IEX's side. 

If I modify the Firefox request and make it a GET request, the API call succeeds. But that's not the default behavior, it should be an options request per compliance.

Can someone from IEX help debug this? This would be good to have in your documentation for other developers :)

I am using this 3rd party IEX Nodejs library which uses Fetch to make the API calls to IEX: https://github.com/JBooker10/node-iex-cloud

**Comment by awarmfastbear** [comment]
I think I am going to re-architect and use my own backend proxy to make the requests to IEX and pass it back to the client. I don't believe it's secure to allow the IEX tokens to be sitting in the clients local network traffic.

**Comment by timpaine-iex** [comment]
this is on your side, the web server serving your react app needs to allow cors. if you're serving your react site statically via nginx, here is a [wide open config](https://enable-cors.org/server_nginx.html). 

Unrelated, but @JBooker10's library is for `node` (e.g. server, leveraging `node-fetch`) whereas your react application is running in the browser and should use native `window.fetch`.
