### ISSUE TITLE
[Data] Quote endpoint "open" not available until market close

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1506]
**Clearly describe the data problem**
During the day, "open" is always null when calling a quote

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/quote?symbols=GOOGL&token={TOKEN}

**What time did the problem occur (including timezone)?**
During market

**What is the expected behavior?**
"open" to have the correct opening value of the stock 

**What are the steps to reproduce**
Call the link above when markets are open 

**Your environment (e.g. browser, OS, API version, language):**
Browser

**Comment by McQgit** [comment]
@DavidKuennen  Have you seen this?
https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud

**Comment by DavidKuennen** [comment]
Oh, thank you very much for this information. Do you know how much UTP authorization costs?

**Comment by McQgit** [comment]
@DavidKuennen I have no experience with that.  Perhaps search the git for UTP - someone else may have said.

**Comment by joshuablackburn-iex** [comment]
You’ll need to reach out to UTP. I do know their price schedule has $250 a year and $250 a month for different use cases, but they will need to answer that.
