### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Neeraja456** [iexg/IEX-API#1507]
We are evaluating stock charts from IEX cloud API.
We were required to show intraday Prices in 30min intervals. During Non trading day it should display previous day details. I am using following URL
https://cloud.iexapis.com/stable/stock/MCHP/intraday-prices?token=
but here it will display intraday price for one minute intervals, but we want to display  intraday prices in 30 min intervals. Please let us know how to get this.

**Clearly describe the problem**
Its displaying prices for 1 min intervals

**What is the expected behavior?**
Should display intraday prices for 30min intervals. During Non trading day it should display previous day details

**Comment by Pfuster12** [comment]
Hi, please read the [API docs ](https://iexcloud.io/docs/api/#intraday-prices) carefully for intraday prices:

chartInterval | • Optional  If passed, chart data will return every Nth element as defined by chartInterval
-- | --

So adding `chartInterval=30` will return every 30 min element.

https://cloud.iexapis.com/stable/stock/MCHP/intraday-prices?chartInterval=30&token=<token>

Also, don't show your API token so publicly.
