### ISSUE TITLE
Incorrect SNP Market Cap

### ISSUE THREAD

**Issue by pwenke** [iexg/IEX-API#1512]
Problem
At some point around 5/27/20 or 5/28/20, the market cap for SNP jumped from $11B to $17T.  I believe this is incorrect.

Example (symbol, previous market cap data, incorrect market cap data):
SNP
11,613,699,680
17,045,614,248,000

Data URL
https://cloud.iexapis.com/v1/stock/{symbol}/quote
https://cloud.iexapis.com/stable/stock/{symbol}/quote

Date / Time
SNP is still reporting a market cap of $17T as of 6/11/20 CST

Expected Behavior
As far as I know, the SNP market cap is around $65B, not $17T

Steps to Reproduce
https://cloud.iexapis.com/stable/stock/SNP/quote

Environment
Chrome
Windows 10
Both v1 and stable API
ColdFusion

Thanks,
Pat

**Comment by evancarter-iex** [comment]
Fixed.
