### ISSUE TITLE
[Issue] The Basic Dividends Endpoint only ever returns 1 dividend, even when there are multiple dividends

### ISSUE THREAD

**Issue by tashburn** [iexg/IEX-API#1513]
When performing the request `/stock/HYG/dividends/5y`, I expect many dividends. There's only 1 dividend returned --

```
[{"exDate":"2015-07-01","paymentDate":"2015-07-08","recordDate":"2015-07-06","declaredDate":"2015-06-30","amount":"0.394715000","flag":"Cash","currency":"USD","description":"BTC iShares iBoxx USD High Yield Corporate Bond ETF","frequency":"monthly","date":"2020-06-11"}]
```

All the other symbols I've tried only ever return 1 symbol, or 0 symbols.

When I try this endpoint again with HYG and range `3y`, it returns 0 results. With range `1y`, it returns 1 result. It's broken!

**Comment by McQgit** [comment]
@tashburn   range=3y is not valid.  See the docs (5y, 2y, ...)
https://iexcloud.io/docs/api/

Dividends prior to the last are only included with paid plans:
https://iexcloud.io/docs/api/#dividends-basic
