### ISSUE TITLE
[Request] `/search` does not return results from all available exchanges

### ISSUE THREAD

**Issue by christiankm** [iexg/IEX-API#1515]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Is your feature request related to a problem? Please describe.**
You could say that. When calling the `/search` endpoint the API will only return results from the IEX Exchange. But it seems impossible to search for symbols in international exchanges, or options, mutual funds, etc, without doing a lot of manual work.

**Describe the solution you'd like**
I would expect that `/search` returns results from all available data sources (exchanges). Right now, I would need to download all reference data, and then search in that in my app. I cannot rely or really use your `/search` endpoint, as it will not return many symbols.

**Describe alternatives you've considered**
Manual download of symbols, and searching in local files.

**Additional context**

**Comment by joshuablackburn-iex** [comment]
The search endpoint returns values for all 90k+ symbols, including global.

**Comment by christiankm** [comment]
Doesn’t seem so for me, but let me dig deeper and I’ll get back to you with some examples!

**Comment by gregorycarter** [comment]
I'm also having an issue with this search endpoint (again).  It has not been returning the 'name' data for international stocks.  Eg:
<img width="502" alt="Screenshot 2020-06-17 at 10 47 44" src="https://user-images.githubusercontent.com/46213/84883179-26219f80-b088-11ea-8caf-d72d54702cf0.png">

**Comment by christiankm** [comment]
> The search endpoint returns values for all 90k+ symbols, including global.

You're totally right. My apologies. I had a bug in my app that would filter some results away.
