### ISSUE TITLE
sentiment endpoint returning {} for newer data

### ISSUE THREAD

**Issue by blazespinnaker** [iexg/IEX-API#1516]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

I ran two api calls with my growth account secret token:

curl "https://cloud.iexapis.com/v1/stock/aapl/sentiment/daily/20200602?token=sk_..
{}
curl "https://cloud.iexapis.com/v1/stock/aapl/sentiment/daily/20200601?token=sk_
{"sentiment":0.07860683229813664,"totalScores":161,"positive":0.87,"negative":0.13}

Note the only difference is one is june 1st (which works) and the other is june 2nd (which just gives {})

**What time did the problem occur? (with timezone)**
June 17th, 8:06pm PST

**What is the expected behavior?**
I expected sentiment data for the june 2nd date like I got for the june 1st date, but just got {}

**Your environment (e.g. browser, OS, API version, language):**
curl / linux

**API URL (if applicable)**
https://cloud.iexapis.com/v1/stock/aapl/sentiment/daily/20200601

**What are the steps to reproduce the bug?**
As per above

**Additional context**

**Comment by blazespinnaker** [comment]
Got feedback from support this is no longer offered.  Please update the docs ASAP for future users.

**Comment by ahoin001** [comment]
were you able to find another api for this specific task?

**Comment by joshuablackburn-iex** [comment]
There is already a note in the docs. We are working to bring back this data which may be available as a premium data set.
