### ISSUE TITLE
Documentation should have link to open an account

### ISSUE THREAD

**Issue by samboustani** [iexg/IEX-API#1517]
The following page under Authentication says that you need an account to use the API.
https://addisonlynch.github.io/iexfinance/stable/configuration.html#config-auth

**Describe the solution you'd like**
The sentence should be a link to where one can open an account, which is obviously somewhere outside the documentation.

**Comment by McQgit** [comment]
@samboustani That's a 3rd party site.  The IEX people have no control over it.

The IEX main site is https://iexcloud.io/
