### ISSUE TITLE
[Data] Missing historical pricing for Sanofi in FR market

### ISSUE THREAD

**Issue by sinecureio** [iexg/IEX-API#1519]
Hi IEX,

The endpoint https://cloud.iexapis.com/stable/stock/SAN-FP/chart/max?chartCloseOnly=true&token=token returns an empty array.

However, querying only last year returns the correct results: https://cloud.iexapis.com/stable/stock/SAN-FP/chart/1y?chartCloseOnly=true&token=token

The query also returns empty array for 2y and 5y.

Thanks!

**Comment by soufianekhoudmi** [comment]
I have the same issue with some french stocks @sinecureio 
Did you found a workaround?
