### ISSUE TITLE
Expose Capital Expense Spending in Financials or provide calculation of Free Cash Flow

### ISSUE THREAD

**Issue by ktemby** [iexg/IEX-API#152]
## Summary
When I'm looking at a company I want to see the Free Cash Flow, rather than just Cash Flow, so that I have a better picture of company health and ability to meet obligations.

## Details
"Free Cash Flow" which is cash flow minus capital expense doesn't seem to be available, since Capital Expense isn't available in the API

Right now "Cash Flow" for the trailing 4 quarters is available with 
https://api.iextrading.com/1.0/stock/AAPL/financials?filter=cashFlow

Ideally either an API call like 
https://api.iextrading.com/1.0/stock/AAPL/financials?filter=freeCashFlow

Would provide the following 4 quarters of free cash flow, or a call like 
https://api.iextrading.com/1.0/stock/AAPL/financials?filter=capitalExpense

Would include the last 4 quarters of reported Capital Expense, which could be subtracted from Cash Flow to calculate Free Cash Flow.

### Date/time of issue
12/27/2017

### API URL
https://api.iextrading.com/1.0/stock/AAPL/financials?

### What you expected to happen
I expected that Free Cash Flow would be provided.

### What actually happened
Only 'Cash Flow' was provided in the API.

### Other Information (sample code, links, etc.)
In the 'key ratios' in Morningstar for example, both Cap Spending, and Free Cash Flow are shown.
http://financials.morningstar.com/ratios/r.html?t=AAPL&region=usa&culture=en-US

**Comment by timpaine-iex** [comment]
closing as stale
