### ISSUE TITLE
Indicator Endpoint 

### ISSUE THREAD

**Issue by fjinvestments** [iexg/IEX-API#1520]
Hi everyone, 

I have an issue regarding our indicator endpoints, hope you can help. 

When I go to make the api call to grab the most recent stochastic value of symbol X, I get an entire daily read of every stochastic value in an array, and then the entire chart data for that symbol for that day. The problem is that to continually check the most recent stochastic values for multiple symbols, I'm going to blow through all my allocated API calls for the month very quickly. I get the data I want, but the extra calls being made is not feasible for the strategy we are running. Is there a way to just get the stochastic values for a symbol without redundantly making calls for the day's worth of chart data, or even better just the most recent stochastic value? Let me know if that's possible.

**Comment by evancarter-iex** [comment]
Please reach out to support@iexcloud.io if this is still an issue.

**Comment by Admin-NWIF** [comment]
Hey @fjinvestments did IEX support provide a solution for this? I'm having a similar issue, can't really use any strategy based on technical indicators with IEX if its making 20,000+ API calls per indicator request.
