### ISSUE TITLE
[Data] Extra entry for 6/26/2020

### ISSUE THREAD

**Issue by a-scales** [iexg/IEX-API#1521]
When making a request to `https://sandbox.iexapis.com/stable/stock/DIA/chart/5y` in the sandbox environment, we get an extra entry for June 26th, 2020.
`https://sandbox.iexapis.com/stable/stock/DIA/chart/5y` returns 
```
...
  {
    "date": "2020-06-26",
    "close": 260.18,
    "volume": 5597882,
    "change": -7.29,
    "changePercent": -2.8506,
    "changeOverTime": 0.43069
  },
  {
    "date": "2020-06-26",
    "close": 258.88,
    "volume": 5445477,
    "change": 0,
    "changePercent": 0,
    "changeOverTime": 0.42917
  },
...
```

This first occurred today, 6/30/2020 around 11am EDT. 

I would expect this endpoint to return one data point for each day. However, we get a single extra day for 6/26. Just making the same request for `https://sandbox.iexapis.com/stable/stock/DIA/chart/5y` or `https://sandbox.iexapis.com/stable/stock/QQQ/chart/5y` both return the extra day in sandbox.
Including `chartInterval` or `chartByDay` parameters don't change the result.

**Comment by a-scales** [comment]
I just ran the same request in production and got the same result
```
  {
    "date": "2020-06-26",
    "uClose": 250.38,
    "uOpen": 255.65,
    "uHigh": 256.05,
    "uLow": 249.7,
    "uVolume": 5331447,
    "close": 250.38,
    "open": 255.65,
    "high": 256.05,
    "low": 249.7,
    "volume": 5331447,
    "currency": "",
    "change": -7.06,
    "changePercent": -2.7424,
    "label": "Jun 26, 20",
    "changeOverTime": 0.42407
  },
  {
    "date": "2020-06-26",
    "uClose": 250.38,
    "uOpen": 255.65,
    "uHigh": 256.05,
    "uLow": 249.7,
    "uVolume": 5331447,
    "close": 250.38,
    "open": 255.65,
    "high": 256.05,
    "low": 249.7,
    "volume": 5331447,
    "currency": "",
    "change": 0,
    "changePercent": 0,
    "label": "Jun 26, 20",
    "changeOverTime": 0.42407
  },
```

**Comment by mjw2194** [comment]
I appear to have the same issue when making the analogous requests (5Y Price History) for AAPL, ABBV, and ABT

**Comment by a-scales** [comment]
The IEX team got back to me and it seems like they fixed it (for now)

**Comment by mjw2194** [comment]
Thx!
