### ISSUE TITLE
[Data]  Wrong last annual value for NetIncome for JCI

### ISSUE THREAD

**Issue by poturaev** [iexg/IEX-API#1526]
I see wrong last annual value for NetIncome for JCI symbol.

`{"symbol":"JCI","financials":[{"reportDate":"2019-09-30","fiscalDate":"2019-09-30","currency":"USD","grossProfit":7701000000,"costOfRevenue":16267000000,"operatingRevenue":23968000000,"totalRevenue":23968000000,"operatingIncome":1443000000,"netIncome":474000000,"researchAndDevelopment":319000000,"operatingExpense":22525000000,"currentAssets":12283000000,"totalAssets":42287000000,"totalLiabilities":21458000000,"currentCash":2821000000,"currentDebt":511000000,"shortTermDebt":511000000,"longTermDebt":6708000000,"totalCash":2821000000,"totalDebt":7219000000,"shareholderEquity":19766000000,"cashChange":2606000000,"cashFlow":1202000000}]}
`
netIncome:474000000

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/JCI/financials?token=mytoken&period=annual

**What time did the problem occur (including timezone)?**
20200708 19:00:00 UTC

**What is the expected behavior?**
Return value 5674000000 instead of 474000000

**What are the steps to reproduce**
Call to URL: https://cloud.iexapis.com/stable/stock/JCI/financials?token=mytoken&period=annual

![image](https://user-images.githubusercontent.com/61711775/86964981-8a0f2380-c16f-11ea-9374-0c5d3814b1fd.png)

**Comment by evancarter-iex** [comment]
Fixed.
