### ISSUE TITLE
[Request] Support limit on collections

### ISSUE THREAD

**Issue by jmarrr** [iexg/IEX-API#1528]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Is your feature request related to a problem? Please describe.**
I am trying to build a screener and using collection endpoint to get top 10 result based on my query per sectors but I am concerned about the data weight I use on huge sectors with 1000+ result which might be called more than once a day so I was looking for a limit feature where a collection should return only specific limit that we set by default just like how `listLimit` and `limit` works on list and news 

**Describe the solution you'd like**
https://sandbox.iexapis.com/stable/stock/market/collection/sector?collectionName=Technology?limit=10&token=

**Comment by timpaine-iex** [comment]
@jmarrr good idea, would you mind submitting it on the [roadmap](https://iexcloud.io/console/roadmap) where others can vote and we can see it alongside other initiatives?

**Comment by DirkGehlich** [comment]
Any news on this?
It is pretty much not usable, when trying to receive all quotes of one sector.
