### ISSUE TITLE
When is split data updated

### ISSUE THREAD

**Issue by brettbs** [iexg/IEX-API#153]
## Summary
First off, awesome API! 

Ticker GGG split today 12/28/2017. When I use https://api.iextrading.com/1.0/stock/ggg/splits/1m I get an empty set. 

// 20171228211944
// https://api.iextrading.com/1.0/stock/ggg/splits/1m

[
  
]

I assume there is a set time when this is updated? When can I safely execute my code to get splits for the previous day?

**Comment by jimmyzzxhlh** [comment]
FYI - I saw that the split shows up now, so it seems like there is a 1-2 day delay...

**Comment by evancarter-iex** [comment]
Splits should show up the next business day.
