### ISSUE TITLE
[Issue] Can't access/see certain pages on console

### ISSUE THREAD

**Issue by negnatz** [iexg/IEX-API#1531]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**
I am having trouble accessing certain pages on the console, including API Tokens, Message Use, and other side panel pages. When I click on those pages, it either appears blank or shows the home content. When I try to refresh the page, I get stuck in an infinite loading screen with the pink loading icon in the center. Sometimes the desired screen shows but it is rare and spotty. 
The home page is normal and shows the desired content. I am currently on the free plan, but am planning to upgrade to a paid subscription. However, I want to make sure I can access these pages again before I pay.

**What time did the problem occur? (with timezone)**
I have noticed it occurring for the past ~1 week or so (EST)

**What is the expected behavior?**
To see API keys and broken down message use as well as other pages on the console besides home.
I am mainly trying to see my API key but see that page at all.

**Your environment (e.g. browser, OS, API version, language):**
I tried using both Chrome and Safari with the same result on each.

**API URL (if applicable)**
https://iexcloud.io/console/tokens (Example page that isn't showing content)

**What are the steps to reproduce the bug?**
Unsure

**Additional context**

**Comment by timpaine-iex** [comment]
@negnatz are there any errors listed in the javascript console (hit F12 or open developer tools to see)

Also are you using ad-blockers/custom stylers like stylish, etc?
