### ISSUE TITLE
get_historical_data() blowing up my message budget

### ISSUE THREAD

**Issue by jlheidecker** [iexg/IEX-API#1535]
`get_historical_data('AAPL', start, end, output_format='pandas', token=iexc_key)`

That call is for one symbol and 5 days, and should cost only 50 messages. The pandas dataframe has the expected 5 days, however, it's costing 2530 messages!

I switched to simple get request and it costs the expected 50 messages.

```
URL = 'https://cloud.iexapis.com/stable/stock/'+symbol+'/chart/5d?token=iexc_key'
response = requests.get(URL).json()
```

**Comment by McQgit** [comment]
@jlheidecker A number of people struggle using that iexfinance python app. It was not developed (and not supported by) the IEX folks. See https://github.com/addisonlynch/iexfinance and especially https://github.com/addisonlynch/iexfinance/issues/197

**Comment by jlheidecker** [comment]
Thanks @McQgit . I didn't realize I was posting on the wrong Github.

**Comment by enthusiasttrader** [comment]
So what is a good place to get live data and also historical intraday data for backtesting ?
