### ISSUE TITLE
IEX Cloud: Stock chart values are coming null for close

### ISSUE THREAD

**Issue by Neeraja456** [iexg/IEX-API#1536]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

We are using IEX stock chart value in order to display stock chart for our organisation, Sometimes there will be a lot of null values for close because of that we cant able to get exact value. Is there something you can help on this?
**Clearly describe the data problem**

**Data URL (The URL you used to access the data without your token):**

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
Please reach out to support@iexcloud.io if this is still an issue.
