### ISSUE TITLE
[Issue] Individual symbol problem terminates batch request

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1537]
**Clearly describe the problem**
I made a batch request for intraday-prices with several symbols, one of which was GBTC. I received 451 Unavailable For Legal Reasons for the request and no data. I believe I should have received intraday-prices data for the other symbols requested instead of one symbol terminating the request.

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/market/batch?symbols=GBTC,SPY&types=intraday-prices&chartIEXOnly=true&token=

**Comment by wsywsya119** [comment]
I have the same issue. When I check the symbol below the API
https://cloud.iexapis.com/beta/ref-data/symbols?token={token}

I can't find the GBTC

**Comment by timpaine-iex** [comment]
@wsywsya119 
<img width="1421" alt="Screen Shot 2020-12-28 at 10 30 20 AM" src="https://user-images.githubusercontent.com/74613173/103225343-b1150980-48f7-11eb-8a97-d394942ccc23.png">


@humenick you're doing `chartIEXOnly` and `GBTC` trades OTC

**Comment by humenick** [comment]
@timpaine-iex 

Removing `chartIEXOnly` gives the same error.

The problem is having GBTC included in a list on a batch request kills the batch request for all symbols! I don't care so much that one symbol cannot be returned, I care about missing data for all the other symbols. And if I notice no data is retuned and believe this error is the cause, I have to go through and figure out which symbol in the list caused the error.

Also note, the error message appears to have changed from July, still returning a 451 error, but now with the text: “The requested data requires permission to access.”

The API currently returns nothing for unknown symbols, why not do the same for `GBTC` instead of killing the request? Or return an error message inside the GBTC returned object so the other objects requested can be returned?

**Comment by timpaine-iex** [comment]
@humenick I agree that bad symbols probably shouldn't kill the whole request, but I think its worth thinking through a bit more about the UX around how to indicate that one of the symbols in the batch request didn't work properly. For example, something like a 451 indicates that additional permissions are required (I'm looking into this for `GBTC`, I believe this is a known thing like the [utp authorization requirements](https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud)). For some endpoints, an empty array might indicate that there are no values (e.g. no dividends for the date range), for other endpoints an empty array might indicate that no data is available from the API, and for other endpoints you might get a 404 indicating that a symbol is not known.

So for example if I'm requesting `quote` and `dividends` from the `batch` endpoint, what is the best way to differentiate between `data-available-but-none-for-this-symbol` vs `no-data-available` vs `symbol-not-found` vs `extra-auth-required`?

**Comment by timpaine-iex** [comment]
@humenick are you able to fetch data via e.g. `chart` for GBTC? there are two someone unrelated issues here, one is batch failing if any sub-request fails, the second is you not being able to access data for GBTC

**Comment by timpaine-iex** [comment]
changing name and reopening

**Comment by timpaine-iex** [comment]
@wsywsya119 hiding our discussion here and moving to other issue

**Comment by kewur** [comment]
This is a blocker for me as well. I am batching 100 symbols together and failing on a single one. I can "batch" requests by 1, effectively not having this issue anymore, but I don't believe it would be beneficial for anyone to ddos IEX cloud with single symbol lookups.

Perhaps we can return a "206 partial content"  with a field of errors in the batch response that could potentially look like this?

`
{
   "AAPL": {
      "intraday-prices": [ //data
      ],
   "errors": [
      "GBTC": {
         "errorMessage": "451 Legal reasons"
      }
   ]
}`

**Comment by timpaine-iex** [comment]
@kewur this is a good idea, I will circulate it a bit internally

**Comment by humenick** [comment]
Here are some responses I get for GBTC:

https://cloud.iexapis.com/stable/stock/GBTC/intraday-prices?token=
https://cloud.iexapis.com/stable/stock/market/batch?symbols=GBTC,SPY&types=intraday-prices&token=
`The requested data requires permission to access.`

https://cloud.iexapis.com/stable/stock/GBTC/quote?token=
https://cloud.iexapis.com/stable/stock/market/batch?symbols=GBTC,SPY&types=quote&token=
`{
symbol: "GBTC",
companyName: "Grayscale Bitcoin Trust",
primaryExchange: "OTCQX MARKETPLACE",
calculationPrice: "previousclose",
open: null,
openTime: null,
openSource: "official",
close: null,
closeTime: null,
closeSource: "official",
high: null,
highTime: null,
highSource: null,
low: null,
lowTime: null,
lowSource: null,
latestPrice: 32,
latestSource: "Previous close",
latestTime: "December 31, 2020",
latestUpdate: 1609390800000,
latestVolume: 0,
iexRealtimePrice: null,
iexRealtimeSize: null,
iexLastUpdated: null,
delayedPrice: null,
delayedPriceTime: null,
oddLotDelayedPrice: null,
oddLotDelayedPriceTime: null,
extendedPrice: null,
extendedChange: null,
extendedChangePercent: null,
extendedPriceTime: null,
previousClose: 32,
previousVolume: 14220908,
change: 0,
changePercent: 0,
volume: 0,
iexMarketPercent: null,
iexVolume: null,
avgTotalVolume: 14397384,
iexBidPrice: null,
iexBidSize: null,
iexAskPrice: null,
iexAskSize: null,
iexOpen: null,
iexOpenTime: null,
iexClose: null,
iexCloseTime: null,
marketCap: 19410918400,
peRatio: null,
week52High: 32.9,
week52Low: 5.54,
ytdChange: 0,
lastTradeTime: 1609785974323
}`

https://cloud.iexapis.com/stable/stock/GBTC/chart/date/20201231?token=
`{
marketHigh: 32.24,
marketLow: 31.89,
marketAverage: 32.16,
marketVolume: 361851,
marketNotional: 11636244.75,
marketNumberOfTrades: 1457,
marketOpen: 32.24,
marketClose: 31.89,
exchangeType: "OTC",
date: "2020-12-31",
minute: "09:30",
changeOverTime: null,
marketChangeOverTime: -0.01137411620043051
}
...`

https://cloud.iexapis.com/stable/stock/GBTC/chart/date/20201231?chartByDay=true&token=
`{
close: 32,
high: 32.9,
low: 31.15,
open: 32.24,
symbol: "GBTC",
volume: 14220908,
id: "HISTORICAL_PRICES",
key: "GBTC",
subkey: "",
date: "2020-12-31",
updated: 1609468357000,
changeOverTime: 0,
marketChangeOverTime: 0,
uOpen: 32.24,
uClose: 32,
uHigh: 32.9,
uLow: 31.15,
uVolume: 14220908,
fOpen: 32.24,
fClose: 32,
fHigh: 32.9,
fLow: 31.15,
fVolume: 14220908,
label: "Dec 31, 20",
change: 0,
changePercent: 0
}`
