### ISSUE TITLE
Realtime Frequency? & Throttling Criteria?

### ISSUE THREAD

**Issue by jrseriel** [iexg/IEX-API#154]
## Summary
I have two questions that I can't find answers to. The first being; What is the actual frequency in milliseconds of the quotes being updated? I find that quite often alot of the quotes get updated at the same time for seemingly unrelated reasons. Some clarification on the specifications of the realtime data would be very much appreciated.

Secondly, In the API Documentation, its states that you throttle users by their IP but then state that we should be fine making 100 requests per second(1 request per 10 milliseconds). Is this set in stone as the maximum requests we can make per second? Or is this more loose based on how much traffic your systems are receiving. Basically if we follow this rule to the letter, we shouldn't need to worry about being throttled? Also, if we have been throttled in the past, is there anyway to correct the problem and be unthrottled in the future, or is the throttling permanent? Again, any affirmation or correction would be very much appreciated. 

## Details
Seen above as these are non-technical specific.

### Date/time of issue
12/30/2017 3:08AM EST

### API URL
https://api.iextrading.com/1.0/stock/market/batch?types=quote&symbols=aapl

### What you expected to happen
10 millisecond quote update reflections.

### What actually happened
A bunch of unrelated stocks being all updated after several seconds even around high volume trading hours(open,close). And only updating quotes after a certain time has passed.

### Other Information (sample code, links, etc.)
It could just be the nature of the market or the particular stocks I am viewing, again some specifications would be appreciated.

**Comment by joshuablackburn-iex** [comment]
Right now our data is conflated and batched.  We have a number of initiatives in the works to stream updates from our trading system to the API, but non are in place as of now.  

As for throttling, it is currently around 100 per second with bursts allowed.  Throttling is per second, so you will receive 429 statuses until the threshold is reset.  This is a good amount to code to until we release more functionality for HTTP Streaming.
