### ISSUE TITLE
[Issue] International ref-data retunring 400

### ISSUE THREAD

**Issue by kidpollo** [iexg/IEX-API#1542]
##  Welcome to IEX Cloud's Github Community.  

**Clearly describe the problem**
Ref data for international symbols is not working 

**What time did the problem occur? (with timezone)**
Noticed today PST

**What is the expected behavior?**
JSON response

**Your environment (e.g. browser, OS, API version, language):**
any

**API URL (if applicable)**
https://cloud.iexapis.com/stable/ref-data/region/ca/symbols

**What are the steps to reproduce the bug?**
Just go to the url, see a ngnx 400 page

**Comment by timpaine-iex** [comment]
@kidpollo I can't repro, are you including your token in the request?
