### ISSUE TITLE
Missing latest dividend data for ticker ABM

### ISSUE THREAD

**Issue by WillTron** [iexg/IEX-API#1543]
**Clearly describe the data problem**
The /dividends/ EP is failing to report the latest announced dividend for ABM. returned json lists the March dividend declared date as the most recent, but ABM has a more timely declared dividend for July.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=abm&types=dividends&range=1y&token=my_token

**What time did the problem occur (including timezone)?**
4:30PM MST, but the data has been missing since at least last week

**What is the expected behavior?**
Since the ex-Date is in the past, the most recent dividend data should appear in the /dividends/ EP. the most recent declared dividend should be:

        "exDate": "2020-07-01"
        "paymentDate": "2020-08-03"
        "recordDate": "2020-07-02"
        "declaredDate": "2020-06-17"
        "amount": "0.185"

**What are the steps to reproduce**
run above API call

**Your environment (e.g. browser, OS, API version, language):**
latest Chrome, Win10 Pro, IEX Cloud v1, PHP/Python, Launch Plan

**Additional context**
api json output:
```
{
  "ABM": {
    "dividends": [
      {
        "exDate": "2020-04-01",
        "paymentDate": "2020-05-04",
        "recordDate": "2020-04-02",
        "declaredDate": "2020-03-04",
        "amount": "0.185",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-07-27"
      },
      {
        "exDate": "2019-12-31",
        "paymentDate": "2020-02-03",
        "recordDate": "2020-01-02",
        "declaredDate": "2019-12-18",
        "amount": "0.185",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-07-27"
      },
      {
        "exDate": "2019-10-02",
        "paymentDate": "2019-11-04",
        "recordDate": "2019-10-03",
        "declaredDate": "2019-09-05",
        "amount": "0.18",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-07-27"
      }
    ]
  }
}
```

**Comment by evancarter-iex** [comment]
Closing as Stale.
