### ISSUE TITLE
Free Account & 50,000 core messages/mo

### ISSUE THREAD

**Issue by suchislife801** [iexg/IEX-API#1544]
**Clearly describe the problem**

You promise 50,000 Core API calls on the free account

**What time did the problem occur? (with timezone)**

When I realized your sandbox API returns mangled data???? WTF?

**What is the expected behavior?**

50,000 free CORE API CALLS. NOT SANDBOX API CALLS.

**Your environment (e.g. browser, OS, API version, language):**

A browser.

**API URL (if applicable)**

https://sandbox.iexapis.com/stable/stock/aapl/dividends/ytd?token=

**What are the steps to reproduce the bug?**

Sign Up then realize you can't see mangled data.

**Additional context**

Why? Just why?

**Comment by joshuablackburn-iex** [comment]
Please read our docs closely. First, we do not measure based on API calls, but on messages which is our system for offering over 200 datasets under one contract. 

The sandbox is a free test environment we offer devs to do integration tests. We give you unlimited use of the sandbox at no cost. We also provide millions of real time price updates for free through IEX real time data. The 50k messages on the free plan is available for you to use against any dataset you choose. How many api calls you get depends on the type of data you choose to use.

**Comment by suchislife801** [comment]
So you've closed the question but no where in it, you describe where is the API Key the 50,000 Requests. Where is it? I still don't know. Where is it generated?

**Comment by joshuablackburn-iex** [comment]
Log into the console and go to the API Tokens tab. This is covered in our welcome email and our help documents if you need further assistance.
