### ISSUE TITLE
Getting security class from IEXCloud (e.g. equity, fixed income, commodity, foreign, large/mid/small cap, developed/emerging markets)

### ISSUE THREAD

**Issue by petr-nazarov** [iexg/IEX-API#1546]
Hi!
My name is Petr, and we use IEXCloud on the team.
My team has been looking for a way to obtain the asset classification (for stocks, ETFs, etc.) and have been unable to do so through the API

We would like to input a symbol and receive an output telling us if it's classified as an equity, fixed income, commodity, etc. (on the top level), as well as identify a subclass (e.g., foreign, large/mid/small cap, developed/emerging markets, etc.)
This seems like very basic information to have about a security, and yet, we can't seem to find it in the API documentation!

**Comment by timpaine-iex** [comment]
Top level asset class is returned by the symbols endpoint.

Your second subclass is arbitrary, you can back out region via our ref data endpoints as well but things like "mega/large/mid/small/micro cap" and "developed/emerging markets" are not really reference data but more of classification data.  You can get some industry and region data from the company endpoint, market cap from the key stats endpoint, and we have some new sector and factor data coming in the pipeline. For other specific types of classifications feel free to submit an idea on the [unofficial roadmap](https://iexcloud.io/console/roadmap) and we'll start collecting votes from the community.
