### ISSUE TITLE
Network was slow/down 

### ISSUE THREAD

**Issue by timothydlee** [iexg/IEX-API#1547]
We utilize IEXCloud for retrieving market data and security detail information but we were having major issues over the weekend through Monday morning (Aug 1, 2020 - Aug 3, 2020 morning). 

We were having to wait for 1-2 minutes before we would get a response.

Attached is a screenshot of a call we tried making on Aug 3, 2020 that failed after 1 minute, trying to get Market Data information pertaining to the symbol SIRI:
<img width="858" alt="Screen Shot 2020-08-04 at 3 59 50 PM" src="https://user-images.githubusercontent.com/22381489/89339358-06602e00-d66c-11ea-876a-a91ab3f37884.png">

We also noticed about a month ago, that there were issues pertaining to the Symbol Search endpoint. We are just curious how frequent these issues pop up and how do you alert the parties that are using your product that there is something malfunctioning?

**Comment by joshuablackburn-iex** [comment]
Were you using production or sandbox? The sandbox is less provisioned than the production API and we mention in our docs that it is a shared environment. 

As for alerts, we provide a system status endpoint, system status in the console, and a dedicated system status page. 

We did not get any other reports of slow downs, or internal alerts. It is possible that routes to our system were slow or experiencing issues.

**Comment by timothydlee** [comment]
We were using both, production and sandbox, and noticed the slow down in both.

**Comment by timpaine-iex** [comment]
can't repro, please definitely reach out to us if you notice substantial slowdowns moving forward so we can investigate. The [status page](https://status.iexcloud.io) is also helpful, though its not particularly granular, so when in doubt please reach out.
