### ISSUE TITLE
[Request] Please add Griffin Mining (GFM) to your stock list. Thank you!

### ISSUE THREAD

**Issue by sjm35** [iexg/IEX-API#1549]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please add Griffin Mining (GFM) to your stock list. 

**Describe alternatives you've considered**

**Additional context**

**Comment by timpaine-iex** [comment]
<img width="697" alt="Screen Shot 2020-12-16 at 10 09 08 AM" src="https://user-images.githubusercontent.com/74613173/102366509-bd5ba700-3f86-11eb-96ee-495294646131.png">
