### ISSUE TITLE
open,close values missing in Open-Close endpoint when used with stock/market/ 

### ISSUE THREAD

**Issue by pg1337** [iexg/IEX-API#155]
## Summary
open,close values missing in Open-Close endpoint when used with stock/market/ 

## Details
Open-Close returns only high,low keys instead of open,close,high,low when used with /stock/market/ 
Works correctly for single ticker

### Date/time of issue
7.24 PM IST ( GMT+ 5.5)

### API URL
https://api.iextrading.com/1.0/stock/market/open-close

### What you expected to happen
{"open":{"price":171,"time":1514471400132},"close":{"price":171.08,"time":1514494800281},"high":170.59,"low":169.22}

### What actually happened
{"high":170.59,"low":169.22}

**Comment by evancarter-iex** [comment]
This appears to be working? Are you still seeing this problem?

**Comment by pg1337** [comment]
Sorry replying a late- When used during market hours for /market/, API returns open,high,low during market hours but no Close or LTP field for all symbols
When used during market hours for a single ticker, it returns correctly.

When used off market hours, it returns only High/Low, doesnt return Open/close.

**Comment by joshuablackburn-iex** [comment]
This appears to be working as designed.  After market hours you should see all data.  During market hours we do not have an official close, so that field is omitted.
