### ISSUE TITLE
[Request] Stock Price by Date Returns Invalid API Key 

### ISSUE THREAD

**Issue by TechniumUnlimited** [iexg/IEX-API#1550]
**Clearly describe the problem**
When trying to use a date format to return historical price data, I get 403 Forbidden due to Invalid API Key

**What time did the problem occur? (with timezone)**
6AM PST

**What is the expected behavior?**
Returning price info for date

**Your environment (e.g. browser, OS, API version, language):**
Python Latest Version, Windows

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/ARCC/chart/20150811?token=

**What are the steps to reproduce the bug?**
Ask for a date for historical price data

**Additional context**
Trying to compare price at X date with price at latest date, but get 403 despite valid API Key and asking for data within "Free API" range of 5 years

**Comment by evancarter-iex** [comment]
This is working.
