### ISSUE TITLE
HTTP error 403: Forbidden

### ISSUE THREAD

**Issue by farazbukhari98** [iexg/IEX-API#1551]
Hello, I am trying to figure out what is wrong with my HTTP request to get the data from IEX API.

Date/time of issue: 08/12/2020, 1PM

What you did: Wrote the code to request data for 5 stocks

What you expected to happen: Trying to print a pandas dataframe with the stocks that I chose.

What actually happened: Error returned: raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Additional Relevant Information: Here is my full code with the API key blocked out:
```
import pandas as pd 

#Using IEX Cloud API to get stock data
IEX_API_Key = 'API key here'

tickers = ['JPM','BAC','C','WFC','GS',]

#Serialize ticker list into separated string of tickers 
ticker_string = ''

#Loop through every element of `tickers` and add them and a comma to ticker_string
for ticker in tickers:
    ticker_string += ticker
    ticker_string += ','

#Drop the last comma from ticker_string
ticker_string = ticker_string[:-1]

#Determine which endpoint to ping from the IEX Cloud API
#Theres a historical prices endpoint, which we can send an HTTP request to using the 'chart' keyword

endpoints = 'chart'
years = 10


#Interpolate the endpoint request into a http_request string.
##This interpolated string is important because it allows us 
###to easily change our string's value at a later date without 
####changing each occurrence of the string in our codebase.
HTTP_request = f'https://cloud.iexapis.com/stable/stock/market/batch?symbols={ticker_string}&types={endpoints}&range={years}y&token={IEX_API_Key}'

#Make the request and store the data in a pandas dataframe.
bank_data = pd.read_json(HTTP_request)
```

As you can see, towards the end, I am trying to read the JSON from the HTTP_request. I cannot do so here.

**Comment by farazbukhari98** [comment]
An extensive Google search led me towards people using urllib for web scraping. I tried a few techniques from there but it was not helpful. 

Here is the tutorial I am following for reference: https://www.freecodecamp.org/news/how-to-create-auto-updating-data-visualizations-in-python-with-matplotlib-and-aws/

**Comment by nickmccullum** [comment]
That endpoint doesn't support 10 years as a timeframe. Try 2 years or 5 years, or removing the `y` from the URL and adding in `max` instead, like this:

```python
HTTP_request = f'https://cloud.iexapis.com/stable/stock/market/batch?symbols={ticker_string}&types={endpoints}&range=max&token={IEX_API_Key}'
```

**Comment by timpaine-iex** [comment]
I recommend looking into the available [language bindings](https://iexcloud.io/libraries/) as they'll handle a lot of the minutiae for you
