### ISSUE TITLE
Java SocketException: Connection Reset after 12ish minutes of running application

### ISSUE THREAD

**Issue by mchaney2** [iexg/IEX-API#1552]
Hi, I am designing an app using the following steps:

1. Get all stock symbols (calling /ref-data/symbols)
2. For each stock symbol:
    a)call up all annual earnings available
    b)analyze earnings data
    c)return a single rating number
3. Sort and rank set of stocks by ranking number from 2c
4. Write ranked set to .txt file

Somewhere between 1 and 2c I'm getting a Socket Exception saying that the connection reset. This is usually about 12 minutes into starting the Run. 

I'm a novice to intermediate programmer so I'm learning as I go. I'm working on reordering my code to hopefully make it more efficient, and maybe find out where exactly in my code the connection is resetting.

I'm writing this to see if there is some server timeout rule that I wasn't aware of, or any tips that you know off the top of your head that could help me. 

Thank you

**Comment by mchaney2** [comment]
![image](https://user-images.githubusercontent.com/6640572/90168281-dfd87c00-dd6a-11ea-8cac-38c95637b3ca.png)

**Comment by mchaney2** [comment]
I'm also reading over some stuff at [this link](https://stackoverflow.com/questions/28910223/http-https-client-connection-reset-on-https-requests) so if I'm able to figure it out otherwise I'll post what fixed it and close the issue.

**Comment by timpaine-iex** [comment]
I'm not sure this is something we can help with, but if you see any specific issues on our end that you can cleanly reproduce, please ping me and I'll reopen.
