### ISSUE TITLE
Invalid historical candles for international exchanges (e.g. open, high, low = 0)

### ISSUE THREAD

**Issue by andreaskoepf** [iexg/IEX-API#1553]
(On 7/27/2020 I reported this problem via E-Mail to support@iexcloud.io but I have not receive a reply until now.)

**Clearly describe the problem**

Historical EOD prices of common stocks provided for different European exchanges (e.g. ETR, PAR, LON) in a lot of cases only have a reliable close price. Thousands of EOD candles have a value of 0 in their in open, high, low fields. I also noticed that some stocks have bad initial or ending prices when the range is set to 'max' (e.g. the same candle repeated many times).

**What time did the problem occur? (with timezone)**
It definitely happend on 6/30/2020 (and persists until now 8/14/2020 3:45pm UTC +2).

**What is the expected behavior?**
I would expect complete data with valid open, high, low, close prices and volume for liquid stocks.

**Your environment (e.g. browser, OS, API version, language):**
I am using python (`requests` http lib) to access the REST API. I am specifying version `stable`.

**API URL (if applicable)**
`https://cloud.iexapis.com/stable/stock/{symbol}/chart/max?token={your_token}` and use one of the symbols listed below.

**What are the steps to reproduce the bug?**
Execute a GET request to the chart API endpoint with one of the symbols below.

**Additional context**

Here is a list of symbols that had more than 1000 zero-open candles of the German stock market:

Symbol: ADM-GY; count(open=0): 1724 (48.0089111328125%);
Symbol: AGJ-GY; count(open=0): 2300 (81.35832977294922%);
Symbol: BMT-GY; count(open=0): 1073 (30.013986587524414%);
Symbol: BSP-GY; count(open=0): 1414 (60.067970275878906%);
Symbol: CVS-GY; count(open=0): 1092 (81.98197937011719%);
Symbol: DCO-GY; count(open=0): 1378 (38.77321243286133%);
Symbol: DIE-GY; count(open=0): 1626 (48.14924621582031%);
Symbol: E8X-GY; count(open=0): 1070 (29.90497398376465%);
Symbol: ERO1-GY; count(open=0): 2257 (60.81918716430664%);
Symbol: FBEN-GY; count(open=0): 1417 (53.07115936279297%);
Symbol: FMV-GY; count(open=0): 1093 (29.279399871826172%);
Symbol: FOT-GY; count(open=0): 1200 (35.90664291381836%);
Symbol: FPMB-GY; count(open=0): 1464 (44.0698356628418%);
Symbol: G6P-GY; count(open=0): 1508 (42.26457214355469%);
Symbol: GOS-GY; count(open=0): 1197 (33.520023345947266%);
Symbol: H9W-GY; count(open=0): 1335 (38.58381652832031%);
Symbol: HLBN-GY; count(open=0): 1067 (30.599369049072266%);
Symbol: HNM-GY; count(open=0): 1102 (80.79178619384766%);
Symbol: HP3-GY; count(open=0): 1150 (34.114505767822266%);
Symbol: IDP-GY; count(open=0): 1122 (31.5700626373291%);
Symbol: IFA-GY; count(open=0): 1278 (86.00269317626953%);
Symbol: K1R-GY; count(open=0): 1155 (33.09455490112305%);
Symbol: KA8-GY; count(open=0): 1143 (30.610605239868164%);
Symbol: KFI1-GY; count(open=0): 1318 (88.51578521728516%);
Symbol: LSPP-GY; count(open=0): 1034 (33.376373291015625%);
Symbol: MCE-GY; count(open=0): 2265 (62.242374420166016%);
Symbol: MED-GY; count(open=0): 1066 (28.548473358154297%);
Symbol: MLL-GY; count(open=0): 1104 (29.57406997680664%);
Symbol: MWB-GY; count(open=0): 1403 (37.573646545410156%);
Symbol: NFC-GY; count(open=0): 1266 (42.65498733520508%);
Symbol: NKE-GY; count(open=0): 1186 (33.23059844970703%);
Symbol: O4B-GY; count(open=0): 1193 (32.64915084838867%);
Symbol: OPC-GY; count(open=0): 1998 (53.5656852722168%);
Symbol: P4O-GY; count(open=0): 1255 (35.17376708984375%);
Symbol: PEP-GY; count(open=0): 1130 (31.643796920776367%);
Symbol: PMAG-GY; count(open=0): 1164 (32.459564208984375%);
Symbol: PPX-GY; count(open=0): 1540 (41.24263381958008%);
Symbol: PRU-GY; count(open=0): 1057 (69.63109588623047%);
Symbol: QB7-GY; count(open=0): 1058 (29.594406127929688%);
Symbol: RNY-GY; count(open=0): 1101 (34.01297378540039%);
Symbol: RPL-GY; count(open=0): 1919 (57.975830078125%);
Symbol: SJJ-GY; count(open=0): 1029 (62.06272506713867%);
Symbol: SLL-GY; count(open=0): 1088 (30.28110122680664%);
Symbol: SMWN-GY; count(open=0): 1761 (47.28786087036133%);
Symbol: SND-GY; count(open=0): 1088 (29.137653350830078%);
Symbol: SWJ-GY; count(open=0): 1883 (54.000572204589844%);
Symbol: TTO-GY; count(open=0): 1040 (67.4886474609375%);
Symbol: UNP-GY; count(open=0): 1527 (57.191009521484375%);
Symbol: UNVB-GY; count(open=0): 1046 (73.55836486816406%);
Symbol: UPAB-GY; count(open=0): 1743 (66.93548583984375%);
Symbol: USX1-GY; count(open=0): 1057 (75.28489685058594%);

**Comment by evancarter-iex** [comment]
This should be fixed (based on my spot checking)
