### ISSUE TITLE
[Data] AAPL/TSLA shows stock split as upcoming dividend

### ISSUE THREAD

**Issue by marekk657** [iexg/IEX-API#1554]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
AAPL or TSLA ticker. range=next shows "upcoming" dividend but this is actually upcoming split.

https://investor.apple.com/dividend-history/default.aspx

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/AAPL/dividends?token=XXXXX&range=next
https://cloud.iexapis.com/stable/stock/tsla/dividends?token=XXXXX&range=next

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**
Split shoudnt be shown as "upcoming" dividend.

**What are the steps to reproduce**
Check data url

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

Invaid response AAPL:
`{
    "exDate": "2020-08-31",
    "paymentDate": "2020-08-28",
    "recordDate": "2020-08-24",
    "declaredDate": "2020-07-30",
    "amount": "",
    "flag": "Stock",
    "currency": "",
    "description": "Ordinary Shares",
    "frequency": "quarterly",
    "symbol": "AAPL"
}`

Invalid response TSLA:
`{
    "exDate": "2020-08-31",
    "paymentDate": "2020-08-28",
    "recordDate": "2020-08-21",
    "declaredDate": "2020-08-11",
    "amount": "",
    "flag": "Stock",
    "currency": "",
    "description": "Ordinary Shares",
    "frequency": "unspecified",
    "symbol": "TSLA"
}`

**Comment by timpaine-iex** [comment]
@marekk657 I believe this has been fixed, can you double check and ping me if its still an issue so ic an reopen
