### ISSUE TITLE
[Data] TSLA/AAPL Wrong PE/Ratio, Historic Intraday, Historic Prices

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1560]
**Clearly describe the data problem**
Since the Split, PE/Ratio, Historic Intraday and Historic Prices are wrong.

**What is the expected behavior?**
The historic prices and intradays should be normalized as well, to reflect the current amount of total shares.

**Comment by timpaine-iex** [comment]
consolidating into https://github.com/iexg/IEX-API/issues/1561
