### ISSUE TITLE
[Data] TSLA / AAPL wrong historic data after bugfix

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1561]
**Clearly describe the data problem**

![image](https://user-images.githubusercontent.com/7766565/91873116-f17db700-ec78-11ea-9f41-787f90fb875f.png)

The close prices suddenly multiplies in both AAPL and TSLA historic data.

**Comment by timpaine-iex** [comment]
@DavidKuennen can you check now, we made some changes to adjustments. 
<img width="626" alt="Screen Shot 2020-12-16 at 9 58 56 AM" src="https://user-images.githubusercontent.com/74613173/102365231-5093dd00-3f85-11eb-9b54-21f21f16c57d.png">
