### ISSUE TITLE
[Data] TSLA split not being shown in the splits endpoint

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1562]
**Clearly describe the data problem**
The splits endpoint doesn't return TSLA splits

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/splits/5y?symbols=TSLA&token=

**Comment by MorningSleeper** [comment]
Unfortunately, the basic splits endpoint has been broken for at least 9 months.

https://github.com/iexg/IEX-API/issues/1330

**Comment by tchristofferson** [comment]
I'm having the same issue.

**Comment by evancarter-iex** [comment]
Fixed.
