### ISSUE TITLE
When trying to get a real time quote many (not all) companies are returning null for OPEN price

### ISSUE THREAD

**Issue by Shrikantjee** [iexg/IEX-API#1563]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**
When trying to get a real time quote many (not all) companies are returning null for OPEN price.  For example UBER works fine, but TSLA returns nulls.

**What time did the problem occur? (with timezone)**
10:30 am Central time.

**What is the expected behavior?**
Should return OPEN data.

**Your environment (e.g. browser, OS, API version, language):**
Edge browser, Windows 10.

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/TSLA/quote?token=MYTOKEN

**What are the steps to reproduce the bug?**
Use the above URL to make the call in any browser

**Additional context**

**Comment by geeksified** [comment]
has this been fixed? I can still see null open price even on highly traded stocks during trading hours.

**Comment by timpaine-iex** [comment]
@geeksified @Shrikantjee yeah this is covered by that help center document, it is an upstream restriction not a bug
