### ISSUE TITLE
Get news for specific language only

### ISSUE THREAD

**Issue by rariancom** [iexg/IEX-API#1564]
It should be possible to get news for a specific language only.

Endpoint: GET /stock/{symbol}/news/last/{last} 
Suggested Endpoint:  GET /stock/{symbol}/news/last/{last}/{language}

(or something like that :)
Now we get all news and have to throw out the non English items, waste of message use.

**Comment by Atum7** [comment]
This must be very useful for me as well.

**Comment by samyoungnyc** [comment]
Bump

**Comment by timpaine-iex** [comment]
sounds like a reasonable request, mind submitting on the [roadmap](https://iexcloud.io/console/roadmap)

**Comment by nypinstripes** [comment]
@joshuablackburn-iex @evancarter-iex @timkpaine 

Wanted to check if this made it onto the radar / roadmap, just starting to implement the api in my app this week, would prefer not using credits and filtering out all foreign language articles.

**Comment by timpaine-iex** [comment]
This has actually worked for many months, you can use [timeseries](https://iexcloud.io/docs/api/#time-series) with `subattribute=lang|en`. Apologies for not responding sooner.
