### ISSUE TITLE
[Bug] Wrong P/E ratios reported for some stock symbols

### ISSUE THREAD

**Issue by eazar001** [iexg/IEX-API#1565]
**Clearly describe the problem**

Stable version of the API is reporting that KHC (Kraft Heinz) has a P/E ratio of -215.23. This does not seem to be supported by other available sources on the web. This is just one example but `peRatio` (including others such as `priceToBook` to a name a few) also appear to be incorrect for a significant amount of common stocks.

**What time did the problem occur? (with timezone)**

September 4th, approximately 11:30 AM MT

**What is the expected behavior?**

The correct P/E ratio needs to be reported; it seems for example, -215.23 wasn't even close to the real value.

**Your environment (e.g. browser, OS, API version, language):**

Firefox, Windows 10 and Debian Linux, Stable API, English on a paid "Launch" account.

**API URL (if applicable)**

Malfunctioning endpoints are both `/stats` and `advanced-stats`

**What are the steps to reproduce the bug?**

Query one of the stats APIs for a random stock ticker and occasionally I will get a very wrong P/E, or P/B ratio. I used the `VTV` ETF to test.

**Additional context**

**Comment by McQgit** [comment]
@eazar001 I have the TTM EPS at -0.15.  Using Friday's close is 33.47 / -0.15 = -223.13 P/E

I suspect most of the P/E's you are looking at are MRQ or even last fiscal year.  I didn't look at the IEX docs as to what they say they are using - just happened to notice this the other day on my private stats page.

**Comment by eazar001** [comment]
Hi @McQgit , I was actually comparing to the source here: https://www.zacks.com/stock/chart/KHC/fundamental/pe-ratio-ttm

According to Zacks, this is a TTM P/E of closer to just under 13x multiple. Perhaps there's something I'm misunderstanding here?

**Comment by eazar001** [comment]
Though, to follow up it seems their EPS differs significantly from your value of -0.15. They're reporting 2.79; perhaps their calculation is off....

**Comment by eazar001** [comment]
OK yes, it seems their TTM EPS is outdated for the calculation. I'm closing this issues for now as there seems to be latency issues from my source. Feel free to reopen this ticket if you feel this is premature.
