### ISSUE TITLE
get historical intraday throwing Invalid auth token error 

### ISSUE THREAD

**Issue by enthusiasttrader** [iexg/IEX-API#1566]
import pandas as pd
import time
import yfinance as yf
import datetime as dt
import yfinance as yf
from iexfinance.stocks import get_historical_intraday
stock='TSLA'
start = dt.datetime(2020,9,1)
end = dt.datetime.now()
api_key='*****************************************'

sp = get_historical_intraday('STNE', date='start',output_format='pandas', token=api_key)
print(sp)

IEXAuthenticationError: The query could not be completed. Invalid auth token.

Getting this error, although my API is correct. I also deleted the old token and generated a new key and i am still having same issues

**Comment by McQgit** [comment]
@enthusiasttrader  See:  https://github.com/iexg/IEX-API/issues/1535#issuecomment-660381618
