### ISSUE TITLE
isUSMarketOpen property of Quote does not reflect actual market state. [Data]

### ISSUE THREAD

**Issue by unozerocode** [iexg/IEX-API#1567]
**Clearly describe the problem**
When getting a quote, the "isUSMarketOpen" property of the response indicates market is closed. 
Taking the example directly from the documentation "REST How-To", we applied the API call as given.

**What time did the problem occur? (with timezone)**
11:12 AM, Monday, September 7, 2020 (CDT)

**What is the expected behavior?**
The response should indicate that the market is open.  Instead, the "isUSMarketOpen" field is false.
From the documentation for Quote: "isUSMarketOpen" is a boolean that means: _For US stocks, indicates if the market is in normal market hours. Will be false during extended hours trading._

```
{
   "symbol":"AAPL",
   "companyName":"Apple, Inc.",
   "primaryExchange":"NASDAQ",
   "calculationPrice":"close",
   "open":null,
   "openTime":null,
   "openSource":"official",
...
   "week52Low":52.77,
   "ytdChange":0.63396,
   "lastTradeTime":1599249600801,
   "isUSMarketOpen":false
}
```

Additionally, the "open" property is null, when we are expecting a float.

**Your environment (e.g. browser, OS, API version, language):**
Chrome browser, Windows 10, API Version 1, Language: Elixir

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/aapl/quote?token=...

**What are the steps to reproduce the bug?**
Use the above URL to make the call in any browser, during market open hours.

**Comment by McQgit** [comment]
@unozerocode Market is closed today - Labor Day holiday.  
https://www.nasdaq.com/articles/2020-stock-market-holidays-and-bond-market-holidays-2019-12-28

**Comment by unozerocode** [comment]
That is hilarious, ok thanks. We are not in the US so we didn´t know.
