### ISSUE TITLE
[Issue] losers, gainers, actives endpoint empty arrays

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1568]
Since 9/8/20 6:30 AM PDT

https://cloud.iexapis.com/v1//stock/market/list/losers?token=
https://cloud.iexapis.com/v1//stock/market/list/gainers?token=
https://cloud.iexapis.com/v1//stock/market/list/mostactive?token=

**Comment by MorningSleeper** [comment]
Seems losers and gainers have fixed themselves since post, actives still empty array.

**Comment by MorningSleeper** [comment]
Anyone else getting the empty array for actives?

**Comment by MorningSleeper** [comment]
Again, all three empty arrays since 6:30 AM PST

**Comment by adamwozney-iex** [comment]
Hey @MorningSleeper - Thanks for reaching out. Our tech team is aware of the issue and is currently investigating.

**Comment by MorningSleeper** [comment]
Gainers is returning [] again.

**Comment by MorningSleeper** [comment]
Working today, hope your team found and fixed the cause of this recurring issue, thanks.
