### ISSUE TITLE
Format of /time-series endpoint and retrieving a time series. [Data]

### ISSUE THREAD

**Issue by unozerocode** [iexg/IEX-API#1569]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
The JSON response to the GET /time-series endpoint does not match the documentation, and the series-id it returns does not allow us to query for a time series.

**Data URL (The URL you used to access the data without your token):**
https://sandbox.iexapis.com/stable/time-series/
and when attempting to retrieve a particular time series:
https://sandbox.iexapis.com/stable/time-series/NPMIATIMTENH_EUAOJWZDANMPNE_EELUNRLOECTAER_GE_TODEN_SNCSRITROR?
the API returns "Not found" with HTTP 404 code.

From what the [documentation ](https://iexcloud.io/docs/api/#time-series) says, we first need to get a list of the inventory of time-series by calling the endpoint just with /time-series, and then choose one of the time series records it returns, calling the endpoint again with GET /time-series/{id}. with id being one of the id´s given by the platform.

The inventory response is very complex and the documentation does not fully explain all the parts of it, in particular the "schema" field is not very well documented and seems to be an abstraction leak from your internal representation, which is not good from an API usage standpoint, the whole reason for an API is to provide clear and well-defined actions and resources so that a client can get what it needs without understanding the inner representation, so at the very least this endpoint needs to be refactored and documented.

**What time did the problem occur (including timezone)?**
10:18 AM Friday, September 11, 2020 (CDT)

**What is the expected behavior?**
We would expect to be able to retrieve a time series by calling the GET /time-series/{id} endpoint with an id given to us by the platform, instead it does not find the resource.

**What are the steps to reproduce**
Get from https://sandbox.iexapis.com/stable/time-series/
Choose one of the ids in the list of records it returns, and now call the api with that id:
Get from https://sandbox.iexapis.com/stable/time-series/{id}

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Windows 10, API Version 1, Elixir

**Additional context**
Console log of attempt to persist returned data, validation errors at the bottom of every record, most of which are coming back missing "weightKey" and "subkey", in addition to all sorts of undocumented extra information. We can turn off those validations, but we have already turned off 19 validations just for the Quote response which does not match the documentation, so our API boundary is rapidly becoming porous. And we would move forward if we could just get a time-series back but since that doesn´t work either we are stuck until we can get a helpful response.

Full API response [here](https://gist.github.com/unozerocode/a55c46d52c1c8deb4e9ccb683f8381d0)
`

%{
  "created" => "2020-05-06T08:00:10.000Z",
  "description" => " uinnstvoneDE oncEnnPt)Eatgmaeie(rcdar etgens ejnArn s",
  "id" => "NPMIATIMTENH_EUAOJWZDANMPNE_EELUNRLOECTAER_GE_TODEN_SNCSRITROR",
  "inv_pk" => 32,
  "schema" => %{
    "additionalProperties" => true,
    "properties" => %{
      "companyName" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "earningsDate" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "earningsDateStatus" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "eventId" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "fiscalYear" => %{"anyOf" => [%{"type" => "number"}, %{"type" => "null"}]},
      "quarter" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "symbol" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "timeOfDay" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "updated" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]}
    },
    "required" => [],
    "type" => "object"
  },
  "updated" => "2020-05-06T08:00:10.000Z",
  "version" => 1,
  "weight" => 1160692,
  "weightKey" => "ESREPAJO_INEAHZWLNIDRCGOULS_EMODRENITNNR_TE_AUEMR_ENNTOCPATMET"
}
[error] Error inserting series inventory
#Ecto.Changeset<
  action: :insert,
  changes: %{
    created: ~D[2020-05-06],
    description: " uinnstvoneDE oncEnnPt)Eatgmaeie(rcdar etgens ejnArn s",
    iex_id: "NPMIATIMTENH_EUAOJWZDANMPNE_EELUNRLOECTAER_GE_TODEN_SNCSRITROR",
    inv_pk: 32,
    schema: %{
      "additionalProperties" => true,
      "properties" => %{
        "companyName" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "earningsDate" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "earningsDateStatus" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "eventId" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "fiscalYear" => %{
          "anyOf" => [%{"type" => "number"}, %{"type" => "null"}]
        },
        "quarter" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "symbol" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "timeOfDay" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "updated" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]}
      },
      "required" => [],
      "type" => "object"
    },
    updated: ~D[2020-05-06],
    version: 1,
    weight: 1160692
  },
  errors: [
    weightkey: {"can't be blank", [validation: :required]},
    subkey: {"can't be blank", [validation: :required]}
  ],
  data: #Maya.IEXCloud.SeriesInventory<>,
  valid?: false
>
[info] Series inventory, persisting record
%{
  "created" => "2020-05-06T08:00:19.000Z",
  "description" => " lAsnenaAlrnystat(t Ivnysv)D/ast yoEe",
  "id" => "PMTUSTNAAEILAS_E_ZYLYRREIMDORTWL_NAHO",
  "inv_pk" => 34,
  "schema" => %{
    "additionalProperties" => true,
    "properties" => %{
      "additionalInfoUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "announceDate" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "companyName" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "endDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventDesc" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventId" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventStatus" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "externalNote" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "inviteUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "localTimeStart" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "organizer" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "purl" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "referenceLink" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "scheduleUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "sectorNames" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "startDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "symbol" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "timeZone" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "updated" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "venue" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "venueAddress" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "venueCity" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "venueCountry" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "venueCountryIso" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "venueState" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      }
    },
    "required" => [],
    "type" => "object"
  },
  "updated" => "2020-05-06T08:00:19.000Z",
  "version" => 1,
  "weight" => 1179688,
  "weightKey" => "_OILTRITLNNLASMEADHYZ_STRAY_EPUOAEWMR"
}
[error] Error inserting series inventory
#Ecto.Changeset<
  action: :insert,
  changes: %{
    created: ~D[2020-05-06],
    description: " lAsnenaAlrnystat(t Ivnysv)D/ast yoEe",
    iex_id: "PMTUSTNAAEILAS_E_ZYLYRREIMDORTWL_NAHO",
    inv_pk: 34,
    schema: %{
      "additionalProperties" => true,
      "properties" => %{
        "additionalInfoUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "announceDate" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "companyName" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "endDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "eventDesc" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "eventId" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "eventStatus" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "externalNote" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "inviteUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "localTimeStart" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "organizer" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "purl" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "referenceLink" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "scheduleUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "sectorNames" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "startDate" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "symbol" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "timeZone" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "updated" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "venue" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "venueAddress" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "venueCity" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "venueCountry" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "venueCountryIso" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "venueState" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        }
      },
      "required" => [],
      "type" => "object"
    },
    updated: ~D[2020-05-06],
    version: 1,
    weight: 1179688
  },
  errors: [
    weightkey: {"can't be blank", [validation: :required]},
    subkey: {"can't be blank", [validation: :required]}
  ],
  data: #Maya.IEXCloud.SeriesInventory<>,
  valid?: false
>
[info] Series inventory, persisting record
%{
  "created" => "2020-05-06T08:00:21.000Z",
  "description" => "napn(tBt  sssoUl)e/ye rnsaEuiestvsnIAvedt",
  "id" => "SNSM__UIOWEAA_ENSMIEUTZRODBILPEPTSLHETRUR",
  "inv_pk" => 36,
  "schema" => %{
    "additionalProperties" => true,
    "properties" => %{
      "additionalInfoUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "announceDate" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "companyName" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "endDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventDesc" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventId" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventStatus" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "externalNote" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "inviteUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "localTimeStart" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "organizer" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "purl" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "referenceLink" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "scheduleUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "sectorNames" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "startDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "symbol" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "timeZone" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "updated" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "venue" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "venueAddress" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "venueCity" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "venueCountry" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "venueCountryIso" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "venueState" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      }
    },
    "required" => [],
    "type" => "object"
  },
  "updated" => "2020-05-06T08:00:21.000Z",
  "version" => 1,
  "weight" => 1172650,
  "weightKey" => "_SLD_MITIARSINOSHTTRABLNEESEEPUZUPUREMWO_"
}
[error] Error inserting series inventory
#Ecto.Changeset<
  action: :insert,
  changes: %{
    created: ~D[2020-05-06],
    description: "napn(tBt  sssoUl)e/ye rnsaEuiestvsnIAvedt",
    iex_id: "SNSM__UIOWEAA_ENSMIEUTZRODBILPEPTSLHETRUR",
    inv_pk: 36,
    schema: %{
      "additionalProperties" => true,
      "properties" => %{
        "additionalInfoUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "announceDate" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "companyName" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "endDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "eventDesc" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "eventId" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "eventStatus" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "externalNote" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "inviteUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "localTimeStart" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "organizer" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "purl" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "referenceLink" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "scheduleUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "sectorNames" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "startDate" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "symbol" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "timeZone" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "updated" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "venue" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "venueAddress" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "venueCity" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "venueCountry" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "venueCountryIso" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "venueState" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        }
      },
      "required" => [],
      "type" => "object"
    },
    updated: ~D[2020-05-06],
    version: 1,
    weight: 1172650
  },
  errors: [
    weightkey: {"can't be blank", [validation: :required]},
    subkey: {"can't be blank", [validation: :required]}
  ],
  data: #Maya.IEXCloud.SeriesInventory<>,
  valid?: false
>
[info] Series inventory, persisting record
%{
  "created" => "2020-05-06T08:00:22.000Z",
  "description" => "rtledltC ait snsoIkA (pM/ aEa)sveyynrsanavtet",
  "id" => "_EIE_LSMLCAKRYHOA_ITMWRSRPATPOATERLEIMADUN_TZ",
  "inv_pk" => 36,
  "schema" => %{
    "additionalProperties" => true,
    "properties" => %{
      "additionalInfoUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "announceDate" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "companyName" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "endDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventDesc" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventId" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "eventStatus" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "externalNote" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "inviteUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "localTimeStart" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "organizer" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "purl" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "referenceLink" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "scheduleUrl" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "sectorNames" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "startDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "symbol" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "timeZone" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "updated" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "venue" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "venueAddress" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      },
      "venueCity" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
      "venueCountry" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "venueCountryIso" => %{
        "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
      },
      "venueState" => %{
        "anyOf" => [
          %{"type" => "string"},
          %{"type" => "number"},
          %{"type" => "null"}
        ]
      }
    },
    "required" => [],
    "type" => "object"
  },
  "updated" => "2020-05-06T08:00:22.000Z",
  "version" => 1,
  "weight" => 1159189,
  "weightKey" => "TSPIAOMMA_NLAIULPTRDR_RTZO__RISEELHEKWEAYCATM"
}
[error] Error inserting series inventory
#Ecto.Changeset<
  action: :insert,
  changes: %{
    created: ~D[2020-05-06],
    description: "rtledltC ait snsoIkA (pM/ aEa)sveyynrsanavtet",
    iex_id: "_EIE_LSMLCAKRYHOA_ITMWRSRPATPOATERLEIMADUN_TZ",
    inv_pk: 36,
    schema: %{
      "additionalProperties" => true,
      "properties" => %{
        "additionalInfoUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "announceDate" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "companyName" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "endDate" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "eventDesc" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "eventId" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "eventStatus" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "externalNote" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "inviteUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "localTimeStart" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "organizer" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "purl" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "referenceLink" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "scheduleUrl" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "sectorNames" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "startDate" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "symbol" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "timeZone" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "updated" => %{"anyOf" => [%{"type" => "string"}, %{"type" => "null"}]},
        "venue" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "venueAddress" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        },
        "venueCity" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "venueCountry" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "venueCountryIso" => %{
          "anyOf" => [%{"type" => "string"}, %{"type" => "null"}]
        },
        "venueState" => %{
          "anyOf" => [
            %{"type" => "string"},
            %{"type" => "number"},
            %{"type" => "null"}
          ]
        }
      },

  ...`

**Comment by joshuablackburn-iex** [comment]
You can call /time-series in production without any cost. Don't use sandbox, which is scrambling the results. The result of schema is the actual json schema of the data. This is a self documenting endpoint, not a leak of internal code. The docs don't reflect everything in the schema because the schema is the schema. A future release we are working on now will make all docs data driven and will support json schema and openAPI spec.
