### ISSUE TITLE
[Issue] Getting 429 Errors with Sandbox API on Stock Ratings/Recommendations

### ISSUE THREAD

**Issue by hurricanenara** [iexg/IEX-API#1571]
Hello, I've been using the IEX Cloud API (sandbox) to build a clone of a stock trading website for the past few weeks and noticed I started getting 429 errors. I am in development mode and do have to make numerous fetches as I refresh the specific page I'm working on at that time. Is there any way to go around this issue? The specific endpoint I'm using that's causing the 429 error is `/stock/{ticker}/recommendation-trends`

Any help would be greatly appreciated!

**Comment by adamwozney-iex** [comment]
Hi @hurricanenara - It looks like you're running into our request limits. Our sandbox only allows ten calls per second. You can read more here [https://iexcloud.io/docs/api/#request-limits](url).
