### ISSUE TITLE
[Data] Estimated earnings date AMD

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1573]
**Clearly describe the data problem**
The estimated earnings report date for Q3 2020 AMD is 2021-02-02, which is clearly wrong. Is should be around October 2020.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/estimates?symbols=AMD&token=

**Comment by evancarter-iex** [comment]
Fixed.
