### ISSUE TITLE
Keys of a dictionary are in a random order

### ISSUE THREAD

**Issue by Sintekoz** [iexg/IEX-API#1574]
Date/time of the issue: 20-09-20
What you did: Tried to get an info of a company (Stock profiles > Company)
What you expected to happen: Companies' info
What actually happened: Companies' info, but values are in a random order
Additional relevant information: 
<img width="1786" alt="Screen Shot 2020-09-20 at 12 04 41 PM" src="https://user-images.githubusercontent.com/42314862/93707690-7c93f380-fb39-11ea-93bb-3999c32f4456.png">

**Comment by adamwozney-iex** [comment]
Hey @Sintekoz - After reviewing the screenshot, it looks like you might be using the sandbox environment. To get your production keys, head over to the console and make sure sandbox testing is off. [https://iexcloud.io/console/tokens](url).
