### ISSUE TITLE
[Data] Cumulative after hours volume for a ticker

### ISSUE THREAD

**Issue by dsrapaport** [iexg/IEX-API#1575]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
I am trying to get the "cumulative after market hours volume" for a ticker, but have been able to get it.  

For example: If the current day / time is Monday 7pm ET, I need to get the "cumulative after hours total volume" for $AAPL.  More specifically, I am trying to get the cumulative total volume for $AAPL from 4:01pm ET to 7:45pm ET.  

I believe that I can get a specific minute of after hours volume (e.g., the volume during the minute of 7:45pm) for $AAPL, but cannot seem to figure out how to get the cumulative total volume for a period of time after market hours.

**Data URL (The URL you used to access the data without your token):**
GET /stock/{symbol}/quote/volume

**What time did the problem occur (including timezone)?**
This is a problem specific to getting volume after hours (after market close - i.e., 4:01pm-8pm ET).

**What is the expected behavior?**
I would like to get the sum of the volume from after the market closes to a specific time (e.g., total volume for $AAPL from 4:01pm to 7:45pm ET).

**What are the steps to reproduce**
I don't know how to get the cumulative total volume.

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Windows 10.

**Additional context**
I apologize if this is a total bush league question.  I am not too sophisticated in these things.  Thank you for your help.  I greatly appreciate it!

**Comment by timpaine-iex** [comment]
grouping with https://github.com/iexg/IEX-API/issues/693
