### ISSUE TITLE
Parsing JSON data into Excel from IEX please help with this code

### ISSUE THREAD

**Issue by zeroize2** [iexg/IEX-API#1578]
`Sub getData()

'Array col headers
Dim myarrow As Variant
myarray = Array("reportDate", "fiscalDate", "totalRevenue", "costOfRevenue", "researchAndDevelopment", "sellingGeneralAndAdmin", "operatingExpense", "operatingIncome", "otherIncomeExpenseNet")
arrSize = UBound(myarray) - LBound(myarray) + 1

'msgbox(arrsize)
Dim ws As Worksheet
Set ws = Sheets("sheet1")

Dim ticker As String
ticker = ws.Range("R7").Value

Dim lastrow As Integer
lastrow = ws.Cells(Rows.Count, "A").End(xlUp).Row

'Clear Range
ws.Range("A1:O" & lastrow).Clear

Dim rngTarget As Range
Set rngTarget = ws.Range(Cells(1, 1), Cells(1, arrSize))
rngTarget = myarray

'write to sheet

'send web request for api data
u = "https://sandbox.iexapis.com/stable/stock/aapl/financials?period=annual&token=Tsk_66862b4b2a394bc5839be0e4fb6e899d"

Set myrequest = CreateObject("WinHttp.WinHttpRequest.5.1")
myrequest.Open "Get", u
myrequest.Send

'parse JSON
Dim Json As Object
Set Json = JsonConverter.ParseJson(myrequest.ResponseText)

'get # of Objects in Array
Dim arrayLen As Integer
arrayLen = Json.Count

'MsgBox (arrayLen)

'Loop through elements
Dim element As Variant
Dim x, y, r As Integer

r = 2
y = 1
x = 1

While x < arrayLen + 1
    For Each element In myarray
        'ws.Cells(r, y).Value = Json(x)(element)
        y = y + 1
    Next element
    
    y = 1
    x = x + x
    r = r + 1
Wend

Debug.Print JsonConverter.ConvertToJson(Json)
End Sub

`

in the immediate I get the data
{"symbol":"AAPL","financials":[{"reportDate":"2019-09-23","fiscalDate":"2019-09-25","currency":"USD","grossProfit":99674096362,"costOfRevenue":169935225767,"operatingRevenue":268261373259,"totalRevenue":265933563770,"operatingIncome":65260548225,"netIncome":56749137530,"researchAndDevelopment":16229778582,"operatingExpense":206223761947,"currentAssets":166847728533,"totalAssets":343114356502,"totalLiabilities":257456032397,"currentCash":29136578742,"currentDebt":16276403717,"shortTermDebt":16378134885,"longTermDebt":96253958936,"totalCash":102849127782,"totalDebt":113153101704,"shareholderEquity":91412621367,"cashChange":25311107073,"cashFlow":69714873552}]}

but in excel I am failing to have it plot.. I am a complete noob to this any help as to how to make this work would be great, and adding multiple tickers would be even better

**Comment by adamwozney-iex** [comment]
Hi @zeroize2 - You can call several tickers at once using the batch endpoint [https://iexcloud.io/docs/api/#batch-requests](url). Our documentation has examples of this. Hope this helps!
