### ISSUE TITLE
[enhancement request] Add currency to quote endpoint

### ISSUE THREAD

**Issue by dchambers** [iexg/IEX-API#1579]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**

The 'Quote'  end-point (https://iexcloud.io/docs/api/#quote) includes price information (e.g. `delayedPrice`) but does not detail the currency of the quoted price, which makes the price meaningless -- e.g. is it 4 oranges, 4 apples or 4 Canadian dollars?

**Comment by rada-it** [comment]
I have a question which fits with this issue title:
I´m using the API and getting data from different symbols of different exchanges.

Wenn i try to get the symbols https://cloud.iexapis.com/stable/ref-data/exchange/FRA/symbols?token=xxx i get the full list of all symbols with the currency. >> Here for AHLA-GF the currency is USD
But when i request the price for the symbols (for example: AHLA-GF for the Alibaba Share in Frankfurt/GF) i get the price in Euro.
Is the price always the price of the requested Exchange Location? ( Frankfurt (Exchange: -GF) = EUR = German Exchange, NYSE = USD = US exchange)?
Found nothing in the documentation...

**Comment by timpaine-iex** [comment]
@dchambers @alex-romanenko @danthedeckie @rada-it this is done and will roll out over the next 24hrs as stock quotes regenerate
