### ISSUE TITLE
Add ASX:NEA symbol

### ISSUE THREAD

**Issue by SanJagDar** [iexg/IEX-API#1580]
Date/time of the issue: 28-09-2020
What you did: Searched for ASX:NEA symbol and could not find.
What you expected to happen: Be able to see stock info for ASX:NEA
What actually happened: No symbol found
Additional relevant information: Nearmap Ltd (ASX: NEA)

**Comment by adamwozney-iex** [comment]
Hey @SanJagDar - We don't cover this symbol yet, but starting December 1st we will.

For more information regarding our data upgrade, you can check out our most recent blog post: https://intercom.help/iexcloud/en/articles/4529082-iex-cloud-s-2020-data-upgrade
