### ISSUE TITLE
[Data] JPM logo is a building image

### ISSUE THREAD

**Issue by JamesChloroBenzene** [iexg/IEX-API#1581]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
Logo image is a building image.
Correct JPM logo is needed.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/jpm/logo

**What time did the problem occur (including timezone)?**
Always

**What is the expected behavior?**
Correct JPM logo link

**What are the steps to reproduce**
https://cloud.iexapis.com/stable/stock/jpm/logo

**Your environment (e.g. browser, OS, API version, language):**
Windows, Android OS

**Additional context**

**Comment by adamwozney-iex** [comment]
Hey @JamesChloroBenzene - The tech team is aware of this issue and has added to their queue. Thanks for flagging!

**Comment by timpaine-iex** [comment]
looks like its ok now
