### ISSUE TITLE
[Data] No new IPOs in the upcoming IPOs endpoint since August

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1582]
**Clearly describe the data problem**
The upcoming IPO endpint hasn't been updating since august

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/upcoming-ipos?symbols=TSLA&token={token}

**Comment by MorningSleeper** [comment]
Correct, there is a note in API docs about them looking for a new source of data for it. Hopefully, it gets fixed soon.

https://iexcloud.io/docs/api/#ipo-calendar

**Comment by DavidKuennen** [comment]
Oh, thank you very much @MorningSleeper

**Comment by fgisslen** [comment]
Is there any news about the IPO Calendar?

**Comment by timpaine-iex** [comment]
follow API docs / emails for updates
