### ISSUE TITLE
Question about general Data Reliability of IEX

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1583]
I noticed that there have been increasing problems with data reliability in the recent history. There are currently 350 open issues and not a single developer response in weeks. 

This raises the question whether iex is still a reliable service. I have an app with tens of thousands of users daily and all the support requests are because there is some data missing or wrong.

**Comment by noam2** [comment]
I agree

**Comment by rsksmiles** [comment]
I agree any comment from Iex would be a help please.

**Comment by unozerocode** [comment]
We had the same problem, issues are just ignored https://github.com/iexg/IEX-API/issues/1556 or closed without resolution, and found some worrying [complexity issues](https://gist.github.com/unozerocode/a55c46d52c1c8deb4e9ccb683f8381d0) in their design, so we moved on to another platform. @DavidKuennen out of curiosity, what is your product?

**Comment by joshuablackburn-iex** [comment]
There is a huge update coming. We've been hard at work for months to bring a massive upgrade in data and a simplification of the API. Emails should be going out to all customers soon.

**Comment by DavidKuennen** [comment]
@joshuablackburn-iex Thank you for your response. I'm looking forward to the update. 

@unozerocode It's https://stockevents.app

**Comment by Cyral** [comment]
> @joshuablackburn-iex Thank you for your response. I'm looking forward to the update.
> 
> @unozerocode It's https://stockevents.app

Not sure if you got the huge update email yet, bet you aren't happy about the earnings endpoint either.

**Comment by jesseorosz** [comment]
I've been using it for a year and a half now and it's gotten steadily worse.

IEX works on adding new functionality yet can't even get simple metrics like Day 5 Change Percent working in the Key Stats call.

**Comment by jesseorosz** [comment]
> @joshuablackburn-iex Thank you for your response. I'm looking forward to the update.
> 
> @unozerocode It's https://stockevents.app

Nice app, but IEX left you hung out to dry with their new message and redistribution changes with several endpoints.

**Comment by joshuablackburn-iex** [comment]
@jesseorosz  I'm sorry your experience has been less than optimal. We've not be satisfied with the quality of data and that is why we've made adjustments. We are happy to support independent, high quality providers, and we think many issues will be resolved.

As for earnings, despite our best efforts, this was the best we could do. There are less than 5 providers of estimates data and we were unable to compromise on our mission to make this data easily accessible and available to everyone. Unfortunately we could not get the same rights to display the data, but we feel the added quality and global coverage are beneficial to the majority of our customers.
