### ISSUE TITLE
Add CSE:WIFI or WIFI.CN symbol

### ISSUE THREAD

**Issue by jayPare** [iexg/IEX-API#1585]
Please add CSE:WIFI or WIFI.CN symbol (AMERICAN AIRES INC).

**Comment by adamwozney-iex** [comment]
Hey @jayPare - We don't cover this symbol yet, but starting December 1st we will. 

For more information regarding our data upgrade, you can check out our most recent blog post: https://intercom.help/iexcloud/en/articles/4529082-iex-cloud-s-2020-data-upgrade

**Comment by jayPare** [comment]
I tried the method described here:
https://intercom.help/iexcloud/en/articles/4063782-international-data

Not working for me.

**Comment by timpaine-iex** [comment]
<img width="1323" alt="Screen Shot 2021-02-10 at 11 55 40 AM" src="https://user-images.githubusercontent.com/74613173/107543118-e8353680-6b96-11eb-9367-4b46964ecbea.png">
