### ISSUE TITLE
Messages and Delays

### ISSUE THREAD

**Issue by JSGalpin-umbc** [iexg/IEX-API#1587]
Been reviewing API docs. The number of messages per call is not clear.

Example: I need to chart the last 60 minutes(1m interval) for 30 stocks. How many messages would a single call be?

Also, It's no longer clear which pricing data 15 min delayed and what is not.

**Comment by joshuablackburn-iex** [comment]
Please look at our Intraday Prices documentation. 
https://iexcloud.io/docs/api/#intraday-prices

It says 1 message per interval returned. So 60 minutes is 60 messages.

If you scroll down to the table that describes each data attribute, we **very** clearly state which attributes are 15 minute delayed.
