### ISSUE TITLE
[Data] Chart endpoint not returning split adjusted historical price

### ISSUE THREAD

**Issue by arunkatti** [iexg/IEX-API#1589]
**Clearly describe the data problem**
Am using the /chart endpoint to get a stock close price at the end of last year, but IEX API is returning the unadjusted Close price of $233.24 as shown below
{"EW":{"chart":[{"date":"2019-12-31","close":233.24,"volume":1220,"changeOverTime":0.0075700946693915885}]}}

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch/date/20191231?types=chart&last=1&symbols=EW&token=pk_xxxxx&chartLast=1&chartCloseOnly=True

**What time did the problem occur (including timezone)?**
10/14/2020 Eastern, throughout the day and yesterday as well

**What is the expected behavior?**
Should have seen split adjusted Close price of $77.76 for 12/31/2019

**What are the steps to reproduce**
Run the URL above

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Windows 10, IEX Cloud API 1.0

**Additional context**

**Comment by arunkatti** [comment]
Is this such a strange issue that nobody else has experienced it? I would think this should be pretty common. No?

**Comment by joshuablackburn-iex** [comment]
The adjusted price is available on that date.
https://cloud.iexapis.com/stable/stock/ew/chart/1y?token=

You're only pulling down the unadjusted value.
