### ISSUE TITLE
Does the IEX Trading Platform provide price data for all exchanges around the world ?

### ISSUE THREAD

**Issue by scott56hannah** [iexg/IEX-API#159]
I am looking for a service that provides price data for trades performed on different exchanges around the world. It appears from a review of the IEX website that this service can provide price data for US exchanges but none for the UK, Australia or any other exchange...

Is that right ?
If not can someone point me to the documentation that describes which exchanges and price data is available for overseas exchanges

**Comment by evancarter-iex** [comment]
https://github.com/iexg/IEX-API/issues/51
