### ISSUE TITLE
Invalid "The API key provided is not valid." error returned at data-points endpoint

### ISSUE THREAD

**Issue by dioncodes** [iexg/IEX-API#1590]
### Date/time of the issue
2020-10-15
### What you did
Performing a GET request to `https://cloud.iexapis.com/v1/data-points/526927-IB/LATEST-FINANCIAL-ANNUAL-REPORT-DATE?token=[token]`.
### What you expected to happen
Either the latest financial annual report date (if existing) or null/empty response
### What actually happened
An incorrect error `The API key provided is not valid.` was returned (same request with same key works for other companies)

**Comment by adamwozney-iex** [comment]
Hey @dioncodes - Could you double check the symbol "526927-IB" is correct? Which symbol is this company for?

**Comment by dioncodes** [comment]
Hi @adamwozney-iex, the symbol should be correct and works for other requests. The company name is "Dion Global Solutions Ltd.". It is also just an example and the this is not the only company/symbol affected. But even if the symbol was not correct (or no data was found) there should be a different error message.

**Comment by timpaine-iex** [comment]
This error shows up incorrectly when the data point doesn't exist, you can check available data points by just hitting `https://cloud.iexapis.com/v1/data-points/526927-IB`
