### ISSUE TITLE
How to best determine if market is open right now

### ISSUE THREAD

**Issue by bethesdamd** [iexg/IEX-API#1591]
I want to determine when the market's open so I'm not doing unnecessary queries.  I have tried holidays() which today returns Thanksgiving as its first record.  I would like to know if it will return that same date, on that date.  In that manner I'll know the market's closed that day.  Or is there a better approach?  I'm querying the api from a stateless Azure Function so I don't have a persistence layer, so i can't easily create a persistent list of holidays.

**Comment by leedstyh** [comment]
I hard code it because not too much holidays in a year.

https://www.nyse.com/markets/hours-calendars

**Comment by joshuablackburn-iex** [comment]
You can use the free IEX DEEP system event endpoint you determine if the market is open. 

https://iexcloud.io/docs/api/#deep-system-event

Also, the stock quote endpoint returns a key called isUSMarketOpen

**Comment by bethesdamd** [comment]
Thanks.   @joshuablackburn-iex - if I'm using the pyEX python library, how would I get isUSMarketOpen?  pyEX seems to work but its documentation looks like a core dump and is difficult to navigate -- should I be using a better python library to IEX?  https://pyex.readthedocs.io/en/latest/

**Comment by joshuablackburn-iex** [comment]
That is a 3rd party library, so you'll need to reach out to the author.

**Comment by bethesdamd** [comment]
Thank you
