### ISSUE TITLE
Sandbox Historical Data Not Relative To Actual Data

### ISSUE THREAD

**Issue by sthorson99** [iexg/IEX-API#1592]
I realize that sandbox data is scrambled. However you state that the data "resembles" that actual data.

I have found that the sandbox day High is often lower than the Close, and the day Low is Higher than the Close.

It would be great if the sandbox data, though scrambled, would at least be realistic. Its impossible to test strategies with the high and low the way it is currently. Plus it makes any charts I build from the data look awful.

I tested primarily AMZN and MSFT on 5yr data. On AMZN today, out of 1259 results, 406 highs are lower than the close and 383 lows are higher than the close.

**Comment by adamwozney-iex** [comment]
Hey @sthorson99 this sounds like a good idea. For feature requests, I recommend checking out our roadmap on the console: https://iexcloud.io/console/roadmap

You can vote on what you see there currently and suggest new items - the feedback we get on our roadmap is a big factor into how we prioritize what we work on, so we’d love to get your input.

**Comment by sthorson99** [comment]
> Hey @sthorson99 this sounds like a good idea. For feature requests, I recommend checking out our roadmap on the console: https://iexcloud.io/console/roadmap
> 
> You can vote on what you see there currently and suggest new items - the feedback we get on our roadmap is a big factor into how we prioritize what we work on, so we’d love to get your input.

Done
