### ISSUE TITLE
[Data] Question regarding general stance for split adjustment

### ISSUE THREAD

**Issue by DavidKuennen** [iexg/IEX-API#1593]
You have split adjusted historical prices and historical earnings, but not historical dividends (for AAPL). Is this intentional as in you always split adjust historical prices and earnings but not dividends or is this a bug? I need to know that, since it defines how I have to use your data.

**Comment by jesseorosz** [comment]
I'm assuming you are using the dividends-basic endpoint. That endpoint has always been inaccurate and spotty at best.

If you want reliable dividend data you need to use the advanced_dividends endpoint.

Of course that call is only 75,000 vs 10 for the basic.
