### ISSUE TITLE
[Data] Missing data for stock quotes

### ISSUE THREAD

**Issue by bethesdamd** [iexg/IEX-API#1594]
I'm seeing NaN values when querying for stock quote data   E.g. IBM for 10/16/2020 at 09:52am:

https://sandbox.iexapis.com/stable/stock/ibm/intraday-prices?token=Tsk_58c11339b1174c379f7e0f6eb63d1397

Why do these nulls occur?  Thanks.

**Comment by bethesdamd** [comment]
question partially resolved

**Comment by adamwozney-iex** [comment]
Hey there - When we run the end point we don't see any NaN or Null results. Are you still having this issue?

Feel free to contact support directly so we can track. 

support@iexcloud.io
