### ISSUE TITLE
[Data] sector and industry not correct

### ISSUE THREAD

**Issue by sammyonline** [iexg/IEX-API#1596]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
"sector" and "industry" not correct

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/nova/company
https://cloud.iexapis.com/stable/stock/enph/company

**What time did the problem occur (including timezone)?**
2:00pm HKT

**What is the expected behavior?**
industry should be "solar" (according to yahoo finance)

**What are the steps to reproduce**
access url directly on browser

**Your environment (e.g. browser, OS, API version, language):**
windows10 chrome

**Additional context**
{"symbol":"NOVA","companyName":"Sunnova Energy International, Inc.","exchange":"New York Stock Exchange","industry":"Wholesale Distributors","website":"http://www.sunnova.com","description":"Sunnova Energy International, Inc. engages in providing solar and energy storage services. It also offers services to customers who purchased their solar energy system through unaffiliated third parties. The company was founded in January, 2013 and is headquartered in Houston, TX.","CEO":"William Jackson Berger","securityName":"Sunnova Energy International Inc","issueType":"cs","sector":"Distribution Services","primarySicCode":5074,"employees":324,"tags":["Distribution Services","Wholesale Distributors"],"address":"20 East Greenway Plaza","address2":null,"state":"TX","city":"Houston","zip":"77046","country":"US","phone":"1.281.985.9904"}

{"symbol":"ENPH","companyName":"Enphase Energy, Inc.","exchange":"NASDAQ","industry":"Semiconductors","website":"http://www.enphase.com","description":"Enphase Energy, Inc. engages in the design, development, manufacture, and sale of microinverter systems for the solar photovoltaic industry. Its products include IQ 7 Microinverter Series, IQ Battery, IQ Envoy, IQ Microinverter Accessories, IQ Envoy Accessories, and Enlighten & Apps. The company was founded by Raghuveer R. Belur and Martin Fornage in March 2006 and is headquartered in Fremont, CA.","CEO":"Badrinarayanan Kothandaraman","securityName":"Enphase Energy, Inc.","issueType":"cs","sector":"Electronic Technology","primarySicCode":3674,"employees":577,"tags":["Electronic Technology","Semiconductors"],"address":"47281 Bayside Parkway","address2":null,"state":"CA","city":"Fremont","zip":"94538","country":"US","phone":"1.877.797.4743"}

**Comment by joshuablackburn-iex** [comment]
Sector and industry depend on who is defining it. Yahoo is not the authority on sector and industry. These are defined by different groups. The one most people reference is GICS, but that is a proprietary categorization and has a very high license fee.

Wall Street Journal has a completely different sector and industry than Yahoo or IEX Cloud. https://www.wsj.com/market-data/quotes/NOVA/company-people

The open standard to use is NAICS https://www.census.gov/eos/www/naics/  which replaced the SIC  https://www.osha.gov/pls/imis/sic_manual.html
