### ISSUE TITLE
Hi, I would like to know whether you provide ESG data or not.

### ISSUE THREAD

**Issue by MatteoSerafino** [iexg/IEX-API#1599]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adamwozney-iex** [comment]
Hey @MatteoSerafino - Looks like you've reached out to IEX Support and they answered your question. Thanks!
