### ISSUE TITLE
Missing splits for TDW (incorrect historical prices)

### ISSUE THREAD

**Issue by chaolc12** [iexg/IEX-API#160]
## Summary
used iex chart to download prices for TDW, but got wrong prices

## Details

For example on 1/5/17 it shows closing price of $3.63, but multiple other sources I checked shows TDW's closing price on 1/5/17 is above $100

### API URL

https://api.iextrading.com/1.0/stock/tdw/chart/1y

### What you expected to happen

expect the download to show correct price

### What actually happened

api url shows:
...
{"date":"2017-01-05","open":3.82,"high":3.88,"low":3.64,"close":3.69,"volume":1210128,"unadjustedVolume":1210128,"change":-0.09,"changePercent":-2.381,"vwap":3.7471,"label":"Jan 5, 17","changeOverTime":0.02216066481994462}
...

### Other Information (sample code, links, etc.)

multiple prices on TDW are incorrect on other days

**Comment by jcape** [comment]
@chaolc12 This is the result of a 1000:31 reverse split on August 1, 2017 that isn't accounted for in our system. Typically, splits data would be at https://api.iextrading.com/1.0/stock/tdw/splits/1y but it looks like this is missing, so we can't adjust prices before then to reflect the split. We're following up with our corporate actions provider to find out why.

**Comment by joshuablackburn-iex** [comment]
Our provider has updated historical data for this security.
