### ISSUE TITLE
cant seem to get pre market and after market hours data accurately

### ISSUE THREAD

**Issue by dahookher** [iexg/IEX-API#1601]
2020-10-27

What you did: we have accurate real time data during market hours and we added in PM and AH too

What you expected to happen: we wanted to real time data during the day and then have a 15 delay for pre market and after market hours

What actually happened: the real time data during market hours work great but then it gets all weird once AH and PM hrs kick in some tickers some stock prices and some just show $0.00 +0.00f

i cant seem to over come this issue has anyone had this issue and if so how did you over come it thank you

**Comment by adamwozney-iex** [comment]
Hey @dahookher - What endpoint are you using and which symbols are you looking for?

**Comment by evancarter-iex** [comment]
Closing until further information is received.
