### ISSUE TITLE
[Data] AAPL and NEE dividends data do not reflect stock split

### ISSUE THREAD

**Issue by JamesChloroBenzene** [iexg/IEX-API#1603]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
AAPL and NEE dividends data do not reflect stock split
AAPL's next dividend per share is $ 0.205 and it is same as $ 0.82 before stock split (4:1)
Also NEE's next dividend per share is $ 0.35 but is is same as $ 1.4 before stock split (4:1)

**Data URL (The URL you used to access the data without your token):**
stock/aapl/dividends/5y
stock/nee/dividends/5y

**What time did the problem occur (including timezone)?**
Always

**What is the expected behavior?**
Past dividends data should reflect stock split
or at least a flag is needed for basic dividend data.

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
Always

**Additional context**
If dividends data don't reflect stock splits,
dividends data is incorrect and useless as it is unless gathering all stock splits information.

**Comment by WillTron** [comment]
Not sure about NEE, but AAPL still has incorrect past dividend data as of this morning. AAPL's 4:1 split officially took effect on 8/31/2020. The first index element in the /dividends/ EP for AAPL is showing some sort of reference to the split, but it's unclear why a split "event" would appear in the /dividends/ EP. As noted by @JamesChloroBenzene, the EP shows all the dividends for the prior year have the "old" pre-split dividend amounts.

```
{
  "AAPL": {
    "dividends": [
      {
        "exDate": "2020-08-31",
        "paymentDate": "2020-08-28",
        "recordDate": "2020-08-24",
        "declaredDate": "2020-07-30",
        "amount": "",
        "flag": "Stock",
        "currency": "",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-11-02"
      },
      {
        "exDate": "2020-08-07",
        "paymentDate": "2020-08-13",
        "recordDate": "2020-08-10",
        "declaredDate": "2020-07-30",
        "amount": "0.82",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-11-02"
      },
      {
        "exDate": "2020-05-08",
        "paymentDate": "2020-05-14",
        "recordDate": "2020-05-11",
        "declaredDate": "2020-04-30",
        "amount": "0.82",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-11-02"
      },
      {
        "exDate": "2020-02-07",
        "paymentDate": "2020-02-13",
        "recordDate": "2020-02-10",
        "declaredDate": "2020-01-28",
        "amount": "0.77",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-11-02"
      },
      {
        "exDate": "2019-11-07",
        "paymentDate": "2019-11-14",
        "recordDate": "2019-11-11",
        "declaredDate": "2019-10-30",
        "amount": "0.77",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-11-02"
      }
    ]
  }
}
```
However, if you query the /upcoming-dividends/ EP, the output has the correct post-split amount of 0.205 for the upcoming dividend
```
{
  "AAPL": {
    "upcoming-dividends": [
      {
        "exDate": "2020-11-06",
        "paymentDate": "2020-11-12",
        "recordDate": "2020-11-09",
        "declaredDate": "2020-10-29",
        "amount": "0.205",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "AAPL"
      }
    ]
  }
}
```

**Comment by timpaine-iex** [comment]
This appears to be fixed, I no longer see the split incorrectly in the dividend endpoint
