### ISSUE TITLE
[Data] AIIQ missing one day data from chart

### ISSUE THREAD

**Issue by dylanitorium** [iexg/IEX-API#1604]
**Clearly describe the data problem**
Values apart from the date, minute and label of the 1 day data for AIIQ are all either null or 0. 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/AIIQ/chart/1d

**What time did the problem occur (including timezone)?**
October 14th

**What is the expected behavior?**
The one day data to be present

**What are the steps to reproduce**
Make a request to https://cloud.iexapis.com/v1/stock/AIIQ/chart/1d

**Your environment (e.g. browser, OS, API version, language):**
Brave and Chrome on Ubuntu 20.04

**Comment by McQgit** [comment]
@dylanitorium I am not IEX nor did I spend much time on this.  But, I saw data for a couple minutes during the day.  That's all the activity I saw on another site for this - it is very thinly traded.  It's an ETF w/only $5 million in assets, after all.  The 3M average trading volume on another site says about 1,300/day.

I think you'll need to provide more specifics for IEX to pursue this.

**Comment by timpaine-iex** [comment]
closing as this is the likely answer, this is very thinly traded indeed.
