### ISSUE TITLE
[ENHANCEMENT] News from outside of the US

### ISSUE THREAD

**Issue by andrewdevilliers** [iexg/IEX-API#1605]
Hi,

I don't get any data from news or investor info calls outside of the USA stock exchanges. The NYSE and NASDAQ tickers work fine, but any of the others (Canada, EU, etc) don't return anything. Is this a limitation to IEX Cloud or am I doing something wrong?

Thanks for your help.

Andrew

**Comment by timpaine-iex** [comment]
@andrewdevilliers the news source has international news but it looks like its available via [ADRs ](https://www.investopedia.com/terms/a/adr.asp). So to get news on, e.g. `VOD-LN`, you'd use the ADR which is `VOD`.

I'll make a note to look into this further and see if we can make it a bit easier, apologies for the inconvenience.

**Comment by timpaine-iex** [comment]
You can access international news via our CityFalcon premium partner https://iexcloud.io/docs/api/#cityfalcon-news
