### ISSUE TITLE
[Issue] Estimates only returns one period

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#1606]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**

Query:

``https://sandbox.iexapis.com/stable/stock/twtr/estimates?last=4&period=quarter&token=``

```json
{
    "symbol": "TWTR",
    "estimates": [
        {
            "consensusEPS": 0.28,
            "announceTime": "OTB",
            "numberOfEstimates": 33,
            "reportDate": "2021-01-25",
            "fiscalPeriod": "Q4 2020",
            "fiscalEndDate": "2020-12-18",
            "currency": "USD"
        }
    ]
}
```

**What time did the problem occur? (with timezone)**

7pm PST 11/5/20

**What is the expected behavior?**

Multiple periods

**Your environment (e.g. browser, OS, API version, language):**

**API URL (if applicable)**

https://sandbox.iexapis.com/stable/stock/twtr/estimates?last=4&period=quarter&token=

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by timpaine-iex** [comment]
@addisonlynch closing as this looks ok now ([same as this](https://github.com/iexg/IEX-API/issues/1623))  (though estimates is a bit in flux as [detailed in the docs](https://intercom.help/iexcloud/en/articles/4529082-iex-cloud-s-2020-data-upgrade) )
