### ISSUE TITLE
[Issue] Update documentation for API System Metadata

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#1607]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**

In the documentation for API System Metadata https://iexcloud.io/docs/api/#status

The json response is:

```json
{
    "status":"up",
    "version":"BETA",
    "time":1548097469618
}
```

This endpoint now includes ``currentMonthAPICalls`` as well. Documentation outdated

**What time did the problem occur? (with timezone)**

**What is the expected behavior?**

**Your environment (e.g. browser, OS, API version, language):**

**API URL (if applicable)**

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by timpaine-iex** [comment]
@addisonlynch updated, thanks for reporting

<img width="475" alt="Screen Shot 2020-12-16 at 9 08 28 AM" src="https://user-images.githubusercontent.com/74613173/102359016-43bfbb00-3f7e-11eb-82d1-c7ee9661979a.png">
