### ISSUE TITLE
/ref-data/exchange/xxx/symbols endpoint giving "Too Many Requests" error on 10ms interval requests.

### ISSUE THREAD

**Issue by eamonno** [iexg/IEX-API#1608]
Hi There,

I am getting a too many requests error trying to query the symbols data for exchanges. I am looking to automate updating the symbols data locally once per day when it refreshes so I have code like

```
exchanges = query /ref-data/exchanges endpoint
for each exchange in exchanges:
    query /ref-data/exchange/exchange/symbols endpoint
cache the lot locally
```
This means about 55 requests to the latter endpoint. I am trying to parallelise these as much as possible. I have made sure there is at least a 10ms delay between requests in accordance with the query throttling guidelines. I can fiddle around with it and find a time where it works but that's not particularly robust and could break when you add more exchanges later.

It looks like this endpoint is not accepting 10ms interval requests which contradicts the information on request intervals in the documentation.

Please either fix this or document the correct request interval required for that endpoint.

Thanks.

**Comment by aflynn93** [comment]
I've actually had this problem with various endpoints for quite some time. I typically get a "Too Many Requests" error if my calls are less than ~25-27 ms apart. I automatically adjust the sleep interval each time I get this error, but this means my app has to process calls at a much slower rate than the documentation states.

**Comment by eamonno** [comment]
I ended up just having a 10ms default delay and then if I get a too many requests response I just stall all requests for 1 second and then start over. It's far from ideal to be using an ugly hack like that in what's going to be production code but it has worked so far.
