### ISSUE TITLE
Are symbols on AEX not supported?

### ISSUE THREAD

**Issue by justmeonthegit** [iexg/IEX-API#1612]
Hi.

Date/time of the issue
16 nov 2020, with free data plan

What you did
Make a request to https://iexcloud.io/docs/api/#symbols for a list of all symbols

What you expected to happen
See also the symplos of the AEX. Eg. Adyen, Shell

What actually happened
I only saw symbols from the states. 
Are AEX symbols not supported by API or is this depending on the plan?

Additional relevant information
Do we have a matrix which data is available on which plan. I took me ages to find out that your sandbox is not replied good information (like the symbol list)

**Comment by McQgit** [comment]
@justmeonthegit  Try:
/ref-data/region/{region}/symbols
or
/ref-data/exchange/{exchange}/symbols

See docs:
https://iexcloud.io/docs/api/#symbols
and scroll down a bit for international symbols

**Comment by justmeonthegit** [comment]
I took the example from the docs itself which says:
https://sandbox.iexapis.com/stable/ref-data/symbols?token=Tsk_17fd147f68cd4a5ba359fddb25428757

With your info it works. Great !
Thxs for the endpoint info. 
Did I missed this query structure somewhere in the docs?

I'm using the pyhton wrapper iexfinance and do see any documentation about the query option as well...

**Comment by McQgit** [comment]
@justmeonthegit The iexfinance wrapper was developed by a 3rd party.  The IEX folks do not support that.

The IEX docs for the symbols I described are here (and not as I described earlier):
https://iexcloud.io/docs/api/#international-symbols

**Comment by justmeonthegit** [comment]
Ok thxs, Is there a better pyhton wrapper for this ?

**Comment by McQgit** [comment]
@justmeonthegit  Don't think so.  I haven't seen one in this git - you could try searching here and at the iexfinance git.  

I'm not IEX either, you just caught me on a slow day :)  Good luck

**Comment by McQgit** [comment]
@justmeonthegit  I saw this in a mailer from iex today - thought of you :)
https://iexcloud.io/blog/how-to-get-market-data-in-python

**Comment by justmeonthegit** [comment]
@McQgit great. !! Did a quick review. The code looks code goods. I have to see how about support for issues. The api is quit simple so maybe I will do a direct call to the api itself. Thanks !
