### ISSUE TITLE
[Issue] Bad response encoding

### ISSUE THREAD

**Issue by Savrov** [iexg/IEX-API#1614]
**Clearly describe the problem**
Some of String values in Api response return bad encoded string.

**What time did the problem occur? (with timezone)**
11/19/2020 @ 9:04am (UTC)

**What is the expected behaviour?**
Text is readable by human :)

**Your environment (e.g. browser, OS, API version, language):**
Browser, Postman, Mac OS v 11.0.1

**API URL (if applicable)**
`https://sandbox.iexapis.com/stable/stock/AML-LN/company?token=YOUR_TPK_TOKEN`

**What are the steps to reproduce the bug?**
Call the provided endpoint.

**Additional context**
None

**Comment by Savrov** [comment]
Response example:
```
{
    "symbol": "AML-LN",
    "companyName": "Aston Martin Lagonda Global Holdings Plc",
    "exchange": "ceLaht g ncxooknESond",
    "industry": "MVehlocretsoi ",
    "website": "/.atdtwtphaosionarnm:/.gwwnlatsc",
    "description": "nsttdo1ens  pnou   )nWn olsraeo xs:)iA((n.ennotdal ernnc n teegnct 1otP a(urr ed  getBoqty krT ( cas yZdaLocst sua rneoagn Mal os,Sa gotucAUasmpt pi9lo,rgaafat -  eaal)regnigui  ndemsttnrnodnmrloM p r Ran hloBV ,(r hacmge  ngroiin  p sewdiiunlo n o ifeih eos iSnnncG g oe1pibaeedTignoesrde .pqaese o rlwahirihostumnfoat cTd adrmndDeut rhs,e)elai,\"K\"hnsdutyi dtnee nsoul s- rmro HsdcGgu odoVpd ie r aaeGag.oaaed rcuuadenrreiwc ,eTuoDd e euf.r srrVftcggaIsn  Sfeunrn1o npaei)uec sgcrp a-eoppun3",
    "CEO": "ribeMaoosTs ",
    "securityName": "craaogM blgo tinlpanod Gdsio sLa AlHnltn",
    "issueType": "cs",
    "sector": "Dereor Cnalmbsuus",
    "primarySicCode": 3889,
    "employees": null,
    "tags": [
        "rVcslooieMhte ",
        "esleurrCDbamsnu o"
    ],
    "address": "u adaoRrybnB",
    "address2": null,
    "state": "acrkiwireWhs",
    "city": "wraiWkc",
    "zip": "C3V5",
    "country": "BG",
    "phone": "44664446924..1"
}
```

**Comment by Savrov** [comment]
Aha, just mentioned, it happens only in **sandbox** env.

**Comment by McQgit** [comment]
@Savrov Note the sandbox test data is intentionally scrambled.  See:
https://iexcloud.io/docs/api/#testing-sandbox

**Comment by Savrov** [comment]
Aha, got it. Sorry, I'm closing an issue.
