### ISSUE TITLE
Batch Stock API returning null latestClose for BRK.B

### ISSUE THREAD

**Issue by gigamegawatts** [iexg/IEX-API#1619]
**Clearly describe the problem**

The following API call returns null for the latestClose field for BRK.B.  The other symbols I use don't have the same problem (e.g. APPL, BAM, BABA).  Some related fields are also null, but I don't use them so I'm not sure if they are usually null.

`https://cloud.iexapis.com/stable/stock/brk.b/quote?token=<removed my private key>`

The full result is:
`{"symbol":"BRK.B","companyName":"Berkshire Hathaway Inc. - Class B","primaryExchange":"NEW YORK STOCK EXCHANGE, INC.","calculationPrice":"tops","open":null,"openTime":null,"openSource":"official","close":null,"closeTime":null,"closeSource":"official","high":null,"highTime":1606748596760,"highSource":"IEX real time price","low":null,"lowTime":1606765428182,"lowSource":"IEX real time price","latestPrice":228.34,"latestSource":"IEX real time price","latestTime":"2:48:55 PM","latestUpdate":1606765735942,"latestVolume":null,"iexRealtimePrice":228.34,"iexRealtimeSize":1,"iexLastUpdated":1606765735942,"delayedPrice":null,"delayedPriceTime":null,"oddLotDelayedPrice":null,"oddLotDelayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":null,"previousVolume":null,"change":null,"changePercent":null,"volume":null,"iexMarketPercent":0.12796827674117692,"iexVolume":246358,"avgTotalVolume":5208115,"iexBidPrice":228.3,"iexBidSize":200,"iexAskPrice":228.33,"iexAskSize":100,"iexOpen":null,"iexOpenTime":null,"iexClose":228.34,"iexCloseTime":1606765735942,"marketCap":535443787072,"peRatio":null,"week52High":233.92,"week52Low":162.13,"ytdChange":0.022295805739514396,"lastTradeTime":1606765735942,"isUSMarketOpen":true}`

**What time did the problem occur? (with timezone)**

Most recent occurrence was right now (Nov 30 2020, 2:50pm EST).  All of my instances of this API call today have had the same problem.

**What is the expected behavior?**
This field should return a numeric value.

**Your environment (e.g. browser, OS, API version, language):**
Chrome browser version 64 on Windows 10 20H2.

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/brk.b/quote?token=<removed my private key>

**What are the steps to reproduce the bug?**
I simply enter the above URL in the browser. 

**Additional context**
The bug was initially discovered in my .Net C# code, but I reproduced it using the simple API URL above.  This is a new problem - the same quote was returning a correct value on Friday Nov 27.

**Comment by joshuablackburn-iex** [comment]
resolved
