### ISSUE TITLE
market previous call only returning 6 stocks

### ISSUE THREAD

**Issue by jjacob123** [iexg/IEX-API#162]
## Summary
market previous call only returning 6 stocks

## Date/time of issue
1/2/2018 2:07PM EST

### API URL
https://api.iextrading.com/1.0/stock/market/previous

### What you expected to happen
I expected all stocks to be returned for 12/29/2018.

### What actually happened
Only six stocks were returned.

### Other Information (sample code, links, etc.)
The API call from above returned a much larger list on 12/31/2017.

**Comment by joshuablackburn-iex** [comment]
This is an issue related to our [maintenance](https://twitter.com/IEXstatus/status/946869559566524416) on Friday.  This will not be an issue for the next trading day.
