### ISSUE TITLE
Including "last" parameter for /income, /cash-flow, and /balance-sheet returns empty dictionary

### ISSUE THREAD

**Issue by virattt** [iexg/IEX-API#1623]
**Clearly describe the problem**
When I try to include the `last` parameter in my request (on both production and sandbox), the API is returning an empty dictionary `{}` as the response.

**What time did the problem occur? (with timezone)**
Noticed in the evening Pacific time (21:00 on Nov 30, 2020)

**What is the expected behavior?**
The API should return the last `n` number of financial statements.

**Your environment (e.g. browser, OS, API version, language):**
Chrome browser and Postman

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/stock/aapl/balance-sheet?period=quarter&last=4&token=...
https://cloud.iexapis.com/stable/stock/aapl/cash-flow?period=quarter&last=4&token=...

**What are the steps to reproduce the bug?**
Use above URLs and add your token

**Additional context**

**Comment by joonilkim** [comment]
+1

**Comment by addisonlynch** [comment]
+1

**Comment by timpaine-iex** [comment]
@virattt are you still seeing this issue? If so ping me and I'll reopen

<img width="712" alt="Screen Shot 2020-12-16 at 9 05 53 AM" src="https://user-images.githubusercontent.com/74613173/102358771-e6c40500-3f7d-11eb-9a10-59cf35fa5d46.png">

**Comment by virattt** [comment]
@timpaine-iex - just verified the fix.  Thank you!
