### ISSUE TITLE
[Historical Prices] chartInterval query param not working in ranges 1m, 3m, 1y and 5y

### ISSUE THREAD

**Issue by Pfuster12** [iexg/IEX-API#1624]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**
Adding `chartInterval` query param to the historical prices url for ranges 1m, 3m, 1y and 5y, does not return data in given interval. It just returns it for every single day. For example:
https://sandbox.iexapis.com/stable/stock/twtr/chart/3m?token={token}&chartInterval=15

**What time did the problem occur? (with timezone)**
2020-12-01T10:00:00Z

**What is the expected behavior?**
Return data in those ranges with interval.

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Windows 10, stable, English

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/stock/twtr/chart/3m?token={token}&chartInterval=15

**What are the steps to reproduce the bug?**
Call API URL and see that data is returned for every day.

**Additional context**

**Comment by Jerland2** [comment]
Wish there was more documentation on which ranges supported which intervals and general syntax supported... Having trouble getting 30 min intervals for 1 month...  Cant seem to get any more granular than closing for each day.

**Comment by Pfuster12** [comment]
Just an update, I emailed the support team and they fixed this some time ago. I can confirm it is working for me now.

@Jerland2 This endpoint should give you 1 month in 30 minutes intervals: https://sandbox.iexapis.com/stable/stock/AAPL/chart/1mm?token={token}
