### ISSUE TITLE
Quote endpoint: previousClose, change and changePercent are way off for many stocks

### ISSUE THREAD

**Issue by kristjanmar** [iexg/IEX-API#1625]
**Clearly describe the data problem**

The "previousClose", "change" and "changePercent" data points in the quote endpoint are way off.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/DKNG/quote?token=APIKEY

It's also wrong for FSTX, ACET and many others.

**What time did the problem occur (including timezone)?**

About 10am EST.

**Comment by stammy** [comment]
I've also noticed these 3 values no longer work for mutual funds (securityType "oef") - seems like previousClose is always identical to latestPrice for these funds

**Comment by kristjanmar** [comment]
This seems to be working again now, at least for the stocks that were having problems before.

**Comment by lpezet** [comment]
I still see problems with mostly mutual funds.
Was working fine for months, and all of a sudden mutual funds are like 1 day behind.
I get latestSource=Close with latestUpdate=Nov 30 (converted here for clarity) and it's Dec 02 ET for any mutual fund symbol right now (I tried 20+ of them).
Or is it just me?
