### ISSUE TITLE
[Data] Key Stats endpoint is not returning data for non US stocks

### ISSUE THREAD

**Issue by stephanemailhot** [iexg/IEX-API#1626]
**Clearly describe the data problem**
The "Key stats" endpoint (https://iexcloud.io/docs/api/#key-stats) is returning empty data (0.0) for many fields such as the 200 day moving average (day200MovingAvg) but only for international stocks such as TSX or China ADR stocks (for example, RY-CT [Royal Bank of Canada], or TCEHY [Tencent]). It is working fine for US stocks.  For the specific SMA(200) value, I receive Not Found instead of the actual 200 day moving avg value.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/DOO-CT/stats/day200MovingAvg?token=<mytoken>
https://cloud.iexapis.com/stable/stock/DOO-CT/stats?token=<mytoken>

**What time did the problem occur (including timezone)?**
This started around Nov 30 2020, eastern time.

**What is the expected behavior?**
I am expecting to see the SMA(200) data instead of zero when I query the key stats endpoints for TSX stocks.

**What are the steps to reproduce**
Enter URL  https://cloud.iexapis.com/stable/stock/DOO-CT/stats/day200MovingAvg?token=<mytoken>
and receive "Not Found" instead of the actual SMA(200) value.

**Your environment (e.g. browser, OS, API version, language):**
Google Chrome Version 87.0.4280.66 (Official Build) (64-bit), english

**Comment by evancarter-iex** [comment]
Fixed.
