### ISSUE TITLE
Key stats API is broken for individual fields, also float value is 0 for all stocks

### ISSUE THREAD

**Issue by alex-klepa** [iexg/IEX-API#1628]
Works fine:
https://sandbox.iexapis.com/stable/stock/aapl/stats/?token=XXX

This will return **Not found**, for any individual stat: 
https://sandbox.iexapis.com/stable/stock/aapl/stats/float?token=XXX
https://sandbox.iexapis.com/stable/stock/aapl/stats/nextEarningsDate?token=XXX
...

Also **float** value is 0 for all stocks at the moment.

**Comment by joshuablackburn-iex** [comment]
As stated in our docs:
Returns null as of December 1, 2020
