### ISSUE TITLE
COST Change/Change Percentage are wrong

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#1629]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
COST Change/Change Percentage are wrong

Costco Wholesale Corp (COST)
387.55 −4.22(−1.08%)
IEX Last Trade as of December 1, 2020.

should be

387.56+5.79 (+1.52%)
At close: 4:00PM EST

**Data URL (The URL you used to access the data without your token):**
https://iextrading.com/apps/stocks/COST

**What time did the problem occur (including timezone)?**
all day today on Dec 1, 2020

**What is the expected behavior?**
387.56+5.79 (+1.52%)
At close: 4:00PM EST

**What are the steps to reproduce**
Here is your data
https://iextrading.com/apps/stocks/COST

Compared to Yahoo Finance and CNBC and others

https://finance.yahoo.com/quote/COST?p=COST
https://www.cnbc.com/quotes/?symbol=COST

**Your environment (e.g. browser, OS, API version, language):**
And browser and API

**Additional context**

**Comment by evancarter-iex** [comment]
Fixed.
