### ISSUE TITLE
Pre-market trade data activity discrepancy

### ISSUE THREAD

**Issue by brentis** [iexg/IEX-API#163]
## Summary

Compared trades in pre-market to current feed and only reported the following during  7am to 8am EST today.

[ { symbol: 'USLV', price: 12.04, size: 800, time: 1514987984976 },   { symbol: 'MGI', price: 12.25, size: 100, time: 1514987802346 },   { symbol: 'DGAZ', price: 25.74, size: 300, time: 1514986624275 },   { symbol: 'NVDA', price: 204.5, size: 300, time: 1514986916477 },   { symbol: 'AMD', price: 11.85, size: 200, time: 1514986979041 },   { symbol: 'INTC', price: 45.3, size: 100, time: 1514986474273 },   { symbol: 'CVX', price: 127.78, size: 100, time: 1514987108259 },   { symbol: 'GE', price: 18.2, size: 100, time: 1514986316255 },   { symbol: 'RIOT', price: 27.55, size: 100, time: 1514988066319 },   { symbol: 'ZVZZT', price: 10.01, size: 1025, time: 1514984427833 } ]

## Details

Looking for alternate data provider and was curious to see how your extended hours data was working.  We were motivated to look at this due to not seeing the timestamp being updated much past market close on the Epoch value.  

This raises the question of whether you are reporting only trade data that takes place in IEX only or if you are reporting last trades from all the markets you show https://iextrading.com/apps/market/

### Date/time of issue

1/03/2018: from 7-8am EST

### API URL

https://api.iextrading.com/1.0/tops/last

### What you expected to happen

Expected to see trade activity commensurate with current provider but only received 10 or so updates.

### What I'd like answered

Why would only a few reports be provided?  Is this because you only report trades from within IEX or is there a parameter or something I am doing wrong to see all pre-market activity?  Given there are 8000 or so supported symbols, I think you can see how something seems awry.  

Thank you.

**Comment by brentis** [comment]
Additionally, When looking at today's afterhours activity.  The timestamps updates still show near or around 3:59 EST, with no indication of after hours update.  Here is a snippet of a few.

[{"symbol":"INTC","price":45.19,"size":300,"time":1515013198597},{"symbol":"GDX","price":23.555,"size":1000,"time":1515013199167},{"symbol":"AMD","price":11.535,"size":200,"time":1515013198627},{"symbol":"GE","price":18.145,"size":100,"time":1515013196789},{"symbol":"SPY","price":270.47,"size":1700,"time":1515013522521},{"symbol":"CX","price":7.875,"size":2100,"time":1515013190041},{"symbol":"BAC","price":29.805,"size":100,"time":1515013197700},{"symbol":"EEM","price":48.52,"size":1468,"time":1515013462404},{"symbol":"CFG","price":43.18,"size":100,"time":1515013198623},{"symbol":"EFA","price":71.195,"size":100,"time":1515013198233},{"symbol":"MDLZ","price":42.555,"size":300,"time":1515013199591},{"symbol":"WFT","price":3.665,"size":100,"time":1515013198870},{"symbol":"MSFT","price":86.3,"size":51,"time":1515013199075},{"symbol":"C","price":74.57,"size":200,"time":1515013199035},{"symbol":"T","price":37.66,"size":300,"time":1515013197681},{"symbol":"EBAY","price":39.25,"size":100,"time":1515013199861},{"symbol":"ORCL","price":47.71,"size":800,"time":1515013197001},{"symbol":"XLU","price":51.79,"size":100,"time":1515013190394},{"symbol":"AAPL","price":172.06,"size":100,"time":1515013198605},{"symbol":"SIRI","price":5.195,"size":100,"time":1515013181275},{"symbol":"M","price":25.33,"size":100,"time":1515013198566},{"symbol":"EWZ","price":42.19,"size":100,"time":1515013199799},{"symbol":"CZR","price":12.475,"size":200,"time":1515013197486},{"symbol":"ZNGA","price":4.015,"size":100,"time":1515013173373},{"symbol":"MU","price":44.965,"size":100,"time":1515013198787},{"symbol":"FCX","price":19.48,"size":600,"time":1515013196527},{"symbol":"KMI","price":18.95,"size":4,"time":1515013198037},{"symbol":"XLF","price":28.065,"size":100,"time":1515013195736},{"symbol":"CHK","price":4.065,"size":400,"time":1515013195053},{"symbol":"JNK","price":36.935,"size":1500,"time":1515013195353},{"symbol":"FB","price":184.48,"size":100,"time":1515013198624},{"symbol":"CSCO","price":39.14,"size":100,"time":1515013197081},{"symbol":"KMX","price":66.95,"size":100,"time":1515013190058},{"symbol":"VWO","price":47.14,"size":3600,"time":1515013199802},{"symbol":"STLD","price":45.59,"size":100,"time":1515013195075},{"symbol":"DDR","price":9.105,"size":189,"time":1515013195027},{"symbol":"JCP","price":3.7,"size":600,"time":1515013189032},{"symbol":"KGC","price":4.465,"size":200,"time":1515013184018},{"symbol":"CMCSA","price":40.38,"size":217,"time":1515013197762},{"symbol":"IAU","price":12.63,"size":2600,"time":1515013105140},{"symbol":"HBAN","price":14.715,"size":916,"time":1515013185225},{"symbol":"USO","price":12.34,"size":200,"time":1515013175900},{"symbol":"TEVA","price":19.13,"size":100,"time":1515013194017},{"symbol":"AKS","price":6.335,"size":100,"time":1515013195044},{"symbol":"RAD","price":2.105,"size":100,"time":1515013191954},{"symbol":"FOXA","price":36.59,"size":100,"time":1515013197802},{"symbol":"RSX","price":22.04,"size":500,"time":1515013197462},{"symbol":"IBM","price":158.45,"size":100,"time":1515013199084},{"symbol":"F","price":12.755,"size":148,"time":1515013197912},{"symbol":"PBR","price":10.975,"size":100,"time":1515013199194},{"symbol":"SCG","price":47.65,"size":100,"time":1515013197699},{"symbol":"EQT","price":58.9,"size":200,"time":1515013197700},{"symbol":"BABA","price":184,"size":100,"time":1515013197318},{"symbol":"OIH","price":27.22,"size":100,"time":1515013188838},{"symbol":"XOM","price":86.685,"size":100,"time":1515013199336},{"symbol":"D","price":77.23,"size":100,"time":1515013195785},{"symbol":"CCC","price":21.325,"size":100,"time":1515013195344},{"symbol":"UAL","price":68.485,"size":100,"time":1515013197202},{"symbol":"GM","price":42.81,"size":100,"time":1515013199086},{"symbol":"CVX","price":128.44,"size":100,"time":1515013197702},{"symbol":"MDT","price":83.87,"size":100,"time":1515013198168},{"symbol":"VZ","price":52.4,"size":100,"time":1515013197843},{"symbol":"AMLP","price":11.33,"size":100,"time":1515013189492},{"symbol":"XRT","price":46,"size":100,"time":1515013183616},{"symbol":"BB","price":13.53,"size":100,"time":1515013186205},{"symbol":"OAS","price":8.805,"size":500,"time":1515013190319},{"symbol":"V","price":115.64,"size":200,"time":1515013198527},{"symbol":"XOP","price":38.565,"size":200,"time":1515013198377},{"symbol":"NVDA","price":212.47,"size":43,"time":1515013197712},{"symbol":"NKE","price":63.46,"size":100,"time":1515013197740},{"symbol":"HYG","price":87.745,"size":100,"time":1515013187406},{"symbol":"KR","price":27.845,"size":200,"time":1515013198151},{"symbol":"ESV","price":6.605,"size":400,"time":1515013199831},{"symbol":"PFE","price":36.69,"size":80,"time":1515013199034},{"symbol":"ALLY","price":29.28,"size":200,"time":1515013198336},{"symbol":"TJX","price":75.3,"size":100,"time":1515013197704},{"symbol":"SCMP","price":17.975,"size":23,"time":1515013195872},{"symbol":"MRK","price":56.12,"size":20,"time":1515013197743},{"symbol":"MGI","price":12.11,"size":100,"time":1515013186354},{"symbol":"BSX","price":25.555,"size":200,"time":1515013191816},{"symbol":"GG","price":13.325,"size":104,"time":1515013198548},{"symbol":"NBR","price":7.055,"size":100,"time":1515013198962},{"symbol":"ABEV","price":6.645,"size":43,"time":1515013169918},{"symbol":"GSAT","price":1.335,"size":300,"time":1515013198121},{"symbol":"VER","price":7.755,"size":200,"time":1515013149006},{"symbol":"TIP","price":113.925,"size":100,"time":1515013191081},{"symbol":"DIS","price":112.23,"size":100,"time":1515013198897},{"symbol":"KLAC","price":107.34,"size":100,"time":1515013197762},{"symbol":"XLE","price":74.52,"size":700,"time":1515013198623},{"symbol":"MYL","price":43.12,"size":100,"time":1515013197683},{"symbol":"CVS","price":73.18,"size":100,"time":1515013198088},{"symbol":"AMGP","price":21,"size":100,"time":1515013198165},{"symbol":"SYMC","price":28.9,"size":100,"time":1515013197684},{"symbol":"SWN","price":5.91,"size":300,"time":1515013199902},{"symbol":"EWJ","price":61.11,"size":56,"time":1515013194095},{"symbol":"VEA","price":45.515,"size":259,"time":1515013199010},{"symbol":"ICON","price":1.195,"size":116,"time":1515013199122},{"symbol":"QEP","price":10.37,"size":200,"time":1515013192933},{"symbol":"VALE","price":12.85,"size":156,"time":1515013198973},{"symbol":"ON","price":22.775,"size":100,"time":1515013198411},{"symbol":"HPE","price":14.705,"size":197,"time":1515013191212},{"symbol":"IAG","price":6.04,"size":100,"time":1515013089241},{"symbol":"RIG","price":11.17,"size":100,"time":1515013196257},{"symbol":"CLF","price":7.845,"size":100,"time":1515013199006},{"symbol":"NLY","price":11.455,"size":437,"time":1515013195041},{"symbol":"ARNC","price":27.995,"size":100,"time":1515013198123},{"symbol":"XLK","price":65.26,"size":900,"time":1515013199053},{"symbol":"MSGN","price":21.15,"size":100,"time":1515013157835},{"symbol":"WFC","price":61.585,"size":60,"time":1515013194583},{"symbol":"AUY","price":3.2,"size":93,"time":1515013195027},{"symbol":"RF","price":17.41,"size":100,"time":1515013190515},{"symbol":"TSM","price":41.71,"size":400,"time":1515013197022},{"symbol":"DAL","price":55.685,"size":200,"time":1515013198261},{"symbol":"MAS","price":43.98,"size":100,"time":1515013197694},{"symbol":"QCOM","price":65.91,"size":100,"time":1515013199285},{"symbol":"WU","price":19.075,"size":100,"time":1515013195050},{"symbol":"PYPL","price":76.78,"size":100,"time":1515013199218},{"symbol":"WMB","price":31.985,"size":100,"time":1515013199055},{"symbol":"UAA","price":15.73,"size":200,"time":1515013190996},{"symbol":"VEON","price":3.99,"size":400,"time":1515013197021},{"symbol":"ABX","price":15,"size":100,"time":1515013195601},{"symbol":"KEY","price":20.23,"size":100,"time":1515013198151},{"symbol":"VRX","price":23.01,"size":200,"time":1515013195105},{"symbol":"HOG","price":50.035,"size":109,"time":1515013195020},{"symbol":"NOK","price":4.825,"size":2000,"time":1515012826367},{"symbol":"NLSN","price":35.99,"size":100,"time":1515013196143},{"symbol":"HAL","price":50.51,"size":4,"time":1515013195043},{"symbol":"IEMG","price":58.51,"size":55,"time":1515013193203},{"symbol":"IWM","price":154.14,"size":53,"time":1515013212714},{"symbol":"PPL","price":30.655,"size":200,"time":1515013197693},{"symbol":"AEE","price":58.075,"size":100,"time":1515013195035},{"symbol":"S","price"

**Comment by joshuablackburn-iex** [comment]
The /last endpoint is an IEX only data feed of our trades.  To get pre/post market prices, you'll want to use /stock/quote.  That includes latestPrice which will continue to update until the end of our system hours at 5pm.

**Comment by brentis** [comment]
That is under-documented and/or unintuitive. Is there not a websocket firehose that could provide this?  Also only a 100 symbols per batch request and I would have to make 80 requests a second or so to get breadth to determine what is updated?   Welcome ideas on how to observe all symbols' market activity.  Primary needs are timestamp/symbol/last price in near realtime during and extended hours.

**Comment by joshuablackburn-iex** [comment]
Our documentation is pretty clear that TOPS and LAST are IEX market data.  They are even listed under "IEX Market Data".  Stock quotes are not currently available via WebSocket, and we are aware of the need.  We'd like to use it ourselves.  We are working on a more efficient method of distribution (SSE) which is currently in QA.

**Comment by brentis** [comment]
could you advise on batch query approach question above?

**Comment by joshuablackburn-iex** [comment]
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb,tsla,ge&filter=latestUpdate,latestPrice,symbol&types=quote

Just use your own symbols list

**Comment by brentis** [comment]
Josh - You are missing my point.  I'm scanning for market changes on all symbols. My "list" is breadth of market which is 6500-8000 symbols.  Is there a way I can do this without exceeding rate limits or violating terms? 

Thank you.

**Comment by joshuablackburn-iex** [comment]
At this time you are not able to do this, and based current terms and agreements we have with our data providers, we are unable to provide a larger number of symbols per call.  If this changes we will update our documentation.  You should be able to get a fairly large number of symbols under the current rate limits by making multiple batch requests.  Once we release SSE that will provide a more efficient way to receive updates.  Despite the current limitations, I doubt all 8500+ symbols will update frequently between 4-5pm.
