### ISSUE TITLE
Charts have stopped working for OTC stocks

### ISSUE THREAD

**Issue by kristjanmar** [iexg/IEX-API#1631]
**Clearly describe the problem**

The chart endpoint has stopped working for most OTC stocks. Examples: ASNAQ, CLUB, ZNOG, AFHIF and many others.

**What time did the problem occur? (with timezone)**

Started on December 1.

**What is the expected behavior?**

The API should respond with data. The response is currently completely empty, no error message or anything.

**API URL (if applicable)**

https://cloud.iexapis.com/stable/stock/AFHIF/chart/1y?token=APIKEY

**Additional context**

This used to work reliably before Dec 1.

**Comment by timpaine-iex** [comment]
I don't see `ASNAQ` trading but the others seem ok now.
