### ISSUE TITLE
[Data] Missing for some symbol when chartByDay=true

### ISSUE THREAD

**Issue by shf0328** [iexg/IEX-API#1632]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
For some symbols, the data presents when chartByDay=false, but is missing when chartByDay=true,

**Data URL (The URL you used to access the data without your token):**
has data:
https://cloud.iexapis.com/v1/stock/ALC/chart/date/20201120?chartByDay=false 

no data:
https://cloud.iexapis.com/v1/stock/ALC/chart/date/20201120?chartByDay=true

**What time did the problem occur (including timezone)?**
2020-12-01 10pm ET

**What is the expected behavior?**
All API call should have at least one point.

**What are the steps to reproduce**
Add token and use above URL

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Win 10, API v1, python

**Additional context**

**Comment by evdubs** [comment]
Similarly, using batch data URLs with chartByDay=true also do not work.

Data URL:
https://cloud.iexapis.com/stable/stock/market/batch?symbols=ALC&types=chart&range=date&exactDate=20201120&chartByDay=true

What time did the problem occur (including timezone)?
2020-12-01 5:00 ET

What is the expected behavior?
```json
"ALC":{"chart":[{"date":"2020-11-20",
"uClose":62.84,
"uOpen":62.78,
"uHigh":63.07,
"uLow":62.49,
"uVolume":656717,
"close":62.84,
"open":62.78,
"high":63.07,
"low":62.49,
"volume":656717,
"currency":"",
"change":-0.5,
"changePercent":-0.7894,
"label":"Nov 20",
"changeOverTime":-0.007894}]}
```
What is the actual behavior?
```
"ALC":{"chart":null}
```

**Comment by evdubs** [comment]
This looks to be fixed now.

**Comment by shf0328** [comment]
> This looks to be fixed now.

No, this haven't been fixed, it's still the same issue.

**Comment by evdubs** [comment]
Are you able to view data for other symbols?

**Comment by shf0328** [comment]
> Are you able to view data for other symbols?

Yes, other symbols are available, but OTC symbols are still not accessible as described in the other issue.

**Comment by shf0328** [comment]
Just find the QCOM symbol missed data for 2020-12-02, okay for previous dates.

**Comment by evancarter-iex** [comment]
Fixed
