### ISSUE TITLE
Charts don't work for many NASDAQ and NYSE stocks

### ISSUE THREAD

**Issue by kristjanmar** [iexg/IEX-API#1633]
**Clearly describe the problem**

The charts don't work for many lesser known NASDAQ and NYSE stocks.

The API simply responds with []

**What time did the problem occur? (with timezone)**

Started on December 1st.

**API URL (if applicable)**

https://cloud.iexapis.com/stable/stock/HUGE/chart/1y?token=APIKEY
https://cloud.iexapis.com/stable/stock/PLAG/chart/1y?token=APIKEY
https://cloud.iexapis.com/stable/stock/TSEM/chart/1y?token=APIKEY
https://cloud.iexapis.com/stable/stock/KMDA/chart/1y?token=APIKEY
https://cloud.iexapis.com/stable/stock/BORR/chart/1y?token=APIKEY
https://cloud.iexapis.com/stable/stock/FLNG/chart/1y?token=APIKEY
https://cloud.iexapis.com/stable/stock/GSH/chart/1y?token=APIKEY

**Additional context**

These worked fine before the platform changes that were rolled out on December 1st.

**Comment by rmantovani** [comment]
same issue here.

**Comment by rmantovani** [comment]
Another issue related is unajusted fields missing in many chart parameters, just works for one day before "The Upgrade" everything works fine

**Comment by evancarter-iex** [comment]
This is resolved.
