### ISSUE TITLE
securityType not returning expected values for a stock 

### ISSUE THREAD

**Issue by stammy** [iexg/IEX-API#1635]
For VTSAX I am getting "MF_O" when I would have expected "oef"

**Comment by timpaine-iex** [comment]
@stammy this looks ok for me now, please ping me if you're still seeing issues and I'll reopen

<img width="597" alt="Screen Shot 2020-12-16 at 8 56 36 AM" src="https://user-images.githubusercontent.com/74613173/102357716-a1eb9e80-3f7c-11eb-9c50-39ca029a4424.png">

**Comment by stammy** [comment]
I'm not seeing that on my end. 

I rely on the securityType value (looks like it was renamed in your example too?) in the batch endpoint and the search endpoint. 

The batch endpoint returns nothing for security/issue type.
The search endpoint returns "securityType" but with value inconsistent to your documentation. And the documentation example code even shows the incorrect return values ("SHARE" instead of "cs" etc)

Batch endpoint and search endpoints below:

<img width="457" alt="Screen Shot 2020-12-16 at 9 07 19 AM" src="https://user-images.githubusercontent.com/30445/102359040-4cb08c80-3f7e-11eb-8e04-3f60e1a2f0b8.png">
<img width="842" alt="Screen Shot 2020-12-16 at 9 05 56 AM" src="https://user-images.githubusercontent.com/30445/102359043-4cb08c80-3f7e-11eb-99fc-986695a34107.png">

**Comment by timpaine-iex** [comment]
search is reported here: https://github.com/iexg/IEX-API/issues/1634 and will be normalized

quote doesn't return `securityType`, consistent with the [documentation](https://iexcloud.io/docs/api/#quote).

**Comment by timpaine-iex** [comment]
was your original issue reporting about `search`? if so just subscribe to watch the other issue and I'll report the resolution there

**Comment by stammy** [comment]
Ah you're totally right re: quote endpoint, was confused there. Thanks.

**Comment by timpaine-iex** [comment]
@stammy no problem, thanks for reporting!
