### ISSUE TITLE
longTermDebt, totalDebt, totalCash are null in /financials API

### ISSUE THREAD

**Issue by virattt** [iexg/IEX-API#1636]
**Clearly describe the problem**
The `/financials` API is returning `null` for `longTermDebt`, `totalDebt`, and `totalCash`.

**What time did the problem occur? (with timezone)**
Noticed December 2, 2020 17:00 Pacific Time

**What is the expected behavior?**
The `/financials` API should return non-null values as specified by the documentation [here](https://iexcloud.io/docs/api/#financials).

**Your environment (e.g. browser, OS, API version, language):**
Postman, Chrome

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/AAPL/financials?period=quarter&token=API_TOKEN

**What are the steps to reproduce the bug?**
Do a GET call on https://cloud.iexapis.com/stable/stock/AAPL/financials?period=quarter&token=API_TOKEN and notice that `longTermDebt`, `totalDebt`, and `totalCash` are `null`.

**Additional context**
It looks like some internal API changes have been occurring, which are being propagated into the external API.  These are pretty serious breaking changes and it would be great to get some clarity on is happening to the APIs... :(

**Comment by timpaine-iex** [comment]
@virattt we've taken some time to map these from the new fundamentals endpoint, can you check again (@ben-berman-iex)

**Comment by evancarter-iex** [comment]
Fixed.
