### ISSUE TITLE
Previous price data missing for 2/December/2020 for AT & T

### ISSUE THREAD

**Issue by rsksmiles** [iexg/IEX-API#1638]
Running the following:

**`https://cloud.iexapis.com/stable/stock/market/batch?symbols=T&types=previous&token=MY_TOKEN`**

is returning the price for the 1st December and not for the 2nd December (See JSON below).

This was executed at 13:42 Central European Time.

This was executed in Postman on a windows 10 OS in English

Prior to the switch to the new Data Source IEX was making the previous day available by 10:00 Central European which was never very stable and so I delayed my refresh until 11:00 Central European Time.

What is the new time that the data will be made available ?

Appreciate I am not a super dooper high paying customer but I must be only one of many who have this sort of issue.

You need to sort out how you do your data upgrades and test / beta test a bit more thoroughly.

{
    "T": {
        "previous": {
            "close": 28.87,
            "high": 29.14,
            "low": 28.745,
            "open": 28.82,
            "symbol": "T",
            "volume": 42064174,
            "id": "HISTORICAL_PRICES",
            "key": "T",
            "subkey": "",
            "date": "2020-12-01",
            "updated": 1606882674000,
            "changeOverTime": 0,
            "marketChangeOverTime": 0,
            "uOpen": 28.82,
            "uClose": 28.87,
            "uHigh": 29.14,
            "uLow": 28.745,
            "uVolume": 42064174,
            "fOpen": 28.82,
            "fClose": 28.87,
            "fHigh": 29.14,
            "fLow": 28.745,
            "fVolume": 42064174,
            "label": "Dec 1, 20",
            "change": 0,
            "changePercent": 0
        }
    }
}

**Comment by evancarter-iex** [comment]
Fixed.
