### ISSUE TITLE
Status Updates

### ISSUE THREAD

**Issue by rsksmiles** [iexg/IEX-API#1639]
The status updates on the url https://status.iexcloud.io/ is not really very helpfull.

How about a status of what is the latest data available in terms of the different exchanges prices and dividends etc.

A statement of when previous day closes will be available would be good aswell.

**Comment by timpaine-iex** [comment]
@rsksmiles please submit your idea on https://iexcloud.io/console/roadmap and we can see how it falls with the rest of the roadmap, thanks!
