### ISSUE TITLE
API "chart/date/" not working

### ISSUE THREAD

**Issue by zarzen** [iexg/IEX-API#164]
## Summary
API `chart/date/` return empty list

## Details
Http request [https://api.iextrading.com/1.0/stock/aapl/chart/date/20170919](https://api.iextrading.com/1.0/stock/aapl/chart/date/20170919) return empty list.

### Date/time of issue
01-04-2018

### API URL
[https://api.iextrading.com/1.0/stock/aapl/chart/date/20170919](https://api.iextrading.com/1.0/stock/aapl/chart/date/20170919)

### What you expected to happen
It should return the data by minute in that day as documented. 

### What actually happened
return an empty list

**Comment by joshuablackburn-iex** [comment]
We can only ensure trailing 30 calendar days of minute bar history at this time.  Our documentation will be updated to make this more clear.
