### ISSUE TITLE
Advanced Fundamentals is missing documented fields

### ISSUE THREAD

**Issue by philippschladitz** [iexg/IEX-API#1640]
**Clearly describe the problem**
The new advanced fundamentals endpoint states the following fields would exist:
assets
assetsCurrent

The fields are missing, for example here: 
https://sandbox.iexapis.com/stable/time-series/fundamentals/F/annual?token=Tsk_cbf654802ddf4d7684fcc0e04ca190c2

**What time did the problem occur? (with timezone)**
Everytime

**What is the expected behavior?**
Add all fields from the documentation to the endpoint. Add assets, add assets current.
Maybe other fields are also missing. 

**Your environment (e.g. browser, OS, API version, language):**
Postman

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/time-series/fundamentals/F/annual?token=Tsk_cbf654802ddf4d7684fcc0e04ca190c2

**What are the steps to reproduce the bug?**
1. Call: https://sandbox.iexapis.com/stable/time-series/fundamentals/F/annual?token=Tsk_cbf654802ddf4d7684fcc0e04ca190c2
2. Look at result and then in documentation

**Comment by timpaine-iex** [comment]
@philippschladitz docs have been updated, please ping me if you see a discrepancy and I'll reopen
