### ISSUE TITLE
[Data] Quote and Batch Quote return null on high and low 

### ISSUE THREAD

**Issue by frankzkzhu** [iexg/IEX-API#1642]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**

**Data URL (The URL you used to access the data without your token):**

**What time did the problem occur (including timezone)?**

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by frankzkzhu** [comment]
BatchQuote and Quote return null value on high and low since this morning (12/3/2020) on NASDAQ Ticks. Is it migration issue?

**Comment by timpaine-iex** [comment]
Closing as you did not fill in the template, and this is likely covered in [the help center docs on nasdaq restrictions](https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud)
