### ISSUE TITLE
[Data] Previous day change and changePercent always 0 starting Dec 1, 2020

### ISSUE THREAD

**Issue by matt-schwartz** [iexg/IEX-API#1645]
**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/tsla/previous
https://sandbox.iexapis.com/v1/stock/tsla/previous

**What time did the problem occur (including timezone)?**
Started Dec 1, 2020, 5am EST.  Still occurring as of this writing on Dec 4.

**What is the expected behavior?**
The "change" and "changePercent" fields of the JSON response should contain non-zero values on days the stock price changed.  Every stock I query is returning 0.

**What are the steps to reproduce**
Direct HTTPS request against the /stock/{symbol}/previous endpoint.

**Your environment (e.g. browser, OS, API version, language):**
API v1, Linux, making requests from Python.

**Comment by evancarter-iex** [comment]
Fixed.
