### ISSUE TITLE
[Data] Quote on specific date doesn't match Nasdaq or Yahoo! Finance records

### ISSUE THREAD

**Issue by tciuro** [iexg/IEX-API#1649]
**Clearly describe the data problem**

I'd like to retrieve the day's quote for a given date: Oct. 15, 2020

This is what I get with Nasdaq or Yahoo! Finance:

```
Date          Close/Last     Volume         Open       High      Low
10/15/2020    $120.71        112,559,200    $118.72    $121.2    $118.15

```
**Data URL (The URL you used to access the data without your token):**

`https://sandbox.iexapis.com/stable/stock/aapl/chart/date/20201015?chartByDay=true&token=Tsk_xxx`

**What time did the problem occur (including timezone)?**

Dec. 4, 2020 @ 15:45 PST

**What is the expected behavior?**

A payload matching the Nasdaq/Yahoo values.

**What are the steps to reproduce**

Just enter the above URL and compare values.

**Your environment (e.g. browser, OS, API version, language):**

Mac OS X Big Sur, Safari

**Additional context**

**Comment by gromgit** [comment]
You're using the sandbox API, and as https://intercom.help/iexcloud/en/articles/2915433-testing-with-the-iex-cloud-sandbox states:
> Note that the IEX Cloud sandbox only returns randomized test data and is meant to mimic the results returned from the production API. The sandbox environment cannot be used to access real financial data.
