### ISSUE TITLE
5y chart for BRK.B missing vwap field for some of the days

### ISSUE THREAD

**Issue by somnath-nirakari** [iexg/IEX-API#165]
## Summary
In the response for 5 yr chart data for BRK.B vwap field is missing for some of the days.
I am not sure if this is specific to this symbol or could be replicated with other symbols.

## Details
    {
        "date": "2013-01-04",
        "open": 28.01,
        "high": 28.93,
        "low": 27.83,
        "close": 28.76,
        "volume": 72623547,
        "unadjustedVolume": 72623547,
        "change": 0.99,
        "changePercent": 3.565,
        **"vwap": 28.4607**,
        "label": "Jan 4, 13",
        "changeOverTime": 0
    }

Missing vwap
   {
        "date": "2013-01-04",
        "open": 93.74,
        "high": 94.05,
        "low": 93.36,
        "close": 93.85,
        "volume": 4142200,
        "unadjustedVolume": 4142200,
        "change": 0.23,
        "changePercent": 0.246,
        "label": "Jan 4, 13",
        "changeOverTime": 0
   }

### Date/time of issue
01/04/2018 1.30 PM

### API URL
https://api.iextrading.com/1.0/stock/BRK.B/chart/5y

### What you expected to happen
vwap field to be present for all days in the response

### What actually happened
vwap field was present in some days but missing for others. I couldn't find a pattern to it.

**Comment by joshuablackburn-iex** [comment]
At this time vwap data comes from our data provider, and we cannot guarantee the availability for all securities.
