### ISSUE TITLE
[Data] Total Cash/Total Debt null on financials endpoint

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#1650]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**

It seems that total cash and total debt are now always null on the financials endpoint. 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/fb/financials?token=<token>

**What time did the problem occur (including timezone)?**
9 am PST

**What is the expected behavior?**
not null.

**What are the steps to reproduce**

call API.
**Your environment (e.g. browser, OS, API version, language):**

Chrome
**Additional context**

Cannot find in any documents as to why these are now null, and not mentioned in the blog posts about new release.

**Comment by timpaine-iex** [comment]
duplicate https://github.com/iexg/IEX-API/issues/1636
