### ISSUE TITLE
[Issue] Legacy Fundamentals (Balance Sheet, Income Statement, Cash Flows) only return up to 3 periods

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#1654]
**Clearly describe the problem**

The following endpoints only return up to 3 periods when they should return up to 12 when the ``last`` parameter is used:

* Balance Sheet
* Income Statement
* Cash Flow

**What time did the problem occur? (with timezone)**

2:17 HST 12/6/20

**What is the expected behavior?**

Up to 12 periods for quarterly

**Your environment (e.g. browser, OS, API version, language):**

Sandbox and API V1. 

**API URL (if applicable)**

https://sandbox.iexapis.com/stable/stock/market/batch?symbols=AAPL&types=balance-sheet&last=4&token=
https://sandbox.iexapis.com/stable/stock/market/batch?symbols=AAPL&types=income-statement&last=4&token=
https://sandbox.iexapis.com/stable/stock/market/batch?symbols=AAPL&types=cash-flow&last=4&token=

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by adamwozney-iex** [comment]
Hey @addisonlynch - We recently updated our [READme](https://github.com/iexg/IEX-API/blob/master/README.md) file and moved all support or bug related questions to another channel. Please reach out to support@iexcloud.io and our support team will follow-up with you there. I think you're already in touch, but wanted to let you know. Sorry for any confusion.

Thanks.

**Comment by addisonlynch** [comment]
@adamwozney-iex thanks for letting me know. Is there reason is this tracker still open? It's going to be tedious to start an email thread for each issue....

**Comment by adamwozney-iex** [comment]
Hey @addisonlynch - Thanks for flagging. Let me connect with our support team and follow-up.

**Comment by timpaine-iex** [comment]
@addisonlynch can you ping me if you're still seeing this and I'll reopen
<img width="744" alt="Screen Shot 2020-12-16 at 11 33 05 AM" src="https://user-images.githubusercontent.com/74613173/102377256-783d7200-3f92-11eb-9516-37bacaea9884.png">
