### ISSUE TITLE
[Issue] sort=desc query Param returns 500 Unexpected Error in 1d historical prices

### ISSUE THREAD

**Issue by Pfuster12** [iexg/IEX-API#1656]
**Clearly describe the problem**
 sort=desc query Param returns 500 Unexpected Error in 1d historical prices

**What time did the problem occur? (with timezone)**
2020-12-08T00:00:00Z

**What is the expected behavior?**
return data

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Windows 10, stable, English

**API URL (if applicable)**
https://sandbox.iexapis.com/stable/stock/twtr/chart/1d?token={token}&chartInterval=15&sort=desc

**What are the steps to reproduce the bug?**
Call url.

**Additional context**

**Comment by adamwozney-iex** [comment]
Hey @Pfuster12 - We recently updated our [READme](https://github.com/iexg/IEX-API/blob/master/README.md) file and moved all support or bug related questions to another channel. Please reach out to support@iexcloud.io and our support team will follow-up with you there. Sorry for any confusion.

Thanks.
