### ISSUE TITLE
[Data] missing amount on dividends API

### ISSUE THREAD

**Issue by achitofel** [iexg/IEX-API#1657]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
the dividend api returns 0 as the amount value for dividends, most of the time its with ETFs

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/sphd/dividends/next?token=
https://cloud.iexapis.com/stable/stock/bndx/dividends/next?token=
https://cloud.iexapis.com/stable/stock/spyd/dividends/next?token=
https://cloud.iexapis.com/stable/stock/vymi/dividends/next?token=

**What time did the problem occur (including timezone)?**
I've noticed it yesterday. 

**What is the expected behavior?**
return the actual amount.

**What are the steps to reproduce**
send an api request with specfic symbols as described.

**Your environment (e.g. browser, OS, API version, language):**
tested with chrome and postman.

**Additional context**
example response:

[
    {
        "amount": 0,
        "currency": "",
        "declaredDate": "0000-00-00",
        "description": "Vanguard International High Dividend Yield ETF",
        "exDate": "2020-12-21",
        "flag": "",
        "frequency": "quarterly",
        "paymentDate": "2020-12-24",
        "recordDate": "2020-12-22",
        "refid": 2051444,
        "symbol": "VYMI",
        "id": "DIVIDENDS",
        "key": "VYMI",
        "subkey": "2051444",
        "date": 1608508800000,
        "updated": 1606190620000
    }
]

thanks in advance!

**Comment by McQgit** [comment]
@achitofel IEX shows scheduled dividends for ETFs before the amounts are known and published by the ETF sponsor.  This lets you know one is upcoming - even if you won't know the amount until closer to the ex-div date.  I, and others, complained about this when IEX first starting doing it but that's the way they prefer it.

You can search this git for further history of this (many months back).

As one example, VYMI does not yet show the distribution for Dec on their site (as the amount is not yet known):
https://investor.vanguard.com/etf/profile/distributions/vymi

**Comment by achitofel** [comment]
> 
> 
> @achitofel IEX shows scheduled dividends for ETFs before the amounts are known and published by the ETF sponsor. This lets you know one is upcoming - even if you won't know the amount until closer to the ex-div date. I, and others, complained about this when IEX first starting doing it but that's the way they prefer it.
> 
> You can search this git for further history of this (many months back).
> 
> As one example, VYMI does not yet show the distribution for Dec on their site (as the amount is not yet known):
> https://investor.vanguard.com/etf/profile/distributions/vymi

this is bad behavior as you provide with some of the fields with bogus data.
I would prefer getting no response at all, and wait for the dividend data to be ready in full, before providing me with half-baked data.
is this something considered to be fixed ?

**Comment by McQgit** [comment]
@achitofel Yes, as I said, IEX prefer it this way stating it provides info that some people like.  Namely, the dates for the next dividend.  Again, if you search this git you will find further background.

I found it is easy to exclude these from processing - I just programmatically ignore any ETF with an amount of zero.

**Comment by achitofel** [comment]
@McQgit but as you can see here: https://seekingalpha.com/symbol/BNDX/dividends/scorecard
BNDX already declared dividend to be paid at DEC 4, 2020.

the API on the other hand, gives this false data (amount is 0 and dates are wrong):

{
        "amount": 0,
        "currency": "",
        "declaredDate": "0000-00-00",
        "description": "Vanguard Total International Bond ETF",
        "exDate": "2020-12-23",
        "flag": "",
        "frequency": "monthly",
        "paymentDate": "2020-12-29",
        "recordDate": "2020-12-24",
        "refid": 2051380,
        "symbol": "BNDX",
        "id": "DIVIDENDS",
        "key": "BNDX",
        "subkey": "2051380",
        "date": 1608681600000,
        "updated": 1606190846000
    }

**Comment by McQgit** [comment]
@achitofel I don't see the problem with BNDX.  The BNDX paid Dec4 has passed.  The next one is the scheduled dividend as IEX show which the amount is not yet known.

**Comment by achitofel** [comment]
@McQgit so in that case, the call to https://cloud.iexapis.com/stable/stock/bndx/dividends/
should bring the last dividend payed right?
still gets an 0
{
        "amount": 0,
        "currency": "",
        "declaredDate": "0000-00-00",
        "description": "Vanguard Total International Bond ETF",
        "exDate": "2020-12-23",
        "flag": "",
        "frequency": "monthly",
        "paymentDate": "2020-12-29",
        "recordDate": "2020-12-24",
        "refid": 2051380,
        "symbol": "BNDX",
        "id": "DIVIDENDS",
        "key": "BNDX",
        "subkey": "2051380",
        "date": 1608681600000,
        "updated": 1606190846000
    }

if i add /1m i'm getting the actual value, but it won't work in any cases..so its a bit buggy
hence i was looking for a response from the dev team

**Comment by adamwozney-iex** [comment]
Hey @achitofel - We recently updated our [READme](https://github.com/iexg/IEX-API/blob/master/README.md) file and moved all support or bug related questions to another channel. Please reach out to support@iexcloud.io and our support team will follow-up with you there. It sounds like you may have already done so, but wanted to follow-up none the less. Sorry for any confusion.

Thanks.

**Comment by timpaine-iex** [comment]
The parameters of the call are given in the docs:
https://iexcloud.io/docs/api/#dividends-basic

With no argument the default is `next`. So the behavior here is correct. For more granular control over the data ranges you can use [timeseries](https://iexcloud.io/docs/api/#time-series) with the `id`: `DIVIDENDS` which should let you query for custom historical or forward date ranges.
