### ISSUE TITLE
[Data] Insider Transaction API missing data and only returning 4 months

### ISSUE THREAD

**Issue by olegnator** [iexg/IEX-API#1658]
**Clearly describe the data problem**
three issues with the API

1. returning data for 4 months only while advertised is 12 (from July to October inclusively)
2. Not returning any new data since 30-10-2020
3. Many transactions (inside the dates returned) are missing when compared to other sources

Regarding number 3, when comparing against this source - https://www.nasdaq.com/market-activity/stocks/tsla/insider-activity e.g. the below transaction is missing in IEX cloud api, and there are many more examples.

DENHOLM ROBYN M | Director | 10/26/2020 | Automatic Sell | Direct | 43,610 | $411.05 | 5,000

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/tsla/insider-transactions?token={myapitolken}

**What time did the problem occur (including timezone)?**

8 December 2020, 18:30 UTC

**What is the expected behavior?**
1. Returning 12 months of data as per documentation
2. Returning newest data
3. Returning all transactions that occured inside the timeframe

**What are the steps to reproduce**
Call the following API, the same issues are happening with other stocks, e.g. Apple, Moderna etc

https://cloud.iexapis.com/stable/stock/tsla/insider-transactions?token={myapitolken}

**Your environment (e.g. browser, OS, API version, language):**
Chrome Latest, Mac OS catalina
API version - stable

**Comment by adamwozney-iex** [comment]
Hey @olegnator - We recently updated our [READme](https://github.com/iexg/IEX-API/blob/master/README.md) file and moved all support or bug related questions to another channel. Please reach out to support@iexcloud.io and our support team will follow-up with you there. Sorry for any confusion.

Thanks.
