### ISSUE TITLE
List of stocks based on indicators, possible through API?

### ISSUE THREAD

**Issue by geeksified** [iexg/IEX-API#1661]
Hi. I'm new to stocks and I have a mini project to list all stocks based on indicators like Relative Volume over 10, Current Volume over 1 million, RSI overbought 60. Is it possible through IEXCloud API?

I wanted to copy finviz.com's indicators but with my own criteria of indicators only. Here's a sample:

![image](https://user-images.githubusercontent.com/45626394/101692713-8fb8be80-3aab-11eb-8eaf-7138bc12a332.png)

**Comment by timpaine-iex** [comment]
@geeksified would you mind detailing this a bit on https://iexcloud.io/console/roadmap

Seems like ideally this type of thing would be subsumed by the [rules engine](https://iexcloud.io/docs/api/#rules-engine-beta) which is still in beta, but feedback like this is helpful for future plans. As of right now I don't think we'd have support for all the possible filter criteria. 

Closing this issue for now as we'll track in the roadmap, but happy to continue the discussion as I think this is a good idea
