### ISSUE TITLE
[Data] Search query (ex. only for IEX available stock)

### ISSUE THREAD

**Issue by SoohanC** [iexg/IEX-API#1663]
Hi, 

I recently started using IEX Cloud api for my personal program.  

I made Search function with Autocomplete feature using "Search" endpoint. It works totally fine. But it looks like it also shows some unavailable and unknown stocks too.  I tried to get rid of those stocks after I received the data,  then it only shows 1~2 out of 10.

Do you have any query for this endpoint?  In my case I only want IEX available Stocks. If you don't, it will be great to have basic queries for this endpoint.

Thank you.

**Comment by adamwozney-iex** [comment]
Hey @SoohanC - Thanks for flagging. We recently updated our READme file and moved all support or bug related questions to another channel. Please reach out to support@iexcloud.io and our support team will follow-up with you there. Sorry for any confusion. 

Thanks,
