### ISSUE TITLE
[Data] Float is returning null in key_stats

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1666]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
 float is null in some key stats

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/batch?types=stats

**What time did the problem occur (including timezone)?**
noon dec 11 UTC

**What is the expected behavior?**
Returns a value. 

**What are the steps to reproduce**
run API

**Your environment (e.g. browser, OS, API version, language):**
windows

**Comment by dsrapaport** [comment]
Hi Jesse -

I looked in the API documentation which had the following information on the "Key Stats":

> Beginning December 1, 2020, the float and nextEarningsDate fields will no longer be available from the Key Stats endpoint. After December 1, 2020, you will be able to access nextEarningsDate from another endpoint – stay tuned for more information on this. Full details can be found in our Help Center.

So it looks like the float is not available from Key Stats (from 12/1/2020 going forward).

**Comment by timpaine-iex** [comment]
`float` is not available, we're looking to source this data but feel free to vote for it on the [roadmap](http://iexcloud.io/console/roadmap) if its very important to you
