### ISSUE TITLE
[Issue]: Historical prices API call when "chartCloseOnly=true" parameter is broken

### ISSUE THREAD

**Issue by dsrapaport** [iexg/IEX-API#1667]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**
The problem is when I do a "historical prices" API call with the "chartCloseOnly=true" parameter, as follows:

https://cloud.iexapis.com/stable/stock/AAPL/chart/1m?filter=date,close,volume&token=pk_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&chartLast=10&chartCloseOnly=true

(note: I have stripped my token value from it so you will have to replace it with yours):

When one submits a "historical prices" API call with the "chartCloseOnly=true" parameter, it yields extra fields in the output. These extra data in the results are the problem.

More specifically, if one uses the "chartCloseOnly=true" parameter, the resulting data should indicate only the adjusted data with the keys "date", "close", and "volume").

However, the issue when submitting the API call is that in addition to those fields date, close, and volume, it also yields data for the following fields:: 

(a) "changeOverTime"
(b) "marketChangeOverTime"
(c) "label":
(d) "change"
(e) "changePercent"

These fields should not be in the data returned as "chartCloseOnly=true"

So, the resulting data from the call (which has the extra/unwanted data):

[{"date":"2020-12-11","close":122.41,"volume":86939786,"changeOverTime":0,"marketChangeOverTime":0,"label":"Dec 11, 20","change":0,"changePercent":0},{"date":"2020-12-10","close":123.24,"volume":81312170,"changeOverTime":0.006780491789886434,"marketChangeOverTime":0.006780491789886434,"label":"Dec 10, 20","change":0.8299999999999983,"changePercent":0.0068},{"date":"2020-12-09","close":121.78,"volume":115089193,"changeOverTime":-0.0051466383465402785,"marketChangeOverTime":-0.0051466383465402785,"label":"Dec 9, 20","change":-1.4599999999999937,"changePercent":-0.0118},{"date":"2020-12-08","close":124.38,"volume":82225512,"changeOverTime":0.01609345641695939,"marketChangeOverTime":0.01609345641695939,"label":"Dec 8, 20","change":2.5999999999999943,"changePercent":0.0213},{"date":"2020-12-07","close":123.75,"volume":86711990,"changeOverTime":0.010946818070419112,"marketChangeOverTime":0.010946818070419112,"label":"Dec 7, 20","change":-0.6299999999999955,"changePercent":-0.0051},{"date":"2020-12-04","close":122.25,"volume":78260421,"changeOverTime":-0.0013070827546768776,"marketChangeOverTime":-0.0013070827546768776,"label":"Dec 4, 20","change":-1.5,"changePercent":-0.0121},{"date":"2020-12-03","close":122.94,"volume":78967630,"changeOverTime":0.004329711624867259,"marketChangeOverTime":0.004329711624867259,"label":"Dec 3, 20","change":0.6899999999999977,"changePercent":0.0056},{"date":"2020-12-02","close":123.08,"volume":89004195,"changeOverTime":0.005473409035209556,"marketChangeOverTime":0.005473409035209556,"label":"Dec 2, 20","change":0.14000000000000057,"changePercent":0.0011},{"date":"2020-12-01","close":122.72,"volume":128166803,"changeOverTime":0.002532472837186523,"marketChangeOverTime":0.002532472837186523,"label":"Dec 1, 20","change":-0.35999999999999943,"changePercent":-0.0029},{"date":"2020-11-30","close":119.05,"volume":169410176,"changeOverTime":-0.027448737848215013,"marketChangeOverTime":-0.027448737848215013,"label":"Nov 30, 20","change":-3.6700000000000017,"changePercent":-0.0299}]

**What time did the problem occur? (with timezone)**
12/12/2020 2pm PST

**What is the expected behavior?**

The call should have yielded a data series with only the "date", "close" and "volume" fields because I used the parameter "chartCloseOnly=true" in the call.

In other words, the call should have yielded the following results:
[{“date”:”2020-12-11","close":122.41,"volume":86939786},{“date”:”2020-12-10","close":123.24,"volume":81312170},{“date”:”2020-12-09","close":121.78,"volume":115089193},{“date”:”2020-12-08","close":124.38,"volume":82225512},{“date”:”2020-12-07","close":123.75,"volume":86711990},{“date”:”2020-12-04","close":122.25,"volume":78260421},{“date”:”2020-12-03","close":122.94,"volume":78967630},{“date”:”2020-12-02","close":123.08,"volume":89004195},{“date”:”2020-12-01","close":122.72,"volume":128166803},{“date”:”2020-11-30","close":119.05,"volume":169410176}]

**Your environment (e.g. browser, OS, API version, language):**
Win 10
I use " https://cloud.iexapis.com/stable" API

**API URL (if applicable)**
I submitted the following "historical prices" API call (note: I have stripped my token value from it so you will have to replace it with yours):

   https://cloud.iexapis.com/stable/stock/AAPL/chart/1m?filter=date,close,volume&token=pk_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&chartLast=10&chartCloseOnly=true

**What are the steps to reproduce the bug?**

1. put the url "https://cloud.iexapis.com/stable/stock/AAPL/chart/1m?filter=date,close,volume&token=pk_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&chartLast=10&chartCloseOnly=true" (using your own key) in the browser.

2. The data returned shows the extra fields which is the bug.

**Additional context**

The specific issue is that the IEX "historical prices" API call is not respecting the "chartCloseOnly=true" parameter (which should yield only the adjusted data with the keys "date", "close", and "volume").  Instead it yields those fields and the others noted above.  This is impairing my code from running, and would require me to make a number of code changes to fix (which takes a large amount of time).

I hope you can help me with this so it returns to the normal behavior as specified in the API documentation (which would mean I wouldn't have to recode my code, which would be very nice).

Thank you.

**Comment by adamwozney-iex** [comment]
Hey @dsrapaport - Thanks for flagging. We recently updated our READme file and moved all support or bug related questions to another channel. Please reach out to support@iexcloud.io and our support team will follow-up with you there. Sorry for any confusion. 

Thanks.

**Comment by dsrapaport** [comment]
Hi @adamwozney-iex ,

Thank you for your message.  I submitted an email to support@iexcloud.io a couple of days ago, following the guidelines for submission from the IEX site.  

I am hoping that they can address this issue as soon as feasibly possible, as the problem is making behavior of the API not follow what is articulated in the API documentation.  Anyone who uses this API call with the chartCloseOnly parameter is impacted by the issue.

(It is also breaking my code, making it not run - so I am hoping they can fix it. :P

Thank you for your help!
@dsrapaport

**Comment by wolgast** [comment]
Hey, I can add that the “chartInterval” parameter isn’t working either...

**Comment by stammy** [comment]
I can confirm that chartInterval param is not working on my end either

**Comment by adamwozney-iex** [comment]
Hey @wolgast , @stammy and @dsrapaport - Thanks for letting me know.

If you could do me a favor and email support@iexcloud.io with a link to this github issue URL and the email account associated with your IEX cloud account, we can monitor, track and respond to your request. 

We're slowly transitioning support requests off of Github and onto a new platform, so sorry for any delays in response.

**Comment by dsrapaport** [comment]
I already submitted this issue to support@iexcloud.io last Saturday.  I received a response yesterday that they are looking at it.  I did not feel confident from the response that it was urgent and would be fixed anytime soon, so I decided that I will need to make changes to my own code - which will take me quite a number of hours to do and to test.  Not really happy about that, but I cannot wait for days on end for someone to address this.  I have also discovered that the same issue exists with the OHLC data from IEX, but I have not reported it to the support email bc I don't think anyone will address it with urgency.

**Comment by timpaine-iex** [comment]
@dsrapaport sorry for the difficulties you're experiencing, please do report continue to report issues as many priorities are driven by how many people are experiencing the specific problem. As far as timeline is concerned, we look into issues as soon as we are able, and grow and scale tiers have access to chat/priority support.
