### ISSUE TITLE
[Data]An error occurred while making the query (402): You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access

### ISSUE THREAD

**Issue by Pratikkapadia7** [iexg/IEX-API#1669]
I have been trying fetching data through API from IEX cloud and it worked fine for 2-3 times but then this message started bugging me!

Anyone who can please give me a solution regarding this query.

Thank You

**Comment by timpaine-iex** [comment]
@Pratikkapadia7 take a look at https://iexcloud.io/docs/api/#how-messages-work and the current usage (you can find this in the [console](https://iexcloud.io/console/)), feel free to ping me if you have further questions
