### ISSUE TITLE
Websocket data gives zero filled object

### ISSUE THREAD

**Issue by Cartman720** [iexg/IEX-API#167]
## Summary

There are some stocks, for example `AAAP`, which all data object properties are filled with `0` and `lastUpdated` property is `-1`, I just want to know is this bug?

### Date/time of issue
2018-01-08

### What you expected to happen
I expected to get stock price or nothing if there is no any trade done.

### Other Information (sample code, links, etc.)

Here is my code 

```
iex.on('message', message => {
	let { symbol, lastSalePrice, lastSaleSize, lastSaleTime, lastUpdated } = JSON.parse(message);

	io.emit(symbol, {
		price: lastSalePrice,
		size: lastSaleSize,
		timestamp: lastSaleTime
	});
});
```

**Comment by joshuablackburn-iex** [comment]
In version 1.0 this is expected behavior for stocks IEX has not traded in the current trading day.

**Comment by DavidTrx** [comment]
Are you using a later version than 1.0? Does the 1.0 in the URL imply that I am no longer attempting to use the latest version… might that be the source of the problem?

— 
David
