### ISSUE TITLE
How to have a specific stock price  

### ISSUE THREAD

**Issue by alemattjent** [iexg/IEX-API#1670]
Is there any way to get the price of a stock on a specific date at a specific time (to the minute) without having to download a long list of data?

**Comment by timpaine-iex** [comment]
historical intraday only lets you request a full day of minute data (docs [here](https://iexcloud.io/docs/api/#historical-prices)). But this seems like a reasonable enhancement so if you could submit it on the [unofficial roadmap](https://iexcloud.io/console/roadmap) we can evaluate it against the current book of work
