### ISSUE TITLE
exactDate query string parameter breaking my query

### ISSUE THREAD

**Issue by jlheidecker** [iexg/IEX-API#1671]
I used to pull chart data with this request:

https://cloud.iexapis.com/stable/stock/market/batch?types=chart&range=1d&chartByDay=true&exactDate=20201007&symbols=AAPL,AMD&token=XXX

At some point over the last few months that stopped working. The return object has no chart data at all. Just empty object. By removing the "exactDate" parameter from the request string, I can get a valid response with chart data, but of course it's not for the right date anymore:

https://cloud.iexapis.com/stable/stock/market/batch?types=chart&range=1d&chartByDay=true&symbols=AAPL,AMD&token=XXX

Anyone know what has changed recently to break this? How do I get 1-day chart data for a specific date now?

**Comment by BlairCurrey** [comment]
@jlheidecker does https://cloud.iexapis.com/stable/stock/AAPL/chart/date/20070604?chartByDay=true&token=XXX give you what you're after? Unfortunately it's not batched, but it is chart data for a specific date. I'm assuming you meant '1d' and not '1m' in your last sentence, otherwise what I said definitely won't help.

**Comment by jlheidecker** [comment]
@BlairCurrey You're right, I wasn't trying to get 1m data here. I updated my original comment to fix the typo.

I've been working this with IEX Cloud support and this morning they informed me that my query will work if I remove the "range" parameter. I confirm that this works and returns the expected data. 

https://cloud.iexapis.com/stable/stock/market/batch?types=chart&chartByDay=true&exactDate=20201007&symbols=AAPL,AMD&token=xxx

**Comment by BlairCurrey** [comment]
Nice to hear. Thanks for sharing.
