### ISSUE TITLE
[Issue] US Trading Dates ends Jan 5th, 2021

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1672]
**Date/time of the issue**
2019-Present

**What you did**
I tried to use the US Holidays and Trading Dates API endpoint.

**What you expected to happen**
The API docs state the endpoint will provide trading dates “Back to 2017 to forward 2 years.” I would expect such an endpoint would be updated periodically to try to provide trading dates up to the furthest option expiry date, currently 2023-01-20 for equities or 2023-12-15 for indices.

**What actually happened**
The API only provides future trading dates until next Tuesday, Jan 5th, 2021. I reported this to support months ago, but nothing has changed. The endpoint has not been updated in over a year.

**API Url (if applicable)**
https://cloud.iexapis.com/stable/ref-data/us/dates/trade/next/5/20210101?token=

**Comment by evancarter-iex** [comment]
This should be fixed.
