### ISSUE TITLE
[Issue] Can't retrieve data for OTC ticker GBTC

### ISSUE THREAD

**Issue by timpaine-iex** [iexg/IEX-API#1673]
moving from https://github.com/iexg/IEX-API/issues/1537

**Comment by timpaine-iex** [comment]
https://github.com/iexg/IEX-API/issues/1537#issuecomment-750797669

**Comment by timpaine-iex** [comment]
https://github.com/iexg/IEX-API/issues/1537#issuecomment-751754249

**Comment by timpaine-iex** [comment]
<img width="1421" alt="Screen Shot 2020-12-28 at 10 30 20 AM" src="https://user-images.githubusercontent.com/74613173/103225343-b1150980-48f7-11eb-8a97-d394942ccc23.png">

**Comment by timpaine-iex** [comment]
@humenick are you able to fetch data via e.g. `chart` for GBTC? there are two somewhat unrelated issues here, one is batch failing if any sub-request fails, the second is you not being able to access data for GBTC

**Comment by kewur** [comment]
cross posting to this issue as well.

--

This is a blocker for me as well. I am batching 100 symbols together and failing on a single one. I can "batch" requests by 1, effectively not having this issue anymore, but I don't believe it would be beneficial for anyone to ddos IEX cloud with single symbol lookups. I have several symbols I'm failing on but as an example "COMS" symbol is failing for me.  The "chart" endpoint does not fail for me.

Perhaps we can return a "206 partial content"  with a field of errors in the batch response that could potentially look like this?

`
{
   "AAPL": {
      "intraday-prices": [ //data
      ],
   "errors": [
     "intraday-prices": [
          "GBTC": {
             "errorMessage": "451 Legal reasons"
          }
      ]
   ]
}`

This would also allow me to get the data through some other legal means for that symbol by falling back to an endpoint such as "chart".

**Comment by timpaine-iex** [comment]
@kewur hiding so we can keep these threads separate

**Comment by evancarter-iex** [comment]
Closing as stale
