### ISSUE TITLE
[Request] Ability to limit range to minutes/hours for pulling realtime indicator data without exponential API usage

### ISSUE THREAD

**Issue by Admin-NWIF** [iexg/IEX-API#1674]
Is it possible to request an indicator (such as bbands or rsi) with a range like (5minutes) or (realtime) to go and get only the most recent bbands data or rsi data? Of course these indicators need some historical data to be computed, and that could be defined through their existing default period/stddev parameters, but as it currently stands the smallest range of time you can request data for is 1d, which results in an insane number of API calls if you need the data in 1 minute intervals. Its something like 20,000 API calls for one BBANDS query with a range of 1d, period of 20, and stddev of 2. Any ideas or suggestions on if there is a way to already do this?

**Comment by timkpaine** [comment]
@Admin-NWIF this seems like a fine idea on the surface, but difficult to implement for arbitrary parameters and timeframes. 

You could collect `quote` repeatedly and calculate the technicals yourself (e.g. via TA-lib). This is also very economical since `quote` is only `1` message

**Comment by Admin-NWIF** [comment]
> @Admin-NWIF this seems like a fine idea on the surface, but difficult to implement for arbitrary parameters and timeframes.
> 
> You could collect `quote` repeatedly and calculate the technicals yourself (e.g. via TA-lib). This is also very economical since `quote` is only `1` message

Yea thats true, I could definitely do the calculations myself, it sort of defeats the purpose of paying a premium just to get a stock quote though. But it looks like it's what I'll have to do for now.

An interesting workaround that is documented under historical data, but not technicals in the API docs, is that you can provide "chartLast" as a query parameter for any technical indicator and set it equal to the period (or period +1) for your indicator. That gave me the latest bbands and rsi at 50 messages used per query which is much more manageable than 20,000.

**Comment by timkpaine** [comment]
@Admin-NWIF technicals accept all chart params (its in the docs for technicals), and `chartLast` is similar to e.g. `last` for the generic `time-series` endpoints. 

<img width="629" alt="Screen Shot 2021-01-01 at 12 10 15 AM" src="https://user-images.githubusercontent.com/3105306/103433806-bad39100-4bc5-11eb-853d-64d759747ceb.png">

`50` per message isn't too bad, you can still slim it down with the `quote` strategy which i'll probably end up implementing for `pyEX` anyway since I already support client side indicators.

**Comment by Admin-NWIF** [comment]
@timkpaine Hey, I'm going to close this thread as I think its resolved, but I had a quick unrelated question and was curious if you had any thoughts/an opinion on it. 

Question: Is there any concern with data accuracy with using IEX data for TA? I noticed it often differs by some cents from the consolidated tape, obviously because the realtime data is coming from the Investor's Exchange and consolidated tape is 15 mins delayed. Curious if you've ever heard of this throwing off TA/Trades dramatically or if there were any real concerns around this?
