### ISSUE TITLE
/quote not working for Nordic/Scandinavian exchanges

### ISSUE THREAD

**Issue by christiankm** [iexg/IEX-API#1675]
Hi there! You recently added support for the Scandinavian exchanges like Copenhagen, Stockholm and Oslo. Thank you for that! Unfortunately it looks like the /quote endpoint is not working correctly - it will either return 404, or will find the symbol but return an empty data entity. Please have a look at this ASAP. Without this, your added support is not fully beneficial.
For example for Danske Bank I get a 404 response:

```
<NSHTTPURLResponse: 0x6030001e92b0> { URL: https://cloud.iexapis.com/stable/stock/DANSKE-DC/quote?displayPercent=true&token=xxxxxxxxxxxxx} { Status Code: 404, Headers {
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    "Content-Encoding" =     (
        gzip
    );
    "Content-Type" =     (
        "text/html; charset=utf-8"
    );
    Date =     (
        "Tue, 29 Dec 2020 15:35:29 GMT"
    );
    Server =     (
        nginx
    );
    "Strict-Transport-Security" =     (
        "max-age=15768000"
    );
    "access-control-allow-credentials" =     (
        true
    );
    "access-control-allow-headers" =     (
        "Origin, X-Requested-With, Content-Type, Accept, Request-Source"
    );
    "access-control-allow-methods" =     (
        "GET, OPTIONS"
    );
} }
```

__Originally posted by @christiankm in https://github.com/iexg/IEX-API/issues/1484#issuecomment-752125732__

**Comment by met68** [comment]
OP seconded.

Am trying to retrieve stock quotes for Finland (e.g. NOKIA-FH or WRT1-FH), but it doesn't work, despite showing as available on the international by regions API for Finland.

Have also submitted an e-mail to IEX support a few days ago, but not heard back.

This is kind of urgent for me and if we can't have Nordics, I will have to cancel my current subscription and look elsewhere.

**Comment by christiankm** [comment]
@evancarter-iex Given that you replied and said you would look into this problem from my previous issue #1484 , is there ANY news on this? It's quite critical to be able to do this.
Being able to search for these stocks and add them to a list is great, and works excellent. But it's honestly quite pointless if we cannot fetch even the current price.
Hope to hear from the team very soon. Please.

**Comment by evancarter-iex** [comment]
@christiankm I am seeing /quote working on stocks like NOKIA-FH, EQNR-NO, DANSKE-DC are you not seeing similar?

**Comment by met68** [comment]
I think I am going to be looking for an alternative. I am a paying customer, but lots of things not working.

I still don't get quotes for say wrt1v-fh or nokia-fh.

Also quotes for US Treasuries and WTI oil are not updated. And I can't get any quotes for gold or silver. Neither spot nor futures. All European stocks are daily closing prices only. So overall, this is pretty much useless to me.

**Comment by met68** [comment]
P.S. And obviously support from IEX Cloud either here or by e-mail is non-existent. Not helpful.

**Comment by timpaine-iex** [comment]
@christiankm we've identified the problem, should be rectified shortly and we'll respond and close this ticket when its ready.

**Comment by christiankm** [comment]
> @christiankm I am seeing /quote working on stocks like NOKIA-FH, EQNR-NO, DANSKE-DC are you not seeing similar?

I'll admit it has been a few weeks since I last checked, but no, some of these return 404 for me when using /quote, and I never get any response if I include them in a /batch request.

2021-03-04 20:02:50.498483+0100 Stokki Debug[5296:169610] [Networking] 🌏 ❌ Request did not return OK: https://cloud.iexapis.com/**stable/stock/DANSKE-DC/quote**?displayPercent=true&token=pk_xxxxx
<NSHTTPURLResponse: 0x6030001f3c30> { URL: https://cloud.iexapis.com/stable/stock/DANSKE-DC/quote?displayPercent=true&token=pk_xxxxx } { Status Code: 404, Headers {
2021-03-04 20:04:58.437888+0100 Stokki Debug[5296:170726] [Networking] 🌏 ❌ Request did not return OK: https://cloud.iexapis.com/**stable/stock/NOKIA-FH/quote**?displayPercent=true&token=pk_xxxxx
<NSHTTPURLResponse: 0x6030001b0ca0> { URL: https://cloud.iexapis.com/stable/stock/NOKIA-FH/quote?displayPercent=true&token=pk_xxxx } { Status Code: 404, Headers

**Comment by christiankm** [comment]
> @christiankm we've identified the problem, should be rectified shortly and we'll respond and close this ticket when its ready.

Working fast while I'm giving feedback. I like that! Can't wait to retry very soon :)

**Comment by evancarter-iex** [comment]
@christiankm /quote should be working now for those exchanges

**Comment by met68** [comment]
Appreciate the fix, thanks!

Am also trying to get quotes for maersk a-dc and maersk b-dc, but doesn't work because of the spaces. Tried without the space, but that doesn't work.

Can you please fix this too? Thanks.

**Comment by christiankm** [comment]
Thank you! I will do thorough testing tonight, but it’s seems to work on my end.

Christian

**Comment by evancarter-iex** [comment]
@met68 Try https://cloud.iexapis.com/stable/stock/MAERSK%20A-DC/quote?token= That should work. I am going to close this as resolved.

**Comment by timpaine-iex** [comment]
more examples of how to quote symbols:
https://github.com/iexcloud/pyEX/blob/main/pyEX/common/checks.py#L494
https://github.com/iexcloud/iexjs/blob/main/src/js/common/checks.js#L465

**Comment by met68** [comment]
While https://cloud.iexapis.com/stable/stock/MAERSK%20A-DC/quote?token= seems to work in browser, JS Fetch batch requests as per: https://cloud.iexapis.com/stable/stock/market/batch?symbols=maersk%20b-dc,...&token=...still don't work.

Please re-open this issue and fix asap. Thanks.

**Comment by christiankm** [comment]
I Think it would be more beneficial to create that as a new issue. It might not be an issue just for Nordic stocks.

Christian
