### ISSUE TITLE
[Data] Don't scramble Advanced Fundamentals FilingType field in Sandbox

### ISSUE THREAD

**Issue by amittleider** [iexg/IEX-API#1676]
**Email account associated with your IEX Account**
amittleider@gmail.com

**Date/time of the issue**
Jan 3, 5:50pm CET

**What you did**
Call AdvancedFundamentals in the Sandbox

**What you expected to happen**
The FIlingType field to be "10-K"

**What actually happened**
The FilingType field is scrambled, and appears as "K01-" or "01K-", etc.

**Additional relevant information**
It's nice to keep this field unscrambled so that we can test requesting only certain types of reports, depending on the data that we already have (for example, query in SQL by most recent 10-K, then request the latest reports).

**Comment by timpaine-iex** [comment]
@amittleider yeah I agree this one can be unscrambled

**Comment by amittleider** [comment]
Could also be useful to unscramble "subkey". That value also comes from the
request (annual, quarter).

**Comment by timpaine-iex** [comment]
This will be deployed today, I will close the issue when it is available
