### ISSUE TITLE
After successfully getting block feed for several days, now response is {}

### ISSUE THREAD

**Issue by DavidTrx** [iexg/IEX-API#168]
## Summary
A new perl program was brought online last week and was successfully getting feed from IEX. Now the response is {}

## Details

See summary

### Date/time of issue

8Jan2018, 9:30AM and ongoing

### API URL
"https://api.iextrading.com/1.0/stock/market/batch?symbols=$stock&types=quote,news,chart&range=1m&last=5"

### What you expected to happen

Expect to get real-time data feed

### What actually happened

Only getting {}

**Comment by evancarter-iex** [comment]
If I insert a stock symbols into the url given above, it works fine for me:

https://api.iextrading.com/1.0/stock/market/batch?symbols=ge,aapl&types=quote,news,chart&range=1m&last=5

**Comment by DavidTrx** [comment]
That’s why I’m puzzled. It worked fine for me also last Thursday and Friday. Now, all of a sudden, without any code change, $content = $response->content(); gives me {}

Have I inadvertently violated some guideline?

— 
David

**Comment by evancarter-iex** [comment]
What does your DNS resolve to?

**Comment by DavidTrx** [comment]
My DNS server address is 75.75.75.75 and 75.75.76.76 (hsd1.md.comcast.net <http://hsd1.md.comcast.net/>)

Is that what you are asking for?

**Comment by evancarter-iex** [comment]
I meant what does api.iextrading.com resolve to for you?

**Comment by DavidTrx** [comment]
I’m getting ‘Not Found’

Aha!

**Comment by DavidTrx** [comment]
… and when I ping ping api.iextrading.com <http://api.iextrading.com/>, I get 100% packet loss

**Comment by evancarter-iex** [comment]
There appears to be a problem with your DNS, you will need to investigate that. 

You should not be able to ping us.

**Comment by DavidTrx** [comment]
When I use Firefox or Google Chrome, I am clearly reaching the site, and downloading files, in the one case ‘download’ and in the other ‘oINeNA1n.dms’ and kRIPfuc.J.dms

— 
David
