### ISSUE TITLE
[Data] the symbols api is missing stock types

### ISSUE THREAD

**Issue by jkotchoff** [iexg/IEX-API#1680]
There are currently 255 entries in the [symbols feed](https://iexcloud.io/docs/api/#international-symbols) that have a null `type` field.

For example: 
```
  {
    "symbol": "EPD",
    "exchange": "NYS",
    "exchangeSuffix": "UN",
    "exchangeName": "NEW YORK STOCK EXCHANGE, INC.",
    "name": "Enterprise Products Partners L P - Unit",
    "date": "2021-01-08",
    "type": null,
    "iexId": "IEX_4652595846562D52",
    "region": "US",
    "currency": "USD",
    "isEnabled": true,
    "figi": "BBG000BR3012",
    "cik": "0001061219",
    "lei": "K4CDIF4M54DJZ6TB4Q48"
  },
```

We are filtering our ingestion of symbols data to particular security types (ie. cs/Common Stock, ad/ADR & et/ETF) and expected the above listing to be categorised with a type so we can aggregate it.

Would it be possible for the IEX to enforce a not-null constraint on the `type` field for symbols?

**Comment by timpaine-iex** [comment]
@jkotchoff thanks for posting, we're aware and are looking for a good, forward facing solution as we look to expand our instrument universe
