### ISSUE TITLE
Earnings API throws an error even with a valid token 

### ISSUE THREAD

**Issue by jkgituser** [iexg/IEX-API#1681]
Running an earnings API call like below throws an error 
          **https://cloud.iexapis.com/stable/stock/aapl/earnings?token=<APIKEY>**

Error - **The requested data requires permission to access.**
The Quotes API does not give an error

**Comment by timpaine-iex** [comment]
Please see the docs https://intercom.help/iexcloud/en/articles/4529082-iex-cloud-s-2020-data-upgrade
