### ISSUE TITLE
widespread wrong prices [Data]

### ISSUE THREAD

**Issue by sqaxomonophonen** [iexg/IEX-API#1682]
The `stock/$symbol/quote` endpoint returns "random" prices for most fields. `latestPrice` seems fine, but e.g. `delayedPrice` (which is important to us) seems to be quite random.

Example:
```
$ curl -s 'https://cloud.iexapis.com/v1/stock/aapl/quote?token=XXXXX' | python -mjson.tool
{
    ...
    "delayedPrice": 9.8,
    ...
}
```

Running the `curl` immediately again yields another "random price":
```
"delayedPrice": 22.68,
```

And again:
```
"delayedPrice": 1.71,
```

(Our account login is `aktiedysten@aktiedysten.dk`)

**Comment by sqaxomonophonen** [comment]
Note: this is a problem for *all* US symbols as far as I can tell.

**Comment by sqaxomonophonen** [comment]
Seems unrelated to #1679 seeing that our prices for Friday (2021-01-08) and back were fine. (Also there's quite a difference in how wrong the prices are in that bug vs this; a little wrong vs totally wrong, respectively)

**Comment by markcorwin-iex** [comment]
We are aware of the issue and actively fixing it.

**Comment by markcorwin-iex** [comment]
The primary problem has been fixed. We will continue to monitor and address any lingering data issues.

**Comment by mmjdotdk** [comment]
Are your historical data correct?
