### ISSUE TITLE
latestPrice and latestVolume is off on hundreds of issues

### ISSUE THREAD

**Issue by TradingLicks** [iexg/IEX-API#1683]
Below is an example of what should be today's top volume stocks by price and this is obviously not the case. Also it looks like the high on many issues is the same wrong number (3152.31 or 853.23 etc.).

{"AHC":{"quote":{"latestVolume":1805570,"changePercent":52.63393,"close":1.68,"avgTotalVolume":76622,"latestPrice":90.105,"high":3152.31,"low":0.65}},"JP":{"quote":{"latestVolume":22005731,"changePercent":440.51832,"close":1.91,"avgTotalVolume":76443,"latestPrice":843.3,"high":854.43,"low":0.64}},"MIN":{"quote":{"latestVolume":7584634,"changePercent":11.16578,"close":3.77,"avgTotalVolume":384321,"latestPrice":45.865,"high":853.23,"low":0.548}},"IRR":{"quote":{"latestVolume":9571522,"changePercent":92.3777,"close":2.78,"avgTotalVolume":153506,"latestPrice":259.59,"high":854.43,"low":0.714}},"JTA":{"quote":{"latestVolume":25744180,"changePercent":0.61202,"close":9.73,"avgTotalVolume":80638,"latestPrice":15.685,"high":853.23,"low":5.06}},"BKT":{"quote":{"latestVolume":335642,"changePercent":0.74092,"close":6.06,"avgTotalVolume":321262,"latestPrice":10.55,"high":853.23,"low":0.4551}},"CMSA":{"quote":{"latestVolume":17219424,"changePercent":30.07,"close":27,"avgTotalVolume":12742,"latestPrice":838.89,"high":853.23,"low":0.633}},"RCP":{"quote":{"latestVolume":123725997,"changePercent":11.22945,"close":25.36,"avgTotalVolume":14806,"latestPrice":310.14,"high":310.19,"low":9.07}},"TEO":{"quote":{"latestVolume":9349902,"changePercent":-0.01807,"close":6.64,"avgTotalVolume":481505,"latestPrice":6.52,"high":854.43,"low":0.4551}},"IRL":{"quote":{"latestVolume":25093136,"changePercent":-0.18967,"close":11.304,"avgTotalVolume":15422,"latestPrice":9.16,"high":379.89,"low":0.714}},"HPF":{"quote":{"latestVolume":4394519,"changePercent":-0.08623,"close":18.67,"avgTotalVolume":105466,"latestPrice":17.06,"high":3152.31,"low":0.4501}},"PCK":{"quote":{"latestVolume":721793,"changePercent":-0.0011,"close":9.05,"avgTotalVolume":70316,"latestPrice":9.04,"high":853.23,"low":1.04}},"GMTA":{"quote":{"latestVolume":11129943,"changePercent":30.97769,"close":26,"avgTotalVolume":7917,"latestPrice":831.42,"high":853.23,"low":10.26}},"PCQ":{"quote":{"latestVolume":19440154,"changePercent":27.91823,"close":18.1,"avgTotalVolume":19482,"latestPrice":523.42,"high":3152.31,"low":8.12}},"MBI":{"quote":{"latestVolume":110944357,"changePercent":0.01493,"close":7.37,"avgTotalVolume":520663,"latestPrice":7.48,"high":3152.31,"low":0.714}}}

**Comment by TradingLicks** [comment]
Here are some more examples:

{"AENZ":{"quote":{"latestVolume":13609343,"latestPrice":379.64,"high":379.64,"low":379.64}},"AIZP":{"quote":{"latestVolume":1864,"latestPrice":130.46,"high":840.3,"low":130.46}},"GJP":{"quote":{"latestVolume":40248782,"latestPrice":66.28,"high":66.28,"low":66.28}},"PCQ":{"quote":{"latestVolume":4193,"latestPrice":18.19,"high":523.42,"low":18.09}},"NCA":{"quote":{"latestVolume":7782976,"latestPrice":79.61,"high":79.61,"low":79.61}},"NMS":{"quote":{"latestVolume":14908587,"latestPrice":68.69,"high":68.69,"low":68.69}},"PMVC":{"quote":{"latestVolume":5524277,"latestPrice":65.49,"high":65.49,"low":65.49}},"BSA":{"quote":{"latestVolume":4796,"latestPrice":25.121,"high":118.465,"low":25}},"GJS":{"quote":{"latestVolume":977008,"latestPrice":108.64,"high":108.64,"low":108.64}},"BZM":{"quote":{"latestVolume":371039184,"latestPrice":0.8269,"high":0.8269,"low":0.8269}},"GF":{"quote":{"latestVolume":937125,"latestPrice":84,"high":84,"low":84}},"AIC":{"quote":{"latestVolume":281445607,"latestPrice":0.924,"high":0.924,"low":0.924}},"EMPW":{"quote":{"latestVolume":88580294,"latestPrice":2.91,"high":2.91,"low":2.91}}}

**Comment by humenick** [comment]
Seriously, WHAT THE FUCK IEX!!!?!?!?!?!?

**Comment by humenick** [comment]
![Screen Shot 2021-01-11 at 14 08 22](https://user-images.githubusercontent.com/1775830/104226984-ac337800-5416-11eb-9a74-c305bd708bbf.png)

**Comment by markcorwin-iex** [comment]
We had an issue with our real-time and delayed price feeds this morning from market open until around 11:30 am E.T. The primary issue has been resolved. We will continue to monitor and address any lingering data issues.

**Comment by TradingLicks** [comment]
Yes it does appear that SPY is erratic today as well. In the 7000 names I monitor, it does look like most are fixed but I'm still noticing price and volume way off (or null) on a few names:

{"GJP":{"quote":{"latestVolume":40248782,"latestPrice":66.28,"high":66.28,"low":66.28}},"TSLA":{"quote":{"latestVolume":42057216,"latestPrice":825.34,"high":null,"low":null}},"GJS":{"quote":{"latestVolume":977008,"latestPrice":108.64,"high":108.64,"low":108.64}},"NMS":{"quote":{"latestVolume":1220117,"latestPrice":68.69,"high":68.69,"low":68.69}},"NVDA":{"quote":{"latestVolume":9507657,"latestPrice":553.84,"high":null,"low":null}},"BIDU":{"quote":{"latestVolume":13627995,"latestPrice":223.96,"high":null,"low":null}},"LMFA":{"quote":{"latestVolume":189520965,"latestPrice":2.86,"high":null,"low":null}},"GOVX":{"quote":{"latestVolume":46349741,"latestPrice":5.62,"high":null,"low":null}},"AAPL":{"quote":{"latestVolume":65012105,"latestPrice":129.225,"high":null,"low":null}},"CHU":{"quote":{"latestVolume":215370,"latestPrice":73.04,"high":73.04,"low":73.04}},"RIDE":{"quote":{"latestVolume":26428821,"latestPrice":27.365,"high":null,"low":null}}}

**Comment by TradingLicks** [comment]
There appears to still be 200-300 nasdaq issues with incorrect volume that are showing a zero changePercent. Only the top dollar names show on my scan, but there is unusually high volume in the nasdaq unchanged category.

{"GJS":{"quote":{"changePercent":0,"latestVolume":1621,"latestPrice":20.71,"high":108.64,"low":20.71}},"CHU":{"quote":{"changePercent":0,"latestVolume":215370,"latestPrice":6.03,"high":73.04,"low":6.03}}}

**Comment by TradingLicks** [comment]
Found another one. Today's Nasdaq total volume for 3900 issues is off by a billion shares so there are probably more...

{"NSEC":{"quote":{"changePercent":32.1451,"latestVolume":9507649,"latestPrice":379.18,"high":379.18,"low":379.18}}}

**Comment by evancarter-iex** [comment]
This is resolved.
