### ISSUE TITLE
Unable to Use api getting error messages

### ISSUE THREAD

**Issue by harry4886** [iexg/IEX-API#1684]
Api Response :   The requested data requires permission to access.

sent mail to support team. no response yet.

**Comment by timpaine-iex** [comment]
We see the email in our support queue, they will get back to you as soon they can. thanks for reaching out!

**Comment by harry4886** [comment]
This issue is super urgent for us as it's impacting our users. and also the turn around time is getting too costly for us.
can you please help to expedite this and get us away for a quick resolution?

**Comment by joshuablackburn-iex** [comment]
What endpoint are you attempting to access?

**Comment by harry4886** [comment]
the endpoint we are trying to access
is URL  :

*API URL*:
https://cloud.iexapis.com/stable/stock/AAPL/earnings/1/?token=pk_95281ac1aa434e98b44773dXXXXXX
(Token is encrypted)



*API Response*:  *The requested data requires permission to access*.

**Comment by joshuablackburn-iex** [comment]
We sent many communications last year related to our data migration including changes to our earnings data. You can read the original note here:

https://intercom.help/iexcloud/en/articles/4529082-iex-cloud-s-2020-data-upgrade

**Comment by joshuablackburn-iex** [comment]
Have you already requested access through the console?

**Comment by harry4886** [comment]
No We haven't, we have our backend admin team working on it. we want that
process to be expedited

**Comment by harry4886** [comment]
Just got the update from the Business team that the API is blocked because
your system considered as a reseller.
we have no clients and we are in research and development mode.

So would request you to kindly look into this as we have a prime demo
scheduled shortly.

Please get a workaround for this at the earliest.

Thanks
Harrish
