### ISSUE TITLE
[Data] Missing symbols

### ISSUE THREAD

**Issue by gpoontip** [iexg/IEX-API#1686]
**Date/time of the issue**: 17-01-2021
**What you did**: Searched for the following symbols through the API and could not find although they all exist here https://iextrading.com/trading/eligible-symbols/: 
- IPOF
- LGVW
- BFT
- ACIC

**What you expected to happen**: Be able to find symbols through the search endpoint 
**What actually happened**: Symbol not found
**Additional relevant information**: All Class A shares listed on the NYSE
**API Url**:
- `/search/<symbol>`

Example: when accessing the `/search/IPOF` endpoint the only results are:
- IPOF=
- IPOF+

The Class A `IPOF` symbol is not showing

**Comment by McQgit** [comment]
@gpoontip I am not IEX but I just looked up all 4 of those quotes and they worked fine for me.  You seem new - might you have omitted the required 'token' parameter?  Here's a working example:

https://cloud.iexapis.com/stable/stock/acic/quote?token=(redacted)

If you had the token, I'm sure the IEX folks would like to know the exact error you receive (http code or whatever).

These are their Getting Started topics, if you haven't seen them yet:
https://intercom.help/iexcloud/en/collections/1659300-getting-started

**Comment by gpoontip** [comment]
@McQgit yes you're right thank you, my fault. When using `/stock/<symbol>/quote` it works, but when searching via `/search/<symbol>` they aren't found. I've updated the original post

**Comment by timpaine-iex** [comment]
@gpoontip I just tried all four and they all worked. I tried exactly the symbols you wrote into e.g. `https://cloud.iexapis.com/stable/search/IPOF?token=<my token>`

<img width="808" alt="Screen Shot 2021-01-18 at 9 13 30 PM" src="https://user-images.githubusercontent.com/74613173/104979373-21341e00-59d2-11eb-8665-93fbd3970080.png">
<img width="815" alt="Screen Shot 2021-01-18 at 9 13 43 PM" src="https://user-images.githubusercontent.com/74613173/104979375-21341e00-59d2-11eb-9546-1549164b1211.png">
<img width="844" alt="Screen Shot 2021-01-18 at 9 13 58 PM" src="https://user-images.githubusercontent.com/74613173/104979377-21ccb480-59d2-11eb-9884-505e6c4792b5.png">
<img width="831" alt="Screen Shot 2021-01-18 at 9 14 05 PM" src="https://user-images.githubusercontent.com/74613173/104979378-21ccb480-59d2-11eb-8ddb-30e1e2650954.png">

**Comment by gpoontip** [comment]
Thanks. It must have been a glitch or been fixed. When I searched yesterday using https://iexcloud.io/console/search it wasn't returning those values. I'll close the issue.
