### ISSUE TITLE
[Issue] Inconsistent data historical prices

### ISSUE THREAD

**Issue by websolut** [iexg/IEX-API#1688]
**Date/time of the issue**
22/01/2021

**What you did**
Requested 
https://sandbox.iexapis.com/stable/stock/NCYT-LN/chart/2y?token=

**What you expected to happen**
Price OCHL is consistent

**What actually happened**

Why I am getting different data on every run?
`{"close":11.27,"high":11.92,"low":11.37,"open":11.99,"symbol":"NCYT-LN","volume":428400,"id":"PARILCORS_ICTHSIE","key":"NL-NTCY","subkey":"0","date":"2021-01-21","updated":1629427546463,"changeOverTime":30.41125885053897,"marketChangeOverTime":31.76283419826455,"uOpen":11.47,"uClose":11.05,"uHigh":11.69,"uLow":11.29,"uVolume":424765,"fOpen":11.44,"fClose":11.25,"fHigh":11.73,"fLow":11.18,"fVolume":440426,"label":"Jan 21, 21","change":-0.2031284513149025,"changePercent":-0.018}
{"close":10.97,"high":11.72,"low":10.94,"open":11.91,"symbol":"NCYT-LN","volume":431914,"id":"ROCI_SRCILHIPTAES","key":"TCY-LNN","subkey":"0","date":"2021-01-21","updated":1682415187175,"changeOverTime":30.52371925039607,"marketChangeOverTime":31.13279473266644,"uOpen":11.93,"uClose":11.33,"uHigh":11.59,"uLow":11.26,"uVolume":428172,"fOpen":11.81,"fClose":11.26,"fHigh":11.66,"fLow":11.13,"fVolume":438095,"label":"Jan 21, 21","change":-0.2048094323149509,"changePercent":-0.0183}
{"close":11.18,"high":11.91,"low":11.19,"open":11.89,"symbol":"NCYT-LN","volume":441899,"id":"AREHLRPSSOCTIIC_I","key":"YNLT-NC","subkey":"0","date":"2021-01-21","updated":1686872513097,"changeOverTime":31.31799072101303,"marketChangeOverTime":30.42269539119353,"uOpen":11.48,"uClose":11.44,"uHigh":11.77,"uLow":11,"uVolume":424176,"fOpen":11.99,"fClose":11.08,"fHigh":11.46,"fLow":10.86,"fVolume":428111,"label":"Jan 21, 21","change":-0.2010235838282725,"changePercent":-0.0182}

`

**API Url (if applicable)**
https://sandbox.iexapis.com/stable/stock/NCYT-LN/chart/2y?token=

**Additional relevant information**

other provider:

        "2021-01-21": {
            "1. open": "1144.0",
            "2. high": "1144.0",
            "3. low": "1082.18",
            "4. close": "1096.0",
            "5. adjusted close": "1096.0",
            "6. volume": "383261",
            "7. dividend amount": "0.0000",
            "8. split coefficient": "1.0"
        },

**Comment by McQgit** [comment]
@websolut The sandbox intentionally scrambles data - see here:
https://iexcloud.io/docs/api/#testing-sandbox

You might want to also see the Getting Started section that IEX provides:
https://iexcloud.io/support/

**Comment by timpaine-iex** [comment]
thanks @McQgit, remind me to have some swag sent to you
