### ISSUE TITLE
[Data] GME reporting incorrect previousClose, change, and changePercent

### ISSUE THREAD

**Issue by JohnMaguire** [iexg/IEX-API#1689]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Email account associated with your IEX Account**
jmaguire2013@gmail.com

**Date/time of the issue**
Now

**What you did**
https://cloud.iexapis.com/stable/stock/GME/quote?token=...

**What you expected to happen**
```
"previousClose": 147.98,
"change": 199.53,
"changePercent": 1.3484,
```

**What actually happened**
```
"previousClose": 76.79,
...
"change": 270.71,
"changePercent": 3.52533,
```

**API Url (if applicable)**
https://cloud.iexapis.com/stable/stock/GME/quote?token=...

**Additional relevant information**

**Comment by timpaine-iex** [comment]
@JohnMaguire this appears to be resolved, are you still getting the same result?

**Comment by JohnMaguire** [comment]
The issue was present up until at least 4:54:35 Eastern, but was resolved by 5:02:23 Eastern.

Is this a common occurrence? I see other issues opened with the same problem. Is there any way to avoid this issue?

**Comment by timpaine-iex** [comment]
No not common, thanks for reporting. I don't see other open issues with the same problem. No way to avoid but we're working hard to better detect and to streamline the process from user reporting to resolution.
