### ISSUE TITLE
Frequently disconnection from websocket

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#169]
Hi, anyone else experience frequently disconnection from websocket? Sometimes my websocket client is disconnected a few times per minute.

Thanks!

**Comment by joshuablackburn-iex** [comment]
We have noticed a large increase in Websocket use recently which has caused an increase in disconnections.  We have added more resources to hopefully alleviate the issue.  Unfortunately there isn't much we can do in the near term with this version of the API other than adding more resources.  Version 2 will introduce more reliable push.
