### ISSUE TITLE
[Data] Options openInterest does not match CBOE

### ISSUE THREAD

**Issue by thwd** [iexg/IEX-API#1691]
##  Welcome to IEX Cloud's Github Community.

**Date/time of the issue**
February 5th, 2021.

**What you did**
`GET /stock/GME/options/20210212?token=<TOKEN>`

**What you expected to happen**
The `openInterest` fields in the response match those published by CBOE.

This should be EOD data for February 4th, 2021. Published at 9:30am ET on the next day (Feb 5th).

**What actually happened**
The `openInterest` fields in the response don't match CBOE. 

**API Url (if applicable)**
`cloud.iexapis.com/v1/stock/GME/options/20210212`

**Additional relevant information**
I have emailed a comparison to support@. It's two small CSV files with the relevant data.

**Comment by timpaine-iex** [comment]
Tracked via support ticket
