### ISSUE TITLE
Custom requests to get needed data

### ISSUE THREAD

**Issue by evanwherchek** [iexg/IEX-API#1692]
**Email account associated with your IEX Account**
evanherchekapps@gmail.com

**Is your feature request related to a problem? Please describe.**
I recently started using the IEX Cloud API (it works great!). I am currently working on a custom class for my app to store stock data. For this class, I need the price but I also need the beta of the stock. The only way to do this right now is to make two separate requests to the API. One request is for a quote to get the price and the other is for the advanced stats to get the beta.

**Describe the solution you'd like**
It would be nice if I could somehow create a custom request to the API to only get the stats I need. That way, I could cut down on the number of requests I'm making and have more efficient code.

**Additional context**
Here's the code I'm working on for reference:
```
class StockPrice{

  String symbol;
  String name;
  double price;
  double change;
  double beta;

  StockPrice({ this.symbol });

  Future<void> getPrice() async {
    try{
      Response quote = await get('https://cloud.iexapis.com/stable/stock/$symbol/quote?token=MY_TOKEN'); //request #1
      Response stats = await get('https://sandbox.iexapis.com/stable/stock/$symbol/stats?token=MY_TOKEN'); //request #2

      Map priceData = jsonDecode(quote.body);
      Map statData = jsonDecode(stats.body);

      name = priceData['companyName'];
      price = priceData['latestPrice'];
      change = priceData['change'];
      beta = statData['beta'];
    }catch (e) {
      print('caught error $e');
      price = 0.0;
    }
  }

}
```

**Comment by timpaine-iex** [comment]
https://iexcloud.io/docs/api/#data-points

e.g. `https://cloud.iexapis.com/v1/data-points/JPM/BETA?token=...`

**Comment by timpaine-iex** [comment]
can probably use `https://cloud.iexapis.com/v1/data-points/JPM/QUOTE-LATESTPRICE` for latest price as well.

**Comment by timpaine-iex** [comment]
key stats endpoint can also accept the specific stat as a path parameter 
https://iexcloud.io/docs/api/#key-stats
