### ISSUE TITLE
[Data] Can't retrieve financial data for OTC symbols JUSHF, TCNNF, GGTTF

### ISSUE THREAD

**Issue by gpoontip** [iexg/IEX-API#1693]
**Date/time of the issue**
Feb 13 10am MST

**What you did**
Retrieve financial data for JUSHF, TCNNF, GGTTF

**What you expected to happen**
Get financial data

**What actually happened**
API returned empty array

**API Url**
- https://cloud.iexapis.com/stable/stock/JUSHF/financials/
- https://cloud.iexapis.com/stable/stock/TCNNF/financials/
- https://cloud.iexapis.com/stable/stock/GGTTF/financials/

**Comment by AndrewBarfield** [comment]
Could it be because you're using the sandbox?

**Comment by gpoontip** [comment]
> Could it be because you're using the sandbox?

No I've updated the issue to avoid any confusion.
Another example of a stock listed on the NYSE that has no financial data is LAC
You can see here https://iextrading.com/apps/stocks/LAC that the financial data is missing from the main IEX website as well

**Comment by McQgit** [comment]
@gpoontip I am not IEX but I'd guess this is only supported for US listings that issue SEC 10-Q and 10-K statements.  LAC is Canadian and does not report to the SEC in this manner:
https://www.sec.gov/cgi-bin/browse-edgar?CIK=lac&owner=exclude&action=getcompany

Of course, your first examples were all foreign issuers - the 5 character symbol with ending 'F' gives it away :)

All that said, the /financial endpoint has migrated to newer endpoints - both basic and advanced.  You'll notice the newer /income endpoint mentions US symbols only - I'm guessing they actually mean 10Q/10K specifically.  See:
https://iexcloud.io/docs/api/#financials
