### ISSUE TITLE
[Data] Time Series Revenue

### ISSUE THREAD

**Issue by ncboiler** [iexg/IEX-API#1698]
Hello,

I am new to the platform and still working in the sandbox.  I am wondering if I am doing something wrong.  I would like to get annual revenue a ticker going back 20 years.  The only place I see to do that is pulling it out of the Advanced Fundamentals however that is 75,000 messages per record so 20 years of revenue data is 1.5 million messages.  Am I doing something wrong or is there a better way to get this data other than the Advanced Fundamentals?  

Thank you!!

**Comment by timpaine-iex** [comment]
You can use the [income](https://iexcloud.io/docs/api/#income-statement) data, here is how I'd access it via [timeseries](https://iexcloud.io/docs/api/#time-series):

`https://cloud.iexapis.com/stable/time-series/INCOME/AAPL/annual?last=20&token=...`
