### ISSUE TITLE
Peer load slow

### ISSUE THREAD

**Issue by aperroni** [iexg/IEX-API#170]
## Summary
peer load slow

## Details
when executing batch request for peers the response is extremely slow
### Date/time of issue
Jan 9, 2018 - slow response is not a function of time of day

### API URL
Batch load with list of symbols just asking for peers

### What you expected to happen
speed comparable to company load.  When I run a batch request for a list of symbols and ask for company data it runs 20 times faster than when I ask for peers.  Wondering if this might be a simple index fix.

**Comment by joshuablackburn-iex** [comment]
Do you mind including your request URL?

**Comment by aperroni** [comment]
Here is the url that executes quick

 

https://api.iextrading.com/1.0/stock/market/batch?symbols=A,AA,AAAP,AABA,AAC,AADR,AAL,AAMC,AAME,AAN,AAOI,AAON,AAP,AAPL,AAT,AAU,AAV,AAWW,AAXJ,AAXN,AB,ABAC,ABAX,ABB,ABBV,ABC,ABCB,ABCD,ABDC,ABE,ABEO,ABEOW,ABEV,ABG,ABIL,ABIO,ABLX,ABM,ABMD,ABR,ABR-A,ABR-B,ABR-C,ABRN,ABT,ABTX,ABUS,ABX,AC,ACAD,ACBI,ACC,ACCO,ACER,ACERW,ACET,ACFC,ACGL,ACGLO,ACGLP,ACH,ACHC,ACHN,ACHV,ACIA,ACIM,ACIU,ACIW,ACLS,ACM,ACMR,ACN,ACNB,ACOR,ACP,ACRE,ACRS,ACRX,ACSF,ACSI,ACST,ACT,ACTA,ACTG,ACU,ACV,ACWF,ACWI,ACWV,ACWX,ACXM,ACY,ADAP,ADBE,ADC,ADES,ADI,ADM,ADMA,ADMP&types=company

 

adding peers to it increase query time by 15x

 

https://api.iextrading.com/1.0/stock/market/batch?symbols=A,AA,AAAP,AABA,AAC,AADR,AAL,AAMC,AAME,AAN,AAOI,AAON,AAP,AAPL,AAT,AAU,AAV,AAWW,AAXJ,AAXN,AB,ABAC,ABAX,ABB,ABBV,ABC,ABCB,ABCD,ABDC,ABE,ABEO,ABEOW,ABEV,ABG,ABIL,ABIO,ABLX,ABM,ABMD,ABR,ABR-A,ABR-B,ABR-C,ABRN,ABT,ABTX,ABUS,ABX,AC,ACAD,ACBI,ACC,ACCO,ACER,ACERW,ACET,ACFC,ACGL,ACGLO,ACGLP,ACH,ACHC,ACHN,ACHV,ACIA,ACIM,ACIU,ACIW,ACLS,ACM,ACMR,ACN,ACNB,ACOR,ACP,ACRE,ACRS,ACRX,ACSF,ACSI,ACST,ACT,ACTA,ACTG,ACU,ACV,ACWF,ACWI,ACWV,ACWX,ACXM,ACY,ADAP,ADBE,ADC,ADES,ADI,ADM,ADMA,ADMP&types=company,peers

 

 

Thanks!
