### ISSUE TITLE
[Data] Intraday data missing after 15:03 on 2021-02-25

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1701]
**Date/time of the issue**
2021-02-25 to present

**What you did**
Requested intraday data for 2021-02-25.

**What you expected to happen**
390 minutes of data to be returned. 

**What actually happened**
334 minutes were returned, up until 15:03. Market data is only returned until 14:48. Appears all symbols may be affected.

**API Url (if applicable)**
https://cloud.iexapis.com/stable/stock/SPY/chart/date/20210225?token=

**Comment by humenick** [comment]
Appears this affects several days this past week. 

There is a notice on https://status.iexapis.com/ from Feb 23rd: “Monitoring - Due to market volume, minute bar may be delayed.”

I’m concerned why this is still a problem as I usually re-request the whole months of intraday data at the end of the month to clean up the regular missing data issues.

**Comment by StockConsultant** [comment]
Yes I just noticed gaps in my intraday data for Friday 2/26 and Thursday 2/25 for the intraday endpoint. Just emailed them, hopefully they fix it so I can rebuild.

**Comment by StockConsultant** [comment]
There has also been an ongoing issue that has an open case: on the last 5-10 mins of the intraday minute data not filling in on some days.

**Comment by DavidKuennen** [comment]
Currently happening again.

**Comment by markortleb** [comment]
I am experiencing gaps in my intraday data as well. It usually seems to be that the last few hours of the trading day are not covered in the intraday data. This has been the case for a few days out of the last like 2 or 3 weeks or so.

**Comment by timpaine-iex** [comment]
please monitor https://status.iexapis.com for status updates

**Comment by achedges** [comment]
Are there any updates on this issue?  I'm still seeing missing market data for various dates/symbols, ie https://cloud.iexapis.com/v1/stock/AAPL/intraday-prices?exactDate=20210303

**Comment by HarveyAtwal** [comment]
I'd like an update too, I'm noticing the same issue:
https://sandbox.iexapis.com/stable/stock/twtr/intraday-prices?exactDate=20210511
