### ISSUE TITLE
No/wrong logos for some companies from most active list

### ISSUE THREAD

**Issue by messin9** [iexg/IEX-API#1703]
Clearly describe the problem
X coming from logo API is wrong
See image:
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/RKT.png
 https://storage.googleapis.com/iexcloud-hl37opg/api/logos/SNDL.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/PLTR.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/CCIV.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/CLOV.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/LKCO.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/DKNG.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/MU.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/NCLH.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/OCGN.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/MICT.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/SPCE.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/VIAC.png
https://storage.googleapis.com/iexcloud-hl37opg/api/logos/KXIN.png

What time did the problem occur? (with timezone)
anytime

What is the expected behavior?
corret logo

Your environment (e.g. browser, OS, API version, language):
IOS

API URL (if applicable)
https://cloud.iexapis.com/stable/stock/xp/logo?token=XXXXXXXXX

What are the steps to reproduce the bug?
Call log api

**Comment by timpaine-iex** [comment]
These all look ok:
RKT, SNDL, PLTR, DKNG, MU, NCLH, OCGN, SPCE, VIAC.

For some of the others I looked around and didn't really see an official logo, but we'll make a note to double check and fill in gaps.
