### ISSUE TITLE
[Issue] There is a typo in the /stock/{symbol}/quote API call

### ISSUE THREAD

**Issue by robertmetcalf** [iexg/IEX-API#1706]
##  There is a typo in the` /stock/{symbol}/quote` API call

Good: `iexlasttrade`

Typo: `iexlastrade`

**Comment by timpaine-iex** [comment]
@robertmetcalf can you clarify what you mean by this? I'm assuming you mean `calculationPrice` is set to `iexlastrade`, I see there's a typo in the documentation but do you see this from the API call itself? Are you using `beta` or `v1`/`stable`?

**Comment by robertmetcalf** [comment]
@timpaine-iex

The typo is in the documentation, specifically in the `calculationPrice` description.

In the JSON results, I have only seen: `"calculationPrice": "close"`. I presume a result of `iexlasttrade` would be correct in the JSON.

The `quote` documentation` is [found here](https://iexcloud.io/docs/api/#quote).

**Comment by timpaine-iex** [comment]
@robertmetcalf great that's what I was hoping, I've already fixed it and it should be deployed today, thanks for pointing out!
