### ISSUE TITLE
Batch quote timing out today [Issue]

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1707]
**Date/time of the issue**
2021-03-17 09:45-present

**What you did**
I have a cron job to request batch quotes for IEX Cloud periodically. 

**What you expected to happen**
Quotes to be returned from the API.

**What actually happened**
Some requests have been timing out today, first starting ~09:45-09:47 ET. Most recently 12:00-12:05 ET.

**API Url (if applicable)**
https://cloud.iexapis.com/stable/stock/market/batch?symbols=SPY,QQQ&types=quote&token=

**Comment by timpaine-iex** [comment]
Some load balancer issues around 9:45 https://status.iexapis.com but I don't see anything around 12. Timeout can be on your side/your isp as well, but we'll continue to monitor.

**Comment by timpaine-iex** [comment]
@humenick looks like there are some networking issue with our cloud provider

**Comment by timpaine-iex** [comment]
Closing as the issues appear to be mitigated

**Comment by humenick** [comment]
Okay, last timeout was 13:46 ET.

Also, could you add a link to https://status.iexapis.com to the README.md?

**Comment by timpaine-iex** [comment]
yep done

**Comment by humenick** [comment]
thank you!
