### ISSUE TITLE
Data request: add quarter end date to Financials endpoint

### ISSUE THREAD

**Issue by PGNetHun** [iexg/IEX-API#171]
## Summary
Add "quarterEndDate" to Financials endpoint:
https://iextrading.com/developer/docs/#financials

## Details
"/stock/{symbol}/financials" returns reported quarters, and only "reportDate" is added, the quarter end date is missing.

Google Finance & Yahoo Finance show quarters data grouped by quarter end date.
I collect financial data from different sources, and the "key" to match the quarters is the quarter end date. Other data providers return quarter end date, IEX not, and so I can't match the IEX quarter financial data with other data.

Example:

NVIDIA Corporation - NVDA
Quarter end date: 2017-10-29   (returned by Yahoo Finance, Google Finance, Intrinio)
IEX "reportDate": 2017-10-31

Google Finance: https://finance.google.com/finance?q=NASDAQ%3ANVDA&fstype=ii

Yahoo Finance: https://finance.yahoo.com/quote/NVDA/financials?p=NVDA

Intrinio: https://api.intrinio.com/historical_data?identifier=NVDA&item=rdexpense&type=QTR

IEX: https://api.iextrading.com/1.0/stock/NVDA/financials

### Date/time of issue
2018-01-09

### API URL
https://iextrading.com/developer/docs/#financials

**Comment by timpaine-iex** [comment]
closing as stale
