### ISSUE TITLE
Field parameter is not allowed in quote batch requests

### ISSUE THREAD

**Issue by andrei-niciu** [iexg/IEX-API#1713]
**What you did**
Batch request for Quote, requesting only latestPrice:
curl --request GET 'https://cloud.iexapis.com/stable/stock/market/batch?symbols=AAPL,TSLA&types=quote&field=latestPrice&token=TOKEN_PLACEHOLDER

**What you expected to happen**
Return latestPrice data (only latestPrice field) for the two symbols.
I am expecting this because documentation specifies that parameters can be used in batch requests. Also, it works as expected for news (for example requesting news in a batch, with value of 'last' parameter being 2):
curl --request GET 'https://cloud.iexapis.com/stable/stock/market/batch?symbols=AAPL,TSLA&types=news&last=2&token=TOKEN_PLACEHOLDER

**What actually happened**
Response: 400 Bad Request
{
    "error": "\"field\" is not allowed"
}

**API Url (if applicable)**
https://cloud.iexapis.com/stable/stock/market/batch

**Additional relevant information**

**Comment by McQgit** [comment]
@andrei-niciu The query term is `filter`, not `field`:
https://iexcloud.io/docs/api/#filter-results

**Comment by andrei-niciu** [comment]
@McQgit, Thanks for pointing this out!
