### ISSUE TITLE
15 minutes delay in the realtime quote

### ISSUE THREAD

**Issue by zwatgit** [iexg/IEX-API#1716]
**Date/time of the issue**
13:19 04/22/2021

**What you did**
Checked realtime quotes

**What you expected to happen**
no delay in real time price

**What actually happened**
By comparing the latestTime value with wall lock, all the tickers showed a delay of 15 minutes

**API Url (if applicable)**
https://cloud.iexapis.com/stable/stock/QQQ/quote

**Additional relevant information**
n/a

**Comment by timpaine-iex** [comment]
QQQ is UTP, Nasdaq requires authorization for realtime. 
https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud
