### ISSUE TITLE
IEX Cloud sandbox is down

### ISSUE THREAD

**Issue by eljog** [iexg/IEX-API#1717]
I was experimenting IEX Cloud while considering to buy the service.
I have been using the Sand box and now it is returning `502` for all API calls.

Url: https://sandbox.iexapis.com/stable/stock/IBM/quote?token=TOKEN

Response: `502 Bad Gateway`

**Comment by WojciechZankowski** [comment]
Looks like it is up, but not fully. For the same request, one time I get

```
403 Forbidden: Test tokens may only be used in the sandbox environment. Please use https://sandbox.iexapis.com
```

and the other time I get full response.

**Comment by timpaine-iex** [comment]
Seems ok now
