### ISSUE TITLE
[Issue] Sandbox View turns itself off

### ISSUE THREAD

**Issue by GerryOnGithub** [iexg/IEX-API#1718]
Okay, so I new here and trying things out. Or I would if I could. The switch to turn Sandbox View on keeps resetting to off. 

I see an error in the console 
Content Security Policy: The page’s settings blocked the loading of a resource at https://www.facebook.com/tr/ (“connect-src”).

Seriously, I have to have facebook enabled or whatever to use the API?

**Comment by timpaine-iex** [comment]
Nope, of course not. follow up in #1446
