### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by kermit-t-frog** [iexg/IEX-API#1719]
**Email account associated with your IEX Account**
matthias.held@web.de

**Date/time of the issue**
not applicable

**What you did**
Queried the chart endpoint for XETRA traded stock, e.g. VOW3-GY (Volkswagen @ XETRA) and ALV-GY (Allianz SE @ XETRA), but also for other (German) stock market exchanges such as Frankfurt (-GF).

I compared the resulting (fully) adjusted close data with another data vendor (alphavantage.co) and the exchange's publicly available data at https://www.boerse-frankfurt.de/equity/allianz-se/price-history/historical-prices-and-volumes (filter for start date 06/05/2020 ,End date 06/05/2021, adjust for splits, dividends, subscription rights.)

**What you expected to happen**
Sufficiently consistent close / (fully) adjusted close data across the three data sources for the available time series history of IEX data. 

**What actually happened**
The adjusted and fully adjusted close prices provided by IEX are only correct for the recent past (2017/2018-2021). The endpoint's adjusted close prices pre 2018 do not reflect historical dividends correctly when compared to the exchange's data. This holds true for all stock tickers tested. 

Nota bene: The issue is **even worse** for other exchanges: When querying the same instruments at Frankfurt Stock Exchange (ALV-GF, VOW3-GF), the data does not reflect any kind of corporate action.

**API Url (if applicable)**
https://cloud.iexapis.com/stable/stock/{symbol}/chart/max?token=MYTOKEN

**Additional relevant information**

**Comment by timpaine-iex** [comment]
submitted via support
