### ISSUE TITLE
Price/Sales from stats API incorrect

### ISSUE THREAD

**Issue by jfroberts** [iexg/IEX-API#172]
## Summary
This appears to be like issue #39, except for the priceToSales field. The value appears to be computed based on the cumulative revenue over the trailing three quarters, instead of the trailing four quarters. I see this issue with both Cypress Semiconductor (CY) and Apple (AAPL). I haven't checked others. The values reported by IEX do not match the values from other sources, and the math (market cap / trailing 12 months revenue) doesn't work out either.

![iex_psratio](https://user-images.githubusercontent.com/35280741/34752508-bb08ae74-f580-11e7-94c1-77a00892da46.png)
![yahoo_psratio](https://user-images.githubusercontent.com/35280741/34752511-bd0da2ce-f580-11e7-8df0-7418d5a60533.png)
![ycharts_psratio](https://user-images.githubusercontent.com/35280741/34752513-be7989ac-f580-11e7-8554-6eabae5a518d.png)

## Details

This example uses Cypress Semiconductor (CY):

IEX priceToSales: 3.2089
IEX marketCap: 5582211502
IEX totalRevenue (Q317, Q217, Q117, Q416): 604574000, 593776000, 531874000, 530172000

Trailing 3 quarters revenue: 604574000 + 593776000 + 531874000 = 1730224000
market cap / 3 quarter revenue = 5582211502 / 1730224000 = 3.226

The math doesn't work out exactly, but it's close enough to make me wonder.

If I use all four quarters of revenue, it comes out much closer to what other sources report:

604574000 + 593776000 + 531874000 + 530172000 = 2260396000
5582211502 / 2260396000 = 2.470

The math works similarly for Apple.

### Date/time of issue

The data I've used comes from Yahoo, YCharts, and IEX after trading on January 9, 2018.

### API URL
https://api.iextrading.com/1.0/stock/cy/stats
https://api.iextrading.com/1.0/stock/cy/financials

**Comment by evancarter-iex** [comment]
Closing. No longer an issue in IEXCloud. https://iexcloud.io
