### ISSUE TITLE
[Data] Symbol suffix for two International exchanges is -null

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1720]
Date/time of the issue

5/8/2021 5:46 PM PST

What you did

Accessed following endpoint

/ref-data/exchanges/

What you expected to happen

To get the exchangeSuffix response attribute for each exchange.

What actually happened

Value is -null for the following exchanges

country: Azerbaijan
region: AZ
shortName:  BSEX
longName: Baku Stock Exchange
mic: BSEX

country: Ukraine
region: UA
shortName:  SEPE
longName: Stock Exchange Perspectiva
mic: SEPE

If you do a lookup for symbols on the above exchanges, symbols are returned with -BSEX and -SEPE after them so seems that should be what exchangeSuffix response attribute should be for each instead of -null.

**Comment by timpaine-iex** [comment]
This one has been a known issue for a while, let me see if I can fix today.
