### ISSUE TITLE
Latest price keeps updating even after the market is closed

### ISSUE THREAD

**Issue by alli1999** [iexg/IEX-API#1721]
I just created a iex cloud account to get stock quotes. But I noticed that every time I refresh the page the latest price changes by a huge amount. Even after refreshing the page after 1 second it shows something completely different.
You can try it out here:
https://sandbox.iexapis.com/stable/stock/EQRELIANCE-IS/quote?token=YOUR_TOKEN

**Comment by timpaine-iex** [comment]
Sandbox is scrambled, each request will be randomly scrambled.

**Comment by alli1999** [comment]
> Sandbox is scrambled, each request will be randomly scrambled.
Thanks for letting me know. I was trying to use the cloud url image of sandbox but it wasn't working for me

**Comment by timpaine-iex** [comment]
what do you mean by cloud url image

**Comment by alli1999** [comment]
So if I use a individual account, will the data I get be accurate?

**Comment by alli1999** [comment]
By cloud url I meant that instead of using sandbox.iexapis.com, should I use cloud.iexapis.com?

**Comment by timpaine-iex** [comment]
should work fine with any account, just use the main url not the sandbox
e.g. via `pyEX` library:

<img width="477" alt="Screen Shot 2021-05-13 at 9 19 40 AM" src="https://user-images.githubusercontent.com/74613173/118131310-5d99e880-b3cc-11eb-9ae1-67bb16b0fe24.png">

**Comment by alli1999** [comment]
Ohhh alright got it. I initially tried it with the above link but I got this message "Test tokens may only be used in the sandbox environment. Please use https://sandbox.iexapis.com". So with the free account I currently am using I won't be able to use cloud.iexapis.com right?

**Comment by alli1999** [comment]
Okay I got it to work. I used the secret token instead. Thanks for the help Tim Paine!
