### ISSUE TITLE
Inaccurate data for NSE exchange

### ISSUE THREAD

**Issue by alli1999** [iexg/IEX-API#1722]
I have taken an individual plan on iexcloud and when I was trying to get data for some equities on the site the share price was not accurate when compared to the official NSE website and Google. Could you please let me know if there is any solution to this? The quotes I checked with the inaccurate data are:
EQRELIANCE-IS
EQHDFC-IS
EQHONAUT-IS
EQITC-IS
And many more............

**Comment by timpaine-iex** [comment]
Just taking the first one and comparing [website](https://www1.nseindia.com/live_market/dynaContent/live_watch/get_quote/GetQuote.jsp?symbol=RELIANCE&illiquid=0&smeFlag=0&itpFlag=0#) to the historical prices endpoint and spot checking, I don't see anything off. Can you explain more what you're seeing?

**Comment by alli1999** [comment]
Hi Tim,

Thanks for getting back to me. The issue I was facing has been resolved by
someone else from your team.
Thanks again for your help.

Regards,
Alistair
