### ISSUE TITLE
Getting High value lower than the low value in response of Historic data

### ISSUE THREAD

**Issue by ankitinfostride** [iexg/IEX-API#1723]
I am fetching data from historic data API endpoint, Here is the screenshot attached for Apple & Amazon data over last year. Here you can see the highlighted or marked values in screenshot.

High value & low value at some places seems off, can you please explain how or let us know !!

![image (10)](https://user-images.githubusercontent.com/64560596/118511933-fd9a9d80-b74f-11eb-9dcd-de49c9a590b0.png)
![image (9)](https://user-images.githubusercontent.com/64560596/118511940-fecbca80-b74f-11eb-9b09-2a47cfe61349.png)

**Comment by timpaine-iex** [comment]
@ankitinfostride could you share the URLs you're querying (omit your token).

**Comment by timpaine-iex** [comment]
here's what I see
<img width="399" alt="Screen Shot 2021-05-17 at 4 05 42 PM" src="https://user-images.githubusercontent.com/74613173/118549619-bb5e6580-b729-11eb-8835-1688f6df0cab.png">

is this related to https://github.com/iexg/IEX-API/issues/1592?

**Comment by ankitinfostride** [comment]
@timpaine-iex - Indeed !
It is just because of sandbox glitch, got me worried like data is inconsistent.
Thank you so much for prompt reply.
