### ISSUE TITLE
[Data] Quarterly income: costOfRevenue = 0, grossProfit = totalRevenue

### ISSUE THREAD

**Issue by humenick** [iexg/IEX-API#1727]
**What you did**
I requested the past 12 quarterly income statements for 6,208 stocks (type: ad, cs, ut). 

**What actually happened**
I received income statements for 2,692 stocks.

Many have:
 - costOfRevenue = 0 (644 stocks, 455 stocks for all 12 quarters)
 - totalRevenue & grossProfit are the same value (628 of the 644 stocks, 392 stocks for all 12 quarters)
 - otherIncomeExpenseNet = 0 (2,627 stocks, 2,147 for all 12 quarters)

The income statements for the 644 stocks appear to be inaccurate.

**API Url (if applicable)**
https://cloud.iexapis.com/stable/stock/AAL/income/12

**Additional relevant information**
Affected symbols: AAIC, AAL, AAT, AAWW, ABR, ABTX, ABUS, ACGL, ACHC, ACR, ACRE, ACTG, ADC, ADP, ADXS, AEL, AER, AFG, AFL, AGEN, AGIO, AGNC, AGO, AGR, AHC, AHH, AIG, AIV, AIZ, AKR, AL, ALBO, ALGT, ALK, ALL, ALNY, ALX, AMCX, AMG, AMH, AMNB, AMP, AMSF, ANAB, ANAT, ANTM, APA, APAM, APLE, APO, APTS, AR, ARCB, ARCC, ARCO, ARE, ARES, ARGO, ARI, ARL, ARNA, ARR, ARTNA, ARWR, ASB, ASTC, ATH, ATSG, AUD, AUMN, AVB, AVEO, AWK, AXAS, AXS, BAM, BANF, BBGI, BBI, BBVA, BCE, BCEI, BCRX, BDN, BEN, BFS, BGCP, BHF, BHVN, BKI, BKNG, BLK, BLX, BMRC, BOKF, BPMC, BRG, BRO, BRT, BRX, BSM, BTU, BX, BXMT, BXP, CABO, CAI, CAR, CARA, CASS, CATY, CB, CBLI, CBZ, CCL, CCRN, CDEV, CDLX, CDR, CDZI, CEI, CEIX, CFFN, CHMI, CHNG, CHTR, CIA, CIM, CINF, CIO, CIVB, CLDX, CLI, CLNC, CLNY, CLR, CLSN, CLXT, CMA, CMCSA, CME, CMO, CMRE, CMRX, CNA, CNBKA, CNO, CNQ, CNS, CNX, CODX, COHN, COMP, COR, COWN, CP, CPA, CPE, CPT, CRBP, CRK, CRSP, CSR, CSTR, CSU, CSWC, CSX, CTIC, CTMX, CUBE, CUZ, CVBF, CVM, CXP, CXW, CYH, CYTK, DAL, DEA, DEI, DEN, DGICA, DHC, DHIL, DHT, DLR, DNLI, DNN, DOC, DRE, DSKE, DSX, DVA, DVD, DVN, DX, E, EAT, ECHO, ECPG, EDIT, EGP, EGY, EHC, EIG, EIX, ELLO, ENB, ENTA, EOG, EOLS, EPD, EPR, EQC, EQH, EQR, EQT, ERF, ESEA, ESGR, ESNT, ESRT, ESS, ETRN, EVR, EWBC, EXPO, EXR, EYES, FAF, FANG, FBC, FBMS, FBNC, FBRX, FCPT, FCRD, FDX, FFG, FFIC, FGEN, FHB, FHI, FLIC, FLMN, FLT, FLY, FNF, FOXA, FR, FRBK, FRME, FRPH, FRT, FTAI, FTK, FVE, GABC, GATX, GBCI, GBLI, GDOT, GEO, GERN, GHL, GL, GLRE, GNW, GOOD, GPMT, GROW, GRUB, GS, GSBD, GSL, GTE, GTS, GTY, GURE, HA, HALL, HASI, HBCP, HCA, HCI, HES, HIG, HIW, HLI, HLNE, HMN, HMST, HNRG, HOMB, HP, HPP, HR, HSII, HTGC, HUM, HURN, HUSA, HWBK, IBKR, ICE, ICON, IDCC, IDRA, IHC, IIIV, IIPR, ILPT, IMGN, IMH, INDB, INDT, INFI, INO, INSM, INVA, INVH, IONS, IRWD, ITUB, IVR, IVZ, JACK, JBGS, JBLU, JHG, JLL, JMP, KALV, KEX, KIM, KKR, KMPR, KNSL, KRC, KREF, KRG, KSU, L, LADR, LAZ, LBAI, LBRDK, LC, LEE, LINC, LMND, LMST, LNC, LOAN, LPI, LPLA, LSI, LSTR, LTC, LUV, LXP, LXRX, MA, MAA, MAC, MAIN, MATX, MAXR, MBI, MBWM, MC, MCBC, MCF, MCO, MCRB, MCY, MD, MDP, MET, MFA, MGP, MHLD, MHO, MITT, MKL, MKTX, MMAC, MMC, MNR, MPW, MRNA, MRTN, MRTX, MS, MSEX, MSGS, MT, MTDR, MTEM, MTG, MUR, MVIS, NAVB, NBHC, NETI, NEWT, NHC, NHI, NKLA, NLY, NM, NMFC, NMRK, NNN, NOAH, NOG, NRP, NSA, NSC, NTLA, NTP, NTRS, NVAX, NVGS, NWG, NWLI, NWSA, NXRT, NYMT, NYMX, O, OAS, OBLN, OCN, ODFL, OFC, OHI, OLP, OMC, OMEX, ONB, ONCT, OPI, OPOF, OPY, ORC, ORI, ORRF, OSBC, OTLK, OUT, OVV, OXSQ, PALI, PAYX, PB, PDCE, PDM, PEAK, PEI, PFG, PGR, PGRE, PHX, PJT, PLD, PMT, PRA, PRAA, PRAH, PRDO, PRG, PRI, PRTA, PRTK, PRU, PSB, PSTV, PTMN, PTN, PTSI, PTVCB, PXD, PYPL, PZN, PZZA, QTS, QURE, RAND, RBNC, RE, REFR, REG, RETA, REXR, RGA, RIG, RKT, RLGY, RLI, RNR, RNST, ROIC, RPAI, RPT, RRC, RWT, SAFT, SAGE, SAIA, SAN, SB, SBGI, SBLK, SBRA, SBUX, SCHW, SCU, SEIC, SF, SFL, SGMO, SI, SIGA, SIGI, SITC, SKT, SKYW, SLG, SLS, SM, SNDX, SNEX, SPCE, SPG, SRC, SRG, SSP, STAG, STC, STFC, STOR, STRA, STT, SVC, SWKH, SWN, SYBT, SYNH, SYRS, TALO, TCI, TCPC, TEF, TFSL, TGTX, THC, THG, TISI, TK, TOT, TRI, TRNO, TRP, TRST, TRTX, TRV, TSLX, TTEK, TUP, TURN, TW, TWO, TWOU, UBA, UDR, UE, UFCS, UHS, UHT, ULH, UMPQ, UNIT, UNM, UNP, UPS, USAK, USEG, USPH, UTI, UVE, V, VALU, VCTR, VER, VHC, VIAC, VICI, VIRT, VLRS, VNO, VNRX, VOYA, VRTS, VTOL, VTR, VXRT, VYGR, WABC, WAFD, WASH, WATT, WCC, WDR, WELL, WERN, WETF, WHG, WLL, WLTW, WMC, WOW, WPC, WPG, WRB, WRE, WRI, WSBF, WTBA, WTI, WTRG, WVE, WWE, XEC, XLRN, XNCR, XOM, XOMA, Y, YELL, YORW, YTEN, ZGNX, ZYME

**Comment by timpaine-iex** [comment]
@humenick 
So 2,692 / 6,208 sounds correct for coverage of NewConstructs vs our old provider

`costOfRevenue` probably has not been mapped from the `advanced_fundamentals` endpoint back to `income`, we'll take a look

`totalRevenue` and `grossProfit` probably have been mapped incorrectly from the `advanced_fundamentals` endpoint back to `income`, we'll take a look

`otherIncomeExpenseNet` probably has not been mapped from the `advanced_fundamentals` endpoint back to `income`, we'll take a look
