### ISSUE TITLE
Easy way to detect new financials?

### ISSUE THREAD

**Issue by DaveDel** [iexg/IEX-API#1728]
Hi,

Is there an easy (and cheap) way to know when new income/cash-flow/balance-sheet records are available?  It would be ideal if there were a couple of fields on Key Stats: latestQtrReportDate & latestYrReportDate - which would correspond to the last reportDate available in the financials endpoints.  Since that's not available, is there some other endpoint that can help?

One idea would be to watch Key Stats/nextEarningsDate.  This would be effective if new financials records are available soon after earnings are published - can anyone comment on this timing?

**Comment by timpaine-iex** [comment]
https://iexcloud.io/docs/api/#data-points
and 
https://iexcloud.io/docs/api/#time-series-metadata-beta
should be helpful for this. 

e.g. https://cloud.iexapis.com/stable/data-points/AAPL will show you a bunch of datapoints and their last updated date, while https://cloud.iexapis.com/stable/metadata/time-series/*/AAPL will provide you some metadata information across the various timeseries records.
