### ISSUE TITLE
Dividend info doesn't return for some symbols

### ISSUE THREAD

**Issue by jimmyzzxhlh** [iexg/IEX-API#173]
## Summary
https://api.iextrading.com/1.0/stock/dl/dividends/5y
This stock has dividends distributed for the last few years, but the API returns an empty JSON. 
http://www.nasdaq.com/symbol/dl/dividend-history

**Comment by goldeneye77** [comment]
Same issue with AbbVie Inc.

https://api.iextrading.com/1.0/stock/abbv/dividends/5y

**Comment by jimmyzzxhlh** [comment]
The above two symbols are fixed now, thanks!

However, I'm now wondering whether the historical chart takes dividend into account, e.g. DL has an ex-dividend date on 01/11/2018 with an amount of 0.45, its close price on 01/10 is 9.78 and open price on 01/11 is 9.38, which reflects the dividend, so 9.78 is not an adjusted price. Will the price be adjusted at some point, or do we keep the data as is?

**Comment by jimmyzzxhlh** [comment]
AA also should have multiple dividends for the past years but the API only returns two dividends, the second one returns an empty string for amount field, which could break parsing logic.

https://api.iextrading.com/1.0/stock/aa/dividends/5y
http://www.nasdaq.com/symbol/aa/dividend-history

`  "AA": {
    "dividends": [
      {
        "exDate": "2016-11-08",
        "paymentDate": "2016-11-25",
        "recordDate": "2016-11-11",
        "declaredDate": "2016-09-29",
        "amount": 0.09,
        "flag": "",
        "type": "Dividend income",
        "qualified": "Q",
        "indicated": ""
      },
      {
        "exDate": "2016-11-01",
        "paymentDate": "2016-11-01",
        "recordDate": "2016-10-20",
        "declaredDate": "2016-10-13",
        "amount": "",
        "flag": "",
        "type": "Stock dividend",
        "qualified": "",
        "indicated": ""
      }
    ]
  }`

**Comment by evancarter-iex** [comment]
This is fixed in IEX Cloud. If you havent already you can sign up for the beta at: https://iexcloud.io/
