### ISSUE TITLE
Cannot get Forex Data

### ISSUE THREAD

**Issue by Keno2903** [iexg/IEX-API#1730]
https://sandbox.iexapis.com/v1/fx/latest?symbols=USDCAD,USDGBP,USDJPY?token=\(My Sandbox Token)

It only returns : "An API key is required to access this data and no key was provided"

What is to do?

**Comment by timpaine-iex** [comment]
query parameters are ampersand-delimited in HTTP requests.
https://en.wikipedia.org/wiki/Query_string
