### ISSUE TITLE
[Data] ytdChange is equal to changePercent, not year to date

### ISSUE THREAD

**Issue by janvarsa** [iexg/IEX-API#1732]
The quote endpoint no longer reports ytdChange correctly. It is now set equal to the changePercent field. For example:

https://cloud.iexapis.com/stable/stock/market/batch?types=quote&token=mytoken&symbols=AMZN,MSFT

symbol: AMZN
latestTime: July 2, 2021
changePercent: 0.02272
ytdChange: 0.02272

symbol: MSFT
latestTime: July 2, 2021
changePercent: 0.02228
ytdChange: 0.02228

**Comment by mchennupati** [comment]
I see the same issue. The stats endpoint has ytdChangePercent set to 0. Can you please fix it ? 
This is the result of both stats and quote for AAPL.

{"AAPL":{"stats":{"companyName":"Apple Inc","marketcap":2335600834760,"week52high":144.63,"week52low":88.55,"week52highSplitAdjustOnly":145.09,"week52lowSplitAdjustOnly":89.15,"week52change":0,"sharesOutstanding":16687631000,"float":0,"avg10Volume":64272026,"avg30Volume":72985344,"day200MovingAvg":129.14,"day50MovingAvg":129.37,"employees":147000,"ttmEPS":4.44,"ttmDividendRate":0.8329943719548589,"dividendYield":0.005951660274041575,"nextDividendDate":"","exDividendDate":"2021-05-07","nextEarningsDate":"2021-07-27","peRatio":30.606345543368587,"beta":1.5766241427106364,"maxChangePercent":52.71713682594512,"year5ChangePercent":5.308880935423673,"year2ChangePercent":1.7926317301706387,"year1ChangePercent":0.5479167380939478,"**ytdChangePercent":0,**"month6ChangePercent":0.07172912421597832,"month3ChangePercent":0.11356430483783075,"month1ChangePercent":0.11176423862101847,"day30ChangePercent":0.11176423862101847,"day5ChangePercent":0.03843300192906973},"quote":{"symbol":"AAPL","companyName":"Apple Inc","primaryExchange":"NASDAQ/NGS (GLOBAL SELECT MARKET)","calculationPrice":"tops","open":null,"openTime":null,"openSource":"official","close":null,"closeTime":null,"closeSource":"official","high":142.865,"highTime":1625579615400,"highSource":"IEX real time price","low":null,"lowTime":null,"lowSource":null,"latestPrice":142.68,"latestSource":"IEX real time price","latestTime":"10:00:16 AM","latestUpdate":1625580016481,"latestVolume":22787881,"iexRealtimePrice":142.68,"iexRealtimeSize":200,"iexLastUpdated":1625580016481,"delayedPrice":null,"delayedPriceTime":null,"oddLotDelayedPrice":null,"oddLotDelayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":139.96,"previousVolume":78945572,"change":2.72,"**changePercent":0.01943**,"volume":22787881,"iexMarketPercent":0.019979962156200484,"iexVolume":455301,"avgTotalVolume":72985344,"iexBidPrice":142.67,"iexBidSize":100,"iexAskPrice":143,"iexAskSize":210,"iexOpen":142.68,"iexOpenTime":1625580016481,"iexClose":142.68,"iexCloseTime":1625580016481,"marketCap":2380991191080,"peRatio":32.14,"week52High":144.63,"week52Low":88.55,"**ytdChange":0.01943**,"lastTradeTime":1625580016481,"isUSMarketOpen":true}
