### ISSUE TITLE
SWYOX

### ISSUE THREAD

**Issue by provinc1** [iexg/IEX-API#1734]
Can you please add SWYOX - Schwab Target 2065 Index Fund

**Comment by timpaine-iex** [comment]
I dont see any volume on this symbol

**Comment by provinc1** [comment]
I just bought SWYOX yesterday.  Anyway to get at least the current price to populate.

**Comment by McQgit** [comment]
@timpaine-iex This is a mutual fund (type=oef).  You typically show latestPrice, low and highs in the quote endpoint for such funds - including other Schwab funds like SWDSX.  SWYOX inception was Feb 2021 and is very small - with just $6M AUM - if that helps.

**Comment by provinc1** [comment]
Thank you Tim.  My issue is just that the LatestPrice doesn’t come in for SWYOX, but it does for SWYNX.  Not sure why.
