### ISSUE TITLE
[Data] TSXV stocks NLC, PAY

### ISSUE THREAD

**Issue by emanresu25** [iexg/IEX-API#1735]
Could I request support for NLC - Neo Lithium Corporation and PAY - Payfare from the TSXV? Thank you.

**Comment by timpaine-iex** [comment]
I see `NLC-CV` and `PAY-CT` in the data, are you not using their exchange suffixes in your queries?

**Comment by emanresu25** [comment]
No I wasn't, I'm new to the platform. :( Thanks for the help.
