### ISSUE TITLE
HOW TO CODE DEEP AUCTION STREAMING

### ISSUE THREAD

**Issue by raygar18** [iexg/IEX-API#1739]
Can anyone help me to code the open and close deep auction for a stock? I would like to stream the information so it updates consistently.

**Comment by timpaine-iex** [comment]
`curl --header 'Accept: text/event-stream' 'https://cloud-sse.iexapis.com/stable/deep?token=YOUR_TOKEN&symbols=spy&channels=auction'`

its in the docs:
https://iexcloud.io/docs/api/#sse-streaming

**Comment by raygar18** [comment]
for some reason when I use this, I keep getting an error with the --header??

**Comment by timpaine-iex** [comment]
https://stackoverflow.com/help/how-to-ask
https://shannoncrabill.com/blog/asking-for-help-as-a-developer/
