### ISSUE TITLE
[Issue] Sandbox data pulls not working

### ISSUE THREAD

**Issue by shashank17** [iexg/IEX-API#1740]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Email account associated with your IEX Account**
invt@live.in

**Date/time of the issue**
any time

**What you did**
Use python to pull data from sandbox

**What you expected to happen**
to get data but i cannot seem to. Only production token works.

**What actually happened**
error - JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**API Url (if applicable)**
https://sandbox.iexapis.com/v1

**Additional relevant information**

**Comment by timpaine-iex** [comment]
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
