### ISSUE TITLE
[Data] Extended hours response attributes for NYSE listed symbols are null. 

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1741]
On Grow plan and trying to get extended hours data for NYSE listed stocks but extendedPrice, extendedChange, extendedChangePercent and extendedPriceTime are returning null in after hours trading at 3:46 PM PDT.

Please correct me if I am wrong but my understanding from endpoint docs is for Nasdaq listed securities, one must complete a vendor agreement to receive such extended hours data but for NYSE listed securities one only needs to be a paid user, which my account is.

Example endpoint URL and response below.

https://cloud.iexapis.com/v1/stock/market/batch?symbols=GME,SPY,AMC,BAC&types=quote&token=

![image](https://user-images.githubusercontent.com/8920632/127239583-2ae8d96b-022f-4657-ae82-a2ecc1e4a66a.png)

![image](https://user-images.githubusercontent.com/8920632/127239554-4647bcfd-276a-407a-9160-575bc1196e37.png)

![image](https://user-images.githubusercontent.com/8920632/127239527-4b4ee856-7474-4c8c-890d-61495e3c3b87.png)

![image](https://user-images.githubusercontent.com/8920632/127239482-7cfd7e3c-2db8-43e5-8f95-22d58662e137.png)

**Comment by timkpaine** [comment]
@MorningSleeper Should be better now.

**Comment by MorningSleeper** [comment]
> @MorningSleeper Should be better now.

Indeed, thank you.
