### ISSUE TITLE
[Data] Date incorrectly scrambled in Sandbox environment

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#1742]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Email account associated with your IEX Account**

**Date/time of the issue**

31.07.2021 9:08 PM CEST

**What you did**

There is an issue with data obfuscation in sandbox environment happening now with AAPL dividends endpoint. 

Production environment
```
"declaredDate": "0000-00-00",
```

Sandbox environment
```
"declaredDate": "000--00000",
```

**What you expected to happen**

I expected to receive correctly formatted date

**What actually happened**

Endpoint returns not correctly formatted date

```
"declaredDate": "000--00000",
```

**API Url (if applicable)**

https://sandbox.iexapis.com/v1/stock/AAPL/dividends/next?token=Tpk_18dfe6cebb4f41ffb219b9680f9acaf2

**Additional relevant information**

**Comment by timpaine-iex** [comment]
This field has to be obfuscated in some form, what would your preferred mechanism be? I can pick a random date at some point in the future and make it correctly format if that would be helpful

**Comment by WojciechZankowski** [comment]
> This field has to be obfuscated in some form, what would your preferred mechanism be? I can pick a random date at some point in the future and make it correctly format if that would be helpful

To put any random date that is in the correct format. Otherwise it is failing parsing mechanism in some clients that are expecting yyyy-MM-dd.

**Comment by timpaine-iex** [comment]
aight looks like we already randomly offset dates except for `0000-00-00`, since `0000-00-00` doesn't convey any additional info I'll just have it return as-is
