### ISSUE TITLE
[Data] Options data v2 Batch requests do not work

### ISSUE THREAD

**Issue by xunamcapital** [iexg/IEX-API#1743]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Email account associated with your IEX Account**
roman@xunam.com

**Date/time of the issue**
any time

**What you did**
https://cloud.iexapis.com/stable/options/KO20210820C00051500,KO20210820C00050000/chart?token=pk_...
or
https://cloud.iexapis.com/stable/options/market/chart?symbols=KO20210820C00051500,KO20210820C00050000&token=pk_....
**What you expected to happen**
An array of multiple symbols. One of the above ways works with all your other APIs, including Options V1 but not for Options V2 (where it is even more important due to the number of symbols)

**What actually happened**
Api does not work for multiple symbols

**API Url (if applicable)**
https://cloud.iexapis.com/stable/options/{OptionSymbol}/chart

**Additional relevant information**
In the options V1 Api we are able to query multiple symbols per request, which is paramount when keeping in mind your request limitations of **1 request per 10 milliseconds**. This functionality does not seem to work with the options V2 that we have to move to. (related issue: https://github.com/iexg/IEX-API/issues/1738 )

Thank you!

**Comment by Spencer-Villarreal** [comment]
I am having the same issue and also having an issue getting the current price of the contract. Instead, I am getting the price from a month ago. This new endpoint seems worse than the original endpoint, I wish they weren't getting rid of it in December 2021.

**Comment by timpaine-iex** [comment]
This will utilize the forthcoming multi-key/multi-subkey support for time-series rather than batch, it will be publicly announced and available in the docs.
