### ISSUE TITLE
Stale data

### ISSUE THREAD

**Issue by mfeenstra** [iexg/IEX-API#1745]
Hello,
I am observing most data from the v1/stock/...../chart/5d endpoint is stuck on last Thursday (today is Saturday, no holidays).  Please see the details in the below attachments.  Is there is a different endpoint I should be using?  Thanks in advance!

--Matt

![iex_api1](https://user-images.githubusercontent.com/3183029/129465418-a540dd6c-a095-46af-a09f-92b2ceb49daa.jpg)
![iex_api2](https://user-images.githubusercontent.com/3183029/129465421-d54eec5b-81d5-4612-bcf9-0bfc417c38a0.jpg)

**Comment by timpaine-iex** [comment]
Looks ok now.

**Comment by mfeenstra** [comment]
Thank you @timpaine-iex  !
