### ISSUE TITLE
Quotes from OTC markets?

### ISSUE THREAD

**Issue by TanerH** [iexg/IEX-API#175]
Feature Request - 
Are there any plans to add quote support for OTC markets?

(In a quick search of feature requests, I didn't see this asked, but may have missed it)

**Comment by evancarter-iex** [comment]
https://github.com/iexg/IEX-API/issues/63

**Comment by TanerH** [comment]
Ahh, I had only checked for "Feature Request" tags, and not "enhancement" -- sorry! :)

**Comment by evancarter-iex** [comment]
No worries, thanks for using the API.
