### ISSUE TITLE
[Data] Question about price of Nasdaq listed stocks

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1752]
If a paid customer has no UTP plan agreement, uses the quote endpoint for a Nasdaq listed stock during normal trading hours and it has not been traded on IEX in last 15 minutes, is the `latestPrice` response attribute supposed to return the price last traded on IEX during the current normal trading session older than 15 minutes if it exists or does it go straight to the last days open?

If it is supposed to return the price last traded on IEX during the current normal trading session older than 15 minutes and such exists what would the value of the `latestSource` response attribute be?  "15 minute delayed price"?

**Comment by timpaine-iex** [comment]
If a trade on IEX within the last 15 minutes, then IEX, otherwise last overall trade based on SIP, otherwise yesterday.

Yes should be "15 Minute delayed price".

**Comment by MorningSleeper** [comment]
I thought without a UTP plan agreement, in the example I provided for a Nasdaq stock, if no trade on IEX within last 15 minutes, it would never be from SIP so always be yesterday's close and thus the value of `latesSource` would be Previous close or am I misunderstanding.

**Comment by timpaine-iex** [comment]
whatever it says here is how it works
https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud

**Comment by MorningSleeper** [comment]
Thanks, I did read that before posting, I reason I was seeking clarification is the relevant excerpt from that page below makes no distinction between the price source whether a trade last occurred within 15 minutes or earlier in the trading day, just that the price returned is the "latest trade seen on Investors Exchange" so I was just wanting to make sure that if no trade within last 15 minutes and no UTP agreement, it still uses whatever price was last seen on Investors Exchange during that day, if any, which it sounds like it does and only if no trade has occurred on Investors Exchange during the day that it would use yesterday's close. 

"... if you don’t have UTP authorization, IEX Cloud will automatically use the latest trade seen on Investors Exchange to populate the Quote fields latestPrice"

**Comment by timpaine-iex** [comment]
That all sounds right
