### ISSUE TITLE
End of Day Options V2 Not Updating

### ISSUE THREAD

**Issue by Spencer-Villarreal** [iexg/IEX-API#1756]
Hello,

I am migrating from using the old options API that will be deprecated in December 2021 and I have noticed that the new API is actually not that much better.

I now have to download every single option in the book just to get the dates then I have to make another API call to get the open/close of the specific option contract.

And then when I get the option contract data, it is a month old. I have tried numerous ways to set the range to 1d, Today, Yesterday.

I hope that I am doing it wrong because if the options don't update daily then this newly updated end point is useless for analysis.

I am using "https://cloud.iexapis.com/stable/options/AMC20211217P00050000/chart?range=1d&token=xxxxxxxxxxxxxxxxxxx"

I feel that you should not deprecate the old endpoint until everything is figured out with the new endpoint.

**Comment by timpaine-iex** [comment]
The new endpoint is more in line with how the rest of the endpoints work. The refdata endpoint will let you subselect down by underlying and date, e.g. `ref-data/options/symbols` gives you the same underlying to expiration mapping as before, `ref-data/options/SPY/symbols` gives you all spy options, `ref-data/options/SPY/symbols/EXPIRATION_DATE` will give you the chain for a single date.

Then you can hit time-series or the options chart endpoint to fetch just the data you need at `10` per record, vs the stock endpoint which only gives you last record for each option at `1000` cost, so you should come out ahead most of the time. This also has the benefit of aligning exactly with stocks endpoints (fetch refdata to get symbols, hit stock endpoints with symbol to get data), futures endpoints, etc. And if we add e.g. options or futures quotes or other similar datasets, you will have a nice symmetric API across all asset classes (`/stock/SPY/quote` vs `/options/SPY2021.../quote` vs `/futures/ES1Z/quote` vs ...). 

You should be able to pass multiple symbols in to time-series endpoints in the coming weeks (which will replace `batch` and should let you grab multiple options in one go). 

Also all options data is affected by an issue with the upstream provider, I believe all data stops at 10/08 and there are gaps from then back into September. It's being looked into, you can ping support to refund credits you used for this in the mean time.

**Comment by Spencer-Villarreal** [comment]
> The new endpoint is more in line with how the rest of the endpoints work. The refdata endpoint will let you subselect down by underlying and date, e.g. `ref-data/options/symbols` gives you the same underlying to expiration mapping as before, `ref-data/options/SPY/symbols` gives you all spy options, `ref-data/options/SPY/symbols/EXPIRATION_DATE` will give you the chain for a single date.
> 
> Then you can hit time-series or the options chart endpoint to fetch just the data you need at `10` per record, vs the stock endpoint which only gives you last record for each option at `1000` cost, so you should come out ahead most of the time. This also has the benefit of aligning exactly with stocks endpoints (fetch refdata to get symbols, hit stock endpoints with symbol to get data), futures endpoints, etc. And if we add e.g. options or futures quotes or other similar datasets, you will have a nice symmetric API across all asset classes (`/stock/SPY/quote` vs `/options/SPY2021.../quote` vs `/futures/ES1Z/quote` vs ...).
> 
> You should be able to pass multiple symbols in to time-series endpoints in the coming weeks (which will replace `batch` and should let you grab multiple options in one go).
> 
> Also all options data is affected by an issue with the upstream provider, I believe all data stops at 10/08 and there are gaps from then back into September. It's being looked into, you can ping support to refund credits you used for this in the mean time.

I can somewhat see what you are saying, I still do not understand how to get the current price of the option. I have the contract symbols but I am still lost as to why when I use the link that I provided above, it tells me the contract was updated Oct 11.
