### ISSUE TITLE
Return on Capital field always seems to bring back null

### ISSUE THREAD

**Issue by kotarofujita** [iexg/IEX-API#176]
## Summary
I notice when I look at any stock stats, I never see any values for "Return on Capital" field (returnOnCapital). Not sure if its something I'm not suppose to have values for or if the data is suppose to be there.

https://api.iextrading.com/1.0/stock/m/stats

Just wanted to bring it up just in case.
### API URL

Examples:
https://api.iextrading.com/1.0/stock/m/stats
https://api.iextrading.com/1.0/stock/aapl/stats
https://api.iextrading.com/1.0/stock/amzn/stats

### What you expected to happen

Maybe see a value in at least one stock.

### What actually happened

I only ever see NULL for that field.

**Comment by exiao** [comment]
I also would like to explore this request. returnOnCapital does not have any values for any stocks.

**Comment by evancarter-iex** [comment]
Please see issue https://github.com/iexg/IEX-API/issues/557 for updates on this and other data issues.

**Comment by evancarter-iex** [comment]
Closing. This is fixed in IexCloud https://iexcloud.io
