### ISSUE TITLE
no way to get 5 or 15-minute chart increments in one call

### ISSUE THREAD

**Issue by mysteryleo** [iexg/IEX-API#179]
## Summary
I want to generate a 15-minute chart like:
http://bigcharts.marketwatch.com/quickchart/quickchart.asp?symb=aapl&insttype=&freq=7&show=&time=18

or maybe a 10 day chart with 5-minute fidelity, but i can only generate either 1 minute charts for a day, or daily charts for a month :(

**Comment by joshuablackburn-iex** [comment]
Current chart ranges can now use a parameter called chartIncrement.  It takes an integer such as 5 or 15.  Chart data will return every nth element.

We've also added a parameter called chartSimplify.  If set to true it will simplify the number of points using Douglas-Peucker algo.

**Comment by joshuablackburn-iex** [comment]
Please note that using chartSimplify will result in the first element of the returned array having an additional key called simplifyFactor.  This is an array of two elements.  Original length of data and simplified length.
