### ISSUE TITLE
need urgent  help replacing my  yahoo finance api i tried alphavanatge but no luck can anyone help 

### ISSUE THREAD

**Issue by ceoboss** [iexg/IEX-API#181]
## Summary

hey i need help replacing my yahoo api i need to pull stock market data for cannabis only this time though below is my api controller can any help me out please i tried useing alphavantage but no luck 

### Date/time of issue

hey i need help replacing my api i need to pull stock market data for cannabis only

### What you expected to happen

i require help if its possible please 

### What actually happened

your support would be awsome  

### Other Information (sample code, links, etc.)
**below is my Api controller** 

class ApiController extends Controller {

  const HISTORY_START = '2011-01-01';
  const LIVE_QUOTES_SOURCE = 'https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES&series_type&symbols=MSFT,FB,AAPL,TWTR,ABBV&apikey=ALH5JDX3RE0FVG6Y&datatype=csv';
  const YQL_ENDPOINT = 'https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES&series_type&symbols=MSFT,FB,AAPL,TWTR,ABBV&"%s" and startDate = "%s" and endDate = "%s"&apikey=ALH5JDX3RE0FVG6Y&datatype=csv';
  const HISORICAL_QUOTES_QUERY = 'select Date, Adj_Close, Volume from alphavantage.co/query?function=BATCH_STOCK_QUOTES&series_type& where symbol = "%s" and startDate = "%s" and endDate = "%s"';
  private $latest_quote = array('l1','c4');

  private $attributes_mapping = array(
    'a' => array('name'=>'Ask'),
    'a2' => array('name'=>'Average Daily Volume'),
    'a5' => array('name'=>'Ask Size'),
    'b' => array('name'=>'Bid'),
    'b2' => array('name'=>'Ask (Realtime)'),
    'b3' => array('name'=>'Bid (Realtime)'),
    'b4' => array('name'=>'Book Value'),
    'b6' => array('name'=>'Bid Size Misc'),
    'c' => array('name'=>'Change & Percent Change'),
    'c1' => array('name'=>'Change'),
    'c3' => array('name'=>'Commission'),
    'c4' => array('name'=>'Currency'),
    'c6' => array('name'=>'Change (Realtime)'),
    'c8' => array('name'=>'After Hours Change (Realtime)'),
    'd' => array('name'=>'Dividend per Share'),
    'd1' => array('name'=>'Last Trade Date'),
    'd2' => array('name'=>'Trade Date'),
    'e' => array('name'=>'Earnings per Share'),
    'e1' => array('name'=>'Error Indication'),
    'e7' => array('name'=>'EPS Estimate Current Year'),
    'e8' => array('name'=>'EPS Estimate Next Year'),
    'e9' => array('name'=>'EPS Estimate Next Quarter'),
    'f0' => array('name'=>'Trade Links Additional'),
    'f6' => array('name'=>'Float Shares'),
    'g' => array('name'=>'Day\'s Low'),
    'g1' => array('name'=>'Holdings Gain Percent'),
    'g3' => array('name'=>'Annualized Gain'),
    'g4' => array('name'=>'Holdings Gain'),
    'g5' => array('name'=>'Holdings Gain Percent (Realtime)'),
    'g6' => array('name'=>'Holdings Gain (Realtime)'),
    'h' => array('name'=>'Day\'s High'),
    'i' => array('name'=>'More Info'),
    'i5' => array('name'=>'Order Book (Realtime)'),
    'j' => array('name'=>'52 week Low'),
    'j1' => array('name'=>'Market Capitalization'),
    'j2' => array('name'=>'Shares Outstanding'),
    'j3' => array('name'=>'Market Cap (Realtime)'),
    'j4' => array('name'=>'EBITDA'),
    'j5' => array('name'=>'Change From 52 Week Low'),
    'j6' => array('name'=>'Percent Change From 52 week Low'),
    'k' => array('name'=>'52 Week High'),
    'k1' => array('name'=>'Last Trade (Realtime) With Time'),
    'k2' => array('name'=>'Change Percent (Realtime)'),
    'k3' => array('name'=>'Last Trade Size'),
    'k4' => array('name'=>'Change From 52 week High'),
    'k5' => array('name'=>'Percent Change From 52 week High'),
    'l' => array('name'=>'Last Trade Date & Time'),
    'l1' => array('name'=>'Last Trade Price'),
    'l2' => array('name'=>'High Limit'),
    'l3' => array('name'=>'Low Limit'),
    'm' => array('name'=>'Day\’s Range'),
    'm2' => array('name'=>'Day\’s Range (Realtime)'),
    'm3' => array('name'=>'50 Day Moving Average'),
    'm4' => array('name'=>'200 Day Moving Average'),
    'm5' => array('name'=>'Change From 200 Day Moving Average'),
    'm6' => array('name'=>'Percent Change From 200 Day Moving Average'),
    'm7' => array('name'=>'Change From 50 Day Moving Average'),
    'm8' => array('name'=>'Percent Change From 50 Day Moving Average'),
    'n' => array('name'=>'Name', 'format_callback'=>'Helper::cleanString'),
    'n4' => array('name'=>'Notes'),
    'o' => array('name'=>'Open'),
    'p' => array('name'=>'Previous Close'),
    'p1' => array('name'=>'Price Paid'),
    'p2' => array('name'=>'Change (%)'),
    'p5' => array('name'=>'Price / Sales'),
    'p6' => array('name'=>'Price / Book'),
    'q' => array('name'=>'Ex-Dividend Date'),
    'r' => array('name'=>'P/E Ratio'),
    'r1' => array('name'=>'Dividend Pay Date'),
    'r2' => array('name'=>'P/E Ratio (Realtime)'),
    'r5' => array('name'=>'PEG Ratio'),
    'r6' => array('name'=>'Price / EPS Estimate Current Year'),
    'r7' => array('name'=>'Price / EPS Estimate Next Year'),
    's' => array('name'=>'Symbol'),
    's1' => array('name'=>'Shares Owned'),
    's6' => array('name'=>'Revenue'),
    's7' => array('name'=>'Short Ratio'),
    't1' => array('name'=>'Last Trade Time'),
    't6' => array('name'=>'Trade Links'),
    't7' => array('name'=>'Ticker Trend'),
    't8' => array('name'=>'1 year Target Price'),
    'v' => array('name'=>'Volume'),
    'v1' => array('name'=>'Holdings Value'),
    'v7' => array('name'=>'Holdings Value (Realtime)'),
    'w' => array('name'=>'52 week Range'),
    'w1' => array('name'=>'Day\'s Value Change'),
    'w4' => array('name'=>'Day\'s Value Change (Realtime)'),
    'x' => array('name'=>'Stock Exchange'),
    'y' => array('name'=>'Dividend Yield'),
  );

  protected $templates_directory = 'auth';

  function beforeroute($f3, $params) {
    // call Controller::beforeroute()
    parent::beforeroute($f3, $params);
    parent::checkSubscription();
  }

  /**
   * Symbol search autocomplete
   * @param $f3
   * @param $params
   */
  function apiSearchAsset($f3, $params) {
    $search_string = $this->f3->get('PARAMS.search');
    print json_encode(['results' => (new ApiModel())->searchAsset($search_string, $this->f3->get('USER')->id)], JSON_NUMERIC_CHECK);
  }

  /**
   * User search autocomplete
   * @param $f3
   * @param $params
   */
  function apiSearchUser($f3, $params) {
    $search_string = $this->f3->get('PARAMS.search');
    print json_encode(['results' => (new ApiModel())->searchUser($search_string)], JSON_NUMERIC_CHECK);
  }

  /**
   * Retrieve market data
   * @param $f3
   * @param $params
   */
  function apiGetQuotes($f3, $params) {
    if (($symbols = $this->f3->get('GET.symbols')) && ($fields = $this->f3->get('GET.fields'))) {
      $fields = explode(',', $fields); // transform to an array
      $checkTradingEnabledSymbols = $this->f3->get('GET.check') ? explode(',', $this->f3->get('GET.check')) : [];
      if ($quote = $this->getYahooFinanceCsvData($symbols, $fields, $checkTradingEnabledSymbols)) {
        print json_encode($quote, JSON_NUMERIC_CHECK);
      }
    }
  }

  /**
   * Add or remove symbols to/from user watchlist
   * @param $f3
   * @param $params
   */
  function apiChangeWatchlist($f3, $params) {
    if ($symbol = $this->f3->get('PARAMS.symbol')) {
      $action = $this->f3->get('PARAMS.action');
      $watchlist = new WatchlistModel($this->f3->get('USER')->id);
      $count = 0;
      if ($action == 'add') {
        $count = $watchlist->addSymbol($symbol);
      } elseif ($action == 'remove') {
        $count = $watchlist->removeSymbol($symbol);
      }
      print $count>0 ? json_encode(array('success' => TRUE)) : json_encode(array('success' => FALSE));
    }
  }

  /**
   * Store current symbol in user session
   * @param $f3
   * @param $params
   */
  function apiSetActiveSymbol($f3, $params) {
    if ($symbol = $this->f3->get('PARAMS.symbol')) {
      $this->f3->set('SESSION.symbol', $symbol);
    }
  }

  function apiTrade($f3, $params) {
    $success = FALSE;
    $message = '';

    if (($symbol = $this->f3->get('POST.symbol')) && ($quantity = abs(intval($this->f3->get('POST.quantity')))) && ($action = $this->f3->get('POST.action'))) {
      Logger::log(sprintf('New trade: %s %d %s', $action, $quantity, $symbol));
      // get user from passed user id if trading on behalf of other user (admin feature)
      $user = $this->f3->get('USER')->is_admin && $this->f3->get('POST.user')>0 ? (new UserModel())->getById(intval($this->f3->get('POST.user'))) : $this->f3->get('USER');

      if ($asset = (new AssetModel())->get($symbol)) {
        $accountCurrency = $user->currency;
        // when asset currency and user account currency are different we need to retrieve FX rate
        if ($asset->currency != $accountCurrency) {
          // When translating from USD to other currencies we use a shortcut, like EUR=X (USD/EUR), GBP=X (USD/GBP)
          // in other cases we use normal pair like EURUSD=X (EUR/USD), GBPUSD=X (GBP/USD)
          $fxSymbol = $asset->currency=='USD' ? $accountCurrency.'=X' : $asset->currency.$accountCurrency.'=X';
        }

        // Retrieve latest market data. When currencies are different we also retrieve FX rate to convert from asset currency to balance currency
        if ($quote = $this->getYahooFinanceCsvData(isset($fxSymbol)?$symbol.','.$fxSymbol:$symbol, $this->latest_quote)) {
          $direction = $action == 'buy' ? 1 : -1;
          $position = (new PositionModel($user->id))->get($symbol);
          $currentQuantity = isset($position['quantity']) ? $position['quantity'] : 0;
          $currentHistoricalCost = isset($position['historical_cost']) ? $position['historical_cost'] : 0;
          $shortSaleQuantity = $direction == -1 ? ($currentQuantity>0 ? abs(min(0,$currentQuantity-$quantity)) : $quantity) : 0; // need to take into account current long position in this asset
          $lastPrice = isset($quote[$symbol]['l1']) ? floatval($quote[$symbol]['l1']) : 0;
          $nominal = $asset->nominal;
          $fxRate = isset($fxSymbol) && isset($quote[$fxSymbol]['l1']) ? floatval($quote[$fxSymbol]['l1']) : 1;
          $commission = floatval($this->f3->get('TRADE.COMMISSION'));
          $tradeAmount = round($lastPrice * $nominal * $quantity * $direction * $fxRate, 2);
          $shortSaleTradeAmount = $shortSaleQuantity ? round($lastPrice * $nominal * $shortSaleQuantity * $direction * $fxRate, 2) : 0;
          $currentBalance = $user->balance;
          $newBalance = $currentBalance - $tradeAmount - $commission;

          // Calculate historical cost
          //http://quant.stackexchange.com/questions/9002/calculate-average-price-cost-unrealized-pl-of-a-position-based-on-executed/9037#9037
          if ($currentQuantity != 0) {
            $closingQty = Helper::sign($currentQuantity) != $direction ? min(abs($currentQuantity), $quantity) * $direction : 0;
            $openingQty = Helper::sign($currentQuantity) == $direction ? $quantity * $direction : $quantity * $direction - $closingQty;
            $newHistoricalCost = $currentHistoricalCost + $openingQty * $lastPrice * $nominal * $fxRate + $closingQty * $currentHistoricalCost / $currentQuantity + $commission;
          } else {
            $newHistoricalCost = $tradeAmount + $commission;
          }

          Logger::log(sprintf('Qty: %d, Price: %f %s (%f), FX: %f, Com: %f, Amount: %f, Prev Balance: %f, New Balance: %f, New Hist Cost: %f', $quantity * $direction, $lastPrice, $asset->currency, $nominal, $fxRate, $commission, abs($tradeAmount), $currentBalance, $newBalance, $newHistoricalCost));
          if ($quantity == 0) {
            $message = $this->f3->get('trade.form.error1');
          } elseif ($lastPrice==0) {
            $message = $this->f3->get('trade.form.error2');
          } elseif (isset($fxSymbol) && $fxRate==1) {
            $message = $this->f3->get('trade.form.error3', [$asset->currency, $accountCurrency]);
          } elseif (!(new MarketModel())->isOpen($symbol)) {
            $message = $this->f3->get('trade.form.error4');
          } elseif ($newBalance < 0) {
            $message = $this->f3->get('trade.form.error5');
          // do not allow short sales if it's disabled
          } elseif ($shortSaleQuantity > 0 && $this->f3->get('TRADE.SHORT_TRADING')==0) {
            $message = $this->f3->get('trade.form.error10');
          // if selling short and trade amount is greater than current balance
          } elseif ($shortSaleQuantity > 0 && $shortSaleTradeAmount > $currentBalance) {
            $message = $this->f3->get('trade.form.error6');
          } elseif ($tradeId = (new TradeModel($user->id))->create($symbol, $quantity * $direction, $lastPrice, $fxRate, $commission, abs($tradeAmount), $newBalance, $newHistoricalCost)) {
            $success = TRUE;
            $currentBalance = $newBalance;
            $message = sprintf($this->f3->get('trade.form.trade.success.message',
              [
                ($direction == 1 ? $this->f3->get('trade.form.trade.success.action.buy') : $this->f3->get('trade.form.trade.success.action.sell')),
                $quantity,
                ($quantity > 1 ? $this->f3->get('trade.form.trade.success.shares') : $this->f3->get('trade.form.trade.success.share')),
                $symbol,
                Helper::formatNumber($lastPrice, 2),
                $asset->currency,
                (isset($fxSymbol)?' ('.str_replace('=X','',$fxSymbol).' '.$this->f3->get('trade.form.trade.success.fxrate').' '.round($fxRate,4).')':''),
                Helper::formatNumber(abs($tradeAmount), 2),
                $accountCurrency,
                Helper::formatNumber($commission, 2),
                $accountCurrency
              ])
            );
          } else {
            $message = $this->f3->get('trade.form.error7');
          }
        } else {
          $message = $this->f3->get('trade.form.error8');
        }
      } else {
        $message = $this->f3->get('trade.form.error9');
      }
    }
    Logger::log($message);
    print json_encode(array('success' => $success, 'message' => $message, 'balance' => $currentBalance), JSON_NUMERIC_CHECK);
  }

  /**
   * Get trades history for current or given user
   * @param $f3
   * @param $params
   */
  function apiGetTradesHistory($f3, $params) {
    // check if user id is passed to filter by user (only for admin)
    $userId = isset($params['user_id']) && $this->f3->get('USER')->is_admin ? intval($params['user_id']) : $this->f3->get('USER')->id;
    $tradeModel = new TradeModel($userId);
    $trades = $tradeModel->getAll();
    print json_encode($trades, JSON_NUMERIC_CHECK);
  }

  /**
   * Get positions for current or given user
   * @param $f3
   * @param $params
   */
  function apiGetPositions($f3, $params) {
    // check if user id is passed to filter by user (only for admin)
    $userId = isset($params['user_id']) && $this->f3->get('USER')->is_admin ? intval($params['user_id']) : $this->f3->get('USER')->id;
    $positionModel = new PositionModel($userId);
    $positions = $positionModel->getList();
    print json_encode($positions, JSON_NUMERIC_CHECK);
  }

  /**
   * Add/modify users
   * @param $f3
   * @param $params
   */
  function apiModifyUsers($f3, $params) {
    // check that current user is admin
    if ($this->f3->get('USER')->is_admin) {
      $action = $this->f3->get('PARAMS.action');
      // Add new users
      if ($action == 'add') {
        $firstName = $f3->get('POST.first_name');
        $lastName = $f3->get('POST.last_name');
        $email = $f3->get('POST.email');
        $phone = $f3->get('POST.phone');
        $newBalance = $f3->get('POST.balance');
        $accountNumber = $f3->get('POST.account_number');
        $isAdmin = $f3->get('POST.admin') == 'on' ? 1 : 0;
        $sendWelcomeEmail = $f3->get('POST.welcome_email');

        $user = new UserModel();
        $user->getByEmail($email);

        if (!$user->dry()) {
          print json_encode([
            'success' => FALSE,
            'message' => $this->f3->get('users.add.error.user_exists')
          ]);
          exit;
        }

        $token = LoginController::generateToken();

        if ($user->add([
            'first_name' => $firstName,
            'last_name' => $lastName,
            'email' => $email,
            'phone' => $phone,
            'balance' => $newBalance,
            'currency' => $this->f3->get('TRADE.ACCOUNT_CURRENCY'),
            'password' => password_hash($token, PASSWORD_BCRYPT),
            'timezone' => $this->f3->get('SITE.TIMEZONE'),
            'language' => $this->f3->get('SITE.LANGUAGE'),
            'is_admin' => $isAdmin,
            'created' => Helper::timeStamp(),
            'account_number' => $accountNumber
          ])) {
          Logger::log(sprintf('User %d (%s) created by admin', $user->id, $email));
          // create a link for password reset
          $password_reset = new PasswordResetModel();
          $password_reset->add($user->id, $token);
          // add default watchlist symbols
          $watchlist = new WatchlistModel($user->id);
          $watchlist->addSymbols($this->f3->get('MARKETS.DEFAULT_WATCHLIST'));
          // send welcome email
          if ($sendWelcomeEmail) {
            $f3->set('vars.first_name', $firstName);
            $f3->set('vars.password_reset_url', Helper::baseUrl() . 'password-reset/' . $user->id . '/' . $token);
            $email = new Email($email, $this->f3->get('email.signup.subject', $f3->get('website.title')), 'email/signup.php');
          }
          print json_encode([
            'success' => TRUE,
            'message' => $this->f3->get('users.add.success')
          ]);
        } else {
          print json_encode([
            'success' => FALSE,
            'message' => $this->f3->get('users.add.general_error')
          ]);
        }
      } elseif ($action == 'edit') {
        $id = $f3->get('POST.id');
        $firstName = $f3->get('POST.first_name');
        $lastName = $f3->get('POST.last_name');
        $email = $f3->get('POST.email');
        $phone = $f3->get('POST.phone');
        $password = $f3->get('POST.password');
        $blocked = $f3->get('POST.blocked')=='on' ? 1 : 0;

        $user = new UserModel();
        $user->getById($id);

        // check if correct ID passed
        if ($user->dry()) {
          print json_encode([
            'success' => FALSE,
            'message' => $this->f3->get('users.edit.error.general_error')
          ]);
          exit;
        }

        // if email is updated check if it's unique
        if ($user->email != $email) {
          $userEmailCheck = new UserModel();
          $userEmailCheck->getByEmail($email);
          if (!$userEmailCheck->dry()) {
            print json_encode([
              'success' => FALSE,
              'message' => $this->f3->get('users.edit.error.dup_email')
            ]);
            exit;
          }
        }

        Logger::log(sprintf('Edit user details, name: %s, email: %s, blocked: %s', $firstName.' '.$lastName, $email, $blocked));
        $user->edit([
          'first_name' => $firstName,
          'last_name' => $lastName,
          'email' => $email,
          'phone' => $phone,
          'password' => ($password ? password_hash($password, PASSWORD_BCRYPT) : $user->password),
          'blocked' => $blocked
        ]);

        print json_encode([
          'success' => TRUE,
          'message' => $this->f3->get('users.edit.success')
        ]);

      // Add/remove funds
      } elseif ($action == 'funds') {
        $id = $f3->get('POST.id');
        $amount = floatval($f3->get('POST.amount'));
        $user = new UserModel();
        $user->getById($id);

        if (!$user->dry() && $amount!=0) {
          Logger::log(sprintf('Add/remove funds, amount: %f, current balance: %f', $amount, $user->balance));
          $tradeId = $this->cashTransaction($amount, $user);
        }

        if (isset($tradeId) && $tradeId>0) {
          print json_encode([
            'success' => TRUE,
            'message' => $this->f3->get('users.funds.success')
          ]);
        } else {
          print json_encode([
            'success' => FALSE,
            'message' => $this->f3->get('users.funds.general_error')
          ]);
        }
      }
    // if not admin just return negative status
    } else {
      print json_encode([
        'success' => FALSE
      ]);
    }
  }

  /**
   * Get balance change history for chart
   * @param $f3
   * @param $params
   */
  function apiGetBalanceHistory($f3, $params) {
    $result = [];
    // initial balance
    $result[] = [
      'date' => $this->f3->get('USER')->created,
      'action' => '',
      'balance' => $this->f3->get('TRADE.INITIAL_BALANCE')
    ];
    $tradeModel = new TradeModel($this->f3->get('USER')->id);
    foreach($tradeModel->getBalanceHistory() as $trade) {
      $result[] = [
        'date' => $trade['created'],
        'action' => ($trade['symbol']!='%CASH%' ? ($trade['quantity']>0 ? $this->f3->get('portfolio.balance.buy') : $this->f3->get('portfolio.balance.sell')).' '.abs($trade['quantity']).' '.$trade['symbol'].' '.$this->f3->get('portfolio.balance.actionat').' '.Helper::formatNumber($trade['price'],2).' '.$trade['currency'] : Helper::formatNumber($trade['total'],2).' '.($trade['quantity']>0 ? $this->f3->get('portfolio.balance.cash_removed') : $this->f3->get('portfolio.balance.cash_added'))),
        'balance' => $trade['balance']
      ];
    };
    print json_encode($result, JSON_NUMERIC_CHECK);
  }

  /**
   * Retrieve historical data for chart
   * @param $f3
   * @param $params
   */
  function apiGetHistoricalData($f3, $params) {
    if ($symbol = $this->f3->get('PARAMS.symbol')) {
      $data_file = $symbol.'.json';
      $db = new DB\Jig('app/data/');
      if ($saved_data = $db->read($data_file)) {
        $start_date = strtotime('+1 Day', $saved_data[count($saved_data)-1]['date']/1000);
      } else {
        $start_date = strtotime(self::HISTORY_START);
      }
      $retrieved_data = $this->getHistoricalQuotes($symbol, $start_date, time());
      $historical_data = array_merge($saved_data, $retrieved_data);
      // if new data received save all to history file
      if (!empty($retrieved_data)) {
        $db->write($data_file, $historical_data);
      }
      print json_encode($historical_data, JSON_NUMERIC_CHECK);
    }
  }

  /**
   * Retrieve given fields data from Yahoo CSV data service
   * @param $symbols - comma delimited list of symbols
   * @param array $fields
   * @param array $checkTradingEnabledSymbols - a list of symbols to check whether they are allowed to be traded
   * @return array, e.g. [0] => array('Last Price' => 12.33, 'Name' => 'Apple', ...)
   */
  private function getYahooFinanceCsvData($symbols, array $fields, array $checkTradingEnabledSymbols = array()) {
    $result = array();
    // if symbol is not the first requested field, make it the first
    if ($fields[0]!='s') {
      $fields = array_filter($fields, function ($item) {
        return $item != 's' ? TRUE : FALSE;
      });
      array_unshift($fields, 's');
    }

    if ($symbols && $data = Helper::getRemoteData(sprintf(self::LIVE_QUOTES_SOURCE, $symbols, implode('',$fields)))) {
      foreach (explode("\n",$data) as $csvString) {
        if (trim($csvString) != '') {
          $csvFields = str_getcsv($csvString);
          $symbol = $csvFields[0];
          // make an array of values indexed by symbol
          for ($i=1; $i<count($csvFields); $i++) {
            $field = $this->attributes_mapping[$fields[$i]];
            // Getting stock name from the database, rather than from API, because sometimes they don't provide names at all
            if ($fields[$i]=='n' && substr($symbol,0,1)!='^') {
              $asset = (new AssetModel())->get($symbol);
              $value = $asset->name;
            // other fields retrieve from CSV
            } else {
              $value = isset($field['format_callback']) ?
                call_user_func_array($field['format_callback'], (isset($field['callback_args']) ? array_merge(array($csvFields[$i]), $field['callback_args']) : array($csvFields[$i]))) :
                $csvFields[$i];
            }
            $result[$symbol][$fields[$i]] = $value;
          }
          if (in_array($symbol, $checkTradingEnabledSymbols)) {
            $result[$symbol]['tradingEnabled'] = isset($result[$symbol]['l1']) && floatval($result[$symbol]['l1'])>0 && (new MarketModel())->isOpen($symbol);
          }
        }
      }
    }
    return $result;
  }

  /**
   * Perform YQL query and return result
   * @param $query
   * @param $key
   * @return null
   */
  private function yqlQuery($query, $key) {
    $url = sprintf(self::YQL_ENDPOINT, urlencode($query));

    // IMPORTANT
    // ---------
    // Function is called with @ to disable warnings
    // When ticker contains ^ there is "HTTP request failed! HTTP/1.0 400 Bad Request" error
    if ($response = @file_get_contents($url)) {
      $data = json_decode($response);
      if (isset($data->query->results->{$key})) {
        return $data->query->results->{$key};
      }
    }

    return NULL;
  }

  /**
   * Get historical data from Yahoo Finance in amCharts acceptable format
   * @param $symbol
   * @param $from
   * @param $to
   * @return array
   */
  private function getHistoricalQuotes($symbol, $from, $to) {
    $result = array();
    foreach (Helper::splitDatesRange($from, $to) as $interval) {
      if ($data = $this->yqlQuery(sprintf(self::HISORICAL_QUOTES_QUERY, $symbol, $interval['start'], $interval['end']), 'quote')) {
        // in case 1 day of data is returned $data could be scalar, so convert it to an array
        $data = is_array($data) ? $data : array($data);
        foreach($data as $row) {
          if(isset($row->Date) && isset($row->Adj_Close)) {
            $date = strtotime($row->Date);
            $result[$date] = [
              'date' => $date*1000,
              'value' => floatval($row->Adj_Close),
              'volume' => floatval($row->Volume)
            ];
          }
        }
      }
    }
    // important to sort the results and then return indexed array
    ksort($result);
    return array_values($result);
  }
}

**Comment by drobertson123** [comment]
Just a helpful suggestion. This isn't a well-formed question or issue for the developers of the IEX-API.

Dumping a huge amount of source code from a different data source in here and saying you need help isn't going to get you anywhere. This area is for communicating bugs and suggestions to the developers of this API.

I am assuming you are not a programmer. My suggestion is to hire a programmer that understands the problem and have them replace the code you are having problems with.

The IEX-API may be a good source of data for you, but you will need someone who understands the API to do the conversion for you.
