### ISSUE TITLE
Open-close returning Yesterdays Date

### ISSUE THREAD

**Issue by bjwest** [iexg/IEX-API#182]
## Summary
The 'open-close' API call is returning todays open and close prices but yesterdays timestamp.

## Details
Entering 'https://api.iextrading.com/1.0/stock/AAPL/open-close' returns the following data:
`{'open': {'price': 176.2, 'time': 1516199400450}, 'close': {'price': 179.1, 'time': 1516222800153}, 'high': 179.25, 'low': 175.07}`
Both timestamps are for yesterdays (Jan 17) dates, but the opening and closing prices are correct for today.   

### Date/time of issue
Jan 18, 2018 from a few minutes after official closing time until the time of this issue report.

### API URL
[AAPL](https://api.iextrading.com/1.0/stock/AAPL/open-close) is an example, but every stock I've checked gives yesterdays timestamp.

### What you expected to happen
Todays closing timestamp returned in results of call to 'open-close'.

### What actually happened
API call returned timestamp of yesterdays closing.

### Other Information (sample code, links, etc.)
The 'previous' API call returns the correct date, so somewhere the timestamp is not being updated for the 'open-close' call.

**Comment by joshuablackburn-iex** [comment]
Today is Jan 17th.  All dates are based on the official exchange time which is eastern standard time.

**Comment by bjwest** [comment]
Huh.  Your right, and the 'previous' call gives the 16th not the 18th.  I don't know where my head was, and I'd just finished manually entering yesterdays data into my database with it's correct date...
