### ISSUE TITLE
Splits missing for some symbols

### ISSUE THREAD

**Issue by jimmyzzxhlh** [iexg/IEX-API#183]
## Summary
https://api.iextrading.com/1.0/stock/aal/splits/5y
It has a split with ratio of 0.373 on 12/09/2013 but the above API returns an empty response.
http://performance.morningstar.com/stock/performance-return.action?p=dividend_split_page&t=AAL

I'll report here if I find more splits missing.

**Comment by massaroni** [comment]
The split for NSPR is missing, for Thursday Feb 8th 2018.

**Comment by massaroni** [comment]
AVIR split missing, for Feb 14, 2018.
