### ISSUE TITLE
Support for OTCMKTS

### ISSUE THREAD

**Issue by aokellermann** [iexg/IEX-API#184]
Would it be possible to add over-the-counter stocks to the API? I was trying to get information on $TCEHY, which returned "Unknown symbol". I tried a few other OTCMKTS stocks and they all returned the same, so I assume it's currently not supported.

**Comment by jcape** [comment]
This is a duplicate of #63. If you'd like to track our progress in adding new data, the best way is to add thumbs-up to that issue's first comment, so you get notifications.
