### ISSUE TITLE
when will API 2.0 replace current version?

### ISSUE THREAD

**Issue by bkcollection** [iexg/IEX-API#186]
## Summary
There are many issues of data accuracy that raise by others but I do not see any action taken except label investigation.

Is IEX plan to upgrade the API to version 2.0 soon? If yes, when?

I think many issues like dividend, EPS and stock split that raise by others is still pending issues. I am not sure if your side plan to make the changes together with API 2.0 or just has no time to make the correction of the data.

Thanks

**Comment by larspeh** [comment]
Extremely interesting question, we need to plan our ressources and right now it feels like a bit of waste to spend more time on version 1
So please can we have an estimate.

Thanks in advance
Lars

**Comment by joshuablackburn-iex** [comment]
We do not have a firm date for release, but the goal is by the end of Q1.  v1 of the API will continue to be available for a period of time after v2 release.  That time has not yet been determined, but could be 4-6 months.  We continue to update and fix v1, and appreciate the patience as we prepare to launch our listings business.
