### ISSUE TITLE
Add ISIN code to all stocks

### ISSUE THREAD

**Issue by SergeC** [iexg/IEX-API#187]
## Summary
I'd like to request a new feature to add ISIN codes to all stocks since Symbol is not unique on all exchanges.

### API URL

Probably https://api.iextrading.com/1.0/ref-data/symbols

### What you expected to happen
I expect to have an ISIN field in the response of the API above.

### What actually happened
No way to get an ISIN code for stocks https://en.wikipedia.org/wiki/International_Securities_Identification_Number

**Comment by joshuablackburn-iex** [comment]
This is not something we can do at this time.  ISIN and CUSIP information require each consumer to pay a license fee to the appropriate organizations.  We are unable to distribute this information without authorization from those organizations.

http://www.isin.org/isin-code-fees/

**Comment by Gys** [comment]
isin.org is an independent commercial organisation that has no influence or copyrights or whatever. They try to profile themselves as such, but their about-page is (eventually, at the bottom) very clear in this. They only control their very own isin.org-database. Which is just that: their own version / list of all (some ?) ISIN codes.

The above linked /isin-code-fees/ states: 'Failure to pay ISIN.org a listing fee or failure to pay ongoing database maintenance fee **will not impact the validity of the ISIN or other code that has been issued by a respective NNA). ISIN.org has no affiliation with the association of national number agencies, (ANNA) or any national number agency (NNA)**. Profiles will simply not remain in the ISIN.org database, if we choose to remove them.' (bold is mine).

**Comment by Gys** [comment]
The actual database can be searched (after registration) at https://www.anna-web.org/
Problem might be that the codes are issued by each country itself. ANNA is the association of those national organisations.

**Comment by myichimoku** [comment]
I would be interested in this as well.
This site has an open database, but seems to be lacking an api... https://www.isindb.com/

Also found this, but not sure how useful that could be... https://registers.esma.europa.eu/publication/searchRegister?core=esma_registers_firds&keyword=isin

This is promising too: https://www.ecb.europa.eu/paym/coll/assets/html/index.en.html

Last but not least, this might be helpful too: https://www.openfigi.com/api

**Comment by andig** [comment]
Interested in this, too. Coming from Europe I'd like to research ETFs by ISIN. Currently the API does not seem to accept ISINs at all and I haven't found a way to convert into an acceptable API id?

Example:

    Name of Security		ISIN	SEDOL	WKN	Last Update	Save results as PDF
    ISHARES III PLC	Copy to clipboard	IE00B4L5Y983	B4L60Z9	A0RPWH	2018-05-15
