### ISSUE TITLE
chart label giving mixed date format

### ISSUE THREAD

**Issue by scottycc** [iexg/IEX-API#19]
https://api.iextrading.com/1.0/stock/fb/chart/3m

The Label field is giving a mixed format result. 

The results up until around the 1m range are shown in the date format 'Aug 8, 17'.

The results after and until the end of the return are shown as 'Sep 15'. (no year)

It also looks like this is not exclusive to 3M, the 1Y chart is also showing this.

**Comment by joshuablackburn-iex** [comment]
This is actually intended behavior.  It will be explained in more detail in our documentation update.  The intent of the label field is to provide what we believe to be a good display for each range.  We use this field for our charts, but it can be used anywhere.  If the label doesn't work, we also provide the date field which can be formatted whichever way works best for you.
