### ISSUE TITLE
NBBO

### ISSUE THREAD

**Issue by VEnvirons** [iexg/IEX-API#191]
## Summary
Couple of questions if I may?

1.)  Curious if the National real-time AND/OR delayed Best Bid, Best Offer (NBBO) can be provided?  If not, is there anyway to reverse engineer the NBBO from the Effective Spread end point?

2.)  The documentation does not specify if the quote OHL is the official national or only based on IEX "tick when traded" aggregation.  It would be nice to get both during the trading session as well as for the previous session etc.

3.)  I understand the documentation states that all endpoints take ?filter= , however, although I have not been able to test this, I have nevertheless noticed it does not work with the https://api.iextrading.com/1.0/stock/aapl/delayed-quote end point.

BTW, is the high and low from the stock->delayed refer to the delayed high and low, which can actually be different?

**Comment by joshuablackburn-iex** [comment]
At this time, the NBBO is not available.  We only provide IEX top of book and depth of book.  The documentation will be updated to make it more clear regarding OHL information.  The IEX and market high low can be derived from /chart/1d.  On stock/quote, we are displaying the official national OHLC.  The filter option on delayed-quote has been fixed and will be released before the open today.
