### ISSUE TITLE
/stock/aapl/chart/2y contains 2 arrays as root element

### ISSUE THREAD

**Issue by sgiulians** [iexg/IEX-API#192]
## Summary
/stock/aapl/chart/2y:
the result contains 2 arrays as root elements. This creates problems on the 99.99% of the JSON-compliant parsers in the world. It obliges people to split the array before parsing it.
Would it be possible to have a single root element like this?
{
  [A],
  [B]
}
or even better collapse the 2 arrays in a single one:
[A,B]

### Date/time of issue
18:18 23/01/2018 - London Time

### API URL
https://iextrading.com/developer/docs/#chart

### What you expected to happen
I would expect a unique root to the json element without splitting it.
Something like this:
{
  [],
  []
}

**Comment by joshuablackburn-iex** [comment]
The chart endpoint returns a collection (array of objects).  

[{
date: "2016-01-22",
open: 98.63,
high: 101.46,
low: 98.37,
close: 101.42,
volume: 65800467,
unadjustedVolume: 65800467,
change: 5.12,
changePercent: 5.317,
vwap: 100.0502,
label: "Jan 22, 16",
changeOverTime: 0
},
{
date: "2016-01-25",
open: 101.52,
high: 101.53,
low: 99.21,
close: 99.44,
volume: 51794525,
unadjustedVolume: 51794525,
change: -1.98,
changePercent: -1.952,
vwap: 100.4126,
label: "Jan 25, 16",
changeOverTime: -0.01952277657266815
}]

**Comment by VEnvirons** [comment]
I agree JSON sometimes overly complicates simple price data and is slower to parse.  Chronological price records can simply be one record in ASCII CSV, on per line like so...
date: "2016-01-22",open: 98.63,high: 101.46,low: 98.37,close: 101.42,volume: 65800467,...etc
or
"2016-01-22",98.63,101.46,98.37,101.42,65800467,... without labels.

In general, I would take off quotation marks off values as well as represent dates as yyyyMMdd like this 20160122 which sorts nicely.
-S

**Comment by joshuablackburn-iex** [comment]
@VEnvirons I'm not sure how JSON is complicated in this scenario, but CSV is always available by using the format=csv parameter.  You can also use the filter parameter to select only the keys you care about.  Quotes in CSV are valid.  Representing the date as a number is something we can look at for a future API version, but chart data is already sorted in ascending order.

**Comment by VEnvirons** [comment]
@joshuablackburn-iex 

That's great.  Question.  Why does the 1 minute data not have open or close?  What is meant by "Average" and "Notional"

-S

**Comment by joshuablackburn-iex** [comment]
Official open and close can occur at different times of the day depending on the Exchange and/or symbol.  To avoid confusion of placing an extra element in a random minute bucket, we offer the open-close endpoint which returns the OHLC.  "average" means average trade price during that minute.  "notional" means the total notional value of trades in that minute.

**Comment by VEnvirons** [comment]
@joshuablackburn-iex
Yes I know, however we are talking about 1 minute interval data.  The OHLC for that minute must be defined to populate a standard OHLC bar chart, regardless of the specific interval resolution in question.  This includes any bar chart, daily, weekly, monthly, 60 minute, 1 minute et al.

The typical aggregation of a bar's OHLC is...
Open = first (Tick when traded) price print in that interval.  For example the 1 minute bar of 9:30 AM (starting at) would be the first trade between time 9:30:00 AM - 9:30:59 AM.
High = the highest (Tick when traded) price print in that interval.  For example the 1 minute bar of 9:30 AM (starting at) would be the highest trade between time 9:30:00 AM - 9:30:59 AM.
Low = the lowest (Tick when traded) price print in that interval.  For example the 1 minute bar of 9:30 AM (starting at) would be the lowest trade between time 9:30:00 AM - 9:30:59 AM.
Close= The Last (Tick when traded) price print in that interval.  For example the 1 minute bar of 9:30 AM (starting at) would be the Last trade between time 9:30:00 AM - 9:30:59 AM.

Alternatively intervals can be sometimes defined by end time so 9:30:01 - 9:31:00 as an example.

So not sure why you define "Average" unless you provide it as additional information, in addition to a standard OHLC price series.

Also, what are the definitions of "MarketHigh", "MarketLow" etc?

-S
