### ISSUE TITLE
Is there a way to rebuild TOPS websocket messages from data in PCAP file

### ISSUE THREAD

**Issue by rterp** [iexg/IEX-API#193]
## Summary
I see that the PCAP file is a capture of the binary data stream and have looked through the specs of the data structure.  We want to be able to get a historical TOPS websocket data for backtesting.  Is there a way to rebuild the websocket API data from the PCAP file, or is there another way to obtain historical websocket messages?

**Comment by joshuablackburn-iex** [comment]
The PCAP file is only capturing our binary data feeds and is not related to the websocket feed.  Retaining a full day history of websocket messages is a very interesting idea.  We will investigate the required effort for this.

**Comment by cgi1** [comment]
Would be a great idea

**Comment by timpaine-iex** [comment]
closing as stale
