### ISSUE TITLE
New API method: stock lookup by name

### ISSUE THREAD

**Issue by Hastewave** [iexg/IEX-API#195]
Hello
I am developing a mobile app and I've got some idea for an improvement in your beautiful API.
It would be great to have an API method to lookup stocks by name. This can be implemented as a filter for a "/ref-date/symbols" method.

Example from another API:
curl
    -X GET
    'https://somapi.com/securities?query=ba&limit=4'

Response
{
    "securities": [
        {
            "symbol": "BA",
            "description": "BOEING COMPANY"
        },
        {
            "symbol": "BAC",
            "description": "BANK OF AMERICA CORPORATION"
        },
        {
            "symbol": "BAX",
            "description": "BAXTER INTERNATIONAL Inc"
        },
        {
            "symbol": "BAP",
            "description": "CREDICORP Ltd"
        }
    ],
    "count": 2492
}

**Comment by ericmosvel** [comment]
Hi.

I'm working with IEX and vue-select (dropdown search). Did you do something similar?

**Comment by Hastewave** [comment]
In iOS it's not possible to use vue-select lib.

**Comment by yay** [comment]
You can easily implement this yourself on the client side by fetching the list of all symbols once via the https://api.iextrading.com/1.0/ref-data/symbols API and then searching them to perform completion. The client will be a lot more responsive as a result of that -- no server requests to make, except for the initial one.

For example (Kotlin code):

```kotlin
object IexSymbols {
    private var cache = mapOf<String, Symbol>()

    fun update() {
        launch {
            Iex.getSymbols()?.let {
                cache = it.map { it.symbol to it }.toMap()
            }
        }
    }

    // returns the list of symbols that have the `part` sequence in their name
    private fun completeByName(part: String, max: Int = 10): List<Symbol> {
        val lowerCasePart = part.toLowerCase()
        return cache.values.asSequence().filter {
            it.name.toLowerCase().contains(lowerCasePart)
        }.take(max).toList()
    }

    // returns the list of symbols that match the first letters of the ticker (`part`)
    fun complete(part: String?, max: Int = 10): List<Symbol> {
        if (part == null || part.isBlank()) return emptyList()

        val upperCasePart = part.toUpperCase()
        return cache.values.asSequence().filter {
            it.symbol.startsWith(upperCasePart)
        }.take(max).toList().takeIf { it.isNotEmpty() } ?: completeByName(part)
    }

    // given the ticker, returns the associated datum
    fun find(symbol: String): Symbol? = cache[symbol]

    // given the ticker, returns the name of the asset
    fun name(symbol: String): String? = find(symbol)?.name

    // check if the ticker is known, e.g:` "AAPL" in IexSymbols`
    operator fun contains(symbol: String) = symbol in cache
}
```

**Comment by Hastewave** [comment]
Yeah, did it in my app the same way.
Issue solved.
Thanks!

**Comment by timpaine-iex** [comment]
either via one of the symbols endpoints, or alternatively the search endpoint. docs have info about all
