### ISSUE TITLE
Api with open, close, high and low prices for various time periods

### ISSUE THREAD

**Issue by elisag1990** [iexg/IEX-API#196]
I was looking for an api that returns open, close, high and low prices. The 1d chart for example does not provide the open and close prices.

**Comment by joshuablackburn-iex** [comment]
The endpoint /stock/ohlc returns open, high, low, and close.  1d chart will be updated to return the open/close price for each minute.

**Comment by elisag1990** [comment]
currently /stock/ohlc looks like returning eod ohlc, is this going to change?

**Comment by elisag1990** [comment]
any date for availability of open and close prices for the 1d chart?

**Comment by joshuablackburn-iex** [comment]
1d chart will get open and close, but that will represent the open and close price of the minute for the purpose of candlestick charting.  OHLC can be used to retrieve the official open/close price when it becomes available from the primary exchange.

**Comment by coreyauger** [comment]
I am also very excited for this.  Thanks for pushing this to "near term".  Just for context, how long would we wait for a feature on the near term to make it into the official API.  Also thanks for democratising the financial playing field :)
