### ISSUE TITLE
stock/dividends/... returning null set on evening of ex-dividend date

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#197]
## Summary
After market close on ex-dividend date, all results are returning "[]" (without the quotes).

## Details
Today, Jan 30, 2018 is the ex-dividend date for both EPD and KMI. All of the following return "[]".

*** For securities where today is NOT the ex-dividend date, the dividends endpoint seems to be working fine. ***

  =WEBSERVICE("https://api.iextrading.com/1.0/stock/KMI/dividends/1y?filter=amount")
  =WEBSERVICE("https://api.iextrading.com/1.0/stock/EPD/dividends/1y?filter=exDate")

  =WEBSERVICE("https://api.iextrading.com/1.0/stock/KMI/dividends/1y?filter=paymentDate")
  =WEBSERVICE("https://api.iextrading.com/1.0/stock/EPD/dividends/1y?filter=recordDate")

### Date/time of issue
Jan 30, 2018, 6:00 PM EST

### API URL
See above

### What you expected to happen
Get valid data vs. a null set

### What actually happened
null set

**Comment by evancarter-iex** [comment]
This should be fixed in IEXCloud. https://iexcloud.io
