### ISSUE TITLE
PG stock earning information is missing 2 quarters info

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#198]
## Summary
PG stock earning information isn't complete

## Details
Currently, PG has already announced earning result for Q2 2018. (http://www.nasdaq.com/symbol/pg/revenue-eps) In IEX API, the latest earning result is Q4 2017. 2 quarters are missing.

### Date/time of issue
31 January 2018

### API URL
https://api.iextrading.com/1.0/stock/PG/earnings

### What you expected to happen
Earnings API will show up-to-date earning result

### What actually happened
Earnings API is not showing up-to-date earning result for certain stock like PG (For some stocks like FB, GOOGL, it is showing up-to-date earning result). Hope this can be fixed for all stocks, to show up-to-date earning result.

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
