### ISSUE TITLE
stock market news

### ISSUE THREAD

**Issue by scottycc** [iexg/IEX-API#2]
API URL: 
https://api.iextrading.com/1.0/stock/market/news/last/5

Sometimes the market news item url leads to https://iextrading.com/404.html 

For example, the first item in this API response gives me this URL: https://api.iextrading.com/1.0/stock/market/article/7570975448613269

This URL lands me on the 404.html page as of the time on this post.

**Comment by evancarter-iex** [comment]
@scottycc Can you check to see if you are still having this problem? We believe we have fixed the issue.

**Comment by scottycc** [comment]
No issues so far! 

If it happens again I will let you guys know. 

Also, thank you very much for the free API.
