### ISSUE TITLE
/Quote after close giving curious results

### ISSUE THREAD

**Issue by bclous** [iexg/IEX-API#20]
Please check out an example /Quote response for Apple as of 5:27 PM EST (after market close)

{"symbol":"AAPL","companyName":"Apple Inc.","primaryExchange":"Nasdaq Global Select","sector":"Technology","calculationPrice":"sip","latestPrice":158.66,"latestSource":"15 minute delayed price","latestTime":"4:59:31 PM","latestUpdate":1505768371879,"latestVolume":28173737,"iexRealtimePrice":158.65,"iexRealtimeSize":100,"iexLastUpdated":1505764798975,"delayedPrice":158.66,"delayedPriceTime":1505768371879,"previousClose":158.67,"change":-0.01,"changePercent":-0.00006,"iexMarketPercent":0.01386,"iexVolume":390488,"avgTotalVolume":28935429,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":819515074480,"peRatio":18.56,"week52High":164.94,"week52Low":104.08,"ytdChange":0.36607834696513114}

This is giving a curious result for a few reasons:

1) The stock closed at 158.67, yet it says the real time price is 158.65, and the delayed price is 158.66.  Since the market has been closed for an hour, shouldn't the real time price, and the delayed price, both reflect the market close price?  Is this pulling quotes from after market trades?

2) I don't think this is handling previous close correctly, or in a helpful way at least.  At 5:30, I still want to be able to see what happened to AAPL stock TODAY.  I would do that by comparing the current price to the previous close.  This seems to be updating the previous close immediately upon market close, however, so I lose all context of what happened today as soon as the market closes.  It seems to me that when the market is closed, the current price should reflect the closing price from that day, and the previous close should still reflect the closing price from the trading day before.  It should give the same result that it gave all day.  It should stay this way until the market opens again.  Otherwise the previous close, change, and changePercent results are pretty useless after the market closes or on a weekend.

**Comment by joshuablackburn-iex** [comment]
1.  Real-time price will always reflect IEX's latest trade, including after hours (up to 5pm EST).  Delayed price will be the 15 minute delayed SIP price, including after hours (up to 5pm EST).

2.  The error you experienced was only on a subset of our servers, and you should be seeing it correctly now.  The intended functionality is to show data relevant to today, so previous close will be the previous trading day.  A subset of our traffic was routed to a server that had todays closing price.

**Comment by bclous** [comment]
Thanks..it seems like it's happening again:

{
    avgTotalVolume = 8034687;
    calculationPrice = close;
    change = 0;
    changePercent = 0;
    companyName = "Morgan Stanley";
    delayedPrice = "47.33";
    delayedPriceTime = 1505767457579;
    iexAskPrice = 0;
    iexAskSize = 0;
    iexBidPrice = 0;
    iexBidSize = 0;
    iexLastUpdated = 1505764797762;
    iexMarketPercent = "0.02351";
    iexRealtimePrice = "47.32";
    iexRealtimeSize = 100;
    iexVolume = 162526;
    latestPrice = "47.475";
    latestSource = "Previous close";
    latestTime = "September 18, 2017";
    latestUpdate = 1505692800000;
    latestVolume = 6913058;
    marketCap = 87191668305;
    peRatio = "13.64";
    previousClose = "47.475";
    primaryExchange = "New York Stock Exchange";
    sector = "Financial Services";
    symbol = MS;
    week52High = "48.8983";
    week52Low = "30.62";
    ytdChange = "0.1027874564459931";
}


I'm getting the same value for latestPrice and previous close for all 30 stocks I'm running

**Comment by bclous** [comment]
Just to help you identify the problem, I was getting the result above from about 7pm all night and then at midnight I started getting what looks to be a correct result.

**Comment by bclous** [comment]
Hey just checking in again on the status of this.  Below are three calls from 9:08 to 9:10 as of this morning.   As you can see the previous close price is incorrect in all of them and is the same as the latest price so the change and change percent are showing as 0.  It's been pretty consistently incorrect for almost all the stocks I look at when the market is closed. 

{"symbol":"ADS","companyName":"Alliance Data Systems Corporation","primaryExchange":"New York Stock Exchange","sector":"Financial Services","calculationPrice":"close","latestPrice":215.05,"latestSource":"Previous close","latestTime":"September 19, 2017","latestUpdate":1505779200000,"latestVolume":517640,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":215.05,"delayedPriceTime":1505853915812,"previousClose":215.05,"change":0,"changePercent":0,"iexMarketPercent":0,"iexVolume":0,"avgTotalVolume":587760,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":11931713772,"peRatio":13.27,"week52High":266.25,"week52Low":197.69,"ytdChange":-0.07707823698553702}

{"symbol":"BAX","companyName":"Baxter International Inc.","primaryExchange":"New York Stock Exchange","sector":"Healthcare","calculationPrice":"close","latestPrice":64.02,"latestSource":"Previous close","latestTime":"September 19, 2017","latestUpdate":1505779200000,"latestVolume":1825440,"iexRealtimePrice":64.025,"iexRealtimeSize":100,"iexLastUpdated":1505851193743,"delayedPrice":64.02,"delayedPriceTime":1505853915812,"previousClose":64.02,"change":0,"changePercent":0,"iexMarketPercent":0.01478,"iexVolume":26980,"avgTotalVolume":2271508,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":34882635914,"peRatio":27.36,"week52High":64.75,"week52Low":43.13,"ytdChange":0.4405940594059406}

{"symbol":"GOOG","companyName":"Alphabet Inc.","primaryExchange":"Nasdaq Global Select","sector":"Technology","calculationPrice":"sip","latestPrice":923.39,"latestSource":"15 minute delayed price","latestTime":"8:40:20 AM","latestUpdate":1505911220940,"latestVolume":913028,"iexRealtimePrice":921.89,"iexRealtimeSize":71,"iexLastUpdated":1505851198943,"delayedPrice":923.39,"delayedPriceTime":1505911220940,"previousClose":921.81,"change":1.58,"changePercent":0.00171,"iexMarketPercent":0.01443,"iexVolume":13175,"avgTotalVolume":1240441,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":639797990424,"peRatio":40.97,"week52High":988.25,"week52Low":727.54,"ytdChange":0.17257740351591314}

**Comment by evancarter-iex** [comment]
Both ADS and BAX hadn't been traded yet on any exchange at the time you specified. So the previous day close is used for latest price. Yahoo Finance/Google Finance showed the same thing at the that time (last price = previous day close). Our previous close price also matches what is seen on Yahoo Finance.

For GOOG:
Our trading system starts at 8am of each trading day and we start receiving pricing data. At that point the system is updated with the previous close price from the listings exchange. This will differ from what you see on Yahoo, because they do not seem to use the official close price.

Example: Instead returning September 18th close price, we start returning the September 19th close price at 8am on September 20th.

Hope that helps.

**Comment by bclous** [comment]
Thanks -

The data I'm seeing after close doesn't reflect what your explaining though.   

For example, on Sept 19th at 8pm, the previous close should reflect the close for Sept 18th.  It should be the same on Sept 20th at 7am.   Once you start receiving price data at 8am, the previous close should then update to the close for the 19th.  Is this your understanding?

This is not what I'm seeing.  After the close in the PM, I'm consistently seeing the previous close updating to the most recent close, and I'm getting 0% and 0 change for every stock.

**Comment by bclous** [comment]
I understand your explanation for my examples this morning, if the previous close is turning over at 8am as opposed to 9:30am.   But as of last night at 8pm they had already all turned over and were showing 0.0% for change on every stock.

**Comment by evancarter-iex** [comment]
Ill monitor tonight after hours.

**Comment by bclous** [comment]
Hey I took a look at this last night and I think have clarified the issue:

At exactly 8PM all of the % changes and dollar changes for the day are going to zero.  I thought it was the previous close price that was incorrect but it looks like it's actually the "latestPrice" field that is erroneously showing the same value as previous close.

**Comment by bclous** [comment]
Just re-reading your API docs - is this behavior on purpose? 

"refers to the latest price being the IEX real time price, the 15 minute delayed market price, or the previous close price."

Doesn't seem like it makes sense on a Thursday evening at 8pm for the "latest price" to show the price from Wednesday's close.

**Comment by evancarter-iex** [comment]
@bclous we are still looking into this on our end.

**Comment by bclous** [comment]
Thanks, I took a very close look last night.  The problem is only between 8pm and 12am EST.   The "lastPrice" is defaulting to previous close from over a day before.   For whatever reason at midnight it goes back to the correct value.

**Comment by joshuablackburn-iex** [comment]
You're right.  The intention is to only show previous close price when we haven't traded, or have a delayed quote for the symbol.  In this particular case, we have a process clearing out today’s prices which causes the code to flip to previous day close.  We will remove the process that clears prices, and add more checks to ensure we don’t fall back to previous day when there has been a current day price.  We are also working on integrating the official open and closing price intraday which will help with this issue as well.

**Comment by bclous** [comment]
Ok thanks please keep me updated on any fixes!

**Comment by bclous** [comment]
Hi Just took a look now -

It looks like the behavior has changed.  Now I'm seeing the correct lastPrice, yet it's 10PM EST and the previous close has now already updated to the close from today, so it's showing 0% change and $0 dollar change for every stock. 

I think the desired behavior would be to have the previous close not update until 8am tomorrow morning when new prices start hitting?  When someone looks at a stock tracker at 9 or 10pm I still think it should show what happened that day.  It seems like instead of changing the lastPrice logic the previous close logic got changed instead and I don't think that's the desired behavior. 

I think how it should be handled is the lastPrice should always be the price of the last trade you have record of.  The previous close should always be the close from t-1 trading days from date of the last trade you have record of. 

The lastPrice date should drive the previous close and it seems like the directionality is going the other way in your model, at least from the outputs I'm observing.

**Comment by bclous** [comment]
lol never mind pls dis

**Comment by joshuablackburn-iex** [comment]
Please have a look at the data tonight.  We've pushed out an update.

**Comment by bclous** [comment]
Looked good to me last night!

**Comment by joshuablackburn-iex** [comment]
Considering this resolved.

**Comment by joshuablackburn-iex** [comment]
Thank you for all the troubleshooting on this issue.
