### ISSUE TITLE
Gainers, Losers list

### ISSUE THREAD

**Issue by tradetools** [iexg/IEX-API#200]
## Summary

While results are correct during market hours (gainers have positive changes, losers have negative 
changes) the same does not apply when the market is closed.

### What you expected to happen

List the gainers with positive change and losers with negative change, sorted by top gainers (maximum win change) and top losers (maximum loss change)

**Comment by tradetools** [comment]
Any update on this?

**Comment by joshuablackburn-iex** [comment]
This is in QA now.

**Comment by bkcollection** [comment]
the gainers and losers list does not shown Friday result on Sunday. The gainers list shall be keep over the weekend until the market open again on Monday. 

It shown as [ ] on Sunday
