### ISSUE TITLE
/stock/market/quote? Or, can we send ~6.000 rqs/m to /stock/:ticker/quote?

### ISSUE THREAD

**Issue by sqaxomonophonen** [iexg/IEX-API#201]
The stock quote endpoint offers a lot of data that is useful to us, specifically open/close prices with timestamps, and a latest price (+timestamp) that's aggregated from multiple sources (thanks!)

The thing is that we'd like to retrieve this data for about 6.000 stocks once per minute during trading hours (and then for a little while until close prices settle), so that amounts to a sustained rate of about 100 requests per second for several hours. Is this a usage pattern you're okay with? On one hand you do advertise "over 100 requests per second", but we're still afraid you might flag this as abuse :)

Alternatively, we'd much rather have a `/stock/market/quote` endpoint that returns the same data for all stocks, and fetch it once per minute, since there'd be a lot less overhead for both of us. A WebSocket endpoint that pushes quote documents whenever they're updated would of course be even better.

**Comment by joshuablackburn-iex** [comment]
Your usage pattern is acceptable.  I don't see us adding a /stock/market/quote, but we are working on streaming quotes.

**Comment by mmjdotdk** [comment]
BTW; you guys at IEX fscking rock! :)

**Comment by ericmosvel** [comment]
Hey guys.

I'm working with IEX and vue-select (dropdown search). Did someone do something similar?
