### ISSUE TITLE
Stock Symbol - Not in database

### ISSUE THREAD

**Issue by travisloneker** [iexg/IEX-API#202]
## Summary
I have two stock symbols that I can pull up on CNN:
http://money.cnn.com/quote/mutualfund/mutualfund.html?symb=WGRNX
http://money.cnn.com/quote/mutualfund/mutualfund.html?symb=WGRIX

but can not be pulled up with the API. I checked the stock symbols on the search area on the website but with no results either.

**NOTE: Not exactly sure where your data is coming from.**

## Details
Details above.

### Date/time of issue
02/02/02 - 11:43 AM CST

### API URL
https://api.iextrading.com/1.0/stock/WGRNX/quote
https://api.iextrading.com/1.0/stock/WGRIX/quote

### What you expected to happen
To receive data for the above two symbols.

### What actually happened
No data.

### Other Information (sample code, links, etc.)

**Sorry not sure why it is half in half out.**

`<script type="text/javascript">
                            //Get stock information for WGRNX
                            function checkStockWGRNX() {
                                $.ajax({
                                    type: "GET",
                                    url: "https://api.iextrading.com/1.0/stock/WGRNX/quote",
                                    data: {

                                    },
                                    success: function(dataWGRNX) {
                                        
                                        console.log(dataWGRNX);
                                        
                                        //Finding specific data
                                        var open          = dataWGRNX.open,
                                            change        = dataWGRNX.change,
                                            changePercent = dataWGRNX.changePercent;

                                        $('#daysopen').append("$" + open);
                                        $('#change').append("$" + change);
                                        $('#changePercent').append(changePercent + "%");

                                    }
                                })
                            }

                            //Run function on load
                            $(window).on('load', checkStockWGRNX);
                            
                            //Get stock information for WGRIX
                            function checkStockWGRIX() {
                                $.ajax({
                                    type: "GET",
                                    url: "https://api.iextrading.com/1.0/stock/WGRIX/quote",
                                    data: {

                                    },
                                    success: function(dataWGRNX) {
                                        
                                        console.log(dataWGRNX);
                                        
                                        //Finding specific data
                                        var open          = dataWGRNX.open,
                                            change        = dataWGRNX.change,
                                            changePercent = dataWGRNX.changePercent;

                                        $('#daysopen').append("$" + open);
                                        $('#change').append("$" + change);
                                        $('#changePercent').append(changePercent + "%");

                                    }
                                })
                            }

                            //Run function on load
                            $(window).on('load', checkStockWGRIX);
                        </script>`

**Comment by evancarter-iex** [comment]
We currently dont have support for mutual funds.

https://github.com/iexg/IEX-API/issues/16
