### ISSUE TITLE
stock/market/ohlc not return open and close

### ISSUE THREAD

**Issue by Jugal112** [iexg/IEX-API#203]
## Summary
Two days ago, https://api.iextrading.com/1.0/stock/market/ohlc returned the ohlc for all stocks. Today it's only returning the high and low.

### Date/time of issue
Today, 2/3/2018

### API URL
https://api.iextrading.com/1.0/stock/market/ohlc

### What you expected to happen
Get OHLC for all stocks

### What actually happened
Got High and Low only for all stocks. No open and close
{"SNOAW":{"high":0.4312,"low":0.4312},"NOMD":{"high":17.16,"low":16.87},"ARR-A":{"high":25.2,"low":25.139},"RTH": ...

**Comment by joshuablackburn-iex** [comment]
All data is available at end of each trading day.  Currently we have a data cleanup that may be clearing some of this data.  We can make adjustments to keep some data around for more time.

**Comment by Jugal112** [comment]
i see, ok so it appears that when I request the data after the trading day is done, I get ohlc. But when I request it on the weekends, then the issue of only getting High and Low is apparent. Thanks!
