### ISSUE TITLE
Short Interest Report returns no data

### ISSUE THREAD

**Issue by awaer** [iexg/IEX-API#205]
## Summary

The IEX Short Interest Report returns no data. 

### Date/time of issue
4:00pm February 3, 2018 (PST) 

### API URL
https://api.iextrading.com/1.0/stock/tsla/short-interest
https://api.iextrading.com/1.0/stock/market/short-interest/batch?symbols=aapl,tsla,amd

### What you expected to happen
Response should contain an object for the specified symbol, as described in the [documentation](https://iextrading.com/developer/docs/#iex-short-interest-list). 

For example,

```javascript
[
  {
    "SettlementDate": "20171013",
    "SecurityName": "ZIEXT Common Stock",
    "CurrentShortInterest": 5363,
    "PreviousShortInterest": 5730,
    "PercentChange": -0.064049,
    "AverageDailyVolume": 2113,
    "DaystoCover": 2.54,
    "StockAdjustmentFlag": "N",
    "RevisionFlag": "N",
    "SymbolinINETSymbology": "ZIEXT",
    "SymbolinCQSSymbology": "ZIEXT",
    "SymbolinCMSSymbology": "ZIEXT",
    "NewIssueFlag": "N",
    "CompanyName": "ZIEXT Test Company"
  },
  {...}
]
```

### What actually happened
Response is empty:
```javascript
// https://api.iextrading.com/1.0/stock/tsla/short-interest
[]
```

```javascript
// https://api.iextrading.com/1.0/stock/market/short-interest/batch?symbols=aapl,tsla,amd
[
  [],
  [],
  []
]
```

**Comment by joshuablackburn-iex** [comment]
The short-interest endpoint will only return data for IEX listed stocks.  We do not have any listed stocks at this time.  Once we list a company, this data will be available.
