### ISSUE TITLE
Data for delisted/acquired companies

### ISSUE THREAD

**Issue by mobiledna** [iexg/IEX-API#206]
Are there any plans to return data for stocks that were delisted, acquired, etc?  For example, Whole Foods Market (WFM) was recently acquired by Amazon (AMZN).  I was trying to get the chart data for WFM before it was acquired using this URL:  https://api.iextrading.com/1.0/stock/WFM/chart.  "Unknown symbol" is returned.

**Comment by Lambdac0re** [comment]
Still nothing?

**Comment by timpaine-iex** [comment]
Unofficial roadmap is here: https://iexcloud.io/console/roadmap
Any updates would be announced via email and in the docs
