### ISSUE TITLE
Beta - what time frame does the reported value of Beta cover

### ISSUE THREAD

**Issue by myvaluealerts** [iexg/IEX-API#209]
as of: 2/8/18: 
  /stock/aapl/stats   returns :   "beta":1.288221

What time period is used to calculate Beta and what market index is it compared to?

thanks,

**Comment by joshuablackburn-iex** [comment]
We can add a key to describe the period.

**Comment by gnicolosi** [comment]
Has there been an update to this?  I would really appreciate knowing what time period, frequency, and benchmark are used in the beta calculations.  Thanks.

**Comment by mikemags1** [comment]
Would also love and update here!

**Comment by evancarter-iex** [comment]
Documented in https://iexcloud.io
