### ISSUE TITLE
DOW quote sending back strange response

### ISSUE THREAD

**Issue by bclous** [iexg/IEX-API#21]
https://api.iextrading.com/1.0/stock/DOW/quote

I'm consistently getting a response like this one for this API call:

["calculationPrice": close, "sector": Basic Materials, "ytdChange": 0.1571180555555556, "changePercent": N/A, "week52Low": <null>, "latestVolume": 43509409, "primaryExchange": New York Stock Exchange, "latestUpdate": N/A, "delayedPriceTime": 1504212969000, "delayedPrice": 66.65000000000001, "latestSource": N/A, "latestPrice": <null>, "marketCap": N/A, "avgTotalVolume": 5651928, "peRatio": N/A, "latestTime": N/A, "change": N/A, "previousClose": N/A, "week52High": 67.5, "symbol": DOW, "companyName": Dow Chemical Company (The)]

I'm making this call on many different tickers and DOW is the only one I'm getting this result with.

**Comment by joshuablackburn-iex** [comment]
DOW is no longer a valid symbol as they have combined with DuPont to become DWDP.  You can always check our Eligible Symbols list (https://iextrading.com/trading/eligible-symbols/) for supported tickers.  It updates daily with a list of symbols we are trading.
