### ISSUE TITLE
Missing change amount/pct for "previousClose" quotes

### ISSUE THREAD

**Issue by McQaws** [iexg/IEX-API#210]
## Summary

A quote with calculationPrice of "previousclose" has zero for change and changePercent.  Finding the change amount thus requires another api call to /previous endpoint to get the change.

### Date/time of issue
Feb 8 just after start of normal market hours and Feb 9 during pre-market I saw this behavior using the symbol RY.  I also saw with MSFT at 8:04a on Feb 9.

### API URL
https://api.iextrading.com/1.0/stock/ry/quote

### What you expected to happen
Expected to have a value in change and change percent.  

### What actually happened
Values were zero

### Other Information (sample code, links, etc.)
Would like to have the change and changePercent show the proper values to avoid having to make another api call to /previous endpoint.

**Comment by joshuablackburn-iex** [comment]
The reason it works this way is because at 8am our market has begun trading, so values update to be relative to today's trading.  Previous close will represent the previous day, and latest price reflects the latest price we have for the stock.  Unless we receive a trade in the first 4 minutes of trading, the latest price we have is the previous close.  That will result in a 0% change.  Once we receive a trade on IEX, or after 15 minutes has elapsed we will have a price for the current day.

**Comment by McQaws** [comment]
Thanks Joshua, I understand the issue of "stale price".  I was just pointing out that you properly flag the stale price but don't provide the matching stale change amount/percent.  This makes it clumsy to use the quote endpoint as a developer as I must always retrieve the /previous endpoint data to match those quotes (if I want the change amount).

If nothing else, it would have been helpful to know in your docs that the change amount/percent is not provided for previousclose prices.  Thanks

**Comment by joshuablackburn-iex** [comment]
I'm not sure if I fully understand the issue, or what you're referring to as "stale price".  If you call the /previous endpoint at 8am on a trading day, it will return the same close value as the /quote endpoint previousClose.  Change amount and percent are calculated as the different between latestPrice (as defined by calculation price) and previousClose.  This is detailed in our docs.

**Comment by McQaws** [comment]
My mistake - I see the docs say it that way.  I will just do another api call to /previous to get the change amount when the quote calculationPrice is previousClose.

**Comment by joshuablackburn-iex** [comment]
Just a heads up, you can get both values in one API call using batch: https://api.iextrading.com/1.0/stock/aapl/batch?types=quote,previous
