### ISSUE TITLE
Stock ticker NSPR is not split-adjusted

### ISSUE THREAD

**Issue by MakerScott** [iexg/IEX-API#211]
## Summary
Stock hasn't recorded a split, and historical data is not adjusting.

## Details
Ticker doesn't seem to be up-to-date with a reverse split.

### Date/time of issue
2/9/2018

### API URL
https://api.iextrading.com/1.0/stock/nspr/chart/1m
https://api.iextrading.com/1.0/stock/nspr/splits/1m

### What you expected to happen
Stock did a 1-35 reverse split on 2/8/2018.

### What actually happened
Historical data on 2/8/2018 is accurate, but past data is not split-adjusted. A split was also never recorded.

**Comment by joshuablackburn-iex** [comment]
This looks to be working in chart and current price.  We will look into the splits endpoint separately.
