### ISSUE TITLE
Duplicate Dividend Entries: SPY

### ISSUE THREAD

**Issue by pgalasti** [iexg/IEX-API#214]
## Summary
Duplicate dividend entries for SPY. Two of the same for entries with "exDate":"2017-12-15"

## Details
Two of the same for entries with "exDate":"2017-12-15". Observe entries using url: https://api.iextrading.com/1.0/stock/spy/dividends/1y
### Date/time of issue
As of 02/10/2018 11:00 P.M. EST

### API URL
https://api.iextrading.com/1.0/stock/spy/dividends/1y

### What you expected to happen
Expected 4 entries per dividend event per other references.

### What actually happened
Retrieved 5 entries; seemingly duplicate of "exDate":"2017-12-15".

**Comment by nictrix** [comment]
I've also had this happen: https://api.iextrading.com/1.0/stock/CNHI/dividends/5y

The first two are exactly the same data:
```
"exDate": "2017-04-24",
"paymentDate": "2017-05-02",
"recordDate": "2017-04-26",
"declaredDate": "2017-04-14",
"amount": 0.11,
"flag": "",
"type": "Dividend income",
"qualified": "",
"indicated": ""
```

**Comment by pgalasti** [comment]
Great thanks!

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
