### ISSUE TITLE
inconsistent date/timestamp formats

### ISSUE THREAD

**Issue by elisag1990** [iexg/IEX-API#215]
## Summary

Timestamps and date in different formats

## Details

Depending on the api, you have timestamps in milliseconds and dates in string format. In the 1d chart the date has the "yyyymmdd" format while in the 5y chart it is in the "yyyy-mm-dd" format. Why not choose a single format and be consistent with it cross all apis?

**Comment by joshuablackburn-iex** [comment]
We are aware of the inconsistency from our multiple data sources.  Unfortunately we cannot change v1 without breaking existing code, so the plan is to normalize the data in v2.
