### ISSUE TITLE
Has anyone do any python hello world example for IEX websocket?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#216]
## Summary
We intent to include IEX websocket stock pricing, at our existing system written in Python. However, we can hardly get python code working together with IEX websocket server.

## Details

Previously, I have a JavaScript socket.io client application as follow

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>
<script>
    console.log("start");
    
    var socket = io('https://ws-api.iextrading.com/1.0/tops');
  
    // Listen to the channel's messages
    socket.on('message', message => console.log(message));

    // Connect to the channel
    socket.on('connect', () => {
      console.log("connect");
        
      // Subscribe to topics (i.e. appl,fb,aig+)
      socket.emit('subscribe', 'snap,fb,aig+');

      // Unsubscribe from topics (i.e. aig+)
      socket.emit('unsubscribe', 'aig+');
    });

    // Disconnect from the channel
    socket.on('disconnect', () => console.log('Disconnected.'));
</script>

```

Just save it as HTML, and open with chrome. I can get

> start
> connect

Now, I want to port the client application running in python environment

```
from socketIO_client import SocketIO, LoggingNamespace

import logging
logging.getLogger('socketIO-client').setLevel(logging.DEBUG)
logging.basicConfig()

def on_message():
    print('message')

def on_connect():
    print('connect')

def on_disconnect():
    print('disconnect')

print("debug 0")
socketIO = SocketIO(host='https://ws-api.iextrading.com/1.0/tops', verify=False)

print("debug 1")
socketIO.on('message', on_message)

print("debug 2")
socketIO.on('connect', on_connect)

print("debug 3")
socketIO.on('disconnect', on_disconnect)

print("debug 4")
```
The code stucks at `socketIO = SocketIO(...`. What I get is

> debug 0
> C:\yocto\sandbox\venv\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> WARNING:socketIO-client:ws-api.iextrading.com:443/1.0/tops/socket.io [engine.io waiting for connection] unexpected status code (404 Not Found)
> C:\yocto\sandbox\venv\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> C:\yocto\sandbox\venv\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)

I know this might related to the library I use, as Python ecosystem seems doesn't have a widely used socket.io library. Just wondering, have anyone able to get websocket works in Python ecosystem?

### Date/time of issue
12 February 2018

### API URL
https://iextrading.com/developer/docs/#tops

### What you expected to happen
Able to get websocket example works in Python ecosystem.

### What actually happened
Not able to get it works under Python ecosystem.

### Other Information (sample code, links, etc.)
Stated in "Details"

**Comment by timkpaine** [comment]
I just got this working for tops, feel free to look at the [code underneath](https://github.com/timkpaine/pyEX/blob/master/pyEX/common.py#L44)

```python
import pyEX.marketdata.ws
x = pyEX.marketdata.ws.topsWS('snap, fb,aig+', print)
x.run()
```
