### ISSUE TITLE
Financials Object seems to be missing data many JSON objects

### ISSUE THREAD

**Issue by mmontefl** [iexg/IEX-API#219]
## Summary
When looking for TotalDebt or my TotalCash, so many dont have that. Sort of important for my analysis.

## Details
This is a bad example. As there are 3000-4000 that actually dont have many Debt and Cash entries.
[https://api.iextrading.com/1.0/stock/FL/financials]
{"symbol":"FL","financials":[{"reportDate":"2017-10-31","grossProfit":580000000,"costOfRevenue":1290000000,"operatingRevenue":1870000000,"totalRevenue":1870000000,"operatingIncome":155000000,"netIncome":102000000,"researchAndDevelopment":null,"operatingExpense":425000000,"currentAssets":2498000000,"totalAssets":3813000000,"totalLiabilities":1156000000,"currentCash":920000000,**"currentDebt":null**,"totalCash":890000000,"totalDebt":126000000,"shareholderEquity":2657000000,"cashChange":-153000000,"cashFlow":245000000,"operatingGainsLosses":null},{"reportDate":"2017-07-31","grossProfit":503000000,"costOfRevenue":1198000000,"operatingRevenue":1701000000,"totalRevenue":1701000000,"operatingIncome":122000000,"netIncome":51000000,"researchAndDevelopment":null,"operatingExpense":381000000,"currentAssets":2644000000,"totalAssets":3946000000,"totalLiabilities":1052000000,"currentCash":1073000000,**"currentDebt":null**,"totalCash":1043000000,"totalDebt":126000000,"shareholderEquity":2894000000,"cashChange":-4000000,"cashFlow":92000000,"operatingGainsLosses":null},{"reportDate":"2017-04-30","grossProfit":680000000,"costOfRevenue":1321000000,"operatingRevenue":2001000000,"totalRevenue":2001000000,"operatingIncome":268000000,"netIncome":180000000,"researchAndDevelopment":null,"operatingExpense":412000000,"currentAssets":2622000000,"totalAssets":3877000000,"totalLiabilities":1055000000,"currentCash":1077000000,"currentDebt":null,"totalCash":1049000000,"totalDebt":127000000,"shareholderEquity":2822000000,"cashChange":4000000,"cashFlow":159000000,"operatingGainsLosses":-25000000},{"reportDate":"2017-01-31","grossProfit":713000000,"costOfRevenue":1400000000,"operatingRevenue":2113000000,"totalRevenue":2113000000,"operatingIncome":284000000,"netIncome":189000000,"researchAndDevelopment":null,"operatingExpense":429000000,"currentAssets":2633000000,"totalAssets":3840000000,"totalLiabilities":1130000000,"currentCash":1046000000,"currentDebt":null,"totalCash":1046000000,"totalDebt":127000000,"shareholderEquity":2710000000,"cashChange":180000000,"cashFlow":339000000,"operatingGainsLosses":-3000000}]}

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
