### ISSUE TITLE
Request: combination of fields from Top and Book

### ISSUE THREAD

**Issue by fimmugit** [iexg/IEX-API#22]
Is it possible to provide a single API call to collect at least these fields:
open, high, low, prev_close, volume, latest_price, last_size, last_time, asks[], bids[]

in which asks[] and bids[] follow the same format of book.

**Comment by joshuablackburn-iex** [comment]
This feature has been added and documentation has been updated.  It is a new endpoint called /stock/{symbol}/book

**Comment by fimmugit** [comment]
Hi, I appreciate what you did to enhance our experience of using IEX's APIs. I just checked the new addition and found several fields I requested are missing (open, high, low) . In addition, it only support one ticker symbol at a time which will have an impact if I have many tickers to update. With some testing, I realized that the TOP and BOOK APIs support around 10 and up symbols. What I try to achieve is to minimize the number of requests to reduce server's load. One way to do that is to make useful info available in one call and the other is to accept as many symbols as possible. For example, Tradier's quote API support many fields and set no limit to the number of symbols in one call (https://developer.tradier.com/documentation/markets/get-quotes). 

For now, I though it might be better to add these fields (open, high, low, prev_close, volume, latest_price, last_size, last_time) to the original book call (deep/book?symbols=symbol list). Can you do that in stead, PLEASE？I am sure IEX will support more features in the future. Keep the good things going to the right direction!
