### ISSUE TITLE
Documentation lacks explanation of what the objects represent

### ISSUE THREAD

**Issue by mmontefl** [iexg/IEX-API#220]
## Summary
https://iextrading.com/developer/docs/#financials

https://iextrading.com/developer/docs/#earnings

## Details
These pages lack explanation of what the objects are exactly

**Comment by helgasoft** [comment]
Also in https://iextrading.com/developer/docs/#key-stats:
peRatioHigh and peRatioLow - are they for a time period and, if yes, what period ?

**Comment by henadzit** [comment]
Same issue!

**Comment by timpaine-iex** [comment]
closing as stale
