### ISSUE TITLE
Some stocks on  /tops/last have price value "0" but on /stock/{symbol}/quote quote was updated a few minutes ago

### ISSUE THREAD

**Issue by stepanmikhaylov-sprinklebit** [iexg/IEX-API#223]
## Details
On February 13 stock GLF quote was updated several times on /stock/{symbol}/quote but it was "price": 0 on /tops/last during whole day
### Date/time of issue

Febrauary 13

### API URL
/tops/last
/stock/{symbol}/quote 

### What you expected to happen
updated price for GLF stock on /tops/last

### What actually happened
price wasn't updated for GLF stock on /tops/last

### Other Information (sample code, links, etc.)
![glf](https://user-images.githubusercontent.com/30049320/36199465-5bb4ac52-1182-11e8-98cc-9470a51e2db9.png)
![glftops](https://user-images.githubusercontent.com/30049320/36199466-5bd71fe4-1182-11e8-9ce5-d5dfc0d0cf1e.png)

**Comment by joshuablackburn-iex** [comment]
TOPS is a data feed of trading on IEX.  This resets daily to match the binary data feed.  The Stock endpoint blends a number of datasources, and is more useful for building applications.

**Comment by stepanmikhaylov-sprinklebit** [comment]
Thank you, @joshuablackburn-iex !
