### ISSUE TITLE
Adjusted close data

### ISSUE THREAD

**Issue by andrewbruce01** [iexg/IEX-API#224]
## Summary

In the docs for charting, there should be a 'close' and an 'unadjustedclose' data point. "unadjustedclose' does not exit when when I query the data. I am assuming 'close' is referring to the adjusted close. Is this correct?

## Details

Docs: https://iextrading.com/developer/docs/#chart

// .../3m

[
    {
        "date": "2017-04-03",
        "open": 143.1192,
        "high": 143.5275,
        "low": 142.4619,
        "close": 143.1092,
        "volume": 19985714,
        "unadjustedClose": 143.7,
        "unadjustedVolume": 19985714,
        "change": 0.039835,
        "changePercent": 0.028,
        "vwap": 143.0507,
        "label": "Apr 03, 17",
        "changeOverTime": -0.0039
    } // , { ... }
]

### Date/time of issue

Feb 14, 2018

### API URL

https://api.iextrading.com/1.0/stock/aapl/chart/3m

### What you expected to happen

I expect to see a 'close' and 'unadjustedclose' data point in the response string. 

### What actually happened

[{"date":"2017-11-13","open":173.5,"high":174.5,"low":173.4,"close":173.97,"volume":16982080,"unadjustedVolume":16982080,"change":-0.7,"changePercent":-0.401,"vwap":174.0077,"label":"Nov 13, 17","changeOverTime":0},....

**Comment by MichaelZhangCA** [comment]
It seems the API returns un-adjusted close price in the "close" field now.

below is copied from https://api.iextrading.com/1.0/stock/AAPL/chart/3m @ 22:51, March 5th. All the close prices are a un-adjusted price.

{"date":"2018-02-06","open":154.83,"high":163.72,"low":154,"close":**163.03**,"volume":68243838, "unadjustedVolume":68243838,"change":6.54,"changePercent":4.179,"vwap":159.6072,"label":"Feb 6","changeOverTime":-0.03896486677670352},
{"date":"2018-02-07","open":163.085,"high":163.4,"low":159.0685,"close":**159.54**,"volume":51608580, "unadjustedVolume":51608580,"change":-3.49,"changePercent":-2.141,"vwap":161.0779,"label":"Feb 7","changeOverTime":-0.0595378448479132},
{"date":"2018-02-08","open":160.29,"high":161,"low":155.03,"close":**155.15**,"volume":54390516," unadjustedVolume":54390516,"change":-4.39,"changePercent":-2.752,"vwap":158.9999,"label":"Feb 8","changeOverTime":-0.08541617543032293}

AAPL had an ex-dividend on Feb 9th from https://api.iextrading.com/1.0/stock/AAPL/dividends/1m, which also cross-checked from other data sources.

[{"exDate":"2018-02-09","paymentDate":"2018-02-15","recordDate":"2018-02-12","declaredDate":"2018-02-01","amount":0.63,"flag":"","type":"Dividend income","qualified":"Q","indicated":""}]

**Comment by ajs11174** [comment]
This appears to be incorrect. The chart endpoint is returning adjusted closes not actual closes. For Apple and the dividend mentioned above, here is what the endpoint is returning as of 5/27/18.

**{"date":"2018-02-09"**,"open":156.4667,"high":157.2835,"low":149.6629,**"close":155.8092**,"volume":70672608,"unadjustedVolume":70672608,"change":1.8828,"changePercent":1.223,"vwap":154.2602,"label":"Feb 9, 18","changeOverTime":-0.0978936075235167}

Here is the close and adjusted close data from Yahoo:
[https://finance.yahoo.com/quote/AAPL/history?period1=1518066000&period2=1518152400&interval=1d&filter=history&frequency=1d](https://finance.yahoo.com/quote/AAPL/history?period1=1518066000&period2=1518152400&interval=1d&filter=history&frequency=1d )

In the above post the close price is listed as 155.15 which is definitely the actual close price on 2/8/18. Again when I hit the 6M chart endpoint for Apple, here is what came back.

**{"date":"2018-02-08"**,"open":159.0259,"high":159.7303,"low":153.8074,**"close":153.9264**,"volume":54390516,"unadjustedVolume":54390516,"change":-4.3554,"changePercent":-2.752,"vwap":157.746,"label":"Feb 8, 18","changeOverTime":-0.10879467059138898}

At some point between March 5th (@MichaelZhangCA's post) and today May 27th. The nature of how the close field is calculating changed. I would imagine it would make sense to report both the adjusted close and the actual/unadjusted close for clarity purposes.

**Comment by asreid2527** [comment]
I noticed this on SPY data today when calculating a MA greater than 50.  The close price is adjusted historically once the dividend is paid, so the close price is correct from now to 3/16/2018 (dividend pay out day) but prior to 3/15 need to add the dividend in to get the correct unadjusted close price.  

Can this be fixed?

**Comment by esc952** [comment]
Is there any update on this?

Also, who the heck are they adjusting for dividends.  For example SFNC paid a $0.15 dividend on 6/14/18...but some prices are "adjusted 0.1500 and others adjusted up to 0.1568 and others much less.

2018-05-29	31.0533	31.2524	30.7547	31.1031	487733	**-0.1469**
2018-05-30	31.3021	32.0984	30.8542	31.8495	481807	-0.1505
2018-05-31	31.7998	32.1979	31.3519	31.8495	594982	-0.1505
2018-06-01	32.0984	32.4467	31.4514	32.2477	412152	-0.1523
2018-06-04	32.3472	32.7453	32.0486	32.6955	294356	-0.1545
2018-06-05	32.7453	32.8448	32.2477	32.4965	261070	-0.1535
2018-06-06	32.5462	33.1932	32.0984	33.1932	329492	**-0.1568**
2018-06-07	33.2927	33.2927	32.5214	32.6458	332787	-0.1542
2018-06-08	32.6955	32.7453	32.2477	32.3969	347984	-0.1531
2018-06-11	32.5960	32.6458	31.8993	31.9988	387429	-0.1512
2018-06-12	32.1481	32.1979	31.5012	31.7998	302964	-0.1502
2018-06-13	31.7500	32.1481	31.4514	31.7500	346193	**-0.1500**
2018-06-14	31.8500	31.9000	31.3250	31.7000	376568	0.0000
2018-06-15	31.5000	31.8000	31.2500	31.5500	1881422	0.0000

Thanks in advance for any help/clue.

**Comment by JohnRobson** [comment]
Any update?!  Please, add "unadjusted close price", very important data.

**Comment by evancarter-iex** [comment]
IEXCloud has this data:
https://iexcloud.io/docs/api/#historical-prices

https://iexcloud.io
