### ISSUE TITLE
Stocks/Chart endpoint returns empty

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#225]
## Summary

Stocks/chart endpoint returning empty intermittently in for both individual tickers and batch requests. Seems if you make about 10 requests it usually fails for 1-2 of them (returning an empty list)

### Date/time of issue

2/14/2018 9PM PST

### API URL

https://api.iextrading.com/1.0/stock/aapl/chart

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,tsla&types=chart

### What you expected to happen

Single

>[
    {
        "date": "2017-12-15"
        "minute": "09:30",
        "label": "09:30 AM",
        "high": 143.98,
       ....

Batch

> {"AAPL":{"chart":[{"date":"2018-01-16","open":177.9,"high":179.39,"lo

### What actually happened

Single

> []

Batch

> [{"AAPL" :  []}, [{"TSLA": []}]

**Comment by eliezerlp** [comment]
Encountered exactly the same issue this morning with at least the following symbols:

AAPL, AAWW, AFSI, ANDAU, ANTM, AZRX, BEDU, BFR, BOXL, CADC, CBAK, CBS.A, CDMOP, CIZN, CRVP, CTIC, CX, DLR, EDGE, EFR, EFX, ENSG, ETV, FAT, FLAG, FSP, FT, GFNCP, GLDD, GPI, HMTV, HPQ, IBKC, IGD, IMMR, IRMD, ISSC, JACK, JONE, KONA, LAMR, LHO, LVS, MDCO, MGYR, MIY, NATR, NK, NNN, NRIM, NYMT, OBAS, OBE, ORC, PARR, PDM, PTNR, PYDS, RDUS, SNV, SRC, STKL, TI.A, TIG, UBIO, UPS, VGZ, VRNS, VVV, WIRE, XON, YUM

**Comment by joshuablackburn-iex** [comment]
This should be resolved.  Please let us know if you continue to experience this issue.

**Comment by eliezerlp** [comment]
@joshuablackburn-iex, seems to have recreated early this morning.

My logging is not the best but I've been able to see the following. We made about 8,500 requests from around 3:07 - 3:13 AM EST. Of those it seems that at least 8,459 of them did not return the data we expected.

Unfortunately I can't confirm if they returned empty `[]` or if they were simply missing data for 2017-02-15.

We were targeting the following endpoint: `https://api.iextrading.com/1.0/stock/a/chart/1m`

**Comment by joshuablackburn-iex** [comment]
the 1m chart is 1 month.  8500 requests in 6 minutes is about 23 requests a second.  Is that your expected behavior?  1 month data does not change intraday and does not include the current trading day.  I just confirmed that all data is returning properly.

**Comment by rterp** [comment]
We are seeing this behavior as well.  We are looping through all tickers once per day using the 1m endpoint
https://api.iextrading.com/1.0/stock/aapl/chart/1m

We are seeing random tickers return an empty string for their data results.  If we hit the endpoint again manually at a later point, we are usually able to get the data for the tickers that failed.

Any idea what is going on here?

**Comment by erichodges** [comment]
I've been seeing this happen as well. Also, the same request will sometimes return only the first day of data. Tested when requesting a 1y of data.
