### ISSUE TITLE
Quote data a day behind 

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#226]
## Summary
At 8:08am eastern on Feb 16 the quote calculationPrice is PREVIOUSCLOSE but the /PREVIOUS endpoint and the quote's latestPrice are still still from 2018-02-14

## Details
Note the /ohlc reflects the close from 2018-02-15 (as expected)

### Date/time of issue
As noted in summary

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote,previous,ohlc

### What you expected to happen
/previous to contain info for 2018-02-15

### What actually happened
{
  "AAPL": {
    "quote": {
      "symbol": "AAPL",
      "companyName": "Apple Inc.",
      "primaryExchange": "Nasdaq Global Select",
      "sector": "Technology",
      "calculationPrice": "previousclose",
      "open": 169.85,
      "openTime": 1518705000709,
      "close": 172.99,
      "closeTime": 1518728400253,
      "high": 173.09,
      "low": 169,
      "latestPrice": 167.37,
      "latestSource": "Previous close",
      "latestTime": "February 14, 2018",
      "latestUpdate": 1518566400000,
      "latestVolume": 50830397,
      "iexRealtimePrice": 0,
      "iexRealtimeSize": 0,
      "iexLastUpdated": 0,
      "delayedPrice": 172.99,
      "delayedPriceTime": 1518731985955,
      "previousClose": 167.37,
      "change": 0,
      "changePercent": 0,
      "iexMarketPercent": 0,
      "iexVolume": 0,
      "avgTotalVolume": 41363516,
      "iexBidPrice": 0,
      "iexBidSize": 0,
      "iexAskPrice": 0,
      "iexAskSize": 0,
      "marketCap": 849237555810,
      "peRatio": 18.19,
      "week52High": 180.1,
      "week52Low": 134.8398,
      "ytdChange": -0.02838732149076969
    },
    "previous": {
      "symbol": "AAPL",
      "date": "2018-02-14",
      "open": 163.045,
      "high": 167.54,
      "low": 162.88,
      "close": 167.37,
      "volume": 40644933,
      "unadjustedVolume": 40644933,
      "change": 3.03,
      "changePercent": 1.844,
      "vwap": 165.5906
    },
    "ohlc": {
      "open": {
        "price": 169.85,
        "time": 1518705000709
      },
      "close": {
        "price": 172.99,
        "time": 1518728400253
      },
      "high": 173.09,
      "low": 169
    }
  },
  "FB": {
    "quote": {
      "symbol": "FB",
      "companyName": "Facebook Inc.",
      "primaryExchange": "Nasdaq Global Select",
      "sector": "Technology",
      "calculationPrice": "previousclose",
      "open": 180.38,
      "openTime": 1518705000374,
      "close": 179.96,
      "closeTime": 1518728400291,
      "high": 180.5,
      "low": 176.84,
      "latestPrice": 179.52,
      "latestSource": "Previous close",
      "latestTime": "February 14, 2018",
      "latestUpdate": 1518566400000,
      "latestVolume": 20683392,
      "iexRealtimePrice": 0,
      "iexRealtimeSize": 0,
      "iexLastUpdated": 0,
      "delayedPrice": 180.15,
      "delayedPriceTime": 1518731999958,
      "previousClose": 179.52,
      "change": 0,
      "changePercent": 0,
      "iexMarketPercent": 0,
      "iexVolume": 0,
      "avgTotalVolume": 27395223,
      "iexBidPrice": 0,
      "iexBidSize": 0,
      "iexAskPrice": 0,
      "iexAskSize": 0,
      "marketCap": 521505736076,
      "peRatio": 29.19,
      "week52High": 195.32,
      "week52Low": 132.9,
      "ytdChange": -0.010472935729246926
    },
    "previous": {
      "symbol": "FB",
      "date": "2018-02-14",
      "open": 173.45,
      "high": 179.81,
      "low": 173.2119,
      "close": 179.52,
      "volume": 28929704,
      "unadjustedVolume": 28929704,
      "change": 6.37,
      "changePercent": 3.679,
      "vwap": 177.2824
    },
    "ohlc": {
      "open": {
        "price": 180.38,
        "time": 1518705000374
      },
      "close": {
        "price": 179.96,
        "time": 1518728400291
      },
      "high": 180.5,
      "low": 176.84
    }
  }
}

**Comment by joshuablackburn-iex** [comment]
I failed to mention before there is a window at the start of the trading day where the latest price we have is previous close.  If IEX doesn't have a trade we fall back to 15 minute delayed SIP, so that means we won't have a price from 8-8:14am.

**Comment by McQaws** [comment]
Josh, I understand the 15m window but shouldn't previous be from Feb 15 - not Feb 14 as returned in my example?

**Comment by joshuablackburn-iex** [comment]
The previous close in quote doesn't update until trading starts at 9:30 per a prior user request to match the behavior of Yahoo Finance. #20
