### ISSUE TITLE
OpenSSL HandShake error

### ISSUE THREAD

**Issue by aseshuk** [iexg/IEX-API#228]
## Summary
Ruby Endpoint not working while sending requests thru proxy. Getting OpenSSL handshake failure

## Details
While testing a endpoint we are getting 
Received fatal alert: handshake_failure (OpenSSL::SSL::SSLError) 
on one of our server which is behing firewalls and uses proxy to access Internet

Wget to the https://api.iextrading.com/1.0/stock/aapl/quote return 200K on the terminal 

On further analysis on OpenSSL we are getting timeout 
 openssl s_client -showcerts -connect api.iextrading.com:443
connect: Connection timed out
connect:errno=110

Do we know why the server is rejecting the request. 
What will be a workaround to resolve it. 
Any specifics certificates are expected to make it work?

### Date/time of issue
02/16/2018 10:45AM 

### API URL
https://api.iextrading.com/1.0/stock/aapl/quote 

### What you expected to happen
Expected JSON details (Which we do get from browser within the same network) 
{"symbol":"AAPL","companyName":"Apple Inc.","primaryExchange":"Nasdaq Global Select","sector":"Technology","calculationPrice":"tops","open":172.4,"openTime":1518791400457,"close":172.99,"closeTime":1518728400253,"high":174.582,"low":171.77,"latestPrice":173.85,"latestSource":"IEX real time price","latestTime":"11:48:48 AM","latestUpdate":1518799728323,"latestVolume":17553226,"iexRealtimePrice":173.85,"iexRealtimeSize":100,"iexLastUpdated":1518799728323,"delayedPrice":174.42,"delayedPriceTime":1518798831511,"previousClose":172.99,"change":0.86,"changePercent":0.00497,"iexMarketPercent":0.03534,"iexVolume":620331,"avgTotalVolume":41363516,"iexBidPrice":173.85,"iexBidSize":100,"iexAskPrice":176.88,"iexAskSize":100,"marketCap":882117160050,"peRatio":18.9,"week52High":180.1,"week52Low":134.8398,"ytdChange":0.0042377800998491715}

### What actually happened
Connection from Application server is rejected

**Comment by evancarter-iex** [comment]
What ip are you connecting from?

**Comment by aseshuk** [comment]
my server is behind a firewall and going thru proxy. so Ip I see might not be same that hits the site
Wanted to check what version of JDM the api is compatible with.. we are using openJDk 1.8 - java-1.8.0-openjdk-1.8.0.

Do I need to upgrade?

**Comment by evancarter-iex** [comment]
That should be fine.

**Comment by evancarter-iex** [comment]
Are you still having this problem? We arent seeing any issues on our side.
