### ISSUE TITLE
Request to add dividend amount to quote on exdiv date

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#229]
## Summary
Please enhance the API to include the dividend amount for a quote on the exdiv date.  

## Details
Schwab, Google, and others report a day's change amount and percentage using an adjusted previous close.  That is, on the exdiv date they subtract the dividend amount from the previous day's close and show the current day's price change in relation to that.  This is not possible with IEX API - or at least I could not find the dividend.

For example, for UPS, Feb 16 is an exdiv date.  The actual close on Feb 15 was 108.31 but Schwab shows 107.40 as the previous close during the trading day due to the 0.91 dividend.  Schwab shows the change amount and percent during trading and at close for Feb 16 in relation to 107.40.

### Date/time of issue
Feb 16 3:55pm EST.

### API URL
https://api.iextrading.com/1.0/stock/ups/dividends/1m

### What you expected to happen
I was hoping to be able to find the dividend amount on the exdiv date so I could calculate the adjusted change amount and percent as do Google, Schwab, and others.

### What actually happened
I could not find the dividend amount on the exdiv date.  I tried the /dividends/1m endpoint but it was empty for ups even near the close of the exdiv date and I would need the dividend amount at the start of trading to be able to derive the adjusted change.

### Other Information (sample code, links, etc.)
Ideally you would factor the dividend in when you display change and change percent as the others do.  But, at least if you provide the divident amount I can derive it accordingly.

**Comment by evancarter-iex** [comment]
This should be fixed in IEXCloud. https://iexcloud.io
