### ISSUE TITLE
chart excluding current session (non 1D)

### ISSUE THREAD

**Issue by scottycc** [iexg/IEX-API#23]
https://api.iextrading.com/1.0/stock/aapl/chart/3m

The current trading session (today) does not show, it also does not show in the evening after the session is closed. 

As is I would have to make an additional API hit to generate a historic chart that included a candlestick at the end for the current session, is that intended? 

Thanks!

**Comment by joshuablackburn-iex** [comment]
All non 1D chart ranges are historical, adjusted data only.  We must wait for official data from the exchanges before we update.  The historical charts get updated after midnight.

**Comment by scottycc** [comment]
Ok, thanks.
