### ISSUE TITLE
Intraday charts should also support OHLC format

### ISSUE THREAD

**Issue by absinha18** [iexg/IEX-API#230]
## Summary
Requesting data from https://api.iextrading.com/1.0/stock/aapl/chart/1d endpoint returns 1 minute data but it does not include open and close. it just has high, low and average. 

## Details
Request to add OHLC formatted data for intraday charts much like 1m , 1y or month or 5y charts. Its not possible to build a technical charting solution without such data.

### API URL

https://api.iextrading.com/1.0/stock/aapl/chart/1d

### What you expected to happen

OHLC data for each period of data returned and not just low, high and average.

**Comment by coreyauger** [comment]
Same as: https://github.com/iexg/IEX-API/issues/196

**Comment by absinha18** [comment]
Is there a timeline on when this can be made available? We could really use ohlc on an intraday hourly chart .. thanks !

**Comment by absinha18** [comment]
Requesting an update on this one? When can we expect this to be rolled into production?

Thanks

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud https://iexcloud.io
