### ISSUE TITLE
Requesting enhancements to the chart endpoint

### ISSUE THREAD

**Issue by absinha18** [iexg/IEX-API#231]
## Summary

Chart endpoints ideally can just expose 1 endpoint like 

/stock/aapl/chart/

and allow further query parameters. Instead of multiple endpoints which currently exists (helps in simplifying clients as well as more intuitive in usage):
/stock/aapl/chart/5y
/stock/aapl/chart/2y
/stock/aapl/chart/1y
/stock/aapl/chart/ytd
/stock/aapl/chart/6m
/stock/aapl/chart/3m
/stock/aapl/chart/1m
/stock/aapl/chart/1d

Suggested changes in details section:

## Details

Allow query parameters

start=<date>
end=<date>
chartInterval = <period of time>
chartIntervalFunction = <intraDay/Daily/Weekly/Monthly>

start = starting date of requested chart data in YYYY-MM-DD format
end = ending date of requested chart data in YYYY-MM-DD format

chartInterval which currently exists as a parameter to return Nth element should ideally be a unit of time as suggested above:
ie. 

1. a multiple of 1min OHLC data when chartIntervalFunction is "intraday".
2. a multiple of 1Day OHLC data when chartIntervalFunction is "daily".
3. a multiple of 1Week OHLC data when chartIntervalFunction is "weekly".
4. a multiple of 1Month data when chartIntervalFunction is "monthly".

### API URL

/stock/aapl/chart/

**Comment by evancarter-iex** [comment]
Individual chart days are fixed with IEXCloud. We are working on ranges.

https://iexcloud.io
