### ISSUE TITLE
Return only the single latest data point 

### ISSUE THREAD

**Issue by mfhawley** [iexg/IEX-API#233]
## Summary
How do you return only the single latest or a truncated group of the latest data points?
I only see options to return a full day, full month, full year, etc.

## Details
Examples:

1. How to return only the latest 10 1-minute candlestick data points  (high, low, close, open, volume, etc)  for a given stock (or preferably a batch of stocks)
- Currently the only option is to download an entire day, entire year, etc

2. How to return a single 1-week or 1-month candle stick representing the latest week or month for a single stock (or preferably a batch of stocks).
- Currently, the closest option is to download a bunch of daily data and manually calculate all the lows, highs, open, latest close price, volume, etc

### Date/time of issue
2/22/2018 10:20am PST

**Comment by absinha18** [comment]
I had opened #231 which will also help this.

**Comment by joshuablackburn-iex** [comment]
You can now fetch n number of chart items by using the parameter chartLast.  Ex:  https://api.iextrading.com/1.0/stock/aapl/chart/1d?chartLast=5

**Comment by timpaine-iex** [comment]
closing as stale
