### ISSUE TITLE
/market/OHLC missing data

### ISSUE THREAD

**Issue by megaskills** [iexg/IEX-API#234]
## Summary
The stock/market/OHCL appears to be reporting data incorrectly. The sample below (taken 8:17pm) shows the first symbol as "0" with a high/low price and all subsequent symbols only having Open/Close.
According to the doc, all symbols should have a OHLC. Also, if I call the stock/AAPL/OHLC endpoint the data format is as expected.

## Details
Unexpected data format
{"0":{"high":273.05,"low":269.64},"SNOAW":{"open":{"price":0.43,"time":1519322805059},"close":{"price":0.43,"time":1519333200247}},"LEG":{"open":{"price":44.98,"time":1519309809434},"close":{"price":44.36,"time":1519333335348}},"GRUB":{"open":{"price":97.91,"time":1519309800366},"close":{"price":98.27,"time":1519333287301}},"CDNA":{"open":{"price":5.39,"time":1519309800438},"close":{"price":5.23,"time":1519333200341}},"NOMD":{"open":{"price":16.82,"time":1519309800603},"close":{"price":16.8,"time":1519333321625}},"TRGP":{"open":{"price":47.03,"time":1519309800757},"close":{"price":45.96,"time":1519333285895}},"GLMD":{"open":{"price":5.59,"time":1519309800079},"close":{"price":5.4,"time":1519333200203}},"ZN":{"open":{"price":4.19,"time":1519309800418},"close":{"price":4.185,"time":1519333200230}},"RTH":{"open":{"price":96.64,"time":1519309800123},"close":{"price":96.465,"time":1519333200283}},"TK":{"open":{"price":7.74,"time":1519309968907},"close":{"price":7.8,"time":1519333322735}},"TCBIP":{"open":{"price":25.45,"time":1519309800589},"close":{"price":25.5,"time":1519333200311}},"GWGH":{"open":{"price":8.83,"time":1519313200444},"close":{"price":8.79,"time":1519333200343}},"NRK":{"open":{"price":12.33,"time":1519309800605},"close":{"price":12.27,"time":1519333322412}},
### Date/time of issue
02/22/2018 8:17pm EDT

### API URL
/stock/market/ohlc

### What actually happened
the data format in the extract is not in the expected format.

**Comment by mguardos** [comment]
I have also noticed this same issue during the past few days. Providing some additional info in case it helps finding the problem.

Even though it returns all stocks opening and closing prices, it does not list the high nor the low values for them, although it returns a random number of high-low pairs sorted by a numeric index: 0, 1, 2 ... n

**Comment by megaskills** [comment]
Thanks Josh, unfortunately not fixed. Below is the tail end of an extract I just ran, note there is no high/low prices for each symbol throughout the entire extract except for the last row, and note the last field is "[object Object]":{"high":null,"low":null}}

https://api.iextrading.com/1.0/stock/market/ohlc

{"price":29.373,"time":1519851600205}},"AEUA":{"close":{"price":32.5,"time":1519851830582}},"CYS-B":{"close":{"price":24.08,"time":1519851720885}},"ESGW":{"close":{"price":30.429,"time":1519851600172}},"HFXE":{"close":{"price":19.88,"time":1519851600203}},"CIC":{"close":{"price":9.67,"time":1519851724140}},"CBB-B":{"close":{"price":49.3,"time":1519854300004}},"CIC+":{"close":{"price":1.13,"time":1519851724140}},"SMDD":{"close":{"price":10.185,"time":1519851600195}},"AZRE":{"close":{"price":16.35,"time":1519854300004}},"[object Object]":{"high":null,"low":null}}

**Comment by liuyigh** [comment]
Please fix this. Thanks!

**Comment by evancarter-iex** [comment]
@megaskills is this still a problem in IEXCloud?

**Comment by evancarter-iex** [comment]
This is fixed with IEXCloud. https://iexcloud.io
