### ISSUE TITLE
Quote shows previous closing price after Market Close

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#235]
## Summary
Closing Quote after market close shows last price and closing price from previous session (2/22) instead of the latest closing session (2/23).

## Details

symbol | "AMZN"
-- | --
companyName | "Amazon.com Inc."
primaryExchange | "Nasdaq Global Select"
sector | "Technology"
calculationPrice | "close"
open | 1494.2
openTime | 1519396200505
close | 1485.34
closeTime | 1519419600412
high | 1500
low | 1486.5
latestPrice | 1485.34
latestSource | "Close"
latestTime | "February 23, 2018"
latestUpdate | 1519419600412
latestVolume | 4382140
iexRealtimePrice | null
iexRealtimeSize | null
iexLastUpdated | null
delayedPrice | 1499.75
delayedPriceTime | 1519423190404
previousClose | 1482.92
change | 2.42
changePercent | 0.00163
iexMarketPercent | null
iexVolume | null
avgTotalVolume | 6502729
iexBidPrice | null
iexBidSize | null
iexAskPrice | null
iexAskSize | null
marketCap | 719063763197
peRatio | 325.73
week52High | 1503.49
week52Low | 833.5
ytdChange | 0.24922414445631233

### Date/time of issue

2018-2-24

### API URL

https://api.iextrading.com/1.0/stock/amzn/quote

### What you expected to happen

The closing price and change should be the quote on 2018-2-23.

### What actually happened

The closing price and change came from the end of day quote on 2018-2-22.

**Comment by aokellermann** [comment]
The "chart" endpoint has the same issue. The last JSON index is 2/22 instead of 2/23. However, other endpoints such as "ohlc" don't seem to be affected.

**Comment by BullMarket** [comment]
Yep, this was throwing off my analysis as well.  I have to now stop using closing price until it's fixed. Please address this at your earliest convenience.

**Comment by BullMarket** [comment]
This could very well be a problem with the data feed IEX and other vendors use. My brokers E*TRADE/OPTIONSHouse is also reporting  AMZN closing price is 1,485.34 for 02/23 instead of 1,500 which is the actual closing price on 02/23. [Link](https://ibb.co/f2gCDH)

**Comment by evancarter-iex** [comment]
The closing price has now been updated.
