### ISSUE TITLE
Open price is not up to date

### ISSUE THREAD

**Issue by yuvalshtemer** [iexg/IEX-API#236]
## Summary

Dear team, I noticed that when pulling data from the web api on beginning of trading day, I'm getting a correct previous close value but the open price seems not to be updated, and updates only later throughout the day.

## Details

This is an example of the API call I'm sending:
https://api.iextrading.com/1.0/stock/market/batch?symbols=goog&types=quote&range=1d&filter=symbol,previousClose,open

**Comment by joshuablackburn-iex** [comment]
Please see the latest comment on #180

**Comment by megaskills** [comment]
Also per the documents the open price is delayed - so typically it's not updated until 9:45 but I think it also depends on whether IEX has an updated quote. Some stocks have staggered opening so first trade will be 9:31 or 9:32 with open price update at 9:46 & 9:47 for example
