### ISSUE TITLE
Enhancement: Add VWAP to quote request

### ISSUE THREAD

**Issue by BullMarket** [iexg/IEX-API#237]
## Summary

VWAP isn't returned when making a "/quote" requests. 

## Details
VWAP is currently being returned when you make "/previous" and "/chart" requests. Is there a technical or a specific reason for not returning VWAP in the "/quote" response?   I understand it may not be feasible to return VWAP intraday (out of scope for this api call?) but we're returning closing price here so after 4 pm VWAP can be returned?

VWAP is  a fairly important metric which I primarily used and also by most institutions and traders alike.  I'm having to now make additional request to "/previous" endpoint simply get VWAP a day later.  It's a waste of resource for both IEX and API users to make whole bunch of calls simply to get one data point. 

### Date/time of issue
N/A

### API URL
https://api.iextrading.com/1.0/stock/aapl/quote

### What you expected to happen
JSON response should include "VWAP" when making "/quote" request.

### What actually happened
No VWAP is  returned.

### Other Information (sample code, links, etc.)
NA

**Comment by BullMarket** [comment]
Hi @joshuablackburn-iex 

Following up here.  It would be awesome to have latest VWAP returned during market hours. I'm eagerly looking forward to this getting added. I sincerely and appreciate if this can go into the roadmap now. 

Thank you!

**Comment by joshuablackburn-iex** [comment]
Would a 15 minute delayed VWAP price satisfy your requirements?  I'm assuming you'll want market wide VWAP, and not just IEX VWAP, so the only source we can currently disseminate is 15 minute delayed SIP.

**Comment by BullMarket** [comment]
@joshuablackburn-iex Yes, we'd want market wide. Unfortunately 15 min delay isn't ideal. Also the /Quote endpoint returns everything in real time so having one piece of data with 15 min delay could cause confusion and more questions but perhaps the documentation would be helpful if it's noted specified there. 

If it isn't possible to have VWAP real time which I understand the limitation you've described, perhaps a compromise would be to just expose the field without a value during market hours or just 15 min delayed and update the  value after market closes based on the days closing price?  Just like it's exposed for "/previous" and "/chart". This would definitely help prevent me from making additional request just to get VWAP to other endpoints.

Thank you for everything you do!

**Comment by joshuablackburn-iex** [comment]
In the meantime, the /chart endpoint already gives you VWAP by minute.  You can sum all minutes marketNotional and divide by sum of marketVolume.  Remember, all keys prefixed with 'market' represent 15 minute delayed SIP.  We are unable to provide real-time SIP due to their restrictions and fee schedule.

**Comment by timpaine-iex** [comment]
closing as stale
