### ISSUE TITLE
Market depth API returns empty objects instead of nulls for certain properties

### ISSUE THREAD

**Issue by yay** [iexg/IEX-API#239]
## Summary
`auction` and `officialPrice` fields are empty objects after market close.

## Details
```json
"auction": {},
"officialPrice": {}
```

This can present deserialization problems (e.g. https://github.com/FasterXML/jackson-databind/issues/1885)
For example `"tradeBreaks": []` is fine, because if it's deserialized to `val tradeBreaks: List<Trade>`, it's just mapped to an empty list. But with an empty object `val officialPrice: OfficialPrice?`, we obviously have an error.

### Date/time of issue
Non-trading hours.

### API URL
https://api.iextrading.com/1.0/deep?symbols=snap

### What you expected to happen
```json
"auction": null,
"officialPrice": null
```

### What actually happened
```json
"auction": {},
"officialPrice": {}
```

### Other Information (sample code, links, etc.)

Some sample Kotlin code of data structures the response JSON is deserialized to.

```kotlin
    data class Deep(
        val symbol: String,
        val marketPercent: Double,
        val volume: Long,
        // ...
        val trades: List<Trade>,
        val tradeBreaks: List<Trade>,
        val auction: Auction? = null,
        val officialPrice: OfficialPrice? = null
    )

    data class Trade(
        val price: Double,
        val size: Int,
        val tradeId: Int,
        val isISO: Boolean,
        val isOddLot: Boolean,
        val isOutsideRegularHours: Boolean,
        val isSinglePriceCross: Boolean,
        val isTradeThroughExempt: Boolean,
        val timestamp: Date
    )

    data class OfficialPrice(
        val priceType: OfficialPriceType,
        val price: Double,
        val timestamp: Date
    )

    enum class OfficialPriceType {
        @JsonProperty("Open")
        OPEN,
        @JsonProperty("Close")
        CLOSE
    }
```

The rest of the APIs should probably be checked to make sure `null` is returned in place of `{}` as well.

**Comment by yay** [comment]
Just to add to this, `https://api.iextrading.com/1.0/tops?symbols=AAPL,AMZN` returns `[{},{}]` this Saturday.
`[null, null]` would be better.
`[]` would be better still ;)

**Comment by yay** [comment]
Subscribing to `https://ws-api.iextrading.com/1.0/deep` can also result in this kind of notifications:
```
{"symbol":"ORCL","messageType":"officialprice","data":{}}
{"symbol":"ORCL","messageType":"auction","data":{}}
```

Theres no data anyway, so I'd expect not to be notified at all.

**Comment by evancarter-iex** [comment]
@yay is this a problem on SSE in IEXCloud?

**Comment by yay** [comment]
I haven't tried IEXCloud yet.

**Comment by evancarter-iex** [comment]
@yay Okay I am closing this. If you see it in IEX Cloud with SSE please let us know. Just so you are aware, in June we are decommissioning IEX API 1.0.
https://iexcloud.io
