### ISSUE TITLE
All historical quotes

### ISSUE THREAD

**Issue by amborle** [iexg/IEX-API#24]
Hi,

I really like your API. 

Currently, you support 5 years of  EOD quotes e.g. https://api.iextrading.com/1.0/stock/aapl/chart/5y

I would appreciate if you could support an "all" chart, i.e. an option in the Chart API to get all quotes which you have on record (i.e. chart/all).

An option in the API to select a from and to date would also be highly appreciated, for instance;

- chart/fromDate=x&toDate=y (get all quotes between and including fromDate and toDate)
- chart/fromDate=x (get all quotes from fromDate until the most recent quotes )
- chart/toDate=y (get all quotes from "beginning of time" until toDate)

**Comment by shuwnyuantee** [comment]
I also run into a situation that I need > 5 years chart. Is it possible for IEX to provide either:

1) 10 years chart
2) `all` chart, which gives all historical EOD data you have on record?

@joshuablackburn-iex  Wonder if IEX have plan to add this? Thanks to you & IEX.

**Comment by joshuablackburn-iex** [comment]
This is actually in the works.  The plan is to support up to 20 years.

**Comment by amborle** [comment]
Fantastic!

**Comment by JohnRobson** [comment]
@joshuablackburn-iex few stocks have more than 20 years, so maybe you can support the full history for all stocks.

**Comment by Stafie** [comment]
@joshuablackburn-iex any updates on this?

**Comment by pianoboysai** [comment]
hope this can be supported quickly~

**Comment by wallingd** [comment]
+1 on this

**Comment by VictorChen** [comment]
is there a timeline for this?

**Comment by joshuablackburn-iex** [comment]
This is a limitation put in place by our data provider.  We are working with a new provider for version 2 which will include more historical data.  This is still planned for early Q4.

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. https://iexcloud.io
