### ISSUE TITLE
Previous whole market returns incomplete list of symbols

### ISSUE THREAD

**Issue by cdevonuk** [iexg/IEX-API#240]
## Summary

Previous, whole market is only returning a list of around 700 symbols (AA to BBT-H). Also some individual symbols are not updated with previous for 2018-02-28 for example : https://api.iextrading.com/1.0/stock/wltw/previous

Please advise at what time previous data is updated during the weekdays and when it is updated for Friday trading days.

Thank you

### Date/time of issue
1st March 2018 9am UK time

### API URL

https://api.iextrading.com/1.0/stock/market/previous

### What you expected to happen

A complete list of symbols with previous data for 2018-02-28

**Comment by cdevonuk** [comment]
This has happened again this weekend. Only symbols from AAC to IGET are displayed in the whole market previous feed.

Today’s date : 11 March 2018
Time : 08:25 GMT

**Comment by sdvisconti** [comment]
What is the earliest time of day that the prior day's complete data set is expected to be available for the https://api.iextrading.com/1.0/stock/market/previous endpoint?  I too have experienced partial information when invoking the API?

**Comment by evancarter-iex** [comment]
This is fixed with IEXCloud https://iexcloud.io
