### ISSUE TITLE
Inconsistent 3M Chart Data

### ISSUE THREAD

**Issue by massaroni** [iexg/IEX-API#241]
## Summary
In this case, the VWAP is out of range of the High/Low quotes.

## Details
Here's the data point in question:  {"date":"2017-12-08","open":12.3222,**"high":12.45,"low":12.3**,"close":12.3222,"volume":5692,"unadjustedVolume":5692,"change":-0.0228,"changePercent":-0.185,**"vwap":13.0548**,"label":"Dec 8, 17","changeOverTime":0.02685000000000004}

### Date/time of issue
Observed Friday March 2nd 2018 8:45AM EST

### API URL
https://api.iextrading.com/1.0/stock/BYBK/chart/3m

### What you expected to happen
I would expect the average quote to be consistent with the high and low quotes, it should be <=12.45 and >=12.3 in this case.  Or the high/low should be different, to match the vwap?

### What actually happened
VWAP was higher than the "high" quote.

**Comment by massaroni** [comment]
More inconsistent data for CEFS.  The Open price (21.94) is higher than the High price (21.622).

https://api.iextrading.com/1.0/stock/CEFS/chart/3m

{"date":"2018-01-30",**"open":21.94,"high":21.622**,"low":21.52,"close":21.6,"volume":3330,"unadjustedVolume":3330,"change":-0.1399,"changePercent":-0.644,"vwap":21.5754,"label":"Jan 30, 18","changeOverTime":0.017859667310682878}

**Comment by massaroni** [comment]
More inconsistent data for GCOW.  The Open price (32.53) is higher than the High price (32.455).

https://api.iextrading.com/1.0/stock/GCOW/chart/3m

{"date":"2018-01-11",**"open":32.53,"high":32.455**,"low":32.23,"close":32.43,"volume":44171,"unadjustedVolume":44171,"change":-0.1,"changePercent":-0.307,"vwap":32.3843,"label":"Jan 11, 18","changeOverTime":0.04222907828769765}

**Comment by massaroni** [comment]
More inconsistent data for HCRF.  The Open price (34.8) is higher than the High price (34.5267).

https://api.iextrading.com/1.0/stock/HCRF/chart/3m

{"date":"2018-01-30",**"open":34.8,"high":34.5267**,"low":34.26,"close":34.331,"volume":4569,"unadjustedVolume":4569,"change":-0.779,"changePercent":-2.219,"vwap":34.3951,"label":"Jan 30, 18","changeOverTime":0.08883602917856016}

**Comment by massaroni** [comment]
More inconsistent data for IMOM.  The Open price (33.06) is higher than the High price (32.944).

https://api.iextrading.com/1.0/stock/IMOM/chart/3m

{"date":"2018-01-26",**"open":33.06,"high":32.944**,"low":32.62,"close":32.7664,"volume":5403,"unadjustedVolume":5403,"change":0.2346,"changePercent":0.721,"vwap":32.8398,"label":"Jan 26, 18","changeOverTime":0.10659912191827078}

**Comment by massaroni** [comment]
More inconsistent data for IQDG.  The Open price (32.515) is higher than the High price (32.4099).

https://api.iextrading.com/1.0/stock/IQDG/chart/3m

{"date":"2018-01-30",**"open":32.515,"high":32.4099**,"low":32.335,"close":32.35,"volume":2525,"unadjustedVolume":2525,"change":-0.165,"changePercent":-0.507,"vwap":32.3692,"label":"Jan 30, 18","changeOverTime":0.06889852237582936}

**Comment by massaroni** [comment]
More inconsistent data for JPHY.  The Open price (51.28) is higher than the High price (51.279).

https://api.iextrading.com/1.0/stock/JPHY/chart/3m

{"date":"2018-01-30",**"open":51.28,"high":51.279**,"low":51.16,"close":51.2164,"volume":15815,"unadjustedVolume":15815,"change":-0.1434,"changePercent":-0.279,"vwap":51.2095,"label":"Jan 30, 18","changeOverTime":-0.0006556097560975581}

**Comment by massaroni** [comment]
Here's an interesting one.  Usually the Open is higher than the High, but in this case it's lower than the Low:

https://api.iextrading.com/1.0/stock/DIVB/chart/3m

{"date":"2018-03-05",**"open":20.77**,"high":26.26,**"low":24.05**,"close":26.26,"volume":6276,"unadjustedVolume":6276,"change":0.3,"changePercent":1.156,"vwap":25.7733,"label":"Mar 5","changeOverTime":0.015471830904218574}

Let me know if you need more examples.  I'll hold off on new ones unless I see a new type of problem.

**Comment by evancarter-iex** [comment]
@massaroni have you had a chance to test this on IEXCloud?

**Comment by massaroni** [comment]
Hi, thanks for following up.  I haven't taken a look at this in a long time, almost a year now.  I just implemented some workarounds on my end to scrub or ignore this kind of inconsistent data, instead of waiting for a comprehensive fix from IEX.

**Comment by evancarter-iex** [comment]
@massaroni okay sounds good. We changed data providers for IEXCloud, so Im going to close this. If you see it again in IEXCloud can you open a new bug? Thanks.
