### ISSUE TITLE
Not listed Dynamic Chart range

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#242]
## Summary

API returns not listed range for Dynamic Chart. 

### Date/time of issue

2018-03-02

### API URL

https://api.iextrading.com/1.0/stock/aapl/chart/dynamic

### What you expected to happen

>  Will return 1d or 1m data depending on the day or week and time of day. Intraday per minute data is only returned during market hours.

I expect to receive 1d or 1m value in range field in Dynamic Chart endpoint.

### What actually happened

I received 'today' value in range field. I guess it should be updated in docs.

### Other Information (sample code, links, etc.)

```
{
  "range": "today",
  "data": [
    {
      ...
    }
  ]
}
```

**Comment by evancarter-iex** [comment]
Documentation updated for IEX Cloud. https://iexcloud.io
