### ISSUE TITLE
Missing OfficialPrice in DEEP documentation

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#243]
## Summary

Missing OfficialPrice in DEEP documentation

### Date/time of issue

2018-03-02

### API URL

https://api.iextrading.com/1.0/deep?symbols=snap

### What you expected to happen

Have the response specified in the documentation.

### What actually happened

OfficialPrice has been added to DEEP response, but it is missing from documentation.

### Other Information (sample code, links, etc.)

https://iextrading.com/developer/docs/#deep

**Comment by joshuablackburn-iex** [comment]
We will update the DEEP section, but in the meantime, there is a specific section for Official Price.  https://iextrading.com/developer/docs/#official-price
