### ISSUE TITLE
Daily List API not consistent with rest of IEX API

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#244]
## Summary

Daily List API not consistent with rest of IEX API. Do you plan to do something with it or not?

### Date/time of issue

2018-03-02

### API URL

https://api.iextrading.com/1.0/ref-data/daily-list/corporate-actions
https://api.iextrading.com/1.0/ref-data/daily-list/dividends
https://api.iextrading.com/1.0/ref-data/daily-list/next-day-ex-date
https://api.iextrading.com/1.0/ref-data/daily-list/symbol-directory

### What you expected to happen

1. Field should be send in respective format, numbers as a numbers, string values as a string
2. If number data is not available then null should be returned?
3. If date value is not available then null should be returned?
4. Field values should be trimmed?

### What actually happened

1. Every field is being sent as a String
2. "0" or "" is returned for numbers if not available
3. "0" is returned for dates if not available
4. Some field like recordID is not trimmed

### Other Information (sample code, links, etc.)

That's how Jackson deserializers look like after new update in my library: https://github.com/WojciechZankowski/iextrading4j 😄 

```java
    @Override
    public BigDecimal deserialize(final JsonParser parser, final DeserializationContext ctx) throws IOException {
        final String val = parser.getValueAsString();

        // #HACK Sometimes instead of a null they return N/A in number field
        // #HACK In Daily List they return empty String if number is N/A
        if (val == null || "N/A".equalsIgnoreCase(val) || val.isEmpty()) {
            return null;
        }

        try {
            return parser.getDecimalValue();
        } catch (IOException e) {
            // #HACK In Daily List they return numbers as a String
            return new BigDecimal(val);
        }
    }
```

```java
    @Override
    public LocalDate deserialize(final JsonParser parser, final DeserializationContext context) throws IOException {
        final String val = parser.getValueAsString();

        // #HACK In Daily List they return "0" if data is not available
        if (val == null || val.equals("0")) {
            return null;
        }

        return super.deserialize(parser, context);
    }
```

**Comment by joshuablackburn-iex** [comment]
Daily List is not being used at this time beyond providing sample and test data for our IEX listed test securities.  This function is intended to directly support trading and the API has initially been modeled after existing Daily List specifications for industry adoption.  We will definitely look to standardize the data with the rest of our API as we ensure regulatory recipients are able to process.

**Comment by WojciechZankowski** [comment]
Makes sense, thank you!
