### ISSUE TITLE
ttmEPS Data inaccurate

### ISSUE THREAD

**Issue by snids** [iexg/IEX-API#245]
## Summary

ttmEPS Data on several stocks I have been pulling data for in Google Sheets isn't accurate, nor are the resulting PEs. 

## Details
For example, Hershey (HSY) epsTTM reports 4.76, which is non-GAAP diluted EPS from the 10-K. Reported diluted eps, which is what should be presented as ttmEPS is actually 3.66. Because IEX is using the wrong ttm data, the p/e is being calculated wrong as well--IEX reports a current HSY p/e of 20.77. The actual current p/e (98.87/3.66) is 26.986 (closing HSY price 3/2/18).

This seems to be occurring with other stocks I have checked (HOG, SBUX). I checked against Morningstar quarterly earnings data. It seems to ttmEPS data isn't being pulled correctly, wherever it's coming from

### Date/time of issue

4 p.m. Thailand

### API URL

https://api.iextrading.com/

### What you expected to happen

To get accurate data. See above.

### What actually happened

See above

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
