### ISSUE TITLE
Historical Dividend Data Inaccurate

### ISSUE THREAD

**Issue by ashutoshraiofficial** [iexg/IEX-API#246]
## Summary

I am using the IEX API to accrue historical dividend data for a program I am building. I would like to begin by thanking the IEX team - good stock data APIs are few and far between, and it is refreshing to see one as useful and applicable as IEX's! However, I have found at least one discrepancy in IEX's data.

## Details

The IEX API reports Agilent Technologies (A) declared a $15.75 dividend on November 3, 2014 (2014-11-03). Considering Agilent's previous and future dividend payments are in the $0.10 range, this seems unlikely. According to NASDAQ, Agilent did not declare or pay any dividends in November 2014 - that year, according to NASDAQ, it only paid dividends in April, June, and September. Agilent's own website states that they declared a dividend of $0.10 on November 20, 2014 (2014-11-20). In either case, it does not seem plausible that Agilent declared a $15.75 dividend in November 2014, as the IEX API claims.

### Date/time of issue

March 3, 2018.

### API URL

https://api.iextrading.com/1.0/stock/a/dividends/5y

https://api.iextrading.com/1.0/stock/a/dividends/5y?format=csv

### What you expected to happen

Receive accurate historical dividend data for Agilent Technologies (A).

### What actually happened

Received what is most likely inaccurate historical dividend data for Agilent Technologies (A), particularly regarding a dividend declared on November 3, 2014 (2014-11-03). IEX's data for this dividend is inconsistent with both NASDAQ's records as well as Agilent's own records.

**Comment by evancarter-iex** [comment]
This is fixed with IEXCLOUD. https://iexcloud.io
