### ISSUE TITLE
Stock Float Data

### ISSUE THREAD

**Issue by TraderMikeS** [iexg/IEX-API#247]
## Summary
Stock/symbol/stats has a value for the float.
Every site I visit has a different value for the float.
Where does IEX get float data and why does everyone not have the same value?

## Details
For stock symbol CADE (a Houston company) 
Yahoo finance shows float = 28.62M shares,
Investors.com (MarketSmith) shows float = 6.7M shares
IEX shows 83.5M shares

### Date/time of issue
3/3/2018 9PM California time

### API URL
https://api.iextrading.com/1.0/stock/cade/stats/?filter=float

### What you expected to happen
Float value that I can believe

### What actually happened
Float value that I cannot believe

**Comment by yay** [comment]
There are some glaring inaccuracies in the `float` data for some symbols.
For example: https://api.iextrading.com/1.0/stock/TOPS/stats
`float` is `59695` shares, while `shortInterest` is `1482658` or 2483.72% of float 🙀 
In this case the short interest data at roughly 1.5M is actually correct. It's the float, that should be 15.3M, that is not.

Other such examples:
https://api.iextrading.com/1.0/stock/TEUM/stats
https://api.iextrading.com/1.0/stock/AIZ/stats
https://api.iextrading.com/1.0/stock/BXC/stats
etc.

**Comment by joshuablackburn-iex** [comment]
I can confirm what you are seeing.  Our 3rd party provider has been notified.  We have also been taking steps to expand our data sources to resolve inaccuracies such as these.  We plan to roll out additional data sources soon.

**Comment by brentis** [comment]
Any update on this?  Been almost 4 mo.  Thanks!

**Comment by yay** [comment]
I guess we should wait for v2 of the API that should include new more accurate data sources: https://github.com/iexg/IEX-API/issues/403

Specifically these parts: `More accurate 3rd party data` and `We do not have an official release date for V2 yet. Some things need to get finalized first, then we will announce.`
