### ISSUE TITLE
Product Feedback Request

### ISSUE THREAD

**Issue by johndifini** [iexg/IEX-API#248]
## Summary
It would be great to have a product feedback site where users could "upvote" feature requests (see this [Asana example](https://community.asana.com/c/productfeedback/l/top/all?order=views)).  If this were in place, I would upvote the request to support [quotes for indexes](https://github.com/iexg/IEX-API/issues/36).  
BTW - Love your product!

## Details
N/A

### Date/time of issue
N/A

### API URL
N/A

### What you expected to happen
N/A

### What actually happened
N/A

### Other Information (sample code, links, etc.)
N/A

**Comment by evancarter-iex** [comment]
This is fixed in IEX Cloud. https://iexcloud.io
