### ISSUE TITLE
Sample Node/Javascript code?

### ISSUE THREAD

**Issue by dknesek** [iexg/IEX-API#249]
Do have or plan to provide a sample application that uses your API written in Javascript/node?

**Comment by joshuablackburn-iex** [comment]
We do plan to have sample code in the future.  At this time we only have applications on our website that demonstrate the use of data.  https://iextrading.com/apps/

**Comment by AngeiMachi** [comment]
+1

**Comment by AngeiMachi** [comment]
It's been a while . nothing changed?

**Comment by joshuablackburn-iex** [comment]
@AngeiMachi We created a new company. https://iexcloud.io
With new data and updated docs https://iexcloud.io/docs/api/
