### ISSUE TITLE
Unexpected results in `/tops/last`

### ISSUE THREAD

**Issue by Dmytro-Medzatiy** [iexg/IEX-API#25]
Hi, thanks for a great job, really enjoy working with your product!

Sometimes `tops/last` gives OK response but all prices in the response are equal to `0` (15-16 Sep) and today Sep 22, 13-10PM UTC then in 5 min everything works fine, then in several minutes it gives zeros again...

HTTP request: `https://api.iextrading.com/1.0/tops/last?symbols=AMZN,GBLAX,BAC,HD,SXCL,AEP,AMSWA,AMGN,AAPL,SCHW,CSCO,CVD,FDX,HPQ,IBM,INTC,INTU,KLAC,MSFT,PFE,VRSN,DIS,ABC,TSLA,ADT,VWO,GE,MMM,CL,DODIX&filter=symbol,price,time`

response:
```
[
{
 symbol: "AMZN",
 price: 0,
 time: 0
},
{ },
{
 symbol: "BAC",
 price: 0,
 time: 0
},
{
 symbol: "HD",
 price: 0,
 time: 0
},
{ },
{
 symbol: "AEP",
 price: 0,
 time: 0
}, ... ]
```

Is it possible that this is normal behavior for some cases or it was just an accidental fault?
Thanks!

**Comment by joshuablackburn-iex** [comment]
This is expected behavior for TOPS.  Each day we reset our trading system which zeros out all symbols.  If you need price data that includes previous day, you can use /stock/quote.
