### ISSUE TITLE
Outdated and inaccurate Dividend/Yield data

### ISSUE THREAD

**Issue by HeadWrench** [iexg/IEX-API#250]
## Summary
I have come across the following data errors:

## Details
RFTA	Dividend & Yield are incorrect.
MDLX	Dividend & Yield incorrect
GNL-A	Ex-dividend date is wrong (showing pay date instead).
PBB and TCCA are both showing an ex-dividend date of Nov 2017, even though the ex-div for Feb has passed, and May 2018 has been declared.

### What you expected to happen
I know that these are small volume issues and data is outsourced. But when errors like this exist it raises doubts about the trustworthiness of all the data. These are preferred shares and baby bonds for which the dividend is fixed and the distribution schedule is known well in advance. I expect that the data would be accurate and updated in a timely manner.

**Comment by HeadWrench** [comment]
Joshua,
Thanks for working on this.
These few examples are probably just the tip of the iceberg. Even though these securities are small issues and understandably have a lesser priority, it is important for this 3rd party data to be updated promptly and accurately. <b>Otherwise it is best not to provide it at all</b>. If we can’t be confident that the information is correct, and that the service takes that responsibility seriously, then it undermines the credibility of <b>all</b> the data.

**Comment by rodoabad** [comment]
Do we have any updates on this @joshuablackburn-iex?

I am with @HeadWrench here regarding updated data.

**Comment by Kernel-Klink** [comment]
I agree with the prior commenters; it is better not to have the data than have wrong data.

It should also be noted Dividend Pay Date is off.  Of ~50 stocks I looked at, the most recent pay date is ~4 months in the past.  I would expect there be at least one in the future, especially if the Ex-Date has been announced.
![image](https://user-images.githubusercontent.com/6157871/43780543-d56d98d6-9a28-11e8-8120-3258f32972ad.png)

As a side note, the Dividend ($0.73) and Yield (7.27%) for Ford appears to include the special dividend from the spring.
https://api.iextrading.com/1.0/stock/F/stats?filter=dividendRate,dividendYield
https://api.iextrading.com/1.0/stock/f/dividends/1y

**Comment by HeadWrench** [comment]
@joshuablackburn-iex 
Now 5 months later, this seems to be a dead issue with IEX. No resolution has been implemented.

I could document tickers that still report stale ex-dividend dates from back in Nov, Dec, and Jan. While any user with half a wit will realize that data is outdated, as we approach the end of the year it will, not might, but will cause many users to accept those incorrect dates as valid and actionable information.

**Comment by joshuablackburn-iex** [comment]
This is related to our data provider.  Unfortunately this is not something that we can address with them, so we are changing data providers for our next version. We have worked hard to bring our users the highest quality data out there with all the same terms of use we have now.  This was no small task and has been in the works for some time.  Should not be much longer.  We are hoping for an October launch.

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. https://iexcloud.io
