### ISSUE TITLE
Request: Provide historical EPS & PE ratio

### ISSUE THREAD

**Issue by clatonhendricks** [iexg/IEX-API#251]
Like the Title says, it would be nice to get the historical EPS & PE ratio. 3-5 years or maybe make it dynamic based on the user request. 
Thank you for all the hard work done. So far this is the best free API for Stocks.

**Comment by leedstyh** [comment]
Yeah, yearly and quarterly, and adjusted on split.

**Comment by timpaine-iex** [comment]
closing as stale
