### ISSUE TITLE
Some Symbols data is NOT real time, its 15 min delayed

### ISSUE THREAD

**Issue by APIMarketer** [iexg/IEX-API#252]
## Summary
Is there a reason some symbols data is not real time? its 15 min delayed? Do we know which symbols data is real time and which not? i mean is there a list of real time data not supported for some symbols?

Eg: DARE is real time, VTGN is 15 min delayed.

### Date/time of issue

any time during market being up

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=dare&types=quote&range=1m
https://api.iextrading.com/1.0/stock/market/batch?symbols=vtgn&types=quote&range=1m

### What you expected to happen

real time data

### What actually happened

15 min delayed data

**Comment by joshuablackburn-iex** [comment]
Real time data is sourced only from IEX trades.  If we have not traded the stock in the last 15 minutes, then we use the next closest data source we have which is 15 minute delayed SIP.  This is all based on the trading day and is not something we can document.  Typically IEX will trade around 5-6k of the 8500+ symbols each day.

**Comment by APIMarketer** [comment]
So, the data is never real time if we dont trade through IEX?

**Comment by joshuablackburn-iex** [comment]
The real time data represents a public feed of all trading on IEX.  We disseminate all trades that occur on our exchange.

**Comment by APIMarketer** [comment]
Ha, I get it now. sorry to be thick. i assumed that the API gives real time data for all symbols regardless of they are traded on IEX.  Can you recommend a source to get real time quotes? I want to check them out for data accuracies. I am developing an app and need real time data. I want to try out a free trial and then pay if it works for me. Are there any like that?
