### ISSUE TITLE
Gainers and Losers are incorrect when Market is closed

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#254]
## Summary
Gainers and Losers are incorrect when Market is closed.  The Gainers list has losers and losers list has gainers.

## Details

Please see the attached screen shot.
![image](https://user-images.githubusercontent.com/3579886/37243751-40e9700e-2444-11e8-9654-1416b0ae1e9d.png)

### Date/time of issue
When market is closed.

### API URL
/stock/market/list/gainers
/stock/market/list/losers

### What you expected to happen

When market is closed, the gainers and losers list should based on the last closing price to determine the Gainers and Losers.

### What actually happened

The Gainers list has losers and Losers list has gainers.

**Comment by joshuablackburn-iex** [comment]
#200
