### ISSUE TITLE
Hello fiends iextrading!  How can I make a api request?

### ISSUE THREAD

**Issue by vyacheslavt** [iexg/IEX-API#256]
Hello fiends iextrading!

How can I make a api request: 
period/range: 30 minutes 
symbol: AMD
last: 10-50 period from the current time

This possible?

**Comment by megaskills** [comment]
Hi 

Take a look at the full documentation for the API provided here
https://iextrading.com/developer/docs/#endpoints


30min bars are available using the Chart endpoint 
https://iextrading.com/developer/docs/#chart

The API is free to use/access - note the terms in the same document above.

The API supports JSONP and some Websockets

If you need more specific help after reading the documents, ask away.

Regards
Peter

**Comment by vyacheslavt** [comment]
Peter, hello.
maybe I'm stupid )) i see return 1min or 1 day , but not everything is clear in docs. could you give an example urls (sorry if this is difficult)

any stock, last week or month, 30 minut bar.

1min = https://api.iextrading.com/1.0/stock/AMD/chart/1d
1day = https://api.iextrading.com/1.0/stock/AMD/chart/1m

**Comment by mitalpha** [comment]
Hi,
We have to make aggregation for time ranges outside of 1min and 1 day ourselves. Note that we get 1 min and websocket data via API in real time only for IEX, not national data.
Mit

**Comment by megaskills** [comment]
Hi Mit
the chart endpoint has optional parameter chartInterval=xx where xx is nth element (or aggregation), so just use 30 to aggregate to 30 minutes bars. If you are using .Net, it's very easy to aggregate using LINQ.

' get 30 minutes bars on last traded day
`https://api.iextrading.com/1.0/stock/aapl/chart/1d?chartInterval=30`

' get 30 minutes bars on a specific date (up to 30 days backward)
`https://api.iextrading.com/1.0/stock/aapl/chart/date/20180316?chartInterval=30`
`https://api.iextrading.com/1.0/stock/aapl/chart/date/20180315?chartInterval=30`
`https://api.iextrading.com/1.0/stock/aapl/chart/date/20180314?chartInterval=30`

I have not been able to get a batch request to work that combines multiple dates in a single query, therefore you have to request each date in a single query. 


Cheers
Peter

**Comment by mitalpha** [comment]
Hi Peter,
When we use batch mode with days range (5 days)
https://api.iextrading.com/1.0/stock/market/batch?types=chart&symbols=aapl,mu&chartInterval=30&range=5d 
It should be option to set chartInterval different from range in days (=30min, =15min,...), seems like small API fix is needed.

Best
Mit

**Comment by megaskills** [comment]
Hi Mit
Yep, only the 1d range or a fixed date returns minute bars.
Therefore you can batch multiples stocks on the most recent trade day, but you can't batch multiple stocks across many dates.

so this works for 1 day
[](https://api.iextrading.com/1.0/stock/market/batch?types=chart&symbols=aapl,mu&chartInterval=30&range=1d)


but this won't work because you can't batch by date.
[](https://api.iextrading.com/1.0/stock/market/batch?types=chart&symbols=aapl,mu&chartInterval=30&range=1d&date=20180314,20180315,20180316
)

Also note then when you range=5d you don't get market wide datum.

Cheers 
Peter

**Comment by vyacheslavt** [comment]
Hi Peter, aah! I tried to get a month, so I could not. Just for the day.
Thank you

**Comment by vyacheslavt** [comment]
hmm, if use one day, then not the opening and closing information of the bars ((

**Comment by vyacheslavt** [comment]
And last bar 15:30,  no information about last closing 16:00

                   [12] => Array
                        (
                            [date] => 20180319
                            [minute] => 15:30
                            [label] => 3:30 PM
                            [high] => 174.79
                            [low] => 174.67
                            [average] => 174.734
                            [volume] => 1800
                            [notional] => 314521.5
                            [numberOfTrades] => 19
                            [marketHigh] => 174.825
                            [marketLow] => 174.65
                            [marketAverage] => 174.736
                            [marketVolume] => 57308
                            [marketNotional] => 10013757.2948
                            [marketNumberOfTrades] => 694
                            [changeOverTime] => -0.014461528048822
                            [marketChangeOverTime] => -0.014200041748236
                        )

**Comment by megaskills** [comment]
minute bars are typical grouped by time commencing, so 9:00am bar is all trades between 9:00 and 9:29.59, 9:30 bar is between 9:30 and 9:59.59 etc

which is why the last bar is 15:30

that's pretty consistent across a lot of data sources as far as I know.

I don't know why IEX excludes the open/close values in each minute bar - seems odd and perhaps a change request needs to created.

**Comment by joshuablackburn-iex** [comment]
@megaskills Open/Close is on its way.  It's in development.

**Comment by megaskills** [comment]
@joshuablackburn-iex  thanks Josh - that's great news.

**Comment by vyacheslavt** [comment]
megaskills, mm, I think it is not normal this is a bug the last 30 minutes of trading are lost. at least it should end at 15:59:59 and be rounded to 16:00 as it is done at 15:30

**Comment by vyacheslavt** [comment]
@joshuablackburn-iex great news! how long wait weeks, months? (Open/Close is on its way. It's in development.)

**Comment by megaskills** [comment]
@vyacheslavt - its not a bug and no data is missing.
the time commencing is used, not time ending.

so, a weekly bar would be dated on a Monday, not on a Friday. 
and a monthly bar would dated as the 1st of the month, not the last day of the month.

the first 60 minute bar would dated 9:30am and not 10:30am.
the first 30 minute bar would also be dated 9:30am and not 10:00am
therefore the last bar of a 30minute set would be 15:30pm which includes all trades to 15:59:59

I hope this makes sense now.
Regards
Peter

**Comment by vyacheslavt** [comment]
@megaskills Peter,hi. I'm comparing it to yahoo finance, but I do not find it similar. this is normal?
printscreen: [https://clip2net.com/s/3SPoRio](url)

**Comment by megaskills** [comment]
@vyacheslavt - 
my apologies, I misinterpreted the docs. the chartinterval is returning the 1 minute bar at x position in the array result and is not aggregating (summing) the results as first stated.

Therefore you will need to apply your own algo to sum the results at 30 minutes. 
pretty straight forward if you are using LINQ 

Sorry about that, I have my own LINQ code for aggregating data so i only ever download 1minute or 1 day bars and my software does any grouping needed.

**Comment by vyacheslavt** [comment]
This is bad ( will have to do the aggregation. now the bars do not make any sense then
