### ISSUE TITLE
Data inconsistency in intraday charts for some stocks

### ISSUE THREAD

**Issue by PietroFardella** [iexg/IEX-API#258]
## Summary
I get some misleading data when I call the https://api.iextrading.com/1.0/stock/{symbol}/chart/date/{date} endpoint.

## Details
I get some minutes of a day having values -1.0 for both High and Low, and 0 for Volume. What does it mean? Is the data unavailable?
The problem is related to some stocks and some days.
### Date/time of issue
Always

### API URL
https://api.iextrading.com/1.0/stock/adm/chart/date/20180302
https://api.iextrading.com/1.0/stock/adp/chart/date/20180302

### What you expected to happen
I expect to get consistent intraday values for High, Low and Volume, considering all the supported symbols and dates.

### What actually happened
I get many minutes in a day (for some stocks) with values -1.0 for High/Low and 0 for Volume.

**Comment by joshuablackburn-iex** [comment]
The -1 for high/low is a bug.  It should be null.  Volume 0 is as designed.  High, low, and volume are for IEX only.  If we did not trade in that minute we will not have a high, low, or volume.

**Comment by PietroFardella** [comment]
Thank you, now it's clear. And what about High=0.0, Low=0.0, Volume=0? Has it the same meaning? This usually happens at the start of a day (ie. minutes from 9:30 to 9:35).

**Comment by michaeldrennen** [comment]
@PietroFardella Yeah. @joshuablackburn-iex just said as much.

> Volume 0 is as designed. High, low, and volume are for IEX only. If we did not trade in that minute we will not have a high, low, or volume.

It would make sense that during the first 5 minutes of trading that there might not be a trade on the IEX platform.

**Comment by evancarter-iex** [comment]
The high/low is fixed now, and in IEXCLoud as well https://iexcloud.io
