### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by dknesek** [iexg/IEX-API#259]
## Summary
I can't get some of your APIs to return anything. It makes me wonder if I need to request permission/access to get to it. Is it accessible via the plain-ole-internet?

## Details
I am particularly interested in your IEX Market Data like TOPS. I am just a  private individual developer building software for personal use.

Under what circumstances does someone need to fill out your Data Agreement (pg. 2 – 10) and Exchange Data Request Form and System Description (pg. 11 – 14)?

**Comment by joshuablackburn-iex** [comment]
The API is freely available and does not require any special permissions.  https://iextrading.com/developer/docs/#iex-market-data

**Comment by dknesek** [comment]
I'm happy. But confused. On this page: https://iextrading.com/trading/market-data/#tops there is a table of agreements. Above the table, it says 

> Users must complete, execute, and submit the necessary agreements and forms before accessing DEEP or TOPS.

![image](https://user-images.githubusercontent.com/185153/37360705-fcbd2420-26be-11e8-85f6-3a3a617164f9.png)
