### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by scottycc** [iexg/IEX-API#26]
I have been getting an increasing number of 502 bad gateway errors, however they still seem at random.

My last encounter was a few minutes ago with this endpoint https://api.iextrading.com/1.0/stock/FB/chart/1D using just my chrome browser. I refreshed a few times and got a couple 502 nginx errors (however, not back to back).

Also, I am no where near the documented throttling limits.

Please let me know if you have any questions.

**Comment by joshuablackburn-iex** [comment]
We rolled out patches on Friday that should have resolved this issue.  Please let us know if you continue to experience this.
