### ISSUE TITLE
Follow up to issue #259

### ISSUE THREAD

**Issue by dknesek** [iexg/IEX-API#261]
@joshuablackburn-iex wrote:
> The API is freely available and does not require any special permissions. https://iextrading.com/developer/docs/#iex-market-data

I'm happy. But confused. On this page: https://iextrading.com/trading/market-data/#tops there is a table of agreements. Above the table, it says 

> Users must complete, execute, and submit the necessary agreements and forms before accessing DEEP or TOPS.

![image](https://user-images.githubusercontent.com/185153/37360705-fcbd2420-26be-11e8-85f6-3a3a617164f9.png)

**Comment by joshuablackburn-iex** [comment]
This is only to consume our binary data feeds from a data center.  Using the Web based API uses the following terms: https://iextrading.com/api-terms/

**Comment by dknesek** [comment]
Thank you. That helps. It would probably be good to make that fact more prominent.
