### ISSUE TITLE
Official Price returning null values (API and socket)

### ISSUE THREAD

**Issue by droakes** [iexg/IEX-API#262]
## Summary
The [official-price](https://iextrading.com/developer/docs/#official-price) API is returning null values for both API and socket requests.

### Date/time of issue
3/15/18 (evening) 

### API URL
https://api.iextrading.com/1.0/deep/official-price?symbols=snap

### What you expected to happen
`
{
  "SNAP": {
    "priceType": "Open",
    "price": 1.05,
    "timestamp": 1494595800005
  }
}
`

### What actually happened
**API:**
`{"SNAP":{}}`

**SOCKET:**
`{"symbol":"SNAP","messageType":"officialprice","data":{}}`
<br>
Also - really appreciate what you guys do.  Thanks so much!

**Comment by joshuablackburn-iex** [comment]
Official Price is will only return data for companies listed on IEX.
