### ISSUE TITLE
Sector varies in /TOPS and /Quote

### ISSUE THREAD

**Issue by lars670** [iexg/IEX-API#263]
## Summary
Sector varies in /TOPS and /Quote

## Details
When doing a snapshot in /Quote from AAPL I get as the sector:
**Technology**
When doing a snapshot in /Tops from AAPL I get as the sector:
**technologyhardwareequipmen**

Same discrepancy for other symbols.

### Date/time of issue
March 16

### API URL
https://api.iextrading.com/1.0/tops?symbols=AAPL
https://api.iextrading.com/1.0/stock/aapl/quote

### What you expected to happen
To receive the same sector for the 2 functions

### What actually happened
Different sectors received

### Other Information (sample code, links, etc.)

Is it at all relevant with field sector in /Tops since this is a field that does not change during the day?

**Comment by joshuablackburn-iex** [comment]
This is the result of multiple data sources and it needs to be normalized.
