### ISSUE TITLE
The ref-data 'type' and the company 'issueType' fields

### ISSUE THREAD

**Issue by andymercer** [iexg/IEX-API#264]
I've seen a couple of github issues on this topic.  Here is my take on this information coding and/or IEX documentation issue.

I assume these fields, (ref-data) 'type' and (company) 'issueType', are the same datum.  At least I have not encountered a ticker symbol reporting conflicting data in these fields. They are (jointly) documented as:

ad  – American Depository Receipt (ADR’s) 
ce  – Closed end fund (Stock and Bond Fund) 
cs  – Common Stock 
et  – Exchange Traded Fund (ETF) 
lp  – Limited Partnerships 
ps  - Preferred Stock
re  – Real Estate Investment Trust (REIT’s) 
si  – Secondary Issue 
N/A - Not Available

https://ws-api.iextrading.com/1.0/ref-data/symbols
returns info for 8591 ticker symbols.  The 'type' field is one of 6 fields per ticker, and its coding statistics for the 8591 are as follows:

bo  = 10
cs  = 5425
et  = 1005
ps  = 521
su  = 61
N/A = 1569

Two questions arise.

1. What are codes bo and su?  Possibly, su means mandatory convertible security.

2. What explains zero records for ad, ce, lp, re, and si?  Many are mis-coded as cs:
bidu, vod, bp, nvs should be ad.
dkl, dmlp, krp, lgcy, mcep should be lp (possibly other codes needed)
aiv, hr, lpt, ofc, ohi should be re.

We have many wrongly coded values, and we have incomplete documentation.  Categories of security types is a complex matter, see also:

http://www.quantumonline.com/SecurityAcronyms.cfm

What are IEX's intentions?

**Comment by andymercer** [comment]
Additional information follows:

1.  The 'su' securities contain the word 'unit' in their name, and that word is discussed in the quantum online link above.  Maybe su means security unit or securitized unit.

2.  The 10 'bo' securities are categorized by quantum online as:
aes, aed, aeh - traditional preferreds
tdi, pfk, jsm, afc - exchange traded debt securities
ccz - special corporate product
gyb, gjr - 3rd party trust preferred
I can't discern the logic of the 'bo' category.

3.  To motivate settling this issue, consider US tax issues.  Master Limited Partnerships have both favorable and unfavorable tax consequences, eg lower dividend tax rate some cases, not other cases, increased tax return preparation costs (schedule K).  Preferreds have the same taxe rate issue but do not share the tax preparation cost.  And so on.  It would be nice to have clarity and definiteness regarding the classification of securities.

**Comment by f2calv** [comment]
To add to the list of undocumented symbol types there is also a (ref-data) 'type' of crypto (yes I know it's pretty obvious what it is) so yes I agree the documentation @ https://iextrading.com/developer/docs/#symbols could do could do with some clarity on ps, bo, su & crypto

Oh and IMO it would also be better if "N/A" was a null instead.

**Comment by evancarter-iex** [comment]
This is fixed in IEX Cloud Docs.
