### ISSUE TITLE
Forecast dividend data

### ISSUE THREAD

**Issue by attex** [iexg/IEX-API#265]
Hei there, 

is there any forecast dividend date in the api ?

**Comment by vyacheslavt** [comment]
I'm also interested

**Comment by megaskills** [comment]
I would like that too - and forecast earnings date & eps

all 3 of the below endpoints which have relevant data seem to only provide past results
- Key Stats
- Earnings 
- Dividends

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
