### ISSUE TITLE
Converting IEX long date in milliseconds in VB.Net

### ISSUE THREAD

**Issue by megaskills** [iexg/IEX-API#266]
## Summary
This is a community support document to demonstrate how to convert the IEX dates that are in the format long milliseconds since midnight 1,1,1970 using VB.net. I used vb.net for ease of reading. 

I have provided two methods (shared in vb / static in C#) - one using the full UTC conversion steps, the other is a shorthand version that uses less code. Both end up with the same result - so just use one of the other.

Using this method you are able to convert the IEX date into any time zone. I like to convert it to "Eastern Standard Time" (ie New York Time) even though I'm in Australia, because I want to see the close price for example as "date at 4pm" which is date in the USA and not 7am in Australia.

Both methods take into account Daylight sayings in your time zone and that of the exchange.

Enjoy!

### Usage
 `  Dim ADate = ConvertIEXDate(latestUpdate, "Eastern Standard Time") `
 `  Dim ADate2 = ConvertIEXDateShortHand(latestUpdate, "Eastern Standard Time")`

### Other Information (sample code, links, etc.)
Long version

    ''' <summary>
    ''' Converts an IEX long date (which refers to a time in milliseconds since midnight Jan 1, 1970 UTC.) to a .net date in the requested TimeZone's local time. 
    ''' </summary>
    ''' <param name="IEXDate">Number of milliseconds elapsed since midnight 1/1/1970 UTC.</param>
    ''' <param name="ExchangeZoneID"></param>
    ''' <returns></returns>
    Private Shared Function ConvertIEXDate(IEXDate As Long?, ExchangeZoneID As String) As Date
        Try
            ' if null or no date, return nothing (effectively DateTime.MinValue)
            If IEXDate Is Nothing OrElse Not IEXDate.HasValue OrElse IEXDate <= 0 Then Return Nothing

            ' IEX Dates are based on milliseconds elapsed since 1/1/1970 so create a base time as a .net object.
            Dim BaseTime As New Date(1970, 1, 1, 0, 0, 0)

            ' IEX Dates are in UTC
            Dim UtcZoneId = "UTC"
            Dim UtcZone = TimeZoneInfo.FindSystemTimeZoneById(UtcZoneId)
            Dim BaseZoneTime = TimeZoneInfo.ConvertTimeFromUtc(BaseTime, UtcZone)

            ' Using the base time (in ticks) create a new date using the IEX Date (long) multiplied
            ' by 10,000 (converts milliseconds To 100 nano seconds used by .net) - in UTC format
            Dim ZoneTime = New Date(IEXDate * 10000 + BaseZoneTime.Ticks, DateTimeKind.Utc)

            ' Get the TimeZone of the Exchange (Not IEX, but the time zone of the Exchange the Symbol is trading on.)
            Dim ExchangeZone As TimeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(ExchangeZoneID)
            Return TimeZoneInfo.ConvertTimeFromUtc(ZoneTime, ExchangeZone)

        Catch ex As Exception

        End Try
        Return Nothing
    End Function

Short version

    ''' <summary>
    ''' Converts an IEX long date (which refers to a time in milliseconds since midnight Jan 1, 1970 UTC.) to a .net date in the requested TimeZone's local time. 
    ''' </summary>
    ''' <param name="IEXDate">Number of milliseconds elapsed since midnight 1/1/1970 UTC.</param>
    ''' <param name="ExchangeZoneID"></param>
    ''' <returns></returns>
    Private Shared Function ConvertIEXDateShortHand(IEXDate As Long?, ExchangeZoneID As String) As Date
        Try
            ' if null or no date, return nothing (effectively DateTime.MinValue)
            If IEXDate Is Nothing OrElse Not IEXDate.HasValue OrElse IEXDate <= 0 Then Return Nothing

            ' IEX Dates are based on milliseconds elapsed since 1/1/1970 so create a base time as a .net object.
            Dim BaseTime As New Date(1970, 1, 1, 0, 0, 0)

            ' Using the base time (in ticks) create a new date using the IEX Date (long) multiplied
            ' by 10,000 (converts milliseconds To 100 nano seconds used by .net) - in local format
            Dim ZoneTime = New Date(IEXDate * 10000 + BaseTime.Ticks, DateTimeKind.Local)

            ' Get the TimeZone of the Exchange (Not IEX, but the time zone of the Exchange the Symbol is trading on.)
            Dim ExchangeZone As TimeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(ExchangeZoneID)

            ' In this shorter code version we bypassed the UTC time, so we need to convert from local and return tolocal 
            Return TimeZoneInfo.ConvertTime(ZoneTime, ExchangeZone).ToLocalTime

        Catch ex As Exception

        End Try
        Return Nothing
    End Function

**Comment by Rickrod82** [comment]
Central
