### ISSUE TITLE
IEX doesn't report the stock split for AFL on 2018-03-20

### ISSUE THREAD

**Issue by rickcockerham** [iexg/IEX-API#267]
## Summary
IEX doesn't report the stock split for AFL on 2018-03-20

## Details
https://api.iextrading.com/1.0/stock/AFL/splits/1m
returns 
[]
https://api.iextrading.com/1.0/stock/AFL/splits/5y
also returns 
[]

### Date/time of issue
2018

### API URL
https://api.iextrading.com/1.0/stock/AFL/splits/1m

### What you expected to happen
I expected it to return the information for the split that happened on 2018-03-20
Question: how far in advance should it show?  On the announced date?

### What actually happened
No data.

**Comment by rickcockerham** [comment]
The split data for AFL is still missing.  Someone else just reported that split data is missing for CHEK.

https://github.com/iexg/IEX-API/issues/289

So, this seems like a larger problem.

**Comment by StockConsultant** [comment]
Any resolution/fixes for the splits API? how does one deal with a split on the ex-date and historical data.

**Comment by rss81** [comment]
Wow, it's now 7 or 8 months later and the split information for Aflac (AFL) on 3/20/2018 2 for 1 is still missing.  I guess IEX is not a great source for split information

**Comment by evancarter-iex** [comment]
@rss81 please see https://github.com/iexg/IEX-API/issues/557 we have negotiated a deal with a new data provider, which will hopefully fix a lot of these issues.

**Comment by rss81** [comment]
That’s awesome.  Thank you

Sent from Mail for Windows 10

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud. If you haven't already you can sign up for the beta here: https://iexcloud.io
