### ISSUE TITLE
API Chart Data Question

### ISSUE THREAD

**Issue by sma27** [iexg/IEX-API#268]
## Summary
What is the difference between marketAverage, marketHigh, marketLow, etc. and the corresponding average, high, low, etc. fields in the chart API? The documentation doesn't have any descriptions.

https://iextrading.com/developer/docs/#chart

Sometimes the average price is 0 and sometimes the marketAverage is 0. Why would values of 0 and -1 exist in the data? Which would I typically use to chart the price of a stock?

## Details
https://api.iextrading.com/1.0/stock/DIA/chart/1d

Below is some sample output from the API call:

{"date":"20180322","minute":"09:30","label":"09:30 AM","high":0,"low":0,"average":0,"volume":0,"notional":0,"numberOfTrades":0,"marketHigh":244.12,"marketLow":243.84,"marketAverage":243.984,"marketVolume":85460,"marketNotional":20850885.6574,"marketNumberOfTrades":341,"changeOverTime":null,"marketChangeOverTime":0},{"date":"20180322","minute":"09:31","label":"09:31 AM","high":243.56,"low":243.56,"average":243.56,"volume":300,"notional":73068,"numberOfTrades":1,"marketHigh":243.98,"marketLow":243.425,"marketAverage":243.609,"marketVolume":51505,"marketNotional":12547084.7751,"marketNumberOfTrades":314,"changeOverTime":null,"marketChangeOverTime":-0.0015369860318709423},{"date":"20180322","minute":"09:32","label":"09:32 AM","high":-1,"low":-1,"average":0,"volume":0,"notional":0,"numberOfTrades":0,"marketHigh":243.57,"marketLow":243.23,"marketAverage":243.395,"marketVolume":30414,"marketNotional":7402632.8045,"marketNumberOfTrades":153,"changeOverTime":null,"marketChangeOverTime":-0.0024140927273919545},{"date":"20180322","minute":"09:33","label":"09:33 AM","high":243.51,"low":243.51,"average":243.51,"volume":100,"notional":24351,"numberOfTrades":1,"marketHigh":243.69,"marketLow":243.4,"marketAverage":243.521,"marketVolume":38032,"marketNotional":9261604.2415,"marketNumberOfTrades":159,"changeOverTime":null,"marketChangeOverTime":-0.0018976654206834147},{"date":"20180322","minute":"09:34","label":"09:34 AM","high":243.39,"low":243.39,"average":243.39,"volume":300,"notional":73017,"numberOfTrades":1,"marketHigh":243.7,"marketLow":243.39,"marketAverage":243.529,"marketVolume":10555,"marketNotional":2570447.366,"marketNumberOfTrades":68,"changeOverTime":null,"marketChangeOverTime":-0.0018648763853367945},{"date":"20180322","minute":"09:35","label":"09:35 AM","high":-1,"low":-1,"average":0,"volume":0,"notional":0,"numberOfTrades":0,"marketHigh":243.8,"marketLow":243.36,"marketAverage":243.58,"marketVolume":11343,"marketNotional":2762928.198,"marketNumberOfTrades":101,"changeOverTime":null,"marketChangeOverTime":-0.0016558462850022803},{"date":"20180322","minute":"09:36","label":"09:36 AM","high":-1,"low":-1,"average":0,"volume":0,"notional":0,"numberOfTrades":0,"marketHigh":244.1,"marketLow":243.675,"marketAverage":243.886,"marketVolume":23010,"marketNotional":5611826.6582,"marketNumberOfTrades":107,"changeOverTime":null,"marketChangeOverTime":-0.0004016656829956603}
...
]

### Date/time of issue
3/22/2018 @ 9:47 PM MDT

### API URL
https://api.iextrading.com/1.0/stock/DIA/chart/1d

### What you expected to happen
I wouldn't expect rows of data to have -1 or 0 values.

**Comment by mfhawley** [comment]
I would like to know an answer to this as well. Very confusing

**Comment by joshuablackburn-iex** [comment]
Anything with a prefix of "market" represents data from all trading venues market wide.  Without the prefix represents **only** IEX data.  I will have the documentation updated to reflect this.

As for the 0 and -1, that is something we are aware of and plan to address in v2.  It would be a breaking change to make them null at this point.  The -1 is an artifact of how our trading system treats prices, and in this case, when there isn't a price.  -1 is sent when we did not have a price in that minute.  In v2, we will translate the trading system data to null.  If you receive a 0, that means there was no data for that minute.  0 average or 0 numberOfTrades means exactly that, there were no trades.

**Comment by mfhawley** [comment]
Josh. Thank you so much for the quick response on this. That is what i figured but wanted to make sure.

Could you by chance take a look at this issue as well as it could be fairly significant to people using this data if across many stocks... https://github.com/iexg/IEX-API/issues/445

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
