### ISSUE TITLE
latestPrice is null

### ISSUE THREAD

**Issue by jcpny1** [iexg/IEX-API#269]
## Summary
For symbol 'DBX', the latestPrice field is null. For other symbols, the latestPrice is always filled in, with the latestPrice. Looking at another data provider, there is a latestPrice for DBX.

## Details
{
  "quote": {
    "symbol": "DBX",
    "companyName": "Dropbox Inc",
    "primaryExchange": "Nasdaq Global Select",
    "sector": "Technology",
    "calculationPrice": "previousclose",
    "open": 29,
    "openTime": 1521819319775,
    "close": 28.48,
    "closeTime": 1521835200577,
    "high": 31.6,
    "low": 27.84,
    "latestPrice": null,
    "latestSource": "N/A",
    "latestTime": "N/A",
    "latestUpdate": null,
    "latestVolume": 55918757,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": 28.8,
    "delayedPriceTime": 1521838794108,
    "previousClose": null,
    "change": null,
    "changePercent": null,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 1862776,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "marketCap": null,
    "peRatio": null,
    "week52High": 31.6,
    "week52Low": null,
    "ytdChange": 0
  },

### Date/time of issue
24-Mar-2018 1930 EDT

### API URL
https://api.iextrading.com/1.0/stock/dbx/batch?types=quote,news,chart&range=1m&last=10

### What you expected to happen
I expected the latestPrice to be the same as the close price -

### What actually happened
The latestPrice was set to null.

**Comment by joshuablackburn-iex** [comment]
Can you try this again?  I'm seeing correct data.

**Comment by jcpny1** [comment]
Yes, it was corrected the next day. I think March 23rd was DBX's first trading day. So perhaps there is some glitch in the code when an equity only has one day of trading.
