### ISSUE TITLE
Current end of Day

### ISSUE THREAD

**Issue by a-gene** [iexg/IEX-API#27]
First love the API.

I was wondering is there a way to get current end of day data similar to the /market/previous. For the current day?

Or when does the /market/previous switches over?

Thanks

**Comment by joshuablackburn-iex** [comment]
This is in the works and should be available soon.

**Comment by joshuablackburn-iex** [comment]
The stock/quote endpoint now returns Open and Close for the current day.  We are also implementing an endpoint to specifically return this data similar to stock/previous.

**Comment by joshuablackburn-iex** [comment]
This is available by using:

https://api.iextrading.com/1.0/stock/market/open-close
or
https://api.iextrading.com/1.0/stock/aapl/open-close

We will update our documentation later today.
