### ISSUE TITLE
Dividends not updated since March 9th

### ISSUE THREAD

**Issue by Flandel** [iexg/IEX-API#270]

**Comment by joshuablackburn-iex** [comment]
We made a number of updates to dividends and splits, and it is currently in QA.

**Comment by prokaktus** [comment]
@joshuablackburn-iex sorry for bothering, it's already month since you put QA label. Do you have any estimates or expectations about when it will be deployed?

Thanks!

**Comment by borgoyn** [comment]
Any estimate on when dividends will be working again?

**Comment by StockConsultant** [comment]
@joshuablackburn-iex I am also having this problem on historical dividends 

for example AAPL:

https://api.iextrading.com/1.0/stock/AAPL/dividends/2y?format=csv

nothing past 2/9/2018 missing August 19th dividend

exDate | paymentDate | recordDate | declaredDate | amount
-- | -- | -- | -- | --
2/9/2018 | 2/15/2018 | 2/12/2018 | 2/1/2018 | 0.63
11/10/2017 | 11/16/2017 | 11/13/2017 | 11/2/2017 | 0.63
8/10/2017 | 8/17/2017 | 8/14/2017 | 8/1/2017 | 0.63
5/11/2017 | 5/18/2017 | 5/15/2017 | 5/2/2017 | 0.63
2/9/2017 | 2/16/2017 | 2/13/2017 | 1/31/2017 | 0.57
11/3/2016 | 11/10/2016 | 11/7/2016 | 10/25/2016 | 0.57
8/4/2016 | 8/11/2016 | 8/8/2016 | 7/26/2016 | 0.57
5/5/2016 | 5/12/2016 | 5/9/2016 | 4/26/2016 | 0.57

**Comment by gbrayjr** [comment]
Any update on when this will be fixed?  AAPL had dividends in May and August - IEX returns no dividends after March.

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/

**Comment by ModelsRUs** [comment]
When do you expect general (non-beta) release? Thank you.

**Comment by evancarter-iex** [comment]
@ModelsRUs You can signup now. We are quickly moving towards removing the "beta" tag off it.

**Comment by ModelsRUs** [comment]
Thank you Evan.
Sorry I'm confused. Do you mean V2? I'm using the Excel API. What do I 
need to sign up for? Is there something I need to change in my worksheet?

Thank you,
- *Paul*
   (917) 476-4468
=================================================

**Comment by evancarter-iex** [comment]
@ModelsRUs Yes if you go to https://iexcloud.io you will be able to signup for version 2. You will need to change your endpoints to hit the new url as specified in the documentation to get the new data.

**Comment by ModelsRUs** [comment]
I'm on the site, but see nothing about Beta. The Beta section under Docs 
also doesn't indicate what to do.

Do I just change from 'https://api.iextrading.com/*1*.0/stock/ to 
'https://api.iextrading.com/*2*.0/stock/ in excel?


- *Paul*
   (917) 476-4468
=================================================

**Comment by evancarter-iex** [comment]
@ModelsRUs Please read through the main website  https://iexcloud.io  and the developer documentation. If you have additional questions please reach out to support@iexcloud.io via email, that way we dont continue to spam other people.
