### ISSUE TITLE
indicated dividends is always blank

### ISSUE THREAD

**Issue by akcalixto** [iexg/IEX-API#271]
## Summary
'**indicated**' field of dividends is always blank. 

### Date/time of issue
3/25/2018 @ 10:20 PM EST

### API URL
https://api.iextrading.com/1.0/stock/aapl/dividends/1y

### What you expected to happen
See a number which represents the total amount of dividends that would be paid on a share of stock over the next 12 months if each dividend were the same amount as the most recent dividend.

### What actually happened
field is blank

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
