### ISSUE TITLE
Cash from Stats API does not equal totalCash from Financials API

### ISSUE THREAD

**Issue by jmsims2** [iexg/IEX-API#275]
## Summary
I've noticed with several stocks, cash from the Stats API and the totalCash from the Financials API do not equal each other.  In many cases the Financials API is null.

## Details
The test case I am using is Argan (AGX).
https://api.iextrading.com/1.0/stock/agx/stats
This returns cash = 2,127,264,000 (this is 4 times AGXs market cap...)

https://api.iextrading.com/1.0/stock/agx/financials
This returns cash = 483,681,000 (most recent quarters financials and this appears to be correct)

### Date/time of issue
March 26, 2018 at 8:25pm EST

### API URL
https://api.iextrading.com/1.0/stock/agx/stats
https://api.iextrading.com/1.0/stock/agx/financials

### What you expected to happen
Expected the cash from Stats and totalCash from Financials to be the same.

### What actually happened
They were different, cash from Stats was about 4x higher.

**Comment by evancarter-iex** [comment]
Fixed with IEXcloud. https://iexcloud.io
