### ISSUE TITLE
Example date in the chart doc doesn't return any data

### ISSUE THREAD

**Issue by dblock** [iexg/IEX-API#278]
## Summary

The date of `20180129` in the `chart` [docs](https://iextrading.com/developer/docs/#chart) doesn't return any data (was the market closed?).

### API URL

https://api.iextrading.com/1.0/stock/msft/chart/date/20180129

### What you expected to happen

To get some data. Other dates work fine.

**Comment by joshuablackburn-iex** [comment]
At this time we only have the last 30 days available.

**Comment by dblock** [comment]
Cool, maybe document it?

**Comment by joshuablackburn-iex** [comment]
This is already documented at:
https://iextrading.com/developer/docs/#chart

"IEX-only data by minute for a specified date in the format YYYYMMDD if available. Currently supporting trailing 30 calendar days."
