### ISSUE TITLE
Returnning a []/{} instead of a "" if no data is available.

### ISSUE THREAD

**Issue by leedstyh** [iexg/IEX-API#28]
Hello,

 I'm using Go programming language to parse the JSON, but a little tricky to deal with `""` in an array or object type. So I think change `""` to `[]/{}` is a good idea.

**Comment by shuwnyuantee** [comment]
@leedstyh  👍  I second your suggestion, I think I will face similar issue soon, I am using Java though.

**Comment by joshuablackburn-iex** [comment]
We've standardized the return values to match appropriate data type. For unknown values we use null. Please let me know if you find any data that still returns a value that breaks your typed variables.

**Comment by leedstyh** [comment]
Thanks @joshuablackburn-iex , closing this now
