### ISSUE TITLE
Return latest intraday chart available

### ISSUE THREAD

**Issue by LayneChris** [iexg/IEX-API#281]
## Summary
Since the intraday charts will return an empty array if the market is closed there should be an endpoint that will give the latest available.

## Details
For instance, https://api.iextrading.com/1.0/stock/aapl/chart/date/20180330 gives an empty array because the market is closed today. The latest available is for 20180329 but how do I know? It could be a weekend or 3 day weekend and guessing what the latest available takes trial and error via a few extra API calls that could be reduced. I always just want to get the latest available intraday chart.

### Date/time of issue
2018-03-30.

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/date/20180330

### What you expected to happen
For there to be a way to get the latest intraday chart. Something like the following would work: https://api.iextrading.com/1.0/stock/aapl/chart/date/available...could also call it "latest" or something else and that would just output the data for 20180329.

### What actually happened
Endpoint is not available ;(

### Other Information (sample code, links, etc.)
Just a quick thanks for making this API freely available in the first place.

**Comment by timpaine-iex** [comment]
closing as stale, should work fine with `time-series`
