### ISSUE TITLE
Request: Revenue information similar to existing Earnings call

### ISSUE THREAD

**Issue by jbirkner** [iexg/IEX-API#282]
## Summary

The Earnings request is very helpful.  Would it be possible to have a similar call with revenue data? 

### Other Information (sample code, links, etc.)
Thanks for this great API!

**Comment by joshuablackburn-iex** [comment]
You should be able to get what you need from:
https://iextrading.com/developer/docs/#financials

**Comment by jbirkner** [comment]
Sorry if I wasn't clear.  What I meant were consensus estimates and surprise data for Revenue.

consensusRevenue
RevenueSurpriseDollar
