### ISSUE TITLE
Stock Prices do not actual match real-time prices?

### ISSUE THREAD

**Issue by DawBin** [iexg/IEX-API#284]
## Summary
Stock Prices are wrong. Is this service on a delay? Is it pulling from an alternate market?

## Details
Checking several symbols and comparing to real-time prices on TDA, there are no correct real-time prices returned.

### Date/time of issue
2018-04-02 2:02PM

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=AAPL&types=quote&range=1m&last=1 

### What you expected to happen
Thought I would get accurate real-time prices. 

### What actually happened
No accurate prices

### Other Information (sample code, links, etc.)
Is this service on a delay? Is it pulling from an alternate market?

**Comment by joshuablackburn-iex** [comment]
IEX is a market, and the real-time prices in our API are trades on our market.  There are currently 12 exchanges, and my guess is TDA is displaying prices for one of them.  They are probably displaying the source next to the price.  If you're looking at AAPL, they are probably showing the last price from Nasdaq.  Nasdaq only represents 1 of the 12 exchanges.

**Comment by DawBin** [comment]
Thanks so much for the explanation, we do love the API.

Feel free to reply with any questions.

Best Regards,
Amanda Tyler
Customer Support
