### ISSUE TITLE
Feature Request - More detailed financials

### ISSUE THREAD

**Issue by alphaville76** [iexg/IEX-API#285]
## Summary
The financial data should more fine granular, like for example those of Morningstar.

Namely I'm looking for the following missing data:

- **Enterprise Value**
- **Filing Date**: when the data was published on SEC (useful for backtesting)
- **EBITDA**: I know, it's already in the  key stats API, but in my opinion it belongs to financials.
- **Operating Cash Flow**: The net cash from (used in) all of the operating activities (actually is available only the total cash flow, including cash from investing and financing). See also #72
- **Free Cash Flow**: Operating Cash Flow minus Capital Expenditures. See also #152 

 Thanks for your valuable API!

**Comment by leedstyh** [comment]
Thinking we also need shares outstanding each quarter to calculate per share data. 

And more periods, say 8 quarters at least.

**Comment by marco-m-alves** [comment]
Would add:

Working Capital detail
- Inventories
- Trade Receivables
- Trade Payables

P&L detail
- SG&A
- Depreciation & Amortisation

**Comment by tjang0806** [comment]
I am looking forward to see "Enterprise Value(EV)".
EV/EBITDA would give users very valuable information to the users

**Comment by timpaine-iex** [comment]
resolved via [fundamentals](https://iexcloud.io/docs/api/#advanced-fundamentals), more targeted valuation endpoints are in-flight
