### ISSUE TITLE
/stock/market/list/ displays incorrectly after hours

### ISSUE THREAD

**Issue by sdak006** [iexg/IEX-API#286]
## Summary
When querying the top 10 lists after hours, it looks like the results are not correct. The gainers have some stocks that have lost value in the last 24 hours, and the losers have some stocks that have gained value in the last 24 hours.

### Date/time of issue
5 April 2018 11:52pm CST

### API URL
/stock/market/list/mostactive
/stock/market/list/gainers
/stock/market/list/losers

### What you expected to happen
When querying Gainers, I expect to receive a list of the 10 stocks that have had the largest percentage gain for the given day. Visa versa for Losers.

### What actually happened
The returned lists seem random, with gainers having stocks with both positive and negative gains.

**Comment by sdak006** [comment]
<img width="494" alt="capture" src="https://user-images.githubusercontent.com/6834083/38404053-02bba678-392d-11e8-8268-4db599de9f56.PNG">

**Comment by evancarter-iex** [comment]
We are currently working on a fix for the issues with the gainers/losers.
