### ISSUE TITLE
ws-api.iextrading.com/1.0/tops API issues

### ISSUE THREAD

**Issue by yay** [iexg/IEX-API#287]
## Summary
1) messages are fired with exactly the same data (expected to fire only on data change)
2) there are no "subscribed"/"unsubscribed" events to listen to (I expect to know when I've successfully subscribed and *more importantly* unsubscribed)

## Details

You have the following JS example at https://iextrading.com/developer/docs/#websockets:
```js
// Import socket.io with a connection to a channel (i.e. tops)
const socket = require('socket.io-client')('https://ws-api.iextrading.com/1.0/tops')

// Listen to the channel's messages
socket.on('message', message => console.log(message))

// Connect to the channel
socket.on('connect', () => {

  // Subscribe to topics (i.e. appl,fb,aig+)
  socket.emit('subscribe', 'snap,fb,aig+')

  // Unsubscribe from topics (i.e. aig+)
  socket.emit('unsubscribe', 'aig+')
})

// Disconnect from the channel
socket.on('disconnect', () => console.log('Disconnected.'))
```

While one can get an idea of how the API can be used from this example alone, a more thorough and formal documentation is needed. For example, is all you see here all you get, or are there some other events to emit and listen to?

I consume the API from Kotlin via the https://github.com/socketio/socket.io-client-java library like so (but the issues described are API issues, not library issues):
```kotlin
socket
    .on("message") { params ->
        val tops = IexApi.parseTops(params.first() as String)
        val symbol = tops.symbol
        // Sometimes we will get a 'message' for symbols after we've unsubscribed from them
        // via `socket.emit("unsubscribe", "AAPL,FB")`, so we check if we've in fact issued
        // the `unsubscribe` event for those symbols. The issue is then of course, when do you
        // clean the `pendingRemove` set? Thankfully, it's easier with the `pendingAdd` set:
        // we know we've successfully subscribed, when we started receiving messages for those
        // symbols, but I'd still prefer to be explicitly notified even in this case.
        if (symbol !in pendingRemove) {
            // We can receive a message for a symbol even if no change occurred:
            // no bid/ask size, price or even volume changes.
            // That's why we use an observable map:
            // it's change listener will only be called when an actual change happens,
            // because `tops` data class instances are compared using the `equals` method.
            map[symbol] = tops
            pendingAdd.remove(symbol)
        }
    }
    .on("subscribed") { params -> // wanted, but no such event to subscribe to

    }
    .on("unsubscribed") { params -> // wanted, but no such event to subscribe to

    }
```

`Tops` data class and `parseTops` function definitions:
```kotlin
data class Tops(
    val symbol: String,
    val marketPercent: Double = 0.0,
    val bidSize: Int = 0,
    val bidPrice: Double = 0.0,
    val askSize: Int = 0,
    val askPrice: Double = 0.0,
    val volume: Long = 0,
    val lastSalePrice: Double = 0.0,
    val lastSaleSize: Int = 0,
    val lastSaleTime: Date? = null,
    val lastUpdated: Date? = null,
    val sector: String = "",
    val securityType: String = ""
)

// The JSON is parsed using FasterXml's Jackon library.
val mapper = jacksonObjectMapper().apply {
    enable(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE)
}

fun parseTops(json: String): Tops = mapper.readValue(json, Tops::class.java)
```

### Date/time of issue
Always.

### API URL
https://ws-api.iextrading.com/1.0/tops

**Comment by joshuablackburn-iex** [comment]
We've been working on a massive upgrade to our backend systems over the last few months that will resolve this issue.  It's been in QA for a while, and is expected to go into production after trading today.  On successful connection you will now receive a snapshot of data, then the live stream.  Messages are sequenced, and duplicates should no longer be sent.

**Comment by yay** [comment]
Nice! I hope we can also get acknowledgments for emitted messages. Currently the code below never logs "Subscribed: ..." / "Unsubscribed: ..." to the console:
```js
const socket = require('socket.io-client')('https://ws-api.iextrading.com/1.0/tops')

socket.on('message', message => console.log(message))

socket.on('connect', () => {
  socket.emit('subscribe', 'fb,aapl,googl', data => console.log(`Subscribed: ${data}`))
  socket.emit('unsubscribe', 'aapl', data => console.log(`Unsubscribed: ${data}`))
})

socket.on('disconnect', () => console.log('Disconnected.'))
```

**Comment by yay** [comment]
I see the status changed to `In deployment` and does seem to work faster now with data arriving for all the newly subscribed symbols at the same time, but I still don't get the acknowledgment of the subscription.

**Comment by joshuablackburn-iex** [comment]
I updated the label to be more accurate.  We are ready and preparing for deployment.  It is not complete yet.

**Comment by evancarter-iex** [comment]
#1 is now deployed.

**Comment by yay** [comment]
Thanks for the update! Will check it out tomorrow.

**Comment by yay** [comment]
Works great 👍

**Comment by evancarter-iex** [comment]
@yay thanks. Can you open another bug about the subscribe/unsubscribe messages. That way it wont get lost. Thanks
