### ISSUE TITLE
stock/market/previous - data availability

### ISSUE THREAD

**Issue by sdvisconti** [iexg/IEX-API#288]
## Summary
I am using the stock/market/previous endpoint and would like to know when the earliest time of day that the complete previous day's data set is available?

## Details
If I query the endpoint at midnight I receive prices for only a small fraction of the market's securities.
### Date/time of issue
12:01 am

### API URL
https://api.iextrading.com/1.0/stock/market/previous

### What you expected to happen
To receive a complete snapshot of prior day prices containing all securities for the entire market.

### What actually happened
I received prices for 380 securities at 12:01 am.
If I query at 12:00 pm I receive prices for 8,584 securities.

**Comment by Rickrod82** [comment]
https://api.iextrading.com/1.0/stock/market/previous

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
