### ISSUE TITLE
No split data for CHEK

### ISSUE THREAD

**Issue by dgquintas** [iexg/IEX-API#289]
## Summary
Split information is missing for CHEK. [A reverse 1:12 split happened on 2018-04-04](https://www.splithistory.com/?symbol=chek), but https://api.iextrading.com/1.0/stock/chek/splits/1m returns `[]`

### Date/time of issue
2018-04-08 

### API URL
https://api.iextrading.com/1.0/stock/chek/splits/1m

### What you expected to happen
To see the split from 2018-04-04

### What actually happened
`[]`

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
