### ISSUE TITLE
Data is not coming in both http and websocket apis

### ISSUE THREAD

**Issue by abhiindia** [iexg/IEX-API#290]
## Summary
I want to use IEX apis but data is not coming for any symbols.

https://api.iextrading.com/1.0/deep/trades?symbols=snap

## Details
https://api.iextrading.com/1.0/deep/trades?symbols=snap
Even http url mentioned in apis is not giving any data.

### API URL

https://api.iextrading.com/1.0/deep/trades?symbols=snap

### What you expected to happen

Data should come when calling api

### What actually happened

Data should come when calling api

**Comment by joshuablackburn-iex** [comment]
This endpoint will only return trade data during market hours.
