### ISSUE TITLE
Underlying or Parent Company

### ISSUE THREAD

**Issue by andymercer** [iexg/IEX-API#291]
## Summary

Some securities have an underlying or parent company, and it would be nice if this datum were available.

## Details

Ticker BAC-I is a preferred stock ticker whose underlying company is BAC.  BML-G is another, and its underlying company is also BAC (thus you can't parse ticker symbols to discover the parent company).  What would be helpful is if BAC-I and BML-G data included a new field parentSymbol in the company endpoint.  When there is no such parent (ie BAC has no parent), then leave parentSymbol blank or omit it.

For some (perhaps all?) preferred stocks, the stats endpoint returns some data for fields returnOnEquity, returnOnAssets, and profitMargin.  Thes data make no sense for a preferred.  However, values 6.84, 0.74, and 17.75 respectively are returned for these fields for tickers BAC-I, BML-G, and BAC (as of 11am apr 9, 2018).  Can I reliably count on a preferred symbol returning such data from its parent?  In other words, will profitMargin for a preferred share always be the profitMargin of the parent company?

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. We added a securityName and a CompanyName. Https://iexcloud.io
