### ISSUE TITLE
High and Low problem

### ISSUE THREAD

**Issue by Jxt0001** [iexg/IEX-API#293]
## Summary
High and Low are not always good

### Date/time of issue
15 apr 18

### API URL
https://api.iextrading.com/1.0/stock/tqqq/ohlc
https://api.iextrading.com/1.0/stock/market/batch?symbols=tqqq&types=price,quote

### What you expected to happen
Always get a good High and Low

### What actually happened
Sometime,  wrong High and Low

### Other Information (sample code, links, etc.)
Quote Day: 13 APR 2018
// 20180415103110
// https://api.iextrading.com/1.0/stock/tqqq/ohlc

{
  "open": {
    "price": 150.01,
    "time": 1523626200325
  },
  "close": {
    "price": 145.45,
    "time": 1523649600372
  },
  **"high": 143.82, >>> must be 150.68
  "low": 134.349 >>> must be 143.66**
}
Same thing for type "Quote"

**Comment by dchenk** [comment]
I'm finding that data from IEX isn't the same as what nasdaq.com and Yahoo give. IEX data does not match data from Nasdaq in prices (o/h/l/c) and volume.

**Comment by evancarter-iex** [comment]
This is fixed with IEX Cloud

https://iexcloud.io
