### ISSUE TITLE
Market time

### ISSUE THREAD

**Issue by AndreyPerelygin** [iexg/IEX-API#294]
## Summary
I need the opportunity to get the status of the market in real time and on a single date.

### What you expected to happen
I can find out if the market is working now, but I can not find out whether it will work tomorrow.

### What actually happened
I would like to be able to know when the market will work for a month ahead and it is desirable to have historical data on the work of the exchange. At the same time having the opportunity to receive real-time information about unplanned market stops.

**Comment by evancarter-iex** [comment]
Fixed with IEX Cloud. https://iexcloud.io
