### ISSUE TITLE
Some Stocks List requests return less than 10 symbols

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#296]
## Details

[List](https://iextrading.com/developer/docs/#list) endpoints should return top-10 symbols from a given list. Sometimes, they return 9.

### Date/time of issue

4/19/18, 5PM PST

### API URL

https://api.iextrading.com/1.0/stock/market/list/iexvolume

### What you expected to happen

Top 10 IEX volume symbols, per the docs:

> Returns an array of quotes for the top 10 symbols in a specified list.

### What actually happened

Top 9 IEX volume symbols

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
