### ISSUE TITLE
Next Earnings information

### ISSUE THREAD

**Issue by wicketr** [iexg/IEX-API#298]
I see on your /earnings api call, you're listing the last 4 reports. However, i know some websites show details on the "next" earnings call. Primarily, the date.

I'd like to see that info under the /earnings call, and/or under the /company api calls so i can keep track of upcoming earnings calls.

**Comment by mitalpha** [comment]
it should go under /market/earningscal
in meantime you can download data from http://www.rightline.net/calendar/

**Comment by bkcollection** [comment]
it should be a different api for earnings calendar. 
Arrange by a specific date, next earnings release or last earnings release

**Comment by cdstamper** [comment]
Any update on when this is coming out of QA and getting released? @joshuablackburn-iex

**Comment by tgtwm1github** [comment]
I am interested in the same item; to get next earnings date for equities? Any information on when this will be available please?

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. If you havent already you can signup for the beta waitlist here: https://iexcloud.io/
