### ISSUE TITLE
return http status 404 or empty json for invalid stock symbol

### ISSUE THREAD

**Issue by shuwnyuantee** [iexg/IEX-API#30]
I realised for invalid stock symbol, IEX api doesn't return error code. It still return http `status 200 OK` with a valid JSON response, but all fields set to `N/A`. 

Eg: Key Stats API, for invalid symbol, it returns this:

```
{
    "returnOnEquity": "N/A",
    "returnOnAssets": "N/A",
    "returnOnCapital": "N/A",
    "profitMargin": "N/A",
    "priceToSales": "N/A",
    "priceToBook": "N/A",
    "day200MovingAvg": "N/A",
    "day50MovingAvg": "N/A",
    "institutionPercent": "N/A",
    "insiderPercent": "N/A",
    "shortRatio": "N/A",
    "EPSSurpriseDollar": "N/A"
}
```

Instead of the above, can it return let say http `status 404 not found` with error message? Or return empty json `{}`?

Thanks!

**Comment by leedstyh** [comment]
Thinking `{}` is good, or simply discard the invalid ones.

Say batch endpoint, user send some symbols and some of them are valid while others are not invalid. This case definitely returns a status 200 instead of 404.

**Comment by leedstyh** [comment]
https://github.com/iexg/IEX-API/issues/28 https://github.com/iexg/IEX-API/issues/29 https://github.com/iexg/IEX-API/issues/30

These seems the same issues, so let's talk together here.

**Comment by joshuablackburn-iex** [comment]
For now I think we will implement it as returning an empty object/array so valid symbols in a batch call continue to work.

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex  Great, thanks for prompt reply. 👍

**Comment by joshuablackburn-iex** [comment]
We've standardized the return values to match appropriate data type.  For unknown values we use null.  Please let me know if you find any data that still returns a value that breaks your typed variables.
