### ISSUE TITLE
Is there a tshark/wireshark filter for the binary feed?

### ISSUE THREAD

**Issue by cgi1** [iexg/IEX-API#300]
I know that the binary data feed is a different project (#13), but is there a way to get the protocol parser for to IEX Transport Protocol (IEX-TP)?

**Comment by vfrazao-ns1** [comment]
Hey @cgi1 it looks like there is another GitHub project under the IEX org that does what you're looking for (<https://github.com/iexg/iexdissectors>) but it hasn't had a commit in about 4 years so I'm not sure if it still works.

On another note, I've started working on a project to decode IEX's binary feeds into Python objects: <https://github.com/vfrazao-ns1/IEX_hist_parser>. If you have any ideas on what would be valuable in the project feel free to drop it in an issue.
