### ISSUE TITLE
Graph Data - "Historically adjusted" - for splits and dividends?  Or just splits?

### ISSUE THREAD

**Issue by bclous** [iexg/IEX-API#301]
## Summary
On your API documentation for chart data source it says "Historically adjusted market wide data".  It appears this data is adjusted for stock splits, but not dividends.   Can you confirm?

If it is indeed not adjusted for dividends, any plans to include an "adjusted close" data point in this response in the future?  Looks like you have the dividend data so it would be easy to calculate.  

Thanks!   Great API.

**Comment by evancarter-iex** [comment]
Closing. This is documented for IEXCloud. https://iexcloud.io
