### ISSUE TITLE
List data is missing when market closed on Sunday

### ISSUE THREAD

**Issue by bkcollection** [iexg/IEX-API#303]
## Summary

the gainers and losers list does not shown Friday result on Sunday. The gainers list shall be keep over the weekend until the market open again on Monday.

It shown as [ ] on Sunday

### Date/time of issue
happen on Sunday. Market close shall retain teh data on Friday market close data

### API URL

/stock/market/list/mostactive
/stock/market/list/gainers
/stock/market/list/losers
/stock/market/list/iexvolume
/stock/market/list/iexpercent

### What you expected to happen

market close data shall retain until the next market open again. 

### What actually happened

the list go to blank and show [ ] 

### Other Information (sample code, links, etc.)

the gainers and losers list does not shown Friday result on Sunday. The gainers list shall be keep over the weekend until the market open again on Monday.

It shown as [ ] on Sunday

**Comment by Ninjarab** [comment]
it's even worst, it seems like gainers and losers are not available during weekdays either 😢
