### ISSUE TITLE
Connecting to the websocket service

### ISSUE THREAD

**Issue by Orbyt** [iexg/IEX-API#305]
## Summary
I'm curious to know if it's possible to connect to the socket.io server provided by iex at `ws-api.iextrading.com/1.0/` using something other than socket.io, such as the popular `ws` package.

## Details
My server utilizes the `ws` package. How can I connect to the service provided by iex? Normally, I would be able to connect via something like the following:

```
import WebSocket from 'ws'
const wsClient = new WebSocket('wss://ws-api.iextrading.com/1.0/tops');
```
However, this does not appear to work, and results in a strange error:
> Error: Unexpected server response: 200

### API URL

- `https://ws-api.iextrading.com/1.0/tops`
- `wss://ws-api.iextrading.com/1.0/tops`

### What you expected to happen
A successful connection is established, and market data is received.

### What actually happened
No apparent connection is established, and no market data is received.

**Comment by evancarter-iex** [comment]
We havent tested it but this github comment seems to indicate it might be possible:

https://github.com/websockets/ws/issues/243#issuecomment-317954057
