### ISSUE TITLE
Stats for all stocks

### ISSUE THREAD

**Issue by yay** [iexg/IEX-API#306]
Currently you can get the tops and last trade data for all symbols
`https://api.iextrading.com/1.0/tops`
`https://api.iextrading.com/1.0/tops/last`
but not the stats:
`https://api.iextrading.com/1.0/stock/aapl/stats`

While returning the list of stats for all symbols might be an overkill, maybe you could allow querying up to, say, 10 fields and throttle such requests to one per second on top of that to keep load reasonable and prevent abuse?

Just as a single example, calling:

`https://api.iextrading.com/1.0/stock/stats?filter=week52high,week52low`

to return the 52-week high/low data for all symbols can be used in conjunction with `tops` API to determine the assets at new all time highs or lows.

**Comment by evancarter-iex** [comment]
Closing. This is fixed in IexCloud https://iexcloud.io
