### ISSUE TITLE
ws-api.iextrading.com/1.0/tops doesn't send subscribe/unsubscribe acknowledgments

### ISSUE THREAD

**Issue by yay** [iexg/IEX-API#307]
## Details

```javascript
const socket = require('socket.io-client')('https://ws-api.iextrading.com/1.0/tops')

socket.on('message', message => console.log(message))

socket.on('connect', () => {
  socket.emit('subscribe', 'fb,aapl,googl', data => console.log(`Subscribed: ${data}`))
  socket.emit('unsubscribe', 'aapl', data => console.log(`Unsubscribed: ${data}`))
})

socket.on('disconnect', () => console.log('Disconnected.'))
```

### Date/time of issue

All the time.

### API URL

https://ws-api.iextrading.com/1.0/tops

### What you expected to happen

The code above to log `"Subscribed: ..."` / `"Unsubscribed: ..."` messages to the console.

### What actually happened

No such messages are logged because the acknowledgments don't arrive.

-------------

Original issue: https://github.com/iexg/IEX-API/issues/287

**Comment by joshuablackburn-iex** [comment]
The current behavior is to immediately return a snapshot of the latest data for each symbol on subscribe.  Are you seeing this behavior?

**Comment by yay** [comment]
Yes, this seems to be the case, at least for the initial subscription. It's hard to tell for subscriptions that follow, because you are already receiving lots of messages for the symbols you've subscribed to previously.

And when you've unsubscribed, how do you know you've successfully unsubscribed? Do you wait to see if no messages arrive for the symbol you've unsubscribed from? If so, for how long do you wait to call it a success? The symbol you've unsubscribed from may simply not trade for a while, for how long depends on how heavily it is traded. A common situation right now: you send the unsubscribe message for a symbol, remove it from the watchlist, and it pops back into the watchlist before the unsubscribe is done.

For new subscriptions, I can at least keep a `pendingAdd` list and remove from it, when the first message for that symbol arrives. But if I try to do the same on unsubscribe and add to the `pendingRemove` list, it's not clear, when I can remove from that list.

Things are just not deterministic enough... If I could send the unsubscribe message, get the acknowledgement in a callback that I've indeed unsubscribed from those symbols, then safely remove them from the watchlist, without them popping right back, that would be perfect.

**Comment by mitalpha** [comment]
What should be done with iex websocket is to install the messaging broker over websocket: something like STOMP protocol broker (or AMQP, Openwire,...)
Probably, you have to benchmark messaging system together with websocket server selection. As I could recall several years ago jetty would be the ws server winner, but today who knows.... just try

**Comment by evancarter-iex** [comment]
IEXCloud will switch to using SSE rather than websockets. https://iexcloud.io
