### ISSUE TITLE
Feature request: an equivalent of /stock/market/previous for current day

### ISSUE THREAD

**Issue by fimmugit** [iexg/IEX-API#31]
I found the /stock/market/previous API very useful. However, an equivalent of it is missing for the current day as we monitor the progression of stocks in the market. Would it be possible to provide an API that gives current day's Open, High, Low, Latest price, and accrue volume (and possibly bid/ask and sizes) to current time?

**Comment by joshuablackburn-iex** [comment]
This is in the works.

**Comment by joshuablackburn-iex** [comment]
Related to #27

**Comment by fimmugit** [comment]
I noticed that a new endpoint open-close was added. There will be no close during trading hours. So it would be more useful to return day's open, high, low, latest price and volume. I understand that means to return a large data structure for the whole market if mimicking /market/previous. Alternatively, it would be nice to accept symbols as a filter to reduce the size of data returned. Thanks for the efforts.

**Comment by yccheok** [comment]
I believe we can get the certain information from current quote API - https://api.iextrading.com/1.0/stock/mcd/quote

open - yes
high - no
low - no
latest price - we can have real-time IEX price (`iexRealtimePrice`), or 15 min delayed price (`latestPrice`. I believe it is aggregated data from all exchanges)

Hope `high` and `low` can be added soon. Thank you.

**Comment by joshuablackburn-iex** [comment]
open-close endpoint should return OHLC

**Comment by yccheok** [comment]
Thanks. Will try out soon.
