### ISSUE TITLE
add data realated to optionable symbols

### ISSUE THREAD

**Issue by mitalpha** [iexg/IEX-API#310]
## Summary
Some trading strategies observe interference between stock  and options behavior close to an expiration date so that it would be great to have for stocks section in API somewhere added fields showing if this stock has traded options and some fields for optionable symbols.
 
## Details
today one could download file http://www.cboe.com/publish/scheduledtask/mktdata/cboesymboldir2.csv
and put weekly, quarterly, monthly, leaps indicators in app
 

### Date/time of issue
05/03/2018

**Comment by evancarter-iex** [comment]
End of day option data is now available: https://iexcloud.io/docs/api/#options
