### ISSUE TITLE
Are financials, TTM figures?

### ISSUE THREAD

**Issue by Abouhend** [iexg/IEX-API#311]
## Summary
When I make an HTTP request for financials,

Are the figures returned representing Financials of one quarter or TTM (twelve trailing months)?

I noticed that the variable "grossProfit" is placed in the financials and Key Stats but in the Key Stats, it is noted that it is TTM, so I wondered whether the rest of figures in the financials are the same.

## Details

reportDate": "2017-03-31",
      "grossProfit": 20591000000,
      "costOfRevenue": 32305000000,
      "operatingRevenue": 52896000000,
      "totalRevenue": 52896000000,
      "operatingIncome": 14097000000,
      "netIncome": 11029000000,
      "researchAndDevelopment": 2776000000,
      "operatingExpense": 6494000000,
      "currentAssets": 101990000000,
      "totalAssets": 334532000000,
      "totalLiabilities": 200450000000,
      "currentCash": 15157000000,
      "currentDebt": 13991000000,
      "totalCash": 67101000000,
      "totalDebt": 98522000000,
      "shareholderEquity": 134082000000,
      "cashChange": -1214000000,
      "cashFlow": 12523000000,

**Comment by joshuablackburn-iex** [comment]
Our documentation states financials return the four most recent quarters.
