### ISSUE TITLE
Cannot request charts for a date using the batch endpoint

### ISSUE THREAD

**Issue by nateyoder** [iexg/IEX-API#312]
## Summary
it would be nice to be able to request charts for a date using the batch endpoint as it is also a valid range.

## Details
It would be great to be able to get daily charts for a batch of stocks via a call like:
`https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=chart&range=date&date=20180501` 

This call currently returns:
`{"error":"\"date\" is not allowed"}`

### Date/time of issue
20180504

### API URL
`https://api.iextrading.com/1.0/stock/market/batch`

### What you expected to happen
The charts from the specified date to be returned

### What actually happened
`{"error":"\"date\" is not allowed"}`

### Other Information (sample code, links, etc.)
Alternative syntax like entering the date explicitly for the range or just entering the date (similar to how is done with news) would also be helpful.

**Comment by JohnP-Ryan** [comment]
Interested in this functionality as well.

**Comment by higgsja** [comment]
I would also like this functionality, exactly as nateyoder specified it.

**Comment by evancarter-iex** [comment]
Fixed in https://iexcloud.io
