### ISSUE TITLE
Stock prices from BVMF - Bovespa stock market (Brazil)

### ISSUE THREAD

**Issue by p4ged0wn** [iexg/IEX-API#314]
## Summary
Hi. I checked the symbols list (https://api.iextrading.com/1.0/ref-data/symbols) and I noticed that many stocks from Brazil are in fact available, but the symbols used are almost random... It is impossible to use this API since it apparently does not use the standard symbols from BVMF. For example:

ABEV3.SA stock is called ABEV in the API ref-data symbols
GGBR4.SA stock is called GGB in the API ref-data symbols
SAPR11.SA stock is called SBS in the API ref-data symbols

Do you know why they use these random symbols instead of the official ones?

please check the actual symbols:
ABEV3.SA - https://www.google.com.br/search?q=ABEV3&source=lnms&tbm=fin
GGBR4.SA - https://www.google.com.br/search?q=GGBR4&source=lnms&tbm=fin
SAPR11.SA - https://www.google.com.br/search?q=SAPR11&source=lnms&tbm=fin

Thank you very much!

**Comment by mcgwebdesign** [comment]
The symbols you mentioned are the US listed ADRs of the Brazilian securities. 

https://en.wikipedia.org/wiki/American_depositary_receipt
https://www.adrbnymellon.com/?cusip=02319V103
