### ISSUE TITLE
Earnings endpoint returns records with Fiscal Period in the future or with fiscal period not matching fiscal end date.

### ISSUE THREAD

**Issue by sdvisconti** [iexg/IEX-API#316]
## Summary
Earnings endpoint returns records with Fiscal Period in the future or with fiscal period not matching fiscal end date.

## Details
Fiscal period atttribute is populated inconsistently, sometimes it references periods in the future, e.g. Q3 and Q4 2018.

### Date/time of issue

May 6, 2018 10:20 am

### API URL
https://api.iextrading.com/1.0/stock/wmt/earnings

### What you expected to happen
Fiscal period should reflect correct reporting period.

### What actually happened
Earnings for Walmart fiscal end date 2018/1/31 have fiscal period Q4 2018
 
{"symbol":"WMT","earnings":[{"actualEPS":1.33,"consensusEPS":1.36,"estimatedEPS":1.36,"announceTime":"BTO","numberOfEstimates":12,"EPSSurpriseDollar":-0.03,"EPSReportDate":"2018-02-20","fiscalPeriod":"Q4 2018","fiscalEndDate":"2018-01-31","yearAgo":1.3,"yearAgoChangePercent":2,"estimatedChangePercent":5,"symbolId":7501},{"actualEPS":1,"consensusEPS":0.97,"estimatedEPS":0.97,"announceTime":"BTO","numberOfEstimates":15,"EPSSurpriseDollar":0.03,"EPSReportDate":"2017-11-16","fiscalPeriod":"Q3 2018","fiscalEndDate":"2017-10-31","yearAgo":0.98,"yearAgoChangePercent":2,"estimatedChangePercent":-1,"symbolId":7501},{"actualEPS":1.08,"consensusEPS":1.07,"estimatedEPS":1.07,"announceTime":"BTO","numberOfEstimates":14,"EPSSurpriseDollar":0.01,"EPSReportDate":"2017-08-17","fiscalPeriod":"Q2 2018","fiscalEndDate":"2017-07-31","yearAgo":1.07,"yearAgoChangePercent":1,"estimatedChangePercent":null,"symbolId":7501},{"actualEPS":1,"consensusEPS":0.96,"estimatedEPS":0.96,"announceTime":"BTO","numberOfEstimates":14,"EPSSurpriseDollar":0.04,"EPSReportDate":"2017-05-18","fiscalPeriod":"Q1 2018","fiscalEndDate":"2017-04-30","yearAgo":0.98,"yearAgoChangePercent":2,"estimatedChangePercent":-2,"symbolId":7501}]}

**Comment by joshuablackburn-iex** [comment]
Fiscal period is the companies reported fiscal period.  Companies can have a fiscal period that does not align with the calendar quarter.
