### ISSUE TITLE
API /deep/trades?symbols=XXXX not working

### ISSUE THREAD

**Issue by TechMF** [iexg/IEX-API#317]
## Summary

API for /deep/trades does not give any data.

### Date/time of issue

May 7, 2018. Time 8:10 AM (CET).

### API URL

https://api.iextrading.com/1.0/deep/trades?symbols=snap

### What you expected to happen

I would expect to get something like this:

{
  "SNAP": [
    {
      "price": 156.1,
      "size": 100,
      "tradeId": 517341294,
      "isISO": false,
      "isOddLot": false,
      "isOutsideRegularHours": false,
      "isSinglePriceCross": false,
      "isTradeThroughExempt": false,
      "timestamp": 1494619192003
    }
  ]
}

### What actually happened

All I get is
{}

### Other Information (sample code, links, etc.)
The problem is the same with any symbol I tried, not just SNAP. The problem also occurred a few days ago, then it worked for a day or so, but now the problem is back.

**Comment by joshuablackburn-iex** [comment]
/deep/trades will only return data on trading days.  At the end of each trading day we clean up the data.  Please give it a try during market hours.
