### ISSUE TITLE
Stale data in 'previous' EOD data table

### ISSUE THREAD

**Issue by aftersought** [iexg/IEX-API#318]
## Summary
"Previous" return data for older trading date than necessary

## Details
For the majority of the stocks in https://api.iextrading.com/1.0/stock/market/previous the 'date' field is 2018-05-02 (instead of -04 as it should be for today, 7th of May).

### Date/time of issue
The stale date was observed on Friday 4th of May first, the issue is still present.

### API URL
https://api.iextrading.com/1.0/stock/market/previous

### What you expected to happen
Expected to get trading EOD data for 2018-05-04

### What actually happened
Got trading EOD data for 2018-05-02

### Other Information (sample code, links, etc.)
None

**Comment by sdvisconti** [comment]
An update on this issue would be greatly appreciated.  The endpoint https://api.iextrading.com/1.0/stock/market/previous is still providing data for 2018-05-02 as of May 12.

**Comment by evancarter-iex** [comment]
@sdvisconti sorry for the delay. This should be fixed now. Please let us know if it isnt.

**Comment by sdvisconti** [comment]
Appears to be working again as of 5/15 5:00 pm EDT.  
What is the earliest time of day that the data should be fully available for the previous day?
I had noticed that if I query to early in the morning (i.e before 5 am EDT), I receive records for some, but not all, symbols.

Thank you.
