### ISSUE TITLE
changing iexId

### ISSUE THREAD

**Issue by mcgwebdesign** [iexg/IEX-API#319]
## Summary
I've noticed that the iexId field is changing around on some symbols. any particular reason? my read of the docs suggested that iexId would remain unchanged as symbols went through name/symbol changes

for example
5/3 HCXZ iexId : 14516
5/4 HCXZ iexId : 14518

5/4 HSEA iexId : 8748
5/7 HSEA* iexId : 14524

**Comment by joshuablackburn-iex** [comment]
The iexId is our best effort at providing a unique ID. There are cases when the ID can change, and those are usually associated with a corporate action, such as a new issue.  If the underlying issue changes (new company), it can get an new ID and still keep the same symbol.  There are also rare times when we receive conflicting information from multiple reference data providers, and we make an internal determination to change the ID.

**Comment by mcgwebdesign** [comment]
Thanks for the information. In my view, the examples shouldn't have caused an id change.

HCXZ there was no change at all.
HSEA was a call by the company (symbology change to add the call designator, but no change to the underlying)
ARGO today was a primary listing venue change along with a symbol change but no change to the underlying

Can go ahead and close this ticket, just wanted to check to see if there was a reason I was missing.

**Comment by joshuablackburn-iex** [comment]
That is a correct observation.  For new issues and IPOs, we don't have reference data from our providers, so we create an id, and then reassigned once we see the symbol from our providers.
