### ISSUE TITLE
1D chart OHLC values do not seem correct

### ISSUE THREAD

**Issue by absinha18** [iexg/IEX-API#321]
## Summary
Requesting data for intraday charting seems to result in OHLC values which have an open-close pair exactly match high-close. 

## Details

There seems to be some bug in the way OHLC is being computed and it seems OC is being copied over from HC

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/1d

### What you expected to happen
Open close high low values to mostly have distinct values.

### What actually happened 

See examples below for AAPL 1D chart 
{
		"date": "20180508",
		"minute": "12:48",
		"label": "12:48 PM",
		"high": 185.56,
		"low": 185.54,
		"average": 185.542,
		"volume": 110,
		"notional": 20409.6,
		"numberOfTrades": 2,
		"marketHigh": 185.58,
		"marketLow": 185.51,
		"marketAverage": 185.549,
		"marketVolume": 12657,
		"marketNotional": 2348498.5595,
		"marketNumberOfTrades": 157,
		"open": 185.56,
		"close": 185.54,
		"marketOpen": 185.54,
		"marketClose": 185.553,
		"changeOverTime": 0.0037598662677781796,
		"marketChangeOverTime": 0.00320074395670352
	},

Also see this record:

	{
		"date": "20180508",
		"minute": "12:44",
		"label": "12:44 PM",
		"high": 185.575,
		"low": 185.575,
		"average": 185.575,
		"volume": 200,
		"notional": 37115,
		"numberOfTrades": 2,
		"marketHigh": 185.612,
		"marketLow": 185.56,
		"marketAverage": 185.585,
		"marketVolume": 15073,
		"marketNotional": 2797317.7036,
		"marketNumberOfTrades": 151,
		"open": 185.575,
		"close": 185.575,
		"marketOpen": 185.582,
		"marketClose": 185.61,
		"changeOverTime": 0.00393839229200355,
		"marketChangeOverTime": 0.0033953837919084673
	},

**Comment by joshuablackburn-iex** [comment]
In this example, IEX only had 2 trades, so that would represent all 4 values.  You can see that the market OHLC is correct since it had 157 trades.

**Comment by joshuablackburn-iex** [comment]
They represent executed trades.  I'll double check the data.

**Comment by joshuablackburn-iex** [comment]
We double checked the data and everything is being displayed correctly.

**Comment by absinha18** [comment]
Ok. Thanks for checking.
