### ISSUE TITLE
Specify date range when using endpoint for news articles

### ISSUE THREAD

**Issue by imapug** [iexg/IEX-API#322]
## Summary
It would be nice to be able to specify a date range for article publication date when retrieving news articles related to a specific stock. 

## Details
As the news end-point is now, the range option - (Number between 1 and 50. Default is 10. i.e. .../news/last/N) seems to return the last N published articles related to {symbol}. Using this range option, it is difficult to retrieve a response of articles published within a range of specified datetimes, as the range option is N number of articles as opposed to N days/weeks etc.
  
### Date/time of issue
05/08/2018 - ongoing

### API URL
https://api.iextrading.com/1.0/stock/TDG/news/last/{n}

**Comment by timpaine-iex** [comment]
closing as stale, possible with `time-series`.
