### ISSUE TITLE
question on quote->latestVolume vs. sum of all volumes returned by volume by venue request.

### ISSUE THREAD

**Issue by jainraje** [iexg/IEX-API#323]
## Summary

Trying to understand differences between latestVolume vs the sum of all volume returned by volume by venue? I would expect latestVolume to be equal to the sum of all volumes by venue.

## Details

here is summary of returned values. Yahoo volume is included just as a reference.

symbol  regularMarketVolume
0   TSLA              5866982
  symbol latestVolume
0   TSLA      4540241
    volume venue      venueName        date marketPercent avgMarketPercent
0     5073  XASE  NYSE American  2018-05-08   0.000856896      0.000913634
0     9675  XNYS           NYSE  2018-05-08    0.00163423       0.00174694
0    11870  XCHI            CHX  2018-05-08      0.002005        0.0128637
0    36311  EDGA      Cboe EDGA  2018-05-08    0.00613341       0.00650411
0    50613  XPHL     Nasdaq PSX  2018-05-08     0.0085492        0.0071376
0    75110  BATY       Cboe BYX  2018-05-08     0.0126871        0.0151394
0    98160  IEXG            IEX  2018-05-08     0.0165805        0.0177139
0   113272  XBOS      Nasdaq BX  2018-05-08     0.0191331        0.0222525
0   246462  BATS       Cboe BZX  2018-05-08     0.0416307        0.0403422
0   342162  ARCX      NYSE Arca  2018-05-08     0.0577957        0.0580862
0   504060  EDGX      Cboe EDGX  2018-05-08     0.0851424        0.0974031
0  1510412  XNGS         Nasdaq  2018-05-08      0.255128          0.29124
0  2917022   TRF   Off Exchange  2018-05-08      0.492723         0.429489

volume from yahoo quote: 5866982, volume from iex quote latestVolume: 4540241, iex volume by venue sum: 5920202

### Date/time of issue

7:53pm PCT on 5/8/2018.

### What you expected to happen

I would expect the volume by venue volume sum to equal the total volume for the day traded for the security.
 
__

**Comment by mitalpha** [comment]
I have similar question: using websocket tops for subscribed symbol we get
...
volume
marketPercent

If we divide volume/marketPercent

result should be consolidated volume for national market (all venues) or what?
When I compare with some brokers data, discrepancy is too high

**Comment by joshuablackburn-iex** [comment]
@mitalpha on a single stock basis from TOPS, volume / marketPercent will give you consolidated volume.  This is last sale eligible only volume.  Who are you comparing our numbers with?

**Comment by mitalpha** [comment]
Hi Josh,

I use TDAmeritrade, ThinkOrSwim app.
some time  ago tops gave me for AMZN
volume= 10934
marketPercent=0.02009
vol/mktPct=544251
TDA shown VOLUME=773800

**Comment by jainraje** [comment]
@joshuablackburn : 

will you please answer my question at the top of this thread?

thank-you,
-jainraje

**Comment by jainraje** [comment]
Update:

I ran tests today (2018-05-10) at approx. 4:20PM PCT to compare volume numbers for symbol 'A' from 3 IEX api end points, 2 TDA endpoints, 2 Yahoo endpoints and Marketsmith charting tool:

Yahoo web quote api call: 1844868, 
Yahoo website: 1,844,868
IEX volume from quote: 1230144, 
IEX sum of volume by venue: 1824864
IEX tops: 1230144 (volume / percent volume)
TDA website: 1,844,868
TDA trading app: 1.84M
Marketsmith Charting tool: 1.8M

NOTES:
1) latestVolume from quotes endpoint matches volume / marketPercent from tops but is very different than all 3rd party (Yahoo, TDA, Marketsmith by ONeal data systems)
2) sum of volume by venue is very different than latestVolume. 
3) It appears sum of volume by venue should be used to get total volume traded per symbol.

Questions:
1) why the difference between latestVolume and the sum of volume by venue (I would have expected them to match)?
2) What parameter to use to get latest total trading volume per symbol?

TIA,
jainraje

**Comment by jainraje** [comment]
Another update:

11:29PM PCT pulled data from the 3 IEX endpoints:

quotes->latestVolume
sum of volume by venue
charts->volume

the end of day volume returned from the charts API does match volume numbers on Yahoo and TDA websites and other leading 3rd data providers.

Please clarify why latestVolume which refers to the total market volume of the stock does not match total Market volume provided by other data providers.

trying to understand what these different IEX volume numbers really represent.


thank

**Comment by jainraje** [comment]
HI IEX, any update here? I spent quite a bit of time outlining my question and running tests. Answers and clarifications would be appreciated. If any aspect is not clear, just let me know.  Thanks. 

Btw, you guys have a really awesome API/service.

**Comment by joshuablackburn-iex** [comment]
We are looking into this.  Thanks for running tests and providing detailed information.  We have to balance these with our normal operations.  Thanks for your patience.

**Comment by jainraje** [comment]
Understood. I appreciate your update. Do let me know if you would like me to run any additional tests or gather volume data from other 3rd party sources for comparison purposes.

**Comment by joshuablackburn-iex** [comment]
Couple of updates for you.  The volume by venue total is correct.  Keep in mind that volume by venue will be 15 minutes delayed, so it will not line up with real time volume on other platforms.  The small difference at the end of the day is due to the fact that we shut down our trading system at 5:00pm ET.  So we will not have the small amount of volume between 5pm and 8pm.  The volume obtained by dividing IEX volume by market share is currently a bug.  When we switched our back end processing the market share percentage changed to only update when IEX has a trade.  That would explain the larger difference after 4pm.  We are working on a fix for this.

**Comment by jainraje** [comment]
Thanks for the update. Very helpful. 

FYI, during my few related tests I noticed that latestVolume from quotes endpoint always matched volume / marketPercent from tops. Does this mean if tops volume number will be fixed so will latestVolume from quote? I have concerns on that latestVolume value. Could you clarify please..

As far as the current day's final volume from the charts endpoint. What time of the day does that get updated?

Again, all I can say is this IEX API/service is well...awesome.
