### ISSUE TITLE
REIT Common and Preferred Dividend Data

### ISSUE THREAD

**Issue by bbartock** [iexg/IEX-API#324]
## Summary
Data appears to be missing for REITs (Common and Preffered) for YTD.  I'm a newbie to this API so I might be missing something but i did check for 1Y and there is data going back further in time.

## Details
These are securities I've found with issue...
Common: 
AI,ANH,NSM,SLD,WMC,RSO,BXMT,DX,NYMT,PFSI,EARN,MITT,MTGE,RWT,CYS,CHMI,IVR,MFA,CMO,TWO,CIM,NRZ,NLY,NLY,NRZ
Preferred:  
DX-B,DX-A,AGNCN,CHMI-A,NYMTP,NYMTO,MTGEP,IVR-A,DLR-I,DLR-H,CYS-A,CMO-E,ARI-C,ANH-C,ANH-A,AGNCB,CYS-B,ANH-C,DLR-G

### Date/time of issue
TODAY

### API URL
"https://api.iextrading.com/1.0/stock/NRZ/dividends/ytd"

**Comment by evancarter-iex** [comment]
Closing. This is fixed in IexCloud https://iexcloud.io
