### ISSUE TITLE
inconsistent data on batch request

### ISSUE THREAD

**Issue by PatrickCaneloDigital** [iexg/IEX-API#325]
## Summary
In my test I use a batch request for 4 stock quotes including quote, chart and dividends
I get some strange errors, and was thus analyzing, and it seems that the returned data are inconsistent from company to company

## Details
Based on this query
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb,ibm,tsla&types=quote,chart,dividends&range=1y

I checked the results and two chart-data (fb, tsla) are missing, and the ibm chart contains the same data as the dividends (in fact it's dividend data)
I counterchecked the individual data with these queries:
https://api.iextrading.com/1.0/stock/aapl/chart/1y
https://api.iextrading.com/1.0/stock/fb/chart/1y
https://api.iextrading.com/1.0/stock/ibm/chart/1y
https://api.iextrading.com/1.0/stock/tsla/chart/1y
and all deliver the data nicely...
So I went back analyzing the returned data form the batch and except the apple report, nothing adds up.
FB & TSLA are strangely empty (charts & dividends) and IBM has the dividend data under the chart entry

### Date/time of issue
Thursady May 10th 2018, 17:21

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb,ibm,tsla&types=quote,chart,dividends&range=1y

### What you expected to happen

I expected to get all data from the individual companies, including dividends and charts

### What actually happened

I got a complete result only for aapl
fb & tsla returned no data, neither for chart nor for dividend
and ibm had the dividend data in the chart part

**Comment by PatrickCaneloDigital** [comment]
I've found out (as an _additional bug_ or request), that the data are _also inconsistent when defining parameters (symbol,type,etc) in different order_; apparently the order matters which from user perspective is not ideal and can be considered a bug as the output should always be the same 

**CHANGING TYPE ORDER:**
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,amd,fb,ibm,intc&types=quote,chart,dividends&range=1m&last=5

does not produce the same results as

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,amd,fb,ibm,intc&types=quote,dividends,chart&range=1m&last=5

**CHANGING SYMBOL ORDER:**
https://api.iextrading.com/1.0/stock/market/batch?symbols=amd,aapl,fb,ibm,intc&types=quote,chart,dividends&range=1m&last=5

does not produce the same result as

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,amd,fb,ibm,intc&types=quote,chart,dividends&range=1m&last=5

**Comment by cgi1** [comment]
@PatrickCaneloDigital Yes, this is a bug and weird behaviour.

There is chart data in the one order for AAPL:

<img width="279" alt="grafik" src="https://user-images.githubusercontent.com/18695252/40270634-f3ac953a-5b90-11e8-8839-999e026fd3ab.png">


In the other not:
<img width="239" alt="grafik" src="https://user-images.githubusercontent.com/18695252/40270625-d64da5ce-5b90-11e8-819d-e735f0d6cb4f.png">
