### ISSUE TITLE
Missing RDS.B dividend on 2018-03-27

### ISSUE THREAD

**Issue by x1a0** [iexg/IEX-API#326]
## Summary
Missing RDS.B dividend payed on 2018-03-27.

## Details
The response of `https://api.iextrading.com/1.0/stock/rds.b/dividends/ytd` is empty. But RDS.B pays dividends quarterly and on 2018-03-27 it paid dividend.

### Date/time of issue
2018-05-11

### API URL
`https://api.iextrading.com/1.0/stock/rds.b/dividends/ytd`

### What you expected to happen
To have 1 entry in the response.

### What actually happened
Empty set in response.

### Other Information (sample code, links, etc.)
```
curl https://api.iextrading.com/1.0/stock/rds.b/dividends/ytd
```

**Comment by ajs11174** [comment]
I have the same issue with AAPL. Actually all the examples @ [https://iextrading.com/developer/docs/#dividends](https://iextrading.com/developer/docs/#dividends) are wrong. Apple paid its most recent dividend on 5/11/18 with an ex-date of 5/11/18. And that record does not show in any of the endpoints.

I tested this endpoint [https://api.iextrading.com/1.0/stock/aapl/dividends/1m](https://api.iextrading.com/1.0/stock/aapl/dividends/1m) on 5/26/18 and it came back blank.

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for the beta waitlist here: https://iexcloud.io/
