### ISSUE TITLE
Firehose for DEEP data

### ISSUE THREAD

**Issue by biyimaks** [iexg/IEX-API#327]
## Summary
For the DEEP web socket endpoint, we can currently subscribe to the DEEP channel for only one stock at a time. Is there a way to subscribe to all DEEP events for all stocks? Something similar to the `firehose` susbscription for the TOPS & Last endpoints?

Also, is there any update on when the WebSockets server rewrite work your team is doing will be ready?

**Comment by joshuablackburn-iex** [comment]
This is something we'd like to eventually offer, but we don't at this time due to the volume of data.

**Comment by biyimaks** [comment]
Thanks for the prompt response.

**Comment by yay** [comment]
Probably should reopen this, so it remains on their tracker.

**Comment by biyimaks** [comment]
@yay, I've reopened it.

**Comment by timpaine-iex** [comment]
closing as stale here, feel free to request on [roadmap](https://iexcloud.io/console/roadmap) where we've centralized requests.
