### ISSUE TITLE
https://api.iextrading.com/1.0/stock/aapl/stats return different answers 

### ISSUE THREAD

**Issue by amircodan** [iexg/IEX-API#328]
## Summary
when I run api query with symbol csco I get one structure
but with "vnet" I get another structure, so I can't make a single procedure. 

### Date/time of issue
2018-05-13

### API URL
https://api.iextrading.com/1.0/stock/aapl/stats

### What you expected to happen
same results
for example :
"company name" is first, marketcap is secont and so on
{"companyName":"Apple Inc.","marketcap":926945875420,"beta":1.296345,"week52high":190.37,"week52low":142.2,"week52change":24.4051,"shortInterest":50912078,"shortDate":"2018-04-30","dividendRate":2.92,"dividendYield":1.5483323,"exDividendDate":"2018-05-11 00:00:00.0","latestEPS":9.2,"latestEPSDate":"2017-09-30","sharesOutstanding":4915138000,"float":4905242477,"returnOnEquity":37.81,"consensusEPS":3.82,"numberOfEstimates":9,"EPSSurpriseDollar":null,"EPSSurprisePercent":1.8325,"symbol":"AAPL","EBITDA":61840000000,"revenue":186280000000,"grossProfit":71331000000,"cash":228093000000,"debt":346419000000,"ttmEPS":9.73,"revenuePerShare":38,"revenuePerEmployee":1514472,"peRatioHigh":114.1,"peRatioLow":0,"returnOnAssets":14.13,"returnOnCapital":null,"profitMargin":21.09,"priceToSales":3.7752979,"priceToBook":7.31,"day200MovingAvg":166.10744,"day50MovingAvg":173.33679,"institutionPercent":66.2,"insiderPercent":null,"shortRatio":1.6044682,"year5ChangePercent":2.1803234455893015,"year2ChangePercent":1.089375968021768,"year1ChangePercent":0.2548105840834208,"ytdChangePercent":0.10350113954529366,"month6ChangePercent":0.08827560338733652,"month3ChangePercent":0.16352531079371932,"month1ChangePercent":0.09274007804872403,"day5ChangePercent":0.022451758970511045,"day30ChangePercent":0.13581201615516272}

**Comment by yay** [comment]
Perhaps a better way to phrase this would be `The order of fields in the returned object is different for different symbols`? I can `make a single procedure`, but consistency wouldn't hurt.

**Comment by amircodan** [comment]
Hi,
Yes, I am interested in consistently of returned response. For now the fields order depending on the symbol requested. 
thanks

amir

**Comment by BitpopCoin** [comment]
Whys it matter? Json doesn't care

**Comment by joshuablackburn-iex** [comment]
This call is returning in object.  Objects are unordered.  For further reading:

https://www.json.org/
"An object is an unordered set of name/value pairs"

We are using the exact same code to return all data, so I cannot speak to why you see a different order, however, order does not matter in an Object.
