### ISSUE TITLE
Quote data is delayed ~5 minutes

### ISSUE THREAD

**Issue by kesarweb** [iexg/IEX-API#329]
## Summary
Quote data is delayed ~5 minutes

## Details
Quote data is delayed ~5 minutes . 
Please see screenshot below.

### Date/time of issue
05/14/2018 11:00 AM

### API URL
https://api.iextrading.com/1.0/stock/IMTE/quote

### What you expected to happen
Per IEX trading API FAQ data is supposed to be Real Time. I expected my clock (already synchronized with Microsoft servers) to match time in the quote returned.

### What actually happened
Regardless of which ticker I request a quote for I get delayed data, always.

### Other Information (sample code, links, etc.)
![image](https://user-images.githubusercontent.com/4732537/40005437-ec78bdb8-5765-11e8-88c6-2107c2eac8a3.png)

**Comment by joshuablackburn-iex** [comment]
Quote data from IEX is real-time, but not every stock trades or quotes rapidly.  Real-time prices are coming from IEX only, so the data will only update when we have a trade.

**Comment by kesarweb** [comment]
@joshuablackburn-iex  oh... can I get real time data anyhow from IEX for stocks that have no trades via IEX ?

Thanks,
Anton

**Comment by joshuablackburn-iex** [comment]
Not at this time.  We are able to deliver our own trades in real-time, but market wide trades come from the SIP, and they have their own price constraints.  This is something we are investigating for a future release.
