### ISSUE TITLE
New API endpoint open-close doesn't update close timestamp accordingly

### ISSUE THREAD

**Issue by mmjdotdk** [iexg/IEX-API#33]
Hey guys,

First off -- thanks for a great endpoint (open-close). It just updated todays quote for AAPL as expected, 15 minutes after market closed. When I call the endpoint I get:

`$ curl -s https://api.iextrading.com/1.0/stock/aapl/open-close/`
`{"open":{"price":153.23,"time":1506691800379},"close":{"price":154.12,"time":1506691800379}}`

Where the values for open and close (153.23 and 154.12) seems spot on and ditto the open time. But the close time is the same as the open time still?

**Comment by mmjdotdk** [comment]
I also wonder why `closeTime` below the `quote` endpoint for AAPL also has 9:30 am for the day it closed (it's the same timestamp as the `open-close` endpoint uses.

**Comment by joshuablackburn-iex** [comment]
This should be resolved.
