### ISSUE TITLE
Historically Adjusted Stock Prices Incorrect because of Incorrect Dividends.

### ISSUE THREAD

**Issue by tmb8u** [iexg/IEX-API#335]
## Summary
I am trying to back into the actual OHLC stock price data not the "Historically Adjusted OHLC Data".  I can reverse adjust with no problem if we agree on the dividend stream.  

I have found that IEX dividend data is not up to date and in some cases incorrect.  This leads to errors in the entire time series for stocks with bad data.

It would be extremely useful if you could provide the raw OHLC and then we can adjust with our own dividend schedules.  

## Details
For example CCE stock returns incorrectly adjusted time series.
"/stock/cce/chart" returns an adjusted time series that is incorrect on the last div date 5/11/18.  The price series seems to be adjusted for a .26 dividend.  But actually the last dividend was changed to .31 for the latest dividend.  This throws off the entire time series historically.
Further 
"/stock/cce/dividends" doesnt even have the dividend data for the last dividend so I cant even see what you are using to adjust without comparing to other sources and finding the difference.

Another Example for BP
"/stock/bp/chart" returns an adjusted time series that is incorrect because the dividend on 5/10/18 is not included or adjusted.  
'/stock/bp/dividends' also does not include this dividend.

### Date/time of issue
2018-05-16 2:40 pm

### API URL
"/stock/cce/chart" 
"/stock/cce/dividends" 

### What you expected to happen
Correct price adjustments or the availability of the RAW data.

It would be extremely useful if you could provide the raw OHLC and then we can adjust with our own dividend schedules.  

### What actually happened
Bad historically adjusted prices.

**Comment by evancarter-iex** [comment]
Is this still a problem with https://iexcloud.io
