### ISSUE TITLE
Latest quote for all stocks like tops/last returns the latest trade?

### ISSUE THREAD

**Issue by Stefama2020** [iexg/IEX-API#340]
Is there an api for getting in a single lightweight call the latest quote for all the stocks traded on IEX similar to what tops/last does for latest trades ?

**Comment by joshuablackburn-iex** [comment]
This type of call does not currently exist.  The only thing we have at the moment is all previous close prices in a single call.  This is something we can look at for a future release.

**Comment by joshuablackburn-iex** [comment]
/stock/market/ohlc will give you data for the current trading day.
/stock/market/previous will give you data for the previous trading day.

**Comment by JohnRobson** [comment]
@joshuablackburn-iex "/stock/market/ohlc" won't show High and Low. I believe that isn't necessary show the open_time.  Just: "close_time, open, high, low, close, volume".

**Comment by timpaine-iex** [comment]
closing as stale
