### ISSUE TITLE
exDividendDate inconsistency in stock/<symbol>/stats

### ISSUE THREAD

**Issue by yay** [iexg/IEX-API#341]
## Summary

The `exDividendDate` is in the `yyyy-MM-dd HH:mm:ss.S` format, where the time component (`HH:mm:ss.S`) is always `00:00:00.0`? Do you plan to use the time component in the future for `exDividendDate`? Can't you use the same format as `"latestEPSDate": "2017-12-31"` instead?

`exDividendDate` is either a string in the `yyyy-MM-dd HH:mm:ss.S` format or the number `0`.

Can you use `null` instead when the dividend date is not known? (Same request for `shortDate` and `latestEPSDate`. Should I create a separate ticket for that?).

Basically, one has to do
```kotlin
if (stats.exDividendDate != LocalDate.ofEpochDay(0)) {
  doStuff()
}
```
or create a custom deserializer that treats zeros as nulls,
instead of a simple null comparison.

### Date/time of issue

Always.

### API URL

https://api.iextrading.com/1.0/stock/AAOI/stats - returns `0` for `exDividendDate`
https://api.iextrading.com/1.0/stock/AAPL/stats - returns `"2018-05-11 00:00:00.0"` for `exDividendDate`

### What you expected to happen

Same format used for `exDividendDate`.

### What actually happened

Either a string or number zero is returned.

**Comment by Ninjarab** [comment]
Hey @joshuablackburn-iex 

The key `exDividendDate` is still returning either 0 or a string in the stats payload.

https://api.iextrading.com/1.0/stock/amd/stats - returns `0`
https://api.iextrading.com/1.0/stock/aapl/stats - returns `"2018-08-10 00:00:00.0"`

Please, stay consistent with the returned type, as @yay mentioned, `null` would be perfect!

Thanks,

**Comment by evancarter-iex** [comment]
Should be fixed in IEX Cloud. https://iexcloud.io
