### ISSUE TITLE
Upcoming ex-dividend dates?

### ISSUE THREAD

**Issue by elisag1990** [iexg/IEX-API#343]
The dividends call only returns past ex-dividend dates. Are you planning to return the next ex-dividend date ?

**Comment by joshuablackburn-iex** [comment]
We are actually working on this right now.  We are in QA with a number of additional endpoints to make upcoming corporate actions easily accessible.

**Comment by rpaskowitz** [comment]
I've noticed that recent dividends are also sometimes missing. Any chance the future dividend work may address this? As an example, https://api.iextrading.com/1.0/stock/CM/dividends/ytd has an empty response, but there was a dividend with record date of 2018-03-28. If unrelated, I can file a separate issue.

**Comment by Wheaties466** [comment]
@joshuablackburn-iex any idea if/when this is going to be released?

**Comment by evancarter-iex** [comment]
Closing. This is fixed in https://iexcloud.io
