### ISSUE TITLE
latestEPS in the stats endpoint is not matching the latest period's EPS in Earnings endpoint

### ISSUE THREAD

**Issue by rkilli** [iexg/IEX-API#344]
## Summary

latestEPS in the stats endpoint is not matching the latest period's EPS in Earnings endpoint

## Details

Referring to the output of this REST call : https://api.iextrading.com/1.0/stock/market/batch?symbols=CECE&types=financials,earnings,stats&range=5y 
The latestEPS field in the Stats endpoint is equal to -0.09 whereas the earnings endpoint shows "actualEPS": 0.05, These two are not matching

### Date/time of issue
23/05/2018

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=CECE&types=financials,earnings,stats&range=5y

### What you expected to happen

The EPS value should match in both the endpoints

### What actually happened

the latest EPS value is not matching between the earnings and stats endpoint.

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
