### ISSUE TITLE
Meaning of shortDate in Key Stats API and other fields

### ISSUE THREAD

**Issue by henadzit** [iexg/IEX-API#345]
## Summary
Hi there. Thank you very much for the great service!

I have a question about the Key Stats endpoint. What's the meaning of the `shortDate` field in https://iextrading.com/developer/docs/#key-stats?

Also what is the date period that the metrics represent? It looks like the revenue matches neither the fiscal year revenue or last year revenue.

### API URL
https://iextrading.com/developer/docs/#key-stats

**Comment by mitalpha** [comment]
shortDate is the date when stock shares short interest was recorded, see call output
...
shortInterest | 46385494
shortDate | "2018-05-15"
...

**Comment by henadzit** [comment]
@mitalpha, thank you for the answer!
