### ISSUE TITLE
Batch API ist still buggy

### ISSUE THREAD

**Issue by PatrickCaneloDigital** [iexg/IEX-API#346]
## Summary
According to issue #325  which was closed but not really resolved:
Batch Request ist still quite buggy. 
At one hand, it does not deliver all the requested data
Additionally the results are inconsistent and vary depending on the order of the symbols

### Date/time of issue
25.05.2018 10.25

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,amd,fb,ibm,tsla&types=quote,chart,dividends&range=1y

### What you expected to happen
All data are delivered as requested
AAPL: quote, chart & dividend
AMD: quote, chart & dividend
FB:  quote, chart & dividend
IBM: quote, chart & dividend
TSLA: quote, chart & dividend

### What actually happened
AAPL: quote, chart & dividend
AMD: only quote
FB:  only quote
IBM: quote, chart & dividend
TSLA: only quote

There are data missing for AMD, FB & TSLA, which in fact makes no sense becuase when asking for the charts at a individual level, all data are available

now, just to test we can change the order of the symbols, using this API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=amd,aapl,fb,ibm,tsla&types=quote,chart,dividends&range=1y

AMD: quote (AND SUDDENLY) chart
AAPL: quote, chart & dividend
FB:  only quote
IBM: quote, chart & dividend
TSLA: only quote

=> that shows that one hand the batch request delivers incomplete data, but additionally there happens some voodoo depending on the symbol order, as in the second case, the API delivers a chart for AMD.

**Comment by rodoabad** [comment]
Here's another example.

```
https://api.iextrading.com/1.0/stock/HRL/batch?types=dividends,splits&range=5y
```

and

```
https://api.iextrading.com/1.0/stock/HRL/batch?types=splits,dividends&range=5y
```

**Comment by evancarter-iex** [comment]
This is fixed in IEXCLoud. More information here: https://iexcloud.io/
