### ISSUE TITLE
JNJ mismatch ohlc data

### ISSUE THREAD

**Issue by evercltech** [iexg/IEX-API#348]
## Summary
Data mismatch between iex chart data and other data providers. Dividend 0.9 is the difference.

## Details
IEX shows close as 121.35 other show 122.25. Open, High and Low also differ
### Date/time of issue
05/24/2018

### API URL
https://api.iextrading.com/1.0/stock/jnj/chart/1y

### What you expected to happen
Data match

### What actually happened
{"date":"2018-05-24","open":122.3129,"high":122.4816,"low":120.6551,"close":121.35,"volume":6923611,"unadjustedVolume":6923611,"change":-1.1912,"changePercent":-0.972,"vwap":121.2845,"label":"May 24","changeOverTime":-0.01848579089339226}

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
