### ISSUE TITLE
Is there an API changes log?

### ISSUE THREAD

**Issue by dblock** [iexg/IEX-API#349]
## Summary

I cannot find an API changes log and some changes have been observed recently that broke some not so careful clients. It doesn't quite seem that the changes are backwards incompatible, but not all fields have clear enough documentation to be sure.

## Details

For example `iexLastUpdated` is now returning `nil`.

### Date/time of issue

May 26, 2018

### API URL

Quote API for MSFT.

### What you expected to happen

The API not to change or to be able to find a definitive log of changes.

### What actually happened

At least one field is now `nil`. 

### Other Information (sample code, links, etc.)

See https://github.com/dblock/iex-ruby-client/commits/master for a more detailed log of fixes.

**Comment by joshuablackburn-iex** [comment]
https://iextrading.com/developer/docs/#changelog
