### ISSUE TITLE
Usage of undocumented API end point

### ISSUE THREAD

**Issue by scottycc** [iexg/IEX-API#35]
While reviewing your stocks app I noticed a call to an undocumented API. 

Is it ok for us to make use of this API (overview)?

**Comment by joshuablackburn-iex** [comment]
It is not part of the official API offering and should not be used. Some endpoints are not designed for public consumption, and therefore cannot be relied upon.

**Comment by scottycc** [comment]
Ok, no problem. 

I was not sure if it was that or just an undocumented future release endpoint.
