### ISSUE TITLE
Symbols containing non-alphanumeric chars ?

### ISSUE THREAD

**Issue by elisag1990** [iexg/IEX-API#350]
I see the ref-data/symbols endpoint returning symbols containing non-alphanumeric chars, are they correct? I've tried using a few in other calls and nothing gets returned. Can you please clarify if any cleaning is needed?

Examples: "WFC+", WYND#", "TPGH=", "VST+A", SAN-I*", "BAC-I*"

**Comment by joshuablackburn-iex** [comment]
We use symbols represented as Nasdaq Integrated Symbology (INET).  Those characters are valid in this symbol convention.  It is recommended to URL encode the symbols to ensure the call works properly.  For example:

https://api.staging.iextrading.com/1.0/stock/WFC+/quote

will work, but

https://api.staging.iextrading.com/1.0/stock/WYND#/quote

will not.  Instead, use:

https://api.staging.iextrading.com/1.0/stock/WYND%23/quote
