### ISSUE TITLE
Support for non-US markets

### ISSUE THREAD

**Issue by jasonboggess** [iexg/IEX-API#351]
## Summary
Currently, it looks like only US markets are supported. Wondering if you could support UK markets and Canadian markets such as

- London Stock Exchange
- Toronto Stock Exchange
- Euronext

https://en.wikipedia.org/wiki/List_of_stock_exchanges

### API URL
https://api.iextrading.com/1.0/ref-data/symbols

### What you expected to happen

- Other stocks are supported

### What actually happened

- Only US stocks appear

**Comment by douglasale** [comment]
**Summary**
I could see that Brazil's Stock Exchange (B3) is also not supported.

**What you expected to happen**

- Brazil's stocks are supported

**What actually happened**

- Only US stocks appear

**Comment by mathieucarbou** [comment]
TSX 👍

**Comment by doppelgunner** [comment]
Please support philippines stocks (PSEI) too soo I could create my own price alert. thanks!!!

**Comment by Michael89s** [comment]
It would be great if you could support Warsaw Stock Exchange :)

**Comment by dblock** [comment]
+1 on Canadian stocks, coming from one of my users at https://market.playplay.io (eg. WJA.TO).

**Comment by GuilhermeZaniniMoreira** [comment]
+1 on Brazil stocks!

**Comment by JP-MRPhys** [comment]
NSE (India) would be a great addition too

**Comment by evancarter-iex** [comment]
Toronto End of Day prices has been deployed: https://iexcloud.io/docs/api/#changelog

**Comment by lukepereira** [comment]
> Toronto End of Day prices has been deployed: https://iexcloud.io/docs/api/#changelog

Have you experimented with this yet? I'm not seeing TSX tickers in their list of supported stocks and don't see where I can specify an exchange. Thanks

**Comment by evancarter-iex** [comment]
Circling back on this, international symbols and exchanges are documented here:

https://iexcloud.io/docs/api/#international-symbols

**Comment by evancarter-iex** [comment]
Closing.This is fixed in https://iexcloud.io
