### ISSUE TITLE
IEX Chart 1D Returning empty array

### ISSUE THREAD

**Issue by davimchun45** [iexg/IEX-API#352]
## Summary
The IEX Chart API for 1D is currently returning an empty array.

### Date/time of issue
5/28/2018 11:26

### API URL
https://api.iextrading.com/1.0/stock/msft/chart/1d

### What you expected to happen
Return data from last friday or today.

### What actually happened
Returned an empty array.

**Comment by joshuablackburn-iex** [comment]
The markets were closed yesterday.
