### ISSUE TITLE
batch API giving no access control allow origin error

### ISSUE THREAD

**Issue by Skgadhoke** [iexg/IEX-API#353]
## Summary
The batch API gives me following error:

(index):1 Failed to load https://ws-api.iextrading.com/1.0/stock/market/batch?symbols=AAPL,BA&types=quote: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.
I can run it on browser by enabling CORS. I am building an ionic3 application, and trying to call the batch API, and testing my application locally using Xcode.

### Date/time of issue
4:04 CST May 28th, 2018

### API URL
https://ws-api.iextrading.com/1.0/stock/market/batch?symbols=AAPL,BA&types=quote

**Comment by davimchun45** [comment]
This isn't a problem with the api but rather an issue with CORS.

**Comment by Skgadhoke** [comment]
I have used the other API: https://api.iextrading.com/1.0/stock/goog/company and not run into the CORS issue. for the batch API I have tried to use a proxy url to get around CORs however that did not resolve the problem. If there is another way to resolve the CORS issue on my end could you please provide some documentation.

**Comment by joshuablackburn-iex** [comment]
Your first example is using the Websocket domain ws-api.iextrading.com which does not support REST requests.  Just change to  https://api.iextrading.com/1.0/stock/market/batch?symbols=AAPL,BA&types=quote
