### ISSUE TITLE
These ticker in the IEX stocks but no data

### ISSUE THREAD

**Issue by bkcollection** [iexg/IEX-API#354]
## Summary
Ticker in for the stocks unable to get data for quote

## Details
Hillman HLM
LTN^ liveXLive
PRSP#
RiverNorth Marketplace Lending (RMPL- )
SMTA# Spirit MTA
SRC#  
TDACU 
WH#
WYND#
### Date/time of issue
All the while

### API URL
all APIs with the stocks above

### What you expected to happen
All the tickers above has data in Yahoo and Nasdaq. The stocks able to find in IEX website as well. 
Eg. https://iextrading.com/apps/stocks/#/HLM-
Nothing was shown in for this stocks

### What actually happened

IN Yahoo https://finance.yahoo.com/quote/HLM-P?p=HLM-P
I am not sure why IEX api for this ticker is HLM- instead of HLM-P
Besides, what is #,-,^ in the ticker actually mean?
It is different from Nasdaq and Yahoo

**Comment by elisag1990** [comment]
Same as my question https://github.com/iexg/IEX-API/issues/350

**Comment by joshuablackburn-iex** [comment]
Please see the answer on #350.  Yahoo uses a different symbology than we do, so there will be differences in ticker names.  We use the standard Nasdaq Integrated (INET) symbology.
