### ISSUE TITLE
For few stocks, I am getting wrong high and low

### ISSUE THREAD

**Issue by rottla** [iexg/IEX-API#355]
## Summary
I am using batch request like https://api.iextrading.com/1.0/stock/market/batch?symbols=UCC,AAPL&types=quote&filter=latestPrice,high,low,open,latestVolume . I am getting open price higher than high of the day

## Details
Happens only for less liquid ETFs like UCC
### Date/time of issue

Tuesday May 29 2018

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=UCC,AAPL&types=quote&filter=latestPrice,high,low,open,latestVolume
Result I get is:
 {"UCC":{"quote":{"latestPrice":86.265,"high":86.265,"low":86.265,"open":87.56,"latestVolume":308}},"AAPL":{"quote":{"latestPrice":187.9,"high":188.75,"low":186.87,"open":187.6,"latestVolume":21573658}}}

Problem is with UCC ticker

### What you expected to happen
Open < High

### What actually happened
Open > High

**Comment by gabrieldodan** [comment]
I have same issue  for this request https://api.iextrading.com/1.0/stock/market/batch?symbols=SSBI,ARCT&types=quote

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
