### ISSUE TITLE
How do I get S&P index values

### ISSUE THREAD

**Issue by woaksie** [iexg/IEX-API#356]
## Summary

I have tried to various symbols e.g. %5EGSPC but always get back unknown. Is there a way to get this info or is it not available?

**Comment by BenCh94** [comment]
https://api.iextrading.com/1.0/stock/voo/chart/5y: Vanguard SandP

**Comment by joshuablackburn-iex** [comment]
Please see issue #36 

We currently do not have index values due to highly restrictive and expensive data contracts.  You can use the symbol SPY.  It tracks the S&P.

**Comment by woaksie** [comment]
Thanks guys
