### ISSUE TITLE
Is premarket/postmarket data available?

### ISSUE THREAD

**Issue by elisag1990** [iexg/IEX-API#357]
No issue, only a question: is premarket/postmarket data available via one of the endpoints?

**Comment by joshuablackburn-iex** [comment]
This is available in /stock/quote  https://iextrading.com/developer/docs/#quote

extendedPrice, extendedChange, extendedChangePercent, extendedPriceTime

These represent prices from 8am-9:30am and 4pm-5pm.  We are aiming to cover the full pre/post market hours in a future version.

**Comment by dextervip** [comment]
@joshuablackburn-iex Is there any way to fetch premarket/postmarket historical data?
