### ISSUE TITLE
How to interpret the intraday volume?

### ISSUE THREAD

**Issue by cgi1** [iexg/IEX-API#359]
## Summary

The intraday volume data does not match with other sources.

## Details

[Example request M1 AAPL](https://api.iextrading.com/1.0/stock/market/batch?symbols=AAPL&types=quote,chart&range=1d&last=5)

```
{  
             "date":"20180601",
             "minute":"09:31",
             "label":"09:31 AM",
             "volume":1252,
             "notional":235275.63,
             "numberOfTrades":14,
             "marketVolume":127177,
             "marketNotional":23900773.8547,
          },
```

If I read the [same candle from alphavantage.co](https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=AAPL&interval=1min&apikey={YOUR_KEY}&outputsize=full), i get other values:

```
"2018-06-01 09:31:00": {
            "1. open": "187.9000",
            "2. high": "187.9900",
            "3. low": "187.7500",
            "4. close": "187.7700",
            "5. volume": "128793"
        },
```

I love your batch request API! But what is your volume column saying _exactly_? And would it be possible to get the complete market volume (including the volume on other exchanges)? And if not: Would it be possible to see the % of volume which has been traded on this exchange, so that I can calculate the complete volume for all exchanges?

Thanks in advance!

### Date/time of issue
Today, last week, always. ;)

### API URL

See example URLs above

### What you expected to happen
Matching volume between all sources so that a user can use your batch request API to get a large list of correct intraday data.

### What actually happened
Volume does not match with other sources.

### Other Information (sample code, links, etc.)
See above.

**Comment by joshuablackburn-iex** [comment]
Our "volume" key is shares traded on IEX only.  "marketVolume" is all last sale eligible shares traded across the whole market.  The marketVolume key is what we see as an Exchange trading these stocks as apposed to other sources.  I cannot speak to their accuracy, or where they get their data.
