### ISSUE TITLE
Question: Quote for Indices?

### ISSUE THREAD

**Issue by bclous** [iexg/IEX-API#36]
I'm trying to pull a quote for the S&P 500 Index (as well as the DOW).  I've tried the quote endpoint for tickers SPX, INX, GSPC, ^GSPC, .INX and none seem to work.  Is there a way to get index data?  Thanks!

**Comment by joshuablackburn-iex** [comment]
We do not have quotes for indices.  The closest we have are the tracking ETFs (SPY, DIA, IWM, etc).  Indices data is not a distributable product, and requires agreements directly with the index data provider.

**Comment by bclous** [comment]
Got it, thanks for your help

**Comment by whitethunder** [comment]
Any chance this will ever be supported, even as a paid option?
