### ISSUE TITLE
IVV Historical Price Errors

### ISSUE THREAD

**Issue by kjacobs686** [iexg/IEX-API#360]
## Summary
Ater pulling 5-year data for IVV, I found the data to be significantly in error.  In some cases the price was more than 10% off the actual historical price.

## Details
See URL's below.

### Date/time of issue
2018-06-03

### API URL
https://iextrading.com/apps/stocks/#/IVV

### What you expected to happen
https://www.google.com/search?client=ubuntu&hs=bcd&channel=fs&ei=9WAUW9KtDY3s5gK7sZeACQ&q=IVV++stock+price&oq=IVV++stock+price&gs_l=psy-ab.3..0i67k1j0l2j0i7i30k1j0i8i30k1.3004.3804.0.4129.4.4.0.0.0.0.97.355.4.4.0....0...1c.1.64.psy-ab..0.4.352....0.RNMOJ2E5-Bk

### What actually happened
https://iextrading.com/apps/stocks/#/IVV

**Comment by evancarter-iex** [comment]
This should be fixed in version 2. More information here: https://github.com/iexg/IEX-API/issues/557

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
