### ISSUE TITLE
How to identify in trades endpoint a sell or a buy trade?

### ISSUE THREAD

**Issue by Code123321** [iexg/IEX-API#363]
## Summary
I have one question regarding to the deep/trades endpoint.

With this endpoint I get the last trades but I don’t know which ordertype(buy or sell) the specific trades are. Can you tell me how I can figure out which type one trade is?

Thanks.

### API URL
https://api.iextrading.com/1.0/deep/trades?symbols=snap (snap is only an example)

**Comment by joshuablackburn-iex** [comment]
Trades represent a buyer and seller.  There is no side in a trade, only on quotes.

**Comment by Code123321** [comment]
Thanks. On which property in the quote I can identify the side?

**Comment by joshuablackburn-iex** [comment]
https://iextrading.com/developer/docs/#quote

The docs for /quote show iexBid and iexAsk data points.
