### ISSUE TITLE
What is meant by 'Subscribe to firehose to return all symbols'?

### ISSUE THREAD

**Issue by connormcglynn** [iexg/IEX-API#365]
Trying to call the API without knowing in advance which stocks will return (for example, all stocks in a particular sector), and I saw that returning all TOPS data might work. The API doc suggest using Firehose, which I'm unfamiliar with. Can someone explain what is meant by 'Subscribe to firehose to return all symbols.'?

Thank you!

**Comment by SeamusBoyle** [comment]
Use `firehose` (the string) as the symbol when subscribing on the WebSocket:

```javascript
const url = 'https://ws-api.iextrading.com/1.0/tops'
const socket = require('socket.io-client')(url)

socket.on('connect', () => {
  socket.emit('subscribe', 'firehose')
})
```

That is what I understand when reading the docs. I haven't tried it since the socket.io server isn't compatible with the socket.io c++ client.

**Comment by joshuablackburn-iex** [comment]
@SeamusBoyle Thanks for responding.  We are aware of the current limitations of our Websocket implementation, and apologize for the inconvenience.  We are working on a replacement that should be available in the next major version.
