### ISSUE TITLE
Bug - stock splits not up-to-date

### ISSUE THREAD

**Issue by janlukasschroeder** [iexg/IEX-API#368]
## Summary

Stock split endpoint is not returning up-to-date data

## Details

Endpoint: https://api.iextrading.com/1.0/stock/ACHV/splits/5y

According to Yahoo Finance a stock split (1/10) occurred on May 24, 2018. However, this stock split is not included in the response of this endpoint.

### Date/time of issue

Today

### API URL

https://api.iextrading.com/1.0/stock/ACHV/splits/5y

### What you expected to happen

See stock split (1/10) on May 24, 2018

### What actually happened

No stock split recorded

### Other Information (sample code, links, etc.)

Yahoo Finance as reference: https://finance.yahoo.com/quote/ACHV/history?period1=1496834338&period2=1528370338&interval=div%7Csplit&filter=split&frequency=1d

**Comment by kartiksubbarao** [comment]
What is the source of the stock split data for the IEX API?

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
