### ISSUE TITLE
Suggestion - add "adjusted close" to charts endpoint

### ISSUE THREAD

**Issue by janlukasschroeder** [iexg/IEX-API#369]
## Summary

Suggestion: add "adjClose" object to charts endpoint. Yahoo Finance provides "adjusted closing" values which are adjusted for stock splits and dividends.

**Comment by joshuablackburn-iex** [comment]
Our close prices for all /chart historical data is adjusted.  Would anyone find it useful to have the unadjusted value?

**Comment by janlukasschroeder** [comment]
@joshuablackburn-iex if the close prices are already adjusted, then there is another bug. 

Endpoint: https://api.iextrading.com/1.0/stock/GEVO/chart/1y 
On date "2018-06-01", "close"=0.2301 - but according to Yahoo Finance the adjusted close price was 4.6. This bug seems to be related to #368

**Comment by asreid2527** [comment]
Unadjusted would be great!  I’m having to go add the dividends back in and would save a lot of time if we had unadjusted open/close/high/low prices when pulling historically.

**Comment by ajs11174** [comment]
@joshuablackburn-iex, I would love to have an unadjusted close price as well. I'm doing some analysis with options data so the adjusted close is more or less meaningless to me. Having the unadjusted close would be awesome.

**Comment by JohnRobson** [comment]
@joshuablackburn-iex  Please, add "unadjusted close price", very important information.

**Comment by helgasoft** [comment]
unadjusted OHLC stock data would be **great**!  Maybe as a (new) separate API call ?

**Comment by JohnRobson** [comment]
I think this is better:
```
"column_names":
["Date","Open","High","Low","Close","Volume","Dividend","Split","Adj_Open","Adj_High","Adj_Low","Adj_Close","Adj_Volume"]
["2018-08-09",207.28,209.78,207.2,208.88,23492626.0,0.0,1.0,206.55343512916548,209.0446720445597,206.47371554787284,208.14782675501777,23492626.0]
```

**Comment by JohnRobson** [comment]
```"column_names":["Date","Open","High","Low","Close","Volume","Dividend","Split","Adj_Open","Adj_High","Adj_Low","Adj_Close","Adj_Volume"]["2018-08-09",207.28,209.78,207.2,208.88,23492626.0,0.0,1.0,206.55343512916548,209.0446720445597,206.47371554787284,208.14782675501777,23492626.0]```

**Comment by evancarter-iex** [comment]
Closing. This is fixed in https://iexcloud.io
