### ISSUE TITLE
Besides quaterly income, is it possible to provide annual income (Last 5 years)?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#37]
For API

https://api.iextrading.com/1.0/stock/googl/earnings

It does provide quarterly income information, which enables us to build something like Google Finance's

![chart](https://user-images.githubusercontent.com/308276/31269306-73f2f8a0-aab2-11e7-8f78-83c6691b7380.png)

I was wondering, is it possible to provide annual income information (last 5 years) as well?

![chart](https://user-images.githubusercontent.com/308276/31269360-a6094cea-aab2-11e7-98d6-578b33777578.png)

Thank you very much

**Comment by joshuablackburn-iex** [comment]
This is something we can add to the roadmap.

**Comment by yccheok** [comment]
Also, current earning API returns 4 quarters. However, the latest quarter is always "future" quarter, not a "past" quarter. Possible to have 4 (or more) "past quarters?

![0](https://user-images.githubusercontent.com/308276/31320257-4680296c-aca4-11e7-82d9-bef6f1e609fe.png)


Thanks.

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex  Besides 5 years data for `earnings` api, will you also provide 5 years data for `financials` call?

As `total revenue, net income, profit margin` are part of `financials` call, not `earnings` api.

Thanks @joshuablackburn-iex

**Comment by pmigueli** [comment]
@joshuablackburn-iex having the annual data would be awesome! Keep going with the extraordinary job IEX is doing! Thanks

**Comment by joshuablackburn-iex** [comment]
Annual financials are available.  Here is an example:
https://api.iextrading.com/1.0/stock/aapl/financials?period=annual

Docs will be updated.
