### ISSUE TITLE
Bug - beta outdated in stats endpoint

### ISSUE THREAD

**Issue by janlukasschroeder** [iexg/IEX-API#370]
## Summary

The value of the "beta" key in the "stats" endpoint is outdated.

## Details

- Call https://api.iextrading.com/1.0/stock/ABIL/stats
- The beta value is "-6.744643". Yahoo Finance shows a beta of 0.32 for the same ticker. See https://finance.yahoo.com/quote/ABIL?p=ABIL

### Date/time of issue

Today

### API URL

https://api.iextrading.com/1.0/stock/ABIL/stats

### What you expected to happen

Beta returned by this endpoint equals beta displayed on Yahoo Finance website.

### What actually happened

Beta differed significantly.

**Comment by bkcollection** [comment]
beta can be different depends on how long it is calculated

**Comment by evancarter-iex** [comment]
Closing. If this is an issue in https://iexcloud.io please create a new issue.
