### ISSUE TITLE
More data points for Earnings and financials 

### ISSUE THREAD

**Issue by bkcollection** [iexg/IEX-API#372]
https://api.iextrading.com/1.0/stock/aapl/earnings
Is that possible to extend from 4 quarters to 12 quarters?

https://api.iextrading.com/1.0/stock/aapl/financials
Is that possible to have **quarters** and **annual** financials. Annual financials  to have 5 years data. Quarters financials to have 5 quarters of data.

Add data points **EBITDA, Net Operating Cashflow, Net investing cashflow, Net financing cashflow and Free Cash flow**

**Comment by joshuablackburn-iex** [comment]
Annual financials are available.  Here is an example:
https://api.iextrading.com/1.0/stock/aapl/financials?period=annual

Docs will be updated.

**Comment by bkcollection** [comment]
Hi Josh,

is it a new API?
Do you have plan to add more data points such as 5 years for annual financials (instead of 4 years) and 12 quarters for quarter financials (instead of 4 quarters).

Will it be something to add more data points for v2?

**Comment by joshuablackburn-iex** [comment]
We are limited to 4 years or 4 quarters with our current provider.  This is something we are planning to address with our next version.

**Comment by bkcollection** [comment]
Thanks Josh,

It will be good if you can expand the financials data to longer period in version 2

**Comment by khanhqnguyen** [comment]
For the earnings, would you provide more than 4 quarters, please?

**Comment by evancarter-iex** [comment]
Closing, this is fixed in IEXCloud. https://iexcloud.io
