### ISSUE TITLE
effective-spread request: volumes dont match avgTotalVolume from quote request

### ISSUE THREAD

**Issue by arbitrage-technology** [iexg/IEX-API#373]
## Summary
for example AEP Stock https://api.iextrading.com/1.0/stock/AEP/quote
avgTotalVolume | 2907178

whereareas

https://api.iextrading.com/1.0/stock/AEP/effective-spread shows

volume | 1653 venue | "XCHI"
volume | 500 venue | "XCIS"
volume | 2197709 venue | "XBOS"
volume | 1495397 venue | "BATY"
volume | 86117 venue | "XASE"
volume | 2169612 venue | "ARCX"
volume | 9689383 venue | "XNYS"
volume | 190844 venue | "XPHL"
volume | 4637268 venue | "BATS"
volume | 714158 venue | "EDGA"
volume | 1994467 venue | "EDGX"
volume | 7187274 venue | "XNGS"
.....

what is wrong? how to reconciliate avgTotalVolume from "quote" request to effective-spread request???
thx
David,

**Comment by joshuablackburn-iex** [comment]
Effective spread data is 15 minutes delayed.
