### ISSUE TITLE
GET A STRING BACK NOT JSON USING SOCKET

### ISSUE THREAD

**Issue by ssoffel** [iexg/IEX-API#376]
## Summary
const socket = io('https://ws-api.iextrading.com/1.0/tops')
 socket.emit('subscribe', 'uaa')

### API URL
'https://ws-api.iextrading.com/1.0/tops'

### What you expected to happen
HOW TO I GET A JSON OBJECT RETURNED?

### What actually happened
'{"symbol":"UAA","sector":"consumerdurablesapparel","securityType":"commonstock","bidPrice":0.0000,"bidSize":0,"askPrice":0.0000,"askSize":0,"lastUpdated":1529006664977,"lastSalePrice":23.4750,"lastSaleSize":100,"lastSaleTime":1529006395919,"volume":130971,"marketPercent":0.02489,"seq":34249}'

### Other Information (sample code, links, etc.)

HOW TO I GET JSON OBJECT RETURNED?

**Comment by joshuablackburn-iex** [comment]
JSON is transmitted as a string over the wire.  You'll need to parse the JSON string to get an object.
