### ISSUE TITLE
1yr charts are missing Fri June 15 2018 data

### ISSUE THREAD

**Issue by martinduo** [iexg/IEX-API#378]
## Summary
This is Sunday June 17, 2018.
I am downloading chart data for several graphs in a charting program. But every download ends with data for June 14th.

## Details
Using this code:
  componentDidMount() {
    const IEX_BASE = 'https://api.iextrading.com/1.0/'
    const symbol = 'qqq' // this.props.cellObject.symbol
    const filter = '?filter=date,open,high,low,close,volume'
    axios
      .get(`${IEX_BASE}stock/${symbol}/chart/1y${filter}`)
      .then((res) => {
        let values = res.data
        let data = values.map((obj) => {
          let date = obj.date
          obj.date = new Date(date)
          return obj
        })
        this.setState({ data })
      })
...
### Date/time of issue
June 17, 2018, 17:00

### What you expected to happen
Price series including Fri June 15

### What actually happened
Last price data was for June 14th

**Comment by joshuablackburn-iex** [comment]
Is anyone else experiencing this issue?  I was not able to reproduce this.

**Comment by martinduo** [comment]
This morning I retried this test. The problem is in my code, not a problem with the API. Sorry for my jumping to a mistaken conclusion and submitting an erroneous complaint. I was inspecting the final data that was returned by the setState({ data }). What I see now is that the .map() operation is returning the resulting array with the last day's price object MISSING! The API's res.data is correct. I'll have to investigate this further.

**Comment by joshuablackburn-iex** [comment]
No problem.  Thanks for following up.

**Comment by martinduo** [comment]
Here's the mistake in my code. 
Change this line:
   let date = obj.date
To this line:
   let date = obj.date + 'T05:00:00.000Z'
Without adding the time, the next statement "obj.date = new Date(date)"  refactors the date to the previous day. I have to use the Date() function to allow the API's response to be used in react-stockcharts for rendering.

**Comment by martinduo** [comment]
I just added another comment to explain the programming fix in case anyone
could use that information, but I see you just closed the thread.
