### ISSUE TITLE
How to get Data of a Specified Year - Such as January to December of 2017

### ISSUE THREAD

**Issue by arpitbatra123** [iexg/IEX-API#379]
## Summary
How to get Data of a Specified Year - Such as January to December of 2017

## Details
How to get Data of a Specified Year - Such as January to December of 2017
as 1y in the endpoint is returning the Last year i.e June 2018 to June 2017
### Date/time of issue

18 June 2018 6:55 PM IST

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/1y

### What you expected to happen
Get data of a specific year - such as all months of 2017

### What actually happened

The endpoint is returning the Last year i.e June 2018 to June 2017

**Comment by timpaine-iex** [comment]
closing as stale, should be possible via `time-series`.
