### ISSUE TITLE
Getting total EPS for last 4 quaters from stats API

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#38]
Currently, I tend to get total EPS for last 4 quarters. As, having EPS for last 4 quarters is more meaningful when doing financial analysis.

From https://api.iextrading.com/1.0/stock/mcd/earnings , I was able to get the following information
> Q3 2017 - null (Because this is not happen yet)
> Q2 2017 - 1.73
> Q1 2017 - 1.47
> Q4 2016 - 1.44

Since, I'm still missing 1 quarter, I tend to get from Nasdaq site

http://www.nasdaq.com/earnings/report/mcd

![nasdaq](https://user-images.githubusercontent.com/308276/31320300-0842fc5a-aca5-11e7-8bdf-54604575e4bc.png)

Hence, my calculated EPS for last 4 quarters is

1.62 + 1.44 + 1.47 + 1.73 = 6.26

However, instead of calculating my own, I prefer to get it directly from https://api.iextrading.com/1.0/stock/mcd/stats . I wish I'm able to get value **6.26** from stats API. But, I couldn't find any value closed to 6.26. The best I can get are

```
latestEPS : 5.43 (May I know how do we get this figure?)
ttmEPS : 4.64 (I believe we get this by calculating the last 3 quarters => 1.44 + 1.47 +  1.73 = 4.64)

```
May I know, is stats API able to provide EPS for last 4 quarters?

For reference, this is the EPS 6.12 displayed in Google Finance. (I'm not sure how do they get that value. But, it is closer than my calculation by taking account into 4 quarters)

![google-finance](https://user-images.githubusercontent.com/308276/31320362-0b866afe-aca6-11e7-9c87-5b50fb120bde.png)

**Comment by shuwnyuantee** [comment]
For `GOOG EPS`, 1 of the quarter (29/6/2017) returns `NULL`. Whereas on Yahoo Finance, it shows valid EPS `5.01`. Any possibility some issue with the data here? 

Sorry to bother again.

<img width="293" alt="iex_edit" src="https://user-images.githubusercontent.com/614382/32086688-8197beac-bb09-11e7-94cc-446799d7f626.png">

<img width="916" alt="yahoo_edit" src="https://user-images.githubusercontent.com/614382/32086694-8874ac3a-bb09-11e7-96b9-ed44d0656341.png">

**Comment by joshuablackburn-iex** [comment]
We have earnings for their GOOGL ticker.  Yahoo may be making manual adjustments to carry over GOOGL attributed earnings to GOOG.  I'll look into whether we want to make those adjustments.

**Comment by shuwnyuantee** [comment]
cool, thanks a lot @joshuablackburn-iex  👍

**Comment by yccheok** [comment]
Today, I tested around 20 stocks and I realize non-null result for 4 quarters. Seems like IEX has fixed my early reported issue.

Thank you @joshuablackburn-iex :)

For the thingy mentioned by @shuwnyuantee , I guess that mostly happens on stocks with multiple classes like 

https://api.iextrading.com/1.0/stock/rds.b/earnings (returns null for most fields)
https://api.iextrading.com/1.0/stock/googl/earnings (returns null for most fields)

However, some multiple classes stock will work fine like

https://api.iextrading.com/1.0/stock/brk.b/earnings (returns 4 quarter actual EPS)
