### ISSUE TITLE
how  to get stock data  from 2017-01-01 to 2017-12-31

### ISSUE THREAD

**Issue by suri281995** [iexg/IEX-API#380]

**Comment by joshuablackburn-iex** [comment]
We currently do not have the ability to query by date or date range.  The best way at this time is to query for a 2 year chart and filter down the dates.

**Comment by irregula-expression** [comment]
@joshuablackburn-iex 
_and do we do it ?_

**Comment by irregula-expression** [comment]
@suri281995 did you find a way out ?

> I'm yet stuck at getting historical data.

**Comment by joshuablackburn-iex** [comment]
https://iextrading.com/developer/docs/#chart

https://api.iextrading.com/1.0/stock/SPY/chart/2y

**Comment by jidhujacob94** [comment]
Hey suri did you got the data?
