### ISSUE TITLE
Add Support for Indian Stocks Symbols

### ISSUE THREAD

**Issue by guptayuvraj** [iexg/IEX-API#381]
## Summary

I am unable to fetch Stock data for the stocks listed in Indian Stock Exchange of NSE/BSE. 

## Details

I wanted to use IEX-API to get stock information for various Indian stocks present in the Indian Stock exchanges. However, upon checking the stock symbols which you support for now, there wasn't any Indian stock listed in there.

### Date/time of issue

19/6/2018 @09:00 EDT

### API URL

https://api.iextrading.com/1.0/ref-data/symbols

### What you expected to happen

I expected the Indian Stock symbols to be present so that I could get relevant price information of those.

### What actually happened

No Indian Stock symbols were present.

**Comment by kprohith** [comment]
When can we expect support for Indian Stock Exchanges(NSE/BSE)?

**Comment by evancarter-iex** [comment]
https://iexcloud.io supports Bombay Stock Exchange.

**Comment by AkshayCloudAnalogy** [comment]
Any update on this?

**Comment by evancarter-iex** [comment]
This is added.

**Comment by amankapur** [comment]
BSE is added. Any plans for NSE ?

**Comment by dushyant-chauhan** [comment]
As on today, NSE data is there in IEX Cloud.

**Comment by Rox3** [comment]
> 

Can u give me list of bse stocks on IEX Cloud
