### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. (stock/quote api only)

### ISSUE THREAD

**Issue by jessysu** [iexg/IEX-API#384]
## Summary

Starting 6/20, the stock/quote api started showing 

No 'Access-Control-Allow-Origin' header is present on the requested resource.

To browser who is browsing other service (and called the API with javascript).

## Details

The other APIs including stock/chart, stock/news are still working when called by the browser with javascript in browser. 

### Date/time of issue

Starting 6/20. Used to work normally.

**Comment by evancarter-iex** [comment]
Sorry about that. I am pushing out a fix for this momentarily.

**Comment by evancarter-iex** [comment]
Should be fixed now.
