### ISSUE TITLE
API stock/{symbol}/quote not returning results when called from javaScript XMLHttpRequest()

### ISSUE THREAD

**Issue by v0rtex2002** [iexg/IEX-API#385]
## Summary
API stock/{symbol}/quote not returning results when called from javaScript XMLHttpRequest()

## Details
When I call it directly with HTTP it returns the expected JSON data, but when called via XMLHttpRequest() in javaScript, the status either stays at or comes back as 0 (rather than 200).  This was working until very recently.

### Date/time of issue
06/20/2018 - Not sure when it started, but I'm fairly certain that it was working yesterday.

### API URL
https://api.iextrading.com/1.0/stock/rgs/quote/

### What you expected to happen
Excpected XMLHttpRequest() to return 200 status and JSON data returned in javasacript

### What actually happened
0 status is returned, no JSON responseText
[was working fine yesterday and for the past several weeks]

**Comment by evancarter-iex** [comment]
@v0rtex2002 please check again. We had a minor issue. It should be fixed now.

**Comment by v0rtex2002** [comment]
Thank you!  it's fixed now.  You rock!!

**Comment by evancarter-iex** [comment]
Glad its working. Sorry that slipped through our testing.
