### ISSUE TITLE
PE ratio from quote API

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#39]
Sorry for opening many issues :)

Currently, from quote API, the PE ttm for MCD stock is 34.4

https://api.iextrading.com/1.0/stock/mcd/quote

![2017-10-09 04_12_42-calculator](https://user-images.githubusercontent.com/308276/31320509-50e5406e-aca8-11e7-9891-7dabc1e4c408.png)

However, if I cross check ychart, google and yahoo finance, most of them provide PE ttm around 26

![ychart](https://user-images.githubusercontent.com/308276/31320528-832cf440-aca8-11e7-97f1-21df874b2ac6.png)

![google](https://user-images.githubusercontent.com/308276/31320529-88a5d98c-aca8-11e7-9f3c-fea53215dc95.png)

![yahoo](https://user-images.githubusercontent.com/308276/31320532-9c1cc796-aca8-11e7-943c-5470364215ab.png)

I believe this has to do with IEX, is using last total 3 quarters EPS during PE calculation - https://github.com/iexg/IEX-API/issues/38

159.60 (MCD last price) / 4.64 (IEX reported EPS) = 34.4

Possible IEX provide PE value, which is calculated based on 4 quarters EPS?

Thanks.

**Comment by yccheok** [comment]
@joshuablackburn-iex Sorry. Not try to be pushy. Just would like to check with you, is there any finding regarding this ticket? Thank you very much.

**Comment by joshuablackburn-iex** [comment]
We have rolled out a fix.  We are running more data validation, but take a look on your end, and let me know if the data looks good.

**Comment by yccheok** [comment]
Appreciate for the fix. Please give me some time to go through it, to see whether most data looks good.

**Comment by yccheok** [comment]
Thank you for the fix. After exam few stocks, the EPS and PE makes much more sense than before. Now, the data seem cover 4 quarters instead of 3 quarters.

However, I realize different sources yield different EPS

```
        Q2 2017, Q1 2017, Q4 2016, Q3 2016
    
IEX     1.32   , 1.04   , 1.24   , ?
GOOGLE  1.32   , 1.04   , 1.43   , 0.82
NASDAQ  1.32   , 1.04   , 1.44   , 0.67
YCHARTS 1.32   , 1.04   , 1.44   , 0.82
```

https://api.iextrading.com/1.0/stock/fb/earnings

https://finance.google.com/finance?q=NASDAQ%3AFB&fstype=ii&ei=tBbnWaD3Np_AuQTwr52QCg

http://www.nasdaq.com/symbol/fb/revenue-eps

https://ycharts.com/companies/FB/eps

**IEX**
![iex](https://user-images.githubusercontent.com/308276/31710435-9bfce9b8-b427-11e7-944a-57ff48dcc6e6.png)

**Google Finance**
![gf](https://user-images.githubusercontent.com/308276/31710446-a6160858-b427-11e7-87ca-84a3104c1d93.png)

**Nasdaq**
![nasdaq](https://user-images.githubusercontent.com/308276/31710464-b2e63bac-b427-11e7-83f4-9c52f3bc3edd.png)

**ycharts**
![ycharts](https://user-images.githubusercontent.com/308276/31710474-bd2a60f2-b427-11e7-985f-98ef04ce2390.png)

Hence, I'm not really sure whether this is a *real* problem which we still need to tackle?
