### ISSUE TITLE
Some Stocks have got a lot of nulls in the financials section..Example : Goldman Sachs

### ISSUE THREAD

**Issue by Abouhend** [iexg/IEX-API#390]
## Summary
Checking the financial section for different stocks. Some companies have weird "nulls" in for some ratios. I know that sometimes that ratio is not applicable to the company but not to the extent of null in gross profit, operating profit and other profit ratios.

Also when I checked these same companies on Yahoo finance, I found that the company is reporting all the missing financials on normal manner.

Example :  
https://api.iextrading.com/1.0/stock/GS/financials

**Comment by evancarter-iex** [comment]
This information has been updated in our documentation for Cloud as to why/how to handle this situation
