### ISSUE TITLE
DEEP websockets: Message type in book channel

### ISSUE THREAD

**Issue by WojciechZankowski** [iexg/IEX-API#392]
## Summary

So according to the documentation: 

> Note: book channel returns messageTypes pricelevelbuy and pricelevelsell.

It suggests that after subscribing to the book channel we will start receiving two types of messages. Perhaps it will be messages for incremental order book. However we receive only book message type with all asks and bids in one response. 

Not sure if it is mistake in documentation or implementation. 

### Date/time of issue

2018-06-22

### API URL

https://ws-api.iextrading.com/1.0/deep

subscription paramter:

```
{
    symbols: ['aapl'],
    channels: ['book'],
}
```

### What you expected to happen

> Note: book channel returns messageTypes pricelevelbuy and pricelevelsell.

### What actually happened

I receive book messageType. It might be just thing to correct in documentation.

**Comment by evancarter-iex** [comment]
IEX Cloud will be using SSE instead of Websockets: https://iexcloud.io
