### ISSUE TITLE
How to get marketPercent or equivalent from TOPS/DEEP pcap files

### ISSUE THREAD

**Issue by onwsk8r** [iexg/IEX-API#393]
## Summary
So I can use the binary messages inside the .pcap.gz files for TOPS and DEEP to get OHLCs for all stocks, and presumably because of the SEC rules for BBO those would be representative (ish, pretty close) of all exchanges, but the `volume` only covers IEX volume and I don't see a way to get either market volume or, in IEX websockets parlance, `marketPercent`. I'm using the data to do technical analysis analysis (that's analyzing technical analyses, sometimes with neural networks), and some of the analyses require volume as an input. Is there a way I can get the total volume? I asked two other people to help me look before I posted here, and I'm not sure if this is the right place to ask - apologies in advance if not.

Also, I really appreciate what you guys do. Prior to finding IEX, I had a source of daily data that is no longer available; the opportunity to analyze minute and hour bars in real time is more than I could have ever asked for.

That being said, I'm writing Node to consume and store and Go to analyze right now (at 1:00 in the morning ftw). It all lives in my private Gitlab, although if any of it could be useful to you I'd be more than happy to open source it - drop me a line if so. My background is in storing and analyzing large data sets.

**Comment by joshuablackburn-iex** [comment]
Those data points are not available on the binary feed.  We keep the binary feeds lean since they are used for trading.  On the JSON web side we supplement the TOPS/DEEP feed with additional information.

**Comment by onwsk8r** [comment]
Makes sense, thanks!
