### ISSUE TITLE
Market-Wide Data for 1 Day Charts

### ISSUE THREAD

**Issue by Lactem** [iexg/IEX-API#394]
## Summary
"1d" and "date" currently provide IEX-only data. I'm wondering if there are any plans to support market-wide data for all charts.

## Details
In [issue 68](https://github.com/iexg/IEX-API/issues/68) Joshua said, "Our next release will supplement that [IEX-only data on 1-day charts] with market wide data." This was 8 months ago, so I'm wondering if that release already happened or if this is still in the works.

### Date/time of issue
N/A

### API URL
https://iextrading.com/developer/docs/#chart

### What you expected to happen
"/stock/aapl/chart/1d" provides data that reflects the whole market.

### What actually happened
"/stock/aapl/chart/1d" provides data that only reflects trades occurring via IEX.

### Other Information (sample code, links, etc.)
N/A

**Comment by SeamusBoyle** [comment]
@Lactem 
Have a look at the doc you linked to, in the response table.

- marketAverage
- marketNotional
- marketNumberOfTrades
- marketOpen
- marketClose
- marketHigh
- marketLow
- marketVolume
- marketChangeOverTime

Lots of spikes for `marketHigh` and `marketLow` that don't end up on the EOD charts. They [the spikes] probably get corrected prior to the creation of the daily values but the minute values don't.
