### ISSUE TITLE
HTTP 429 Error all of the sudden

### ISSUE THREAD

**Issue by aaronarich** [iexg/IEX-API#395]
## Summary
Hi there! I've got a simple static webpage that pulls in ~40 stocks with latest price, change, and symbol. This has been working fine for the past 9 months, but within the past week it has only been loading about 20 stocks consistently (HTTP 200), while the remaining return a HTTP 429 in the console. 

Would anybody be able to share further insight about why these errors are happening all of the sudden? The API Docs state that 100 requests per second should be fine, which I'm making less than that.

Any help on these error responses, or advice on how to make this a bit more efficient would be greatly appreciated.

Thanks,
Aaron

---

## Details
Site: [https://stocks.aaronarich.com/](https://stocks.aaronarich.com/)
Source: [https://github.com/aaronarich/stock-stickler](https://github.com/aaronarich/stock-stickler)

### Date/time of issue
June 22, 2018

![screen shot 2018-06-26 at 6 58 19 am](https://user-images.githubusercontent.com/1185005/41907269-597f9250-790e-11e8-9175-84155f0e776b.png)

**Comment by joshuablackburn-iex** [comment]
We will look into this today.  We were trying to target one abusive user, and it seems our solution was too broad.  Will keep you updated.

**Comment by aaronarich** [comment]
Excellent, thank you so much @joshuablackburn-iex

**Comment by evancarter-iex** [comment]
What is the url you are hitting?

________________________________

**Comment by aaronarich** [comment]
Hi @evancarter-iex - I'm hitting requests from the [/stocks/.../quote](https://iextrading.com/developer/docs/#quote) endpoint... for example `https://api.iextrading.com/1.0/stock/aapl/quote`

I've got 39 of those, each pulling quotes from individual stocks. Thanks!

**Comment by evancarter-iex** [comment]
@aaronarich Can you try using the batch requests like this: https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote that way to you can do multiple stocks per request.
https://iextrading.com/developer/docs/#batch-requests


If that isnt something you can do and you are just looking for price try this: https://api.iextrading.com/1.0/stock/aapl/price

**Comment by aaronarich** [comment]
@evancarter-iex I can definitely give that a shot! Batch would definitely be more ideal... sending it all in one request should help with the "too many requests", yeah? :)

**Comment by evancarter-iex** [comment]
@aaronarich Yup exactly.

**Comment by aaronarich** [comment]
@evancarter-iex awesome, appreciate your insight! I'll try to find some time to work on this soon. Thanks!
