### ISSUE TITLE
BUG: News range limited to 10 in batch requests

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#397]
## Summary

When making a batch request, News only returns up to 10 news items

## Details

Per the docs for News: 

> **range** - Number between 1 and 50. Default is 10. (i.e. .../news/last/1)

``range`` value > 10 works fine for individual requests (/stock/market/news/last/15), but in batch requests only up to 10 news items will be returned at once.

### Date/time of issue

6/26/2018

### API URL

https://api.iextrading.com/1.0/stock/aapl/batch?types=news&last=20

### What you expected to happen

The 20 latest news items in a list

### What actually happened

10 latest news items in a list

### Other Information (sample code, links, etc.)

Seems that ``range`` values 1 < range < 10 work fine.

**Comment by evancarter-iex** [comment]
This is fixed in IEX Cloud. https://iexcloud.io
