### ISSUE TITLE
BUG: Incorrect Key Stats EPS data

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#398]
## Summary

AAPL EPS data in Key Stats returns 0 (see bolded field in response).

### Date/time of issue

6/26/2018

### API URL

https://api.iextrading.com/1.0/stock/aapl/stats

### What you expected to happen

{"companyName":"Apple Inc.","marketcap":895390689460,"beta":1.227215,"week52high":194.2,"week52low":142.28,"week52change":26.4711,"shortInterest":45958599,"shortDate":"2018-05-31","dividendRate":2.92,"dividendYield":1.6028984,"exDividendDate":"2018-05-11 00:00:00.0",**"latestEPS":2.07**,"latestEPSDate":"2017-09-30","sharesOutstanding":4915138000,"float":4905331314,"returnOnEquity":40.86,"consensusEPS":3.82,"numberOfEstimates":9,"EPSSurpriseDollar":null,"EPSSurprisePercent":1.8325,"symbol":"AAPL","EBITDA":61840000000,"revenue":186280000000,"grossProfit":71331000000,"cash":228093000000,"debt":346419000000,"ttmEPS":9.73,"revenuePerShare":38,"revenuePerEmployee":1514472,"peRatioHigh":114.1,"peRatioLow":0,"returnOnAssets":15.19,"returnOnCapital":null,"profitMargin":21.55,"priceToSales":3.673585,"priceToBook":7.43,"day200MovingAvg":170.93132,"day50MovingAvg":182.9,"institutionPercent":54.2,"insiderPercent":null,"shortRatio":1.7009499,"year5ChangePercent":2.5094039388084166,"year2ChangePercent":1.0485088515328673,"year1ChangePercent":0.2687002177760104,"ytdChangePercent":0.06593564129045086,"month6ChangePercent":0.07649706189636507,"month3ChangePercent":0.05847313057503951,"month1ChangePercent":-0.033990879202460626,"day5ChangePercent":-0.018956325057892243,"day30ChangePercent":-0.03178315174063257}

### What actually happened

{"companyName":"Apple Inc.","marketcap":895390689460,"beta":1.227215,"week52high":194.2,"week52low":142.28,"week52change":26.4711,"shortInterest":45958599,"shortDate":"2018-05-31","dividendRate":2.92,"dividendYield":1.6028984,"exDividendDate":"2018-05-11 00:00:00.0",**"latestEPS":0**,"latestEPSDate":"2017-09-30","sharesOutstanding":4915138000,"float":4905331314,"returnOnEquity":40.86,"consensusEPS":3.82,"numberOfEstimates":9,"EPSSurpriseDollar":null,"EPSSurprisePercent":1.8325,"symbol":"AAPL","EBITDA":61840000000,"revenue":186280000000,"grossProfit":71331000000,"cash":228093000000,"debt":346419000000,"ttmEPS":9.73,"revenuePerShare":38,"revenuePerEmployee":1514472,"peRatioHigh":114.1,"peRatioLow":0,"returnOnAssets":15.19,"returnOnCapital":null,"profitMargin":21.55,"priceToSales":3.673585,"priceToBook":7.43,"day200MovingAvg":170.93132,"day50MovingAvg":182.9,"institutionPercent":54.2,"insiderPercent":null,"shortRatio":1.7009499,"year5ChangePercent":2.5094039388084166,"year2ChangePercent":1.0485088515328673,"year1ChangePercent":0.2687002177760104,"ytdChangePercent":0.06593564129045086,"month6ChangePercent":0.07649706189636507,"month3ChangePercent":0.05847313057503951,"month1ChangePercent":-0.033990879202460626,"day5ChangePercent":-0.018956325057892243,"day30ChangePercent":-0.03178315174063257}

### Other Information (sample code, links, etc.)

Working on seeing if there are any additional tickers where this is the case.

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
