### ISSUE TITLE
chart missing 20min day of data 20180626 from 11:23 to 11:43 for all symbols

### ISSUE THREAD

**Issue by mitalpha** [iexg/IEX-API#399]
## Summary
https://api.iextrading.com/1.0/stock/{symbol}/chart/1d

## Details
chart missing 20min day of data 20180626 from 11:23 to 11:43
### API URL
https://api.iextrading.com/1.0/stock/{symbol}/chart/1d

### What you expected to happen
full set of min data

### What actually happened
missed 20 min of data

**Comment by torbjor** [comment]
Seeing same thing. Any chart using `id` is returning 371 objects after close and not the usual 390.

**Comment by joshuablackburn-iex** [comment]
This looks like it was isolated.  Looking into the cause and potential resolution.

**Comment by king3andre** [comment]
Any resolution on this?

Seeing some malformed history response on certain charts. Not sure if this is related to the same ticket. See example response below:

```{
        "date": "20180717",
        "minute": "10:18",
        "label": "10:18 AM",
        "high": -1,
        "low": -1,
        "average": -1,
        "volume": 0,
        "notional": 0,
        "numberOfTrades": 0,
        "marketHigh": -1,
        "marketLow": -1,
        "marketAverage": -1,
        "marketVolume": 0,
        "marketNotional": 0,
        "marketNumberOfTrades": 0,
        "changeOverTime": null,
        "marketChangeOverTime": -1.0052688149381441
    }```
