### ISSUE TITLE
HTTP Error 502: Bad Gateway with Python libraries and manual connection

### ISSUE THREAD

**Issue by payne92** [iexg/IEX-API#4]
I'm getting a 502 bad gateway error when I use the Python `urllib2 `or `urllib`:

```
import urllib2                                                                                 |
req = urllib2.Request("https://api.iextrading.com/1.0/stock/AAPL/quote")                       |
resp = urllib2.urlopen(req)
```
yields:

```
urllib2.HTTPError: HTTP Error 502: Bad Gateway
```

I also get the error if I connect "manually" and send the HTTP headers via:

```
openssl s_client -connect api.iextrading.com:443
```

Interestingly, it works fine in a browser, using the Python `requests` library, or the `wget `command line tool.  It's very strange -- I _suspect_ you have a chunking error in your proxying or code around reading and processing the request bytes.

**Comment by evancarter-iex** [comment]
@payne92 Thanks for the report. I have hunch what this is, Ill look into it.

**Comment by evancarter-iex** [comment]
@payne92 hmm I cant seem to reproduce it on two different systems here. Using python 2.7.13 and 2.7.10.

What version of python are you using?

**Comment by payne92** [comment]
Python 2.7.6 (on ubuntu 14.04 LTS, supported till 2019).   I've got a couple other platforms I can try; I'll look into it this afternoon and post results.  

Were you able to reproduce the problem using openssl from the command line, connecting directly to port 443 and sending the HTTP request?  (I do see that failure on the same ubuntu platform.  Maybe there's too much version skew between the client and your server in the SSL/TLS negotiation somewhere.)

**Comment by evancarter-iex** [comment]
It could be an SNI issue. I believe before 2.7.9 python doesnt support SNI in its modules that are included. If thats not being sent, it could just be sending the default site which I bet would 502.

**Comment by payne92** [comment]
I believe you're right about it being an SNI issue.

More data:  works fine on python 2.7.**13** with urllib2.  

Curiously, on python 2.7.6 (my original report) `urllib2` fails, but the `requests` library works.  `requests` depends on `urllib3` (not a core library), and that works as well.   My guess:   `urllib3` implements working SNI on this pre-2.7.9 version of Python.

I've now got a clear workaround.

But given that Ubuntu LTS is popular and banging around for a few more years, this version of Python will be out there.  I'd suggest at least (a) documenting this in your API docs/eratta and (b) returning a more descriptive error than "502 bad gateway" (if possible).

Thanks!

**Comment by lssilva** [comment]
I am on python 2.7..12 and I also get bad request but after a few successful requests.
is there any throttling in place?
