### ISSUE TITLE
TOP websocket first message all prices 0 (before market open)

### ISSUE THREAD

**Issue by AustinMCrane** [iexg/IEX-API#400]
## Summary
when connecting via websocket (before market open) to `https://api.iextrading.com/1.0/tops?symbols=SNAP,fb,AIG%2b` or any symbols, the prices are like so:

```
[
{
"symbol": "SNAP",
"sector": "softwareservices",
"securityType": "commonstock",
"bidPrice": 0,
"bidSize": 0,
"askPrice": 0,
"askSize": 0,
"lastUpdated": 1530098930812,
"lastSalePrice": 0,
"lastSaleSize": 0,
"lastSaleTime": 0,
"volume": 0,
"marketPercent": 0
},
{
"symbol": "FB",
"sector": "softwareservices",
"securityType": "commonstock",
"bidPrice": 0,
"bidSize": 0,
"askPrice": 0,
"askSize": 0,
"lastUpdated": 1530098930805,
"lastSalePrice": 0,
"lastSaleSize": 0,
"lastSaleTime": 0,
"volume": 0,
"marketPercent": 0
},
{
"symbol": "AIG+",
"sector": "n/a",
"securityType": "warrant",
"bidPrice": 0,
"bidSize": 0,
"askPrice": 0,
"askSize": 0,
"lastUpdated": 1530098930801,
"lastSalePrice": 0,
"lastSaleSize": 0,
"lastSaleTime": 0,
"volume": 0,
"marketPercent": 0
}
]
```
### Date/time of issue
june 27, 6:40 cst

### API URL
`https://api.iextrading.com/1.0/tops`

### Other Information (sample code, links, etc.)
this happens via websocket or a simple get request through browser.

**Comment by joshuablackburn-iex** [comment]
This is expected.  We zero out all of our market data at the start of each trading day.

**Comment by AustinMCrane** [comment]
@joshuablackburn-iex what is the reasoning that this is expected? why would a top for a company ever have zero values beside them going belly up?

**Comment by joshuablackburn-iex** [comment]
TOPS is our exchange market data feed.  On system start we zero out all quotes.  At that point there are not quotes or trades for any symbol, therefore, we show zero for everyone.  Once trading begins data will populate.  TOPS represents IEX only market data as stated in our documentation.  If you are looking for a stock quote, you should look at the /stock REST endpoint.
