### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by joshuablackburn-iex** [iexg/IEX-API#402]
Want to let everyone know we now have basic support for crypto quotes.  This does not require any code changes.  They have been added to our reference data, and you can call the /stock/quote endpoint like any other stock.  Data is currently limited to a rolling 24 hour window for crypto to USDT symbols.  We plan to add support for other endpoints in the future.  Below are the crypto symbols we currently support.

Bitcoin USD (BTCUSDT)
https://api.iextrading.com/1.0/stock/BTCUSDT/quote

EOS USD (EOSUSDT)
https://api.iextrading.com/1.0/stock/EOSUSDT/quote

Ethereum USD (ETHUSDT)
https://api.iextrading.com/1.0/stock/ETHUSDT/quote

Binance Coin USD (BNBUSDT)
https://api.iextrading.com/1.0/stock/BNBUSDT/quote

Ontology USD (ONTUSDT)
https://api.iextrading.com/1.0/stock/ONTUSDT/quote

Bitcoin Cash USD (BCCUSDT)
https://api.iextrading.com/1.0/stock/BCCUSDT/quote

Cardano USD (ADAUSDT)
https://api.iextrading.com/1.0/stock/ADAUSDT/quote

Ripple USD (XRPUSDT)
https://api.iextrading.com/1.0/stock/XRPUSDT/quote

TrueUSD (TUSDUSDT)
https://api.iextrading.com/1.0/stock/TUSDUSDT/quote

TRON USD (TRXUSDT)
https://api.iextrading.com/1.0/stock/TRXUSDT/quote

Litecoin USD (LTCUSDT)
https://api.iextrading.com/1.0/stock/LTCUSDT/quote

Ethereum Classic USD (ETCUSDT)
https://api.iextrading.com/1.0/stock/ETCUSDT/quote

MIOTA USD (IOTAUSDT)
https://api.iextrading.com/1.0/stock/IOTAUSDT/quote

ICON USD (ICXUSDT)
https://api.iextrading.com/1.0/stock/ICXUSDT/quote

NEO USD (NEOUSDT)
https://api.iextrading.com/1.0/stock/NEOUSDT/quote

VeChain USD (VENUSDT)
https://api.iextrading.com/1.0/stock/VENUSDT/quote

Stellar Lumens USD (XLMUSDT)
https://api.iextrading.com/1.0/stock/XLMUSDT/quote

Qtum USD (QTUMUSDT)
https://api.iextrading.com/1.0/stock/QTUMUSDT/quote

**Comment by scottycc** [comment]
USDT is not equal to USD as your labels would suggest. 

USDT is Tether, another cryptocurrency.

**Comment by bishinew** [comment]
Thanks for supporting Cryptos.

We also trade regular currency pair too. Can you please support them, too? Otherwise we have to get Crypto data from IEX and regular currency data from other sources. Very inconvenient.

Thank you very much for consideration.

**Comment by joshuablackburn-iex** [comment]
@bishinew  This is something we are currently working on.

**Comment by Shaping** [comment]
When will IEX deliver BitMEX XBTUSD quotes?   Who is the best source for this data now?

**Comment by SeamusBoyle** [comment]
@Shaping Looks like the current data is from Binance. Did you look at https://www.bitmex.com/app/apiOverview?

**Comment by Shaping** [comment]
Yes, the /quote and /quotebucket APIs are returning 403s.  All the other APIs work.

**Comment by Shaping** [comment]
BitMEX charts its .BXBT index, defined as (GDAX BTC + BTSP BTC)/2.   There used to be 4 averaged components.  Now there are only 2.  I want the actual values as they were displayed historically in BitMEX XBTUSD charts.   You would think this data would be easy to find.

**Comment by SeamusBoyle** [comment]
@Shaping 
.BXBT candles
https://www.bitmex.com/api/udf/history?symbol=.BXBT&resolution=60&from=1532066400&to=1532070000

Maybe they have a different symbol for the old weights. I suggest you ask them, this is not related to IEX anymore.

**Comment by Shaping** [comment]
Yes, I’m able to retrieve 500 candles at a time using the REST API /bucketed endpoint.  They have a 301 problem, with that URL they’ve not acknowledged or fixed yet.  It slows processing in my HTTP client.

**Comment by Shaping** [comment]
Yes, /bucketed is good.   The tick files BM has are good.   Candles could be built from the bids in that stream.  I’m told that is the convention.   Is that correct?

 

I need data going back to the beginning of XBTUSD and I don’t even know when that is, but it seems to be sometime in 2016.

**Comment by Shaping** [comment]
Yes, I’m able to get the 10080 data-point limit.  I will do an SUnit test comparing this data in arrays of opens, highs, lows, and closes, with the individual bars retrieved with /bucketed.  The bars I build from the arrays should match the bars retrieved directly with /bucketed.

**Comment by bartclaeys** [comment]
How is the crypto feed ordered? Right now BTC is followed by EOS, ETH and BNB. This order does seem random and not by market cap. Unfortunately market cap data is lacking from the feed, so it's impossible to order by a meaningful value. I could fall back on volume, but that seems more volatile.

**Comment by Mobiletainment** [comment]
Thank you! Do you also plan on adding news for crypto?
