### ISSUE TITLE
API Version 2

### ISSUE THREAD

**Issue by joshuablackburn-iex** [iexg/IEX-API#403]
All,

While we continue to fix issues and improve version 1 of our API, we have been hard at work on version 2.  We've learned a lot since we launched last year, and we plan to take those lessons and make an even better API.  There are some very exciting developments in version 2, some we cannot disclose at this time, but hopefully we will have more announcements soon.  Thank you to those that have stuck with us and have patiently waited for improvements to the API.  We are committed to making a sustainable and reliable platform that you can depend on.

Some of the focus for v2 that we can disclose now:

- Broader data sets
- More accurate 3rd party data
- Improved WebSocket support
- SSE
- Official SDKs
- Normalizing data structures
- Better API versioning
- More organized documentation
- Improved latency

Things we are interested in and investigating:
- GraphQL
- Binary format in addition to JSON and CSV
- Widgets
- Better support for Excel / Google Sheets

One thing we are changing for version 2 is a requirement to use an API key.  This should help us provide a better experience for all users.

What are your thoughts about the API key requirement?  Will that negatively impact your workflow?

More to follow.  Stay tuned.

**Comment by kapitan-k** [comment]
I’m increasingly using your API and I do not oppose an API key.

About format (I know you did not ask for opinions about it): Personally I’m a big proponent of protocol-buffers (used it in many projects). Clear format, easy versioning, multi language support, high performance. You could simply provide .proto files and everyone could generate the code in the preferred language. = No guessing game about returned structures.

**Comment by flashover** [comment]
Hi Joshua,

I've built a wrapper to query your API so it won't be a problem for me to integrate the API-key.

I'm mostly looking forward to more accurate data, as I've seen some errors with EPS / Dividend information on some (even popular) stocks. Speed of the API won't be an issue for me, as I'm caching entries for a little while before refreshing them. 

Cheers,

**Comment by joshuablackburn-iex** [comment]
@McQgit Thanks for the feedback.  My main goal is to keep the platform simple and easy to use.  You make valid points for each use case of an API key, which is one of the main reasons we currently do not have them.  Going forward, the ambition we have for the platform will require keys to both ensure stability for all users, and to enable personalized services.  We will make sure to consider cases where a developer needs to test an endpoint.  We are also working on solutions for Excel.

**Comment by joshuablackburn-iex** [comment]
@flashover  Data accuracy is very important to us.  I think everyone will be more than pleased with what we are working on.

**Comment by SeamusBoyle** [comment]
@joshuablackburn-iex I'm not opposed to an API key requirement, particularly for personalisation purposes (e.g. Saving a watchlist to IEX servers).

The demo version of an app I have developed is available for users to try before buying. So I would like to see the API permit requests without an API key, otherwise, it is very time-consuming for my apps users just to run the demo. Maybe the API could support non-API key requests limited by requests-per-minute or CPU-time-per-hour  (counted against users IP).

For binary format, I prefer msgpack over protobuf. Switching a client app from JSON to MsgPack is normally a single line of code change. Protobuf requires additional compilation, and code generated from proto files is large. I think msgpack+JSON+CSV would also be easier to maintain server-side compared to proto+JSON+CSV.

I'm currently writing a client SDK for a time series database that uses msgpack, it embeds raw binary data as columns, one column per msgpack field so you read the entire array, not each element.

RE one-minute candles. I like how the one-minute data is returned one day at a time. It makes it super easy to cache and resample. I also like how null bars are included (for when no trades occurred in the minute), these bars are impossible to insert client-side without an accurate calendar. When designing v2/candles please don't change these two things. If v2 can return minute data spanning multiple days please divide them by trading day in the response. The trading day can sometimes span midnight (e.g Forex, Crypto data from Asian exchanges).

RE websocket (non-socket.io). If not using msgpack or protobuff, please consider gzip+json. This could be an option in the query string when connecting. This request is mainly if the new websocket can be used to make requests that return large responses (e.g. candles, batch quotes).

**Comment by WojciechZankowski** [comment]
@joshuablackburn-iex 

> Official SDKs

Looks like I am out of business 😄 Will be sad moment because I engaged a bit already.

But will v1 be still there or you plan to remove it?

**Comment by bkcollection** [comment]
Joshua,

How the api key affected a website that use your API in version 1?
Will there be a limitation of usage for v2 once the API key is implemented? v1 allow developer to use the API freely even for distribution

Does it mean distribution is not allowed in v2 anymore? Please clarify

**Comment by joshuablackburn-iex** [comment]
@bkcollection  We do not have an official release date for V2 yet.  Some things need to get finalized first, then we will announce.  The plan is to keep v1 around for 6 months after the launch of v2.  We also have an approach to handle client side API use through the use of domain specific client keys, but we will put out more detail later.  The API data will remain free to distribute.

**Comment by joshuablackburn-iex** [comment]
@WojciechZankowski  Not necessarily. We could pick an existing library to be officially promoted.

**Comment by joshuablackburn-iex** [comment]
@SeamusBoyle Great feedback.  Thank you.

**Comment by yccheok** [comment]
I hope that old API will stay around longer. As, for a small development team, we may not have adequate resource to perform the migration. Thank you.

**Comment by joshuablackburn-iex** [comment]
@yccheok  Is 6 months not enough time to switch to v2?

**Comment by metbril** [comment]
@bkcollection I don't like my API key in the query string. I prefer in an HTTP header.

**Comment by joshuablackburn-iex** [comment]
We receive a lot of questions about supporting additional data sets.  I thought I'd share some of the data we are investigating and hoping to bring to version 2.  None of these are final, but should give a sense for what we would like to have:

Full day coverage of 15 minute delayed US equities
International stocks
Currencies (FOREX)
Mutual fund data
Options data
Commodities data
Index data
OTC data
Treasuries data
Analyst recommendations, ratings, upgrades/downgrades
Expanded fundamentals

Hopefully some additional interesting alternative data sets.

**Comment by justin-shaw** [comment]
@joshuablackburn-iex 
Any plans to have pre-post market data in the chart endpoints for version 2? Also curious about technical indicators being added in(ema, sma, rsi, psar etc..), are any of those being considered?  New to the IEX API as well, excellent work btw on v1 .. can't wait to see what comes from v2.

**Comment by joshuablackburn-iex** [comment]
@justin-shaw Pre/Post is definitely something that will be available.  Technical indicators are being looked at.  If not at launch, it'll eventually make it in.

**Comment by jjttjj** [comment]
Some sort of machine readable schema such as OpenAPI would be great to have. Does anyone have one for V1? I'm starting to attempt to put one together.

**Comment by bkcollection** [comment]
What is the difference between Full day coverage of 15 minute delayed US
equities
International stocks vs the data in v1 now? Current version is real time.
Any idea?

On Jul 13, 2018 11:09 AM, "Justin Tirrell" <notifications@github.com> wrote:

Some sort of machine readable schema such as OpenAPI would be great to
have. Does anyone have one for V1? I'm starting to attempt to put one
together.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iexg/IEX-API/issues/403#issuecomment-404712625>, or mute
the thread

**Comment by joshuablackburn-iex** [comment]
@jjttjj I agree.  We are looking to support a schema.

**Comment by joshuablackburn-iex** [comment]
@bkcollection Full day coverage for US equities means 4am-8pm ET.  Right now our systems at IEX are only online from 8am-5pm ET, so we only publish prices during those hours.

**Comment by bkcollection** [comment]
josh,

Is there any plan for full day real time quote instead of 15 minutes delay?

**Comment by joshuablackburn-iex** [comment]
@bkcollection IEX will continue to provide real time pricing from 8-5pm.  For 4am-8am and 5pm-8pm, we have to stick to delayed for now.  Very few places display real time pricing after regular market hours due to very thin trading.  Real time pricing can also get very expensive not only for us to distribute, but for you the user if you need to do anything with the data.  We are looking into as many options as possible while trying to keep the cost and legal paperwork to a minimum for our users.

**Comment by lovettchris** [comment]
API key is fine by me, pretty standard these days.  Just put it in the HTTP header though so it is encrypted with https payload.  I look forward to your v2, especially mutual fund data.  I'd be happy to be a guinea pig if you need one :-) Cheers!

**Comment by jjttjj** [comment]
Would you consider streamlining the `date` field on `/chart/` responses? 

For example, `date` only refers to a day, and when intraday data is requested a separate `minute` field is given.  A single date string should be able to precisely encompass both of these in a [standardized](https://en.wikipedia.org/wiki/ISO_8601) way. I'm struggling to think of a real world situation where I client would use one of these without the other and without some sort of parsing of at least one of the strings into some sort of date type, so why not allow it to be done in a single parse call rather then putting the burden on the client to combine two fields and parse them?

**Comment by bwong** [comment]
Will there be support for the annual financials in addition to the last four quarters?

**Comment by sasoftwarerl** [comment]
Is there an estimated release date for API Version 2.0?

**Comment by calvinballhero** [comment]
Very much looking forward to this next release, mostly the expanded data sets. Happy to beta test if needed.

**Comment by joshuablackburn-iex** [comment]
@sasoftwarerl  Targeting early Q4

**Comment by JoeSalmeri** [comment]
Is API Version 2.0 backward compatible with V 1.0?

Meaning I can just change the URL from /1.0 to /2.0 and expect existing code to work or will additional changes be required?

Is a preview of the 2.0 API docs available?

**Comment by joshuablackburn-iex** [comment]
@JoeSalmeri  Version 2 will include some breaking changes.  I wouldn't count on it being as simple as changing the version.  There are still a number of things that need to be finalized.  We will try to release a doc preview as soon as we can.

**Comment by JoeSalmeri** [comment]
Thanks Joshua, I will be on the lookout for the doc preview.

**Comment by sasoftwarerl** [comment]
@joshuablackburn-iex 
Sounds good Joshua, good luck, I'll be on the lookout for V2.0

**Comment by roblav96** [comment]
Dear @joshuablackburn-iex,

Preface:
The ~5,000 yearly github contributions were from commits to an automated trading platform for Robinhood which **heavily** used the IEX API. [robinhood.tools](https://robinhood.tools/) (currently mid-refactor) 🤒

----

I started using the IEX API in March of last year and immediately fell in love with the _simplicity_, please don't complicate things with a free API key. I'm sure as you know, socket.io is terribly inefficient/sloppy and needs to be replaced with the standard WebSocket protocol. I _highly_ recommend [uWebSockets](https://github.com/uNetworking/uWebSockets#excel-across-the-board) `npm install uws@10.148.1`. Currently the project is being refactored to use a rewritten `C` library with [uWebSockets-node](https://github.com/uNetworking/uWebSockets-node) on the way. You can scale uWebSockets to infinity with [ClusterWS](https://github.com/ClusterWS/ClusterWS).

And that's it! I can't think of anything else to criticize.
=]

Seriously though, huge props and thanks for doing such an incredibly good job on this API project! Everything from batch requests, to lightening fast responses, working with this API has been the most seamless experience in my entire career.

Please don't hesitate to ask for help with anything! I would be more than happy to submit some PRs if needed. Thanks again! :D

**Comment by joshuablackburn-iex** [comment]
@roblav96  Thank you for your feedback.  I agree with you on socket.io.  I'm not a fan either, and I've been looking at uWS for a while.  The plan is to integrate uWS.  socket.io was a way to quickly offer Websocket support at the time.  We've also been running SSE in beta for a while, and it will roll out with version 2.

I appreciate the comments regarding the simplicity of the API.  We aim to make this as simple to use as possible.  In order to deliver the pipeline of services we've been working on, and upgrade our data to the highest quality possible, we have to introduce API keys.  Our goal is to keep this as easy to use as possible.

**Comment by bartclaeys** [comment]
I have been using GraphQL to access Github API and it has been an extremely frustrating experience. I am totally against GraphQL, it overcomplicated a lot of things, and it's yet another weird 'language' to learn. I know it's all the hype, but if you look at the support forums of Github you'll quickly realize GraphQL is very hard to understand, plus implementation of GraphQL by Github is poor and lacking in comparison to their old style API.

**Comment by joshuablackburn-iex** [comment]
@bartclaeys Great feedback.  I think between our batch calls and filter parameters we are able to offer a great deal of flexibility, and may not need to offer something like GraphQL at this time.  I'd rather spend that time elsewhere than add complexity.

**Comment by appagg** [comment]
Looking forward to the fund or ETF data supports in v2.0.

**Comment by timkpaine** [comment]
@joshuablackburn-iex any chance for early access? Doing the socket-io api from python was particularly annoying, I don't want to be caught out.

**Comment by chris831** [comment]
Also wondering if you have a pre-release available; or perhaps a revised expectation on release.

And, any revised dovs on the v1.6 TOPS file?

**Comment by chris831** [comment]
Has this initiative been abandoned?

**Comment by joshuablackburn-iex** [comment]
It is still on track.  The plan is a Q4 release.  We are finalizing contracts with partners.

**Comment by chris831** [comment]
Great! 

Any revised docs on the v1.6 TOPS file?

**Comment by chris831** [comment]
Is there a more appropriate venue to address differences in the TOPS spec and the actual TOPS files?

**Comment by yccheok** [comment]
> @yccheok Is 6 months not enough time to switch to v2?

@joshuablackburn-iex Sorry, I away for other tasks. Yes, 6 months is reasonable. But, should we start migrating now, as I just go through IEX documentation just now. It seems v1 is still being used. Currently, we're already happy with v1, for fundamental data retrieval.

We also using websocket - https://iextrading.com/developer/docs/#websockets . Will v1 -> v2 migration affect that too?

Thank you.

**Comment by xufab** [comment]
Will `/stock/{symbol}/logo` be incorporated in `/stock/{symbol}/company` in v2?

**Comment by chris831** [comment]
guess not

**Comment by joshuablackburn-iex** [comment]
@xufab The logo endpoint will change with the intent of returning base64 encoded image.  We can also return the url in the company endpoint.

**Comment by chris831** [comment]
Is there an updated document for the current TOPS file format?
Is there a more appropriate venue to address differences in the TOPS spec and the actual TOPS files?

**Comment by WojciechZankowski** [comment]
> 
> 
> Is there an updated document for the current TOPS file format?
> Is there a more appropriate venue to address differences in the TOPS spec and the actual TOPS files?

This is what you want? https://iextrading.com/trading/market-data/#specifications

**Comment by chris831** [comment]
I have followed the format in the TOPS spec from this link and it would appear to be out of date...looking for a current specification of file and message structures.  Trial and error lead me to pcap-ng format rather than pcap...but still the message formats are not consistent in size or organization to the descriptions provided...

Am I missing something?  Is there an updated doc for the file structure?

**Comment by WojciechZankowski** [comment]
> 
> 
> I have followed the format in the TOPS spec from this link and it would appear to be out of date...looking for a current specification of file and message structures. Trial and error lead me to pcap-ng format rather than pcap...but still the message formats are not consistent in size or organization to the descriptions provided...
> 
> Am I missing something? Is there an updated doc for the file structure?

I run TOPS file from yesterday and it seems to be working. I have library updated to the newest specification from the link I gave previously. There must be something wrong in your implementation. Indeed messages are not constant in size. 

You can check my implementation for further details:  https://github.com/WojciechZankowski/iextrading4j-hist  Start with TOPSSample class and go deeper.

**Comment by myichimoku** [comment]
@joshuablackburn-iex Thanks for all the great data and simplicity thus far. I have started to use your API for a personal project recently. A key is fine, but would access to data remain free ?

**Comment by aokellermann** [comment]
@joshuablackburn-iex Is there any chance of getting an early set of endpoint documentation before it is released? Additionally, an api key would be a very small price to pay for free and accurate data.

**Comment by chris831** [comment]
> 
> 
> > I have followed the format in the TOPS spec from this link and it would appear to be out of date...looking for a current specification of file and message structures. Trial and error lead me to pcap-ng format rather than pcap...but still the message formats are not consistent in size or organization to the descriptions provided...
> > Am I missing something? Is there an updated doc for the file structure?
> 
> I run TOPS file from yesterday and it seems to be working. I have library updated to the newest specification from the link I gave previously. There must be something wrong in your implementation. Indeed messages are not constant in size.
> 
> You can check my implementation for further details: https://github.com/WojciechZankowski/iextrading4j-hist Start with TOPSSample class and go deeper.

Thanks, taking a look today...

**Comment by rajivkbhatia** [comment]
Thanks for all the great data so far

I have a few questions
-Will the api limits be the same? Will they be determined by IP address or key? 

Thanks

**Comment by chris831** [comment]
> 
> 
> > I have followed the format in the TOPS spec from this link and it would appear to be out of date...looking for a current specification of file and message structures. Trial and error lead me to pcap-ng format rather than pcap...but still the message formats are not consistent in size or organization to the descriptions provided...
> > Am I missing something? Is there an updated doc for the file structure?
> 
> I run TOPS file from yesterday and it seems to be working. I have library updated to the newest specification from the link I gave previously. There must be something wrong in your implementation. Indeed messages are not constant in size.
> 
> You can check my implementation for further details: https://github.com/WojciechZankowski/iextrading4j-hist Start with TOPSSample class and go deeper.

Turns out the issue was with the PcapReader I was using; created one myself and everything fell in line...also needed to install npcap rather than libpcap to get the project you referenced working...

Hope this saves someone some time...

**Comment by chris831** [comment]
Any more info on an early 2018Q4 release?  any docs yet?

**Comment by jjttjj** [comment]
Are there any further developments regarding some sort of machine readable schema for the api?  JSON Schema or protocol buffers?
