### ISSUE TITLE
Is there any way to get only real time Quote not delayed quote on Quote end point?

### ISSUE THREAD

**Issue by shashank2490** [iexg/IEX-API#405]
## Summary
Is there any way to get only real time Stock Quote when using **Quote** end point?
Right now it gives real time and 15 min delayed quote randomly.

**Comment by joshuablackburn-iex** [comment]
Can you provide more detail about what you're seeing?  What do you mean by randomly?  Real time prices are the result of trades on IEX only.  15 min delayed quote is the last trade across the entire market.  It's worth noting that not every stock trades every second, so you may not observe an update continuously.

**Comment by aprsa** [comment]
To clarify, does this mean that there is no real-time access to the market quote (as opposed to the real-time IEX quote) through the IEX API?

**Comment by joshuablackburn-iex** [comment]
That is correct.  We control our own data and have chosen to make it free.  Quotes from the rest of the market have a much higher cost, and are much more restrictive in terms of use.  We may look into a way to offer this in a newer version of the API, but the other exchanges have additional costs.

**Comment by JohnRobson** [comment]
@shashank2490  In quote, you have "iexLastUpdated, delayedPriceTime, extendedPriceTime", just check who has the bigger value (more recent time) and use that price, very simple.

**Comment by austinyearlykim** [comment]
@JohnRobson @joshuablackburn-iex  is this what the endpoint:

/stock/aapl/price

returns?  It prioritizes which has the latest price-update-time for you? 

The documentation says...
FROM: /stock/aapl/price
"A single number, being the IEX real time price, the 15 minute delayed market price, or the previous close price, is returned."

It never clearly defines what determines which one you get back, nor does it say anything about picking one~

**Comment by evancarter-iex** [comment]
This can be done in https://iexcloud.io using the field paramater https://iexcloud.io/docs/api/#quote
