### ISSUE TITLE
Question: Any plans to return popular indicators and oscillator like RSI, Momentum, etc?

### ISSUE THREAD

**Issue by anthonybusto** [iexg/IEX-API#406]
## Summary

I'm just curious if you guys are planning to return indicators such as the Relative Strength Index, Momentum, etc? 

/stock/market/batch?symbols=aapl,fb,tsla&types=quote,news,chart&range=1m&last=5

Maybe adding another node to this response above so we can have the chart, at the given time intervals and then have the corresponding indicators at those times as well? So we can see that, for example, on 06-29-2018 the price of a stock was $50.85 and at that time the RSI was 72 and the momentum is 102. This is just a random example using random numbers but this would be a great tool. When I trade, I like to look for 3 things, the price and then what the RSI and Momentum was during that time. If price is going down, but the momentum is going up, then that is referred to as a divergence and is an early tell to possibly buy this stock. I then use the RSI as a final confirmation, so if we have a divergence and the RSI is below 30 (meaning oversold) then this is a great time to buy with a high probability that the stock is going to turn around. If your API could return all this data in one neat JSONObject, that would be a great, awesome and very powerful tool to us.

Just an idea, but I think many traders would find this extremely useful and the the IEX API would be a great place to go and pull in that data.

Hope that you guys may consider this.

Thank you,

-AB

**Comment by evancarter-iex** [comment]
This is available via https://iexcloud.io/docs/api/#technical-indicators
