### ISSUE TITLE
1D Date Chart only gives information from 9:30am to 12:59pm

### ISSUE THREAD

**Issue by a13xk13m** [iexg/IEX-API#408]
## Summary
Whenever I retrieve 1d chart data for any weekday, it only provides me with data from 9:30am to 12:59pm.

## Details
This has happened for every stock that I've tested this on. This also occurs with 1d chart data of the current day.
### Date/time of issue
7/3/2018

### API URL
https://api.iextrading.com/1.0/stock/GS/chart/date/20180702

**Comment by joshuablackburn-iex** [comment]
July 3rd was a half day for US markets.  All exchanges stopped trading at 1pm ET.  What you saw is expected.
