### ISSUE TITLE
`batch?symbols=` API endpoint does not return any values in `chart` dict.

### ISSUE THREAD

**Issue by cgi1** [iexg/IEX-API#409]
## Summary

The `batch?symbols=` API endpoint does not return any values in `chart` dict.

### Date/time of issue

Time of issue creation

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=WMB,WMGI,WMT,WP,WOW,WOR,WPM,WPX,WPZ,WRB,WRD,WRK,WRI,WSM,WTW,WU,WUBA,WTR,WTTR&types=quote,chart&range=1d&last=5

### What you expected to happen

The last chart data gets returned

### What actually happened

All chart arrays are empty

### Other Information (sample code, links, etc.)

_(Search for `"chart":`)_

`{"WMB":{"quote":{"symbol":"WMB","companyName":"Williams Companies Inc. (The)","primaryExchange":"New York Stock Exchange","sector":"Energy","calculationPrice":"close","open":26.92,"openTime":1530624600904,"close":27.04,"closeTime":1530637336677,"high":27.28,"low":26.9,"latestPrice":27.04,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637336677,"latestVolume":2964740,"iexRealtimePrice":27.02,"iexRealtimeSize":100,"iexLastUpdated":1530637183209,"delayedPrice":27.04,"delayedPriceTime":1530637336677,"extendedPrice":27.04,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530638429728,"previousClose":26.7,"change":0.34,"changePercent":0.01273,"iexMarketPercent":0.04359,"iexVolume":129233,"avgTotalVolume":8327694,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":22380569952,"peRatio":40.36,"week52High":33.67,"week52Low":24,"ytdChange":-0.09648357790428001},"chart":[]},"WMGI":{"quote":{"symbol":"WMGI","companyName":"Wright Medical Group N.V.","primaryExchange":"Nasdaq Global Select","sector":"Healthcare","calculationPrice":"close","open":25.87,"openTime":1530624600514,"close":25.7,"closeTime":1530637200229,"high":26.06,"low":25.44,"latestPrice":25.7,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637200229,"latestVolume":824686,"iexRealtimePrice":25.7,"iexRealtimeSize":57,"iexLastUpdated":1530637185405,"delayedPrice":25.7,"delayedPriceTime":1530637200229,"extendedPrice":25.7,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530639382312,"previousClose":25.85,"change":-0.15,"changePercent":-0.0058,"iexMarketPercent":0.04217,"iexVolume":34777,"avgTotalVolume":1292473,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":2723424040,"peRatio":-183.57,"week52High":29.89,"week52Low":19.01,"ytdChange":0.11598088171104318},"chart":[]},"WMT":{"quote":{"symbol":"WMT","companyName":"Walmart Inc.","primaryExchange":"New York Stock Exchange","sector":"Consumer Defensive","calculationPrice":"close","open":84.09,"openTime":1530624600818,"close":84.44,"closeTime":1530637341336,"high":85.05,"low":84.09,"latestPrice":84.44,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637341336,"latestVolume":4351391,"iexRealtimePrice":84.42,"iexRealtimeSize":63,"iexLastUpdated":1530637195750,"delayedPrice":84.44,"delayedPriceTime":1530637341336,"extendedPrice":84.44,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530640745621,"previousClose":84,"change":0.44,"changePercent":0.00524,"iexMarketPercent":0.023,"iexVolume":100082,"avgTotalVolume":8860823,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":249169300545,"peRatio":19.37,"week52High":109.98,"week52Low":73.13,"ytdChange":-0.12774833579760145},"chart":[]},"WP":{"quote":{"symbol":"WP","companyName":"Worldpay Inc. Class A","primaryExchange":"New York Stock Exchange","sector":"Industrials","calculationPrice":"close","open":82.5,"openTime":1530624600855,"close":82.26,"closeTime":1530637320780,"high":82.68,"low":81.91,"latestPrice":82.26,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637320780,"latestVolume":1149691,"iexRealtimePrice":82.275,"iexRealtimeSize":1,"iexLastUpdated":1530637193187,"delayedPrice":82.26,"delayedPriceTime":1530637320780,"extendedPrice":82.26,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530640494607,"previousClose":82.06,"change":0.2,"changePercent":0.00244,"iexMarketPercent":0.07919,"iexVolume":91044,"avgTotalVolume":2035394,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":25719438993,"peRatio":49.55,"week52High":86.06,"week52Low":59.1,"ytdChange":0.1196476599212279},"chart":[]},"WOW":{"quote":{"symbol":"WOW","companyName":"WideOpenWest Inc.","primaryExchange":"New York Stock Exchange","sector":"Communication Services","calculationPrice":"close","open":9.88,"openTime":1530624600912,"close":10.3,"closeTime":1530637322877,"high":10.38,"low":9.88,"latestPrice":10.3,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637322877,"latestVolume":392370,"iexRealtimePrice":10.32,"iexRealtimeSize":100,"iexLastUpdated":1530637175912,"delayedPrice":10.3,"delayedPriceTime":1530637322877,"extendedPrice":10.3,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530639430842,"previousClose":9.82,"change":0.48,"changePercent":0.04888,"iexMarketPercent":0.02228,"iexVolume":8742,"avgTotalVolume":524830,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":878406557,"peRatio":1030,"week52High":17.68,"week52Low":6.025,"ytdChange":0.018748173258003903},"chart":[]},"WOR":{"quote":{"symbol":"WOR","companyName":"Worthington Industries Inc.","primaryExchange":"New York Stock Exchange","sector":"Basic Materials","calculationPrice":"close","open":42.95,"openTime":1530624600904,"close":43.04,"closeTime":1530637321382,"high":43.68,"low":42.85,"latestPrice":43.04,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637321382,"latestVolume":353582,"iexRealtimePrice":42.97,"iexRealtimeSize":100,"iexLastUpdated":1530637150565,"delayedPrice":43.04,"delayedPriceTime":1530637321382,"extendedPrice":43.04,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530639382318,"previousClose":42.85,"change":0.19,"changePercent":0.00443,"iexMarketPercent":0.01689,"iexVolume":5972,"avgTotalVolume":308845,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":2534066080,"peRatio":15.37,"week52High":53.27,"week52Low":39.52,"ytdChange":-0.042767378907287656},"chart":[]},"WPM":{"quote":{"symbol":"WPM","companyName":"Wheaton Precious Metals Corp (Canada)","primaryExchange":"New York Stock Exchange","sector":"Basic Materials","calculationPrice":"close","open":22.11,"openTime":1530624600858,"close":22.46,"closeTime":1530637251662,"high":22.66,"low":22.11,"latestPrice":22.46,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637251662,"latestVolume":1480964,"iexRealtimePrice":22.44,"iexRealtimeSize":100,"iexLastUpdated":1530637155752,"delayedPrice":22.46,"delayedPriceTime":1530637251662,"extendedPrice":22.46,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530639081000,"previousClose":21.93,"change":0.53,"changePercent":0.02417,"iexMarketPercent":0.02406,"iexVolume":35632,"avgTotalVolume":1443945,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":9953528035,"peRatio":34.55,"week52High":22.72,"week52Low":18.32,"ytdChange":0.0399677811647754},"chart":[]},"WPX":{"quote":{"symbol":"WPX","companyName":"WPX Energy Inc.","primaryExchange":"New York Stock Exchange","sector":"Energy","calculationPrice":"close","open":18.4,"openTime":1530624600856,"close":18.49,"closeTime":1530637218231,"high":18.82,"low":18.28,"latestPrice":18.49,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637218231,"latestVolume":4616533,"iexRealtimePrice":18.46,"iexRealtimeSize":100,"iexLastUpdated":1530637172013,"delayedPrice":18.49,"delayedPriceTime":1530637218231,"extendedPrice":18.49,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530640493655,"previousClose":17.93,"change":0.56,"changePercent":0.03123,"iexMarketPercent":0.01621,"iexVolume":74834,"avgTotalVolume":7397618,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":7389071131,"peRatio":-57.78,"week52High":19.23,"week52Low":8.87,"ytdChange":0.3233334241788957},"chart":[]},"WPZ":{"quote":{"symbol":"WPZ","companyName":"Williams Partners L.P. Representing Limited Partner Interests","primaryExchange":"New York Stock Exchange","sector":"Energy","calculationPrice":"close","open":40.28,"openTime":1530624600906,"close":40.5,"closeTime":1530637323593,"high":40.91,"low":40.28,"latestPrice":40.5,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637323593,"latestVolume":767600,"iexRealtimePrice":40.55,"iexRealtimeSize":100,"iexLastUpdated":1530637197980,"delayedPrice":40.5,"delayedPriceTime":1530637323593,"extendedPrice":40.5,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530638429591,"previousClose":40.1,"change":0.4,"changePercent":0.00998,"iexMarketPercent":0.02071,"iexVolume":15897,"avgTotalVolume":1500165,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":39553347816,"peRatio":29.78,"week52High":44.06,"week52Low":32.74,"ytdChange":0.06488452462876479},"chart":[]},"WRB":{"quote":{"symbol":"WRB","companyName":"W.R. Berkley Corporation","primaryExchange":"New York Stock Exchange","sector":"Financial Services","calculationPrice":"close","open":72.08,"openTime":1530624600952,"close":72.17,"closeTime":1530637324705,"high":73.07,"low":72.04,"latestPrice":72.17,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637324705,"latestVolume":312761,"iexRealtimePrice":72.07,"iexRealtimeSize":100,"iexLastUpdated":1530637170166,"delayedPrice":72.17,"delayedPriceTime":1530637324705,"extendedPrice":72.17,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530637354667,"previousClose":71.89,"change":0.28,"changePercent":0.00389,"iexMarketPercent":0.02876,"iexVolume":8995,"avgTotalVolume":390054,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":8780858803,"peRatio":26.05,"week52High":79.74,"week52Low":62,"ytdChange":0.04497514048230072},"chart":[]},"WRD":{"quote":{"symbol":"WRD","companyName":"WildHorse Resource Development Corporation","primaryExchange":"New York Stock Exchange","sector":"Energy","calculationPrice":"close","open":24.87,"openTime":1530624637519,"close":24.49,"closeTime":1530637323595,"high":25,"low":24.01,"latestPrice":24.49,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637323595,"latestVolume":930856,"iexRealtimePrice":24.5,"iexRealtimeSize":100,"iexLastUpdated":1530637192050,"delayedPrice":24.49,"delayedPriceTime":1530637323595,"extendedPrice":24.49,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530639430845,"previousClose":24.3,"change":0.19,"changePercent":0.00782,"iexMarketPercent":0.00713,"iexVolume":6637,"avgTotalVolume":1760534,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":2480295183,"peRatio":28.48,"week52High":29.67,"week52Low":10.36,"ytdChange":0.3359111062906723},"chart":[]},"WRK":{"quote":{"symbol":"WRK","companyName":"Westrock Company","primaryExchange":"New York Stock Exchange","sector":"Consumer Cyclical","calculationPrice":"close","open":57.19,"openTime":1530624600927,"close":56.59,"closeTime":1530637335818,"high":57.42,"low":56.49,"latestPrice":56.59,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637335818,"latestVolume":1025651,"iexRealtimePrice":56.59,"iexRealtimeSize":13,"iexLastUpdated":1530637195090,"delayedPrice":56.59,"delayedPriceTime":1530637335818,"extendedPrice":57.001,"extendedChange":0.411,"extendedChangePercent":0.00726,"extendedPriceTime":1530637863238,"previousClose":56.93,"change":-0.34,"changePercent":-0.00597,"iexMarketPercent":0.01306,"iexVolume":13395,"avgTotalVolume":1642844,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":14512611663,"peRatio":17.1,"week52High":71.55,"week52Low":54.05,"ytdChange":-0.11905308243986},"chart":[]},"WRI":{"quote":{"symbol":"WRI","companyName":"Weingarten Realty Investors","primaryExchange":"New York Stock Exchange","sector":"Real Estate","calculationPrice":"close","open":30.55,"openTime":1530624600906,"close":30.74,"closeTime":1530637321383,"high":30.945,"low":30.22,"latestPrice":30.74,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637321383,"latestVolume":555093,"iexRealtimePrice":30.76,"iexRealtimeSize":100,"iexLastUpdated":1530637184449,"delayedPrice":30.74,"delayedPriceTime":1530637321383,"extendedPrice":30.74,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530639483713,"previousClose":30.35,"change":0.39,"changePercent":0.01285,"iexMarketPercent":0.03073,"iexVolume":17058,"avgTotalVolume":682100,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":3939300998,"peRatio":12.81,"week52High":33.83,"week52Low":25.67,"ytdChange":-0.023033089063200833},"chart":[]},"WSM":{"quote":{"symbol":"WSM","companyName":"Williams-Sonoma Inc. (DE)","primaryExchange":"New York Stock Exchange","sector":"Consumer Cyclical","calculationPrice":"close","open":61.34,"openTime":1530624600955,"close":61.48,"closeTime":1530637324706,"high":62.27,"low":61.03,"latestPrice":61.48,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637324706,"latestVolume":800667,"iexRealtimePrice":61.51,"iexRealtimeSize":50,"iexLastUpdated":1530637196004,"delayedPrice":61.48,"delayedPriceTime":1530637324706,"extendedPrice":61.57,"extendedChange":0.09,"extendedChangePercent":0.00146,"extendedPriceTime":1530637863238,"previousClose":60.99,"change":0.49,"changePercent":0.00803,"iexMarketPercent":0.04944,"iexVolume":39585,"avgTotalVolume":2710913,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":5109271607,"peRatio":17.77,"week52High":65.99,"week52Low":42.68,"ytdChange":0.19331915040139425},"chart":[]},"WTW":{"quote":{"symbol":"WTW","companyName":"Weight Watchers International Inc","primaryExchange":"New York Stock Exchange","sector":"Consumer Cyclical","calculationPrice":"close","open":101.15,"openTime":1530624600815,"close":101.09,"closeTime":1530637322028,"high":102.52,"low":100.58,"latestPrice":101.09,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637322028,"latestVolume":373388,"iexRealtimePrice":101.14,"iexRealtimeSize":100,"iexLastUpdated":1530637032070,"delayedPrice":101.09,"delayedPriceTime":1530637322028,"extendedPrice":101.09,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530639382783,"previousClose":100.99,"change":0.1,"changePercent":0.00099,"iexMarketPercent":0.0121,"iexVolume":4518,"avgTotalVolume":1434471,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":6700470530,"peRatio":50.55,"week52High":105.7265,"week52Low":32.16,"ytdChange":1.1145170750574955},"chart":[]},"WU":{"quote":{"symbol":"WU","companyName":"Western Union Company (The)","primaryExchange":"New York Stock Exchange","sector":"Financial Services","calculationPrice":"close","open":20.5,"openTime":1530624600802,"close":20.11,"closeTime":1530637471027,"high":20.53,"low":20.09,"latestPrice":20.11,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637471027,"latestVolume":2139124,"iexRealtimePrice":20.105,"iexRealtimeSize":100,"iexLastUpdated":1530637198045,"delayedPrice":20.11,"delayedPriceTime":1530637471027,"extendedPrice":20.231,"extendedChange":0.121,"extendedChangePercent":0.00602,"extendedPriceTime":1530637863238,"previousClose":20.44,"change":-0.33,"changePercent":-0.01614,"iexMarketPercent":0.04294,"iexVolume":91854,"avgTotalVolume":4469599,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":9265231976,"peRatio":10.64,"week52High":22.21,"week52Low":18.38,"ytdChange":0.057527125818197314},"chart":[]},"WUBA":{"quote":{"symbol":"WUBA","companyName":"58.com Inc. American Depositary Shares each representing 2 Class A","primaryExchange":"New York Stock Exchange","sector":"Technology","calculationPrice":"close","open":70.48,"openTime":1530624600825,"close":66.73,"closeTime":1530637322031,"high":70.48,"low":66.6,"latestPrice":66.73,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637322031,"latestVolume":1250807,"iexRealtimePrice":66.8,"iexRealtimeSize":13,"iexLastUpdated":1530637197409,"delayedPrice":66.73,"delayedPriceTime":1530637322031,"extendedPrice":67.605,"extendedChange":0.875,"extendedChangePercent":0.01311,"extendedPriceTime":1530638026075,"previousClose":69.72,"change":-2.99,"changePercent":-0.04289,"iexMarketPercent":0.03718,"iexVolume":46505,"avgTotalVolume":1304222,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":9834104599,"peRatio":43.9,"week52High":89.9,"week52Low":42.92,"ytdChange":-0.16785721741410964},"chart":[]},"WTR":{"quote":{"symbol":"WTR","companyName":"Aqua America Inc.","primaryExchange":"New York Stock Exchange","sector":"Utilities","calculationPrice":"close","open":35.46,"openTime":1530624610086,"close":35.91,"closeTime":1530637321400,"high":36.08,"low":35.36,"latestPrice":35.91,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637321400,"latestVolume":343636,"iexRealtimePrice":35.9,"iexRealtimeSize":4,"iexLastUpdated":1530637188067,"delayedPrice":35.91,"delayedPriceTime":1530637321400,"extendedPrice":35.858,"extendedChange":-0.052,"extendedChangePercent":-0.00145,"extendedPriceTime":1530637863238,"previousClose":35.44,"change":0.47,"changePercent":0.01326,"iexMarketPercent":0.0066,"iexVolume":2268,"avgTotalVolume":588801,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":6388304755,"peRatio":26.02,"week52High":39.55,"week52Low":32.3,"ytdChange":-0.046271572868625294},"chart":[]},"WTTR":{"quote":{"symbol":"WTTR","companyName":"Select Energy Services Inc. Class A","primaryExchange":"New York Stock Exchange","sector":"Industrials","calculationPrice":"close","open":14.37,"openTime":1530624600956,"close":14.55,"closeTime":1530637448209,"high":14.87,"low":14.21,"latestPrice":14.55,"latestSource":"Close","latestTime":"July 3, 2018","latestUpdate":1530637448209,"latestVolume":390909,"iexRealtimePrice":14.55,"iexRealtimeSize":200,"iexLastUpdated":1530637186010,"delayedPrice":14.55,"delayedPriceTime":1530637448209,"extendedPrice":14.55,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1530639382777,"previousClose":14.18,"change":0.37,"changePercent":0.02609,"iexMarketPercent":0.01474,"iexVolume":5762,"avgTotalVolume":897508,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":1550838697,"peRatio":44.09,"week52High":21.96,"week52Low":11.22,"ytdChange":-0.17621263157894726},"chart":[]}}`

**Comment by joshuablackburn-iex** [comment]
This call did not return chart data because US markets were closed on July 4th.

**Comment by cgi1** [comment]
Well.. Thats right. It is like so often a documentation problem. 

Is the API not returning data if the market was closed on yesterday? No.. Even if today is a Sunday, it returns the data from Friday. If it is working like this, one would assume, that the API always returns the data from the last trading day. Nevertheless, I understand that this implies some effort by filtering out the holidays. Here is some working code which could build the base for that problem in python3 (I use it by myself)

```

import pandas_market_calendars as mcal
import numpy

def get_offset_to_last_market_date(timestamp=None):


    """
    :return: offset to last market date
    """
    # Getting candle of last weekday in the past
    if timestamp == None:
        today = datetime.datetime.today()
    else:
        if isinstance(timestamp, str):
            today = datetime.datetime.strptime(timestamp, '%Y-%m-%d')
        elif isinstance(timestamp, datetime):
            today = timestamp
        else:
            print("timestamp has invalid type! <str> or <datetime> supported")

    weekday_today = weekday(month=today.month, year=today.year, day=today.day)
    offset_to_last_weekday = 1
    if weekday_today == 0:
        print("Today is Monday. Last market day was a Friday.")
        offset_to_last_weekday = 3
    elif weekday_today >= 1 and weekday_today <= 5:
        offset_to_last_weekday = 1
    elif weekday_today == 6:
        offset_to_last_weekday = 2
        print("Today is Sunday. Last market day was a Friday.")
    else:
        print("LOGIC ERROR ")

    yesterday_date = (today - datetime.timedelta(days=offset_to_last_weekday))

    nyse = mcal.get_calendar('NYSE')
    holidays = nyse.holidays()

    # ToDo: To be improvement on christmas

    if numpy.datetime64(yesterday_date.date()) in holidays.holidays:
        print('(%s) was a holiday!' % yesterday_date)
        if weekday_today == 0:
            print(
                'Today is Monday. Last Friday was a holiday. So Thursday should be good (It is not been handled if Thursday is a holiday too!).')
            offset_to_last_weekday = 4
        elif weekday_today == 1:
            print(
                'Today is Tuesday. Yesterday was Monday, which was a holiday. So Friday should be good. (It is not been handled if Friday was a holiday too (or a weekend day)!).')
            offset_to_last_weekday = 4
        elif weekday_today >= 2 and weekday_today <= 5:
            print(
                'Today is Wednesday-Friday. Yesterday was a a holiday, so just add one day as offset. (It is not been handled if that day was a holiday too (or a weekend day)!).')
            offset_to_last_weekday = 2
        elif weekday_today == 6:
            offset_to_last_weekday = 3
            print(
                "Today is Sunday. Last market day was a Friday, which was a holiday, so just add one day as offset. (It is not been handled if that day was a holiday too (or a weekend day)!).")
        else:
            print("LOGIC ERROR ", logging.ERROR)

    return offset_to_last_weekday
```
