### ISSUE TITLE
key stats api - ebitda, marketcap are round numbers or with decimal?

### ISSUE THREAD

**Issue by shuwnyuantee** [iexg/IEX-API#41]
In `key stats` api, many fields are of type `number` per your documentation. Number can either be `(1) round number ,  or  (2) number with decimal places` . In Java, the types used will be `(1) int / long   (2) double` .

Based on sample output in API doc & a few tested stocks, I declare most `number` field as `double`, except these fields highlighted in red:

<img width="333" alt="stats" src="https://user-images.githubusercontent.com/614382/31368482-aab90ad6-adb0-11e7-8bc9-38f7497800ad.png">

```
marketcap
shortInterest
sharesOutstanding
float
numberOfEstimates
EBITDA
revenue
grossProfit
cash
debt
```

The highlighted fields are usually big number, which I would assume they will be round number, as decimal places has no significant meaning. But my assumption seems wrong, as came across EBITDA returns this:

<img width="596" alt="222" src="https://user-images.githubusercontent.com/614382/31368438-6a7176fc-adb0-11e7-8df2-0c0a08b3a373.png">

Can I safely treat some number fields to always return round number? If yes, which of the fields? Or shall I always assume all of them might return number with decimal places?

Thanks!

**Comment by evancarter-iex** [comment]
This should be constant among fields in IEXcloud. https://iexcloud.io
