### ISSUE TITLE
Batch requests for dividends and chart, chart has dividends data

### ISSUE THREAD

**Issue by DisfiguredBeast** [iexg/IEX-API#410]
## Summary
When making a batch request for chart and dividends, chart contains dividends data.

## Details
When making a batch request for chart and dividends, dividends seem fine but chart contains the same data as dividends.
Happens with a single symbol request and a market request for multiple symbols.

### Date/time of issue
07/05/2018

### API URL
https://api.iextrading.com/1.0/stock/aapl/batch?types=dividends,chart&range=1y
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,htht&types=dividends,chart&range=1y

### What you expected to happen
"dividends" contains an array of dividends, "chart" contains an array of chart data.

### What actually happened
"chart" contains the same data as "dividends"

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud https://iexcloud.io
