### ISSUE TITLE
When should late "sip" quote change to "close"?

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#411]
## Summary
Quotes w/calculationPrice of "sip" appear well after the close.  Usually these are marked "close" before 4:30pm but the past week I have seen the "sip" data often persist until later for several tickers (not all).

## Details
This is similar to other issues I've raised in the past but not quite the same.  If the quote data will be better rationalized and defined in V2 I'm happy to wait.

### Date/time of issue
Thu Jul5 4:56pm ET

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=UPS&types=quote,previous,ohlc

### What you expected to happen
Expecting calculationPrice to be "close" shortly after market closes.

### What actually happened
See "sip" quote info instead.  It has today's market close price and "latestTime" but "closeTime" reflects previous market day date and time.  All other fields related to market close also are from day prior - close, closeTime, all the ohlc data, and so on.

### Other Information (sample code, links, etc.)
Sample info from Thu Jul5 at 4:56pm
Array
(
    [quote] => Array
        (
            [symbol] => UPS
            [companyName] => United Parcel Service Inc.
            [primaryExchange] => New York Stock Exchange
            [sector] => Industrials
            [calculationPrice] => sip
            [open] => 105.99
            [openTime] => 1530797462471
            [close] => 105.76
            [closeTime] => 1530637388764
            [high] => 106.34
            [low] => 104.94
            [latestPrice] => 106.29
            [latestSource] => 15 minute delayed price
            [latestTime] => 4:03:41 PM
            [latestUpdate] => 1530821021464
            [latestVolume] => 2851680
            [iexRealtimePrice] => 106.25
            [iexRealtimeSize] => 100
            [iexLastUpdated] => 1530820798005
            [delayedPrice] => 106.29
            [delayedPriceTime] => 1530821021464
            [extendedPrice] => 106.29
            [extendedChange] => 0
            [extendedChangePercent] => 0
            [extendedPriceTime] => 1530822820003
            [previousClose] => 105.76
            [change] => 0.53
            [changePercent] => 0.00501
            [iexMarketPercent] => 0.01875
            [iexVolume] => 53469
            [avgTotalVolume] => 2939826
            [iexBidPrice] => 0
            [iexBidSize] => 0
            [iexAskPrice] => 0
            [iexAskSize] => 0
            [marketCap] => 91588836758
            [peRatio] => 17.01
            [week52High] => 135.53
            [week52Low] => 101.4531
            [ytdChange] => -0.12578068788844
        )

    [previous] => Array
        (
            [symbol] => UPS
            [date] => 2018-07-03
            [open] => 106.26
            [high] => 106.85
            [low] => 105.46
            [close] => 105.76
            [volume] => 1145680
            [unadjustedVolume] => 1145680
            [change] => -0.12
            [changePercent] => -0.113
            [vwap] => 106.0671
        )

    [ohlc] => Array
        (
            [open] => Array
                (
                    [price] => 105.99
                    [time] => 1530797462471
                )

            [close] => Array
                (
                    [price] => 105.76
                    [time] => 1530637388764
                )

            [high] => 106.34
            [low] => 104.94
        )

)

**Comment by joshuablackburn-iex** [comment]
Is this still occurring?

**Comment by McQgit** [comment]
I have not seen it occur the past few trading days.  Did you change something? :)
