### ISSUE TITLE
Questions - IEX HIST Binary Data Feed

### ISSUE THREAD

**Issue by vfrazao-ns1** [iexg/IEX-API#412]
## Summary

I am creating a small Python program to decode IEX's binary data feeds <https://github.com/vfrazao-ns1/IEX_hist_parser> and have a couple of questions.

I understand that the binary data feeds are a different product from the API so if this is not the appropriate venue for questions on the topic please direct me to the correct place. 

## Questions

1. Is the HIST data adjusted for dividends, splits, etc.? If so how often?
2. Am I required to fill out and submit a Data Agreement prior to accessing the data?

**Comment by joshuablackburn-iex** [comment]
HIST data is just a raw output of our market data feed, and is not adjusted.  You do not need a data agreement for HIST.
