### ISSUE TITLE
News API not logging past articles and doesn't recognize "&" or apostrophes 

### ISSUE THREAD

**Issue by PhublePhilly** [iexg/IEX-API#414]
The news API is not logging previous articles for some stocks. 

We have the code set to load the past 10 articles on our server, but the API only loads 3 or 4 news articles for a lot of common stocks, such as Apple, American Airlines, AMC...etc. The news API also does not recognize "&" or apostrophes. 

7/01/2018 5:00 PM

## API URL
https://api.iextrading.com/1.0/stock/fcau/news/last/10

## What you expected to happen 
The API to load the past 10 news articles for a given stock.

## What actually happened
Only same-day articles have been loading 

### Other Information (sample code, links, etc.)
https://phuble.com/stock/SNAP/profile#news

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
