### ISSUE TITLE
Financials data: Total Liabilities and Current Liabilities Field is null for all stocks and not giving any data

### ISSUE THREAD

**Issue by itcaddie** [iexg/IEX-API#415]
## Summary
Hi IEX team, We are trying to use the below financial api and trying to use the Total Liabilities field element or total Current Liabilities from the API but we are getting blank or null or no data data for any of the stocks. Please check and do the needful to resolve the issue as we require this field Current Liabilities or Total Liabilities for Every Quarter. Usually we will have the current liabilities & total Liabilities in the balance sheet of financials.

## Details
We request you to check and provide us the Current Liabilities of Total Current Liabilities fields for the quarters. By using below we are getting blank or null and no data data for total liabilities field for all the stocks
API : https://api.iextrading.com/1.0/stock/aapl/financials

### Date/time of issue

Sunday 11:52 AM EST

### API URL
Sample stock API where we are getting blank or null for Total Liabilities.
https://api.iextrading.com/1.0/stock/aapl/financials

### What you expected to happen

We need data for Total Liabilities for every quarter or add new field called current liabilities and provide data for every quarter.

### What actually happened

NO Data Is coming when we try to see data.

### Other Information (sample code, links, etc.)

Sample example : This is the balance sheet from nasdaq where you can see both the fields Current Liabilities and Total Liabilities. Please check and apply the fix to the existing financial api to get us the data.

https://www.nasdaq.com/symbol/aapl/financials?query=balance-sheet

Much Appreciated!

Thanks
Venkat

**Comment by dantash** [comment]
any news on this topic?

**Comment by evancarter-iex** [comment]
This is fixed with IEX Cloud. Https://iexcloud.io
