### ISSUE TITLE
Certain endpoints not returning data

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#416]
## Summary

Most of the ``ref-data`` endpoints return empty, as well as ``IEX Short Interest List`` from ``Stock``. I mentioned this in #199, but not sure if my usage is incorrect or the endpoints are indeed returning incorrectly.

### Date/time of issue

7/9/18

### API URL

``ref-data/daily-list/corporate-actions``
``ref-data/daily-list/dividends``
``ref-data/daily-list/next-day-ex-date``
``stock/market/short-interest/20180609``

### What actually happened

``[]``

### Other Information (sample code, links, etc.)

I understand that certain endpoints return empty on certain days (i.e. when there are no dividends), but even selecting dates where dividends were issued returns empty.

**Comment by joshuablackburn-iex** [comment]
All of these are returning empty as designed.  These particular endpoints are for IEX listed securities only, and IEX currently does not have any listed securities.
