### ISSUE TITLE
No data for several symbols

### ISSUE THREAD

**Issue by Nimce** [iexg/IEX-API#417]
## Summary
IEX API does not give chart data for several symbols, for example: FSBW.

## Details
IEX API returns -1 in high, low, average.

### Date/time of issue
Since 07/10/2018.

### API URL
https://api.iextrading.com/1.0/stock/fsbw/chart/1d

### What you expected to happen
IEX API returns correct values, for example the AAPL stock:
https://api.iextrading.com/1.0/stock/aapl/chart/1d

### What actually happened
-1 values are returned.

**Comment by joshuablackburn-iex** [comment]
This typically occurs in thinly traded names.  The symbol FSBW, for example, only averages 30k shares a day.  It is entirely possible to have multiple minutes in the day when no trades occur.  This will result in the -1 values.
