### ISSUE TITLE
When is chart endpoint updated?

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#418]
Hi, anybody know at what time the chart endpoint is updated with OHLC for current day?

Thanks!

**Comment by joshuablackburn-iex** [comment]
The 1D chart is updated every minute with real time data, and back filled with 15 minute data.  So a 1D chart will be complete by 4:15 ET.  OHLC endpoint should be complete a little after 4pm.  Some exchanges report official close later than 4pm.  There are cases where the official close could go as long as 5pm ET before being published.

**Comment by gabrieldodan** [comment]
Thank you very much @joshuablackburn-iex for the answer. More precisely I am interested to know when the data(open, high, low, close, volume) for current day is included in period=1m chart. Do you have any idea? 


Also I have just noticed an inconsistency on chart and ohlc endpoints.  
https://api.iextrading.com/1.0/stock/market/batch?symbols=SSBI&types=ohlc
https://api.iextrading.com/1.0/stock/market/batch?symbols=SSBI&types=chart&period=1m

At this moment ohlc endpoint says open=15.8 but chart endpoint says open=15.7089 ...

**Comment by joshuablackburn-iex** [comment]
The first availability should be 11pm ET.

**Comment by gabrieldodan** [comment]
Thank you!

**Comment by bkcollection** [comment]
Hi Joshua,

https://api.iextrading.com/1.0/stock/aapl/chart/1y

is that mean the OHLC for 27 July will only be updated at 27 July 11pm ET for the api above?
