### ISSUE TITLE
Batch request returns null for nearly all endpoints [Issue]

### ISSUE THREAD

**Issue by Davincible** [iexg/IEX-API#42]
Batch request returns null for nearly all endpoints.

Tried requests:
- https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,tsla&types=symbol,latestPrice,latestSource,latestUpdate,latestVolume,previousClose
- https://api.iextrading.com/1.0/stock/tsla/batch?types=symbol,latestPrice,latestSource,latestUpdate,latestVolume,previousClose

**Comment by joshuablackburn-iex** [comment]
It looks like you want to get a quote for multiple symbols, then filter the result.  The correct URL to do that is  https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,tsla&types=quote&filter=symbol,latestPrice,latestSource,latestUpdate,latestVolume,previousClose

**Comment by joshuablackburn-iex** [comment]
The 'types' parameter is used to define the endpoints you want to return.  The 'filter' parameter is used to define the key names you want from each endpoint.
