### ISSUE TITLE
failed iexfinance installation in Python 3.7

### ISSUE THREAD

**Issue by Chipingai** [iexg/IEX-API#420]
## Summary

Failed iexfinance 0.3.3 installation in Python 3.7

## Details
I enter pip3 install iexfinance, but got error massage: could not find a version that satisfies the requirement numy==1.9.3 (from versions:1.14.5, 1.15.orc2). No matching distribution found for numpy==1.9.3.
### Date/time of issue

7/11/2018  12:00AM

**Comment by joshuablackburn-iex** [comment]
Since this is not an official library, you should contact the author or wait for a response from another user.
