### ISSUE TITLE
range=1m return data from a year ago

### ISSUE THREAD

**Issue by khollm** [iexg/IEX-API#421]
## Summary
When I try to get chart info over the last month it gives me information of the last year's last month.
I think I should add that if I try with AAPL instead of BCR the information I receive are correct

## Details
see summary
### Date/time of issue
Today

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=BCR&types=chart&filter=date&range=1m

### What you expected to happen
Get info over the last month

### What actually happened
get info over last year last month

### Other Information (sample code, links, etc.)

```
{"BCR":{
"chart":[
{"date":"2017-12-04"},
{"date":"2017-12-05"},
{"date":"2017-12-06"},
{"date":"2017-12-07"},
{"date":"2017-12-08"},
{"date":"2017-12-11"},
{"date":"2017-12-12"},
{"date":"2017-12-13"},
{"date":"2017-12-14"},
{"date":"2017-12-15"},
{"date":"2017-12-18"},
{"date":"2017-12-19"},
{"date":"2017-12-20"},
{"date":"2017-12-21"},
{"date":"2017-12-22"},
{"date":"2017-12-26"},
{"date":"2017-12-27"},
{"date":"2017-12-28"}
]}
}
```
Thank you for reading and keep the good Work ;)

**Comment by joshuablackburn-iex** [comment]
BCR is no longer a valid symbol.  What you are seeing is the last available 1 month chart before that symbol stopped trading.

**Comment by khollm** [comment]
Ok how can I know if a Stock is active?
(Thanks for the fast answer)

**Comment by joshuablackburn-iex** [comment]
You can use this endpoint https://iextrading.com/developer/docs/#symbols

**Comment by khollm** [comment]
Thank you.
