### ISSUE TITLE
quote endpoint returns wrong data for many symbols

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#422]
## Details
quote endpoint return wrong data for many symbols. Wrong data means high value lower than open/close value, or low value greater than open/close value

### Date/time of issue
July 13, 2018

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=PICB&types=quote

### What you expected to happen
high >= open

### What actually happened
high < open

### Other Information (sample code, links, etc.)

The issue happens for many other symbols: PEJ, LIVE, NHLD, PICB, DLHC ..

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud. http://iexcloud.io
