### ISSUE TITLE
Incorrect daily price change on ex-dividend date

### ISSUE THREAD

**Issue by HeadWrench** [iexg/IEX-API#423]
## Summary
For some securities, IEX is reporting an incorrect price change amount on ex-dividend date. The market price was adjusted down for the amount of the dividend, however the Previous Close was not adjusted down accordingly. This results in a calculation of daily change that gives a false report of a big drop in share price.

## Details
The affected tickers that I observed this morning July 13th are
BDCL
CEFL
LRET
LMLP
MLPQ
DVYL
SDYL
SMHD
As an example, yesterday's close for MLPQ was $32.79 and ex-dividend is today at $1.1285.
The issue opened trading appropriately at the dividend adjusted price of 31.66 however IEX still shows the Previous Close at 32.79 with daily change of -1.13 (-3.45%) which of course is simply inaccurate.
On the subject of inaccuracy, IEX reports the ex-dividend date for MLPQ as October 10,**2017**
### Date/time of issue

July 13, 2018

### API URL
https://iextrading.com/apps/stocks/MLPQ

### What you expected to happen

See above

### What actually happened

See above

**Comment by joshuablackburn-iex** [comment]
@HeadWrench Thank you for bringing this to our attention.  We source this data from a 3rd party, so we will reach out immediately and figure out what is going on.

**Comment by mikmorg** [comment]
I came here for a similar issue. Yahoo and Bloomberg, for instance, show EEM close prices accurate for 4/17/2017 at 39.55, where IEX shows the adjusted close to be 37.9541. Similar differences exist throughout this symbol's adjusted prices on IEX vs Yahoo & BB.

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557

**Comment by evancarter-iex** [comment]
This should be fixed in IEXCloud. If its not please file a new bug. https://iexcloud.io
