### ISSUE TITLE
Images not loading in news - 403 forbidden

### ISSUE THREAD

**Issue by peder1001** [iexg/IEX-API#425]
## Summary
Images in news items do not work. 403 permission denied

## Details
Example: https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=news
Try opening/loading an image, for example:
https://api.iextrading.com/1.0/stock/aapl/news-image/7896719890823430

### Date/time of issue
Sunday 15th July 2018

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=news

### What you expected to happen
Expected to be able to load an image

### What actually happened
403 denied

### Other Information (sample code, links, etc.)
![image](https://user-images.githubusercontent.com/6201162/42736109-58ff77da-8860-11e8-8a80-959c8f1941a3.png)

![image](https://user-images.githubusercontent.com/6201162/42736124-a02ad74e-8860-11e8-9cb1-b5c924db5dc9.png)

**Comment by pingpingsim** [comment]
I'm getting the same issue as well.

**Comment by estherh5** [comment]
I'm also running into this issue. Has anyone found a good workaround for this?

**Comment by drewbutcher** [comment]
I'm having the same issue as well.  Hope there is a fix soon!

**Comment by GermaVinsmoke** [comment]
I'm also having the same issue.

**Comment by ereyes1** [comment]
Me tooos.

**Comment by icastillejogomez** [comment]
Please fix it!! 😢 😭

**Comment by jonivrapi** [comment]
I am also having this issue

**Comment by derekm228** [comment]
Surprised this hasn't been addressed yet.

**Comment by evancarter-iex** [comment]
We are aware of the issue but have been focused on more pressing priorities. This is in the queue.

**Comment by tmswartz12** [comment]
Would love to have this issue fixed!

**Comment by marty331** [comment]
Still broken - Nov 8.  Please fix!!

**Comment by SauceDoctR914** [comment]
Still an issue :(

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557 for updates on this and other issues.

**Comment by zeroblaz3** [comment]
I checked #557 yet see no reference to this issue. Can you please help us understand?

**Comment by evancarter-iex** [comment]
This is fixed in IEX Cloud. https://iexcloud.io/

It does appear that some images are not being propagated properly (still looking into why) but they return a "Not found" but many are correctly returning images.

**Comment by barrard** [comment]
Still broken.... Need help?

**Comment by SauceDoctR914** [comment]
@evancarter-iex yes even with the cloud, that is an accurate description, some work some don't.

**Comment by roman-simionov** [comment]
The same issue is reproduced at https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb,tsla&types=quote,news,chart&range=1m&last=5
