### ISSUE TITLE
Wrong Open Value

### ISSUE THREAD

**Issue by Fabix84** [iexg/IEX-API#426]
Hi,

I have been monitoring the opening price of some symbols for a few days, and I have noticed that the opening price indicated differs from the real opening price. After a couple of days, you find the correct price in the chart api, but by calling the api (quote or ohlc) in real time, the indicated price is often wrong.

For example, now for Netflix stock (NLFX):
_https://api.iextrading.com/1.0/stock/market/batch?symbols=NFLX&types=ohlc&range=1m_

we have this result:
{"NFLX":{"ohlc":{"open":{"price":399.01,"time":1531747800470},"close":{"price":395.8,"time":1531512000167},"high":403.355,"low":391.75}}}

so for your data the open value is **399.01**.

The real open value is **398.98**.

Why does this discrepancy exist? Is possible to fix?

Thank you

**Comment by joshuablackburn-iex** [comment]
@Fabix84 The real time open/close price you get in quote or ohlc is from IEX.  The open/close price you're getting in the historical chart data is from our 3rd data provider.  IEX is disseminating the correct ("real") open value.  We are displaying the open value marked as the official opening price from the primary listing exchange.  Other providers, including Yahoo, are showing the first consolidated trade after 9:30.  The first trade is not the official opening price.  There are times the primary listing exchange takes longer to publish the official open than for a trade to happen elsewhere.  

In your Netflix example for today, 399.01 is the official opening price.  398.98 is the first consolidated trade.  When our 3rd party data provider gives us adjusted historical prices, it includes the wrong open.  We will reach out to them and identify this error.

**Comment by evancarter-iex** [comment]
@Stafie This is fixed in IEXCLoud. https://iexcloud.io
