### ISSUE TITLE
Looking for an api key for platinum palladium and rhodium

### ISSUE THREAD

**Issue by Mawn12** [iexg/IEX-API#427]
## Summary

Im looking for an api for palladium platinum and rhodium. Does this support commodities stock market?

**Comment by joshuablackburn-iex** [comment]
We currently do not support commodities, but it is on our roadmap.

**Comment by mitalpha** [comment]
https://api.iextrading.com/1.0/stock/pplt/quote
https://api.iextrading.com/1.0/stock/pall/quote
https://api.iextrading.com/1.0/stock/plg/quote
https://api.iextrading.com/1.0/stock/sppp/quote
futures is another story

**Comment by timpaine-iex** [comment]
https://iexcloud.io/console/roadmap
