### ISSUE TITLE
hist json stale

### ISSUE THREAD

**Issue by jsanelli** [iexg/IEX-API#428]
## Summary  
hist links returned by api do not include recent updates  

## Details  
links from API do not contain recent hist  

### Date/time of issue  
July 18, 2018  

### API URL
https://api.iextrading.com/1.0/hist  

### What you expected to happen  
20180717  

### What actually happened  
[{"link":"https://www.googleapis.com/download/storage/v1/b/iex/o/data%2Ffeeds%2F20180713%2F20180713_IEXTP1_DEEP1.0.pcap.gz?generation=1531526641047461&alt=media","date":"20180713","feed":"DEEP","version":"1.0","protocol":"IEXTP1","size":"544710889"},{"link":"https://www.googleapis.com/download/storage/v1/b/iex/o/data%2Ffeeds%2F20180713%2F20180713_IEXTP1_TOPS1.6.pcap.gz?generation=1531526818097837&alt=media","date":"20180713","feed":"TOPS","version":"1.6","protocol":"IEXTP1","size":"451273279"}]}  

### Other Information (sample code, links, etc.)

**Comment by evancarter-iex** [comment]
Sorry about that. They should be coming online now. Reopen the bug if they arent there in the next couple of hours.

**Comment by jsanelli** [comment]
20180717 works great, tnx. However, yesterday's 20180718 is missing.

**Comment by evancarter-iex** [comment]
@jsanelli Thanks they were a bit delayed today. Going out as we speak.
