### ISSUE TITLE
Best way and earliest way to get finalized EOD quotes

### ISSUE THREAD

**Issue by jacklin10** [iexg/IEX-API#429]
## Summary

I'm trying to get final EOD quotes in a more timely manner.  
Using the api's I describe in the details below, I only seem to be able to get an EOD quotes for current day at midnight aka the next day. I'd like to get them closer to market close.

I'm not sure if I need to use a different api endpoint or if maybe it isn't possible.  

## Details

Doing this will get me the EOD quote for TACO as of yesterday (Jul 17th).  This is perfect.
https://api.iextrading.com/1.0/stock/market/chart/1m?chartLast=2&symbols=TACO&chartReset=true

My issue is that at market close today (Jul 18th) I won't see the Jul 18th quote in the results.  I'll see only Jul 17th until midnight. 

I can instead use this method:
https://api.iextrading.com/1.0/stock/market/quote?symbols=TACO

Which will give me a quote at 3:59pm, but i'm assuming that isn't the final quote and is subject to change. ( Or maybe not?  I can't tell for sure )

So my question is:  What is the best way (soonest timeframe) to get the final EOD quote when the market closes today.

### Date/time of issue

This isn't really a specific date/time kind of issue.  I assume what i'm reporting happens everyday.

### API URL

Two examples given above in the summary.

### What you expected to happen

My expectation is that I can use the this api: 
https://api.iextrading.com/1.0/stock/market/chart/1m?chartLast=2&symbols=TACO

around 4pm EST at market close, to get the final EOD quote. 

### What actually happened

Instead you can only get the EOD quote at midnight.

**Comment by mitalpha** [comment]
https://www.sec.gov/fast-answers/answerscloseprhtm.html

**Comment by gabrieldodan** [comment]
See also #418 Personally I update EOD data at 23:15:00 ET but I have noticed that sometimes data is not accurate for some symbols. I mean, for example close reported at 23:15:00 is different than close reported at 01:00:00 next day. 

quote endpoint has some issues also, see #422

**Comment by jacklin10** [comment]
Hmm, okay.  So it seems like the best way to do this is snag the quote a few different times then.  
I can use this to present an unofficial EOD: 
https://api.iextrading.com/1.0/stock/market/quote?symbols=TACO

Then run an update using the types=ohlc (as you point out in your referenced issue) at 11:15 in case of a change, and then maybe again the next day to clean up any misreporting done in the previous 2 pulls.

There doesn't really seem to be a silver bullet way to get that accurate EOD in a timely manner I guess.  At least not with one call.  Bummer.

**Comment by McQgit** [comment]
@jacklin10 
"I can instead use this method:
https://api.iextrading.com/1.0/stock/market/quote?symbols=TACO
Which will give me a quote at 3:59pm, but i'm assuming that isn't the final quote and is subject to change. ( Or maybe not? I can't tell for sure ) ..."

I've been getting EOD (official consolidated) closes looking at the /quote endpoint at 4:30p every trading day.  Look at the quote "latestPrice" and when it says "Close" - that's the official close.  I check the "latestUpdate" to ensure its the right day too (its in millisecs).  Sometimes odd things happen such as not seeing "Close" on some symbols (see my history of reported issues) but it's relatively good.  The "Close" status appears, I think, as early as 4:15-4:20p but waiting until 4:30p has worked out better.

I am hoping they better rationalize and define the quotes in V2.

**Comment by evancarter-iex** [comment]
With IEX Cloud, close prices will come in around 4:30pm ET. Mutual fund prices and other EOD prices will be available at roughly anywhere from 8:30pm to 9:30pm ET.

https://iexcloud.io
