### ISSUE TITLE
How to get simple item from get_news() using Json library

### ISSUE THREAD

**Issue by spiderman04** [iexg/IEX-API#431]
## Summary
I am trying to use the json methods (versus using reg and other complicated methods) to look for say, the 'headline' from the return list. The doc says the type is either a list or dict but in Python 3.6.5 I see the return as <list>.

How can I easily get the 'headline' string from the API call and using json.loads() to covert the list.

## Details
Code I have is simple:

from iexfinance import Stock

theQuote = Stock(x)   # where x is a simple loop from a list
newsList = theQuote.get_news(last=7)    # type does not return <dict> but rather <list>
jsonStr = json.loads(str(newsList))   # I have tried other variations of ''.join(), etc.
print(jsonStr['headline'])  

Error:

### Date/time of issue
7/20/18 from Python 3.6.5 on Windows 7 64-bit at 1pm EST.

### API URL
using plugin for Python here:
#Reference: https://addisonlynch.github.io/iexfinance/stable/usage.html

### What you expected to happen
For example, for x='DATA' quote, the headline string to be returned as:

{...,'headline': 'Tableau Software makes interim CFO permanent'...

### What actually happened
Traceback (most recent call last):
  File "C:\Users\admin2\Desktop\stock_info.py", line 30, in <module>
    jsonStr = json.loads(str(newsList))
  File "C:\Users\admin2\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\admin2\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\admin2\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

**Comment by joshuablackburn-iex** [comment]
It looks like you are using one of the unofficial libraries.  This will require a response from other users or the owner of that library.

**Comment by spiderman04** [comment]
I'm confused, isn't this library from your web site on iexfiance? OTOH, do you have a better library in mind?

**Comment by joshuablackburn-iex** [comment]
It is listed here:
https://iextrading.com/developer/docs/#unofficial-libraries-and-integrations
