### ISSUE TITLE
[Feature Request] Add a way to get companies with highest marketcap

### ISSUE THREAD

**Issue by PlanetVaster** [iexg/IEX-API#432]
## Summary
Could you add a way to get the [x] number of highest companies by marketcap (and maybe other params like price as well). Say for example, on my website homepage I want to show the top 10 companies by marketcap so I call something like https://api.iextrading.com/1.0/stock/market/highest?type=marketcap&amount=10 or something like that to get the top 10 companies by marketcap.

### Other Information (sample code, links, etc.)
Thanks for making this great api, and for making it free. I appreciate all the hard work the IEX Trading team put into it :).

**Comment by joshuablackburn-iex** [comment]
This would be a nice enhancement of our `lists` endpoint.
