### ISSUE TITLE
Market refresh of last 5 days

### ISSUE THREAD

**Issue by nomisvai** [iexg/IEX-API#435]
## Summary
Is there a way to quickly retrieve all symbols EOD OHLC values for the last 5 days?

## Details
It would be nice if we could call a endpoint like: https://api.iextrading.com/1.0/stock/market/ohlc/5d that would return the last 5 days OHLC of all stocks. It would allow for doing a quick sync, and updating corrected errors on our local db. Right now a single request for each symbols has to be sent and it's takes a long time, the 429  throttling does not help either.. 

sample of a payload: 

{  "SPY": { 
    [
      "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    },
    {
      "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    },
    {
       "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    },
    {
      "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    },
    {
       "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    }
	]},
  "IBM": { 
    [
      "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    },
    {
      "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    },
    {
       "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    },
    {
      "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    },
    {
       "time": 1532352600138,
      "open": 279.46,
      "close": 280.2,
      "low": 279.46,
      "high": 280.2
    }
	]}
    /// .. etc for all symbols
}

**Comment by timpaine-iex** [comment]
closing as stale, at this point "all" (100,000+) symbols is simply too many symbols to be returning data for. for IEX Cloud, there is the `batch` endpoint as well as the `chart` and `time-series` endpoints which would let you construct a query for 100 symbols at a time and just the last e.g. `5` records, using `filter` to subselect the columns you want.
