### ISSUE TITLE
list endpoint return no data for most active

### ISSUE THREAD

**Issue by vishnukumarbp** [iexg/IEX-API#436]
## Summary
Trying to use "List" end point for most active stocks. It is returning empty list.

### Date/time of issue
25/July/2018 10AM

### API URL
https://api.iextrading.com/1.0/stock/market/list/mostactive

### What you expected to happen
Should return list of most active stock data

### What actually happened
returned empty array

**Comment by joshuablackburn-iex** [comment]
Are you still experiencing this issue?  There is a period of time in the morning where this will return empty due to the trading system resetting for a new trading day.
