### ISSUE TITLE
Chart API for AAMC problem in json format

### ISSUE THREAD

**Issue by theofil** [iexg/IEX-API#437]
## Summary
Chart returns broken json format for last 2 days
https://api.iextrading.com/1.0/stock/AAMC/chart/1m

## Details
See for example 2018-07-23 and 2018-07-24 for AAMC
<img width="710" alt="image" src="https://user-images.githubusercontent.com/4677362/43209014-fa72911a-902b-11e8-8a52-06ac733c7a46.png">

### Date/time of issue
2018-07-25 14:57 UTC

### API URL
https://api.iextrading.com/1.0/stock/AAMC/chart/1m

### What you expected to happen
see also OPEN, LOW, HIGH with real or NULL values if for some reason IEX doesn't have the OPEN/LOW/HIGH for those dates

**Comment by joshuablackburn-iex** [comment]
We investigated this, and data for the 23rd and 24th is correct.  This symbol only traded odd lots for those two days which does not update the last sale information.  Therefore, you will not have a high, low, and other related info.
