### ISSUE TITLE
Reliability of historical data by Chart API

### ISSUE THREAD

**Issue by Fabix84** [iexg/IEX-API#438]
Hi,

I'm monitoring some historical data from some stocks, for example Apple (AAPL).

https://api.iextrading.com/1.0/stock/aapl/batch?types=chart&range=5y

For example for the first element 25 July 2013:
"date":"2013-07-25", "open":57.4681, "high":57.5594, "low":56.8305, "close":57.1813, "volume":57371671
Open: 57.46
High: 57.55
Low: 56.83
Close: 57.17

there is a big discrepance with the data from others service providers, for example Yahoo (but not only Yahoo) that assign for the same day this values:

Open: 62.96
High: 63.06
Low: 62.26
Close: 62.64

Which data is the correct data?

Thank you,
Fabio

**Comment by jgresham** [comment]
second this

**Comment by brains4math** [comment]
IEX data is adjusted for dividends and splits, while yahoo data you're looking at is not. However this does not explain the 5.5 dollar difference, because AAPL paid more than that in dividends. In fact, I am not quite sure how yahoo finance is making their adjustments.

**Comment by schlambe4** [comment]
Doubtful that is the issue, there was an earnings report on 7/23 (2 days before) but the Dividend payment was only $3.05 (paid on 8/8)

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
