### ISSUE TITLE
Paid access to Market API

### ISSUE THREAD

**Issue by AndreyPerelygin** [iexg/IEX-API#439]
## Summary
Our service has some problems with limit of 100 requests per second.
We would like have real time data of all stocks in our database.

We try to contact with your team through the web site info, but had no luck.

**Comment by joshuablackburn-iex** [comment]
Have you tried the Websocket API?  This will allow you to subscribe to `firehose` and get real time updates on all symbols.

**Comment by AndreyPerelygin** [comment]
I was trying to use the websocket in test mode. I'm confused by the stability of the connection. What is the connection limit?

**Comment by joshuablackburn-iex** [comment]
What behavior did you experience from the server?

**Comment by elvistudio** [comment]
Joshua, how to get real time updates on all symbols via firehose? Do you have this example or similar as I can't find it. Thank you!

**Comment by evancarter-iex** [comment]
IEXCloud will use SSE which should scale a lot better than websockets. https://iexcloud.io
