### ISSUE TITLE
Dividend API doesn't return info for some stock (Like Banco Santander SAN)

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#44]
Hi,

We realize https://api.iextrading.com/1.0/stock/san/dividends/5y doesn't return any info.

For stock SAN, they do pay dividend - http://www.nasdaq.com/symbol/san/dividend-history

P/S We feel very grateful to IEX, for allowing public to access financial data at no cost. With such open data, we are able to provide more value on the top of them, to help investors making better decision. The following is part of the on-going developed feature, based on IEX data. Thank you!

![0](https://user-images.githubusercontent.com/308276/31632913-366bcb0a-b2f1-11e7-81b8-2589d0af1ace.png)

**Comment by evancarter-iex** [comment]
This appears to be fixed. Reopen if its not returning data.
