### ISSUE TITLE
News endpoint not returning last 5

### ISSUE THREAD

**Issue by dionk** [iexg/IEX-API#440]
## Summary
stock/news/last/5 is not returning 5 objects for all stocks.

## Details
When using this API previously, I was able to get the last 5 news articles for a given stock no matter the date. However, I noticed that recently, it's been only giving me varying amounts of news, sometimes 1, 3, or 4 (ex: NVDA/MU).

### Date/time of issue
Jul 27, 2018

### API URL
/stock/"stockname"/news/last/5

### What you expected to happen
Return 5 of the most recent news articles regarding company/stock.

### What actually happened
Returns 1-5.

**Comment by evancarter-iex** [comment]
This should be fixed with IEX Cloud. https://iexcloud.io
