### ISSUE TITLE
seeing (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))

### ISSUE THREAD

**Issue by jainraje** [iexg/IEX-API#442]
HI Guys,

I'm seeing this exception in my code just recently. I'm wondering if something changed on the server which triggers this. Below are 2 requests. 

First request generates an exception:
08/02/2018 01:42:59 PM ERROR (Thread-387) smdb_web.py:1510 getQuotes_iex() Exception error: HTTPSConnectionPool(host='api.iextrading.com', port=443): Max retries exceeded with url: /1.0/stock/market/batch?symbols=IJS,IJT,ILF,ILG,ILMN,ILPT,IMAX,IMDZ,IMGN,IMH,IMKTA,IMMR,IMMU,IMO,IMPV,IMXI,INAP,INBK,INCY,INDA,INDB,INDEX,INDY,INFN,INFO,INFY,ING,INGN,INGR,INN,INNT,INO,INOV,INS,INSM,INSP,INST,INSW,INSY,INT,INTC,INTF,INTL,INTU,INVA,INVH,INWK,INXN,IO,IONS,IOO,IOSP,IOTS,IOVA,IP,IPAR,IPE,IPG,IPGP,IPHI,IPHS,IPI,IQ,IQDF,IQV,IR,IRBT,IRDM,IRET,IRM,IRMD,IRT,IRTC,IRWD,ISBC,ISCA,ISD,ISRG,ISRL,ISTB,ISTR,IT,ITA,ITB,ITCI,ITE,ITG,ITGR,ITI,ITIC,ITM,ITOT,ITRI,ITT,ITUB,ITW,IUSG,IUSV,IVAC,IVC&types=quote (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),)) for vendor: iex

The second request data is returned:
08/02/2018 01:43:09 PM DEBUG (Thread-387) connectionpool.py:393 _make_request() https://api.iextrading.com:443 "GET /1.0/stock/market/batch?symbols=IJS,IJT,ILF,ILG,ILMN,ILPT,IMAX,IMDZ,IMGN,IMH,IMKTA,IMMR,IMMU,IMO,IMPV,IMXI,INAP,INBK,INCY,INDA,INDB,INDEX,INDY,INFN,INFO,INFY,ING,INGN,INGR,INN,INNT,INO,INOV,INS,INSM,INSP,INST,INSW,INSY,INT,INTC,INTF,INTL,INTU,INVA,INVH,INWK,INXN,IO,IONS,IOO,IOSP,IOTS,IOVA,IP,IPAR,IPE,IPG,IPGP,IPHI,IPHS,IPI,IQ,IQDF,IQV,IR,IRBT,IRDM,IRET,IRM,IRMD,IRT,IRTC,IRWD,ISBC,ISCA,ISD,ISRG,ISRL,ISTB,ISTR,IT,ITA,ITB,ITCI,ITE,ITG,ITGR,ITI,ITIC,ITM,ITOT,ITRI,ITT,ITUB,ITW,IUSG,IUSV,IVAC,IVC&types=quote HTTP/1.1" 200 None

Above scenario shows how the exception is handled and the next retry takes care of the issue. I have scenarios the server continues generate this exception on my side and my system locks up after the number of retries is exceeded.

I'm trying to understand the details here and why this is recently being generated. I never saw this before until recently (week or 2).

Thx,
-R

**Comment by evancarter-iex** [comment]
@jainraje Hmm...is it a certain time of day this occurs? Or is it completely random?

**Comment by evancarter-iex** [comment]
@jainraje Also what OS, language etc are you using?

**Comment by mitalpha** [comment]
https://api.iextrading.com/1.0/stock/market/batch?symbols=IJS,IJT,ILF,ILG,ILMN,ILPT,IMAX,IMDZ,IMGN,IMH,IMKTA,IMMR,IMMU,IMO,IMPV,IMXI,INAP,INBK,INCY,INDA,INDB,INDEX,INDY,INFN,INFO,INFY,ING,INGN,INGR,INN,INNT,INO,INOV,INS,INSM,INSP,INST,INSW,INSY,INT,INTC,INTF,INTL,INTU,INVA,INVH,INWK,INXN,IO,IONS,IOO,IOSP,IOTS,IOVA,IP,IPAR,IPE,IPG,IPGP,IPHI,IPHS,IPI,IQ,IQDF,IQV,IR,IRBT,IRDM,IRET,IRM,IRMD,IRT,IRTC,IRWD,ISBC,ISCA,ISD,ISRG,ISRL,ISTB,ISTR,IT,ITA,ITB,ITCI,ITE,ITG,ITGR,ITI,ITIC,ITM,ITOT,ITRI,ITT,ITUB,ITW,IUSG,IUSV,IVAC,IVC&types=quote
put in browser - no issues, 
probably it is your app or box to blame, 
I don't see any issues with such queries in my logs, 
run every day

**Comment by jainraje** [comment]
@evancarter-iex running python 3.6 on a ubuntu 16.04 LTS box. System has been running for months with out seeing this specific error. I just updated a few libraries (requests, crypto, urlib3) this weekend. Will provde update on any occurances of the error in the coming week.

@mitalpha as i mentioned this is a random error. The url works in a browser and with my python code. The error occurs infrequently and ive only started seeng it last week. 

Will run more tests and provide further updates this week.

**Comment by jainraje** [comment]
HI,
I appreciate you folks keeping this open for monitoring purposes. I haven't seen this same error since. It could have been some library update or change on my end (or potentially even a temporary library change on the server). I'm going to close this.

**Comment by morendav** [comment]
I've been getting this error - is there any resolution ?
