### ISSUE TITLE
What time do you adjust close values on Ex-Div dates?

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#443]
## Summary
The Quote latestPrice and close price are reduced by the amount of dividend on the ex-div date.  The /Previous endpoint close value is adjusted the same way.  What time of day is the official close adjusted in this manner?

## Details
I have not seen this happen before.  But, Fri Aug3 at 7a eastern I saw a couple tickers had their close prices adjusted for the dividend.  It is nice to have some sort of adjustment for this but it is not possible to tell from the /Quote or /Previous endpoints whether you are looking at official close or ex-div adjusted ones.  

Note the OHLC close was not adjusted so reflects Thu official close.  However, I also want to know the amount of change from one official close to the next and OHLC doesn't have change amounts so requires extra API calls.

### Date/time of issue
Fri Aug3 7a eastern

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=nsc&types=quote,previous,ohlc

### What you expected to happen
It's fine to adjust the close although it would be better to have the calculationPrice have a different value than "close" or some other indicator to distinguish an adjusted close from official.

It would be helpful to know the time of day the ex-div adjustments are made so can take proper precautions.

### What actually happened
Array
(
    [quote] => Array
        (
            [symbol] => NSC
            [companyName] => Norfolk Southern Corporation
            [primaryExchange] => New York Stock Exchange
            [sector] => Industrials
            [calculationPrice] => close
            [open] => 167.16
            [openTime] => 1533216600504
            [close] => 168.51
            [closeTime] => 1533240121638
            [high] => 169.72
            [low] => 166.755
            [latestPrice] => 168.51
            [latestSource] => Close
            [latestTime] => August 2, 2018
            [latestUpdate] => 1533240121638
            [latestVolume] => 1310788
            [iexRealtimePrice] => 
            [iexRealtimeSize] => 
            [iexLastUpdated] => 
            [delayedPrice] => 169.31
            [delayedPriceTime] => 1533240121638
            [extendedPrice] => 169.31
            [extendedChange] => 0.8
            [extendedChangePercent] => 0.00475
            [extendedPriceTime] => 1533242607406
            [previousClose] => 167.1365
            [change] => 1.3735
            [changePercent] => 0.00822
            [iexMarketPercent] => 
            [iexVolume] => 
            [avgTotalVolume] => 1798346
            [iexBidPrice] => 
            [iexBidSize] => 
            [iexAskPrice] => 
            [iexAskSize] => 
            [marketCap] => 47187815532
            [peRatio] => 21.41
            [week52High] => 172.81
            [week52Low] => 112.5
            [ytdChange] => 0.17170918329978
        )

    [previous] => Array
        (
            [symbol] => NSC
            [date] => 2018-08-02
            [open] => 166.3702
            [high] => 168.9181
            [low] => 165.9671
            [close] => 168.51
            [volume] => 1310396
            [unadjustedVolume] => 1310396
            [change] => 1.3735
            [changePercent] => 0.822
            [vwap] => 167.9381
        )

    [ohlc] => Array
        (
            [open] => Array
                (
                    [price] => 167.16
                    [time] => 1533216600504
                )

            [close] => Array
                (
                    [price] => 169.31
                    [time] => 1533240121638
                )

            [high] => 169.72
            [low] => 166.755
        )

)

**Comment by evancarter-iex** [comment]
With IEXCloud this should occur around 4am-5am ET time.
https://iexcloud.io
