### ISSUE TITLE
What date time type is used for fields in JSON quotes such as latestUpdate? 

### ISSUE THREAD

**Issue by idurucz** [iexg/IEX-API#446]
## Summary
What date time type is used for fields in quotes such as latestUpdate? 

## Details
I am trying to convert values from the quote JSON to something human readable, but unable to figure out what type I am looking at.
For example:
### `"latestUpdate":1533651872864`
...this looks like a **`long`** for me.
If I use the following constructor from java's Date class: **`Date(long)`**
...then I get 2018-24-07 03:24:32 (using yyyy-mm-dd hh:mm:ss SimpleDateFormat) which is certainly not right!

### Date/time of issue
2018/Aug/07 16:09

### API URL
https://api.iextrading.com/1.0/stock/tsla/quote

**Comment by MaxWT** [comment]
Hey, I've just tried to run the same request and it looks like the date is in milliseconds format. You can use moment js to convert this into the readable date:

moment(1533651872864).format('DD MMM YYYY hh:mm a') or
moment.unix(1533651872864/1000).format('DD MMM YYYY hh:mm a')

**Comment by duruczi** [comment]
Thanks. What result did that give you? Just so I know what to expect if I manage to test above for the same number.

**Comment by MaxWT** [comment]
You can basically use any formatting that is described in moment js docs here: https://momentjs.com/docs/ -- so according to the docs, if you implement the same method that I've mentioned above, you should get something like '7 Aug 2018 11:54 am'.

**Comment by duruczi** [comment]
Thanks. I'm still trying to figure out another way to convert it because the corporate application where I need to do this doesn't allow anithing other than java.* classes really.

**Comment by duruczi** [comment]
Sorted. Such a schoolboy error on my end! The type is indeed long millis but where I messed it up is not the conversion/paring but just the display format for the SimpleDateFormat. I have used 'mm' instead of 'MM' for month and so got 24 by some reason instead of 08 (August).
The actual return of above long millis value is: 2018-08-07 03:24:32
