### ISSUE TITLE
Question: Is there a way to get index values like DOW/NASDAQ/S&P 500 ?

### ISSUE THREAD

**Issue by TheMightyPope** [iexg/IEX-API#447]
I couldn't quite figure out if IEX supports retrieving date form the major indexes, like DOW/NASDAQ/S&P 500 etc. I searched here, and in the developer documentation.

If so, how?

Sorry, I'm not sure how to mark this as a 'question', hope I did it right.

**Comment by joshuablackburn-iex** [comment]
We are unable to distribute index data.  The index data providers have this locked down and require every data consumer to have a direct contract with them and pay large fees.  Using the ETF is the best way for now.

**Comment by dblock** [comment]
@joshuablackburn-iex Ran into this trying to get DWCPF. Is there a chart/documentation somewhere on what is supported and what is not?
