### ISSUE TITLE
Dividends always lagging behind

### ISSUE THREAD

**Issue by elisag1990** [iexg/IEX-API#449]
I was looking at dividends and they seem to always be lagging behind, For example, for MSFT and AAPL the endpoint is still returning the March one as the latest when clearly a more recent dividend was issued in June.

Is this the correct behavior for the endpoint?

**Comment by kotarofujita** [comment]
This has been an issue for a while now. Would be nice to get some kinda update for this.

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
