### ISSUE TITLE
Financials API - request for more data & questions

### ISSUE THREAD

**Issue by shuwnyuantee** [iexg/IEX-API#45]
Sorry for opening various issues. I am from [JStock](https://play.google.com/store/apps/details?id=org.yccheok.jstock.gui&hl=en) team, same as @yccheok . 

Currently with `financials` api, I am able to show income chart (last 4Q) in our app, outcome as below:

![jstockincomechart](https://user-images.githubusercontent.com/614382/31699652-9f0736a8-b3f6-11e7-8a1c-cdcfe3e447bd.png)

However, I would also like to show charts similar to below:

![4yearsrevenue](https://user-images.githubusercontent.com/614382/31699565-2bf77394-b3f6-11e7-9868-eaddaf65fff6.png)

![cashflowtiny](https://user-images.githubusercontent.com/614382/31699765-689ebebe-b3f7-11e7-9a5e-a0bac30c1e00.png)

So I would like to request for additional data:

```
1) Total Revenue for last 5 years (to calculate 4 years of YOY growth rate)
2) Operating, Investing, Financing CashFlow for last 4Q
```

Another question regarding `Total Debt`. Sometimes this field is `null` (below screenshot). In this case, it means the `data is unavailable` or `total debt = 0`?

<img width="308" alt="debtnull" src="https://user-images.githubusercontent.com/614382/31700038-3fbb41f0-b3f9-11e7-934f-942df96ae912.png">

Sorry to bother, thanks & really appreciate IEX generosity.

**Comment by joshuablackburn-iex** [comment]
If we have null values it will generally mean we do not have data for that field.  We prefer null since a value of 0 is valid.

**Comment by joshuablackburn-iex** [comment]
We are also working on the annual view of financials.

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex  Thanks & appreciate your help. Looking forward to annually financials data 👍

**Comment by dwhittemore** [comment]
Adding in another vote to get annual financials, thank you!

**Comment by joshuablackburn-iex** [comment]
Annual financials are available.  Here is an example:
https://api.iextrading.com/1.0/stock/aapl/financials?period=annual

Docs will be updated.
