### ISSUE TITLE
changePercent issue

### ISSUE THREAD

**Issue by crino85** [iexg/IEX-API#450]
## Summary
changePercent issue not shown correctñy

## Details
I'm using your API to get some stock prices but I realized the "changePercent" field is not in % format and I shall multiplicate x100 the result. However, in your web the changePercent is shown correctly.

### Date/time of issue
08/09/2018

### API URL
API: https://api.iextrading.com/1.0/stock/adbe/quote/
WEB: https://iextrading.com/apps/stocks/ADBE

### What you expected to happen
"changePercent" should be shown in the same format that is shown in the web.

### What actually happened
"changePercent" at API is not in the % format.

**Comment by joshuablackburn-iex** [comment]
Please refer to our documentation to see how to get the format you want:
https://iextrading.com/developer/docs/#quote

You need to use the displayPercent parameter.  That is what we use for the website.
