### ISSUE TITLE
IEX-API: the api calls doesn't work when the stock symbol has a dot.

### ISSUE THREAD

**Issue by wandakpli** [iexg/IEX-API#451]
## Summary
The api calls doesn't work when the stock symbol has a dot.
e.g. for symbol: MFR.UN

### Date/time of issue
Aug 9, 2018

### API URL
https://api.iextrading.com/1.0/stock/MFR.UN/quote

### What you expected to happen
It should return all the details of the quote like other symbol without the dot.

### What actually happened
received an error: Unknown symbol

**Comment by wandakpli** [comment]
What is the workaround for symbol with dot?

**Comment by joshuablackburn-iex** [comment]
The API does support symbols with dots.  The symbol you are using is not in our list of supported symbols.  Please be sure to refer to our symbol list:  https://iextrading.com/developer/docs/#symbols

Example:  https://dev.iextrading.com/api/1.0/stock/brk.a/quote

**Comment by wandakpli** [comment]
How about the symbol CJR.B

**Comment by evancarter-iex** [comment]
Please check the symbol list. It has a list of our current symbols.
