### ISSUE TITLE
"extended" data from /stock/aapl/quote api covers only PART of Extended-hours trading

### ISSUE THREAD

**Issue by rayjiang2013** [iexg/IEX-API#452]
## Summary
"extended" data from /stock/aapl/quote api covers only PART of Extended-hours trading: currently, it only covers 8:00 - 9:30 and 16:00 - 17:00. Can we extend that to 4:00 a.m. to 9:30 a.m. ET and 4:00 p.m. to 8:00 p.m. ET, especially for after market.

## Details
Pre-market trading occurs from 4:00 a.m. to 9:30 a.m. ET, although the majority of the volume and liquidity come to the pre-market at 8:00AM ET.After-hours trading on a day with a normal session occurs from 4:00 p.m. to 8:00 p.m. ET. 
### Date/time of issue
always

### API URL
/stock/aapl/quote

### What you expected to happen
the response should also give data for 4:00 a.m. to 8:00 a.m. ET and 5:00 p.m. to 8:00 p.m. ET, especially for after market.

### What actually happened
the "extended" data only covers 8:00 - 9:30 and 16:00 - 17:00

### Other Information (sample code, links, etc.)
None

**Comment by evancarter-iex** [comment]
Fixed in iexcloud.io
