### ISSUE TITLE
Financials totalLiabilities is always null

### ISSUE THREAD

**Issue by abeatte** [iexg/IEX-API#453]
## Summary
When retrieving a stocks financials totalLiabilities field is always null. 
Docs state it should be present yet any stock I try I see a null value
https://iextrading.com/developer/docs/#financials

### Date/time of issue
Aug 9th 2018

### API URL
https://api.iextrading.com/1.0/stock/[stock ticker]/financials

### What you expected to happen
I expect to have a valid number for a stocks totalLiabilities

### What actually happened
No totalLiabilities values (for any stock) are being returned. The value is always null
{
reportDate: "2018-05-31",
...
totalLiabilities: null,
...
}

**Comment by evancarter-iex** [comment]
This is fixed in Iexcloud. https://iexcloud.io
