### ISSUE TITLE
Financials does not give Goodwill or Intangible Assets values

### ISSUE THREAD

**Issue by abeatte** [iexg/IEX-API#455]
## Summary
The data returned from the Financials endpoint is missing Goodwill and Intangible Assets. 

### API URL
https://iextrading.com/developer/docs/#financials
https://api.iextrading.com/1.0/stock/rad/financials

### What you expected to happen
There is so much data delivered by the financials endpoint. 
It is just missing Goodwill and Intangible Assets. These are things easily found on the balance sheet for any company. 

### What actually happened
financial data was returned but was missing Goodwill and Intangible Assets

**Comment by abeatte** [comment]
Hey @joshuablackburn-iex, any idea on an ETA for this feature? It'd be super helpful. B-)

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557 for future updates.

**Comment by arjd** [comment]
Will this request make it into IEX Cloud?

**Comment by joshuablackburn12345** [comment]
These are available in IEX Cloud under Balance Sheet

**Comment by joshuablackburn-iex** [comment]
This is available from IEX Cloud under Balance Sheet.
