### ISSUE TITLE
Upcoming IPO API returns different amount of rawData and viewData fields

### ISSUE THREAD

**Issue by uc2pac** [iexg/IEX-API#456]
## Summary
Upcoming IPO API returns not equal rawData and viewData fields

### Date/time of issue
08/11/2018 - 1:30PM EDT

### API URL
/stock/market/upcoming-ipos

### What you expected to happen
I expected viewData should contain same amount of upcoming IPO companies as rawData. Otherwise there is no sense in viewData

### Other Information (sample code, links, etc.)
<img width="1085" alt="screen shot 2018-08-11 at 1 33 25 pm" src="https://user-images.githubusercontent.com/4955533/43994472-36082d24-9d6b-11e8-814f-d5517dc03106.png">

**Comment by joshuablackburn-iex** [comment]
Fixed and deployed.
