### ISSUE TITLE
Stocks: IEX Short Interest List data is missing

### ISSUE THREAD

**Issue by friendchristoph** [iexg/IEX-API#458]
## Summary
After trying a number of tickers and market, there appears to be no short interest data in the IEX Short Interest List API

## Details
API returns an empty array

### Date/time of issue
8/14 @ 5pm

### API URL
https://iextrading.com/developer/docs/#iex-short-interest-list
https://api.iextrading.com/1.0/stock/msft/short-interest
https://api.iextrading.com/1.0/stock/market/short-interest

### What you expected to happen
Receive short interest data

### What actually happened
Received no data

### Other Information (sample code, links, etc.)
Sample data is still available: https://api.iextrading.com/1.0/stock/market/short-interest/sample

**Comment by joshuablackburn-iex** [comment]
This has been answered in #205 #416 #448 

IEX is a stock exchange, and we are approved to list companies.  We currently do not have a company listed, but when we do list a company, we have a regulatory obligation to provide this information for symbols listed **only** on IEX.  To see which symbols are listed on IEX, please reference https://iextrading.com/developer/docs/#iex-listed-symbol-directory

@ Everyone:  How can we improve our documentation to make this more clear?  Maybe include a link to the listed symbol directory to show which symbols we currently support?

**Comment by friendchristoph** [comment]
My mistake, must have only searched open issues. Apologies for the duplicate.

Linking to the IEX listed symbol directory under short interest would be helpful to show supported symbols. Maybe a link under 'IEX-listed securities' that directs to the symbol directory?

Thanks for your help.
