### ISSUE TITLE
How to get a collection with tag "Metals & Mining"

### ISSUE THREAD

**Issue by leedstyh** [iexg/IEX-API#459]
Hi,

Tag that contains `&` always return an error message: `xxx is not allowed`.

Thanks

**Comment by leedstyh** [comment]
Also @joshuablackburn-iex , `filter` does not work for collection endpoint: https://api.iextrading.com/1.0/stock/market/collection/tag?collectionName=Computer%20Hardware&filter=symbol,latestPrice still returns all the fields.

**Comment by jr-graham** [comment]
@leedstyh Try to query for Metals and Mining using collectionName=Metals%20%26%20Mining.

**Comment by leedstyh** [comment]
Thanks @jr-graham ,that works well, so we need to change `&` to `%26`.

And since the `filter` issue is not fixed, so I leave this open, is that OK @joshuablackburn-iex ?

**Comment by joshuablackburn-iex** [comment]
@leedstyh Yes, that works.

**Comment by evancarter-iex** [comment]
Closing. If this is an issue in https://iexcloud.io please create a new issue.
