### ISSUE TITLE
Is it possible to provide day high / day low price for quote API

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#46]
Hi,

For quote API https://iextrading.com/developer/docs/#quote

https://api.iextrading.com/1.0/stock/aapl/quote

Is it possible to provide day high / day low price in the respond?

Thank you.

**Comment by joshuablackburn-iex** [comment]
This is almost complete.

**Comment by rottla** [comment]
Hi Josh, Any rough estimate on when would high/low would be available? Thanks

**Comment by BullMarket** [comment]
^
What' Rottla said. It would be great if we can get an ETA. I understand that beggars (us) can't be choosers. We appreciate what  you are doing. Thanks.

**Comment by mburns1** [comment]
Yes, the day's high and low would be a great addition to both the HTTP and websocket.

**Comment by rottla** [comment]
Saw in issue thread #69 that OHLC is now in Test environment. Great. Josh, If there is a way you want us to beta test, please let us know !!

**Comment by BullMarket** [comment]
Hi @joshuablackburn-iex , I'm wondering when can we expect to get High/Low/Volume/VWAP added to quote endpoint - https://api.iextrading.com/1.0/stock/aapl/quote ? If there is a test end point where it's available please share that as well. Thank you!

**Comment by rdemuth** [comment]
And when you do this, will the change apply to the quote that comes at the beginning of the 'batch' api?  That would be useful also.

**Comment by ModelsRUs** [comment]
Hi 28 days ago, this was noted as "almost complete". Hate to be a nag, but any ETA?
Thanks much!

**Comment by rottla** [comment]
Yup, waiting eagerly

**Comment by evancarter-iex** [comment]
We appreciate the enthusiasm. When we have updates to this, we will post them here. In the meantime I am locking this thread.

**Comment by joshuablackburn-iex** [comment]
Open High Low and Close are now are available from /quote.  Documentation update to follow.
