### ISSUE TITLE
Broken logo link received for numerous tickers

### ISSUE THREAD

**Issue by boknows** [iexg/IEX-API#460]
## Summary

Very much like Issue #40, I've noticed that the logo for ZION comes back with a googleapis error and is a broken link picture.  The API returns this link as the logo: https://storage.googleapis.com/iex/api/logos/ZION.png which is broken.

**Comment by boknows** [comment]
Tickers also effected: AFL, ARE, BF.B, KSU, HBI, PNW, SPY, SBAC,

**Comment by evancarter-iex** [comment]
Most of these are fixed.
