### ISSUE TITLE
Bug when requesting types dividend and splits

### ISSUE THREAD

**Issue by bartclaeys** [iexg/IEX-API#461]
When specifying `types` with `quote`, `dividend` & `split`, it seems impossible to get AND dividend AND split data at the same time.

The following for ticker `SBUX` successfully retrieves `quote` and `splits`, but not `dividends`:

[https://api.iextrading.com/1.0/stock/market/batch?symbols=SBUX&types=quote,splits,dividends&range=5y](https://api.iextrading.com/1.0/stock/market/batch?symbols=SBUX&types=quote,splits,dividends&range=5y)

The following for the same ticker successfully retrieves `quote` and `dividends`, but not `splits`:

[https://api.iextrading.com/1.0/stock/market/batch?symbols=SBUX&types=quote,dividends,splits&range=5y](https://api.iextrading.com/1.0/stock/market/batch?symbols=SBUX&types=quote,dividends,splits&range=5y)

Workaround is sending two requests and combining the results.
The difference between two endpoints is the order of the types: `splits,dividends` vs `dividends,splits`. Further examination shows that when adding more types, the problem remains: `quote,chart,news,splits,dividends` vs `quote,chart,news,dividends,splits`.

Summarized, when type `dividend` is being requested, it boots `splits` and the other way around.

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud. https://iexcloud.io
