### ISSUE TITLE
Eventing of new listings, delistings and acquisitions.

### ISSUE THREAD

**Issue by tomwheyprotein** [iexg/IEX-API#462]
## Summary
I would like to be able to subscribe to events, which include those events triggered by new listings, delistings and acquisitions.  Does the iex-api allow third party developer clients and servers to listen for these api events?

**Comment by bartclaeys** [comment]
It doesn't look like. I've been looking for this info as well, and it does not seem readily available.

Two resources:
https://listingcenter.nasdaq.com/IssuersPendingSuspensionDelisting.aspx
https://www.theonlineinvestor.com/mergers/

**Comment by mukster** [comment]
I, too, would like to query on a daily basis for corporate events such as mergers, acquisitions, and spin-offs.

**Comment by timpaine-iex** [comment]
IEX cloud has `upcoming-events`
