### ISSUE TITLE
API does not return latest dividend date

### ISSUE THREAD

**Issue by bartclaeys** [iexg/IEX-API#463]
When trying to retrieve dividend data, I don't get the latest date.

API call:

> https://api.iextrading.com/1.0/stock/market/batch?symbols=CHL&types=dividends&range=5y

Shows 08/29/2017 as latest dividend date, while IEX's page shows 05/23/2018 as latest date:

> https://iextrading.com/apps/stocks/CHL

Does IEX's site runs on a different API version?

**Comment by elisag1990** [comment]
Known problem. I also reported the issue here https://github.com/iexg/IEX-API/issues/449.

**Comment by JohnRobson** [comment]
## Summary

Seems that the dividends are outdated.

## Details

MSFT paid dividends Aug 15, 2018 and also May 16, 2018.
https://www.nasdaq.com/symbol/msft/dividend-history
But in API, there is only Feb 14, 2018

Same with AAPL (and maybe all other stocks)
https://www.nasdaq.com/symbol/aapl/dividend-history

### API URL

https://api.iextrading.com/1.0/stock/msft/dividends/1y
https://api.iextrading.com/1.0/stock/aapl/dividends/1y

**Comment by JohnRobson** [comment]
Related to #463

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
