### ISSUE TITLE
History pricing api from a specific date is not working

### ISSUE THREAD

**Issue by appagg** [iexg/IEX-API#464]
## Summary
History pricing api from a specific date is not working. 

Also, it'd be nice to support range by specifying dates, e.g

https://api.iextrading.com/1.0/stock/market/batch?types=chart&symbols=aapl,mu&start=20180801&end=20180813

## Details
https://api.iextrading.com/1.0/stock/aapl/chart/data/20180129 returns an empty array
### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/data/20180129

### What you expected to happen
return the history pricing for that date.

### What actually happened
empty

**Comment by SeamusBoyle** [comment]
@appagg The data isn't available that far back. Retention is a few months last time I checked.

**Comment by evancarter-iex** [comment]
We only retain the last 30 days (roughly).
