### ISSUE TITLE
/stats detail

### ISSUE THREAD

**Issue by robert-heath** [iexg/IEX-API#466]
## Summary
The time-frame for various stats is ambiguous. Some data (revenue, EBITDA e.g.) appears to be quarterly (and stale) while other data appears to be annual aligned with latestEPSDate, or possibly the most recent fiscal year. 

## Details
stats for IMMR returns:

EPS Date: 2017-12-31
EBITDA:     -5.2
Revenue:     11.9
(EBITDA and revenue in millions)

The EBITDA and revenue numbers appear to be for the quarter ended 2017-09-30. 

Would it be possible to include a field (fields?) that clarify the timeframe for the various income statement and balance sheet items?

### Date/time of issue
2018-08-19 13:34 PDT -0700

### API URL
https://api.iextrading.com/1.0/stock/immr/stats'

### What you expected to happen
Return stats for most recent 10-K or 10-Q

### What actually happened
Returns stats for various periods

**Comment by evancarter-iex** [comment]
Closing. If this is an issue in https://iexcloud.io please create a new issue.
