### ISSUE TITLE
totalLiabilities endpoint returning "null"

### ISSUE THREAD

**Issue by seankongery** [iexg/IEX-API#467]
## Summary
Hello. When hitting the totalLiabilities endpoint, I am receiving a "null" value for each company I've tried. I see that a couple of people have reported this issue, but I haven't seen a response on either of the tickets. Is this an issue that is being actively investigated/worked on?

## Details
Tested 3M, CAT, AAPL, PCTI, and a few others

### Date/time of issue
Sunday, August 19th

### API URL
https://iextrading.com/developer/docs/#financials

### What you expected to happen
I was expecting the endpoint to return a number.

### What actually happened
I received a "null" value

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
