### ISSUE TITLE
Some symbols not recognized

### ISSUE THREAD

**Issue by seattlevinay** [iexg/IEX-API#468]
## Summary
Symbols that worked with APIVantage for quotes not working with IEX

## Details

The following is the log of my software showing the symbols:

(*Couldn't download BHYIX*)
(*Couldn't download DFSTX*)
(*Couldn't download HHDS*)
(*Couldn't download IARE*)
(*Couldn't download ODVIX*)
(*Couldn't download PCRIX*)
(*Couldn't download PIFZX*)
(*Couldn't download PRFDX*)
(*Couldn't download PRRDX*)
(*Couldn't download PTTRX*)
(*Couldn't download QCILRX*)
(*Couldn't download TCIEX*)
(*Couldn't download TCYIX*)
(*Couldn't download TIBDX*)
(*Couldn't download TIIEX*)
(*Couldn't download TIGRX*)
(*Couldn't download TILVX*)
(*Couldn't download TIMVX*)
(*Couldn't download TRPWX*)
(*Couldn't download VBIPX*)
(*Couldn't download VIGIX*)
(*Couldn't download VIIIX*)
(*Couldn't download VISVX*)
(*Couldn't download VIVIX*)
(*Couldn't download VSGIX*)
(*Couldn't download VDIGX*)
(*Couldn't download VEMAX*)
(*Couldn't download VEUSX*)
(*Couldn't download VGSNX*)
(*Couldn't download VMFXX*)
(*Couldn't download VIGAX*)
(*Couldn't download VIGRX*)
(*Couldn't download VITSX*)
(*Couldn't download VWAHX*)
(*Couldn't download VIPSX*)
(*Couldn't download VWIGX*)
(*Couldn't download VTRIX*)
(*Couldn't download VIMAX*)
(*Couldn't download VPADX*)
(*Couldn't download VMVAX*)
(*Couldn't download VGSLX*)
(*Couldn't download VGSIX*)
(*Couldn't download VFSTX*)
(*Couldn't download VSGAX*)
(*Couldn't download VISGX*)
(*Couldn't download VGTSX*)
(*Couldn't download VTHRX*)
(*Couldn't download PRRIX*)

### Date/time of issue

8/23/18 9:45PM

### API URL

https://api.iextrading.com/1.0/stock/symbol/quote

### What you expected to happen

I expected to get the normal response for the quote of a known symbol 

### What actually happened

return value for each one of above symbols is "Unknown symbol"

**Comment by wbhern** [comment]
In the current version of the API (1.0), IEX does not provide mutual fund quotes/data. Support is anticipated in the 2.0 version of the API due this fall.

**Comment by joshuablackburn-iex** [comment]
Coming in v2

**Comment by johnatkinson4857** [comment]
Would really be helpful to be able access mutual fund quotes with the iex API. Do you have a date estimate of when it might be ready?

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
