### ISSUE TITLE
Chart Data Not Returning Complete Results

### ISSUE THREAD

**Issue by dennismarksbury** [iexg/IEX-API#469]
## Summary
When requesting chart data, some data fields are missing.

## Details

When accessing historical data, "open" and "close" fileds are not provided at 9:33AM.  Also, high/low values are often -1 and volume is frequently 0.  Here is a segment of the returned JSON result set:

{
        "date": "20180821",
        "minute": "09:33",
        "label": "09:33 AM",
        "high": -1,
        "low": -1,
        "average": -1,
        "volume": 0,
        "notional": 0,
        "numberOfTrades": 0,
        "marketHigh": 57.27,
        "marketLow": 57.1,
        "marketAverage": 57.182,
        "marketVolume": 27994,
        "marketNotional": 1600760.8422,
        "marketNumberOfTrades": 163,
        "marketOpen": 57.2,
        "marketClose": 57.1,
        "changeOverTime": null,
        "marketChangeOverTime": -0.0014145259591707728
    }

Most of the data DOES contain open/close, but these fields seem to be sporadically not listed.

### Date/time of issue

8/24/2018 5:00PM EST

### API URL

https://api.iextrading.com/1.0/stock/roku/chart/date/20180821

### What you expected to happen

Consistent data sets

**Comment by dennismarksbury** [comment]
Attached is the raw data returned from the API

[roku_20180821.json.txt](https://github.com/iexg/IEX-API/files/2319916/roku_20180821.json.txt)

**Comment by joshuablackburn-iex** [comment]
This happens when IEX has no trades during the minute.
