### ISSUE TITLE
OHLCV data for all stocks in 1 call?

### ISSUE THREAD

**Issue by Thordin** [iexg/IEX-API#47]
Wondering if it would be possible instead of having to aggregate the data ourselves by spamming top every second (which doesn't have volume) or doing market/batch 100 symbols at a time (and doesn't have high or low).

market/previous is closest to what I am looking for but it only returns the previous day even when the markets are closed today and there's no intraday option.

https://api.iextrading.com/1.0/stock/market/previous

**Comment by leedstyh** [comment]
yeah, something like `https://api.iextrading.com/1.0/stock/market/current` to return current trading day's real-time OHLCV data for all stocks would be great

**Comment by joshuablackburn-iex** [comment]
This is in the works, and close to completion.

**Comment by BullMarket** [comment]
@leedstyh @joshuablackburn-iex this is exactly what I'm looking for as well. One call would return OHLCV & vwap for all active stocks.

**Comment by BullMarket** [comment]
@joshuablackburn-iex @chrisnager-iex @evancarter-iex sorry to spam tag everyone but I'm really looking forward to this. I'd appreciate if there is an update on this enhancement or when can we potentially expect it. Thank you very much for what you do guys!

**Comment by joshuablackburn-iex** [comment]
I know this is high demand item.  It is being code reviewed, but with the holiday week, it might not make it to production until next week.  Thanks for the patience on this one.

**Comment by BullMarket** [comment]
@joshuablackburn-iex That sounds great. Appreciate it for fast tracking this enhancement.

**Comment by fimmugit** [comment]
Any update yet?

**Comment by GitBevo** [comment]
At the risk of sounding like I am piling on, I too am greatly interested in this feature and would appreciate a update on it's status.

Thanks much, for the API and the chance to express enhancements.
Gary

**Comment by joshuablackburn-iex** [comment]
Open High Low and Close are now are available from /quote.  Documentation update to follow.  This is still limited by 100 per call at this time.

**Comment by rompish** [comment]
Are you planning to make same data as "market/previous" available but for **current** day or at least right after market close? I am personally interested in trading statistics - volume and vwap price - which are presented perfectly in market/previous in a single call for all symbols.

Thank you

**Comment by JimLynchCodes** [comment]
sad that no one from iex has commented here in years... I too am curious how to do this. 🤔
