### ISSUE TITLE
Option Quotes

### ISSUE THREAD

**Issue by ameliabob** [iexg/IEX-API#471]
## Summary
Can I get quotes on Options or will I be able to?

## Details
I cannot get a return on a quote using "FNKO181116C00012500" as a symbol
### Date/time of issue
8/28/2018 6:31am

### What you expected to happen
A return the same as a normal stock would return

**Comment by evancarter-iex** [comment]
@ameliabob This has been deployed on iexcloud. https://iexcloud.io or https://iexcloud.io/docs/api/#options
