### ISSUE TITLE
Data consistency issue: Fidelity or IEX correct?

### ISSUE THREAD

**Issue by charleswg** [iexg/IEX-API#475]
## Summary
Huge transaction volume differences

## Details

Volume on 10:24 8/29/2018 for GLD:
IEX: 146,741
Fidelity: 9,935

Volume on 10:25 8/29/2018 for GLD:
IEX: 1,112,377
Fidelity: 7,200

### Date/time of issue
timestamp volume difference 10:25 8/29/2018

IEX Data download on 8/31/2018
Fidelity Data download on 8/31/2018

### API URL
https://api.iextrading.com/1.0/stock/GLD/chart/date/20180829/?filter=date,minute,marketClose,marketHigh,marketLow,marketOpen,marketVolume

### What you expected to happen
Volume after two days should be market wide?

### What actually happened
Huge inconsistency. Who's right or wrong?

### Other Information (sample code, links, etc.)
Fidelity download directly from active trader pro.

**Comment by schlambe4** [comment]
The first thing to determine is the time assigned to the first bar of RTH.  ThinkOrSwim calls it 9:30, TradeStation says it's 9:31.  The IEX-API data shows large volume at 9:30, so it's reasonable to assume that is the first bar of RTH for that feed.  ThinkOrSwim and TradeStation report the same series of volume numbers (making the time allowance described above)  with 10:24 reported at 9935 and 10:25 at 7200 shares.  It's possible that IEX is aggregating volumes from more exchanges than the retail brokers, hard to know without digging further.

**Comment by charleswg** [comment]
I tend to agree actually. The whole day for GLD the IEX volume is higher than FI but most of the time  IEX is just 10%-20% higher. I think IEX is aggregate across exchanges.  FI has a rather large portfolio and GLD isn't higly traded.

**Comment by joshuablackburn-iex** [comment]
We verified and looks like our data was correct for these dates.  Please let us know if you continue to experience this issue.
