### ISSUE TITLE
Key Stats - Incorrect Short Data

### ISSUE THREAD

**Issue by rajpatelukyahoo** [iexg/IEX-API#477]
## Summary
ShortDate and ShortInterest information inaccurate for some stocks and etf.

## Details
Some of the equities and some etf's reporting  historical / outdated  information
"shortInterest":199117351,"shortDate":"2013-01-15"

### Date/time of issue

09/05/18 

### API URL
https://api.iextrading.com/1.0/stock/QQQ/stats

### What you expected to happen

It should display current information or null or  blank 

### What actually happened
It displays historical / outdated information

**Comment by joshuablackburn-iex** [comment]
We may need to remove this information.  Nasdaq has recently changed their terms.

**Comment by peterdavies299** [comment]
Short interest data is inaccurate for many company, like AAPL, FB. Could you please correct them? Thank you very much!

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557 for updates to this issue and others.
