### ISSUE TITLE
Endpoint returning only latest price, high, low, volume and a timestamp?

### ISSUE THREAD

**Issue by Stefama2020** [iexg/IEX-API#478]
I believe a fundamental endpoint is still missing, one that returns current price together with day high, low, volume and a timestamp for the current price. It would be great if it were a "market" kind of endpoint (one that returns this data for all symbols).

Anything of this kind coming with v2.0 apis ?

**Comment by McQgit** [comment]
@elisag1990   Can't you just use the 'filter' ?  Example:

`(...)stock/market/batch?symbols=MSFT&types=quote&filter=latestPrice,latestVolume,high,low,latestTime`

**Comment by timpaine-iex** [comment]
closing as stale
