### ISSUE TITLE
Recent symbol change QINC -> DDIV no historical data merge

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#479]
## Summary
symbol change
QINC -> DDIV	 effective 09/06/2018

## Details
Recent symbol change QINC -> DDIV no historical data merge
### Date/time of issue

9/7/2018

### API URL

https://api.iextrading.com/1.0/stock/qinc/chart/2y
https://api.iextrading.com/1.0/stock/ddiv/chart/2y

### What you expected to happen

qinc historical data to be merged with new symbol ddiv data

### What actually happened

qinc now has only 1 day of historical data
ddiv has 2 days of data

**Comment by StockConsultant** [comment]
same  with recent symbol change on 

YDIV to  FID on 08/30/2018

**Comment by joshuablackburn-iex** [comment]
I will have to look into this, but if the symbol change is an underlying change in the Issue record, then we do not have a way to merge at this time. I will verify the corporate action.

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
