### ISSUE TITLE
MHH historical split on 8/24 not performed

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#480]
## Summary

No split adjust for prices on MHH from 8/24 onward for historical data. Volume has been adjusted.

## Details
No split adjust for prices on MHH from 8/24 onward for historical data. Volume has been adjusted.

### Date/time of issue

9/7/2018

### API URL

https://api.iextrading.com/1.0/stock/mhh/chart/2y?format=csv
https://api.iextrading.com/1.0/stock/mhh/chart/2y?

### What you expected to happen

historical prices to be split adjusted

### What actually happened

no split adjustment to prices

### Other Information (sample code, links, etc.)

8/23/2018 | 20.24 | 20.45 | 19.7824 | 20.04 | 10962 | 5481 | -0.06 | -0.299 | 20.2293 | 23-Aug | 1.672
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
8/24/2018 | 19.97 | 20.899 | 19.7723 | 20.3 | 18778 | 9389 | 0.26 | 1.297 | 20.2996 | 24-Aug | 1.706667
8/27/2018 | 10 | 10.3 | 9.5 | 10.16 | 36940 | 36940 | -10.14 | -49.951 | 9.9339 | 27-Aug | 0.354667
8/28/2018 | 10.16 | 10.47 | 9.649 | 10.235 | 26359 | 26359 | 0.075 | 0.738 | 10.1757 | 28-Aug | 0.364667

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
