### ISSUE TITLE
API support to query available ticker symbols supported by api?

### ISSUE THREAD

**Issue by Kph1108** [iexg/IEX-API#481]
## Summary
Looking for a way to access all available ticker symbols that are supported by the api.

I know they are listed here:
https://iextrading.com/trading/eligible-symbols/

but I'm looking to for api support to pull these values.

**Comment by SeamusBoyle** [comment]
@Kph1108 You can get the symbols list in JSON, refer to the [Reference Data](https://iextrading.com/developer/docs/#reference-data) section of the docs.

**Comment by Kph1108** [comment]
Wow can't believe I missed that. Still getting familiar with the API. Thanks!!

**Comment by mutluit** [comment]
Suggestion / Proposal:

It would be good if back issues of the daily symbols list could be get too, ie. using an optional date param (YYYY-MM-DD) in the request.

Thx
