### ISSUE TITLE
Feature Request: Support CSV format on previous endpoint

### ISSUE THREAD

**Issue by pbbadenhorst** [iexg/IEX-API#482]
## Summary

The data retrieved from the /stock/market/previous endpoint returns invalid data if format=csv is specified.

I'm was using the stock/market/previous endpoint and retrieved json data successfully (both with the format parameter missing and specified as json).
I would however like to retrieve csv data using ?format=csv as an optimization.

Looking at the api documentation at the parameter 'format' is not specified as supported.
[https://iextrading.com/developer/docs/#previous](https://iextrading.com/developer/docs/#previous)

But when trying it like below, the data seems to almost work and just needs some serialization logic.
[https://api.iextrading.com/1.0/stock/market/previous?format=csv](https://api.iextrading.com/1.0/stock/market/previous?format=csv)

### Date/time of issue

2018-09-12 11:00 AM PDT

### API URL

Works returning json
https://api.iextrading.com/1.0/stock/market/previous
https://api.iextrading.com/1.0/stock/market/previous?format=json

Does not work
https://api.iextrading.com/1.0/stock/market/previous?format=csv

### What you expected to happen

I expected the endpoint to either not work at all with
- either blank data or
- an indication that the csv format is not supported or
- (preferred) the data in the format like the below (ellipses used to indicate additional rows):

symbol,date,open,high,low,close,volume,unadjustedVolue,change,changePercent,vmap
AAL,2018-09-11,39.33,40.305,39.065,40.18,5863979,5863979,0.75,1.902,39.9827
ABBV,2018-09-11,93.72,93.733,92.88,93.18,2638845,2638845,-0.64,-0.682,93.2739
ABC,2018-09-11,87.25,87.81,83.96,84.1,2498721,2498721,-4.23,-4.789,84.947
...

### What actually happened

The data was returned as two lines of text like below (ellipses used to indicate additional text of a long line)

AAL,ABBV,ABC,AAWW,...
[object Object],[object Object],[object Object],[object Object],...

**Comment by evancarter-iex** [comment]
This is supported on https://iexcloud.io
