### ISSUE TITLE
What does extendedPrice return during regular trading hours?

### ISSUE THREAD

**Issue by kzaveri16** [iexg/IEX-API#484]
First, thank you for this superawesome service ! I am a huge fan of Brad since Michael Lewis's Flash Boys. 
Quick question of ExtendedPrice in particular and extended variables in general. What do they return during regular trading hours?

**Comment by joshuablackburn-iex** [comment]
'extended' variables are used to represent data from 8am ET to the open at 9:30 ET, and from the close at 4pm ET to our trading system shut down at 5pm ET.
