### ISSUE TITLE
No split adjust for prices on INFY for 9/11

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#485]
## Summary

No split adjust for prices on INFY for 9/11 onward

## Details

No split adjust for prices on INFY from 9/11 onward for historical data. Unadjusted volume for split hint starts on incorrect day 9/10, probably from use of erronous 3rd party data, Briefing? Use Nasdaq or Fidelity for correct split dates.

### Date/time of issue

9/13/2018

### API URL

https://api.iextrading.com/1.0/stock/INFY/chart/2y?format=csv

### What you expected to happen

historical prices to be split adjusted

### What actually happened

historical prices not split adjusted, unadjusted volume (split hint) starts on incorrect split date, probably from incorrect 3rd part data source for splits. 

### Other Information (sample code, links, etc.)

9/10/2018 | 20.76 | 20.96 | 20.595 | 20.7 | 8940582 | 4470291
-- | -- | -- | -- | -- | -- | --
9/11/2018 | 20.72 | 21.11 | 20.7 | 20.97 | 4336312 | 4336312
9/12/2018 | 10.57 | 10.65 | 10.525 | 10.55 | 4392513 | 4392513

Note: Split sources from Briefing (and some other 3rd party sources) note INFY split date to be 9/10 which is incorrect
https://www.briefing.com/investor/calendars/stock-splits/2018/9/

(briefing has been incorrect for many split dates and should not be considered a reliable split source)

Correct 3rd part sources state split dates as 9/11 are

https://www.nasdaq.com/markets/upcoming-splits.aspx

https://eresearch.fidelity.com/eresearch/conferenceCalls.jhtml?tab=splits&begindate=9/11/2018

**Comment by joshuablackburn-iex** [comment]
We handle split and dividend adjustments by updating all prior historical data.  The table you presented shows the price going from 20.72 to 10.57.  We do not have the hard cutover like that, instead, we adjust all prior data to match the split.
