### ISSUE TITLE
New requirement: get stock data between a period

### ISSUE THREAD

**Issue by jameslaicn** [iexg/IEX-API#486]
Hi, 

It is very helpful that I can get history daily stock data through below API, but is it possible to provide an API to get the stock data between two dates? such as "/stock/aapl/chart/201801-2018-08-20" ? and can we get one day data based on day?  I know "/stock/aapl/chart/1d" provided the data based on minutes, but is it possible to get one day "open, close, high, low"? Thanks a lot.

/stock/aapl/chart
/stock/aapl/chart/5y
/stock/aapl/chart/2y
/stock/aapl/chart/1y
/stock/aapl/chart/ytd
/stock/aapl/chart/6m
/stock/aapl/chart/3m
/stock/aapl/chart/1m
/stock/aapl/chart/1d
/stock/aapl/chart/date/20180129
/stock/aapl/chart/dynamic

**Comment by aajtodd** [comment]
Agreed that it would be useful to query previous OHLC for a specific date or range

/stock/aapl/previous/20180129
/stock/market/previous/20180129

This could obviously also fall under the chart API.

Something like:
/stock/aapl/chart/date/20180129?interval=daily

The only issue I see is that it is currently limited to previous 30 trading days and returns data in minute format (which is great but would also be useful to just get previous end-of-day pricing).

**Comment by timpaine-iex** [comment]
closing as stale, available on IEX Cloud

**Comment by aam1r** [comment]
> closing as stale, available on IEX Cloud

Can you provide a link to the docs that mention this?

I’ve been trying to find this but can’t find anything in the docs

**Comment by aam1r** [comment]
> https://iexcloud.io/docs/api/#time-series

Sorry, I should have been more specific. I am only interested in OHLC data for a specific stock ticker between a certain date range.

I tried `https://cloud.iexapis.com/stable/time-series/OHLC/AAPL` but that is not a valid endpoint.

**Comment by ConJabi** [comment]
I agree, being able to put in a specific range for the Historical Prices endpoint would make things much easier. 
something like:

```
GET /stock/{symbol}/chart/from=2018-01-01&to=2019-06-01

GET /stock/AAPL/chart/from=2018-01-01&to=2019-06-01
```

**Comment by timpaine-iex** [comment]
Yes like I said, timeseries.
`https://cloud.iexapis.com/stable/time-series/HISTORICAL_PRICES/AAPL?from=2018-01-01&to=2019-06-01&token=...`

**Comment by ConJabi** [comment]
`https://cloud.iexapis.com/stable/time-series/HISTORICAL_PRICES/AAPL?from=2018-01-01&to=2019-06-01&token=...`

How would i add the charts parameter chartCloseOnly=True?
