### ISSUE TITLE
Get Sector Performance Over Different Time Ranges

### ISSUE THREAD

**Issue by exiao** [iexg/IEX-API#487]
## Summary
Currently the sector performance API only offers performance metrics for the current day. It would be useful to get this data by 1W, 1M, YTD, 1Y, etc.

### Date/time of issue
Sept 16, 2018

### API URL
https://api.iextrading.com/1.0/stock/market/sector-performance

**Comment by exiao** [comment]
Also, I am curious what the sector performance is based off, is it a weighted average based on market cap of the stocks within the sector?

**Comment by joshuablackburn-iex** [comment]
@exiao Yes, it is weighted average based on market cap of underlying stocks.
