### ISSUE TITLE
Add more than 4 quarters for financial metrics

### ISSUE THREAD

**Issue by exiao** [iexg/IEX-API#488]
## Summary
We would like to show TTM annual revenue growth of a stock using the IEX API. Currently the API only allows you to retrieve last 4 quarters or last 4 calendar years.

For example, if we wanted Q3 2017 - Q2 2018 revenue for APPL, that is available. Q3 2016 - Q2 2017 revenue is not available. In order to get this metric, we need to use a different provider. 

We would like the previous 8 quarters of financials in order to power this metric.

### Date/time of issue
September 16, 2018

### API URL
https://iextrading.com/developer/docs/#financials
https://api.iextrading.com/1.0/stock/aapl/financials

**Comment by aaron25mt** [comment]
Also would like to see this

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557

**Comment by evancarter-iex** [comment]
IEX Cloud now has 12 quarters of financial data.

https://iexcloud.io
