### ISSUE TITLE
Batch/quote close volume does not match historical close volume for 9/14

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#489]
## Summary

For Friday 9/14 closes the batch/quote close volume does not match historical close volumes.

## Details

For example AAPL (most symbols are showing a slight error)
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl&types=quote
or 
https://api.iextrading.com/1.0/stock/market/quote?symbols=AAPL

with give an incorrect close latest volume as below of 31920851

"latestSource":"Close","latestTime":"September 14, 2018","latestUpdate":1536955200321,"latestVolume":31920851,"

and when calling https://api.iextrading.com/1.0/stock/aapl/chart/2y

{"date":"2018-09-14","open":225.75,"high":226.84,"low":222.522,"close":223.84,"volume":31999289,

the volume is 31999289 which is correct.

just about all the symbols A, AA etc. have a small error in this volume, the open, high,low and close quotes seem to be correct.

### Date/time of issue

9/16/2018

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl&types=quote
or 
https://api.iextrading.com/1.0/stock/market/quote?symbols=AAPL

vs 

 https://api.iextrading.com/1.0/stock/aapl/chart/2y

### What you expected to happen

the closing volumes to match for the historical and batch/quote close

### What actually happened

small errors/differences in closing volume across most tickers.

**Comment by joshuablackburn-iex** [comment]
This is a known limitation of the current API.  The IEX trading system shuts down at 5pm ET.  Any trades on the market between 5pm and 8pm are not included in volumes until the following day.
