### ISSUE TITLE
When are splits applied to historical/previous day data?

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#490]
## Summary
When are splits applied to historical or previous data? I noticed that today on 9/17 saex had a 1:10 reverse split which as of the morning of 9/17 had already been adjusted for in the historical and previous close data. If I remember a split usually took till the next day to show up in historical data?

https://api.iextrading.com/1.0/stock/saex/chart/2y
https://api.iextrading.com/1.0/stock/market/previous

## Details

When are splits applied to historical or previous data? I noticed that today on 9/17 saex had a 1:10 reverse split which as of the morning of 9/17 had already been adjusted for in historical data. If I remember a split usually took till the next day to show up in historical data?

https://api.iextrading.com/1.0/stock/saex/chart/2y
https://api.iextrading.com/1.0/stock/market/previous

### Date/time of issue

9/17/2018

### API URL

https://api.iextrading.com/1.0/stock/saex/chart/2y
https://api.iextrading.com/1.0/stock/market/previous

### What you expected to happen

no split adjusted data on historical or previous close data till new historical or previous data is available.

### What actually happened

split was adjusted data on historical or previous close data on same day as split.

**Comment by joshuablackburn-iex** [comment]
Prices are adjusted nightly.  The first job runs at 10pm ET and runs again at 1am and 4am ET.  Our data provider is responsible for adjusted historical prices.
