### ISSUE TITLE
Add More ETF Fundamentals (e.g. Category, Expense Ratio, Holdings)

### ISSUE THREAD

**Issue by exiao** [iexg/IEX-API#491]
## Summary
For my application, I would like to surface relevant data needed to make a purchase decision on ETFs. This includes the following:
- Category: Technology
- Style: Growth
- Fees / Expense Ratio: 0.09%
- Holdings: AAPL (10%), FB (5%)...
- Fundamentals Data: P / E, P / Sales, ROIC, etc.

Currently, only price movement + dividend yield data is available, which makes it more difficult to decide whether to purchase.

### Date/time of issue
Sept 17, 2018

### API URL
https://api.iextrading.com/1.0/stock/SPY/stats

**Comment by kzaveri16** [comment]
I agree. This information would be very helpful.

**Comment by adamfortuna** [comment]
+1 on expense ratio! I was looking to see if it was possible and stumbled on this ticket.

**Comment by timpaine-iex** [comment]
https://iexcloud.io/console/roadmap
