### ISSUE TITLE
TOPS Websocket endpoint `lastSaleTime` > `lastUpdated`

### ISSUE THREAD

**Issue by zhy0** [iexg/IEX-API#492]
## Summary
When using [TOPS endpoint's](https://iextrading.com/developer/docs/#tops) Websocket, sometimes we have `lastSaleTime > lastUpdated`. Is this OK behavior?

## Details
I would expect `lastUpdated` to refer to the last time **any** of the fields has been updated, so that `lastUpdated >= lastSaleTime`. But quite often this is not true:

```json
{  
   "symbol":"FB",
   "sector":"softwareservices",
   "securityType":"commonstock",
   "bidPrice":156.8,
   "bidSize":600,
   "askPrice":160.55,
   "askSize":100,
   "lastUpdated":1537294397502,
   "lastSalePrice":160.55,
   "lastSaleSize":100,
   "lastSaleTime":1537294402213,
   "volume":601153,
   "marketPercent":0.04138,
   "seq":121018
}
```
Or am I missing the point of `lastUpdated`?

**Comment by joshuablackburn-iex** [comment]
This can happen at times.  There are times when lastUpdated can reflect the quote that triggered the trade, and can be sequenced before the trade.
