### ISSUE TITLE
Batch Request Formatting

### ISSUE THREAD

**Issue by mfhawley** [iexg/IEX-API#494]
## Summary
Batch Requests are not returned in standard JSON format. 

## Details
Batch Requests are not returned in standard JSON format. Json is typically [{}, {}, {}] or {[{}, {}]} format but batch request is  {{[{}, {}]}} which is throwing errors in our app. Can you please explain why this is or any ideas on how to fix the issue to put it back into proper JSON formatiing?
We can simply re-format the structure on our backend but if we make, for example, many calls per second it can add alot of extra time.

### Date/time of issue

9/21/2018 @ 12:15am

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=A&types=chart&range=1d

### What you expected to happen

Different bracket format such as [{}, {}, {}] or {[{}, {}]}

### What actually happened

Bracket in format of  {{[{}, {}]}} which is not typical JSON format

**Comment by mfhawley** [comment]
Could someone provide some insight into this topic please? Thank you!

**Comment by joshuablackburn-iex** [comment]
Can you explain why you think our formatting is invalid?  I understand your example of an array of objects [{},{}], but not why an object must only contain an array.  Our API output does validate.
