### ISSUE TITLE
iexvolume and iexpercent missing for list on weekends

### ISSUE THREAD

**Issue by mdshibu76** [iexg/IEX-API#495]
## Summary

iexvolume and iexpercent list do not show up weekends. The Friday's iexvolume and iexpercent list should have been  displayed over the weekend until the market open again on Monday.

It is shown as [ ] on Saturday or Sunday

### Date/time of issue

Observed the issue Saturday and Sunday.  Friday market close data should have been retained

### API URL

/stock/market/list/iexvolume
/stock/market/list/iexpercent

### What you expected to happen

It is shown as [ ] on Saturday or Sunday
The Friday's market close data should have been retained.

### What actually happened

The output is shown as [ ] on Saturday or Sunday

**Comment by evancarter-iex** [comment]
@mdshibu76 is this still a problem with IEXCloud?

**Comment by hamermike** [comment]
@evancarter-iex I can confirm that this is an issue with the cloud API, at least with /stock/market/list/gainers and /stock/market/list/mostactive (Saturday 11:11 PM EST).
