### ISSUE TITLE
Regular Dividends and Historical data

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#496]
## Summary

To bring up the impact of including regular dividends in IEX Historical data, and possible solutions to remove regular dividends from the IEX Historical data.

## Details

On most platforms, stock data is not typically adjusted for regular dividends. The data is only adjusted for stock splits  and special dividends. When the historical data is adjusted for regular dividends, back testing and technical indicators can vary from their true readings. These variations/errors become larger the further one goes back in history with the addition of more dividends.

If the historical data needs to be adjusted for regular dividends. Some sources add an extra field called unadjusted close that does not include the regular dividends. With this  unadjusted close field one can remove the regular dividends from the historical data and restore the data for accurate back testing and technical indicator analysis.

Alternatively (but a little more work) if supplied with an accurate dividend history for any stock one could remove the regular dividends from a stocks historical data. Currently the dividend history for stocks does not seem to work (missing latest dividends, this is also mentioned in other issue topics). 

### Date/time of issue

9/23/2018

### API URL

https://api.iextrading.com/1.0/stock/aapl/chart/2y

https://api.iextrading.com/1.0/stock/AAPL/dividends/2y

### What you expected to happen

The historical data includes regular dividends and could be not adjusted for regular dividends to match most platforms, there is no unadjusted close field (not containing regular dividends) provided so one can adjust the historical data to match most platforms. There is no accurate dividend history that can be used to adjust the historical data.

https://api.iextrading.com/1.0/stock/AAPL/dividends/2y

is missing the most recent dividends.

### What actually happened

Historical data is adjusted for regular dividends which does not match most platforms and there is no means to adjust the historical data.

**Comment by bbuchanan** [comment]
I believe this is what I'm encountering as well. It's preventing me from supporting IEX in my platform.

**Comment by StockConsultant** [comment]
yes, I hope they can add an unadjusted close field in their new update. The only site which uses data like this is StockCharts.com no other site uses data like this since it skews the historical data and indicators the further you go back.

**Comment by bbuchanan** [comment]
I made a quick switch to alphavantage. A full set of data (not just 5 years), unadjusted.

**Comment by evancarter-iex** [comment]
@StockConsultant  & @bbuchanan  Unadjusted close is a field on IEXCloud. https://iexcloud.io
