### ISSUE TITLE
Total Liabilities is null

### ISSUE THREAD

**Issue by aflynn93** [iexg/IEX-API#497]
## Summary
Whenever I get financial data for a stock, the Total Liabilities value is always null. I know this issue has been mentioned in the past, but it doesn't seem like anything has been done with it. Are there any plans to fix this, or is this a more "bottom of the barrel" issue?

## Details
Total Liabilities always returns null

### Date/time of issue
2018-09-24

### API URL
https://api.iextrading.com/1.0/stock/amzn/financials?period=annual

### What you expected to happen
I expected financial data for each field to be returned for a given stock.

### What actually happened
I got the expected data on every field except TotalLiabilities.

**Comment by upenr** [comment]
Hi, another bug (I think) is that the "Total Current Liabilities" data is not even available via the API. Check this Yahoo Finance link for a list of data that should be available via this API: https://finance.yahoo.com/quote/AAPL/balance-sheet

**Comment by aflynn93** [comment]
I actually do see the data on Yahoo Finance. It is bolded and called "Total Current Liabilities". Does this API use Yahoo Finance? If so, does it do so using a Yahoo API or does it scrape/crawl the webpage to get the data?

**Comment by aflynn93** [comment]
I'm sorry, I thought you meant on the Yahoo page. Total Current Liabilities and Total Liabilities are on Yahoo, but Total Current Liabilities is not available on this API, and Total Liabilities is null. You are correct, I misunderstood your message.

**Comment by joshuablackburn-iex** [comment]
@upenr We are not scraping Yahoo Finance.  We have 3rd party providers and our own data.  We will greatly expand our available data in version 2.

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud. If you havent already you can sign up for the beta here: https://iexcloud.io
