### ISSUE TITLE
Broaden Available Financial Data Like EBT and EBIT

### ISSUE THREAD

**Issue by MichaelPHartmann** [iexg/IEX-API#498]
There are a few key data points missing from the financials, namely any information that would make finding out how much a company paid in tax impossible. 

The financials request returns lots of useful data but missing are things like pre-tax income/EBT or even EBIT. I use the data for a small value investing project and need to create effective tax numbers for my models to be accurate.

Tuesday, September 25th, 2018

https://api.iextrading.com/1.0/stock/aapl/financials

**Comment by aflynn93** [comment]
Also Total Current Liabilities

**Comment by evancarter-iex** [comment]
This available in the /income statement of https://iexcloud.io https://iexcloud.io/docs/api/#income-statement
