### ISSUE TITLE
Trustworthiness of TOPS Feed for Recreating OHLCV Chart Data from >30 Days Ago

### ISSUE THREAD

**Issue by clickingbuttons** [iexg/IEX-API#499]
## Summary
I love your [historical charts](https://api.iextrading.com/1.0/stock/aapl/chart/date/20180829) endpoint. However, I'd like to get more than the previous 30 days' worth of intraday data, and I'd like to get premarket/after hours as well.

## Details
I downloaded your [TOPS binary feed](https://iextrading.com/trading/market-data/#hist) hoping to be able to extract all TRADE_REPORTs to recreate OHLCV for a day >30 days ago, but it seems the feed (as intended) doesn't have TRADE_REPORTs on exchanges other than IEX. Right now, I cannot get accurate volume data for that day, only continuous OHLC based off IEX's limited volume from TRADE_REPORTs.

Having reached this point, I suppose I have three questions:
1. Is it too heavy of a data burden to serve more than the past 30 days of historical intraday data? Other APIs seem to follow suit with the 30 day limit, so I'm curious.
2. How does IEX gather the data for the historical charts endpoint (can OHLCV be done from just from your TOPS feed, or do you use a third-party provider for part of it?)
3. When the best bid or ask gets taken out in your TOPS feed (which I'm assuming includes all exchanges), how often is it due to the trade being executed?

### Date/time of issue
All the time.

### API URL
An [AAPL chart](https://api.iextrading.com/1.0/stock/aapl/chart/date/20180129) from January (in the docs).

### What you expected to happen
To be able to get greater than the past 30 days of intraday chart data.

### What actually happened
IEX rightfully only keeps the past 30 days worth of data, so I'm trying to recreate per-minute OHLCV data from TOPS. I'm aware [Tiingo](https://www.tiingo.com/welcome) rehosts it from IEX, but I want premarket and volume data which Tiingo doesn't have.

### Other Information (sample code, links, etc.)
I know little about the implementation of the technology behind exchanges -- please excuse my ignorance.

**Comment by joshuablackburn-iex** [comment]
TOPS is an IEX product and represents our own quotes and trades. It does not include data for other exchanges. We currently support 30 days, but have plans to support more in our next version. If you use our dated historical minute bar data, you are able to obtain OHLC for both IEX and the market (consolidated tape). The market is 15 minutes delayed, but if you are doing this historically, you will get the full trading day. We do not cover outside of regular market hours at this time.

To answer your question regarding data burden, the underlying data is >200GB per day, but the minute bar data itself is relatively small.

To answer question 3, our bids and asks fluctuate constantly, as on most markets. You would need to line up our trade timestamps with quotes to see which are the result of a trade versus an order being amended, canceled, or the market moving.
