### ISSUE TITLE
afterhours/pre-market data

### ISSUE THREAD

**Issue by jjosyde** [iexg/IEX-API#5]
First off great API and love the new improvements as well. Would it be possible to get pre-market and after hours data on the roadmap? Thanks again!

**Comment by joshuablackburn-iex** [comment]
We currently update our prices from 8am - 9:30am and 4pm to 5pm.  These are our system hours.  Is this sufficient pre/post market hours, or are you requesting 4am - 8pm.  The later may not happen in the near future.

**Comment by joshuablackburn-iex** [comment]
We currently return the official open/close of each stock, and you're able to check the realtime or delayed price update time to see if it is pre/post market.
