### ISSUE TITLE
Sparse Charts - Fill in the gaps w/historically adjusted market-wide data by minute

### ISSUE THREAD

**Issue by massaroni** [iexg/IEX-API#50]
The IEX-only intra-day data by minute for Small-cap and Mid-cap stocks, is still **very sparse**.  Even many S&P500 stocks often have blocks of 20 or 30 minutes without a single trade.

Some examples:
[https://api.iextrading.com/1.0/stock/spxl/chart/1d](https://api.iextrading.com/1.0/stock/spxl/chart/1d)
[https://api.iextrading.com/1.0/stock/roka/chart/date/20171024](https://api.iextrading.com/1.0/stock/roka/chart/date/20171024)
[https://api.iextrading.com/1.0/stock/bhf/chart/date/20171025](https://api.iextrading.com/1.0/stock/bhf/chart/date/20171025)

It would be extremely helpful to adjust intra-day charts with market-wide data, to **fill in the gaps**, even if there's a 15 minute delay.  It's an honorable philosophy to provide open access to market data about public companies, but charts this sparse still leave IEX users at a major disadvantage.

On the phone last month, Josh mentioned this was a work in progress.  Is this still on the roadmap, is it coming soon?

**Comment by joshuablackburn-iex** [comment]
This is actually in QA now.

**Comment by massaroni** [comment]
Awesome, thanks, we're looking forward to this one.

**Comment by joshuablackburn-iex** [comment]
market wide data is provided with a prefix of "market"
