### ISSUE TITLE
Upcoming IPO for current and next month not showing all data

### ISSUE THREAD

**Issue by samerawada92** [iexg/IEX-API#500]
## Summary

When making a request to "https://api.iextrading.com/1.0/stock/market/upcoming-ipos" i am only getting about 6 companies with upcoming IPO dates. Even though they are correct, the issues is that we are not getting a full list of all the upcoming IPOs. 

For example if we look at the listed IPO data from Nasdaq, we can see that there are other companies not listed on IEXtrading.

Is there a way to get the full list of upcoming IPOs?

### API URL

https://api.iextrading.com/1.0/stock/market/upcoming-ipos

**Comment by joshuablackburn-iex** [comment]
We show the same number of IPOs. We separate IPOs by stocks going today versus in the future.
https://iextrading.com/developer/docs/#ipo-calendar

**Comment by samerawada92** [comment]
You are correct, is it only NASDAQ companies?

**Comment by joshuablackburn-iex** [comment]
We include all IPOs.

**Comment by samerawada92** [comment]
Great, thank you!

**Comment by xxx44yyy** [comment]
@joshuablackburn-iex You plan to split the IPO to a different activity? 
Nasdaq shows 4 types (pricing, upcoming, filings, withdrawn), and you have only one - **Upcoming**.

https://www.nasdaq.com/markets/ipos/activity.aspx?tab=pricings
