### ISSUE TITLE
Interpreting the candle time endpoints

### ISSUE THREAD

**Issue by simonskok** [iexg/IEX-API#501]
## Summary
This is not really an issue, but more of a clarification request. The api call https://api.iextrading.com/1.0/stock/aapl/chart/1d?chartLast=5 returns the last 5 1-minute data bars with the last time stamp being 15:59 PM. Does the timestamp imply the duration from 15:59 until 16:00, so that the close price is actually the closing price at the market close at 16:00 PM, or from 15:58 to 15:59 and the 9:30 candle timestamp on the next day actually represents the last minute candle during the regular trading hours?
Does the 9:30 candle "hold" all the trading information from 16:00 PM yesterday until the market open next day, i.e. post and pre-market trading?
Thank you for your great work!

### Date/time of issue
Always

### API URL

https://api.iextrading.com/1.0/stock/aapl/chart/1d?chartLast=5

### What you expected to happen

Get the data candle with timestamps corresponding to the end of the time period

### What actually happened
Not sure how to interpret the timestamp

**Comment by joshuablackburn-iex** [comment]
The 9:30 entry represents trading data from 9:30-9:31.  That means 15:59 represents trading data up to the close.  There should always be 390 entries.
