### ISSUE TITLE
What is the data source for endpoint "Previous"?

### ISSUE THREAD

**Issue by bb10128** [iexg/IEX-API#503]
## Summary

Are the data behind endpoint "Previous" from a 3rd-party data vendor?  Which vendor?  And what are the exact definitions for "open" and "close" for this endpoint?

## Details

1)  Since endpoint "Previous" contains yesterday's open/high/low/close, adjusted for corporate actions with ex-date equal to today, it appears unlikely such data can come from SIP or other exchanges directly. Could you please confirm that such data are indeed sourced from a third-party data vendor?   Can you disclose the name of the third-party, as this will tell me a lot about  the data quality.

2) As a general comment, in your API documentation, could you always document the data source? 

3) Finally, for endpoint "Previous", are "open" and "close" (before corporate action adjustments) the official open/close from the primary listing exchange (i.e. from the open/close auctions), similar to the "open" and "close" behind endpoint "OHLC"?

Thanks.

### API URL
https://api.iextrading.com/1.0/stock/market/previous

**Comment by joshuablackburn-iex** [comment]
@bb10128 
1. The `previous` endpoint along with all adjusted historical data is from a 3rd party.  Currently that is QuoteMedia.  We have a new, higher quality data source planned for V2.
2. I agree that we should label our data sources, and V2 docs will do so where we are able.  In some instances we may be prohibited by our contract to disclose the company name. Our goal is to be as open and transparent as possible, so we will make every effort to improve our docs.
3. 'Open' and 'Close' in the `previous` endpoint are corporate actions adjusted official open and close.  If that is not the case, then we will need to investigate with our vendor.  In cases where it is a company listed on IEX, we are the source of the official open and close.

**Comment by bb10128** [comment]
Thanks Josh.   QuoteMedia data quality is not that high.

Also I can confirm that "Open" and "Close" under "Previous" endpoint are NOT the official listing exchange open/close.  I looked at the condition codes in my tick data to double check.
