### ISSUE TITLE
Understanding values returned from chart endpoint

### ISSUE THREAD

**Issue by sribas** [iexg/IEX-API#505]
## Summary
When accessing the chart endpoint for data by the minute for a specific date, on some minutes the data just comes as -1 for high\low\average and 0 for volume\notional\number of trades.

## Details

Is it correct to assume that whenever it returns -1 and 0 there was no traded volume on those minutes or is this an issue?

### Date/time of issue
Today

### API URL
https://api.iextrading.com/1.0/stock/chek/chart/date/20180904

### What you expected to happen
Prices and volume by the minute.

### What actually happened
For some minutes the values are -1 and 0.

### Other Information (sample code, links, etc.)
Example: https://api.iextrading.com/1.0/stock/chek/chart/date/20180904
(minute 9:31 already returns -1 on high, low and average)

**Comment by joshuablackburn-iex** [comment]
This is the result of our internal database not having a value for that minute. The DB is returning -1 for its null values.  This is something we are going to normalize in V2.  In the minutes that you receive a -1, that means IEX does not have a trade in that minute.  If the key is prefixed with "market" and you receive the same data, that means there were no trades on the market in that minute.
