### ISSUE TITLE
Unable to find Corporate Action for Stock.

### ISSUE THREAD

**Issue by JGSilverman** [iexg/IEX-API#508]
## Summary
On October 1, 2018, Honeywell paid a stock dividend of 0.1 share Garrett Motion Inc. common stock to shareholders.  I am unable to find this corporate action through the api.  Can you let me know where it is? Which endpoint do I have to hit?

### API URL

https://api.iextrading.com/1.0//stock/hon/dividends/5y

### What you expected to happen

I thought I'd get the divided information back.

### What actually happened

An empty array returned to me.

**Comment by evancarter-iex** [comment]
This is fixed in iexcloud. Please use that https://iexcloud.io
