### ISSUE TITLE
Company description for AAPL grammatically incorrect

### ISSUE THREAD

**Issue by mishkamishka47** [iexg/IEX-API#509]
## Summary
The `description` field of the company description for AAPL is grammatically incorrect.

## Details
The first part of the sentence reads:
> Apple Inc **is designs**, manufactures and markets mobile communication and media devices and personal computers...

The word "is" shouldn't be there.

### Date/time of issue

5 October 2018 @ 9:18 CDT

### API URL

`https://api.iextrading.com/1.0/stock/aapl/company`

### What you expected to happen

Company description would be a complete sentence

### What actually happened

Company description has an error

**Comment by joshuablackburn-iex** [comment]
I agree this is poorly written.  This comes from a 3rd party, so we will need to ask them to fix this.
