### ISSUE TITLE
international stocks/Exchange support

### ISSUE THREAD

**Issue by twentylemon** [iexg/IEX-API#51]
Is there any plan to support international stocks? For example, Shopify is cross listed on the TSX and NYSE, but the TSX version is unavailable.
https://api.iextrading.com/1.0/stock/market/batch?types=quote&symbols=SHOP.TO,SHOP

**Comment by AlekzZz** [comment]
that would be really awesome

**Comment by ronnyworm** [comment]
I'd really welcome this as well.
I am used to calling APC.F / APC.FRA / fra:apc to get access to the stock price of Apple shares from the stock market at Frankfurt (in EUR) for example.

**Comment by 2567910** [comment]
+1

**Comment by evancarter-iex** [comment]
Note, we have Mexico and Canada End of Day data in IEXCloud and will be adding more as we go. 
Https://iexcloud.io

**Comment by evancarter-iex** [comment]
Closing. https://iexcloud.io has international exchange support

**Comment by timpaine-iex** [comment]
https://intercom.help/iexcloud/en/articles/4580026-supported-stock-exchanges-on-iex-cloud
