### ISSUE TITLE
data type inconsistency in daily historical stats and recent stats

### ISSUE THREAD

**Issue by AustinMCrane** [iexg/IEX-API#510]
## Summary

here are two different api requests to iex:
https://iextrading.com/developer/docs/#historical-daily
and
https://iextrading.com/developer/docs/#recent

historical-daily

[
  {
    "date": "2017-05-09",
    "volume": 152907569,
    "routedVolume": 46943802,
    "marketShare": 0.02246,
    "isHalfday": 0,
    "litVolume": 35426666
  },
...
recent-stats

[
  {
    "date": "2017-01-11",
    "volume": 128048723,
    "routedVolume": 38314207,
    "marketShare": 0.01769,
    "isHalfday": false,
    "litVolume": 30520534
  },
...
in the first link the isHalfday value is a int (0/1) and in the recent it is a bool value.
this seems like the best fix is at the api level.

### Date/time of issue
Saturday October 6, 2018

### API URL
https://api.iextrading.com/1.0/stats/historical/daily
https://api.iextrading.com/1.0/stats/recent

### What you expected to happen
both values of is isHalfday to be booleans true false instead of one being an int (0,1) and the other a boolean

### What actually happened
one is a bool one is an int

### Link to package issue:
https://github.com/timpalpant/go-iex/issues/21

**Comment by evancarter-iex** [comment]
Closing. If this is an issue in https://iexcloud.io please create a new issue.
