### ISSUE TITLE
Will IEX ever start charging for this service?

### ISSUE THREAD

**Issue by swamyg** [iexg/IEX-API#511]
## Summary
Not sure if this is the right place to post. This seems to be one of a kind service that IEX is providing and I'm not sure how they are doing it for free. While I'm surprised by the generosity and would like to build some apps on top of this API, I'd like to know if there is any the roadmap for pricing in the future? 

Don't want to be suddenly slapped with a huge cost down the road. Thanks.

**Comment by MauriceArikoglu** [comment]
Wandering about the same thing.

**Comment by danieljhochman** [comment]
+1 Would also like to know

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557
