### ISSUE TITLE
Symbology for Preffered Tickers

### ISSUE THREAD

**Issue by danieljhochman** [iexg/IEX-API#514]
Hi,

I saw that you use symbology from Nasdaq Integrated (INET). So why can't I pull up quotes for tickers like this?

https://api.iextrading.com/1.0/stock/BAC.PRA/quote
https://www.nasdaq.com/symbol/bac.pra

Thanks!

**Comment by smidwap** [comment]
https://api.iextrading.com/1.0/stock/BAC-A/quote

**Comment by danieljhochman** [comment]
Thanks! Is there a way to pull the full ticker universe which IEX covers?
