### ISSUE TITLE
What's mean seq field in websocket payload response?

### ISSUE THREAD

**Issue by icastillejogomez** [iexg/IEX-API#516]
## Summary

What's mean seq field in websocket payload response?
```
{
  askPrice: 0,
  askSize: 0,
  bidPrice: 0,
  bidSize: 0,
  lastSalePrice: 262.9,
  lastSaleSize: 100,
  lastSaleTime: 1539115196809,
  lastUpdated: 1539115200000,
  marketPercent: 0.02509,
  sector: "automobilescomponents",
  securityType: "commonstock",
  seq: 55344, // <- This field
  symbol: "TSLA",
  volume: 298933
}
```
### Date/time of issue
2018-oct-10 7:40am GMT+0001

### API URL
https://iextrading.com/developer/docs/#tops

### What you expected to happen
Not necessary

### What actually happened
Not necessary

### Other Information (sample code, links, etc.)
Not necessary

**Comment by joshuablackburn-iex** [comment]
This got added when we changed out a backend component in our system, and simply represents our internal message sequence number.  You can disregard.

**Comment by icastillejogomez** [comment]
Can we use it to check if receive message is the latest message available? Thank you @joshuablackburn-iex for the answer 😄
