### ISSUE TITLE
In Stock/Chart, Change and ChangePercent responses give meaningless values

### ISSUE THREAD

**Issue by chrisfs** [iexg/IEX-API#517]
## Summary
In the stock/chart calls, the "change" and "changepercent" responses gives meaningless values. 

## Details
In the stock/chart calls, the "change" and "change percent" responses (as opposed to "Changeovertime") give meaningless values. It's not Close-Open, it's not change over time. There's no apparent meaning for these values. 
### Date/time of issue
3:46 PT 10/10/2018

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/5y

### What you expected to happen
That change and change percent are derived from Close-Open of the same day

### What actually happened
Sadness, frustration and disappointment.

**Comment by joshuablackburn-iex** [comment]
change and changePercent represent the different between close price of a particular day and close price of the previous day.
