### ISSUE TITLE
Possible adding Quotes for the US 10 Year Bond (TMUBMUSD10Y) and the Dollar Index (DXY) ?

### ISSUE THREAD

**Issue by Mctoodles-NNN** [iexg/IEX-API#518]
## Summary
Possible adding the US 10 Year Bond (TMUBMUSD10Y) and the Dollar Index (DXY) ?

## Details
Possible adding the US 10 Year Bond (TMUBMUSD10Y) and the Dollar Index (DXY) ?

### Date/time of issue
10/11/18

### What you expected to happen
IEX adds quotes for the US 10 Year Bond and the Dollar Index

### What actually happened
It's not added.

**Comment by Mctoodles-NNN** [comment]
How will I know that it'll be added?

**Comment by timpaine-iex** [comment]
We're generally pretty vocal when it comes to new stuff, also all tracked on 
https://iexcloud.io/console/roadmap
