### ISSUE TITLE
SWIFT: Can connect to websocket server but receive no 'message" replies

### ISSUE THREAD

**Issue by piersbravery** [iexg/IEX-API#519]
## Summary
Can connect to websocket server but receive no 'message" replies

## Details
After succesful connection and executing executing self.socket.emit("subscribe","firehose") I appear to receive no "message".  Can connect to websocket server but receive no 'message" replies

### Date/time of issue
11/11/2018 11:06

### API URL
https://ws-api.iextrading.com/1.0/tops

### What you expected to happen
I expected my self.socket.on("message") functions to fire and output "Data Recieved" to my log

### What actually happened
self.socket.on("message") never appears to fire

### Other Information (sample code, links, etc.)

import UIKit
import SocketIO

class ViewController: UIViewController {

    let manager = SocketManager(socketURL: URL(string: "https://ws-api.iextrading.com/1.0/tops")!, config: [.log(true)])

    var socket:SocketIOClient!
    
    override func viewDidLoad() {
        super.viewDidLoad();
        self.socket = manager.defaultSocket;
        self.setSocketEvents();
        self.socket.connect();
    }

    
    private func setSocketEvents()
    {
        self.socket.on(clientEvent: .connect) {data, ack in
            print("CONECTED: ");
           
            self.socket.emit("subscribe","firehose");
        }
        
        self.socket.on(clientEvent: .error) {data, ack in
            print("socket error");
        }

        self.socket.on(clientEvent: .disconnect) {data, ack in
            print("socket disconnect");
        }
        
        self.socket.on("message") {data, ack in
            print("DATA RECEIVED");
        };
    };
    
    override func didReceiveMemoryWarning()
    {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    };

}

**Comment by joshuablackburn-iex** [comment]
Did you connect at 11:06 am or pm ET?  Websocket connections will only receive data during trading hours.  Our trading system starts at 8am ET and shuts down at 5pm ET, but you'll get the majority of data during regular market hours of 9:30-4.

**Comment by piersbravery** [comment]
11:06 central european time.  But I tried it all day and night yesterday with the same results

Im not sure whether my socket.emit is at fault

or my socket.on("message”)

i assume that i just read the data received from “message” the documentation is not clear

**Comment by piersbravery** [comment]
Just to be clear I was testing while the markets were open yesterday.  I could get the data via html.  But my socket.om(“message”) never fired.  It appeared no traffic with “message” appeared in the socket data.  It might be that my implementation is incorrect but I can find no more detail than what you have suppled.

Im working in XCODE 10 IOS 12

**Comment by gabrieldodan** [comment]
same issue , no 'message' replies

**Comment by mikemags1** [comment]
same issue

**Comment by mikemags1** [comment]
figured it out. Might be a bug with the socket.io-client-swift library or might be a hole in the IEX documentation. I think it is the former.

For context, know the overloaded definition of namespace as defined in Socket.IO's docs.
"Socket.IO allows you to “namespace” your sockets, which essentially means assigning different endpoints or paths."

Socket.io-client-swift library does not parse the Socket.IO namespace from the URL. However, the socket.io-client library does.

This Swift code
`                manager = SocketManager(socketURL: URL(string: "https://ws-api.iextrading.com/1.0/tops")!, config: [.log(true)])
        let socket = manager.socket(forNamespace: "/1.0/tops")
        
        socket.onAny { (event) in
            log.debug(event)
        }
        
        socket.on(clientEvent: .connect) {[weak self] (data, _) in
            print("socket connected")
            guard let self = self else { return }
            log.debug(self.tickerHandles.keys.joined(separator: ","))
            socket.emit("subscribe", "firehose")
        }
        
        socket.on("message") {(data, _) in
            log.debug(data)
        }
        
        socket.connect()
`
produces
The XCode socket.io logging line 2019-01-04 11:55:34.985847-0600 bluechxp[67831:724676] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: -1; **nsp: /**}

The node.js code
`
const socket = require('socket.io-client')('https://ws-api.iextrading.com/1.0/tops');

// Listen to the channel's messages
socket.on('message', message => console.log(message));

// Connect to the channel
socket.on('connect', () => {

  // Subscribe to topics (i.e. appl,fb,aig+)
  socket.emit('subscribe', 'snap');

})
`
run it with
>DEBUG=* node <file>.js
produces the logging line
  socket.io-client:manager writing packet {"type":2,"data":["subscribe","snap"],"options":{"compress":true},**"nsp":"/1.0/tops"**} +0ms

To fix this in Swift, just specify the namespace when grabbing the socket from the manager.

`        manager = SocketManager(socketURL: URL(string: "https://ws-api.iextrading.com/1.0./tops")!, config: [
            .log(true)])
        let socket = manager.socket(forNamespace: "/1.0/tops")`
