### ISSUE TITLE
Can't get C# ClientWebSocket to connect

### ISSUE THREAD

**Issue by DierkDroth** [iexg/IEX-API#52]
Hi,

I'm trying to connect using this simple code snippet

`System.Net.WebSockets.ClientWebSocket webSocket = new System.Net.WebSockets.ClientWebSocket();
await webSocket.ConnectAsync(new Uri("wss://ws-api.iextrading.com/1.0/stock/aapl/company"), System.Threading.CancellationToken.None);`

... but keep getting this exception:

System.Net.WebSockets.WebSocketException occurred
  HResult=0x80004005
  Message=The server returned status code '200' when status code '101' was expected.
  Source=System
  StackTrace:
   at System.Net.WebSockets.ClientWebSocket.ValidateResponse(HttpWebRequest request, HttpWebResponse response)

Any idea what I'm doing wrong?

**Comment by jcape** [comment]
Hi @DierkDroth 

The IEX API websockets is actually a socket.io-based server, which is not standard websockets. I'd recommend trying a sockets.io library instead, and there's a list of them available for C# at https://www.nuget.org/packages?q=socket.io&prerel=false

I haven't done any C# in a long while, so I can't speak to any of them directly, but https://github.com/Quobject/SocketIoClientDotNet appears to be widely downloaded and currently maintained, at least.

Hope that helps get you going, let me know if you need additional information.

**Comment by DierkDroth** [comment]
Hi,

Thanks for clarification. 

The roadmap in the docs states that the websocket API would be rewritten to be 'standard' websockets. What is the timeline/ETA for that project?

**Comment by joshuablackburn-iex** [comment]
It is still TBD.  We are working on HTTP streaming first, and hoping it can replace Websockets.

**Comment by DierkDroth** [comment]
Understand. 

What's the timeline/ETA for the HTTP streaming?

**Comment by joshuablackburn-iex** [comment]
The goal is before the end of the month.

**Comment by DierkDroth** [comment]
Thanks for your feedback

**Comment by jcape** [comment]
@DierkDroth I'll close this for now, and leave a comment when we start testing server-sent events for the Stocks API.

**Comment by DierkDroth** [comment]
Curious: what's the progress on that issue? How would I right now get streaming data in a C# environment? 

Thanks in advance

**Comment by jcape** [comment]
@DierkDroth Streaming for the stocks service has been delayed while we complete work on streaming for the market data feeds.

**Comment by DierkDroth** [comment]
Understand.

However, how would I access any of the market data feed (I suppose docs are available [here](https://iextrading.com/developer/docs/#iex-market-data), no?) by C#?

**Comment by jcape** [comment]
@DierkDroth Yes, those are the docs for the market data feeds. They are available via socket.io now, and will be the first to be made available via SSE when that is released publicly.

**Comment by DierkDroth** [comment]
Thanks, is there any ETA for that?

**Comment by DierkDroth** [comment]
>> will be the first to be made available via SSE when that is released publicly.

Is this API version released as of yet?
