### ISSUE TITLE
Sector name mismatch in sector-performance and company endpoints

### ISSUE THREAD

**Issue by ikoniaris** [iexg/IEX-API#520]
## Summary

The `sector-performance` endpoint says that the sector names are `Materials` and `Health Care`.
The `company` endpoint says that the sector names are `Basic Materials` and `Healthcare`. 

### API URL

1. https://api.iextrading.com/1.0/stock/market/sector-performance
2. https://api.iextrading.com/1.0/stock/VALE/company
3. https://api.iextrading.com/1.0/stock/JNJ/company

### What you expected to happen

The sector name to be the same across endpoints.

### What actually happened

Two endpoints return different values the same sector name.

**Comment by ikoniaris** [comment]
I've just realized that the same happens with `Healthcare` vs `Health Care`, e.g.: https://api.iextrading.com/1.0/stock/JNJ/company

**Comment by ikoniaris** [comment]
Interestingly the `collection` endpoint seems to accept both values:
1. https://api.iextrading.com/1.0/stock/market/collection/sector?collectionName=Materials
2. https://api.iextrading.com/1.0/stock/market/collection/sector?collectionName=Basic%20Materials

**Comment by evancarter-iex** [comment]
@ikoniaris Is this still an issue with IEX Cloud?

**Comment by evancarter-iex** [comment]
Closing. If this is an issue in https://iexcloud.io please create a new issue.
