### ISSUE TITLE
Data for intraday durations other than 1 minute.

### ISSUE THREAD

**Issue by KHChart** [iexg/IEX-API#521]
## Summary
Is there a way to obtain OHLC data for intraday durations other than 1 minute?

## Details
I tried using the chartInterval=X parameter, but it displays every Xth 1 minute data point.  For example, chartInterval=5 shows the 1 minute data at 9:30, 9:35, etc.  That data is identical to the 1 minute data when chartInterval is omitted.   See the 2 URLs below.   I would like to get a true 5 minute OHLC bar.  If anyone knows how to accomplish this, please provide a sample query.

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/date/20181010?chartInterval=5
https://api.iextrading.com/1.0/stock/aapl/chart/date/20181010

**Comment by joshuablackburn-iex** [comment]
If you need durations less granular than 1 minute, can you iterate and combine 5  1 minute data points?
