### ISSUE TITLE
other websocket commands?

### ISSUE THREAD

**Issue by brentoboy** [iexg/IEX-API#522]
## Summary
Does the websocket api accept any other commands besides subscribe and unsubscribe?

## Details
The only real documentation about what can or cant be done via websockets appears to be the example provided, which sends me notifications of every bid as it happens.   I love all the data, but I'm only interested in the actual trades, is there a way to filter down to show only the trades?

I'm worried about bandwidth, and the unnecessary processing power required to filter it all as it shows up.

### What you expected to happen
I expected to be able to filter things down a bit
or possibly be able to subscribe to a whole category at once (perhaps this is possible already)

**Comment by joshuablackburn-iex** [comment]
you can subscribe to /last instead of /tops.  /last will only return trades.

**Comment by brentoboy** [comment]
excellent.  Thanks.
are there any other feeds I could subscribe to, or are those the options?

again, thanks, that's just what I needed.

**Comment by joshuablackburn-iex** [comment]
We only have TOPS, Last, and DEEP.  You can find WebSocket information in each of those sections of our docs https://iextrading.com/developer/docs/#iex-market-data
