### ISSUE TITLE
Order Book Endpoint returning empty arrays during trading hours

### ISSUE THREAD

**Issue by maloneyjay1** [iexg/IEX-API#523]
## Summary
Low price / Low float / High volume scannable securities not producing Bid/Ask Book array values. 

## Details
For high volume but low float/low price stocks, I have had considerable difficulty producing non-empty arrays using the Book endpoint.  This has been my experience across all intraday times and across many securities.  However for each of these if I check the Bid/Ask on broker platforms there is no such difficulty with returning current Bid/Ask.  Do certain securities not return valid arrays at this endpoint?

### Date/time of issue
10-12-2018 Intraday (at any time during normal market hours)

### API URL
https://api.iextrading.com/1.0/stock/izea/book

### What you expected to happen
I expect actively traded stocks to have valid Bid and Ask context.

### What actually happened
Actively traded stocks at the Order endpoint provided empty arrays.

**Comment by joshuablackburn-iex** [comment]
The book endpoint only represents IEX displayed orders.  If we do not have a displayed order on our book, the bid / ask arrays will be empty.  This appears to be lightly traded today, so it may not have an active displayed book at all times.
