### ISSUE TITLE
.../stock/LOACU/chart/dynamic returning 1d data during market hours

### ISSUE THREAD

**Issue by michaeldrennen** [iexg/IEX-API#524]
## Summary
API returns data with **range** of **1m**, instead of **today** during market hours.

## Details
Checked this stock (LOACU) on Yahoo Finance, and intraday values don't exist there either. 

### Date/time of issue
2018-10-17 10:45AM EST (really, any time during market hours)

### API URL
https://api.iextrading.com/1.0/stock/LOACU/chart/dynamic 

### What you expected to happen
Expect an empty data set returned during market hours for stocks like this.

### What actually happened
Daily market data over the last month was returned during market hours.

### Other Information (sample code, links, etc.)
Either return an empty data set returned during market hours for stocks like this.
OR
Update to the docs under **dynamic** saying that if intraday data is not available for that stock during market hours, then you will get daily values over the past month.

https://iextrading.com/developer/docs/#chart

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud. See https://iexcloud.io/ for more information.
