### ISSUE TITLE
Discrepancies in DEEP/TOPS Multicast feeds and Web API reference data.

### ISSUE THREAD

**Issue by adam-svetec** [iexg/IEX-API#525]
## Summary

Discrepancies in multicast feed vs web api reference data.

## Details

I am trying to better understand your reference data. I am investigating using the reference data provided in your Web API vs the reference data broadcasted in your DEEP and TOPS feeds.

Looking at our recordings today, I have found the following. I am hoping you can help me understand the discrepancies.

Web API (https://api.iextrading.com/1.0/ref-data/symbols):
I am getting a list of 8742 unique symbols. 
45 are marked as: (isEnabled: false):
"ARVR",  "AUSF",  "BOCT",  "BSAE",  "BSBE",  "BSCE",  "BSDE",  "CGVIC",  "CIVEC",  "CRUSC",  "DBLV",  "DDIV",  "EVFTC",  "EVGBC",  "EVLMC",  "EVSTC",  "FID",  "FLLA",  "FLSA",  "FLZA",  "FOANC",  "FPXE",  "GRBIC",  "HFGIC",  "IVENC",  "IVFGC",  "IVFVC",  "JHEM",  "LSAF",  "MOGLC",  "MUST",  "NONE",  "OKDCC",  "PETZC",  "PFFL",  "PHYL",  "PLCY",  "POCT",  "RPIBC",  "UOCT",  "WBND",  "ZCAN",  "ZDEU",  "ZGBR",  "ZJPN"

DEEP/TOPS Multicast feed ( 233.215.21.4:10378 ):
I am getting a list of 8718 unique symbols broadcast in your (Trading Status Message ‘H’ (0x48)).
All of these symbols seem to be present in your Web API, but the Web API seems to have 24 symbols the MC feed does not have.

A number of symbols marked as NOT enabled by your Web API appear in the DEEP Multicast feed and for example the symbol ‘ARVR’ is even marked as ‘trading (T)’ in DEEP MC but not enabled in Web API.

Trying to understand how I can reconcile these differences.

### Date/time of issue

20181016/all day

### API URL

https://api.iextrading.com/1.0/ref-data/symbols

### What you expected to happen

matching data

### What actually happened

discrepancies

**Comment by evancarter-iex** [comment]
Closing. api.iextrading.com is being sunset in June. If this is an issue in IexCloud https://iexcloud.io please create a new issue.
