### ISSUE TITLE
Some Preferreds missing data

### ISSUE THREAD

**Issue by cgailey** [iexg/IEX-API#527]
## Summary
Some preferreds that I have checked recently are recognized and have some price data, but missing basic fields such as primaryExchange and companyName.  

## Details
Two I have come across in the last few days are BC-A (Brunswick Corp. 6.50% Senior Notes due 10/15/2048), and TMK-C (Torchmark Corp., 6.125% Junior Subordinated Debentures due 6/15/2056).  

Sample data returned:
{"BC-A":{"quote":{"symbol":"BC-A","companyName":"","primaryExchange":"","sector":"","calculationPrice":"sip","open":25.03,"openTime":1539869400154,"close":25.04,"closeTime":1539806521226,"high":25.03,"low":24.99,"latestPrice":25.006,"latestSource":"15 minute delayed price","latestTime":"2:36:21 PM","latestUpdate":1539887781795,"latestVolume":52663,"iexRealtimePrice":25,"iexRealtimeSize":400,"iexLastUpdated":1539886323730,"delayedPrice":25.006,"delayedPriceTime":1539887781795,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":25.04,"change":-0.034,"changePercent":-0.00136,"iexMarketPercent":0.01164,"iexVolume":613,"avgTotalVolume":0,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":0,"peRatio":null,"week52High":25.03,"week52Low":0,"ytdChange":0.016112572125152366}}}

### Date/time of issue
Oct 18, 2018 2:58pm EST

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=BC-A&types=quote

### What you expected to happen
Basic data to be present in the quote.

### What actually happened
Missing companyName, primaryExchange, sector.

### Other Information (sample code, links, etc.)
Thanks!

**Comment by evancarter-iex** [comment]
Fixed with IEXcloud.  https://iexcloud.io/ for more information
