### ISSUE TITLE
Key Stats Not Showing TTM for Revenue and EBITDA 

### ISSUE THREAD

**Issue by rajivkbhatia** [iexg/IEX-API#528]
## Summary
Documentation indicates revenue and EBITDA stats data is TTM but it appears to be showing last quarter

## Details
Example: 
https://api.iextrading.com/1.0/stock/aapl/stats
It is showing 88,293,000,000 for revenue which was the QUARTERLY amount for the quarter ending decemeber 2017

As another example 
I cant figure out where the   "revenue": 11094800000 relates to MCD's EDGAR filings 
https://api.iextrading.com/1.0/stock/mcd/stats

EBITDA (and possibly other stats appear to be wrong)
--

### Date/time of issue
Sunday Oct 21 - Noon CT

### API URL
https://api.iextrading.com/1.0/stock/aapl/stats
https://api.iextrading.com/1.0/stock/mcd/stats

### What you expected to happen
I expected the correct TTM figures to appear 

For example the correct TTM revenue for AAPL is ~$255 billion
and the correct TTM revenue for MCD is ~$22 billion
similar issue for EBITDA as well

### What actually happened

revenue for AAP: 88,293,000,000
revenue for MCD: ~$11 billion which appears to be the sum of 3Q17 and 4Q17

### Other Information (sample code, links, etc.)

Thanks

**Comment by evancarter-iex** [comment]
This is now fixed in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
