### ISSUE TITLE
Inconsistent data in response during trading hours

### ISSUE THREAD

**Issue by BogdanZavu** [iexg/IEX-API#529]
## Summary
Inconsistent data response from 'https://api.iextrading.com/1.0/stock/**symbol**/chart/date/**date**
during trading hours.

## Details
API above works reasonable outside trading hours but during trading hours even though a response is successfully received it contains '-1' values in most of its relevant data fields like low, high, marketAverage etc etc. This applies to any stock symbol.

### Date/time of issue
All the time.

### What you expected to happen
Consistent data in the response just like it happens outside trading hours.

### What actually happened
Response contains bad data meaning '-1' in most of its relevant fields for a minute info.

### Other Information (sample code, links, etc.)
Is there another way to get this information ? Other API should be used instead ?
All I want is minute data for the current day at a given moment in time during trading hours.

**Comment by evancarter-iex** [comment]
Fixed with Iexcloud please see  https://iexcloud.io
