### ISSUE TITLE
3m Chart - VWAP out of range

### ISSUE THREAD

**Issue by massaroni** [iexg/IEX-API#53]
Sometimes the 3m charts have a VWAP that's out of the High/Low range for that day.  Is this a bug, or is it expected?  If this is expected, can you explain why this would happen, and when to expect it?

In this example, the vwap (48.7693) is lower than the daily low price (48.78).
[https://api.iextrading.com/1.0/stock/DMRM/chart/3m](https://api.iextrading.com/1.0/stock/DMRM/chart/3m)
...
{"date":"2017-08-10","open":48.8,"high":48.81,"low":48.78,"close":48.79,"volume":11676,"unadjustedVolume":11676,"change":-0.38,"changePercent":-0.773,"vwap":48.7693,"label":"Aug 10, 17","changeOverTime":-0.023027633159791724}
...

**Comment by massaroni** [comment]
and here's an example where the VWAP's higher than the High:

[https://api.iextrading.com/1.0/stock/CIZ/chart/3m](https://api.iextrading.com/1.0/stock/CIZ/chart/3m)
...
{"date":"2017-10-20","open":34.52,**"high":34.52**,"low":34.37,"close":34.4764,"volume":28886,"unadjustedVolume":28886,"change":0.0564,"changePercent":0.164,**"vwap":34.5333**,"label":"Oct 20","changeOverTime":0.03408518296340716}
...

**Comment by joshuablackburn-iex** [comment]
We are looking into this with our data provider and will keep you updated.

**Comment by Itsme23333** [comment]
I am experiencing the same issue, where vwap is higher than the high or lower than the low for a stock.  Do you have any more insight about this problem.

**Comment by evancarter-iex** [comment]
Closing. This should be fixed in https://iexcloud.io If it isnt please open a new issue. Thanks
