### ISSUE TITLE
Inconsistent data for stock in different endpoints

### ISSUE THREAD

**Issue by rportela** [iexg/IEX-API#533]
## Summary

We encountered different close prices for NETS when we query the "quote" endpoint and "chart". "Chart" seems to be the correct one. 

## Details

The api call to https://api.iextrading.com/1.0/stock/market/batch?symbols=nets&types=quote
shows close price of 2.34 and the call to https://api.iextrading.com/1.0/stock/nets/chart
shows close price of 2.39. 

![alt text](https://i.imgur.com/FoiolrW.png)
![alt text](https://i.imgur.com/DCMZABt.png)

### Date/time of issue

Oct 24th 2018 - 11h00 BRT

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=nets&types=quote
https://api.iextrading.com/1.0/stock/nets/chart

### What you expected to happen

I expected both values to be the same.

### What actually happened

The close price is different for 2018-10-23.

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud https://iexcloud.io
