### ISSUE TITLE
JSON /Symbols Data Type Inconsistency

### ISSUE THREAD

**Issue by piersbravery** [iexg/IEX-API#535]
## Summary
Within Reference Data:SYMBOLS the returned JSON data has an inconsistent field type: iexId. Most of the values returned as strings but some are numbers.  This leads to problems when decoding large numbers of these symbols.

### API URL

URL: https://api.iextrading.com/1.0/ref-data/symbols

### What you expected to happen

All JSON Symbols to  have the same variables names / types.  Particulary iexId which by default is iexId:String

### What actually happened

some JSON Symbols returned with the field iexId as a number instead of a string iexId:Number

### Other Information (sample code, links, etc.)

{"symbol":"ZUO","name":"Zuora Inc. Class A","date":"2018-10-25","isEnabled":true,"type":"cs","iexId":"14265"},{"symbol":"ZVV","name":"","date":"2018-10-25","isEnabled":true,"type":"N/A","iexId":"7907"},{"symbol":"ZVVV","name":"","date":"2018-10-25","isEnabled":true,"type":"N/A","iexId":"7908"},{"symbol":"ZVZZT","name":"NASDAQ TEST STOCK","date":"2018-10-25","isEnabled":true,"type":"N/A","iexId":"7909"},{"symbol":"ZWZZT","name":"NASDAQ TEST STOCK","date":"2018-10-25","isEnabled":true,"type":"N/A","iexId":"7910"},{"symbol":"ZXIET","name":"ZXIET Test Incorporated","date":"2018-10-25","isEnabled":true,"type":"N/A","iexId":"13391"},{"symbol":"ZXZZT","name":"NASDAQ TEST STOCK","date":"2018-10-25","isEnabled":true,"type":"N/A","iexId":"7911"},{"symbol":"ZYME","name":"Zymeworks Inc.","date":"2018-10-25","isEnabled":true,"type":"cs","iexId":"12759"},{"symbol":"ZYNE","name":"Zynerba Pharmaceuticals Inc.","date":"2018-10-25","isEnabled":true,"type":"cs","iexId":"10257"},{"symbol":"BTCUSDT","name":"Bitcoin USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000000},{"symbol":"EOSUSDT","name":"EOS USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000001},{"symbol":"ETHUSDT","name":"Ethereum USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000002},{"symbol":"BNBUSDT","name":"Binance Coin USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000003},{"symbol":"ONTUSDT","name":"Ontology USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000004},{"symbol":"BCCUSDT","name":"Bitcoin Cash USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000005},{"symbol":"ADAUSDT","name":"Cardano USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000006},{"symbol":"XRPUSDT","name":"Ripple USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000007},{"symbol":"TUSDUSDT","name":"TrueUSD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000008},{"symbol":"TRXUSDT","name":"TRON USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000009},{"symbol":"LTCUSDT","name":"Litecoin USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000010},{"symbol":"ETCUSDT","name":"Ethereum Classic USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000011},{"symbol":"IOTAUSDT","name":"MIOTA USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000012},{"symbol":"ICXUSDT","name":"ICON USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000013},{"symbol":"NEOUSDT","name":"NEO USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000014},{"symbol":"VENUSDT","name":"VeChain USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000015},{"symbol":"XLMUSDT","name":"Stellar Lumens USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000016},{"symbol":"QTUMUSDT","name":"Qtum USD","date":"2018-10-25","isEnabled":true,"type":"crypto","iexId":10000017}]

**Comment by covertbert** [comment]
I'll second the pain with this. The differences appear to be that standard symbols are strings but cryptocurrencies are integers.

It's very bad practice to have an API return field values of differing types and it causes pain for anyone using a strongly typed language.

**Comment by evancarter-iex** [comment]
This should be fixed with Iexcloud, https://iexcloud.io
