### ISSUE TITLE
Dividend API only produces dividend data until March 2018.

### ISSUE THREAD

**Issue by kondeg** [iexg/IEX-API#536]
## Summary
Using dividend endpoint, the API produces data only until March 2018. For example, https://api.iextrading.com/1.0/stock/aapl/dividends/1y  results in dividends only until February 2018.

## Details

Using dividend endpoint, the API produces data only until March 2018. For example, https://api.iextrading.com/1.0/stock/aapl/dividends/1y  results in dividends only until February 2018. Dividend data is not up to date.

### Date/time of issue

10/25/18

### API URL
https://api.iextrading.com/1.0/stock/aapl/dividends/1y
https://api.iextrading.com/1.0/stock/aapl/dividends/3m

### What you expected to happen

Expected up to date dividend data. For example:

Declared | Record | Payable | Amount | Type
-- | -- | -- | -- | --
Jul 31, 2018 | Aug 13, 2018 | Aug 16, 2018 | $.73 | Regular Cash
May 1, 2018 | May 14, 2018 | May 17, 2018 | $.73 | Regular Cash
Feb 1, 2018 | Feb 12, 2018 | Feb 15, 2018 | $.63 | Regular Cash
Nov 2, 2017 | Nov 13, 2017 | Nov 16, 2017 | $.63 | Regular Cash

### What actually happened
Only produces data until February

[{"exDate":"2018-02-09","paymentDate":"2018-02-15","recordDate":"2018-02-12","declaredDate":"2018-02-01","amount":0.63,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2017-11-10","paymentDate":"2017-11-16","recordDate":"2017-11-13","declaredDate":"2017-11-02","amount":0.63,"flag":"","type":"Dividend income","qualified":"Q","indicated":""}]

**Comment by GraceRg** [comment]
This issue has been reported numerous times since March 2018, with explanations varying from 'they are working with the vendor to improve the quality of information' to 'they are focusing their efforts on API 2.0'.  Lately, they simply seem to disregard any comments or posts regarding dividend history.
As an income investor, dividends are extremely important and the failure to address this issue means that i simply can't rely on their public data feed.

**Comment by evancarter-iex** [comment]
Please see #557. We have secured a new data provider which will fix a lot of these issues. It will be implemented in version 2.

**Comment by evancarter-iex** [comment]
This is fixed in iexcloud. https://iexcloud.io

**Comment by ModelsRUs** [comment]
there is nothing in the beta notes about this!

**Comment by evancarter-iex** [comment]
@ModelsRUs As per the note https://iexcloud.io is where you can find the updated v2 of the api.

**Comment by estrnod** [comment]
So is that the "beta" cloud api?  This still seems to be an issue there.

**Comment by evancarter-iex** [comment]
@estrnod I double checked AAPL and VZ both have up to date dividends in Cloud.

**Comment by estrnod** [comment]
As per the comment on Mar. 4, the note  https://iexcloud.io implies (as it only shows the "beta" URL) that this is the URL that should show the updated data.  https://cloud.iexapis.com/beta/stock/WMT/dividends/1y?token=... is still showing outdated data.  (See also my other issue #800).  (Shouldn't ALL the dividend data be continually up-to-date?  These don't get updated piecemeal, do they?)
