### ISSUE TITLE
TOPS/DEEP files for 10/26/2018

### ISSUE THREAD

**Issue by chris831** [iexg/IEX-API#539]
## Summary
TOPS/DEEP files for 10/26/2018 session are not available as of 9:10EST 10/29/2018

### What you expected to happen
Would expect file to be available on a T+1 basis as documented

### What actually happened
File is not available

**Comment by evancarter-iex** [comment]
They are starting to post. Sorry about the delay.

**Comment by chris831** [comment]
Thanks
