### ISSUE TITLE
503{"message": "We will be right back"}

### ISSUE THREAD

**Issue by ngyangjo** [iexg/IEX-API#54]
The title says it all. I'm getting this error while trying to request following url:

https://api.iextrading.com/1.0/stock/market/batch?types=quote&symbols=AAPL,FB.

I'm using Java8 and the funny thing is if I turn off the DefaultHostNameVerifier, which I've set to allow all connection, the above url works. 

Below is the piece of code I've in my class and with this code in place, I'm getting 503 error.
`HttpsURLConnection.setDefaultHostnameVerifier((p1,p2)->true);`

But if I remove this code, then the API works. Has anyone faced a similar issue? Is this something on my side or the server side?

**Comment by evancarter-iex** [comment]
It sounds like the setDefaultHostnameVerifier is upset that we use a wildcard cert for api.iextrading.com.  
It looks like its then stripping the SNI request for some reason (thats why you end up with the 503).

**Comment by ngyangjo** [comment]
Hmm ok, so can I expect a fix soon. I'm looking forward to using the API.

**Comment by evancarter-iex** [comment]
@ngyangjo Looks like the bug was fixed in OpenJDK, https://bugs.openjdk.java.net/browse/JDK-8144566 

Not sure about Oracle Java.

**Comment by evancarter-iex** [comment]
I believe this is an issue with OpenJDK. Closing, reopen if it reoccurs after updating OpenJDK.

**Comment by jlanawalt** [comment]
I was getting 503 responses on quote requests with Oracle Java 8 Update 131 (8u131), updating to Java 8 Update 151 (8u151) fixed it. I didn't test interim versions.

Java 8 Update 141 (8u141) change log mentions the Custom HostnameVerifier enables SNI extension issue, but we weren't setting a HostNameVerifier.
