### ISSUE TITLE
websocket feed does not push data, at least for USA symbols

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#540]
Started to happen yesterday. Maybe something related to clock change(winter time) ?

Regards,
Gabriel

**Comment by gabrieldodan** [comment]
Hmm it started but after a delay of about 15 minutes ...

**Comment by joshuablackburn-iex** [comment]
Is this still an issue?  We've updated the number of boxes, but think it may have been one bad box.
