### ISSUE TITLE
Please Include "Date Published" for Financial Reports

### ISSUE THREAD

**Issue by RayManZZZ** [iexg/IEX-API#541]
Hi,

I just wanted to ask if you can include the "**ReportDate**" & "**FiscalEndDate**" on the Financials like you do for Earnings?

Right now it only shows the Fiscal End Date, but not the date which the financials where published. 

(Referencing the data in: "/stock/aapl/financials" and "/stock/aapl/earnings")

**Comment by evancarter-iex** [comment]
This is included in the financials endpoint now.
