### ISSUE TITLE
Delay on websocket feed

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#542]
## Summary
The websocket feed start to push data with a delay of about 15 minutes.

### Date/time of issue
October 31, 2018

### API URL
https://ws-api.iextrading.com/1.0/tops

### What you expected to happen
Websocket feed to start push data immediately after 09:30 (New York timezone)

### What actually happened
The websocket feed start to push data around 09:45 (New York timezone)

### Other Information (sample code, links, etc.)
Seems the issue started to happen as of Monday October 29, 2018

Anyone else has this issue?

Thanks!

**Comment by joshuablackburn-iex** [comment]
Is this still an issue?  This may have been an issue with a single machine at a certain time.  All other servers look good.

**Comment by gabrieldodan** [comment]
works fine today too. the issue seems to be fixed
