### ISSUE TITLE
EBITDA for AAPL Key-Stats is Incorrect

### ISSUE THREAD

**Issue by exiao** [iexg/IEX-API#543]
## Summary
EBITDA is noted as 30.5B, which is not correct. For last 12 months, it is 84B. All of the financial numbers on the /stats endpoint are wrong (revenue, ebitda, gross profit, etc).

## Details
See https://api.iextrading.com/1.0/stock/aapl/stats
http://financials.morningstar.com/income-statement/is.html?t=AAPL&region=usa&culture=en-US

**Comment by rajivkbhatia** [comment]
Also note the previous issue I opened 

https://github.com/iexg/IEX-API/issues/528

**Comment by evancarter-iex** [comment]
Please see #557, we have a new data provider for version 2 which should help fix this problem.
