### ISSUE TITLE
Quote's 52weeklow return string instead of null when no value present

### ISSUE THREAD

**Issue by brettbs** [iexg/IEX-API#546]
## Summary
When executing some quotes week52Low is returning an empty string. I'm not sure when that would ever not be populated. But for some reason it is returning an empty string "". It should return null if there isn't a value. I have noticed this for the past week only. 

## Details

https://api.iextrading.com/1.0/stock/AGF/quote

Yields:
`
{
  "symbol": "AGF",
  "companyName": "DB Agriculture Long ETN due April 1 2038",
  "primaryExchange": "NYSE Arca",
  "sector": "",
  "calculationPrice": "close",
  "open": 10.09,
  "openTime": 1540841909394,
  "close": 11.05,
  "closeTime": 1541188800134,
  "high": null,
  "low": null,
  "latestPrice": 11.05,
  "latestSource": "Close",
  "latestTime": "November 2, 2018",
  "latestUpdate": 1541188800134,
  "latestVolume": 0,
  "iexRealtimePrice": null,
  "iexRealtimeSize": null,
  "iexLastUpdated": null,
  "delayedPrice": 8.775,
  "delayedPriceTime": 1541189400001,
  "extendedPrice": null,
  "extendedChange": null,
  "extendedChangePercent": null,
  "extendedPriceTime": null,
  "previousClose": 11.05,
  "change": 0,
  "changePercent": 0,
  "iexMarketPercent": null,
  "iexVolume": null,
  "avgTotalVolume": 336,
  "iexBidPrice": null,
  "iexBidSize": null,
  "iexAskPrice": null,
  "iexAskSize": null,
  "marketCap": 1049750,
  "peRatio": null,
  "week52High": 11.86,
  "week52Low": "",
  "ytdChange": 0.09890109890109894
}
`

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud https://iexcloud.io
