### ISSUE TITLE
Stock Chart Day - Incorrect change_percent value - CCT - 2017-11-14

### ISSUE THREAD

**Issue by michaeldrennen** [iexg/IEX-API#548]
## Summary
**CCT** on **2017-11-14** shows a **change_percent** of **17631124**

That's obviously not right.

If you look at this screen capture from Yahoo Finance:

https://imgur.com/a/ENTpQvJ

You can see a bunch of missing data before **Nov 14, 2017** for this ticker. It feels like that missing data is causing an issue with your code that calculates the **change_percent**.

## Details
`"date":"2017-11-14","open":16.2738,"high":16.7967,"low":14.9304,"close":15.8681,"volume":1658846,"unadjustedVolume":1658846,"change":15.868,"changePercent":17631124,"vwap":15.7539,"label":"Nov 14, 17","changeOverTime":0}`

### Date/time of issue
Any time. This data is consistently wrong on any API end point that includes that data point.

### API URL
https://api.iextrading.com/1.0/stock/cct/chart/1y

### What you expected to happen
I expected to see a change_percent value that makes logical sense.
If change_percent can't be calculated, in a case like this, then a null value should be returned.

### What actually happened
I received a very large number for the change_percent value that is misleading and not usable.

### Other Information (sample code, links, etc.)
If you look at the 5y chart, you can see the previous data point is on: 2016-03-04
There are a lot of missing data points for this stock ticker.
Perhaps when your system is calculating the change_percent, it's seeing a null (missing) value for the previous price which is borking the calculation.

**Comment by evancarter-iex** [comment]
@michaeldrennen Is this still an issue with IEXCloud data?

**Comment by evancarter-iex** [comment]
Closing. If this is an issue with https://iexcloud.io please create a new issue.
