### ISSUE TITLE
The output is not as expected when both the format=csv option and the filter option are used

### ISSUE THREAD

**Issue by Itsme23333** [iexg/IEX-API#549]
## Summary
For several endpoints, the output is not as expected when both the format=csv option and the filter option are used.

## Details
The filter option does not seem to work as expected for an output format of csv.  The expected result would be that this option would work, or if they are fundamentally incompatible, then the documentation should mention that fact.

### Date/time of issue
November 5th, 2018.

### API URL
https://api.iextrading.com/1.0/stock/aapl/stats?format=csv?filter=marketcap
https://api.iextrading.com/1.0/stock/aapl/stats?filter=marketcap?format=csv

### What you expected to happen
For either
https://api.iextrading.com/1.0/stock/aapl/stats?format=csv?filter=marketcap
or
https://api.iextrading.com/1.0/stock/aapl/stats?filter=marketcap?format=csv
I expected
986564495280
OR
That the documentation would indicate that the two options are incompatible.

### What actually happened
For 
https://api.iextrading.com/1.0/stock/aapl/stats?format=csv?filter=marketcap
I got
{"companyName":"Apple Inc.","marketcap":986564495280,"beta":1.247051,"week52high":233.47,"week52low":150.24,"week52change":25.285301,"shortInterest":0,"shortDate":0,"dividend Rate":2.92,"dividendYield":1.4073646,"exDividendDate":"2018-11-08 00:00:00.0","latestEPS":0,"latestEPSDate":"2017-09-30","sharesOutstanding":4754986000,"float":4745179314,"returnOnEquity":45.37,"consensusEPS":2.17,"numberOfEstimates":10,"EPSSurpriseDollar":null,"EPSSurprisePercent":7.8341,"symbol":"AAPL","EBITDA":30509000000,"revenue":88293000000,"grossProfit":33912000000,"cash":77153000000,"debt":122400000000,"ttmEPS":11.030000000000001,"revenuePerShare":19,"revenuePerEmployee":717829,"peRatioHigh":114.1,"peRatioLow":0,"returnOnAssets":16.16,"returnOnCapital":null,"profitMargin":22.4,"priceToSales":5.2130194,"priceToBook":7.43,"day200MovingAvg":191.54465,"day50MovingAvg":221.1598,"institutionPercent":54.2,"insiderPercent":null,"shortRatio":null,"year5ChangePercent":2.018729567050628,"year2ChangePercent":0.8217818304745431,"year1ChangePercent":0.34065650038769707,"ytdChangePercent":0.21829056476587178,"month6ChangePercent":0.28274483158564384,"month3ChangePercent":0.0787961034808176,"month1ChangePercent":-0.06028352733366549,"day5ChangePercent":-0.022427440633245473,"day30ChangePercent":-0.06028352733366549}

For 
https://api.iextrading.com/1.0/stock/aapl/stats?filter=marketcap?format=csv
I got
{}

### Other Information (sample code, links, etc.)
I also saw the same issue with:

https://api.iextrading.com/1.0/ref-data/symbols?filter=symbol?format=csv
https://api.iextrading.com/1.0/ref-data/symbols?format=csv?filter=symbol

**Comment by mutluit** [comment]
You have a bug in your URL: you used twice the "?". You should replace the 2nd to "&"

**Comment by Itsme23333** [comment]
Thank you.
