### ISSUE TITLE
Is subscribing all 8458 stocks in single websocket a recommended way?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#55]
Currently, we plan to build a stock alert monitoring system, based on IEX websocket API - https://ws-api.iextrading.com/1.0/last

We assume total user interested stocks, will cover entire 8458 stocks supported by IEX.

I was wondering, is using single websocket, to subscribe all 8458 stocks a good practice. (I had tried this. It works so far)

Or, should I use multiple websockets, with

- 1st websocket will subscribe 1st stock to 999th stock.
- 2nd websocket will subscribe 1000st stock 1999th stock.
- 3rd websocket will subscribe 2000nd stock 2999th stock.
- ...

May I know, which way is the recommended approach?

Thank you.

**Comment by gabrieldodan** [comment]
Out of documentation "Subscribe to `firehose` to return all symbols" ;) https://iextrading.com/developer/docs/#last

**Comment by joshuablackburn-iex** [comment]
'firehose' is the way to stream all stocks for TOPS.  TOPS is much less volume than DEEP, so getting all stocks over one connection should be fine.  You could always maintain two connections for redundancy, but you'd need to deconflict data on your side.  DEEP does allow you to subscribe to more than one symbol on one connection, but you can only send one symbol per subscription message.
