### ISSUE TITLE
Websocket API does not works at all

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#551]
The websocket API does not work at all today for me, no data are pushed. Someone else experience same issue?

Thanks!

**Comment by evancarter-iex** [comment]
Im looking into this now

**Comment by evancarter-iex** [comment]
This appears to be working for us. Is this still an issue?

**Comment by gabrieldodan** [comment]
@evancarter-iex still an issue ...More details, I am connecting to this endpoint ``https://ws-api.iextrading.com/1.0/tops`` then i subscribe to ``firehose`` channel. Connection is established but I get no message...

**Comment by evancarter-iex** [comment]
@gabrieldodan hmm working here..After the markets close Ill kick all the boxes, might be a bad box in the bunch. Sorry about that

**Comment by gabrieldodan** [comment]
ok, thank you!

**Comment by jkasun** [comment]
Not working for me either

**Comment by evancarter-iex** [comment]
Kicked the boxes. Let me know if you have problems tomorrow.

**Comment by gabrieldodan** [comment]
@evancarter-iex works fine today. thank you!
