### ISSUE TITLE
Prices wrong and inconsistent - many tickers

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#553]
## Summary
After the close today, many symbols had incorrect and/or inconsistent closing prices.

## Details
Here is just one example.  Errata:
1) latestPrice of 65.995 is not the official close price
2) calculationPrice says "tops" as late at 10:40pm - should be "close".  
3) the "close" price shown is 64.48 - which was prior day's close
4) the "closeTime" is also from prior day
5) delayedPrice should be official close at this time of day, but it is 66.02 instead of 66.01
6) the /previous endpoint shows data for today's close - which is fine.  But, if /previous endpoint is for today then "close" and "closeTime" in /quote endpoint should be too (point #3,#4).
7) the /ohlc endpoint "close" price and time is from prior day (inconsistent with /previous endpoint too). The /ohlc shouldn't be older than /previous.

{
  "SBUX": {
    "quote": {
      "symbol": "SBUX",
      "companyName": "Starbucks Corporation",
      "primaryExchange": "Nasdaq Global Select",
      "sector": "Consumer Cyclical",
      "calculationPrice": "tops",
      "open": 64.3,
      "openTime": 1541514600605,
      "close": 64.48,
      "closeTime": 1541451600230,
      "high": 66.08,
      "low": 64.25,
      "latestPrice": 65.995,
      "latestSource": "IEX real time price",
      "latestTime": "3:59:54 PM",
      "latestUpdate": 1541537994133,
      "latestVolume": 15748568,
      "iexRealtimePrice": 65.995,
      "iexRealtimeSize": 100,
      "iexLastUpdated": 1541537994133,
      "delayedPrice": 66.02,
      "delayedPriceTime": 1541537980503,
      "extendedPrice": 65.995,
      "extendedChange": 0,
      "extendedChangePercent": 0,
      "extendedPriceTime": 1541537994133,
      "previousClose": 64.48,
      "change": 1.515,
      "changePercent": 0.0235,
      "iexMarketPercent": 0.02304,
      "iexVolume": 362847,
      "avgTotalVolume": 13544318,
      "iexBidPrice": 0,
      "iexBidSize": 0,
      "iexAskPrice": 0,
      "iexAskSize": 0,
      "marketCap": 86394054500,
      "peRatio": 28.08,
      "week52High": 66.08,
      "week52Low": 47.37,
      "ytdChange": 0.1621854610987397
    },
    "previous": {
      "symbol": "SBUX",
      "date": "2018-11-06",
      "open": 64.3,
      "high": 66.08,
      "low": 64.25,
      "close": 66.01,
      "volume": 16065429,
      "unadjustedVolume": 16065429,
      "change": 1.53,
      "changePercent": 2.373,
      "vwap": 65.5451
    },
    "ohlc": {
      "open": {
        "price": 64.3,
        "time": 1541514600605
      },
      "close": {
        "price": 64.48,
        "time": 1541451600230
      },
      "high": 66.08,
      "low": 64.25
    }
  }
}

### Date/time of issue
10:40pm eastern

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=sbux&types=quote,previous,ohlc

### What you expected to happen
I expected to see correct closing price reflected properly and consistently.  

### What actually happened
As described previously

### Other Information (sample code, links, etc.)
Prior to 10:40pm but after 5pm the above odd mix of prices also occurred.  But, in this example, the official close of 66.01 did not appear in any of the 3 endpoints as the /previous endpoint wasn't updated to today's until sometime between 5pm and 10:40pm.

I have other debug dumps as above for other tickers and times should that be helpful.

**Comment by evancarter-iex** [comment]
Thanks for the detailed report we are looking into this.

**Comment by McQgit** [comment]
Perhaps a couple of the tickers I follow had issues in the following days.  But, the issue of nearly all tickers having problems as described here did not.

So, it looks largely like a one-off.  Have you added more robust validity checks to catch such errata earlier?

Should V2 be more reliable?  Over the past year I have submitted a variety of similar issues.  Am hoping these are helping you provide a higher quality product.

**Comment by evancarter-iex** [comment]
Thanks for the update.

Yes issues that are created here are definitely a help for us and yes we are adding additional checks as we go and version 2 should be more reliable, for a variety of reasons.
