### ISSUE TITLE
institutionPercent is greater than 100%

### ISSUE THREAD

**Issue by brockelmore** [iexg/IEX-API#554]
## Summary

Using https://api.iextrading.com/1.0/stock/aspn/stats, and others like EPM, GSS, PFNX, SYN, AYI, ZNGA, ZUMZ, etc... Over a hundred. I accessed with batch API, but also double checked with the /stock/<stockSymbol>/stats.

## Details

Institutional ownership percentage should never be greater than 100%, ASPN was at 108.5%, ZNGA was at 119.8%, and ZUMZ was at 134.1%. 

### Date/time of issue

23:11 EST Nov 6, 2018

### API URL

https://api.iextrading.com/1.0/stock/ASPN/stats
https://api.iextrading.com/1.0/stock/market/batch?symbols=ASPN&types=stats

(or others)

### What you expected to happen

Expected % institutional ownership for ASPN to be ~70.33 per nasdaq.com, or at the very least less than 100% as greater than 100% does not make sense.

### What actually happened

% of institutional ownership was > 100% which does not make sense. There are plenty of others that have a % greater than 100.

**Comment by brockelmore** [comment]
They seemed to have fixed it? Not sure how reliable it is though. I will leave open purely because I don't have trust in the reliability/accuracy of the data.

**Comment by evancarter-iex** [comment]
See https://github.com/iexg/IEX-API/issues/557 for an update to this. We are switching data providers in the new API.

**Comment by evancarter-iex** [comment]
No longer an issue in https://iexcloud.io
