### ISSUE TITLE
How can i pull quarter AND annual financials in one call? / Improvement Suggestions

### ISSUE THREAD

**Issue by stanley3333** [iexg/IEX-API#555]
## Summary
First of all: Thank you for this great API!

Here is one question and some suggestions for improvement:
At the moment it is either annual OR quarter. How is it possible to pull quarter AND annual financials in one call?
 
Other Suggestions for Improvements (I know some are already planned):

-Financials Longer History (10Y Annual, 8Q Quaterly) would be great

-division into IncomeStatement, Cash Flow, Balance Sheet

-more datafields (FCF, Cash Investing, Cash from Financing, ...) 
https://financials.morningstar.com/income-statement/is.html?t=MSFT&culture=en&ops=clear
is a good reference. 

-Future Analysts EPS/Sales-Estimates for Q1, Q2, Fiscal Year 1 and 2, and EPS-Long Term Growth Rate Estimate 

### API URL
https://api.iextrading.com/1.0/stock/aapl/financials?period=annual

**Comment by brapplecache** [comment]
I would like to second this. Would be great to have historical financials, 10Y at the least, more would be even better. The income statement, cash flow, and balance sheet division part isn't critical, but would be nice to have it like that in the API docs... just easier to reference. From the balance sheet, I see operating expenses, with R&D, but don't see depreciation or SGA. Nice api, thanks.

**Comment by dmikester1** [comment]
Can you grab a specific quarter with the API instead of all 4 quarters?

**Comment by evancarter-iex** [comment]
Please checkout https://iexcloud.io, we are currently adding features there, including more historical data.
