### ISSUE TITLE
OHLC endpoint not consistent with chart endpoint data availability

### ISSUE THREAD

**Issue by mikemags1** [iexg/IEX-API#556]
## Summary

OHLC endpoint data is not as up-to-date as chart endpoint data

### Date/time of issue

11/07/2018 11:51 AM CST

### API URL

https://api.iextrading.com/1.0/stock/gpro/ohlc
vs 
https://api.iextrading.com/1.0/stock/gpro/chart/1m

### What you expected to happen

OHLC endpoint's close price should match chart endpoint's last day.

### What actually happened

OHLC endpoint's close price was 2 days old, but the chart endpoint had yesterday's close

OHLC showed 
{
"open": {
"price": 5.66,
"time": 1541601000831
},
"close": {
**"price": 5.57,**
**"time": 1541451600543** //[11/05/2018 3:00:00.543 PM CST]
},
"high": 5.945,
"low": 5.62
}

CHART showed
...{
**"date": "2018-11-05",**
"open": 5.48,
"high": 5.71,
"low": 5.17,
**"close": 5.57,**
"volume": 9527405,
"unadjustedVolume": 9527405,
"change": 0.13,
"changePercent": 2.39,
"vwap": 5.4079,
"label": "Nov 5",
"changeOverTime": -0.12421383647798742
},
{
**"date": "2018-11-06",**
"open": 5.52,
"high": 5.7,
"low": 5.46,
**"close": 5.66,**
"volume": 6254410,
"unadjustedVolume": 6254410,
"change": 0.09,
"changePercent": 1.616,
"vwap": 5.6132,
"label": "Nov 6",
"changeOverTime": -0.11006289308176102
}

**Comment by evancarter-iex** [comment]
@mikemags1 Is this still a problem with IEXCloud?

**Comment by mikemags1** [comment]
@evancarter-iex I haven't migrated over to IEXCloud yet. I tried to reproduce the above issue with IEX API, and the issue was not present for the ~850 tickers that I spot checked. I cannot say if it is fixed as a whole though.

I just ran a script to test IEXCloud's /5d endpoint (so as not to eat up my message quota) with a 50 ticker subset, also comparing that data to IEX API data. For 50 stocks, the following endpoints all seemed consistent this time:

https://api.iextrading.com/1.0/stock/<ticker>/ohlc
https://api.iextrading.com/1.0/stock/<ticker>/chart/1m
https://cloud.iexapis.com/beta/stock/<ticker>/ohlc
https://cloud.iexapis.com/beta/stock/<ticker>/chart/5d

As an aside... seeing that even running just this test used up ~0.5% of my free quota, I'm a little disappointed by how high that 0.5% is. Makes me nervous for my expected monthly quota when I finally do migrate to IEXCloud.

I'll leave it up to you if you would like to mark this as closed or if you believe it requires further testing of the 8.5k tickers IEX supports.

**Comment by evancarter-iex** [comment]
@mikemags1 Thanks appreciate the follow up. Im going to close this issue since we did do some work a little bit ago that should have solved this problem

As per your free quota issue, we do have a sandbox that you can use to test different ways to optimize your calls to prevent running over.
