### ISSUE TITLE
How did you build your docs?

### ISSUE THREAD

**Issue by Benjamin-Lee** [iexg/IEX-API#558]
Hi,

No issue here, just really impressed with the quality of your documentation site. I'm working on an unrelated project (open source laboratory automation!) and was wondering how you made it. 

I tried looking in your source and couldn't get any hints. It doesn't look like anything I've seen before, so I'd appreciate any information you can share.

Thanks,
Benjamin

**Comment by cbrandalise** [comment]
https://github.com/lord/slate
