### ISSUE TITLE
Include latestVolume on tops websocket channel

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#56]
Hi,

Would be possible to include latestVolume on tops websocket channel? Currently the websocket provide only IEX volume , would be very useful to provide latestVolume too. By latestVolume  I mean same data returned by quote API endpoint `/stock/aapl/quote`

Thank you!
Gabriel

**Comment by joshuablackburn-iex** [comment]
Definitely a great idea.  We are in the process of testing HTTP Streaming, and hoping to roll out later in the month.  This should be a friendlier, and more standards compliant way to stream data from us.  We'd like to include stock quotes in that streaming, so you get a more complete data set.

**Comment by gabrieldodan** [comment]
I see , sounds good. Thanks!

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud https://iexcloud.io
