### ISSUE TITLE
ERROR: Specific Date Query

### ISSUE THREAD

**Issue by jackspraggdw** [iexg/IEX-API#560]
Getting...

"ValueError: Invalid range: '20181107'. Valid chart types are , 5y, 2y, 1y, ytd, 6m, 3m, 1m, 1d, YYYYMMDD (int), datetime, dynamic" 

...when trying to query specific date, such as... 

test_data = iex.Stock('AABA').chart(range=20181107)

All other range types work fine (datetime doesn't work either), but I am unable to make the call so that this error will go away.  Specifically states that YYYYMMDD format is necessary and in INT mode.  This doesn't work with parentheses or quotes, either.  

Please help.

Thanks.

Danny

**Comment by evancarter-iex** [comment]
I think this is a bug in the library you are using, not IEX API. Please file a bug with them.
