### ISSUE TITLE
Has the "Previous"Endpoint already been deprecated?

### ISSUE THREAD

**Issue by bb10128** [iexg/IEX-API#562]
## Summary

Ever since 11/5/2018, the data from "Previous" endpoint are no-longer corporate action adjusted.  November 2, 2018 was the last day whereas the data were still adjusted.

Is the "Previous" endpoint already deprecated?  

## Details

I took a few snapshots of the "Previous" endpoint over the last a few days.  None of the previous day open/high/low/close were adjusted for any corporate actions, except, ironically :)
"bogus" adjustments on IBKR because it is listed on IEX.

Here is one example:

ZION has a dividend of 0.3 with ex-date = 11/13.
But the "Previous" endpoint data for ZION on 11/13.
2018-11-12|ZION|50|50.43|49.34|49.44|1922853|1922853|-0.72|-1.435|49.7902
whereas the prices were un-adjusted.

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud https://iexcloud.io
