### ISSUE TITLE
I'm only interested in stocks that have call and put options

### ISSUE THREAD

**Issue by bchengwa** [iexg/IEX-API#567]
## Summary
I'm only interested in stocks that provide call and put options. Does IEX have any endpoints that would provide this information? I could not find any but hoping I'm just missing it.

**Comment by nawaralobaidi** [comment]
I have the same interest in Options, I wonder if I can get the options contracts volume and strike prices from IEX ?

**Comment by evancarter-iex** [comment]
@bchengwa @nawaralobaidi Option data has been deployed in IEX Cloud https://iexcloud.io https://iexcloud.io/docs/api/#options
