### ISSUE TITLE
API call that returns intraday data for a range of dates (more than 1 day)?  Please help.

### ISSUE THREAD

**Issue by byramjis** [iexg/IEX-API#568]
## Summary
I looked through other threads and didn't see my answer.  If this has already been discussed I apologize.  I am hoping it's possible to get intraday data (1, 5, 30 minute intervals) for more than a 1 day period.   

## Details
I saw solutions for how to get intraday data for present/current day at set intervals, and for how to do get the same for a specific day in the past.  I didn't see a way to call for a stock price for a specific range set in days or months at a chart interval set in minutes. 

In my perfect world it would look something like this (https://api.iextrading.com/1.0/stock/aapl/chart/60d?chartInterval=5m) and this would get me a chart of 60 days of Apple's stock price at 5 minute intervals.  Is it possible to do what I am asking?

**Comment by evancarter-iex** [comment]
https://iexcloud.io has this function
