### ISSUE TITLE
Dividends of international stocks

### ISSUE THREAD

**Issue by raulinho6** [iexg/IEX-API#569]
Is it possible to become the dividends of international stocks or it only works for US Stocks?

**Comment by atisharma** [comment]
I would also like international stocks dividend data. Adjusted data is provided for (e.g.) LSE stocks, but not separate dividend data.

**Comment by compengi** [comment]
Is there any plan to be able to access dividends of international symbols? I'm keen to have it for my project. Especially that since 2019-03-12 update you support international ref data.

**Comment by joshuablackburn-iex** [comment]
It's in the works and we will be sending out official communication in the coming weeks.

**Comment by mukinabis** [comment]
> It's in the works and we will be sending out official communication in the coming weeks.

Do you have any news?

**Comment by joshuablackburn-iex** [comment]
We sent out multiple communications detailing all the new data. This went live December 1.

**Comment by mukinabis** [comment]
> We sent out multiple communications detailing all the new data. This went live December 1.

@joshuablackburn-iex I read that post, but there was no information about international dividends.
