### ISSUE TITLE
Need API call to check if the market is open or not

### ISSUE THREAD

**Issue by pvanny1124** [iexg/IEX-API#570]
## Summary

Would be nice to have a simple api to check whether the market is currently open or not. This would help devs skip having to cache certain date information on the backend of things.

### Date/time of issue

11/30/18 2.25am

### API URL
n/a

### What you expected to happen

get true or false if the market is open or not

### What actually happened

n/a

**Comment by lars670** [comment]
Good idea, especially if it could be done as a subscription, also for other exchange states than open/close

**Comment by pvanny1124** [comment]
> Good idea, especially if it could be done as a subscription, also for other exchange states than open/close

Absolutely. I had to find another way with webscraping which was tedious but gets the job done. I found this link online that you could curl to retrieve the value inside of the <status> block which returns a 0 if the market is closed or 1 for when it's open. Executing that curl command and then taking the result and parsing the xml to json will get you a nicely formatted object that you can index to get what we're looking for. The only problem with this method is that the exec function creates a child process that when closing out of node, for example, would still run under the hood as node... (check process list). I don't have too much experience with handling processes with nodejs, so maybe someone could improve this? Also, I'm posting the code I have so that it can help anyone out there :)


`
const DOMParser         = require('xmldom').DOMParser;
const util                     = require('util');
const exec              = require('child_process').exec;
const parseString       = require('xml2js').parseString;


var text, parser, xmlDoc;
parser = new DOMParser();

const command = "curl \"http://wu-quotes.apple.com/dgw?imei=42&apptype=finance\" -H \"Content-type: text/xml\" -d \"<?xml version='1.0' encoding='utf−8'?><request devtype='Apple_OSX' deployver='APPLE_DASHBOARD_1_0' app='YGoAppleStocksWidget' appver='unknown' api='finance' apiver='1.0.1' acknotification='0000'><query id='0' timestamp='`date +%s000`' type='getquotes'><list><symbol>GE</symbol></list></query></request>\"";

child = exec(command, function(error, stdout, stderr){

            //convert stdout into xml
            xmlDoc = parser.parseFromString(stdout,"text/xml");
            
            //turn xmlDoc into JSON
            parseString(xmlDoc, function (err, result) {
              
              inspect(result) //Check output on console

              //check status code that tells you whether the market is open or not.
              console.log(result.response.result[0].list[0].quote[0].status[0]); 
            });

            if(error !== null)
            {
                console.log('exec error: ' + error);
            }

});`

**Comment by mutluit** [comment]
Extend the idea to market hours of the day to get the market hours with PreMarket Hours, RegularMarket Hours, AfterMarket Hours.

Or even better make it possible for any given single date YYYY-MM-DD, ie. also for a past or future date.

Thx

**Comment by martyh1** [comment]
This says "fixed with IEX cloud".  Is there an API that returns a boolean for if the market is open/closed?  I can't find one.
