### ISSUE TITLE
Chart 1d does not return same date format

### ISSUE THREAD

**Issue by sanderbrauwers** [iexg/IEX-API#571]
## Summary
chart for 1d shows different date format than the other charts (1m,ytd,5d)
It is inconsistent

### Date/time of issue
2018-11-30

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/1d

### What you expected to happen
"date":"2018-01-02"

### What actually happened
"date":"20180102"

**Comment by evancarter-iex** [comment]
This is fixed in v1 of the https://iexcloud.io api
