### ISSUE TITLE
Max number of symbols in a web batch request

### ISSUE THREAD

**Issue by mutluit** [iexg/IEX-API#572]
## Summary
This is not an issue, just a question:

When requesting batch quotes via web ("/stock/market/batch?symbols=...") is there an upper limit in the number of symbols per request? I tried 255 and it worked, but I wonder how far one can go.

**Comment by joshuablackburn-iex** [comment]
It maxes out at 100 symbols.  If you pass more than 100 we will only return data for the first 100.
