### ISSUE TITLE
AMZN Debt Reported as: "Null"

### ISSUE THREAD

**Issue by drcrook1** [iexg/IEX-API#573]
## Summary

https://api.iextrading.com/1.0/stock/amzn/financials?period=annual 

debt is reported as null.

### Date/time of issue

12/3/2018

### API URL

https://api.iextrading.com/1.0/stock/amzn/financials?period=annual

### What you expected to happen

all fields populated correctly

### What actually happened

All fields associated to debt are reported as "null"

**Comment by slydero** [comment]
I think this is NASDAQ specific. I have the same issue with other stats and was told that NASDAQ stopped supplying certain info. Haven't heard if/when this data will start flowing again.

**Comment by drcrook1** [comment]
Hrm; this is screwing up my night jobs.  It would be great if the old values were left if new bad values were received.

**Comment by evancarter-iex** [comment]
This is fixed in IEX Cloud. If you havent already you can signup for the beta here: 

https://iexcloud.io/
