### ISSUE TITLE
Chart 1d returning empty object

### ISSUE THREAD

**Issue by anarmanafov1** [iexg/IEX-API#575]
## Summary
The following endpoint returns an empty object regardless of what stocks are inputted. 
Issue is not stock specific.

https://api.iextrading.com/1.0/stock/aapl/chart/1d

### Date/time of issue
2018-12-05 4:00pm

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/1d

### What you expected to happen
An object is expected with intraday stock data broken down by minutes.

### What actually happened
An empty object was returned.

**Comment by sheraztariq147** [comment]
Facing same issue. Have anyone resolved this issue?

**Comment by sheraztariq147** [comment]
@markdmurray thanks for response. and why market was closed?

**Comment by markdmurray** [comment]
Death/funeral of George H. W. Bush(former US President)

**Comment by sheraztariq147** [comment]
@markdmurray  thanks man!
