### ISSUE TITLE
DEEP binary parser

### ISSUE THREAD

**Issue by vovalev** [iexg/IEX-API#576]
## Summary
Hi!

There is a whole bunch of historical data available on the web page of the IEX. Can you add some functionality to parse these files?

In R would be perfect!

Thank you very much!

Vladimir

**Comment by vfrazao-ns1** [comment]
I wrote a tool in Python to parse the binary files: https://github.com/vfrazao-ns1/IEXTools

I think I saw another package on Github in Java as well.

**Comment by vslee** [comment]
The Java one is here: https://github.com/WojciechZankowski/iextrading4j-hist

**Comment by profimedica** [comment]
Please create a C# implementation, I was unable to find any. 
Other mentions: https://github.com/QuantConnect/Lean/issues/2178

**Comment by vslee** [comment]
@profimedica, being a C# person myself, I wouldn't hold out hope for someone making a C# version. The approach I have taken is to use the Java version, and then bulk inserting it into Sql Server. You can then use Entity Framework Core to easily access it in C#.

**Comment by profimedica** [comment]
I can download and decompress with 7zip. I will write a simple parser as well.

>     public class IexDownloader
>     {
>         public string UrlBase = "https://api.iextrading.com/1.0/hist?date=";
>         public string DestinationFolder = "C:\\Archive\\Stock\\";
>         public string SevenZipPath = "C:\\Program Files\\7-Zip\\7z.exe";
>         public IexDownloader()
>         {
>             if (!Directory.Exists(DestinationFolder))
>             {
>                 Directory.CreateDirectory(DestinationFolder);
>             }
>         }
>         public async Task<string> GetAsync(string uri)
>         {
>             HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
>             request.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
>             try
>             {
>                 using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
>                 using (Stream stream = response.GetResponseStream())
>                 using (StreamReader reader = new StreamReader(stream))
>                 {
>                     return await reader.ReadToEndAsync();
>                 }
>             }
>             catch (Exception ex)
>             {
> 
>             }
>             return null;
>         }
> 
>         public async Task<string> IexDownloadeDate(DateTime date)
>         {
>             if(date == DateTime.MinValue)
>             {
>                 date = DateTime.Today.AddDays(-1).Date;
>             }
>             string filePath = DestinationFolder + date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture) + ".gzip";
>             if (File.Exists(filePath))
>             {
>                 return filePath + ".data";
>             }
>             // Create a new WebClient instance.
>             using (WebClient myWebClient = new WebClient())
>             {
>                 string links = await GetAsync(UrlBase + date.ToString("yyyyMMdd", CultureInfo.InvariantCulture));
>                 if (!string.IsNullOrEmpty(links))
>                 {
>                     List<IexLinks> urls = JsonConvert.DeserializeObject<List<IexLinks>>(links);
>                     myWebClient.DownloadFile(urls[0].Link, filePath);
>                 }
>             }
>             ExtractFile(filePath, DestinationFolder);
>             return filePath;
>         }
> 
>         public void ExtractFile(string sourceArchive, string destination)
>         {
>             try
>             {
>                 ProcessStartInfo pro = new ProcessStartInfo();
>                 // pro.WindowStyle = ProcessWindowStyle.Hidden;
>                 pro.FileName = SevenZipPath;
>                 pro.Arguments = string.Format("x \"{0}\" -y -o\"{1}\"", sourceArchive, destination);
>                 Process x = Process.Start(pro);
>                 x.WaitForExit();
>             }
>             catch (System.Exception Ex)
>             {
>                 //handle error
>             }
>         }
>     }
> 
>     public class IexLinks
>     {
>         public string Link { get; set; }
>         public string Feed { get; set; }
>         public string Size { get; set; }
>         public string Date { get; set; }
>     }

**Comment by vslee** [comment]
Sounds good, I look forward to seeing your parser!

**Comment by timpaine-iex** [comment]
closing as stale
