### ISSUE TITLE
Peers endpoint no longer returning peers data

### ISSUE THREAD

**Issue by zadamsr** [iexg/IEX-API#578]
## Summary
The /peers used to return a list of peers in the form of symbols, but it no longer does this. For AAPL, for example, I just get an array that contains one element: ["XLK"]. You no longer get the decently sized list of tech related peers. 

### Date/time of issue
12-10-18 8PM

### API URL
https://api.iextrading.com/1.0/stock/<stock>/peers

### What you expected to happen
The peers endpoint should return with a list of peers for whichever symbol is used as a parameter. 

### What actually happened
The peers list is not returning back fully.

**Comment by evancarter-iex** [comment]
This appears to be working for us. Let us know if its still not.
