### ISSUE TITLE
Official Price returns an empty object

### ISSUE THREAD

**Issue by austinbv** [iexg/IEX-API#579]
## Summary
The [official price](https://iextrading.com/developer/docs/#official-price) REST API returns an empty object (`{}`) and the websocket returns nothing when subscribed

## Details
```bash
curl https://api.iextrading.com/1.0/deep/official-price?symbols=snap
# {}
```
```javascript
var io = require("socket.io-client")("https://ws-api.iextrading.com/1.0/deep")
io.on("message", console.log)
io.emit("subscribe", JSON.stringify({symbols: ["snap"], channels: ["officialprice"]}))
// Nothing returned

io.emit("subscribe", JSON.stringify({symbols: ["snap"], channels: ["deep"]}))
// {"symbol":"SNAP","messageType":"securityevent","data":{"securityEvent":"MarketClose","timestamp":1544562000000},"seq":2}
// {"symbol":"SNAP","messageType":"ophaltstatus","data":{"isHalted":false,"timestamp":1544530879993},"seq":1}
// {"symbol":"SNAP","messageType":"tradingstatus","data":{"status":"T","reason":"    ","timestamp":1544530879993},"seq":1}
// {"symbol":"SNAP","messageType":"ssr","data":{"isSSR":false,"detail":" ","timestamp":1544530879993},"seq":1}
// {"symbol":"SNAP","messageType":"book","data":{"bids":[],"asks":[]},"seq":2590}
// {"symbol":"SNAP","messageType":"trades","data":{"price":5.7400,"size":100,"tradeId":1228654707,"isISO":false,"isOddLot":false,"isOutsideRegularHours":false,"isSinglePriceCross":false,"isTradeThroughExempt":false,"timestamp":1544561999452},"seq":1456}
```
As you can see the full feed has no official price or key for the symbol queried

This is consistent with any symbol I use even when I make sure they are listed on this page https://iextrading.com/trading/eligible-symbols/

### Date/time of issue
December 11th 22:15UTC

### API URL
See above
https://api.iextrading.com/1.0/deep/official-price?symbols=snap

### What you expected to happen
I would expect the open or close data for the symbols queried

### What actually happened
See above - no official price is returned

### Other Information (sample code, links, etc.)
See above

**Comment by evancarter-iex** [comment]
This is correct. We only return official prices for IEX Listed Securities.

**Comment by austinbv** [comment]
@evancarter-iex thanks for updating - Where is there a list of IEX Listed Securities?
