### ISSUE TITLE
Can't find info for VFINX stock on the NASDAQ

### ISSUE THREAD

**Issue by drlarryh** [iexg/IEX-API#58]
https://api.iextrading.com/1.0/stock/market/batch?symbols=vfinx&types=quote,news,chart&range=1m&last=1

returned nothing.

Any ideas what is wrong?

**Comment by drlarryh** [comment]
https://api.iextrading.com/1.0/stock/market/batch?symbols=vfinx&types=quote,news,chart&range=1m&last=1

returned nothing.

Any ideas what is wrong?

**Comment by evancarter-iex** [comment]
We dont support mutual funds yet. We may in the future. See https://github.com/iexg/IEX-API/issues/16 for more information.
