### ISSUE TITLE
IEX API Websocket Crypto

### ISSUE THREAD

**Issue by VladSiy** [iexg/IEX-API#580]
Is it possible to get data for cryptocurrency, for example BTCUSDT, from the Stocks section (https://iextrading.com/developer/docs/#crypto), but using a websocket, as shown in IEX Market Data (https://iextrading.com/developer/docs/#deep)?

The code that I use, instead of fb, I would get the data on cryptocurrency:

````
const url = 'https://ws-api.iextrading.com/1.0/deep'
 const socket = require('socket.io-client')(url)
 socket.on('connect', () => {
    console.log('Connected');
    socket.emit('subscribe', JSON.stringify({
        symbols: ['fb'],
        channels: ['trades', 'book'],
    }))
})
socket.on('message', message => console.log(message))
socket.on('disconnect', () => console.log('Disconnected.'))
socket.on('error', () => {
    console.log('error')
})
````

**Comment by evancarter-iex** [comment]
This is not possible currently. We will look into it for Version 2

**Comment by timpaine-iex** [comment]
closing as stale, crypto served on SSE for IEX Cloud
