### ISSUE TITLE
inaccurate peRatio from /quote endpoint

### ISSUE THREAD

**Issue by aullrich2013** [iexg/IEX-API#582]
## Summary
peRatio (/quote endpoint) doesn't match actual financials

### Date/time of issue
12/12/2018

### API URL
https://api.iextrading.com/1.0/stock/adnt/quote
as compared with https://api.iextrading.com/1.0/stock/adnt/stats

### What you expected to happen
I expected the peRatio from the /quote endpoint to be accurate

### What actually happened
the peRatio is reported as +2.79 when the actual p/e ratio is N/A - [The earnings are negative - via yahoo](https://finance.yahoo.com/quote/ADNT/financials?p=ADNT) and [the /stats endpoint](https://api.iextrading.com/1.0/stock/adnt/stats)

### Other Information (sample code, links, etc.)
This *might* be related to the financials endpoint returning the reporting period ending 6/30 as the most recent when in fact 9/30 has been available for some time: 
https://api.iextrading.com/1.0/stock/adnt/financials

**Comment by evancarter-iex** [comment]
Please see https://github.com/iexg/IEX-API/issues/557 for more information on this.

**Comment by aullrich2013** [comment]
@evancarter-iex , I don't fully understand the link. Are you saying this is a known issue and it'll be resolved in the v2 update? Thanks

**Comment by aullrich2013** [comment]
Sorry. spoke too soon. A few other symbols where the ttm EPS is reported as positive by the /stats endpoint but negative by etrade and yahoo finance: PIR, ACET

**Comment by aullrich2013** [comment]
Perfect. Thx

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
