### ISSUE TITLE
Need clarification on what fields represent

### ISSUE THREAD

**Issue by marysue** [iexg/IEX-API#583]
I'm looking for the following, but I don't seem to be able to match what your available fields represent:

Open:  opening pricing for individual stock for today.
Close:  closing (or current price) for individual stock for today.
Current:  current price at this moment in time for individual stock
change:  change in pricing from opening bell to present
change percent:  percent of change from opening bell to present
High:  Highest pricing for individual stock today
Low:  Lowest pricing for individual stock today

I'm currently using your stock api, filtering on symbol, company, open, close, high, low, change and changePercent fields -- but the math isn't working.  Maybe I'm using the wrong fields?

**Comment by evancarter-iex** [comment]
This should be fixed in IEXCloud. https://iexcloud.io, if you are still having issues please file a ticket there.
