### ISSUE TITLE
Faulty Redirects

### ISSUE THREAD

**Issue by prp1277** [iexg/IEX-API#584]
## Summary

The link [https://iexcloud.io/](https://iexcloud.io/) reroutes to a 404 page

### Date/time of issue

12/14/12:00AM

### API URL

https://iexcloud.io/

### What you expected to happen
I expected to learn more about the new Beta version of the software

### What actually happened
I was redirected to a 404 page

### Other Information (sample code, links, etc.)
https://iexcloud.io/

**Comment by evancarter-iex** [comment]
Hmmm works fine for me. Are you still seeing this?
