### ISSUE TITLE
API delivering wrong open/close/data

### ISSUE THREAD

**Issue by machater1980** [iexg/IEX-API#585]
## Summary
I am running a query against a stock for the last month and the open/close/etc data appears to be off by quite a bit. 

## Details
Here is the query I am running for reference:

https://api.iextrading.com/1.0/stock/BAC/chart/1m

The closing price for BAC on 11/12 according to the API was 27.5958, however if you look at any data source for finance (Yahoo, Google, TDAmeritrade, etc) the closing price was actually 27.75.  I tried a few other stocks and they are all about the same (with the data being off by about .15).  The "issue" appears to maybe have corrected itself around early December because the prices are right again, however this is throwing off my calculations for historical data.

### Date/time of issue
12/14/18

### API URL
https://api.iextrading.com/1.0/stock/BAC/chart/1m

**Comment by jesseorosz** [comment]
I've noticed this as well.

From 8/10/18 to  11/7/18 AAPL usually has a difference of about 72 to 77 cents of what he actual open/close is.

From 5/11/18 to 8/9/18 it was a difference between 1.30 and 1.45.

The differences are always short of what the actual values are.

**Comment by machater1980** [comment]
Update on this.

I found out the prices were not adjusted for dividends.  It looks like they
recently fixed this.

**Comment by jesseorosz** [comment]
Great, thank you for the update.

I also saw differences with volume - did you experience this as well?

**Comment by machater1980** [comment]
I don't use volume in my calculations but I saw others had problems with
that.

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud https://iexcloud.io
