### ISSUE TITLE
Quandl & Yahoo & Microsoft vs Iex prices do not match 

### ISSUE THREAD

**Issue by Emarch1** [iexg/IEX-API#586]
Microsoft OPEN at  (Quandl) $85.26 or  (IEX) $83.81 

QuandL MSFT.csv:2017-12-15,**85.26**,87.09,84.88,86.85,52430167.0,0.0,1.0,85.26,87.09,84.88,86.85,52430167.0

IEX MSFT.csv:2017-12-15,83.8092,85.608,83.4356,85.3721,53936687,53936687,2.1232,2.55,84.7656,"Dec 15, 17",1.610144980707966

Yahoo agrees with QuandL and Microsofts website below BUT  IEX is different 

https://www.microsoft.com/en-us/Investor/stock-lookup.aspx

Microsoft link says 
open | High | low | close 
$85.26 | $87.09 | $84.88 | $86.85

**Comment by joshuablackburn-iex** [comment]
Our price is adjusted. In the new IEX Cloud API, we will provide both adjusted and unadjusted OHLCV.
