### ISSUE TITLE
Direct readonly access to DB

### ISSUE THREAD

**Issue by aido93** [iexg/IEX-API#588]
## Summary

Hello guys! I need to analyse a lot of market data (around 200000 quotes). It takes too much time to download them using your REST API. How can I just download all historical data for all quotes in your database?  I don't need all of your data: only prices and volume per day and description of the company (like `/stock/aapl/company`).

**Comment by joshuablackburn-iex** [comment]
This is something we can offer in our new IEX Cloud API. Our current API contract restrictions do not allow for this type of download.

**Comment by timpaine-iex** [comment]
closing as stale
