### ISSUE TITLE
BRK.A Market Cap Incorrect

### ISSUE THREAD

**Issue by nicholasmccullum** [iexg/IEX-API#589]
## Summary

Berkshire Hathaway's market capitalization is shown as $260 billion, when it is actually closer to $500 billion. 

### Date/time of issue

Wednesday, December 19th

**Comment by evancarter-iex** [comment]
This will be fixed in version 2 of the api. See https://github.com/iexg/IEX-API/issues/557 for more information

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. Sign up for beta access, if you havent already.

https://iexcloud.io/
