### ISSUE TITLE
Adobe Logo from the Logo API is wrong

### ISSUE THREAD

**Issue by dennisho-motif** [iexg/IEX-API#590]
## Summary

Adobe Logo from the Logo API is wrong

## Details

Adobe Logo from the Logo API is wrong

### Date/time of issue

2018-12-18

### API URL

https://api.iextrading.com/1.0/stock/adbe/logo

### What you expected to happen

https://www.google.com/imgres?imgurl=http://wwwimages.adobe.com/content/dam/acom/en/badges-buttons/images/Adobe_standard_logo_RGB.png&imgrefurl=http://t3.gstatic.com/images?q%3Dtbn:ANd9GcQvPwQiRlAt5y64VWIODeCYaH3SgEontde1bSpnjeg1fwAId5Wi&h=283&w=211&tbnid=Ej0QQOpLqnRDQM:&q=adobe+symbol+stock&tbnh=160&tbnw=119&usg=AI4_-kRkf1kzAGBNlm3Y9Ps3eNzbOymWUg&vet=1&docid=kuXPFm1xiI25DM&itg=1&sa=X&ved=2ahUKEwiQ173TwazfAhU5HjQIHfGhDaAQ_B0wHnoECAgQFA

### What actually happened

https://storage.googleapis.com/iex/api/logos/ADBE.png

**Comment by evancarter-iex** [comment]
This is fixed in https://iexcloud.io
