### ISSUE TITLE
Websocket endpoint https://ws-api.iextrading.com/1.0/tops stale

### ISSUE THREAD

**Issue by jaytula** [iexg/IEX-API#591]
## Summary

Websocket endpoint https://ws-api.iextrading.com/1.0/tops returns stale data with lastSaleTime of around 11:49am PST today (Wednesday, Dec 19th).  It also stopped streaming any additional data.

## Details

Here are some example quotes and last sale times retrieved just now:

AAPL: 160.77 Wed Dec 19 2018 12:59:59 GMT-0800 (Pacific Standard Time)
AMZN: 1540.11 Wed Dec 19 2018 11:48:56 GMT-0800 (Pacific Standard Time)
BABA: 137.14 Wed Dec 19 2018 12:59:57 GMT-0800 (Pacific Standard Time)
BAC: 24.66 Wed Dec 19 2018 11:49:11 GMT-0800 (Pacific Standard Time)
FB: 136.3 Wed Dec 19 2018 11:49:05 GMT-0800 (Pacific Standard Time)
GOOGL: 1047.32 Wed Dec 19 2018 11:49:05 GMT-0800 (Pacific Standard Time)
INTC: 46.69 Wed Dec 19 2018 11:49:15 GMT-0800 (Pacific Standard Time)
JNJ: 129.03 Wed Dec 19 2018 11:49:00 GMT-0800 (Pacific Standard Time)
JPM: 98.59 Wed Dec 19 2018 11:48:49 GMT-0800 (Pacific Standard Time)
MSFT: 104.75 Wed Dec 19 2018 11:49:15 GMT-0800 (Pacific Standard Time)
PG: 92.24 Wed Dec 19 2018 11:48:46 GMT-0800 (Pacific Standard Time)
ROKU: 31.19 Wed Dec 19 2018 11:46:14 GMT-0800 (Pacific Standard Time)
UNH: 251.65 Wed Dec 19 2018 11:49:10 GMT-0800 (Pacific Standard Time)
V: 132.905 Wed Dec 19 2018 11:48:59 GMT-0800 (Pacific Standard Time)
WMT: 91.49 Wed Dec 19 2018 11:49:09 GMT-0800 (Pacific Standard Time)
XOM: 71.52 Wed Dec 19 2018 11:49:15 GMT-0800 (Pacific Standard Time)

### Date/time of issue

Since 11:49am PST today Dec 19th

### API URL

 https://ws-api.iextrading.com/1.0/tops

### What you expected to happen

Last sale time should be closer to 1PM PST.

### What actually happened

Last sale time is around 11:49am PST

### Other Information (sample code, links, etc.)

It appears that some quotes are now being updated so I guess it is being fixed.

**Comment by joshuablackburn-iex** [comment]
This was due to high data volume rate related to the Fed announcement. We experienced 4-5x average message rates, and our system behavior is to conflate more data in order to stay active rather than fall over. Normal data rates should have resumed.
