### ISSUE TITLE
Sector mismatch in market/collection/sector?collectionName={sector} and {symbol}/company endpoints

### ISSUE THREAD

**Issue by pwenke** [iexg/IEX-API#594]
## Summary
The sector collection and company endpoints return conflicting sector information for 24 companies.  In addition, the company endpoint returns no sector information for 6 companies, and there is no company information returned whatsoever for ARLO# (not found).

## Details
Sector mismatch information for the following symbols:

VTSI sector mismatch - collection sector: Technology, company sector: Industrials
WTRH sector mismatch - collection sector: Industrials, company sector: Consumer Discretionary
PBY sector mismatch - collection sector: Consumer Discretionary, company sector: Financials
NEPT sector mismatch - collection sector: Health Care, company sector: Consumer Staples
ALTM sector mismatch - collection sector: Industrials, company sector: Energy
ALYA sector mismatch - collection sector: Industrials, company sector: Technology
FLMN sector mismatch - collection sector: Industrials, company sector: Energy
BSTI sector mismatch - collection sector: Technology, company sector: Industrials
BV sector mismatch - collection sector: Technology, company sector: Industrials
INS sector mismatch - collection sector: Industrials, company sector: Technology
JD sector mismatch - collection sector: Technology, company sector: Consumer Discretionary
KONE sector mismatch - collection sector: Communication Services, company sector: Technology
MGY sector mismatch - collection sector: Industrials, company sector: Energy
CJ sector mismatch - collection sector: Materials, company sector: Energy
CSL sector mismatch - collection sector: Consumer Discretionary, company sector: Industrials
DHR sector mismatch - collection sector: Industrials, company sector: Health Care
DSWL sector mismatch - collection sector: Consumer Discretionary, company sector: Industrials
EMES sector mismatch - collection sector: Energy, company sector: Materials
XYF sector mismatch - collection sector: Materials, company sector: Financials
YVR sector mismatch - collection sector: Consumer Staples, company sector: Consumer Discretionary
CVIA sector mismatch - collection sector: Energy, company sector: Materials
HFFG sector mismatch - collection sector: Industrials, company sector: Consumer Staples
SMSH sector mismatch - collection sector: Industrials, company sector: Consumer Discretionary
SPB sector mismatch - collection sector: Consumer Staples, company sector: Consumer Discretionary

No sector is returned from the company endpoint for the following symbols:

OXLC
INDU
IRR
CUBS
DFFN
SCIN

### Date/time of issue
12/20/2018, all day

### API URL
https://api.iextrading.com/1.0/stock/market/collection/sector?collectionName={sector}
https://api.iextrading.com/1.0/stock/{symbol}/company

### What you expected to happen
Sectors to match across endpoints.  I understand that there are sector naming discrepancies between the two endpoints, but that is not the issue here.

### What actually happened
This data is saying the same company is in two entirely different sectors.

**Comment by evancarter-iex** [comment]
Thanks. This will be fixed in version 2, see https://github.com/iexg/IEX-API/issues/557 for more information

**Comment by evancarter-iex** [comment]
This should be fixed in https://iexcloud.io if its not, please file a new issue. Thanks
