### ISSUE TITLE
API Version 2, Tokens

### ISSUE THREAD

**Issue by lars670** [iexg/IEX-API#595]
## Summary
As I can deduct from the new documentation then a Token is needed for a connection. This will make evaluation periods quite difficult, at least with direct connection to IEX. Of course we can proxy this and make a stream server with IEX, but that was really not the plan.

### What you expected to happen
Some kind of solution that would enable us to offer the client to test the program before registering on the IEX site.
Some kind of grace period, maybe a registration via the API

**Comment by evancarter-iex** [comment]
I'm not sure I fully understand your particular situation. Can you expand? Or you can email us if you prefer not to do it on here.

**Comment by lars670** [comment]
I mean; must the  "Token" be unique for each user connecting to IEX to retrieve data?

Background
We have designed a HTML5 application "TOP" which connects to IEX as of today with your API in version 1.
https://top.softcapital.com/

When a new user of ours want to connect to IEX V2, does he have to have a new Token, thus register for this.?
If the new user further to our registration process also has to register for a Token at IEX this will make evaluation periods somewhat more compliated.

**Comment by evancarter-iex** [comment]
Is the request coming from your server via the HTML5 app or is it a client side app?

**Comment by lars670** [comment]
It is a client side application for the feed
while there still is a serverside connection to us for a portfolio calculations.

**Comment by evancarter-iex** [comment]
@lars670 lets take this to email, so we can sort it out.

**Comment by joshuablackburn-iex** [comment]
@lars670 

If you are the one paying for a subscription to the IEX Cloud service, each of your users will not be required to sign up for a token. In your admin console you'll have access to a secret token and public token.  The public key is used in your client app to communicate with our servers. You'll just pass the public token with each HTTP request. We will allow you to restrict public tokens to a specific domain to prevent misuse.

Does this help answer your question?
