### ISSUE TITLE
return programmatically from API market open hours range for a given date

### ISSUE THREAD

**Issue by sanikolov** [iexg/IEX-API#596]
## Summary
For up to N days ahead (e.g. 365, 3*365) given a date parameter return the range during which market is scheduled to be open on that date; None/Close if it will be closed; Unknown if date is too far in the future;
InvalidRequest if date is in the past.
My investigation led me to believe that the current API does not support the above.
Scraping data off the other exchanges' web sites is not exactly bot friendly.
Data should be up-to-date at least 1 full day before unexpected market closures such as Dec 5, 2018.

## Details
Example:  
market_open_hours "2018-12-24" -> (9:30, 13:00)
market_open_hours "2018-12-25" -> None/Closed or similar
market_open_hours "2019-01-03" -> (9:30, 16:00)
market_open_hours "2089-10-08" -> Unknown
market_open_hours "1981-06-14" -> InvalidRequest

Another implementation could look like this
market_open_dates "2019" "regular" -> list of dates on which market is open from 9:30 to 16:00
market_open_dates "2019" "early_close" -> list of dates on which market is open from 9:30 to 13:00

It's shorter but I don't like it because it's somewhat imprecise, how do we know that an early close always corresponds to 13:00?

### Date/time of issue
N/A

### API URL
N/A

### What you expected to happen
See above

### What actually happened
Nothing

### Other Information (sample code, links, etc.)
N/A

**Comment by joshuablackburn-iex** [comment]
Holiday and trade dates available in IEX Cloud.
