### ISSUE TITLE
Stock - OHLC - missing Volume data, needs simplified return format

### ISSUE THREAD

**Issue by umariani** [iexg/IEX-API#598]
## Summary
Hello Developers

I tried the Stocks - OHLC to retrieve data.
I think the returned data also needs the Volume data.
The return layout can be improved and simplified from the current format.

## Details

I tried the Stocks - OHLC to retrieve data.
I think the returned data also needs the Volume data.
The return layout can be improved and simplified from the current format.

Current 
   https://api.iextrading.com/1.0/stock/spy/ohlc

 ###----------------------------------------------
{"open":{"price":246.75,"time":1545402600087},"close":{"price":240.7,"time":1545426000484},"high":249.71,"low":239.98}
 
 ### After split by "comma"
 {"open":{"price":246.75
 "time":1545402600087}
 "close":{"price":240.7
 "time":1545426000484}
 "high":249.71
 "low":239.98}

Suggested Format - simplifies parsing
  {"symbol":SPY
  "time":1545402600087
 "open":246.75
 "high":249.71
 "low":239.98
 "close":240.7
 "volume":255345633}

Regards

### Date/time of issue
2018-12-23

### API URL
   https://api.iextrading.com/1.0/stock/spy/ohlc

### What you expected to happen
Volume data missing
Simplified return format for  OHLC and Volume

### What actually happened
No Volume data
Messy return format makes parsing more complicated
to many " {"  and " }" and repetitive words

**Comment by McQgit** [comment]
@umariani  The 'time' for the open and close is not the same which your new format ignores.  After the open and before the close the date of the timestamp won't even be the same.  In that case the open reflects the active trading day but the close reflects prior close.

Also, don't you have a function to parse json?  That would avoid you needing to parse by commas and such.

**Comment by evancarter-iex** [comment]
api.iextrading.com is sunsetted.
