### ISSUE TITLE
1 day chart. Time stamp with date

### ISSUE THREAD

**Issue by potan89** [iexg/IEX-API#6]
It would be great to have a time stamp that includes a whole date not only minutes for 1 day chart request (https://api.iextrading.com/1.0/stock/aapl/chart/1d.).
At the moment we have to find out if exchange is closed or not to understand if we have to show one day chart. That's not very convenient. 

Example:
{"minute":"09:30","label":"09:30 AM","high":162.11,"low":162.07,"average":162.087,"volume":1095,"notional":177484.96,"numberOfTrades":11,"changeOverTime":0}

It would be much better to have:
{date: "2017-09-07", "minute":"09:30","label":"09:30 AM","high":162.11,"low":162.07,"average":162.087,"volume":1095,"notional":177484.96,"numberOfTrades":11,"changeOverTime":0}

**Comment by xapss** [comment]
👍

**Comment by joshuablackburn-iex** [comment]
We've added a new chart option called `dynamic` which will figure this out for you.  Documentation has been updated to reflect this addition.  Please let us know if this will work.

**Comment by potan89** [comment]
Sorry, I don't see any updates.

**Comment by joshuablackburn-iex** [comment]
The newest chart docs are at https://iextrading.com/developer/docs/#chart

**Comment by rsepulveda2** [comment]
i have to agree with potan89's request. What if i want 1 min data on a specific date which includes a date field in addition to the minute field? Your dynamic option isn't date specific and it produces daily data if requested outside of market hours? Thanks.

**Comment by shuwnyuantee** [comment]
I face similar issue with intraday (1d) chart. As 1d chart doesn't have date information, I workaround it this way:  query `quote` api, get date from `closeTime` / `openTime` [1].

I assume the date in `quote` api always represent same date `chart/1d` data? @joshuablackburn-iex  Is my assumption correct?

Although I can live with this workaround, but having full timestamp in `1d` chart will be much useful & less error prone.

Thanks @joshuablackburn-iex  & IEX.

**Comment by maryokhin** [comment]
Speaking of the 1d chart, does anybody see lot's of -1s in the data?
```
{
"date": "20171115",
"minute": "10:55",
"label": "10:55 AM",
"high": 0,
"low": 0,
"average": -1,
"volume": 0,
"notional": 0,
"numberOfTrades": 0,
"changeOverTime": -1.0059017593144517
},
```
How do use the data for plotting if there are gaps with -1 in it?

**Comment by maryokhin** [comment]
I tried plotting by filtering out all the -1s, but the predictably  saw large gaps in chart
<img width="539" alt="screenshot 2017-11-15 21 11 19" src="https://user-images.githubusercontent.com/4390231/32857881-b35db712-ca49-11e7-863c-67c7519af4cd.png">
do you know how to get around the -1s @joshuablackburn-iex?

**Comment by jcape** [comment]
Closing this issue: 1d contains a date field with a YYYYMMDD string, dynamic flips between "today" and "1m" depending on whether it's called during market hours or not, and -1s in the data as noted is a separate issue, #121

**Comment by shuwnyuantee** [comment]
The date works great, thanks for that 👍

**Comment by Harmonium** [comment]
My workaround for the -1 is to replace the value by the previous one (if not 0) to avoid a gap. This way I will always have the right number of datas for the right time (minute). It is not perfect but for now it does the job.
