### ISSUE TITLE
Toronto Stock Exchange support 

### ISSUE THREAD

**Issue by susanlinsfu** [iexg/IEX-API#602]
I would first like to thank the IEX team for providing such a great API! 

Currently, I use IEX for any business I do with U.S stocks but unfortunately have to also make calls to the  Vantage Alpha API to get end of day data for TSX stocks. I would love to shift my app to fully only use IEX.

Since Canada is the U.S's cool hip upstairs neighbor I have two questions:

1) Is there any plan to include TSX data in the near future (within 3 months)?
2) If so, would the calls be explicit to specify which market to use. For example, would a call look like something this:

 /stock/tsx/ter 
or
/stock/nasdaq/ter 

where the market the ticker resides in is intentionally specified?

Thanks!

**Comment by evancarter-iex** [comment]
It's on our list for version 2 (more information here: https://github.com/iexg/IEX-API/issues/557). Make sure you follow that/subscribe for more information

**Comment by evancarter-iex** [comment]
End of Day pricing for Toronto has been deployed.  https://iexcloud.io/docs/api/#changelog
