### ISSUE TITLE
Datapoints that appear to be erroneous on 1D due to large deviations

### ISSUE THREAD

**Issue by mfhawley** [iexg/IEX-API#603]
## Summary
There are several datapoints on several different stocks that appear to have some erroneous datapoints because the marketLow's appear to be excessively low creating a deceiving tail on some of the candlesticks in our app.
Also, the returned datapoints are not consistent with that seen on other stock market websites.

Screenshots below are from our application. JSON screenshots show data returned from IEX.
 
## Details
Some examples are when making the 1d API call.
JNJ: https://api.iextrading.com/1.0/stock/jnj/chart/1d
For the date of 12282018 at 12:27 it returns a marketLow of 123.516. (See screenshot). This appears to be incorrect as it is not seen on other websites and in general not how stocks typically behave.
[Another error you can see in the screenshot below is the points from 14:00 to 14:10. This also appears to be incorrect as you can see in the screenshot below even though it is correctly displaying the data returned from IEX]
![screenshot_2018-12-29-16-40-55](https://user-images.githubusercontent.com/14339122/50543298-24f56d80-0b89-11e9-8762-ff43c5cbc15a.png)
Data screenshot
![image](https://user-images.githubusercontent.com/14339122/50543302-50785800-0b89-11e9-937a-298b96080c50.png)

Another Example is Facebook.
FB: https://api.iextrading.com/1.0/stock/fb/chart/1d
For the data 12282018 at 2:16 it returns a marketLow of 131.756. Also appears to be erroneous for the same reasons as above.
![screenshot_2018-12-29-16-40-36](https://user-images.githubusercontent.com/14339122/50543304-7aca1580-0b89-11e9-8795-ef9aa7eb0cf6.png)
Data Screenshot
![image](https://user-images.githubusercontent.com/14339122/50543308-87e70480-0b89-11e9-82ec-68131f0133b5.png)

### Date/time of issue
12/28/2018 during several time frames

API calls screenshotted above were made on Saturday Dec 29 (returning 12/28 data)

### API URL
JNJ: https://api.iextrading.com/1.0/stock/jnj/chart/1d
FB: https://api.iextrading.com/1.0/stock/fb/chart/1d

### What you expected to happen
I would expect a value that does not suddenly drop so sharly then rebound. All other web charting platforms do not display a price drop even close to what is seen from IEX returned data

### What actually happened
The price dropped sharly then rebounded which seemed to be an obvious error. This happens for many many stocks through the returned IEX data

**Comment by evancarter-iex** [comment]
@mfhawley are you seeing this in IEXCloud?

**Comment by mfhawley** [comment]
Yes. Still see this in both IEXcloud and the standard free service.
Below are a few examples...

AAPL: https://cloud.iexapis.com/beta/stock/aapl/chart/1d
@ 12:27pm the marketHigh erroneously surges to 176+
@10:57 the marketClose and marketLow erroneously drop below 175...
@ the whole start of the day at the left side of the chart in the below image you can see strange looking candlesticks that are mostly erroneous
![screenshot_2019-03-04-15-39-06](https://user-images.githubusercontent.com/14339122/53777312-c660ae80-3ead-11e9-8946-3f1916e14eba.png)


TSLA: https://cloud.iexapis.com/beta/stock/tsla/chart/1d
@12:43 the markethigh randomly surges to 293
@11:50 this may also be a slight error in the marketHigh
![screenshot_2019-03-04-18-44-15](https://user-images.githubusercontent.com/14339122/53777531-8d750980-3eae-11e9-87e1-4e44d427168e.png)

**Comment by evancarter-iex** [comment]
@mfhawley okay thanks we are looking into this today some more on our end. But is going to require some leg work. Ill let you know when I know some more.

**Comment by mfhawley** [comment]
@evancarter-iex
No problem, as long as you guys are working towards a fix it is reassuring. I appreciate the followup!

**Comment by evancarter-iex** [comment]
@mfhawley yeah sorry about the delay, we were pressed while we were launching the Cloud product

**Comment by mfhawley** [comment]
Also, if it helps to visualize and cross reference some of this data I'm see those charts through my app called Candl on the Google Play Store

You can set it to candle charts in the settings and I usually just search through AMZN, FB, GOOG, GE, TSLA, etc. And almost always one or several of those have issues on the 1D charts.

Then I cross reference the minute of the candlestick that has an issue in my app with IEX actual returned API data to double check...
Not sure if that helps at all

https://play.google.com/store/apps/details?id=com.stocksymbolapp

**Comment by mfhawley** [comment]
Check out GOOG from Friday 3-8-19
Several very erroneous data points on the 1-day time frame with 1-minute candlesticks :/
![Screenshot_2019-03-09-08-13-25](https://user-images.githubusercontent.com/14339122/54074113-8732b480-4243-11e9-8d87-47c39284c290.png)

**Comment by evancarter-iex** [comment]
@mfhawley Yeah we are testing some solutions to this but not ready to deploy it yet. We havent forgotten about it, just want to make sure its right

**Comment by evancarter-iex** [comment]
This should be fixed now in https://iexcloud.io  If it's still an issue please reopen.
