### ISSUE TITLE
Is Executive Compensation available in the API?

### ISSUE THREAD

**Issue by taylorgoolsby** [iexg/IEX-API#604]
Hi!

I was wondering if [executive compensation](https://www.sec.gov/fast-answers/answers-execomphtm.html) is available through the API. I looked through it. If it's in there I missed it and I apologize. If it's not in there, are their plans to add it?

**Comment by evancarter-iex** [comment]
Its not currently available but we can see if we can put it on the list for [Version 2](https://github.com/iexg/IEX-API/issues/557)

**Comment by joshuablackburn-iex** [comment]
CEO compensation is available on IEX Cloud https://iexcloud.io/docs/api/#ceo-compensation

**Comment by taylorgoolsby** [comment]
Is CEO Compensation part of the "START" pricing level?
I can't find it on the [pricing page](https://iexcloud.io/pricing/).

![image](https://user-images.githubusercontent.com/14286600/53447936-209fd200-39cb-11e9-887c-ca38bc16b763.png)
