### ISSUE TITLE
Totally wrong data on UGAZ on Dec 20th 12:37pm (marketClose)

### ISSUE THREAD

**Issue by lvca** [iexg/IEX-API#605]
## Summary
UGAZ on Dec 20th, 2018, 12:37pm contains wrong data. And after 12:37pm marketClose is always 0 till the rest of the day.

## Details

Look at "UGAZ" ticker on Dec 20th, 2018, 12:37pm shows a crazy amount in closing, almost double of the real price. And after 12:37pm marketClose is always 0 till the rest of the day.

### Date/time of issue

UGAZ on Dec 20th, 2018, 12:37pm

### API URL

https://api.iextrading.com/1.0/stock/UGAZ/chart/date/20181220

### What you expected to happen

To receive the correct value in `marketClose`.

### What actually happened

The value is >90% of the correct one. Also, after 12:37pm marketClose is always 0 till the rest of the day.

### Other Information (sample code, links, etc.)

Easy like that, please check it out, I can't trust such crazy values with no sense. Thanks.

**Comment by evancarter-iex** [comment]
Fixed in IEXCloud. https://iexcloud.io
