### ISSUE TITLE
Dividends are incorrect?

### ISSUE THREAD

**Issue by rclai** [iexg/IEX-API#606]
## Summary

I checked the dividend history on your API for the AI ticker and saw that they payed out 55 cents per share but other sites like nasdaq, yahoo finance and the alpha advantage api are reporting 37.5 cents per share, so I am confused of this discrepancy.

https://api.iextrading.com/1.0/stock/ai/dividends/1y
```
[
  {
    "exDate": "2017-12-28",
    "paymentDate": "2018-01-31",
    "recordDate": "2017-12-29",
    "declaredDate": "2017-12-14",
    "amount": 0.55,
    "flag": "FI",
    "type": "Dividend income",
    "qualified": "",
    "indicated": ""
  },
  {
    "exDate": "2017-09-28",
    "paymentDate": "2017-10-31",
    "recordDate": "2017-09-29",
    "declaredDate": "2017-09-14",
    "amount": 0.55,
    "flag": "",
    "type": "Dividend income",
    "qualified": "Q",
    "indicated": ""
  },
  {
    "exDate": "2017-06-28",
    "paymentDate": "2017-07-31",
    "recordDate": "2017-06-30",
    "declaredDate": "2017-06-16",
    "amount": 0.55,
    "flag": "",
    "type": "Dividend income",
    "qualified": "Q",
    "indicated": ""
  },
  {
    "exDate": "2017-03-29",
    "paymentDate": "2017-04-28",
    "recordDate": "2017-03-31",
    "declaredDate": "2017-03-14",
    "amount": 0.625,
    "flag": "",
    "type": "Dividend income",
    "qualified": "Q",
    "indicated": ""
  }
]
```

Other sites:
https://finance.yahoo.com/quote/AI/history?p=AI
https://www.nasdaq.com/symbol/ai/dividend-history
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=AI&outputsize=full&apikey=YOUR-API-KEY

**Comment by jameslulusoft** [comment]
Not sure if this is related but there is issues with MSFT. Notice how there is only one 2018 payment date. When reviewing https://www.streetinsider.com/dividend_history.php?q=msft there are 4 payment dates in 2018. Kinda confused. 

https://api.iextrading.com/1.0/stock/msft/dividends/1y

[{
  "exDate": "2018-02-14",
  "paymentDate": "2018-03-08",
  "recordDate": "2018-02-15",
  "declaredDate": "2017-11-29",
  "amount": 0.42,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2017-11-15",
  "paymentDate": "2017-12-14",
  "recordDate": "2017-11-16",
  "declaredDate": "2017-09-19",
  "amount": 0.42,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2017-08-15",
  "paymentDate": "2017-09-14",
  "recordDate": "2017-08-17",
  "declaredDate": "2017-06-13",
  "amount": 0.39,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2017-05-16",
  "paymentDate": "2017-06-08",
  "recordDate": "2017-05-18",
  "declaredDate": "2017-03-14",
  "amount": 0.39,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2017-02-14",
  "paymentDate": "2017-03-09",
  "recordDate": "2017-02-16",
  "declaredDate": "2016-11-30",
  "amount": 0.39,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2016-11-15",
  "paymentDate": "2016-12-08",
  "recordDate": "2016-11-17",
  "declaredDate": "2016-09-20",
  "amount": 0.39,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2016-08-16",
  "paymentDate": "2016-09-08",
  "recordDate": "2016-08-18",
  "declaredDate": "2016-06-14",
  "amount": 0.36,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2016-05-17",
  "paymentDate": "2016-06-09",
  "recordDate": "2016-05-19",
  "declaredDate": "2016-03-15",
  "amount": 0.36,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2016-02-16",
  "paymentDate": "2016-03-10",
  "recordDate": "2016-02-18",
  "declaredDate": "2015-12-02",
  "amount": 0.36,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2015-11-17",
  "paymentDate": "2015-12-10",
  "recordDate": "2015-11-19",
  "declaredDate": "2015-09-15",
  "amount": 0.36,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2015-08-18",
  "paymentDate": "2015-09-10",
  "recordDate": "2015-08-20",
  "declaredDate": "2015-06-09",
  "amount": 0.31,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2015-05-19",
  "paymentDate": "2015-06-11",
  "recordDate": "2015-05-21",
  "declaredDate": "2015-03-10",
  "amount": 0.31,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2015-02-17",
  "paymentDate": "2015-03-12",
  "recordDate": "2015-02-19",
  "declaredDate": "2014-12-03",
  "amount": 0.31,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2014-11-18",
  "paymentDate": "2014-12-11",
  "recordDate": "2014-11-20",
  "declaredDate": "2014-09-16",
  "amount": 0.31,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2014-08-19",
  "paymentDate": "2014-09-11",
  "recordDate": "2014-08-21",
  "declaredDate": "2014-06-10",
  "amount": 0.28,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2014-05-13",
  "paymentDate": "2014-06-12",
  "recordDate": "2014-05-15",
  "declaredDate": "2014-03-11",
  "amount": 0.28,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2014-02-18",
  "paymentDate": "2014-03-13",
  "recordDate": "2014-02-20",
  "declaredDate": "2013-11-19",
  "amount": 0.28,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2013-11-19",
  "paymentDate": "2013-12-12",
  "recordDate": "2013-11-21",
  "declaredDate": "2013-09-17",
  "amount": 0.28,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2013-08-13",
  "paymentDate": "2013-09-12",
  "recordDate": "2013-08-15",
  "declaredDate": "2013-06-12",
  "amount": 0.23,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}, {
  "exDate": "2013-05-14",
  "paymentDate": "2013-06-13",
  "recordDate": "2013-05-16",
  "declaredDate": "2013-03-11",
  "amount": 0.23,
  "flag": "",
  "type": "Dividend income",
  "qualified": "Q",
  "indicated": ""
}]

Differs from value from say https://www.streetinsider.com/dividend_history.php?q=msft

**Comment by ski2day** [comment]
I have reviewed several stocks and the ex-dividend date is falling short on more than just MSFT.

**Comment by rclai** [comment]
Wow, I thought it was only for obscure tickers, but MSFT is pretty big.
