### ISSUE TITLE
IEX timeout

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#607]
## Summary

Today just started getting API timeouts starting around 11am EST

## Details

Today just started getting API timeouts starting around 11am EST

function call

https://api.iextrading.com/1.0/stock/market/quote?filter=symbol,open,high,low,latestUpdate,latestPrice,l
atestVolume&format=csv&symbols=(up to 95 symbols)

maybe our ip address needs to be whitelisted, we have slowed our pulls down by a third since we had some timeouts last Friday (when you made some changes?) but for the most part have not had an issue over he past 6 months running this api.

ip address: 45.58.116.218

so maybe our ip needs to be whitelisted.

### Date/time of issue

11am EST

### API URL

https://api.iextrading.com/1.0/stock/market/quote?filter=symbol,open,high,low,latestUpdate,latestPrice,l
atestVolume&format=csv&symbols=(up to 95 symbols)

### What you expected to happen

api not timeout

### What actually happened

api timeout multiple times

**Comment by evancarter-iex** [comment]
We are aware of the issue due to market conditions and working to mitigate it.

**Comment by StockConsultant** [comment]
Ok thanks, we have seen issues in the past near market close (4pm EST) when the market was moving fast but only up to 20-60 sec delay which we can work around, once it hits about 100+ secs it becomes an issue for us.

**Comment by StockConsultant** [comment]
Looking good today, rises slightly during the day but is probably network congestion related.

![stocktime](https://user-images.githubusercontent.com/42130156/50780994-5b5e7700-1272-11e9-9ff9-b69c43a38929.png)

**Comment by evancarter-iex** [comment]
Thanks we did some mitigation on our side. Let me know if it repeats.


________________________________
