### ISSUE TITLE
get specific quarter cash flow

### ISSUE THREAD

**Issue by dmikester1** [iexg/IEX-API#608]
## Summary
I want to pull a specific cash flow number, ideally the latest one.  But when I hit the endpoint: https://api.iextrading.com/1.0/stock/AOS/financials , I get all 4 quarters of data.  I want to do something like /financials/1/cashFlow or /financials/0/cashFlow

### Date/time of issue
01/03/19

### API URL
https://api.iextrading.com/1.0/stock/AOS/financials

**Comment by joshuablackburn-iex** [comment]
https://iexcloud.io/docs/api/#cash-flow
