### ISSUE TITLE
Using Filter with batch request 

### ISSUE THREAD

**Issue by jimhoranjr** [iexg/IEX-API#61]
Using the filter with a single stock seems to work fine
https://api.iextrading.com/1.0/stock/aapl/quote?filter=latestPrice,symbol

However when trying to use batch it returns null as values

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote?filter=symbol,latestPrice

AAPL |  
-- | --
quote?filter=symbol | null
latestPrice | null
FB |  
quote?filter=symbol | null
latestPrice | null

What am I doing wrong ?

**Comment by joshuablackburn-iex** [comment]
You have an extra ? in your batch call.  Just replace that with an &

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote&filter=symbol,latestPrice
