### ISSUE TITLE
Gainers list OZM with a 916% gain when the point gain was 9.62 and the last price from 10.67

### ISSUE THREAD

**Issue by martyh1** [iexg/IEX-API#610]
## Summary
Gainers list seems incorrect.  Three specific things:

## Details
1) Gainers list OZM with a 916% gain when the point gain was 9.62 and the last price from 10.67.
"changePercent":9.21905  (* 100)

2) PHUN doesn't show up in gainers when it had a true over 100% gain.  How could that be?
changePercent":1.02654  (* 100)

3) The losers list was showing two items sometimes 3 or 4 maximum throughout the day.  And some that were on the list had very little loss: 
ADRO  changePercent":-0.0034  (* 100)
IVC  changePercent":-0.00444 (* 100)

### Date/time of issue
1/4/19  all day

### API URL
https://api.iextrading.com/1.0/stock/market/list/gainers
https://api.iextrading.com/1.0/stock/market/list/losers

### What you expected to happen
1) Stocks/symbols with higher gains or higher losses to appear in the gainers and losers list, like PHUN that gained over %100
2) gainers or losers with very little loss or gain to NOT appear in the gainers and losers lists
3) OZM to show the correct percentage gain.  

### What actually happened
Described above

### Other Information (sample code, links, etc.)
This can be seen using the API URLs.  No need to show code.  Here is losers and gainers as of 1/4/19 2:46PM mountain:
[{"symbol":"IVC","companyName":"Invacare Corporation","primaryExchange":"New York Stock Exchange","sector":"Healthcare","calculationPrice":"close","open":4.55,"openTime":1546612200551,"close":4.48,"closeTime":1546635724223,"high":4.65,"low":4.43,"latestPrice":4.48,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635724223,"latestVolume":575364,"iexRealtimePrice":4.47,"iexRealtimeSize":16,"iexLastUpdated":1546635590355,"delayedPrice":4.48,"delayedPriceTime":1546635724223,"extendedPrice":4.48,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1546635773451,"previousClose":4.5,"change":-0.02,"changePercent":-0.00444,"iexMarketPercent":0.03637,"iexVolume":20926,"avgTotalVolume":983643,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":148740646,"peRatio":-2.84,"week52High":20,"week52Low":3.05,"ytdChange":0.0378298320787493},{"symbol":"MDXG","companyName":"MiMedx Group Inc","primaryExchange":"NASDAQ Capital Market","sector":"Healthcare","calculationPrice":"close","open":3.9,"openTime":1541601000563,"close":2.95,"closeTime":1541624400694,"high":4.75,"low":3.66,"latestPrice":2.95,"latestSource":"Close","latestTime":"November 7, 2018","latestUpdate":1541624400694,"latestVolume":28026250,"iexRealtimePrice":null,"iexRealtimeSize":null,"iexLastUpdated":null,"delayedPrice":3.66,"delayedPriceTime":1541624400694,"extendedPrice":3.73,"extendedChange":0.78,"extendedChangePercent":0.26441,"extendedPriceTime":1541627999219,"previousClose":3.66,"change":-0.71,"changePercent":-0.19399,"iexMarketPercent":null,"iexVolume":null,"avgTotalVolume":2758730,"iexBidPrice":null,"iexBidSize":null,"iexAskPrice":null,"iexAskSize":null,"marketCap":327552875,"peRatio":59,"week52High":18.25,"week52Low":3.005,"ytdChange":-0.9667172727272728},{"symbol":"ADRO","companyName":"Aduro Biotech Inc.","primaryExchange":"Nasdaq Global Select","sector":"Healthcare","calculationPrice":"close","open":3,"openTime":1546612200434,"close":2.93,"closeTime":1546635600476,"high":3.24,"low":2.9,"latestPrice":2.93,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635600476,"latestVolume":2427462,"iexRealtimePrice":2.925,"iexRealtimeSize":100,"iexLastUpdated":1546635594828,"delayedPrice":2.93,"delayedPriceTime":1546635600476,"extendedPrice":3.012,"extendedChange":0.082,"extendedChangePercent":0.02799,"extendedPriceTime":1546636271346,"previousClose":2.94,"change":-0.01,"changePercent":-0.0034,"iexMarketPercent":0.03452,"iexVolume":83796,"avgTotalVolume":1344600,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":232653966,"peRatio":null,"week52High":9.925,"week52Low":2.34,"ytdChange":0.07352307692307691},{"symbol":"ELGX","companyName":"Endologix Inc.","primaryExchange":"Nasdaq Global Select","sector":"Healthcare","calculationPrice":"close","open":0.71,"openTime":1546612200794,"close":0.6038,"closeTime":1546635600422,"high":0.723,"low":0.59,"latestPrice":0.6038,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635600422,"latestVolume":2165291,"iexRealtimePrice":0.6038,"iexRealtimeSize":100,"iexLastUpdated":1546635588242,"delayedPrice":0.6038,"delayedPriceTime":1546635600422,"extendedPrice":0.6038,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1546635588242,"previousClose":0.7149,"change":-0.1111,"changePercent":-0.15541,"iexMarketPercent":0.00824,"iexVolume":17842,"avgTotalVolume":959384,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":62465321,"peRatio":-1.06,"week52High":6.72,"week52Low":0.59,"ytdChange":-0.18932891891891893}]
============================ gainers ==============
[{"symbol":"OZM","companyName":"Och-Ziff Capital Management Group LLC Class A Shares representing Class A limited liability company interests","primaryExchange":"New York Stock Exchange","sector":"Financial Services","calculationPrice":"close","open":10.9,"openTime":1546612624681,"close":10.73,"closeTime":1546635722202,"high":11.11,"low":10.07,"latestPrice":10.73,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635722202,"latestVolume":84336,"iexRealtimePrice":10.86,"iexRealtimeSize":31,"iexLastUpdated":1546622049783,"delayedPrice":10.73,"delayedPriceTime":1546635722202,"extendedPrice":10.86,"extendedChange":0.13,"extendedChangePercent":0.01212,"extendedPriceTime":1546622049783,"previousClose":1.05,"change":9.68,"changePercent":9.21905,"iexMarketPercent":0.05203,"iexVolume":4388,"avgTotalVolume":847989,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":5278730607,"peRatio":30.66,"week52High":11.11,"week52Low":0.8637,"ytdChange":9.248461764705882},{"symbol":"EPZM","companyName":"Epizyme Inc.","primaryExchange":"Nasdaq Global Select","sector":"Healthcare","calculationPrice":"close","open":7.26,"openTime":1546612200699,"close":7.94,"closeTime":1546635600518,"high":8.189,"low":6.4,"latestPrice":7.94,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635600518,"latestVolume":5062922,"iexRealtimePrice":7.945,"iexRealtimeSize":200,"iexLastUpdated":1546635597150,"delayedPrice":7.94,"delayedPriceTime":1546635600518,"extendedPrice":8,"extendedChange":0.06,"extendedChangePercent":0.00756,"extendedPriceTime":1546637377855,"previousClose":5.98,"change":1.96,"changePercent":0.32776,"iexMarketPercent":0.0503,"iexVolume":254665,"avgTotalVolume":734790,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":628594341,"peRatio":null,"week52High":21.4,"week52Low":5.14,"ytdChange":0.2243117241379311},{"symbol":"TBIO","companyName":"Translate Bio Inc.","primaryExchange":"Nasdaq Global Select","sector":"Healthcare","calculationPrice":"close","open":6.91,"openTime":1546612200730,"close":8.38,"closeTime":1546635600289,"high":8.46,"low":6.51,"latestPrice":8.38,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635600289,"latestVolume":322448,"iexRealtimePrice":7.99,"iexRealtimeSize":100,"iexLastUpdated":1546633978812,"delayedPrice":8.38,"delayedPriceTime":1546635600289,"extendedPrice":8.38,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1546636342631,"previousClose":6.78,"change":1.6,"changePercent":0.23599,"iexMarketPercent":0.0388,"iexVolume":12511,"avgTotalVolume":129862,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":378290714,"peRatio":null,"week52High":16.6,"week52Low":5,"ytdChange":0.14119694259012017},{"symbol":"SVA","companyName":"Sinovac Biotech Ltd.","primaryExchange":"Nasdaq Global Select","sector":"Healthcare","calculationPrice":"close","open":6.85,"openTime":1546612200365,"close":7.03,"closeTime":1546635600230,"high":7.1,"low":6.4,"latestPrice":7.03,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635600230,"latestVolume":9948,"iexRealtimePrice":6.41,"iexRealtimeSize":100,"iexLastUpdated":1546615015513,"delayedPrice":7.03,"delayedPriceTime":1546635600230,"extendedPrice":6.41,"extendedChange":-0.62,"extendedChangePercent":-0.08819,"extendedPriceTime":1546615015513,"previousClose":6.91,"change":0.12,"changePercent":0.01737,"iexMarketPercent":0.05026,"iexVolume":500,"avgTotalVolume":22982,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":499983168,"peRatio":null,"week52High":8.75,"week52Low":5.73,"ytdChange":0.0073413467048710195},{"symbol":"GME","companyName":"GameStop Corporation","primaryExchange":"New York Stock Exchange","sector":"Consumer Cyclical","calculationPrice":"close","open":14,"openTime":1546612230676,"close":15.24,"closeTime":1546635690891,"high":15.29,"low":13.7,"latestPrice":15.24,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635690891,"latestVolume":11695040,"iexRealtimePrice":15.245,"iexRealtimeSize":100,"iexLastUpdated":1546635597568,"delayedPrice":15.24,"delayedPriceTime":1546635690891,"extendedPrice":15.285,"extendedChange":0.045,"extendedChangePercent":0.00295,"extendedPriceTime":1546637468446,"previousClose":12.97,"change":2.27,"changePercent":0.17502,"iexMarketPercent":0.02117,"iexVolume":247584,"avgTotalVolume":3748238,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":1553985462,"peRatio":4.56,"week52High":20.31,"week52Low":11.56,"ytdChange":0.16736889058913546},{"symbol":"INSG","companyName":"Inseego Corp.","primaryExchange":"Nasdaq Global Select","sector":"Technology","calculationPrice":"close","open":4.28,"openTime":1546612200907,"close":4.93,"closeTime":1546635600185,"high":4.97,"low":4.26,"latestPrice":4.93,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635600185,"latestVolume":2648999,"iexRealtimePrice":4.92,"iexRealtimeSize":64,"iexLastUpdated":1546635597416,"delayedPrice":4.93,"delayedPriceTime":1546635600185,"extendedPrice":5,"extendedChange":0.07,"extendedChangePercent":0.0142,"extendedPriceTime":1546636530199,"previousClose":4.2,"change":0.73,"changePercent":0.17381,"iexMarketPercent":0.02247,"iexVolume":59523,"avgTotalVolume":514143,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":361823442,"peRatio":null,"week52High":4.97,"week52Low":1.59,"ytdChange":0.1690706635071091},{"symbol":"GTT","companyName":"GTT Communications Inc.","primaryExchange":"New York Stock Exchange","sector":"Communication Services","calculationPrice":"close","open":21.8,"openTime":1546612200454,"close":25.21,"closeTime":1546635721029,"high":25.57,"low":21.8,"latestPrice":25.21,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635721029,"latestVolume":669314,"iexRealtimePrice":25.2,"iexRealtimeSize":100,"iexLastUpdated":1546635583171,"delayedPrice":25.21,"delayedPriceTime":1546635721029,"extendedPrice":25.21,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1546635723101,"previousClose":21.76,"change":3.45,"changePercent":0.15855,"iexMarketPercent":0.04432,"iexVolume":29664,"avgTotalVolume":488576,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":1379018664,"peRatio":null,"week52High":62.317,"week52Low":21.68,"ytdChange":0.09648103448275872},{"symbol":"RECN","companyName":"Resources Connection Inc.","primaryExchange":"Nasdaq Global Select","sector":"Industrials","calculationPrice":"close","open":15.15,"openTime":1546612200806,"close":15.75,"closeTime":1546635600550,"high":16.73,"low":15.14,"latestPrice":15.75,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635600550,"latestVolume":789474,"iexRealtimePrice":15.74,"iexRealtimeSize":100,"iexLastUpdated":1546635598395,"delayedPrice":15.75,"delayedPriceTime":1546635600550,"extendedPrice":16,"extendedChange":0.25,"extendedChangePercent":0.01587,"extendedPriceTime":1546635616101,"previousClose":13.6,"change":2.15,"changePercent":0.15809,"iexMarketPercent":0.02128,"iexVolume":16800,"avgTotalVolume":143588,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":496803337,"peRatio":19.21,"week52High":19.5,"week52Low":12.72,"ytdChange":0.13440012203876525},{"symbol":"CENX","companyName":"Century Aluminum Company","primaryExchange":"Nasdaq Global Select","sector":"Basic Materials","calculationPrice":"close","open":7.55,"openTime":1546612200900,"close":8.38,"closeTime":1546635600458,"high":8.47,"low":7.43,"latestPrice":8.38,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635600458,"latestVolume":3592558,"iexRealtimePrice":8.365,"iexRealtimeSize":100,"iexLastUpdated":1546635573950,"delayedPrice":8.38,"delayedPriceTime":1546635600458,"extendedPrice":8.38,"extendedChange":0,"extendedChangePercent":0,"extendedPriceTime":1546636661063,"previousClose":7.31,"change":1.07,"changePercent":0.14637,"iexMarketPercent":0.02217,"iexVolume":79647,"avgTotalVolume":1460756,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":734357811,"peRatio":null,"week52High":24.77,"week52Low":6.54,"ytdChange":0.11458192052980129},{"symbol":"AKS","companyName":"AK Steel Holding Corporation","primaryExchange":"New York Stock Exchange","sector":"Basic Materials","calculationPrice":"close","open":2.31,"openTime":1546612293550,"close":2.56,"closeTime":1546635736428,"high":2.63,"low":2.3,"latestPrice":2.56,"latestSource":"Close","latestTime":"January 4, 2019","latestUpdate":1546635736428,"latestVolume":18156337,"iexRealtimePrice":2.565,"iexRealtimeSize":164,"iexLastUpdated":1546635593370,"delayedPrice":2.56,"delayedPriceTime":1546635736428,"extendedPrice":2.55,"extendedChange":-0.01,"extendedChangePercent":-0.00391,"extendedPriceTime":1546637492286,"previousClose":2.25,"change":0.31,"changePercent":0.13778,"iexMarketPercent":0.02288,"iexVolume":415417,"avgTotalVolume":10882511,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":807787430,"peRatio":5.57,"week52High":6.8,"week52Low":2.05,"ytdChange":0.07920259414225939}]

**Comment by evancarter-iex** [comment]
Closing. This should be fixed in https://iexcloud.io Please create a new ticket if you see the same problem in IEXCloud.
