### ISSUE TITLE
API Timeout / Possible blacklist

### ISSUE THREAD

**Issue by JakeMHughes** [iexg/IEX-API#611]
## Summary
I'm trying to pull close to minute-by-minute data for each company during the open market time for 30 days. I think 2-3 days ago I had a temporary block since I was having a parsing issues but since I'm still in the debug/testing phase I chalked it up to my own error. The same thing happened yesterday and I haven't been able to access the API since.

### Date/time of issue
1/4/2019 around 12pm(noon) - now

### API URL
https://api.iextrading.com/1.0/stock/######/batch?types=quote

Where the "##" is the current symbol

### What you expected to happen
Load company quote data

### What actually happened
HTTP Timeout

### Other Information (sample code, links, etc.)
Similar posts like this ask for an IP, my public IP is: 73.147.228.211

I'm trying to start learning machine learning and I want to use this data as the training set. Is there a better way to pull the minute-by-minute data that wont get me blacklisted?

**Comment by evancarter-iex** [comment]
You can use https://api.iextrading.com/1.0/stock/aapl/chart/1d once at the end of the day to get the minute by minute data from the current day.

**Comment by JakeMHughes** [comment]
Thanks, Ill give that a shot and space out the requests after market close
