### ISSUE TITLE
Get minute data filtered by date

### ISSUE THREAD

**Issue by alienbuild** [iexg/IEX-API#612]
Hi,

I'm after access to minute data which is currently available on the 1d chart. Is it possible to also filter by date somehow to retrieve the minute data from a different specific date ie:

https://api.iextrading.com/1.0/stock/market/batch?symbols=atvi,fb&types=quote,chart&range=1d&chartInterval=60&date=20190105

I realise there is a /date/20190105 property for a different end point but it doesn't allow me to set a chartinterval
https://api.iextrading.com/1.0/stock/atvi/chart/date/20190103

I'm hoping I've just got the syntax wrong, but appreciate it may not be possible with the current setup. 

Thanks!

**Comment by danialfarid** [comment]
@alienbuild How did you get around this? I am looking for exactly the same thing to get minute data for specific day in batch.

**Comment by evancarter-iex** [comment]
This is fixed in IEX Cloud. https://iexcloud.io/ for more information. 

https://iexcloud.io/docs/api/#historical-prices
