### ISSUE TITLE
SPY missing prices

### ISSUE THREAD

**Issue by uj-0203mN** [iexg/IEX-API#613]
## Summary
SPY is missing several minute prices:OHLC, e.g. , 1:42pm today.

## Details
Bash script:
spy()
{
    fn="spy.json"
    wget -O $fn "https://api.iextrading.com/1.0/stock/SPY/chart/1d?filter=date,label,close,high,low,open,volume"
    echo
}
export -f spy 
spy.json:
...
{"date":"20190107","label":"1:40 PM","close":255.62,"high":255.62,"low":255.52,"open":255.52,"volume":200},{"    date":"20190107","label":"1:41 PM","close":255.57,"high":255.62,"low":255.55,"open":255.62,"volume":201},{"date":"2019    0107","label":"1:42 PM","high":-1,"low":-1,"volume":0}, ...

### Date/time of issue
Today.

### API URL

See script above.

### What you expected to happen

OHLC should be a Double number ( as a String).

### What actually happened
See spy.json

### Other Information (sample code, links, etc.)

Thanks for your API, it is definitely useful.

**Comment by uj-0203mN** [comment]
Happenis today, Jan. 8, 2018, 11:42am.

{"date":"20190108","label":"11:42 AM","high":-1,"low":-1,"volume":0}]

**Comment by evancarter-iex** [comment]
This should be fixed now.
