### ISSUE TITLE
realtime stock charts with IEX/Websockets?

### ISSUE THREAD

**Issue by KChan440** [iexg/IEX-API#615]
## Summary
Is there a way to have a websocket connection feeding in the chart ranges for a given stock? (1d, 5d, 1m, etc.)

I'm not sure what other supported channels there are besides last, tops, and deep. Do these channels have the ability to present the chart data?

I'm using socket.io in javascript to establish connections.

**Comment by joshuablackburn-iex** [comment]
We can implement Webhooks for chart data since it doesn't update very often.

**Comment by timpaine-iex** [comment]
closing as stale
