### ISSUE TITLE
Peers endpoint seems to be giving weird results

### ISSUE THREAD

**Issue by saadq** [iexg/IEX-API#616]
## Summary
I don't think the `/peers` endpoint is behaving correctly.

## Details

Here are some examples:

---

[`/aapl/peers`](https://api.iextrading.com/1.0/stock/aapl/peers)

```json
["XLK"]
```

---

[`/msft/peers`](https://api.iextrading.com/1.0/stock/msft/peers)

```json
["XLK"]
```

---

[`/googl/peers`](https://api.iextrading.com/1.0/stock/googl/peers)

```json
["XLK"]
```

---

[`/xlk/peers`](https://api.iextrading.com/1.0/stock/xlk/peers)

```json
[]
```

It seems pretty weird that `aapl`, `msft`, and `googl` have a shared peer of `xlk` but they aren't peers of each other. Also, it's strange that `xlk` doesn't consider any of these companies a peer.

### Date/time of issue

1/13/2019 9:35AM EST

### API URL

* https://api.iextrading.com/1.0/stock/aapl/peers
* https://api.iextrading.com/1.0/stock/msft/peers
* https://api.iextrading.com/1.0/stock/googl/peers
* https://api.iextrading.com/1.0/stock/xlk/peers

### What you expected to happen

I expected there to be more peers based on the example given in the docs, although that is a much smaller issue than the fact that the peers that are returned don't seem to be correct.

### What actually happened

Very few companies seem to have peers, and those that do seem to give back weird results.

### Other Information (sample code, links, etc.)

Let me know if there's anything else I can provide.

**Comment by saadq** [comment]
It looks like this is fixed now!

**Comment by saadq** [comment]
I don't think it was actually fixed, it seems more of a case that it sometimes works and sometimes gives weird results. Currently at the time of this writing, it is giving similar results as above.

I noticed that the docs mentioned:

> This is not intended to represent a definitive or accurate list of peers, and is subject to change at any time.

From this statement, are we to gather that this endpoint is not suitable for use as the list of peers can be inaccurate and may change to results like above?

**Comment by amittleider** [comment]
I agree that this endpoint is not giving accurate results. A call to `/nke/peers` returns `[]`, a call to `/fl/peers` returns `[]`, but they are clearly peers.

**Comment by evancarter-iex** [comment]
No longer valid since old API has been retired.
