### ISSUE TITLE
IEX symbols not found

### ISSUE THREAD

**Issue by patcoh** [iexg/IEX-API#618]
## Summary
IEX symbols not found

## Details
Hello,

With the IEX API, there are symbols for companies like **Beiersdorf** or **l'oreal** that I cannot find. They exist in Yahoo finance or Google finance. 

When I try the url https://api.iextrading.com/1.0/stock/BEI.DE/chart/1y?chartInterval=5 , the Unknown symbol error is returned.

Is there a way to get them or IEX API does not list these symbols ?

Thank you.

### Date/time of issue
01/14/2019

### API URL
https://api.iextrading.com/1.0/stock/BEI.DE/chart/1y?chartInterval=5

**Comment by evancarter-iex** [comment]
@davidi99 Those symbols are working in IEXCloud https://iexcloud.io


The BEI.DE is a German Exchange symbol which we are hoping to add at some point to IEXCloud. See here for more information https://github.com/iexg/IEX-API/issues/702
