### ISSUE TITLE
Company API - missing Sector and Industry

### ISSUE THREAD

**Issue by massaroni** [iexg/IEX-API#62]
Sector and Industry are now missing from all companies, including S&P 500 favorites like Apple and Amazon.

[https://api.iextrading.com/1.0/stock/aapl/company](https://api.iextrading.com/1.0/stock/aapl/company)
{"symbol":"AAPL","companyName":"Apple Inc.","exchange":"Nasdaq Global Select",**"industry":""**,"website":"http://www.apple.com","description":"Apple Inc is designs, manufactures and markets mobile communication and media devices and personal computers, and sells a variety of related software, services, accessories, networking solutions and third-party digital content and applications.","CEO":"Timothy D. Cook","issueType":"cs",**"sector":""**}

[https://api.iextrading.com/1.0/stock/amzn/company](https://api.iextrading.com/1.0/stock/amzn/company)
{"symbol":"AMZN","companyName":"Amazon.com Inc.","exchange":"Nasdaq Global Select",**"industry":""**,"website":"http://www.amazon.com","description":"Amazon.com Inc is an online retailer. The Company sells its products through the website which provides services, such as advertising services and co-branded credit card agreements. It also offers electronic devices like Kindle e-readers and Fire tablets.","CEO":"Jeffrey P. Bezos","issueType":"cs",**"sector":""**}

**Comment by joshuablackburn-iex** [comment]
We are looking into this.

**Comment by evancarter-iex** [comment]
Should be fixed now
