### ISSUE TITLE
Include changePercent on tops websocket channel

### ISSUE THREAD

**Issue by AdrenaLeen** [iexg/IEX-API#620]
Would be possible to include changePercent on tops websocket channel? Currently the websocket provide only marketPercent, would be very useful to provide changePercent too. By changePercent I mean same data returned by quote API endpoint /stock/aapl/quote

**Comment by joshuablackburn-iex** [comment]
We have streaming stock quotes with IEX Cloud. We are unable to include change percent with TOPS since it requires non IEX data.
