### ISSUE TITLE
primaryExchange returns null in limited equities

### ISSUE THREAD

**Issue by karla72** [iexg/IEX-API#621]
## Summary
We use your api v1. 

## Details
Out of ~8000 tickers, ~150 tickers return a null "primaryExchange". 

### Date/time of issue
Jan 14, 2019 8 PM EST

### API URL

Symbols are eliminated for simplicity. 

`https://api.iextrading.com/1.0/stock/market/batch?symbols=&types=quote,chart&range=1m&last=10`

### What you expected to happen
To return a primary exchange (e.g., Nasdaq Global Select, NYSE, etc.)

### Other Information (sample code, links, etc.)

Not a big issue, though!
On a irrelevant topic, is API V2 ready to use for those same API V1 tickers?
Is there a link that we can go thru to see the main differences between V1 and V2? 
Which one do you recommend? 

Thanks a million! 🌼🌼🌼🌼

Emma

**Comment by evancarter-iex** [comment]
@karla72 

Sorry about the delay in response. Is this still an issue with IEXCloud?

**Comment by karla72** [comment]
No, Not an issue anymore.  Thanks so much for your response!

**Comment by evancarter-iex** [comment]
Closing. Open a new ticket if you see any problems in IEX Cloud. Thanks!
