### ISSUE TITLE
Batch Requests is not giving the results in a JSON array

### ISSUE THREAD

**Issue by dilipdiwakar** [iexg/IEX-API#622]
## Summary

Batch Requests is not giving the results in a JSON array

## Details
We want the response to come in a Json Array for batch requests. the response we get is pretty hard for us to iterate through each symbols. if the response comes in a json array, it will be easy for us to iterate through the each symbols.

### Date/time of issue
Jan 15 2019.

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote&displayPercent=true&filter=symbol,companyName,sector,latestPrice,previousClose,change,changePercent,week52Low,week52High,marketCap,peRatio

### What you expected to happen

we want the results to shown in a Jsonarray, so that it will be easy to iterate through the array for every symbols.
[ {
  "AAPL": {
    "quote": {
      "symbol": "AAPL",
      "companyName": "Apple Inc."
    }
  }
},{
  "FB": {
    "quote": {
      "symbol": "FB",
      "companyName": "Facebook Inc."
    }
  }
}
]

### What actually happened

the below api response is not in a Json Array. it is hard to iterate through the symbols
{
  "AAPL": {
    "quote": {
      "symbol": "AAPL",
      "companyName": "Apple Inc."
    }
  },
  "FB": {
    "quote": {
      "symbol": "FB",
      "companyName": "Facebook Inc."
    }
  }
}

### Other Information (sample code, links, etc.)
Can you please make the necessary change. there is no issue with the  response , but we need it in a array format

**Comment by sheraztariq147** [comment]
@dilipdiwakar which language you are using?

**Comment by dilipdiwakar** [comment]
I am using javascript , irrespective of any language, if it is not a JsonArray, We cannot iterate through the elements and store it in database or we cannot even store it in a variable and display it the UI.

please suggest me how i can iterate your batch response. Is it possible for you guys to give it as a jsonArray only for this batch request.

**Comment by saadq** [comment]
I would prefer an array as well as that would be easier to work with, but it shouldn't be too much of an issue converting the response to an array yourself by doing something like:

```js
const response = {
  "AAPL": {
    "quote": {
      "symbol": "AAPL",
      "companyName": "Apple Inc.",
      "sector": "Technology",
      "latestPrice": 155.86,
      "previousClose": 154.94,
      "change": 0.92,
      "changePercent": 0.594,
      "week52Low": 142,
      "week52High": 233.47,
      "marketCap": 737187095580,
      "peRatio": 13.13
    }
  },
  "FB": {
    "quote": {
      "symbol": "FB",
      "companyName": "Facebook Inc.",
      "sector": "Technology",
      "latestPrice": 148.3,
      "previousClose": 147.54,
      "change": 0.76,
      "changePercent": 0.515,
      "week52Low": 123.02,
      "week52High": 218.62,
      "marketCap": 426182702860,
      "peRatio": 20.07
    }
  }
}

const array = Object.values(response).map(stock => stock.quote)

console.log(array)

// Output:

[
  {
    "symbol": "AAPL",
    "companyName": "Apple Inc.",
    "sector": "Technology",
    "latestPrice": 155.86,
    "previousClose": 154.94,
    "change": 0.92,
    "changePercent": 0.594,
    "week52Low": 142,
    "week52High": 233.47,
    "marketCap": 737187095580,
    "peRatio": 13.13
  },
  {
    "symbol": "FB",
    "companyName": "Facebook Inc.",
    "sector": "Technology",
    "latestPrice": 148.3,
    "previousClose": 147.54,
    "change": 0.76,
    "changePercent": 0.515,
    "week52Low": 123.02,
    "week52High": 218.62,
    "marketCap": 426182702860,
    "peRatio": 20.07
  }
]
```

**Comment by dilipdiwakar** [comment]
Thanks for your response.

Why for some symbols stock price is not matching with the real time data. I
see a huge difference in the price , when i make the below call
https://api.iextrading.com/1.0/stock/market/collection/sector?collectionName=Technology

Is there a way i can get a real time data ?

Thanks for your help...

-Dilip

**Comment by joshuablackburn-iex** [comment]
@dilipdiwakar Is this still an issue? If prices are not matching, can you please provide more information.

The result of a batch request depends on how you want to use it. We could add an optional url param to convert results to an array to keep the call backwards compatible.
