### ISSUE TITLE
How to get stock price (close) at a given date?

### ISSUE THREAD

**Issue by wichtounet** [iexg/IEX-API#623]
Hi, 

I just discovered this API and it seems absolutely great. I only have two needs: Get the actual price and get the close price at a given date. 

I did not find any endpoint for getting the stock price at a given date. chart/date only works for 30 days in the past. 

Is there anything like that?

Thanks

**Comment by wichtounet** [comment]
Thank you for your answer. 
Yes, but this only works for the last year. I would need dates farther in the past. Moreover, it gives me way too much data. I would like only the data at a date.

**Comment by craigs99** [comment]
Has anyone figured this out?  I currently have logic that uses the chart endpoint recommended above, then I loop through it to find the date I am looking for.

However, the new cloud platform limits the number of messages you can receive in a month.  Retrieving all the unneeded data will be costly.  If I use /chart/date/yyyymmdd, it returns the data by minute which is just as costly.

Any thoughts?

**Comment by joshuablackburn-iex** [comment]
We will add this functionality in today.

**Comment by craigs99** [comment]
That great!  Thanks.   where did you add the functionality?  Did you add a new endpoint?  or change an existing one?

**Comment by wichtounet** [comment]
Is the new feature /stock/aapl/chart/date/20190109?chartByDay=true ?

**Comment by craigs99** [comment]
I can't seem to get that to work.  When I make the following call:

https://cloud.iexapis.com/beta/stock/AAPL/chart/date/20190301?chartByDay=true?token=XXXXX

I get the following error:

{"error":"child \"chartByDay\" fails because [\"chartByDay\" must be a boolean]"}

What am I doing wrong?

**Comment by evancarter-iex** [comment]
https://cloud.iexapis.com/beta/stock/AAPL/chart/date/20190301?chartByDay=true&token=XXXXX

Note the &token, which should fix your problem. We need to fix that error message.

**Comment by evancarter-iex** [comment]
Also this should be useful for anyone who needs more information about how Query Strings work: 
https://en.wikipedia.org/wiki/Query_string

**Comment by craigs99** [comment]
Well, that is embarrassing.   Thanks!
