### ISSUE TITLE
Websocket API does not works

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#626]
## Summary
Connection to websocket works properly , I receive some messages, then after a few seconds no message is received

### Date/time of issue
January 23, 2019

### API URL
https://ws-api.iextrading.com/1.0/tops

### What you expected to happen
Receive messages continuously 

### What actually happened
After a few seconds no message is received

Anyone else has this issue?

Thanks!

**Comment by joshuablackburn-iex** [comment]
Does your websocket library handle reconnects?

**Comment by gabrieldodan** [comment]
@joshuablackburn-iex I am not disconnected, simply I not receive messages

**Comment by gabrieldodan** [comment]
I am using socket.io library as suggested by APi documentation

**Comment by Code123321** [comment]
@joshuablackburn-iex Same for me. There seems to be a problem on the iex side with the websocket.

**Comment by evancarter-iex** [comment]
Let me know if this fixes the problem.

**Comment by Code123321** [comment]
@evancarter-iex Thanks for the fast support. It does work for me. Can you tell me whether its possible to get the data which we didn`t get today? I'm looking for time & sales data from the 30 companies of Dow Jones.

**Comment by gabrieldodan** [comment]
@evancarter-iex Seems to be fixed. Thank you!

**Comment by kwcoffee1** [comment]
I'm new to using WebStockIO and want to program in C#. So, I'm attempting to used a third-party library. Upon running the code below, I get the following console window displays: "DoWrite data = System.Byte[]".  I'm not sure if the code is at fail or the webstock server is at fail.

    using Quobject.SocketIoClientDotNet.Client;  // NuGet package
    using System;

    namespace ConsoleApp1
    {
        class Program
        {
            static void Main(string[] args)
            {
                var socket = IO.Socket("https://ws-api.iextrading.com/1.0/tops");

                // Listen to the channel"s messages
                socket.On("message", message => Console.WriteLine(message));

                // Connect to the channel
                socket.On("connect", () => {
                    Console.WriteLine("Connected");
                    // Subscribe to topics (i.e. appl,fb,aig+)
                    socket.Emit("subscribe", "snap,fb,aig+");

                    // Unsubscribe from topics (i.e. aig+)
                    socket.Emit("unsubscribe", "aig+");
                });

                Console.ReadLine();
                // Disconnect from the channel
                socket.Disconnect();
                // OR:
                //socket.On("disconnect", () => Console.WriteLine("Disconnected."));
            }
        }
    }

Any suggestions on how to implement WebStockIO in C# ?

Thanks

**Comment by MrDevDevy** [comment]
> 
> 
> I'm new to using WebStockIO and want to program in C#. So, I'm attempting to used a third-party library. Upon running the code below, I get the following console window displays: "DoWrite data = System.Byte[]". I'm not sure if the code is at fail or the webstock server is at fail.
> 
> ```
> using Quobject.SocketIoClientDotNet.Client;  // NuGet package
> using System;
> 
> namespace ConsoleApp1
> {
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             var socket = IO.Socket("https://ws-api.iextrading.com/1.0/tops");
> 
>             // Listen to the channel"s messages
>             socket.On("message", message => Console.WriteLine(message));
> 
>             // Connect to the channel
>             socket.On("connect", () => {
>                 Console.WriteLine("Connected");
>                 // Subscribe to topics (i.e. appl,fb,aig+)
>                 socket.Emit("subscribe", "snap,fb,aig+");
> 
>                 // Unsubscribe from topics (i.e. aig+)
>                 socket.Emit("unsubscribe", "aig+");
>             });
> 
>             Console.ReadLine();
>             // Disconnect from the channel
>             socket.Disconnect();
>             // OR:
>             //socket.On("disconnect", () => Console.WriteLine("Disconnected."));
>         }
>     }
> }
> ```
> 
> Any suggestions on how to implement WebStockIO in C# ?
> 
> Thanks

I am having a similar problem using WebSocketSharp. My error is |Fatal|WebSocket.doHandshake|Not a WebSocket handshake response.

**Comment by MrDevDevy** [comment]
I got a websocket response, but it's not accepting my connection. Here's my error: 

> |Fatal|StackBuilderSink._PrivateProcessMessage|WebSocketSharp.WebSocketException: A timeout has occurred while reading an HTTP request/response. ---> System.IO.IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.Net.Sockets.SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
>                               at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>                               at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>                               --- End of inner exception stack trace ---
>                               at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>                               at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
>                               at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>                               at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>                               at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>                               at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>                               at System.IO.Stream.ReadByte()
>                               at WebSocketSharp.HttpBase.readHeaders(Stream stream, Int32 maxLength)
>                               at WebSocketSharp.HttpBase.Read[T](Stream stream, Func`2 parser, Int32 millisecondsTimeout)
>                               --- End of inner exception stack trace ---
>                               at WebSocketSharp.HttpBase.Read[T](Stream stream, Func`2 parser, Int32 millisecondsTimeout)
>                               at WebSocketSharp.HttpRequest.GetResponse(Stream stream, Int32 millisecondsTimeout)
>                               at WebSocketSharp.WebSocket.sendHttpRequest(HttpRequest request, Int32 millisecondsTimeout)
>                               at WebSocketSharp.WebSocket.sendHandshakeRequest()
>                               at WebSocketSharp.WebSocket.doHandshake()
>                               at WebSocketSharp.WebSocket.connect()

It's got a blockingcall. If I understand correctly, that means on the server's end I am being denied, but I have no way to know the reason.

**Comment by joshuablackburn-iex** [comment]
Fixed with IEX Cloud.  https://iexcloud.io/docs/api/#streaming
