### ISSUE TITLE
stock/market/today-earnings is not showing any results

### ISSUE THREAD

**Issue by dilipdiwakar** [iexg/IEX-API#627]
## Summary

why this endpoint always give 0 results

https://api.iextrading.com/1.0/stock/market/today-earnings

{"bto":[],"amc":[]}

## Details
the endpoint is not returning any results.

### Date/time of issue

Jan 23rd 2019

### API URL
https://api.iextrading.com/1.0/stock/market/today-earnings

**Comment by evancarter-iex** [comment]
Appears to be working.
