### ISSUE TITLE
Add support for OTC markets

### ISSUE THREAD

**Issue by kazazor** [iexg/IEX-API#63]
The market is not supported so not data on OTC stocks could be fetched.
For example: CBIS

**Comment by Jack-Zeh** [comment]
I would very much like this as well. It was provided in the old Yahoo interface.
How long is "long-term" LOL...

**Comment by rwgieseler** [comment]
This OTC Stock support would be a huge plus on the researching and tracking I currently am doing manually in supporting part of my 401K investment opportunities.  Thanks and keep us posted.

**Comment by Jake0303** [comment]
Would love to see this happen!

**Comment by NateRobinHood** [comment]
I would like to see this feature as well, currently can't fetch data for ntdoy(nintendo adr stock)

**Comment by Jake0303** [comment]
@evancarter-iex Any updates on this? Just curious

**Comment by TSHsoft** [comment]
I also cannot fetch data for TCEHY (Tencent Holdings)

**Comment by jcartan** [comment]
Another vote for this feature.  I also cannot fetch data for TCEHY and several other companies in my portfolio.

**Comment by bartclaeys** [comment]
Same here, trying to fetch data for DMLRY, BMWYY and TCEHY.

**Comment by ikoniaris** [comment]
+1 for this feature.

**Comment by evancarter-iex** [comment]
OTC is now supported in IEXCloud. Sign up for beta access, if you haven't already.

https://iexcloud.io/
