### ISSUE TITLE
Issue with date parameter for HTTP requests

### ISSUE THREAD

**Issue by lawleygrant** [iexg/IEX-API#630]
## Summary
There is an issue with the date parameter when making HTTP requests.  I have tried a bunch of different dates to try to return the minute-by-minute chart for that specific date but the API keeps returning an empty array no matter what date I try.  I even tried to use the one provided on the documentation (/stock/aapl/chart/date/20180129) but it doesn't work.  **This is a pretty serious issue** as my code depends on being able to regularly pull the data from specific dates in the past.  

### Date/time of issue

I discovered this issue on January 27, 2019

### API URL

/stock/aapl/chart/date/20180129

### What you expected to happen

I expected the API to return a JSON object of minute-by-minute data

### What actually happened

API returned an empty JSON object for all dates i tried.

**Comment by evancarter-iex** [comment]
This is fixed in https://iexcloud.io
