### ISSUE TITLE
Value of "0" for "latestEPS" in /stocks/{symbol}/stats is ambiguous

### ISSUE THREAD

**Issue by ManfredLange** [iexg/IEX-API#631]
## Summary

Value of "0" for "latestEPS" in /stocks/{symbol}/stats is ambiguous as it could mean at least the follwing two things:
- latestEPS is actually zero 
- latestEPS value is not available

Example: https://api.iextrading.com/1.0/stock/aapl/stats shows "0" for "latestEPS" for "latestEPSDate" of 30 Sep 2018. However, EPS for Apple in that quarter was $2.94/share (basic) and $2.92/share (diluted) as per Morningstar.

### Date/time of issue

From 26 January 2019, but could have been the case prior to this date.

### API URL
https://api.iextrading.com/1.0/stock/aapl/stats

or generically
https://api.iextrading.com/1.0/stock/{symbol}/stats

### What you expected to happen

If a given value is not available, then it should be consistently shown as "null" instead of "0" for this field and others. An EPS of 0 is very much a valid value. However, it clearly is wrong for symbol AAPL for the quarter ending 30 Sep 2018.

### What actually happened

IEX version 1.0 returned value "0" instead of the correct value (either 2.94 or 2.92) or "null" if the value is in fact not available in your data.

### Other Information (sample code, links, etc.)

I think it would be important for both version 1.0 of the api as well as the new 2.0 version to clearly separate between the value "0" (i.e. zero) and "null" (not available) for all values. This should be consistently being used for all endpoints for all values.

I had a look at these issues as well but believe they are different from this one:

- https://github.com/iexg/IEX-API/issues/38
- https://github.com/iexg/IEX-API/issues/306
- https://github.com/iexg/IEX-API/issues/344

**Comment by evancarter-iex** [comment]
This should be fixed in IEX Cloud. If you see any examples there, please file a bug report for them.

https://iexcloud.io
