### ISSUE TITLE
Websocket-Sharp Example?

### ISSUE THREAD

**Issue by MrDevDevy** [iexg/IEX-API#632]
I am unable to connect. Have any users using Websocket-Sharp been successful in retrieving data? Please provide an example? Thanks!

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebSocketSharp;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {

            using (var ws = new WebSocket("wss://ws-api.iextrading.com/1.0/tops/socket.io/?EIO=3&transport=websocket"))
            {

                ws.OnMessage += (sender, e) =>
                    Console.WriteLine("Data: " + e.Data);

                ws.Connect();

                Console.ReadKey(true);

            }
        }
     
    }
}
```
I checked an error message and it seems my connection is getting denied for some reason. Here is my error:

> |Fatal|StackBuilderSink._PrivateProcessMessage|WebSocketSharp.WebSocketException: A timeout has occurred while reading an HTTP request/response. ---> System.IO.IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.Net.Sockets.SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
>                                at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>                                at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>                                --- End of inner exception stack trace ---
>                                at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>                                at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
>                                at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>                                at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>                                at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>                                at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>                                at System.IO.Stream.ReadByte()
>                                at WebSocketSharp.HttpBase.readHeaders(Stream stream, Int32 maxLength)
>                                at WebSocketSharp.HttpBase.Read[T](Stream stream, Func`2 parser, Int32 millisecondsTimeout)
>                                --- End of inner exception stack trace ---
>                                at WebSocketSharp.HttpBase.Read[T](Stream stream, Func`2 parser, Int32 millisecondsTimeout)
>                                at WebSocketSharp.HttpRequest.GetResponse(Stream stream, Int32 millisecondsTimeout)
>                                at WebSocketSharp.WebSocket.sendHttpRequest(HttpRequest request, Int32 millisecondsTimeout)
>                                at WebSocketSharp.WebSocket.sendHandshakeRequest()
>                                at WebSocketSharp.WebSocket.doHandshake()
>                                at WebSocketSharp.WebSocket.connect()

**Comment by MrDevDevy** [comment]
I cannot make a websocket connection to ws-api.iextrading.com/1.0/tops/ so I tried wss://tops.iextrading.com/ and a connection was made. I don't know if it's possible to communicate here? I am new to websockets, but here is where I am now. I get a connection with the response: 

> RESPONSE: 0{"sid":"Fn6ubOBr90FRM6H1AABG","upgrades":[],"pingInterval":25000,"pingTimeout":60000}

The upgrade field is empty, I am expecting it to say websocket. Still, I am trying to send the server the subscribe event with this string: 

> 42["subscribe",{"symbol":"AAPL"}]

After this point is hangs then times out. Here's my code below:

```
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebSocketSharp;
using Newtonsoft.Json;

class StockQuote
{
    public StockQuote(){}
    public string symbol { get; set; }
}

namespace ConsoleApp2
{

    class Program
    {

        static void Main(string[] args)
        {

            //using (var ws = new WebSocket("wss://ws-api.iextrading.com/1.0/tops/socket.io/?EIO=3&transport=websocket"))
            using (var ws = new WebSocket("wss://tops.iextrading.com/socket.io/?EIO=3&transport=websocket"))
            {
                StockQuote AAPL_Quote = new StockQuote();
                AAPL_Quote.symbol = "AAPL";

                string ServerMessage = "42[\"subscribe\",";
                ServerMessage += JsonConvert.SerializeObject(AAPL_Quote);
                ServerMessage += "]";

                ws.OnMessage += (sender, e) =>
                {
                    Console.WriteLine("RESPONSE: " + e.Data);
                    if(e.Data == "40"){
                        Console.WriteLine("SENDING MESSAGE..");
                        Console.WriteLine(ServerMessage);
                        ws.Send(ServerMessage);
                    }
                };

                ws.OnError += (sender, e) => {
                    Console.WriteLine("ERROR: " + e.Message);
                };

                ws.OnClose += (sender, e) => {
                    Console.WriteLine("CLOSED!");
                };

                ws.OnOpen += (sender, e) =>
                {
                    Console.WriteLine("CONNECTED!");

                };

                Console.WriteLine("CONNECTING..");
                ws.ConnectAsync();

                Console.ReadKey(true);

            }

        }

    }
}

```

**Comment by RuiFigueiredoAlgo** [comment]
That's pretty easy in VB6 you just add msinet.ocx to the project 
than

Public Function API_Tira(Ficheiro As String) As String
Dim s As String
Dim I As Integer
    On Error GoTo FTPPutError
    Form1.Inet1.AccessType = icUseDefault
    Form1.Inet1.Protocol = icHTTPS
    Form1.Inet1.RemotePort = 443
    Form1.Inet1.RequestTimeout = 30
    I = 0
    API_Tira = Form1.Inet1.OpenURL(Ficheiro)
    Form1.Inet1.Execute
    Sleep 30
    While Form1.Inet1.StillExecuting = True And I < 40
        I = I + 1
        DoEvents
    Wend
    Form1.Inet1.Cancel
    Exit Function
FTPPutError:
    Debug.Print Err.Description
    Form1.Inet1.Cancel
    Form1.Inet1.Cancel
    Form1.Inet1.Cancel
    API_Tira = "-1"
End Function

than use it 

tratar = API_Tira("https://api.iextrading.com/1.0/stock/market/batch?symbols=" & qual & "&types=quote")

VB6 the greatest and fastest language and now with updated sqlserver client for the newest sql server generations including azure sql server since this client now provides the encripted and nlatest TLS 1.2 standards

Announcement: bit.ly/SNC18
OLEDB Driver Info: bit.ly/OLEDB18
ADODB Info with Native Client 18: bit.ly/ADODB18
Download Native Client 18 Here: bit.ly/SNC18Down

Anyone ? using the amazing IEX API with VB6 ?

Kinds regards

**Comment by MrDevDevy** [comment]
I'll look into it if I can't first resolve the issue in C#. I was hoping to use this with SciCharts which targets C#/WPF

Wouldn't OpenURL block? I want to display data in real time.

**Comment by RuiFigueiredoAlgo** [comment]
Openurl does not block it is a "get" request. The only way is to get several requests to get real time.
I think! I'm still learning and iex is simply amazing.
Tomorrow I will try using winsocket instead of inet, if I can figure differences!

But IMHO I think the overall goal is many openurl requests, you can check when iex 2.0 will be launched, will be paid and for 9$ you will get right to 5 million requests per month.

I think this shows a little how this is intended to work.

Regards

**Comment by MrDevDevy** [comment]
I'll check today and see if I can't get an asynchronous read using your method. At this point, i'd still prefer a solution for my original post, thanks again! :)
