### ISSUE TITLE
latestVolume resets to 1,000 after going almost to 10,000 

### ISSUE THREAD

**Issue by RuiFigueiredoAlgo** [iexg/IEX-API#633]
## Summary

I've been recording nearly 70 stock symbols from premarket to posmarket every 30seconds

## Details

Everytime latestvolume approaches 10,000 it goes back to 1,0000

### Date/time of issue

2019-02-01

### API URL

https://api.iextrading.com/1.0/stock/market/batch?symbols=UQM,AXON,IAG,MIN,AXU,UUUU,AKS,CVM,CNAT,CRNT,VVUS,BOXL,JVA,BKYI,FEDU,MLSS,AWSM,DTEA,ZYNE,EYEN,TTNP,BIOC,RWLK,AVCO,TRVN,IPCI,HMNY,OCX,EGO,HSGX,SXTC,VTVT,CODX,SCYX,BPTH,SPI,MNGA,CCCL,INPX,FBIO,TROV,CREG,CLDX,GERN,BTX,APRN,ONCS,MYND,AMMA,CTRV,ONTX,AKAO,OGEN,DPW,NVCN,PRAN,LODE,FTNW,XSPA,FRAN,SNNA,OHGI,AAPL&types=quote

### What you expected to happen

Volume to go up and down but not kind of a reset !

### Other Information (sample code, links, etc.)

![latestvolume](https://user-images.githubusercontent.com/47220667/52129574-c01daf00-262f-11e9-9e6b-a043e2e4948a.png)

**Comment by TonyP1** [comment]
Aldo, is this program  available or some you created?
https://api.iextrading.com/1.0/stock/aapl/quote/stock/open-close
You can use this for latest quotes

**Comment by RuiFigueiredoAlgo** [comment]
Solved 

I began the development in "mysql" and changed to "sql server" because of better "window functions" to process technical indicators, so when the automated algo started it was treating an former mysql field which was number in mysql now in sqlserver was text 

![untitled](https://user-images.githubusercontent.com/47220667/52174721-c0cd5700-278f-11e9-8c85-33389b23747e.png)

Function TiraSessao1MinutoREFAZ(qual As String, DemoTrace As Boolean, Optional JsonString As String, Optional DataS As Date, Optional HoraS As String) As Integer
Dim tratar As String
Dim I, J As Long
Dim Acao As Integer
Dim rs As Recordset
Dim rsUltimo As Recordset
Dim Trailing As Recordset
Dim JB  As JsonBag
Dim PenultimoVolume As Long

Dim UltimoPreco As Currency
Dim AcaoTratar As Integer
Dim ValorAComprar As Currency

Dim RecMarket1m As Long
Dim SeqMarket1m As Long
    
Dim CalculoTrailer As Currency

    If DemoTrace = True Then
        tratar = JsonString
        If qual = "REFAZ" Then
            Tabela = ""
        Else
            Tabela = "DEMO_"
        End If
        Form1.List1.Refresh
    Else
        Tabela = ""
        tratar = ""
        I = 0
        Do
            'Debug.Print "https://api.iextrading.com/1.0/stock/market/batch?symbols=" & qual & "&types=quote"
            
            tratar = API_Tira("https://api.iextrading.com/1.0/stock/market/batch?symbols=" & qual & "&types=quote")
            'Tratar = API_Tira("https://api.iextrading.com/1.0/stock/" & qual & "/quote")
            If tratar = "-1" Or tratar = "" Then
                Sleep 3000
                DoEvents
            End If
            I = I + 1
        Loop Until (tratar <> "-1" And tratar <> "") Or I = 30
        
        If I = 30 Then
            TiraSessao1MinutoREFAZ = -1
            Exit Function
        End If
    End If
        
    
    If tratar = "Unknown symbol" Or tratar = "Not Found" Or tratar = "" Then
        TiraSessao1MinutoREFAZ = -1
        Exit Function
    Else
        'Ligacao.Execute "insert into JSONs (data,hora,jsons ) values ('" & Format(Date, "yyyy-MM-dd") & "','" & Time & "','" & tratar & "')"
        If DemoTrace = False Then
            Abre_RECORDSET Ligacao, Trailing, "select * from jsons where idseq = -1"
            Trailing.AddNew
            Trailing!Data = Format(Date, "yyyy-MM-dd")
            Trailing!hora = Trim(Time)
            Trailing!JSON = tratar
            Trailing.Update
            Fecha_RECORDSET Trailing
        End If
        Set JB = New JsonBag
        JB.JSON = tratar
        
        Abre_RECORDSET Ligacao, Trailing, "select * from dbo.Trailing"
        
        For I = 1 To JB.Count
            If JB.Name(I) = "TOPS" Then
                'Stop
            End If
            Abre_RECORDSET Ligacao, rs, "select * from dbo.stocks where symbol = '" & JB.Name(I) & "'"
            Acao = rs!IdStock
            Fecha_RECORDSET rs
            
            'AcaoTratar = AcaoIndice(Acao)
            
            Abre_RECORDSET Ligacao, rs, "select * from dbo." & Tabela & "Market1m_today where idstock = -1"
            rs.AddNew
            For J = 1 To JB.Item(I).Item(1).Count
                If ExisteCampo(rs, JB.Item(I).Item(1).Name(J)) = True Then
                    If JB.Item(I).Item(1).Item(J) <> "" Then
                        Select Case UCase(JB.Item(I).Item(1).Name(J))
                            Case UCase("latestVolume")
                                'Acoes(AcaoTratar).VolumeAtual = CLng(JB.Item(I).Item(1).Item(J))
                            Case UCase("previousClose")
                                'Acoes(AcaoTratar).FechoAnterior = CCur(JB.Item(I).Item(1).Item(J))
                        End Select
                        If rs.Fields(JB.Item(I).Item(1).Name(J)).Type = 200 Then
                            rs.Fields(JB.Item(I).Item(1).Name(J)).Value = Left(JB.Item(I).Item(1).Item(J), rs.Fields(JB.Item(I).Item(1).Name(J)).DefinedSize)
                        Else
                            If rs.Fields(JB.Item(I).Item(1).Name(J)).Type = 135 Then
                                rs.Fields(JB.Item(I).Item(1).Name(J)).Value = Epoch2Date(CCur(JB.Item(I).Item(1).Item(J)))
                            Else
                                'Debug.Print rs.Fields(JB.Item(I).Item(1).Name(J)).Type & " " & rs.Fields(JB.Item(I).Item(1).Name(J)).Name
                                If InStr(1, UCase(JB.Item(I).Item(1).Name(J)), UCase("changePercent")) <> 0 Then
                                    rs.Fields(JB.Item(I).Item(1).Name(J)).Value = JB.Item(I).Item(1).Item(J) * 100
                                    rs.Fields(JB.Item(I).Item(1).Name(J)).Value = Round(rs.Fields(JB.Item(I).Item(1).Name(J)).Value, 3)
                                    rs.Fields(JB.Item(I).Item(1).Name(J)).Value = Round(rs.Fields(JB.Item(I).Item(1).Name(J)).Value, 3)
                                    If InStr(1, UCase(JB.Item(I).Item(1).Name(J)), UCase("extend")) <> 0 Then
                                        If rs.Fields(JB.Item(I).Item(1).Name(J)).Value <> 0 Then
                                            'Acoes(AcaoTratar).ExtendedChangePercent = rs.Fields(JB.Item(I).Item(1).Name(J)).Value
                                        End If
                                    Else
                                        If rs.Fields(JB.Item(I).Item(1).Name(J)).Value <> 0 Then
                                            'Acoes(AcaoTratar).ChangePercent = rs.Fields(JB.Item(I).Item(1).Name(J)).Value
                                        End If
                                    End If
                                Else
                                    
                                    If JB.Item(I).Item(1).Name(J) = "latestTime" Then
                                        rs.Fields(JB.Item(I).Item(1).Name(J)).Value = Left(JB.Item(I).Item(1).Item(J), 12)
                                    Else
                                        If rs.Fields(JB.Item(I).Item(1).Name(J)).Type = 4 Then
                                            rs.Fields(JB.Item(I).Item(1).Name(J)).Value = JB.Item(I).Item(1).Item(J)
                                        Else
                                            If rs.Fields(JB.Item(I).Item(1).Name(J)).Type = 20 Then ' long
                                                rs.Fields(JB.Item(I).Item(1).Name(J)).Value = JB.Item(I).Item(1).Item(J)
                                            Else
                                                If rs.Fields(JB.Item(I).Item(1).Name(J)).Type = 3 Then ' int
                                                    rs.Fields(JB.Item(I).Item(1).Name(J)).Value = JB.Item(I).Item(1).Item(J)
                                                Else
                                                    'MsgBox JB.Item(I).Item(1).Name(J) & " " & rs.Fields(JB.Item(I).Item(1).Name(J)).Type
                                                    rs.Fields(JB.Item(I).Item(1).Name(J)).Value = Left(JB.Item(I).Item(1).Item(J), rs.Fields(JB.Item(I).Item(1).Name(J)).DefinedSize)
                                                End If
                                            End If
                                        End If
                                    End If
                                End If
                            End If
                        End If
                    End If
                End If
            Next
            rs!IdStock = Acao
            If DemoTrace = False Then
                rs!Data = Format(Date, "yyyy-MM-dd")
                rs!hora = Format(Time, "hh:mm:ss")
            Else
                rs!Data = DataS
                rs!hora = HoraS
            End If
            
            Debug.Print rs!extendedPriceTime
            If Trim(UCase(rs!latestsource)) = UCase("Close") Or IsNull(rs!latestvolume) = True Then
                'Acoes(AcaoTratar).Close = rs!extendedprice
                rs.CancelUpdate
            Else
                If Time >= "14:30:00" Then
                End If
                rs.Update
            End If
            Fecha_RECORDSET rs
        Next
        Fecha_RECORDSET Trailing
    End If
    TiraSessao1MinutoREFAZ = 1
End Function

**Comment by TonyP1** [comment]
Thanks
Rui, I believe you are Brasilian, are you at  Usa or Brasil ?

**Comment by RuiFigueiredoAlgo** [comment]
Neither, Portugal
