### ISSUE TITLE
year5changepercent is not showing the sign for positive or negative

### ISSUE THREAD

**Issue by mcollis2** [iexg/IEX-API#634]
## Summary

When you call stats on a ticker symbol, it would appear that the sign for the change percent is not correct necessarily, particularly for year5changepercent.

## Details
If I run this command in powershell, which returns stats for a symbol:

Invoke-WebRequest -method Get https://api.iextrading.com/1.0/stock/ZF/stats -UseBasicParsing

I get year5changepercent as 0.3163... at time of writing.

If I go to various sources, the year 5 change percent should be more like -0.3163.  This is how your year1changepercent works.

DVD would be another symbol to test with but I think it is probably happening for all symbols.

### Date/time of issue

2/1/2019 10:41am.

### API URL

https://api.iextrading.com/1.0/stock/DVD/stats
https://api.iextrading.com/1.0/stock/ZF/stats

### What you expected to happen

It to return a negative value

### What actually happened

It returns a positive value

### Other Information (sample code, links, etc.)

Perhaps you have defined a field to only accept a positive number.

**Comment by mcollis2** [comment]
This is probably also broken for year2percent from again reviewing ZF.

Thanks

**Comment by evancarter-iex** [comment]
This is fixed in IEXCloud. https://iexcloud.io for more information.
