### ISSUE TITLE
IEX Cloud: Stock Batch Requests unexpected response, incorrect message counting

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#635]
## Summary

Some Stock batch requests return duplicate results, and charge against messaging count accordingly.

## Details

Consider:

https://cloud.iexapis.com/beta/stock/market/batch?types=price&symbols=aapl&token=

This returns as expected:

``[{"AAPL":{"price":166.44}}]``

However, when adding another symbol, duplicate records are returned.

### API URL

https://cloud.iexapis.com/beta/stock/market/batch?types=price&symbols=aapl,tsla&token=

### What you expected to happen

``[{"AAPL":{"price":166.44}}, {"TSLA:{"price":322.22}}]``

### What actually happened

``[{"AAPL":{"price":166.44}},{"AAPL":{"price":166.44}},{"TSLA:{"price":322.22}},{"TSLA:{"price":322.22}}]``

### Other Information (sample code, links, etc.)

Per the above, these requests charge for 4 messages, though they are 2-message requests.

**Comment by joshuablackburn-iex** [comment]
This has been fixed.
