### ISSUE TITLE
IEX Cloud: Account usage fails without specifying type

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#636]
## Summary

When obtaining usage data (per https://iexcloud.io/docs/api/#usage), the ``type`` parameter is listed as Optional. However, "Not Found" is returned when it is not specified.

## Details

The below does not work:

https://cloud.iexapis.com/beta/account/usage?token=

but 

https://cloud.iexapis.com/beta/account/usage/messages?token=
https://cloud.iexapis.com/beta/account/usage/rules?token=

etc. are ok

### Date/time of issue

2/2/19 7:30pm EST

### API URL

https://cloud.iexapis.com/beta/account/usage?token=

### What you expected to happen

Usage information for account

### What actually happened

"Not found"

**Comment by evancarter-iex** [comment]
This is deployed and fixed.
