### ISSUE TITLE
IEX Cloud: Certain account usage types return "The API key provided is not valid"

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#637]
## Summary

Certain Account endpoints return unexpected error message

## Details

The ``/usage/rules``, ``/usage/rule-records``, ``/usage/alerts``, and ``/usage/alert-records`` endpoints return an unexpected error message ("The API key provided is not valid") for both Start and Launch account types. 

I understand that the Start accounts do not have access to the rules engine, which may cause this error. But "The API key provided is not valid" is a bit misleading for my launch account (which has access to the rules engine, but no rules set) because it is the same error returned as when an *truly* invalid API key is passed. I believe the call should return either a scope-specific error message or an empty data structure to indicate that an account has no rules, rather than an error.

Consider a Launch account, which purchases 

### Date/time of issue

2/2/19 - 7:45pm EST

### API URL

https://cloud.iexapis.com/beta/account/usage/rules?token=
https://cloud.iexapis.com/beta/account/usage/rule-records?token=
https://cloud.iexapis.com/beta/account/usage/alert?token=
https://cloud.iexapis.com/beta/account/usage/alert-records?token=

### What you expected to happen

[]
OR
{}
OR
The requested resource is not available for this account

### What actually happened

"The API key provided is not valid."

### Other Information (sample code, links, etc.)

Requesting messages seems to work:

https://cloud.iexapis.com/beta/account/usage/messages?token=

**Comment by joshuablackburn-iex** [comment]
In each of these cases did you use the SK token?

**Comment by addisonlynch** [comment]
@joshuablackburn-iex yes...all calls used the SK token. I believe the token is accepted, since messages work (https://cloud.iexapis.com/beta/account/usage/messages?token=)

**Comment by joshuablackburn-iex** [comment]
Got it. Thanks. I'm able to repeat this issue, and we are hoping to get a fix out today.

**Comment by hygu98** [comment]
I think I am having a similar problem with this end point:  https://cloud.iexapis.com/v1/stock/market/batch?token='MY_PUBLIC_OR_PRIVATE_TOKEN_HERE'.  The message I get in the browser request is: The API key provided is not valid.
