### ISSUE TITLE
IEX Cloud: Pay as you go endpoint returns "not found"

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#638]
## Summary

Account pay as you go endpoint returns "Not found" for all requests

### Date/time of issue

2/2/2019 - 8pm EST

### API URL

https://cloud.iexapis.com/beta/account/payasyougo?allow=false&token=
https://cloud.iexapis.com/beta/account/payasyougo?allow=true&token=

### What actually happened

Not found

**Comment by joshuablackburn-iex** [comment]
An updated has been deployed.
