### ISSUE TITLE
Invalid data point returned by API for CMLS 1Y Chart on June 13, 2018

### ISSUE THREAD

**Issue by michaeldrennen** [iexg/IEX-API#639]
## Summary
Invalid data point returned by API.
CMLS 1Y Chart on June 13th, 2018 shows a changePercent of 45212.5 which is very incorrect.
Check your data provider.

## Details
{"date":"2018-06-13","open":14.25,"high":14.5,"low":14.25,"close":14.5,"volume":50000,"unadjustedVolume":50000,"change":14.468,"changePercent":45212.5,"vwap":14.375,"label":"Jun 13, 18","changeOverTime":206.1428571428571}

### Date/time of issue
Anytime. Call the following API URL at any time to view the incorrect data.

### API URL
https://api.iextrading.com/1.0/stock/CMLS/chart/1y

### What you expected to happen
Receive valid data.

### What actually happened
Received invalid data.

### Other Information (sample code, links, etc.)
There seem to be about a dozen missing days of data for CMLS in June. Might be related.

Also, you guys are awesome! https://i.imgur.com/SnpgTxq.gif

Is there a better place for me to report data issues? I want to be helpful but not annoying or noisy.
Thanks!

**Comment by joshuablackburn-iex** [comment]
@michaeldrennen Thanks for pointing this out. We are on it.

**Comment by evancarter-iex** [comment]
@michaeldrennen Is this still an issue in the IEXCloud data?

**Comment by evancarter-iex** [comment]
Closing due to lack of response. Please create a new issue if this is still a problem in https://iexcloud.io
