### ISSUE TITLE
IEX Cloud: Batch stock requests given bad symbols return incorrect error

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#640]
## Summary

When making a request to /stock/market/batch, if a single bad symbol is passed, "API Key is not valid" is returned

### Date/time of issue

2/4/19 - 1pm EST

### API URL

https://cloud.iexapis.com/beta/stock/market/batch?symbols=badsymbol&types=quote&token=sk_

### What you expected to happen

200: {}

This is the behavior of the legacy v1 developer API

### What actually happened

403: The API key provided is not valid.

### Other Information (sample code, links, etc.)

The behavior when multiple symbols are passed and one is invalid remains the same as before:

https://cloud.iexapis.com/beta/stock/market/batch?symbols=badsymbol,aapl&types=quote&token=sk_

Simply returns aapl only.

This also seems to only apply to batch requests. Requests for a single bad symbol (/stock/badsymbol/quote) return 404: Unknown symbol as before.

**Comment by joshuablackburn-iex** [comment]
With the new token auth layer it seems we've be too aggressive with error handling, and the wrong error code. We are working on this now.

**Comment by evancarter-iex** [comment]
We return unknown symbol now for one off requests and batches return the symbols that exist.
