### ISSUE TITLE
IEX Cloud High Low price errors

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#641]
## Summary

Quote and Book endpoints for IEX cloud

{"quote":{"symbol":"AAPL","open":167.48,"high":169.32,"low":165.93,"latestUpdate":1549314000627,"latestPrice":171.25,"latestVolume":31376269}}

error in High and low prices

iex api 1.0 is correct for high and low

**** another note there is a problem with open high low on Quote endpoints for the old api 1.0 and also on IEX cloud that happens on the first 15 mins of market open from 9:30 to 9:45 where the open high and low retain the previous days values until about the 9:45 update, This is really hard to approx manually taking large samples for the first 15 mins to get some reasonable open high and low values (and costly now for IEX cloud hits). It would be nice to get these values when called vs doing all the work on my end. But maybe there is another way I'm not considering.

### API URL

Quote and Book endpoints

**Comment by joshuablackburn-iex** [comment]
Thank you pointing out this issue. We have a cleanup job that appears to be failing which would cause previous day data to show. We are looking into this and will resolve as soon as possible.

**Comment by StockConsultant** [comment]
Hi Josh,

Just a heads up (sure you guys know this already) for the Quote endpoint, today's open is yesterdays open, high and low are null and the latestprice and volume are correct, this  a few mins after 9:30am open

[{"symbol":"AAPL","open":172.93,"high":null,"low":null,"latestUpdate":1549463510569,"latestPrice":175.19,"latestVolume":987448},

**Comment by StockConsultant** [comment]
An update at 10am

the low price continue to be yesterday's low price

[{"symbol":"AAPL","open":174.8,"high":175.33,"low":172.35,"latestUpdate":1549465157514,"latestPrice":173.55,"latestVolume":4279562},{"symbol":"AMD","open":23.63,"high":24.14,"low":22.98,"latestUpdate":1549465158102,"latestPrice":23.775,"latestVolume":21667599},

**Comment by evancarter-iex** [comment]
@StockConsultant we are actively working on this and hope to have it ironed out in the next couple of days

**Comment by StockConsultant** [comment]
Thanks!!!!

________________________________________

**Comment by evancarter-iex** [comment]
This is fixed.
