### ISSUE TITLE
IEX Cloud Previous endpoint not updating

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#642]
## Summary

Previous End point still showing  2/1 close data

cloud.iexapis.com/beta/stock/market/previous

{"AAL":{"date":"2019-02-01","open":35.77,"high":36.59,"low":35.77,"close":36.11,"volume":6612246},"AAAU":{"date":"2019-02-01","open":13.21,"high":13.21,"low":13.16,"close":13.17,"volume":18608},"AADR":{"date":"2019-02-01","open":44.34,"high":44.53,"low":44.34,"close":44.52,"volume":13226},"AAC":{"date":"2019-02-01","open":2.47,"high":2.47,"low":2.34,"close":2.44,"volume":95672},"A":{"date":"2019-02-01","open":76.16,"high":76.59,"low":75.62,"close":76.04,"volume":1343915},"AA":{"date":"2019-02-
....

old api working and gives data around 10pm to 11:45pm EST on same day, not sure if new cloud api going to behave the same (would be nice)?

api.iextrading.com/1.0/stock/market/previous 

{"AAME":{"date":"2019-02-04","open":2.8498,"high":2.8498,"low":2.8,"close":2.8,"volume":3116},"AABA":{"date":"2019-02-04","open":68.19,"high":68.55,"low":67.7481,"close":68.41,"volume":7195252},"AA":{"date":"2019-02-04","open":28.43,"high":29.19,"low":28.351,"close":29.09,"volume":2337192},"AAAU":{"date":"2019-02-04","open":13.12,"high":13.1399,"low":13.11,"close":13.12,"volume":21901},"AAL":{"date":"2019-02-04","open":36.16,"high":36.81,"low":36.12,"close":36.78,"volume":9089334},"AAN":{"date":"2019-02-04","open":50.07,"high":50.74,"low":49.73,"close":50.67,"volume":486305},"A":{"date":"2019-02-04","open":76.18,"high":76.23,"low":75.32,"close":76.03,"volume":2245893},

### Date/time of issue

7:15 am EST

### API URL

cloud.iexapis.com/beta/stock/market/previous ...

**Comment by joshuablackburn-iex** [comment]
This should be good to go. Our adjusted close prices aren't available until 4-5am ET. You can still get end of day close as early as 4:30pm ET with /stock/market/ohlc

**Comment by StockConsultant** [comment]
ok thanks, the docs for api 1.0 also said Previous endpoint was 4am but update was earlier at 11:30pm, I take it you will enforce the 4am for the new cloud api. I'll look at ohlc, thanks!
