### ISSUE TITLE
IEX Cloud OHLC no symbol names included

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#645]
## Summary

IEX Cloud OHLC no symbol names included

when you call 

cloud.iexapis.com/beta/stock/market/ohlc 
with a symbol list ie:

symbols=AAPL,AMD,AMRN,AIG,CRZO,ACHC,ARNA,HLF

data is returned but no symbol name for each data bucket, if you include a symbol (like ZZZZZ) which is not found then the data is just missing so keying off the symbol list provided to index down could be dangerous, there is no way to ensure that the data is for that symbol. Adding format=csv has empty object fields (open close and no symbol field)

[{"open":{"price":174.8,"time":1549463400637},"close":{"price":174.18,"time":1549400400246},"high":175.33,"low":172.35},{"open":{"price":23.63,"time":1549463400702},"close":{"price":23.31,"time":1549400400225},"high":24.14,"low":22.98},{"open":{"price":16.16,"time":1549463400965},"close":{"price":16.14,"time":1549400400339},"high":16.63,"low":15.86},{"open":{"price":43.65,"time":1549463410138},"close":{"price":43.66,"time":1549400409301},"high":43.85,"low":43.29},{"open":

open | close | high | low
-- | -- | -- | --
[object Object] | [object Object] | 175.33 | 172.35
[object Object] | [object Object] | 24.14 | 22.98

Calling cloud.iexapis.com/beta/stock/market/ohlc with no arguments (just token) gives the full list with symbol names included but doing so uses up excess weights (at 2x per symbol) for symbols I do not need.

Calling cloud.iexapis.com/beta/stock/market/ohlc with just format=csv (and token) returns symbol names but empty objects.

### Date/time of issue

2/6

### API URL

cloud.iexapis.com/beta/stock/market/ohlc

**Comment by evancarter-iex** [comment]
We are looking into this.

**Comment by joshuablackburn-iex** [comment]
This is an edge case we didn't account for. If you call /stock/market/ohlc we don't expect to see the symbols param. /market/ohlc is meant to retrieve all symbols in the market, which does include the symbol as a key.  If you want just a few symbols, the way would be

 /stock/market/batch?symbols=aapl,amd&types=ohlc

This will also return symbols as the key.

We will need to fix the case where /market/ohlc is called with symbols specified.

**Comment by evancarter-iex** [comment]
This is fixed. Let us know if you have any additional issues. Thanks
