### ISSUE TITLE
Getting 'Forbidden' when calling any valid endpoint

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#646]
## Summary
When calling the following endpoint (or any valid endpoint), I am consistently getting 'Forbidden'

https://cloud.iexapis.com/beta/stock/aapl/ohlc&token=my_published_token_here

### Date/time of issue
2019.02.06 15:48 (Eastern)

### API URL
https://cloud.iexapis.com/beta/stock/aapl/ohlc&token=my_published_token_here

### What you expected to happen
In this instance, I expected the OHLC data for aapl

### What actually happened
Forbidden

### Other Information (sample code, links, etc.)
Call was made from the URL field on a browser
I get the same results when calling the end-point from Postman

**Comment by joshuablackburn-iex** [comment]
You need to change your url from &token= to ?token=
