### ISSUE TITLE
How to get the news directly related to the company we are looking for?

### ISSUE THREAD

**Issue by kiranparab0** [iexg/IEX-API#647]
## Summary
News API returns news result, which are not relevant to the search in most cases.

### Date/time of issue
Anytime.

### API URL
https://api.iextrading.com/1.0/stock/aapl/news

### What you expected to happen
Get the most relevant news of the company 

### What actually happened
Returns random news also, which are not directly about the company or related to comapny. 

### Other Information (sample code, links, etc.)
Below is news link from one of the result item for AAPL
https://api.iextrading.com/1.0/stock/aapl/article/7391024919540528

When you go the news, you realize its neither about the company nor related to the company indirectly as well.

**Comment by joshuablackburn-iex** [comment]
The article you posted explicitly lists and links to Apple on page 3.
