### ISSUE TITLE
short ratio / short interest

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#649]
Will the key stats API call return short interest and short ratio? It went missing in V1, and I notice it still isn't in v2?

**Comment by joshuablackburn-iex** [comment]
Probably will not return in the near term due to contract and fee changes made by other exchanges. It is now cost prohibitive to provide this data.

**Comment by slydero** [comment]
This stinks. I subscribed to cloud/V2 because I was notified that this has been resolved in V2. Sounds like it's not happening at all.
