### ISSUE TITLE
Websocket connect to TOPS randomly disconnects with EOFException

### ISSUE THREAD

**Issue by rterp** [iexg/IEX-API#65]
Our TOPS websocket client has been working without issues for a couple of weeks, but over the last few days the connection to the websocket is getting dropped due to an EOFException.  This randomly occurs anywhere from 5 - 45 minutes after connecting to the TOPS websocket endpoint and subscribing to firehose data.  

Any idea what my be going on?  We are using the Java socket.io client library.

thanks,
-Rob

**Comment by evancarter-iex** [comment]
@rterp Do you have a debug log or any logging I could look at?

**Comment by evancarter-iex** [comment]
Closing. Reopen when/if there is more data.

**Comment by rterp** [comment]
Will do, we are seeing the same issue with subscribing to the DEEP endpoint as well.  Unfortunately the exception is being swallowed by the Java Socket.IO library, so we'll be downloading the source for it and adding debug statements to get a better idea of what is going on.

**Comment by rterp** [comment]
Below is the EOF exception that we are seeing every few minutes from our client.  
Attached is a simple socket.io Java client.  Github wouldn't allow me to upload a .jar file, so I had to change the extension to .zip 

The app is a simple socket.io client that subscribes to deep for all tickers in the attached ticker file.  In order to run the app change the extension back to .jar and issue the command

java -jar SocketIOClient-0.0.1.jar Symbols2.txt
(make sure symbols2.txt is in the same directory as the .jar file

We have also tested with a Node.js client and are seeing disconnects every few minutes as well.

[SocketIOClient-0.0.1.zip](https://github.com/iexg/IEX-API/files/1477007/SocketIOClient-0.0.1.zip)




[Symbols2.txt](https://github.com/iexg/IEX-API/files/1477003/Symbols2.txt)



`java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:60)
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:1         13)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.         java:97)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201         )
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.         java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor         .java:617)
        at java.lang.Thread.run(Thread.java:745)
error: io.socket.engineio.client.EngineIOException: websocket error
`

**Comment by evancarter-iex** [comment]
Im looking into this.

**Comment by evancarter-iex** [comment]
@rterp are you still seeing these problems. We rolled out something on friday, and I want to see if it fixed the issue.

**Comment by rterp** [comment]
I’m out of town the next couple of weeks, but I relayed the message to our devs and they should be testing today.

**Comment by tvroley** [comment]
Unfortunately we're still having similar disconnect problems since the update on Friday.

**Comment by rterp** [comment]
We are seeing the same issue with the with the DEEP endpoint as well.

**Comment by evancarter-iex** [comment]
@rterp we are still looking into this. Its on our radar to try and find a solution

**Comment by rterp** [comment]
Hi there, any update on this?

**Comment by evancarter-iex** [comment]
We are still looking into this. It appears to be something with the underlying libraries, which makes a solution difficult. We will update as we know more.

**Comment by evancarter-iex** [comment]
@rterp We did some work on the underlying libraries and deployed something this afternoon. Can you let us know if you are still seeing this?

**Comment by rterp** [comment]
Ok, should be able to get a test going by the end of the week.

Thanks,

-Rob

**Comment by rterp** [comment]
@evancarter-iex  we have been disconnected more than a dozen times this morning since the market opened on both the TOPS and DEEP endpoints.

**Comment by evancarter-iex** [comment]
@rterp I see what you are seeing. Was fine yesterday, now investigating and hopefully will have a fix by this afternoon

**Comment by evancarter-iex** [comment]
@rterp can you share your connection code from your app with us?

**Comment by rterp** [comment]
Attached is our sample node app we have been using to test TOPS and DEEP.  It is getting the list of tickers from one of our local web services.

**Comment by rterp** [comment]
Uploading the files again.  These are actually javascript files being run within node, I had to save a .txt to upload them here.

[socketTestDEEP.txt](https://github.com/iexg/IEX-API/files/1665886/socketTestDEEP.txt)
[socketTestTOPS4.txt](https://github.com/iexg/IEX-API/files/1665887/socketTestTOPS4.txt)

**Comment by evancarter-iex** [comment]
Hmm okay. I deployed something tonight that hopefully will help. I spent a good hour streaming firehose this afternoon and didnt have any problems. Let me what you see

**Comment by rterp** [comment]
Ok, thanks.  We’ll try running our test apps again in the morning and let you know.

**Comment by rterp** [comment]
We've seen about half a dozen disconnects today for both TOPS and DEEP.

**Comment by evancarter-iex** [comment]
@rterp Got a bug fix for some of them inbound. Still tracking down a weird JSON/socketio issue

**Comment by evancarter-iex** [comment]
After a lot of debugging, I have unfortunately found that there are significant issues with socket.io post 1.0 release which lead to these disconnects.

https://github.com/socketio/socket.io/issues/777
https://github.com/socketio/socket.io/issues/3025

Among others. Until they fix these upstream issues there isnt much we can do.

**Comment by rterp** [comment]
We didn’t have any disconnects today on either the TOPS or the DEEP endpoints, which is a first.

**Comment by evancarter-iex** [comment]
Interesting. Let me know how it goes but in my testing I was still seeing disconnects randomly.

**Comment by evancarter-iex** [comment]
@rterp Would you be interested in helping beta test our new SSE endpoint? Send us an email at ux@iextrading.com if you are and Ill hook you up.

**Comment by rterp** [comment]
@evancarter-iex Yea, we'd be interested if we could get DEEP data via the endpoint.  I'll send an email to the address you referenced.

**Comment by rterp** [comment]
Just wanted to check in on this to see if you guys are looking at moving DEEP to use SSEs or other possible options?

**Comment by evancarter-iex** [comment]
@rtep we still are, we are just backlogged currently on other things

**Comment by joshuablackburn-iex** [comment]
This is fixed with IEX Cloud. IEX Cloud offers SSE streaming for a number of endpoints including TOPS, LAST, DEEP, stock/quote and others on the way.
