### ISSUE TITLE
Historical Market Cap

### ISSUE THREAD

**Issue by moesalih** [iexg/IEX-API#650]
Is there a way to get historical market cap values?

If not, it would be great if this was added. Perhaps by adding it to the Historical Prices endpoint.

**Comment by snowde** [comment]
This doesn't make sense, there is no historical market cap values?

**Comment by McQgit** [comment]
You could lookup historical balance-sheet for its commonStock value.  Then, lookup the price for the filing date to derive the Market Cap on that date.  I do that using other vendor sources but it should work for IEX too.

If you want the Market Cap for other dates, you just need some code to carry forward the commonStock value from prior filing.

Given its an old request, just wanted to provide an alternative possibility that works now.
