### ISSUE TITLE
IEX cloud Batch endpoint, CSV format

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#651]
## Summary

IEX cloud Batch endpoint CSV

https://cloud.iexapis.com/beta/stock/market/batch?symbols=aapl,amd&types=quote&filter=... &format=csv

adding format=csv returns no data 

is csv format supported for /market/batch?

![empty](https://user-images.githubusercontent.com/42130156/52481065-7c6cfd00-2b7b-11e9-9ce2-d7a1bc29fd31.png)

### Date/time of issue

2/8

### API URL

https://cloud.iexapis.com/beta/stock/market/batch

**Comment by evancarter-iex** [comment]
This is resolved.
