### ISSUE TITLE
IEX Cloud Quote, market/batch quote endpoints

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#652]
## Summary

@joshuablackburn-iex

Ok latest update to the quote endpoint (and batch/market quote) fills in nulls for high and low until about 9:45 when the high and low values are set NOTE the high value that is set is the previous high (see data below). The open value remains previous days open until about 9:45. The quote endpoint and market/batch quote produce the same results

Is this normal behavior (other than the previous high set initially for the high value) that after 15 mins the open (previous days open), high (null) and low (null) values will be populated?

at 9:35am

![iex935](https://user-images.githubusercontent.com/42130156/52486338-db853e80-2b88-11e9-87d0-6640ac78f10d.png)

approx 9:47am

![iex950](https://user-images.githubusercontent.com/42130156/52486353-e4761000-2b88-11e9-981e-f95d3aa8ab82.png)

cloud.iexapis.com/beta/stock/market/quote?filter=symbol,open,high,low,latestUpdate,latestPrice,latestVolume&symbols=AAPL,AMD,AMRN,AMRN,AIG,CRZO,ACHC,ARNA,HLF

**Comment by mfhawley** [comment]
Im getting similar issues with the historical data like this for example:
https://cloud.iexapis.com/beta/stock/aapl/chart/date/20190207

A bunch of nulls for the marketClose
![image](https://user-images.githubusercontent.com/14339122/52513750-b06b1100-2bc1-11e9-8b4e-6d1f4b517496.png)

**Comment by StockConsultant** [comment]
It seems like the open high low data must be taken from delayed and not latest price updates (see below on CRUS the latest price is 39.32 and high is still 39.09) and follows from above that the open high low seems to not update until about 9:45am (with the initial high error of the previous high).

{"symbol":"CRUS","open":38.58,"high":39.09,"low":38.43,"latestUpdate":1550156437134,"latestPrice":39.32,"latestVolume":34844},

it would nice to have the open high low be populated from the latest prices. It takes extra work to fill in the open high low from latestprices on our end and would now cost more since a large amount of sampling is needed.

**Comment by StockConsultant** [comment]
@joshuablackburn-iex @joshuablackburn-iex iex 

any fix for this yet?

on today's results the values for high and low are null until 9:45pm EST and open contains yesterdays open.

at 9:45am EST the high and low values are filled in with YESTERDAYs High and Low and Open remains at yesterdays open.

9:45am (same for market batch endpoint)

https://cloud.iexapis.com/beta/stock/market/quote?filter=symbol,open,high,low,latestUpdate,latestPrice,latestVolume&token=...&symbols=AAPL,AMD,

[{"symbol":"AAPL","open":173.23,"high":175,"low":172.73,"latestUpdate":1551365134159,"latestPrice":174.53,"latestVolume":1770052},{"symbol":"AMD","open":24.11,"high":24.23,"low":23.18,"latestUpdate":1551365135230,"latestPrice":23.345,"latestVolume":5880149},

AAPL and AMD open high low are yesterdays data.

Later in the day as previously shown the High and low values seem to be done on delayed data? Is there a IEX latest high and low and open that I can use that does not initialize to yesterdays data after the market opens and is up to date (IEX realtime)

I am still using V1 and hope this will be fixed before the V1 eol as I still have no suitable working V2 to use.

**Comment by evancarter-iex** [comment]
We are looking into this.

**Comment by evancarter-iex** [comment]
@StockConsultant 
We have fixed the high low issues. You are correct that high/low is based on delayed data and will be null before 9:45am ET (we have updated the documentation that will go out soon, with clarification on these points).

In addition, open/close is 15 minutes delayed. So wont be updated till 9:45am ET.

**Comment by StockConsultant** [comment]
@evancarter-iex @joshuablackburn-iex 

there is still one issue I noticed today, the open is null prior to market open pre 9:30am est (as is high and low both null) but once the market opens the open price is set to yesterdays (Fridays) open (from null) while the high and low remain null until the 9:45 point.

for quote and batch endpoints (9:36pm)

[{"symbol":"AAPL","open":170.32,"high":null,"low":null,"latestUpdate":1552311318350,"latestPrice":176.43,"latestVolume":1958244},{"symbol":"AMD","open":21.35,"high":null,"low":null,"latestUpdate":1552311314170,"latestPrice":22.075,"latestVolume":2829225},

it would be great to have an IEX open high low, but for now I can recreate this

**Comment by evancarter-iex** [comment]
@StockConsultant we are looking at it, saw the same thing

**Comment by evancarter-iex** [comment]
@StockConsultant The open/ being yesterdays data should be fixed now. Im going to close this bug. If you see anything else please open additional issues. Thanks
