### ISSUE TITLE
Retrieving Historic Closing Prices

### ISSUE THREAD

**Issue by gs124** [iexg/IEX-API#653]
I'm having what is probably a fairly basic difficulty, but would be grateful for an assist.

I'm looking to retrieve the historic closing price for a stock for a particular date (e.g., the closing price for SPY on 31 January 2019).

I understand that this can be done through the chart function, but that seems to return a large volume of additional data.

https://api.iextrading.com/1.0/stock/aapl/chart/date/20190131 returns minute-by-minute values with a different "close" value for each minute (unclear to me what that means).

https://api.iextrading.com/1.0/stock/aapl/chart/1m returns daily values for close and other fields for every day over the last month.

I understand how to use the ?filter parameter to return, e.g, only close values, but not how to narrow the data returned further to bring back only a single value.

Is there a parameter to narrow the chart to return only the daily close value on and only on a particular day?

Many thanks.

**Comment by evancarter-iex** [comment]
This is fixed in https://iexcloud.io
