### ISSUE TITLE
Iex Cloud - Dividend not available for ETF & BOND

### ISSUE THREAD

**Issue by rajpatelukyahoo** [iexg/IEX-API#654]
## Summary
Dividend data not available.

ETF checked - SPY, QQQ
Bond Stock: DHY

## Details
returns empty array
[]

### API URL
https://cloud.iexapis.com/beta/stock/DATA/dividends/1y?token=pk_????
**returns []**
https://cloud.iexapis.com/beta/stock/SPY/dividends/next?token=pk_abcb
**returns "Not found"**

**Comment by Username-r-all-taken** [comment]
Do you plan to fix this? If so, any ETA? thanks.

**Comment by slipcon** [comment]
Probably related, but /beta/stock/<symbol>/stats seems to have null for the dividend related fields for both ETFs and mutual funds - e.g.:

https://cloud.iexapis.com/beta/stock/FNIDX/stats?token=pk_xxxxxxxxxxxx returns:


{
     ....
    "companyName": "Fidelity International Sustainability Index Fund",
     ....
    **"dividendYield": null,**
      ....
    **"ttmDividendRate": null,**
     ....
}

**Comment by gthom9** [comment]
Also having an issue receiving dividends for ETFs. I have tested ITOT, IXUS, IMTB, and ILTB. All return the empty array [].

**Comment by mariusmoo** [comment]
I'm also seeing this for about 100 ETFs that I tried.

Examples:
https://cloud.iexapis.com/beta/stock/VYM/dividends/5y?token=XXXX returns empty
Old API: https://api.iextrading.com/1.0/stock/VYM/dividends/5y returns data up to 12/2017 only; but VYM has issued dividends since then.

If I replace the ticker symbol with AAPL, everything is fine.

**Comment by evancarter-iex** [comment]
This is fixed for most dividends. We are still looking into some stragglers like VYM and some Fidelity ETFs & Mutual Funds. If you see anymore please open a ticket for the funds in question.

**Comment by rperezretan** [comment]
It is also happening with FTF :)

**Comment by osbarge** [comment]
This is happening again for SPY
