### ISSUE TITLE
(Beta) Returning day-old close data this morning

### ISSUE THREAD

**Issue by wbhern** [iexg/IEX-API#656]
## Summary
Retrieving stock prices this morning via Batch, close, latestClose and change are reporting data for February 7, not February 8 (although latestTime is returning February 8).

### API URL
https://cloud.iexapis.com/beta/stock/market/batch?symbols=AMZN,FB&types=quote&token=XXXXXX

### What you expected to happen
February 8 data

### What actually happened
February 7 close data returned - AMZN shows a close and latestPrice of 1614.37, which is the Feb 7 close. (Feb 8 close was 1588.22.) FB shows a close of 166.38, which is the Feb 7 close. (Feb 8 close was 167.33.) All supporting/related data is also for the previous day.

{"AMZN":{"quote":{"symbol":"AMZN","companyName":"Amazon.com, Inc.","calculationPrice":"close","open":1585.62,"openTime":1549636200134,"close":1614.37,"closeTime":1549659600461,"high":null,"low":null,"latestPrice":1614.37,"latestSource":"Close","latestTime":"February 8, 2019","latestUpdate":1549659600461,"latestVolume":0,"iexRealtimePrice":null,"iexRealtimeSize":null,"iexLastUpdated":null,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":1587.7,"extendedChange":-26.67,"extendedChangePercent":-0.01652,"extendedPriceTime":1549760397090,"previousClose":1640.26,"change":-25.89,"changePercent":-0.01578,"iexMarketPercent":null,"iexVolume":null,"avgTotalVolume":6646260,"iexBidPrice":null,"iexBidSize":null,"iexAskPrice":null,"iexAskSize":null,"marketCap":792983387110,"week52High":2050.5,"week52Low":1307,"ytdChange":0.03310475957196583}},"FB":{"quote":{"symbol":"FB","companyName":"Facebook, Inc. Class A","calculationPrice":"close","open":164.47,"openTime":1549636200824,"close":166.38,"closeTime":1549659600460,"high":null,"low":null,"latestPrice":166.38,"latestSource":"Close","latestTime":"February 8, 2019","latestUpdate":1549659600460,"latestVolume":0,"iexRealtimePrice":null,"iexRealtimeSize":null,"iexLastUpdated":null,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":167.38,"extendedChange":1,"extendedChangePercent":0.00601,"extendedPriceTime":1549760230601,"previousClose":170.49,"change":-4.11,"changePercent":-0.02411,"iexMarketPercent":null,"iexVolume":null,"avgTotalVolume":24997965,"iexBidPrice":null,"iexBidSize":null,"iexAskPrice":null,"iexAskSize":null,"marketCap":474936701400,"week52High":218.62,"week52Low":123.02,"ytdChange":0.2021576886792452}}}

**Comment by evancarter-iex** [comment]
Looking into this.

**Comment by evancarter-iex** [comment]
Should be updating now. Sorry about the delay, we were working to fix the underlying issue.

**Comment by wbhern** [comment]
Confirmed. It's providing latest/greatest now. Thanks.
