### ISSUE TITLE
issue with symbol/chart/date/...

### ISSUE THREAD

**Issue by cfrick16** [iexg/IEX-API#659]
## Summary
The chart API call does not work correctly when searching for a specific date.

### Date/time of issue
2/10/19 12:03 am

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/date/20160129

### What you expected to happen
Return the stock information of Apple on January 29, 2016

### What actually happened
Returned an empty list

**Comment by joshuablackburn-iex** [comment]
minute bar data is only available for the last 30 days.
