### ISSUE TITLE
How do I receive data in the csv file

### ISSUE THREAD

**Issue by myvaluealerts** [iexg/IEX-API#66]
how do I receive the following data in csv format.
By using the "filter" I restricted an enourmous amount of data to about 25 fields.  
The "&format=csv" opens a csv file but the data does not write to the file.

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,tsla&types=quote,earnings,stats
&filter=symbol,latestPrice,latestVolume,avgTotalVolume,float,sharesOutstanding,shortRatio,EPSttm,companyName,dividendRate,dividendYield,exDividendDate,exDividendDate,week52High,priceToBook,marketCap&format=csv

**Comment by rottla** [comment]
I would also like a simple working  example to download to .csv

**Comment by bitfool** [comment]
Reading the API docs, I only see "format" as a passable parameter in the /tops call and a few other IEX calls, but not in /stock.  Hopefully ?format=csv parameter will be added soon there as well.  Meanwhile, a working example in /tops is simply: 
https://api.iextrading.com/1.0/tops?format=csv&symbols=aapl,xiv,ziv,sbux,amzn

**Comment by joshuablackburn-iex** [comment]
We are looking to add this soon.

**Comment by bitfool** [comment]
Meanwhile, it's usually pretty simple to take JSON input and output CSV for yourself in Javascript or PHP or whatever code you use, if you must use CSV for some reason.  I usually go the other direction myself (convert CSV to JSON for internal coding use), but to each one's own.

**Comment by rottla** [comment]
Thanks, I have a charting program that takes OHLC data in CSV. Hence, looking for something simple. Send a bunch of symbols and get a OHLC csv back.

**Comment by BullMarket** [comment]
Well you can actually get the OHLC data as CSV from here https://iextrading.com/apps/stocks/#/AAPL under the Chart there is "Download CSV Data" Link  https://api.iextrading.com/1.0/stock/AAPL/chart/5y?format=csv   which you can use to get different time frames.

But don't bother using this. It's riddled with inconsistency as I've found out. For some symbols there are no columns https://iextrading.com/apps/stocks/#/ADXSW (VWAP column is missing here), I'd hope the column should be there even if data is missing. For some other symbols you get a CSV file but it's empty without any headers.

**Comment by joshuablackburn-iex** [comment]
@BullMarket Sorry to hear about the inconsistencies in the data.  We strive for the most complete and accurate data set, so we will look into a fix for this.

**Comment by myvaluealerts** [comment]
this is working for me.  it is php code.  you'll need to adjust it for your VBA code in excel.  I can't get the filter to work properly so I'm receiving a lot of data I don't really want. 

What you need to know can be found here:  https://iextrading.com/developer/docs/#company

curl_setopt($ch, CURLOPT_URL, 'https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,tsla,ge&types=quote,earnings,stats
&filter=symbol,latestPrice,latestVolume,avgTotalVolume,float,float,float,float,float,float,float,float,sharesOutstanding,shortRatio,ttmEPS,companyName,dividendRate,dividendYield,exDividendDate,exDividendDate,week52High,priceToBook,marketCap');

**Comment by BullMarket** [comment]
@joshuablackburn-iex  Thanks so much. Greatly appreciate the level of commitment for accurate data.

**Comment by twoinvesting** [comment]
@barrett77 I found a good solution for Google Sheets, possibly even Excel but it might take some tweaking. It requires grabbing some JavaScript that someone smarter than me wrote called IMPORTJSON.

It is then as easy as `=IMPORTJSON("https://api.iextrading.com/1.0/stock/AAPL/stats?filter=dividendRate","dividendRate")` 

This would then return 2.52 into that cell.

More details are here: [http://www.twoinvesting.com/2017/11/replacing-yahoo-finance-with-the-iex-api-in-google-sheets/](url) (It’s my site, but I’m not selling anything)

**Comment by joshuablackburn-iex** [comment]
@twoinvesting We've just released an enhancement to the API that may help out with this.  We just need to update our docs, but this improvement is available for stock/quote and stock/stats

If you want a specific field, you can now call 

https://api.iextrading.com/1.0/stock/aapl/stats/dividendRate
or
https://api.iextrading.com/1.0/stock/aapl/quote/latestPrice

As long as you pass the name of the field, it'll return just the value.  This should be much more helpful in Excel.

**Comment by twoinvesting** [comment]
@joshuablackburn-iex Awesome. You guys are the best!

**Comment by barrett77** [comment]
Awesome this looks great. If its possible to pull https://api.iextrading.com/1.0/stock/aapl/stats/dividendRate this into a csv file then I could simply insert this code into my old yahoo finance code and it should work! Are you still planning on making the csv available? 

@twoinvesting 
I'm working on that code in google sheets which i have my excel sheet connected to currently. Before I was using importhtml from nasdaq to get the dividend data however, sometimes the data would come back as #REF! and sometimes it would work. It isn't a great solution, but it was working well enough. 

Your solution will most likely work for me though as long as I can pull back the correct data from the IEX-API. I will work on trying to get this directly into excel instead of having to go through google sheets and then querying the published url. 


Thanks for all your help!

**Comment by joshuablackburn-iex** [comment]
CSV format should work for quote, chart, earnings, financials, dividends, splits, effective-spread, volume-by-venue, company, stats, and news

**Comment by barrett77** [comment]
@joshuablackburn-iex Does this work for https://api.iextrading.com/1.0/stock/aapl/stats/dividendRate as well?

**Comment by joshuablackburn-iex** [comment]
That URL will return a single number.  The format of that url is meant to define a single data point you'd like to return, and is not structured for CSV.  If you want a CSV of stats, you'd use https://api.iextrading.com/1.0/stock/aapl/stats?format=csv

**Comment by barrett77** [comment]
Would anyone be able to help me parse the data from the CSV file into Excel using VBA?
I'd like to pass the symbol of the stock into the URL and then pull out the price and dividend data. 

Either that or help with converting some javascript to vba.

**Comment by guanm326** [comment]
Is there a way to convert the pcap files to CSV? Or other formats like Jason where theres tags for bid/ask, etc fields?  If not, is there a way to historical top of book data and trades data in csv format?
