### ISSUE TITLE
Concern about the abuse of Publishable token

### ISSUE THREAD

**Issue by shoujs** [iexg/IEX-API#661]
## Summary
If I put the publishable token to an iOS app and make requests, people can intercept the request and extract the token.  I am afraid in this case, people can abuse the api request with the token.

In the console, the secret token can be refreshed but not the publishable token. If it is abused, how can I stop it?

And I appreciate the advice from the community what the best practice is to deal with the token stuff for mobile app.

**Comment by joshuablackburn-iex** [comment]
We are rolling out token management updates to the console on Monday. It allows everyone to assign domain and IP restrictions to a token, create additional publishable tokens, and delete existing tokens.

**Comment by shoujs** [comment]
Thank you for the quick response. The token management is a solution.
Besides that, May I suggest using hashed token as query parameter instead of plain token? Like hash(pk_token + timestamp + salt). and then IEXCloud verify the request against the hashed token generated from app. The hashed token is dynamic and we can avoid expose pk_token to users.

**Comment by joshuablackburn-iex** [comment]
@shoujs I like that. We will take a look at adding that option as well.

**Comment by joshuablackburn-iex** [comment]
We've updated the console to include managing publishable tokens and domain/IP restrictions.

**Comment by shoujs** [comment]
Thank you very much. Let me keep the issue open for a moment.

**Comment by GeekStocks** [comment]
@shoujs  I agree with you and opened [725](https://github.com/iexg/IEX-API/issues/725) because this issue should not be closed. This is a very real security flaw.
