### ISSUE TITLE
IEX Cloud - Missing 5Y Chart Data

### ISSUE THREAD

**Issue by sgreenlay** [iexg/IEX-API#664]
## Summary

IEX Cloud is missing chart data compared to 1.0.

### Date/time of issue

2/11/19

### API URL

https://cloud.iexapis.com/beta/stock/AFL/chart/5y?token=TOKEN
https://api.iextrading.com/1.0/stock/AFL/chart/5y

### What you expected to happen

I was expecting IEX Cloud to match the quantity of data provided by IEX v1.0 but found that a number of stocks are completely missing chart data.

**Comment by joshuablackburn-iex** [comment]
I cannot reproduce this issue. I see data back to 2014 when I specify 5y. Can you please verify?

**Comment by sgreenlay** [comment]
Looks like it works now. Thanks!
