### ISSUE TITLE
Mutual funds endpoint not available

### ISSUE THREAD

**Issue by vhavasi** [iexg/IEX-API#666]
## Summary

https://cloud.iexapis.com/beta/ref-data/mutual-fund/symbols?token={public token} returns 'Not Found'

## Details

Mutual funds endpoint for available symbols not found.

### Date/time of issue
12-02-2019

### API URL

https://cloud.iexapis.com/beta/ref-data/mutual-fund/symbols?token={public token}

### What you expected to happen

Pull a list of available mutual fund symbols.

### What actually happened

'Not Found' error message

### Other Information (sample code, links, etc.)

https://cloud.iexapis.com/beta/ref-data/mutual-fund/symbols?token={public token}

**Comment by joshuablackburn-iex** [comment]
I cannot reproduce this issue.  Can you try this again?

**Comment by vhavasi** [comment]
Still able to reproduce on my side. Take a look on attached screenshots. I included my public token in case it’s token related. OTC ref data call is working correctly, so I guess is not something network related on my side.

**Comment by lgellert** [comment]
I'm currently getting a _Not Found_ message for the Mutual Fund Symbol listing endpoint:

https://cloud.iexapis.com/beta/ref-data/mutual-fund/symbols?token={my_token}

**Comment by evancarter-iex** [comment]
Looking into this. Theres a typo on the documentation page (which I am fixing as I post this). It should be:

https://cloud.iexapis.com/beta/ref-data/mutual-funds/symbols?&token=XXXX

Note the **s** on mutual funds

**Comment by vhavasi** [comment]
Thank you! It’s working now. Should have been thought! 😊 Thank you for the professional support! Happy to point out a bug in your documentation. 😉

 

Best regards & keep up the ninja style,

Viktor
