### ISSUE TITLE
Cloud beta not returning current mutual fund data

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#667]
## Summary
The beta cloud API is not returning current data for mutual funds

## Details
API is returning inconsistent data for mutual funds (see example)

### Date/time of issue
current (last tested 2019.02.12 1138E)

### API URL
https://cloud.iexapis.com/beta/stock/market/batch?types=quote,dividends&symbols=aceix, usaix, vdigx&range=1y&token=MY_KEY

### What you expected to happen
Mutual fund prices will be as of close of
[sample_mutuals.txt](https://github.com/iexg/IEX-API/files/2856714/sample_mutuals.txt)

 previous day

### What actually happened
Prices are inconsistent (ACEIX  is for 2/11, USAIX and VDIGX are for 2/7)

**Comment by wbhern** [comment]
If I could tag on to this with a question: on a daily basis, when should I expect to see todays closing data for mutual funds through this endpoint? (6pm ET? 7pm?) Thanks.

**Comment by evancarter-iex** [comment]
@wbhern Just to give you an update, we are testing EOD stuff in the next couple of days in our staging environment. In the beginning it will probably be available at 9pm ET but we are still working on pushing it up.

**Comment by wbhern** [comment]
Super -- appreciate both the effort and the update. Very much looking forward to trying it out live.

**Comment by evancarter-iex** [comment]
This is fixed. We are seeing mutual fund data around 8:30-9:30pm every night. Not sure we can get it sooner than than 8:30pm though.

Im going to close this, since this bug is resolved.

**Comment by wbhern** [comment]
@evancarter-iex  -- turned on the mutual funds retrieval in my code last night, and sure enough, they showed up in that window. Obviously would love continuing to see a push towards 6:00pm, but really happy to have a committed source in a workable timeframe. Thanks for the work on this.

**Comment by evancarter-iex** [comment]
@wbhern We can look at it but we are doing official closes across a lot of different equities hence the 8:30pm ET but Ill see if we could split out mutual funds in the future to do it earlier
