### ISSUE TITLE
1 yr dividend for mutual funds?

### ISSUE THREAD

**Issue by curtcotner** [iexg/IEX-API#668]
## Summary
First of all, thanks very much for adding mutual fund support.  It greatly improves the capabilities of your API.
 
In my usage of the IEX-API, I want to show the trailing annual dividend per share for each stock.  I do this by parsing through and totaling up the quarterly payments returned by https://cloud.iexapis.com/beta/stock/IBM/dividends/1y?token=.

This currently returns and empty string for mutual funds like SCHK.  I know most mutual funds don't have quarterly dividends, but would it be possible to return the last 12 monthly distributions instead?  That would allow me to treat stocks and mutual funds similarly in my spread sheet, with only difference being whether my VB code is totaling 4 dividend payments or 12 distribution payments.

**Comment by rayshan** [comment]
Reference: Yahoo Finance shows dividends: https://finance.yahoo.com/quote/FFFHX/history?period1=1149231600&period2=1552374000&interval=div%7Csplit&filter=div&frequency=1d

Which seems to be a combination of dividend distribution and capital gains distribution: https://fundresearch.fidelity.com/mutual-funds/fees-and-prices/315792416

**Comment by evancarter-iex** [comment]
This is now fixed, for most mutual funds and ETFs. There are still some outstanding like the Fidelity funds. If you could open a new ticket for the Fidelity funds that would be great. Thanks
