### ISSUE TITLE
Can I make the following assumption on isEnabled from IEX ref data API

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#67]
Regarding

https://iextrading.com/developer/docs/#iex-ref-data

    isEnabled | will be true if the symbol is enabled for trading on IEX.

I know https://iextrading.com/developer/docs/#quote will only return delayed price, when a particular symbol's `isEnabled` is false.

Take `AIEQ` for an example.

I also monitor those symbols with `isEnabled` false, are having such behavior. They will not return meaningful result on APIs

https://api.iextrading.com/1.0/stock/AIEQ/stats
https://api.iextrading.com/1.0/stock/AIEQ/peers
https://api.iextrading.com/1.0/stock/AIEQ/financials
https://api.iextrading.com/1.0/stock/AIEQ/earnings
https://api.iextrading.com/1.0/stock/AIEQ/dividends/5y

Hence, can I make an assumption that, all symbols with `isEnabled` false, API stats, peers, financials, earnings and dividends will not work for them?

**Comment by joshuablackburn-iex** [comment]
isEnabled is to indicate when IEX is not trading a symbol.  It may be the same for other exchanges, so you may still get information when requesting a quote.  In cases where we are not trading but other exchanges are, we will return delayed quotes.  There shouldn't be a direct correlation between isEnabled false and a lack of data from the stock endpoint.  It may just be the symbol is very thinly traded.

**Comment by yccheok** [comment]
Hi Joshua,

Thanks for quick reply.

Now I understand the purpose for `isEnabled`. Then, I will merely use the flag `isEnabled`, to decide whether I should apply websocket real-time stock streaming, for a particular stock.
