### ISSUE TITLE
Batch Requests - Have a lot of issues

### ISSUE THREAD

**Issue by u382514** [iexg/IEX-API#670]
## Summary
Batch requests are returning unexpected results: 

## Details
<https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=chart,earnings,financials,dividends,news&range=5y>

The above will send back the details but FB's charts will be empty. 

Making a slight change to the URL (moving chart to the end) like below: 

<https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=earnings,financials,dividends,news,chart&range=5y>

will return the dividend information in the charts AND FB chart will still be empty (seems like a dividends/chart reference issue?) 

### Date/time of issue

02/12/2019 6:00PM cst

### API URL

see above

### What you expected to happen

All of the data is passed back correctly, regardless of the order of the types/symbols

### What actually happened

It did not.

### Other Information (sample code, links, etc.)
Attached are two JSON results from the URL's mentioned above. 

[examples.zip](https://github.com/iexg/IEX-API/files/2858333/examples.zip)

**Comment by evancarter-iex** [comment]
Is this occurring on IEXCloud as well? Or just the old API?
