### ISSUE TITLE
IEX cloud : credit consumption speed makes free and launch plans useless

### ISSUE THREAD

**Issue by elisag1990** [iexg/IEX-API#671]
Sorry to say it guys because I respect the work you have been doing here but the speed at which api calls consume credit (i.e. your so called "messages") is way to high, making any of the plans. apart the premium. useless.

How can it be that a single call to the following consumes 300 messages????

https://cloud.iexapis.com/beta/stock/market/batch?symbols=aapl,fb&types=quote,news,chart&range=1m&last=5&token=TOKEN

This call only retrieved quotes, news and 1 month chart for 2 stocks......if I were to make the same call for all 7000+ symbols I would be consuming over 1 million of your message credits. 

If you are trying to scuttle this all thing you are perfectly on the right track.

**Comment by shoujs** [comment]
Wait for them rolling out a sandbox environment if you are just complaining too much messages consumed while in the development phase. For production usage, I might agree with you.

**Comment by elisag1990** [comment]
I'm sorry but I really don't see why in production prices should get lower. In fact I could bet on seeing them rise even more.

**Comment by joshuablackburn-iex** [comment]
The addition of a sandbox environment will help alleviate message use in development. Our data weighting follows a central pricing philosophy to assign fair weights based on frequency and the cost of the data. This data is not cheap to source. We have set very aggressive prices to make professional level data accessible, where it would otherwise cost thousands per month. We do evaluate our weighting to make adjustments as necessary, and we have more functionality on the way to help make using the API more efficient.

**Comment by joshuablackburn-iex** [comment]
@elisag1990  Also, please see the historical prices documentation for parameters you can use to lower the cost of each call. If you are just charting you may not need the full adjusted and unadjusted data set and could possibly use chartCloseOnly.

**Comment by elisag1990** [comment]
@joshuablackburn I know what you get charged for market data elsewhere but we all should try to be more honest, where you pay thousands of dollars you also have reliable data and here data reliability is long to come. Also let's be honest the free and launch plans are of no use. Any minimal use of the api would blow away the credit not in a month but in a day or so. This said what is it that you are trying to do here? If it is democratizing markets you can't bring me examples of what others do because otherwise to me you are just another company trying to make money.

**Comment by wbhern** [comment]
@elisag1990 -- speak for yourself. Those of us with more modest needs I believe will find the free and/or launch plans very useful. I for one am quite content with what I can capture under the usage limits, which is the only reason I'm weighing in on your rant. Whether you're right about the cost/benefit in your use case or not, I honestly don't care, but to state that the lower-tiered pricing schemes are useless is both inaccurate and unhelpful.

I can understand frustration with the transition and there may very well be areas where the weighting is way off, but reducing the hyperbole and focusing on the issues would be far more productive.

**Comment by joshuablackburn-iex** [comment]
Thank you for understanding that this is a beta, and we are in the very early stages. User feedback is helpful for us to know what is working and what is not. We are also developers, and using IEX Cloud to power our own applications. There will be some things that don't work for the majority of use cases, and we will address those as they arise. Our goal remains to make this the most accessible financial data platform for everyone.

**Comment by xmanko** [comment]
1. I think we would all need an open source proxy server for IEX on a docker image. This proxy server/cache would keep the data up to date using Webhooks/streaming and/or end of days algos. The user would be paying per message between IEX and the proxy, but then it's illimited between the proxy and the user in-house algo/models. Currently, I am using an illimited data provider and all my backtesting algos constantly re-download the data from the data provider servers.

2. What is also very important is the quality of the data. We are all doing data analysis and it's very time consuming to develop filters and algo to sanitized the data so analysis and models don't crash or output meaningless results.

**Comment by elisag1990** [comment]
> @elisag1990 -- speak for yourself. Those of us with more modest needs I believe will find the free and/or launch plans very useful. I for one am quite content with what I can capture under the usage limits, which is the only reason I'm weighing in on your rant. Whether you're right about the cost/benefit in your use case or not, I honestly don't care, but to state that the lower-tiered pricing schemes are useless is both inaccurate and unhelpful.
> 
> I can understand frustration with the transition and there may very well be areas where the weighting is way off, but reducing the hyperbole and focusing on the issues would be far more productive.

I speak for myself, where am I saying something different?

**Comment by xmanko** [comment]
@elisag1990 Out of curiosity what data provider are you currently using and at what cost per month ?

**Comment by xmanko** [comment]
@joshuablackburn-iex 
> The addition of a sandbox environment will help alleviate message use in development.

Maybe you can setup a "lazy" sandbox environment by removing data weighting on two tickers, "AAPL" and "IBKR".

**Comment by joshuablackburn-iex** [comment]
@xmanko 
I agree completely that quality of data is important. It is our number one priority. We are working quickly to stabilize our equities data, and work out remaining bugs.

We are close on a sandbox environment. We are about 60% through development. All users will be issued a test pk token and test sk token, and will access the api through a new subdomain. Everything beyond that will be exactly the same. We intend for all endpoints to work exactly the same, with the same entitlements. You'll be able to see in the console what your test usage is, so you'll be able to both test against our endpoints and see what you can expect for message use. All data returned from the sandbox environment will be the same type and magnitude, but randomly altered to prevent distributing production data.

**Comment by wbhern** [comment]
@elisag1990 --

> I speak for myself, where am I saying something different?

When you make categorical statements like: 

_"Also let's be honest the free and launch plans are of no use. Any minimal use of the api would blow away the credit not in a month but in a day or so."_

you're purporting to speak for any/everyone. What you consider minimal is beyond maximal for me -- everyone's mileage varies. 

And no, I haven't looked closely at the data weight for each API call, because after working with the details that are relevant to me, seeing the consequent cost, and then doing the math, I came to a wildly different conclusion about the usefulness of the free and launch plans than you did.

I'd approach the problem you apparently have with the pricing model in a different manner than you have, but that's certainly your prerogative, and I'll not be continuing to critique it.

**Comment by elisag1990** [comment]
I m

> @elisag1990 --
> 
> > I speak for myself, where am I saying something different?
> 
> When you make categorical statements like:
> 
> _"Also let's be honest the free and launch plans are of no use. Any minimal use of the api would blow away the credit not in a month but in a day or so."_
> 
> you're purporting to speak for any/everyone. What you consider minimal is beyond maximal for me -- everyone's mileage varies.
> 
> And no, I haven't looked closely at the data weight for each API call, because after working with the details that are relevant to me, seeing the consequent cost, and then doing the math, I came to a wildly different conclusion about the usefulness of the free and launch plans than you did.
> 
> I'd approach the problem you apparently have with the pricing model in a different manner than you have, but that's certainly your prerogative, and I'll not be continuing to critique it.

This is only your own interpretation of the thing. Don't confuse reality with your ideas, they don't necessarily coincide.

**Comment by rickblokdijk** [comment]
It all depends on the functionality you want to build. But I agree, if you need regular updates on a lot of symbols the quota can go fast, so you have to be creative. I hoped the weight was less when filter the data with only fields needed but unfortunately :).
Anyhow, I am happy that this data is also available for the individual developer/startup, and the service, docs etc look really good! Just add that extra zero after each quota ;)

**Comment by bishinew** [comment]
We start testing the new API with the following batch call with 5 million per month Launch plan. The messages are used up so quickly.
/stock/market/batch?symbols=AAPL,QQQ&types=quote,stats

Each call has average symbols around 10-20. There are around 10000 calls. In four days, we use up 5 million messages. 

If we remove stats endpoint from the call, 5 million message will last about 2 weeks.

It seems only Scale plan is enough for commercial use. Launch plans are good for use with personal or a limit number of people.

**Comment by joshuablackburn-iex** [comment]
@bishinew 
A key feature that may be missed is pay-as-you-go. We can do a better job of communicating this. When you exceed your 5 million quota, you do not have to upgrade to 499. You can continue paying for what you use, and we've discounted messages over the quota.

In your first example, the stats endpoint data only updates once per day. So it is more efficient to only call that once. However, if you were to continue at the 5 million per 4 days pace, you would end up with a little over 26 million messages over 21 trading days. That would end up being **$32** for the month. Is $32 too much for your use case?

In the second example you would use 10 million for the month, so the bill for the month would be **$14**. 

We feel like these are all reasonable numbers given how expensive this data is elsewhere. Like I said before, we could do a much better job communicating how this works, but please let us know if $30 a month is too much.

**Comment by rickblokdijk** [comment]
I think the pay-as-you go option is great. 
Can you explain this in the documentation:

Key Stats Data Weighting
5 per call per symbol for full stats
1 per call per symbol for single stat filter

https://cloud.iexapis.com/beta/stock/aapl/stats?token=pk_xxxxxxxxxxxxxxxxxxx
https://cloud.iexapis.com/beta/stock/aapl/stats?token=pk_xxxxxxxxxxxxxxxxxxx&filter=day5ChangePercent

Both consumes 5 messages. Should a filter option consume:

A) 1 message or
B)  6 messages

Or do I misunderstood something?

**Comment by joshuablackburn-iex** [comment]
/stock/aapl/stats/day5ChangePercent?token=

That will be 1 message. You do highlight an issue where filter doesn't apply the weight. We can update it so that filter of 1 value will be 1 message.

**Comment by rickblokdijk** [comment]
ah clear.. sorry. yeah no need to update I guess. Only if you can use the filter attribute with 2 fields, and it will cost 2 messages. Then you only have to do a single call for getting 2 values for the lowest message cost.
