### ISSUE TITLE
Add revenue data to earning api

### ISSUE THREAD

**Issue by shoujs** [iexg/IEX-API#672]
## Summary
Current earning API `/stock/aapl/earnings` lacks of revenue data which is equal important as eps data as far as I see.
May I suggest adding revenue data to the earning API?

**Comment by joshuablackburn-iex** [comment]
Revenue is available from /stock/aapl/income

**Comment by shoujs** [comment]
Thank you. I see which API to get the revenue now. But it is inconvenient. Revenue and EPS are usually reported together. 
In my use case, if I want to show people earning report, I have to make 2 different request to get all the data I want(and people want).
I think adding revenue to earning report will benefit a lot of developers. Thank you.
