### ISSUE TITLE
Return complete earning histories

### ISSUE THREAD

**Issue by shoujs** [iexg/IEX-API#673]
## Summary
Current earning API `https://cloud.iexapis.com/beta/stock/nflx/earnings/10` only returns 5 quarters for maximum.
It that possible for IEXCloud provide a complete earning history of a company? for example, earning history from year 2000?

### API URL
`https://cloud.iexapis.com/beta/stock/nflx/earnings/10`

### What you expected to happen
 I expect it could give last 10 quarters.

### What actually happened
It gives me earnings of last 5 quarters

**Comment by joshuablackburn-iex** [comment]
Right now this is not possible. Earnings history over that many years is very expensive data and is not something we have access to at this time.
