### ISSUE TITLE
Where to report incorrect data?

### ISSUE THREAD

**Issue by shoujs** [iexg/IEX-API#675]
## Summary
I think Github issues is a platform best serving for API design discussions and tracking.
Reporting incorrect data should be moved to somewhere else, for staffs in charge of data consolidation to review.

For example, I found in Spotify's Q4 2018 earning, the eps (2.32007) is incorrect. It should be €0.36
Checkout their [press release](https://www.businesswire.com/news/home/20190206005298/en/).

## API 
https://cloud.iexapis.com/beta/stock/spot/earnings/10

**Comment by joshuablackburn-iex** [comment]
We are reporting basic EPS, not diluted EPS. 2.32 is the correct EPS for Q4

**Comment by shoujs** [comment]
But your consensus EPS is based on diluted shares. Actual EPS and consensus EPS should be consistent. 

`{
   symbol:"SPOT",
   earnings:[
      {
         actualEPS:2.32007,
         consensusEPS:-0.15,
         EPSSurpriseDollar:2.47,
      }
   ]
}
`

**Comment by shoujs** [comment]
Many sources use diluted EPS in reporting. Check out seekingalpha and streetinsider. I think we should stick to diluted EPS or better provide EPS in both formats.
