### ISSUE TITLE
Historical prices: wrong weighting for 1d data

### ISSUE THREAD

**Issue by stellarator** [iexg/IEX-API#676]
## Summary

[Documentation](https://iexcloud.io/docs/api/#historical-prices) states that weight for intraday minute bar data should be `1` per symbol per time interval for `1d` range up to a max of `50`. But real weight differs and looks like general weight for per day/month/... data. Moreover it doesn't contain cap limit.

### Date/time of issue

2017-02-13

### API URL

[https://cloud.iexapis.com/beta/stock/aapl/chart/date/20190212](https://cloud.iexapis.com/beta/stock/aapl/chart/date/20190212)

### What you expected to happen

Usage weight should contain mentioned cap limit (`50`) and should weight `1` per symbol per time interval for intraday data.

### What actually happened

For the mentioned request I was charged for **390 (time intervals) * 10 = 3900 messages**
I think the following link works the same way [https://cloud.iexapis.com/beta/stock/aapl/chart/1d](https://cloud.iexapis.com/beta/stock/aapl/chart/1d)

**Comment by joshuablackburn-iex** [comment]
I jut verified that 1d range does in fact limit to 50. The /date/20190212 does have the same weight as other historical data as specified in the docs. The reasoning is storing minute bar data on our side is 390x heavier on storage than end of day ohlcv. We will think through more use cases and ensure our weight is aligned with our pricing philosophy, but it is currently working as designed.
