### ISSUE TITLE
Today Earnings - 40 results max?

### ISSUE THREAD

**Issue by dwatring** [iexg/IEX-API#677]
## Summary
When I reach the /today-earnings endpoint, I only receive a max of 40 results. Are all earnings not returned? Wondering if I'm missing something, or if it's currently possible to return all earnings for the day.

### Date/time of issue
9:35AM, Feb 13, 2018

### API URL
https://api.iextrading.com/1.0/stock/market/today-earnings

### What you expected to happen
A return of all earnings for the day, sorted by BTO and AMC.

### What actually happened
A return of 20 earnings for each time (BTO and AMC).

### Other Information (sample code, links, etc.)
N/A

**Comment by joshuablackburn-iex** [comment]
We will update this to pull all earnings unless specified.

**Comment by dwatring** [comment]
Awesome, thanks @joshuablackburn-iex .

**Comment by dwatring** [comment]
Will this update be part of the new 2.0 release? Currently on V1.0.

Wondering if/when I can see some extra earnings data. 

Thanks!

**Comment by timpaine-iex** [comment]
closing as stale
