### ISSUE TITLE
Provide crypto-fiat pairs 

### ISSUE THREAD

**Issue by JMCA2** [iexg/IEX-API#678]
Right now the crypto endpoint only provides crypto-crypto pairs from Binance.

I think it's really necessary for the API to also provide crypto values in fiat currency. Such as BTC-USD, ETH-EUR, BCH-GBP etc.

**Comment by evancarter-iex** [comment]
This has been deployed.

**Comment by JMCA2** [comment]
@evancarter-iex EUR pairs are missing. Maybe it would be possible to add an optional parameter to crypto and stocks requests so that the quotes are converted to other currency, now that you also have real-time fx rates?
