### ISSUE TITLE
IEX Cloud: Mutual Fund Data Issue

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#679]
## Summary

1. Mutual Fund Data updates too late. Yahoo Finance updates the data around 6pm for the current trading day. IEX data updates next morning.

2. Change and Change Percent Missing

### API URL

https://cloud.iexapis.com/beta/stock/AAAAX/quote
https://cloud.iexapis.com/beta/stock/AAAAX/previous

**Comment by evancarter-iex** [comment]
@bishinew 

1) We understand this is a concern and are doing the best we can within the framework we have
2) We are working on adding this

**Comment by wbhern** [comment]
@evancarter-iex  --

Just to set expectations, does your response on the timing of mutual fund updates mean that you're working on a solution/improvement, or that we should expect mutual fund data to be delayed until the following morning indefinitely?

**Comment by evancarter-iex** [comment]
@wbhern We are working on improving the timeline for sure. As for how close to the Yahoo time we can get, its hard to say currently. We definitely want to get as close to that time as possible on our end.  When we have more information, you guys will be the first to know.

**Comment by wbhern** [comment]
@evancarter-iex - super, that's appreciated. I just wanted to plan accordingly if it wasn't going to move in that direction, but I will be glad to tap into the IEX Cloud data for mutual funds when it does.

**Comment by joshuablackburn-iex** [comment]
Fixed and deployed.

**Comment by wbhern** [comment]
@Josh - just for clarity, I assume that means the change and change percent
issue was fixed; any notion or projection for the timeframe for end-of-day
mutual fund data?

**Comment by evancarter-iex** [comment]
@wbhern Thats correct. The change and change % are fixed. We are still working hard on getting the time frame moved up for mutual fund. It something we want as much as you guys do, trust me :)
