### ISSUE TITLE
API and Chart Data Don't Match

### ISSUE THREAD

**Issue by radikal9** [iexg/IEX-API#68]
We are pulling data from the API (say https://iextrading.com/apps/stocks/#/apa) and it is not matching the data from the chart API (https://api.iextrading.com/1.0/stock/apa/chart).

**Comment by joshuablackburn-iex** [comment]
The first link you provided is for our Stocks app.  Did you intend to include that, or a link to our stock quote endpoint?  The following link works: https://iextrading.com/apps/stocks/#/APA

**Comment by radikal9** [comment]
Hi Josh - thanks for the follow up. We are using the API to capture different intraday data points on a stock and found discrepancies in areas like the low and high of a stock. Yesterday for APA at 9:41:17 we had a low of $43.01 using the API while the IEX chart was showing a low of $45.74. Now the chart is per minute and we are pulling our data more often than that using the API which can lead to some discrepancies but Yahoo Finance for instance shows the low of the day for APA as $45.08 (https://finance.yahoo.com/quote/APA/history/). We were using the first link as a reference to the API to try and see why there is such a big discrepancy in the low pricing.

**Comment by joshuablackburn-iex** [comment]
We currently don't provide market wide high and low, but it's in development and almost complete.  The current 1 day chart is only showing IEX data.  Our next release will supplement that with market wide data.

**Comment by radikal9** [comment]
We are grabbing the stock price for say APA every 10 seconds and saving it in a table so we can get close to our own low and high for a stock.  Great to hear that IEX will be supporting this! The data that the API is sending say around 9.17 yesterday for API says that the stock price was $43.01 but this does not match the data your chart API is using to build the chart or the data that other companies like Yahoo Finance are showing. So the API says that at 9.17 the price was $43.01 but your chart around that time is saying it is $45.08. Why is there such a big discrepancy on the price between the API and the stock chart?

**Comment by joshuablackburn-iex** [comment]
Do you mind providing more information about the exact time you're looking at?  Is it 9:17am EST?  9:17pm EST?  Also, you said the "API" says the price is 43.01.  What endpoint are you seeing 43.01, and where are you finding the stock chart?

**Comment by radikal9** [comment]
Hi Josh - thanks for taking the time to follow up. Digging into this deeper, it appears to have been an issue on our dev side. Looking forward to having the market wide high and low in the API!
