### ISSUE TITLE
Sentiment endpoint

### ISSUE THREAD

**Issue by rajpatelukyahoo** [iexg/IEX-API#680]
## Summary
Sentiment endpoint requires some clarification or a fix.

https://cloud.iexapis.com/beta/stock/aapl/sentiment/daily?token=pk_
- Not found message

https://cloud.iexapis.com/beta/stock/market/sentiment/minute?token=pk
- [] 

As per documentation
type | Optional. Can only be daily or minute. Default is daily.
date | Optional. Format YYYYMMDD date to fetch sentiment data.

## Details
Data is only returned when the date is specified.
https://cloud.iexapis.com/beta/stock/AAPL/sentiment/daily/20190213?token=pk

**Comment by joshuablackburn-iex** [comment]
Sentiment data is only available to Launch and Scale users.

**Comment by rajpatelukyahoo** [comment]
I am a launch user @joshuablackburn-iex .

It seems like it only works when date is specified.
