### ISSUE TITLE
Stock Earnings API Proposal: Next Earnings Date API End-Point

### ISSUE THREAD

**Issue by Bensign** [iexg/IEX-API#681]
## Summary

My use case is to know when the next earnings report will be for a particular stock. A potential end-point for this could be `/stock/#{ticker}/earnings/next` that, in the event a future earnings date is known by IEX, it returns a single earnings object of the next earnings report with the same fields present in the `/stock/#{ticker}/earnings` call. If no future earnings report is known at this time, it simply returns nil or an empty array or something along those lines. 

### Date/time of issue

02/13/2019 at approximately 9:30PM PST

### API URL

https://iextrading.com/developer/docs/#earnings

### What you expected to happen

* I expected there to be a separate API end-point for knowing the subsequent earning date. 

### What actually happened

* There is only an end-point for preceding earnings on a per-stock basis and earnings happening today on a per-market basis. 

### Other Information (sample code, links, etc.)

Let me know if I can help clarify anything on this.

**Comment by gabbersepp** [comment]
I have the same use case.
Would be nice if we can get those informations

**Comment by joshuablackburn-iex** [comment]
@Bensign 
Would this work? https://iexcloud.io/docs/api/#estimates

This will give you forward looking estimates as well as the next earnings report date. We can also update the docs to improve clarity if necessary.

**Comment by gabbersepp** [comment]
@joshuablackburn-iex  very nice. didn't see that

**Comment by Bensign** [comment]
@joshuablackburn-iex Ah-ha, that does work! Thanks for sharing that.
