### ISSUE TITLE
Quote latestTime is mixing date/datetime formats depending upon the symbol

### ISSUE THREAD

**Issue by wbhern** [iexg/IEX-API#682]
## Summary
Using https://cloud.iexapis.com/beta/stock/ibm/quote?token=pk_XXXXXXX produces a latestTime response of "4:01:37 PM"

Using the same query for FDX produces the latestTime in the heretofore standard format: "February 14, 2019"

The erroneous -- or at least inconsistent -- latestTime value occurred in roughly 80% of my sample.

### Date/time of issue
2/14/2019 after 18:00 US CST

### API URL
https://cloud.iexapis.com/beta/stock/ibm/quote?token=pk_XXXXXXX 

### What you expected to happen
The latestTime response to be "February 14, 2019"

### What actually happened
latestTime was 4:01:37 PM

{"symbol":"IBM","companyName":"International Business Machines Corporation","calculationPrice":"sip","open":137.23,"openTime":1550154610009,"close":137.52,"closeTime":1550091666027,"high":138.48,"low":136.21,"latestPrice":137.16,"latestSource":"15 minute delayed price","latestTime":"4:01:37 PM","latestUpdate":1550178097717,"latestVolume":2788640,"iexRealtimePrice":136.48,"iexRealtimeSize":16,"iexLastUpdated":1550177998630,"delayedPrice":137.16,"delayedPriceTime":1550178097717,"extendedPrice":137.39,"extendedChange":0.23,"extendedChangePercent":0.00168,"extendedPriceTime":1550192213127,"previousClose":137.52,"change":-0.36,"changePercent":-0.00262,"iexMarketPercent":0.01860440931780366,"iexVolume":51881,"avgTotalVolume":5224486,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":124650185040,"week52High":162.11,"week52Low":105.94,"ytdChange":0.1910263848624253}

**Comment by joshuablackburn-iex** [comment]
This is as designed. latestTime is a helper key that provides a human readable format of latestUpdate depending on the source of the latest price. If you need machine readable time please use latestUpdate.

**Comment by wbhern** [comment]
Josh -- I can shift my approach, but I guess I'm puzzled about a change to a process that has produced the heretofore expected results for at least a year or more. Based on the other reports from yesterday, this would simply seem to be a symptom of something awry.
