### ISSUE TITLE
IEX Cloud batch issues now grow to reporting old closing data for stocks

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#685]
## Summary
When the cloud API was first introduced I was able to get the most recent 'close' price for all shares and mutual funds in my portfolio. Earlier this week I noticed that only stock prices were being updated - now even the stock prices are frequently reporting old closes (as of today I am getting closes for Feb 13, 2019 for most stocks).

### Date/time of issue
Feb 14,2019 - Feb 15, 2019

### API URL
https://cloud.iexapis.com/beta/stock/market/batch?types=quote,dividends&symbols=erf,es,ese,etn,exc,expd&range=1y&token=MY_TOKEN

### What you expected to happen
As of the end-of-day, I expect quotes to reflect open, high, low and close for the latest trading day.

### What actually happened
Some stocks report closing price for the latest trading day, others are not updated from the previous trading day's close. Further, the open timestamp is later than the closing timestamp. (See data below)

All of these shares reported open timestamps later than the closing timestamp

### Other Information (sample code, links, etc.)

[2019-02-14 Sample Dailies.txt](https://github.com/iexg/IEX-API/files/2869299/2019-02-14.Sample.Dailies.txt)

**Comment by joshuablackburn-iex** [comment]
This should be resolved now. We are investigating some late reporting of close prices that occurred when mutual fund and otc were introduced. We have a new end of day process in QA that should speed up processing of overnight files.

**Comment by GraceRg** [comment]
Josh,

Thanks for the reply, is there any way to get a credit for the end-points called while the issue existed?
Please advise, Rg

Roger G Grace
roger.grace@me.com
+1 512.751-8211

**Comment by GraceRg** [comment]
Josh,

Actually, I just ran the same queries again with the same results - open date time stamp is later than the close stamp and close prices are still as of Feb 13.
Can I send anything to assist with debugging? (See below for formatted json results from moments ago).

Rg

Roger G Grace
roger.grace@me.com
+1 512.751-8211



{
    "ERF": {
        "quote": {
            "symbol": "ERF",
            "companyName": "Enerplus Corporation",
            "calculationPrice": "sip",
            "open": 8.2,
            "openTime": 1550154600255,
            "close": 8.24,
            "closeTime": 1550091675308,
            "high": 8.46,
            "low": 8.17,
            "latestPrice": 8.372,
            "latestSource": "15 minute delayed price",
            "latestTime": "4:01:46 PM",
            "latestUpdate": 1550264506969,
            "latestVolume": 544587,
            "iexRealtimePrice": 0,
            "iexRealtimeSize": 0,
            "iexLastUpdated": 0,
            "delayedPrice": 8.372,
            "delayedPriceTime": 1550264506969,
            "extendedPrice": 8.2,
            "extendedChange": -0.172,
            "extendedChangePercent": -0.02054,
            "extendedPriceTime": 1550183586612,
            "previousClose": 8.34,
            "change": 0.032,
            "changePercent": 0.00384,
            "iexMarketPercent": null,
            "iexVolume": 0,
            "avgTotalVolume": 611648,
            "iexBidPrice": 0,
            "iexBidSize": 0,
            "iexAskPrice": 0,
            "iexAskSize": 0,
            "marketCap": 2040683372,
            "week52High": 13.87,
            "week52Low": 6.84,
            "ytdChange": 0.05289660377358487
        },
        "dividends": [
            {
                "exDate": "2019-01-30",
                "paymentDate": "2019-02-15",
                "recordDate": "2019-01-31",
                "declaredDate": "2019-01-21",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-12-27",
                "paymentDate": "2019-01-15",
                "recordDate": "2018-12-28",
                "declaredDate": "2018-12-17",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-11-28",
                "paymentDate": "2018-12-14",
                "recordDate": "2018-11-29",
                "declaredDate": "2018-11-19",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-10-29",
                "paymentDate": "2018-11-15",
                "recordDate": "2018-10-30",
                "declaredDate": "2018-10-19",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-09-27",
                "paymentDate": "2018-10-15",
                "recordDate": "2018-09-28",
                "declaredDate": "2018-09-18",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-08-29",
                "paymentDate": "2018-09-14",
                "recordDate": "2018-08-30",
                "declaredDate": "2018-08-20",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-07-27",
                "paymentDate": "2018-08-15",
                "recordDate": "2018-07-30",
                "declaredDate": "2018-07-18",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-06-28",
                "paymentDate": "2018-07-16",
                "recordDate": "2018-06-29",
                "declaredDate": "2018-06-19",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-05-29",
                "paymentDate": "2018-06-15",
                "recordDate": "2018-05-30",
                "declaredDate": "2018-05-17",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-04-27",
                "paymentDate": "2018-05-15",
                "recordDate": "2018-04-30",
                "declaredDate": "2018-04-19",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-03-28",
                "paymentDate": "2018-04-16",
                "recordDate": "2018-03-29",
                "declaredDate": "2018-03-19",
                "amount": 0.01,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-02-27",
                "paymentDate": "2018-03-15",
                "recordDate": "2018-02-28",
                "declaredDate": "2018-02-16",
                "amount": 0.01,
                "flag": "No Change QoQ"
            }
        ]
    },
    "ES": {
        "quote": {
            "symbol": "ES",
            "companyName": "Eversource Energy",
            "calculationPrice": "sip",
            "open": 70.19,
            "openTime": 1550154609289,
            "close": 70.06,
            "closeTime": 1550091787460,
            "high": 70.48,
            "low": 69.73,
            "latestPrice": 70.256,
            "latestSource": "15 minute delayed price",
            "latestTime": "4:11:45 PM",
            "latestUpdate": 1550265105935,
            "latestVolume": 1735010,
            "iexRealtimePrice": 0,
            "iexRealtimeSize": 0,
            "iexLastUpdated": 0,
            "delayedPrice": 70.256,
            "delayedPriceTime": 1550265105935,
            "extendedPrice": 70.19,
            "extendedChange": -0.066,
            "extendedChangePercent": -0.00094,
            "extendedPriceTime": 1550183791998,
            "previousClose": 70.1,
            "change": 0.156,
            "changePercent": 0.00223,
            "iexMarketPercent": null,
            "iexVolume": 0,
            "avgTotalVolume": 1625773,
            "iexBidPrice": 0,
            "iexBidSize": 0,
            "iexAskPrice": 0,
            "iexAskSize": 0,
            "marketCap": 22263142816,
            "week52High": 70.62,
            "week52Low": 52.76,
            "ytdChange": 0.10634088360371699
        },
        "dividends": [
            {
                "exDate": "2019-03-04",
                "paymentDate": "2019-03-29",
                "recordDate": "2019-03-05",
                "declaredDate": "2019-02-06",
                "amount": 0.535,
                "flag": "Increase"
            },
            {
                "exDate": "2018-05-23",
                "paymentDate": "2018-06-29",
                "recordDate": "2018-05-24",
                "declaredDate": "2018-05-02",
                "amount": 0.505,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-03-05",
                "paymentDate": "2018-03-30",
                "recordDate": "2018-03-06",
                "declaredDate": "2018-02-07",
                "amount": 0.505,
                "flag": "Increase"
            }
        ]
    },
    "ESE": {
        "quote": {
            "symbol": "ESE",
            "companyName": "ESCO Technologies Inc.",
            "calculationPrice": "sip",
            "open": 67.9,
            "openTime": 1550154600403,
            "close": 68.12,
            "closeTime": 1550091725255,
            "high": 68.41,
            "low": 67.27,
            "latestPrice": 67.32,
            "latestSource": "15 minute delayed price",
            "latestTime": "4:02:03 PM",
            "latestUpdate": 1550264523843,
            "latestVolume": 101641,
            "iexRealtimePrice": 0,
            "iexRealtimeSize": 0,
            "iexLastUpdated": 0,
            "delayedPrice": 67.32,
            "delayedPriceTime": 1550264523843,
            "extendedPrice": 65.2,
            "extendedChange": -2.12,
            "extendedChangePercent": -0.03149,
            "extendedPriceTime": 1549372970907,
            "previousClose": null,
            "change": null,
            "changePercent": null,
            "iexMarketPercent": null,
            "iexVolume": 0,
            "avgTotalVolume": 108257,
            "iexBidPrice": 0,
            "iexBidSize": 0,
            "iexAskPrice": 0,
            "iexAskSize": 0,
            "marketCap": 1744867080,
            "week52High": 71.47,
            "week52Low": 54.35,
            "ytdChange": 0.038728591266779674
        },
        "dividends": [
            {
                "exDate": "2019-04-02",
                "paymentDate": "2019-04-18",
                "recordDate": "2019-04-03",
                "declaredDate": "2019-02-07",
                "amount": 0.08,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2019-01-02",
                "paymentDate": "2019-01-18",
                "recordDate": "2019-01-03",
                "declaredDate": "2018-11-15",
                "amount": 0.08,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-10-02",
                "paymentDate": "2018-10-17",
                "recordDate": "2018-10-03",
                "declaredDate": "2018-08-07",
                "amount": 0.08,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-07-03",
                "paymentDate": "2018-07-19",
                "recordDate": "2018-07-05",
                "declaredDate": "2018-05-08",
                "amount": 0.08,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-04-02",
                "paymentDate": "2018-04-18",
                "recordDate": "2018-04-03",
                "declaredDate": "2018-02-06",
                "amount": 0.08,
                "flag": "No Change QoQ"
            }
        ]
    },
    "ETN": {
        "quote": {
            "symbol": "ETN",
            "companyName": "Eaton Corp. Plc",
            "calculationPrice": "previousclose",
            "open": 77.14,
            "openTime": 1550154601420,
            "close": 77.67,
            "closeTime": 1550091710480,
            "high": null,
            "low": null,
            "latestPrice": 77.2,
            "latestSource": "Previous close",
            "latestTime": "February 14, 2019",
            "latestUpdate": 1550102400000,
            "latestVolume": 1706954,
            "iexRealtimePrice": 0,
            "iexRealtimeSize": 0,
            "iexLastUpdated": 0,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": 77.2,
            "extendedChange": 0,
            "extendedChangePercent": 0,
            "extendedPriceTime": 1550276347596,
            "previousClose": 77.2,
            "change": 0,
            "changePercent": 0,
            "iexMarketPercent": null,
            "iexVolume": 0,
            "avgTotalVolume": 2838785,
            "iexBidPrice": 0,
            "iexBidSize": 0,
            "iexAskPrice": 0,
            "iexAskSize": 0,
            "marketCap": 33458480000,
            "week52High": 89.46,
            "week52Low": 64.46,
            "ytdChange": 0.125200408103775
        },
        "dividends": [
            {
                "exDate": "2018-11-01",
                "paymentDate": "2018-11-16",
                "recordDate": "2018-11-02",
                "declaredDate": "2018-10-23",
                "amount": 0.66,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-08-02",
                "paymentDate": "2018-08-17",
                "recordDate": "2018-08-03",
                "declaredDate": "2018-07-24",
                "amount": 0.66,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-05-03",
                "paymentDate": "2018-05-18",
                "recordDate": "2018-05-04",
                "declaredDate": "2018-04-24",
                "amount": 0.66,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-03-09",
                "paymentDate": "2018-03-23",
                "recordDate": "2018-03-12",
                "declaredDate": "2018-02-28",
                "amount": 0.66,
                "flag": "Increase"
            }
        ]
    },
    "EXC": {
        "quote": {
            "symbol": "EXC",
            "companyName": "Exelon Corporation",
            "calculationPrice": "previousclose",
            "open": 47.85,
            "openTime": 1550154600256,
            "close": 47.9,
            "closeTime": 1550091730629,
            "high": null,
            "low": null,
            "latestPrice": 47.86,
            "latestSource": "Previous close",
            "latestTime": "February 14, 2019",
            "latestUpdate": 1550102400000,
            "latestVolume": 3855892,
            "iexRealtimePrice": 0,
            "iexRealtimeSize": 0,
            "iexLastUpdated": 0,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": 47.86,
            "extendedChange": 0,
            "extendedChangePercent": 0,
            "extendedPriceTime": 1550276347786,
            "previousClose": 47.86,
            "change": 0,
            "changePercent": 0,
            "iexMarketPercent": null,
            "iexVolume": 0,
            "avgTotalVolume": 5391243,
            "iexBidPrice": 0,
            "iexBidSize": 0,
            "iexAskPrice": 0,
            "iexAskSize": 0,
            "marketCap": 46412043560,
            "week52High": 48.16,
            "week52Low": 36.5,
            "ytdChange": 0.08599954617653731
        },
        "dividends": [
            {
                "exDate": "2019-02-19",
                "paymentDate": "2019-03-08",
                "recordDate": "2019-02-20",
                "declaredDate": "2019-02-05",
                "amount": 0.3625,
                "flag": "Increase"
            },
            {
                "exDate": "2018-11-14",
                "paymentDate": "2018-12-10",
                "recordDate": "2018-11-15",
                "declaredDate": "2018-09-24",
                "amount": 0.345,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-08-14",
                "paymentDate": "2018-09-10",
                "recordDate": "2018-08-15",
                "declaredDate": "2018-07-24",
                "amount": 0.345,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-05-14",
                "paymentDate": "2018-06-08",
                "recordDate": "2018-05-15",
                "declaredDate": "2018-05-01",
                "amount": 0.345,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-02-14",
                "paymentDate": "2018-03-09",
                "recordDate": "2018-02-15",
                "declaredDate": "2018-01-30",
                "amount": 0.345,
                "flag": "Increase"
            }
        ]
    },
    "EXPD": {
        "quote": {
            "symbol": "EXPD",
            "companyName": "Expeditors International of Washington, Inc.",
            "calculationPrice": "sip",
            "open": 73.42,
            "openTime": 1550154600272,
            "close": 73.77,
            "closeTime": 1550091600376,
            "high": 74.46,
            "low": 73.14,
            "latestPrice": 74.039,
            "latestSource": "15 minute delayed price",
            "latestTime": "4:24:37 PM",
            "latestUpdate": 1550265877313,
            "latestVolume": 1010479,
            "iexRealtimePrice": 0,
            "iexRealtimeSize": 0,
            "iexLastUpdated": 0,
            "delayedPrice": 74.039,
            "delayedPriceTime": 1550265877313,
            "extendedPrice": 73.77,
            "extendedChange": -0.269,
            "extendedChangePercent": -0.00363,
            "extendedPriceTime": 1550183791981,
            "previousClose": 73.96,
            "change": 0.079,
            "changePercent": 0.00107,
            "iexMarketPercent": null,
            "iexVolume": 0,
            "avgTotalVolume": 1152429,
            "iexBidPrice": 0,
            "iexBidSize": 0,
            "iexAskPrice": 0,
            "iexAskSize": 0,
            "marketCap": 12778391010,
            "week52High": 78.16,
            "week52Low": 60.8,
            "ytdChange": 0.09986661268756487
        },
        "dividends": [
            {
                "exDate": "2018-11-30",
                "paymentDate": "2018-12-17",
                "recordDate": "2018-12-03",
                "declaredDate": "2018-11-06",
                "amount": 0.45,
                "flag": "No Change QoQ"
            },
            {
                "exDate": "2018-05-31",
                "paymentDate": "2018-06-15",
                "recordDate": "2018-06-01",
                "declaredDate": "2018-05-09",
                "amount": 0.45,
                "flag": "Increase"
            }
        ]
    }
}
