### ISSUE TITLE
Subset of stock quotes giving stale response [with extremely low volume/no volume]

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#686]
## Summary
Issue was reported as closed this morning, but latest calls to end-point still produce stale results. If issue is closed, when will results be updated?

When the cloud API was first introduced I was able to get the most recent 'close' price for all shares and mutual funds in my portfolio. Earlier this week I noticed that only stock prices were being updated - now even the stock prices are frequently reporting old closes (as of today I am getting closes for Feb 13, 2019 for most stocks).

## Details
Stocks ERF, ES, ESE (among others) report an opening date of Feb 14 but a closing date of Feb 13 when requested after close of trading on Feb 14 and again in the early hours of Feb 15.

### Date/time of issue
Latest calls took place 2019.02.15 0908 Eastern

### API URL
https://cloud.iexapis.com/beta/stock/market/batch?types=quote,dividends&symbols=erf,es,ese,etn,exc,expd&range=1y&token=MY_TOKEN

### What you expected to happen
Closing timestamp should be later than opening timestamp when end-point is invoked after close of trading for a given day.

### What actually happened
Closing timestamp is from previous day

### Other Information (sample code, links, etc.)
[2019-02-14 Sample Dailies.txt](https://github.com/iexg/IEX-API/files/2869535/2019-02-14.Sample.Dailies.txt)

**Comment by evancarter-iex** [comment]
You were correct to reopen this. This appears to be happening to a subset of stocks. (Most seem fine). We are working on trying to determine why that is.

**Comment by sqaxomonophonen** [comment]
We're experiencing a similar problem with a subset of stocks (about 20 symbols). For instance, the quote endpoint currently reports 2019-02-21 as the latest close date for NYSE:AMOV. However, the historical data (chart) endpoint doesn't seem to be affected: it has close data for both 2019-02-21 and 2019-02-22.

**Comment by evancarter-iex** [comment]
@sqaxomonophonen Do you have a list of those 20 symbols? Or are they same as the original report?

**Comment by sqaxomonophonen** [comment]
> @sqaxomonophonen Do you have a list of those 20 symbols? Or are they same as the original report?

I did some cross referencing of the quote/chart EOD discrepancies we know of. Seems it was more like 50-60 symbols :-) More info in the attached file:

[iex-discrepancies.txt](https://github.com/iexg/IEX-API/files/2901306/iex-discrepancies.txt)

The list is likely not exhaustive since it's just based on symbols that raised a flag in our application. I haven't done a full cross reference against GraceRg's list, but at least the 3 symbols mentioned (ERF, ES, ESE) are not on my list.

**Comment by GraceRg** [comment]
All,

I believe the ’stale’ stock prices issue has been largely resolved (at least for the 200+ stocks that I track regularly). As of Friday, Feb 22, there were only a couple of stocks in question:

FDUS, FSIC

That said, I can easily give you a list (see below) of mutual funds for which prices are often delayed by 24hrs. This list represents every fund I track, so my expectation is that the issue may be much broader than my short list suggests.

ACEIX, LBNDX, MABAX, NOTAX, NOTCX, PNOPX,
USAGX, USAIX, USCGX, USCRX, USIBX, USSBX, VDIGX

Hope this helps ...

Regards, 

Roger G Grace
roger.grace@me.com
+1 512.751-8211

**Comment by evancarter-iex** [comment]
We believe the reason for the stock discrepancy is due to those stocks not trading recently.  We dont handle that as well as we should in the chart endpoint, (its just duplicating the open/close from the day before since there was no trades). We are still looking into how to make this a) documented better b) handled better in the the chart endpoint.

@GraceRg As for mutual funds, they should be updated by 8am every day. We are still working with our data provider to push it back to around 8pm day of.

**Comment by sqaxomonophonen** [comment]
@evancarter-iex ok, we can work with that. However, for NYSE:AMOV I saw a close value of 15 (15.0000) for 2019-02-21 and 15.0395 for 2019-02-22 in the chart endpoint (the quote endpoint says 15.0000 / 2019-02-21), so it's not simply a copy of the previous day's value? (looking up EOD charts for AMOV on Google gives similar values). It's not a problem for us, but I wanted to point it out in case there might be something else going on that you've missed.

**Comment by evancarter-iex** [comment]
@sqaxomonophonen Thanks, yeah looking into it, it looks like AMOV didnt have an official close on NYSE on one day but may have traded elsewhere, hence the incongruity.  We will work on cleaning up the close/chart stuff on these low volume stocks and update the documentation.

**Comment by evancarter-iex** [comment]
I havent seen any issues with this recently. Im going to close this. If its still an issue can you file a new issue with the particular stock (I checked the ones above and they looked good to me)
