### ISSUE TITLE
Expected earnings dates returned in EPSReportDate are stale

### ISSUE THREAD

**Issue by nhsb1** [iexg/IEX-API#687]
## Summary

The REST API returns stale earnings date for EPSReportDate for all symbols queried.

## Details

According to the API documentation (https://iexcloud.io/docs/api/#earnings), the EPSReportDate response attribute should return the "Expected Earnings Date" (YYYY-MM-DD).  For the symbols that I checked, it returns the most recent, but stale, actual earnings date information. 

### Date/time of issue

On-going (2/15/2019, at 11:41am eastern)

### API URL

https://cloud.iexapis.com/beta/stock/aapl/earnings?token=my_token
https://cloud.iexapis.com/beta/stock/xlnx/earnings?token=my_token
https://cloud.iexapis.com/beta/stock/oled/earnings?token=my_token
https://cloud.iexapis.com/beta/stock/emr/earnings?token=my_token

### What you expected to happen

For each of the symbols queried, I expected EPSReportDate to return the next expected earnings date.  As of today, those symbol (date) combinations for the expected dates should be: AAPL (5/7/19), XLNX (4/24/19), OLED (2/21/19 AMC), EMR (5/7/19).  For example, I would have expected the response from AAPL to be:

{"symbol":"AAPL","earnings":[{"actualEPS":4.18,"consensusEPS":4.66,"announceTime":"AMC","numberOfEstimates":36,"EPSSurpriseDollar":-0.48,"EPSReportDate":"2019-05-19","fiscalPeriod":"Q4 2018","fiscalEndDate":"2018-12-31","yearAgo":3.89,"yearAgoChangePercent":0.0746}]}

### What actually happened

The most recent prior earnings date was returned for the EPSReportDate value.  Below is the response I actually received:

{"symbol":"AAPL","earnings":[{"actualEPS":4.18,"consensusEPS":4.66,"announceTime":"AMC","numberOfEstimates":36,"EPSSurpriseDollar":-0.48,"EPSReportDate":"2019-01-30","fiscalPeriod":"Q4 2018","fiscalEndDate":"2018-12-31","yearAgo":3.89,"yearAgoChangePercent":0.0746}]}

**Comment by joshuablackburn-iex** [comment]
Forward looking is under /estimates. We will update the docs to make this more clear.
