### ISSUE TITLE
Dividend/next end point does not work for symbol without announced dividend

### ISSUE THREAD

**Issue by rittik97** [iexg/IEX-API#688]
API calls such as https://cloud.iexapis.com/beta/stock/aapl/dividends/next?token=YOUR_TOKEN_HERE
return "Not found" for all symbols.

**Comment by cgailey** [comment]
This seems to happen when there is no announced upcoming dividend (by ex-date). Try 'STX' symbol. I get:

{"exDate":"2019-03-19","paymentDate":"2019-04-03","recordDate":"2019-03-20","declaredDate":"2019-02-04","amount":0.63,"flag":"No Change QoQ","symbol":"STX"}

Apple's most recent ex-date is Feb 8, so in the past.

**Comment by evancarter-iex** [comment]
This should be fixed now and is deployed.
