### ISSUE TITLE
Provide open, change, change%, high, low for websocket

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#69]
Currently, we have `last` channel which is able to provide IEX real-time pricing.

However, besides real-time last price, we are also interested in open, change, change%, high, low as well. Basically, we want to show user price movement in stock watchlist, in real-time.

Is it feasible, to have a channel which is able to stream the below data in single shot?

- Last
- Open
- Change
- Change%
- Day High
- Day Low

A similar ticket is found https://github.com/iexg/IEX-API/issues/56

Thanks.

**Comment by leedstyh** [comment]
Thinking that'll generate a lot of redundant data, things can be calculated by either client side (end user) or server side (your app) should not be sent every time. 

Say my use case is filtering stocks on my server and then send the results to client, that way will waste too much bandwidth.

**Comment by leedstyh** [comment]
How about send the full data right after the ws connection is open, and send `last` afterwards.

**Comment by joshuablackburn-iex** [comment]
We are rolling out OHLC into a testing environment today.  I would recommend waiting for that data since websocket data only represents IEX trades and not market wide.

**Comment by maryokhin** [comment]
@joshuablackburn-iex will there be an announcement about this somewhere? I am developing a new app and trying to decide between using polling HTTP or WS. Thanks.

**Comment by joshuablackburn-iex** [comment]
@maryokhin It would probably be good to write to HTTP for now.  We are working on SSE, which we hope to have by the end of the month, and we favor SSE over Websocket going forward.

**Comment by maryokhin** [comment]
@joshuablackburn-iex great, thanks for the quick reply

**Comment by yccheok** [comment]
@joshuablackburn-iex Oh, we just plan to roll out a new feature based on IEX Websocket. Will websocket be supported in foreseeable future?

**Comment by BullMarket** [comment]
Hi @joshuablackburn-iex , I'm wondering when can High/Low/Volume/VWAP be added to quote endpoint - https://api.iextrading.com/1.0/stock/aapl/quote ? Thank you!

**Comment by joshuablackburn-iex** [comment]
Open High Low and Close are now are available from /quote.  Documentation update to follow.

**Comment by yccheok** [comment]
Hi @joshuablackburn-iex 

According to https://iextrading.com/developer/docs/#last

Previously, I was using 

https://ws-api.iextrading.com/1.0/last

```
const url = 'https://ws-api.iextrading.com/1.0/last'
const socket = require('socket.io-client')(url)

socket.on('connect', () => {
  socket.emit('subscribe', 'snap')
})

```

I was able to receive `connect` event.

However, when I switch to 

https://ws-api.iextrading.com/1.0/quote

```
const url = 'https://ws-api.iextrading.com/1.0/quote'
const socket = require('socket.io-client')(url)

socket.on('connect', () => {
  socket.emit('subscribe', 'snap')
})

```

I was no longer able to receive `connect` event. Am I missing something?

Thanks.

**Comment by jcape** [comment]
@yccheok Quote is not a valid websocket endpoint, and we don't currently support websockets for the Stocks API at this time.

That being said, top-of-book quotes are available at https://iextrading.com/developer/docs/#tops and some components of the stocks/<stock>/quote are available in streaming form via our DEEP API: https://iextrading.com/developer/docs/#deep
