### ISSUE TITLE
What's "IEX-only data" data in API docs?

### ISSUE THREAD

**Issue by pps83** [iexg/IEX-API#690]
https://iextrading.com/developer/docs/#chart has this:

![image](https://user-images.githubusercontent.com/1614246/52906358-ed0cbd00-31fe-11e9-8da1-ed3f99b185eb.png)

What exactly does "IEX-only data" mean here? It should be tooltip or a link right there for the explanation.

**Comment by joshuablackburn-iex** [comment]
It means data that comes only from Investors Exchange (IEX).
