### ISSUE TITLE
multiple zero values in one minute data

### ISSUE THREAD

**Issue by louisLouL** [iexg/IEX-API#692]
## Summary
There is a lot of zero values in MarketClose field for SPY on 20190204. 

## Details
Starting from approximately 11:00 AM

### Date/time of issue
2/4/2019

### API URL
https://api.iextrading.com/1.0/stock/spy/chart/date/20190204

### What you expected to happen
Can you please either fix it or fill the marketclose with next minute marketopen?

### What actually happened
A lot of 0 value

### Other Information (sample code, links, etc.)

```json
{
    "date": "20190204",
    "minute": "11:00",
    "label": "11 AM",
    "high": 270.33,
    "low": 270.19,
    "average": 270.326,
    "volume": 2716,
    "notional": 734206.04,
    "numberOfTrades": 4,
    "marketHigh": 270.33,
    "marketLow": 270.15,
    "marketAverage": 270.243,
    "marketVolume": 132710,
    "marketNotional": 35863923.0206,
    "marketNumberOfTrades": 607,
    "open": 270.19,
    "close": 270.33,
    "marketOpen": 270.17,
    "marketClose": 0,
    "changeOverTime": 0.001062809446043107,
    "marketChangeOverTime": 0.0005627732875215642
},
```

**Comment by joshuablackburn-iex** [comment]
This was an issue that has since been resolved. It should be good going forward, and we will need to back populate old days.
