### ISSUE TITLE
IEX Cloud: Add Div info to Quote Endpoint

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#696]
## Summary
Is it possible to add current dividend and ex-div date to Quote endpoint? 

### API URL

/stock/aapl/quote

**Comment by evancarter-iex** [comment]
Is this in regards to the old api or cloud?

**Comment by bishinew** [comment]
New API 

IEX Cloud

**Comment by bishinew** [comment]
For endpoint Quote: one batch call with multiple symbols (for example 10 symbols) is one message or 10 messages?

**Comment by evancarter-iex** [comment]
10 messages
