### ISSUE TITLE
New API IEX Cloud Use Too much Messages

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#697]
## Summary
I have a batch call with endpoints: quote and stats. In one day, I got.

KEY_STATS | 2,166,420
-- | --
STOCK_QUOTE | 108,322

The page impression is around 10,000.

How come so much quota (more than 2 million) was used in one day. 

We have $9 plan. We will exceed quote in about two days.

And I just start to test the API since yesterday.

Please help.

### API URL

/stock/market/batch?symbols=APPL,GOOGL,QQQ,IBM,MSFT&types=quote,stats

**Comment by joshuablackburn-iex** [comment]
The message weighting reflects the frequency and value of the data. We encourage efficient use of the platform. Key stats are not changing during the day, so you would have far less use if you cache the data.

**Comment by gbreeze** [comment]
Hm.. I played around with earnings and estimates today. My starter limit is almost used.

![image](https://user-images.githubusercontent.com/1906169/53444407-5c0fc000-3a0e-11e9-9afc-23d26de8b54c.png)

OK, to fill my tables with this data for the ~6000 stocks will cost me something... :-|
