### ISSUE TITLE
Dividend Data for AINV date swap

### ISSUE THREAD

**Issue by cgailey** [iexg/IEX-API#698]
## Summary
I've encountered a few errors in the dividend data.  Should they be reported here or directly to Eventvestor, the provider?

## Details
curl https://cloud.iexapis.com/beta/stock/AINV/dividends/next?token=pk_TOKEN
returns:
{"exDate":"2019-04-04","paymentDate":"2019-03-21","recordDate":"2019-04-05","declaredDate":"2019-02-06","amount":0.45,"flag":"No Change QoQ","symbol":"AINV"}
Looks like pay date and record date were swapped.

### Date/time of issue
Feb 20, 2019 13:52

### API URL
https://cloud.iexapis.com/beta/stock/AINV/dividends/next

**Comment by joshuablackburn-iex** [comment]
All data related issues should be reported here.

**Comment by evancarter-iex** [comment]
This is fixed.
