### ISSUE TITLE
New API IEX Cloud: Batch Request with Invalid Symbol

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#699]
## Summary
The batch Quote request with symbol
AAPL,XYZ

New API: returns unknown symbol
Old API returns quote: AAPL

This is critical bug for us. User may enter a invalid symbol with other valid symbols. It should returns quote for valid symbols. Also some symbols used in IEX may be different from what users knows.

Please do the same as the old API

### API URL

stock/market/batch?symbols=AAPL,XYZ&types=quote

**Comment by evancarter-iex** [comment]
We are looking into this.

**Comment by joshuablackburn-iex** [comment]
We've reverted functionality to match the old API. Batch will return data for valid symbols.
