### ISSUE TITLE
Multiple quotes through stocks endpoint

### ISSUE THREAD

**Issue by jrseriel** [iexg/IEX-API#7]
Not so much a bug rather a request for multiple quotes through the stocks endpoint.

**Comment by joshuablackburn-iex** [comment]
Here is an example of a batch call:

https://api.iextrading.com/1.0/stock/market/batch?types=quote,news&symbols=aapl,nflx,fb

We currently limit the number of symbols to 25 per call.  Our API documentation will be updated next week with all of our new calls.

**Comment by jrseriel** [comment]
Thank you for this information. Is there any symbol limit on the TOPs endpoint?

**Comment by joshuablackburn-iex** [comment]
The TOPS endpoint does not have a limit.  If you request /tops without the symbols parameter, it will return all symbols.

**Comment by joshuablackburn-iex** [comment]
Documentation has been updated.
