### ISSUE TITLE
where does the data come from?

### ISSUE THREAD

**Issue by myvaluealerts** [iexg/IEX-API#70]
Where does IEX pull data from?  And, does IEX really understand that your users are developing software they hope will be reliable and repeatable so we have a basis for making an investment decision and recommending investments to our clients?

I'm excited about acquirig reliable data from a supplier who understands the importance of reliable analysts concensus data (EPS forcast data current year and next year, PEG, and more).  Yahoo decided it was just a bunch of numbers and  did not understand the data represented "a stream of future cash flows to be generated by a corporation".  The sum of those future cash flows therefore could be discounted to reflect a current valid stock price.  A proper valuation if you will.  Hence the reason I developed my website myvaluealerts.com to help determine a realistic value for individual stocks.

I'm new to IEX.  I'm here because my data feed was cut off on 11/1/17 when yahoo shut down feeding data.  I consider the yahoo shutdown a good thing because much of the yahoo finance data was contaminated AND but more importantly there was no one to report problems to.  Yahoo did not seem to care about the data or the users of the data they were only interested in using the site to advertise.  Good bye and good riddence to Yahoo Finance!

**Comment by joshuablackburn-iex** [comment]
@myvaluealerts IEX is a registered primary listing exchange, so real time trades and quotes come from us.  Once we list companies we will also provide corporate action data.  The API also power our own Exchange applications, so reliability is a top concern.  

Some data comes from third parties, and we make a best effort on data quality, but we cannot make any guarantees.  As issues with data are brought to our attention, we will work to address the concern.
