### ISSUE TITLE
Historical prices (/chart/): Get prices since date (or, get n latest prices)

### ISSUE THREAD

**Issue by lohisoftware** [iexg/IEX-API#700]
## Summary

Can you please comment, would it be possible to add an endpoint in the /chart/ API that would return prices since a given date, or alternatively, n latest prices?

I try to explain my use case below.

## Details

I'm working on a stock screener where I need about 1 year worth of daily prices for all symbols, updated daily. Since I'm a developer on a shoestring, I'd like to call the /chart/1y API only once for all symbols and then call some other, cheaper API endpoint daily to add new prices to my prices database.

If I call /chart/1m for all symbols once a day, it blows out the $9 plan quota, especially since the /chart/ API weighting is quite high. I'd only like to load the prices that I don't already have, which is usually just one price.

I could call the /ohlc/ API as a cheaper alternative to grab the latest daily prices. However, that gets too hacky in my opinion. If there are days when I fail to call the /ohlc/ API, I'm now missing prices, and then I'd have to call the /chart/1m endpoint for all symbols, which would be expensive. And, /ohlc/ doesn't return volume and also the prices seem to be somewhat different from what /chart/ API returns - I'd optimally get my prices only from one source.

Overall I like the API very much. Thanks.

**Comment by joshuablackburn-iex** [comment]
We've updated historical prices to be able to call by a single date using the range 'date' and query parameter chartByDay=true.  

https://iexcloud.io/docs/api/#historical-prices

You can use the /previous endpoint to fetch just yesterday price to fill in the gaps once you've loaded history. https://iexcloud.io/docs/api/#previous-day-prices

**Comment by sidlani** [comment]
Lohisoftware, how are you planning to adjust your historical data for splits/dividends?

**Comment by lohisoftware** [comment]
@joshuablackburn-iex Absolutely fantastic, thank you very much! This makes me really happy.

**Comment by lohisoftware** [comment]
@sidlani That's a good question. Yes, I do have some code that detects splits. You are correct that in that case I should adjust the historical data.

**Comment by JPayne3** [comment]
To download the last nn days of data I use this URL:
https://cloud.iexapis.com/beta/stock/market/batch?symbols=[symbols]&types=chart&range=[1m]&chartLast=[nn]&filter=date,open,high,low,close,volume&token=pk_xxxxxxxxxxx

Set the nn variable as needed and make sure the range specified is long enough to contain nn days.
(Figure 20 days per month, use no more than 100 symbols , and note the capital L in chartLast!)
