### ISSUE TITLE
New API IEX Cloud: Major Index Support

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#701]
## Summary

Does new API support the major indexes? If not, when will you support them? What are the symbols?

**Comment by joshuablackburn-iex** [comment]
It is difficult to support indexes in an API product. Each is controlled by a single company that charges very high fees to each consumer, plus additional fees if the data is displayed to anyone. It also requires a contract directly with the index provider. We recommend using the ETF for each. DIA, SPY, IWM

**Comment by bishinew** [comment]
I notice that. Is it possible to have four decimal points for DIA, SPY etc?

Currently DIA: 259.21 times 100  = 25921

If you can provide last price as 259.2107 times 100 = 25921.07, it looks better.

Just asking if possible.

Thanks
