### ISSUE TITLE
Values divided by 10

### ISSUE THREAD

**Issue by Ahrnov** [iexg/IEX-API#704]
## Summary
For ABIL, values seem to have been divided by 10 up to 2018/03/23.

### Date/time of issue
2019/02/22

### API URL
https://api.iextrading.com/1.0/stock/ABIL/chart/2y

### What you expected to happen / What actually happened
With date 2017-02-21, close is 2.9, Google says around 28 -> divided by 10
With date 2018-03-21, close is 0.390048, Google says 3.90 -> divided by 10
2 days later, 2018-03-23, close is 3.65, Google says 3.65 -> OK
With date 2019-02-21, close is 1.9435, Google says 1.94 -> OK

Same behavior for 5 year request.

### Others
{
        "change": 0.0511,
        "changeOverTime": 0,
        "changePercent": 1.794,
        "close": 2.9,
        "date": "2017-02-21",
        "high": 2.92,
        "label": "Feb 21, 17",
        "low": 2.85,
        "open": 2.89,
        "unadjustedVolume": 5081,
        "volume": 5081,
        "vwap": 2.8788
    }
{
        "change": -0.008152,
        "changeOverTime": -0.8655006896551724,
        "changePercent": -2.047,
        "close": 0.390048,
        "date": "2018-03-21",
        "high": 0.4087,
        "label": "Mar 21, 18",
        "low": 0.39,
        "open": 0.4029,
        "unadjustedVolume": 45215,
        "volume": 45215,
        "vwap": 0.394618
    }
{
        "change": 3.31,
        "changeOverTime": 0.25862068965517243,
        "changePercent": 973.529,
        "close": 3.65,
        "date": "2018-03-23",
        "high": 5.9499,
        "label": "Mar 23, 18",
        "low": 2.64,
        "open": 2.64,
        "unadjustedVolume": 300089,
        "volume": 300089,
        "vwap": 4.2549
    }
{
        "change": 0.0343,
        "changeOverTime": -0.3298275862068965,
        "changePercent": 1.797,
        "close": 1.9435,
        "date": "2019-02-21",
        "high": 1.9799,
        "label": "Feb 21",
        "low": 1.87,
        "open": 1.96,
        "unadjustedVolume": 97990,
        "volume": 97990,
        "vwap": 1.9156
    }

**Comment by joshuablackburn-iex** [comment]
The company had a 1 for 10 stock split. Data was adjusted for the split.

**Comment by Ahrnov** [comment]
Many thanks for that information, but the following request gives nothing (JSON is []):
https://api.iextrading.com/1.0/stock/ABIL/splits/2y
