### ISSUE TITLE
iex cloud Key Stats missing Beta, returnOnEquity, returnOnAssets, profitMargin, and so on 

### ISSUE THREAD

**Issue by datamelon** [iexg/IEX-API#705]
## Summary

Hi,

Key Stats missing many fields in IEX cloud such as Beta, returnOnEquity, returnOnAssets, profitMargin, priceToSales, priceToBook, institutionPercent and so on. Are you going to add those fields? Or where can I find these data? Thanks.

**Comment by joshuablackburn-iex** [comment]
We will not have 100% parity with the IEX v1 API. Everything will still be available, but may be on different endpoints. Based on the weight of data, it would make /stats too heavy if we include all of these stats.

**Comment by datamelon** [comment]
We prefer to keep the old way. It is not heavy to include these stats in one API call. Otherwise we have to modify many code to meet the new API. Could you please keep the existing format as much as possible? It is very reliable, and has been tested for long time. Thanks!

**Comment by datamelon** [comment]
Could you please maintain a consistent format? It will save a developer lots of work. Thank you very much!
