### ISSUE TITLE
Should we use Secret Token or Publishable Token in the following case?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#706]
For my use case, we intent to consume https://cloud.iexapis.com/beta/stock/mcd/dividends/5y?token=XXX from our Android app.

For `XXX`, should we replace it with Secret Token, or Publishable Token?

We tested both. Both works.

We look at https://iexcloud.io/docs/api/#api-reference

> Publishable API tokens are meant solely to identify your account with IEX Cloud, they aren’t secret. They can be published in places like your website JavaScript code, or in an iPhone or Android app.
> 
> Secret API tokens should be kept confidential and only stored on your own servers. Your account’s secret API token can perform any API request to IEX Cloud.

I guess for Android app, we should use Publishable Token?

But, this isn't clear for us still. We don't see any difference between Publishable Token and Secret Token? The only difference we notice, is that besides Secret Token, there's a Regenerate button in API console UI.

**Comment by joshuablackburn-iex** [comment]
You should **only** use publishable token in the app. Your secret token has permission to change your account, including billing. The secret token should be kept secret.
