### ISSUE TITLE
several questions regarding your APIs

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#707]
Hi

1. I understand correctly that IEX API will not longer be available and instead I should use the new IEX cloud API?

2. What international stocks exchange do you support at the moment? I read that you're going to add some more, any expectations on when?

3. I failed to retrieve dividends history for BDCL, SPY, SDY. is there such information for ETF/mutual funds?

4. 5 years back to dividend history, will this limitation be removed?

5. I found how to retrieve "real time" Price, dividend history, price history but I've missed the fundamentals: PE, FPE, payout ratio, 1/3/5/10 years growth and more. How can I get them?

Thanks

**Comment by joshuablackburn-iex** [comment]
The IEX API will sunset all non-IEX data in June 2019. Data provided by IEX will continue to be offered in the IEX API for free. IEX Cloud will be the platform for 3rd party data going forward.

International EOD prices are in development now. We are hoping to provide this in the next week or two. 

We will look into ETF/mutual fund dividends, and we are also working with our provider to expand dividend history.

The /stats endpoint has many of these data points. We are working on an advanced stats endpoint to provide more data without increasing the data weight of the existing stats. https://iexcloud.io/docs/api/#key-stats

**Comment by Amosss** [comment]
I understand correctly that international dividends history and ETF/MF data (price/dividends history) are not to be expected soon?

Thanks

**Comment by joshuablackburn-iex** [comment]
We do have mutual fund price history currently.
