### ISSUE TITLE
Could I get Nasdaq or SP500 index in IEX cloud's data?

### ISSUE THREAD

**Issue by bokuno** [iexg/IEX-API#708]
## Summary

For some indexes such as Nasdaq S&P500 or Dow Jones(DJIA) , I could not get data from IEX cloud's data. Are they included in IEX cloud?

### API URL

https://cloud.iexapis.com/beta/stock/{symbol}/quote?token=YOUR_TOKEN_HERE

### What you expected to happen
Could get Nasdaq S&P500 DJIA index data.

### What actually happened
Could not get Nasdaq S&P500 DJIA index data.

**Comment by evancarter-iex** [comment]
We won't be able to host index data in the near term. This data is essentially monopolized, so pricing is very high and requires a direct contract between each consumer and the index provider regardless of who actually supplies the data. The major index providers charge over $10k a year for delayed data, and that isn’t a price point we want to work with for our initial users.


________________________________

**Comment by bokuno** [comment]
Thank you very much.
