### ISSUE TITLE
Where do I find beta, exDividendDate, returnOnEquity, returnOnAssets, profitMargin, priceToSales, priceToBook, institutionPercent, insiderPercent from the old /stats/ endpoint?

### ISSUE THREAD

**Issue by sidlani** [iexg/IEX-API#709]
## Summary
Where do I find beta, exDividendDate, returnOnEquity, returnOnAssets, profitMargin, priceToSales, priceToBook, institutionPercent, insiderPercent from the old /stats/ endpoint?

**Comment by bishinew** [comment]
Please make the IEX Cloud New API Stats endpoint the same as old API. At lease add Ex-Div Date and beta etc. Thanks.

**Comment by evancarter-iex** [comment]
https://iexcloud.io/docs/api/#advanced-stats This is fixed now.
