### ISSUE TITLE
Quote + Historical batch call with chartCloseOnly=true filters quote incorrectly

### ISSUE THREAD

**Issue by aokellermann** [iexg/IEX-API#710]
## Summary
When issuing a batch call to multiple symbols with quote and chart endpoint, using chartCloseOnly=true parameter filters all data in quote except "close" in all but first symbol in list.

## Details
In the below example call, all the data for the first symbol (TSLA) is returned correctly. However, for all the others, the quote data ONLY has "close". The chart data is correct. This bug is present in both sandbox and cloud.

### Date/time of issue
n/a

### API URL
https://sandbox.iexapis.com/beta/stock/market/batch?types=quote,chart&range=1m&chartCloseOnly=true&symbols=TSLA,AMD,AAPL&token=TOKEN

### What you expected to happen
Full quote data for all symbols

### What actually happened
Only close in quote for all but first symbol

### Other Information (sample code, links, etc.)
With parameter:
https://sandbox.iexapis.com/beta/stock/market/batch?types=quote,chart&range=1m&chartCloseOnly=true&symbols=TSLA,AMD,AAPL&token=TOKEN

{"TSLA":{"quote":{"symbol":"TSLA","companyName":"Tesla Inc","calculationPrice":"close","open":294.85,"openTime":1551104211044,"close":307.49,"closeTime":1562088582678,"high":null,"low":null,"latestPrice":297.51,"latestSource":"Close","latestTime":"February 22, 2019","latestUpdate":1582882142773,"latestVolume":0,"iexRealtimePrice":null,"iexRealtimeSize":null,"iexLastUpdated":null,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":299,"extendedChange":0.3,"extendedChangePercent":0.00101,"extendedPriceTime":1573927420071,"previousClose":291.51,"change":3.49,"changePercent":0.0122,"iexMarketPercent":null,"iexVolume":null,"avgTotalVolume":7621009,"iexBidPrice":null,"iexBidSize":null,"iexAskPrice":null,"iexAskSize":null,"marketCap":51078828972,"week52High":406.3,"week52Low":249.78,"ytdChange":-0.03816399521120338},"chart":[{"date":"2019-01-23","close":295.69,"volume":12548846},{"date":"2019-01-24","close":294.64,"volume":8387380},{"date":"2019-01-25","close":309.68,"volume":7381991},{"date":"2019-01-28","close":310.55,"volume":6674963},{"date":"2019-01-29","close":307.64,"volume":4831849},{"date":"2019-01-30","close":314.88,"volume":11607423},{"date":"2019-01-31","close":307.78,"volume":12622430},{"date":"2019-02-01","close":321.19,"volume":7600393},{"date":"2019-02-04","close":322.37,"volume":7511882},{"date":"2019-02-05","close":330.51,"volume":6791336},{"date":"2019-02-06","close":319.21,"volume":5147432},{"date":"2019-02-07","close":321.31,"volume":6711676},{"date":"2019-02-08","close":320.9,"volume":5855456},{"date":"2019-02-11","close":317.77,"volume":7390131},{"date":"2019-02-12","close":326.26,"volume":5674924},{"date":"2019-02-13","close":319.05,"volume":5269747},{"date":"2019-02-14","close":306.91,"volume":5434888},{"date":"2019-02-15","close":314.02,"volume":3960381},{"date":"2019-02-19","close":316.96,"volume":4264186},{"date":"2019-02-20","close":311.2,"volume":7403905},{"date":"2019-02-21","close":296.89,"volume":9062370},{"date":"2019-02-22","close":308.05,"volume":5891385}]},"AMD":{"quote":{"close":24.77},"chart":[{"date":"2019-01-23","close":20.8,"volume":81480705},{"date":"2019-01-24","close":21.13,"volume":101367240},{"date":"2019-01-25","close":22.17,"volume":114574374},{"date":"2019-01-28","close":20.64,"volume":141132743},{"date":"2019-01-29","close":19.37,"volume":131337263},{"date":"2019-01-30","close":24.18,"volume":213906234},{"date":"2019-01-31","close":25.31,"volume":185986624},{"date":"2019-02-01","close":24.73,"volume":107951020},{"date":"2019-02-04","close":24.22,"volume":73635773},{"date":"2019-02-05","close":23.69,"volume":126477829},{"date":"2019-02-06","close":24.42,"volume":79765730},{"date":"2019-02-07","close":23.63,"volume":87662007},{"date":"2019-02-08","close":23.95,"volume":78421168},{"date":"2019-02-11","close":23.62,"volume":62143201},{"date":"2019-02-12","close":23.66,"volume":67819547},{"date":"2019-02-13","close":23.33,"volume":59607610},{"date":"2019-02-14","close":24.14,"volume":65863972},{"date":"2019-02-15","close":24.17,"volume":81813569},{"date":"2019-02-19","close":24.43,"volume":60361991},{"date":"2019-02-20","close":25.14,"volume":58849111},{"date":"2019-02-21","close":24.62,"volume":50336203},{"date":"2019-02-22","close":24.85,"volume":55040543}]},"AAPL":{"quote":{"close":175.67},"chart":[{"date":"2019-01-23","close":156.07,"volume":23369965},{"date":"2019-01-24","close":154.8,"volume":26559140},{"date":"2019-01-25","close":159.08,"volume":33684147},{"date":"2019-01-28","close":163.2,"volume":26573475},{"date":"2019-01-29","close":159.18,"volume":43080155},{"date":"2019-01-30","close":170.01,"volume":62584591},{"date":"2019-01-31","close":171.69,"volume":42228188},{"date":"2019-02-01","close":166.56,"volume":32811496},{"date":"2019-02-04","close":172.62,"volume":31644569},{"date":"2019-02-05","close":176.58,"volume":36181518},{"date":"2019-02-06","close":174.27,"volume":28703507},{"date":"2019-02-07","close":171.75,"volume":32581691},{"date":"2019-02-08","close":174.45,"volume":24089720},{"date":"2019-02-11","close":173.78,"volume":21572673},{"date":"2019-02-12","close":171.2,"volume":23364240},{"date":"2019-02-13","close":177.33,"volume":22586096},{"date":"2019-02-14","close":171.7,"volume":22417781},{"date":"2019-02-15","close":173.29,"volume":25089229},{"date":"2019-02-19","close":179.26,"volume":19820856},{"date":"2019-02-20","close":176.18,"volume":26344839},{"date":"2019-02-21","close":178.77,"volume":17464755},{"date":"2019-02-22","close":178.8,"volume":19070593}]}}

Without parameter:
https://sandbox.iexapis.com/beta/stock/market/batch?types=quote,chart&range=1m&symbols=TSLA,AMD,AAPL&token=TOKEN

{"TSLA":{"quote":{"symbol":"TSLA","companyName":"Tesla Inc","calculationPrice":"close","open":296.29,"openTime":1627673444473,"close":304.04,"closeTime":1574287575063,"high":null,"low":null,"latestPrice":305.22,"latestSource":"Close","latestTime":"February 22, 2019","latestUpdate":1612092924460,"latestVolume":0,"iexRealtimePrice":null,"iexRealtimeSize":null,"iexLastUpdated":null,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":303,"extendedChange":0.3,"extendedChangePercent":0.00099,"extendedPriceTime":1627526591244,"previousClose":304.5,"change":3.49,"changePercent":0.01202,"iexMarketPercent":null,"iexVolume":null,"avgTotalVolume":7481086,"iexBidPrice":null,"iexBidSize":null,"iexAskPrice":null,"iexAskSize":null,"marketCap":52841136270,"week52High":400.95,"week52Low":251.68,"ytdChange":-0.039254760191721444},"chart":[{"date":"2019-01-23","open":295.6,"close":295.74,"high":308.6,"low":283.56,"volume":12675986,"uOpen":293.4,"uClose":297.48,"uHigh":306.4,"uLow":288.79,"uVolume":12878111,"change":0,"changePercent":0,"label":"Jan 23","changeOverTime":0},{"date":"2019-01-24","open":288.2,"close":299.4,"high":305.78,"low":288.09,"volume":8284409,"uOpen":283.18,"uClose":292.64,"uHigh":298.76,"uLow":289.61,"uVolume":8325015,"change":4.11,"changePercent":1.3855,"label":"Jan 24","changeOverTime":0.0142},{"date":"2019-01-25","open":302.31,"close":304.32,"high":310.95,"low":294.91,"volume":7434124,"uOpen":307.59,"uClose":301.08,"uHigh":310.16,"uLow":291.43,"uVolume":7462156,"change":5.72,"changePercent":1.973,"label":"Jan 25","changeOverTime":0.033981},{"date":"2019-01-28","open":297.18,"close":298.06,"high":301.77,"low":292.62,"volume":6706292,"uOpen":297.45,"uClose":303.72,"uHigh":302.23,"uLow":295.01,"uVolume":6692339,"change":-0.67,"changePercent":-0.2326,"label":"Jan 28","changeOverTime":0.031946},{"date":"2019-01-29","open":307.91,"close":299.08,"high":313.42,"low":295.4,"volume":4792189,"uOpen":295.3,"uClose":300.69,"uHigh":306.14,"uLow":293,"uVolume":4737325,"change":1.13,"changePercent":0.3694,"label":"Jan 29","changeOverTime":0.03441},{"date":"2019-01-30","open":303.75,"close":313.85,"high":320,"low":310.01,"volume":11482583,"uOpen":304.17,"uClose":312.79,"uHigh":316,"uLow":312.23,"uVolume":11461159,"change":11.53,"changePercent":3.8432,"label":"Jan 30","changeOverTime":0.075196},{"date":"2019-01-31","open":313,"close":321.4,"high":319.19,"low":295,"volume":12906224,"uOpen":304,"uClose":319.92,"uHigh":316.09,"uLow":307,"uVolume":12588339,"change":-1.79,"changePercent":-0.5861,"label":"Jan 31","changeOverTime":0.069984},{"date":"2019-02-01","open":317.82,"close":318.21,"high":319.6,"low":303.5,"volume":7287700,"uOpen":313.96,"uClose":314.36,"uHigh":320,"uLow":316.2,"uVolume":7521273,"change":5.2,"changePercent":1.75,"label":"Feb 1","changeOverTime":0.088993},{"date":"2019-02-04","open":324.45,"close":313.35,"high":329.3,"low":314.27,"volume":7634865,"uOpen":314.47,"uClose":328.48,"uHigh":317.8,"uLow":307.29,"uVolume":7381262,"change":0.69,"changePercent":0.2189,"label":"Feb 4","changeOverTime":0.089623},{"date":"2019-02-05","open":314.73,"close":322.62,"high":328.23,"low":315.15,"volume":6803340,"uOpen":320.18,"uClose":333.84,"uHigh":326.64,"uLow":319,"uVolume":7073404,"change":8.69,"changePercent":2.7084,"label":"Feb 5","changeOverTime":0.122168},{"date":"2019-02-06","open":325.63,"close":324.36,"high":329.72,"low":327.93,"volume":5118565,"uOpen":326.71,"uClose":328.24,"uHigh":333.44,"uLow":326.94,"uVolume":5128984,"change":-4.23,"changePercent":-1.3049,"label":"Feb 6","changeOverTime":0.107036},{"date":"2019-02-07","open":326.3,"close":314.98,"high":329,"low":316,"volume":6589161,"uOpen":318.2,"uClose":313.8,"uHigh":326,"uLow":314,"uVolume":6699056,"change":-9.9,"changePercent":-3.139,"label":"Feb 7","changeOverTime":0.071577},{"date":"2019-02-08","open":315.61,"close":313.9,"high":308.9,"low":306.9,"volume":5947014,"uOpen":317.11,"uClose":308.8,"uHigh":317.91,"uLow":301.2,"uVolume":5852042,"change":-1.74,"changePercent":-0.5667,"label":"Feb 8","changeOverTime":0.066173},{"date":"2019-02-11","open":325,"close":328.48,"high":327.9,"low":314.8,"volume":7135293,"uOpen":323.7,"uClose":312.85,"uHigh":329,"uLow":315.9,"uVolume":7202275,"change":7.07,"changePercent":2.406,"label":"Feb 11","changeOverTime":0.090016},{"date":"2019-02-12","open":317.9,"close":324.36,"high":332.09,"low":319.13,"volume":5717249,"uOpen":330.1,"uClose":324.71,"uHigh":323.6,"uLow":323.78,"uVolume":5704327,"change":-1.04,"changePercent":-0.3348,"label":"Feb 12","changeOverTime":0.087293},{"date":"2019-02-13","open":317.58,"close":312.37,"high":314.4,"low":314.45,"volume":5255234,"uOpen":315.2,"uClose":315.41,"uHigh":325.49,"uLow":318.69,"uVolume":5289553,"change":-3.68,"changePercent":-1.2051,"label":"Feb 13","changeOverTime":0.07356},{"date":"2019-02-14","open":318.45,"close":314.32,"high":315.43,"low":307,"volume":5393273,"uOpen":305.1,"uClose":309.39,"uHigh":309.7,"uLow":312,"uVolume":5272586,"change":-4.6,"changePercent":-1.4891,"label":"Feb 14","changeOverTime":0.058499},{"date":"2019-02-15","open":319.1,"close":323.18,"high":315,"low":309.1,"volume":4085775,"uOpen":308.1,"uClose":313.42,"uHigh":321,"uLow":305.2,"uVolume":3915565,"change":4.29,"changePercent":1.399,"label":"Feb 15","changeOverTime":0.072387},{"date":"2019-02-19","open":315.84,"close":311.98,"high":323.14,"low":316.04,"volume":4193233,"uOpen":321.4,"uClose":317.26,"uHigh":321.66,"uLow":314.02,"uVolume":4353143,"change":-2.24,"changePercent":-0.7396,"label":"Feb 19","changeOverTime":0.065794},{"date":"2019-02-20","open":316.25,"close":307.5,"high":315.5,"low":309,"volume":7365962,"uOpen":319.26,"uClose":304.98,"uHigh":309.5,"uLow":311,"uVolume":7223699,"change":-3.22,"changePercent":-1.0155,"label":"Feb 20","changeOverTime":0.052335},{"date":"2019-02-21","open":308.59,"close":300.27,"high":308.2,"low":303.3,"volume":9070795,"uOpen":311.96,"uClose":300.77,"uHigh":318.1,"uLow":298.3,"uVolume":8955913,"change":-11.47,"changePercent":-3.7542,"label":"Feb 21","changeOverTime":0.013095},{"date":"2019-02-22","open":300.84,"close":297.75,"high":301.7,"low":296.7,"volume":5820288,"uOpen":308.8,"uClose":295.87,"uHigh":302.8,"uLow":294.5,"uVolume":5781820,"change":3.52,"changePercent":1.21,"label":"Feb 22","changeOverTime":0.025985}]},"AMD":{"quote":{"symbol":"AMD","companyName":"Advanced Micro Devices, Inc.","calculationPrice":"close","open":24.61,"openTime":1584503666271,"close":25.33,"closeTime":1569973079030,"high":null,"low":null,"latestPrice":25,"latestSource":"Close","latestTime":"February 22, 2019","latestUpdate":1560625898552,"latestVolume":0,"iexRealtimePrice":null,"iexRealtimeSize":null,"iexLastUpdated":null,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":25.2,"extendedChange":0.14,"extendedChangePercent":0.00587,"extendedPriceTime":1627722818305,"previousClose":24.77,"change":0.45,"changePercent":0.01927,"iexMarketPercent":null,"iexVolume":null,"avgTotalVolume":90099752,"iexBidPrice":null,"iexBidSize":null,"iexAskPrice":null,"iexAskSize":null,"marketCap":24553071989,"week52High":34.4,"week52Low":9.13,"ytdChange":0.31266},"chart":[{"date":"2019-01-23","open":20.26,"close":19.9,"high":20.65,"low":19.58,"volume":79298579,"uOpen":20.47,"uClose":20.1,"uHigh":20.64,"uLow":19.6,"uVolume":79871612,"change":0,"changePercent":0,"label":"Jan 23","changeOverTime":0},{"date":"2019-01-24","open":20.08,"close":21.76,"high":21.76,"low":20.31,"volume":100016822,"uOpen":20.89,"uClose":21.83,"uHigh":21.52,"uLow":20.89,"uVolume":97489523,"change":1.08,"changePercent":5.458,"label":"Jan 24","changeOverTime":0.05404},{"date":"2019-01-25","open":21.45,"close":22.96,"high":22.25,"low":21.3,"volume":115848611,"uOpen":21.19,"uClose":22.08,"uHigh":22.52,"uLow":20.97,"uVolume":113596113,"change":1.13,"changePercent":5.3678,"label":"Jan 25","changeOverTime":0.112548},{"date":"2019-01-28","open":20.65,"close":20.67,"high":21.01,"low":20.3,"volume":139475212,"uOpen":20.93,"uClose":20.24,"uHigh":21.02,"uLow":20.58,"uVolume":138334041,"change":-1.78,"changePercent":-8.152,"label":"Jan 28","changeOverTime":0.019415},{"date":"2019-01-29","open":20.39,"close":19.8,"high":20.81,"low":19.08,"volume":132589576,"uOpen":20.73,"uClose":20.07,"uHigh":20.83,"uLow":19.82,"uVolume":134222671,"change":-0.97,"changePercent":-4.6301,"label":"Jan 29","changeOverTime":-0.027963},{"date":"2019-01-30","open":22.05,"close":23.63,"high":24.23,"low":21.46,"volume":215188933,"uOpen":22.33,"uClose":23.21,"uHigh":23.3,"uLow":22.03,"uVolume":212966860,"change":3.86,"changePercent":20.9452,"label":"Jan 30","changeOverTime":0.169499},{"date":"2019-01-31","open":24.14,"close":24.9,"high":26.27,"low":23.15,"volume":187993389,"uOpen":23.54,"uClose":24.76,"uHigh":26.29,"uLow":23.44,"uVolume":183118145,"change":1.38,"changePercent":5.8763,"label":"Jan 31","changeOverTime":0.236328},{"date":"2019-02-01","open":25.63,"close":25.17,"high":25.96,"low":24.48,"volume":108465017,"uOpen":25.55,"uClose":25.27,"uHigh":25.8,"uLow":25.14,"uVolume":107819767,"change":0.1,"changePercent":0.4246,"label":"Feb 1","changeOverTime":0.2463},{"date":"2019-02-04","open":25.51,"close":24.55,"high":24.94,"low":24.68,"volume":72995671,"uOpen":25.38,"uClose":24.24,"uHigh":25.47,"uLow":25.01,"uVolume":71574652,"change":-0.38,"changePercent":-1.558,"label":"Feb 4","changeOverTime":0.228796},{"date":"2019-02-05","open":23.67,"close":24.01,"high":24.95,"low":23.52,"volume":127233199,"uOpen":23.79,"uClose":23.61,"uHigh":23.98,"uLow":23.47,"uVolume":124192166,"change":-0.85,"changePercent":-3.4002,"label":"Feb 5","changeOverTime":0.181682},{"date":"2019-02-06","open":24.6,"close":23.66,"high":24.97,"low":24.02,"volume":81636435,"uOpen":24.76,"uClose":24.03,"uHigh":25.14,"uLow":23.71,"uVolume":82435265,"change":-0.05,"changePercent":-0.2155,"label":"Feb 6","changeOverTime":0.181471},{"date":"2019-02-07","open":24.12,"close":23.75,"high":23.95,"low":23.34,"volume":87988950,"uOpen":23.02,"uClose":23.62,"uHigh":24.07,"uLow":22.68,"uVolume":86851920,"change":-0.62,"changePercent":-2.6106,"label":"Feb 7","changeOverTime":0.150633},{"date":"2019-02-08","open":22.73,"close":23.81,"high":23.36,"low":22.57,"volume":78485884,"uOpen":22.51,"uClose":23.69,"uHigh":24.33,"uLow":22.38,"uVolume":79198166,"change":0.39,"changePercent":1.7346,"label":"Feb 8","changeOverTime":0.165735},{"date":"2019-02-11","open":23.91,"close":23.53,"high":23.35,"low":23.25,"volume":61684842,"uOpen":23.98,"uClose":23.89,"uHigh":24.06,"uLow":23.76,"uVolume":61954447,"change":-0.09,"changePercent":-0.4077,"label":"Feb 11","changeOverTime":0.164189},{"date":"2019-02-12","open":24.4,"close":23.57,"high":24.15,"low":23.4,"volume":68884140,"uOpen":24.27,"uClose":23.55,"uHigh":24.15,"uLow":23.51,"uVolume":69858427,"change":-0.14,"changePercent":-0.6141,"label":"Feb 12","changeOverTime":0.159406},{"date":"2019-02-13","open":23.12,"close":23.68,"high":24.08,"low":23.05,"volume":59219782,"uOpen":23.91,"uClose":23.4,"uHigh":23.83,"uLow":23.75,"uVolume":58205976,"change":0.03,"changePercent":0.135,"label":"Feb 13","changeOverTime":0.15984},{"date":"2019-02-14","open":23.77,"close":23.63,"high":23.41,"low":23.25,"volume":64516378,"uOpen":23.03,"uClose":23.77,"uHigh":24.32,"uLow":23.26,"uVolume":64739342,"change":0.29,"changePercent":1.2601,"label":"Feb 14","changeOverTime":0.172902},{"date":"2019-02-15","open":24.33,"close":24.07,"high":24.75,"low":23.8,"volume":80072976,"uOpen":23.58,"uClose":24.07,"uHigh":24.7,"uLow":23.9,"uVolume":82281558,"change":0.57,"changePercent":2.4451,"label":"Feb 15","changeOverTime":0.19827},{"date":"2019-02-19","open":23.83,"close":24.42,"high":25.26,"low":24.77,"volume":57619920,"uOpen":24.54,"uClose":24,"uHigh":25.44,"uLow":24.01,"uVolume":59544897,"change":0.28,"changePercent":1.1596,"label":"Feb 19","changeOverTime":0.217167},{"date":"2019-02-20","open":24.65,"close":25.07,"high":25.25,"low":24.6,"volume":59934468,"uOpen":24.9,"uClose":25.04,"uHigh":24.53,"uLow":24.9,"uVolume":59671480,"change":0,"changePercent":0,"label":"Feb 20","changeOverTime":0.215052},{"date":"2019-02-21","open":24.87,"close":24.23,"high":25.06,"low":24.57,"volume":52037078,"uOpen":24.71,"uClose":24.72,"uHigh":25.11,"uLow":23.91,"uVolume":51969093,"change":-0.03,"changePercent":-0.1286,"label":"Feb 21","changeOverTime":0.21539},{"date":"2019-02-22","open":24.22,"close":25.54,"high":24.9,"low":24.31,"volume":53405192,"uOpen":24.22,"uClose":24.67,"uHigh":24.86,"uLow":24.99,"uVolume":54861513,"change":0.45,"changePercent":1.869,"label":"Feb 22","changeOverTime":0.239493}]},"AAPL":{"quote":{"symbol":"AAPL","companyName":"Apple Inc.","calculationPrice":"close","open":175.57,"openTime":1574707769198,"close":175.74,"closeTime":1558825722172,"high":null,"low":null,"latestPrice":175.1,"latestSource":"Close","latestTime":"February 22, 2019","latestUpdate":1613358206906,"latestVolume":0,"iexRealtimePrice":null,"iexRealtimeSize":null,"iexLastUpdated":null,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":178.63,"extendedChange":-0.21,"extendedChangePercent":-0.00126,"extendedPriceTime":1551779406802,"previousClose":178.55,"change":1.97,"changePercent":0.01159,"iexMarketPercent":null,"iexVolume":null,"avgTotalVolume":29545072,"iexBidPrice":null,"iexBidSize":null,"iexAskPrice":null,"iexAskSize":null,"marketCap":838573330250,"week52High":241.33,"week52Low":147,"ytdChange":0.109117},"chart":[{"date":"2019-01-23","open":161.19,"close":159.82,"high":156.55,"low":155.7,"volume":23256219,"uOpen":154.33,"uClose":156.58,"uHigh":155.56,"uLow":155.9,"uVolume":23273372,"change":0,"changePercent":0,"label":"Jan 23","changeOverTime":0},{"date":"2019-01-24","open":157.53,"close":154.3,"high":160.6,"low":156.24,"volume":26637531,"uOpen":158.34,"uClose":160,"uHigh":159.17,"uLow":156.77,"uVolume":25724329,"change":-1.25,"changePercent":-0.798,"label":"Jan 24","changeOverTime":-0.008204},{"date":"2019-01-25","open":160.62,"close":161.28,"high":158.38,"low":155.52,"volume":33913532,"uOpen":162.63,"uClose":159.53,"uHigh":162.51,"uLow":154.65,"uVolume":33831201,"change":5.19,"changePercent":3.3705,"label":"Jan 25","changeOverTime":0.025412},{"date":"2019-01-28","open":161.48,"close":157.8,"high":163.09,"low":155.87,"volume":27327024,"uOpen":163.5,"uClose":162.6,"uHigh":163.15,"uLow":156.59,"uVolume":26225346,"change":-1.49,"changePercent":-0.9627,"label":"Jan 28","changeOverTime":0.01554},{"date":"2019-01-29","open":159.55,"close":155.31,"high":165.9,"low":159.92,"volume":43532031,"uOpen":162.88,"uClose":160.33,"uHigh":159.14,"uLow":155.02,"uVolume":43022734,"change":-1.68,"changePercent":-1.0657,"label":"Jan 29","changeOverTime":0.005146},{"date":"2019-01-30","open":165.71,"close":165.43,"high":169.84,"low":162.15,"volume":61263638,"uOpen":168.25,"uClose":171.4,"uHigh":168.18,"uLow":167.74,"uVolume":63788725,"change":10.86,"changePercent":6.9783,"label":"Jan 30","changeOverTime":0.07377},{"date":"2019-01-31","open":173.98,"close":168.29,"high":177,"low":171.56,"volume":41790521,"uOpen":170.13,"uClose":173.89,"uHigh":171,"uLow":172.53,"uVolume":42167695,"change":1.2,"changePercent":0.7531,"label":"Jan 31","changeOverTime":0.083542},{"date":"2019-02-01","open":172.31,"close":174.74,"high":174.7,"low":172.36,"volume":33344687,"uOpen":169.73,"uClose":168.24,"uHigh":173.56,"uLow":171.72,"uVolume":33345839,"change":0.08,"changePercent":0.0496,"label":"Feb 1","changeOverTime":0.083489},{"date":"2019-02-04","open":170.38,"close":175.76,"high":177.73,"low":171.02,"volume":32492102,"uOpen":170.14,"uClose":173.72,"uHigh":173.6,"uLow":171.09,"uVolume":31708144,"change":4.73,"changePercent":2.94,"label":"Feb 4","changeOverTime":0.116274},{"date":"2019-02-05","open":175.71,"close":181.29,"high":182.89,"low":175.93,"volume":36777752,"uOpen":175.67,"uClose":175.27,"uHigh":180.54,"uLow":179.88,"uVolume":37610978,"change":3.04,"changePercent":1.7178,"label":"Feb 5","changeOverTime":0.137593},{"date":"2019-02-06","open":175.13,"close":177.07,"high":179.97,"low":172.97,"volume":28308540,"uOpen":175.39,"uClose":181.97,"uHigh":183.56,"uLow":173.92,"uVolume":28696964,"change":0.06,"changePercent":0.0352,"label":"Feb 6","changeOverTime":0.135566},{"date":"2019-02-07","open":174.4,"close":176.21,"high":174.54,"low":176.55,"volume":32824774,"uOpen":177.4,"uClose":178.97,"uHigh":179.89,"uLow":173.25,"uVolume":33303695,"change":-3.4,"changePercent":-1.9852,"label":"Feb 7","changeOverTime":0.112345},{"date":"2019-02-08","open":169.42,"close":178.5,"high":172.32,"low":175.33,"volume":24554772,"uOpen":173.45,"uClose":175.49,"uHigh":171.35,"uLow":169.47,"uVolume":24279824,"change":-0.55,"changePercent":-0.317,"label":"Feb 8","changeOverTime":0.10898},{"date":"2019-02-11","open":172.96,"close":173.89,"high":175.45,"low":173.58,"volume":21227008,"uOpen":179.19,"uClose":177.19,"uHigh":172.89,"uLow":177.68,"uVolume":21034830,"change":-1,"changePercent":-0.5853,"label":"Feb 11","changeOverTime":0.101943},{"date":"2019-02-12","open":177.9,"close":171.05,"high":180,"low":177.3,"volume":22651060,"uOpen":173.9,"uClose":171.63,"uHigh":174,"uLow":171.7,"uVolume":23309379,"change":1.49,"changePercent":0.8688,"label":"Feb 12","changeOverTime":0.112415},{"date":"2019-02-13","open":178.4,"close":175.9,"high":179.82,"low":177.62,"volume":22651154,"uOpen":175.28,"uClose":170.88,"uHigh":177.42,"uLow":177.18,"uVolume":23517143,"change":-0.72,"changePercent":-0.4217,"label":"Feb 13","changeOverTime":0.106692},{"date":"2019-02-14","open":173.44,"close":171.9,"high":177.79,"low":175.97,"volume":22831480,"uOpen":178.12,"uClose":171.2,"uHigh":172.29,"uLow":169.64,"uVolume":22870813,"change":0.65,"changePercent":0.3744,"label":"Feb 14","changeOverTime":0.114767},{"date":"2019-02-15","open":179.49,"close":173.02,"high":179.9,"low":171.1,"volume":25855287,"uOpen":176.56,"uClose":176.92,"uHigh":178.5,"uLow":173.82,"uVolume":25384654,"change":-0.38,"changePercent":-0.2304,"label":"Feb 15","changeOverTime":0.109862},{"date":"2019-02-19","open":170.17,"close":173.92,"high":178,"low":172.36,"volume":19712913,"uOpen":175.62,"uClose":175.65,"uHigh":178.38,"uLow":173.6,"uVolume":19273379,"change":0.52,"changePercent":0.3107,"label":"Feb 19","changeOverTime":0.112957},{"date":"2019-02-20","open":173.46,"close":176.84,"high":179.15,"low":175.29,"volume":26687766,"uOpen":174.18,"uClose":172.82,"uHigh":178.35,"uLow":175.58,"uVolume":26577068,"change":1.1,"changePercent":0.6658,"label":"Feb 20","changeOverTime":0.118978},{"date":"2019-02-21","open":175.9,"close":172.92,"high":177.33,"low":173.9,"volume":17385136,"uOpen":177.7,"uClose":175.48,"uHigh":177.77,"uLow":175.4,"uVolume":17376795,"change":-1.01,"changePercent":-0.5837,"label":"Feb 21","changeOverTime":0.113134},{"date":"2019-02-22","open":176.99,"close":176.18,"high":178,"low":174.41,"volume":19799534,"uOpen":177.42,"uClose":177.18,"uHigh":174,"uLow":173.49,"uVolume":18936469,"change":1.95,"changePercent":1.1645,"label":"Feb 22","changeOverTime":0.129861}]}}

**Comment by joshuablackburn-iex** [comment]
This is fixed.
