### ISSUE TITLE
IEX Cloud. How do i read company info in batch

### ISSUE THREAD

**Issue by SorenRamus** [iexg/IEX-API#711]
## Summary
When I try to read company info in batch mode i get an error.

"types" required with a valid value

Seems like company is no longer a valid batch request.
Need a list of valid batch requests then

## Details
Request:
"https://cloud.iexapis.com/BETA/stock/market/batch?symbols=A%2CAA%2CAAC%2CAAL%2CAAMC%2CAAME%2CAAN%2CAAOI%2CAAON%2CAAP%2CAAPL%2CAAT%2CAAU%2CAAWW%2CAAXN%2CAB%2CABBV%2CABC%2CABCB%2CABDC%2CABEO%2CABG%2CABIL%2CABIO%2CABM%2CABMD%2CABR%2CABT%2CABTX%2CABUS%2CAC%2CACA%2CACAD%2CACB%2CACBI%2CACC%2CACCO%2CACER%2CACET%2CACGL%2CACHC%2CACHN%2CACHV%2CACIA%2CACIU%2CACIW%2CACLS%2CACM%2CACMR%2CACN%2CACNB%2CACOR%2CACRE%2CACRS%2CACRX%2CACST%2CACTG%2CACU%2CACY%2CADBE%2CADC%2CADES%2CADI%2CADIL%2CADM%2CADMA%2CADMP%2CADMS%2CADNT%2CADOM%2CADP%2CADRO%2CADS%2CADSK%2CADSW%2CADT%2CADTN%2CADUS%2CADVM%2CADXS%2CAE%2CAEE%2CAEGN%2CAEHR%2CAEIS%2CAEL%2CAEM%2CAEMD%2CAEO%2CAEP%2CAER%2CAERI%2CAES%2CAETI%2CAEY%2CAEYE%2CAEZS%2CAFG%2CAFH%2CAFI&types=company?token=pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
### Date/time of issue
Sun, 24 Feb 2019 11:57:02 GMT

### API URL
See details

### What you expected to happen
I would expect a list of "company" like in the old version 1.0 API

### What actually happened
Error message: "types" required with a valid value
Web Response:
{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Content-Security-Policy: default-src 'self'; child-src 'none'; object-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://js.intercomcdn.com/fonts/ https://fonts.gstatic.com; frame-src 'self' https://js.stripe.com/; img-src 'self' data: https://*.intercomcdn.com https://www.google-analytics.com https://downloads.intercomcdn.com/; connect-src 'self' https://auth.iexcloud.io https://api.iexcloud.io https://api.iexcloud.io https://cloud.iexapis.com wss://iexcloud.io wss://tops.iexcloud.io wss://api.iexcloud.io wss://iexcloud.io https://api-iam.intercom.io/messenger/ https://nexus-websocket-a.intercom.io/ https://nexus-websocket-b.intercom.io/ wss://nexus-websocket-a.intercom.io/ wss://nexus-websocket-b.intercom.io/ https://www.google-analytics.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com/recaptcha/api.js https://www.google-analytics.com https://js.stripe.com/v3/ https://widget.intercom.io/widget/lhos563b https://js.intercomcdn.com/ https://www.googletagmanager.com;
  X-Content-Security-Policy: default-src 'self'; child-src 'none'; object-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://js.intercomcdn.com/fonts/ https://fonts.gstatic.com; frame-src 'self' https://js.stripe.com/; img-src 'self' data: https://*.intercomcdn.com https://www.google-analytics.com https://downloads.intercomcdn.com/; connect-src 'self' https://auth.iexcloud.io https://api.iexcloud.io https://api.iexcloud.io https://cloud.iexapis.com wss://iexcloud.io wss://tops.iexcloud.io wss://api.iexcloud.io wss://iexcloud.io https://api-iam.intercom.io/messenger/ https://nexus-websocket-a.intercom.io/ https://nexus-websocket-b.intercom.io/ wss://nexus-websocket-a.intercom.io/ wss://nexus-websocket-b.intercom.io/ https://www.google-analytics.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com/recaptcha/api.js https://www.google-analytics.com https://js.stripe.com/v3/ https://widget.intercom.io/widget/lhos563b https://js.intercomcdn.com/ https://www.googletagmanager.com;
  Frame-Options: SAMEORIGIN
  X-Frame-Options: SAMEORIGIN
  Strict-Transport-Security: max-age=15768000
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Credentials: true
  Access-Control-Allow-Methods: GET, OPTIONS
  Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
  Date: Sat, 23 Feb 2019 23:57:02 GMT
  Set-Cookie: ctoken=e99d7d1e2b134a0c85abc107bb1c7a99; Max-Age=43200; Path=/; Expires=Sun, 24 Feb 2019 11:57:02 GMT
  Server: nginx
  Content-Type: text/html; charset=utf-8
}}

### Other Information (sample code, links, etc.)

The version 1.0 request that works:
"https://api.iextrading.com/1.0/stock/market/batch?symbols=A%2CAA%2CAABA%2CAAC%2CAAL%2CAAMC%2CAAME%2CAAN%2CAAOI%2CAAON%2CAAP%2CAAPL%2CAAT%2CAAU%2CAAWW%2CAAXN%2CAB%2CABB%2CABBV%2CABC%2CABCB%2CABDC%2CABEO%2CABEV%2CABG%2CABIL%2CABIO%2CABM%2CABMD%2CABR%2CABT%2CABTX%2CABUS%2CAC%2CACA%2CACAD%2CACB%2CACBI%2CACC%2CACCO%2CACER%2CACET%2CACGL%2CACH%2CACHC%2CACHN%2CACHV%2CACIA%2CACIU%2CACIW%2CACLS%2CACM%2CACMR%2CACN%2CACNB%2CACOR%2CACP%2CACRE%2CACRS%2CACRX%2CACST%2CACTG%2CACU%2CACV%2CACY%2CADAP%2CADBE%2CADC%2CADES%2CADI%2CADIL%2CADM%2CADMA%2CADMP%2CADMS%2CADNT%2CADOM%2CADP%2CADRO%2CADS%2CADSK%2CADSW%2CADT%2CADTN%2CADUS%2CADVM%2CADX%2CADXS%2CAE%2CAEE%2CAEF%2CAEG%2CAEGN%2CAEHR%2CAEIS%2CAEL%2CAEM%2CAEMD%2CAEO%2CAEP&types=company"
Response:
{StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: keep-alive
  Content-Security-Policy: default-src 'self'; child-src 'none'; object-src 'none'; style-src 'self' 'unsafe-inline'; font-src data:; frame-src 'self'; connect-src 'self' https://auth.iextrading.com https://api.iextrading.com https://api.iextrading.com wss://iextrading.com wss://tops.iextrading.com wss://api.iextrading.com wss://iextrading.com; script-src 'self' 'unsafe-inline' 'unsafe-eval';
  X-Content-Security-Policy: default-src 'self'; child-src 'none'; object-src 'none'; style-src 'self' 'unsafe-inline'; font-src data:; frame-src 'self'; connect-src 'self' https://auth.iextrading.com https://api.iextrading.com https://api.iextrading.com wss://iextrading.com wss://tops.iextrading.com wss://api.iextrading.com wss://iextrading.com; script-src 'self' 'unsafe-inline' 'unsafe-eval';
  Frame-Options: SAMEORIGIN
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=15768000
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Credentials: true
  Access-Control-Allow-Methods: GET, OPTIONS
  Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
  Date: Sun, 24 Feb 2019 00:42:53 GMT
  Set-Cookie: ctoken=b9620755257f4963914d7e20dc5a6485; Domain=.iextrading.com; Path=/; Expires=Sun, 24 Feb 2019 12:42:53 GMT; Secure
  Server: nginx
  Content-Length: 52983
  Content-Type: application/json; charset=utf-8
}}

**Comment by aokellermann** [comment]
You are using ?token=TOKEN when it should be &token=TOKEN.

**Comment by perigee** [comment]
with `stable` API, it is broken either.

```
curl https://cloud.iexapis.com/stable/stock/market/batch?symbols=aapl%2Cfb%2Ctsla&types=company&token=$(IEX_TOKEN)
```
got return: `"types" required with a valid value`
