### ISSUE TITLE
Data quality in new IEX cloud is not better or equal quality than old API v1

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#713]
Compare the following new API

https://cloud.iexapis.com/beta/stock/mcd/company?token=pk_xxx
https://cloud.iexapis.com/beta/stock/mcd/batch?token=pk_xxx&types=quote,stats

with old API

https://api.iextrading.com/1.0/stock/mcd/company
https://api.iextrading.com/1.0/stock/mcd/batch?types=quote,stats

We notice the new API data quality is not equal or better than old API. Please see screenshot

### Old API
<img width="675" alt="old" src="https://user-images.githubusercontent.com/308276/53297196-a6017600-3855-11e9-9096-c449acb55334.png">

<img width="956" alt="old2" src="https://user-images.githubusercontent.com/308276/53297197-abf75700-3855-11e9-9e4f-6f7c1980527f.png">

### New cloud API
<img width="491" alt="new" src="https://user-images.githubusercontent.com/308276/53297200-ba457300-3855-11e9-953a-1cb9b85085e6.png">

<img width="508" alt="new2" src="https://user-images.githubusercontent.com/308276/53297201-bca7cd00-3855-11e9-8538-e97b0beae38f.png">

We really like to move over to cloud API, because some end point like dividend information seems to be better. At this moment, should we move all API to v2, or we should use mixture of V1 and V2, depending on end point data quality?

**Comment by joshuablackburn-iex** [comment]
This is more related to an end of day process not picking up all symbols rather than the underlying data quality. We have the data, but need to look into the end of day process that caches the data.

**Comment by yccheok** [comment]
For https://cloud.iexapis.com/beta/stock/mcd/company?token=pk_xxx , we still notice the "description" field still appear much shorter than previous https://api.iextrading.com/1.0/stock/mcd/company

> Operates and franchises a food restaurant chain

compared to

> McDonald's Corp operates a chain of restaurants with approximately 37,200 restaurants in 120 countries. It also receives franchise royalties, and licensing pacts. The company offers a uniform value-priced menu with special additions based on regions.

Do you plan to "fix" this too? Thank you.
