### ISSUE TITLE
Will IEX LAST SSE streaming endpoint consume message quota?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#714]
Currently, we are using WebSocket https://ws-api.iextrading.com/1.0/last . There are roughly 50k client devices, consume such end point, per day.

We are planning to migrate to IEX cloud, as we know IEX will drop V1 API very soon.

We need to estimate the cost required, to migrate to IEX cloud.

I was wondering, will https://cloud-sse.iexapis.com/beta/last?token=YOUR_TOKEN&symbols=spy,aapl,tsla consumes message point? If yes, then 5,000,000 message quota per month seem to be too little for our case.

But, we are a bit confused. What does it mean by "Free, unlimited Investors Exchange data (Realtime trades, top of book, depth of book, auctions, listings data, more)" in the pricing page? Does that include SSE IEX LAST ?

**Comment by joshuablackburn-iex** [comment]
No, it will not. TOPS, LAST, and DEEP are all IEX data endpoints, and do not count towards message quota.
