### ISSUE TITLE
Sandbox message quota exceeded

### ISSUE THREAD

**Issue by nickkraakman** [iexg/IEX-API#716]
Hi, I have been using the API and really love how quickly you guys are adding new features! Was stoked to hear about the Sandbox, but am a little confused about it. The Sandbox documentation section says:

"_All tier features are enforced at this time, but **you are not limited by the number of calls you can make**. Your are not charged for test usage._"

However, after making several calls to `https://sandbox.iexapis.com` with my test token, I receive the following message:

"_You have exceeded your allotted message quota. Please enable pay-as-you-go to regain access_"

When clicking `View test data` in the cloud console, I indeed see that I have used 100% of my test messages. However, I thought the Sandbox would allow for unlimited testing with scrambled data, or am I missing something?

Thanks!

**Comment by joshuablackburn-iex** [comment]
Fixed.
