### ISSUE TITLE
Get dividend history of stocks/symbols for more than 5 years

### ISSUE THREAD

**Issue by anandnatarajan** [iexg/IEX-API#717]
## Summary
I want to get Dividend information of ETF's for more than 5 years. Currently Stock returns Dividend information for only max of 5 years, i want to see all available dividends history.

**Comment by joshuablackburn-iex** [comment]
We are already working with our provider on this.

**Comment by anandnatarajan** [comment]
Thank you Josh!!! Is there a timeline of when this is expected?

**Comment by tylervc33** [comment]
Josh, is there a timeline of when this is expected?

**Comment by Amosss** [comment]
Is there an updated timeline for this?

**Comment by Freddv2** [comment]
Hello Josh, Is there an updated timeline for this?

**Comment by evancarter-iex** [comment]
@Freddv2 We are still working on this

**Comment by clokk** [comment]
bumping to see if this is possible has been closed?

**Comment by joshuablackburn-iex** [comment]
Dividends are now available for over 12 years.

**Comment by clokk** [comment]
Thanks joshua. Found in the docs under advanced dividends. For others that may come across this issue here is the example endpoint in the docs:

https://sandbox.iexapis.com/stable/time-series/advanced_dividends/AAPL?last=4&token=Tsk_418734e3ae354f119e14d946c5061851
