### ISSUE TITLE
Is there no way to avoid costs with new cloud APIs?

### ISSUE THREAD

**Issue by martyh1** [iexg/IEX-API#718]
I have an Android app that consumes the v1.0 APIs.  The majority of it uses calls that will no longer work after June 2019 (i.e. https://api.iextrading.com/1.0/stock/...).  I don't charge for my app and there are no ads, i.e. I get no revenue from this at all.  It sounds like with the IEX cloud APIs, I can no longer sustain my app using IEX (cloud) data because of cost.  My understanding is that the free version cannot be used commercially.  Even if  I could use the free version, each user of my app would need their own key, correct?  I certainly can't offer the app using my own key since any user could cause the limit to be hit and affect all users.

- Is my app commercial if I don't charge for it?  If so....
- Can I somehow at least pass the cost onto the end user? By allowing them to use their own key?
- Am I simply hosed (cost-wise) with a free version of my app on the google play store and the new cloud API?

My app can be found on the play store at https://play.google.com/store/apps/details?id=com.marty.stocksearch.

**Comment by mutluit** [comment]
One possible solution could be if you set up your own public server for your users, and cache the data you get from IEX there. Ie. the app would get and update its data from your cache server...

**Comment by joshuablackburn-iex** [comment]
@martyh1 

If you are not deriving any revenue at all, then your app is not considered commercial use.

You are not required to have a key for each of your users. If you would like to offset the cost, you can have each user provide a key.

Like @mutluit said above, caching data is an efficient way to reduce message use and cost. 

Do you mind sharing what data you use from the API now and with what frequency?

By no means are we trying to make it expensive for our users. We are committed to making this type of data more accessible. There was a lot of demand for more data with favorable terms, and we set out to provide that while making it sustainable for us. This data is extremely expensive, and our goal was to structure the API in a way to allow everyone to access the full data set at very accessible prices.

We are deploying new features and updates rapidly, including ways to use the API more efficiently. We want to make sure you have as many options as possible while protecting the value of the underlying data.

**Comment by martyh1** [comment]
Seems to me that caching data on my own server/site/database doesn't save that much considering that the most interesting data is real-time intraday data, and that data would require new calls to IEX Cloud every time.  I'm thinking day-trading usage mostly.  

My calls look like this:
    ChartsActivity.java  (18 usages found)
        https://api.iextrading.com/1.0/stock/"+symbol+"/quote?filter="+dataItemsToRetrieve
        https://api.iextrading.com/1.0/stock/"+symbol+"/chart/"+thePeriod
        https://api.iextrading.com/1.0/stock/"+symbol+"/stats
        https://api.iextrading.com/1.0/stock/"+symbol+"/batch?types=news,comapny
        https://api.iextrading.com/1.0/stock/"+symbol+"/quote?filter="+dataItemsToRetrieve
        https://api.iextrading.com/1.0/stock/"+symbol+"/chart/"+thePeriod
        https://api.iextrading.com/1.0/stock/"+symbol+"/stats
        https://api.iextrading.com/1.0/stock/"+symbol+"/batch?types=news,company
        https://api.iextrading.com/1.0/stock/"+symbol+"/quote?filter="+dataItemsToRetrieve
        https://api.iextrading.com/1.0/stock/"+symbol+"/chart/"+thePeriod
        https://api.iextrading.com/1.0/stock/"+symbol+"/stats
        https://api.iextrading.com/1.0/stock/"+symbol+"/batch?types=news,company
        https://api.iextrading.com/1.0/stock/"+symbol+"/quote?filter="+dataItemsToRetrieve
        https://api.iextrading.com/1.0/stock/"+symbol+"/chart/"+thePeriod
        https://api.iextrading.com/1.0/stock/"+symbol+"/stats
        https://api.iextrading.com/1.0/stock/"+symbol+"/batch?types=news,company
    MainActivity.java  (16 usages found)
        https://api.iextrading.com/1.0/stock/market/sector-performance
        https://api.iextrading.com/1.0/stock/market/batch?symbols=" + encodedStockName + "&types=quote,news&range=1m&last=5
        https://api.iextrading.com/1.0/stock/market/news
        https://api.iextrading.com/1.0/stock/market/list/gainers
        https://api.iextrading.com/1.0/stock/market/list/losers
        https://api.iextrading.com/1.0/stock/market/batch?symbols=" + sectorEtfsStr + "&types=quote&range=1m&last=5
        https://api.iextrading.com/1.0/stock/market/list/iexvolume
        https://api.iextrading.com/1.0/ref-data/symbols?filter=symbol,name
    TrackPositions.java  (1 usage found)
        https://api.iextrading.com/1.0/stock/"+selectedSymbol+"/quote?filter=latestVolume,latestPrice

- API Call frequency: I haven't implemented anything like Firebase yet (it's on my list) to see *HOW* the app is being used (i.e. frequency of calls). 
- User base: 35 installs on active devices.  Not a lot but trying to grow that.

I want to go the route of creating a REST API backend (and cache data) because I need to learn that anyway.  I've already seen some solutions but don't want to go with a design that isn't scalable and EXTREMELY affordable both long term and short term. I'm looking at the MEAN stack for this (MongoDB, Express, Angular, and Node.js) and hosting everything (app and database) on my existing Bluehost account.  I'm afraid I'll be racking up costs on Bluehost also.  If anyone has input on that route or other better suggestions, I'd appreciate it.

End goal: monetize the app or get hired as an Android and/or backend developer.  I'm currently unemployed and need income ASAP!

**Comment by mutluit** [comment]
@martyh1, realtime data means streaming data. If you look in the row "SSE Streaming" in the price list (link see above), it's available for paying customers only, but not avail in the free START plan.

Your server should better have one or more Gigabit connection(s) to the internet, ie. multiple IPs or multiple servers... (the latter is better, but needs more administration work...)

But even if you do streaming, then IMO you can't just pass-thru-proxy the requests of your users to the iex server, as the users could eat up all your available messages. A better method would be to serve them from your own server's DB only. 

Yes, you can use your own REST API for your users. But you could also make a streaming API avail for them instead, ie. Push services. But as said, do stream only what is already in your local DB...

Regarding network bandwidth you of course should make a calculation using expected number of users connecting at the same time to the server and their average consummation of records, and the avg length of the records etc. And you of course need to know how much traffic per month is in your tariff. For example the following cloud provider offers 20 TB/m traffic per VPS for $2.49/m: https://www.hetzner.com/cloud. And it's easily scalable: just add more vCores(vCPUs), RAM, SSD disk space etc on demand for the VPS.

Btw, as I understand it, the IEX market data itself is free; one pays only for the market data from the other market places IEX obtains (buys) and makes avail to its own users.

**Comment by martyh1** [comment]
Thanks for your insight.  Much appreciated.  When I say realtime, I'm not assuming push or streaming.  I simply mean that when the data is requested (e.g. push of a button in the app for refresh), the data is not 15-min delayed.  Maybe I'm not using the terminology correctly.  I would consider push support later, but for the moment, I simply want to keep from losing the functionality I currently have (refresh data on manual request for up-to-the-minute fresh data; i.e. no constant/continuous data updates).

I'm thinking what you're suggesting is a way for my app to use cloud/remote storage and not consuming REST API calls at all.  Wasn't thinking that direction.  Then requests for certain data would still require smarts on the server side (in what form? JS?) to determine if that data is available in my server's DB.  If not, that "smarts" would have to request the data from IEX and store it in my cache (and then allow the remote storage call to complete).

The IEX market data (if I'm using the right term) is going away in favor of the new IEX cloud API.  All those calls I have "https://api.iextrading.com/1.0/stock..." will not work after June 2019.  At least that's my understanding.

**Comment by mutluit** [comment]
I think you have enough time till then. FYI here's the cloud-API for comparison:
https://iexcloud.io/docs/api/
I guess you can find most, maybe even all, of your current API calls there as well.
The LAUNCH tariff includes also a test API key (called "sandbox" key) for testing the real thing, but without spending any of "messages" (FYI: the cost/weight units are called messages. The doc of each API call lists also the cost of the call, and each API call causes a realtime update of the remaining messages in your account --> can be verified in the account data after login).

You need first to plan and setup a DB for all the market data you need (I think you better should set some max upper limits like # of days to keep in the DB, etc) , and then create a (REST) API to access the DB. Ie. HTTP GET interface that returns CSV or JSON data, ie. the same output format you are using right now, to keep the required changes to your app to a minimum.

**Comment by JP-MRPhys** [comment]
@martyh1 martyh1, I am using SSE with OkSse in Android. I am able to stop/close my SSE connection in my app but it still seems to obtaining a data from IEX after closing the connection. So I came here looking how to send a "stop/disconnect" request SSE to IEX. There was some dicussion about nodeJs but not in Java. So if you guys have any pointers would be great to know. May be I missed the necessary post. It seems we are doing the same things so would be happy to dicuss further to collaborate. 

@joshuablackburn-iex: Also reading solutions here and considering the cache etc. I agree and think if there was a frequency setting 1min, 30sec, 5mins, which we can add to our SSE endpoints, then it will simply things, a-lot. Not sure IEX would consider those and user-cost etc. Specially in initial stages where development time etc is resources to save.

**Comment by JP-MRPhys** [comment]
Sorry guys, I think there is already the frequency setting in the streaming documentation.

curl --header 'Accept: text/event-stream' 'https://cloud-sse.iexapis.com/stable/stocksUS1Minute?token=YOUR_TOKEN&symbols=spy'  


However, I am not sure how to close/disconnect SSE from JAVA.

**Comment by antoinevulcain** [comment]
For stock market gainers, loser and financial data you can always get them for free 👍

[https://financialmodelingprep.com/api/v3/stock/gainers](https://financialmodelingprep.com/api/v3/stock/gainers)

[https://financialmodelingprep.com/api/v3/stock/losers](https://financialmodelingprep.com/api/v3/stock/losers)

Their offical [github](https://github.com/antoinevulcain/Financial-Modeling-Prep-API)

**Comment by joshuablackburn-iex** [comment]
@antoinevulcain While it is possible to get "free" data around the internet, IEX Cloud offers fully legal, fully compliant institutional grade data. Users of IEX Cloud can always rely on our data to be the same used by the largest institutions in the world. 

We've seen many cases of sites taking our old, free IEX API and creating new APIs against our terms of service. Since the old API will fully shut down on June 15th, I caution use of APIs that do not clearly identify themselves or data sources.

**Comment by antoinevulcain** [comment]
@joshuablackburn-iex 👍

**Comment by martyh1** [comment]
With the switch over to IEX cloud and the upcoming end of life for the original apis, my app now directs users to apply for a token basically as a developer. They can then enter the token into my app and go from there. I expect to lose plenty of users this way but I simply wanted to keep an app live on the app store that was still usable and didn't require tons of changes. I would love it if I got compensated by IEX for directing people directly to their site for registration. Google shows I have 300 users with the app installed and actively using their devices.  My app is at  https://play.google.com/store/apps/details?id=com.marty.stocksearch&hl=en
