### ISSUE TITLE
List of Splits effective today, and/or a Split-flag in Quote data

### ISSUE THREAD

**Issue by mutluit** [iexg/IEX-API#719]
## Summary
Whishlist:
Splits effective today in Quotes, and/or a daily Splits list (symbols only).

## Details
The Quote data should have a new boolean field "Split:" with values "Yes" or "No" indicating a split effective today/now.
Alternatively or additionally a new daily list containing all symbols where a split is effective today/now.

**Comment by jkPnF** [comment]
This would be a neat enhancement. Especially valuable to those that are using the data for charting and historical prices need to be accurate. Thanks for looking into this IEX team.

**Comment by joshuablackburn-iex** [comment]
Have you looked at:

Splits https://iexcloud.io/docs/api/#splits
or
Upcoming Splits  https://iexcloud.io/docs/api/#upcoming-events
or
Splits Basic https://iexcloud.io/docs/api/#splits-basic

**Comment by MorningSleeper** [comment]
@joshuablackburn-iex As reported in https://github.com/iexg/IEX-API/issues/1330 the Splits Basic endpoint returns no results or partial results for some supported symbols. Appreciate if you could take a look.
