### ISSUE TITLE
Build Income Statement, Balance Sheet, Cash Flow from Financials - Question & Data Request

### ISSUE THREAD

**Issue by shuwnyuantee** [iexg/IEX-API#72]
I am constructing `Income Statement`, `Balance Sheet` & `Cash Flow` from `financials` api. But since fields are limited, I can only create brief one.

I have question & request here:

- `operatingGainsLosses` field - I guess this is related to Cash Flow Statement - adjustment. May I know what does it include exactly?

- Is it possible to add these fields in `financials`?

```
a) For Balance sheet
- Total current liabilities


b) For Cash Flow
- investing cash flow
- financing cash flow


c) For Income statement
- income before income tax
- provision for income tax

```

Thanks for help.

**Comment by shuwnyuantee** [comment]
I am combining all the below issues into 1 here & closing the others.

https://github.com/iexg/IEX-API/issues/72
https://github.com/iexg/IEX-API/issues/73
https://github.com/iexg/IEX-API/issues/74

Sorry for posting multiples tickets previously. Hope this ease your work & thanks for your help & time.

**Comment by samuelchodur** [comment]
I am hoping for these fields as well.
