### ISSUE TITLE
Extended session quote data issues

### ISSUE THREAD

**Issue by ParisMiami** [iexg/IEX-API#722]
## Summary
Premarket/after hours timestamp issues. https://cloud.iexapis.com/beta/symbol/quote returns invalid timestamps for extended hours. Timestamps are either well into the future or remain static for subsequent calls (do not update).

**Comment by joshuablackburn-iex** [comment]
We are looking into this as a possible GMT timezone conversion issue.

**Comment by ParisMiami** [comment]
Hi Josh! 
Thank you for the follow up! The problem is not only with timestamps, but also extendedPrice, which often returns erratic values, making it virtually unusable. Note that this did not used to happen in the old API (https://api.iextrading.com/1.0/). The behavior is widespread and not isolated to just certain symbols. The timestamp is 10 hours in the future and remains static (does not update with price). Please let me know if you need more details and if I can be of any help!
Thanks so much!

**Comment by ParisMiami** [comment]
Please look into extendedPriceTime specifically as it is not updating currently and stays static (on the symbols I've tried).

**Comment by evancarter-iex** [comment]
@ParisMiami we are actively looking into this, trying to figure out what exactly is going on

**Comment by evancarter-iex** [comment]
This should be fixed now.
