### ISSUE TITLE
New API IEX Cloud: Stats Endpoint Issue

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#723]
## Summary
Stats endpoint in new API misses several key stats:

Ex-Div Date    
Beta
EBITDA	
etc.

Those parameters are available in the old API stats endpoint. Please keep the same as old API. At least add Ex-Div Date and Beta. Ex-Div Date is very important date. Please bring Ex-Div Date back in Stats endpoint.

### API URL
/stock/{symbol}/stats/{stat}

**Comment by joshuablackburn-iex** [comment]
The ex dividend date is currently in stats. The key is nextDividendDate. We will get the docs updated to reflect that. It would typically be called the next ex date, but our key unfortunately just says nextDividendDate. 

EBITDA is part of the financials, and a stat our partner values highly. They have placed a high value on that number, especially the amount of effort they put in to provide accuracy. We are unable to provide that in the existing stats endpoint while keeping the weight low. We are looking into an advanced stats endpoint to include this type of data.

**Comment by bishinew** [comment]
Key nextDividendDate is in Doc, but not in the API itself. Please check it. 
Is it possible to add Beta in the Stats endpoint?

Thanks
