### ISSUE TITLE
NEW API IEX Cloud: Stats Endpoint key nextDividendDate missing in API itself

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#724]
## Summary
Key nextDividendDate is in Doc, but not in the API itself. Please check it.
Is it possible to add Beta back in the Stats endpoint?

### API URL
/stock/{symbol}/stats/{stat}

**Comment by joshuablackburn-iex** [comment]
It is missing for symbols that do not have a defined next ex dividend date. We will update the call to always return the key to avoid confusion.

**Comment by bishinew** [comment]
You said nextDividendDate is actually Ex-Div Date. I always check IBM and AAPL. They are big and has dividend history. I don't understand what you said. Can you consider doing the same as old API. Just bring back Ex-Div Date. For IBM

Ex-Dividend Date | 2019-02-07
-- | --

I don't understand Next Ex-Div Date. This is the date from Yahoo Finance. Many investors follow.

Thanks

**Comment by bishinew** [comment]
Please add Beta to Stats endpoint which is in the old API. Many thanks.

**Comment by joshuablackburn-iex** [comment]
ex dividend date has been added. Beta will be in a new advanced stats endpoint.

**Comment by bishinew** [comment]
Thanks.

You may want to set the different weight for some of those stats. To have a new endpoint it increases work on our development and your development too. Please consider having one stat point.
