### ISSUE TITLE
Requests should be signed with the SECRET token

### ISSUE THREAD

**Issue by GeekStocks** [iexg/IEX-API#725]
## Summary

**Disclaimer**: we're doing our due diligence on your beta. We are **not** using your data/beta for commercial purposes at this time, just exploratory & test use. All test data is located in an easily deleted development system isolated from production due to your very stringent [legal terms](https://iexcloud.io/terms/).

I'm surprised that you are rolling out this service using API tokens **in the clear** that cause the account holder to be billed. _I think you are asking for trouble._

## Details

I'm aware that you've touched on this issue in [706](https://github.com/iexg/IEX-API/issues/706) and in [661](https://github.com/iexg/IEX-API/issues/661) but your solution — _restricting calls to certain domains_ — does not prevent miscreants from domain spoofing.

What you are doing with this API is akin to [basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), and there is a really good reason why developers stopped using that a long time ago: **logs**. 

In [661](https://github.com/iexg/IEX-API/issues/661) @shoujs expressed concern about network intercepts, but truthfully its much easier than that: anyone with developer toolkit knowledge can see the network request, and every network history log captures the querystring with token.

What you've done with domain restrictions is reduce the surface area for attack _which is laudable, don't get me wrong_. But its not enough. Not with my wallet anyway.

I would be much more comfortable if you would just implement standard request signing like [Amazon Web Services does](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html) with their cloud offering. The request cannot be tampered with en route, the hash signature captured in logs is useless, and the request cannot be replayed after 15 seconds or so.

_**Your "publishable" token may as well be cash.**_

**Comment by joshuablackburn-iex** [comment]
Thank you for this highlighting this, and you are correct. We do have more work to do, and it is something we are actively working on. I appreciate the time you've taken to test out our platform and provide very useful feedback. Look for further improvements soon.

**Comment by joshuablackburn-iex** [comment]
I'm also interested to get your feedback on our legal terms, specifically which areas you believe to be very stringent. In many cases, we must include legal terms of our data partners which could be a factor.

**Comment by GeekStocks** [comment]
Well @joshuablackburn-iex your response is perfect and its a credit to you and IEX for being open and blunt about it. This is a **beta** after all and every developer involved should have their big boy pants on and be prepared for substantial changes. In reading through your existing issues its clear some don't understand that. 

_On the other hand_, some frustration **is** understandable given that IEX has begun charging for this service in its quite unfinished state. That's an _interesting_ business decision that presents some significant reputational risk.

As noted already in this issue (_and others yet unpublished_) I do find some _serious_ holes in the current offering _but in the same sentence_ let me state unequivocally that I (we) want you to succeed here; keep going - push through it. I'll take a minute to tell you why.

Recently [Nasdaq bought Quandl](https://business.nasdaq.com/mediacenter/pressreleases/1855930/nasdaq-acquires-quandl-to-advance-the-use-of-alternative-data) and as a result Quandl's public domain [Stock Price WIKI](https://www.quandl.com/databases/WIKIP) has turned to shit. Additionally, last month someone upstream from Barron's forced them to stop providing data in CSV format - _to their **subscribers** nonetheless_! Here's a link, but be warned that [this link opens a CSV file](http://www.barrons.com/public/resources/documents/NYSE.csv).

My point is this: whether or not those actions are coincidence or the latest skirmishes in a data war, the victims are academia and any low budget project, commercial or not. _IEX's entrance into this space is absolutely needed!_ There is not much difference between the [dragons Brad is slaying](https://iextrading.com/insights/cost-transparency-whitepaper/) and your project IMO. Any negative feedback from me (us) should be received in the context in which it is proffered: **_we want you to be strong enough to disrupt_**.

**Comment by joshuablackburn-iex** [comment]
The signed request feature is close to being rolled out. Here is a link to how it will work:

https://iexcloud.io/docs/api/#signed-requests-in-dev

**Comment by joshuablackburn-iex** [comment]
This feature has been deployed.
