### ISSUE TITLE
OHLC endpoint for TSX returning empty values

### ISSUE THREAD

**Issue by cgailey** [iexg/IEX-API#726]
## Summary
Thanks for the addition of Toronto EOD prices!!  Presently it appears the symbols are recognized but the data is empty.

## Details
https://cloud.iexapis.com/beta/stock/RY.TO/ohlc?token=TOKEN
returns
{"open":{},"close":{},"high":null,"low":null}

Same result for TD.TO, BCE.TO, CM.TO

### Date/time of issue
Thu Feb 28 07:28:41 CST 2019

### API URL
https://cloud.iexapis.com/beta/stock/RY.TO/ohlc?token=TOKEN

**Comment by joshuablackburn-iex** [comment]
That endpoint is currently not supported. We will update our docs to reflect what is supported. You can use https://cloud.iexapis.com/beta/stock/ry.to/previous?token=TOKEN

**Comment by cgailey** [comment]
That works.  Thanks.
