### ISSUE TITLE
dividend, eps, peRatio null in iex cloud

### ISSUE THREAD

**Issue by arjd** [iexg/IEX-API#727]
## Summary
ttmEPS, ttmDividendRate, peRatio, and dividendYield are suddenly all null for the key stats endpoint.

## Details
As examples, AAPL and AOS both returned nulls for these keys.

### Date/time of issue
Morning of Feb 28th

### API URL
https://cloud.iexapis.com/beta/stock/{symbol}/stats?token={token}

### Other Information (sample code, links, etc.)

**Comment by evancarter-iex** [comment]
We are looking into this

**Comment by evancarter-iex** [comment]
@arjd Should be fixed now. Let us know if you see any additional problems.
