### ISSUE TITLE
API Documentation not clear when values are nullable (delayed?), often lacking realtime fallbacks

### ISSUE THREAD

**Issue by jonstelly** [iexg/IEX-API#728]
## Summary
API documentation is lacking several details, like timing for fields where some fields are realtime while others are delayed, and also if a numeric field may be null or not

## Details
The API documentation is comprehensive in terms of breadth, but it lacks important details.  There are many fields that are sometimes null and that's not called out in the docs.  Also, documentation is not consistent in calling out which fields are realtime and which are delayed.  It feels like the Response Attribute tables need at least 1 more column (timing) for API calls where some fields are realtime and others are not.  And the Type field needs to indicate if numeric fields are nullable.

For one example, the [quote](https://iexcloud.io/docs/api/#quote) endpoint, it's not called out that High or Low are nullable.  Apparently they're null during the opening 15 minutes of the session because they're 15-minute delayed... But I have no fallback during that time, can we get realtime iexOpen, iexClose, iexHigh, iexLow fields added to the quote endpoint?  I'd rather the IEX realtime data there anyway.

### Date/time of issue
The opening 15 minutes of a session

### API URL
`/stock/???/quote`

### What you expected to happen
Be able to generate an OHLC item on a graph from the data

### What actually happened
Low and High are null (documentation doesn't call that out) and there is no fallback (iexLow, iexHigh)

**Comment by StockConsultant** [comment]
I would love to see an iexOpen iexLow and iexHigh added.

**Comment by evancarter-iex** [comment]
This is now documented.
