### ISSUE TITLE
Stock not supported

### ISSUE THREAD

**Issue by Katipoo** [iexg/IEX-API#729]

**Comment by joshuablackburn-iex** [comment]
Please provide some information or we will need to close this. I have no information to go in here.

**Comment by Katipoo** [comment]
Threee of my stocks I own are not supported and I was directed to contact you to have them added... I just downloaded this extension, but if It won't show my stock, then this application will not work for me.

Please Add the following Stock Symbols:
1.  LBUY (Leafbuyer Technologies)
2. RDDTF (Radient Technologies)
3. MJNA (Medical Marijuana)

Thank you!

**Comment by joshuablackburn-iex** [comment]
We do not run that extension, but we do support each of these symbols. The developer has not updated to our latest version to support these symbols.
