### ISSUE TITLE
"estimates" endpoint with filter, message usage

### ISSUE THREAD

**Issue by ddaywombat** [iexg/IEX-API#730]
I am worried about excessive usage when all I need to pull is one data point.

## Details
Using the estimates endpoint, i want to pull a batch for the expected earnings date. What I have put together results in message usage of 20k for two symbols, which is the same usage even without using a filter. Which makes sense with IEX weighting "estimates" usage at 10k/symbol. Is there another way to filter, or work around the "estimates" endpoint so that I can just batch pull the next expected earnings report date and not get hit with so much usage?

### Date/time of issue
2/28/19

### API URL
Sandbox (so no one else gets dinged)
https://sandbox.iexapis.com/beta/stock/market/batch?token=Tpk_YOURTOKENHERE&symbols=xrx,ivz&types=estimates&filter=reportDate

Cloud Beta
https://cloud.iexapis.com/beta/stock/market/batch?token=pk_YOURTOKENHERE&symbols=xrx,ivz&types=estimates&filter=reportDate

### What you expected to happen
Less usage!

### What actually happened
The same usage as the full un-filtered request

**Comment by joshuablackburn-iex** [comment]
If you only need the next earnings date you can find that in the key stats endpoint.

https://iexcloud.io/docs/api/#key-stats

If you call just the one field, like /stock/aapl/stats/nextEarningsDate  that will only be 1 message.

**Comment by ddaywombat** [comment]
Totally missed key stats. Thank you.
