### ISSUE TITLE
Is there a way to disable "$1 / 1,000,000 Pay as you go messages" feature?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#731]
We planned to subscribe to $9/ month package.

However, we are concern over "$1 / 1,000,000 Pay as you go messages".

Is there a way to disable such (If the 5,000,000 message quota is consumed, sub-subsequent API  call will yield failure), or place an upper limit of $ on how much we can afford to pay?

As, we don't want to have an incident, where a app bug/ or an abnormal surge of traffic, causes us a surprised end-of-month billing.

Thank you.

**Comment by joshuablackburn-iex** [comment]
It is disabled by default. We also have a cool down period if you go from enabled to disabled just to make sure it doesn't get turned on by accident. We provide API endpoints to monitor your use, and an endpoint to toggle pay-as-you-go on/off.
