### ISSUE TITLE
Account page is blank

### ISSUE THREAD

**Issue by jhunter1955** [iexg/IEX-API#732]
## Summary
when choosing Account to view my usage, the page is blank.

## Details
Using Firefox browser, after sign-in, selecting the Account page, the page is blank
### Date/time of issue

3/1/2019 11:10 am CST

### What you expected to happen
I expect to see my usage data.

### What actually happened
Page was blank

**Comment by joshuablackburn-iex** [comment]
Are you on IEX Cloud or the original API? iexcloud.io

**Comment by jhunter1955** [comment]
You are correct, using an old link. you may close the issue
