### ISSUE TITLE
Several APIs problems and questions

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#734]
Hi

How can I get the "real time" price of aapl? 
I saw the "chart" API but I get a lot of info, I just want to get the last known price.
If in trading hours, then the delayed price and if outside trading hours, then the close price.

How can I get the "real time" price/fundamentals/dividends of a symbol outside the US? Is there a prefix/suffix for the symbol? Example of aapl: https://cloud.iexapis.com/beta/stock/aapl/dividends/5y

several APIs for dividends ends at the end of 2017/beginning of 2018, is it a bug?
https://api.iextrading.com/1.0/stock/bdcl/dividends/5y (2017)
https://api.iextrading.com/1.0/stock/spy/dividends/5y (2017)
https://api.iextrading.com/1.0/stock/aapl/dividends/5y (beginning of 2018)

What is flag: "ex" for dividend history?

Thanks

**Comment by joshuablackburn-iex** [comment]
Stock quotes give you price.
https://iexcloud.io/docs/api/#quote

Outside the US we currently only have Canada. We will update our docs with reference data for Canada.

Dividends have more history when you use Cloud. The links you provided are for the old API.
https://iexcloud.io/docs/api/#dividends

**Comment by Amosss** [comment]
This question was closed too soon, sorry for re-opening it:
While old API has data for ETF's dividend history, the new one returns empty data, for example bdcl, spy, sdy. Is it known?

I didn't find the following information in the new APIs:
price_earning
price_book
return_equity
forward_price_earning
payout_ratio
growth1y
growth3y
growth5y
growth10y
estimate5growth
past5growth
debt_equity
Beta
----
div announcements (not paid yet)
----
Is it available maybe in different names?
Thanks
