### ISSUE TITLE
Peers API is returning empty for MCD

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#735]
https://cloud.iexapis.com/beta/stock/MCD/peers?token=pk_...

is returning empty peer result. We are expecting MCD should have some peer result

**Comment by evancarter-iex** [comment]
I see peers for MCD. Is this still an issue?

**Comment by yccheok** [comment]
Ok. Looks good to me now. But, I'm pretty sure I'm getting empty result few days ago.

Btw, I have some payment issues and I contact someone by clicking on the chat button at bottom right (inside IEX cloud console). Not sure can someone get back to me? Thanks.

**Comment by evancarter-iex** [comment]
Responded in the chat.
