### ISSUE TITLE
Cannot submit idea for roadmap

### ISSUE THREAD

**Issue by arjd** [iexg/IEX-API#736]
## Summary

See screenshot.

### Other Information (sample code, links, etc.)

![image](https://user-images.githubusercontent.com/20357504/53682410-5989c080-3cc3-11e9-862f-22557a75efb9.png)

**Comment by evancarter-iex** [comment]
We had lots of people who were able to enter input. Is this still a problem for you?

**Comment by arjd** [comment]
Oh, well I'm guessing it's something with my browser. I might try again at some point but I see my suggestion was already covered by an GitHub issue that recently closed.

Thanks!
