### ISSUE TITLE
data available?

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#737]
While old API has data for ETFs dividend history, the new API returns empty data, for example bdcl, spy, sdy. Is it known?

I didn't find the following information in the new APIs:
price_earning
price_book
return_equity
forward_price_earning
payout_ratio
growth1y
growth3y
growth5y
growth10y
estimate5growth
past5growth
debt_equity
Beta
---
div announcements (not paid yet)
---
Is it available maybe in different names?
Thanks

**Comment by Amosss** [comment]
Sorry for the styling, I didn't find a way to remove it. Even copy/paste using notepad didn't help.

**Comment by evancarter-iex** [comment]
Dupe of #715

**Comment by Amosss** [comment]
The other discussion is a request regarding dividends, my question has no relation to dividends and now it is closed with no apparent reason.... @evancarter-iex

**Comment by evancarter-iex** [comment]
Correction. This is a dupe of #654

**Comment by Amosss** [comment]
What about this part?
I didn't find the following information in the new APIs:
price_earning
price_book
return_equity
forward_price_earning
payout_ratio
growth1y
growth3y
growth5y
growth10y
estimate5growth
past5growth
debt_equity
Beta

Thanks

**Comment by evancarter-iex** [comment]
I see, the way this request was submitted, made it very hard to understand. For those can you open a new ticket (since this one is very hard to read with everything bolded).
