### ISSUE TITLE
/chart/date requests return empty set

### ISSUE THREAD

**Issue by Sofianel5** [iexg/IEX-API#738]
## Summary
I am trying to create a chart with data from each day in the week. The only problem is all calls to /stock/aapl/chart/date/20180129 or any date return a null set. This is the example linked on the https://iextrading.com/developer/docs/#chart page. If the example provided is returning an error, but the other examples return data there must be a problem with the /chart/date route on your end.

## Details
When i press the link provided, https://api.iextrading.com/1.0/stock/aapl/chart/date/20180129 , my browser renders [], but if i press any other link, ie https://api.iextrading.com/1.0/stock/aapl/chart/1d , data is displayed. In my code, i put the averages into a dict, which prints to {'NFLX': None, 'AAPL': None}. In debug, calls show as:
DEBUG:urllib3.connectionpool:https://api.iextrading.com:443 "GET /1.0/stock/AAPL/chart/date/20190304 HTTP/1.1" 200 2 

or 

DEBUG:urllib3.connectionpool:https://api.iextrading.com:443 "GET /1.0/stock/AAPL/chart/date/20190301 HTTP/1.1" 200 None

### Date/time of issue
March 3rd, 9:49 EST

### API URL
https://api.iextrading.com/1.0/stock/aapl/chart/date/20180129

### What you expected to happen

Return of a .json containing the data

### What actually happened

return of []

### Other Information (sample code, links, etc.)
My python lookup function contacts API as:
response0 = requests.get(f"https://api.iextrading.com/1.0/stock/{urllib.parse.quote_plus(symbol)}/chart/date/{day0}")
where day0 is defined as 20190304
Please request if needed, I provided everything i could think of.

**Comment by evancarter-iex** [comment]
This is fixed in IexCloud. Please use that going forward.

https://iexcloud.io
