### ISSUE TITLE
Additional Data Requested for Quote & Financials

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#740]
Hi
I didn't find the following information in the new APIs:
price_earning
price_book
return_equity
forward_price_earning
payout_ratio
growth1y
growth3y
growth5y
growth10y
estimate5growth
past5growth
debt_equity
Beta

Maybe they appear using a different name?
Thanks
ps: re-posted by request to make it more readable.

**Comment by xxx44yyy** [comment]
and EBITDA forget

**Comment by bishinew** [comment]
Please add Beta and EBITDA to STATS endpoint like the old API does. Thanks

**Comment by evancarter-iex** [comment]
Hi there most of these are now available at https://iexcloud.io/docs/api/#advanced-stats . For anyone thats not please open a new github issue. Thanks.
