### ISSUE TITLE
Question about using Beta end point (https://cloud.iexapis.com/beta/)

### ISSUE THREAD

**Issue by stockgainsmobile** [iexg/IEX-API#743]
## Summary

I have a question about using beta endpoints (https://cloud.iexapis.com/beta/). I am pulling for example price (https://cloud.iexapis.com/beta/stock/AAPL/price?token={token}) for apple on March 4th after hours.

It shows 174.97 when from different data sources the price at close is 175.85

Then for example from batch endpoint the iex realtimemarket price does show 175.85 but the change percent once again is 0.88 from various sources but no value from the batch single request returns this value.

Should i be using some other end point instead of /beta or should I use (https://api.iextrading.com/1.0)
for now. Just wondering the status of beta at the moment.

**Comment by evancarter-iex** [comment]
@stockgainsmobile Sorry that we never got back to you on this. Did you figure out your answer? Or is it still a problem?

**Comment by stockgainsmobile** [comment]
@evancarter-iex yes you can close this ticket. Thank you!
