### ISSUE TITLE
Symbols type errors & strange types for a few symbols

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#745]
## Details

1. type is null:

- ELAN#
- CCZ
- JBK
- AFC
- GYB
- PIY

2. Strange type:

- RGR (type = Consumer Durables)
- UBOT (type = Miscellaneous)

3. Type which is not in the documentation: **wt** [https://iexcloud.io/docs/api/#symbols](https://iexcloud.io/docs/api/#symbols)

4. Another strange type: cef (see: AABA)

### API URL
https://cloud.iexapis.com/beta/ref-data/symbols

**Comment by evancarter-iex** [comment]
@xxx44yyy We updated the documentation for WT & CEF.

We fixed the "Strange Types" for RGR and UBOT.

As for the null types, we updated with a default value, since thats what we given.

**Comment by xxx44yyy** [comment]
@evancarter-iex CCZ, JBK and another - with type struct, but i not found this type in doc

**Comment by evancarter-iex** [comment]
@xxx44yyy its a default field when we dont have any data. I will add it to documentation

**Comment by xxx44yyy** [comment]
ok, thanks!
