### ISSUE TITLE
Company it's not company (issuer)

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#746]
## Summary
One company can have many tickers (common stocks, bonds, stocks of different types). But now the company is just the details of a ticker.

request: https://cloud.iexapis.com/beta/stock/brk.a/company/?token={my_token}
response:
```json
{
"symbol":"BRK.A",
"companyName":"Berkshire Hathaway Inc. Class A",
"exchange":"New York Stock Exchange",
"industry":"Multi-Line Insurance",
"website":"http://www.berkshirehathaway.com",
"description":"Operates as a holding company which offers insurance, rail transportation and energy generation & distribution services",
"CEO":"Warren Edward Buffett",
"issueType":"cs",
"sector":"Finance",
"employees":389000,
"tags":["Finance","Multi-Line Insurance"]
}
```

and...

request: https://cloud.iexapis.com/beta/stock/brk.a/company/?token={my_token}
response:
```json
{
"symbol":"BRK.B",
"companyName":"Berkshire Hathaway Inc. Class B",
"exchange":"New York Stock Exchange",
"industry":"Multi-Line Insurance",
"website":"http://www.berkshirehathaway.com",
"description":"Operates as a holding company which offers insurance, rail transportation and energy generation & distribution services",
"CEO":"Warren Edward Buffett",
"issueType":"cs",
"sector":"Finance",
"employees":389000,
"tags":["Finance","Multi-Line Insurance"]
}
```

These are not two companies. It should be one company with two tickers. The correct information should be:
**companyName => Berkshire Hathaway Inc.**

For both requests. Without **Class**

**Comment by xxx44yyy** [comment]
Because of this error, the number of companies will always be equal to the number of tickers. It's wrong, it can't be.

**Comment by joshuablackburn-iex** [comment]
This is a valid point. companyName should really be securityName. We will make that change and companyName will be the parent company of the security.

**Comment by evancarter-iex** [comment]
This is deployed. We now have a companyName and SecurityName
