### ISSUE TITLE
Wrong name of the exchanges

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#747]
open issue: [https://github.com/iexg/IEX-API/issues/746](https://github.com/iexg/IEX-API/issues/746)

request: https://cloud.iexapis.com/beta/stock/brk.a/company/?token={my_token}
response:
```json
{
"symbol":"BRK.A",
"companyName":"Berkshire Hathaway Inc. Class A",
"exchange":"New York Stock Exchange",
"industry":"Multi-Line Insurance",
"website":"http://www.berkshirehathaway.com",
"description":"Operates as a holding company which offers insurance, rail transportation and energy generation & distribution services",
"CEO":"Warren Edward Buffett",
"issueType":"cs",
"sector":"Finance",
"employees":389000,
"tags":["Finance","Multi-Line Insurance"]
}
```

"exchange" -> "New York Stock Exchange". 

But here [https://iexcloud.io/docs/api/#u-s-exchanges](https://iexcloud.io/docs/api/#u-s-exchanges) another name ("**NYSE**").

**Comment by joshuablackburn-iex** [comment]
There is a mismatch due to the exchange going by different names, though it is not incorrect. We will update our exchange ref data call to include short name and long name.
