### ISSUE TITLE
EPS Report date is wrong in the Earnings Call

### ISSUE THREAD

**Issue by rittik97** [iexg/IEX-API#748]
Example: https://cloud.iexapis.com/beta/stock/EXPE/earnings?token=token
This is true for AAPL as well.

The date is one greater than the actual release date.
V1 API is correct: 
https://api.iextrading.com/1.0/stock/EXPE/earnings

I believe the current value in the IEX cloud API maybe the date EPS was updated in your databases.

**Comment by evancarter-iex** [comment]
This should be fixed now. Let us know if you see additional issues.
