### ISSUE TITLE
Reference interest rates

### ISSUE THREAD

**Issue by JMCA2** [iexg/IEX-API#749]
It would be very useful, especially for traders, for calculating financing costs. If you offered reference interest rates on the API. Both official central bank rates and others.
Especifically:

- ECB
- FED
- BoE
- LIBOR rates
- tom-next rates for currency swaps costs

**Comment by evancarter-iex** [comment]
Some of this has been added

https://cloud.iexapis.com/stable/data-points/market

**Comment by timpaine-iex** [comment]
closing as stale
