### ISSUE TITLE
AAPL dividend lookup not working

### ISSUE THREAD

**Issue by twoinvesting** [iexg/IEX-API#75]
Hey guys,

Anyone know why this no longer works for AAPL? I’ve taken it directly from the API documentation. It was working as of a couple days ago. And, it still works for other stocks, just not AAPL for some reason.

https://api.iextrading.com/1.0/stock/aapl/dividends/3m

Thanks,

Scott

**Comment by joshuablackburn-iex** [comment]
@twoinvesting We see the data is missing today, and we've reached out to our data provider regarding this issue.  We are working to restore this as quickly as possible.

**Comment by evancarter-iex** [comment]
Should be fixed.
