### ISSUE TITLE
How to get quotes for a specific date? 

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#751]
For example, how do I know the closing price of the AAPL on March 1, 2010?

**Comment by joshuablackburn-iex** [comment]
https://cloud.iexapis.com/beta/stock/aapl/chart/date/20190301?chartByDay=true&token=YOUR_TOKEN

**Comment by JPayne3** [comment]
The URL above works but..........
You send a lot of info I don't want.  Filter doesn't seem to work,  but maybe I'm doing it wrong.
Also can I get data on a date for a batch of symbols?
