### ISSUE TITLE
What is the cost for /stock/aapl/chart/5y and /stock/aapl/chart/max

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#752]
From https://iexcloud.io/docs/api/#historical-prices , it isn't clear

> 10 per symbol per time interval returned (Excluding 1d)
> 
> Example: If you query for AAPL 5 day, it will return 5 days of prices for AAPL for a total of 50.

For `/stock/aapl/chart/5y`, will the cost be 50, or 10*5*356 ?

How about `/stock/aapl/chart/max`?

**Comment by joshuablackburn-iex** [comment]
The historical prices documentation needs some work and should be more clear. We will update that.

For 5 years of aapl is 12,580 messages if you use /chart/5y
5 years of aapl using the parameter chartCloseOnly=true is 2,516 messages.

**Comment by joshuablackburn-iex** [comment]
chart/max for apple is 40,100.

You are able to test all endpoints yourself by using our testing sandbox.
https://iexcloud.io/docs/api/#sandbox

You can call any endpoint using the sandbox URL, and view the message use in your console.
