### ISSUE TITLE
IEX Cloud returning stale prices as current prices for mutual funds

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#754]
## Summary

Beginning 2019.03.04, the cloud api seems to return stale prices with incorrect closing datetime. (See below for details).

## Details
I performed a batch query of several mutual funds. the 'latest price' was correct for the 'latest time', but the 'close' price was for the previous day. This appears to be consistent for all reported funds.

### Date/time of issue
Last tested 2019.03.07 17:02EST

### API URL
https://cloud.iexapis.com/beta/stock/market/batch?types=quote,dividends&symbols=ACEIX, LBNDX, MABAX,NOTAX,NOTCX,PNOPX&token=MY_KEY

### What you expected to happen
Close price should match latest price when reported for a given date.

### What actually happened
Latest price was the closing price for the Latest Date, closing price was for the previous day.

### Other Information (sample code, links, etc.)

{
    "ACEIX": {
        "quote": {
            "symbol": "ACEIX",
            "companyName": "Invesco Equity & Income Fund",
            "calculationPrice": "previousclose",
            "open": null,
            "openTime": null,
            "close": 9.98,
            "closeTime": 1551839340000,
            "high": null,
            "low": null,
            "latestPrice": 9.93,
            "latestSource": "Previous close",
            "latestTime": "March 6, 2019",
            "latestUpdate": 1551848400000,
            "latestVolume": 0,
            "iexRealtimePrice": null,
            "iexRealtimeSize": null,
            "iexLastUpdated": null,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": null,
            "extendedChange": null,
            "extendedChangePercent": null,
            "extendedPriceTime": null,
            "previousClose": 9.93,
            "change": 0,
            "changePercent": 0,
            "iexMarketPercent": null,
            "iexVolume": null,
            "avgTotalVolume": 0,
            "iexBidPrice": null,
            "iexBidSize": null,
            "iexAskPrice": null,
            "iexAskSize": null,
            "marketCap": 0,
            "peRatio": null,
            "week52High": 11.18,
            "week52Low": 8.8,
            "ytdChange": 0.081699
        },
        "dividends": []
    },
    "LBNDX": {
        "quote": {
            "symbol": "LBNDX",
            "companyName": "Lord Abbett Bond Debenture Fund Inc.",
            "calculationPrice": "previousclose",
            "open": null,
            "openTime": null,
            "close": 7.78,
            "closeTime": 1551839340000,
            "high": null,
            "low": null,
            "latestPrice": 7.78,
            "latestSource": "Previous close",
            "latestTime": "March 6, 2019",
            "latestUpdate": 1551848400000,
            "latestVolume": 0,
            "iexRealtimePrice": null,
            "iexRealtimeSize": null,
            "iexLastUpdated": null,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": null,
            "extendedChange": null,
            "extendedChangePercent": null,
            "extendedPriceTime": null,
            "previousClose": 7.78,
            "change": 0,
            "changePercent": 0,
            "iexMarketPercent": null,
            "iexVolume": null,
            "avgTotalVolume": 0,
            "iexBidPrice": null,
            "iexBidSize": null,
            "iexAskPrice": null,
            "iexAskSize": null,
            "marketCap": 0,
            "peRatio": null,
            "week52High": 8.19,
            "week52Low": 7.41,
            "ytdChange": 0.041499
        },
        "dividends": []
    },
    "MABAX": {
        "quote": {
            "symbol": "MABAX",
            "companyName": "Blackrock Basic Value Fund",
            "calculationPrice": "previousclose",
            "open": null,
            "openTime": null,
            "close": 21.1,
            "closeTime": 1551839340000,
            "high": null,
            "low": null,
            "latestPrice": 21,
            "latestSource": "Previous close",
            "latestTime": "March 6, 2019",
            "latestUpdate": 1551848400000,
            "latestVolume": 0,
            "iexRealtimePrice": null,
            "iexRealtimeSize": null,
            "iexLastUpdated": null,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": null,
            "extendedChange": null,
            "extendedChangePercent": null,
            "extendedPriceTime": null,
            "previousClose": 21,
            "change": 0,
            "changePercent": 0,
            "iexMarketPercent": null,
            "iexVolume": null,
            "avgTotalVolume": 0,
            "iexBidPrice": null,
            "iexBidSize": null,
            "iexAskPrice": null,
            "iexAskSize": null,
            "marketCap": 0,
            "peRatio": null,
            "week52High": 28.63,
            "week52Low": 18.13,
            "ytdChange": 0.097179
        },
        "dividends": []
    },
    "NOTAX": {
        "quote": {
            "symbol": "NOTAX",
            "companyName": "Dws Strategic High Yield Tax Free Fund",
            "calculationPrice": "previousclose",
            "open": null,
            "openTime": null,
            "close": 11.78,
            "closeTime": 1551839340000,
            "high": null,
            "low": null,
            "latestPrice": 11.79,
            "latestSource": "Previous close",
            "latestTime": "March 6, 2019",
            "latestUpdate": 1551848400000,
            "latestVolume": 0,
            "iexRealtimePrice": null,
            "iexRealtimeSize": null,
            "iexLastUpdated": null,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": null,
            "extendedChange": null,
            "extendedChangePercent": null,
            "extendedPriceTime": null,
            "previousClose": 11.79,
            "change": 0,
            "changePercent": 0,
            "iexMarketPercent": null,
            "iexVolume": null,
            "avgTotalVolume": 0,
            "iexBidPrice": null,
            "iexBidSize": null,
            "iexAskPrice": null,
            "iexAskSize": null,
            "marketCap": 0,
            "peRatio": null,
            "week52High": 12.09,
            "week52Low": 11.67,
            "ytdChange": 0.004259
        },
        "dividends": []
    },
    "NOTCX": {
        "quote": {
            "symbol": "NOTCX",
            "companyName": "Dws Strategic High Yield Tax Free Fund",
            "calculationPrice": "previousclose",
            "open": null,
            "openTime": null,
            "close": 11.79,
            "closeTime": 1551839340000,
            "high": null,
            "low": null,
            "latestPrice": 11.8,
            "latestSource": "Previous close",
            "latestTime": "March 6, 2019",
            "latestUpdate": 1551848400000,
            "latestVolume": 0,
            "iexRealtimePrice": null,
            "iexRealtimeSize": null,
            "iexLastUpdated": null,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": null,
            "extendedChange": null,
            "extendedChangePercent": null,
            "extendedPriceTime": null,
            "previousClose": 11.8,
            "change": 0,
            "changePercent": 0,
            "iexMarketPercent": null,
            "iexVolume": null,
            "avgTotalVolume": 0,
            "iexBidPrice": null,
            "iexBidSize": null,
            "iexAskPrice": null,
            "iexAskSize": null,
            "marketCap": 0,
            "peRatio": null,
            "week52High": 12.09,
            "week52Low": 11.68,
            "ytdChange": 0.004255
        },
        "dividends": []
    },
    "PNOPX": {
        "quote": {
            "symbol": "PNOPX",
            "companyName": "Putnam Sustainable Leaders Fund",
            "calculationPrice": "previousclose",
            "open": null,
            "openTime": null,
            "close": 85.27,
            "closeTime": 1551839340000,
            "high": null,
            "low": null,
            "latestPrice": 84.75,
            "latestSource": "Previous close",
            "latestTime": "March 6, 2019",
            "latestUpdate": 1551848400000,
            "latestVolume": 0,
            "iexRealtimePrice": null,
            "iexRealtimeSize": null,
            "iexLastUpdated": null,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": null,
            "extendedChange": null,
            "extendedChangePercent": null,
            "extendedPriceTime": null,
            "previousClose": 84.75,
            "change": 0,
            "changePercent": 0,
            "iexMarketPercent": null,
            "iexVolume": null,
            "avgTotalVolume": 0,
            "iexBidPrice": null,
            "iexBidSize": null,
            "iexAskPrice": null,
            "iexAskSize": null,
            "marketCap": 0,
            "peRatio": null,
            "week52High": 103.54,
            "week52Low": 69.38,
            "ytdChange": 0.141107
        },
        "dividends": []
    }
}

**Comment by evancarter-iex** [comment]
This is correct.

Mutual Funds are not updated until around (roughly 8:30-9:30pm ET for us and other sites like Yahoo etc), thus the "latest price" will be yesterday's close as Mutual Funds are not actively traded. "Close" refers to the day before close price.
