### ISSUE TITLE
Actual costing for News API

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#755]
From documentation - https://iexcloud.io/docs/api/#market-volume-u-s, this is the costing for News API

> 10 per symbol per news item returned

For 2 days, we have consume roughly 500 News API call.

When we check our console, API costing for news is around 1178.

<img width="379" alt="2019-03-08 09_20_05-iex cloud console" src="https://user-images.githubusercontent.com/308276/54000701-660a8f00-4183-11e9-8bb9-4fa500da7259.png">

We're bit surprise. As, per documentation description, News API seems to be a very expensive costing, as it is "per symbol, per news item"

Can you kindly clarify on the actual costing for News API?

**Comment by joshuablackburn-iex** [comment]
Sorry for the out of date docs. News weight is only 1, not 10.

**Comment by yccheok** [comment]
May I know, if symbol MCD produces 6 news, will the cost be 1 or 6 ?
