### ISSUE TITLE
Is there a way to get delayed-quote for multiple tickers at one API call

### ISSUE THREAD

**Issue by allondata** [iexg/IEX-API#756]
## Summary
I am looking for pulling delayed-quote for multiple tickers in one single call.
Urls provided in details section.

## Details

Existing API url : https://api.iextrading.com/1.0/stock/xom/delayed-quote
Expected API URL: https://api.iextrading.com/1.0/stock/xom, aapl, cvx/delayed-quote

### Date/time of issue
Mar  - 08  - 2019

### API URL
https://api.iextrading.com/1.0/stock/xom/delayed-quote

### What you expected to happen
work with multiple tickers
Expected API URL: https://api.iextrading.com/1.0/stock/xom, aapl, cvx/delayed-quote

### What actually happened
returns Unknow symbol message

### Other Information (sample code, links, etc.)
none

**Comment by SunnyShankar** [comment]
Being able to pull multiple tickers at one go, helps analyze / compare multiple securities simultaneously. Looking forward to a solution for this.

**Comment by evancarter-iex** [comment]
This works with IEXCloud.

https://cloud.iexapis.com/beta/stock/market/batch?symbols=aapl,fb&types=delayed-quote&token=TOKEN

Please note that a large portion of IEX API will be decommissioned in June and moved over to https://iexcloud.io
