### ISSUE TITLE
Please limit the scope of "IEX Cloud Data" to only copyrightable items

### ISSUE THREAD

**Issue by GeekStocks** [iexg/IEX-API#758]
## Summary
The definition of "IEX Cloud Data" in [section 16.15](https://iexcloud.io/terms/) is overly broad; _it should not be required to delete all the downloaded uncopyrightable facts upon contract termination._

## Details
In [725 you asked for feedback](https://github.com/iexg/IEX-API/issues/725#issuecomment-468232619) on the legal terms. I don't want to commingle 2 very different issues under the same thread since that's usually not good netiquette. I hope you don't mind breaking this out to its own issue.

_Very quickly_, to understand this issue a primer may be needed. Software and proprietary file formats (e.g.: your JSON structure) are 100% copyrightable; you can own them and give them away (e.g.: open source). The **facts** being conveyed inside the JSON response (e.g.: a closing price or a quarterly filing) are **not** protected by copyright. [Copyright does not extend to facts.](https://www.copyright.gov/help/faq/faq-protect.html) If needed, a fuller understanding of these issues can be achieved by studying [Feist Publications, Inc., v. Rural Telephone Service Co.](https://en.wikipedia.org/wiki/Feist_Publications,_Inc.,_v._Rural_Telephone_Service_Co.)

With that prerequisite dealt with, the issue I find stringent is regarding termination. In this business switching providers is unfortunately a given. Over time, company mergers often mean that terms and pricing change and data quality can really erode quickly. Migrating to alternate providers must be constantly considered and prepared for.

In IEX Cloud's case, **you're requiring the deletion of every byte downloaded when a customer migrates to another provider**. I refer to [section 9.4(iii)](https://iexcloud.io/terms/) which states…

> Customer will delete the Software and any `IEX Cloud Data`;

…and the definition of `IEX Cloud Data` in [section 16.15](https://iexcloud.io/terms/) which states…

> "`IEX Cloud Data` means all data provided to Customer by IEX Cloud via the Services."

**"…all data…" is an overly broad definition**. I am used to seeing deletion clauses stick to a more customary "copyright" line, meaning that copyrighted software and files that are in a copyrighted, proprietary format are the things needing to be deleted when terminating. _This makes sense because the provider actually **owns** those things._ But under the IEX Cloud definition, even uncopyrightable facts such as a closing price or a public domain quarterly filing must be deleted upon termination. _Wow! What are customers paying for? Is IEX Cloud renting facts?_

I am not inclined to use facts that could disappear; **I'm not renting facts.** Placing IEX Cloud delivered facts into an existing system would irrevocably pollute that system unless fact provenance tracking were incorporated to enable a clean deletion process. _Under that contract clause, IEX Cloud delivered facts are like thousands of tiny viruses that you have to quarantine from everything else you're doing._

I hope I've explained this well enough; _its an issue that causes most people's eyes to glaze over (lol)._ I hope you can see what a non-starter this issue can be. I hope you can change this requirement. If you can't, if this is a third party requirement being foisted upon you, then I encourage you to _eliminate that third-party from your lineup_. That clause is evil, and **any company that would attempt to control the freedom of uncopyrightable facts is super-evil.**

**Comment by joshuablackburn-iex** [comment]
The data owned by IEX is freely available from IEX Cloud and the IEX Exchange. Our 3rd party providers require their own data rules, one of which is deleting data upon contract termination. That is fairly common once you start dealing with the very large providers.

You're welcome to have your legal department contact IEX legal and make a case for changing this language, but it will probably require changes to all 3rd party contracts.

We [share the concerns](https://www.linkedin.com/pulse/how-stock-exchanges-abuse-privilege-power-profits-bradley-katsuyama/) around over priced and over restrictive financial data. We started this to do something about it, and as much as we would like, it will not change immediately. I feel we are providing a lot of value at much more accessible prices. Our terms and price may not fully align with everyones needs, and in those cases there may be other companies with a better aligned service.
