### ISSUE TITLE
Add symbol property in news batch response

### ISSUE THREAD

**Issue by kiranparab0** [iexg/IEX-API#759]
## Summary
Add symbol property in news batch response

## Details
Adding symbol property in news batch response will allow easy transformation and mapping to server side objects of the result

### Date/time of issue
Anytime

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=news&last=5

### Other Information (sample code, links, etc.)
Symbol property is available in quote batch response, allowing easy transformation and mapping to server side objects.
https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote

**Comment by evancarter-iex** [comment]
We will look into this. Please note that IEX API 1.0 is being discontinued in June and will be replaced by https://iexcloud.io

**Comment by timpaine-iex** [comment]
closing as stale
