### ISSUE TITLE
Logo endpoint for OTC stocks is returning broken links

### ISSUE THREAD

**Issue by ws420** [iexg/IEX-API#760]
The LOGO endpoint seems broken with OTC stocks. The image URL returned from the API is broken

Test with:
https://cloud.iexapis.com/beta/stock/SVVTF/logo

Returns:
`{"url":"https://storage.googleapis.com/iex/api/logos/SVVTF.png"}`

But the image URL returned by the API is broken:
https://storage.googleapis.com/iex/api/logos/SVVTF.png
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to iex/api/logos/SVVTF.png.
</Details>
</Error>
```

**Comment by evancarter-iex** [comment]
This is fixed.
