### ISSUE TITLE
CSE stocks questions

### ISSUE THREAD

**Issue by ws420** [iexg/IEX-API#761]
I noticed that you started [adding CSE stocks](https://cloud.iexapis.com/beta/stock/CXXI.CN/quote) to the API (no price yet). I know that you already confirmed that support for CSE stocks is coming, but I have a few questions about the endpoints that will be available for CSE stocks, with a paid plan at $9/m.

- Will you support intraday prices (delayed 15m) or just EOD?
- Fundamentals data (market cap in CAD, outstanding shares, PE, EPS)?
- Financials (balance sheet, earnings, estimates, cashflow, ...)?
- Analysts rating and price targets?
- Insiders transactions?
- Institutional ownership?
- RSS news for CSE stocks?
- CEO name & compensation?

Thank you!

**Comment by weedstreet420** [comment]
It was working a couple of days ago but now IEX API is returning either "Unknown Symbol" or "Forbidden" when querying for CSE stocks.

The API endpoint URL I posted here 22 days ago is not working anymore https://cloud.iexapis.com/beta/stock/CXXI.CN/quote

Why was it removed from the API? Will you still support CSE stocks in the future or do I need to look for another data provider subscription? I would appreciate an answer.
Thanks

**Comment by ws420** [comment]
Still no answer 6 months later and same issue persists - no support for CSE stocks, no timeline announced, zero reply to support requests
...great service

**Comment by evancarter-iex** [comment]
@ws420 Unfortunately, there's a reason we cannot comment on this. Closing.
