### ISSUE TITLE
IEX Cloud API usage control should be call rate limit, not # of calls limit 

### ISSUE THREAD

**Issue by min-mwei** [iexg/IEX-API#762]
## Summary

Currently this call limit control makes very hard to see even if worth to try out IEX. I have exhausted all my quota now until next month. Now the api returns nothing! 

## Details

I am doing a small test program to get all symbols, and get the chart data for each symbol. This simple program exhausted all the quota in one go (not sure if the usage counter is even right to indicate 500K calls, because I am making one call to get the symbols, one chart call per symbol). 

A better model, imho, is to limit the call rate for the "free accounts". Since I am doing tryouts, I don't kind to be rate limited say, 1 call per second.   

### Date/time of issue
3/9/2019 

### API URL

https://cloud.iexapis.com/beta/

**Comment by evancarter-iex** [comment]
Hi, the 3rd party data provider we use requires the data weighting we are using.  (IEX Data is still free)

Make sure you understand the idea of data weighting:

https://iexcloud.io/docs/api/#data-weighting

Each endpoint has documentation on how many messages per call it takes.

We also have a sandbox environment for testing, which you can monitor to see how much each request costs in terms of messages (you can use this even if you are out of messages in production):

https://iexcloud.io/docs/api/#sandbox

**Comment by StockConsultant** [comment]
@evancarter-iex how does one get the free IEX data, does using quote or batch endpoints and filtering by just IEX... data fields result in no cost?

Also any estimate on when the beta period will end? 2 weeks, 1 month? etc...
