### ISSUE TITLE
New API IEX Cloud Host URL

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#763]
## Summary

Is it possible to get the permanent host url? When your system upgrade or update the host url stays the same.  

If we distribute our software, IEX host is coded in the software. If you update the host url, the software has to update. This is not good for the users since users ignore the update and suddenly see the service stopped.

The current host url is

https://cloud.iexapis.com/beta/

I expect you drop bet from the url in the real production.  We hope the host url will be permanent without change in the real production.

**Comment by joshuablackburn-iex** [comment]
The base URL will always be cloud.iexapis.com. The version will change. Right now the version is beta, but when we move into v1, beta users will automatically be forwarded. We would then start v2-beta. Our recommendation is you code to a specific version since major version changes could break your code.

**Comment by bishinew** [comment]
For distributed software such as an Android app or  iOS app, updating the URL is not a good practice since some of users may not update or new version cannot be supported in the new phone. If the basic function is working users may not care about it.

So we suggest IEX use the same host URL without v1, v2 etc.  During the test developer can add v1 or v2. After the code is promoted to production, you can forward url to production or migrate the code to production server.

Please consider.

Thanks
