### ISSUE TITLE
Would IEX consider to show case paid clients work at their website?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#765]
Hi, I was wondering, would IEX be interested to show case paid client products at their website? It may create a win-win scenario :

1. Clients have opportunity to market their product.
2. IEX can demonstrate their determination, to make financial data affordable.

For instance, we use IEX data to display peer information, and dividend information, in JStock (https://jstock.co)

### Peer information
![Screenshot_20190310-234459](https://user-images.githubusercontent.com/308276/54087631-a3dc0300-438f-11e9-9031-f4f4111b567e.png)

### Dividend information
![Screenshot_20190310-234735](https://user-images.githubusercontent.com/308276/54087633-a63e5d00-438f-11e9-874e-74059a933a78.png)

Thank you.

**Comment by joshuablackburn-iex** [comment]
Yes. We would like to feature our users. Please email us at support@iexcloud.io and send details of the app. We are compiling this information and building this part of the site.

**Comment by yccheok** [comment]
Thank you. I had sent necessary information to your mentioned email.
