### ISSUE TITLE
Streaming SSE messages issue

### ISSUE THREAD

**Issue by mfhawley** [iexg/IEX-API#767]
## Summary
Streaming server side events seems to be very wasteful in that it returns numerous points for the exact same datapoint/second (roughly 50+ points of the exact same datapoints returned for each second). Making the required messages needed 50x as much.

(Then also skips several seconds as well (see second attached screenshot where it jumps from 1:03:32 to 1:03:50)

### Date/time of issue
03/11/2019 1:00pm EST

### API URL
https://cloud-sse.iexapis.com/beta/stocksUS?token=TOKEN_HERE&symbols=aapl

### What you expected to happen
I expect to see either exactly one datapoint returned per minute or exactly one datapoint returned for every second.

### What actually happened
It returned between 10-50 datapoints for each second, then skips over 10 seconds or so and returns 10-50 datapoints for that second

### Other Information (sample code, links, etc.)
P.S. - If would be even more awesome if the there is a streaming endpoint for 1-minute data.

![image](https://user-images.githubusercontent.com/14339122/54142978-0e1f9280-43e6-11e9-9a1e-0cfc3c8ceb9e.png)
![image](https://user-images.githubusercontent.com/14339122/54143068-49ba5c80-43e6-11e9-8a4e-515087193890.png)

**Comment by joshuablackburn-iex** [comment]
In your specific example, data is actually changing. The SSE connection is streaming each update on the stock. The quote (bid/ask) and delayed trades are updating in the screenshots above. The market just moves fast and we are sending all updates.

What we can look at adding is a conflated feed that updates on lower intervals, or maybe even removes quotes.

**Comment by mfhawley** [comment]
I see. That makes sense then I supposed. I suppose it would be intended for short stints of streaming rather than streaming all stocks all day.

Thank you for the explanation though!
