### ISSUE TITLE
Add Canadian symbols to /ref-data/symbols (or as an alternative, docs on how to get end-of-day prices on TSX)

### ISSUE THREAD

**Issue by arifb** [iexg/IEX-API#768]
Hi, thanks very much for deploying Canadian end-of-day prices, from another issue it seems you can get those at  https://cloud.iexapis.com/beta/stock/{symbol}/previous. 

How do we get a list of symbols to use with the API? /ref-data/symbols doesn't return any Canadian data.

Or is there another method/flow that is recommended?

**Comment by evancarter-iex** [comment]
https://cloud.iexapis.com/beta/ref-data/region/ca/symbols should work. We need to update the documentation.

**Comment by evancarter-iex** [comment]
Documentation updated.

**Comment by arifb** [comment]
Awesome @evancarter-iex thanks for the quick response and docs!
