### ISSUE TITLE
DHR missing fundownership insider transactions recommendation trends 

### ISSUE THREAD

**Issue by rajpatelukyahoo** [iexg/IEX-API#769]
## Summary
Data not available for all symbols.

https://cloud.iexapis.com/beta/stock/DHR/fund-ownership?&token=????
https://cloud.iexapis.com/beta/stock/DHR/institutional-ownership?&token=?
https://cloud.iexapis.com/beta/stock/DHR/recommendation-trends?&token=???
https://cloud.iexapis.com/beta/stock/DHR/insider-transactions?&token=

## Details
DHR is a SP500, no data returned for any of the above API call
### API URL
https://cloud.iexapis.com/beta/stock/DHR/fund-ownership?&token=????
https://cloud.iexapis.com/beta/stock/DHR/institutional-ownership?&token=?
https://cloud.iexapis.com/beta/stock/DHR/recommendation-trends?&token=???
https://cloud.iexapis.com/beta/stock/DHR/insider-transactions?&token=

### What you expected to happen

return valid data as it does for DOW 30 stocks.

### What actually happened

[] - returned

**Comment by evancarter-iex** [comment]
This is fixed now.
