### ISSUE TITLE
Some stock data you could add

### ISSUE THREAD

**Issue by lucas03** [iexg/IEX-API#77]
Hi,
I was using yahoo finance data that they discontinued using lately. So when I was checking your api, I miss a few yahoo had and that could be useful to more people. Thanks for doing this API (and for free!)  
https://api.iextrading.com/1.0/stock/jnj/quote

```
earnings_per_share
dividend_per_share
dividend_yield
ex_dividend_date
industry
```

**Comment by shuwnyuantee** [comment]
I think you can get these information from:

https://iextrading.com/developer/docs/#key-stats

https://iextrading.com/developer/docs/#company

**Comment by lucas03** [comment]
Nice! Is there a bulk endpoint for key stats?

**Comment by shuwnyuantee** [comment]
By bulk u mean query multiple symbols in 1 call? Eg:

https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=stats

This might help u:  https://iextrading.com/developer/docs/#batch-requests

**Comment by joshuablackburn-iex** [comment]
@lucas03 This data should be available between /quote and /stats, and you can use batch requests to fetch both in the same call.  Closing this issue unless you are experience further issues.

**Comment by ssathya** [comment]
Are historic Key Stats available? Historic values for at least 5 years will be nice.
