### ISSUE TITLE
Library for node TypeScript only? JavaScript Not supported?! this is bizarre.

### ISSUE THREAD

**Issue by MasterJames** [iexg/IEX-API#771]
TypeScript is not a language don't use it exclusively, please ?!

TypeScript is not JavaScript. While it might seem like an improvement it has to be compiled into a language that is understood (unnecessarily complicated defeatist to it's original vision purpose and design). It is created by Microsoft (strike 1) and really they have admitted default via incompetency and will wrap V8 with Edge in the future (so all Microsoft browser technology is dead), have always tried to use the clout to keep control, etc. {a horrible attitude that has only punished them thank goodness}.

TypeScript will not run in the browser it's not a computer language that any computer can understand (strike 2). It has to be run through a compiler after some extra third party extension and really is only understood in the IDE with special addons, etc. (stike 3).

You could add TypeScript wrapper around a proper RunTime JavaScript version, easily.

I feel there is more then an argument that you are not supporting JavaScript (worlds most popular language especially for this kind of service) and this being the only language that really counts. [See globally known admitted statistics on programming language popularity.] That is continually growing moving forward. 

Unfortunately some people are confused by this meddling by Microsoft and providing only the (technically) 'unusable' (or at least awkward [bad kind of disruptive ill intended]) TypeScript. 

Anyway hopefully without being as offensive as this fact is to me. I'm saying please provide a pure JavaScript solution. It should be easy to strip out the TypeScript as the compiler has to work hard to do for every end use situation (another waste=stike).

I will not be using TypeScript ever and so I can't use your services. It's sad and depressing people don't see the damage being caused to a great successful runtime language by having to compile it from some other undesired hack)? I'm surely not alone on this. If it's a heated contentious debate then the damage has been done. Don't let that happen here. Please do the right thing and provide a pure JavaScript NodeJS solution First (then approach the redundant idea of adding the Crutch for Noobs called TypeScript).

You simply can't stand by and think TypeScript is JavaScript, because it's not. And so maybe it's easier to add the Type Clutter later. Again your not providing a usable tool for the majority of developers. Full Stop. It will be easy to fix this grieves oversight, and then you will see many more usages, etc. So I'm off to find a useful tool I can use, but I'd sure like to know when you actually support JavaScript.

**Comment by joshuablackburn-iex** [comment]
I'm not sure what you're talking about here. IEX Cloud is REST and SSE. These are language agnostic. We actually have 3rd party libraries in many languages https://iexcloud.io/docs/api/#libraries

Please let me know why you are so convinced we are using TypeScript.

**Comment by MasterJames** [comment]
Right sorry I was confused and stressed out I guess this week, and have edited the question. I am saying it's important to think of JavaScript first and then provide alternatives like TypeScript. I looked at the TypeScript only Source and feel it's important for me to ask for a version that doesn't need special attention to run in nodejs, and so it's easy to add to your build process I imagined so one can add through npm a package that is ready to go without compiling. I also see npm install -g ts-node now?

**Comment by joshuablackburn-iex** [comment]
I'm still a bit confused because we don't offer source code. We only provide the URL based API with JSON or CSV data formats.

**Comment by MasterJames** [comment]
I guess this is the source of my confusion.
https://iexcloud.io/docs/api/#libraries

I thought this was your stuff in TS only.
https://github.com/bilalq/iex-api/tree/master/src

**Comment by MasterJames** [comment]
This is perfect thanks, again sorry for the confusion and jumping to odd conclusions.
https://iextrading.com/developer/docs/#deep
