### ISSUE TITLE
Caching period

### ISSUE THREAD

**Issue by aas395** [iexg/IEX-API#773]
Hi,

I didn't see this anywhere on the website. Could someone tell me what the allowed caching period is for data retrieved from the historical EOD prices endpoint? Ideally I wouldn't need to retrieve the full dataset more than once per symbol, considering how much of the quota each request uses, and then I could update prices daily after that. Thank you!

**Comment by joshuablackburn-iex** [comment]
You can choose whatever caching strategy works best for you. We actually recommend using efficient strategies like this. If the data isn't changing then you don't need to call multiple times.
