### ISSUE TITLE
Company Information is Scrambled

### ISSUE THREAD

**Issue by kbeck1** [iexg/IEX-API#774]
## Summary

I'm testing the new cloud API and ran into some problems with how the stock's company information is displayed.

## Details

When using the new cloud IEX API, I receive scrambled data instead of human readable data. See examples from the old API vs the new cloud API for AT&T (T).

### Date/time of issue

March 13, 2019

### API URL

https://sandbox.iexapis.com/beta/stock/T/company/?&token=xxxxxxxx

### What you expected to happen
This example is from the old API.

```json
{
  "symbol": "T",
  "companyName": "AT&T Inc.",
  "exchange": "New York Stock Exchange",
  "industry": "Communication Services",
  "website": "http://www.att.com",
  "description": "AT&T Inc is engaged in provision of communications and digital entertainment services in the United States and the world. It provides fixed-line services, including voice, data, and television services to consumers and small businesses.",
  "CEO": "Randall L. Stephenson",
  "issueType": "cs",
  "sector": "Communication Services",
  "tags": [
    "Communication Services",
    "Telecom Services"
  ]
}
```

### What actually happened
With the new cloud IEX API.

```json
{
  "symbol": "T",
  "companyName": "AT&T, Inc.",
  "exchange": " aYkkeotrwSxecE Nhn ocg",
  "industry": "nisemorMcaot jelcouniTma",
  "website": "t/apt:.wc.w/mthwot",
  "description": "ancecc,sSonesl oinoL  dtls ed crioe Piatldd ta dvnanseriv-aeetin ravgD",
  "CEO": "lte nnaoh .adLSepRlns",
  "securityName": "A c.T&TIn",
  "issueType": "cs",
  "sector": "tmsuninoicCmao",
  "employees": 277526,
  "tags": [
    "ctinCmsuaoomni",
    "lomeoauaojisccTei Mtrnmn"
  ]
}
```

### Other Information (sample code, links, etc.)

https://sandbox.iexapis.com/beta/stock/T/company/?&token=xxxxxxxx

**Comment by evancarter-iex** [comment]
Sandbox is for testing.

cloud.iexapis.com is for real requests.
