### ISSUE TITLE
Support for Path Parameters

### ISSUE THREAD

**Issue by kbeck1** [iexg/IEX-API#775]
## Summary

It would be nice to have support for path parameters across all endpoints.

## Details

The Key Stats endpoint supports path parameters, allowing a query and return of a single value. It would be nice if this was available for other endpoints (e.g. company, dividends,etc).

https://iexcloud.io/docs/api/#key-stats

### Date/time of issue

March 13, 2019

### API URL

https://cloud.iexapis.com

### What you expected to happen

```
Communications
```

### What actually happened

```json
{
  "symbol": "T",
  "companyName": "AT&T, Inc.",
  "exchange": "New York Stock Exchange",
  "industry": "Major Telecommunications",
  "website": "http://www.att.com",
  "description": "Provides DSL internet, local and long-distance voice and data services",
  "CEO": "Randall L. Stephenson",
  "securityName": "AT&T Inc.",
  "issueType": "cs",
  "sector": "Communications",
  "employees": 268000,
  "tags": [
    "Communications",
    "Major Telecommunications"
  ]
}
```

### Other Information (sample code, links, etc.)

https://cloud.iexapis.com/beta/stock/T/company/sector?&token=xxxxx

**Comment by timpaine-iex** [comment]
closing as stale, this is the goal around `time-series`.
