### ISSUE TITLE
Dividends returning 2018 dates not 2019

### ISSUE THREAD

**Issue by metron9** [iexg/IEX-API#779]
## Details
https://api.iextrading.com/1.0/stock/pci/dividends/1m

Returns: Dates for 2018 it should be 2019
[{"exDate":"2018-03-09","paymentDate":"2018-04-02","recordDate":"2018-03-12","declaredDate":"2018-03-01","amount":0.164063,"flag":"","type":"Dividend income","qualified":"","indicated":""}]

### Date/time of issue

Today 03/14/2019

### API URL
https://api.iextrading.com/1.0/stock/pci/dividends/1m

### What you expected to happen

Should return the last dividend of 2019 not 2018

### What actually happened
returns dates years 2018 instead of 2019

### Other Information (sample code, links, etc.)

PCI last dividend X was 03-08-2019 and the pay date will be 04-01-2019
A few days ago it was returning 2019 dates, but the payment date isone greater than the days it should be, i.e. 04-01-2019 not 04-02-2019, That's a secondary issue need the Year fixed

**Comment by evancarter-iex** [comment]
We are looking into this

**Comment by evancarter-iex** [comment]
This actually for api.iextrading.com. IEX Cloud https://iexcloud.io has a completely new data provider which has 2019 data.
