### ISSUE TITLE
I need help (php) huge favor.

### ISSUE THREAD

**Issue by Mb460** [iexg/IEX-API#78]
Hello iex community. 

I would like to ask for a HUGE favor.... well.. maybe not that huge... 

Here's the thing... I'm not that great at coding. I dabbled in php 3 way back in the day, and i have forgotten MOST of that at this point. But i have need for a personal script that will do a specific thing, and this API will give me the info i need to start down that path.

Is anyone willing to make a PHP file, which accesses the API, and displays 
Date, Daily high, Daily low of any random stock?   say, Apple... for 100 days including current day.

Once i have access and can see a result, i think i can manipulate the data the way i need it to be manipulated.  

date - high - low (of the day)
11/10/17 | 200.05 |  197.16
11/11/17 | 210.42 |  195.34
11/12/17 | 250.95 |  245.34
etc....

if someone is willing to help me out with that, i don't even care if it just lists the data, returned in one long string. i just need to be able to get the data, so i can manipulate it as i need to. 

Thanks in advance!!!!!!!!
Mitch

**Comment by scottycc** [comment]
https://iextrading.com/developer/docs/#chart will work for what the data you want

file_get_contents() & json_decode() are the php functions you will want to look at

**Comment by Mb460** [comment]
Thank you.

In not at my computer but... would I do something like form action (link) 
method GET, then basically run that code?
