### ISSUE TITLE
Additional filtering options on chartCloseOnly=true

### ISSUE THREAD

**Issue by dsrapaport** [iexg/IEX-API#781]
## Summary
I am trying to get only the "date", "close", and "volume" data for a ticker (e.g., AAPL) for the last 29 days, using the parameter chartCloseOnly=true, but it does not seem to filter only for those three fields.

## Details
I should be able to get the "date", "close", and "volume" data for a ticker (e.g., AAPL) for the last 29 days using the following URL:

[https://cloud.iexapis.com/beta/stock/aapl/chart/3m?token=[my token]&chartLast=29&chartCloseOnly=true](url)

However, that query/url seems to yield not only the "date", "close", and "volume" data, but also the "change", "changePercent", "changeOverTime" data for each day as well (which I don't need)

Separately, I tried using the filter parameter (per below) but that still gave me the unwanted "change", "changePercent", "changeOverTime" data:

[https://cloud.iexapis.com/beta/stock/aapl/chart/3m?token=[my token]&chartLast=29&chartCloseOnly=true&filter=date,close,volume](url)

When I used the parameter "chartCloseOnly=true" yesterday, it seemed to work.  However, now it doesn't. 

Thank you for your help.  I appreciate it!

### Date/time of issue
11am-12:30pm PST

### API URL
[https://cloud.iexapis.com/beta/stock/aapl/chart/3m?token=[my token]&chartLast=29&chartCloseOnly=true](url)

### What you expected to happen
I expected to get a data series for the past 29 days which only included the "date", "close", and "volume" for each day.

### What actually happened
The url (https://cloud.iexapis.com/beta/stock/aapl/chart/3m?token=[my token]&chartLast=29&chartCloseOnly=true) not only gave me the "date", "close", and "volume" for each day for the past 29 days, but also the corresponding "change", "changePercent", and "changeOverTime" data for each day which I do not need.

### Other Information (sample code, links, etc.)

**Comment by joshuablackburn-iex** [comment]
It seems the endpoint is working properly, but returning more data than you want. I looked into this and it does appear filter is not working properly. This will be resolved shortly.

**Comment by dsrapaport** [comment]
Thank you Joshua!  Very much appreciate it.

**Comment by evancarter-iex** [comment]
This fix has been deployed. Closing. Please open any additional issues you see as new github issues. Thanks

**Comment by Johnnyskidmarks** [comment]
Filter works fine in all end points I've tested except that the API documentation is incorrect. Instead of 
```?filter=symbol,volume,lastSalePrice``` 
 you would use 
```&filter=symbol,volume,lastSalePrice```
 after the token.
