### ISSUE TITLE
OHLC documentation is unclear

### ISSUE THREAD

**Issue by jonstelly** [iexg/IEX-API#782]
## Summary
The [OHLC documentation](https://iexcloud.io/docs/api/#ohlc) says that Open is either the open or the close price, and that close is either the open or the close price, and that time is either the open or the close time.

Under what cases would open be close, or would close be open?  Why the complexity/nuance?

### What you expected to happen

This seems like it should be a simple API, OHLC values across all exchanges, 15 minute delayed.  Open would always be the Open price, Close would always be the Close price, and Time would be now - 15 minutes.

### What actually happened

Not sure

**Comment by joshuablackburn-iex** [comment]
The docs are very poorly worded, and we will get that resolved. Open is open and close is close. 

We are also working on a time series endpoint that should hopefully put an end to all the guess work and jumping between endpoints.
