### ISSUE TITLE
SKM dividends wrong

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#783]
## Summary

The company has never paid such dividends. 
for check: [https://www.nasdaq.com/symbol/skm/dividend-history](https://www.nasdaq.com/symbol/skm/dividend-history)

### API URL
https://cloud.iexapis.com/beta/stock/skm/dividends/5y?token=MY_TOKEN

### Other Information (sample code, links, etc.)
```json
[{
"exDate":"2018-06-29",
"paymentDate":"2018-08-26",
"recordDate":"2018-06-30",
"declaredDate":"2018-07-27",
"amount":1000,
"flag":"Interim"},
{
"exDate":"2017-06-28",
"paymentDate":"2017-08-28",
"recordDate":"2017-06-30",
"declaredDate":"2017-07-31",
"amount":1000,
"flag":"Interim"}
]`

**Comment by evancarter-iex** [comment]
This appears to be due to the fact that the dividends is in local currency. We will look into this

**Comment by joshuablackburn-iex** [comment]
We've added currency to dividends.
