### ISSUE TITLE
Re-download data without payment

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#784]
We've added currency to dividends.

_Originally posted by @joshuablackburn-iex in https://github.com/iexg/IEX-API/issues/783#issuecomment-473421600_

Thank you! However, I used a paid account, how do I re-download data without payment?

It's common. Payment -> download data -> finding a bug -> your fix -> new payment -> download data. I can pay again, it's not a problem (you have great plans), but I think it is illogical.

**Comment by joshuablackburn-iex** [comment]
The model is based on usage which is what allows us to offer such a low starting price. We understand it makes it harder to understand pricing at first, but overall it should lead to lower cost. We are constantly evaluating ideas to help our users save time and money, and we will add this concern as well.
