### ISSUE TITLE
A question about API V1

### ISSUE THREAD

**Issue by fabriziocesarini** [iexg/IEX-API#785]
Hello everyone
I have a simple question
After June 2019 the historicals data on API v1 will remain available?
Thanks

**Comment by joshuablackburn-iex** [comment]
https://iextrading.com/developer/docs/#getting-started

This page explains the API transition and what v1.0 endpoints will remain.

**Comment by fabriziocesarini** [comment]
Hi Josh,
Thank you for answering but i didn't understand
The page you linked I saw but it is not very clear.
My question is very simple.
For example this request:
https://api.iextrading.com/1.0/stock/aapl/chart/5y
Will it return the values after June 1?
Thank you very much
Fabrizio
