### ISSUE TITLE
One company can have different symbols

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#787]
One company can have different symbols (tickers). For example, there is a company Berkshire hathaway, it has two different tickers: BRK.A and BRK.B

But you don't seem to be:

![Снимок экрана 2019-03-17 в 1 30 55](https://user-images.githubusercontent.com/40538167/54482438-64605b80-4854-11e9-8625-27425928e988.png)

That is, in the screenshots we should see an array, not a string.

**Comment by joshuablackburn-iex** [comment]
I'm not sure I understand the issue here. Is this a feature request or a bug report?

When you query the stats endpoint, as shown above, you are returned data for the security, not the parent company. Returning an array of symbols would be misleading, and incorrect.
