### ISSUE TITLE
Will there be information about the indexes (SP500, etc)?

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#788]
Will there be information about the indexes (SP500, etc)?

**Comment by joshuablackburn-iex** [comment]
We are working on historical index data, but intraday index data requires additional contracts between you and the index provider. They also charge additional fees.

**Comment by xxx44yyy** [comment]
I am interested in the list stocks of the index (which includes tickers). Intraday quotes are not interesting.
