### ISSUE TITLE
Expand Earnings History to Multiple Years

### ISSUE THREAD

**Issue by drobertson123** [iexg/IEX-API#79]
Currently, you return the last 4 earnings periods. I seriously appreciate the information but it isn't enough for solid Y/Y analysis. At least 2-3 years would be better. 5-10 years would be amazing.

Any chance that is on the expansion list?

**Comment by evancarter-iex** [comment]
We have at least 12 quarters of earnings periods in IEXCloud. https://iexcloud.io
