### ISSUE TITLE
Tops as types in batch endpoint? 

### ISSUE THREAD

**Issue by josephmaxim** [iexg/IEX-API#790]
Is it possible to have TOPS along with Charts using Batch endpoint? I wanna be able to make a single request instead of iterating through the symbols and make 10 to 15 request.

**Comment by josephmaxim** [comment]
Updates on this?

**Comment by timpaine-iex** [comment]
this is doable with an important caveat - TOPS applies only to US Equities (traded on IEX Exchange), whereas `batch` will work for the expanding symbol universe we now support (though coverage varies endpoint to endpoint still for international equities)
