### ISSUE TITLE
https://iextrading.com/developer/docs/#getting-started

### ISSUE THREAD

**Issue by fabriziocesarini** [iexg/IEX-API#791]
https://iextrading.com/developer/docs/#getting-started

This page explains the API transition and what v1.0 endpoints will remain.

_Originally posted by @joshuablackburn-iex in https://github.com/iexg/IEX-API/issues/785#issuecomment-473881838_

Hi Josh,
Thank you for answering ... but i didn't understand
The page you linked I saw but it is not very clear for me.
Please help me clarify
My question is very simple.
Historical Values remain available for api v1? Yes or no?
For example this request:
https://api.iextrading.com/1.0/stock/aapl/chart/5y
Will it return the values after June 1?
Thank you very much
Fabrizio

**Comment by joshuablackburn-iex** [comment]
No. That data will not be available. Everything under /stock will no longer be available on the old API, but will be on IEX Cloud.
