### ISSUE TITLE
Modify dividends info "next" API to return upcoming dividends by pay date

### ISSUE THREAD

**Issue by estrnod** [iexg/IEX-API#792]
## Summary
 Informed that dividends "next" option is based on exDate, would like at least an option to have it based on paymentDate (or changed to do so).

## Details
Dividends which are past the exDate but before paymentDate are not included; have to get history to get them (a more expensive call).
### Date/time of issue
3/19/2019 around 11:00 MST.

### API URL
for example:
https://cloud.iexapis.com/beta/stock/KHC/dividends/next?token=... 

### What you expected to happen
See upcoming payments

### What actually happened
Will only show declared dividends before the exDate.

### Other Information (sample code, links, etc.)
See final outcome of https://github.com/iexg/IEX-API/issues/776.

**Comment by timpaine-iex** [comment]
I didn't follow up but `upcoming-dividends` and all other upcoming events endpoints support the `exactDate` argument. You can also use `timeseries` to query ranges of ex dividend dates
