### ISSUE TITLE
Filtering results without headers

### ISSUE THREAD

**Issue by mrfolsom** [iexg/IEX-API#793]
## Summary
I am trying to filter specific values for earnings, dividends and financial statements. 

## Details
I am trying to get several specific data points and figured out how to filter but can't figure out how to remove the header from results.

### Date/time of issue
3/20/19 8:20a cst

### API URL
=WEBSERVICE("https://sandbox.iexapis.com/beta/stock/"&D4&"/stats/?token=Tpk_xxxxx&filter=ttmEPS")

### What you expected to happen
5.51

### What actually happened
{"ttmEPS":5.51}

**Comment by joshuablackburn-iex** [comment]
You should use:

https://sandbox.iexapis.com/beta/stock/SYMBOL/stats/ttmEPS?token=YOUR_TOKEN

That will return just the value. We are working on a new endpoint geared towards Excel users who only need specific data points.

**Comment by tonydividend** [comment]
Any update or work around for Excel users? Been searching for hours for a resolution to this exact issue for excel.

**Comment by jasonzanfardino** [comment]
The data points endpoint https://iexcloud.io/docs/api/#data-apis
