### ISSUE TITLE
New API: ETFs miss DIV and YIELD info in Stats Endpoint

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#796]
## Summary

 ETFs miss DIV, ex-Div Date and YIELD info in Stats Endpoint. These information is available in Stats endpoint for common stocks. The old API works for both common stocks and ETFs.

ttmDividendRate | null
dividendYield | null
exDividendDate | null

Please check and correct it.

### API URL

https://cloud.iexapis.com/beta/stock/market/batch?symbols=VPU,QQQ,VTI&types=stats&token=*

**Comment by evancarter-iex** [comment]
Dupe of https://github.com/iexg/IEX-API/issues/654
