### ISSUE TITLE
403 in Market Volume Endpoint

### ISSUE THREAD

**Issue by MichaelPHartmann** [iexg/IEX-API#797]
### Date/time of issue
Thursday March 21st, 4:11PM PST

### API URL
https://cloud.iexapis.com/beta/stock/market/volume?&token={}

### What you expected to happen
Expected JSON output or message "An API key is required to access this data and no key was provided" as is common in other example URLs.

### What actually happened
403 Forbidden

### Other Information (sample code, links, etc.)
Verified URL from docs as well as tried request from personal project, both return the same URL and 403.

**Comment by joshuablackburn-iex** [comment]
Fixed.
