### ISSUE TITLE
Key Stats API has gain multiple and not percent gain as indicated in field name

### ISSUE THREAD

**Issue by Razzlegames** [iexg/IEX-API#798]
## Summary
`stats` endpoint: `ChangePercent` Values are actually 1/100 * percent (just a raw multiple for gain).

These should be corrected to be percent, or renamed to reflect the different data.

## Details

- on the endpoint `/1.0/stock/{ticker}/stats` several fields are incorrect.  For example Apple shows up as:

```
{
...
  year5ChangePercent: 1.755010393601157,
  year2ChangePercent: 0.4323946298968051,
  year1ChangePercent: 0.10865236426126207,
  ytdChangePercent: 0.24067143415868825,
  month6ChangePercent: -0.0976206213739349,
  month3ChangePercent: 0.1951129565216326,
  month1ChangePercent: 0.14476000469428482,
  day5ChangePercent: 0.0481947130883301,
  day30ChangePercent: 0.14617304868870729
}
```

- But clearly these value are not percent as the `YTD` is around 24%, not 0.24%.  These are not percent change, but instead multiples.  

- I didn't verify the other values such as `insiderPercent`, `institutionPercent`, `EPSSurprisePercent` so they may be correct.

### Date/time of issue
3/21/2019

### API URL
https://api.iextrading.com/1.0/stock/aapl/stats

### What you expected to happen
Values in percent should be scaled correctly

### What actually happened
1/100 * percent is what is displayed

**Comment by joshuablackburn-iex** [comment]
This is as designed. On the quote endpoint we support a parameter to convert. For example .25 to 25.

https://iexcloud.io/docs/api/#quote

We can make this available for the stats endpoint as well.

**Comment by Razzlegames** [comment]
Interesting.  But it's not percent.  I guess it's a "won't fix" due to breaking others reliant on this behavior?
