### ISSUE TITLE
iex-luxcium-api

### ISSUE THREAD

**Issue by Luxcium** [iexg/IEX-API#799]
We are looking for the community to test our work in progress version and open issues to help us improve our code base 

To develop some code using your platform we decided to do a fork of the existing NodeJs implementation and work on that project for ourselves (and for everyone else tanks to the MIT license).
 
We decided to go and publish our work to the world before it is completely 100% perfect and decided to update that work in progress quickly to meet the high standards one must expect of some project with your name on it (even if it is an unofficial version).

The NPM link is : 
https://www.npmjs.com/package/iex-luxcium-api/v/0.4.2

The git hub is : 
https://github.com/luxcium/iex-luxcium-api

We hope to have community support to help us track bugs and problems and improve the code base quality to the highest standards of industry...

We already have put tests in place for up to 93% of the code base and we are about to add more tests to include browser coverage in the automated test ...

The stability of the product should be better in one or two months as we are trying to work as quickly as possible to reach that goal.

**Comment by timpaine-iex** [comment]
closing as stale
