### ISSUE TITLE
total volume

### ISSUE THREAD

**Issue by bkcollection** [iexg/IEX-API#8]
Which api is showing both IEX volume and total overall volume for a stock?

**Comment by joshuablackburn-iex** [comment]
The Stock Quote endpoint shows both of those data points.

Example:  https://api.iextrading.com/1.0/stock/aapl/quote

Docs:  https://iextrading.com/developer/docs/#quote

**Comment by bkcollection** [comment]
`{"symbol":"AAPL","companyName":"Apple Inc.","primaryExchange":"Nasdaq Global Select","sector":"Technology","calculationPrice":"close","latestPrice":161.5,"latestSource":"Previous close","latestTime":"September 11, 2017","latestUpdate":1505088000000,"latestVolume":31182291,"iexRealtimePrice":161.485,"iexRealtimeSize":100,"iexLastUpdated":1505159998913,"delayedPrice":161.36,"delayedPriceTime":1505163592858,"previousClose":161.5,"change":0,"changePercent":0,"iexMarketPercent":0.00943,"iexVolume":294049,"avgTotalVolume":26742434,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":834184322000,"peRatio":18.89,"week52High":164.94,"week52Low":102.53,"ytdChange":0.39044339216530344}`

iexVolume is volume traded in IEX
avgTotalVolume is volume average by a certain days.
This two are different. What I ask is the volume total across all exchanges. The data is shown in yahoo finance and Google finance
https://www.google.com/finance?q=NASDAQ:AAPL
https://finance.yahoo.com/quote/AAPL?p=AAPL

**Comment by joshuablackburn-iex** [comment]
latestVolume represents total market volume.
