### ISSUE TITLE
Include Upcoming Earnings & Other Events

### ISSUE THREAD

**Issue by drobertson123** [iexg/IEX-API#80]
It is pretty critical to know when a new earnings announcement is expected. Dividends and Splits are also extremely important.

Is there any chance you could add a request for future events?

For earnings it would be good to know the following info;
Expected Date
Time of Day:  BMO/REG/AMC
Confirmed or Estimated Date
Date the Announcement was Confirmed
Expected EPS

Thanks, this data is amazing.

**Comment by matroll** [comment]
hey, i was using IEX API with /earnings and the first entry was usually the upcoming EPS report date which was awesome.
it now disappeared in the last 2 weeks or so (first entry is last announced earnings)
any idea why? is that voluntary? 
upcoming earnings date was very helpful

thanks
