### ISSUE TITLE
Declared future dividend for stock not available in historical dividends list or "next"

### ISSUE THREAD

**Issue by estrnod** [iexg/IEX-API#800]
## Summary
Wal-Mart (WMT) which has declared a future dividend (and the ex-div date is in the future also) but is not showing up in IEX API historical stocks lists or next.

### Date/time of issue
As of writing this issue (3/22/2019, 9:43 MST)

### API URL
https://cloud.iexapis.com/beta/stock/WMT/dividends/next?token=...  (returns empty array)

https://cloud.iexapis.com/beta/stock/WMT/dividends/5y?filter=exDate%2CpaymentDate%2Camount&token=...

https://cloud.iexapis.com/beta/stock/WMT/dividends/5y?filter=exDate%2CpaymentDate%2Camount&token=...

### What you expected to happen
To see the upcoming dividend at the top of the list.  Compare to: https://finance.yahoo.com/quote/WMT?p=WMT&.tsrc=fin-srch which shows:  Ex-Dividend Date | 2019-05-09 (and also shown as May 8, 2019 in proprietary TD Ameritrade app, probably due to difference in time zones).

### What actually happened
for 1y:

0 |  
-- | --
exDate | "2018-12-06"
paymentDate | "2019-01-02"
recordDate | "2018-12-07"
amount | 0.52
1 |  
exDate | "2018-08-09"
paymentDate | "2018-09-04"
recordDate | "2018-08-10"
amount | 0.52
2 |  
exDate | "2018-05-10"
paymentDate | "2018-06-04"
recordDate | "2018-05-11"
amount | 0.52

**Comment by theofficejackpot** [comment]
Hi, I see this issue was posted in March... and now Sep 2019, I still see this issue.  

I believe they paid a dividend in sept 2019, but /1y or /next/ does not show it :(. Please advise?


[  
   {  
      "exDate":"2019-05-09",
      "paymentDate":"2019-06-03",
      "recordDate":"2019-05-10",
      "declaredDate":null,
      "amount":0.53,
      "flag":null,
      "currency":"USD",
      "description":null,
      "frequency":"Quarterly",
      "date":"2019-09-16"
   },
   {  
      "exDate":"2019-03-14",
      "paymentDate":"2019-04-01",
      "recordDate":"2019-03-15",
      "declaredDate":null,
      "amount":0.53,
      "flag":null,
      "currency":"USD",
      "description":null,
      "frequency":"Quarterly",
      "date":"2019-09-16"
   },
   {  
      "exDate":"2018-12-06",
      "paymentDate":"2019-01-02",
      "recordDate":"2018-12-07",
      "declaredDate":"2018-02-20",
      "amount":0.52,
      "flag":"No Change QoQ",
      "currency":"USD",
      "description":"Wal-Mart Stores Declares Quarterly Dividend of $0.52 Per Share",
      "frequency":"Quarterly",
      "date":"2019-09-16"
   }
]

**Comment by estrnod** [comment]
What do you know - yes, they did. I missed that. And there is another declared, payable in January. Looks like the div data is a little flaky (I'm using the 5y and not seeing them either.)




---- On Sun, 15 Sep 2019 17:20:25 -0700 notifications@github.com wrote ----



Hi, I see this issue was posted in March... and now Sep 2019, I still see this issue.

I believe they paid a dividend in sept 2019, but /1y or /next/ does not show it :(. Please advise?

[
{
"exDate":"2019-05-09",
"paymentDate":"2019-06-03",
"recordDate":"2019-05-10",
"declaredDate":null,
"amount":0.53,
"flag":null,
"currency":"USD",
"description":null,
"frequency":"Quarterly",
"date":"2019-09-16"
},
{
"exDate":"2019-03-14",
"paymentDate":"2019-04-01",
"recordDate":"2019-03-15",
"declaredDate":null,
"amount":0.53,
"flag":null,
"currency":"USD",
"description":null,
"frequency":"Quarterly",
"date":"2019-09-16"
},
{
"exDate":"2018-12-06",
"paymentDate":"2019-01-02",
"recordDate":"2018-12-07",
"declaredDate":"2018-02-20",
"amount":0.52,
"flag":"No Change QoQ",
"currency":"USD",
"description":"Wal-Mart Stores Declares Quarterly Dividend of $0.52 Per Share",
"frequency":"Quarterly",
"date":"2019-09-16"
}
]

**Comment by theofficejackpot** [comment]
so what's your backup plan in these cases?  I've written a small program to look through the last full year and extrapolate out the next year and then as I get 'next' dividends I update the 'forecasted' data.  just seeing what others are doing.  I don't understand how a basic company like WMT can have such a glaringly obvious defect?? No offense to iexcloud, Makes me wonder/worried if anyone uses this feed for anything other than a hobby??

**Comment by estrnod** [comment]
I highlight "late" declaration dates, which are past their typical interims, but since when they updated the missing one last time, the declared date was left blank or invalid, and my comparison for when the next one should be expected didn't work.


I don't think it's WMT's fault - the next div payable is showing on my TD Ameritrade app.







---- On Sun, 15 Sep 2019 17:47:27 -0700 notifications@github.com wrote ----



so what's your backup plan in these cases? I've written a small program to look through the last full year and extrapolate out the next year and then as I get 'next' dividends I update the 'forecasted' data. just seeing what others are doing. I don't understand how a basic company like WMT can have such a glaringly obvious defect?? No offense to iexcloud, Makes me wonder/worried if anyone uses this feed for anything other than a hobby??

**Comment by jesseorosz** [comment]
> so what's your backup plan in these cases? I've written a small program to look through the last full year and extrapolate out the next year and then as I get 'next' dividends I update the 'forecasted' data. just seeing what others are doing. I don't understand how a basic company like WMT can have such a glaringly obvious defect?? No offense to iexcloud, Makes me wonder/worried if anyone uses this feed for anything other than a hobby??

Their quote data is good, however most third party data (like dividends) is very suspect. They state they're working with a data vendor, however my guess is that they're scraping the data from multiple sources. There's no way a third party vendor would provide such bad data over such a long period of time.

**Comment by evancarter-iex** [comment]
@jesseorosz et al.

We currently do not scrape dividends data. We are *very* aware of the issues regarding dividends and are in the process of expanding our dividend information.

**Comment by evancarter-iex** [comment]
@jesseorosz 
@estrnod   
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
