### ISSUE TITLE
Dividend yield seems to be calculated incorrectly

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#803]
## Summary

step 1. get stat data:

request: https://cloud.iexapis.com/beta/stock/amc/stats/?token=MY_TOKEN
response:
```json
{
"week52change":0.11739100000000001,
"week52high":21.45,
"week52low":11.66,
"marketcap":1600870229,
"employees":40162,
"day200MovingAvg":16.24,
"day50MovingAvg":14.2,
"float":102698574,
"avg10Volume":1462308.4,
"avg30Volume":1840626.33,
"ttmEPS":1.1433,
"ttmDividendRate":0.8,
"companyName":"AMC Entertainment Holdings, Inc.",
"sharesOutstanding":52048000,
"maxChangePercent":-0.203175,
"year5ChangePercent":-0.350302,
"year2ChangePercent":-0.501325,
"year1ChangePercent":0.083453,
"ytdChangePercent":0.168348,
"month6ChangePercent":-0.261765,
"month3ChangePercent":0.228385,
"month1ChangePercent":0.104106,
"day30ChangePercent":0.097668,
"day5ChangePercent":0.004,
"nextDividendRate":null,
"dividendYield":0.05312084993359894,
"peRatio":13.172395696667541,
"nextEarningsDate":"2019-05-01",
"exDividendDate":"2019-03-08"
}
```
**"dividendYield":0.05312084993359894**

Okay, check this...

step 2. get last quote (last close price):
request: https://cloud.iexapis.com/beta/stock/amc/chart/1d?chartByDay=true&chartCloseOnly=true&chartLast=1&token=
response: 
```json
[{
"date":"20190322",
"minute":"15:59",
"label":"3:59 PM",
"high":15.075,
"low":15.065,
"average":15.07,
"volume":1049,
"notional":15808.675,
"numberOfTrades":11,
"marketHigh":15.08,
"marketLow":15.06,
"marketAverage":15.067,
"marketVolume":34261,
"marketNotional":516206.22,
"marketNumberOfTrades":202,
"open":15.065,
"close":15.075,
"marketOpen":15.07,
"marketClose":15.06,
"changeOverTime":null,
"marketChangeOverTime":-0.01843648208469052
}]
```

last price: **"close":15.075**

step 3: get upcoming dividend:

request: https://cloud.iexapis.com/beta/stock/amc/dividends/next?token=MY_TOKEN
response: []

step 4: So there is no current yield. Okay, so where did the number (**"dividendYield":0.05312084993359894**) in the first request come from? Let's try to calculate the last value of the dividend.

get last dividends:
request: https://cloud.iexapis.com/beta/stock/amc/dividends/1m?token=MY_TOKEN
response:
```json
[{
"exDate":"2019-03-08",
"paymentDate":"2019-03-25",
"recordDate":"2019-03-11",
"declaredDate":"2019-02-19",
"amount":0.2,
"flag":"No Change QoQ",
"currency":"USD",
"description":"AMC Entertainment Holdings Declares Quarterly Dividend of $0.20 Per Share",
"frequency":"Quarterly"
}]
```
Now, let's calculate the dividend yield: payout amount / current price * 100 = 0.2 / 15.075 * 100 = **1.32%**

But at the first step we saw that the dividend yield is **0.05%**. Where is truth?

**Comment by McQgit** [comment]
@xxx44yyy  Dividend yield is an annualized amount.  0.20 was the most recent quarterly payment.  So, multiplying 1.32669 x 4 gives 5.3% yield.  Or, figure as (0.2 * 4) / 15.075 * 100.  

Note dividend yield can be calculated many different ways and important to know which you are looking at.  For US equities, it is common to annualize the most recent dividend amount to figure the yield and this is called the 'forward yield'.  This works well with consistent patterns of dividend amounts which is common in the US.  For ETFs, other funds and non-US companies, it is more common to add up the past year's dividends and divide that by the current price to give a 'trailing yield'.  

A further issue is that special dividends should normally be ignored but it's not unusual to see automated systems include specials in the yield they show.   Your example AMC has a large special dividend Sept 2018.

**Comment by xxx44yyy** [comment]
@McQgit Ok, your calculations: **5.3%**
My calculations:
- current yield: it does not exist, because no future dividend is declared
- the yield of the last dividend: **1.25%**
IEX API calculations: **0.05%**

I do not understand which calculations are correct and why?

**Comment by McQgit** [comment]
@xxx44yyy The IEX number was 0.053... - which is 5.3% (not 0.05%).  Use the 'displayPercent' query string parameter if you want percent figures multiplied by 100.

As for 'current yield' - there is no single meaning for what that is.  Yields are forward or trailing as I described.  Sometimes the forward yield is called the 'indicated yield' or even 'annualized yield'.  But, your idea that a 'current yield' only applies to future dividends doesn't make sense.  Plenty of companies pay dividends regularly but their yield isn't zero after their last one but before they announce the next one.  An upcoming dividend, if available, is often used for a forward yield - but if no future dividend is announced the most recent past dividend is used.  A future dividend is never used when calculating the trailing yield.

I am describing the common uses of dividend yields.  None is 'correct' - you choose the one that makes sense for your situation.

**Comment by xxx44yyy** [comment]
Okay, thanks you very much!

**Comment by xxx44yyy** [comment]
@McQgit For example, XYZ reports that a dividend (upcoming dividend) of$ 1 will be paid on may 1, 2019. The price of stock XYZ is $100 today. How to call the yield in this case (1%)? I would call it current yield, because it does not fit the term trailing and forward dividend yields.

**Comment by McQgit** [comment]
@xxx44yyy  Call it what you like but more commonly that is just called the forward or indicated yield.  That is, it is the amount of dividend you can expect to receive in the upcoming year should you buy today and the dividend amount is not changed.  Further, a $1 dividend, if paid quarterly, for a share price of $100 is a 4% yield (not 1%).  

You sometimes see the term 'current yield' when looking at historical data to clarify it is the latest rather than a past yield.  That is, if 3 years ago the above was paying $0.50 per quarter with a share price of $60, it had a yield then of 3.33%.  But, 'current yield' has no specific calculation tied to it.

**Comment by xxx44yyy** [comment]
@McQgit Thanks for the detailed answer!
