### ISSUE TITLE
IEX Cloud V2 down: Saturday 3/23?

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#804]
## Summary
Virtually every call I make from my Excel API (using my token) is resulting in an error. This spans stats, quotes, company, dividends, etc.
It would be helpful if notice is provided when the API has been disabled

**Comment by evancarter-iex** [comment]
Working fine here. What issue are you seeing? What was the error?

**Comment by evancarter-iex** [comment]
Closing this. API is currently online. If you have the error messages let me know and Ill look into the issue.

**Comment by ModelsRUs** [comment]
Please re-open this issue. Webservice is still not functioning in Beta.

**Comment by ModelsRUs** [comment]
Failed: =WEBSERVICE(https://cloud.iexapis.com/beta/stock/ABBV/company?filter=companyName&token=xxxxx). Result = #Value!
Failed: =WEBSERVICE(https://cloud.iexapis.com/beta/stock/MSFT/dividends/1Y?filter=amount&token=xxxxx). Result = #Value!
Failed: =WEBSERVICE(https://cloud.iexapis.com/beta/stock/AMZN/stats?filter=dividendYield&token=xxxxx). Result = #Value!
Failed: =WEBSERVICE(https://cloud.iexapis.com/beta/stock/GOOG/earnings?filter=EPSReportDate&token=xxxxx). Result = #Value!
Failed: =WEBSERVICE(https://cloud.iexapis.com/beta/stock/T/quote?filter=latestPrice&token=xxxxx). Result = #Value!

Last one: (not sure if my syntax is correct on this one)
=Webservice(https://cloud.iexapis.com/beta/stock/ABBV/chart/1m?format=csv&filter=date,close,volume,changePercent&token=xxxxx). Result = #Value!

**Comment by evancarter-iex** [comment]
@ModelsRUs All those calls are working for us, I also tried from a wifi access point and it works fine as well

**Comment by ModelsRUs** [comment]
Have you tried Webservice? Is there an issue with my token? There's 
obviously an issue, which has nothing to do with Excel, since (as I've 
said)"

  * V1 (no token) is working fine
  * Issue exists in multiple workbooks
  * Nothing changed on my end since last Friday when V2 was working fine

Thank you.
- *Paul*
   (917) 476-4468
=================================================

**Comment by evancarter-iex** [comment]
Unclear. Are you able to do those requests via a web browser?

**Comment by ModelsRUs** [comment]
Sorry Evan - I'm unclear as to what you're asking. I don't use IEX with 
a web browser.

As noted in issue #804, I'm using the Webservice function in Excel (over 
my wireless internet connection, which is working fine) to import data.
I've been using multiple workbooks with IEX for many months, and several 
weeks ago, switched the retrieval of some data (at your suggestion) from 
V1 to V2 Beta, which incorporates the token.
On Saturday, all V2 calls ceased functioning. V1 data (using the same 
Webservice function in Excel) is still working, which is why I'm 
wondering if there's an issue with my token. The same issue exists in 
all workbooks where IEX is utilized.

Thank you,
- *Paul*
   (917) 476-4468
=================================================

**Comment by evancarter-iex** [comment]
Paul,

I just checked. You have reached your message limit for the month and thus any additional request requires an upgrade.  If you login to https://iexcloud.io you will see your message usage in the console.

**Comment by ModelsRUs** [comment]
Thank you Evan.
I was told by IEX support that Webservice calls were not subject to V2 
limits. In any event, it's highly unlikely I made anything in excess of 
500 calls, much less 500,000 since the beginning of the month. What 
constitutes a "Message"?

Thank you,
- *Paul*
   (917) 476-4468
=================================================

**Comment by ModelsRUs** [comment]
Hi Evan
Thanks again for all your help. I checked my "message" usage, and see the bulk of it resulted from when I was converting my models from V1 to V2. If I continue to buck up against my limit, I will certainly consider upgrading.
