### ISSUE TITLE
Tops Endpoint returns empty array

### ISSUE THREAD

**Issue by josephmaxim** [iexg/IEX-API#805]
Date: Saturday, March 23, 2019. 8:24pm
<img width="830" alt="Screen Shot 2019-03-23 at 8 31 30 PM" src="https://user-images.githubusercontent.com/10732770/54873348-d7188c00-4daa-11e9-9583-bdb22d35c0bd.png">

Or is the tops endpoint only available during trading hours?

**Comment by evancarter-iex** [comment]
@josephmaxim TOPS endpoint will only return data during market hours.
