### ISSUE TITLE
How is week52change calculated?

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#807]
## Summary

request: https://cloud.iexapis.com/beta/stock/jnj/stats/?token=MY_TOKEN
response:
```json
{
"week52change":0.094404,
"week52high":148.99,
"week52low":118.62,
...
}
```

request: https://cloud.iexapis.com/beta/stock/aapl/stats/?token=MY_TOKEN
response: 
```json
{
"week52change":0.1583,
"week52high":233.47,
"week52low":142,
...
}
```

How is week52change calculated?

**Comment by McQgit** [comment]
@xxx44yyy A 52 week change is the difference between the current price and the one 52 weeks ago.  Has nothing to do with 52 week high and low.  If you look at a one-year chart (anywhere) for either of those tickers you'll see that's how much their price increased (using closing prices).

**Comment by xxx44yyy** [comment]
> @xxx44yyy A 52 week change is the difference between the current price and the one 52 weeks ago. Has nothing to do with 52 week high and low. If you look at a one-year chart (anywhere) for either of those tickers you'll see that's how much their price increased (using closing prices).

Thank you! Bad documentation, I have a lot of questions...
