### ISSUE TITLE
How can I receive 15 minute delayed data for the main indices (S&p 500, Dow Jones, etc)

### ISSUE THREAD

**Issue by mfhawley** [iexg/IEX-API#808]
## Summary
Is there a way to get returned **JSON** data from iexcloud API for the major indices such as the S&P500, Dow Jones, Nasdaq Composite, Russell 2000, etc?
Even 0-15 minute delayed data would be acceptable.

It would be even more awesome to get OHLCV data but at the least, the close.

## Details
Intraday close or OHLCV data would be awesome.

Historical data would also be awesome.

### Date/time of issue
03/24/2019

### API URL
Its seems these should work for returning the most updated close price almost to the minute but it is not specifically JSON data which is an issue.

The below also may not actually be the indices but instead ETF of the indices. I also can't find the russell 2000.

https://cloud.iexapis.com/beta/stock/dia/price?token=

https://cloud.iexapis.com/beta/stock/spy/price?token=

https://cloud.iexapis.com/beta/stock/oneq/price?token=

### What you expected to happen
Be returned OHLCV data throughout the day for the 3 or 4 main indices.

### What actually happened
I found some jerry-rigged calls I could make (above) but they don't return JSON data. Just a number

**Comment by McQgit** [comment]
You could use the 'quote' endpoint along with 'filter' to select a few indicators.  Example:

[]https://cloud.iexapis.com/beta/stock/market/batch?symbols=dia,spy,iwm&types=quote&filter=open,high,low,close,latestVolume&token=(token)

Note latestVolume was zero over the weekend.  You'll have to report that as a bug yourself.  It works in the v1.0 api. 

A google of 'Russell 2000 ETF' told me IWM or VTWO might suffice.  IWM trades far more volume.

**Comment by evancarter-iex** [comment]
We don't have S&P or other major indices currently and are unlikely to have in the near future. This data is essentially monopolized, so pricing is very high and requires a direct contract between each consumer and the index provider regardless of who actually supplies the data. The major index providers charge over $10k a year for delayed data, and that isn’t a price point we want to work with for our initial users.

An alternative is to display ETFs that match those indices, such as SPY for the S&P 500, DIA for Dow Jones, and IWM for Russell 2000

**Comment by mfhawley** [comment]
Thank Evan. I think ETFs to match that is perfectly fine. McQgit has a good idea there. 
However, I noticed an issue with that call regarding what is being updated. It seems only the Volume and Low are the only things _frequently_ updating. 
The Open should of course stay the same while the Close should **always** be changing with the High changing as the price is increasing and making new highs. 

Below is some time sampling I did this morning of 3-25-19 and as you can see the high and close are remaining constant through the market price is changing and making new high during part of this time frame (specifically between the last 4 or 5 time samples)

`10:00AM EST
{"DIA":{"quote":{"open":254.69,"high":255.66,"low":253.971,"close":254.96,"latestVolume":807475}},"SPY":{"quote":{"open":278.89,"high":280.02,"low":278.26,"close":279.25,"latestVolume":15458187}},"IWM":{"quote":{"open":149.48,"high":149.99,"low":148.663,"close":149.62,"latestVolume":4813120}}}

10:05AM EST
{"DIA":{"quote":{"open":254.69,"high":255.66,"low":253.83,"close":254.96,"latestVolume":862796}},"SPY":{"quote":{"open":278.89,"high":280.02,"low":278.12,"close":279.25,"latestVolume":16115100}},"IWM":{"quote":{"open":149.48,"high":149.99,"low":148.62,"close":149.62,"latestVolume":5004223}}}

10:09 EST
{"DIA":{"quote":{"open":254.69,"high":255.66,"low":253.83,"close":254.96,"latestVolume":901953}},"SPY":{"quote":{"open":278.89,"high":280.02,"low":278.12,"close":279.25,"latestVolume":16587807}},"IWM":{"quote":{"open":149.48,"high":149.99,"low":148.62,"close":149.62,"latestVolume":5557367}}}

10:12 EST
{"DIA":{"quote":{"open":254.69,"high":255.66,"low":253.78,"close":254.96,"latestVolume":931477}},"SPY":{"quote":{"open":278.89,"high":280.02,"low":277.94,"close":279.25,"latestVolume":17224868}},"IWM":{"quote":{"open":149.48,"high":149.99,"low":148.62,"close":149.62,"latestVolume":5781934}}}

10:16 EST
{"DIA":{"quote":{"open":254.69,"high":255.66,"low":253.72,"close":254.96,"latestVolume":987835}},"SPY":{"quote":{"open":278.89,"high":280.02,"low":277.94,"close":279.25,"latestVolume":18921699}},"IWM":{"quote":{"open":149.48,"high":149.99,"low":148.62,"close":149.62,"latestVolume":6160707}}}

10:28 EST
{"DIA":{"quote":{"open":254.69,"high":255.66,"low":253.66,"close":254.96,"latestVolume":1115825}},"SPY":{"quote":{"open":278.89,"high":280.02,"low":277.83,"close":279.25,"latestVolume":21582514}},"IWM":{"quote":{"open":149.48,"high":149.99,"low":148.46,"close":149.62,"latestVolume":6974168}}}

11:25 EST
{"DIA":{"quote":{"open":254.69,"high":255.66,"low":253.57,"close":254.96,"latestVolume":1692257}},"SPY":{"quote":{"open":278.89,"high":280.02,"low":277.71,"close":279.25,"latestVolume":31824957}},"IWM":{"quote":{"open":149.48,"high":150.155,"low":148.405,"close":149.62,"latestVolume":11468402}}}

11:31 EST
{"DIA":{"quote":{"open":254.69,"high":255.66,"low":253.57,"close":254.96,"latestVolume":1719359}},"SPY":{"quote":{"open":278.89,"high":280.02,"low":277.71,"close":279.25,"latestVolume":33547592}},"IWM":{"quote":{"open":149.48,"high":150.52,"low":148.405,"close":149.62,"latestVolume":12182010}}}

11:46 EST
{"DIA":{"quote":{"open":254.69,"high":255.89,"low":253.57,"close":254.96,"latestVolume":1839805}},"SPY":{"quote":{"open":278.89,"high":280.185,"low":277.71,"close":279.25,"latestVolume":36022660}},"IWM":{"quote":{"open":149.48,"high":151.32,"low":148.405,"close":149.62,"latestVolume":13241803}}}
`

**Comment by joshuablackburn-iex** [comment]
Why would the official closing price change during the day if the stock hasn't closed yet? If anything, close should be null.

**Comment by mfhawley** [comment]
Given the volume and low are changing throughout the day in that API call, it appears that the data returns the updated single day OHLCV data at that progress of the day.

So it would be returning the latest close price at any give moment throughout the day. Not just end of day data.

Example below.
![20190327_142053](https://user-images.githubusercontent.com/14339122/55113240-cbbfac00-509b-11e9-8205-185a25851209.jpg)

**Comment by joshuablackburn-iex** [comment]
If you refer to the documentation for /quote
https://iexcloud.io/docs/api/#quote

It shows that open and close refer to the official opening and closing price of the stock. This is not a rolling candle.  The stock quote endpoint is returning data every time the stock has a trade or quote update.

If the goal is to show OHLCV candle throughout the day, the intraday prices endpoint will do just that.
https://iexcloud.io/docs/api/#intraday-prices
