### ISSUE TITLE
Incorrect marketCap

### ISSUE THREAD

**Issue by bhysyq** [iexg/IEX-API#81]
The `marketCap` data may not be correct for some stocks.
For example: https://api.iextrading.com/1.0/stock/market/batch?symbols=AAPL,DCIX&types=quote&range=1m&last=1&filter=symbol,marketCap,latestTime
`DCIX` should be around `8.24M`, but the result says `33` which is not correct.

**Comment by joshuablackburn-iex** [comment]
Thank you for bringing this to our attention.  We will reach out to our data provider to address this issue.  It looks like we are seeing 3 shares for total outstanding shares, and this is causing marketcap to be miscalculated.

**Comment by joshuablackburn-iex** [comment]
This has been resolved.
