### ISSUE TITLE
C# SSE Streaming sample code

### ISSUE THREAD

**Issue by RobinhoodFR** [iexg/IEX-API#810]
## Summary
C# SSE Streaming sample code
I'm searching for a sample code in C# in order to benefit from SSE Streaming from IEXCloud. I have an appropriate account ("LAUNCH").

## Details
Unable to find existing C# sample code for running SSE Streaming
### Date/time of issue
March 25 2019

### API URL
Sample: "https://cloud-sse.iexapis.com/beta/last?symbols=snap&token=MYTOKEN"

### What you expected to happen
To benefit from realtime datapoint ("last" in my API URL example)

### What actually happened
N.A

### Other Information (sample code, links, etc.)
Thanks by advance! ++

**Comment by evancarter-iex** [comment]
@RobinhoodFR We dont use C# here so I can only point you to what Google is showing. Eyeballing it, something like this https://gist.github.com/dmiddlecamp/b698292a5f579e8d288c seems like it might work.

**Comment by RobinhoodFR** [comment]
Hello!

Well done it works like a charm :-)

Have a nice day++

Le lun. 25 mars 2019 à 16:02, evancarter-iex <notifications@github.com> a
écrit :

**Comment by RobinhoodFR** [comment]
Issue solved by Iexcloud support.

Using this ressource: https://gist.github.com/dmiddlecamp/b698292a5f579e8d288c

It seems to works perfectly.
