### ISSUE TITLE
Recommendation trends dates format

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#811]
## Summary
No documentation on what to do with the datestamps in recommendation trends API call

## Details

The API returns fields like 'consensusEndDate' in what looks like MS? Nothing I can find to actually tell us though, and how to parse it.
### Date/time of issue

25/3/19.

### API URL

/stock/{symbol}/recommendation-trends

### What you expected to happen

Return a parsed datetime, or provide docs to tell us the format.

### What actually happened

Neither, as far as I can tell!

**Comment by McQgit** [comment]
@professorDante  The docs show unix style epoch timestamps in milliseconds.  Are you seeing something else?

[]https://www.epochconverter.com/

[]https://iexcloud.io/docs/api/#recommendation-trends

In php, I format them like:  
`$dmy  = date("n/j/Y",$epochTimeMs/1000);`

Note their stamps are often GMT and php adjusts timezones depending on your config.  If your preferred language does similar careful to avoid shifting stamp a day.  This can more easily happen when the 'time' portion of the epoch is midnight.

**Comment by professorDante** [comment]
"The docs show unix style epoch timestamps in milliseconds."

I must be blind - where do they say it's an epoch timestamp?

**Comment by McQgit** [comment]
@professorDante  I can tell just by looking at them - same as if I saw 12/31/2019 I'd know without being told its mm/dd/yyyy.  Did you try converting one using the link I provided to verify?

**Comment by professorDante** [comment]
All good - just checking it wasn't in the docs. That's great you can tell, but not everyone knows it's an epoch time. Like me. 

I'm using python so I can convert it no probs.
