### ISSUE TITLE
Fiscal period in earnings call doesn't adhere to docs

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#812]
## Summary
FiscalPeriod doesn't correspond to format given in the docs.

## Details

Cannot work out the format for the FiscalPeriod attribute. Docs state Q# YYYY but getting it like this : 0 2Q118
### Date/time of issue
25/3/19

### API URL
/stock/TTD/earnings/4

### What you expected to happen

Should be returned in the designated format Q# YYYY

### What actually happened

Returns seemingly gibberish.

**Comment by joshuablackburn-iex** [comment]
Are you using sandbox for this call? Sandbox is test data and will be randomized. I'm unable to reproduce this in production.

**Comment by professorDante** [comment]
Yes, Sandbox. Just because it is randomized, doesn't mean it should be unparseable!
