### ISSUE TITLE
How many symbols are allowed in filter arg to APIs?

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#814]
## Summary

Cannot find docs on how many symbols can be passed in 1 API call via filter

## Details

/stock/{symbol}/dividends/{range}. Can this be passed ?symbols=AAPL, FB, and if so, how many?

### Date/time of issue
25/3/19

### API URL
/stock/{symbol}/dividends/{range}

**Comment by McQgit** [comment]
@professorDante  Use the 'batch' function for up to 100 symbols at a time:
[](https://iexcloud.io/docs/api/#batch-requests)

Example:
[]https://cloud.iexapis.com/beta/stock/market/batch?symbols=ibm,msft,aapl&types=quote,ohlc,dividends&range=6m&token=(token)

**Comment by McQgit** [comment]
Oh, I forgot the link to the related docs:
[]https://iexcloud.io/docs/api/#batch-requests

**Comment by professorDante** [comment]
brill, thank you!
