### ISSUE TITLE
TM (Toyota Motor) missing from Dividends (Beta API)

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#815]
## Summary
TM (Toyota Motor) missing from Dividend Data

## Details
No dividend data returned

### Date/time of issue
March 25 7:00PM PST

### API URL
https://cloud.iexapis.com/beta/stock/tm/dividends/1y?token=

### What you expected to happen
Return data

### What actually happened
Empty result

### Other Information (sample code, links, etc.)

It's in the old API:
https://api.iextrading.com/1.0/stock/TM/dividends/1y

https://www.nasdaq.com/symbol/tm/dividend-history

**Comment by estrnod** [comment]
Sounds like my last bug, #800

**Comment by jesseorosz** [comment]
yea seems there are some issues with dividend data @estrnod 

hopefully it gets fixed soon - i have many plans for this data!

**Comment by joshuablackburn-iex** [comment]
Thank you for your patience on this. We are working with our data partner to fill in the data gaps.

**Comment by evancarter-iex** [comment]
@estrnod & @jesseorosz  TM now has dividend data. Thanks for your patience on this.
