### ISSUE TITLE
IPO Calendar JSON case mismatch

### ISSUE THREAD

**Issue by hamermike** [iexg/IEX-API#817]
## Summary
The case of the "viewData" array object names are not camelCase. This is the case in the documentation and response.

## Details
```
"viewData": [
    {
        "Company": "VACCINEX, INC.",
        "Symbol": "VCNX",
        "Price": "$12.00 - 15.00",
        "Shares": "3,333,000",
        "Amount": "44,995,500",
        "Float": "11,474,715",
        "Percent": "29.05%",
        "Market": "NASDAQ Global",
        "Expected": "2018-08-09"
    },
    ...
]
```

### Date/time of issue
3/27/2019 12:04 AM EST

### API URL
https://cloud.iexapis.com/beta/stock/market/upcoming-ipos

### What you expected to happen
Expected JSON names to be camelCase. "company", "symbol", etc.

### What actually happened
JSON names are not camelCase. "Company", "Symbol", etc.

### Other Information (sample code, links, etc.)
The rawData array in the same response is returning the data correctly with camelCase.

**Comment by evancarter-iex** [comment]
This should be fixed now. Thanks for the information.
