### ISSUE TITLE
Efficiently pull max available end of (week/month/quarter/year) prices

### ISSUE THREAD

**Issue by ngburke** [iexg/IEX-API#820]
## Summary
My application needs to pull end of year price data for a symbol as far back as is available. The historical prices endpoint can inefficiently achieve this through lots of calls by date, or perhaps by using `max` coupled with `chartInterval`. I would like a more efficient method.

## Details
Ideally something along the lines of `https://sandbox.iexapis.com/beta/stock/aapl/chart/max?chartByDay=true&interval=[yearly|monthly|weekly|daily]` would be possible. I would expect in my use case (yearly) the data returned to go back say 20yrs, thus returning 20 data points at a weight of 2 each. Another useful ability would be to provide a start/end date for the data instead of `max` so I could limit the fetch. 

### Date/time of issue
3/27/2019 4:30pm

**Comment by ngburke** [comment]
My current method to pull the lats price for a security in a given year is to walk this query back from 12/31/yyyy (cloud.iexapis.com/stable/stock/AAPL/chart/date/20181231?chartByDay=true)
) until I hit a date that returns data. It's pretty ugly, but it works. Is there any recommendation on a better way until the proposed change in this issue is made?

**Comment by pmn4** [comment]
Similarly, I would like end-of-month prices for a security as far back as there is data.
In the short term, I can live with getting all data and plucking the dates I need, but as I grow, that will be an expensive call.

**Comment by ngburke** [comment]
Any updates on this?

**Comment by timpaine-iex** [comment]
folding into https://github.com/iexg/IEX-API/issues/221
