### ISSUE TITLE
DividendNext ex-date incorrect on BOOM

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#821]
## Summary
Ex-date is incorrect on BOOM.
IEX API has it as 2019-03-29 whereas it's 2019-03-28.

## Details
{"exDate":"2019-03-29","paymentDate":"2019-04-16","recordDate":"2019-03-31","declaredDate":"2019-03-15","amount":0.02,"flag":"No Change QoQ","currency":"USD","description":"DMC Global Declares Quarterly Dividend of $0.02 Per Share","frequency":"Quarterly","symbol":"BOOM"}

### Date/time of issue
March 28 2019 14:00 UTC

### API URL
https://cloud.iexapis.com/beta/stock/boom/dividends/next?token=

### What you expected to happen
Return correct ex div date

### Other Information (sample code, links, etc.)
https://www.nasdaq.com/symbol/boom/dividend-history
https://www.streetinsider.com/dividend_history.php?q=BOOM
https://www.marketbeat.com/stocks/NASDAQ/BOOM/

**Comment by evancarter-iex** [comment]
This has been fixed.
