### ISSUE TITLE
Missing Dividend Data

### ISSUE THREAD

**Issue by kbeck1** [iexg/IEX-API#825]
## Summary
Missing dividend data for the following: 
CVX, OKE, TM, V, XOM

Maybe more that I don't currently follow.

### Date/time of issue
March 29, 2019 18:10 UTC

### API URL

https://cloud.iexapis.com/beta/stock/{symbol}/dividends?token=xxxxxx

### What you expected to happen
Report dividend data.

### What actually happened
Consistently  returns an empty array [].

### Other Information (sample code, links, etc.)
Dividend information can be found here https://www.nasdaq.com/quotes/dividend-history.aspx

**Comment by evancarter-iex** [comment]
@kbeck1 You are missing the {range} on your query https://iexcloud.io/docs/api/#dividends For example: https://cloud.iexapis.com/beta/stock/{symbol}/dividends/1y?token=xxxx returns data for those stocks
