### ISSUE TITLE
Fund Ownership vs. Institutional Ownership

### ISSUE THREAD

**Issue by Jacyle** [iexg/IEX-API#826]
## Summary
When I look at the API Documentation, I can't tell the difference between Fund Ownership and Institutional Ownership.

What is the difference?

**Comment by evancarter-iex** [comment]
@Jacyle is this in regards to the old API or the new Cloud?

**Comment by Jacyle** [comment]
The new Cloud API

**Comment by joshuablackburn-iex** [comment]
Institutional ownership is for firms considered buy-side or sell-side.

Fund ownership are for all other firms, such as mutual or pension funds, not classified as buy-side or sell-side.
