### ISSUE TITLE
stock/market/previous In IEX API vs CloudIEX

### ISSUE THREAD

**Issue by RuiFigueiredoAlgo** [iexg/IEX-API#828]
**In IEX API stock/market/previous**

https://api.iextrading.com/1.0/stock/market/previous

It will bring the closing prices for the previous session from all major Stocks Exchanges Nyse, Nasdaq, etc. 

> The ancient API returns around 5.800 symbols

**Now in IEX Cloud**

https://cloud.iexapis.com/beta/stock/market/previous?token=my_token

It brings all stocks even from OTC, pinksheets, etc.

> In these new API it returns around 48.000 symbols !!!!

Can there be a compatibility option in order to get the same base symbols as the old IEX API 
stock/market/previous 

Examples:
https://cloud.iexapis.com/beta/stock/market/previous_compatibility?token=my_token
or
https://cloud.iexapis.com/beta/stock/market/previous?token=my_token&version=iexapi
or 
https://cloud.iexapis.com/beta/stock/market/previous_old?token=my_token

Thanks for your attention.

Kind regards.

**Comment by joshuablackburn-iex** [comment]
We will update this to match, then provide additional endpoints for other markets.

**Comment by RuiFigueiredoAlgo** [comment]
Any news about this ?

I'm still using the old 
https://api.iextrading.com/1.0/stock/market/previous

**Comment by idratherjack** [comment]
Any update on this? 

Additionally I also noticed the /previous endpoint now returns old dates? It took me 3 attempts (300K in calls) to find out..:(

This is what I see (June 16th, 2019) when I call the eindpoint on /stable/ now : 
{"A":{"symbol":"A","date":"**2019-02-19**","open":78,"high":78.32,"low":77.41,"close":77.52,"volume":2967968,"uOpen":78,"uHigh":78.32,"uLow":77.41,"uClose":77.52,"uVolume":2967968,"change":null,"changePercent":null},

**Comment by RuiFigueiredoAlgo** [comment]
Any news about this ?

I'm still using the old
https://api.iextrading.com/1.0/stock/market/previous

But today it is forbiden

**Comment by evancarter-iex** [comment]
This is resolved.
