### ISSUE TITLE
LatestVolume sometimes resets to 0 (zero) early in the morning

### ISSUE THREAD

**Issue by RuiFigueiredoAlgo** [iexg/IEX-API#831]
I've noticed that sometimes **lastestvolume** from type **"quote"** resets to 0

cloud.iexapis.com/beta/stock/market/batch?symbols="  & stocks & "&types=quote&token=my_token

> High Low not updating also!
As can be seen on the image **IExRealTimePrice is 1,77** ! why is **High field only 1,45 ?**

Thanks for your attention.

Kind regards

![Untitled](https://user-images.githubusercontent.com/47220667/55338416-9a2e5280-5498-11e9-817c-f07c5abf055f.png)

**Comment by RuiFigueiredoAlgo** [comment]
What about Low High? 
Should not be current session Low/High till the request/timeframe  ?

If it is, it is falty, as you can see in the printscreen 
IEXRealTimePrice equals 1,77 and High equals 1,45 should be at least 1,77

Thanks,

Kind regards.

**Comment by evancarter-iex** [comment]
As per the documentation here: https://iexcloud.io/docs/api/#quote High/Low is 15 minutes delayed.

**Comment by RuiFigueiredoAlgo** [comment]
Thanks for the answer, Can live well with that delay. 

I'll use my database records instead using Iexrealtime.

**Comment by evancarter-iex** [comment]
We haved deployed a fix for the volume issue. If it happens again please let us know.
