### ISSUE TITLE
Batch Requests

### ISSUE THREAD

**Issue by candrwow** [iexg/IEX-API#832]
## Summary

I use Batch Requests with type "sentiment",response is inconsistent.

## Details
symbols is "AAPL,BILI",type is "Daily",types is  "sentiment",AAPL is 
`"sentiment": {
            "sentiment": 0.10715294117647059,
            "totalScores": 17,
            "positive": 0.94,
            "negative": 0.06
        }`
,a JsonObject,but BILI is a null JsonArray:
`"sentiment": []`
I use Gson to parse response,can you change null Array to JSONObject.

**Comment by evancarter-iex** [comment]
@candrwow sorry for the long delay. This has been fixed for a while but forgot to close this bug report.
