### ISSUE TITLE
Intraday data missing for Agilent Technologies "A" for 4/3/2019

### ISSUE THREAD

**Issue by scottyrotten6** [iexg/IEX-API#833]
## Summary
Intraday data is missing for Agilent Technologies "A" for 4/3/2019. Doesn't seem to be missing for any other symbols but I did not check all of them

## Details
Not much to add
### Date/time of issue
4/3/2019

### API URL
https://api.iextrading.com/1.0/stock/A/chart/date/20190403/?filter=minute,marketOpen,marketHigh,marketLow,marketClose,marketVolume&format=csv

### What you expected to happen
all other symbols return a file with data, and this symbol returns data for all other dates. There is just something wrong with A for 20190403.

### What actually happened
got a file with the minutes returned but no other data

**Comment by evancarter-iex** [comment]
The old api is being decommissioned. Please use https://iexcloud.io and see if the problem repeats and refile the issue if it does.

**Comment by scottyrotten6** [comment]
https://cloud.iexapis.com/beta/stock/A/chart/date/20190403/?token=my_token&format=csv

I did it in iexcloud.io and it is missing all the market data. If I do it for 0402 all the market data is there.

**Comment by scottyrotten6** [comment]
I figured out the filters now. So here is the original query in the new format. Same issue.

https://cloud.iexapis.com/beta/stock/A/chart/date/20190402/?token=my_token&filter=minute,marketOpen,marketHigh,marketLow,marketClose,marketVolume&format=csv
