### ISSUE TITLE
Inconsistent Data in Gainers/Losers after midnight

### ISSUE THREAD

**Issue by ckz8780** [iexg/IEX-API#834]
## Summary

I see this issue has been reported multiple times before but they're all marked as closed and resolved. Unfortunately I'm still seeing inconsistent data in the top gainers and losers using the `/stock/market/list/` endpoints. 

## Details

There are symbols missing from both the gainers and losers list which are shown in the symbol list in ref-data. For example, today the top loser according to IEX is ODP at -23.61%. On Finviz for example, OPTT, NSPR, AVEO and RBZ all lost more than ODP and are in the IEX symbol list, but don't show up in the top losers. This is a similar situation to the top gainers, and I assume most active as well though I haven't looked at that in detail. Either way, the top gainers/losers is very inconsistent and unreliable from what I can see which is unfortunate because I'd really like to display it on my landing page.

### Date/time of issue

Original 4/5/2019 12:29AM, but occurs continually/randomly/sporadically

### API URL

`/stock/market/list/*` endpoints

### What you expected to happen

Top gainers and losers should be accurate (losers shown below as an example):

https://i.imgur.com/1bo6JvS.png

### What actually happened

Top gainers and losers are not accurate. Both are missing items, and losers have stocks that went up in them:

https://i.imgur.com/ZeR9kwn.png

### Other Information (sample code, links, etc.)

Using pyEX and have tested with my live production key. Please let me know if any more info is needed. Thanks!

**Comment by ckz8780** [comment]
Re: title change - you're right that this particular occurrence was after midnight, however just FYI I've also seen this problem during market hours and extended hours (particularly missing symbols which are in the IEX list).

Thanks for looking into it!

**Comment by ckz8780** [comment]
@evancarter-iex any chance we could get an update on this? It's still a problem and I'm now a paying subscriber on the Grow plan and seeing this issue during market hours: https://i.imgur.com/qmlIlUn.png

This is quite embarrassing for my application since this is right on the homepage in front of the login wall. Could we escalate this issue to give it more priority?

Thanks!!

**Comment by evancarter-iex** [comment]
@ckz8780 We are working on this as we speak. We believe something we did to fix the off hours change affected this.

**Comment by ckz8780** [comment]
Awesome! Thank you! Very glad to hear it's on its way to being fixed as this is a really useful feature and can be used for all kinds of awesome stuff :) 

Cheers!

**Comment by evancarter-iex** [comment]
@ckz8780 We just deployed something that we think will fix it. Please let me know if its looking better from your end.

**Comment by ckz8780** [comment]
@evancarter-iex it looks better for sure though there are still a few missing tickers - I haven't checked if they are on your list but three of them missing right now (just before midnight) which are on Finviz's list are PT, RHE and LGL ... everything else appears to be in order though so I'll monitor for a few days and see if it is more accurate.

Thank you!!

**Comment by ckz8780** [comment]
Update: There are still some missing symbols which show up at the `/ref-data/symbols` endpoint:

My top gainers today as of 11:55AM EDT: https://i.imgur.com/cJq0tYg.png

Finviz top gainers: 
![image](https://user-images.githubusercontent.com/5307491/57540754-6eb24980-731b-11e9-9401-641d8eb17003.png)

Highlighted items are not in the top gainer list returned from IEX at all. Red ticks are items that were not returned but exist in the `/ref-data/symbols/` list

Seems there are still some bugs to work out on this one. 

Let me know if there's anything I can do to help! Thanks :)

**Comment by evancarter-iex** [comment]
@ckz8780 hmm okay we will keep poking at it. Sorry about this.

**Comment by joshuablackburn-iex** [comment]
@ckz8780 I do not classify our list not matching Finviz as a bug. Finviz is not a standard we set out to match. Most sites use different criteria for building the gainers/losers list. Yahoo Finance, for example, has a default criteria of greater than 3% gain, US stock, mid cap or greater market cap, and volume greater than 15,000 shares. (https://finance.yahoo.com/gainers)

Our criteria is US common stock, intraday market cap >= 3 billion, and minimum volume of 20,000 shares. We will update our docs to reflect this criteria. We will also add an enhancement to our roadmap to define custom criteria, and add more lists.

**Comment by ckz8780** [comment]
Ah well that makes sense! It's the market cap and volume most likely that is causing the discrepancy, but yes that'd be good to be able to specify. Many top gainers of interest to active traders are microcap, nanocap, small cap and low volume as they're the most volatile and make great trading stocks, so it'd be nice to be able to show them.

One thing I'm still unsure about though, is why occasionally it seems that the list of gainers/losers gets trimmed after market hours. Sometimes I'll a full list of 10 items on my site all day, but later in the evening (usually after 8pm), the same list has been whittled down to only 4-5 symbols and the ones that were on it before are gone. That was the original reason for this ticket - that the data coming back fdrom IEX seems inconsistent. I'll keep an eye out and see if this issue is still present with the updates you've made to this issue and knowing the criteria will give me a better understanding of whether it truly is a bug. 

Thanks for the help!
