### ISSUE TITLE
Intermittent quotes of FB

### ISSUE THREAD

**Issue by etnatrader** [iexg/IEX-API#835]
### Date/time of issue
2019-04-04, 2019-04-05, all the time

### API URL
https://ws-api.iextrading.com/1.0/tops

### What you expected to happen
Actual FB quote (it's about 175.5 today):
> {QuoteType:2, Key:1, Ask:175.5500, **Bid:175.5000**, Last:175.5000, Mark: 175.5000, Date:2019.04.05 15:04:01:1350, DailyVolume:85732, Volume:100, AskSize:100, **BidSize:200**, Week52High:218.62, Week52Low:123.02, High:178, Low:175.5301}

### What actually happened
Intermittent Bid with different BidSize:
> {QuoteType:2, Key:1, Ask:175.5500, **Bid:175.5000**, Last:175.5000, Mark: 175.5000, Date:2019.04.05 15:04:01:1350, DailyVolume:85732, Volume:100, AskSize:100, **BidSize:200**, Week52High:218.62, Week52Low:123.02, High:178, Low:175.5301}
> {QuoteType:2, Key:1, Ask:175.5500, **Bid:172.0200**, Last:175.5000, Mark: 175.5000, Date:2019.04.05 15:04:01:1350, DailyVolume:85732, Volume:100, AskSize:100, **BidSize:100**, Week52High:218.62, Week52Low:123.02, High:178, Low:175.5301}

**Comment by joshuablackburn-iex** [comment]
I'm not sure I understand what the issue is. The bid and ask are quoted prices, not trades. These fluctuate all the time.
