### ISSUE TITLE
CSV export broken for missing for Agilent Technologies "A" for 4/3/2019

### ISSUE THREAD

**Issue by scottyrotten6** [iexg/IEX-API#837]
## Summary
The market intraday data is missing for Agilent Technologies (A) for 4/3/2019 ONLY. All other days are there. 

## Details
Not much to add

### Date/time of issue
4/3/2019

### API URL
https://cloud.iexapis.com/beta/stock/A/chart/date/20190403/?token=my_token&filter=minute,marketOpen,marketHigh,marketLow,marketClose,marketVolume&format=csv

**Comment by ben-berman-iex** [comment]
Hi there, it looks like without the filter it does work, we are looking into why the filter seems to be an issue in this case

**Comment by scottyrotten6** [comment]
Cool thanks! Its literally for that stock and that day only, but unfortunately I really need the data ☹ Thanks again for your weekend response 😊

**Comment by evancarter-iex** [comment]
This should be fixed now.
