### ISSUE TITLE
Chart api returning null for certain properties (for GPRO)

### ISSUE THREAD

**Issue by Diastro** [iexg/IEX-API#838]
## Summary
GPRO Ticker returns abnormal results when using the chart api.

## Details
Certain values are null in specific minutes and high/low values are wrong: 
  {
    "date": "20190405",
    "minute": "09:31",
    "label": "09:31 AM",
    "high": -1,
    "low": -1,
    "average": -1,
    "volume": 0,
    "notional": 0,
    "numberOfTrades": 0,
    "marketHigh": 6.66,
    "marketLow": 6.642,
    "marketAverage": 6.654,
    "marketVolume": 3480,
    "marketNotional": 23157.4915,
    "marketNumberOfTrades": 4,
    "open": null,
    "close": null,
    "marketOpen": 6.642,
    "marketClose": 6.66,
    "changeOverTime": null,
    "marketChangeOverTime": -0.005381165919282582
  },

### Date/time of issue
April 6th 2019 - 2:19PM PST

### API URL
https://api.iextrading.com/1.0/stock/gpro/chart?range=1d

### What you expected to happen
These should not be null.

**Comment by evancarter-iex** [comment]
Api.iextrading.com is being sunsetted in June. Please use https://iexcloud.io and see if the problem reoccurs. Thanks
