### ISSUE TITLE
Dividend Data Incomplete

### ISSUE THREAD

**Issue by ldsemail** [iexg/IEX-API#839]
## Summary

Much of the Dividend History Data seems to be inaccurate or incomplete.
Example below:

## Details

Looking up Dividend History data for symbol:  NEE

### Date/time of issue

2019-04-07  10:55 AM

### API URL

https://api.iextrading.com/1.0/stock/nee/dividends/5y

### What you expected to happen

Expected to see full history of Dividend payments.
See result below.
Note:   

-   Missing dividends made after exDate: 2018-02-26.  
-   Dividends were made with exDate:  2018-06-04, 2018-08-29 , 2018-11-29, 2019-02-27 

  
- Also Dividend with exDate: 2017-11-24  has flag value of "FI"  Final.

     

### What actually happened

[{"exDate":"2018-02-26","paymentDate":"2018-03-15","recordDate":"2018-02-27","declaredDate":"2018-02-16","amount":1.11,"flag":"","type":"Dividend income","qualified":"","indicated":""},{"exDate":"2017-11-22","paymentDate":"2017-12-15","recordDate":"2017-11-24","declaredDate":"2017-10-13","amount":0.9825,"flag":"FI","type":"Dividend income","qualified":"","indicated":""},{"exDate":"2017-08-23","paymentDate":"2017-09-15","recordDate":"2017-08-25","declaredDate":"2017-07-27","amount":0.9825,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2017-05-25","paymentDate":"2017-06-15","recordDate":"2017-05-30","declaredDate":"2017-05-18","amount":0.9825,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2017-02-24","paymentDate":"2017-03-15","recordDate":"2017-02-28","declaredDate":"2017-02-17","amount":0.9825,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2016-11-22","paymentDate":"2016-12-15","recordDate":"2016-11-25","declaredDate":"2016-10-14","amount":0.87,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2016-08-26","paymentDate":"2016-09-15","recordDate":"2016-08-30","declaredDate":"2016-07-29","amount":0.87,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2016-05-26","paymentDate":"2016-06-15","recordDate":"2016-05-31","declaredDate":"2016-05-19","amount":0.87,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2016-02-24","paymentDate":"2016-03-15","recordDate":"2016-02-26","declaredDate":"2016-02-12","amount":0.87,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2015-11-24","paymentDate":"2015-12-15","recordDate":"2015-11-27","declaredDate":"2015-10-16","amount":0.77,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2015-08-26","paymentDate":"2015-09-15","recordDate":"2015-08-28","declaredDate":"2015-07-31","amount":0.77,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2015-05-27","paymentDate":"2015-06-15","recordDate":"2015-05-29","declaredDate":"2015-05-22","amount":0.77,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2015-02-25","paymentDate":"2015-03-16","recordDate":"2015-02-27","declaredDate":"2015-02-13","amount":0.77,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2014-11-25","paymentDate":"2014-12-15","recordDate":"2014-11-28","declaredDate":"2014-10-17","amount":0.725,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2014-08-27","paymentDate":"2014-09-15","recordDate":"2014-08-29","declaredDate":"2014-07-25","amount":0.725,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2014-05-29","paymentDate":"2014-06-16","recordDate":"2014-06-02","declaredDate":"2014-05-23","amount":0.725,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2014-02-26","paymentDate":"2014-03-17","recordDate":"2014-02-28","declaredDate":"2014-02-14","amount":0.725,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2013-11-26","paymentDate":"2013-12-16","recordDate":"2013-11-29","declaredDate":"2013-10-18","amount":0.66,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2013-08-28","paymentDate":"2013-09-16","recordDate":"2013-08-30","declaredDate":"2013-07-26","amount":0.66,"flag":"","type":"Dividend income","qualified":"Q","indicated":""},{"exDate":"2013-05-30","paymentDate":"2013-06-17","recordDate":"2013-06-03","declaredDate":"2013-05-24","amount":0.66,"flag":"","type":"Dividend income","qualified":"Q","indicated":""}]

### Other Information (sample code, links, etc.)

Dividend History can be found below:
   https://www.nasdaq.com/symbol/nee/dividend-history

**Comment by evancarter-iex** [comment]
Api.iextrading.com is being sunset in June. Please use https://iexcloud.io where this data is up to date.
