### ISSUE TITLE
Include analyst EPS growth estimates - enhancement request

### ISSUE THREAD

**Issue by carthaigh** [iexg/IEX-API#84]
Analyst EPS growth estimates would be very useful i.e.:

Next Year [%]
Next 5 Years (per annum) [%]

Thank you!

**Comment by myvaluealerts** [comment]
Along with this request, I would like to see:
analysts consensus ->  PEG Ratio
analysts consensus ->  Est. EPS Current Year
analysts consensus ->  Est. EPS Next Year
analysts consensus ->  1 year price target.
analysts consensus ->  5 year EPS growth rate expectations
analysts consensus ->  1 year EPS growth rate expectations
analysts consensus ->  EPS for ttm (trailing 12 months)

fyi:  IEX proveds ttmEPS of 3.56 for XOM.  However, that number does not match many of the other data provider numbers.  Diluted EPS ttm is reported as:
IEX 3.56;   Yahoo 2.77;   NASDAQ 2.66;   MorningStar 3.07;   Zacks 3.56

**Comment by rahulrs** [comment]
analysts consensus -> 1 year price target.
This will be a very useful feature to have. Is there a plan to make this available ?

**Comment by evancarter-iex** [comment]
Closing. This is fixed in IexCloud https://iexcloud.io
