### ISSUE TITLE
CEO Compensation Data is out of date

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#841]
## Summary
ceo-compensation dataset has data for 2017 for all symbols and not 2018

### Date/time of issue
April 8 2019

### API URL
https://cloud.iexapis.com/beta/stock/aapl/ceo-compensation?

### What you expected to happen
Data for 2018 is available

**Comment by MorningSleeper** [comment]
I see IBM and FB now show 2018 but GOOG still shows 2017. Also companyName response attribute is blank on all three of above symbols.

**Comment by evancarter-iex** [comment]
This is fixed.
