### ISSUE TITLE
When will websocket streaming be deprecated, and can deprecation decision be delayed?

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#842]
Previously, we spend significant amount of time, to use web socket - https://ws-api.iextrading.com/1.0/last , at server side and Android client side.

We know that web socket will be deprecated at some time. May I know when will it be? Can such deprecation be delayed, as we do not have enough resources, to port the code from websocket to SSE ?

**Comment by timpaine-iex** [comment]
closing as stale.
