### ISSUE TITLE
Getting zero extended prices pre market

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#844]
## Summary

Many symbols are returning extended price as zero for pre market calls. 

## Details

BURL, CRM returning zero prices for pre market data.

### Date/time of issue

from 5.15 am NY time.

### API URL

https://cloud.iexapis.com/beta/stock/market/batch/?types=quote&symbols=burl&token=token

### What you expected to happen

extended price should never be zero.

### What actually happened

extended price was zero.

### Other Information (sample code, links, etc.)

We run calls to quote pre market from 5.15 - 9.30 am.

**Comment by evancarter-iex** [comment]
@professorDante Is this still an issue? We have had premarket prices every morning, and I was checking this morning and saw extended prices.

**Comment by professorDante** [comment]
I would think so - it's tough for us to check as we are PST time, but we put a bit of code in to only update if the extended price is non zero. It looks like only pre market, and if the extended price is not different to market price

**Comment by evancarter-iex** [comment]
@professorDante Hmm Ill keep an eye on it. I know this morning I saw premarket quotes for the two symbols you gave but Ill look again Monday.

**Comment by professorDante** [comment]
Yes it's random, based on market movements it look like.

**Comment by evancarter-iex** [comment]
I havent seen this recently. I am going to close this, if its still an issue lets file a new bug. Thanks!
