### ISSUE TITLE
Is it possible to get the balance sheet, cash flow statement, and other financial docs from the previous year?

### ISSUE THREAD

**Issue by FrickProgrammer** [iexg/IEX-API#845]
## Summary
My algo needs to compare data from the previous year. However, when I request the financial documents, it only gives me that quarter. It there a way to request a specific time frame, say this latest quarter than a year before that?

### Other Information (sample code, links, etc.)

**'Financials: 
 [
    {
        "reportDate": "2018-12-31",
        "grossProfit": 31719000000,
        "costOfRevenue": 52654000000,
        "operatingRevenue": 84373000000,
        "totalRevenue": 84373000000,
        "operatingIncome": 23034000000,
        "netIncome": 19965000000,
        "researchAndDevelopment": 3902000000,
        "operatingExpense": 61339000000,
        "currentAssets": 140828000000,
        "totalAssets": 373719000000,
        "totalLiabilities": 255827000000,
        "currentCash": 44771000000,
        "currentDebt": 21741000000,
        "shortTermDebt": 21741000000,
        "longTermDebt": 92989000000,
        "totalCash": 86427000000,
        "totalDebt": 114730000000,
        "shareholderEquity": 117892000000,
        "cashChange": 18858000000,
        "cashFlow": 26690000000
    }
]
Quote: 
 {
    "symbol": "AAPL",
    "companyName": "Apple, Inc.",
    "calculationPrice": "tops",
    "open": 196.42,
    "openTime": 1554730200095,
    "close": 197,
    "closeTime": 1554494400394,
    "high": 199.5,
    "low": 196.34,
    "latestPrice": 198.875,
    "latestSource": "IEX real time price",
    "latestTime": "12:17:00 PM",
    "latestUpdate": 1554740220243,
    "latestVolume": 12781502,
    "iexRealtimePrice": 198.875,
    "iexRealtimeSize": 100,
    "iexLastUpdated": 1554740220243,
    "delayedPrice": 199.06,
    "delayedPriceTime": 1554739331755,
    "extendedPrice": 196.5,
    "extendedChange": -2.375,
    "extendedChangePercent": -0.01194,
    "extendedPriceTime": 1554730194696,
    "previousClose": 197,
    "change": 1.875,
    "changePercent": 0.00952,
    "iexMarketPercent": 0.027141489317922103,
    "iexVolume": 346909,
    "avgTotalVolume": 28583873,
    "iexBidPrice": 198.87,
    "iexBidSize": 100,
    "iexAskPrice": 198.89,
    "iexAskSize": 100,
    "marketCap": 937751310000,
    "peRatio": 16.21,
    "week52High": 233.47,
    "week52Low": 142,
    "ytdChange": 0.25698699999999997
}
Stats: 
 {
    "week52change": 0.16997299999999999,
    "week52high": 233.47,
    "week52low": 142,
    "marketcap": 928910160000,
    "employees": 132000,
    "day200MovingAvg": 190.7,
    "day50MovingAvg": 177.71,
    "float": 4708742476,
    "avg10Volume": 27937902.7,
    "avg30Volume": 28583873.43,
    "ttmEPS": 12.27,
    "ttmDividendRate": 2.82,
    "companyName": "Apple, Inc.",
    "sharesOutstanding": 4715280000,
    "maxChangePercent": 194.049505,
    "year5ChangePercent": 1.634394,
    "year2ChangePercent": 0.371293,
    "year1ChangePercent": 0.169973,
    "ytdChangePercent": 0.247467,
    "month6ChangePercent": -0.119632,
    "month3ChangePercent": 0.331711,
    "month1ChangePercent": 0.12881,
    "day30ChangePercent": 0.130689,
    "day5ChangePercent": 0.030119,
    "nextDividendRate": null,
    "dividendYield": 0.01431472081218274,
    "nextEarningsDate": "2019-05-01",
    "exDividendDate": "2019-02-08",
    "peRatio": 16.21
}
Earnings: 
 [
    {
        "actualEPS": 4.18,
        "consensusEPS": 4.66,
        "announceTime": "AMC",
        "numberOfEstimates": 36,
        "EPSSurpriseDollar": -0.48,
        "EPSReportDate": "2019-01-29",
        "fiscalPeriod": "Q4 2018",
        "fiscalEndDate": "2018-12-31",
        "yearAgo": 3.89,
        "yearAgoChangePercent": 0.0746
    }
]
Balance Sheet: 
 {
    "symbol": "AAPL",
    "balancesheet": [
        {
            "reportDate": "2018-12-31",
            "currentCash": 44771000000,
            "shortTermInvestments": 41656000000,
            "receivables": 18077000000,
            "inventory": 4988000000,
            "otherCurrentAssets": 12432000000,
            "currentAssets": 140828000000,
            "longTermInvestments": 158608000000,
            "propertyPlantEquipment": 39597000000,
            "goodwill": 0,
            "intangibleAssets": null,
            "otherAssets": 34686000000,
            "totalAssets": 373719000000,
            "accountsPayable": 44293000000,
            "currentLongTermDebt": 9772000000,
            "otherCurrentLiabilities": 42249000000,
            "totalCurrentLiabilities": 108283000000,
            "longTermDebt": 92989000000,
            "otherLiabilities": 23607000000,
            "minorityInterest": 0,
            "totalLiabilities": 255827000000,
            "commonStock": 40970000000,
            "retainedEarnings": 80510000000,
            "treasuryStock": null,
            "capitalSurplus": null,
            "shareholderEquity": 117892000000,
            "netTangibleAssets": 117892000000
        }
    ]
}
Cash Flow: 
 {
    "symbol": "AAPL",
    "cashflow": [
        {
            "reportDate": "2018-12-31",
            "netIncome": 19965000000,
            "depreciation": 3395000000,
            "changesInReceivables": 5109000000,
            "changesInInventories": -1076000000,
            "cashChange": 18858000000,
            "cashFlow": 26690000000,
            "capitalExpenditures": -3355000000,
            "investments": 9422000000,
            "investingActivityOther": -56000000,
            "totalInvestingCashFlows": 5844000000,
            "dividendsPaid": -3568000000,
            "netBorrowings": 6000000,
            "otherFinancingCashFlows": -1318000000,
            "cashFlowFinancing": -13676000000,
            "exchangeRateEffect": null
        }
    ]
}
Income Statement: 
 {
    "symbol": "AAPL",
    "income": [
        {
            "reportDate": "2018-12-31",
            "totalRevenue": 84373000000,
            "costOfRevenue": 52654000000,
            "grossProfit": 31719000000,
            "researchAndDevelopment": 3902000000,
            "sellingGeneralAndAdmin": 4783000000,
            "operatingExpense": 61339000000,
            "operatingIncome": 23034000000,
            "otherIncomeExpenseNet": 872000000,
            "ebit": 23034000000,
            "interestIncome": 890000000,
            "pretaxIncome": 23906000000,
            "incomeTax": 3941000000,
            "minorityInterest": 0,
            "netIncome": 19965000000,
            "netIncomeBasic": 19965000000
        }
    ]
}
`**

**Comment by McQgit** [comment]
Can't you use the 'last' parameter to specify the 5 most recent quarters?  Example:
[]https://cloud.iexapis.com/beta/stock/aapl/cash-flow/5?token=(redacted)

For details, see:
[]https://iexcloud.io/docs/api/#cash-flow

**Comment by FrickProgrammer** [comment]
I believe you are correct. I am coming from a python background and I think
the docs are a little bit different for it! Thanks.

**Comment by evancarter-iex** [comment]
Thanks @McQgit Closing.
