### ISSUE TITLE
Price Target endpoint for tickers not found returns 404

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#846]
## Summary
When asking the price target endpoint API for tickers not present, it 404's instead of returning empty JSON. Example given. Other endpoints correctly return empty JSON, for example the earnings.

## Details

Calling https://cloud.iexapis.com/beta/stock/AUG/price-target?token={token} returns a 404.

### Date/time of issue

9.50 am PST. 8/4/19.

### API URL

https://cloud.iexapis.com/beta/stock/AUG/price-target?token=

### What you expected to happen

Empty JSON should be returned, not a 404.

### What actually happened

Get 404 exception.

**Comment by joshuablackburn-iex** [comment]
The API returns 404 when data is not available. This could also be a 204 code, or it could be an empty object, or an empty array, or an empty string. There are many opinions, but we currently return 404.

**Comment by professorDante** [comment]
What happens when you batch request then? It will 404, when you have one stock unknown? Isn't that wrong? That means for something like a quote API you will never get any prices returned for a batch request.

**Comment by professorDante** [comment]
In fact, testing this on the quote endpoint, batching, with 1 bad stock in 100 does return a 404. This must be a mistake.

**Comment by joshuablackburn-iex** [comment]
In a batch request it will return null for that data point since the overall object will be keyed by symbol, therefore some data is returned to the client.

**Comment by joshuablackburn-iex** [comment]
If it is returning a 404 for 1 bad stock, then it will need to be fixed.

**Comment by professorDante** [comment]
So to be 100% clear - for a single stock ,it will 404. For a batch, it will always return something? For all APIs?

**Comment by joshuablackburn-iex** [comment]
Let me investigate the current behavior and get back to you.
