### ISSUE TITLE
timestamps converting to dates years in future

### ISSUE THREAD

**Issue by jgrandydev** [iexg/IEX-API#847]
## Summary

API is returning is timestamp values years in the future 

## Details

retrieve quotes for major equities such as AAPL and GOOG and price timestamps are years in the future 

### Date/time of issue

2019-04-08 11:00:00 PM PST 

### API URL

https://sandbox.iexapis.com/beta/stock/market/batch?types=quote&symbols=AAPL,GOOG&token=TOKEN

{
"AAPL": {
"quote": {
"symbol": "AAPL",
"companyName": "Apple, Inc.",
"calculationPrice": "close",
"open": 197.58,
"openTime": 1576056449375,
"close": 205,
"closeTime": 1623865222750,
"high": 208.71,
"low": 199.72,
"latestPrice": 199,
"latestSource": "Close",
"latestTime": "April 8, 2019",
"latestUpdate": 1597693162915,
"latestVolume": 26810846,
"iexRealtimePrice": 202.59,
"iexRealtimeSize": 102,
"iexLastUpdated": 1618098815769,
"delayedPrice": 208.42,
"delayedPriceTime": 1594934893857,
"extendedPrice": 210.09,
"extendedChange": 3.6,
"extendedChangePercent": 0.01838,
"extendedPriceTime": 1589102661416,
"previousClose": 203.05,
"change": 1.37,
"changePercent": 0.00671,
"iexMarketPercent": 0.025059819820258886,
"iexVolume": 657561,
"avgTotalVolume": 29916858,
"iexBidPrice": 0,
"iexBidSize": 0,
"iexAskPrice": 0,
"iexAskSize": 0,
"marketCap": 954907193975,
"peRatio": 16.55,
"week52High": 239.83,
"week52Low": 147,
"ytdChange": 0.25935173914123333
}
},
"GOOG": {
"quote": {
"symbol": "GOOG",
"companyName": "Alphabet, Inc.",
"calculationPrice": "close",
"open": 1210.45,
"openTime": 1567959910839,
"close": 1243.81,
"closeTime": 1590824503168,
"high": 1229.98,
"low": 1220.1,
"latestPrice": 1253.26,
"latestSource": "Close",
"latestTime": "April 8, 2019",
"latestUpdate": 1627466870018,
"latestVolume": 892946,
"iexRealtimePrice": 1263.72,
"iexRealtimeSize": 3,
"iexLastUpdated": 1625708512903,
"delayedPrice": 1226.22,
"delayedPriceTime": 1596782571378,
"extendedPrice": 1229.31,
"extendedChange": -4.45,
"extendedChangePercent": -0.00374,
"extendedPriceTime": 1615199299918,
"previousClose": 1236,
"change": -8.07,
"changePercent": -0.0067,
"iexMarketPercent": 0.04662751467404526,
"iexVolume": 40546,
"avgTotalVolume": 1415733,
"iexBidPrice": 0,
"iexBidSize": 0,
"iexAskPrice": 0,
"iexAskSize": 0,
"marketCap": 868415390233,
"peRatio": 28.49,
"week52High": 1312.74,
"week52Low": 993.11,
"ytdChange": 0.148788
}
}
}

### What you expected to happen

timestamps should be today's date ( or close to it ) 

### What actually happened

Console.WriteLine(new DateTime(1970, 1, 1).AddMilliseconds(1597693162915));

8/17/2020 7:39:22 PM

**Comment by joshuablackburn-iex** [comment]
This is due to the sandbox environment manipulating the data, but we do provide legitimate millisecond epoch timestamps in production data. 

We can exclude more keys from manipulation in the sandbox environment. Most of the timestamps in the quote object should be fine, but other dates in the system are sensitive and will only be valid in production.

**Comment by jgrandydev** [comment]
To my eye this is very poor policy and not in the spirit of IEX nor of the open source movement which has taken over the world.  Nowadays people can download fully functional versions of almost any product and work with it on a dev/test license.  Restrictions are placed on scalability not functionality. 
 Or a time limit is imposed.

The sandbox should function exactly as production - except with caps and throttles.   If the data values are artificially manipulated it is extraordinarily difficult for engineers to develop and test and demo - especially if I need to integrate IEX data with other systems.  

I've never heard of any financial market data provider deliberately manipulating data to impossible values.  You're shooting yourself in the foot.   Making life difficult for 3rd party developers will only drive people away from IEX Cloud.  

Please reconsider this policy and please survey engineers and I'm sure you will find that everyone is opposed.

**Comment by evancarter-iex** [comment]
@jgrandydev As per our pricing page https://iexcloud.io/pricing/ you can do a lot of testing/retrieving of real data through https://cloud.iexapis.com with whatever data you want to see (up to 500,000 messages).
The sandbox is designed to help people who need to do additional testing beyond the limits of 500,000 messages while they are doing development.

**Comment by tchell** [comment]
I think accessing real data isn't the real issue here. I think its reasonable to assume that the sandbox will return valid data even if it is fake. It's really annoying to develop based on the documentation and then realize that the data you are getting is not only different from what the documentation states. 
For a detailed example:
In python the date.fromtimestamp() function throws an error when creating a date from a timestamp in the future. So if we are developing based on the idea that the timestamps returned are going to be in the past then this data breaks our code by providing invalid data. And we now have to create a workaround for this problem, but only when consuming the sandbox version. We shouldn't have to have to versions of code for consuming two versions of the API. 
It should not be the responsibility of your customers to test your API to make sure the data (even the fake data) we are receiving is valid. We should be able to assume that the data we receive follows the documentation and returns data that is valid. What is even the point of providing a sandbox if the data being provided isn't useful for testing?

**Comment by joshuablackburn-iex** [comment]
I appreciate the feedback. Unfortunately it is not as black and white of an issue. First, we are a delivery platform and not all of the data is ours to give away, even on a trial basis. As you can see, we make our IEX data free. We also have to protect our data creators. We are trying to make a scalable platform to deliver data, and we have to protect our partners from users that will log in and download all the data for free and either leave or further distribute on the web. 

That being said, we always appreciate suggestions to improve the product. The sandbox functionality was developed soon after we launched the business as a way to overcome testing in a usage billing model. It’s not a perfect solution, but it was intended to come close to real data. We can add more intelligence around things like timestamps to only be in the past. String fields are a little more difficult to deal with at scale and not leak information. We can try to think of ways to balance the need to protect our data partners and improve the test experience. 

I would say, after dealing with financial data for some time, that you cannot blindly trust data to work. We’ve experienced issues even from sources of truth or multi multi billion dollar companies. Recommend coding defensively, but it is our goal to provide the easiest and highest quality experience.

**Comment by jpuk** [comment]
> 
> For a detailed example:
> In python the date.fromtimestamp() function throws an error when creating a date from a timestamp in the future. 

I had the same issue and realised the timestamp is longer than Python's datetime.fromtimestamp function expected or needs a decimal place. (Like you see if you run date on the command line to produce a timestamp.)
gdate +%s.%N
1588533746.214504000

Try just using just the first 10 digits and it should work fine.

datetime.fromtimestamp(int(str(timestamp)[:10]))
