### ISSUE TITLE
earning updated not promptly

### ISSUE THREAD

**Issue by shoujs** [iexg/IEX-API#849]
## Details
Levi's reported its earning after market close on 9th April. But till now, IEX cloud does not have its earning updated.

The api returns earnings of empty.

I think it is a general issue. I observed other company's earnings are not getting promptly updated either.

How much time delayed should we expect for eanring api?

### API URL

https://cloud.iexapis.com/beta/stock/levi/earnings?token=pk_

**Comment by shoujs** [comment]
I also see no messages cosumed if the earning api returns empty data. is that true for all api generally?

**Comment by evancarter-iex** [comment]
@shoujs we are looking into this

**Comment by hujingzhen** [comment]
The V1 data is also empty:
https://api.iextrading.com/1.0/stock/EXPE/earnings

**Comment by evancarter-iex** [comment]
This is should be fixed in https://iexcloud.io
