### ISSUE TITLE
Can reference data returns an identifier on security?

### ISSUE THREAD

**Issue by wsxiaoys** [iexg/IEX-API#85]
As symbol might be renamed from time to time. It'll be handy if we have an unique id to track the exact security.

**Comment by joshuablackburn-iex** [comment]
This is an obvious omission on our part.  We already maintain this internally, so we will look to deploy this today.

**Comment by joshuablackburn-iex** [comment]
This was deployed today, and should be available tomorrow.

**Comment by wsxiaoys** [comment]
wow, that's really impressive speed for productionize a feature.

Thanks a lot!

**Comment by wsxiaoys** [comment]
Verified it works, thanks!

**Comment by leedstyh** [comment]
Hi, sorry to reply here closed issue.

I see this endpoint  (https://api.iextrading.com/1.0/ref-data/symbols) returns a `iexId` filed. Is this what you are talking about? @joshuablackburn-iex 

If so, my question is why not using `SEC CIK`?

**Comment by mcgwebdesign** [comment]
@joshuablackburn-iex 

I've noticed that the iexId field is changing around on some symbols. any particular reason?

for example
5/3 HCXZ iedId : 14516
5/4 HCXZ iedId : 14518
