### ISSUE TITLE
In computing the cost of a call, what is the numeric value of a "data type" that is multiplied by the weight?

### ISSUE THREAD

**Issue by estrnod** [iexg/IEX-API#851]
Re https://iexcloud.io/docs/api/#data-weighting, which states that " We calculate message counts by multiplying the type of data object by that data object’s weight."  I have not been able to find any documentation on what VALUE a "data type" constitutes, in order to understand what the true cost of a call is.  For instance, take https://iexcloud.io/docs/api/#company, with a weight of 1.  What is the value that is multiplied by this weight - is it the number of bytes returned?  the number of fields?  the number of objects (like in the case of a call that returns an array of results)?

**Comment by joshuablackburn-iex** [comment]
We will update the documentation for company, but the other endpoints do list the unit. For company, it is 1 message per symbol requested.

**Comment by estrnod** [comment]
I have looked at some others, and they show the weighting.  But the description of the calculation above notes that the weight is multiplied by another factor implied by the data object.  This is what I cannot find.
