### ISSUE TITLE
Streaming data old API vs Cloud API

### ISSUE THREAD

**Issue by derekg52** [iexg/IEX-API#853]
I'm currently using the v1 tops endpoint with WebSockets (https://ws-api.iextrading.com/1.0/tops) and trying to figure out precisely what I need going forward to support my application.  I tried using the new API with the new tops endpoint but it didn't work.  I wasn't completely clear whether WebSockets were still supported or everything is SSE now?

With tops coming from IEX itself (and not being sunsetted June 1st), is there a timeline for closing the legacy API or it will be open as far as you know?

**Comment by evancarter-iex** [comment]
@derekg52 sorry somehow this question slipped through.

1) We are only supporting SSE on https://iexcloud.io
2) June will be when we turn off the legacy API. Websockets might stay a bit longer but eventually it will go away as well.

**Comment by derekg52** [comment]
So if I got this right, the firehose websocket method to tops from the old API is going away.  To do the same in the new world requires SSE and a scale membership correct? 

The tops REST method would provide the data for free but requires a polling interval to get it updated, correct?

**Comment by joshuablackburn-iex** [comment]
The TOPS firehose is only available via SSE and only to Scale users. REST method is available to all users. Maintaining a 3 MB/s stream is not cost effective for free.

Also, this may be helpful.
https://intercom.help/iexcloud/migrating-to-iex-cloud-from-legacy-iex-group-api/known-discrepancies-iex-cloud-api-v-legacy-iex-group-api

**Comment by derekg52** [comment]
Gotcha and that all makes sense.  Is there a date yet for the legacy API shutdown or is it still sometime in June?

**Comment by joshuablackburn-iex** [comment]
https://iextrading.com/developers

**Comment by timpaine-iex** [comment]
closing as stale
