### ISSUE TITLE
Key Stats Message weighting Incorrect

### ISSUE THREAD

**Issue by pblarry49** [iexg/IEX-API#854]
## Summary
When using the key stats API the data weighting is incorrectly documented.

## Details
Documentation states: "1 per call per symbol for single stat filter".
when sending a batch request with 4 tickers filtering for a single field, the system is charging 20 messages instead of 4. 

### Date/time of issue
4/11/19 1619 EDT
### API URL
"https://sandbox.iexapis.com/beta/stock/market/batch?symbols=AAPL,MO,T,JNJ&types=stats&filter=ttmDividendRate&token=Tpk_054d873611c645d393e20c148e77927a"

### What you expected to happen
I expected to be charged for 4 messages.

### What actually happened
I was charged for 20 messages

**Comment by evancarter-iex** [comment]
@pblarry49 In order to get 1 per call you need to use the call /stock/{symbol}/stats/{stat} not the batch call. If you use the filter in the batch call you get charged the full 5 messages.

**Comment by pblarry49** [comment]
Thanks, that explains it.
