### ISSUE TITLE
IEX Cloud API: ETFs miss DIV, MarketCap and YIELD info in Stats Endpoint

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#855]
ETFs miss DIV, ex-Div Date and YIELD info in Stats Endpoint. These information is available in Stats endpoint for common stocks. The old API works for both common stocks and ETFs.

ttmDividendRate | null
dividendYield | null
exDividendDate | null

Please check and correct it.

Details
Date/time of issue
API URL
https://cloud.iexapis.com/beta/stock/market/batch?symbols=VPU,VOO,VTI&types=stats&token=*

Please note that this issue is in Stats endpoint. This is the second time we opened this issue (#796). You think it is Dupe of #654. But #654 is closed too. The issue still exists.

Thanks

**Comment by slipcon** [comment]
Was just about to re-enter this exact same issue.   I'm not using the batch API, but the straight stats API, and see the same thing with both mutual funds and ETFs.   This is a high priority for me

**Comment by bishinew** [comment]
Any updates on this issue? Thanks

**Comment by bishinew** [comment]
Div and Yield info are missing in STATS endpoint for ETFs.  Please fix it. Thanks

**Comment by Jabotical** [comment]
If it helps, here's a list of the ETFs I'm trying to look at via /stats, all of which have no dividendRate info:

VBR, VTI, VXUS, IXUS, VYM, VCIT, TIP, BND, VWO, IEMG, TTP, KBWY, BIL

Is there another (non-batch) way besides the /stats endpoint to view them via queries, that works?

**Comment by evancarter-iex** [comment]
@Jabotical @bishinew @slipcon We have updated and expanded our dividend data. With that we now have the yield/rate for etfs. Please email support@iexcloud.io if you have additional issues. Thanks
