### ISSUE TITLE
WEBSERVICE consistently fails with sandbox API

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#856]
## Summary
WEBSERVICE consistently fails with sandbox API

## Details
WEBSERVICE consistently fails with sandbox API

### Date/time of issue
Recurring over multiple weeks

### API URL
=WEBSERVICE("https://sandbox.iexapis.com/stock/MSFT/company?token=[[[Tsk_mysanddboxtoken]]]")

### What you expected to happen
Retrieve actual data

### What actually happened
=WEBSERVICE("https://sandbox.iexapis.com/stock/MSFT/company?token=[[[Tsk_mysanddboxtoken]]]") produces #VALUE! in Excel

**Comment by evancarter-iex** [comment]
@ModelsRUs Thats most likely due to the fact that the data is randomized for testing. Excel may interpret some of those fields as invalid.

**Comment by ModelsRUs** [comment]
Thank you Evan.
So what data is available and what data isn't? How do I know if my code isn't good or the the issue is on your end? Of what use is the sandbox if errors aren't necessarily errors?

Also, I sent support this exact question 5 times without the courtesy of a response. What is IEX's policy regarding responding to emails?

**Comment by evancarter-iex** [comment]
@ModelsRUs All Endpoints are available in Sandbox that are available for your tier. Unfortunately it seems that Excel is interpreting the randomized data badly, but it's very hard for us to debug that issue from the Excel standpoint.

If you are seeing #VALUE! in Sandbox and Excel. I recommend using a web browser to go the same URL and see what it returns.

As for answering emails, we endeavour to answer all emails but on occasion things slip through or get caught in spam filters etc.

**Comment by ModelsRUs** [comment]
When I paste the above string directly in my browser, I get "Not Found". It doesn't seem like this is an Excel issue

**Comment by evancarter-iex** [comment]
@ModelsRUs My apologies, I misread your url. It looks like your url is incorrect: https://sandbox.iexapis.com/beta/stock/MSFT/company?token=Testtoken note the /beta/ that was missing

**Comment by ModelsRUs** [comment]
Thank you Evan. It now works. I wish the documentation for Webservice were more complete!

As I mentioned above, I've been asking support this same question for WEEKS and it's been ignored. How could it have been "missed" 5 times? If valid emails are being blocked by your spam filters, that's also an issue.

Anyway, thank you for letting me know.

**Comment by evancarter-iex** [comment]
@ModelsRUs Trust us, we are aware of our issues with our Spam filters, unfortunately its not under our control
