### ISSUE TITLE
Data randomly null

### ISSUE THREAD

**Issue by Amerkashi** [iexg/IEX-API#857]
## Summary
Data randomly shows as null

## Details
https://cloud.iexapis.com/beta/stock/aapl/quote?token=mytoken
  "symbol": "AAPL",
  "companyName": "Apple, Inc.",
  "calculationPrice": "previousclose",
  "open": null,
  "openTime": null,
  "close": 198.95,
  "closeTime": 1555012800272,
  "high": null,
  "low": null,
  "latestPrice": 198.95,
  "latestSource": "Previous close",
  "latestTime": "April 11, 2019",
  "latestUpdate": 1554955200000,
  "latestVolume": 200943,
  "iexRealtimePrice": null,
  "iexRealtimeSize": null,
  "iexLastUpdated": null,
  "delayedPrice": null,
  "delayedPriceTime": null,
  "extendedPrice": 199.95,
  "extendedChange": 1,
  "extendedChangePercent": 0.00503,
  "extendedPriceTime": 1555072415336,
  "previousClose": 198.95,
  "change": 0,
  "changePercent": 0,
  "iexMarketPercent": null,
  "iexVolume": null,
  "avgTotalVolume": 28892262,
  "iexBidPrice": null,
  "iexBidSize": null,
  "iexAskPrice": null,
  "iexAskSize": null,
  "marketCap": 938104956000,
  "peRatio": 16.21,
  "week52High": 233.47,
  "week52Low": 142,
  "ytdChange": 0.259815
}
### Date/time of issue
EST timezone - 8:30am

**Comment by evancarter-iex** [comment]
@Amerkashi We had a delayed nightly job last night, this should not reoccur.

**Comment by Amerkashi** [comment]
This still happens and is not fixed
![image](https://user-images.githubusercontent.com/36113589/56854195-c5258e00-6900-11e9-9c6b-cbe63caf7628.png)

**Comment by evancarter-iex** [comment]
We null out open on Weekends. iexRealtimePRrice,Size,LastUpdated are null as you would expect on the weekend.
