### ISSUE TITLE
At 8:15am, quote latest is from 2 days ago

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#858]
## Summary
'latest' info stale - says from 'previous close' but date and price are from 2 days ago.  This happened on about 15 ETFs and stock tickers (all of them I checked).  Note the /previous endpoint has similarly stale info.

## Details
Sample from QQQ
Array
(
    [quote] => Array
        (
            [symbol] => QQQ
            [companyName] => 
            [calculationPrice] => previousclose
            [open] => 185.78
            [openTime] => 1554989400465
            [close] => 185.03
            [closeTime] => 1555012800184
            [high] => 185.78
            [low] => 184.69
            [latestPrice] => 185.47
            [latestSource] => Previous close
            [latestTime] => April 10, 2019
            [latestUpdate] => 1554868800000
            [latestVolume] => 392708
            [iexRealtimePrice] => 0
            [iexRealtimeSize] => 0
            [iexLastUpdated] => 0
            [delayedPrice] => 185.03
            [delayedPriceTime] => 1555012800184
            [extendedPrice] => 185.86
            [extendedChange] => 0.39
            [extendedChangePercent] => 0.0021
            [extendedPriceTime] => 1555070484508
            [previousClose] => 185.47
            [change] => 0
            [changePercent] => 0
            [iexMarketPercent] => 
            [iexVolume] => 0
            [avgTotalVolume] => 33980141
            [iexBidPrice] => 0
            [iexBidSize] => 0
            [iexAskPrice] => 0
            [iexAskSize] => 0
            [marketCap] => 0
            [peRatio] => 
            [week52High] => 187.53
            [week52Low] => 143.46
            [ytdChange] => 0.197508
        )

    [previous] => Array
        (
            [date] => 2019-04-10
            [open] => 184.75
            [close] => 185.47
            [high] => 185.53
            [low] => 184.52
            [volume] => 24562958
            [uOpen] => 184.75
            [uClose] => 185.47
            [uHigh] => 185.53
            [uLow] => 184.52
            [uVolume] => 24562958
            [change] => 0
            [changePercent] => 0
            [changeOverTime] => 0
            [symbol] => QQQ
        )

    [ohlc] => Array
        (
            [open] => Array
                (
                    [price] => 185.78
                    [time] => 1554989400465
                )

            [close] => Array
                (
                    [price] => 185.03
                    [time] => 1555012800184
                )

            [high] => 185.78
            [low] => 184.69
            [symbol] => QQQ
        )

)

### Date/time of issue
Fri Apr12 at 8:17am NY time.

### API URL
https://cloud.iexapis.com/beta/stock/market/batch?symbols=qqq&types=quote,previous,ohlc&token=(redacted)

### What you expected to happen
After 8am, I expect 'previous close' to be from most recent close.  And, this is what has been happening until today.

### What actually happened
The previous close data, including price, was from Apr10 - not Apr11

### Other Information (sample code, links, etc.)
Once the market opened the quotes looked fine.

**Comment by evancarter-iex** [comment]
@McQgit Sorry about that, we had a delayed nightly job last night. It should not reoccur.
