### ISSUE TITLE
Volume by Venue documentation incorrect

### ISSUE THREAD

**Issue by snydercoder** [iexg/IEX-API#859]
## Summary
Volume by Venue doc mistake

## Details
If you go to https://iexcloud.io/docs/api/#volume-by-venue, you see the HTTP request example shows:
/stock/{symbol}/delayed-quote

When it should be: 
/stock/{symbol}/volume-by-venue

### Date/time of issue
4/12/19 12:30p CDT

**Comment by evancarter-iex** [comment]
@snydercoder Good catch. I updated the docs and next time we do a deploy it will be fixed. Thanks
