### ISSUE TITLE
Top 10 symbol lists

### ISSUE THREAD

**Issue by maryokhin** [iexg/IEX-API#86]
Hi, I am very interested in using this API https://iextrading.com/developer/docs/#list, but I find somewhat limiting. Are there any plans for additional functionality for these lists? 

At the very least:
1. Being able to request more than 10 symbols, at least bump the limit to 50.
2. Being able to filter by sector (not client side), to receive the same N symbols for that sector only.

**Comment by joshuablackburn-iex** [comment]
We will look at this request.  We have already started work on the sector lists.

**Comment by joshuablackburn-iex** [comment]
listLimit query param can be used.
