### ISSUE TITLE
A few logo icons are damaged and cannot be displayed

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#861]
## Summary
Logo icons for SBUX, BLK, and PG do not display.  Also, the logo icons for the Select SPDR series of ETFs do not display (XLU, XLE, XLK, XLF, ...).

## Details
The logos are found, but, don't display as a valid image.  Firefox notes the png files contain errors whereas other browsers just show nothing.  

### Date/time of issue
Sat Apr13 2019

### API URL
https://storage.googleapis.com/iex/api/logos/BLK.png

### What you expected to happen
Valid logo to be displayed, especially for SBUX and BLK and PG.  I see logos for other ETF families but not for the Select SPDR series.

### What actually happened
No visible logo - possible damaged / corrupt png

### Other Information (sample code, links, etc.)
n/a

**Comment by evancarter-iex** [comment]
This is fixed. However, we are looking at ways to get ETF logos but that is filed elsewhere. Closing.
