### ISSUE TITLE
Mexico stocks changed from .mx to -mm

### ISSUE THREAD

**Issue by kidpollo** [iexg/IEX-API#862]
## Summary
Cant find information on why the mexico tickers changed to be suffixed from `.mx` to `-MM`
It seems everywhere else they are suffixed with `.mx` as they where suffixed in the begging.

## Details
Also the exchange API shows mexico as .mx https://cloud.iexapis.com/beta/ref-data/exchanges no symbol suffix info to be found anywhere. I wonder if this is a bug?

### Date/time of issue
I could not find when this change happened. 2019-03-07.???

### API URL
Now
https://cloud.iexapis.com/beta/stock/sorianab-mm/price
Before
https://cloud.iexapis.com/beta/stock/sorianab,mx/price
 
### What you expected to happen
.mx suffux is more standard. Seems to be used already on established websites like yahoo finance. For example https://finance.yahoo.com/quote/SORIANAB.MX?p=SORIANAB.MX&.tsrc=fin-srch

**Comment by lars670** [comment]
Looks like a switch from Reuters Instrument Code (RIC) to OpenFIgi. This is mentioned in the documentation.
https://www.openfigi.com/search#!?simpleSearchString=sorianab&page=1

**Comment by kidpollo** [comment]
Ugh that’s not good for me :( I am porting a system already based on the
Reuter’s code :(

**Comment by lars670** [comment]
We are quite happy with this, since RIC are protected by IP rights and cannot be redistributed.
