### ISSUE TITLE
Missing Xetra Symbols

### ISSUE THREAD

**Issue by shlomme** [iexg/IEX-API#863]
## Summary
According to https://www.xetra.com/xetra-de/instrumente/alle-handelbaren-instrumente/xetra, there are more than 2500 tradeable instruments on Xetra. When runnin /ref-data/exchange/etr/symbols, I only get 1106. 

### Date/time of issue
2019-04-14 15:36 CEST

### API URL
/ref-data/exchange/etr/symbols

### What you expected to happen
All tradeable instruments from Xetra returned.

### What actually happened
Only a subset of tradeable instruments were returned.

**Comment by evancarter-iex** [comment]
@shlomme Is this still an issue?

**Comment by unzico** [comment]
I just tried fetching all XETRA instruments via `https://cloud.iexapis.com/stable/ref-data/exchange/etr/symbols?token={{token}}` and got 1105 using `array.length`.

**Comment by tadeussenf** [comment]
1108 as of today

**Comment by sklinkert** [comment]
I'm also wondering why most of the Xetra ETFs are missing. According to https://www.xetra.com/xetra-en/instruments/etf-exchange-traded-funds/list-of-tradable-etfs and https://etfs24.de/liste-der-in-deutschland-handelbaren-etfs/ there should be **1,481 tradable ETFs** and **220 ETCs** (https://www.xetra.com/xetra-en/instruments/etc-exchange-traded-commodities/list-of-tradable-etcs).

I tried this URL: `https://cloud.iexapis.com/stable/ref-data/exchange/etr/symbols?token=<token>` and I got 1174 symbols.

**Comment by TychoVrahe** [comment]
Still missing this data

**Comment by themaxwellcode** [comment]
Any news? Still can't get data for the most xetra etfs... :(
