### ISSUE TITLE
Different data returned: API 1.0 vs IEX Cloud

### ISSUE THREAD

**Issue by jtsco77** [iexg/IEX-API#864]
## Summary
IEX API 1.0 appears to be providing different numbers than IEX cloud.  And in both cases, a few are returning numbers that do not match other sources of financial statement data.  Any guidance on how to fix / better understand would be greatly appreciated.

## Details
I'm admittedly new to IEX - and looking for any guidance on why the numbers returned for Financial Statements do not match across both IEX API 1.0 and IEX Cloud - as well as those same statements posted on traditional sites (Yahoo, Morningstar, etc.).

Those values where gaps exist:
IEX API 1.0 (financials) / IEX Cloud (income):  **costOfRevenue** 
IEX API 1.0 (financials) / IEX Cloud (income): **operatingIncome**
IEX API 1.0 (financials) / IEX Cloud (income): **operatingExpense**
To be clear I also looked at these metrics across 7 different popular websites - to review the various ways calculations may influence how numbers are displayed, but could not understand what was creating the gap.

For reference, when looking at the following metrics all values matched:
**reportDate
totalRevenue
netIncome
researchAndDevelopment**
Additionally, the values of these metrics matched those on all other sites reviewed.

Any guidance you could provide on what may be the source of the discrepancy - or how to appropriately assess these metrics would be greatly appreciated.  Thanks.

### Date/time of issue
4/14/19

### API URL
IEX API 1.0:  https://api.iextrading.com/1.0/stock/rlgt/financials?period=annual
IEX Cloud: https://cloud.iexapis.com/beta/stock/rlgt/income?[TOKEN]&period=annual

**Comment by McQgit** [comment]
I won't address your specific IEX question, but, I recommend becoming familiar with Edgar.  Example:
[]https://www.sec.gov/cgi-bin/browse-edgar?CIK=RLGT&owner=exclude&action=getcompany

The actual financial statements in SEC's Edgar are often helpful.  My experience with free sites like Yahoo, Morningstar, etc is they often differ between each other and from the actual financials.  Many reasons but often these variances arise from trying to fit all financials into a simplified template (M* especially).  I used such sites for years although now prefer a paid service.  

You didn't mention Edgar so thought it worth mentioning - if perhaps tangential.

**Comment by joshuablackburn-iex** [comment]
Agree with @McQgit that the SEC filings are the source of truth. We will have as reported data available as an endpoint soon, as well as searchable filings.

A difference in numbers is expected between 1.0 and Cloud since we have changed data providers. The data available in Cloud is sourced from a much higher quality provider.
