### ISSUE TITLE
Request Signing Sample errors.

### ISSUE THREAD

**Issue by cmcfarla77** [iexg/IEX-API#865]
## Summary
I'm translating the sample to fit within my code, but, am getting irregular responses to the sample (as is).

Using the Node request signing sample, results in success ~60% of the time.

## Details
I ran the sample 100 times over 5 minutes, resulting in 57% success, 43% failures

### Date/time of issue
4/15/2019 10:30AM (CDT) - 4/15/2019 10:40AM (CDT)

### API URL
the sample hits: https://cloud.iEXapis.com/beta/stock/aapl/company

### What you expected to happen
100% successful

### What actually happened
~60% successful
~40% returning: Hashed authorization is invalid

### Other Information (sample code, links, etc.)
code I'm using: 
const moment = require('moment');
const crypto = require('crypto');
const https  = require('https');

const method = 'GET'
const host = 'cloud.iexapis.com'

const access_key = process.env.PUBLIC_KEY // public key
const secret_key = process.env.SECRET_KEY // secret key for public key

const canonical_querystring = 'token=' + access_key ;
const canonical_uri = '/beta/stock/aapl/company'

var ts = moment.utc();
const iexdate = ts.format("YYYYMMDDTHHmmss") + 'Z';
const datestamp = ts.format("YYYYMMDD");

function sign(secret, data) {
    return crypto.createHmac('sha256', secret).update(data, "utf8").digest('hex');
};

function getSignatureKey(key, datestamp) {
    const signedDate = sign(key, datestamp);
    return sign(signedDate, 'iex_request');
}

if ( ! access_key || ! secret_key ) {
    console.warn('No access key is available.')
    process.exit(1);
}

const canonical_headers = 'host:' + host + '\n' + 'x-iex-date:' + iexdate + '\n';
const signed_headers = 'host;x-iex-date'
const payload = '';
const payload_hash = crypto.createHash('sha256').update(payload).digest('hex');
const canonical_request = method + '\n' + canonical_uri + '\n' + canonical_querystring + '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash;
const algorithm = 'IEX-HMAC-SHA256';
const credential_scope = datestamp + '/' + 'iex_request';
const string_to_sign = algorithm + '\n' +  iexdate + '\n' +  credential_scope + '\n' + crypto.createHash('sha256').update(canonical_request, "utf8").digest('hex');
const signing_key = getSignatureKey(secret_key, datestamp)
const signature = crypto.createHmac('sha256', signing_key).update(string_to_sign, "utf8").digest('hex');
const authorization_header = algorithm + ' ' + 'Credential=' + access_key + '/' + credential_scope + ', ' +  'SignedHeaders=' + signed_headers + ', ' + 'Signature=' + signature
const headers = {'x-iex-date':iexdate, 'Authorization':authorization_header}

const options = {
    host: host,
    port: 443,
    path: canonical_uri + "?" + canonical_querystring,
    method: 'GET',
    headers: headers
};

const req = https.request(options, function(res) {
    res.setEncoding('utf8');
    res.on('data', function(chunk) {
        var parsed = JSON.parse(chunk);
        console.log(parsed);
    });
});
req.end();

**Comment by cmcfarla77** [comment]
Node v10.15.3
moment@2.24.0
https@1.0.0
crypto@1.0.1

**Comment by ryandietrich-iex** [comment]
I have been running this code against our production system:

https://gist.github.com/ryandietrich-iex/a2ea0f1e2051153a0bd2450576136463

I'm seeing little to no errors on our end. We do have a latency timeout threshold of two seconds for the stamp of the message (to disallow re-requests of intercepted messages).  We're discussing increasing this threshold as it may be the cause of your issues, or it could be that your clock is adrift more than our threshold.

**Comment by cmcfarla77** [comment]
re-running the same code this afternoon, response is decidedly different. 100% success.  potential transient error?
