### ISSUE TITLE
Account endpoints return Not Found in sandbox environment

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#867]
## Summary

The account endpoints including:

* metadata
* usage

Return "Not Found" in the sandbox environment when test tokens are used.

### Date/time of issue

7pm EST 4/15/2019

### API URL

https://sandbox.iexapis.com/beta/account/metadata?token=

### What you expected to happen
```json
{"overagesEnabled":false,"effectiveDate":1549052448000,"endDateEffective":null,"subscriptionTermType":"monthly","tierName":"launch","messageLimit":5000000,"messagesUsed":1}
```
### What actually happened

Not found

**Comment by timpaine-iex** [comment]
closing as stale

**Comment by addisonlynch** [comment]
@timkpaine has the issue been resolved?
