### ISSUE TITLE
Add split data for ETFs

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#869]
## Summary

Splits endpoint returns empty for ETFs symbols

### API URL

https://cloud.iexapis.com/beta/stock/MVV/splits?range=5y&token=
https://cloud.iexapis.com/beta/stock/SVXY/splits?range=5y&token=

### What you expected to happen

For SVXY:
![image](https://user-images.githubusercontent.com/21162161/56180374-0baceb80-5fd7-11e9-9c10-b81fda90d710.png)

For MVV:

![image](https://user-images.githubusercontent.com/21162161/56180389-1798ad80-5fd7-11e9-80e5-68bf6e896286.png)

For AAPL:

```json
[{"exDate":"2014-06-09","declaredDate":"2014-04-23","ratio":0.142857,"toFactor":7,"fromFactor":1,"description":"7-for-1 Split"}]
```

### What actually happened

SVXY, MVV:

```
[]
```

AAPL:

```json
[{"exDate":"2014-06-09","declaredDate":"2014-04-23","ratio":0.142857,"toFactor":7,"fromFactor":1,"description":"7-for-1 Split"}]
```

**Comment by scottyrotten6** [comment]
I agree this is needed. Can I upvote this somehow to see if we get a response?
