### ISSUE TITLE
Collections return empty

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#870]
## Summary

Collections endpoint returns empty for given examples in IEX Cloud [documentation](https://iexcloud.io/docs/api/#collections)

### Date/time of issue

4/15/2019 11:50pm EST

### API URL

https://cloud.iexapis.com/beta/stock/market/collection/tag?collectionName=Computer%20Hardware&token=

https://cloud.iexapis.com/beta/stock/market/collection/sector?collectionName=Health%20Care&token=

### What you expected to happen

Collection data

### What actually happened

```
[]
```

### Other Information (sample code, links, etc.)

This appears to be an issue in IEX Cloud and the legacy v1 developer API

**Comment by evancarter-iex** [comment]
This should be fixed now. Let me know if you have additional questions.
