### ISSUE TITLE
Symbols: CE vs CEF

### ISSUE THREAD

**Issue by AndreRoehrig** [iexg/IEX-API#873]
## Summary

What is the difference?

## Details

Two types exist: 'CE - Closed end fund' and 'CEF - Closed Ended Fund'. It is unclear what the difference is.

### Date/time of issue

Permanently.

### API URL

https://iexcloud.io/docs/api/#symbols

**Comment by timpaine-iex** [comment]
`CE` is not used, it is only `CEF`. I will update the docs
