### ISSUE TITLE
Add additional key for lastupdated

### ISSUE THREAD

**Issue by lars670** [iexg/IEX-API#874]
> ##

 Summary
Datapoints same timestamp

## Details
In the documentation for Datapoints you write:
> We also provide update times for some endpoints which allow you to call an endpoint only once it has new data.
though it seems that all avaiable keys has the same timestamp in this case:
2019-04-17T07:00:17+00:00

### Date/time of issue
2019-04-17T07:00:17+00:00

### API URL
/data-points/AAPL

### What you expected to happen
If we query CEO of AAPL with key we would expect that timestamp was sometime in the past

### What actually happened
Timestamp is "Now."
key:"CEO","weight":1,"description":"ceo","lastUpdated":"2019-04-17T05:01:09+00:00"},

### Other Information (sample code, links, etc.)
This data call would be very useful if actually the last date of a change was published.

**Comment by joshuablackburn-iex** [comment]
I agree. I think we will add an additional key and leave lastUpdated.

**Comment by amittleider** [comment]
The same thing happens with the `LATEST-FINANCIAL-ANNUAL-REPORT-DATE` and `LATEST-FINANCIAL-QUARTERLY-REPORT-DATE` keys. According to the API, the data point is updated about once every day or two -- however, there are not new annual reports available daily. This makes it a little difficult to build a cache around annual reports that we already have.

@joshuablackburn-iex , is there any ETA for this?
