### ISSUE TITLE
inconsistency in intraday charts' date format

### ISSUE THREAD

**Issue by sqaxomonophonen** [iexg/IEX-API#875]
## Summary

For `https://cloud.iexapis.com/beta/stock/aapl/chart/date/20190416`, I receive an array of JSON objects, some having the `date` field in `YYYYMMDD` format, and others in `YYYY-MM-DD` format. The documentation says it should be `YYYY-MM-DD`

## Details
I get 249 results in the following format:
```
{
   "date": "20190416",
   ...
}
```
Followed by 141 results in the following format:
```
{
   "date": "2019-04-16",
   ...
}
```

### Date/time of issue
Around 2019-04-17 11:00 UTC

### API URL
`https://cloud.iexapis.com/beta/stock/aapl/chart/date/20190416`

### What you expected to happen
I expect the date to always be `YYYY-MM-DD`

### What actually happened
The date is sometimes `YYYYMMDD`

**Comment by evancarter-iex** [comment]
This should be fixed now.
