### ISSUE TITLE
Access Denied for logo ACAM

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#876]
## Summary

When accessing https://storage.googleapis.com/iex/api/logos/ACAM.png it gives the following error:

<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to iex/api/logos/ACAM.png.
</Details>
</Error>

### Date/time of issue

April 18 2019

### API URL

https://storage.googleapis.com/iex/api/logos/ACAM.png

### What you expected to happen

Page is available

### What actually happened

Access Denied

**Comment by evancarter-iex** [comment]
This is fixed in iexcloud.io, though I cant find any logo for them.
