### ISSUE TITLE
latestPrice returning incorrect (yesterday's) closing price

### ISSUE THREAD

**Issue by Sterillium** [iexg/IEX-API#877]
## Summary
latestPrice returning incorrect (yesterday's) closing price. I believe this is similar to issues as stated in #404, #544 ,#382, #235 meaning it could be a systemic problem that has yet to be solved. 

## Details
$TSLA request returning previous day's closing price

### Date/time of issue
April 17th 2019 after close and April 18th before open

### API URL
"https://cloud.iexapis.com/beta/stock/TSLA/quote?token=pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

{"symbol":"TSLA",
"companyName":"Tesla,Inc.",
"calculationPrice":"close",
"open":274.38,
"openTime":1555507801103,
"close":273.36,
"closeTime":1555531200214,
"high":274.79,
"low":268.535,
"latestPrice":273.36,
"latestSource":"Close",
"latestTime":"April 17, 2019",
"latestUpdate":1555531200214,
"latestVolume":5117518,
"iexRealtimePrice":271.19,
"iexRealtimeSize":100,
"iexLastUpdated":1555531196032,
"delayedPrice":271.23,
"delayedPriceTime":1555531200214,
"extendedPrice":270.98,
"extendedChange":-2.38,
"extendedChangePercent":-0.00871,
"extendedPriceTime":1555574440123,
"previousClose":266.38,
"change":6.98,
"changePercent":0.0262,
"iexMarketPercent":0.018219379003649817,
"iexVolume":93238,
"avgTotalVolume":9018941,
"iexBidPrice":0,
"iexBidSize":0,
"iexAskPrice":0,
"iexAskSize":0,
"marketCap":47215012560,
"peRatio":-47.32,
"week52High":387.46,
"week52Low":247.77,
"ytdChange":-0.092335}

### What you expected to happen

After the closing bell, I expected "latestPrice" to return the most recent closing price: 271.23

### What actually happened

"latestPrice" returned the previous day's closing price: 273.36

### Other Information (sample code, links, etc.)

Other returned fields also contain incorrect data related to the previous closing numbers.

**Comment by mikezliu** [comment]
I've also seen this issue after market close. It usually corrects itself after a while, but users who fetch prices during the bad times report incorrect prices.

**Comment by mikezliu** [comment]
As of this moment (~2:30 new york time), many symbols including SPY are returning incorrect prices.  For example, SPY shows "latestPrice": 289.45. But according to Bloomberg, Google, Yahoo, and other major sources, 289.45 is the previous day's closing price.  Today's closing price of SPY is 290.02.

{
    "SPY": {
        "quote": {
            "symbol": "SPY",
            "companyName": "SPDR S&P 500 ETF Trust",
            "calculationPrice": "close",
            "open": 290.12,
            "openTime": 1555594200056,
            "close": 289.45,
            "closeTime": 1555617600378,
            "high": 290.32,
            "low": 288.66,
            "latestPrice": 289.45,
            "latestSource": "Close",
            "latestTime": "April 18, 2019",
            "latestUpdate": 1555617600378,
            "latestVolume": 69309809,
            "iexRealtimePrice": 290.16,
            "iexRealtimeSize": 200,
            "iexLastUpdated": 1555620123266,
            "delayedPrice": 290.02,
            "delayedPriceTime": 1555618200003,
            "extendedPrice": 290.11,
            "extendedChange": 0.66,
            "extendedChangePercent": 0.00228,
            "extendedPriceTime": 1555631078590,
            "previousClose": 290.16,
            "change": -0.71,
            "changePercent": -0.00245,
            "iexMarketPercent": 0.016778231202455054,
            "iexVolume": 1162896,
            "avgTotalVolume": 70308391,
            "iexBidPrice": 0,
            "iexBidSize": 0,
            "iexAskPrice": 0,
            "iexAskSize": 0,
            "marketCap": 0,
            "peRatio": null,
            "week52High": 293.94,
            "week52Low": 233.76,
            "ytdChange": 0.154517
        }
    }
}

**Comment by evancarter-iex** [comment]
This should be fixed going forward. Please open a new issue if its still a problem.
