### ISSUE TITLE
Short Term Debt Is Missing From Balance Sheet Endpoint

### ISSUE THREAD

**Issue by exiao** [iexg/IEX-API#878]
## Summary
From the /balance-sheet API call, you cannot get the total debt number, because short term debt is missing as a field. It is present in the /financials/ endpoint, so it means we have to make calls to both in order to get total debt.

### Date/time of issue
April 18, 2019

### API URL
https://cloud.iexapis.com/beta/stock/market/batch?types=balancesheet,financials&symbols=aapl&token=YYYYYYY

### What you expected to happen
shortTermDebt is available on both financials and balance-sheet api calls

### What actually happened
It is missing from balance-sheet

**Comment by alvarozamora** [comment]
can I bump this?
