### ISSUE TITLE
Why does the quote request for certain stocks return a null week52Low?

### ISSUE THREAD

**Issue by Chocksy** [iexg/IEX-API#882]
## Summary
I'm making a quote request for some stocks (ROIC, HTHT) and when the market is not open the quote request returns a null `week52Low` value instead of the actual one.

## Details
- it happens only to certain stocks
- it happens only when the market is closed
- high and low are also null
- the week52High value is always present it seems. 

### Date/time of issue
Fri 19 Apr 2019

### API URL
https://cloud.iexapis.com/beta/stock/market/batch?token={MY_TOKEN}&symbols=HTHT,ROIC,DIS&types=quote

### What you expected to happen
I would like the request to always return the week52Low value.

**Comment by evancarter-iex** [comment]
@Chocksy I believe this was because it was a holiday and stuff got scrubbed but no new data was coming in. We will look into this.

**Comment by evancarter-iex** [comment]
@Chocksy Just checking in I havent seen this reoccur but I may be missing something

**Comment by evancarter-iex** [comment]
Im closing this. If it reoccurs please file a new bug. Thanks!

**Comment by Chocksy** [comment]
@evancarter-iex it still happens every day for HTHT. Maybe you can check before the market opens.
