### ISSUE TITLE
Allow users to sign up for Cloud API through app (via another API)?

### ISSUE THREAD

**Issue by martyh1** [iexg/IEX-API#883]
## Summary
Is there a way to allow my users (Android app) to sign up for one of your Cloud API subscription levels through my app (via some sort of sign up API) instead of going through your web site?  

## Details
I'm currently using API 1.0 and am looking to allow my app to continue to be used for free (no google play fee and no ads; at least for now).  My idea is to let users get their own token by signing up on your site but your site is geared towards developers.  I think this would cause me to lose users that haven't had to do anything extra at all to use my app.  I'd prefer something that keeps it all in the app.  I would actually be generating revenue for IEX Trading (and zero for myself) since I'm driving users to your plans.  I simply don't have the time or knowledge to build a backend REST API (to cache data to save on message usage) that might allow me to use my own token for all my users (and then possibly offset the cost with a new "paid" version of my app).

When I asked something similar before (https://github.com/iexg/IEX-API/issues/718), I had about 35 active installs.  I'm now up to 304 active installs.

My app (Stock Search) on the google play store:  https://play.google.com/store/apps/details?id=com.marty.stocksearch

### Date/time of issue
4/19/19

### What you expected to happen
Allow signup of different cloud API subscription levels through an API.

**Comment by timpaine-iex** [comment]
Closing as stale, users will need to be signed up on our site but business accounts can leverage e.g. oauth to leverage us as the identity provider.
