### ISSUE TITLE
Sector names mismatch between endpoints in new IEX Cloud API

### ISSUE THREAD

**Issue by ikoniaris** [iexg/IEX-API#886]
## Summary
There is no official list of sector names in IEX Cloud API docs. 

One would think that the "canonical" way to get them is to hit the `sector-performance` endpoint. This returns sector names from the old API, while the `collection` endpoint that you would then have to use to actually get the sector's tickers expects different values.

As an example, the `sector-performance` endpoint says there is a "Health Care" sector but when you pass that to `collection` you get nothing. Hitting the `company` endpoint for say BMY you find out that the sector name is actually called "Health Technology" now. Passing the latter to `collection` actually works. "Electronic Technology" vs just "Technology" is another example. 

Frankly the old sector names sound better than the new.

### Date/time of issue
April 20, 2019

### API URL
1. https://cloud.iexapis.com/stable/stock/market/sector-performance?token=XXX
2. https://cloud.iexapis.com/stable/stock/market/collection/sector?collectionName=Health%20Care&token=XXX
3. https://cloud.iexapis.com/stable/stock/market/collection/sector?collectionName=Health%20Technology&token=XXX

### What you expected to happen
I expected the 2nd link above to work based on the results from the 1st link.

### What actually happened
The 2nd link doesn't work, but the 3rd does instead.

**Comment by joshuablackburn-iex** [comment]
For collections, please use the sectors reference data.
https://iexcloud.io/docs/api/#sectors

The sector performance endpoint is based on the SPDR sector ETFs. We will update our docs to make this more clear, and provide a way to get sector performance for the proprietary sector classifications of our symbols.

**Comment by ikoniaris** [comment]
@joshuablackburn-iex the example URLs there don't work; they're missing the version (e.g. /stable)

**Comment by andrewdevilliers** [comment]
Hi @jonathanyam-iex , I see you closed this, but I have the same issue. The sectors in https://iexcloud.io/docs/api/#sectors are different to those of e.g. "https://cloud.iexapis.com/stable/rules/lookup/sector. It causes a lot of matching problems.

**Comment by AndrewBarfield** [comment]
Hello @jonathanyam-iex, @joshuablackburn-iex, @evancarter-iex
It's February 2021 and I'm having this problem. Is there any solution? (I'm open to hacks too)
Here's the email I sent to support last night:

***

I'm attempting to find a list of symbols (stocks) based on the current performance of sectors.

First, I query for [sector-performance](https://iexcloud.io/docs/api/#sector-performance) using:
* https://cloud.iexapis.com/stable/stock/market/sector-performance?token=xxxxxxx.

I get the expected JSON array. (Note the name properties):
```JSON
  [
    {
      "type":"sector",
      "name":"Materials",
      "performance":0.01542,
      "lastUpdated":1612546228060
    },
    {
      "type":"sector",
      "name":"Communication Services",
      "performance":0.01177,
      "lastUpdated":1612546066877
    },
    {
      "type":"sector",
      "name":"Energy",
      "performance":0.01173,
      "lastUpdated":1612546271991
    },
    ...
  ]
```
Unfortunately, the sector names in this response doesn't match the names of the sectors in the reference list:
* https://cloud.iexapis.com/stable/ref-data/sectors?token=xxxxxxx.
```JSON
  [
    {
      "name":"Other Services (except Public Administration)"
    },
    {
      "name":"Commercial Services"
    },
    {
      "name":"Retail Trade"
    },
    ...
  ]
```
What I'm trying to accomplish here is to pass the "best performing" sector from [sector-performance](https://iexcloud.io/docs/api/#sector-performance) directly into a [market collection query](https://iexcloud.io/docs/api/#collections). However, none of the following queries work. They all give an empty array response:
* https://cloud.iexapis.com/stable/stock/market/collection/sector?collectionName=Materials&token=xxxxxxx.
* https://cloud.iexapis.com/stable/stock/market/collection/sector?collectionName=Communication%20Services&token=xxxxxxx.
* https://cloud.iexapis.com/stable/stock/market/collection/sector?collectionName=Energy&token=xxxxxxx.

_Just for clarity_, another way of asking the same question is: How can differences between sector names among the API endpoints be reconciled?

Thank you!

**Comment by AndrewBarfield** [comment]
Update from support:

Hi Drew — There's not current way to reconcile these perfectly. We will be changing industry/sector data by the end of the quarter though, and are hoping to provide a more streamlined experience.

Thank You,
Nelson DeMoraes
Customer Support Specialist

**Comment by jjfantini** [comment]
Hello, 
I am still having an issue with the different JSON responses from the API endpoints, will the endpoint for a /company/sector be the same as the /sector-performance/ labels? ie not "Electronic Technology" for AAPL and just be "Technology"? 

@AndrewBarfield

**Comment by timpaine-iex** [comment]
@jjfantini No, `sector-perforance` utilizes the State Street Select Sector SPDRs which are based off of GICS, while `company` is based off NAICS/SIC.
