### ISSUE TITLE
U.S. Holidays and Trading Dates - Weighting

### ISSUE THREAD

**Issue by cmcfarla77** [iexg/IEX-API#888]
## Summary
Cost in documentation is wrong.  Appears to charge 1 message per record returned.

## Details
Documentation has: 
Data Weighting
1 per call

iexcloud-messages-used: indicates 1 per row

### Date/time of issue
4/20/19 4:17pm (CDT)

### API URL
https://cloud.iexapis.com/v1/ref-data/us/dates/holiday/next/5

### What you expected to happen
to be charged 1 message

### What actually happened
was charged 5 messages according to header returned.

### Other Information (sample code, links, etc.)
It makes sense that it's 1 per row returned, but, the documentation needs updating.

**Comment by McQgit** [comment]
@cmcfarla77  The docs describe this in the Data Weighting section as 
" ... We calculate message counts by multiplying the type of data object by that data object’s weight.  ..."

See:
[]https://iexcloud.io/docs/api/#data-weighting 

This applies to all the api's.  I think the docs would only become messier to repeat this for each.  That said, the Data Weighting section could be clearer by giving a couple examples.

**Comment by cmcfarla77** [comment]
While in principal I don't disagree, the documentation for U.S. holidays and Trading Dates says: 1 per call.
Most of the api's say x per symbol,  or y per record.  When it says 1 per call, I'd expect it to be 1 per call. :)
