### ISSUE TITLE
U.S. Holidays and Trading Dates optional parameters

### ISSUE THREAD

**Issue by cmcfarla77** [iexg/IEX-API#889]
## Summary
based on the documentation for /ref-data/us/dates/holiday, the only mandatory parameter is type.
e.g. https://cloud.iexapis.com/v1/ref-data/us/dates/holiday should be valid, it returns a 404
https://cloud.iexapis.com/v1/ref-data/us/dates/holiday/next is valid and returns appropriately

### Date/time of issue
4/20/19 4:21PM (CDT)

### API URL
https://cloud.iexapis.com/v1/ref-data/us/dates/holiday/5

### What you expected to happen
return the next 5 holidays

### What actually happened
404

**Comment by evancarter-iex** [comment]
This is updated in the latest documentation that we will push out shortly.
