### ISSUE TITLE
Documentation update: https://iexcloud.io/docs/api/#international-exchanges

### ISSUE THREAD

**Issue by cmcfarla77** [iexg/IEX-API#890]
## Summary
documentation specifies: 
International Exchanges
Returns an array of U.S. exchanges.

## Details
by definition should be: 
Returns an array of International exchanges

### Date/time of issue
4/20/19 4:43PM (CDT)

### API URL
N/A

### What you expected to happen
N/A

### What actually happened
N/A

**Comment by kiranshashiny** [comment]
This is a question and not an issue:


Is there stock ranking data available - along with other information when I do the query?

I was hoping to see something like 'Sell', 'Strong-Sell', 'Buy', 'Hold' etc.

![Screen Shot 2019-04-26 at 5 12 05 PM](https://user-images.githubusercontent.com/14288989/56805372-787d7c80-6846-11e9-9ffc-031797b52a6c.png)
