### ISSUE TITLE
https://iexcloud.io/docs/api/#cash-flow documentation question

### ISSUE THREAD

**Issue by cmcfarla77** [iexg/IEX-API#891]
## Summary
Cashflow lists:
GET /stock/{symbol}/cash-flow/{last}/{field}

however, fields usage is not defined as a parameter (neither is symbol for that matter, but it's use is pretty obvious.)

The presumed use would be if I wanted to only return a single field of cash-flow, e.g. reportDate but that doesn't appear to work. 

### Date/time of issue
4/20/19  11:40pm (CDT)

### API URL
https://cloud.iexapis.com/v1/stock/msft/cash-flow/reportdate?token=<TOKEN>&period=annual

### What you expected to happen
it to return only reportdate?
or documentation to be correct? 

### What actually happened
"all fields" returned

**Comment by evancarter-iex** [comment]
Documentation updated.
