### ISSUE TITLE
Error in documentation for IEX Short Interest Report Specification

### ISSUE THREAD

**Issue by Itsme23333** [iexg/IEX-API#893]
## Summary

The document IEX Short Interest Report Specification is contained at https://iextrading.com/docs/IEX%20Short%20Interest%20Report%20Specification.pdf

On page 7 there is a statement that reads:

If the Average Daily Volume for a security is 1,600,000 shares and the
Current Short Interest is 80,000 shares, the Days to Cover is 1,600,000 /
80,000 = 20

That should read:

If the Average Daily Volume for a security is 80,000 shares and the
Current Short Interest is 1,600,000 shares, the Days to Cover is 1,600,000 /
80,000 = 20

or:

If the Current Short Interest for a security is 1,600,000 shares and the
Average Daily Volume is 80,000 shares, the Days to Cover is 1,600,000 /
80,000 = 20

**Comment by timpaine-iex** [comment]
closing as stale
