### ISSUE TITLE
Error in documentation for list?

### ISSUE THREAD

**Issue by cmcfarla77** [iexg/IEX-API#894]
## Summary
https://iexcloud.io/docs/api/#list
does this api have a listlimit parameter or not?

## Details
the documentation page referenced above doesn't have it
but the changelog on 3/8/19 does.

2019-03-08
...
Added listLimit query parameter to list to specify number of items to return

if it DOES allow for it, I couldn't get it to work.

### Date/time of issue
4/21/19

### API URL
https://cloud.iexapis.com/v1/stock/market/list/gainers?token=<TOKEN>&listLimit=3

### What you expected to happen
list top 3 gainers

### What actually happened
same result as without the parameter (7 items)

**Comment by evancarter-iex** [comment]
This is updated in the documentation release that is going out shortly. It does exist and is able to be used.
