### ISSUE TITLE
Query all available symbols using constraints

### ISSUE THREAD

**Issue by programmishka** [iexg/IEX-API#895]
Hello dear community,

I like the IEX REST API.

My question ist: how can I get all available US symbols by market cap under 2 billion for example (small cap)? Is there a possibility to build such query? If not, please add a possibility to accept queries for a list of symbols. It would be then possible to create some kind of stocks screener.

And my second question is (stable version):
why does the call /ref-data/symbols return 8687 symbols, /ref-data/iex/symbols returns 8752 symbols (more than symbols) and /ref-data/region/US/symbols return 63760 symbols? I thought, all other requests should return a subset of /symbols.

**Comment by joshuablackburn-iex** [comment]
This is something that will be available when Rules Engine launches.
