### ISSUE TITLE
Exchange code mismatch across APIs

### ISSUE THREAD

**Issue by manueldude44** [iexg/IEX-API#896]
## Summary
When comparing the data between the following end points, there is no way to verify the data between them. Ideally, you would be able to get all exchanges then verify that each exchange in the US exists in the first list.
`GET /ref-data/exchanges` 
`GET /ref-data/market/us/exchanges`

### Date/time of issue
Monday April 22, 2019 - 10:30 PM CST

### API URL
`GET /ref-data/exchanges` 
`GET /ref-data/market/us/exchanges`

### What you expected to happen
I expected the property `exchange` within `GET /ref-data/exchanges` to match the property `mic` or any other property found on `GET /ref-data/market/us/exchanges`.

### What actually happened
Property `exchange` within `GET /ref-data/exchanges` is just an abbreviation for the exchange while `mic` on `GET /ref-data/market/us/exchanges` is a Market Identifier Code.

### Other Information (sample code, links, etc.)
The way I found this issue was by getting all symbol information on `GET /ref-data/symbols` and then trying to filter the `exchange` property to the exchange property on `GET /ref-data/market/us/exchanges`. 

There should be one unified exchange code used across different endpoints, and then if someone wants to get the full exchange information, that should be found on any of the `exchanges` endpoints.

**Comment by evancarter-iex** [comment]
@manueldude44 Hey there, sorry for the delay in response. Cleaning up the ref-data exchange endpoints is on our list of things to do.

**Comment by timpaine-iex** [comment]
closing as stale, these apis are a lot closer and have common attributes
