### ISSUE TITLE
Weight Watchers Symbol Change April 22 - symbol no longer in symbols API

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#897]
## Summary
Weight Watchers had their symbol change from WTW to WW on April 22 - neither symbol is in the symbols API

## Details
WTW and WW are both absent from the symbols API call

### Date/time of issue
April 22 11PM PST

### API URL

https://cloud.iexapis.com/beta/ref-data/symbols?token=

### What you expected to happen
 Either symbol to show up in the symbols call

### What actually happened
Neither are returned

**Comment by evancarter-iex** [comment]
This should be fixed now.
