### ISSUE TITLE
[Data] Estimates API returns incorrect values for reportDate if AMC

### ISSUE THREAD

**Issue by rittik97** [iexg/IEX-API#898]
**Describe the data problem**
The Estimates API call has inaccurate information. For tickers that have announceTime==AMC 
reportDate== correctvalue+1

for IRBT returned value (reportDate) is 2019-04-24 but correct value is 2019-04-23
for RRC returned value (reportDate) is 2019-04-23 but correct value is 2019-04-22
for HA returned value (reportDate) is 2019-04-24 but correct value is 2019-04-23

This issue only happens for tickers with announceTime==AMC 

**Data URL (The URL you used to access the data):**
https://cloud.iexapis.com/stable/stock/HA/estimates?token=my_token

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by joshuablackburn-iex** [comment]
Fix has been deployed.
