### ISSUE TITLE
[Data]Wrong Earning report date and time

### ISSUE THREAD

**Issue by hujingzhen** [iexg/IEX-API#899]
Wrong earning date for some stocks compared with nasdaq.
Here is the link:
https://cloud.iexapis.com/beta/stock/ROKU/earnings/4/?&token=YOUR_TOKEN

The correct earning date for the last quater is 2019-02-21 AMC. The API returns 2019-02-02.
{"symbol":"ROKU","earnings":[{"actualEPS":0.05,"consensusEPS":-0.11,"announceTime":"DMT","numberOfEstimates":12,"EPSSurpriseDollar":0.16,"EPSReportDate":"2019-02-22","fiscalPeriod":"Q4 2018","fiscalEndDate":"2018-12-31","yearAgo":0.06,"yearAgoChangePercent":-0.1667},{"actualEPS":-0.09,"consensusEPS":-0.12,"announceTime":"AMC","numberOfEstimates":12,"EPSSurpriseDollar":0.03,"EPSReportDate":"2018-11-07","fiscalPeriod":"Q3 2018","fiscalEndDate":"2018-09-30","yearAgo":-8.79,"yearAgoChangePercent":-0.9898},{"actualEPS":0,"consensusEPS":-0.15,"announceTime":"AMC","numberOfEstimates":11,"EPSReportDate":"2018-08-08","fiscalPeriod":"Q2 2018","fiscalEndDate":"2018-06-30","yearAgo":-0.18,"yearAgoChangePercent":-1},{"actualEPS":-0.07,"consensusEPS":-0.16,

I found "DMT" is used in lots of earnings from the API. however, I didn't see any company reports the earning 'during the market time'.  Does that mean all the earning dates with 'DMT' is wrong?

Thanks

**Comment by hujingzhen** [comment]
Here is another wrong data:
{"symbol":"BXMT","earnings":[{"actualEPS":0.68,"consensusEPS":2.86,"announceTime":"AMC","numberOfEstimates":10,"EPSSurpriseDollar":-2.18,"EPSReportDate":"2019-02-12","fiscalPeriod":"Q4 2018","fiscalEndDate":"2018-12-31","yearAgo":0.65,"yearAgoChangePercent":0.0462},{"actualEPS":0.75,"consensusEPS":0.67,"announceTime":"BTO","numberOfEstimates":8,"EPSSurpriseDollar":0.08,"EPSReportDate":"2018-10-23","fiscalPeriod":"Q3 2018","fiscalEndDate":"2018-09-30","yearAgo":0.69,"yearAgoChangePercent":0.087},{"actualEPS":0.83,"consensusEPS":0.66,"announceTime":"AMC","numberOfEstimates":8,"EPSSurpriseDollar":0.17,"EPSReportDate":"2018-07-24","fiscalPeriod":"Q2 2018","fiscalEndDate":"2018-06-30","yearAgo":0.6,"yearAgoChangePercent":0.3833}]}

The correct announceTime for 2018-10-23 is 'AMC' instead of 'BTO'.

**Comment by joshuablackburn-iex** [comment]
Should be resolved.
