### ISSUE TITLE
changePercent is off by a factor of 100

### ISSUE THREAD

**Issue by eigood** [iexg/IEX-API#9]
I have to multiply changePercent by 100 to get the correct value for display. I assume that since "Percent" is in the name, that the value will be constrainted between 0 and 100, not 0 and 1.  That's based on Hungarian Notation.

**Comment by eigood** [comment]
And I now see that the other *Percent values are also off the same way.

**Comment by joshuablackburn-iex** [comment]
Since these data points are already in use, I'm inclined to keep them as is.  However, I can support a display parameter that converts values to display friendly formats.

**Comment by joshuablackburn-iex** [comment]
displayPercent parameter has been added and documentation has been updated.
