### ISSUE TITLE
Availability of Indices Data

### ISSUE THREAD

**Issue by achenft** [iexg/IEX-API#901]
## Summary
Do you offer realtime indices data, e.g. Dow Jones Industrial Average (DJIA), Nasdaq Composite (COMP) or S&P 500 (CBOE SPX)?

If so what is the licensing fee, if any?

Thanks.

**Comment by evancarter-iex** [comment]
Hi there, we don't have S&P or other major indices currently and are unlikely to have in the near future. This data is essentially monopolized, so pricing is very high and requires a direct contract between each consumer and the index provider regardless of who actually supplies the data. The major index providers charge over $10k a year for delayed data, and that isn’t a price point we want to work with for our initial users.

An alternative is to display ETFs that match those indices, such as SPY for the S&P 500, DIA for Dow Jones, and IWM for Russell 2000
