### ISSUE TITLE
Please add Ranking data along with other information during a query.

### ISSUE THREAD

**Issue by kiranshashiny** [iexg/IEX-API#902]
This is a feature request to include the ranking data in the query.

Currently the data that I retrieve from IEX does not have a Buy/Sell/Strong Sell type of a ranking.
I was hoping that if it could be included in the query data.

Please see attached snap from zack's that includes the Zack's ranking for every stock that I query.  I am requesting something similar in the data.

![Screen Shot 2019-04-26 at 5 12 05 PM](https://user-images.githubusercontent.com/14288989/56805577-21c47280-6847-11e9-8b75-f9c3937e2c2b.png)

**Comment by kiranshashiny** [comment]
{"symbol":"A","companyName":"Agilent Technologies, Inc.","calculationPrice":"close","open":null,"openTime":null,"close":77.01,"closeTime":1575371374819,"high":80.48,"low":76.91,"latestPrice":79.78,"latestSource":"Close","latestTime":"April 25, 2019","latestUpdate":1569107735171,"latestVolume":1440694,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":78.21,"delayedPriceTime":1608363397830,"extendedPrice":0,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":1633461334986,"previousClose":75.84,"change":0.96,"changePercent":0.01267,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":1787354,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":24567331825,"peRatio":21.87,"week52High":85.99,"week52Low":61.32,"ytdChange":0.1863, **"Ranking:Buy"** }


See the last key:value - that's what I am requesting.

**Comment by joshuablackburn-iex** [comment]
This is already available.
https://iexcloud.io/docs/api/#recommendation-trends
