### ISSUE TITLE
ISSUE_TEMPLATE.md seems to be deprecated now (and can probably be safely removed)

### ISSUE THREAD

**Issue by richardeschloss** [iexg/IEX-API#903]
Very minor request. It seems like you want all the new issues going forward to be using the issue templates in .github folder. The ISSUE_TEMPLATE.md is still part of the repo, and hasn't been updated for over a year. Minor suggestion would be to phase this old file out so people aren't tempted to copy-n-paste it and deviate from convention.

The templates in the .github folder seem to make life much easier for both sides: requester and dev. The newer templates require the requester to do a bit of homework before clicking the submit button (which, is a good thing; more info you have, the better you can troubleshoot).  

Related to #99

**Comment by evancarter-iex** [comment]
Thanks. Removed that file.
