### ISSUE TITLE
Add endpoint for all news last 5

### ISSUE THREAD

**Issue by martyh1** [iexg/IEX-API#904]
**Describe the problem
Is there no more news like in API 1.0, /stock/market/news/last/5

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - API Version [e.g. v1]

**URL (if applicable)**
 - API URL associated with the issue.

**Additional context**

**Comment by timpaine-iex** [comment]
Closing as stale, use `time-series` for this with `last=5`
