### ISSUE TITLE
Issue with stock gainers / losers

### ISSUE THREAD

**Issue by Amerkashi** [iexg/IEX-API#905]
**Clearly describe the problem**
Data for /market/list/**gainers** or /market/list/**losers** sometimes is not correct. I'm not able to find a pattern on when this issue happens

**What time did the problem occur? (with timezone)**
EST random times - not necessarily market-close

**What is the expected behavior?**
/market/list/gainers should should only positive data and /market/list/losers should only show negative data

**Your environment (e.g. browser, OS, API version, language):**

**API URL (if applicable)**
/market/list/gainers or /market/list/losers

**What are the steps to reproduce the bug?**
Just query the api and you'll see. Screenshot below
![image](https://user-images.githubusercontent.com/36113589/56854147-13865d00-6900-11e9-9810-56887f793c87.png)

![image](https://user-images.githubusercontent.com/36113589/56854157-30229500-6900-11e9-943d-7a5bfff015cd.png)

**Additional context**
There needs to be better way to handle this. This should be simple fix to filter-out all negative data from /gainers and positive data from /losers

**Comment by evancarter-iex** [comment]
@Amerkashi We deployed something that should help with this. Let us know if you see this going forward.

**Comment by Amerkashi** [comment]
Thanks. Right now, it looks good. I'll keep checking and report back:
![image](https://user-images.githubusercontent.com/36113589/56982957-79692380-6b50-11e9-99c9-16f36b4186f6.png)

**Comment by Amerkashi** [comment]
Reporting back. Unfortunately, still same issue:
![image](https://user-images.githubusercontent.com/36113589/57015491-12e11580-6be3-11e9-9fc8-0778d33f956a.png)

**Comment by evancarter-iex** [comment]
@Amerkashi We are looking into it again. Thanks for the update.

**Comment by evancarter-iex** [comment]
@Amerkashi what time was that screenshot btw?

**Comment by Amerkashi** [comment]
It was off-market hours at about 8am EST

**Comment by evancarter-iex** [comment]
@Amerkashi we deployed something in the last couple of days to hopefully improve this. Is it still an issue?

**Comment by Amerkashi** [comment]
@evancarter-iex Checked a few times in last couple of days and seems to be okay. Thanks
