### ISSUE TITLE
Provide IV for options

### ISSUE THREAD

**Issue by shoujs** [iexg/IEX-API#906]
Thanks for rolling out options api. 
May I suggest add implied volatility to the options api?

**Comment by benschaechter-iex** [comment]
@shoujs Thanks for your request. Just to confirm, would you want implied volatility (IV) returned to you expressed as a simple float/percentage like the following (shown as the final return attribute)? Anything else expectation wise? 

GET /stock/{symbol}/options/{expiration}/{optionSide}

```
[
    {
        "symbol": "AAPL",
        "id": "AAPL20190621C00240000",
        "expirationDate": "20190621",
        "contractSize": 100,
        "strikePrice": 240,
        "closingPrice": 0.39,
        "side": "call",
        "type": "equity",
        "volume": 884,
        "openInterest": 12197,
        "bid": 0.38,
        "ask": 0.42,
        "lastUpdated": "2019-04-25",
        "impliedVolatility" : 0.343
    },
]
```

**Comment by shoujs** [comment]
Hi Ben, thanks for considering my proposal. The float type of the IV is good to me.  If you are asking me anything else, I would say if you can provide greeks(delta, gamma, theta, etc) would be great. I don't want to be too greedy. Currently you providing IV is good enough for me. Thank you.

**Comment by SC4RECOIN** [comment]
Providing Greeks and IV is something I would like to see in the API as well

**Comment by timpaine-iex** [comment]
I've added this to the unofficial roadmap, feel free to vote so we can prioritize accordingly:
https://iexcloud.io/console/roadmap
