### ISSUE TITLE
[Data] Duplicate dividend entry with Hasbro

### ISSUE THREAD

**Issue by dmikester1** [iexg/IEX-API#907]
**Clearly describe the data problem**
I'm getting a almost identical dividend entry from Hasbro.  I was able to get around any completely exactly identical entries and skip them properly.  I will bring them up in another issue.  But because the description is different by one word, I was not able to easily get around this duplicate entry.

**Data URL (The URL you used to access the data without your token):**
 https://cloud.iexapis.com/v1/stock/HAS/dividends/2y?token=

**What time did the problem occur (including timezone)?**
4/28/19 11:22pm CST

**What is the expected behavior?**
Get seperate unique results from the dividend API calls

**What are the steps to reproduce**
Get the json data from the URL  https://cloud.iexapis.com/v1/stock/HAS/dividends/2y?token=

**Your environment (e.g. browser, OS, API version, language):**
Firefox, Windows 10, Cloud API V1, English/PHP

**Additional context**
The duplicate entries have an ExDate of '2018-07-31' and the only difference is the addition of the word 'Cash' in one of the descriptions.
Here is a full dump of the JSON from that call:
array(11) { [0]=> object(stdClass)#8 (10) { ["exDate"]=> string(10) "2019-04-30" ["paymentDate"]=> string(10) "2019-05-15" ["recordDate"]=> string(10) "2019-05-01" ["declaredDate"]=> string(10) "2019-02-08" ["amount"]=> float(0.68) ["flag"]=> string(8) "Increase" ["currency"]=> string(3) "USD" ["description"]=> string(37) "Hasbro Hikes Quarterly Dividend 7.94%" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [1]=> object(stdClass)#9 (10) { ["exDate"]=> string(10) "2019-01-31" ["paymentDate"]=> string(10) "2019-02-15" ["recordDate"]=> string(10) "2019-02-01" ["declaredDate"]=> string(10) "2018-12-06" ["amount"]=> float(0.63) ["flag"]=> string(13) "No Change QoQ" ["currency"]=> string(3) "USD" ["description"]=> string(53) "Hasbro Declares Quarterly Dividend of $0.63 per Share" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [2]=> object(stdClass)#32 (10) { ["exDate"]=> string(10) "2018-10-31" ["paymentDate"]=> string(10) "2018-11-15" ["recordDate"]=> string(10) "2018-11-01" ["declaredDate"]=> string(10) "2018-08-01" ["amount"]=> float(0.63) ["flag"]=> string(13) "No Change QoQ" ["currency"]=> string(3) "USD" ["description"]=> string(53) "Hasbro Declares Quarterly Dividend of $0.63 per Share" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [3]=> object(stdClass)#33 (10) { ["exDate"]=> string(10) "2018-07-31" ["paymentDate"]=> string(10) "2018-08-15" ["recordDate"]=> string(10) "2018-08-01" ["declaredDate"]=> string(10) "2018-05-17" ["amount"]=> float(0.63) ["flag"]=> string(13) "No Change QoQ" ["currency"]=> string(3) "USD" ["description"]=> string(58) "Hasbro Declares Quarterly Cash Dividend of $0.63 per Share" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [4]=> object(stdClass)#28 (10) { ["exDate"]=> string(10) "2018-07-31" ["paymentDate"]=> string(10) "2018-08-15" ["recordDate"]=> string(10) "2018-08-01" ["declaredDate"]=> string(10) "2018-07-23" ["amount"]=> float(0.63) ["flag"]=> string(13) "No Change QoQ" ["currency"]=> string(3) "USD" ["description"]=> string(53) "Hasbro Declares Quarterly Dividend of $0.63 per Share" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [5]=> object(stdClass)#25 (10) { ["exDate"]=> string(10) "2018-04-30" ["paymentDate"]=> string(10) "2018-05-15" ["recordDate"]=> string(10) "2018-05-01" ["declaredDate"]=> string(10) "2018-02-07" ["amount"]=> float(0.63) ["flag"]=> string(8) "Increase" ["currency"]=> string(3) "USD" ["description"]=> string(38) "Hasbro Hikes Quarterly Dividend 10.53%" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [6]=> object(stdClass)#6 (10) { ["exDate"]=> string(10) "2018-04-30" ["paymentDate"]=> string(10) "2018-05-15" ["recordDate"]=> string(10) "2018-05-01" ["declaredDate"]=> string(10) "2018-04-23" ["amount"]=> float(0.63) ["flag"]=> string(13) "No Change QoQ" ["currency"]=> string(3) "USD" ["description"]=> string(53) "Hasbro Declares Quarterly Dividend of $0.63 Per Share" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [7]=> object(stdClass)#22 (10) { ["exDate"]=> string(10) "2018-01-31" ["paymentDate"]=> string(10) "2018-02-15" ["recordDate"]=> string(10) "2018-02-01" ["declaredDate"]=> string(10) "2017-12-07" ["amount"]=> float(0.57) ["flag"]=> string(13) "No Change QoQ" ["currency"]=> string(3) "USD" ["description"]=> string(53) "Hasbro Declares Quarterly Dividend of $0.57 Per Share" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [8]=> object(stdClass)#7 (10) { ["exDate"]=> string(10) "2017-10-31" ["paymentDate"]=> string(10) "2017-11-15" ["recordDate"]=> string(10) "2017-11-01" ["declaredDate"]=> string(10) "2017-08-02" ["amount"]=> float(0.57) ["flag"]=> string(13) "No Change QoQ" ["currency"]=> string(3) "USD" ["description"]=> string(54) "Hasbro Declares Quarterly Dividend of $0.57 Per Share." ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [9]=> object(stdClass)#29 (10) { ["exDate"]=> string(10) "2017-07-28" ["paymentDate"]=> string(10) "2017-08-15" ["recordDate"]=> string(10) "2017-08-01" ["declaredDate"]=> string(10) "2017-05-18" ["amount"]=> float(0.57) ["flag"]=> string(13) "No Change QoQ" ["currency"]=> string(3) "USD" ["description"]=> string(53) "Hasbro Declares Quarterly Dividend of $0.57 Per Share" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } [10]=> object(stdClass)#5 (10) { ["exDate"]=> string(10) "2017-04-27" ["paymentDate"]=> string(10) "2017-05-15" ["recordDate"]=> string(10) "2017-05-01" ["declaredDate"]=> string(10) "2017-02-06" ["amount"]=> float(0.57) ["flag"]=> string(8) "Increase" ["currency"]=> string(3) "USD" ["description"]=> string(38) "Hasbro Hikes Quarterly Dividend 11.76%" ["frequency"]=> string(9) "Quarterly" ["date"]=> string(10) "2019-04-29" } }

**Comment by dmikester1** [comment]
So after looking closer at this it appears the "declaredDated" on those 2 results were different.  Now the two results after those duplicates are duplicates as well.  But they are even harder to identify because the flag is different, declaredDate is different, and the description is very different.  If we could get both sets of duplicates combined or removed that would be great!

**Comment by evancarter-iex** [comment]
@dmikester1 this should be fixed now. Let me know if its not. Sorry about the delay
