### ISSUE TITLE
List of available tickers in the options data

### ISSUE THREAD

**Issue by Jacyle** [iexg/IEX-API#908]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to retrieve a list of tickers who have available options data

**Describe the solution you'd like**
A simple endpoint that returns a list of tickers available in the options data

**Describe alternatives you've considered**

**Additional context**

**Comment by evancarter-iex** [comment]
https://iexcloud.io/docs/api/#options-symbols should work for that.
