### ISSUE TITLE
Forex Data

### ISSUE THREAD

**Issue by audeo23** [iexg/IEX-API#91]
Hi,

I just wanted to know if you have any plan to add forex data to the API ?
Thanks a lot for the work you are doing.

Ludovic.

**Comment by bishinew** [comment]
Please Forex support. We appreciate the API.

**Comment by tg12** [comment]
This, 1000 x this.

**Comment by MasterJames** [comment]
Shouldn't this stay open until there is a proper action plan or explanation that this will not happen?
https://github.com/iexg/IEX-API/issues/103#issuecomment-394161865

**Comment by JohnRobson** [comment]
I believe that if someone finds a Free and Good Quality data from those forex currencies, just send the Link to IEX and asking them to include it. This is the best way to very quickly see the Forex on IEX.

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io

**Comment by MasterJames** [comment]
Okay great. Too bad it's TypeScript.
