### ISSUE TITLE
Is the API down now?

### ISSUE THREAD

**Issue by Itsme23333** [iexg/IEX-API#910]
**Clearly describe the problem**
I had a program running this morning and at about 10:18 it stopped receiving data.  The error is: 

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.  I tried again at almost noon EDT, with the same results.

Also I went to https://iextrading.com/apps/stocks/ which I believe also uses the same API, and there is nothing displayed on the page.

**What time did the problem occur? (with timezone)**
10:18 AM EDT

**What is the expected behavior?**
An API call would succeed.

**Your environment (e.g. browser, OS, API version, language):**
Windows Python

**API URL (if applicable)**
https://cloud.iexapis.com/v1/stock/aapl/chart/date/20180418?chartByDay=True&token=myIEXToken

**What are the steps to reproduce the bug?**
Attempt to access the API.

**Additional context**
Is there a status page that shows the status of the API, or a twitter account?

**Comment by evancarter-iex** [comment]
@Itsme23333 We are up and running. What IP are you hitting us from?

**Comment by Itsme23333** [comment]
47.44.234.138

**Comment by evancarter-iex** [comment]
@Itsme23333 Hmmm nothing in our firewall shows that ip as an issue. From our standpoint everything is up and running.

**Comment by evancarter-iex** [comment]
Could it be another ip?

**Comment by Itsme23333** [comment]
I initially posted the wrong IP. It's 75.137.103.91.

**Comment by Itsme23333** [comment]
I initially posted the wrong IP.  I have posted the correct IP to the
thread.  It's  It's 75.137.103.91.

**Comment by joshuablackburn-iex** [comment]
Our status page is https://status.iexcloud.io/

**Comment by Itsme23333** [comment]
My program finally started to be able to reconnect at exactly 4:15 PM.  It was continuing to run from earlier, so I didn't change anything on my end.  Any idea what happened?

**Comment by evancarter-iex** [comment]
We were up the whole time from our end. Ill investigate some more later today.

**Comment by McQgit** [comment]
I had a cron job run at 10:00am eastern Mon Apr 29 and it timed out too.  I only had a 30s timeout set on my curl and did one retry at 10:01am which also timed out after 30s.  My curl was trying:

https://cloud.iexapis.com/v1/stock/market/batch?symbols=MCD,SBUX,(40 others redacted),SPY&types=quote,previous,ohlc&token=(redacted)

My task was running on an AWS EC2 server.  Hard to know where the fault lied but given @Itsme23333 had similar problem about the same time ... ??

I've run that task daily at 10am for a long time without trouble.  Several weeks or more with the cloud api and more than a year with the prior api.

**Comment by RobinhoodFR** [comment]
Hello!

To confirm what McQgit said I have a similar issue.

The url I use is: https://cloud-sse.iexapis.com/beta/last?symbols=

I do that with a list of 120 symbols real time.

My plateform is dotNet/c# but I guess it did not depend on that. I live in France.

It was working like a charm for a time but since several days the streaming just stop after some minutes of usage. For instance yesterday it stopped working after less thant half an hour. 

I will investigate today if I got any error message from your server.

My best regards

**Comment by McQgit** [comment]
@RobinhoodFR I only had a timeout problem on the Monday morning.  After the failure at 10am I didn't try again until around 1pm and it was fine then and has been fine since.

**Comment by evancarter-iex** [comment]
@RobinhoodFR please file a bug with us or hit us up at support@iexcloud.io. This issue has been resolved though I never saw any issues for @Itsme23333 during that time and our API was up.
