### ISSUE TITLE
[Issue]Trading Symbols End Point Not Working

### ISSUE THREAD

**Issue by bb10128** [iexg/IEX-API#911]
**Clearly describe the problem**

https://cloud.iexapis.com/v1/ref-data/iex/symbols?token=pk_something
returns 4/26/19 list. 

**What time did the problem occur? (with timezone)**

All day long on 4/29/19.

**What is the expected behavior?**

To return a list for 4/29.

**Your environment (e.g. browser, OS, API version, language):**

Chrome, Windows.  V1.  Rest API directly on thru a browser

**API URL (if applicable)**

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by evancarter-iex** [comment]
This should be fixed now. Let me know if its not
