### ISSUE TITLE
[Request] Historic key stats

### ISSUE THREAD

**Issue by para2x** [iexg/IEX-API#912]
**Is your feature request related to a problem? Please describe.**
Well... I'd like to first thank the IEX team for offering such a great service. 
I was wondering if anybody knows if this feature exist or not or if IEX plans to add that at some point. 

**Describe the solution you'd like**
I'd like to get access to historic key starts like marketcap, avgVolume, EPS, and etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by timpaine-iex** [comment]
duplicate of https://github.com/iexg/IEX-API/issues/507
