### ISSUE TITLE
[Issue] Historical prices endpoint not updated

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#913]
**Clearly describe the problem**
Historical prices endpoint is not updated 

**What time did the problem occur? (with timezone)**
2019-04-30 08:17:00 UTC

**What is the expected behavior?**
Historical data for 2019-04-29 and 2019-04-26

**API URL (if applicable)**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=amzn&types=chart&chartLast=2&token=<token>

**What are the steps to reproduce the bug?**
Call https://cloud.iexapis.com/v1/stock/market/batch?symbols=amzn&types=chart&chartLast=2&token=<token>

**Comment by evancarter-iex** [comment]
@gabrieldodan I see data for those days. Do you not?

**Comment by gabrieldodan** [comment]
@evancarter-iex yes but data is updated too late, the docs state that it should be updated after 4am, "Prior trading day available after 4am ET Tue-Sat"

**Comment by gabrieldodan** [comment]
@joshuablackburn-iex @evancarter-iex it's Saturday 11th 4:41 AM New York Time and data for prior trading day is still not available  :(
