### ISSUE TITLE
batch calls error

### ISSUE THREAD

**Issue by slloyd88** [iexg/IEX-API#914]
https://api.iextrading.com/1.0/stock/market/batch?symbols=SNMP,SDR&types=quote,chart,dividends&range=5y

This will only return chart data for the first symbol.
subsequent symbols get dividends in the chart section.

**Comment by evancarter-iex** [comment]
Hi there,

api.iextrading.com is being sunsetted in June. Please move to https://iexcloud.io which has resolved this issue. Thanks.

**Comment by slloyd88** [comment]
I tried going to https://iexcloud.io/ but the website just times out.

This site can’t be reached iexcloud.io took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Comment by evancarter-iex** [comment]
@slloyd88 what ip are you connecting from?

**Comment by slloyd88** [comment]
192.30.201.10

**Comment by slloyd88** [comment]
I also tried on my phone (tMobile) with wifi turned off and get the same message.  My phone has a IPV6 address.
