### ISSUE TITLE
[Data] Price targets are 10x to 100x higher than current price

### ISSUE THREAD

**Issue by marian2js** [iexg/IEX-API#915]
I found 2 symbols where the price targets are way higher than they should: *YDNX* and *BABA*

YNDX price targets (currently $37.40)
```
{
  symbol: 'YNDX',
  updatedDate: '2019-04-25',
  priceTargetAverage: 2869.16,
  priceTargetHigh: 3299.67,
  priceTargetLow: 2005.68,
  numberOfAnalysts: 15
}
```

BABA price targets (currently $185.87)
```
 {
  symbol: 'BABA',
  updatedDate: '2019-04-28',
  priceTargetAverage: 1399.12,
  priceTargetHigh: 1913.49,
  priceTargetLow: 828.53,
  numberOfAnalysts: 45 
}
```

**What time did the problem occur (including timezone)?**
The error has been occurring at least for the last 4 days

**Comment by evancarter-iex** [comment]
@marian2js Sorry for the delay we are looking into this

**Comment by marian2js** [comment]
Hi @evancarter-iex, thanks for following up on this. I just found that **JD.CH** also has the same issue.

**Comment by evancarter-iex** [comment]
This has to do with the price targets being in the local currency.

**Comment by jesseorosz** [comment]
Any update?
