### ISSUE TITLE
Is there any plan to enhance the type of data provided for Company profile info beyond a single-sentence description?

### ISSUE THREAD

**Issue by estrnod** [iexg/IEX-API#916]
I am accustomed to seeing much more descriptive detail on a Company profile, and using it to determine the range of things a company is involved in, countries they do business in, other companies they may hold, etc.  The type of information being currently returned is more often than not, common knowledge.   (Not to always be pointing at Yahoo, but they are a good example - and a public source.  Look up any stock and look at the profile - for instance, https://finance.yahoo.com/quote/WRK/profile?p=WRK, go to "Profile" tab and scroll down to "Description" below the map.  This is the kind of data I am looking for, and think users of our apps will be also.)

**Comment by mfeenstra** [comment]
Yes please return the description information, it is very helpful, thank you.  The long description still exists in the 1.0 api.

**Comment by evancarter-iex** [comment]
@estrnod @mfeenstra We have updated our company profiles to be more descriptive.
