### ISSUE TITLE
1 API request should be 1 message used

### ISSUE THREAD

**Issue by slloyd88** [iexg/IEX-API#917]
**Clearly describe the problem**
When I make this call it adds over 100k messages as used.  WHY?  Shouldn't 1 hit to your server equal 1 message?  How are you defining a message?

https://cloud.iexapis.com/stable/stock/market/batch?symbols=sdt&types=quote,chart,dividends&range=5y

**What time did the problem occur? (with timezone)**

**What is the expected behavior?**
One API hit should be 1 message, not thousands.

**Your environment (e.g. browser, OS, API version, language):**

**API URL (if applicable)**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=sdt&types=quote,chart,dividends&range=5y
**What are the steps to reproduce the bug?**

**Additional context**

I have used your new system for less than 10 minutes trying it out and it says I have already used  116,295 messages.  Even though I have maybe hit your server 20 times max.

**Comment by McQgit** [comment]
@slloyd88  IEX uses a weighting scheme for message count.  See this intro item:
[]https://iexcloud.io/docs/api/#data-weighting

And especially this as it is likely the one causing your very high usage:
[]https://iexcloud.io/docs/api/#historical-prices

I agree their docs could be better but this will clarify that you shouldn't be expecting 1 call being 1 message.

**Comment by slloyd88** [comment]
Then there is no practical way to measure usage.  I could use up the free 500,000 messages in less than 10 minutes by getting historical data for 20 or so stock symbols.  So how would I know what "Plan" to upgrade to?  This kind of measurement just confuses the user.

**Comment by evancarter-iex** [comment]
@slloyd88 https://intercom.help/iexcloud/getting-started/getting-started-with-iex-cloud has a lot of information on data weighting. Also this document walks you through testing and to do it to figure out how much your costs will be https://intercom.help/iexcloud/getting-started/testing-iex-cloud

@McQgit Thanks for the links, been meaning to ask you to email support@iexcloud.io (its good don't worry). When you have a chance can you drop us an email?

**Comment by Itsme23333** [comment]
I just wanted to add that you can use the sandbox functionality to make exactly the calls you want to make and get back dummy data and it will tell you the number of dummy messages sent, but it doesn't cost you any real messages.  I found it very useful in converting one of my programs, and I will be using it in the future for other programs as well.
