### ISSUE TITLE
options query for VIX.CBO not working

### ISSUE THREAD

**Issue by Jacyle** [iexg/IEX-API#918]
**Clearly describe the problem**
'https://cloud.iexapis.com/v1/stock/VIX.CBO/options/201905?token=%s' returns 'JSONDecodeError: Expecting value'.

VIX.CBO appears in the /ref-data/options/symbols list of symbols.

**What is the expected behavior?**
Returns VIX CBOE options information

**Comment by evancarter-iex** [comment]
@Jacyle we are looking into this

**Comment by evancarter-iex** [comment]
This is fixed now.
