### ISSUE TITLE
[Data] Duplicate dividend entry with New Jersey Resources

### ISSUE THREAD

**Issue by dmikester1** [iexg/IEX-API#919]
**Clearly describe the data problem**
There is a duplicate entry for the dividend data for New Jersey Resources.  It is almost certainly duplicate but different enough that it is causing me issues.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/NJR/dividends/2y?token=

**What time did the problem occur (including timezone)?**
4/30/19 in evening

**What is the expected behavior?**
For the API to return unique seperate dividend data for each stock.

**What are the steps to reproduce**
Make the API call asking for the last 2 years of dividends for New Jersey Resources

**Your environment (e.g. browser, OS, API version, language):**
Firefox, Windows 10, V1, English/PHP

**Additional context**
Here are the 2 duplicate entries.  I don't know why the amount is different therefore causing the flag to be different.  Please combine/remove the duplicate.
  2 => 
  (object) array(
     'exDate' => '2018-09-20',
     'paymentDate' => '2018-10-01',
     'recordDate' => '2018-09-21',
     'declaredDate' => '2018-07-10',
     'amount' => 0.2725,
     'flag' => 'No Change QoQ',
     'currency' => 'USD',
     'description' => 'New Jersey Resources Corp. Declares Quarterly Dividend of $0.2725 Per Share',
     'frequency' => 'Quarterly',
     'date' => '2019-04-30',
  ),
  3 => 
  (object) array(
     'exDate' => '2018-09-20',
     'paymentDate' => '2018-10-01',
     'recordDate' => '2018-09-21',
     'declaredDate' => '2018-09-10',
     'amount' => 0.2925,
     'flag' => 'Increase',
     'currency' => 'USD',
     'description' => 'New Jersey Resources Hikes Quarterly Dividend 7.34%',
     'frequency' => 'Quarterly',
     'date' => '2019-04-30',
  ),

**Comment by evancarter-iex** [comment]
@dmikester1 we are looking into this.

**Comment by dmikester1** [comment]
Thank you for your quick response!  Can you look at the duplicate entries for Hasbro also?  I created an issue a couple days ago.

**Comment by evancarter-iex** [comment]
@dmikester1 yup we are looking into that one as well. Ill let you know when have a resolution.

**Comment by evancarter-iex** [comment]
@dmikester1 HAS and NJR should be fixed. Sorry about the delay on that.
