### ISSUE TITLE
Issue when using the following code in VBA

### ISSUE THREAD

**Issue by jshanaphy** [iexg/IEX-API#92]
Trying to use the IEX API to pull data in to Excel workbooks using VBA, here is the code I wrote (basic)
   
 Function StockPrice(ticker As String, item As String) As Double

    Dim strURL As String, strCSV As Double, itemFound As Integer, tag As String

    itemFound = 0
    If item = "lastprice" Then
        tag = "price"
        itemFound = 1
    ElseIf item = "pe" Then
        tag = "peRatio"
        itemFound = 1
    
    End If

    If itemFound = 1 Then
    
        strURL = "https://api.iextrading.com/1.0/stock/" & ticker & "/" & tag
        Set XMLHTTP = CreateObject("MSXML2.XMLHTTP")
        XMLHTTP.Open "GET", strURL, False
        XMLHTTP.send
        StockPrice = XMLHTTP.responseText
        Set XMLHTTP = Nothing
        
    Else
    
        StockPrice = "Item Not Found"
        
    End If

    End Function

The price parameter works, however PE Ratio does not. If I enter https://api.iextrading.com/1.0/stock/ulta/peRatio in my browser to test, I end up getting a "Forbidden" message. Additionally, while the price part of my macro works, it will not update when I refresh connections, and if I use capital letters for the ticker (ie ULTA vs ulta), there are two different prices being pulled, both of which normally differ from the real time price on the Stocks app created by IEX. Any ideas on what I'm doing wrong? I'd like to be able to eventually make use of all the data IEX provides in my Excel book, but clearly I'm doing something incorrectly. Thanks

**Comment by joshuablackburn-iex** [comment]
Looks like you're missing the endpoint.  The URL should be https://api.iextrading.com/1.0/stock/ulta/quote/peRatio

**Comment by jshanaphy** [comment]
Thank you for the quick fix. Clearly I should've been more attentive reading the manual before posting this. Sorry about that.
