### ISSUE TITLE
[Data] Missing dividends for certain ETFs

### ISSUE THREAD

**Issue by chortleflux** [iexg/IEX-API#920]
**Clearly describe the data problem**
New dividends are missing today for certain ETFs that have today (May 1, 2019) as their ex-dividend date.

The example below is for JNK, but the same holds true for TFI, and CWB.

Note that other ETFs with today as their ex-dividend date have the correct data (eg CMBS, EMB, LQD among others).

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/beta/stock/JNK/dividends?token=XXXX&range=1m

**What time did the problem occur (including timezone)?**
1:00pm CST

**What is the expected behavior?**
There should be a dividend appearing with exDate equal to 2019-05-01 with amount equal to 0.17078

**What are the steps to reproduce**
Request the data as per the url above

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**
The previous months dividend appears with the correct details (which is ok), but the new dividend should appear as well.

**Comment by evancarter-iex** [comment]
This appears to be due the fact that our update ran before midnight. Ill see if we can make it run after midnight as well to hopefully catch this in the future.

**Comment by chortleflux** [comment]
Thanks for looking into this.  JNK is a 10 billion USD ETF, and it is very important to have the dividend data available before the market open on the ex-dividend date.  

CWB is 4 billion USD, and TFI is 3 billion USD.  I am pointing this out to indicate that it is really important to get these right as they are each among the largets ETFs for their asset class.

**Comment by evancarter-iex** [comment]
@chortleflux understood. We updated our nightly jobs to run before and after midnight as well as at around 4am eastern time. If you see something similar going forward please let us know.

**Comment by chortleflux** [comment]
Today the same issue happened (around 8:30am EST) with the following dividends not available (all have today June 3, 2019 as ex-dividend date):

EMB
EMLC
JNK
LQD
MBB
TIP
CWB
TFI
CMBS

Again, these are major ETFs with significant market cap (except CMBS, which is small).

Can you please look into what happened?  Thanks.

**Comment by evancarter-iex** [comment]
@chortleflux This appears to be related to the Google Cloud issues this weekend. There was some significant issues which caused boxes not to register properly or got stuck in a weird state. I kicked them and they are working now. I am investigating if theres anything we can do to avoid this in the future (though it was a pretty big google cloud issue this weekend)

**Comment by chortleflux** [comment]
Thanks for investigating.

**Comment by evancarter-iex** [comment]
@chortleflux This should be fixed now. We are looking into ways to continue to durablize the setup, but as stated, Sunday GCE issues were widespread.

**Comment by chortleflux** [comment]
Missing VGK dividend (ex-div date is today, amount is 0.9598).  Market cap of VGK is 18.6 billion USD.

Other Vanguard ETFs that dividends with ex-div date today that I examined look good (VNQI, VT, VWO, and others).

**Comment by chortleflux** [comment]
I don't have the ability to reopen this issue, but I believe it should be reopened.  Today the following dividends are missing (all have today 6/21/2019 as their ex-dividend date):

XLE
SPY
XLV
XLK
VPU

Note that SPY is the largest ETF in the world.  I am sure more ETFS with today as ex-dividend date are missing in addition to these.  Can you please look into this?
