### ISSUE TITLE
Update Documentation to state billing starts at 00:00 UTC at 1st of the month

### ISSUE THREAD

**Issue by Itsme23333** [iexg/IEX-API#922]
**Clearly describe the problem**
What time zone is used for determining the start of the month as far as message usage goes?  On April 30th, I completed downloading some data using the API at 10:00 PM EDT.  I was surprised to view in my console that I had used 594,280 messages for the month of May, since as far as I know I hadn't made any calls in May.  My console shows that these were historical data calls, which is what I was making on April 30th, so the billing is probably for the calls that I made, but I'm surprised that the calls I made in April were billed in May instead of April.

**What time did the problem occur? (with timezone)**
10:00 PM EDT

**What is the expected behavior?**
That billing would be based on EDT/EST or that if it is based on GMT that would be clearly disclosed.  I'm not asking for these calls to be credited back to my account if this is the expected behavior, but if it is the expected behavior then it should be clearly documented.

**Your environment (e.g. browser, OS, API version, language):**
Windows Python

**API URL (if applicable)**
Stock Historical

**What are the steps to reproduce the bug?**
Make historical stock calls at around 10:00 PM EDT on the last day of the month.

**Additional context**

**Comment by evancarter-iex** [comment]
Billing is based on UTC time. We will add a note in the documentation


________________________________

**Comment by evancarter-iex** [comment]
This is documented in the latest documentation we push out.
