### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by juliuskittler** [iexg/IEX-API#923]
**Clearly describe the data problem**

For some tickers (only IEX tickers due to chartIEXOnly=true), I am getting empty .csv files  when trying to download historic intra-day data (see api-urls below). The specified dates seem to be within the valid time period. For some tickers, correct and full .csv files are returned, whereas for others empty .csv files are returned. It is not clear why for some tickers empty .csv files are returned. 

Other tickers that are not available get a response with an error message that they are not found. This is not the case for the tickers for which empty .csv files are returned. Hence, the empty .csv file issue is not because these tickers are not available.

**Data URL (The URL you used to access the data without your token):**

*Here are a few examples that return empty .csv files:*

https://cloud.iexapis.com/stable/stock/CEL/chart/date/20190311?format=csv&token=MY_TOKEN&chartIEXOnly=true

https://cloud.iexapis.com/stable/stock/CELGZ/chart/date/20190311?format=csv&token=MY_TOKEN&chartIEXOnly=true

https://cloud.iexapis.com/stable/stock/CELH/chart/date/20190311?format=csv&token=MY_TOKEN&chartIEXOnly=true

*Here are a few examples that return full .csv files:*

https://cloud.iexapis.com/stable/stock/CALF/chart/date/20190311?format=csv&token=MY_TOKEN&chartIEXOnly=true

https://cloud.iexapis.com/stable/stock/CALM/chart/date/20190311?format=csv&token=MY_TOKEN&chartIEXOnly=true

https://cloud.iexapis.com/stable/stock/CALX/chart/date/20190311?format=csv&token=MY_TOKEN&chartIEXOnly=true

**What time did the problem occur (including timezone)?**

This problem keeps occuring. It was recorded on various time points on 
2019-05-02 between e.g. 9:00 and 13:00 (timezone Sweden).
 
**What is the expected behavior?**

It's not clear why the response is empty. Were there no trades? (If so, there should be a response with 0 values.) Was the ticker not existing? (If so, there should be a different type of response.)

**What are the steps to reproduce**

Open one of the above links in the browser and you will see that an empty .csv file gets downloaded.

**Your environment (e.g. browser, OS, API version, language):**

- macOS High Sierra, 10.13.4 
- various browsers (Chrome, Opera) 
- API version: see api_urls above (it seems like they use the last stable version)

**Additional context**

**Comment by evancarter-iex** [comment]
@juliuskittler can you try again?

**Comment by juliuskittler** [comment]
@evancarter-iex It works for the api_url examples that I mentioned previously. However, it does not work for other examples e.g.:

https://cloud.iexapis.com/stable/stock/CVRS/chart/date/20190401?format=csv&token=MY_TOKEN&chartIEXOnly=true

https://cloud.iexapis.com/stable/stock/CWAI/chart/date/20190401?format=csv&token=MY_TOKEN&chartIEXOnly=true

https://cloud.iexapis.com/stable/stock/CZNC/chart/date/20190401?format=csv&token=MY_TOKEN&chartIEXOnly=true

What did you do to fix the the api_url examples that I mentioned previously? Why does it work sometimes but sometimes not?

**Comment by evancarter-iex** [comment]
@juliuskittler Hi there, this should be fixed going forward. We added some redundancy checking to prevent "holes" in the minute bars for whatever reason and then backported it for the available dates. If you see any others go ahead and open a new ticket.
