### ISSUE TITLE
[Data] 429 server error // Realtime "last" on 120 stocks

### ISSUE THREAD

**Issue by RobinhoodFR** [iexg/IEX-API#925]
**Clearly describe the data problem**

IEX websocket API (last datapoint) server response return randomly "(429) Too Many Requests."
It was working fine for a time with arround 120 stocks (among most liquid). Since some days I receive this error. After investigating it seems to be a server limit on IEX side.

**Data URL (The URL you used to access the data without your token):**

https://cloud-sse.iexapis.com/beta/last?symbols=

**What time did the problem occur (including timezone)?**

When US equities markets are open

**What is the expected behavior?**

Streaming last datapoint for 120 US stocks realtime.

**What are the steps to reproduce**

Use the URL above with 120 among most liquid stocks (DJI and NDX100 stocks for instance)

**Your environment (e.g. browser, OS, API version, language):**

C#/dotNet

**Additional context**
I planned to stream a larger number of stocks. If it is confirm that IEX cap the number of stocks that could be streamed real time it is gonna be an issue for me.
Thanks by advance!

**Comment by evancarter-iex** [comment]
@RobinhoodFR  Hi there, sorry for this, we had an issue with some users causing stability issues so we had to put in a temporary fix short term to prevent it falling over for everyone. You can subscribe to up to 50 stocks per connection. Feel free to open several connections in the short term while we work on a longer term fix.

**Comment by RobinhoodFR** [comment]
Thanks evan. My ip: 86.252.215.46 (not fixed to my mind)
