### ISSUE TITLE
[Data] WW post market prices not moving

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#926]
**Clearly describe the data problem**
WW is moving after hours on its earnings report 2/5/19, but IEX shows extended movement of 0.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stock/WW/quote
**What time did the problem occur (including timezone)?**

From post market onwards.
**What is the expected behavior?**
We should be seeing post market movements.

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

Chrome/Linux/Python
**Additional context**

**Comment by evancarter-iex** [comment]
@professorDante Has this been an issue post this date? Ive been eyeballing WW and other stocks and they seem okay.

**Comment by professorDante** [comment]
It seems OK now - but this seems to be a recurring issue with post/pre market data. It sometimes just seems to return garbage numbers. This one was just easily noticeable, as there was a big move in post market due to earnings. I don't have 100% confidence in the pre/post market data at the moment.

**Comment by evancarter-iex** [comment]
@professorDante I am not seeing any additional issues. Just remember that pre/post market data is 15 minute delayed.  
If it happens again lets reopen/file a new bug. Thanks
