### ISSUE TITLE
Implement functionality to make it easier to keep adjusted data up-to-date

### ISSUE THREAD

**Issue by Itsme23333** [iexg/IEX-API#927]
**Is your feature request related to a problem? Please describe.**

Probably a very common use case for IEX Cloud data is to download historical data for multiple stocks, then keep that data up-to-date by downloading just the most recent data for those stocks daily or weekly.  For unadjusted data, the old data never changes, so it’s only necessary to initialize a database with the historical data then insert newer data whenever it is downloaded, such as daily, weekly, etc.
For adjusted data, the situation is different.  Any time there is a split, the older data is no longer valid and the old data must either be adjusted based on a split factor, or all the historical data for that symbol must be downloaded again.  A user can choose either option depending on what they prefer.

The problem is knowing when there has been a split in a particular symbol.  There is nothing in a given day’s pricing information to know that a split has taken place on that day for that particular symbol.  The splits endpoint is not well-suited to this task because you would need to query it for every symbol every time you downloaded new adjusted data, and most of the information returned would not be useful because you can’t restrict it to a date range.

In my case, when I determine that a split has taken place, I will download all the adjusted historical data for a symbol instead of trying to adjust the previously downloaded data.  What I am seeking is a way to determine when to download the adjusted data again for a symbol.  This solution would also work for users who choose to adjust the previously downloaded adjusted data instead of re-downloading it.

**Describe the solution you'd like**
As an overview, there are three good solutions to this problem that I can see.  Either include the most recent split date with the Symbols endpoint, or set up another splits endpoint that would allow splits inquiries for all symbols with a date range or include information with the historical data indicating the last split date, Any of the options would be suitable to me.  I am presenting them with my most preferred option first.

--Option 1:  Include the lastSplitDate with the data returned by the Symbols call.--
This could be an optional parameter for the Symbols call such as

GET /ref-data/symbols&includeLastSplitDate=true.

The data returned would have a lastSplitDate value returned for each stock (that had ever split) as part of the returned JSON.

Another variant for this option would be to let the call look like
GET /ref-data/symbols&showLastSplitDateAfter=20190101.

The data returned in this call would only have a lastSplitDate value returned if the most recent split date for the symbol is on or after the showLastSplitDateAfter value.

 
An example returned data might look like:

[
  {
    "symbol": "A",
    "name": "Agilent Technologies Inc.",
    "date": "2019-03-07",
    "type": "cs",
    "iexId": "IEX_46574843354B2D52",
    "region": "US",
    "currency": "USD",
    "isEnabled": true,
     **“lastSplitDate”:”2014-11-03”**
  },
  {
    "symbol": "AA",
    "name": "Alcoa Corp.",
    "date": "2019-03-07",
    "type": "cs",
    "iexId": "IEX_4238333734532D52",
    "region": "US",
    "currency": "USD",
    "isEnabled": true,
    **“lastSplitDate”:”2016-10-06”**
  }
]

--Option 2: Have another splits endpoint that would show the most recent split dates for all symbols (those symbols returned by a GET /ref-data/symbols call) within a specified date range—

Note that this option does not return the multiplier for a given split.  It would only need to return the exDate, and it would not need to return all splits for that symbol within the time range.  It only needs to return the most recent split where the exDate is either in the past or today.  If the exDate is in the future then it does not get returned.  Because this call does not return as much data as a call to the splits endpoint, then it should be cheaper to call.  Perhaps 2 per symbol.  The purpose of this call is to provide the user with a list of symbols that have split during the specified time period.  The user can then call the splits endpoint only for those symbols that have split during this period of time instead of for all symbols.  The date range would begin with the beginDate specified in the URL and end with the current date.  If you wanted to support an optional endDate parameter then some people might find that useful, but I envision not needing that parameter.  The payload would only include those stocks which have split during the interval.

This option would be called with a URL such as:
GET /stock/splits&beginDate=20190401
and the return JSON might look like:

[
    {
        "Symbol": "Stock1",
        "exDate": "2019-04-05"
    } ,
    {
        "Symbol": "Stock2",
        "exDate": "2019-04-23"
    } 
]

--Option 3:  Include a last split date with the historical data—

This option would involve including a lastSplitDate value with the data returned by the Historical Prices endpoint, and possibly the quote endpoint (The quote endpoint wouldn’t matter to me, but it might matter to some users).  The lastSplitDate field would indicate the most recent date for a split for that symbol.  It would not include the multiplier for the split.  This value could always be returned as part of the historical data, or it might only be returned if a parameter is included with the historical data call such as showLastSplitDateAfter=2019-04-01, which would only return a value for lastSplitDate if the lastSplitDate was on or after the showLastSplitDateAfter value.  An example of the historical data would be

[
{
"date":"2018-04-18",
"uClose":177.84,
"uOpen":177.81,
"uHigh":178.82,
"uLow":176.88,
"uVolume":20754538,
"close":177.84,
"open":177.81,
"high":178.82,
"low":176.88,
"volume":20754538,
"change":0,
"changePercent":0,
"label":"Apr 18, 18",
"changeOverTime":0,
**“lastSplitDate”:”2014-06-09”**
}
]

**Describe alternatives you've considered**
I would be open to any other solution that implements this functionality.  There are a few ways to implement this functionality without your implementing one of these solutions, but they require considerably more work to implement on the user side of things.

**Comment by jkPnF** [comment]
I agree with the OP. Any other user side implementation is quite cumbersome. Would it be possible to implement one of the above options suggested?

**Comment by joshuablackburn-iex** [comment]
In the meantime, this can be done using the splits endpoint https://iexcloud.io/docs/api/#splits

**Comment by Itsme23333** [comment]
I ask again that you consider adding this functionality.  Although you mention that this can be done by calling the splits endpoint, that is not a practical solution.  The cost for the splits endpoint is 75,000 per call and if there are about 9,000 symbols then that works out to be 67,000,000 messages to determine which symbols have been split.  And since I'm trying to keep this up to date daily, if we assume 22 days per month, it would take 1.5 billion calls per month.  Just to reinterate, I'm not looking to get all the information contained in the splits endpoint for free.  I just need to know when to call the splits endpoint, and you provide that information by returning the last split date as part of historical data, or have a separate splits endpoint that just provides the last split data, without the other information at a much lower cost.

**Comment by jkPnF** [comment]
IEX - We urge you to consider adopting one of the options outlined by itsme23333 above. This will make it developer friendly. Any decent chart building application that utilizes end-of-day data has a huge hole because of the lack of a simple way to know if a stock split or had a price adjustment due to dividend etc. Other providers like quandl provide a easy way to get to this. 

Right now, the lack of the simpler options make us want to consider Quandl as our data provider of choice. I realize that there's a plethora of items your dev team can work on but something like providing these basic options will develop a lot of credibility of your platform with indie developers. We have been pinging you for the past 6 months to review this request but feel like we are not being heard to.

**Comment by Itsme23333** [comment]
Please keep this suggestion under consideration.  Even though I have coded a cumbersome, but workable solution for myself, which consumes 2 messages per stock per day, I feel that it would be very useful for other users, and if it were available, I would switch over to using it myself.

**Comment by Itsme23333** [comment]
Please consider implementing this suggestion.

**Comment by timpaine-iex** [comment]
[Splits](https://iexcloud.io/docs/api/#splits-basic) is only `10` per record and can be queries like any other time-series endpoint with custom ranges/limit of number of records returned:

e.g. querying over a custom range:
https://cloud.iexapis.com/stable/time-series/SPLITS/?from=2021-08-10&to=2021-08-31&token=...

just getting the last few:
https://cloud.iexapis.com/stable/time-series/SPLITS/?last=10&token=...

getting a predefined range:
https://cloud.iexapis.com/stable/time-series/SPLITS/?range=ytd&token=...

getting for a given symbol:
https://cloud.iexapis.com/stable/time-series/SPLITS/NVDA/last=1&token=...

**Comment by Itsme23333** [comment]
Thanks, Tim.

Thank you for the examples.  I was unaware that you could get the most recent splits from the endpoint.  I thought that you had to specify symbols as part of the call.  Although the information provided with the splits endpoint does not implement my preferred solution, it is adequate for my needs, so I will close this issue.

I appreciate your help.
