### ISSUE TITLE
1 minute Chart data not returning for several stocks for 5/2/2019 (e.g. AGQ, AIA)

### ISSUE THREAD

**Issue by scottyrotten6** [iexg/IEX-API#928]
**Clearly describe the data problem**
1 minute chart data is not returning any data for may 2 for several symbols. I tried it with iextrading/1.0 and it still works.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/AGQ/chart/date/20190502/?token=myToken&filter=minute,marketOpen,marketHigh,marketLow,marketClose,marketVolume&format=csv

**What time did the problem occur (including timezone)?**
5/2/2019 but could be more dates that aren't working

**What is the expected behavior?**
I expect a csv file to be returned with the requested data.

**What are the steps to reproduce**
Just follow the URL above. It will return an empty csv file.

**Your environment (e.g. browser, OS, API version, language):**
google chrome, Windows, v1, english

**Additional context**

**Comment by evancarter-iex** [comment]
@scottyrotten6 Is this still an issue?

**Comment by scottyrotten6** [comment]
Sorry for the delayed response. I was out of town for the weekend. It is working fine now. Thank you for fixing it!
