### ISSUE TITLE
Unable to query Dividend Daily List

### ISSUE THREAD

**Issue by ophirbuchman** [iexg/IEX-API#929]
**Clearly describe the data problem**
The query always returns empty

**Data URL (The URL you used to access the data without your token):**
/ref-data/daily-list/dividends
/ref-data/daily-list/dividends/20171210

**What time did the problem occur (including timezone)?**
It's a continuous issue

**What is the expected behavior?**
Expect to return a list of companies which ex-date occurs on the relevant date
Same as "https://www.nasdaq.com/dividend-stocks/dividend-calendar.aspx"

**What are the steps to reproduce**
Navigate to URL

**Your environment (e.g. browser, OS, API version, language):**
Using Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**

**Comment by evancarter-iex** [comment]
@ophirbuchman First api.iextrading.com is being sunsetted in June. Please move over to using https://iexcloud.io for everything except IEX data (like the request you are making)

Second, That endpoint returns dividends for "IEX-listed securities" only. For a list of IEX Listed securities please query https://api.iextrading.com/1.0/ref-data/daily-list/symbol-directory

Thanks.

**Comment by ophirbuchman** [comment]
Thanks - I will move to the new API
Can you please let me know if you do have a query which provides a dividend ex-date calendar?
