### ISSUE TITLE
net asset value(NAV) for closed end mutual funds

### ISSUE THREAD

**Issue by jeinis** [iexg/IEX-API#930]
I am requesting that the statistic net asset value(NAV) be added to the iexapi for  closed end mutual funds

**Comment by evancarter-iex** [comment]
Are you referring to cloud or api.iextrading.com. Api.iextrading.com is sunsetting on June 1st.

**Comment by evancarter-iex** [comment]
Closing, since this in the roadmap in the console, and the old api sunsets June 1st.
