### ISSUE TITLE
[Data] Historical Volume for  London Stock Exchange issues

### ISSUE THREAD

**Issue by AndreRoehrig** [iexg/IEX-API#932]
**Clearly describe the data problem**
Many equities on the London market show wrong adjusted prices. Prices are changing by over 2000000% from day to day regularly.

**Data URL (The URL you used to access the data without your token):**
some examples (but there are many more):
https://cloud.iexapis.com/beta/stock/CTR-LN/chart/max?token=xxx&chartCloseOnly=true
https://cloud.iexapis.com/beta/stock/CPT-LN/chart/max?token=xxx&chartCloseOnly=true
https://cloud.iexapis.com/beta/stock/CZN-LN/chart/max?token=xxx&chartCloseOnly=true
https://cloud.iexapis.com/beta/stock/AXS-LN/chart/max?token=xxx&chartCloseOnly=true

**What time did the problem occur (including timezone)?**
Always

**What is the expected behavior?**
Correct adjusted prices. In some cases it seems that stock splits were not observed for the adjusted prices.

**What are the steps to reproduce**
Call the API.

**Your environment (e.g. browser, OS, API version, language):**
doesn't matter here

**Additional context**

**Comment by evancarter-iex** [comment]
@AndreRoehrig We are looking into this.

**Comment by evancarter-iex** [comment]
@AndreRoehrig Just to give you some more clarity, we are trying to track down with our data provider exactly why this is occuring, its a multistage process on our end.

**Comment by jaylancer43** [comment]
Hello, is this issue fixed ? I am seeing wrong prices for LSE as of today. Some details as below

	2019-07-17   ELM.LN    Actual Close = 132.10         IEX API Close = 1.32
	2019-07-17   EZJ.LN     Actual Close = 1034.50       IEX API Close = 10.34

**Comment by jaylancer43** [comment]
Also the volumes of LSE are way too incorrect, any idea if this is being looked up to get fixed ?

**Comment by evancarter-iex** [comment]
@jaylancer43 The prices for those are items are in pounds vs pence. Can you give me an example of the volume issue so I can see whats going on there?

**Comment by jaylancer43** [comment]
Hello, thanks for your reply. Please consider the following 2 examples for instance for 18 July 2019 in comparison with yahoo volume. The IEX volume are quite different. 

Symbol | Volume IEX | Volume yahoo | Date
AEO | 178,166 | 183,166 | 7/18/2019
HSBA | 12,795,672 | 17,569,609 | 7/18/2019

I can give more example if you would like to. Its happening only for historical volumes.
