### ISSUE TITLE
Values aren't updates consistently

### ISSUE THREAD

**Issue by Sterillium** [iexg/IEX-API#935]
**Clearly describe the problem**
latest* values (e.g. latestPrice) aren't updated consistently even though the real price is fluctuating actively. I'm polling $TSLA prices about once every 4 seconds. More times than not, the values I receive back are the same as the previous. Sometimes the "latestPrice" value takes more than a minute to change even though I'm polling every 4 seconds.

**What time did the problem occur? (with timezone)**
Occurs continually. 

**What is the expected behavior?**
I would expect the latestPrice to change at least once every 4 seconds. 

**Your environment (e.g. browser, OS, API version, language):**
Multiple environments. 

**API URL (if applicable)**
https://cloud.iexapis.com/beta/stock/TSLA/quote?token=pk_XXXXXXXXXXXXXXX

**What are the steps to reproduce the bug?**
Poll the latestPrice continually every 4 seconds for a few minutes

**Additional context**
![ScreenHunter 769](https://user-images.githubusercontent.com/7354624/57243130-9c567480-7035-11e9-8d23-2f9eec417112.png)

**Comment by evancarter-iex** [comment]
@Sterillium Hey there, Our latestPrice values come from trades on IEX or 15 minute delayed from the SIP. Some stocks are more active/less active depending on the minute/hour/time of day on IEX in this case TSLA seems very "bursty" on IEX currently, which accounts for what you are seeing.
