### ISSUE TITLE
[Data] Estimates API returns incorrect announceTime

### ISSUE THREAD

**Issue by rittik97** [iexg/IEX-API#936]
**Clearly describe the data problem**
For several stocks that are expected to release earnings before trading hours, DMT is returned instead of BTO. 
Expected value: "announceTime":"BTO"
Returned value: "announceTime":"DMT"

This is happening with the majority of stocks reporting before market hours. 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/beta/stock/M/estimates?token=token

**What time did the problem occur (including timezone)?**
All times 

**What is the expected behavior?**
"announceTime":"BTO"

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by shoujs** [comment]
I have the same question. What does DMT mean?

**Comment by rittik97** [comment]
I believe it is During Market Trading. 
Lot's of issues with the new v2 IEX API unfortunately. Has set back development over a month for me.
Lot's issues with their quotes and prices as well. 
Really regret migrating from v1.

**Comment by joshuablackburn-iex** [comment]
@rittik97 Can you elaborate on the quote and price issues? We have far more data than the v1 API, some of which has had a few 3rd party integration issues, but we need to have issues filed in order to fix them.

The old v1 API will be sunset on June 1st, so if there are actual issues we'd like to know about them and get it fixed asap.

**Comment by shoujs** [comment]
> I believe it is During Market Trading.
Actually it is before market opening. So the DMT seems not intuitive to me.

**Comment by evancarter-iex** [comment]
This should be resolved. If it isnt please send an email to support@iexcloud.io
