### ISSUE TITLE
[Data] Close in Quote Endpoint is a day behind

### ISSUE THREAD

**Issue by roykhchan** [iexg/IEX-API#938]
**Clearly describe the data problem**
Close and PreviousClose for Quote Endpoint is a day behind, and api.iextrading.com is accurate.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/SPY/quote

**What time did the problem occur (including timezone)?**
2019-05-07 11:15 PM MST

**What is the expected behavior?**
The close price for SPY

**What are the steps to reproduce**
run the Data URL

**Your environment (e.g. browser, OS, API version, language):**
Chrome

**Additional context**
From: https://cloud.iexapis.com/stable/stock/SPY/quote
{"symbol":"SPY","companyName":"SPDR S&P 500 ETF Trust","calculationPrice":"close","open":290.15,"openTime":1557235800048,"close":292.82,"closeTime":1557259200375,"high":290.81,"low":285.81,"latestPrice":292.82,"latestSource":"Close","latestTime":"May 7, 2019","latestUpdate":1557259200375,"latestVolume":144596691,"iexRealtimePrice":288.58,"iexRealtimeSize":200,"iexLastUpdated":1557262774300,"delayedPrice":288.42,"delayedPriceTime":1557259800003,"extendedPrice":288.08,"extendedChange":-4.74,"extendedChangePercent":-0.01619,"extendedPriceTime":1557272697363,"previousClose":294.03,"change":-1.21,"changePercent":-0.00412,"iexMarketPercent":0.01802863524726164,"iexVolume":2606881,"avgTotalVolume":62466662,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":0,"peRatio":null,"week52High":294.95,"week52Low":233.76,"ytdChange":0.166317}

From: https://api.iextrading.com/1.0/stock/SPY/quote
{"symbol":"SPY","companyName":"SPDR S&P 500","primaryExchange":"NYSE Arca","sector":"","calculationPrice":"close","open":290.15,"openTime":1557235800048,"close":287.93,"closeTime":1557259200375,"high":290.81,"low":285.81,"latestPrice":287.93,"latestSource":"Close","latestTime":"May 7, 2019","latestUpdate":1557259200375,"latestVolume":142452514,"iexRealtimePrice":288.58,"iexRealtimeSize":200,"iexLastUpdated":1557262774300,"delayedPrice":287.93,"delayedPriceTime":1557259800001,"extendedPrice":288.59,"extendedChange":0.66,"extendedChangePercent":0.00229,"extendedPriceTime":1557262785796,"previousClose":292.82,"change":-4.89,"changePercent":-0.0167,"iexMarketPercent":0.0183,"iexVolume":2606881,"avgTotalVolume":64413655,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":272448003900,"peRatio":null,"week52High":294.95,"week52Low":233.76,"ytdChange":0.13926145376615887}

**Comment by evancarter-iex** [comment]
@roykhchan has this reoccurred?

**Comment by roykhchan** [comment]
@evancarter-iex yesterday was fine, but today this issue reoccurs again. 

From: https://cloud.iexapis.com/stable/stock/acp/quote
{"symbol":"ACP","companyName":"Aberdeen Income Credit Strategies Fund","calculationPrice":"close","open":12.6,"openTime":1557495001001,"close":12.63,"closeTime":1557536700000,"high":12.79,"low":12.6,"latestPrice":12.63,"latestSource":"Close","latestTime":"May 10, 2019","latestUpdate":1557536700000,"latestVolume":54948,"iexRealtimePrice":12.78,"iexRealtimeSize":22,"iexLastUpdated":1557506646236,"delayedPrice":12.67,"delayedPriceTime":1557518319010,"extendedPrice":12.66,"extendedChange":0.03,"extendedChangePercent":0.00238,"extendedPriceTime":1557494990006,"previousClose":12.84,"change":-0.21,"changePercent":-0.01636,"iexMarketPercent":0.006296862488170634,"iexVolume":346,"avgTotalVolume":94906,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":165124620,"peRatio":47.45,"week52High":14.48,"week52Low":10.07,"ytdChange":0.180796}

From: https://api.iextrading.com/1.0/stock/acp/quote
{"symbol":"ACP","companyName":"Aberdeen Income Credit Strategies Fund","primaryExchange":"New York Stock Exchange","sector":"Financial Services","calculationPrice":"close","open":12.6,"openTime":1557495001001,"close":12.67,"closeTime":1557518521015,"high":12.79,"low":12.6,"latestPrice":12.67,"latestSource":"Close","latestTime":"May 10, 2019","latestUpdate":1557518521015,"latestVolume":54921,"iexRealtimePrice":12.78,"iexRealtimeSize":22,"iexLastUpdated":1557506646236,"delayedPrice":12.67,"delayedPriceTime":1557518521015,"extendedPrice":12.66,"extendedChange":-0.01,"extendedChangePercent":-0.00079,"extendedPriceTime":1557494990005,"previousClose":12.63,"change":0.04,"changePercent":0.00317,"iexMarketPercent":0.0063,"iexVolume":346,"avgTotalVolume":95057,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":165648492,"peRatio":null,"week52High":14.48,"week52Low":10.07,"ytdChange":0.25310834163665963}

**Comment by evancarter-iex** [comment]
OK thanks for the update. We have a fix in testing as we speak.


________________________________

**Comment by evancarter-iex** [comment]
This should be fixed now.

**Comment by mikezliu** [comment]
This issue seems to be reoccurring: https://github.com/iexg/IEX-API/issues/1098

**Comment by evancarter-iex** [comment]
I'm seeing correct quotes on roku and spy. Is there something you are seeing this on?

________________________________
