### ISSUE TITLE
[Data] Duplicate Dividend Data

### ISSUE THREAD

**Issue by dmikester1** [iexg/IEX-API#940]
**Clearly describe the data problem**
I found duplicate dividend data with Arrow Financial Corp. (AROW) and with Microchip Technology (MCHP).

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/AROW/dividends/2y?token=
https://cloud.iexapis.com/v1/stock/MCHP/dividends/2y?token=

**What time did the problem occur (including timezone)?**
5/9/19 9:55pm CST

**What is the expected behavior?**
Return separate unique dividend data for each company.

**What are the steps to reproduce**
Get the JSON results using the above API calls.

**Your environment (e.g. browser, OS, API version, language):**
Firefox, Windows 10, V1, PHP/English

**Additional context**
Here is the duplicate sets of data for each company.
AROW dupes:
2 => 
  (object) array(
     'exDate' => '2018-11-29',
     'paymentDate' => '2018-12-14',
     'recordDate' => '2018-11-30',
     'declaredDate' => '2018-10-31',
     'amount' => 0.26,
     'flag' => 'No Change QoQ',
     'currency' => 'USD',
     'description' => 'Arrow Financial Corp. Declares Quarterly Dividend of $0.26 Per Share',
     'frequency' => 'Quarterly',
     'date' => '2019-05-10',
  ),
  3 => 
  (object) array(
     'exDate' => '2018-11-29',
     'paymentDate' => '2018-12-14',
     'recordDate' => '2018-11-30',
     'declaredDate' => '2018-10-31',
     'amount' => 0.26,
     'flag' => 'No Change QoQ',
     'currency' => 'USD',
     'description' => 'Arrow Financial Corp. Declares Quarterly Dividend of $0.26 Per Share',
     'frequency' => 'Quarterly',
     'date' => '2019-05-10',
  ),

MCHP dupes:
7 => 
  (object) array(
     'exDate' => '2017-08-17',
     'paymentDate' => '2017-09-05',
     'recordDate' => '2017-08-21',
     'declaredDate' => '2017-08-03',
     'amount' => 0.362,
     'flag' => 'Increase',
     'currency' => 'USD',
     'description' => 'Microchip Technology Hikes Quarterly Dividend 0.14%',
     'frequency' => 'Quarterly',
     'date' => '2019-05-10',
  ),
  8 => 
  (object) array(
     'exDate' => '2017-08-17',
     'paymentDate' => '2017-09-05',
     'recordDate' => '2017-08-21',
     'declaredDate' => '2017-08-03',
     'amount' => 0.362,
     'flag' => 'Increase',
     'currency' => 'USD',
     'description' => 'Microchip Technology Hikes Quarterly Dividend 0.14%',
     'frequency' => 'Quarterly',
     'date' => '2019-05-10',
  ),

**Comment by evancarter-iex** [comment]
@dmikester1 this is fixed now. Let us know if you see anything else.
