### ISSUE TITLE
account/metadata documentation is out of date

### ISSUE THREAD

**Issue by droidkfx** [iexg/IEX-API#941]
**Clearly describe the problem**
The account/metadata endpoint describes: 
```
{
    "payAsYouGoEnabled":true,
...
}
```
as the message structure. However actual usage of the endpoint results in: 
```
{
    "overagesEnabled": false,
...
```

**What time did the problem occur? (with timezone)**
Friday, May 10, 10:00 AM MST

**What is the expected behavior?**
The API documentation should match the resulting data.

**Your environment (e.g. browser, OS, API version, language):**
API V1

**API URL (if applicable)**
GET /account/metadata

**What are the steps to reproduce the bug?**

1. Hit the endpoint and check the resulting structure with the API documentation

**Additional context**

**Comment by evancarter-iex** [comment]
The endpoint was updated to reflect what is in the documentation.
