### ISSUE TITLE
[Request] Futures

### ISSUE THREAD

**Issue by JMCA2** [iexg/IEX-API#942]
**Is your feature request related to a problem? Please describe.**
Retail traders need access to futures pricing. It can also be useful for non-traders for monitoring the markets.

**Describe the solution you'd like** **Describe alternatives you've considered**
Real-time access to Futures quotes for Scale plans. 15-min delayed or EOD for all other users.

**Additional context**
There aren't accesible APIs offering futures data for individuals or independent developers.

**Comment by timpaine-iex** [comment]
tracked on roadmap
