### ISSUE TITLE
Sectors Crosswalk

### ISSUE THREAD

**Issue by Jacyle** [iexg/IEX-API#943]
The 'Sector Performance' and the 'Company' endpoints provide different sectors

I lieu of a feature request, I was wondering if someone could help me complete a crosswalk (link below) of the 11 sectors from 'Sector Performance' (I realize these are SPDR) and the 20 'Company' sectors. I feel as though this might be helpful to others as well.

https://docs.google.com/spreadsheets/d/1QByzfmihL5LupATVvaNN-S5nGf8MJDGwmutjR-s69xc/edit?usp=sharing

**Comment by Jacyle** [comment]
Thinking more about this, if it's not too big of an ask, would it be possible to add the SPDR sectors back to the Company endpoint? It wouldn't hurt to have Sector, "Sub-Sector" (which is what's being called sector now), and Industry. Just more ways to slice the data.

**Comment by joshuablackburn-iex** [comment]
There isn't a one for one correlation. The sector performance endpoint is populated using the ETFs for each sector. The sector names on each stock is provided by our data partner and is their own proprietary data. Using the SPDR sector requires additional contracts with S&P and is currently cost prohibitive. It seems like this should be generally available data, but for the purposes of an API platform, it is prohibitive.

**Comment by Jacyle** [comment]
Understood, thanks for the explanation
