### ISSUE TITLE
[Issue] - 291 records in Key Stats with no 52week data

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#944]
**Clearly describe the problem**

There are 291 records in key_stats that have no data for week52change, week52high, week52low, marketcap and many other fields

WTRU is one of the many examples

**What time did the problem occur? (with timezone)**
9PM PST

**What is the expected behavior?**
Has data

**Your environment (e.g. browser, OS, API version, language):**
n/a

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/wtru/stats?token=

**What are the steps to reproduce the bug?**
API call and take a look at the null values

**Additional context**
There is data in quote for these 291 records, and most have records for the "percent" fields in key_stats...so there is pricing data for these records

Here are the symbols:
symbol
ABEOW
ACAMU
ACAMW
ACTTU
ADILW
AEP-B
AFC
AGFSW
AIG+
ALACR
ALACU
ALACW
ALGRR
ALGRU
ALGRW
AMBCW
AMCIU
AMCIW
AMRHW
AMRWW
ANDAR
ANDAU
ANDAW
APDNW
APOPW
ARYAU
ARYAW
ATISW
BCACR
BCACU
BCACW
BIOX+
BLNKW
BNGOW
BNTCW
BRACR
BRACU
BRACW
BROGR
BROGU
BROGW
BRPAR
BRPAU
BRPAW
BRPM=
BVXVW
BWMCU
BWMCW
CCC+
CCC=
CCH+
CCH=
CCZ
CELGZ
CETXW
CFFAU
CFFAW
CFXA
CHAC+
CHAC=
CHEKW
CHEKZ
CIC+
CIC=
CLRBW
CLRBZ
CMSSR
CMSSU
CMSSW
CNACR
CNACU
CNACW
CREXW
CRSAU
CRSAW
CTACU
CTACW
CTXRW
CYRXW
CYTXZ
DCUD
DDMXU
DDMXW
DEACU
DFBHU
DFBHW
DLPNW
DPHCU
DPHCW
DRIOW
DSKEW
DTV
DYNC
EDTXU
EDTXW
ENTXW
ESTRW
EVSIW
EYEGW
EYESW
FG+
FLMNW
FMCIU
FMCIW
FPAC=
FPAYW
FTACU
FTACW
GCVRZ
GIG+
GIG=
GIG^
GLACR
GLACU
GLACW
GLOP-A
GM+B
GMHIU
GMHIW
GPAQU
GPAQW
GRAF=
GRP=
GRSHU
GRSHW
GSAH+
GSAH=
GTYHW
GYB
HCACU
HCACW
HCCHR
HCCHU
HCCHW
HHHHR
HHHHU
HHHHW
HIG+
HJLIW
HK+
HSACU
HUNTU
HUNTW
IEAWW
IFFT
IMACW
IMRNW
INSUU
IPOA+
IPOA=
JASNW
JBK
JFIN
JFKKU
JSYNR
JSYNW
KBLMR
KBLMU
KBLMW
KTOVW
KXINW
LACQU
LACQW
LCAHU
LEND
LFACU
LFACW
LGC=
LHC+
LHC=
LINDW
LMFAW
LOACR
LOACU
LOACW
MDGSW
MFAC=
MGY+
MMDMR
MMDMU
MMDMW
MNCLU
MNCLW
MOSC=
MTECU
MTECW
MTFBW
MUDSU
MUDSW
MYNDW
NDRAW
NEBUU
NEBUW
NEE-R
NESRW
NFC=
NHLDW
NRCG+
NSPR+
NSPR+B
NUROW
NXTDW
OMAD+
ONTXW
OPESU
OPESW
OPGNW
OTLKW
OXBRW
PACQU
PACQW
PAVMW
PAVMZ
PHIOW
PHUNW
PIY
PVT+
PVT=
RMG=
ROSEU
ROSEW
RPLA=
RWGE=
SAMAU
SAMAW
SCACU
SCACW
SGLBW
SHIPW
SHLL=
SJIU
SLNOW
SNGXW
SNOAW
SOLOW
SONM
SPAQ+
SRTSW
STNLU
STNLW
SUSL
SWP
TACOW
TALO+
TBLTU
TBLTW
TBRGU
TBRGW
TDACU
TDACW
TDW+
TDW+A
TDW+B
THCBU
THCBW
THWWW
TIBRU
TIBRW
TKKSR
TKKSU
TKKSW
TMCXU
TMCXW
TOTAR
TOTAU
TOTAW
TPGH+
TPGH=
TRNE=
TWLVR
TWLVU
TWLVW
TWNKW
TZACU
TZACW
UBER
USWSW
UUUU+
VEACU
VEACW
VERBW
VKTXW
VST+A
VTIQU
VTIQW
WHLRW
WRLSR
WRLSU
WRLSW
WTRU
ZIONW

**Comment by joshuablackburn-iex** [comment]
We will have to look at each of these, but we will probably focus on the bigger names first. Most of these I spot check against other sources, and they are also missing market cap and 52 week data. A lot of these rarely even trade.
