### ISSUE TITLE
IEX Cloud: SPY reporting incorrect last updated price

### ISSUE THREAD

**Issue by mikezliu** [iexg/IEX-API#945]
**Clearly describe the data problem**

SPY is returning a latest price of 286.66 and a close price of 286.66. The actual price should be 288.1. It is now Saturday 1am EDT.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=spy&types=quote&token=...

**What time did the problem occur (including timezone)?**

Saturday 1am EDT. May 11, 2019.

**What is the expected behavior?**

The latest price should be 288.1

**What are the steps to reproduce**

Call https://cloud.iexapis.com/stable/stock/market/batch?symbols=spy&types=quote&token=...

**Your environment (e.g. browser, OS, API version, language):**

IEX Cloud stable

**Additional context**

**Comment by evancarter-iex** [comment]
Thanks we have a fix rolling out on Monday that should address this problem.


________________________________

**Comment by mikezliu** [comment]
This issue seems to be reoccurring: https://github.com/iexg/IEX-API/issues/1098
