### ISSUE TITLE
IEX Cloud: GOOG reporting incorrect last updated price

### ISSUE THREAD

**Issue by mikezliu** [iexg/IEX-API#948]
**Clearly describe the data problem**

GOOG is returning a latest price of 1164.27. The actual price is 1,132.03 according to Bloomsberg and other financial portals.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=goog&types=quote&token=...

**What time did the problem occur (including timezone)?**

Tuesday 2am EDT.

**What is the expected behavior?**

The latest price should be 1,132.03

**What are the steps to reproduce**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=goog&types=quote&token=...

**Your environment (e.g. browser, OS, API version, language):**

IEX Cloud stable

**Additional context**

**Comment by rgmvisser** [comment]
I see the same issue for FB stock:
```
Quote {
  symbol: 'FB',
  companyName: 'Facebook, Inc.',
  calculationPrice: 'previousclose',
  open: 183.5,
  openTime: 1557754200874,
  close: 181.54,
  closeTime: 1557777600346,
  high: 185.43,
  low: 180.84,
  latestPrice: 188.34,
  latestSource: 'Previous close',
  latestTime: 'May 10, 2019',
  latestUpdate: 1557460800000,
  latestVolume: 16761054,
  iexRealtimePrice: 181.48,
  iexRealtimeSize: 100,
  iexLastUpdated: 1557777599835,
  delayedPrice: 181.62,
  delayedPriceTime: 1557777539929,
  extendedPrice: 183.43,
  extendedChange: -4.91,
  extendedChangePercent: -0.02607,
  extendedPriceTime: 1557754200700,
  previousClose: 188.34,
  change: 0,
  changePercent: 0,
  iexMarketPercent: 0.025705841649337806,
  iexVolume: 430857,
  avgTotalVolume: 16924016,
  iexBidPrice: 0,
  iexBidSize: 0,
  iexAskPrice: 0,
  iexAskSize: 0,
  marketCap: 537624063600,
  week52High: 218.62,
  week52Low: 123.02,
  ytdChange: 0.388119,
  peRatio: 27.75 }
```
The current stock price is 181.54. The latest price here corresponds with 05/10/2019 @ 4:00am (UTC)

**Comment by evancarter-iex** [comment]
@rgmvisser @mikezliu  We’ve deployed a fix that should address this in the next overnight process. Thank you for your patience as we work through this temporary integration issue.
