### ISSUE TITLE
[Request] Swiss stock historical data

### ISSUE THREAD

**Issue by atisharma** [iexg/IEX-API#949]
### Date/time of the issue
2019-05-14

### What you did
Request symbols for 'CH' region and look for Swiss exchanges in data/exchanges endpoint.

### What you expected to happen
Symbols to be returned or Swiss exchanges (Virtex) to be included.

### What actually happened
Null return.

**Comment by evancarter-iex** [comment]
@atisharma Please add this to the Roadmap in the Console so other people can vote on it. Thanks

**Comment by evancarter-iex** [comment]
Closing this will be moved to the Roadmap in the console.

**Comment by wichtounet** [comment]
@evancarter-iex I tried to add this to the console a few weeks ago but it never appeared anyplace. Do you filter some Roadmap Ideas?

**Comment by evancarter-iex** [comment]
@wichtounet we add them periodically. The next batch should go up soon for people to vote on.

**Comment by wichtounet** [comment]
@evancarter-iex 👍

**Comment by ymyke** [comment]
I just checked but can't find anything around Swiss Stock Exchange. I would like to upvote too.
