### ISSUE TITLE
IEX Cloud: Warrant has latest price as null, but has a delayed price

### ISSUE THREAD

**Issue by mikezliu** [iexg/IEX-API#951]
**Clearly describe the data problem**

NRCG+ has latestPrice of null, but has delayed price, open, close prices. It was working a few days ago.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=NRCG%2B&types=quote&token=

**What time did the problem occur (including timezone)?**

1am PDT May 15

**What is the expected behavior?**

Return latestPrice

**What are the steps to reproduce**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=NRCG%2B&types=quote&token=

**Your environment (e.g. browser, OS, API version, language):**

IEX Cloud stable

**Additional context**

{
    "NRCG+": {
        "quote": {
            "symbol": "NRCG+",
            "companyName": "NRC Group Holdings Corp.",
            "calculationPrice": "previousclose",
            "open": 0.9,
            "openTime": 1557840897482,
            "close": 0.89,
            "closeTime": 1557864000063,
            "high": 0.9,
            "low": 0.8856,
            "latestPrice": null,
            "latestSource": "N/A",
            "latestTime": "N/A",
            "latestUpdate": null,
            "latestVolume": 21500,
            "iexRealtimePrice": 0,
            "iexRealtimeSize": 0,
            "iexLastUpdated": 0,
            "delayedPrice": 0.89,
            "delayedPriceTime": 1557864600001,
            "extendedPrice": 0.89,
            "extendedChange": null,
            "extendedChangePercent": null,
            "extendedPriceTime": 1557873000021,
            "previousClose": null,
            "change": null,
            "changePercent": null,
            "iexMarketPercent": null,
            "iexVolume": 0,
            "avgTotalVolume": null,
            "iexBidPrice": 0,
            "iexBidSize": 0,
            "iexAskPrice": 0,
            "iexAskSize": 0,
            "marketCap": null,
            "peRatio": null,
            "week52High": 0.9,
            "week52Low": 0,
            "ytdChange": 0
        }
    }
}

**Comment by evancarter-iex** [comment]
@mikezliu Hmm okay thanks we will take a look at this, its probably a mismatch between multiple data providers.

**Comment by evancarter-iex** [comment]
@mikezliu This appears to be resolved. Can you reopen if its reoccurs?
