### ISSUE TITLE
[Issue] stock price returning closing price from 2 trading sessions ago

### ISSUE THREAD

**Issue by mstorus** [iexg/IEX-API#952]
**Clearly describe the problem**
Fetching `/stock/{symbol}/price` returns the wrong price.

Expected result: I expected this endpoint to return the price from the close of the most recent trading session.

Actual result: It returns the closing price from 2 trading sessions ago.

**What time did the problem occur? (with timezone)**
2019-05-14 23:17 America/Los_Angeles (2019-05-15 06:17 UTC)

**What is the expected behavior?**
I expected the endpoint to return a price of `188.66`, corresponding to the closing price of the most recent trading session.

**Your environment (e.g. browser, OS, API version, language):**
Chrome, MacOS, IEX production `stable` (`https://cloud.iexapis.com/stable/stock`)

**API URL (if applicable)**
`https://cloud.iexapis.com/stable/stock/AAPL/price?token=pk_...`

**What are the steps to reproduce the bug?**
request `https://cloud.iexapis.com/stable/stock/AAPL/price?token=pk_...` after the close of trading. (Unsure exactly what the conditions are, maybe only occurs greater than 15 minutes after the close of trading)

**Additional context**
Comparison with Yahoo! Finance results
![Apple Inc  (AAPL) Stock Historical Prices   Data-1](https://user-images.githubusercontent.com/1182738/57753138-25a62080-76a0-11e9-8ce6-7489cb52bffa.jpg)

The problem also appears in the `quote` endpoint (`https://cloud.iexapis.com/stable/stock/AAPL/quote?token=pk_...`). Possibly due to `latestTime` and `latestUpdate` being the wrong day (actual May 13, 2019, expected May 14, 2019).
```
{
   "symbol":"AAPL",
   "companyName":"Apple, Inc.",
   "calculationPrice":"previousclose",
   "open":186.33,
   "openTime":1557840600757,
   "close":188.66,
   "closeTime":1557864000530,
   "high":189.7,
   "low":185.41,
   "latestPrice":185.72,
   "latestSource":"Previous close",
   "latestTime":"May 13, 2019",
   "latestUpdate":1557720000000,
   "latestVolume":35613330,
   "iexRealtimePrice":188.61,
   "iexRealtimeSize":100,
   "iexLastUpdated":1557863999883,
   "delayedPrice":188.66,
   "delayedPriceTime":1557864000530,
   "extendedPrice":188.98,
   "extendedChange":3.26,
   "extendedChangePercent":0.01755,
   "extendedPriceTime":1557877469675,
   "previousClose":185.72,
   "change":0,
   "changePercent":0,
   "iexMarketPercent":0.022050984841911724,
   "iexVolume":785309,
   "avgTotalVolume":28497603,
   "iexBidPrice":0,
   "iexBidSize":0,
   "iexAskPrice":0,
   "iexAskSize":0,
   "marketCap":854512577600,
   "peRatio":15.49,
   "week52High":233.47,
   "week52Low":142,
   "ytdChange":0.176039
}
```

**Comment by mikezliu** [comment]
Seems to affect almost every US ticker I checked.

FB is reporting 181.54, actual price is 180.73, etc...

I've reported this issue many times already

**Comment by evancarter-iex** [comment]
@mstorus @mikezliu We’ve deployed a fix that should address this in the next overnight process. Thank you for your patience as we work through this temporary integration issue.

**Comment by mikezliu** [comment]
Seems to be reoccurring: https://github.com/iexg/IEX-API/issues/1098
