### ISSUE TITLE
Cryptocurrencies quotes do not change since some minutes

### ISSUE THREAD

**Issue by reuniware** [iexg/IEX-API#953]
Hello. 
What is happening ? Thanks

**Comment by evancarter-iex** [comment]
@reuniware What url are you hitting?

**Comment by evancarter-iex** [comment]
The crypto prices appear to be working on end. Please reopen when/if you have more detail.

**Comment by reuniware** [comment]
Hello
It is now ok. Thanks
Le 15 mai 2019 4:04 PM, "evancarter-iex" <notifications@github.com> a
écrit :
