### ISSUE TITLE
Transition old APi to New

### ISSUE THREAD

**Issue by jimhoranjr** [iexg/IEX-API#955]
Hi
I've been using the current API to get occasional updates on a list of Stocks also specifying a list of attributes using filter.
My old url is below
strURL = "https://api.iextrading.com/1.0/stock/market/batch?symbols=" & SymbLst & _
"&types=quote&filter=" & AttribLst
This works fine. However my attempt to switch to the cloud hasn't been successful could you provied some guidance. The New URL is below
IEXCloudURL = strURL = "https://cloud.iexapis.com/v1/stock/market/batch?symbols=" & SymbLst & _
"&types=quote&filter=" & AttribLst & "token= " & PublicToken
with PublicToken being the public token I received when I registered.

Below is the call. This is from a VBA module in excel . After I get the data I use ParseJSON to get what I'm looking for.
With xmlhttp
.Open "get", URLtoUse, False
.SetRequestHeader "If-Modified-Since", "Sat, 1 Jan 2000 00:00:00 GMT"
.send
x = .ResponseText
End With

Thanks
Jim
@jimhoranjr

**Comment by joshuablackburn-iex** [comment]
that should work. Have you activated your account?

**Comment by bjwest** [comment]
Are you blocking VPM access now?  I can't get to anything ipx related unless I turn off my vpn.  Was working fine yesterday.

**Comment by evancarter-iex** [comment]
@bjwest what ip are you trying to connect from?

**Comment by bjwest** [comment]
I'm using Private Internet Access, so it's one of their lot.  I get a new address every time I restart or wake my computer, so I can't say what yesterdays was.  My IP today is 199.116.115.131 (or was until I turned it off to test again) and it's still the same.  With VPN on, connection times out, with it off, site loads up quite fast.

**Comment by evancarter-iex** [comment]
@bjwest that particular ip is on a series of ban lists for forum spamming. So its blocked from accessing us.

**Comment by bjwest** [comment]
Thanks for the quick response.  I'm starting to run into that more and more with PIA's addresses, especially with the Chicago zone.  I'll see if I can modify my script to shut down the VPN when I grab the days closings then bring it back up.  It may be time for me to search for a new VPN provider that's not so popular with the spammers.

**Comment by evancarter-iex** [comment]
@bjwest ok im going to close this. Let me know if I can be anymore help

**Comment by evancarter-iex** [comment]
@jimhoranjr apologies. What error are you getting?
