### ISSUE TITLE
IEX Cloud: Some symbols return invalid SSE price

### ISSUE THREAD

**Issue by mikezliu** [iexg/IEX-API#957]
**Clearly describe the data problem**

Certain symbols return prices that are incorrect and different from batch quote prices when using SSE streaming.

For example, BCACR returns a latestPrice of 0.25 (when streaming) but the actual price is 0.4269.  Batch quotes returns the correct latestPrice of 0.4269.

curl --header 'Accept: text/event-stream' https://cloud-sse.iexapis.com/stable/stocksUS\?symbols\=BCACR\&token\=pk_...

There's some other issues in the JSON result, like delayedPrice is 0, but delayedTime is > latestUpdate.

I see this issue for these US tickers:
BCACR
BCACU
APLT
BCACW
IVOL
CCC=

[
  {
    "symbol": "BCACR",
    "companyName": "Bison Capital Acquisition Corp.",
    "calculationPrice": "previousclose",
    "open": 0.45,
    "openTime": 1557853454677,
    "close": 0.4269,
    "closeTime": 1557864000464,
    "high": null,
    "low": null,
    "latestPrice": 0.25,
    "latestSource": "Previous close",
    "latestTime": "January 30, 2019",
    "latestUpdate": 1548824400000,
    "latestVolume": 212978,
    "iexRealtimePrice": 0,
    "iexRealtimeSize": 0,
    "iexLastUpdated": 0,
    "delayedPrice": 0,
    "delayedPriceTime": 1557950840192,
    "extendedPrice": 0.4319,
    "extendedChange": 0.1819,
    "extendedChangePercent": 0.7276,
    "extendedPriceTime": 1557864440192,
    "previousClose": 0.25,
    "change": 0,
    "changePercent": 0,
    "iexMarketPercent": null,
    "iexVolume": 0,
    "avgTotalVolume": 3813,
    "iexBidPrice": 0,
    "iexBidSize": 0,
    "iexAskPrice": 0,
    "iexAskSize": 0,
    "marketCap": 1994750,
    "peRatio": null,
    "week52High": 0,
    "week52Low": 0,
    "ytdChange": -0.10714285714285723
  }
]

Compare with batch quotes:
https://cloud.iexapis.com/stable/stock/market/batch?symbols=BCACR&types=quote&token=pk_

{
    "BCACR": {
        "quote": {
            "symbol": "BCACR",
            "companyName": "Bison Capital Acquisition Corp.",
            "calculationPrice": "close",
            "open": 0.45,
            "openTime": 1557853454677,
            "close": 0.4269,
            "closeTime": 1557864000464,
            "high": null,
            "low": null,
            "latestPrice": 0.4269,
            "latestSource": "Close",
            "latestTime": "May 14, 2019",
            "latestUpdate": 1557864000464,
            "latestVolume": 0,
            "iexRealtimePrice": null,
            "iexRealtimeSize": null,
            "iexLastUpdated": null,
            "delayedPrice": null,
            "delayedPriceTime": null,
            "extendedPrice": 0.4319,
            "extendedChange": 0.005,
            "extendedChangePercent": 0.01171,
            "extendedPriceTime": 1557864440192,
            "previousClose": 0.25,
            "change": 0.1769,
            "changePercent": 0.7076,
            "iexMarketPercent": null,
            "iexVolume": null,
            "avgTotalVolume": 3813,
            "iexBidPrice": null,
            "iexBidSize": null,
            "iexAskPrice": null,
            "iexAskSize": null,
            "marketCap": 3406235,
            "peRatio": null,
            "week52High": 0,
            "week52Low": 0,
            "ytdChange": 0.6004571428571428
        }
    }
}

**Data URL (The URL you used to access the data without your token):**

curl --header 'Accept: text/event-stream' https://cloud-sse.iexapis.com/stable/stocksUS\?symbols\=BCACR\&token\=pk_...

https://cloud.iexapis.com/stable/stock/market/batch?symbols=BCACR&types=quote&token=pk_

**What time did the problem occur (including timezone)?**

6am PDT May 16, 2019

**What is the expected behavior?**

Correct prices

**What are the steps to reproduce**

Call the Data URLs

**Your environment (e.g. browser, OS, API version, language):**

IEX Cloud stable

**Additional context**

**Comment by evancarter-iex** [comment]
@mikezliu these have been cleaned up. APLT and IVOL are working now. The rest should be cleaned up after close today.
Leaving this open till we confirm that after close today.

**Comment by evancarter-iex** [comment]
@mikezliu this should be cleaned up can you confirm that it is?

**Comment by evancarter-iex** [comment]
@mikezliu Im going to close this. If you see anything additional, please open a new issue.
