### ISSUE TITLE
Intraday - Market*

### ISSUE THREAD

**Issue by lars670** [iexg/IEX-API#958]
In an intraday request we got this answer from INTC:

data: [{"date":"2019-05-16","minute":"10:58","label":"10:58 AM",
"high":45.85,
"low":45.83,
"average":45.838,
"volume":315,
"notional":14438.95,
"numberOfTrades":4,
"marketHigh":null,
"marketLow":null,
"marketAverage":null,
"marketVolume":0,
"marketNotional":0,
"marketNumberOfTrades":0,
"open":45.85,
"close":45.83,
"marketOpen":null,
"marketClose":null,
"changeOverTime":0.006875343218012134,
"marketChangeOverTime":0.005793793618048452}]

All marketwide data is "Null"
we were of the opinion that this would be delayed data from the other exchanges.

**Comment by evancarter-iex** [comment]
@lars670 Market data is 15 minute delayed. After 15 minutes have passed that data will fill in.

**Comment by lars670** [comment]
Yes I know.
It is still the same, and the market is opened 2.5 hours ago
