### ISSUE TITLE
Reopen #958 Intraday data IEX, marketwide 

### ISSUE THREAD

**Issue by lars670** [iexg/IEX-API#959]
**Clearly describe the data problem**
see #958
Marketwide data for INTC is "null" - 2 hours after market open

**Data URL (The URL you used to access the data without your token):**
PM","high":45.83,"low":45.815,"average":45.825,"volume":300,"notional":13747.5,"numberOfTrades":3,"marketHigh":null,"marketLow":null,"marketAverage":null,"marketVolume":0,"marketNotional":0,"marketNumberOfTrades":0,"open":45.815,"close":45.83,"marketOpen":null,"marketClose":null,"changeOverTime":0.006589785831960555,"marketChangeOverTime":0.005793793618048452}]

**What time did the problem occur (including timezone)?**
18:05 CET

**What is the expected behavior?**
Get delayed market wide intraday data

**What are the steps to reproduce**
Query Intraday for INTC

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment]
@lars670 what url are you hitting? Im hitting https://cloud.iexapis.com/beta/stock/intc/chart/1d?token= and I see that data filled in as expected.

**Comment by lars670** [comment]
I am hitting:
https://cloud.iexapis.com/stable/stock/INTC/intraday-prices? bl.a bl.a. 

Got this right now:
{"date":"2019-05-16","minute":"13:29","label":"1:29 PM","high":45.595,"low":45.59,"average":45.593,"volume":300,"notional":13678,"numberOfTrades":3,"marketHigh":null,"marketLow":null,"marketAverage":null,"marketVolume":0,"marketNotional":0,"marketNumberOfTrades":0,"open":45.595,"close":45.59,"marketOpen":null,"marketClose":null,"changeOverTime":0.0014936847885778132,"marketChangeOverTime":0.0005267085107317058}]

Same for AAPL

**Comment by lars670** [comment]
![test](https://user-images.githubusercontent.com/33923464/57875062-47271980-7812-11e9-896d-636a6b39a9f0.png)

**Comment by evancarter-iex** [comment]
@lars670 I see that data now, (now that its passed 15 minutes delayed) https://cloud.iexapis.com/stable/stock/INTC/intraday-prices?token=

**Comment by lars670** [comment]
Yes, but but....
Market has opened 3 hours ago - What is the principle here?

**Comment by evancarter-iex** [comment]
@lars670 Not sure I understand the question. Data from IEX is realtime, market data, aka data such as marketHigh etc is 15 minute delayed throughout the trading day. It will fill in after 15 minutes has passed.

**Comment by lars670** [comment]
I am thinking time is now 19:53 - So Marketwide data should be values from 19:38, certainly not "Null" data
since delay is 15 minutes

**Comment by evancarter-iex** [comment]
@lars670 Ah I see, no we fill in the 15 minute data to match the minute it actually occurred, not "now"

**Comment by lars670** [comment]
Ahhh, that is not delayed data - this is both delayed and conflated data.
This means 4 quotes per hour, as I understand you. This is a huge disappointment, and this data basically cannot be used to draw an intraday chart.

**Comment by evancarter-iex** [comment]
@lars670 not sure I follow how you get to that?

**Comment by lars670** [comment]
As I understand you mark a value every 15 minutes and publish this for market wide data, the remaining 14 minutes you publish "Nulls"
Is this a correct assumption?

**Comment by evancarter-iex** [comment]
@lars670 That is incorrect.

The market data is 15 minute delayed. All it means is that when we receive it we shove it into the correct minute bucket matching 15 minutes ago.  So if its 14:15 currently, we will receive 14:00 and put in that bucket. When its 14:16 we receive 14:01 and put in that bucket etc.

**Comment by lars670** [comment]
I understand, this is the way it should work.. .15 minutes delayed data, but otherwise the same data. But why is Marketopen, MarketVolume, MarketHigh and Low = null ?
Will check more tomorrow - kinda late here in Denmark.

**Comment by evancarter-iex** [comment]
@lars670 Market data is 15 minute delayed as well.

**Comment by lars670** [comment]
I think I got you.
