### ISSUE TITLE
http request that only returns previous closing price

### ISSUE THREAD

**Issue by JamesTran23** [iexg/IEX-API#96]
Is there a way to request the previous day's closing price without the labels?  Something like what is returned by stock/aapl/price?  The closest I can find is stock/aapl/previous?filter=close but that returns the string

{"close":171.1}

and then I have to use regular expressions to filter out to get just 171.1

**Comment by joshuablackburn-iex** [comment]
You are able to call /stock/aapl/previousClose  or /stock/aapl/close.  Any key that is returned from the full quote can be passed in the URL.  We will update the documentation to explain this new functionality.

**Comment by JamesTran23** [comment]
Great!  I tried it but I'm getting "Forbidden" when I make these two calls.

https://api.iextrading.com/1.0/stock/aapl/previousClose
https://api.iextrading.com/1.0/stock/aapl/close

**Comment by joshuablackburn-iex** [comment]
Sorry.  I mistyped previously.  It should be /stock/aapl/quote/previousClose
