### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by ernst20020530** [iexg/IEX-API#963]
**Clearly describe the problem**
I am using python to call API. yesterday everything works. but today API always return 403. But if I copy paste the URL into firefox browser, the expected result returns.

**What time did the problem occur? (with timezone)**
10:00 PM 5/17/2019 (EST)

**What is the expected behavior?**
python API call is supposed to return json result instead of 403

**Your environment (e.g. browser, OS, API version, language):**

Firefox. Ubtuntu, Python

**API URL (if applicable)**
https://sandbox.iexapis.com/beta/stock/AAPL/financials/2?token=<My test token>

**What are the steps to reproduce the bug?**

Use the example sandbox API with my test token. 

**Additional context**
Traceback (most recent call last):
  File "./Application.py", line 61, in <module>
    res = api.Get();
  File "./Application.py", line 31, in Get
    res = requests.get(url).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
<Response [403]>

**Comment by ernst20020530** [comment]
I am new to IEX. I just call API less than 10 times, then exhausted 500,000 message. How do you calculate the message?

**Comment by ben-berman-iex** [comment]
@ernst20020530 have you instituted any domain restrictions on the token you are using? We are currently resolving some issues with that so in the interim I would remove those restrictions if you have any on it

**Comment by ernst20020530** [comment]
@ben-berman-iex I am not sure what domain restriction mean. My code has no restriction. Can you give more detail? 
And I just call API less than 10 times, then exhausted 500,000 message. How do you calculate the message?

**Comment by McQgit** [comment]
@ernst20020530  See here about the weighting for the API:
[]https://iexcloud.io/docs/api/#data-weighting

Also, see their Help Center.  Their FAQ has some more info on weighting:
[]https://iexcloud.io/support/
