### ISSUE TITLE
[Issue] Domain Restriction not restricting

### ISSUE THREAD

**Issue by dylanitorium** [iexg/IEX-API#965]
**Clearly describe the problem**

A domain-restricted publishable token can be used to make successful requests from non-whitelisted domains and from using the browser.

**What time did the problem occur? (with timezone)**
8:23AM NZST

**What is the expected behavior?**

A 401 error should occur when a request is made using domain-restricted publishable token, when there is no referring domain present or when the domain is not included in the whitelist

**Your environment (e.g. browser, OS, API version, language):**
Chome 74.0.3729.131, Mac 10.14.3, v1, Javascript

**API URL (if applicable)**

https://cloud.iexapis.com/stable/stock/aapl/price?token=<token>

**What are the steps to reproduce the bug?**

1. Create a publishable token
2. Restrict the domain of the token
3. Enter the url into the browser using the token
or 
3. Do a `fetch` from the console of website not included in the domain whitelist.

**Additional context**

Currently on the Grow plan.

We are aware that we can do signed requests to secure our tokens from being compromised but this will impact user experience and we'd expect domain restriction to work in any case.

On friday we had reported this issue via the support email, a fix was rolled out that tipped the scales right to the opposite end; entering any domain into the whitelist would cause 401 errors on any request. This fix has since been rolled back and we are in the initial state of domain restriction not restricting.

**Comment by shoujs** [comment]
It happens to me too. I can paste the api url with restricted pk token to browser and get the result successfully.

**Comment by evancarter-iex** [comment]
@dylanitorium @shoujs This should be fixed now. Let us know if its not.
