### ISSUE TITLE
[Issue] - 2y/5y/max not working for AAPL Historical Prices

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#968]
**Clearly describe the problem**

https://cloud.iexapis.com/stable/stock/AAPL/chart/5y?token=
 throws error "An unknown error has occurred" - 2y and max also do not work

https://cloud.iexapis.com/stable/stock/AAPL/chart/1y?token=
works fine

**What time did the problem occur? (with timezone)**
6:15AM PST May 20 2019

**What is the expected behavior?**
data is returned

**Your environment (e.g. browser, OS, API version, language):**
win10, chrome, english

**API URL (if applicable)**

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by evancarter-iex** [comment]
@jesseorosz we see this and will have fix shortly

**Comment by evancarter-iex** [comment]
@jesseorosz This is fixed. Let us know if you see it again.
