### ISSUE TITLE
[Issue] SSE streaming sometimes yield incorrect JSON response

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#969]
We are using the following code

```
    stream.on('data', (response) => {
        var str = response.toString()

        var array = str.split(/\r?\n/)

        array.forEach(function(value){
            value = value.replace('data:', '')

            if (value.length <= 0) {
                return;
            }

            console.log("DEBUG -> " + value + "<- END");

            var json = JSON.parse(value)

```

Normally, we would get the following respond.

`DEBUG ->  [{"symbol":"MYL","price":19.7300,"size":482,"time":1558368449203,"seq":604}]<- END`

But sometimes, we can get

`DEBUG ->  [{"symbol":"NTGR","price":27.6950,"size":10<- END`

Is that something normal?

**Comment by yccheok** [comment]
Note that, when the incident happen, I'm opening 68 stream connection, and listen to total 3354 different stocks.

**Comment by joshuablackburn-iex** [comment]
May be related to your string split. What is the goal of the split on new line?

**Comment by yccheok** [comment]
I notice that, instead of receiving a complete

` data: [{"symbol":"MYL","price":19.7300,"size":482,"time":1558368449203,"seq":604}]` in 1 round of `stream.on('data'` callback, we may sometimes receive in 2 round of `stream.on('data'` callback.

We may receive

`data: [{"symbol":"MYL","price":19.7300,"`

followed by the following in second round

`size":482,"time":1558368449203,"seq":604}]`

Is this normal behavior in SSE? Right now, we are using the following workaround in our code

```
function install_handlers(stream, codes) {    
    var previous = ''

    stream.on('data', (response) => {
        var str = response.toString()
        
        if (str == null) {
            return
        }

        str = str.trim()

        if (str.length <= 0) {
            return
        }

        if (!str.endsWith('}]')) {
            previous = previous + str
            return
        } else if (!str.startsWith('data:')) {
            str = previous + str
            previous = ''
            // continue
        } else {
            previous = ''
        }

        var array = str.split(/\r?\n/)
        
        array.forEach(function(value){
            value = value.replace('data:', '')
            
            if (value.length <= 0) {
                return;
            }
            
            var json = null
            
            try {
                json = JSON.parse(value)
            } catch(e) {
                console.log("\"" + value + "\" causes exception " + e)
                return
            }
            
            json = json[0]
            
            ////////////////////////////////////////////////////////////////////
            const symbol = json.symbol
            const time = json.time
            ////////////////////////////////////////////////////////////////////
        });
    });
}

```

**Comment by evancarter-iex** [comment]
This has been updated in the documentation to help deal with the issue. https://iexcloud.io/docs/api/#sse-streaming under nodejs sample code.
