### ISSUE TITLE
Enhancement request: Please add historic volatility

### ISSUE THREAD

**Issue by ModelsRUs** [iexg/IEX-API#97]
Could use different periods as options (like Chart or Dividends) - e.g., 1m, 3m, 6m, 1y

Thank you SO MUCH for making this data available. I use it in my excel models, and would be boxed in a corner if not for the IEX-API.

**Comment by ModelsRUs** [comment]
Hi
Roadmap says research required. Not sure what this means, but if I can be of assistance, please let me know.

**Comment by lars670** [comment]
This could be calculated rather easy by downloading the history of the stock. Ecxel even has a build-in formula for this.

**Comment by ModelsRUs** [comment]
Yes, thank you Lars670. The suggestion is appreciated.
I was able to pull data using e.g.,
=WEBSERVICE(https://api.iextrading.com/1.0/stock/AAPL/chart/1Y?filter=date,close).
I then used a combination of formulas to parse and extract the necessary data for Excel's STDDEV function, but this is quite messy.
I didn't see any Endpoint for "History" in the Stocks App - is there an EASIER way I've overlooked?

Regards,

**Comment by drobertson123** [comment]
Actually, there are a wide variety of ways to calculate historic volatility. The commonly used Log Normal Standard Deviation model suffers from some well-known problems such as the excessive influence of gaps on the results. Even a moderate gap will cause the formula to overestimate volatility through the sampling window.

Then there is the question of what window would you use? Should it be short, 30 to 90 days or long, a year or more.

Here is a good overview of different models. The one you choose is based on your use case.

http://www.todaysgroep.nl/media/236846/measuring_historic_volatility.pdf

**Comment by ModelsRUs** [comment]
Thank you drobertson. Yes, this can be calculated in Excel (and I have) but it requires first downloading and writing vba to parse historical data from a csv function (using Chart), There are quite a few other financial statistics, already available in IEX out-of-the-box (e.g., 50 / 200 day moving averages, % Change in price, various ratios) that could likewise be calculated - some with considerably less effort than standard deviation - which are provided in the toolkit.

**Comment by ModelsRUs** [comment]
Drobertson123 thank you again for posting that link. It's very helpful, and I've found myself going back to it multiple times. The incorporation of a GOOD historic vol is a major hurdle for many of my apps.

**Comment by timpaine-iex** [comment]
closing as stale
