### ISSUE TITLE
[Request] Additional Frequencies for historical data

### ISSUE THREAD

**Issue by Prajakta-j** [iexg/IEX-API#970]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I want a historical where time range in 10 years and frequency in yearly, quarterly,  monthly, weekly. How I can get prices

**Comment by timpaine-iex** [comment]
dupe https://github.com/iexg/IEX-API/issues/221
