### ISSUE TITLE
[Request] intraday-prices for After/Premarket hours

### ISSUE THREAD

**Issue by Devination** [iexg/IEX-API#973]
**Is your feature request related to a problem? Please describe.**
Using https://iexcloud.io/docs/api/#intraday-prices it seems we only get data from *9:30* to *15:59*.

**Describe the solution you'd like**
Is it possible to get this data for the extended hours? In particular I'm interested in retrieving the *marketNumberOfTrades*.

**Comment by timpaine-iex** [comment]
grouping with https://github.com/iexg/IEX-API/issues/693
