### ISSUE TITLE
[Data] No recent earnings data

### ISSUE THREAD

**Issue by dwhittemore** [iexg/IEX-API#974]
**Clearly describe the data problem**
Previously, earnings for the /financials endpoint was arriving within a week or so of an earnings call; but have not seen any new earnings data come in since early May

**Data URL (The URL you used to access the data without your token):**
Example that doesn't have new earnings yet: https://api.iextrading.com/1.0/stock/PCTY/financials

**What time did the problem occur (including timezone)?**
It's constant

**What is the expected behavior?**
Expected to see data for the 3/31/2019 quarter's release

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by joshuablackburn-iex** [comment]
The old IEX API at api.iextrading.com is scheduled to sunset on June 1st. Please use https://iexcloud.io which has more quantity and quality of data.
