### ISSUE TITLE
Ticker symbol not supported - FXAIX and FGROX

### ISSUE THREAD

**Issue by alorenz55** [iexg/IEX-API#975]
**Clearly describe the data problem**
The ticker symbols for FXAIX and FGROX are not supported. Can you add them? 

**Data URL (The URL you used to access the data without your token):**

**What time did the problem occur (including timezone)?**
N/A

**What is the expected behavior?**
Display data

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
Browser

**Additional context**

**Comment by evancarter-iex** [comment]
@alorenz55 both https://cloud.iexapis.com/stable/stock/FXAIX/quote?token= and https://cloud.iexapis.com/stable/stock/FGROX/quote?token= work. Mutual funds are not traded during the day however, so you will only see end of day prices.
