### ISSUE TITLE
[Request] IEXCloud Daily Symbol Split List and Symbol name change list

### ISSUE THREAD

**Issue by StockConsultant** [iexg/IEX-API#976]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a API call to get a stock symbol list of the day's upcoming splits and ratios. Also along the same lines an API call to get a list any symbol changes for that day. This could be available before the 9:30 am EST market open. 

This would prevent customer complaints of ugly unadjusted daily charts on split days, and for symbol changes keep the old daily data merged with the new symbol.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jkPnF** [comment]
I think this would be a great enhancement. Rather than a API call per symbol trying to detect which symbol may have split, it would be great to get a list of symbols that day that experienced a split ( and split ratio). Quandl offers this feature and is very very convenient.
