### ISSUE TITLE
[Data] 429 server error // Realtime "last" on only 30 stocks  !??

### ISSUE THREAD

**Issue by RobinhoodFR** [iexg/IEX-API#977]
Clearly describe the data problem

IEX websocket API (last datapoint) server response return randomly "(429) Too Many Requests."
It was working fine for a time with only 30 stocks (DOW stocks, among most liquid). Since some days I receive this error. After investigating it seems to be a server limit on IEX side.

**This is an additional issue, in reference to the previous issue (https://github.com/iexg/IEX-API/issues/925). This is really anoying, even if it happened only 2 or 3 times a week....**

Data URL (The URL you used to access the data without your token):

https://cloud-sse.iexapis.com/beta/last?symbols=

What time did the problem occur (including timezone)?

When US equities markets are open

What is the expected behavior?

Streaming last datapoint for only 30 US stocks realtime.

What are the steps to reproduce

Use the URL above with 30 among most liquid stocks (DJI  stocks for instance)

Your environment (e.g. browser, OS, API version, language):

C#/dotNet

Additional context
I planned to stream a larger number of stocks. If it is confirm that IEX cap the number of stocks that could be streamed real time it is gonna be an issue for me.
Thanks by advance!

**Comment by lars670** [comment]
As I recall IEX standard API has a limit of 50 symbols (It in the api doc.) but you can have concurrent sessions. Still that does not explain your 30 symbols problem

**Comment by evancarter-iex** [comment]
@RobinhoodFR Looking into this. I think I see this but trying to track down exactly whats going on here.

**Comment by evancarter-iex** [comment]
@RobinhoodFR What ip are you hitting us from?

**Comment by RobinhoodFR** [comment]
Thanks evan. My ip 86.252.215.46 (not fixed to my mind)

**Comment by evancarter-iex** [comment]
@RobinhoodFR Hmmm not seeing any 429s from that ip in the last couple of days. In fact not really seeing any activity from that ip. Do you use any additional ones?

**Comment by RobinhoodFR** [comment]
Mais I send you my Iextoken for futher investigation on your email support adress?

**Comment by evancarter-iex** [comment]
@RobinhoodFR Yes. And please reference this github issue when you send it. Thanks

**Comment by evancarter-iex** [comment]
Havent seen this repeat on our side. Im closing for now since its unverified.
