### ISSUE TITLE
[Issue]Allowed domains for token gives Error

### ISSUE THREAD

**Issue by SorenRamus** [iexg/IEX-API#978]
**Clearly describe the problem**
A request is rejected with error: "The referer in the request header is not allowed. Please check the associated domain(s) for this API key"
When sending request.

The error is returned when allowed domains are an IP address. 
If allowed domains are blank the response is as expected.

**What time did the problem occur? (with timezone)**
First time may 17. 2019 and every time since then.

**What is the expected behavior?**
A proper response as before mey 17.

**Your environment (e.g. browser, OS, API version, language):**
Windows Server 2016 (C# application) 
Windows 10 (Google Chrome) 

**API URL (if applicable)**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=WMT%2CKO%2CNOC%2CBA&types=ohlc&token=pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**What are the steps to reproduce the bug?**
Fill token  "Allowed Domain" list with Your IP address and send a request using the token.  

**Additional context**

**Comment by evancarter-iex** [comment]
@SorenRamus Hi there, are you setting the referer header in your request? ie: curl --referer https://1.2.3.4 https://cloud.iexapis.com/v1/stock/aapl/quote\?token\=

That appears to work for me

**Comment by evancarter-iex** [comment]
Im closing, this since this works for me. We can reopen if it continues to be a problem
