### ISSUE TITLE
Will the API support foreign markets like Canada

### ISSUE THREAD

**Issue by djoron** [iexg/IEX-API#98]
Good day,

First thanks for developping such an API ! I was wondering, will foreign markets eventually be supported ? I live in Canada so that would be the first I'm interested in (TSX - Toronto Stock Exchange). Request similar to issue #76. Note the same symbol name can appear between markets unless you add a suffix (ex: CAE on US market vs CAE.to on Toronto Stock exchange).

Thank you !

Dominic

**Comment by djoron** [comment]
Similar to issue #76 .

**Comment by evancarter-iex** [comment]
Duplicate of #76. Closing this.
