### ISSUE TITLE
[Request] Upcoming-events endpoint needs time horizon

### ISSUE THREAD

**Issue by hmTodd** [iexg/IEX-API#980]
**Is your feature request related to a problem? Please describe.**
I just saw the upcoming-events endpoint in the docs today.  Great addition and much needed.  However, it would be nice to limit the days forward it looks, so we can request it every day and not pay for the same data day after day.  

Also, it is currently showing old data with nothing "upcoming".  - Looking at splits only, 

**Describe the solution you'd like**
I envision calling this every morning with a focus on that day's dividends and splits.  If there are dividends or splits scheduled out a week or month I don't care about them, but I'll be charged for the same data every day.

The current splits and dividends endpoints have something like /1m or /3m options which could work, but a better alternative would be an optional tag like horizon=x, where x is some number of days forward.
  

**Describe alternatives you've considered**

**Additional context**

**Comment by timpaine-iex** [comment]
this supports `exactDate` now
