### ISSUE TITLE
[Data] Duplicate symbols data

### ISSUE THREAD

**Issue by gcobcqwe** [iexg/IEX-API#981]
**Clearly describe the data problem**
I found duplicate symbol with Cosmo Ventures Inc. (CMVO) 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/ref-data/region/US/symbols?token=

**What time did the problem occur (including timezone)?**
2019-05-25 01:03 UTC+8 

**What is the expected behavior?**
return without duplicate symbol data

**What are the steps to reproduce**
Get the JSON results using the above API calls.

**Your environment (e.g. browser, OS, API version, language):**
Chrome, mac , stable, English

**Additional context**
Here is the duplicate symbol sets of data:
index 9539: 
{
        "symbol": "CMOV",
        "exchange": "OTC",
        "name": "Cosmos Ventures Inc",
        "date": "2019-05-24",
        "type": "cs",
        "iexId": "IEX_4730514D31382D52",
        "region": "US",
        "currency": "USD",
        "isEnabled": true
    },
index 10807:
 {
        "symbol": "CMOV",
        "exchange": "OTC",
        "name": "Cosmo Ventures Inc.",
        "date": "2019-05-24",
        "type": "cs",
        "iexId": "IEX_523036314E362D52",
        "region": "US",
        "currency": "USD",
        "isEnabled": true
    }

**Comment by evancarter-iex** [comment]
Resolved.
