### ISSUE TITLE
[Data] GE dividend data is not correct

### ISSUE THREAD

**Issue by norlan-perdomo** [iexg/IEX-API#982]
**Clearly describe the data problem**
Key Stats endpoint dividend fields are incorrect.

```
{
    "ttmDividendRate": 0.26,
    "dividendYield": 0.027513227513227517
}
```

Correct dividends from dividend.com: https://www.dividend.com/dividend-stocks/conglomerates/conglomerates-general/ge-general-electric/

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/ge/stats

**What time did the problem occur (including timezone)?**
2019-05-25 12:36 PM EST
 
**What is the expected behavior?**
The value of `ttmDividendRate` and `dividendYield` for GE should be close to the perspective values on other websites such as dividend.com.

**What are the steps to reproduce**
GET request to https://cloud.iexapis.com/stable/stock/ge/stats

**Your environment (e.g. browser, OS, API version, language):**
Browser

**Additional context**

**Comment by evancarter-iex** [comment]
@norlan-perdomo Hi there, sorry for the delay. We calculate ttmDividendRate and dividendYield based on the trailing 12 months. This number matches what other sites such as Yahoo have.

**Comment by norlan-perdomo** [comment]
@evancarter-iex thanks for looking into it.
