### ISSUE TITLE
[Issue] upcoming-earnings.reportDate is different from other sources

### ISSUE THREAD

**Issue by bitministry** [iexg/IEX-API#983]
the upcoming-earnings.reportDate is almost never accurate. 
NASDAQ homepage has almost always a different date, the correct one. 

this problem occurs always 

expected behavior is correct data 

https://iexcloud.io/docs/api/#financials 

to reproduce just compare NASDAQ earnings calendar

**Comment by kalevigit** [comment]
the dates returned by upcoming-earnings endpoint are wrong 

1. the financials endpoint almost never give new data on the upcoming-earnings.reportDate 
2. the upcoming-earnings.reportDate is almost never accurate. NASDAQ homepage has almost always a different date, the correct one.

**Comment by evancarter-iex** [comment]
@kalevigit This is something we are working on but a lot of upcoming earnings data is contradictory in many different places including NASDAQ.
