### ISSUE TITLE
Ability to see options data in testing for free users

### ISSUE THREAD

**Issue by kwsorensen** [iexg/IEX-API#984]
**Clearly describe the problem**

Tried doing a get request on https://cloud.iexapis.com/v1/ref-data/options/symbols with my token embedded. Had **test data enabled**. It returned 

> The requested data is not available to free tier accounts. Please upgrade for access to this data.

I am looking for a system that has options and options history - would be willing to pay but I want to know whether or not you have the data I am looking for first. Please add test results for options (free tier) that return mock data. So far your system looks like what I am looking for - except I cannot see what type of data you have on options (stock ticket, strikeprice, date/time, option cost, etc.).

**Comment by joshuablackburn-iex** [comment]
You need to use sandbox.iexapis.com for testing rather than the production url of cloud.iexapis.com
