### ISSUE TITLE
[Data] financials endpoint charges 5000 per call for old data

### ISSUE THREAD

**Issue by kalevigit** [iexg/IEX-API#985]
Financials endpoint data weights is 5000 per symbol per period
But there is no option to test for new data. 

**How am I supposed to get fresh financials?** 
https://iexcloud.io/docs/api/#financials

this is a business process error 

implement querystring parameter:
**financials?onlyAfter=YYYY-MM-DD**

**Comment by joshuablackburn-iex** [comment]
While not the same as the solution you proposed, we do already have a way to look up the latest financials report date for a symbol. You can use the Data Points endpoint to get the latest financials report date for free.

**Comment by xunamcapital** [comment]
Hi,
is it possible to use this feature (https://iexcloud.io/docs/api/#data-points )  with batch requests? How do I check this for multiple symbols a day - do I have to iterate through all my symbols individually or is there another way?

I have tried to use "market" as as symbol and **symbols=** parameter to get a batch response and this does not work for this API call even though it works for most other API calls.

Thank you!
