### ISSUE TITLE
Timeout when connecting to iexcloud.io site

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#987]
Hi

In the last few days, your site isn't working at all, let alone the apis. I keep getting the following in my browser, clearing the cookies didn't help.

The connection has timed out

The server at iexcloud.io is taking too long to respond.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by evancarter-iex** [comment]
Hi,

What ip are you contacting us from?

________________________________

**Comment by Amosss** [comment]
It was fixed 2 days ago and now it's working
