### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by kmsteiner** [iexg/IEX-API#989]
**Clearly describe the data problem**
I cannot get primaryExchange data

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/market/batch?types=quote&symbols=aapl,fb&filter=primaryExchange,latestVolume,changePercent,latestPrice,previousClose&token=MY_TOKEN

**What time did the problem occur (including timezone)?**
13:06 EDT

**What is the expected behavior?**
{"AAPL":{"quote":{"primaryExchange":"Nasdaq Global Select","latestVolume":23648925,"changePercent":-0.00384,"latestPrice":178.97,"previousClose":179.66}},"FB":{"quote":{"primaryExchange":"Nasdaq Global Select","latestVolume":8785850,"changePercent":0.00105,"latestPrice":181.06,"previousClose":180.87}}}

**What are the steps to reproduce**
execute the above URL

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Windows 10,API cloud

**Additional context**

**Comment by McQgit** [comment]
@kmsteiner  The primaryExchange is not part of the Quote results - you need to use the Company endpoint's `exchange` instead.
[]https://iexcloud.io/docs/api/#company

That is, just change your url to something like the following:

`https://cloud.iexapis.com/stable/stock/market/batch?types=quote,company&symbols=aapl,fb&filter=exchange,latestVolume,changePercent,latestPrice,previousClose&token=MY_TOKEN`
