### ISSUE TITLE
[Issue] Getting WinError 10054 upon trying to connect through the API

### ISSUE THREAD

**Issue by abinder1** [iexg/IEX-API#990]
Using the Python pyEX module, I am trying to interact through the API.  Below is some code I am trying to run, trying to get Python to interact with the API and return message usage data

```
from pyEX import client as pyEXclient

def load_pk(name = None):
	sbpk_file = open(name, 'r')
	key = sbpk_file.read().strip()
	sbpk_file.close()

return key

mode = 'sandbox' # either 'sandbox' or 'beta'
pk = 'None'

if mode == 'sandbox':
	pk = load_pk('api_keys/sandbox_secret.iexkey')
if mode == 'beta':
	pk = load_pk('api_keys/beta_secret.iexkey')

myClient = pyEXclient.Client(api_token=pk, version=mode)
y = myClient.usage()
```

I have been able to contact the server and get usage data prior to getting this message, but now I get the following.  It comes through stderr and reports WinError 10054.  Any thoughts on how to resolve this?

[reset.log](https://github.com/iexg/IEX-API/files/3229233/reset.log)

**Comment by evancarter-iex** [comment]
pyEX is an unofficial library so I cant comment on how it works beyond what you are seeing. If you are able to hit the api via a browser then It might be better to bring it up with them.
