### ISSUE TITLE
[Data] TSX quotes did not update on May 27

### ISSUE THREAD

**Issue by cgailey** [iexg/IEX-API#991]
**Clearly describe the data problem**
Requesting quote data for TSX (-CT) on May 28 returns values from May 24.  Note that latestSource says previous close, however TSX was open Mon May 27.  Examples shown for TSX:TD, TSX:BMO

"TD-CT":{"quote":{
"symbol":"TD-CT",
"companyName":"The Toronto-Dominion Bank",
"calculationPrice":"previousclose",
"open":null,
"openTime":null,
"close":null,
"closeTime":null,
"high":null,
"low":null,
"latestPrice":76.1,
"latestSource":"Previous close",
"latestTime":"May 24, 2019",
"latestUpdate":1558670400000,
"latestVolume":0,
"iexRealtimePrice":null,
"iexRealtimeSize":null,
"iexLastUpdated":null,
"delayedPrice":null,
"delayedPriceTime":null,
"extendedPrice":null,
"extendedChange":null,
"extendedChangePercent":null,
"extendedPriceTime":null,
"previousClose":76.1,
"change":0,
"changePercent":0,
"iexMarketPercent":null,
"iexVolume":null,
"avgTotalVolume":2794842,
"iexBidPrice":null,
"iexBidSize":null,
"iexAskPrice":null,
"iexAskSize":null,
"marketCap":0,
"peRatio":null,
"week52High":80.05,
"week52Low":65.56,
"ytdChange":0.115018
}},

"BMO-CT":{"quote":{
"symbol":"BMO-CT",
"companyName":"Bank of Montreal",
"calculationPrice":"previousclose",
"open":null,
"openTime":null,
"close":null,
"closeTime":null,
"high":null,
"low":null,
"latestPrice":103.6,
"latestSource":"Previous close",
"latestTime":"May 24, 2019",
"latestUpdate":1558670400000,
"latestVolume":0,
"iexRealtimePrice":null,
"iexRealtimeSize":null,
"iexLastUpdated":null,
"delayedPrice":null,
"delayedPriceTime":null,
"extendedPrice":null,
"extendedChange":null,
"extendedChangePercent":null,
"extendedPriceTime":null,
"previousClose":103.6,
"change":0,
"changePercent":0,
"iexMarketPercent":null,
"iexVolume":null,
"avgTotalVolume":1517927,
"iexBidPrice":null,
"iexBidSize":null,
"iexAskPrice":null
,"iexAskSize":null,
"marketCap":0,
"peRatio":null,
"week52High":109,
"week52Low":86.25,
"ytdChange":0.156766
}}

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=TD-CT,BMO-CT&types=quote&token=MY_TOKEN

**What time did the problem occur (including timezone)?**
18:00 EDT May 28 2019

**What is the expected behavior?**
Return current quote data.

**What are the steps to reproduce**
Use above url in browser.

**Your environment (e.g. browser, OS, API version, language):**
Browser OS X Safari 12.1.1

**Additional context**

**Comment by evancarter-iex** [comment]
@cgailey hmmm Ill look into this. I did note that its now up to date. Probably something to do with the Holiday and how our data provider generates it. Thanks.

**Comment by cgailey** [comment]
What time does the update happen for TSX?  When I submitted the bug it was 6pm EDT on May 28 and data for the 28th still wasn't there.  Thanks.

**Comment by evancarter-iex** [comment]
@cgailey 4am ET but we are working to move that up

**Comment by evancarter-iex** [comment]
@cgailey we have worked with our data provider to make sure this doesnt happen in the future. If it does lets file a new bug/reopen this one. Thanks

**Comment by cgailey** [comment]
> @cgailey 4am ET but we are working to move that up

@evancarter-iex thanks.  Obviously 4AM is less than ideal for end of day prices.  I'll open a new issue for moving up the time the update happens so we can be aware when it changes.
