### ISSUE TITLE
[Data] Calling 1-minute delayed intraday prices minute by minute

### ISSUE THREAD

**Issue by pathvine** [iexg/IEX-API#992]
**Clearly describe the data problem**
According to the IEX Cloud documentation:
> Data Weighting
> 1 per symbol per time interval up to a max use of 50 messages
> Example: If you query for AAPL 1d at 11:00am, it will return 90 minutes of data for a total of 50. 

The data weighing of the 1d (intraday) is 50 messages max. However, in v1.0 API, I used to call the same endpoint 390 times per day to get the OHLCV data with 1-minute delay.

With the IEX cloud, this isn't feasible anymore because this method will result in 390 * 50 = 19,500 messages for one symbol. I know this calculation simplifies the actual situation a bit because I am assuming every call is hitting the 50-messages cap.

The question now is, how can I retrieve the intraday OHLCV with 1-minute delay efficiently with the IEX cloud API?

**Data URL (The URL you used to access the data without your token):**
GET /stock/{symbol}/intraday-prices (or)
GET /stock/{symbol}/1d

**What time did the problem occur (including timezone)?**
Any time

**What is the expected behavior?**
1-minute delayed OHLCV data should cost 1 message or an API should let us call for a certain minute.

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
Node.js on Google Chrome

**Additional context**

**Comment by evancarter-iex** [comment]
@pathvine Hi there, the best way to get the full minute by minute breakdown would be to do a single call at the end of the day to the chart end point. For example https://cloud.iexapis.com/stable/stock/aapl/chart/1d, if called after 4pm ET would give you the data you need
