### ISSUE TITLE
[Data] one minute historical data since 2010 or earlier

### ISSUE THREAD

**Issue by eusorov** [iexg/IEX-API#994]
**Clearly describe the data problem**
Right now it is possible to get 1 min data only for last 3 month.
I need 1 min data from earlier than 2010, how is it possible to get this?

**Data URL (The URL you used to access the data without your token):**
https://api.iextrading.com/1.0/stock/aapl/chart/date/20190301

**What time did the problem occur (including timezone)?**
2019-05-29 13.55 UTC

**What is the expected behavior?**
If I put another day lets say 20180101, 
https://api.iextrading.com/1.0/stock/aapl/chart/date/20180101 

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
Chromo

**Additional context**

**Comment by joshuablackburn-iex** [comment]
The IEX API has completed the 1st phase sunset. (https://iextrading.com/developer/)
Please use IEX Cloud (https://iexcloud.io) to continue receiving data.
