### ISSUE TITLE
[Data] OHLC => close is EOD previous day during open market hours

### ISSUE THREAD

**Issue by myichimoku** [iexg/IEX-API#995]
**Clearly describe the data problem**
On a https://cloud.iexapis.com/stable/stock/SYMBOL/ohlc?token=xyz call during the day, the close is the EOD from the day before.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/DELL/ohlc?token=

**What time did the problem occur (including timezone)?**
17:00 CET

**What is the expected behavior?**
Close would show current (delayed) price or be empty

**What are the steps to reproduce**
https://cloud.iexapis.com/stable/stock/DELL/ohlc?token= during open market hours

**Your environment (e.g. browser, OS, API version, language):**
Linux, brave

**Additional context**
N/A

**Comment by evancarter-iex** [comment]
@myichimoku Yeah this was done to match how Yahoo Finance handles it during the day (after requests from users). Thanks for reaching out!
