### ISSUE TITLE
Please tell us when prior trading day data is available!

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#996]
It's 5:25 AM New York timezone and prior trading day data is not yet available on chart endpoint. 

https://cloud.iexapis.com/v1/stock/market/batch?symbols=EPP&types=chart&chartLast=2&token=mytoken

Documentation state that data is available after 4:00 AM ET but it doesn't ...

**Comment by joshuablackburn-iex** [comment]
Our data partner is working on splitting up our overnight process to provide closing prices much earlier. Hopefully as early as 9pm. The full split+dividend adjusted data, which takes the longest time, will continue to be available in the early morning. We are even considering populating the end of day prices in phases such as close price immediately, then close volume after 8pm, then adjusted prices later.

I understand your frustration, but know that we are actively working a solution we plan to have in place soon.

**Comment by gabrieldodan** [comment]
Sounds good @joshuablackburn-iex . Thanks for clarifications!

How would i know when the solution is implemented? Will you updated this issue or update the documentation?

Thanks!

**Comment by joshuablackburn-iex** [comment]
For something this big, we would send out a product update.
