### ISSUE TITLE
API doc is erroneous, again #2 [Issue]

### ISSUE THREAD

**Issue by aspenforest** [iexg/IEX-API#997]
**Clearly describe the problem**
parameter "last" is described both as a path param and as a query param

**What time did the problem occur? (with timezone)**
continuous

**What is the expected behavior?**
not be both at the same time

**Your environment (e.g. browser, OS, API version, language):**
brains, eyes, english

**API URL (if applicable)**
https://iexcloud.io/docs/api/#earnings

**What are the steps to reproduce the bug?**
RTFM

**Additional context**

**Comment by aspenforest** [comment]
**OH MY GOD...** 
Don't tell me it's a feature...

Examples
/stock/aapl/earnings
/stock/aapl/earnings**/2**
/stock/aapl/earnings**?last=2**
/stock/aapl/earnings/1/actualEPS

**Comment by joshuablackburn-iex** [comment]
@aspenforest  We provide this GitHub community as a transparent way to communicate with our users, and to create a public reference for fixes and enhancements. While we appreciate every issue raised in this forum, we do expect a level of professionalism. Some of the issues you've raised need to be addressed in the docs. Others are there for a reason. We are not here to create the exact perfect implementation of REST, for which developers disagree regularly, but an API that is easy to use.

If you have such a major issue with our system or docs, you are welcome to email us directly. This is a commercial product and we will take appropriate steps to maintain professionalism in this forum.
